
CREATE  OR REPLACE VIEW V_ORDENDECOMPRA_RUBRO
AS WITH UNICOS AS
(
SELECT DISTINCT
  ORDENDECOMPRAPPTO.COMPANIA, 
  ORDENDECOMPRAPPTO.CLASEORDEN,
  ORDENDECOMPRAPPTO.NUMERO,  
  ORDENDECOMPRAPPTO.RUBRO,
  PLAN_PRESUPUESTAL.NOMBRE,
  ORDENDECOMPRAPPTO.RUBRO || ' ' || DECODE(ORDENDECOMPRAPPTO.AUXILIAR,PCK_DATOS.FC_CONS_AUXILIAR,'',ORDENDECOMPRAPPTO.AUXILIAR) || ' ' ||   PLAN_PRESUPUESTAL.NOMBRE RUBRONOM,
  FUENTE_RECURSOS.NOMBRE NOMBREFTERECURSO,
  PLAN_PPTAL_CONFIG.CODIGO_CCEPT RUBROCCEPT,
  PLAN_PPTAL_CONFIG.CODIGO_CCEPT || ' ' ||   PP_CCEPT.NOMBRE RUBRONOM_CCEPT
FROM ORDENDECOMPRAPPTO 
    INNER JOIN PLAN_PRESUPUESTAL   
        ON ORDENDECOMPRAPPTO.COMPANIA = PLAN_PRESUPUESTAL.COMPANIA
        AND ORDENDECOMPRAPPTO.ANOPPTO  = PLAN_PRESUPUESTAL.ANO
        AND ORDENDECOMPRAPPTO.RUBRO    = PLAN_PRESUPUESTAL.CODIGO
    LEFT JOIN FUENTE_RECURSOS
        ON ORDENDECOMPRAPPTO.COMPANIA = FUENTE_RECURSOS.COMPANIA
        AND ORDENDECOMPRAPPTO.ANOPPTO  = FUENTE_RECURSOS.ANO
        AND ORDENDECOMPRAPPTO.FUENTE_RECURSO = FUENTE_RECURSOS.CODIGO
    LEFT JOIN PLAN_PPTAL_CONFIG 
         ON ORDENDECOMPRAPPTO.COMPANIA = PLAN_PPTAL_CONFIG.COMPANIA
            AND ORDENDECOMPRAPPTO.ANOPPTO = PLAN_PPTAL_CONFIG.ANO
            AND ORDENDECOMPRAPPTO.RUBRO = PLAN_PPTAL_CONFIG.CODIGO
            AND CASE WHEN PLAN_PRESUPUESTAL.MAN_CEN_CTO IN (0) THEN '99999999999999999999' ELSE ORDENDECOMPRAPPTO.CENTRO_COSTO END = PLAN_PPTAL_CONFIG.CENTRO_COSTO
            AND CASE WHEN PLAN_PRESUPUESTAL.MAN_AUX_TER IN (0) THEN '999999999999999999' ELSE ORDENDECOMPRAPPTO.TERCERO END = PLAN_PPTAL_CONFIG.TERCERO
            AND CASE WHEN PLAN_PRESUPUESTAL.MAN_AUX_TER IN (0) THEN '999' ELSE ORDENDECOMPRAPPTO.SUCURSAL END = PLAN_PPTAL_CONFIG.SUCURSAL
            AND CASE WHEN PLAN_PRESUPUESTAL.MAN_AUX_GEN IN (0) THEN '99999999999999999999' ELSE ORDENDECOMPRAPPTO.AUXILIAR END = PLAN_PPTAL_CONFIG.AUXILIAR
            AND CASE WHEN PLAN_PRESUPUESTAL.MAN_AUX_REF IN (0) THEN '99999999999999999999' ELSE ORDENDECOMPRAPPTO.REFERENCIA END = PLAN_PPTAL_CONFIG.REFERENCIA
            AND CASE WHEN PLAN_PRESUPUESTAL.MAN_AUX_FUE IN (0) THEN '99999999999999999999' ELSE ORDENDECOMPRAPPTO.FUENTE_RECURSO END = PLAN_PPTAL_CONFIG.FUENTE_RECURSO
    LEFT JOIN PLAN_PRESUPUESTAL   PP_CCEPT
        ON PLAN_PPTAL_CONFIG.COMPANIA = PP_CCEPT.COMPANIA
        AND PLAN_PPTAL_CONFIG.ANO  = PP_CCEPT.ANO
        AND PLAN_PPTAL_CONFIG.CODIGO_CCEPT    = PP_CCEPT.CODIGO
            
)
SELECT 
  COMPANIA, 
  CLASEORDEN,
  NUMERO,
  LISTAGG(RUBRO , ',' on overflow truncate) WITHIN GROUP(ORDER BY COMPANIA ,CLASEORDEN , NUMERO ) RUBRO,
  LISTAGG(NOMBRE, ',' on overflow truncate) WITHIN GROUP(ORDER BY COMPANIA,CLASEORDEN,NUMERO,RUBRO) NOMBRE,																				   
  LISTAGG(RUBRONOM , ',' on overflow truncate) WITHIN GROUP(ORDER BY COMPANIA ,CLASEORDEN , NUMERO ) RUBRONOMBRE,
  LISTAGG(NOMBREFTERECURSO , ',' on overflow truncate) WITHIN GROUP(ORDER BY COMPANIA ,CLASEORDEN , NUMERO ) FUENTERECURSO,
  LISTAGG(RUBROCCEPT , ',' on overflow truncate) WITHIN GROUP(ORDER BY COMPANIA ,CLASEORDEN , NUMERO ) RUBROCCEPT  ,
  LISTAGG(RUBRONOM_CCEPT , ',' on overflow truncate) WITHIN GROUP(ORDER BY COMPANIA ,CLASEORDEN , NUMERO ) RUBRONOM_CCEPT  
FROM UNICOS 
GROUP BY COMPANIA, 
  CLASEORDEN,
  NUMERO;
  



