SELECT        
	ORDENDECOMPRA.CLASEORDEN, 
	ORDENDECOMPRA.NUMERO, 
	TERCERO.NOMBRE, 
	ORDENDECOMPRA.OBJETOCONTRATO, 
	ORDENDECOMPRA.VALORTOTAL, 
	V_ORDENDECOMPRA_RES.FECHACDP FECHA,
	V_ORDENDECOMPRA_RES.COMPROBANTES  RESERVA,  
	TERCERO.NIT
FROM ORDENDECOMPRA 
  INNER JOIN TIPOORDENDECOMPRA 
          ON  ORDENDECOMPRA.COMPANIA    = TIPOORDENDECOMPRA.COMPANIA
         AND ORDENDECOMPRA.CLASEORDEN   = TIPOORDENDECOMPRA.CODIGO 
  INNER JOIN TERCERO 
          ON ORDENDECOMPRA.COMPANIA = TERCERO.COMPANIA 
         AND ORDENDECOMPRA.TERCERO  = TERCERO.NIT 
         AND  ORDENDECOMPRA.SUCURSAL = TERCERO.SUCURSAL 
   LEFT JOIN V_ORDENDECOMPRA_RES
		  ON ORDENDECOMPRA.COMPANIA = V_ORDENDECOMPRA_RES.COMPANIA
		 AND ORDENDECOMPRA.CLASEORDEN = V_ORDENDECOMPRA_RES.CLASEORDEN
		 AND ORDENDECOMPRA.NUMERO = V_ORDENDECOMPRA_RES.NUMERO
WHERE ORDENDECOMPRA.COMPANIA = s$compania$s  
  AND ORDENDECOMPRA.CLASEORDEN BETWEEN s$tipoContratoInicial$s AND s$tipoContratoFinal$s 
  AND ORDENDECOMPRA.FECHA      BETWEEN s$fechaInicial$s        AND s$fechaFinal$s
ORDER BY ORDENDECOMPRA.NUMERO, 
         TERCERO.DIRECCION
