SELECT ORDENDECOMPRA.CLASEORDEN,
  ORDENDECOMPRA.NUMERO,
  TERCERO.NOMBRE,
  TERCERO.CARGO,
  ORDENDECOMPRA.OBJETOCONTRATO,
  ORDENDECOMPRA.NOMBRECONTRATISTA,
  ORDENDECOMPRA.DURACION,
  TO_CHAR(ORDENDECOMPRA.FECHAINICIO, 'DD/MM/YYYY') FECHAINICIO,
  TO_CHAR(ORDENDECOMPRA.FECHAFINALIZACION, 'DD/MM/YYYY') FECHAFINALIZACION,
  ORDENDECOMPRA.VALORTOTAL,
  ORDENDECOMPRA.VALORPAGOS,
  SUPERVISORES.CEDULA,
  ORDENDECOMPRA.ESTADO
FROM SUPERVISORES
INNER JOIN TERCERO
ON TERCERO.COMPANIA  = SUPERVISORES.COMPANIA
AND TERCERO.NIT      = SUPERVISORES.CEDULA
AND TERCERO.SUCURSAL = SUPERVISORES.SUCURSAL
LEFT JOIN ORDENDECOMPRA
ON SUPERVISORES.NUMEROCONTRATO = ORDENDECOMPRA.NUMERO
AND SUPERVISORES.CLASEORDEN    = ORDENDECOMPRA.CLASEORDEN
AND SUPERVISORES.COMPANIA      = ORDENDECOMPRA.COMPANIA
WHERE ORDENDECOMPRA.COMPANIA   = 's$compania$s'
AND -1                        IN (
  CASE
    WHEN 's$estado$s'                = 'Z'
    OR ORDENDECOMPRA.ESTADO = 's$estado$s'
    THEN -1
    ELSE 0
  END)
AND TERCERO.NOMBRE BETWEEN 's$terceroInicial$s' AND 's$terceroFinal$s'
AND ORDENDECOMPRA.FECHAINICIO BETWEEN s$fechaInicial$s AND s$fechaFinal$s
ORDER BY TERCERO.NOMBRE
