SELECT ORDENDECOMPRA.CLASEORDEN, 
       ORDENDECOMPRA.NUMERO, 
       TO_CHAR(ORDENDECOMPRA.FECHA,'DD/MM/YYYY') FECHA, 
       TERCERO.NOMBRE BENEFICIARIO, 
       ORDENDECOMPRA.OBJETOCONTRATO  OBJETO, 
       ORDENDECOMPRA.DURACION DURA, 
       ORDENDECOMPRA.VALORTOTAL VALORCONTRATO, 
       ORDENDECOMPRAPPTO.FUENTE_RECURSO ORIGENRECURSOS, 
       ORDENDECOMPRA.COMPANIA, 
       ORDENDECOMPRAPPTO.RUBRO
FROM ORDENDECOMPRA 
       LEFT JOIN TERCERO 
              ON ORDENDECOMPRA.COMPANIA = TERCERO.COMPANIA 
              AND ORDENDECOMPRA.SUCURSAL = TERCERO.SUCURSAL 
              AND ORDENDECOMPRA.TERCERO = TERCERO.NIT
       LEFT JOIN TIPOORDENDECOMPRA 
              ON ORDENDECOMPRA.COMPANIA = TIPOORDENDECOMPRA.COMPANIA 
              AND ORDENDECOMPRA.CLASEORDEN = TIPOORDENDECOMPRA.CODIGO
       LEFT JOIN ORDENDECOMPRAPPTO
              ON ORDENDECOMPRA.COMPANIA = ORDENDECOMPRAPPTO.COMPANIA
              AND ORDENDECOMPRA.CLASEORDEN = ORDENDECOMPRAPPTO.CLASEORDEN
              AND ORDENDECOMPRA.NUMERO = ORDENDECOMPRAPPTO.NUMERO
WHERE ORDENDECOMPRA.COMPANIA = s$compania$s 
       AND TO_CHAR(ORDENDECOMPRA.FECHA,'MM')   = s$mes$s
       AND TO_CHAR(ORDENDECOMPRA.FECHA,'YYYY') = s$ano$s
       AND NVL(TIPOORDENDECOMPRA.CLASE,'')<>'M'
       AND (ORDENDECOMPRAPPTO.TIPOPPTO IN ('DIS') OR ORDENDECOMPRAPPTO.TIPOPPTO IS NULL)
ORDER BY ORDENDECOMPRA.COMPANIA, 
         ORDENDECOMPRA.NUMERO
