SELECT  ORDENDECOMPRA.COMPANIA, 
        ORDENDECOMPRA.CLASEORDEN, 
        ORDENDECOMPRA.NUMERO, 
        ORDENDECOMPRA.VALORTOTAL, 
        TO_CHAR(ORDENDECOMPRA.FECHA,'DD/MM/YYYY') FECHA, 
        TERCERO.NOMBRE, 
        ORDENDECOMPRA.DESCRIPCION
   FROM ORDENDECOMPRA 
       LEFT JOIN TERCERO 
              ON ORDENDECOMPRA.COMPANIA = TERCERO.COMPANIA 
             AND ORDENDECOMPRA.TERCERO  = TERCERO.NIT 
             AND ORDENDECOMPRA.SUCURSAL = TERCERO.SUCURSAL 
       LEFT JOIN TIPOORDENDECOMPRA 
              ON ORDENDECOMPRA.CLASEORDEN = TIPOORDENDECOMPRA.CODIGO 
             AND ORDENDECOMPRA.COMPANIA   = TIPOORDENDECOMPRA.COMPANIA
 WHERE ORDENDECOMPRA.COMPANIA = s$compania$s
   AND ORDENDECOMPRA.FECHA    BETWEEN s$fechaInicial$s AND s$fechaFinal$s 
 ORDER BY ORDENDECOMPRA.COMPANIA, 
         ORDENDECOMPRA.CLASEORDEN,
         ORDENDECOMPRA.FECHA
