SELECT  
          TERCERO.NOMBRE NOMBRE_CONTRATISTA,  
          TERCERO.NIT NIT_CONTRATISTA,  
          ORDENDECOMPRA.NUMERO NUMERO_CONTRATO,  
          ORDENDECOMPRA.FECHA FECHA_CONTRATO,  
          ORDENDECOMPRA.OBJETOCONTRATO,  
          ORDENDECOMPRA.VALORTOTAL,  
          ORDENDECOMPRA.DURACION PLAZO,  
          ORDENDECOMPRA.FECHAFIRMA FECHA_FIRMA,  
          ORDENDECOMPRA.FECHAFINALIZACION,  
          NOVEDADCONTRATO.TIPOT NOVEDAD,  
          CLASETRANSACCIONC.NOMBRE NOMBRE_NOVEDAD,  
          NOVEDADCONTRATO.VALORTOTAL VALOR_NOVEDAD,  
          TRUNC(MONTHS_BETWEEN(NOVEDADCONTRATO.FECHAFINAL, NOVEDADCONTRATO.FECHAINICIAL)) TIEMPOMESES_NOVEDAD,  
          (NOVEDADCONTRATO.FECHAFINAL - NOVEDADCONTRATO.FECHAINICIAL) TIEMPODIAS_NOVEDAD,  
          EXTRACT(DAY FROM SYSDATE) DIA_EXPEDICION,  
          PCK_SYSMAN_UTL.FC_NOMBRE_MES(EXTRACT(MONTH FROM SYSDATE)) MES_EXPEDICION,  
          EXTRACT(YEAR FROM SYSDATE) ANO_EXPEDICION  
        FROM  ORDENDECOMPRA  
              LEFT JOIN TERCERO  
              ON (ORDENDECOMPRA.TERCERO = TERCERO.NIT)  
              AND (ORDENDECOMPRA.SUCURSAL = TERCERO.SUCURSAL)  
              AND (ORDENDECOMPRA.COMPANIA = TERCERO.COMPANIA)  
              LEFT JOIN NOVEDADCONTRATO  
              ON (ORDENDECOMPRA.COMPANIA = NOVEDADCONTRATO.COMPANIA)  
              AND (ORDENDECOMPRA.CLASEORDEN = NOVEDADCONTRATO.CLASEORDEN)  
              AND (ORDENDECOMPRA.NUMERO = NOVEDADCONTRATO.ORDENDECOMPRA)  
              LEFT JOIN CLASETRANSACCIONC  
              ON (NOVEDADCONTRATO.TIPOT = CLASETRANSACCIONC.TIPOT)  
              AND (NOVEDADCONTRATO.CLASET = CLASETRANSACCIONC.CLASET)  
        WHERE ORDENDECOMPRA.COMPANIA = s$compania$s  
        AND ORDENDECOMPRA.CLASEORDEN = 's$tipocontrato$s'  
        AND ORDENDECOMPRA.NUMERO = 's$numerocontrato$s'
