MERGE INTO CONSULTAS FIN USING (SELECT '002329CertificadoContrato' INFORME ,TO_CLOB(q'[SELECT ORDENDECOMPRA.COMPANIA AS COMPANIA, 
  ORDENDECOMPRA.NUMERO as NUMERO, 
  ORDENDECOMPRA.CLASEORDEN AS CLASEORDEN,
  ORDENDECOMPRA.OBJETOCONTRATO AS OBJETO,
  ORDENDECOMPRA.OBLIGACIONC AS ACTIVIDAD,
  ORDENDECOMPRA.PLAZODEENTREGA AS PLAZO,
  ORDENDECOMPRA.VALORTOTAL AS VALORCONTRATO, 
  TO_CHAR(ORDENDECOMPRA.FECHA,'DD/MM/YYYY') FECHAINICIO,
  TO_CHAR(ORDENDECOMPRA.FECHAFINALIZACION,'DD/MM/YYYY') FECHAFIN ,
  TERCERO.NIT AS CEDULA,
  TERCERO.NOMBRE AS TERCERO,
  NVL(TERCERO.EXPEDIDACEDULA,'-') AS EXPCEDULA
FROM ORDENDECOMPRA 
       INNER JOIN TIPOORDENDECOMPRA 
              ON  ORDENDECOMPRA.COMPANIA  = TIPOORDENDECOMPRA.COMPANIA 
             AND ORDENDECOMPRA.CLASEORDEN = TIPOORDENDECOMPRA.CODIGO 
       INNER JOIN TERCERO 
              ON  ORDENDECOMPRA.COMPANIA  = TERCERO.COMPANIA 
             AND ORDENDECOMPRA.TERCERO    = TERCERO.NIT 
             AND ORDENDECOMPRA.SUCURSAL   = TERCERO.SUCURSAL 
       LEFT JOIN ORDENDECOMPRAPPTO
              ON ORDENDECOMPRA.COMPANIA    = ORDENDECOMPRAPPTO.COMPANIA
             AND ORDENDECOMPRA.CLASEORDEN  = ORDENDECOMPRAPPTO.CLASEORDEN
             AND ORDENDECOMPRA.NUMERO      = ORDENDECOMPRAPPTO.NUMERO
                 
WHERE ORDENDECOMPRA.COMPANIA   = s$compania$s
  AND ORDENDECOMPRA.CLASEORDEN BETWEEN s$tipoContratoInicial$s AND s$tipoContratoFinal$s
  AND ORDENDECOMPRA.TERCERO    BETWEEN s$terceroInicial$s  AND s$terceroFinal$s
  AND ORDENDECOMPRA.FECHA      BETWEEN s$fechaInicial$s AND s$fechaFinal$s
 ORDER BY TERCERO.NIT, ORDENDECOMPRA.NUMERO]') CONSULTA, 9 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);
  
COMMIT; 