MERGE INTO CONSULTAS FIN USING (SELECT '002936InversionPorCuencasDetallado' INFORME ,TO_CLOB(q'[SELECT 
    ORDENDECOMPRA.COMPANIA,
    ES_LOCALIZA.BARRIO CODIGO_CUENCA,
    UPPER(BARRIOS.NOMBRE) AS NOMBRE_CUENCA,
    ORDENDECOMPRA.CLASEORDEN || ' - ' || TIPOORDENDECOMPRA.NOMBRE NOMBRE_CONTRATO,
    ORDENDECOMPRA.NUMERO,
    ORDENDECOMPRA.OBJETOCONTRATO,
    CONTRATOS_INV.FUENTE_RECURSO,
    ORDENDECOMPRA.VALORTOTAL,
    ROUND(ORDENDECOMPRA.VALORTOTAL /
        COUNT(*) OVER (PARTITION BY ORDENDECOMPRA.COMPANIA,
                         ORDENDECOMPRA.CLASEORDEN,
                         ORDENDECOMPRA.NUMERO),2) AS VALOR_PRORRATEADO
FROM ORDENDECOMPRA
INNER JOIN (
    SELECT 
        COMPROBANTE_PPTAL.COMPANIA,
        COMPROBANTE_PPTAL.TIPOCONTRATO,
        COMPROBANTE_PPTAL.NUMEROCONTRATO,
        LISTAGG(DISTINCT DETALLE_COMPROBANTE_PPTAL.FUENTE_RECURSO 
        || ' - ' || FUENTE_RECURSOS.NOMBRE, ', ')
            WITHIN GROUP (ORDER BY DETALLE_COMPROBANTE_PPTAL.FUENTE_RECURSO) 
            AS FUENTE_RECURSO
    FROM DETALLE_COMPROBANTE_PPTAL
    INNER JOIN COMPROBANTE_PPTAL
        ON COMPROBANTE_PPTAL.COMPANIA = DETALLE_COMPROBANTE_PPTAL.COMPANIA
       AND COMPROBANTE_PPTAL.ANO = DETALLE_COMPROBANTE_PPTAL.ANO
       AND COMPROBANTE_PPTAL.TIPO = DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE
       AND COMPROBANTE_PPTAL.NUMERO = DETALLE_COMPROBANTE_PPTAL.COMPROBANTE
    INNER JOIN PLAN_PRESUPUESTAL
        ON PLAN_PRESUPUESTAL.COMPANIA = DETALLE_COMPROBANTE_PPTAL.COMPANIA
       AND PLAN_PRESUPUESTAL.ANO = DETALLE_COMPROBANTE_PPTAL.ANO
       AND PLAN_PRESUPUESTAL.CODIGO = DETALLE_COMPROBANTE_PPTAL.CUENTA
    INNER JOIN TIPO_COMPROBPP
        ON TIPO_COMPROBPP.COMPANIA = COMPROBANTE_PPTAL.COMPANIA
       AND TIPO_COMPROBPP.CODIGO = COMPROBANTE_PPTAL.TIPO
    INNER JOIN FUENTE_RECURSOS
        ON FUENTE_RECURSOS.COMPANIA = DETALLE_COMPROBANTE_PPTAL.COMPANIA
        AND FUENTE_RECURSOS.ANO = DETALLE_COMPROBANTE_PPTAL.ANO
        AND FUENTE_RECURSOS.CODIGO = DETALLE_COMPROBANTE_PPTAL.FUENTE_RECURSO
    WHERE PLAN_PRESUPUESTAL.DESTINO = 'I'
      AND PLAN_PRESUPUESTAL.NATURALEZA = 'D'
      AND COMPROBANTE_PPTAL.TIPOCONTRATO IS NOT NULL
      AND COMPROBANTE_PPTAL.NUMEROCONTRATO IS NOT NULL
      AND TIPO_COMPROBPP.CLASE = 'RES'
    GROUP BY 
        COMPROBANTE_PPTAL.COMPANIA,
        COMPROBANTE_PPTAL.TIPOCONTRATO,
        COMPROBANTE_PPTAL.NUMEROCONTRATO
) CONTRATOS_INV
    ON CONTRATOS_INV.COMPANIA = ORDENDECOMPRA.COMPANIA
   AND CONTRATOS_INV.TIPOCONTRATO = ORDENDECOMPRA.CLASEORDEN
   AND CONTRATOS_INV.NUMEROCONTRATO = ORDENDECOMPRA.NUMERO
INNER JOIN TIPOORDENDECOMPRA
    ON TIPOORDENDECOMPRA.COMPANIA = ORDENDECOMPRA.COMPANIA
    AND TIPOORDENDECOMPRA.CODIGO = ORDENDECOMPRA.CLASEORDEN
INNER JOIN ES_LOCALIZA
    ON ES_LOCALIZA.COMPANIA = ORDENDECOMPRA.COMPANIA
    AND ES_LOCALIZA.COD_ESTUDIO = ORDENDECOMPRA.DESC_ESTPREVIOS
INNER JOIN BARRIOS
    ON BARRIOS.PAIS = ES_LOCALIZA.PAIS
    AND BARRIOS.DEPARTAMENTO = ES_LOCALIZA.DEPARTAMENTO
    AND BARRIOS.CIUDAD = ES_LOCALIZA.CIUDAD
    AND BARRIOS.CODIGO = ES_LOCALIZA.BARRIO
INNER JOIN TIPOSDIVISION
]') || TO_CLOB(q'[    ON TIPOSDIVISION.CODIGO = BARRIOS.TIPODIVISION
WHERE ORDENDECOMPRA.COMPANIA = s$compania$s
AND ORDENDECOMPRA.FECHAFIRMA BETWEEN 's$fechaInicial$s' AND 's$fechaFinal$s'
AND TIPOSDIVISION.ES_CUENCA = -1
   ORDER BY CODIGO_CUENCA]') CONSULTA, 9 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);