WHERE EXTRACT( YEAR FROM ORDENDECOMPRA.FECHADILIGENCIAMIENTO)= s$vigencia$s
AND EXTRACT( MONTH FROM ORDENDECOMPRA.FECHADILIGENCIAMIENTO) BETWEEN s$mesInicial$s  AND s$mesFinal$s
AND ORDENDECOMPRA.COMPANIA= s$compania$s 
AND TIPOORDENDECOMPRA.CLASE NOT IN ('M')
