SELECT  OC.NUMERO "NÚMERO CONTRATO", 
        OC.CLASEORDEN "CLASE ORDEN", 
        T.NOMBRE "NOMBRE", 
        ORDENDECOMPRAPPTO.NUMEROPPTO DISPONIBILIDAD, 
        SUBSTR(OBJETOCONTRATO,1,255)  || SUBSTR(OBJETOCONTRATO,256,1000) "OBJETO CONTRATO", 
        V_ORDENDECOMPRA_RUBRO.RUBRO RUBRO, 
        OC.VALORFINAL  "VALOR TOTAL INICIAL", 
        OC.VALORTOTAL-OC.VALORFINAL ADICIONES,
        NVL(VALORPAGOS,0) PAGOS, 
        OC.FECHA "FECHA INICIALIZACION", 
        OC.FECHAFINALIZACION "FECHA FINALIZACION", 
        OC.PLAZODEENTREGA  "PLAZO DE ENTREGA", 
        (CASE WHEN OC.ESTADO = 'V' THEN 'Vigente' ELSE 
          (CASE WHEN OC.ESTADO = 'A' THEN 'Anulado' ELSE 
            (CASE WHEN OC.ESTADO = 'L' THEN 'Liquidado' ELSE 
              (CASE WHEN OC.ESTADO = 'T' THEN 'Terminado' ELSE 
                (CASE WHEN OC.ESTADO = 'S' THEN 'Suspendido' ELSE 
                  (CASE WHEN OC.ESTADO = 'P' THEN 'En Proceso de Sanción o Proceso Judicial' ELSE 'Todos'
                  END)
                END)
              END)
            END)
          END)
        END) ESTADO, 
        NVL(OC.VALORTOTAL,0) "VALOR FINAL",
        PCK_SYSMAN_UTL.FC_ROUND((NVL(VALORPAGOS,0)/ OC.VALORTOTAL)*100,2) || '%' "PORCENTAJE EJECUTADO", 
        OC.VALORTOTAL-VALORPAGOS "VALOR SIN EJECUTAR",
        PCK_SYSMAN_UTL.FC_ROUND(100-((NVL(VALORPAGOS,0)/OC.VALORTOTAL)*100),2) || '%' "PORCENTAJE SIN EJECUTAR", 
        OC.INTERVENTOR, 
        S.NOMBRE SUPERVISOR,
        SUM(NOVEDADCONTRATO.VALOR_LIBERADO) "VALOR LIBERADO",
        OC.FECHALIQUIDACION "FECHA LIQUIDACION", 
        OC.FECHAFIRMA "FECHA FIRMA",
        OC.DURACION "PROGRAMAS EN TIEMPO",
        OC.VALOR_ANTICIPO "ANTICIPO",
        OC.VALORTOTAL+ OC.VALORTOTAL -OC.VALORFINAL  "VALOR TOTAL"
 FROM ORDENDECOMPRA OC 
      LEFT JOIN TERCERO T 
             ON OC.TERCERO  = T.NIT 
            AND OC.SUCURSAL = T.SUCURSAL 
            AND OC.COMPANIA = T.COMPANIA 
      LEFT JOIN TIPOORDENDECOMPRA TOC 
             ON OC.COMPANIA   = TOC.COMPANIA 
            AND OC.CLASEORDEN = TOC.CODIGO 
      LEFT JOIN (SELECT ORDENDECOMPRA.COMPANIA, 
                        ORDENDECOMPRA.TIPOAFECTADO, 
                        ORDENDECOMPRA.NUMEROAFECTADO, 
                        SUM(ORDENDECOMPRA.VALORTOTAL)  SUMADEVALORTOTAL
                  FROM ORDENDECOMPRA
                  GROUP BY ORDENDECOMPRA.COMPANIA, 
                           ORDENDECOMPRA.TIPOAFECTADO, 
                           ORDENDECOMPRA.NUMEROAFECTADO) AC 
             ON OC.COMPANIA   = AC.COMPANIA
            AND OC.CLASEORDEN = AC.TIPOAFECTADO 
            AND OC.NUMERO     = AC.NUMEROAFECTADO 
      LEFT JOIN SUPERVISORES S 
             ON OC.NUMERO     = S.NUMEROCONTRATO 
            AND OC.CLASEORDEN = S.CLASEORDEN 
            AND OC.COMPANIA   = S.COMPANIA 
      LEFT JOIN (SELECT NOVEDADCONTRATO.COMPANIA,
                        NOVEDADCONTRATO.CLASEORDEN, 
                        NOVEDADCONTRATO.ORDENDECOMPRA, 
                        NOVEDADCONTRATO.CLASET, 
                        NOVEDADCONTRATO.TIPOT, 
                        NOVEDADCONTRATO.VALORTOTAL VLRADICION
                 FROM NOVEDADCONTRATO
                 WHERE NOVEDADCONTRATO.TIPOT LIKE 'AD%') NOVEDADESCONTRATO 
             ON OC.NUMERO     = NOVEDADESCONTRATO.ORDENDECOMPRA 
            AND OC.CLASEORDEN = NOVEDADESCONTRATO.CLASEORDEN 
            AND OC.COMPANIA   = NOVEDADESCONTRATO.COMPANIA 
      LEFT JOIN  NOVEDADCONTRATO 
             ON OC.NUMERO     = NOVEDADCONTRATO.ORDENDECOMPRA
            AND OC.CLASEORDEN = NOVEDADCONTRATO.CLASEORDEN 
            AND OC.COMPANIA   = NOVEDADCONTRATO.COMPANIA
      LEFT JOIN ORDENDECOMPRAPPTO 
             ON OC.COMPANIA   = ORDENDECOMPRAPPTO.COMPANIA
            AND OC.CLASEORDEN = ORDENDECOMPRAPPTO.CLASEORDEN
            AND OC.NUMERO     = ORDENDECOMPRAPPTO.NUMERO
      LEFT JOIN V_ORDENDECOMPRA_RUBRO
            ON  OC.COMPANIA   = V_ORDENDECOMPRA_RUBRO.COMPANIA
            AND OC.CLASEORDEN = V_ORDENDECOMPRA_RUBRO.CLASEORDEN
            AND OC.NUMERO     = V_ORDENDECOMPRA_RUBRO.NUMERO 
 WHERE OC.COMPANIA = s$compania$s 
   AND T.NIT BETWEEN 's$terceroIni$s' AND 's$terceroFin$s'  
   AND OC.FECHA BETWEEN s$fechaInicial$s AND s$fechaFinal$s
   AND TOC.NOMBRE BETWEEN 's$tipoContratoInicial$s' AND 's$tipoContratoFinal$s'  
   AND NVL(TOC.CLASE,'')<>'M' 
     s$strWhere$s
 GROUP BY 
            OC.NUMERO, 
            OC.CLASEORDEN, 
            T.NOMBRE, 
            ORDENDECOMPRAPPTO.NUMEROPPTO, 
            SUBSTR(OBJETOCONTRATO,1,255)  || SUBSTR(OBJETOCONTRATO,256,1000), 
            V_ORDENDECOMPRA_RUBRO.RUBRO, 
            OC.VALORFINAL, 
            OC.VALORTOTAL-OC.VALORFINAL,
            NVL(VALORPAGOS,0), 
            OC.FECHA, 
            OC.FECHAFINALIZACION, 
            OC.PLAZODEENTREGA, 
            (CASE WHEN OC.ESTADO = 'V' THEN 'VIGENTE' ELSE 
                  (CASE WHEN OC.ESTADO = 'A' THEN 'ANULADO' ELSE 
                        (CASE WHEN OC.ESTADO = 'L' THEN 'LIQUIDADO' ELSE 
                              (CASE WHEN OC.ESTADO = 'T' THEN 'TERMINADO' ELSE 
                                    (CASE WHEN OC.ESTADO = 'S' THEN 'SUSPENDIDO' ELSE 
                                          (CASE WHEN OC.ESTADO = 'P' THEN 'EN PROCESO DE SANCIÓN O PROCESO JUDICIAL' ELSE 'TODOS'
                                          END)
                                    END)
                              END)
                        END)
                  END)
            END), 
            NVL(OC.VALORTOTAL,0),
            PCK_SYSMAN_UTL.FC_ROUND((NVL(VALORPAGOS,0)/ OC.VALORTOTAL)*100,2) || '%', 
            OC.VALORTOTAL-VALORPAGOS,
            PCK_SYSMAN_UTL.FC_ROUND(100-((NVL(VALORPAGOS,0)/OC.VALORTOTAL)*100),2) || '%', 
            OC.INTERVENTOR, 
            S.NOMBRE,
            OC.FECHALIQUIDACION, 
            OC.FECHAFIRMA,
			OC.DURACION,
            OC.VALOR_ANTICIPO,
            OC.COMPANIA,
            OC.ESTADO, 
            OC.VALORTOTAL+ OC.VALORTOTAL -OC.VALORFINAL
