UrlServiceUtilEnum.getUrl=http\://localhost\:9763/services/recursos/codigo
url.error.message=http://172.16.13.53:9763/services/MSG_ERRORS_MESSAGES_DataService/ERRORS_MESSAGES
url.error.manager=http://172.16.13.53:9763/services/MSG_LOGS_DataService/insertarLog
url.business.manager=http://172.16.13.53:9763/services/BUSINESS_LOGS_DataService/insertarLog
url.error.provider=http://127.0.0.1:9763/services/error/error/msginterfaz
claseValidadorCrudMensaje=com.sysman.exception.processor.message.CrudMessageProcessorOra