 CREATE OR REPLACE  VIEW "V_SOLICITUD_CDP" AS
  SELECT BPNOVEDADPROYECTO.COMPANIA,
       BPNOVEDADPROYECTO.FECHA, 
       BPNOVEDADPROYECTO.CODIGO CONSECUTIVO,
       BPNOVEDADPROYECTO.DEPENDENCIA,
       TO_CHAR(BPNOVEDADPROYECTO.FECHA_VALIDEZ, 'DD/MM/YYYY') FECHA_VALIDEZ,
       BP_D_NOVEDADPROYECTO.ID_META_PRODUCTO,
       BP_D_NOVEDADPROYECTO.ANORUBRO ,
       BP_D_NOVEDADPROYECTO.RUBROPRESUPUESTAL RUBRO,
       BP_D_NOVEDADPROYECTO.AUXILIAR,
       BP_D_NOVEDADPROYECTO.FUENTERECURSOS,
       BPNOVEDADPROYECTO.VIGENCIA,
       BPNOVEDADPROYECTO.DEPENDENCIA_SEC,
       BPNOVEDADPROYECTO.RESPONSABLE_SEC,
       BPNOVEDADPROYECTO.SUCURSAL_SEC,
       BP_D_NOVEDADPROYECTO.VIGENCIA_PLAN_INDICATIVO,
       BP_D_NOVEDADPROYECTO.PROYECTO,
       PROYECTOS.VALOREJECUTADO,
       PROYECTOS.CODIGOBPIM,
       PROYECTOS.VIGENCIAINICIO, 
       PROYECTOS.NOMBREPROYECTO,
       NVL(UNIDADPROYECTOS.NOMBRE,'Sin unidad de medida') NOMBRE_MEDIDA,
       METAPRODUCTO.DESCRIPCION   DESCRIPCION_METAPRODUCTO,
       EJE.DESCRIPCION            DESCRIPCION_EJE,
       SECTOR.DESCRIPCION         DESCRIPCION_SECTOR,
       PROGRAMA.DESCRIPCION       DESCRIPCION_PROGRAMA,
       METARESULTADO.DESCRIPCION  DESCRIPCION_METARESULTADO,       
       METAS.CANTIDAD_EJECUTADA, 
       METAS.CANTIDAD_PROGRAMADA,
       BP_D_NOVEDADPROYECTO.VALORSOLICITADO,
       BP_D_NOVEDADPROYECTO.CANTIDAD,
       (CASE WHEN METAPRODUCTO.TIPO_META_INDICADOR='MM' THEN 'Mantenimiento' ELSE
          CASE WHEN METAPRODUCTO.TIPO_META_INDICADOR='MR' THEN 'Reducción' ELSE 
           CASE WHEN METAPRODUCTO.TIPO_META_INDICADOR='Mi' THEN 'Incremento' ELSE 'Sin Definir' 
           END
          END
        END) AS TIPO_META_I,
        PROGRAMA.DESCRIPCION_TEXTO_BP DESCRIPCION_TEXTO_BP_PRO,
        BPNOVEDADPROYECTO.OBJETO,
        BPNOVEDADPROYECTO.OBSERVACIONES,
        BP_D_NOVEDADPROYECTO.NOVEDAD,
        BPNOVEDADPROYECTO.TIPOT ,
        BPNOVEDADPROYECTO.CLASET,
        BPNOVEDADPROYECTO.MODIFICACION,
        METAPRODUCTO.DESCRIPCION_INDICADOR_MEDIDA,
        BP_D_NOVEDADPROYECTO.CENTRO_COSTO,
        BP_D_NOVEDADPROYECTO.REFERENCIA
FROM  BPNOVEDADPROYECTO INNER JOIN    BP_D_NOVEDADPROYECTO  
   ON BPNOVEDADPROYECTO.COMPANIA    = BP_D_NOVEDADPROYECTO.COMPANIA 
  AND BPNOVEDADPROYECTO.TIPOT       = BP_D_NOVEDADPROYECTO.TIPOT
  AND BPNOVEDADPROYECTO.CLASET      = BP_D_NOVEDADPROYECTO.CLASET
  AND BPNOVEDADPROYECTO.CODIGO      = BP_D_NOVEDADPROYECTO.NOVEDAD 
  AND BPNOVEDADPROYECTO.DEPENDENCIA = BP_D_NOVEDADPROYECTO.DEPENDENCIA
INNER JOIN PROYECTOS 
   ON BP_D_NOVEDADPROYECTO.COMPANIA = PROYECTOS.COMPANIA 
  AND BP_D_NOVEDADPROYECTO.PROYECTO = PROYECTOS.CODIGO
LEFT JOIN BP_PLAN_INDICATIVO METAPRODUCTO
   ON BP_D_NOVEDADPROYECTO.COMPANIA                  = METAPRODUCTO.COMPANIA 
  AND BP_D_NOVEDADPROYECTO.ID_META_PRODUCTO          = METAPRODUCTO.ID
  AND BP_D_NOVEDADPROYECTO.VIGENCIA_PLAN_INDICATIVO  = METAPRODUCTO.VIGENCIA_INICIAL
LEFT JOIN BP_PLAN_INDICATIVO EJE
   ON BP_D_NOVEDADPROYECTO.COMPANIA                       = EJE.COMPANIA 
  AND SUBSTR(BP_D_NOVEDADPROYECTO.ID_META_PRODUCTO,1,'2') = EJE.ID
  AND BP_D_NOVEDADPROYECTO.VIGENCIA_PLAN_INDICATIVO       = EJE.VIGENCIA_INICIAL
LEFT JOIN BP_PLAN_INDICATIVO SECTOR
   ON BP_D_NOVEDADPROYECTO.COMPANIA                       = SECTOR.COMPANIA 
  AND SUBSTR(BP_D_NOVEDADPROYECTO.ID_META_PRODUCTO,1,'4') = SECTOR.ID
  AND BP_D_NOVEDADPROYECTO.VIGENCIA_PLAN_INDICATIVO       = SECTOR.VIGENCIA_INICIAL
LEFT JOIN BP_PLAN_INDICATIVO PROGRAMA
   ON BP_D_NOVEDADPROYECTO.COMPANIA                       = PROGRAMA.COMPANIA 
  AND SUBSTR(BP_D_NOVEDADPROYECTO.ID_META_PRODUCTO,1,'6') = PROGRAMA.ID
  AND BP_D_NOVEDADPROYECTO.VIGENCIA_PLAN_INDICATIVO       = PROGRAMA.VIGENCIA_INICIAL
LEFT JOIN BP_PLAN_INDICATIVO METARESULTADO
   ON BP_D_NOVEDADPROYECTO.COMPANIA                       = METARESULTADO.COMPANIA 
  AND SUBSTR(BP_D_NOVEDADPROYECTO.ID_META_PRODUCTO,1,'8') = METARESULTADO.ID
  AND BP_D_NOVEDADPROYECTO.VIGENCIA_PLAN_INDICATIVO       = METARESULTADO.VIGENCIA_INICIAL  
LEFT JOIN (SELECT BP_PLAN_INDICATIVO_METAS.COMPANIA,
                  BP_PLAN_INDICATIVO_METAS.ID_PLAN,
                  BP_PLAN_INDICATIVO_METAS.VIGENCIA_PLAN,
                  SUM(BP_PLAN_INDICATIVO_METAS.CANTIDAD_PROGRAMADA) CANTIDAD_PROGRAMADA,
                  SUM(BP_PLAN_INDICATIVO_METAS.CANTIDAD_EJECUTADA) CANTIDAD_EJECUTADA                  
           FROM  BP_PLAN_INDICATIVO_METAS              
           GROUP BY BP_PLAN_INDICATIVO_METAS.COMPANIA,
                    BP_PLAN_INDICATIVO_METAS.ID_PLAN,
                    BP_PLAN_INDICATIVO_METAS.VIGENCIA_PLAN
          ) METAS
    ON BP_D_NOVEDADPROYECTO.COMPANIA                       = METAS.COMPANIA 
      AND BP_D_NOVEDADPROYECTO.ID_META_PRODUCTO            = METAS.ID_PLAN
      AND BP_D_NOVEDADPROYECTO.VIGENCIA_PLAN_INDICATIVO    = METAS.VIGENCIA_PLAN
LEFT JOIN UNIDADPROYECTOS  
   ON METAPRODUCTO.COMPANIA                       = UNIDADPROYECTOS.COMPANIA 
  AND METAPRODUCTO.UNIDAD_MEDIDA                  = UNIDADPROYECTOS.UNIDAD;
