ALTER TABLE EV_FUNCIONES ADD CARGO VARCHAR2(5 CHAR);
COMMIT;
ALTER TABLE EV_FUNCIONES ADD CONSTRAINT FK_EV_FUNCIONES_CARGOS FOREIGN KEY (COMPANIA, CARGO) REFERENCES CARGOS (COMPANIA, ID_DE_CARGO);
COMMIT;