SELECT DETALLE_COMPROBANTE_PPTAL.COMPANIA,
  DETALLE_COMPROBANTE_PPTAL.ANO,
  DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE,
  DETALLE_COMPROBANTE_PPTAL.COMPROBANTE,
  DETALLE_COMPROBANTE_PPTAL.CONSECUTIVO,
  DETALLE_COMPROBANTE_PPTAL.CUENTA,
  DETALLE_COMPROBANTE_PPTAL.DESCRIPCION,
  DETALLE_COMPROBANTE_PPTAL.VALOR_DEBITO,
  DETALLE_COMPROBANTE_PPTAL.VALOR_CREDITO,
  PLAN_PRESUPUESTAL.NOMBRE,
  PLAN_PRESUPUESTAL.NATURALEZA,
  CASE WHEN plan_presupuestal.naturaleza='C' THEN VALOR_CREDITO-VALOR_DEBITO ELSE VALOR_DEBITO-VALOR_CREDITO END AS Vlr
FROM DETALLE_COMPROBANTE_PPTAL
INNER JOIN PLAN_PRESUPUESTAL
ON (DETALLE_COMPROBANTE_PPTAL.COMPANIA = PLAN_PRESUPUESTAL.COMPANIA)
AND (DETALLE_COMPROBANTE_PPTAL.ANO     = PLAN_PRESUPUESTAL.ANO)
AND (DETALLE_COMPROBANTE_PPTAL.CUENTA  = PLAN_PRESUPUESTAL.CODIGO) 
AND DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE = '$P!{PR_TIPO_CPTE}'
AND DETALLE_COMPROBANTE_PPTAL.COMPROBANTE = $P!{PR_COMPROBANTE}
