SELECT COMPANIA,
  ANO,
  TIPOCOBRO,
  CASE
    WHEN ESTADO=0
    THEN'DESHABILITADO'
    ELSE 'ACTIVO'
  END AS EST,
  SF_CONCEPTOS.CODIGO,
  SF_CONCEPTOS.NOMBRE,
  SF_CONCEPTOS.VALOR_BASE,
  SF_CONCEPTOS.FORMULA
FROM SF_CONCEPTOS
WHERE SF_CONCEPTOS.COMPANIA='s$compania$s'
AND SF_CONCEPTOS.ANO       =s$ano$s
AND SF_CONCEPTOS.TIPOCOBRO ='s$tipocobro$s'
ORDER BY SF_CONCEPTOS.CODIGO
