WITH CONSULTA AS
  (SELECT INMUEBLES.PADRE,
    INMUEBLES.CENTRO_COSTO,
    INMUEBLES.COMERCIALIZACION,
    INMUEBLES.AREA,
    INMUEBLES.NOMBRE_INMUEBLE,
    INMUEBLES.PERIODODEUDA,
    FACTURA_CONTRATO.ANO,
    FACTURA_CONTRATO.MES,
    CASE
      WHEN FACTURA_CONTRATO.CENTRO_COSTO IN ('07')
      THEN INMUEBLES.COMERCIALIZACION
      ELSE ''
    END COMERCIOVENTA,
    CASE
      WHEN CONTRATOS.INMUEBLE IN ('999999')
      THEN FACTURA_CONTRATO.TERCERO
      ELSE CONTRATOS.TERCERO
    END ARRENDATARIO,
    FACTURA_CONTRATO.FECHA,
    FACTURA_CONTRATO.FECHA_LIMITE_PAGO,
    FACTURA_CONTRATO.FECHA_SEGUNDO_VENCIMIENTO FECHA_SEGUNDO_VENCIMIENTO,
    FACTURA_CONTRATO.CENTRO_COSTO CC,
    MAX(FACTURA_CONTRATO.DESCRIPCION) KEEP (DENSE_RANK FIRST
  ORDER BY ROWNUM) NOTA,
    FACTURA_CONTRATO.NOMBRES_TERCERO NOMBRES_TERCERO,
    FACTURA_CONTRATO.VALOR_MORA VALOR_MORA,
    FACTURA_CONTRATO.CONTRATO,
    FACTURA_CONTRATO.IMPRESA,
    FACTURA_CONTRATO.EDADH DIASMORA,
    FACTURA_CONTRATO.DEUDAACUMULADO001 DEUDAACUMULADO001,
    FACTURA_CONTRATO.DEUDAINTERES DEUDAINTERES,
    TERCERO.NOMBRE NOMBRE_ARRENDATARIO,
    CENTRO_COSTO.NOMBRE NOMBRE_CC,
    BODEGAS.NOMBRE,
    CONTRATOS.INMUEBLE,
    PCK_SYSMAN_UTL.FC_NOMBRE_MES(EXTRACT (MONTH FROM SYSDATE)) MES_FACTURADO,
    SUM(DETALLE_FACTURA_CONTRATO.VALOR_BASE) BASE,
    SUM(DETALLE_FACTURA_CONTRATO.VALOR_IVA) IVA,
    SUM(DETALLE_FACTURA_CONTRATO.VALOR_RETEFUENTE) RTEFTE,
    SUM(DETALLE_FACTURA_CONTRATO.VALOR_BASE) + SUM(DETALLE_FACTURA_CONTRATO.VALOR_IVA) - SUM(DETALLE_FACTURA_CONTRATO.VALOR_RETEFUENTE) TOTALCONCEPTO,
    SUM(DETALLE_FACTURA_CONTRATO.VALOR_BASE) + SUM(DETALLE_FACTURA_CONTRATO.VALOR_IVA) - SUM(DETALLE_FACTURA_CONTRATO.VALOR_RETEFUENTE) TOTAL_FACTURADO,
    DETALLE_FACTURA_CONTRATO.NUMERO_FACTURA NUMERO_FACTURA,
    SUM(
    CASE
      WHEN DETALLE_FACTURA_CONTRATO.CONCEPTO  IN ('001')
      THEN DETALLE_FACTURA_CONTRATO.VALOR_BASE + DETALLE_FACTURA_CONTRATO.VALOR_IVA - DETALLE_FACTURA_CONTRATO.VALOR_RETEFUENTE
      ELSE 0
    END) CANON,
    CASE
      WHEN FACTURA_CONTRATO.IMPRESA IN (-1)
      THEN 'REIMPRESA POR: '
        || 's$usuario$s'
        || ' _ '
        || SYSDATE
      ELSE ''
    END USUARIO
  FROM FACTURA_CONTRATO
  INNER JOIN TERCERO
  ON FACTURA_CONTRATO.COMPANIA  = TERCERO.COMPANIA
  AND FACTURA_CONTRATO.TERCERO  = TERCERO.NIT
  AND FACTURA_CONTRATO.SUCURSAL = TERCERO.SUCURSAL
  INNER JOIN CONTRATOS
  ON FACTURA_CONTRATO.COMPANIA  = CONTRATOS.COMPANIA
  AND FACTURA_CONTRATO.CONTRATO = CONTRATOS.CODIGO
  INNER JOIN INMUEBLES
  ON CONTRATOS.COMPANIA  = INMUEBLES.COMPANIA
  AND CONTRATOS.INMUEBLE = INMUEBLES.DENOMINACION
  INNER JOIN CENTRO_COSTO
  ON FACTURA_CONTRATO.COMPANIA      = CENTRO_COSTO.COMPANIA
  AND FACTURA_CONTRATO.ANO          = CENTRO_COSTO.ANO
  AND FACTURA_CONTRATO.CENTRO_COSTO = CENTRO_COSTO.CODIGO
  INNER JOIN DETALLE_FACTURA_CONTRATO
  ON FACTURA_CONTRATO.COMPANIA = DETALLE_FACTURA_CONTRATO.COMPANIA
  AND FACTURA_CONTRATO.ANO     = DETALLE_FACTURA_CONTRATO.ANO
  AND FACTURA_CONTRATO.MES     = DETALLE_FACTURA_CONTRATO.MES
  AND FACTURA_CONTRATO.TIPO    = DETALLE_FACTURA_CONTRATO.TIPO_FACTURA
  AND FACTURA_CONTRATO.NUMERO  = DETALLE_FACTURA_CONTRATO.NUMERO_FACTURA
  LEFT JOIN BODEGAS
  ON INMUEBLES.COMPANIA                     = BODEGAS.COMPANIA
  AND INMUEBLES.PADRE                       = BODEGAS.CODIGO
  WHERE DETALLE_FACTURA_CONTRATO.COMPANIA   = s$compania$s
  AND DETALLE_FACTURA_CONTRATO.ANO          = s$anio$s
  AND DETALLE_FACTURA_CONTRATO.TIPO_FACTURA = 's$tipoFactura$s'
  AND DETALLE_FACTURA_CONTRATO.CONTRATO BETWEEN s$comprobanteInicial$s AND s$comprobanteFinal$s
  AND FACTURA_CONTRATO.ANULADA    IN (0)
  AND TERCERO.REGIMEN BETWEEN 'C' AND 'C'
  GROUP BY INMUEBLES.PADRE,
    INMUEBLES.CENTRO_COSTO,
    INMUEBLES.COMERCIALIZACION,
    INMUEBLES.AREA,
    INMUEBLES.NOMBRE_INMUEBLE,
    INMUEBLES.PERIODODEUDA,
    BODEGAS.NOMBRE,
    TERCERO.NOMBRE,
    CENTRO_COSTO.NOMBRE,
    CONTRATOS.INMUEBLE,
    CASE
      WHEN CONTRATOS.INMUEBLE IN ('999999')
      THEN FACTURA_CONTRATO.TERCERO
      ELSE CONTRATOS.TERCERO
    END,
    CASE
      WHEN FACTURA_CONTRATO.CENTRO_COSTO IN ('07')
      THEN INMUEBLES.COMERCIALIZACION
      ELSE ''
    END,
    FACTURA_CONTRATO.ANO,
    FACTURA_CONTRATO.MES,
    FACTURA_CONTRATO.FECHA,
    FACTURA_CONTRATO.FECHA_LIMITE_PAGO,
    FACTURA_CONTRATO.FECHA_SEGUNDO_VENCIMIENTO,
    FACTURA_CONTRATO.CENTRO_COSTO,
    FACTURA_CONTRATO.NOMBRES_TERCERO,
    FACTURA_CONTRATO.VALOR_MORA,
    FACTURA_CONTRATO.CONTRATO,
    FACTURA_CONTRATO.IMPRESA,
    FACTURA_CONTRATO.EDADH,
    FACTURA_CONTRATO.DEUDAACUMULADO001,
    FACTURA_CONTRATO.DEUDAINTERES,
    DETALLE_FACTURA_CONTRATO.NUMERO_FACTURA
  ORDER BY FACTURA_CONTRATO.ANO,
    FACTURA_CONTRATO.MES
  )
SELECT 
  CONSULTA.BASE,
  CONSULTA.IVA,
  CONSULTA.RTEFTE,
  CONSULTA.NUMERO_FACTURA,
  CONSULTA.NOMBRES_TERCERO,
  CONSULTA.ARRENDATARIO,
  CONSULTA.NOMBRE_CC,
  CONSULTA.MES_FACTURADO,
  CONSULTA.FECHA,
  CONSULTA.INMUEBLE,
  CONSULTA.COMERCIOVENTA,
  CASE WHEN CONSULTA.COMERCIOVENTA IN ('') THEN '' ELSE 'Comercialización'
  END COMERCIOVENTANULL,
  CONSULTA.DEUDAACUMULADO001,
  CONSULTA.DEUDAINTERES,
  CONSULTA.FECHA_SEGUNDO_VENCIMIENTO,
  CONSULTA.TOTAL_FACTURADO + CONSULTA.VALOR_MORA TOTALMORA,
  CONSULTA.FECHA_LIMITE_PAGO,
  CONSULTA.TOTAL_FACTURADO,
  CONSULTA.USUARIO,
  ROUND((CONSULTA.TOTAL_FACTURADO),0) TOTALFACTURADO,
  CASE WHEN CONSULTA.DIASMORA IN (0) THEN ''  ELSE 'Su Factura Presenta Mora de: ' || CONSULTA.DIASMORA || ' Días.  ' || CONSULTA.NOTA END DIASMORACONOTA,
  CASE WHEN CONSULTA.DIASMORA IN (0)  THEN '' ELSE 'Su Factura Presenta Mora de: ' || CONSULTA.DIASMORA || ' Días.  ' END DIASMORASINOTA,
  SUBSTR(CHR(205)
        || CHR(102)
        || CHR(40)
        || '415'
        || CHR(41)
        || 's$codigoEan$s'
        || CHR(40)
        || '8020'
        || CHR(41)
        || LPAD(CONSULTA.NUMERO_FACTURA,19,0)
        || CHR(40)
        || '3900'
        || CHR(41)
        || LPAD(CONSULTA.TOTAL_FACTURADO,14,0)
        || CHR(40)
        || '96'
        || CHR(41)
        || TO_CHAR(CONSULTA.FECHA_SEGUNDO_VENCIMIENTO,'YYYYMMDD'),3) PIEBARRA,
   TO_CHAR(PCK_CODIGODEBARRAS.FC_IMPRIMIRCODIGODEBARRAS(CHR(205)
        || CHR(102)
        || '415'
        ||'s$codigoEan$s'
        || '8020'
        || LPAD(CONSULTA.NUMERO_FACTURA,19,0)
        || CHR(102)
        || '3900'
        || LPAD(CONSULTA.TOTAL_FACTURADO,14,0)
        || CHR(102)
        || '96'
        ||  TO_CHAR(CONSULTA.FECHA_SEGUNDO_VENCIMIENTO,'YYYYMMDD')))  CODIGODEBARRAS_BIN
FROM CONSULTA
