MERGE INTO CONSULTAS FIN USING (SELECT '002303LiquidacionMultasCorpo' INFORME ,TO_CLOB(q'[SELECT SFA.COMPANIA, 
SFA.TIPO, 
SFA.CODIGO, 
SFA.TERCERO TERCERO_NIT,
TER.NOMBRE TERCERO_NOMBRE,
SF_FACTURA.FECHA_VENCIMIENTO FECHA_ACTUALIZACION,
SF_FACTURA.NUMERO_RESOLUCION,
SF_FACTURA.NUMERO_EXPEDIENTE,
TASAS.TASAINTERES TASA_INTERESES,
SFA.SUCURSAL, 
SFA.DEUDA_CAPITAL - NVL(CAPITAL_PAGOS.PAGOS,0) DEUDA_CAPITAL,
DA.CAPITAL A_CAPITAL,
s$interesCalculado$s A_INTERES,
SFA.DEUDA_INTERES,
DA.INTERES APLICAINTERES,
CASE WHEN  SFA.DEUDA_INTERES > = DA.TOTAL_CUOTA THEN SFA.DEUDA_INTERES - NVL(INTERESES_PAGOS.PAGOS,0) - DA.INTERES ELSE 0 END  SALDOINTERES,
CASE WHEN DA.INTERES_EXPEM > 0 
  THEN ((SFA.INTERES_ACT + SFA.INTERES_EX) - NVL(INTERESES_PAGOS.PAGOS,0)) 
  ELSE DA.INTERES_EXPEM END INTERESEXTEM,
SFA.DEUDA_TOTAL,
DA.TOTAL_CUOTA VALOR_ACTUALIZADO,
TO_DATE('s$fechaVencimientoPago$s', 'DD/MM/YYYY') FECHA_VENCIMIENTOPAGO,
        TO_DATE('s$fechaPago$s', 'DD/MM/YYYY') FECHA_CORTE,
        's$diasMora$s' DIAS_MORA
FROM SF_ABONOS SFA
INNER JOIN TERCERO TER
ON TER.COMPANIA = SFA.COMPANIA
AND TER.NIT = SFA.TERCERO
AND TER.SUCURSAL = SFA.SUCURSAL
INNER JOIN SF_FACTURA
ON SF_FACTURA.COMPANIA = SFA.COMPANIA
AND SF_FACTURA.TIPO_FACTURA = SFA.TIPO_FACT
AND SF_FACTURA.NUMERO_FACTURA = SFA.NRO_FACT
 INNER JOIN SF_DETALLE_ABONO DA
 ON SFA.COMPANIA = DA.COMPANIA
    AND SFA.TIPO = DA.TIPO_ABONO
    AND SFA.CODIGO = DA.CODIGO_ABONO
 INNER JOIN SF_TASAS_INTERES TASAS
 ON DA.COMPANIA = TASAS.COMPANIA
    AND SF_FACTURA.ANO = TASAS.ANO
    AND DA.TIPO_ABONO = TASAS.TIPOCOBRO
LEFT JOIN (  SELECT DC.COMPANIA,
                  DC.ANO,
                  DC.TIPOFACT TIPO,
                  DC.NROFACT CODIGO,
                  SUM(DC.VALOR_BASE) PAGOS
                  FROM   SF_DETALLE_CUOTAABONO DC
                INNER JOIN SF_DETALLE_ABONO DA
                ON DC.COMPANIA = DA.COMPANIA
                AND DC.TIPO_ABONO = DA.TIPO_ABONO
                AND DC.CODIGO_ABONO = DA.CODIGO_ABONO
                AND DC.CUOTA = DA.CUOTA
                INNER JOIN SF_DETALLE_FACTURA SDF
                ON SDF.COMPANIA = DC.COMPANIA
                AND SDF.TIPO_FACTURA = DC.TIPOFACT
                AND SDF.FACTURA = DC.NROFACT
                AND SDF.CONCEPTO = DC.CONCEPTO
                WHERE DC.COMPANIA        = 's$compania$s'
                AND DC.TIPO_ABONO        = 's$tipoCobro$s'
                AND DC.NROFACT      = 's$numero_factura$s'
                AND DA.ESTADO            IN ('R')
                GROUP BY DC.COMPANIA,
                  DC.ANO,
                  DC.TIPOFACT,
                  DC.NROFACT) CAPITAL_PAGOS
ON CAPITAL_PAGOS.COMPANIA = SFA.COMPANIA
AND CAPITAL_PAGOS.TIPO = SFA.TIPO_FACT
AND CAPITAL_PAGOS.CODIGO = SFA.NRO_FACT
LEFT JOIN (SELECT DC.COMPANIA,
                  DC.ANO,
                  DC.TIPOFACT TIPO,
                  DC.NROFACT CODIGO,
                  SUM(DC.VALOR_BASE) PAGOS
                  FROM   SF_DETALLE_CUOTAABONO DC
                INNER JOIN SF_DETALLE_ABONO DA
                ON DC.COMPANIA = DA.COMPANIA
                AN]') || TO_CLOB(q'[D DC.TIPO_ABONO = DA.TIPO_ABONO
                AND DC.CODIGO_ABONO = DA.CODIGO_ABONO
                AND DC.CUOTA = DA.CUOTA
                WHERE DC.COMPANIA        = 's$compania$s'
                AND DC.TIPO_ABONO        = 's$tipoCobro$s'
                AND DC.NROFACT      = 's$numero_factura$s'
                AND DA.ESTADO            IN ('R')
                AND (DC.CONCEPTO = PCK_SYSMAN_UTL.FC_VALIDARPARAMETRO (UN_COMPANIA  => 's$compania$s',
                  UN_PARAMETRO => 'SF CONCEPTO INTERESES PAGOS PARCIALES',
                  UN_MODULO    => -1 ) OR DC.CONCEPTO = PCK_SYSMAN_UTL.FC_VALIDARPARAMETRO (UN_COMPANIA  => 's$compania$s',
                  UN_PARAMETRO => 'SF CONCEPTO INTERESES EXTEMPORANEOS PAGOS PARCIALES',
                  UN_MODULO    => -1 ))
                GROUP BY DC.COMPANIA,
                  DC.ANO,
                  DC.TIPOFACT,
                  DC.NROFACT) INTERESES_PAGOS
ON INTERESES_PAGOS.COMPANIA = SFA.COMPANIA
AND INTERESES_PAGOS.TIPO = SFA.TIPO_FACT
AND INTERESES_PAGOS.CODIGO = SFA.NRO_FACT
WHERE SFA.COMPANIA = 's$compania$s'
AND SFA.TIPO_FACT     = 's$tipoCobro$s'
AND SFA.NRO_FACT   = 's$numero_factura$s'
AND DA.ESTADO = 'A']') CONSULTA, 69 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);