SELECT SF_ABONOS.TIPO,
  SF_ABONOS.CODIGO,
  SF_DETALLE_CUOTAABONO.TIPOFACT,
  SF_DETALLE_CUOTAABONO.NROFACT,
  SF_ABONOS.TERCERO,
  SF_ABONOS.SUCURSAL,
  NVL(TO_CHAR(SF_ABONOS.FECHA_INICIO,'DD/MM/YYYY'),' ') FECHA_INICIO,
  NVL(TO_CHAR(SF_DETALLE_ABONO.FECHACUOTA,'DD/MM/YYYY'),' ') FECHACUOTA,
  SF_DETALLE_ABONO.CUOTA,  
  TERCERO.NOMBRE NOMTERCERO,
  TERCERO.DIRECCION,
  SF_DETALLE_CUOTAABONO.TOTAL_CUOTA TFACTURA,
  SF_DETALLE_CUOTAABONO.TOTAL_CUOTA,
  SUBSTR(CHR(205)
  || CHR(102)
  || CHR(40)
  || '415'
  || CHR(41)
  || PCK_SYSMAN_UTL.FC_PAR(UN_COMPANIA =>'001',UN_NOMBRE =>'SF CODIGO EAN',UN_MODULO=>'69',UN_FECHA_PAR=>SYSDATE,UN_IND_MAYUS=>0)
  || CHR(40)
  || '8020'
  || CHR(41)
  || SF_ABONOS.TIPO
  ||SF_ABONOS.CODIGO
  || CHR(40)
  || '3900'
  || CHR(41)
  || (SF_DETALLE_CUOTAABONO.TOTAL_CUOTA)
  || CHR(40)
  || '96'
  || CHR(41)
  || TO_CHAR(SF_DETALLE_ABONO.FECHACUOTA,'YYYYMMDD'),3) AS PIEBARRA,
  TO_CHAR(PCK_CODIGODEBARRAS.FC_IMPRIMIRCODIGODEBARRAS(CHR(205)
  || CHR(102)
  || '415'
  || PCK_SYSMAN_UTL.FC_PAR(UN_COMPANIA=>'001',UN_NOMBRE=>'SF CODIGO EAN',UN_MODULO=>'69',UN_FECHA_PAR=>SYSDATE,UN_IND_MAYUS=>0)
  || '8020'
  || LPAD(SF_TIPO_COBRO.TIPOFACTURA_RECAUDO,5,0)
  ||LPAD(SF_DETALLE_CUOTAABONO.NROFACT,19,0)
  || CHR(102)
  || '3900'
  || LPAD(SF_DETALLE_CUOTAABONO.TOTAL_CUOTA,14,0)
  || CHR(102)
  || '96'
  || TO_CHAR(SF_DETALLE_ABONO.FECHACUOTA,'YYYYMMDD'))) AS CODIGODEBARRAS_BIN,
  NVL(CIUDAD.NOMBRE,' ') CIUDAD
FROM SF_DETALLE_CUOTAABONO
INNER JOIN SF_DETALLE_ABONO
ON SF_DETALLE_CUOTAABONO.COMPANIA      = SF_DETALLE_ABONO.COMPANIA
AND SF_DETALLE_CUOTAABONO.CUOTA        = SF_DETALLE_ABONO.CUOTA
AND SF_DETALLE_CUOTAABONO.CODIGO_ABONO = SF_DETALLE_ABONO.CODIGO_ABONO
AND SF_DETALLE_CUOTAABONO.TIPO_ABONO   = SF_DETALLE_ABONO.TIPO_ABONO
INNER JOIN SF_ABONOS
ON SF_DETALLE_ABONO.COMPANIA      = SF_ABONOS.COMPANIA
AND SF_DETALLE_ABONO.CODIGO_ABONO = SF_ABONOS.CODIGO
AND SF_DETALLE_ABONO.TIPO_ABONO   = SF_ABONOS.TIPO
LEFT JOIN TERCERO
ON SF_ABONOS.COMPANIA = TERCERO.COMPANIA
AND SF_ABONOS.TERCERO = TERCERO.NIT
AND SF_ABONOS.SUCURSAL= TERCERO.SUCURSAL
LEFT JOIN CIUDAD
ON TERCERO.PAIS = CIUDAD.PAIS
AND TERCERO.DEPARTAMENTO = CIUDAD.DEPARTAMENTO
AND TERCERO.CIUDAD = CIUDAD.CODIGO

INNER JOIN SF_TIPO_COBRO 
ON SF_DETALLE_CUOTAABONO.COMPANIA      = SF_TIPO_COBRO.COMPANIA
AND SF_DETALLE_CUOTAABONO.ANO          = SF_TIPO_COBRO.ANO
AND SF_DETALLE_CUOTAABONO.TIPOFACT = SF_TIPO_COBRO.CODIGO
WHERE SF_ABONOS.COMPANIA = s$compania$s
AND SF_ABONOS.TIPO= 's$tipo$s'
AND SF_ABONOS.CODIGO = s$nroFactura$s
AND SF_DETALLE_ABONO.CUOTA=s$nroCuota$s
