MERGE INTO CONSULTAS FIN USING (SELECT '002370FEREPORTEBUSQUEDANOTAS' INFORME ,TO_CLOB(q'[SELECT 
ESTADO_NOTAS.CLASE,        
ESTADO_NOTAS.ESTADO,        
ESTADO_NOTAS.FECHA,        
ESTADO_NOTAS.NUMFACTURA,        
ESTADO_NOTAS.NUMFORMATO,
COMPROBANTE_CNT.VLR_DOCUMENTO VALOR,
COMPROBANTE_CNT.TERCERO,
ESTADO_NOTAS.OBSERVACION
FROM ESTADO_NOTAS,COMPROBANTE_CNT WHERE COMPROBANTE_CNT.NUMERO = ESTADO_NOTAS.NUMFORMATO AND TIPO = 'NCL']') CONSULTA, 69 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);