MERGE INTO CONSULTAS FIN USING (SELECT '002506ContrantosTel' INFORME ,TO_CLOB(q'[SELECT SF_CONTRATOS.CREATED_BY,SYSDATE AS FECHA_REGISTRO, SF_CONTRATOS.TIPO||'  '||SF_TIPO_COBRO.NOMBRE AS TIPO_COBRO, SF_CONTRATOS.NUMERO,
SF_CONTRATOS.TERCERO||'  '||TERCERO.NOMBRE AS NOMBRE_TERCERO, SF_CONTRATOS.VENDEDOR||'  '||TERCERO1.NOMBRE  AS NOMBRE_VENDEDOR, TERCERO.CIUDAD ||'  '||CIUDAD.NOMBRE AS CIUDAD, 
SF_CONTRATOS.DATE_CREATED, 
CASE WHEN SF_CONTRATOS.ESTADO = 2 THEN 'ACTIVO' WHEN SF_CONTRATOS.ESTADO = 3 THEN 'SUSPENDIDO' WHEN SF_CONTRATOS.ESTADO = 5 THEN 'CANCELADO' ELSE ' ' END AS ESTADO, OBJETO_CONTRATO,
SF_DETALLE_CONTRATO.CONCEPTO, CENTRO_UTILIDAD.CODIGO CENTRO_UTILIDADES, CENTRO_UTILIDAD.DESCRIPCION NOMBRE_CENTRO, SF_CONCEPTOS.NOMBRE NOMBRE_PRODUCTO, SF_DETALLE_CONTRATO.CANTIDAD,
SF_DETALLE_CONTRATO.VALOR_UNITARIO,SF_DETALLE_CONTRATO.VALOR_BASE,
CASE WHEN SF_CONTRATOS.ACTA_NOTIFIACION = 1 THEN 'S' WHEN SF_CONTRATOS.ACTA_NOTIFIACION = 0 THEN 'N' ELSE ' ' END AS ACTA_NOTIFIACION, SF_CONTRATOS.FECHA_INICIO,
SF_CONTRATOS.FECHA_FINALIZACION,SF_CONTRATOS.TIEMPO_CONTRATADO
FROM SF_CONTRATOS 
INNER JOIN SF_DETALLE_CONTRATO ON
SF_CONTRATOS.COMPANIA = SF_DETALLE_CONTRATO.COMPANIA AND
SF_CONTRATOS.TIPO = SF_DETALLE_CONTRATO.TIPO AND
SF_CONTRATOS.NUMERO = SF_DETALLE_CONTRATO.NUMERO AND
SF_CONTRATOS.TERCERO = SF_DETALLE_CONTRATO.TERCERO
INNER JOIN SF_TIPO_COBRO ON 
SF_CONTRATOS.COMPANIA = SF_TIPO_COBRO.COMPANIA AND
SF_CONTRATOS.ANO = SF_TIPO_COBRO.ANO AND
SF_CONTRATOS.TIPO = SF_TIPO_COBRO.CODIGO
INNER JOIN SF_CONCEPTOS ON
SF_CONCEPTOS.COMPANIA = SF_DETALLE_CONTRATO.COMPANIA AND
SF_CONCEPTOS.ANO = SF_DETALLE_CONTRATO.ANO AND
SF_CONCEPTOS.TIPOCOBRO = SF_DETALLE_CONTRATO.TIPO AND
SF_CONCEPTOS.CODIGO = SF_DETALLE_CONTRATO.CONCEPTO 
LEFT JOIN TERCERO ON
SF_CONTRATOS.COMPANIA = TERCERO.COMPANIA AND
SF_CONTRATOS.TERCERO = TERCERO.NIT
INNER JOIN TERCERO  TERCERO1 ON
SF_CONTRATOS.COMPANIA = TERCERO1.COMPANIA AND
SF_CONTRATOS.VENDEDOR = TERCERO1.NIT
INNER JOIN CIUDAD ON
TERCERO.PAIS = CIUDAD.PAIS AND
TERCERO.DEPARTAMENTO = CIUDAD.DEPARTAMENTO AND
TERCERO.CIUDAD = CIUDAD.CODIGO
LEFT JOIN CENTRO_UTILIDAD ON
SF_DETALLE_CONTRATO.COMPANIA = CENTRO_UTILIDAD.COMPANIA AND
SF_DETALLE_CONTRATO.ANO = CENTRO_UTILIDAD.ANO AND
SF_DETALLE_CONTRATO.CENTRO_UTILIDAD = CENTRO_UTILIDAD.CODIGO
WHERE
SF_CONTRATOS.COMPANIA=s$compania$s AND
SF_CONTRATOS.TIPO =  's$tipoCobro$s' AND
SF_CONTRATOS.NUMERO=s$numero$s ]') CONSULTA, 69 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, 'MROSERO' CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);