MERGE INTO CONSULTAS FIN USING (SELECT '002514INF_FAC_IDCBIS_sub' INFORME ,TO_CLOB(q'[SELECT ROW_NUMBER() OVER(PARTITION BY SF_FACTURA.NUMERO_FACTURA ORDER BY SF_DETALLE_FACTURA.FACTURA) AS ITEMS, 
SF_FACTURA.NUMERO_FACTURA,  SF_FACTURA.TIPO_FACTURA, TERCERO.NOMBRE, SF_FACTURA.TERCERO, TERCERO.TELEFONOS, 
SF_OBJETO_COBRO.DIRECCION, CIUDAD.NOMBRE CIUDAD, SF_FACTURA.CENTRO_COSTO, TERCERO.DIRECCIONEMAIL, SF_CONCEPTOS.CODEQUIV_DIAN, 
SF_CONCEPTOS.NOMBRE NOMBRECONCEPTO, SF_CONCEPTOS.UNIDAD, SF_DETALLE_FACTURA.CANTIDAD, SF_DETALLE_FACTURA.VALOR_UNITARIO, 
SF_DETALLE_FACTURA.VALOR_NETO, SF_FACTURA.VALOR_TOTAL, TERCERO.TIPOENTIDAD,
(CASE 
    WHEN SF_OBJETO_COBRO.TIPO_PAGO = 1 THEN 'PAGO DE CONTADO'
    WHEN SF_OBJETO_COBRO.TIPO_PAGO = 2 THEN 'PAGO A CREDITO'
    ELSE ''
END || RPAD(' ', 7) || SF_MEDIO_PAGO.DESCRIPCION) AS TIPO_PAGO , 
 SF_OBJETO_COBRO.OBSERVACIONES, 
('Prefijo ' || SF_OBJETO_COBRO.TXTPREFIJO || RPAD(' ', 7) || 'Numero ' || SF_OBJETO_COBRO.TXTCONTRATO) AS CONTRATO, 
SF_FACTURA.CREATED_BY,     TO_CHAR(SF_FACTURA.FECHA_EXPEDICION, 'YYYY-MM-DD') AS FECHA_EXPEDICION,
    TO_CHAR(SF_FACTURA.FECHA_VENCIMIENTO, 'YYYY-MM-DD') AS FECHA_VENCIMIENTO,SF_TIPO_COBRO.LEYENDA_FACTURA
FROM SF_DETALLE_FACTURA
INNER JOIN SF_FACTURA ON SF_DETALLE_FACTURA.FACTURA = SF_FACTURA.NUMERO_FACTURA
AND SF_DETALLE_FACTURA.TIPO_FACTURA = SF_FACTURA.TIPO_FACTURA 
AND SF_DETALLE_FACTURA.COMPANIA = SF_FACTURA.COMPANIA 
INNER JOIN SF_OBJETO_COBRO ON SF_FACTURA.COMPANIA = SF_OBJETO_COBRO.COMPANIA
AND SF_FACTURA.ANO = SF_OBJETO_COBRO.ANO
AND SF_FACTURA.NUMERO_FACTURA = SF_OBJETO_COBRO.NRO_FACTURA
AND SF_FACTURA.TIPOCOBRO = SF_OBJETO_COBRO.TIPOCOBRO
INNER JOIN SF_TIPO_COBRO ON SF_FACTURA.COMPANIA = SF_TIPO_COBRO.COMPANIA 
AND SF_FACTURA.TIPO_FACTURA = SF_TIPO_COBRO.CODIGO 
AND SF_DETALLE_FACTURA.ANO = SF_TIPO_COBRO.ANO 
INNER JOIN TERCERO ON SF_FACTURA.COMPANIA = TERCERO.COMPANIA 
AND SF_FACTURA.TERCERO = TERCERO.NIT 
AND SF_FACTURA.SUCURSAL = TERCERO.SUCURSAL 
INNER JOIN SF_CONCEPTOS ON SF_CONCEPTOS.COMPANIA = SF_DETALLE_FACTURA.COMPANIA 
AND SF_CONCEPTOS.ANO = SF_DETALLE_FACTURA.ANO 
AND SF_CONCEPTOS.TIPOCOBRO = SF_DETALLE_FACTURA.TIPOCOBRO 
AND SF_CONCEPTOS.CODIGO = SF_DETALLE_FACTURA.CONCEPTO 
INNER JOIN CIUDAD ON CIUDAD.DEPARTAMENTO = TERCERO.DEPARTAMENTO
AND CIUDAD.CODIGO = TERCERO.CIUDAD 
LEFT JOIN SF_MEDIO_PAGO ON SF_OBJETO_COBRO.COMPANIA = SF_MEDIO_PAGO.COMPANIA
AND SF_OBJETO_COBRO.TIPO_MEDIOPAGO= SF_MEDIO_PAGO.CODIGO
WHERE  SF_FACTURA.COMPANIA =  s$compania$s AND SF_FACTURA.TIPO_FACTURA   = 's$tipoFactura$s'
AND SF_FACTURA.NUMERO_FACTURA BETWEEN s$facturaInicial$s AND s$facturaFinal$s  
AND SF_FACTURA.fecha_pago IS NULL
 AND ANULADA IN (0)]') CONSULTA, 69 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, 'MROSERO' CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);