MERGE INTO CONSULTAS FIN USING (SELECT '002705SUBCONTRATOINMUEBLESESPECIFICO' INFORME ,TO_CLOB(q'[SELECT DISTINCT INMUEBLE_FACTURACION.CODIGOINMUEBLE,
INMUEBLE_FACTURACION.AREA AREAINMUEBLE,
INMUEBLE_FACTURACION.DIRECCION,
INMUEBLE_FACTURACION.OBSERVACIONES,INMUEBLE_FACTURACION.EDIFICIO, INMUEBLE_FACTURACION.TIPO,
INMUEBLE_FACTURACION.LINDERONORTE, INMUEBLE_FACTURACION.LINDEROSUR,
INMUEBLE_FACTURACION.LINDEROORIENTE,INMUEBLE_FACTURACION.LINDEROOCCIDENTE, INMUEBLE_FACTURACION.LINDEROCENIT,
INMUEBLE_FACTURACION.LINDERONADIR, CASE WHEN INMUEBLE_FACTURACION.TIPO = 1 THEN  'Local' WHEN INMUEBLE_FACTURACION.TIPO = 2 THEN 'Mezzanine' WHEN INMUEBLE_FACTURACION.TIPO = 3 THEN 'Bodega' WHEN INMUEBLE_FACTURACION.TIPO = 4 THEN 'Sótano' WHEN INMUEBLE_FACTURACION.TIPO = 5 THEN 'Oficina' WHEN INMUEBLE_FACTURACION.TIPO = 6 THEN 'Piso' WHEN INMUEBLE_FACTURACION.TIPO = 7 THEN 'Casa' WHEN INMUEBLE_FACTURACION.TIPO = 8 THEN 'Lote' WHEN INMUEBLE_FACTURACION.TIPO = 9 THEN 'Plazoleta' WHEN INMUEBLE_FACTURACION.TIPO = 10 THEN 'Galeria Bochica' WHEN INMUEBLE_FACTURACION.TIPO = 11 THEN 'Edificio' WHEN INMUEBLE_FACTURACION.TIPO = 12 THEN 'Terraza' WHEN INMUEBLE_FACTURACION.TIPO = 13 THEN 'Baño' WHEN INMUEBLE_FACTURACION.TIPO = 14 THEN 'Pasillo' WHEN INMUEBLE_FACTURACION.TIPO = 15 THEN 'Espacio' END NOMBRETIPO,
CASE WHEN INMUEBLE_FACTURACION.EDIFICIO = 1 THEN     'Ascensores'     WHEN INMUEBLE_FACTURACION.EDIFICIO = 2 THEN     'Pedregal'     WHEN INMUEBLE_FACTURACION.EDIFICIO = 3 THEN     'RTN'     WHEN INMUEBLE_FACTURACION.EDIFICIO = 4 THEN     'Bachue'     WHEN INMUEBLE_FACTURACION.EDIFICIO = 5 THEN     'RTS'     WHEN INMUEBLE_FACTURACION.EDIFICIO = 6 THEN     'Bochica'     WHEN INMUEBLE_FACTURACION.EDIFICIO = 7 THEN     '0001'     WHEN INMUEBLE_FACTURACION.EDIFICIO = 8 THEN     '0003'     END EDIFICIO_LETRAS
FROM SF_CONTRATOS
INNER JOIN TERCERO T
ON (SF_CONTRATOS.COMPANIA= T.COMPANIA
AND SF_CONTRATOS.TERCERO= T.NIT
AND SF_CONTRATOS.SUCURSAL = T.SUCURSAL)
LEFT JOIN TERCERO TS
ON (SF_CONTRATOS.COMPANIA= TS.COMPANIA
AND SF_CONTRATOS.VENDEDOR= TS.NIT
AND SF_CONTRATOS.SUCURSAL = TS.SUCURSAL)
LEFT JOIN TERCERO TOG
ON (SF_CONTRATOS.COMPANIA= TOG.COMPANIA
AND SF_CONTRATOS.ORDENADORGASTO= TOG.NIT
AND SF_CONTRATOS.SUCURSAL = TOG.SUCURSAL)
LEFT JOIN TERCERO TRL
ON (SF_CONTRATOS.COMPANIA= TRL.COMPANIA
AND SF_CONTRATOS.REPRESENTANTELEGAL= TRL.NIT
AND SF_CONTRATOS.SUCURSAL = TRL.SUCURSAL)
LEFT JOIN SF_DETALLE_CONTRATO ON (
SF_CONTRATOS.COMPANIA = SF_DETALLE_CONTRATO.COMPANIA
AND SF_CONTRATOS.NUMERO = SF_DETALLE_CONTRATO.NUMERO
AND SF_CONTRATOS.TIPO = SF_DETALLE_CONTRATO.TIPO)
LEFT JOIN INMUEBLE_FACTURACION ON (
SF_DETALLE_CONTRATO.COMPANIA = INMUEBLE_FACTURACION.COMPANIA
AND SF_DETALLE_CONTRATO.INMUEBLE = INMUEBLE_FACTURACION.CODIGOINMUEBLE)
INNER JOIN SF_COTIZACION ON (
SF_CONTRATOS.COMPANIA = SF_COTIZACION.COMPANIA
AND SF_CONTRATOS.NUMCOTIZACION = SF_COTIZACION.NUMERO)
LEFT JOIN CIIU ON
(SF_CONTRATOS.COMPANIA= CIIU.COMPANIA
AND SF_CONTRATOS.DESTINACION = CIIU.ID_CIIU )
WHERE SF_CONTRATOS.NUMERO = 's$numero$s' AND SF_CONTRATOS.COMPANIA = 's$comp]') || TO_CLOB(q'[ania$s' AND SF_CONTRATOS.TIPO = 's$tipoCobro$s' ORDER BY CODIGOINMUEBLE ASC]') CONSULTA, 69 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, 'LJDIAZ' CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);

MERGE INTO CONSULTAS_SUB FIN USING (SELECT '002651contratopersonalizado' INFORME_PADRE, '002705SUBCONTRATOINMUEBLESESPECIFICO' INFORME_HIJO, 'PR_STRSQL_SUB_CONTRATOS' PARAMETRO ,'LJDIAZ' CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (FIN.INFORME_PADRE = INI.INFORME_PADRE AND INI.INFORME_HIJO = FIN.INFORME_HIJO)  WHEN MATCHED THEN  UPDATE SET FIN.PARAMETRO = INI.PARAMETRO , FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME_PADRE,INFORME_HIJO, PARAMETRO,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME_PADRE,INI.INFORME_HIJO, INI.PARAMETRO,INI.CREATED_BY,SYSDATE);