ARQB_LINEA_BASE_PROD=6.1.0
DUITAMA_PROD=6.0.4
ALCTRINIDAD_STG=3.1.9
ESPFUNZA_STG=3.9.6
ALC_MELGAR_QA=UNDEFINED
UESVALLE_SGT=4.3.6
HONDA_PROD=5.9.3
ALC_MELGAR_PROD=6.0.4
TUNJA_ALC_NOMINA_QA=UNDEFINED
CORPOBOYACA_PROD=6.1.0
IDCBIS_PROD=5.8.5
CAQUETA_PROD=6.0.3
CARDER_PROD=5.8.5
GUACAMAYAS_QA=UNDEFINED
CREMIL_QA=1.0.9
HONDA_QA=1.0.7
ESPFUNZA_PROD=5.7.2
USPEC_PROD=5.7.7
IRDPASTO_STG=5.3.2
ALCCHIQUINQUIRA_PROD=3.3.0
INSDEPORTECAJICA_STG=3.1.9
FUNZA_ALC_QA=UNDEFINED
ALC_SANMARTIN_QA=UNDEFINED
ESPINIO_PROD=5.7.9
ESE_MIRAFLORES_STG=5.4.3
ASOCENTRO_PROD=5.7.9
FLORENCIA_QA=UNDEFINED
TVANDINA_PROD=5.7.7
INSVIVIENDACAJICA_PROD=6.0.4
ESP_CHIA_STG=1.4.6
ALC_GUICAN_STG=2.0.0
REDVITAL_QA=UNDEFINED
ALCCUBARA_STG=4.3.1
FLORENCIA_PROD=5.3.5
PRE_TELEPACIFICO_PROD=5.8.5
CENTROMH_STG=3.0.8
ALC_SANTAMARIA_PROD=5.1.9
ALC_TIBANA_PROD=2.0.0
ITTACACIAS_PROD=6.0.3
CENTROMH_PROD=6.0.4
BUCARAMANGA_ALC_PROD=UNDEFINED
CAJICAORACLE_PROD=4.3.5
IDSN_PROD=6.1.0
UPC_QA=UNDEFINED
DUITAMA_QA=UNDEFINED
ALC_SANMARTIN_PROD=5.5.0
ACACIAS_ALC_PROD=5.5.3
CORPOBOYACA_QA=1.1.2
IMRD_TOCANCIPA_QA=UNDEFINED
CONTRALORIA_META_PROD=5.5.8
PANQUEBA_UNIST_PROD=UNDEFINED
ALC_GUICAN_QA=5.2.6
UPC_PROD=UNDEFINED
SOGAMOSO_PROD=6.1.0
IDERF_FUSAGASUGA_STG=3.0.0
IRDPASTO_PROD=5.3.0
CAJICATEST_PROD=3.8.8
CHISCAS=1.6.2
ESP_CAJICA_QA=UNDEFINED
INSVIVIENDACAJICA_STG=2.2.6
ALCCUBARA_PROD=6.0.4
EATIMJ_YURUPARI_STG=4.1.9
GUACAMAYAS_PROD=6.0.5
TUTA_ALC_QA=UNDEFINED
IDSN_QA=UNDEFINED
AGUAZUL_PROD=UNDEFINED
NARINO_PROD=6.1.0
TUTA_ALC_PROD=5.3.7
ALCSABOYA_STG=5.4.9
SOGAMOSOCOLEGIO_PROD=5.2.7
CORTOLIMA_QA=1.0.9
IDEAM_QA=UNDEFINED
AGUAZUL_QA=UNDEFINED
IRDFUSAGASUGA_PROD=5.2.9
TUNJA_ALC_PROD=3.8.6
COSERVICIOS_PROD=5.5.0
CASTILLA_ALC_QA=UNDEFINED
ESE_MIRAFLORES_PROD=4.0.0
INSTCULCAJICA_STG=5.3.7
GUACAMAYAS_STG=1.6.8
SINCHI_PROD=5.5.2
CONTRALORIA_META_STG=4.9.9
ASOCENTRO_STG=3.8.4
ESPINIO_STG=4.0.4
DEMO_PROD=6.1.0
DEVOPS_QA=1.1.3
TVANDINA_STG=2.3.3
UESVALLE_STG=5.1.9
ESP_MADRID_PROD=5.6.8
CONSEJO_TOCANCIPA_STG=5.1.1
EATIMJ_YURUPARI_PROD=5.9.8
IDSN_STG=6.0.9
ESP_CAJICA_PROD=3.1.7
TOCANCIPA_PROD=5.5.3
EPS_MALLAMAS_STG=5.9.8
CONSEJO_TOCANCIPA_PROD=5.5.2
BUENAVISTA_PROD=5.5.6
FEDERACION_QA=UNDEFINED
EPS_MALLAMAS_PROD=5.9.0
CAJICA_QA=1.1.1
ALC_TIBANA_STG=5.5.8
SINCHI_QA=1.1.1
TUNJA_ALC_NOMINA_PROD=UNDEFINED
BUENAVISTA_STG=5.2.8
IMRD_TOCANCIPA_PROD=5.9.3
NARINO_QA=1.1.4
ESP_MADRID_STG=5.1.9
TELEPACIFICO_PROD=6.1.0
CHISCAS_PROD=6.1.0
IRDFUSAGASUGA_STG=3.0.0
IDCBIS_QA=1.1.6
ESP_MADRID_QA=UNDEFINED
ACUALCOS_PROD=5.5.8
ALC_GUICAN_PROD=5.7.1
ESP_CHIA_PROD=5.8.4
INSDEPORTECAJICA_PROD=5.7.7
CAQUETA_QA=1.1.1
INSTCULCAJICA_PROD=5.3.1
CHISCAS_STG=2.0.0
FEDERACION_PROD=5.5.0
PANQUEBA_STG=1.6.8
BUCARAMANGA_ALC_QA=UNDEFINED
IDIPRON_PROD=UNDEFINED
USPEC_QA=UNDEFINED
SOGAMOSO_QA=UNDEFINED
IDEAM_PROD=5.9.0
REDVITAL_PROD=6.0.4
CASTILLA_ALC_PROD=6.1.0
TUNJA_ALC_QA=UNDEFINED
CARDER_STG=6.0.9
ALCSABOYA_PROD=5.3.0
CAJICA_PROD=6.0.3
IDIPRON_QA=UNDEFINED
PRE_HONDA_PROD=5.8.5
ALC_SANTAMARIA_STG=3.0.0
ALCCHIQUINQUIRA_STG=3.7.4
COSERVICIOS_STG=5.4.3
UESVALLE_PROD=6.1.0
TELEPACIFICO_QA=1.1.0
ALCTRINIDAD_PROD=6.1.0
PANQUEBA_PROD=5.8.0
ESP_CHIA_QA=1.6.1
ALC_SANMARTIN_STG=1.4.9
PRE_FEDERACION_PROD=5.8.5
FUNZA_ALC_PROD=UNDEFINED
TOCANCIPA_QA=1.1.6
CORTOLIMA_PROD=6.1.0
ACUALCOS_STG=2.6.2
ACACIAS_ALC_QA=1.1.1
CREMIL_PROD=6.1.0
ITTACACIAS_STG=2.4.8