IS_NEW_ENTITY=false
DEPLOY_WILDFLY=true
DEPLOY_WSO2=true
DEPLOY_REPORTS=true
EXECUTE_METASCRIPTS=true
METASCRIPTS_VERSION_TO_EXECUTE=6.1.0
EXECUTE_PLSQL=true
EXECUTE_ONDEMAND_PLSQL=false
TICKETS=4493
