MERGE INTO CONSULTAS FIN USING (SELECT '000314IInventarioCodCUBS' INFORME ,TO_CLOB(q'[SELECT
    INVENTARIO.COMPANIA, 
    INVENTARIO.CODIGOELEMENTO, 
    INVENTARIO.NOMBRELARGO, 
    CASE WHEN INVENTARIO.TIENEMOVIMIENTO <> 0 THEN INVENTARIO.TIPO ELSE '' END TIPOE, 
    INVENTARIO.UNIDAD, 
    INVENTARIO.CODIGOCUBS,
    INVENTARIO.ESTADOS,
    INVENTARIO.REFERENCIA
FROM  INVENTARIO 
WHERE INVENTARIO.COMPANIA = s$compania$s
    AND INVENTARIO.CODIGOELEMENTO BETWEEN 's$elementoInicial$s' AND 's$elementoFinal$s'
ORDER BY INVENTARIO.COMPANIA, 
        s$ordenar$s]') CONSULTA, 10 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);