SELECT ALMACENCONTABILIDAD.TIPOMOVIMIENTO,
  TIPOMOVIMIENTO.NOMBRE,
  ALMACENCONTABILIDAD.CUENTADEBITO,
  ALMACENCONTABILIDAD.CUENTACREDITO,
  ALMACENCONTABILIDAD.ANO,
  ALMACENCONTABILIDAD.COMPANIA,
  ALMACENCONTABILIDAD.CODIGOELEMENTO
FROM ALMACENCONTABILIDAD
  INNER JOIN TIPOMOVIMIENTO
     ON ALMACENCONTABILIDAD.COMPANIA               = TIPOMOVIMIENTO.COMPANIA
    AND ALMACENCONTABILIDAD.TIPOMOVIMIENTO         = TIPOMOVIMIENTO.CODIGO
WHERE ALMACENCONTABILIDAD.COMPANIA      = s$compania$s
  AND ALMACENCONTABILIDAD.ANO                    = s$anio$s
AND (ALMACENCONTABILIDAD.CUENTADEBITO  IS NOT NULL
 OR  ALMACENCONTABILIDAD.CUENTACREDITO IS NOT NULL)
  AND ALMACENCONTABILIDAD.CODIGOELEMENTO         = '$P!{PR_CODIGOELEMENTO}'
   
ORDER BY ALMACENCONTABILIDAD.COMPANIA,
  ALMACENCONTABILIDAD.CODIGOELEMENTO,
  ALMACENCONTABILIDAD.TIPOMOVIMIENTO,
  ALMACENCONTABILIDAD.ANO
