SELECT 
  ELEMENTO,
  PLACA,
  SERIE,
  TIPOMOVIMIENTO.NOMBRE TIPOMOVIMIENTO,
  NVL(MOVIMIENTOF,MOVIMIENTOI) MOVIMIENTO
FROM 
  DEVOLUTIVO LEFT JOIN TIPOMOVIMIENTO 
  ON DEVOLUTIVO.COMPANIA= TIPOMOVIMIENTO.COMPANIA
  AND NVL(TIPOMOVIMIENTOF,TIPOMOVIMIENTOI)=TIPOMOVIMIENTO.CODIGO
WHERE DEVOLUTIVO.COMPANIA=s$compania$s
  AND DEVOLUTIVO.ELEMENTO BETWEEN 's$desde$s' AND 's$hasta$s' 
  AND DEVOLUTIVO.PLACAANULADA NOT IN(0)
