  SELECT  DEVOLUTIVO.COMPANIA, 
        DEVOLUTIVO.ELEMENTO, 
        DEVOLUTIVO.SERIE, 
        DEVOLUTIVO.ESTADO, 
        DEVOLUTIVO.SERIEDEVOLUTIVO, 
        DEVOLUTIVO.DEPENDENCIA, 
        DEVOLUTIVO.RESPONSABLE, 
        DEVOLUTIVO.VALOR, 
        INVENTARIO.NOMBRELARGO AS NOMBRE_LARGO, 
        INVENTARIO.CODIGOELEMENTO, 
        DEPENDENCIA.NOMBRE AS NOMBREDEPENDENCIA, 
        TERCERO.NOMBRE AS NOMBRERESPONSABLE, 
        INVENTARIO.UNIDAD, 
        DEVOLUTIVO.VALOR AS TVALOR, 
        UNIDAD.NOMBRE AS NOMBREUNIDAD, 
        ESTADODEVOLUTIVO.DESCRIPCION, 
        INVENTARIO.NOMBRELARGO || ' ' || 
        CASE(NVL(DEVOLUTIVO.MARCA,' ')) 
          WHEN ' ' 
            THEN ' ' 
        ELSE 'Marca: ' || DEVOLUTIVO.MARCA || ' ' ||  TO_CHAR(DEVOLUTIVO.DESCRIPCION) END || ' ' || 
        CASE(NVL(D_MOVIMIENTO.ESCRITURA,' '))
          WHEN ' ' 
            THEN ''
        ELSE 'Escritura: ' || D_MOVIMIENTO.ESCRITURA     END || ' ' || 
    
        CASE(NVL(D_MOVIMIENTO.NUMEROCATASTRAL ,' '))
          WHEN ' '
            THEN ' '
        ELSE 'Catastro: ' || D_MOVIMIENTO.NUMEROCATASTRAL END || ' ' || 
        CASE(NVL(D_MOVIMIENTO.MATINMOBILIARIA ,' '))
          WHEN ' '
          THEN ' '
        ELSE 'Matricula: ' || D_MOVIMIENTO.MATINMOBILIARIA END || ' ' || 
        CASE(NVL(D_MOVIMIENTO.COD_CHIP,' '))
          WHEN ' '
          THEN ''
        ELSE 'Chip: ' || D_MOVIMIENTO.COD_CHIP END || ' ' || 
        CASE(NVL(DEVOLUTIVO.SERIE,'0'))
          WHEN 0
          THEN ''
        ELSE 'Serie: ' || DEVOLUTIVO.SERIE END || ' ' || 
        CASE(NVL(D_MOVIMIENTO.AREA,' '))
          WHEN ' '
          THEN ''
        ELSE 'Area: ' || D_MOVIMIENTO.AREA END AS  NOMBRELARGO, 
        LPAD(DEVOLUTIVO.ELEMENTO,3) AS AGRUPACION, 
        TO_CHAR(DEVOLUTIVO.FECHAENTRADA,'DD/MM/YYYY') FECHAENTRADA, 
        INVENTARIO.UNIDAD, 
        DEVOLUTIVO.SERIEANTERIOR, 
        D_MOVIMIENTO.ESCRITURA, 
        D_MOVIMIENTO.NUMEROCATASTRAL, 
        D_MOVIMIENTO.MATINMOBILIARIA, 
        D_MOVIMIENTO.AREA, 
        D_MOVIMIENTO.COD_CHIP, 
        TO_CHAR(DEVOLUTIVO.FECHASALIDASERVICIO,'DD/MM/YYYY') FECHASALIDASERVICIO, 
        LPAD(INVENTARIO.NOMBRELARGO || ' ' || 
        CASE(NVL(DEVOLUTIVO.MARCA,' ')) 
          WHEN ' '
          THEN ''
        ELSE 'Marca: ' || DEVOLUTIVO.MARCA || ' ' || TO_CHAR(DEVOLUTIVO.DESCRIPCION) END ,255) AS NOMB_LAR,
          DEPENDENCIA_RESPONSABLE.SUPERVISOR,
  DEPENDENCIA_RESPONSABLE.SUCURSAL_SUPERVISOR,
  TERCERO_SUP.NOMBRE NOMBRE_SUPERVISOR
FROM COMPANIA 
  INNER JOIN DEVOLUTIVO 
     ON COMPANIA.CODIGO = DEVOLUTIVO.COMPANIA
    LEFT JOIN RESPONSABLE 
      ON DEVOLUTIVO.COMPANIA = RESPONSABLE.COMPANIA 
      AND DEVOLUTIVO.RESPONSABLE = RESPONSABLE.CEDULA 
     AND DEVOLUTIVO.SUCURSAL_RESPONSABLE = RESPONSABLE.SUCURSAL
    LEFT JOIN INVENTARIO 
      ON DEVOLUTIVO.COMPANIA = INVENTARIO.COMPANIA 
      AND DEVOLUTIVO.ELEMENTO = INVENTARIO.CODIGOELEMENTO 
    LEFT JOIN DEPENDENCIA 
      ON DEVOLUTIVO.COMPANIA = DEPENDENCIA.COMPANIA 
      AND DEVOLUTIVO.DEPENDENCIA = DEPENDENCIA.CODIGO 
    LEFT JOIN UNIDAD 
      ON INVENTARIO.UNIDAD = UNIDAD.UNIDAD 
    LEFT JOIN ESTADODEVOLUTIVO 
      ON DEVOLUTIVO.ESTADO = ESTADODEVOLUTIVO.ESTADO    
    LEFT JOIN D_MOVIMIENTO 
      ON DEVOLUTIVO.COMPANIA = D_MOVIMIENTO.COMPANIA 
      AND DEVOLUTIVO.SERIE = D_MOVIMIENTO.SERIE 
      AND DEVOLUTIVO.ELEMENTO = D_MOVIMIENTO.ELEMENTO 
      AND DEVOLUTIVO.TIPOMOVIMIENTOI = D_MOVIMIENTO.TIPOMOVIMIENTO
     LEFT JOIN V_ENTDEVOLUTIVO 
      ON D_MOVIMIENTO.COMPANIA = V_ENTDEVOLUTIVO.COMPANIA 
      AND D_MOVIMIENTO.TIPOMOVIMIENTO = V_ENTDEVOLUTIVO.TIPOMOVIMIENTO 
     LEFT JOIN TERCERO 
     ON RESPONSABLE.COMPANIA = TERCERO.COMPANIA
      AND RESPONSABLE.CEDULA = TERCERO.NIT
      AND RESPONSABLE.SUCURSAL = TERCERO.SUCURSAL
       LEFT JOIN DEPENDENCIA_RESPONSABLE  
 ON DEVOLUTIVO.COMPANIA             = DEPENDENCIA_RESPONSABLE.COMPANIA
AND DEVOLUTIVO.DEPENDENCIA          = DEPENDENCIA_RESPONSABLE.DEPENDENCIA
AND DEVOLUTIVO.RESPONSABLE          = DEPENDENCIA_RESPONSABLE.RESPONSABLE
AND DEVOLUTIVO.SUCURSAL_RESPONSABLE = DEPENDENCIA_RESPONSABLE.SUCURSAL
LEFT JOIN TERCERO TERCERO_SUP
    ON  DEPENDENCIA_RESPONSABLE.COMPANIA            = TERCERO_SUP.COMPANIA         
    AND DEPENDENCIA_RESPONSABLE.SUPERVISOR          = TERCERO_SUP.NIT 
    AND DEPENDENCIA_RESPONSABLE.SUCURSAL_SUPERVISOR = TERCERO_SUP.SUCURSAL 
WHERE DEVOLUTIVO.COMPANIA = s$compania$s
  AND DEVOLUTIVO.DEPENDENCIA BETWEEN s$dependencia$s AND s$dependenciafinal$s  
  AND DEVOLUTIVO.PLACAANULADA = 0 
  AND DEVOLUTIVO.FECHAADQUISICION BETWEEN s$fechainicial$s AND s$fechafinal$s
ORDER BY  DEVOLUTIVO.ELEMENTO, 
          DEVOLUTIVO.SERIE