SELECT DEVOLUTIVO.ELEMENTO, 
      DEVOLUTIVO.SERIE, 
      DEVOLUTIVO.DEPENDENCIA, 
      DEVOLUTIVO.RESPONSABLE, 
      NVL(DEPRECIACION.VALORTOTAL,DEVOLUTIVO.VALOR) VALOR, 
      DEPENDENCIA.NOMBRE, 
      NVL(DEPRECIACION.VLRLIBROS,0)  DEP_LIBROS, 
      DEVOLUTIVO.ELEMENTO CODIGOELEMENTO, 
      TERCERO.NOMBRE NOMBRE_RESPONSABLE, 
      INVENTARIO.NOMBRELARGO|| ' '||DEVOLUTIVO.DESCRIPCION || CASE WHEN TRIM(DEVOLUTIVO.MARCA) IS NULL THEN ' ' ELSE 'Marca: '||DEVOLUTIVO.MARCA END || CASE WHEN TRIM(SERIEDEVOLUTIVO) IS NULL THEN ' ' ELSE SERIEDEVOLUTIVO END AS NOMBRE_DESCRIPCION, 
      DEVOLUTIVO.VALOR VLR
FROM DEVOLUTIVO
  LEFT JOIN RESPONSABLE ON DEVOLUTIVO.COMPANIA = RESPONSABLE.COMPANIA
    AND DEVOLUTIVO.RESPONSABLE = RESPONSABLE.CEDULA
    AND DEVOLUTIVO.SUCURSAL_RESPONSABLE = RESPONSABLE.SUCURSAL
  INNER JOIN TERCERO ON RESPONSABLE.COMPANIA = TERCERO.COMPANIA
    AND RESPONSABLE.CEDULA = TERCERO.NIT
    AND RESPONSABLE.SUCURSAL = TERCERO.SUCURSAL
  LEFT JOIN INVENTARIO ON DEVOLUTIVO.COMPANIA = INVENTARIO.COMPANIA
    AND DEVOLUTIVO.ELEMENTO = INVENTARIO.CODIGOELEMENTO
  LEFT JOIN DEPENDENCIA ON DEVOLUTIVO.COMPANIA = DEPENDENCIA.COMPANIA
    AND DEVOLUTIVO.DEPENDENCIA = DEPENDENCIA.CODIGO
 LEFT JOIN (SELECT  DEPRECIAR.COMPANIA,
        DEPRECIAR.ELEMENTO,
        DEPRECIAR.SERIE,
        CASE WHEN PCK_SYSMAN_UTL.FC_PAR(DEPRECIAR.COMPANIA,'MANEJA NIIF EN ALMACEN',10,DEPRECIAR.PERIODO)='SI'
              THEN DEPRECIAR.NIIF_VLRLIBROS
              ELSE DEPRECIAR.VLRLIBROS
              END VLRLIBROS,
       CASE WHEN PCK_SYSMAN_UTL.FC_PAR(DEPRECIAR.COMPANIA,'MANEJA NIIF EN ALMACEN',10,DEPRECIAR.PERIODO)='SI'
              THEN DEPRECIAR.NIIF_VLRELEMENTO
              ELSE DEPRECIAR.VLRELEMENTO
              END VALORTOTAL              
                  FROM DEPRECIAR INNER JOIN 
                    (SELECT COMPANIA, ELEMENTO, SERIE, MAX(PERIODO) PERIODO
                     FROM DEPRECIAR
                     WHERE COMPANIA =s$compania$s
                         AND DEPRECIAR.PERIODO<= TRUNC(SYSDATE) 
                       GROUP BY COMPANIA, ELEMENTO, SERIE 
                     ) ULTIMO
                     ON DEPRECIAR.COMPANIA = ULTIMO.COMPANIA              
                    AND DEPRECIAR.ELEMENTO = ULTIMO.ELEMENTO
                    AND DEPRECIAR.SERIE = ULTIMO.SERIE
                    AND DEPRECIAR.PERIODO = ULTIMO.PERIODO
                  WHERE DEPRECIAR.COMPANIA=s$compania$s
                    AND DEPRECIAR.PERIODO<= TRUNC(SYSDATE) 
                  )DEPRECIACION 
   ON   DEVOLUTIVO.COMPANIA =DEPRECIACION.COMPANIA
   AND  DEVOLUTIVO.ELEMENTO =DEPRECIACION.ELEMENTO
   AND  DEVOLUTIVO.SERIE    =DEPRECIACION.SERIE
WHERE DEVOLUTIVO.COMPANIA = s$compania$s
AND DEVOLUTIVO.DEPENDENCIA BETWEEN 's$depInicial$s' AND 's$depFinal$s'
AND DEPENDENCIA.CLASE_BODEGA NOT IN (40, 50, 90) 
AND DEVOLUTIVO.PLACAANULADA=0
