SELECT 	DEVOLUTIVO.COMPANIA, 
		SUM(DEVOLUTIVO.VALOR)  GRUPO, 
		ESTADODEVOLUTIVO.DESCRIPCION ESTADODEVOLUTIVODESCRIPCION, 
		DEVOLUTIVO.DEPENDENCIA,
    DEPENDENCIA.NOMBRE 
FROM DEVOLUTIVO 
	LEFT JOIN INVENTARIO 
		ON  DEVOLUTIVO.COMPANIA = INVENTARIO.COMPANIA 
		AND DEVOLUTIVO.ELEMENTO = INVENTARIO.CODIGOELEMENTO
  LEFT JOIN TIPOMOVIMIENTO 
		ON  DEVOLUTIVO.COMPANIA 		    = TIPOMOVIMIENTO.COMPANIA 
		AND DEVOLUTIVO.TIPOMOVIMIENTOF  = TIPOMOVIMIENTO.CODIGO
  LEFT JOIN ESTADODEVOLUTIVO 
		ON DEVOLUTIVO.ESTADO = ESTADODEVOLUTIVO.ESTADO 
	LEFT JOIN DEPENDENCIA 
		ON  DEVOLUTIVO.COMPANIA    = DEPENDENCIA.COMPANIA 
		AND DEVOLUTIVO.DEPENDENCIA = DEPENDENCIA.CODIGO 
	LEFT JOIN RESPONSABLE 
		ON  DEVOLUTIVO.COMPANIA    = RESPONSABLE.COMPANIA 
		AND DEVOLUTIVO.RESPONSABLE = RESPONSABLE.CEDULA
		AND DEVOLUTIVO.SUCURSAL_RESPONSABLE = RESPONSABLE.SUCURSAL
	     INNER JOIN TERCERO 
	      ON  RESPONSABLE.COMPANIA    = TERCERO.COMPANIA 
	      AND RESPONSABLE.CEDULA      = TERCERO.NIT
	      AND RESPONSABLE.SUCURSAL    = TERCERO.SUCURSAL
WHERE DEVOLUTIVO.COMPANIA = s$compania$s 
 AND DEVOLUTIVO.ELEMENTO BETWEEN s$elementodesde$s 
                            AND s$elementoHasta$s 
  AND TIPOMOVIMIENTO.CONCEPTO = 'CM' 
  AND TIPOMOVIMIENTO.CLASE 	  = 'S' 
  AND INVENTARIO.TIPO 	      = 'D' 
GROUP BY  DEVOLUTIVO.COMPANIA, 
          ESTADODEVOLUTIVO.DESCRIPCION, 
          DEVOLUTIVO.DEPENDENCIA, 
          DEPENDENCIA.NOMBRE
