MERGE INTO CONSULTAS FIN USING (SELECT '000488IInvIndivDevolu' INFORME ,TO_CLOB(q'[SELECT INVENTARIO.CODIGOELEMENTO, 
       INVENTARIO.NOMBRELARGO, 
       DEPENDENCIA.NOMBRE NOMBREDEPENDENCIA, 
       TERCERO.NOMBRE NOMRESPONSABLE,
       DEVOLUTIVO.DEPENDENCIA, 
       INVENTARIO.UNIDAD, 
       DEVOLUTIVO.VALOR AS VLR, 
       UNIDAD.NOMBRE, 
       DEVOLUTIVO.ELEMENTO, 
       TO_CHAR(DEVOLUTIVO.FECHAULTMOV,'DD/MM/YYYY') FECHAULTMOV, 
       DEVOLUTIVO.SERIE, 
       DEVOLUTIVO.DESCRIPCION,
       DEVOLUTIVO.MOVIMIENTOF,
       DEVOLUTIVO.TIPOMOVIMIENTOF,
       DEVOLUTIVO.RESPONSABLE, 
       DEVOLUTIVO.MARCA,
       DEVOLUTIVO.SERIEDEVOLUTIVO, 
       ESTADODEVOLUTIVO.DESCRIPCION AS NOMESTADO,
       INVENTARIO.NOMBRELARGO || ' ' || DEVOLUTIVO.DESCRIPCION || ' ' || 
       CASE  WHEN TRIM(NVL(DEVOLUTIVO.MARCA,'')) IS NOT NULL THEN 'MARCA: ' || DEVOLUTIVO.MARCA || ' '
        ELSE ''
       END || 
       CASE  WHEN TRIM(NVL(DEVOLUTIVO.SERIEDEVOLUTIVO,'')) IS NOT NULL THEN 'SERIE: ' || DEVOLUTIVO.SERIEDEVOLUTIVO || ' ' 
        ELSE ''
       END DESCRIPCIONELEMENTO,
           DEPENDENCIA_RESPONSABLE.SUPERVISOR,
       DEPENDENCIA_RESPONSABLE.SUCURSAL_SUPERVISOR,
       TERCERO_SUP.NOMBRE NOMBRE_SUPERVISOR
FROM DEVOLUTIVO 
    LEFT JOIN RESPONSABLE ON DEVOLUTIVO.COMPANIA = RESPONSABLE.COMPANIA 
          AND DEVOLUTIVO.RESPONSABLE = RESPONSABLE.CEDULA
	  AND DEVOLUTIVO.SUCURSAL_RESPONSABLE = RESPONSABLE.SUCURSAL 
    LEFT JOIN INVENTARIO ON DEVOLUTIVO.COMPANIA = INVENTARIO.COMPANIA AND DEVOLUTIVO.ELEMENTO = INVENTARIO.CODIGOELEMENTO 
    LEFT JOIN DEPENDENCIA ON DEVOLUTIVO.COMPANIA = DEPENDENCIA.COMPANIA AND DEVOLUTIVO.DEPENDENCIA = DEPENDENCIA.CODIGO 
    LEFT JOIN UNIDAD ON INVENTARIO.UNIDAD = UNIDAD.UNIDAD 
    LEFT JOIN D_MOVIMIENTO ON DEVOLUTIVO.COMPANIA = D_MOVIMIENTO.COMPANIA AND DEVOLUTIVO.ELEMENTO = D_MOVIMIENTO.ELEMENTO 
        AND DEVOLUTIVO.SERIE = D_MOVIMIENTO.SERIE AND DEVOLUTIVO.ORIGEN = D_MOVIMIENTO.TIPOMOVIMIENTO 
        AND DEVOLUTIVO.NUMEROORIGEN = D_MOVIMIENTO.MOVIMIENTO         
    LEFT JOIN ESTADODEVOLUTIVO ON DEVOLUTIVO.ESTADO = ESTADODEVOLUTIVO.ESTADO
    LEFT JOIN TERCERO ON DEVOLUTIVO.COMPANIA = TERCERO.COMPANIA AND DEVOLUTIVO.RESPONSABLE = TERCERO.NIT AND DEVOLUTIVO.SUCURSAL_RESPONSABLE = TERCERO.SUCURSAL
       LEFT JOIN DEPENDENCIA_RESPONSABLE  
 ON DEVOLUTIVO.COMPANIA             = DEPENDENCIA_RESPONSABLE.COMPANIA
AND DEVOLUTIVO.DEPENDENCIA          = DEPENDENCIA_RESPONSABLE.DEPENDENCIA
AND DEVOLUTIVO.RESPONSABLE          = DEPENDENCIA_RESPONSABLE.RESPONSABLE
AND DEVOLUTIVO.SUCURSAL_RESPONSABLE = DEPENDENCIA_RESPONSABLE.SUCURSAL
LEFT JOIN TERCERO TERCERO_SUP
    ON  DEPENDENCIA_RESPONSABLE.COMPANIA            = TERCERO_SUP.COMPANIA         
    AND DEPENDENCIA_RESPONSABLE.SUPERVISOR          = TERCERO_SUP.NIT 
    AND DEPENDENCIA_RESPONSABLE.SUCURSAL_SUPERVISOR = TERCERO_SUP.SUCURSAL 
WHERE INVENTARIO.COMPANIA = s$compania$s
  AND INVENTARIO.CODIGOELEMENTO BETWEEN 's$elementoInicial$s' AND 's$elementoFinal$s' 
  AND DEVOLUTIVO.BODEGA NOT ]') || TO_CLOB(q'[IN (SELECT CODIGO FROM CLASE_BODEGA WHERE CODIGO IN(20,40,50,60,90)) 
  AND DEVOLUTIVO.PLACAANULADA IN(0)]') CONSULTA, 10 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);