WITH C_HKARDEXENTDEVINSER AS (
    SELECT  D_MOVIMIENTO.COMPANIA,
            TIPOMOVIMIENTO.CODIGO AS TIPOMOVIMIENTO, 
            D_MOVIMIENTO.SERIE  AS SERIE, 
            D_MOVIMIENTO.ELEMENTO AS ELEMENTO, 
            D_MOVIMIENTO.ESTADO AS ESTADO, 
            D_MOVIMIENTO.FECHA  AS FECHA, 
            D_MOVIMIENTO.HORA  AS HORA, 
            D_MOVIMIENTO.MOVIMIENTO  AS MOVIMIENTO1, 
            D_MOVIMIENTO.CANTIDAD AS CANTIDAD, 
            'E' AS CLASE, 
            CASE WHEN DEPENDENCIA.NOMBRE IS NULL THEN DEPENDENCIA_1.NOMBRE ELSE DEPENDENCIA.NOMBRE END AS DEPENDENCIA,
            CASE WHEN TERCERO.NOMBRE     IS NULL THEN RESPONSABLE_1.NOMBRE ELSE TERCERO.NOMBRE END  AS RESPONSABLE
    FROM TIPOMOVIMIENTO 
      INNER JOIN D_MOVIMIENTO 
        ON TIPOMOVIMIENTO.COMPANIA             = D_MOVIMIENTO.COMPANIA 
        AND TIPOMOVIMIENTO.CODIGO              = D_MOVIMIENTO.TIPOMOVIMIENTO 
      INNER JOIN V_MOVIMIENTO 
        ON D_MOVIMIENTO.COMPANIA               = V_MOVIMIENTO.COMPANIA 
        AND D_MOVIMIENTO.TIPOMOVIMIENTO        = V_MOVIMIENTO.TIPOMOVIMIENTO 
        AND D_MOVIMIENTO.MOVIMIENTO            = V_MOVIMIENTO.NUMERO 
      LEFT JOIN V_ENTDEVOLUTIVO 
        ON D_MOVIMIENTO.COMPANIA               = V_ENTDEVOLUTIVO.COMPANIA 
        AND D_MOVIMIENTO.TIPOMOVIMIENTO        = V_ENTDEVOLUTIVO.TIPOMOVIMIENTO 
        AND D_MOVIMIENTO.MOVIMIENTO            = V_ENTDEVOLUTIVO.NUMERO 
      LEFT JOIN DEPENDENCIA  DEPENDENCIA_1 
        ON V_ENTDEVOLUTIVO.COMPANIA            = DEPENDENCIA_1.COMPANIA 
        AND V_ENTDEVOLUTIVO.DEPENDENCIA_ORIGEN = DEPENDENCIA_1.CODIGO 
      LEFT JOIN DEPENDENCIA 
        ON V_MOVIMIENTO.COMPANIA               = DEPENDENCIA.COMPANIA 
        AND V_MOVIMIENTO.DEPENDENCIA_ORIGEN    = DEPENDENCIA.CODIGO 
      LEFT JOIN TERCERO  RESPONSABLE_1 
        ON V_ENTDEVOLUTIVO.COMPANIA            = RESPONSABLE_1.COMPANIA 
        AND V_ENTDEVOLUTIVO.RESPONSABLE_ORIGEN = RESPONSABLE_1.NIT
        AND V_ENTDEVOLUTIVO.SUCURSAL_RESORIGEN = RESPONSABLE_1.SUCURSAL
      LEFT JOIN TERCERO 
        ON V_MOVIMIENTO.COMPANIA               = TERCERO.COMPANIA 
        AND V_MOVIMIENTO.RESPONSABLE_ORIGEN    = TERCERO.NIT
        AND V_MOVIMIENTO.SUCURSAL_RESORIGEN    = TERCERO.SUCURSAL
    WHERE TIPOMOVIMIENTO.COMPANIA = s$compania$s   
      AND D_MOVIMIENTO.FECHA BETWEEN s$fechaInicial$s AND s$fechaFinal$s 
      AND D_MOVIMIENTO.SERIE IS NOT NULL
      AND TIPOMOVIMIENTO.CONCEPTO IN ('DS','DT') 
      AND TIPOMOVIMIENTO.TIPOELEMENTO = s$tipo$s
      AND D_MOVIMIENTO.IND_REG  NOT IN (0)),
C_HKARDEXSALDEVINSER AS (
    SELECT    TIPOMOVIMIENTO.COMPANIA, 
              TIPOMOVIMIENTO.CONCEPTO, 
              'S' AS CLASE, 
              TIPOMOVIMIENTO.CODIGO AS TIPOMOVIMIENTO, 
              D_MOVIMIENTO.DESCARGO AS MOVIMIENTO, 
              D_MOVIMIENTO.ELEMENTO AS ELEM, 
              D_MOVIMIENTO.SERIE, 
              D_MOVIMIENTO.CANTIDAD, 
              D_MOVIMIENTO.FECHA, 
              D_MOVIMIENTO.HORA, 
              DEPENDENCIA.NOMBRE AS DEPENDENCIA, 
              TERCERO.NOMBRE AS RESPONSABLE
      FROM TIPOMOVIMIENTO 
        INNER JOIN D_MOVIMIENTO 
          ON TIPOMOVIMIENTO.COMPANIA              = D_MOVIMIENTO.COMPANIA 
          AND TIPOMOVIMIENTO.CODIGO               = D_MOVIMIENTO.TIPOMOVIMIENTO 
        LEFT JOIN V_DESCARGOBODEGA 
          ON D_MOVIMIENTO.COMPANIA                = V_DESCARGOBODEGA.COMPANIA 
          AND D_MOVIMIENTO.TIPOMOVIMIENTO         = V_DESCARGOBODEGA.TIPOMOVIMIENTO 
          AND D_MOVIMIENTO.MOVIMIENTO             = V_DESCARGOBODEGA.NUMERO 
        LEFT JOIN DEPENDENCIA 
          ON V_DESCARGOBODEGA.COMPANIA            = DEPENDENCIA.COMPANIA 
          AND V_DESCARGOBODEGA.DEPENDENCIA_ORIGEN = DEPENDENCIA.CODIGO 
        LEFT JOIN TERCERO 
          ON V_DESCARGOBODEGA.COMPANIA            = TERCERO.COMPANIA 
          AND V_DESCARGOBODEGA.RESPONSABLE_ORIGEN = TERCERO.NIT
          AND V_DESCARGOBODEGA.SUCURSAL_RESORIGEN = TERCERO.SUCURSAL
      WHERE TIPOMOVIMIENTO.COMPANIA = s$compania$s 
        AND TIPOMOVIMIENTO.CONCEPTO ='DT' 
        AND D_MOVIMIENTO.SERIE NOT IN (0) 
        AND D_MOVIMIENTO.FECHA BETWEEN s$fechaInicial$s AND s$fechaFinal$s 
        AND TIPOMOVIMIENTO.TIPOELEMENTO = s$tipo$s 
        AND TIPOMOVIMIENTO.CLASE ='D' 
        AND D_MOVIMIENTO.IND_REG NOT IN (0))  ,
        SALDOSANTERIORES AS (
        SELECT   COMPANIA,       
                 ELEMENTO,
                 FECHA,
                 TO_CHAR(HORA,'HH:MI:SS')HORA,
                 VALORUNITARIO AS VLRUNITARIOANT,
                 VLRUNITARIOPROM,
                 SALDOKARDEX AS CANTIDAD,
                 SALDOKARDEX * VLRUNITARIOPROM TOTALANTERIOR,
                 VALORSALDO,
                 SERIE
          FROM  V_ULTIMOMOVIMIENTO_ALM
          WHERE V_ULTIMOMOVIMIENTO_ALM.COMPANIA = s$compania$s
            AND V_ULTIMOMOVIMIENTO_ALM.ELEMENTO BETWEEN s$elementoInicial$s AND s$elementoFinal$s),
         TOTALES AS (SELECT   LPAD(ELEMENTO,3) AS AGRUPACIONTOTALES,
                        SUM(CANTIDAD) AS CANTIDAD1, 
                        SUM(VALORUNITARIO) AS VALORUNITARIO, 
                        SUM(VALORTOTAL) AS VALORTOTAL1 
                FROM ELEMENTOBODEGA 
                WHERE COMPANIA          = s$compania$s
                  AND LPAD(ELEMENTO,3) BETWEEN LPAD(s$elementoInicial$s,3) AND LPAD(s$elementoFinal$s,3)
                  AND FECHAENTRADA     <= s$fechaFinal$s  
                  AND FECHACANCELACION <= s$fechaFinal$s
                  GROUP BY LPAD(ELEMENTO,3)
)   
            
SELECT  DISTINCT CASE WHEN C_HKARDEXENTDEVINSER.CANTIDAD IS NOT NULL THEN C_HKARDEXENTDEVINSER.CANTIDAD ELSE 0 END  AS ENTRADAS, 
        CASE WHEN C_HKARDEXSALDEVINSER.CANTIDAD IS NOT NULL THEN C_HKARDEXSALDEVINSER.CANTIDAD ELSE 0 END  AS SALIDAS, 
        CASE WHEN C_HKARDEXENTDEVINSER.CANTIDAD * DEVOLUTIVO.VALOR IS NULL THEN 0 ELSE C_HKARDEXENTDEVINSER.CANTIDAD * DEVOLUTIVO.VALOR END  AS VLRENTRADAS, 
        CASE WHEN C_HKARDEXSALDEVINSER.CANTIDAD * DEVOLUTIVO_1.VALOR IS NULL THEN 0 ELSE C_HKARDEXSALDEVINSER.CANTIDAD * DEVOLUTIVO_1.VALOR END  AS VLRSALIDAS, 
        CASE WHEN C_HKARDEXENTDEVINSER.RESPONSABLE IS NULL THEN C_HKARDEXSALDEVINSER.RESPONSABLE ELSE C_HKARDEXENTDEVINSER.RESPONSABLE END AS TERCERO, 
        CASE WHEN C_HKARDEXENTDEVINSER.DEPENDENCIA IS NULL THEN C_HKARDEXSALDEVINSER.DEPENDENCIA ELSE C_HKARDEXENTDEVINSER.DEPENDENCIA END AS DEPENDENCIA1, 
        CASE WHEN C_HKARDEXENTDEVINSER.FECHA IS NULL THEN C_HKARDEXSALDEVINSER.FECHA ELSE C_HKARDEXENTDEVINSER.FECHA END  AS FECHA, 
        CASE WHEN C_HKARDEXENTDEVINSER.HORA IS NULL THEN C_HKARDEXSALDEVINSER.HORA ELSE C_HKARDEXENTDEVINSER.HORA END  AS HORA, 
        TIPOMOVIMIENTO.CODIGO AS TIPOMOV, 
        CASE WHEN C_HKARDEXENTDEVINSER.MOVIMIENTO1 IS NULL THEN C_HKARDEXSALDEVINSER.MOVIMIENTO ELSE C_HKARDEXENTDEVINSER.MOVIMIENTO1 END AS MOVIMIENTO,
        CASE WHEN C_HKARDEXENTDEVINSER.ELEMENTO IS NULL THEN C_HKARDEXSALDEVINSER.ELEM ELSE C_HKARDEXENTDEVINSER.ELEMENTO END AS COD_ELEMENTO, 
        CASE WHEN C_HKARDEXENTDEVINSER.SERIE IS NULL THEN C_HKARDEXSALDEVINSER.SERIE ELSE C_HKARDEXENTDEVINSER.SERIE END  AS SERIE, 
        CASE WHEN INVENTARIO.NOMBRELARGO IS NULL THEN INVENTARIO_1.NOMBRELARGO ELSE INVENTARIO.NOMBRELARGO END AS NOMBRELARGO, 
        CASE WHEN INVENTARIO.UNIDAD IS NULL THEN INVENTARIO_1.UNIDAD ELSE INVENTARIO.UNIDAD END AS UNIDAD, 
        CASE WHEN CASE WHEN TRIM(DEVOLUTIVO.MARCA) IS NULL THEN TRIM(DEVOLUTIVO_1.MARCA) ELSE TRIM(DEVOLUTIVO.MARCA) END ='' THEN NULL ELSE CASE WHEN DEVOLUTIVO.MARCA IS NULL THEN DEVOLUTIVO_1.MARCA ELSE DEVOLUTIVO.MARCA END END  AS MARCA, 
        CASE WHEN DEVOLUTIVO.DESCRIPCION IS NULL THEN DEVOLUTIVO_1.DESCRIPCION ELSE DEVOLUTIVO.DESCRIPCION END  AS DESCRIPCION, 
        CASE WHEN CASE WHEN TRIM(DEVOLUTIVO.SERIEDEVOLUTIVO) IS NULL THEN TRIM(DEVOLUTIVO_1.SERIEDEVOLUTIVO) ELSE TRIM(DEVOLUTIVO.SERIEDEVOLUTIVO) END ='' THEN NULL ELSE CASE WHEN TRIM(DEVOLUTIVO.SERIEDEVOLUTIVO) IS NULL THEN TRIM(DEVOLUTIVO_1.SERIEDEVOLUTIVO) ELSE TRIM(DEVOLUTIVO.SERIEDEVOLUTIVO) END END AS SERIEDEVOLUTIVO, 
        CASE WHEN CASE WHEN C_HKARDEXENTDEVINSER.CANTIDAD IS NOT NULL THEN C_HKARDEXENTDEVINSER.CANTIDAD ELSE 0 END <> 0 THEN CASE WHEN C_HKARDEXENTDEVINSER.CANTIDAD IS NOT NULL THEN C_HKARDEXENTDEVINSER.CANTIDAD ELSE 0 END ELSE 0 END  AS SALDOKARDEX, 
        CASE WHEN CASE WHEN C_HKARDEXENTDEVINSER.CANTIDAD IS NOT NULL THEN C_HKARDEXENTDEVINSER.CANTIDAD ELSE 0 END <>0 THEN DEVOLUTIVO.VALOR ELSE 0 END AS VLRSALDOKARDEX, 
        CASE WHEN DEVOLUTIVO.VALOR IS NULL THEN DEVOLUTIVO_1.VALOR ELSE DEVOLUTIVO.VALOR END AS VLRUNITARIOPROM, 
        CASE WHEN C_HKARDEXENTDEVINSER.ESTADO IS NULL THEN 'M' ELSE C_HKARDEXENTDEVINSER.ESTADO END AS ESTADO, 
        CASE WHEN LPAD(C_HKARDEXENTDEVINSER.ELEMENTO,3) IS NULL THEN LPAD(C_HKARDEXSALDEVINSER.ELEM,3) ELSE LPAD(C_HKARDEXENTDEVINSER.ELEMENTO,3) END AS AGRUPACION, 
        LPAD( CASE WHEN C_HKARDEXENTDEVINSER.ELEMENTO IS NULL THEN C_HKARDEXSALDEVINSER.ELEM ELSE C_HKARDEXENTDEVINSER.ELEMENTO END,3) ||  CASE WHEN INVENTARIO.NOMBRELARGO IS NULL THEN INVENTARIO_1.NOMBRELARGO ELSE INVENTARIO.NOMBRELARGO END ||  CASE WHEN C_HKARDEXENTDEVINSER.SERIE IS NULL THEN C_HKARDEXSALDEVINSER.SERIE ELSE C_HKARDEXENTDEVINSER.SERIE END AS GRUPO, 
        DEVOLUTIVO.COMPANIA ,
        SALDOSANTERIORES.CANTIDAD,
        SALDOSANTERIORES.VLRUNITARIOANT,
        SALDOSANTERIORES.TOTALANTERIOR,
        TOTALES.CANTIDAD1,
        TOTALES.VALORTOTAL1,
        CASE WHEN INVENTARIO.MARCA IS NOT NULL  OR INVENTARIO.MARCA = ' '
          THEN 'Marca' ||  INVENTARIO.MARCA || ' ' 
          ELSE '' 
        END  || CASE WHEN INVENTARIO.DESCRIPCION IS NULL THEN  ' ' ELSE INVENTARIO.DESCRIPCION END || 
        CASE WHEN DEVOLUTIVO.SERIEDEVOLUTIVO IS NULL THEN '' 
           ELSE 'Serie' || DEVOLUTIVO.SERIEDEVOLUTIVO ||  CASE WHEN INVENTARIO.SERIE =0 THEN '' ELSE '' END
        END AS DETALLE,
	PCK_GENERALES.FC_NOMBREINVENTARIO(LPAD(  CASE WHEN C_HKARDEXENTDEVINSER.ELEMENTO IS NULL THEN C_HKARDEXSALDEVINSER.ELEM ELSE C_HKARDEXENTDEVINSER.ELEMENTO END,s$parametro$s) , s$compania$s , NULL) AS NOMBREINVENTARIO
FROM TIPOMOVIMIENTO 
   INNER JOIN C_HKARDEXENTDEVINSER 
    ON TIPOMOVIMIENTO.COMPANIA = C_HKARDEXENTDEVINSER.COMPANIA  
    AND TIPOMOVIMIENTO.CODIGO = C_HKARDEXENTDEVINSER.TIPOMOVIMIENTO 
  LEFT JOIN C_HKARDEXSALDEVINSER 
    ON TIPOMOVIMIENTO.COMPANIA = C_HKARDEXSALDEVINSER.COMPANIA 
    AND TIPOMOVIMIENTO.CODIGO = C_HKARDEXSALDEVINSER.TIPOMOVIMIENTO 
  LEFT JOIN DEVOLUTIVO 
    ON C_HKARDEXENTDEVINSER.ELEMENTO = DEVOLUTIVO.ELEMENTO 
    AND C_HKARDEXENTDEVINSER.SERIE = DEVOLUTIVO.SERIE 
  LEFT JOIN DEVOLUTIVO  DEVOLUTIVO_1 
    ON C_HKARDEXSALDEVINSER.ELEM = DEVOLUTIVO_1.ELEMENTO 
    AND C_HKARDEXSALDEVINSER.SERIE = DEVOLUTIVO_1.SERIE 
  LEFT JOIN INVENTARIO  INVENTARIO_1 
    ON DEVOLUTIVO_1.COMPANIA = INVENTARIO_1.COMPANIA 
    AND DEVOLUTIVO_1.ELEMENTO = INVENTARIO_1.CODIGOELEMENTO 
  LEFT JOIN INVENTARIO 
    ON DEVOLUTIVO.COMPANIA = INVENTARIO.COMPANIA 
    AND DEVOLUTIVO.ELEMENTO = INVENTARIO.CODIGOELEMENTO
  LEFT JOIN SALDOSANTERIORES
     ON DEVOLUTIVO.COMPANIA              = SALDOSANTERIORES.COMPANIA 
    AND DEVOLUTIVO.ELEMENTO              = SALDOSANTERIORES.ELEMENTO 
  LEFT JOIN TOTALES ON  LPAD(CASE WHEN C_HKARDEXENTDEVINSER.ELEMENTO IS NULL THEN C_HKARDEXSALDEVINSER.ELEM ELSE C_HKARDEXENTDEVINSER.ELEMENTO END ,3) = TOTALES.AGRUPACIONTOTALES 
WHERE CASE WHEN C_HKARDEXENTDEVINSER.MOVIMIENTO1 IS NULL THEN C_HKARDEXSALDEVINSER.MOVIMIENTO ELSE C_HKARDEXENTDEVINSER.MOVIMIENTO1 END IS NOT NULL 
AND CASE WHEN C_HKARDEXENTDEVINSER.ELEMENTO IS NULL THEN C_HKARDEXSALDEVINSER.ELEM ELSE C_HKARDEXENTDEVINSER.ELEMENTO END  BETWEEN s$elementoInicial$s AND s$elementoFinal$s
AND DEVOLUTIVO.COMPANIA = s$compania$s
ORDER BY CASE WHEN C_HKARDEXENTDEVINSER.FECHA IS NULL THEN C_HKARDEXSALDEVINSER.FECHA ELSE C_HKARDEXENTDEVINSER.FECHA END , 
CASE WHEN C_HKARDEXENTDEVINSER.HORA IS NULL THEN C_HKARDEXSALDEVINSER.HORA ELSE C_HKARDEXENTDEVINSER.HORA END
