SELECT 
    DEPRECIAR.COMPANIA,
    DEPRECIAR.ELEMENTO,
    DEPRECIAR.SERIE,
    DEPRECIAR.PERIODO,
    DEPRECIAR.BODEGA,
    INVENTARIO.NOMBRELARGO|| ' '  || DEVOLUTIVO.DESCRIPCION||CASE WHEN TRIM(DEVOLUTIVO.MARCA) IS NULL THEN '' ELSE ' MARCA: '|| DEVOLUTIVO.MARCA END NOMBRELARGOS,
    DEPRECIAR.VLRELEMENTO,
    DEPRECIAR.VLRDEPRECIACION,
    DEPRECIAR.COSTOAJUSTADO,
    DEPRECIAR.VLRLIBROS,
    DEPRECIAR.DEPACUMULADA,
    SUBSTR(DEPRECIAR.ELEMENTO, 1, s$agrupacion$s) AGRUPACION,
    PCK_ALMACEN.FC_NOMBREINVENTARIO(DEPRECIAR.COMPANIA,SUBSTR(DEPRECIAR.ELEMENTO,1, s$agrupacion$s),0) NOMBREINVENTARIO,
    '' CODIGOCUENTA,
    '' NOMBRECUENTA,
    TRIM(D_MOVIMIENTO.CENTRODECOSTO) CENTRODECOSTO,
    CENTRO_COSTO.NOMBRE
FROM DEPRECIAR
  INNER JOIN DEVOLUTIVO
    ON DEPRECIAR.COMPANIA       = DEVOLUTIVO.COMPANIA
    AND DEPRECIAR.ELEMENTO      = DEVOLUTIVO.ELEMENTO
    AND DEPRECIAR.SERIE         = DEVOLUTIVO.SERIE
  INNER JOIN INVENTARIO
    ON DEPRECIAR.COMPANIA       = INVENTARIO.COMPANIA
    AND DEPRECIAR.ELEMENTO      = INVENTARIO.CODIGOELEMENTO
  INNER JOIN D_MOVIMIENTO
    ON DEVOLUTIVO.COMPANIA          = D_MOVIMIENTO.COMPANIA
    AND DEVOLUTIVO.ELEMENTO         = D_MOVIMIENTO.ELEMENTO
    AND DEVOLUTIVO.SERIE            = D_MOVIMIENTO.SERIE
    AND DEVOLUTIVO.TIPOMOVIMIENTOF  = D_MOVIMIENTO.TIPOMOVIMIENTO
    AND DEVOLUTIVO.MOVIMIENTOF      = D_MOVIMIENTO.MOVIMIENTO
  INNER JOIN CENTRO_COSTO
    ON D_MOVIMIENTO.COMPANIA      = CENTRO_COSTO.COMPANIA
    AND D_MOVIMIENTO.CENTRODECOSTO  = CENTRO_COSTO.CODIGO
  INNER JOIN DEPENDENCIA
    ON DEPRECIAR.COMPANIA = DEPENDENCIA.COMPANIA
    AND DEPRECIAR.DEPENDENCIA = DEPENDENCIA.CODIGO
  INNER JOIN BODEGA
    ON DEPRECIAR.COMPANIA = BODEGA.COMPANIA
    AND DEPRECIAR.BODEGA = BODEGA.CODIGO
WHERE DEPRECIAR.COMPANIA        = s$compania$s
  AND DEPRECIAR.ELEMENTO BETWEEN 's$elementoInicial$s' AND 's$elementoFinal$s'
  AND TO_CHAR(DEPRECIAR.PERIODO, 'DD/MM/YYYY')                                                          = 's$ultimoDia$s'
  AND TO_DATE(TO_CHAR(NVL(DEVOLUTIVO.FECHAANULADA, TO_DATE('31/12/3000')), 'DD/MM/YYYY'), 'DD/MM/YYYY') > TO_DATE('s$ultimoDia$s', 'DD/MM/YYYY')
  AND CENTRO_COSTO.ANO                                                                                  = s$anio$s
  AND CENTRO_COSTO.CODIGO BETWEEN 's$ccInicial$s' AND 's$ccFinal$s'
  AND BODEGA.CLASE_BODEGA NOT IN (20,40,50)
  AND DEPENDENCIA.COMODATO IN (0)
  AND TO_DATE(TO_CHAR(DEVOLUTIVO.FECHAADQUISICION, 'DD/MM/YYYY'), 'DD/MM/YYYY') <= TO_DATE('s$ultimoDia$s', 'DD/MM/YYYY')
