MERGE INTO CONSULTAS FIN USING (SELECT '000537SubinformeDEntDevolutivo' INFORME ,TO_CLOB(q'[SELECT  D_MOVIMIENTO.COMPANIA,      
        D_MOVIMIENTO.TIPOMOVIMIENTO,        
        D_MOVIMIENTO.MOVIMIENTO,       
        SUM(D_MOVIMIENTO.VALORTOTAL) AS SUMADEVALORTOTAL,  
        LPAD(ELEMENTO,s$nivelGrupo$s) AS AGRUPACION,     
        SUM(D_MOVIMIENTO.VALORIVA) AS SUMADEVALORIVA,   
        SUM(D_MOVIMIENTO.VALORBASE) AS SUMADEVALORBASE
     
FROM D_MOVIMIENTO 
WHERE D_MOVIMIENTO.COMPANIA         = $P{PR_COMPANIA}    
    AND D_MOVIMIENTO.TIPOMOVIMIENTO = $P{PR_TIPOMOVIMIENTO} 
    AND D_MOVIMIENTO.MOVIMIENTO     = $P{PR_MOVIMIENTO} 
GROUP BY D_MOVIMIENTO.COMPANIA, D_MOVIMIENTO.TIPOMOVIMIENTO, D_MOVIMIENTO.MOVIMIENTO, LPAD(ELEMENTO,s$nivelGrupo$s)]') CONSULTA, 10 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);

MERGE INTO CONSULTAS_SUB FIN USING (SELECT '000536SDFTUNJA' INFORME_PADRE, '000537SubinformeDEntDevolutivo' INFORME_HIJO, 'PR_STRSQL_D_MOVIMIENTO' PARAMETRO ,NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (FIN.INFORME_PADRE = INI.INFORME_PADRE AND INI.INFORME_HIJO = FIN.INFORME_HIJO)  WHEN MATCHED THEN  UPDATE SET FIN.PARAMETRO = INI.PARAMETRO , FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME_PADRE,INFORME_HIJO, PARAMETRO,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME_PADRE,INI.INFORME_HIJO, INI.PARAMETRO,INI.CREATED_BY,SYSDATE);
MERGE INTO CONSULTAS_SUB FIN USING (SELECT '002486FormTraspasosUspec' INFORME_PADRE, '000537SubinformeDEntDevolutivo' INFORME_HIJO, 'PR_STRSQL_D_MOVIMIENTO' PARAMETRO ,'JCROJAS' CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (FIN.INFORME_PADRE = INI.INFORME_PADRE AND INI.INFORME_HIJO = FIN.INFORME_HIJO)  WHEN MATCHED THEN  UPDATE SET FIN.PARAMETRO = INI.PARAMETRO , FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME_PADRE,INFORME_HIJO, PARAMETRO,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME_PADRE,INI.INFORME_HIJO, INI.PARAMETRO,INI.CREATED_BY,SYSDATE);