SELECT 
  DEVOLUTIVO.ELEMENTO,
  DEVOLUTIVO.SERIE,
  DEVOLUTIVO.PLACA,
  SUBSTR(DEVOLUTIVO.ELEMENTO,0,3) AGRUPACION,
  ESTADODEVOLUTIVO.DESCRIPCION,
  INVENTARIO.NOMBRELARGO,
  PCK_ALMACEN.FC_NOMBREINVENTARIO(INVENTARIO.COMPANIA,SUBSTR(DEVOLUTIVO.ELEMENTO,0,3),0) NOMBRELARGO2,
  DEVOLUTIVO.VALOR,
  DEVOLUTIVO.DESCRIPCION DESCRIPCIONDEVOLUTIVO,
  DEVOLUTIVO.DEPENDENCIA,
  DEPENDENCIA.NOMBRE
FROM DEVOLUTIVO
  INNER JOIN INVENTARIO
    ON  DEVOLUTIVO.COMPANIA=INVENTARIO.COMPANIA
    AND DEVOLUTIVO.ELEMENTO=INVENTARIO.CODIGOELEMENTO
  LEFT JOIN ESTADODEVOLUTIVO
    ON  DEVOLUTIVO.ESTADO = ESTADODEVOLUTIVO.ESTADO
  LEFT JOIN DEPENDENCIA
    ON  DEVOLUTIVO.COMPANIA  = DEPENDENCIA.COMPANIA
    AND DEVOLUTIVO.DEPENDENCIA  = DEPENDENCIA.CODIGO
WHERE DEVOLUTIVO.COMPANIA=s$compania$s
  AND DEVOLUTIVO.ELEMENTO BETWEEN 's$elementoInicial$s' AND 's$elementoFinal$s'
  AND DEVOLUTIVO.VALOR BETWEEN s$desde$s AND s$hasta$s
  AND DEVOLUTIVO.PLACAANULADA IN (0)
ORDER BY 
  DEVOLUTIVO.ELEMENTO,
  DEVOLUTIVO.SERIE
