SELECT
      COMPANIA, 
      TIPOMOVIMIENTO,
      MOVIMIENTO,
      ELEMENTO AS CODIGOELEMENTO,
      TIPOMOVIMIENTO_NOM TIPOMOV, 
      NOMBRELARGO, 
      UNIDAD, 
      CANTIDAD, 
      VALORUNITARIO,
      VALORTOTAL_MOV,
      RESPONSABLE_DESTINO_CARGO AS CARGORESPONSABLE, 
      DEPENDENCIA_DESTINO DEPENDENCIA, 
      DEPENDENCIA_DESTINO_NOM NOMBREDEPENDENCIA, 
      DESCRIPCION_MOV DESCRIPCION, 
      FECHA_MOV FECHA,
      TERCERO_NOM NOMBRERESPONSABLE, 
      TERCERO,
      NOMBRELARGO || ' ' ||  
      CASE  WHEN TRIM(NVL(ESPECIFICACION,'')) IS NULL THEN ' ' 
        ELSE ESPECIFICACION 
       END || 
      CASE  WHEN TRIM(NVL(MARCA,'')) IS NOT NULL THEN 'MARCA: ' || MARCA || ' '
        ELSE ''
      END || 
      CASE  WHEN TRIM(NVL(SERIEDEVOLUTIVO,'')) IS NOT NULL THEN ', SERIE: ' || SERIEDEVOLUTIVO || ' ' 
        ELSE ''
      END ||
      CASE WHEN TRIM(NVL(SERIE,''))= 0 THEN ','
        ELSE ', PLACA: ' || SERIE
      END DESCRIPCIONELEMENTO,
      NOMBRELARGO || ' ' || 
      CASE WHEN ESPECIFICACION IS NULL THEN ' ' 
        ELSE ESPECIFICACION END NOMBREELEMENTO,
        CASE TRIM(SERIE) WHEN '' THEN NULL 
        ELSE SERIE 
      END SERIE
FROM V_MOVIMIENTO_INFORME 
WHERE COMPANIA       = s$compania$s
  AND TIPOMOVIMIENTO = 's$tipoMovimiento$s'
  AND MOVIMIENTO BETWEEN s$movimientoInicial$s AND s$movimientoFinal$s
ORDER BY COMPANIA, TIPOMOVIMIENTO, MOVIMIENTO, ELEMENTO
