Insert into CONSULTAS (INFORME,CONSULTA,APLICACION,CONSULTA_OPCIONAL,CREATED_BY,MODIFIED_BY,DATE_CREATED,DATE_MODIFIED) values ('000534SubDDescargoBodega',TO_CLOB(q'[SELECT DISTINCT 
  SUBSTR(D_MOVIMIENTO.ELEMENTO,0,PCK_SYSMAN_UTL.FC_PAR(UN_COMPANIA => D_MOVIMIENTO.COMPANIA,UN_NOMBRE => 'DIGITOS AGRUPACION INVENTARIO',UN_MODULO => PCK_DATOS.FC_MODULOALMACEN,UN_FECHA_PAR => SYSDATE)) AS AGRUPACION, 
  SUM(VALORTOTAL)  AS SUMADEVALORTOTAL 
FROM D_MOVIMIENTO
WHERE D_MOVIMIENTO.COMPANIA       = '$P!{PR_COMPANIA}'
  AND D_MOVIMIENTO.TIPOMOVIMIENTO = '$P!{PR_TIPOMOVIMIENTO}' 
  AND D_MOVIMIENTO.MOVIMIENTO     = $P!{PR_NUMERO}   
GROUP BY SUBSTR(D_MOVIMIENTO]')
|| TO_CLOB(q'[.ELEMENTO,0,PCK_SYSMAN_UTL.FC_PAR(UN_COMPANIA => D_MOVIMIENTO.COMPANIA,UN_NOMBRE => 'DIGITOS AGRUPACION INVENTARIO',UN_MODULO => PCK_DATOS.FC_MODULOALMACEN,UN_FECHA_PAR => SYSDATE))
]'),'10',TO_CLOB(q'[-- CONSULTA INICIAL
SELECT  D_MOVIMIENTO.COMPANIA,      
        D_MOVIMIENTO.TIPOMOVIMIENTO,        
        D_MOVIMIENTO.MOVIMIENTO,       
        SUM(D_MOVIMIENTO.VALORTOTAL) AS SUMADEVALORTOTAL,  
        LPAD(ELEMENTO,s$nivelGrupo$s) AS AGRUPACION,     
        SUM(D_MOVIMIENTO.VALORIVA) AS SUMADEVALORIVA,   
        SUM(D_MOVIMIENTO.VALORBASE) AS SUMADEVALORBASE
        
FROM D_MOVIMIENTO 
WHERE D_MOVIMIENTO.COMPANIA         = $P{PR_COMPANIA}    
    AND D_MOVIMIENTO.TIPOMOVIMIENTO = $P{P]')
|| TO_CLOB(q'[R_TIPOMOVIMIENTO} 
    AND D_MOVIMIENTO.MOVIMIENTO     = $P{PR_NUMERO} 
GROUP BY D_MOVIMIENTO.COMPANIA, D_MOVIMIENTO.TIPOMOVIMIENTO, D_MOVIMIENTO.MOVIMIENTO, LPAD(ELEMENTO,s$nivelGrupo$s)]'),null,null,null,null);
