MERGE INTO CONSULTAS FIN USING (SELECT '001383CInvIndivDevoluDepenEspec1' INFORME ,TO_CLOB(q'[SELECT 
  DEVOLUTIVO.COMPANIA,
  DEVOLUTIVO.ELEMENTO,
  DEVOLUTIVO.SERIE,
  DEVOLUTIVO.ESTADO,
  DEVOLUTIVO.SERIEDEVOLUTIVO,
  DEVOLUTIVO.DEPENDENCIA,
  DEVOLUTIVO.RESPONSABLE,
  DEVOLUTIVO.VALOR,
  INVENTARIO.CODIGOELEMENTO,
  DEPENDENCIA.NOMBRE NOMBREDEPENDENCIA,
  TERCERO.NOMBRE NOMBRERESPONSABLE,
  INVENTARIO.UNIDAD,
  DEVOLUTIVO.VALOR TVALOR,
  UNIDAD.NOMBRE NOMBREUNIDAD,
  ESTADODEVOLUTIVO.DESCRIPCION,
  INVENTARIO.NOMBRELARGO
  || ' '
  || CASE WHEN NVL(DEVOLUTIVO.MARCA,' ')=' ' THEN '' ELSE 'MARCA: ' || DEVOLUTIVO.MARCA END || ' ' || SUBSTR(NVL(DEVOLUTIVO.DESCRIPCION, ''), 1, 3000)
  || ' '
  || CASE WHEN NVL(D_MOVIMIENTO.ESCRITURA,' ')=' ' THEN '' ELSE 'ESCRITURA: ' || D_MOVIMIENTO.ESCRITURA END
  || ' '
  || CASE WHEN NVL(D_MOVIMIENTO.NUMEROCATASTRAL,' ')=' ' THEN '' ELSE 'CATASTRO: ' || D_MOVIMIENTO.NUMEROCATASTRAL END
  || ' '
  || CASE WHEN NVL(D_MOVIMIENTO.MATINMOBILIARIA,' ')=' ' THEN '' ELSE 'MATRICULA: ' || D_MOVIMIENTO.MATINMOBILIARIA END
  || ' '
  || CASE WHEN NVL(D_MOVIMIENTO.COD_CHIP,' ')=' ' THEN '' ELSE 'CHIP: ' || D_MOVIMIENTO.COD_CHIP END
  || ' '
  || CASE WHEN NVL(TO_CHAR(DEVOLUTIVO.SERIE),' ')=' ' THEN '' ELSE 'SERIE: ' || DEVOLUTIVO.SERIE END
  || ' '
  || CASE WHEN NVL(D_MOVIMIENTO.AREA,' ')=' ' THEN '' ELSE 'AREA: ' || D_MOVIMIENTO.AREA END NOMBRELARGO,
  SUBSTR(DEVOLUTIVO.ELEMENTO,0,3) AGRUPACION,
  TO_CHAR(DEVOLUTIVO.FECHAENTRADA, 'DD/MM/YYYY') FECHAENTRADA,
  INVENTARIO.UNIDAD ,
  DEVOLUTIVO.SERIEANTERIOR,
  D_MOVIMIENTO.ESCRITURA,
  D_MOVIMIENTO.NUMEROCATASTRAL,
  D_MOVIMIENTO.MATINMOBILIARIA,
  D_MOVIMIENTO.AREA,
  D_MOVIMIENTO.COD_CHIP,
  PCK_ALMACEN.FC_NOMBREINVENTARIO(DEVOLUTIVO.COMPANIA, SUBSTR(INVENTARIO.CODIGOELEMENTO,0,3),0) NOMBRE_INVENTARIO,
  DEPENDENCIA_RESPONSABLE.SUPERVISOR,
  DEPENDENCIA_RESPONSABLE.SUCURSAL_SUPERVISOR,
  TERCERO_SUP.NOMBRE NOMBRE_SUPERVISOR
FROM DEVOLUTIVO
	LEFT JOIN RESPONSABLE
		ON DEVOLUTIVO.COMPANIA   = RESPONSABLE.COMPANIA 
    		AND DEVOLUTIVO.RESPONSABLE = RESPONSABLE.CEDULA 
		AND DEVOLUTIVO.SUCURSAL_RESPONSABLE = RESPONSABLE.SUCURSAL 
  	LEFT JOIN TERCERO
   		ON RESPONSABLE.COMPANIA= TERCERO.COMPANIA
   		AND RESPONSABLE.CEDULA= TERCERO.NIT
   		AND RESPONSABLE.SUCURSAL= TERCERO.SUCURSAL
	LEFT JOIN INVENTARIO
		ON DEVOLUTIVO.COMPANIA  = INVENTARIO.COMPANIA
		AND DEVOLUTIVO.ELEMENTO = INVENTARIO.CODIGOELEMENTO
	LEFT JOIN DEPENDENCIA
		ON DEVOLUTIVO.COMPANIA     = DEPENDENCIA.COMPANIA
		AND DEVOLUTIVO.DEPENDENCIA = DEPENDENCIA.CODIGO
	LEFT JOIN UNIDAD
		ON INVENTARIO.UNIDAD = UNIDAD.UNIDAD
	LEFT JOIN ESTADODEVOLUTIVO
		ON DEVOLUTIVO.ESTADO = ESTADODEVOLUTIVO.ESTADO
	LEFT JOIN V_ENTDEVOLUTIVO
		ON DEVOLUTIVO.TIPOMOVIMIENTOI = V_ENTDEVOLUTIVO.TIPOMOVIMIENTO
		AND DEVOLUTIVO.COMPANIA       = V_ENTDEVOLUTIVO.COMPANIA
	LEFT JOIN D_MOVIMIENTO
		ON DEVOLUTIVO.COMPANIA       = D_MOVIMIENTO.COMPANIA
		AND DEVOLUTIVO.TIPOMOVIMIENTOI = D_MOVIMIENTO.TIPOMOVIMIENTO
		AND DEVOLUTIVO.ELEMENTO       = D_MOVIMIENTO.ELEM]') || TO_CLOB(q'[ENTO
		AND DEVOLUTIVO.SERIE          = D_MOVIMIENTO.SERIE
               LEFT JOIN DEPENDENCIA_RESPONSABLE  
 ON DEVOLUTIVO.COMPANIA             = DEPENDENCIA_RESPONSABLE.COMPANIA
AND DEVOLUTIVO.DEPENDENCIA          = DEPENDENCIA_RESPONSABLE.DEPENDENCIA
AND DEVOLUTIVO.RESPONSABLE          = DEPENDENCIA_RESPONSABLE.RESPONSABLE
AND DEVOLUTIVO.SUCURSAL_RESPONSABLE = DEPENDENCIA_RESPONSABLE.SUCURSAL
LEFT JOIN TERCERO TERCERO_SUP
    ON  DEPENDENCIA_RESPONSABLE.COMPANIA            = TERCERO_SUP.COMPANIA         
    AND DEPENDENCIA_RESPONSABLE.SUPERVISOR          = TERCERO_SUP.NIT 
    AND DEPENDENCIA_RESPONSABLE.SUCURSAL_SUPERVISOR = TERCERO_SUP.SUCURSAL 
WHERE DEVOLUTIVO.COMPANIA = s$compania$s
AND DEVOLUTIVO.DEPENDENCIA BETWEEN s$dependenciaInicial$s AND s$dependenciaFinal$s
AND DEVOLUTIVO.PLACAANULADA = 0
ORDER BY   Devolutivo.ELEMENTO, Devolutivo.SERIE]') CONSULTA, 10 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);