SELECT DEPRECIAR.COMPANIA,
       DEPRECIAR.DEPACUMULADA, 
       DEPRECIAR.ELEMENTO,
       DEPRECIAR.SERIE,
       DEPRECIAR.VLRDEPRECIACION, 
       DEPRECIAR.VLRLIBROS,
       (DEPRECIAR.DEPACUMULADA - DEPRECIAR.VLRDEPRECIACION) AS DEPRECIACION_ANTERIOR,
       LPAD(DEPRECIAR.ELEMENTO,  s$agrupacion$s) AS AGRUPACION,
       DEVOLUTIVO.VALOR AS VALOR_DEVOLUTIVO,
       INVENTARIO.NOMBRELARGO || ' ' || DEVOLUTIVO.DESCRIPCION 
       || CASE WHEN DEVOLUTIVO.MARCA IS NULL OR DEVOLUTIVO.MARCA = ' ' 
       THEN '' ELSE ' MARCA: ' || DEVOLUTIVO.MARCA END AS NOMBRE_LARGO,
       PCK_ALMACEN.FC_NOMBREINVENTARIO(DEVOLUTIVO.COMPANIA, DEVOLUTIVO.ELEMENTO, 0) AS NOMBRE_INVENTARIO,
       INVCONTAB.DEPRECCREDITOS AS CODIGOCUENTA,
       PLAN_CONTABLE.NOMBRE AS NOMBRECUENTA
  FROM DEPRECIAR
 INNER JOIN DEVOLUTIVO
    ON DEPRECIAR.COMPANIA = DEVOLUTIVO.COMPANIA
   AND DEPRECIAR.ELEMENTO = DEVOLUTIVO.ELEMENTO
   AND DEPRECIAR.SERIE    = DEVOLUTIVO.SERIE
 INNER JOIN INVENTARIO
    ON DEVOLUTIVO.COMPANIA = INVENTARIO.COMPANIA
   AND DEVOLUTIVO.ELEMENTO = INVENTARIO.CODIGOELEMENTO
 INNER JOIN s$tablaInventario$s INVCONTAB
    ON DEPRECIAR.COMPANIA          = INVCONTAB.COMPANIA
   AND DEPRECIAR.ANO               = INVCONTAB.ANO
   AND LPAD(DEPRECIAR.ELEMENTO, 5) = INVCONTAB.CODIGOELEMENTO
  INNER JOIN PLAN_CONTABLE
    ON INVCONTAB.COMPANIA       = PLAN_CONTABLE.COMPANIA
   AND INVCONTAB.ANO            = PLAN_CONTABLE.ANO
   AND INVCONTAB.DEPRECCREDITOS = PLAN_CONTABLE.CODIGO
WHERE DEPRECIAR.COMPANIA =  s$compania$s 
  AND DEVOLUTIVO.PLACAANULADA <> 0
  AND TRUNC(DEPRECIAR.PERIODO) = TO_DATE('s$ultimoDia$s','DD/MM/YYYY') 
  AND TRUNC(DEVOLUTIVO.FECHAADQUISICION) <= TO_DATE('s$ultimoDia$s','DD/MM/YYYY') 
  AND DEPRECIAR.ELEMENTO BETWEEN 's$elementoInicial$s' AND 's$elementoFinal$s'
ORDER BY DEPRECIAR.ELEMENTO
       , DEPRECIAR.SERIE
       , DEPRECIAR.PERIODO
