MERGE INTO CONSULTAS FIN USING (SELECT '001467TDR' INFORME ,TO_CLOB(q'[SELECT D_MOVIMIENTO.COMPANIA, 
       D_MOVIMIENTO.TIPOMOVIMIENTO, 
       ENTDEVOLUTIVO.NUMERO CONSECUTIVO, 
       TIPOMOVIMIENTO.NOMBRE NOMBRETIPOMOVIMIENTO, 
       DEPENDENCIA_1.NOMBRE NOMBREDEPENDENCIA1,
       DEPENDENCIA.NOMBRE NOMBREDEPENDENCIA, 
       D_MOVIMIENTO.ELEMENTO, 
       INVENTARIO.UNIDAD, 
       D_MOVIMIENTO.CANTIDAD, 
       NVL(INVENTARIO.DESCRIPCION, ' ') DESCRIPCIONINVENTARIO,  
       D_MOVIMIENTO.SERIE, 
       D_MOVIMIENTO.VALORUNITARIO, 
       D_MOVIMIENTO.VALORTOTAL, 
       ENTDEVOLUTIVO.DESCRIPCION DESCRIPCIONENTDEVOLUTIVO,  
       RESPONSABLE_1.NIT        CEDULANUEVA, 
       RESPONSABLE_1.NOMBRE     RESPONSABLENUEVO,  
       RESPONSABLE.NIT         CEDULAANTERIOR ,  
       RESPONSABLE.NOMBRE     RESPONSABLEANTERIOR  ,
       ENTDEVOLUTIVO.TIPOMOVIMIENTO || ENTDEVOLUTIVO.NUMERO as GRUPO,
       INVENTARIO.NOMBRELARGO,
       INVENTARIO.NOMBRELARGO || ' ' 
       || case when NVL(DEVOLUTIVO.MARCA,' ') = ' ' 
               then '' 
               ELSE 'Marca: ' || DEVOLUTIVO.MARCA 
          END || '. ' || ENTDEVOLUTIVO.DESCRIPCION AS NOMBRELARGO,
       DEVOLUTIVO.MARCA, 
       TRIM(TO_CHAR(ENTDEVOLUTIVO.fecha, 'Day')) || ', '|| TRIM(TO_CHAR(ENTDEVOLUTIVO.fecha, 'DD "de" Month')) 
       || ' ' || TRIM(TO_CHAR(ENTDEVOLUTIVO.fecha, '"de" YYYY')) FECHATRASPASO,
       TO_CHAR(D_MOVIMIENTO.FECHA) AS FECHA
  FROM V_ENTDEVOLUTIVO ENTDEVOLUTIVO
       INNER JOIN TIPOMOVIMIENTO
               ON ENTDEVOLUTIVO.COMPANIA       = TIPOMOVIMIENTO.COMPANIA 
              AND ENTDEVOLUTIVO.TIPOMOVIMIENTO = TIPOMOVIMIENTO.CODIGO
       INNER JOIN D_MOVIMIENTO
               ON ENTDEVOLUTIVO.COMPANIA       = D_MOVIMIENTO.COMPANIA  
              AND ENTDEVOLUTIVO.TIPOMOVIMIENTO = D_MOVIMIENTO.TIPOMOVIMIENTO
              AND ENTDEVOLUTIVO.NUMERO         = D_MOVIMIENTO.MOVIMIENTO
              INNER JOIN INVENTARIO
               ON D_MOVIMIENTO.COMPANIA = INVENTARIO.COMPANIA
              AND D_MOVIMIENTO.ELEMENTO = INVENTARIO.CODIGOELEMENTO 
              INNER JOIN DEVOLUTIVO
                     ON D_MOVIMIENTO.COMPANIA = DEVOLUTIVO.COMPANIA 
                    AND D_MOVIMIENTO.ELEMENTO = DEVOLUTIVO.ELEMENTO
                    AND D_MOVIMIENTO.SERIE    = DEVOLUTIVO.SERIE
       INNER JOIN TERCERO RESPONSABLE
               ON ENTDEVOLUTIVO.COMPANIA           = RESPONSABLE.COMPANIA    
              AND ENTDEVOLUTIVO.RESPONSABLE_ORIGEN = RESPONSABLE.NIT
              AND ENTDEVOLUTIVO.SUCURSAL_RESORIGEN = RESPONSABLE.SUCURSAL
       INNER JOIN TERCERO RESPONSABLE_1
               ON ENTDEVOLUTIVO.COMPANIA            = RESPONSABLE_1.COMPANIA    
              AND ENTDEVOLUTIVO.RESPONSABLE_DESTINO = RESPONSABLE_1.NIT
              AND ENTDEVOLUTIVO.SUCURSAL_RESDESTINO = RESPONSABLE_1.SUCURSAL
       INNER JOIN DEPENDENCIA 
               ON ENTDEVOLUTIVO.COMPANIA           = DEPENDENCIA.COMPANIA
              AND ENTDEVOLUTIVO.DEPENDENCIA_ORIGEN = DEPENDENCIA.CODIGO
       INNER JOIN DEPENDENCIA DEPENDENCIA_1
           ]') || TO_CLOB(q'[    ON ENTDEVOLUTIVO.COMPANIA            = DEPENDENCIA_1.COMPANIA 
              AND ENTDEVOLUTIVO.DEPENDENCIA_DESTINO = DEPENDENCIA_1.CODIGO   
 WHERE ENTDEVOLUTIVO.COMPANIA       = s$compania$s 
   AND ENTDEVOLUTIVO.TIPOMOVIMIENTO = 's$tipoMovimiento$s' 
   AND ENTDEVOLUTIVO.NUMERO         = 's$movimientoInicial$s']') CONSULTA, 10 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);