SELECT
  CASE
    WHEN TIPOMOVIMIENTO.CLASE IN 'E'
    THEN D_MOVIMIENTO.VALORTOTAL
    ELSE 0
  END ENTRADAS,
  CASE
    WHEN TIPOMOVIMIENTO.CLASE IN 'S'
    THEN D_MOVIMIENTO.VALORTOTAL
    ELSE 0
  END SALIDAS,
  CASE
    WHEN TIPOMOVIMIENTO.CLASE IN 'E'
    THEN D_MOVIMIENTO.CANTIDAD
    ELSE 0
  END CANTENTRADAS,
  CASE
    WHEN TIPOMOVIMIENTO.CLASE IN 'S'
    THEN D_MOVIMIENTO.CANTIDAD
    ELSE 0
  END CANTSALIDAS,
  D_MOVIMIENTO.FECHA,
  TIPOMOVIMIENTO.NOMBRE,
  D_MOVIMIENTO.COMPANIA,
  D_MOVIMIENTO.ELEMENTO,
  D_MOVIMIENTO.CANTIDAD,
  D_MOVIMIENTO.TIPOMOVIMIENTO,
  D_MOVIMIENTO.MOVIMIENTO,
  D_MOVIMIENTO.IND_REG,
  D_MOVIMIENTO.HORA,
  TIPOMOVIMIENTO.NOMBRECORTO,
  D_MOVIMIENTO.ELEMENTO  AS CODIGOELEMENTO,
  INVENTARIO.NOMBRELARGO AS NELEMENTO,
  D_MOVIMIENTO.AUXILIAR,
  NVL(AUXILIAR.CODIGO,'99999999999999999999') CODAUXILIAR,
  NVL(AUXILIAR.NOMBRE,'Varios') NAUXILIAR
FROM D_MOVIMIENTO
INNER JOIN MOVIMIENTO
ON D_MOVIMIENTO.COMPANIA        = MOVIMIENTO.COMPANIA
AND D_MOVIMIENTO.TIPOMOVIMIENTO = MOVIMIENTO.TIPOMOVIMIENTO
AND D_MOVIMIENTO.MOVIMIENTO     = MOVIMIENTO.NUMERO
LEFT JOIN TIPOMOVIMIENTO
ON MOVIMIENTO.COMPANIA        = TIPOMOVIMIENTO.COMPANIA
AND MOVIMIENTO.TIPOMOVIMIENTO = TIPOMOVIMIENTO.CODIGO
LEFT JOIN INVENTARIO
ON D_MOVIMIENTO.ELEMENTO  = INVENTARIO.CODIGOELEMENTO
AND D_MOVIMIENTO.COMPANIA = INVENTARIO.COMPANIA
LEFT JOIN AUXILIAR
ON INVENTARIO.COMPANIA      = AUXILIAR.COMPANIA
AND INVENTARIO.ANO          = AUXILIAR.ANO
AND INVENTARIO.AUXILIAR     = AUXILIAR.CODIGO
WHERE D_MOVIMIENTO.COMPANIA = s$compania$s
AND D_MOVIMIENTO.ELEMENTO BETWEEN 's$elementoInicial$s' AND 's$elementoFinal$s'
AND TO_CHAR(D_MOVIMIENTO.FECHA,'DD/MM/YYYY') BETWEEN s$fechaInicial$s AND s$fechaFinal$s
ORDER BY D_MOVIMIENTO.TIPOMOVIMIENTO,
  D_MOVIMIENTO.MOVIMIENTO
