MERGE INTO CONSULTAS FIN USING (SELECT '001894ELEMENTOSCOMPONENTES' INFORME ,TO_CLOB(q'[WITH ULTIMOMOV AS
  (SELECT D_MOVIMIENTO.SERIE,
    D_MOVIMIENTO.COMPANIA,
    MAX(D_MOVIMIENTO.ELEMENTO) KEEP (DENSE_RANK LAST
  ORDER BY TO_DATE( TO_CHAR(D_MOVIMIENTO.FECHA + NUMTODSINTERVAL(TO_CHAR(D_MOVIMIENTO.HORA,'hh24'),'HOUR' ) + NUMTODSINTERVAL(TO_CHAR(D_MOVIMIENTO.HORA,'mi' ),'MINUTE') + NUMTODSINTERVAL(TO_CHAR(D_MOVIMIENTO.HORA,'ss' ),'SECOND') ,'DD/MM/YYYY hh24:mi:ss') ,'DD/MM/YYYY hh24:mi:ss')) ELEMENTO,
    MAX(MOVIMIENTO.BODEGA_DESTINO) KEEP (DENSE_RANK LAST
  ORDER BY TO_DATE( TO_CHAR(D_MOVIMIENTO.FECHA + NUMTODSINTERVAL(TO_CHAR(D_MOVIMIENTO.HORA,'hh24'),'HOUR' ) + NUMTODSINTERVAL(TO_CHAR(D_MOVIMIENTO.HORA,'mi' ),'MINUTE') + NUMTODSINTERVAL(TO_CHAR(D_MOVIMIENTO.HORA,'ss' ),'SECOND') ,'DD/MM/YYYY hh24:mi:ss') ,'DD/MM/YYYY hh24:mi:ss')) BODEGA,
    MAX( TO_DATE( TO_CHAR(D_MOVIMIENTO.FECHA   + NUMTODSINTERVAL(TO_CHAR(D_MOVIMIENTO.HORA,'hh24'),'HOUR' ) + NUMTODSINTERVAL(TO_CHAR(D_MOVIMIENTO.HORA,'mi' ),'MINUTE') + NUMTODSINTERVAL(TO_CHAR(D_MOVIMIENTO.HORA,'ss' ),'SECOND') ,'DD/MM/YYYY hh24:mi:ss') ,'DD/MM/YYYY hh24:mi:ss') ) KEEP (DENSE_RANK LAST
  ORDER BY ROWNUM) FECHA,
    MAX(MOVIMIENTO.DEPENDENCIA_DESTINO) KEEP (DENSE_RANK LAST
  ORDER BY TO_DATE( TO_CHAR(D_MOVIMIENTO.FECHA + NUMTODSINTERVAL(TO_CHAR(D_MOVIMIENTO.HORA,'hh24'),'HOUR' ) + NUMTODSINTERVAL(TO_CHAR(D_MOVIMIENTO.HORA,'mi' ),'MINUTE') + NUMTODSINTERVAL(TO_CHAR(D_MOVIMIENTO.HORA,'ss' ),'SECOND') ,'DD/MM/YYYY hh24:mi:ss') ,'DD/MM/YYYY hh24:mi:ss')) DEPENDENCIA,
    MAX( D_MOVIMIENTO.TIPOMOVIMIENTO) KEEP (DENSE_RANK LAST
  ORDER BY TO_DATE( TO_CHAR(D_MOVIMIENTO.FECHA + NUMTODSINTERVAL(TO_CHAR(D_MOVIMIENTO.HORA,'hh24'),'HOUR' ) + NUMTODSINTERVAL(TO_CHAR(D_MOVIMIENTO.HORA,'mi' ),'MINUTE') + NUMTODSINTERVAL(TO_CHAR(D_MOVIMIENTO.HORA,'ss' ),'SECOND') ,'DD/MM/YYYY hh24:mi:ss') ,'DD/MM/YYYY hh24:mi:ss')) TIPO,
    MAX( D_MOVIMIENTO.MOVIMIENTO) KEEP (DENSE_RANK LAST
  ORDER BY TO_DATE( TO_CHAR(D_MOVIMIENTO.FECHA + NUMTODSINTERVAL(TO_CHAR(D_MOVIMIENTO.HORA,'hh24'),'HOUR' ) + NUMTODSINTERVAL(TO_CHAR(D_MOVIMIENTO.HORA,'mi' ),'MINUTE') + NUMTODSINTERVAL(TO_CHAR(D_MOVIMIENTO.HORA,'ss' ),'SECOND') ,'DD/MM/YYYY hh24:mi:ss') ,'DD/MM/YYYY hh24:mi:ss')) MOVIMIENTO,
    MAX( D_MOVIMIENTO.VALORUNITARIO) KEEP (DENSE_RANK LAST
  ORDER BY TO_DATE( TO_CHAR(D_MOVIMIENTO.FECHA + NUMTODSINTERVAL(TO_CHAR(D_MOVIMIENTO.HORA,'hh24'),'HOUR' ) + NUMTODSINTERVAL(TO_CHAR(D_MOVIMIENTO.HORA,'mi' ),'MINUTE') + NUMTODSINTERVAL(TO_CHAR(D_MOVIMIENTO.HORA,'ss' ),'SECOND') ,'DD/MM/YYYY hh24:mi:ss') ,'DD/MM/YYYY hh24:mi:ss')) VALOR
  FROM D_MOVIMIENTO
  INNER JOIN MOVIMIENTO
  ON D_MOVIMIENTO.COMPANIA                                                                                                                                                                                                                                                            = MOVIMIENTO.COMPANIA
  AND D_MOVIMIENTO.TIPOMOVIMIENTO                                                                                                ]') || TO_CLOB(q'[                                                                                                                                                     = MOVIMIENTO.TIPOMOVIMIENTO
  AND D_MOVIMIENTO.MOVIMIENTO                                                                                                                                                                                                                                                         = MOVIMIENTO.NUMERO
  WHERE D_MOVIMIENTO.IND_REG NOT  IN (0)
  AND D_MOVIMIENTO.COMPANIA = 's$compania$s'
  AND TO_DATE( TO_CHAR(D_MOVIMIENTO.FECHA + NUMTODSINTERVAL(TO_CHAR(D_MOVIMIENTO.HORA,'hh24'),'HOUR' ) + NUMTODSINTERVAL(TO_CHAR(D_MOVIMIENTO.HORA,'mi' ),'MINUTE') + NUMTODSINTERVAL(TO_CHAR(D_MOVIMIENTO.HORA,'ss' ),'SECOND') ,'DD/MM/YYYY hh24:mi:ss') ,'DD/MM/YYYY hh24:mi:ss') <= TO_DATE(TO_CHAR(SYSDATE, 'DD/MM/YYYY')
    || ' 23:59:59', 'DD/MM/YYYY hh24:mi:ss')
  GROUP BY D_MOVIMIENTO.SERIE,
    D_MOVIMIENTO.COMPANIA
  )
SELECT D.CODIGO_ELEMENTO ,
  D.CODIGO_COMPONENTE COMPONENTE,
  D.SERIE_COMPONENTE SERIE,
  I.NOMBRELARGO,
  ULTIMOMOV.VALOR,
  E.CONSECUTIVO ELEMENTO,
  E.CONSECUTIVO
  || ' '
  || E.NOMBRE NOMBREELEMENTO,
  D.CODIGO_COMPONENTE COMPONENTE,
  D.SERIE_COMPONENTE SERIE,
  I.NOMBRELARGO NOMBRECOMPONENTE,
  ULTIMOMOV.TIPO,
  ULTIMOMOV.MOVIMIENTO,
  TO_CHAR(ULTIMOMOV.FECHA,'DD/MM/YYYY')AS FECHA,
  DEPENDENCIA.NOMBRE DEPENDENCIA
FROM ELEMENTOSCOMPONENTES E
INNER JOIN DETALLE_ELEMENTOSCOMPONENTES D
ON E.COMPANIA     = D.COMPANIA
AND E.CONSECUTIVO = D.CODIGO_ELEMENTO
INNER JOIN INVENTARIO I
ON D.COMPANIA           = I.COMPANIA
AND D.CODIGO_COMPONENTE = I.CODIGOELEMENTO
LEFT JOIN ULTIMOMOV
ON D.COMPANIA           = ULTIMOMOV.COMPANIA
AND D.CODIGO_COMPONENTE = ULTIMOMOV.ELEMENTO
 AND D.SERIE_COMPONENTE  = ULTIMOMOV.SERIE
 LEFT JOIN DEPENDENCIA
 ON ULTIMOMOV.COMPANIA     = DEPENDENCIA.COMPANIA
  AND ULTIMOMOV.DEPENDENCIA = DEPENDENCIA.CODIGO
  WHERE D.COMPANIA          = 's$compania$s'
  AND D.CODIGO_COMPONENTE BETWEEN 's$elementodesde$s' AND 's$elementoHasta$s']') CONSULTA, 10 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);