MERGE INTO CONSULTAS FIN USING (SELECT '001846IEstadoDevYBiAFecha' INFORME ,TO_CLOB(q'[ WITH ULTIMOMOVESTADODEVYBIFECHA_AGR AS (
SELECT D_MOVIMIENTO.COMPANIA,
        D_MOVIMIENTO.ELEMENTO,
        SUBSTR(D_MOVIMIENTO.ELEMENTO, 0,s$digito$s) AGRUPACION,
        SUM(D_MOVIMIENTO.VALORTOTAL) VLRADICIONES,                               
    SUM(CASE WHEN TIPOMOVIMIENTO.NOMBRE IN ('RAI') THEN D_MOVIMIENTO.VALORTOTAL ELSE 0 END) AJUSTES
   FROM D_MOVIMIENTO
  INNER JOIN MOVIMIENTO
     ON D_MOVIMIENTO.COMPANIA       = MOVIMIENTO.COMPANIA
    AND D_MOVIMIENTO.TIPOMOVIMIENTO = MOVIMIENTO.TIPOMOVIMIENTO
    AND D_MOVIMIENTO.MOVIMIENTO     = MOVIMIENTO.NUMERO
  INNER JOIN TIPOMOVIMIENTO
     ON D_MOVIMIENTO.TIPOMOVIMIENTO = TIPOMOVIMIENTO.CODIGO
    AND D_MOVIMIENTO.COMPANIA       = TIPOMOVIMIENTO.COMPANIA
WHERE D_MOVIMIENTO.COMPANIA = 's$compania$s'
    AND D_MOVIMIENTO.FECHA <= 's$fecha$s'
    AND D_MOVIMIENTO.ELEMENTO BETWEEN 's$elementoInicial$s' AND 's$elementoFinal$s'
    AND D_MOVIMIENTO.IND_REG  NOT IN (0)
    AND TIPOMOVIMIENTO.CONCEPTO = 'CR'
GROUP BY D_MOVIMIENTO.COMPANIA,
        D_MOVIMIENTO.ELEMENTO)
        
        SELECT DEPRECIAR.COMPANIA,
 INV.NOMBRELARGO,
        INVENTARIO.TIPO,
        INVENTARIO.NOMBRELARGO    AS NOMBRE,
    SUM (DEPRECIAR.COSTOAJUSTADO - DEPRECIAR.VLRELEMENTO)  AJUSTEXINFLACIONAC,
    SUM (DEPRECIAR.DEPACUMULADAAJ)                         ACUMAJUSXINFLACIONDEP,
    SUM (DEPRECIAR.COSTOAJUSTADO)                          SUMADECOSTOAJUSTADO,
    SUM (DEPRECIAR.VLRELEMENTO)                            SUMADEVLRELEMENTO,
    SUM (DEPRECIAR.AJDEPACUMULADA)                         SUMADEAJDEPACUMULADA,
    SUM (DEPRECIAR.VLRELEMENTO)                            SUMDEVLRELEMVALORADI,
    SUBSTR(DEVOLUTIVO.ELEMENTO, 0, s$digito$s) EXPR3,
    SUBSTR(DEVOLUTIVO.ELEMENTO, 0, s$digito$s) AGRUPACION,
    SUM (DEPRECIAR.DEPACUMULADA)                                            SUMADEDEPACUMULADA,
    SUM (DEPRECIAR.VLRLIBROS)                                               SUMADEVLRLIBROS,
    SUM (DEPRECIAR.ACUMDEPAJ)                                               SUMADEACUMDEPAJ,
    SUM (DEPRECIAR.ACUMAJUSTESAJ)                                           SUMADEACUMAJUSTESAJ,
    SUM (DEPRECIAR.ACUMDEPAJ)                                               ACUMDEPAJFER,
        INVENTARIO.CUENTAACTIVO,
        INVENTARIO.CUENTAACTIVOS,
        SUBSTR(DEVOLUTIVO.ELEMENTO,0,s$digito$s)   NOMBREINV,
    SUM(ULTIMOMOVESTADODEVYBIFECHA_AGR.VLRADICIONES)                        VALORADICIONES,
        INVENTARIOCONTABILIDAD.DEPRECCREDITO                                CODDEPACUM,
        INVENTARIO.CUENTAACTIVO                                             CODBODEGA,
        INVENTARIO.CUENTAACTIVOS                                            CODSERVICIO,
        SUBSTR(DEVOLUTIVO.ELEMENTO,0,s$digito$s) GRUPO,
    SUM (DEPRECIAR.VLRDEPRECIACION)                                         SUMADEVLRDEPRECIACION,
    SUM (ULTIMOMOVESTADODEVYBIFECHA_AGR.AJUSTES)                            SUMADEAJUSTES
   FROM DEPRECIAR
  INNER JOIN DEVOLUTI]') || TO_CLOB(q'[VO
     ON DEPRECIAR.COMPANIA = DEVOLUTIVO.COMPANIA
    AND DEPRECIAR.SERIE    = DEVOLUTIVO.SERIE
    AND DEPRECIAR.ELEMENTO = DEVOLUTIVO.ELEMENTO
  INNER JOIN INVENTARIO
     ON DEPRECIAR.COMPANIA  = INVENTARIO.COMPANIA
    AND DEPRECIAR.ELEMENTO  = INVENTARIO.CODIGOELEMENTO
  LEFT JOIN ULTIMOMOVESTADODEVYBIFECHA_AGR
     ON DEPRECIAR.COMPANIA  = ULTIMOMOVESTADODEVYBIFECHA_AGR.COMPANIA
    AND DEPRECIAR.ELEMENTO  = ULTIMOMOVESTADODEVYBIFECHA_AGR.ELEMENTO
  LEFT JOIN INVENTARIOCONTABILIDAD
     ON DEPRECIAR.COMPANIA = INVENTARIOCONTABILIDAD.COMPANIA
    AND DEPRECIAR.ELEMENTO = INVENTARIOCONTABILIDAD.CODIGOELEMENTO
    AND DEPRECIAR.ANO = INVENTARIOCONTABILIDAD.ANO
    AND SUBSTR(DEPRECIAR.ELEMENTO, 0,s$digito$s) = INVENTARIOCONTABILIDAD.CODIGOELEMENTO
 INNER JOIN INVENTARIO INV
     ON DEPRECIAR.COMPANIA = INV.COMPANIA
   AND SUBSTR(DEPRECIAR.ELEMENTO, 0 ,3) = INV.CODIGOELEMENTO 
  WHERE DEPRECIAR.COMPANIA = 's$compania$s'
    AND DEPRECIAR.ELEMENTO BETWEEN 's$elementoInicial$s' AND 's$elementoFinal$s'
    AND DEVOLUTIVO.FECHAULTMOV > 's$fecha$s'
    GROUP BY DEPRECIAR.COMPANIA,
 INV.NOMBRELARGO,
        INVENTARIO.TIPO,
        INVENTARIO.NOMBRELARGO,
        INVENTARIOCONTABILIDAD.DEPRECCREDITO  ,
        SUBSTR(DEVOLUTIVO.ELEMENTO,0,s$digito$s) ,
        INVENTARIO.CUENTAACTIVO,
        INVENTARIO.CUENTAACTIVOS,
        SUBSTR(DEVOLUTIVO.ELEMENTO,0,s$digito$s),
        INVENTARIO.CUENTAACTIVO,
        INVENTARIO.CUENTAACTIVOS,
        SUBSTR(DEVOLUTIVO.ELEMENTO,0,s$digito$s) 
  ORDER BY INVENTARIO.TIPO,
  CASE WHEN 's$orden$s' = '1' THEN SUBSTR(DEVOLUTIVO.ELEMENTO, 0, s$digito$s) ELSE INVENTARIO.NOMBRELARGO END]') CONSULTA, 10 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);