WITH REQUISICIONES AS (
  SELECT 
   COMPANIA,
   CLASEORDEN,
   ORDENDECOMPRA,
   LISTAGG(ORDENDESUMINISTRO, ', ') WITHIN GROUP (ORDER BY ORDENDESUMINISTRO) REQS
   FROM ( SELECT DISTINCT 
            COMPANIA,
            CLASEORDEN,
            ORDENDECOMPRA,
            D_ORDENDECOMPRA.ORDENDESUMINISTRO
          FROM D_ORDENDECOMPRA
          WHERE D_ORDENDECOMPRA.COMPANIA      = s$compania$s
            AND D_ORDENDECOMPRA.CLASEORDEN    = 's$claseOrden$s'
            AND D_ORDENDECOMPRA.ORDENDECOMPRA = s$ordenDeCompra$s)
  GROUP BY  
   COMPANIA,
   CLASEORDEN,
   ORDENDECOMPRA
)
SELECT 
  ORDENDECOMPRA.CLASEORDEN,
  ORDENDECOMPRA.FECHA,
  TERCERO.DIRECCION || ' ' || CIUDAD.NOMBRE || ' ' || DEPARTAMENTO.NOMBRE DIRECCION,
  TERCERO.TELEFONOS || CASE WHEN TERCERO.FAX IS NULL THEN '' ELSE ', ' || TERCERO.FAX END TELEFONOS,
  REQUISICIONES.REQS  REQUISICIONES, 
  ORDENDECOMPRA.NUMERO ORDENDECOMPRA,
  TERCERO.NOMBRE,
  ORDENDECOMPRA.TERCERO,
  NVL(ORDENDECOMPRA.DESCRIPCION,' ') DESCRIPCION,
  NVL(V_ORDENDECOMPRA_RUBRO.RUBRO,' ') RUBRO,
  NVL(ORDENDECOMPRA.NUMCOTIZACION,' ') NUMCOTIZACION,
  D_ORDENDECOMPRA.ELEMENTO AS CODIGO,
  INVENTARIO.NOMBRELARGO NOMBRELARGO,
  INVENTARIO.UNIDAD,
  D_ORDENDECOMPRA.CANTIDAD,
  D_ORDENDECOMPRA.VALORUNITARIO,
  D_ORDENDECOMPRA.CANTIDAD * D_ORDENDECOMPRA.VALORUNITARIO SUBTOTAL,
  D_ORDENDECOMPRA.VLRDESCUENTO,
  D_ORDENDECOMPRA.VLRIVA,
  D_ORDENDECOMPRA.VLRTOTAL,
  D_ORDENDECOMPRA.VALORIMPCONSUMO,
  ORDENDECOMPRA.AJUSTEPESO,
  ORDENDECOMPRA.VALORTOTAL AS VALTOTAL,
  ORDENDECOMPRA.NOTAS,
  ORDENDECOMPRA.FORMADEPAGO ,
  V_ORDENDECOMPRA_DIS.COMPROBANTES DISPONIBILIDAD, 
  V_ORDENDECOMPRA_DIS.TOTAL_DIS VALORDISPONIBILIDAD, 
  CASE TERCERO.REGIMEN
    WHEN 'C' THEN 'Común'
    WHEN 'S' THEN 'Simplificado'
    WHEN 'G' THEN 'Gran Contribuyente'
    ELSE 'Ninguno'
  END REGIMEN  
FROM ORDENDECOMPRA  
INNER JOIN TERCERO
   ON ORDENDECOMPRA.COMPANIA  = TERCERO.COMPANIA
  AND ORDENDECOMPRA.TERCERO   = TERCERO.NIT
  AND ORDENDECOMPRA.SUCURSAL  = TERCERO.SUCURSAL
 LEFT JOIN CIUDAD
   ON TERCERO.PAIS         = CIUDAD.PAIS 
  AND TERCERO.DEPARTAMENTO = CIUDAD.DEPARTAMENTO         
  AND TERCERO.CIUDAD       = CIUDAD.CODIGO     
 LEFT JOIN DEPARTAMENTO
   ON DEPARTAMENTO.PAIS   = CIUDAD.PAIS
  AND DEPARTAMENTO.CODIGO = CIUDAD.DEPARTAMENTO
INNER JOIN D_ORDENDECOMPRA
   ON ORDENDECOMPRA.COMPANIA      = D_ORDENDECOMPRA.COMPANIA
  AND ORDENDECOMPRA.CLASEORDEN    = D_ORDENDECOMPRA.CLASEORDEN
  AND ORDENDECOMPRA.NUMERO        = D_ORDENDECOMPRA.ORDENDECOMPRA
INNER JOIN INVENTARIO
   ON D_ORDENDECOMPRA.COMPANIA = INVENTARIO.COMPANIA
  AND D_ORDENDECOMPRA.ELEMENTO  = INVENTARIO.CODIGOELEMENTO
LEFT JOIN REQUISICIONES
   ON ORDENDECOMPRA.COMPANIA      = REQUISICIONES.COMPANIA
  AND ORDENDECOMPRA.CLASEORDEN    = REQUISICIONES.CLASEORDEN
  AND ORDENDECOMPRA.NUMERO        = REQUISICIONES.ORDENDECOMPRA
LEFT JOIN V_ORDENDECOMPRA_DIS 
   ON ORDENDECOMPRA.COMPANIA    = V_ORDENDECOMPRA_DIS.COMPANIA 
  AND ORDENDECOMPRA.CLASEORDEN  = V_ORDENDECOMPRA_DIS.CLASEORDEN
  AND ORDENDECOMPRA.NUMERO      = V_ORDENDECOMPRA_DIS.NUMERO
LEFT JOIN V_ORDENDECOMPRA_RUBRO  
   ON ORDENDECOMPRA.COMPANIA    = V_ORDENDECOMPRA_RUBRO.COMPANIA 
  AND ORDENDECOMPRA.CLASEORDEN  = V_ORDENDECOMPRA_RUBRO.CLASEORDEN
  AND ORDENDECOMPRA.NUMERO      = V_ORDENDECOMPRA_RUBRO.NUMERO  
WHERE ORDENDECOMPRA.COMPANIA    = s$compania$s
  AND ORDENDECOMPRA.CLASEORDEN  = 's$claseOrden$s'
  AND ORDENDECOMPRA.NUMERO      = s$ordenDeCompra$s  
ORDER BY 
  D_ORDENDECOMPRA.ORDENDECOMPRA,
  D_ORDENDECOMPRA.CODIGO  
