MERGE INTO CONSULTAS FIN USING (SELECT '001861ElementosInseviblesSinBaja' INFORME ,TO_CLOB(q'[SELECT DEVOLUTIVO.COMPANIA,
  SUBSTR(ELEMENTO, 0,5) Grupo,
  DEVOLUTIVO.ELEMENTO,
  DEVOLUTIVO.SERIE,
  DEVOLUTIVO.TIPOMOVIMIENTOF,
  DEVOLUTIVO.MOVIMIENTOF,
  TO_CHAR(DEVOLUTIVO.FECHAULTMOV,'DD/MM/YYYY')AS FECHAULTMOV,
  (INVENTARIO.NOMBRELARGO || ' - Marca: ' || DEVOLUTIVO.MARCA || ' - Modelo: ' || DEVOLUTIVO.MODELO || ' - Serie: ' || DEVOLUTIVO.SERIEDEVOLUTIVO) NOMBRELARGO,
  DEVOLUTIVO.VALOR,
  DEVOLUTIVO.VALORULTIMOV,
  TIPOMOVIMIENTO.NOMBRE,
  TIPOMOVIMIENTO.CLASE,
  TIPOMOVIMIENTO.CONCEPTO
FROM DEVOLUTIVO
INNER JOIN INVENTARIO
ON DEVOLUTIVO.COMPANIA  = INVENTARIO.COMPANIA
AND DEVOLUTIVO.ELEMENTO = INVENTARIO.CODIGOELEMENTO
INNER JOIN TIPOMOVIMIENTO
ON DEVOLUTIVO.COMPANIA         = TIPOMOVIMIENTO.COMPANIA
AND DEVOLUTIVO.TIPOMOVIMIENTOF = TIPOMOVIMIENTO.CODIGO
WHERE DEVOLUTIVO.COMPANIA      = s$compania$s
AND DEVOLUTIVO.FECHAULTMOV BETWEEN   s$fechaInicial$s AND   s$fechaFinal$s
AND TIPOMOVIMIENTO.CLASE   = 'T'
AND TIPOMOVIMIENTO.CONCEPTO= 'DS']') CONSULTA, 10 APLICACION ,TO_CLOB(q'[(null)]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);