SELECT DISTINCT D_MOVIMIENTO.COMPANIA,
  D_MOVIMIENTO.TIPOMOVIMIENTO,
  D_MOVIMIENTO.MOVIMIENTO,
  SUM(D_MOVIMIENTO.VALORTOTAL) AS SUMADEVALORTOTAL,
  SUBSTR(ELEMENTO,1,5)         AS EXPR1,
  SUM(D_MOVIMIENTO.VALORIVA)   AS SUMADEVALORIVA,
  SUM (D_MOVIMIENTO.VALORTOTAL)-   SUM(D_MOVIMIENTO.VALORIVA) AS  SUMADEVALORBASE
 FROM D_MOVIMIENTO
 INNER JOIN MOVIMIENTO
    ON MOVIMIENTO.COMPANIA       = D_MOVIMIENTO.COMPANIA
   AND MOVIMIENTO.TIPOMOVIMIENTO = D_MOVIMIENTO.TIPOMOVIMIENTO
   AND MOVIMIENTO.NUMERO         = D_MOVIMIENTO.MOVIMIENTO
WHERE D_MOVIMIENTO.COMPANIA     = '$P!{PR_COMPANIA}'  
AND D_MOVIMIENTO.TIPOMOVIMIENTO = '$P!{PR_TIPO}'  
AND D_MOVIMIENTO.MOVIMIENTO BETWEEN s$movimientoInicial$s AND s$movimientoFinal$s
 GROUP BY D_MOVIMIENTO.COMPANIA,
  D_MOVIMIENTO.TIPOMOVIMIENTO,
  D_MOVIMIENTO.MOVIMIENTO,
  SUBSTR(ELEMENTO,1,5),
  MOVIMIENTO.AJUSTECENTAVOS1,
  MOVIMIENTO.AJUSTE_DEC_MANUAL
