SELECT 
    D_MOVIMIENTO.FECHA,
    D_MOVIMIENTO.ELEMENTO,
    INVENTARIO.NOMBRELARGO,
    INVENTARIO.UNIDAD,
    D_MOVIMIENTO.TIPOMOVIMIENTO,
    TIPOMOVIMIENTO.TIPOELEMENTO,
    TIPOMOVIMIENTO.CLASE,
    D_MOVIMIENTO.MOVIMIENTO,
    SUM(CASE WHEN TIPOMOVIMIENTO.CONCEPTO  NOT IN ('DT') THEN D_MOVIMIENTO.CANTIDAD ELSE 0 END)  CANTIDADSCL,
    SUM(CASE WHEN TIPOMOVIMIENTO.CONCEPTO  NOT IN ('DT') THEN D_MOVIMIENTO.VALORTOTAL ELSE 0 END) TVALORSCL,
    SUM(CASE WHEN TIPOMOVIMIENTO.CONCEPTO IN ('DT') THEN CANTIDAD ELSE 0 END) CANTIDADSCA,
    SUM(CASE WHEN TIPOMOVIMIENTO.CONCEPTO IN ('DT') THEN D_MOVIMIENTO.VALORTOTAL ELSE 0 END) TVALORSCA,
    SUM(CASE WHEN TIPOMOVIMIENTO.CONCEPTO  NOT IN ('DT') THEN D_MOVIMIENTO.VALORTOTAL ELSE 0 END) - 
    SUM(CASE WHEN TIPOMOVIMIENTO.CONCEPTO IN ('DT') THEN D_MOVIMIENTO.VALORTOTAL ELSE 0 END) TOTALEXISTENCIASALDO,
    SUM(CASE WHEN TIPOMOVIMIENTO.CONCEPTO  NOT IN ('DT') THEN D_MOVIMIENTO.CANTIDAD ELSE 0 END) -
    SUM(CASE WHEN TIPOMOVIMIENTO.CONCEPTO IN ('DT') THEN CANTIDAD ELSE 0 END) CANTIDADEXISTENCIA,
    MOVIMIENTO.TERCERO,
    DEPENDENCIA.NOMBRE  NOMBREDEPENDENCIA,
    MOVIMIENTO.DEPENDENCIA_DESTINO   DEPENDENCIA,
    CASE WHEN TERCERO.NOMBRE1 IN ('') THEN '' ELSE TERCERO.NOMBRE1 || '' END ||
    CASE WHEN TERCERO.NOMBRE2 IN ('') THEN '' ELSE TERCERO.NOMBRE2 || '' END ||
    CASE WHEN TERCERO.APELLIDO1 IN ('') THEN '' ELSE TERCERO.APELLIDO1 || '' END ||
    CASE WHEN TERCERO.APELLIDO2 IN ('') THEN '' ELSE TERCERO.APELLIDO2 END NOMBRERESONSABLE,
    SUBSTR(D_MOVIMIENTO.ELEMENTO,0,s$digitos$s)  AGRUPACION,
    INVENTARIOAGRUPACION.NOMBRELARGO NOMBREGRUPO
  FROM INVENTARIO
  LEFT JOIN D_MOVIMIENTO
  ON INVENTARIO.COMPANIA      = D_MOVIMIENTO.COMPANIA
  AND INVENTARIO.CODIGOELEMENTO = D_MOVIMIENTO.ELEMENTO
  LEFT JOIN INVENTARIO INVENTARIOAGRUPACION
  ON INVENTARIOAGRUPACION.COMPANIA      = D_MOVIMIENTO.COMPANIA
  AND INVENTARIOAGRUPACION.CODIGOELEMENTO = SUBSTR(D_MOVIMIENTO.ELEMENTO,0,s$digitos$s)
  LEFT JOIN TIPOMOVIMIENTO
  ON  D_MOVIMIENTO.COMPANIA      = TIPOMOVIMIENTO.COMPANIA 
  AND D_MOVIMIENTO.TIPOMOVIMIENTO = TIPOMOVIMIENTO.CODIGO
  INNER JOIN MOVIMIENTO
  ON D_MOVIMIENTO.COMPANIA       = MOVIMIENTO.COMPANIA
  AND D_MOVIMIENTO.TIPOMOVIMIENTO = MOVIMIENTO.TIPOMOVIMIENTO
  AND D_MOVIMIENTO.MOVIMIENTO      = MOVIMIENTO.NUMERO
  INNER JOIN DEPENDENCIA
  ON MOVIMIENTO.DEPENDENCIA_DESTINO = DEPENDENCIA.CODIGO
  AND MOVIMIENTO.COMPANIA   = DEPENDENCIA.COMPANIA
  LEFT JOIN RESPONSABLE
  ON MOVIMIENTO.COMPANIA = RESPONSABLE.COMPANIA
  AND MOVIMIENTO.TERCERO   = RESPONSABLE.CEDULA
  INNER JOIN TERCERO
  ON RESPONSABLE.COMPANIA = TERCERO.COMPANIA
  AND RESPONSABLE.CEDULA = TERCERO.NIT
  AND RESPONSABLE.SUCURSAL = TERCERO.SUCURSAL
   WHERE INVENTARIO.COMPANIA = s$compania$s
  AND TIPOMOVIMIENTO.CLASE IN ('S')
  AND MOVIMIENTO.DEPENDENCIA_DESTINO BETWEEN 's$dependenciaInicial$s' AND 's$dependenciaFinal$s'
  AND TIPOMOVIMIENTO.TIPOELEMENTO IN ('M')
  AND D_MOVIMIENTO.FECHA BETWEEN TO_DATE('s$fechaInicial$s','DD/MM/YYYY') AND TO_DATE('s$fechaFinal$s','DD/MM/YYYY') 
  AND MOVIMIENTO.TERCERO BETWEEN 's$responsableInicial$s' AND 's$responsableFinal$s'
 GROUP BY D_MOVIMIENTO.ELEMENTO,
    INVENTARIO.NOMBRELARGO,
    INVENTARIO.UNIDAD,
    D_MOVIMIENTO.TIPOMOVIMIENTO,
    D_MOVIMIENTO.MOVIMIENTO,
    D_MOVIMIENTO.FECHA,
    MOVIMIENTO.TERCERO,
    DEPENDENCIA.NOMBRE,
    MOVIMIENTO.DEPENDENCIA_DESTINO,
    CASE WHEN TERCERO.NOMBRE1 IN ('') THEN '' ELSE TERCERO.NOMBRE1 || '' END ||
    CASE WHEN TERCERO.NOMBRE2 IN ('') THEN '' ELSE TERCERO.NOMBRE2 || '' END ||
    CASE WHEN TERCERO.APELLIDO1 IN ('') THEN '' ELSE TERCERO.APELLIDO1 || '' END ||
    CASE WHEN TERCERO.APELLIDO2 IN ('') THEN '' ELSE TERCERO.APELLIDO2 END,
    SUBSTR(D_MOVIMIENTO.ELEMENTO,0,s$digitos$s),
    TIPOMOVIMIENTO.CLASE,
    TIPOMOVIMIENTO.TIPOELEMENTO,
    INVENTARIOAGRUPACION.NOMBRELARGO
