MERGE INTO CONSULTAS FIN USING (SELECT '002072MOEIDEAM' INFORME ,TO_CLOB(q'[SELECT
  V_MOVIMIENTO_INFORME.COMPANIA,
  V_MOVIMIENTO_INFORME.TIPOMOVIMIENTO,
  ELEMENTO CODIGO,
  TRIM(DESCRIPCION_INV) || ' / PLACA: ' || V_MOVIMIENTO_INFORME.SERIE NOMBRELARGO,
    CASE WHEN IND_REG IS NULL OR  IND_REG IN (0) THEN
  '  '
  ELSE
  'X' END NOREGISTRADO,
  TIPOMOVIMIENTO_NOM TIPOMOVIMIENTO_NOMBRE,
  TIPOMOVIMIENTO_NOMCORTO NOMBRECORTO,
  UNIDAD,
  CANTIDAD,
  VALORUNITARIO,
  VALORTOTAL_D VALORTOTAL,
   TO_CHAR(FECHA_MOV, 'DD')
  || ' de '
  || PCK_SYSMAN_UTL.FC_NOMBRE_MES(TO_CHAR(FECHA_MOV, 'MM'))
  || ' de '
  || TO_CHAR(FECHA_MOV, 'YYYY') FECHA ,
  V_MOVIMIENTO_INFORME.MOVASOCIADO,
TO_CHAR(V_MOVIMIENTO_INFORME.FECHAMOVASOCIADO,'DD/MM/YYYY') FECHAMOVASOCIADO,
  DESCRIPCION_MOV DESCRIPCION,
  DEPENDENCIA_DESTINO_NOM DEPENDENCIA_NOMBRE,
  RESPONSABLE_DESTINO_NOM TERCERO_NOMBRE,
  TIPOMOVASOCIADO_NOM DOCASOCIADO_NOMBRE,
  V_MOVIMIENTO_INFORME.RESPONSABLE_DESTINO CEDULA,
  NVL(V_MOVIMIENTO_INFORME.VALORDOCASOCIADO,0) VALORDOCASOCIADO,
  AJUSTECENTAVOS1_MOV AJUSTECENTAVOS1,
  TOTALCONAJUSTE_MOV TOTALCONAJUSTE,
  (V_MOVIMIENTO_INFORME.TIPOMOVIMIENTO || V_MOVIMIENTO_INFORME.MOVIMIENTO)  GRUPO,
  TIPOPESONA,
  AJUSTECENTAVOS_D DETALLEAJUSTE,
  V_MOVIMIENTO_INFORME.TERCERO NIT,
  V_MOVIMIENTO_INFORME.UNIDAD NUMERO,
  V_MOVIMIENTO_INFORME.DEPENDENCIA_DESTINO_NOM,
  V_MOVIMIENTO_INFORME.MOVIMIENTO,
  V_MOVIMIENTO_INFORME.RESPONSABLE_DESTINO_NOM,
  V_MOVIMIENTO_INFORME.RESPONSABLE_DESTINO,
  CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(U.NOMBRE1,' '), U.NOMBRE2),' '),U.APELLIDO1),' '),U.APELLIDO2) USUARIO,
  M.CREATED_BY,
  M.AUXILIAR,
  A.NOMBRE NOMBRE_AUXILIAR,
  M.ORFEO,
  V_MOVIMIENTO_INFORME.SERIE,
  V_MOVIMIENTO_INFORME.CODIGO AS CONSECUTIVO,
  TERCERO_NOM,
  M.DEPENDENCIA_DESTINO,
    CASE WHEN M.REGISTRADO IN (0)
  THEN 'EN ELABORACION'
  ELSE 'APROBADO'
  END ESTADO
FROM V_MOVIMIENTO_INFORME
LEFT JOIN MOVIMIENTO M
ON V_MOVIMIENTO_INFORME.COMPANIA = M.COMPANIA
AND V_MOVIMIENTO_INFORME.MOVIMIENTO = M.NUMERO
AND V_MOVIMIENTO_INFORME.TIPOMOVIMIENTO = M.TIPOMOVIMIENTO
INNER JOIN USUARIO U
ON M.CREATED_BY = U.CODIGO
LEFT JOIN AUXILIAR A
ON M.COMPANIA = A.COMPANIA
AND M.AUXILIAR = A.CODIGO
AND TO_CHAR(FECHA_MOV, 'YYYY') = A.ANO
WHERE   V_MOVIMIENTO_INFORME.COMPANIA       = s$compania$s
AND   V_MOVIMIENTO_INFORME.TIPOMOVIMIENTO = 's$tipoMovimiento$s'
AND   V_MOVIMIENTO_INFORME.MOVIMIENTO  BETWEEN s$movimientoInicial$s AND s$movimientoFinal$s
ORDER BY   MOVIMIENTO]') CONSULTA, 10 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, 'MROSERO' MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);