MERGE INTO CONSULTAS FIN USING (SELECT '002071MOIDEAM' INFORME ,TO_CLOB(q'[SELECT
	DISTINCT V_MOVIMIENTO_INFORME.COMPANIA ,
	V_MOVIMIENTO_INFORME.TIPOMOVIMIENTO ,
	V_MOVIMIENTO_INFORME.MOVIMIENTO NUMERO ,
	V_MOVIMIENTO_INFORME.CODIGO ,
	V_MOVIMIENTO_INFORME.ELEMENTO ,
	V_MOVIMIENTO_INFORME.SERIEDEVOLUTIVO ,
	V_MOVIMIENTO_INFORME.SERIE ,
	TIPOMOVIMIENTO_NOM ,
	TO_CHAR(FECHA_MOV, 'DD') || ' de' || PCK_SYSMAN_UTL.FC_NOMBRE_MES(TO_CHAR(FECHA_MOV, 'MM')) || ' de ' || TO_CHAR(FECHA_MOV, 'YYYY') FECHA ,
	V_MOVIMIENTO_INFORME.MOVASOCIADO ,
	TO_CHAR(V_MOVIMIENTO_INFORME.FECHAMOVASOCIADO , 'DD/MM/YYYY')AS FECHAMOVASOCIADO,
	RESPONSABLE_ORIGEN_NOM,
	V_MOVIMIENTO_INFORME.RESPONSABLE_ORIGEN NOMBRE_ORIGEN,
	V_MOVIMIENTO_INFORME.FACTURANO ,
	UNIDAD_NOM ,
	CANTIDAD ,
	TERCERO.NIT NIT_PROVEEDOR,
	TERCERO.NOMBRE NOMBRE_PROVEEDOR,
	NOMBRELARGO ||
	CASE
		WHEN TRIM(NVL(V_MOVIMIENTO_INFORME.ESPECIFICACION, '')) IS NULL THEN ' '
		ELSE ', ' || V_MOVIMIENTO_INFORME.ESPECIFICACION
	END ||
	CASE
		WHEN TRIM(NVL(V_MOVIMIENTO_INFORME.MARCA, '')) IS NOT NULL THEN ', MARCA: ' || V_MOVIMIENTO_INFORME.MARCA || ' '
		ELSE ''
	END ||
	CASE
		WHEN TRIM(NVL(V_MOVIMIENTO_INFORME.SERIEDEVOLUTIVO, '')) IS NOT NULL THEN ', SERIE: ' || V_MOVIMIENTO_INFORME.SERIEDEVOLUTIVO || ' '
		ELSE ''
	END ||
	CASE
		WHEN TRIM(NVL(V_MOVIMIENTO_INFORME.SERIE, '')) = 0 THEN ' '
		ELSE ', PLACA: ' || V_MOVIMIENTO_INFORME.SERIE
	END DESCRIPCIONELEMENTO ,
	VALORUNITARIO ,
	VALORTOTAL_D VALORTOTAL ,
	M.AJUSTECENTAVOS AJUSTECENT,
	M.AJUSTE_DEC_MANUAL,
	AJUSTECENTAVOS1_MOV AJUSTECENTAVOS ,
	V_MOVIMIENTO_INFORME.TOTALCONAJUSTE_MOV TOTALCONAJUSTE ,
	DESCRIPCION_MOV DESCRIPCION ,
	M.CREATED_BY,
	M.AUXILIAR,
	M.ORFEO,
	A.NOMBRE NOMBRE_AUXILIAR,
	CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(U.NOMBRE1, ' '), U.NOMBRE2), ' '), U.APELLIDO1), ' '), U.APELLIDO2) USUARIO,
	(M.TIPOMOVIMIENTO || V_MOVIMIENTO_INFORME.MOVIMIENTO) GRUPO,
	D.NIIF_VIDA_UTIL,
	CASE
		WHEN M.REGISTRADO IN (0) THEN 'EN ELABORACION'
		ELSE 'APROBADO'
	END ESTADO,
	M.VALORTOTAL VALORSUBTOTAL,
	M.VALORIVA,
	M.VALORTOTALCONIVA
FROM
	V_MOVIMIENTO_INFORME
INNER JOIN MOVIMIENTO M ON
	V_MOVIMIENTO_INFORME.COMPANIA = M.COMPANIA
	AND V_MOVIMIENTO_INFORME.MOVIMIENTO = M.NUMERO
	AND V_MOVIMIENTO_INFORME.TIPOMOVIMIENTO = M.TIPOMOVIMIENTO
LEFT JOIN DEVOLUTIVO D ON
	V_MOVIMIENTO_INFORME.COMPANIA = D.COMPANIA
	AND V_MOVIMIENTO_INFORME.MOVIMIENTO =
	CASE
		WHEN V_MOVIMIENTO_INFORME.CLASE = 'S' THEN D.MOVIMIENTOF
		ELSE D.MOVIMIENTOI
	END
	AND V_MOVIMIENTO_INFORME.SERIE = D.SERIE
	AND V_MOVIMIENTO_INFORME.TIPOMOVIMIENTO =
	CASE
		WHEN V_MOVIMIENTO_INFORME.CLASE = 'S' THEN D.TIPOMOVIMIENTOF
		ELSE D.TIPOMOVIMIENTOI
	END
INNER JOIN USUARIO U ON
	M.CREATED_BY = U.CODIGO
LEFT JOIN AUXILIAR A ON
	M.COMPANIA = A.COMPANIA
	AND M.ANO = A.ANO
        AND M.AUXILIAR = A.CODIGO
INNER JOIN TERCERO ON
	TERCERO.COMPANIA = M.COMPANIA
	AND TERCERO.SUCURSAL = M.SUCURSAL
	AND TERCERO.NIT = M.TERCERO
WHERE
	V_MOVIMIENTO_INFORME.COMPANIA = s$compania$s
	AND V_MOVIMIENTO_]') || TO_CLOB(q'[INFORME.TIPOMOVIMIENTO = 's$tipoMovimiento$s'
	AND V_MOVIMIENTO_INFORME.MOVIMIENTO BETWEEN s$movimientoInicial$s AND s$movimientoFinal$s
ORDER BY
	ELEMENTO,
	SERIE]') CONSULTA, 10 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);