MERGE INTO CONSULTAS FIN USING (SELECT '002109MOIDIACA' INFORME ,TO_CLOB(q'[SELECT  D_MOVIMIENTO.MOVIMIENTO,D_MOVIMIENTO.TIPOMOVIMIENTO, D_MOVIMIENTO.COMPANIA,
CASE TIPOMOVIMIENTO.TIPOPESONA 
  WHEN 'R' THEN TERCERO.NOMBRE || ', c.c. ' || RESPONSABLE.CEDULA
   ELSE TERCERO.NOMBRE || ', Tel: ' || TERCERO.TELEFONOS || ' , Nit: ' || TERCERO.NIT || CASE WHEN TERCERO.DIRECCION IS NULL THEN ''
   ELSE ', Dirección: ' || TERCERO.DIRECCION || '' 
   END || CASE WHEN TERCERO.FAX IS NULL THEN '' ELSE '  ,Fax:' || TERCERO.FAX END
 END DESC_TIPOPERSONA,
  PCK_ALMACEN_COM4.FC_NUMREQUISICIONES(D_MOVIMIENTO.COMPANIA,NVL(MOVIMIENTO.TIPOMOVASOCIADO,'A'),NVL(MOVIMIENTO.MOVASOCIADO,1),NVL(MOVIMIENTO.MOVASOCIADO,1)) AS NUMREQ,
  D_MOVIMIENTO.ELEMENTO, 
  D_MOVIMIENTO.SERIE, 
  CASE D_MOVIMIENTO.IND_REG 
      WHEN  -1 THEN ''  
      ELSE '*' 
  END NOREGISTRADO ,  
  TIPOMOVIMIENTO.TIPOPESONA, 
  CASE TIPOMOVIMIENTO.TIPOPESONA WHEN 'R'
    THEN TER_RESP.NOMBRE
    ELSE TERCERO.NOMBRE
  END NOM_TIPOPERSONA,
  D_MOVIMIENTO.CANTIDAD, 
  D_MOVIMIENTO.VALORUNITARIO, 
  D_MOVIMIENTO.VALORTOTAL ,
  MOVIMIENTO.MOVASOCIADO,
  TO_CHAR(MOVIMIENTO.FECHAMOVASOCIADO, 'DD/MM/YYYY')FECHAMOVASOCIADO,  
  MOVIMIENTO.FACTURANO, 
  MOVIMIENTO.REMISIONNO , 
  DOCASOCIADO.NOMBRE AS NOMBRE_DOCASOC,
  UNIDAD.NOMBRE AS NOMBREUNIDAD, 
  MOVIMIENTO.AJUSTECENTAVOS1,
  MOVIMIENTO.TOTALCONAJUSTE, 
  MOVIMIENTO.AUXILIAR,
  AUXILIAR.NOMBRE AS NOMBRE_AUXILIAR,
  D_MOVIMIENTO.AJUSTECENTAVOS AS AJUSTEDETALLE, 
  MOVIMIENTO.AJUSTE_DEC_MANUAL, 
  MOVIMIENTO.TERCERO,
  MOVIMIENTO.DESCRIPCION,
  TIPOMOVIMIENTO.NOMBRE AS NOMBRE_TIPOMOV,
  CASE WHEN INVENTARIO.NOMBRELARGO IS NULL THEN '' ELSE
   INVENTARIO.NOMBRELARGO END ||
    CASE WHEN  D_MOVIMIENTO.ESPECIFICACION IS NULL THEN '' ELSE
      ' Especificación: '|| D_MOVIMIENTO.ESPECIFICACION END ||
    CASE WHEN  D_MOVIMIENTO.MARCA IS NULL THEN '' ELSE
       ' Marca: '|| D_MOVIMIENTO.MARCA END ||
    CASE WHEN  D_MOVIMIENTO.SERIE IS NULL THEN '' ELSE
       ' Serie: '|| D_MOVIMIENTO.SERIE END  NOMBRELARGO,
       RESPONSABLE.CARGO,
       TERCERO.NOMBRE NOMBRETERCERO,
       TER_RESP.NOMBRE NOMBRERESPONSABLE,
       MOVIMIENTO.CENTRODECOSTO AS CENTRO_COSTO
,
TO_CHAR(MOVIMIENTO.FECHA, 'DD/MM/YYYY')FECHA
  FROM D_MOVIMIENTO
INNER JOIN INVENTARIO
ON D_MOVIMIENTO.COMPANIA = INVENTARIO.COMPANIA 
AND D_MOVIMIENTO.ELEMENTO  = INVENTARIO.CODIGOELEMENTO
LEFT JOIN UNIDAD
ON INVENTARIO.UNIDAD = UNIDAD.UNIDAD
INNER JOIN MOVIMIENTO
ON D_MOVIMIENTO.COMPANIA        = MOVIMIENTO.COMPANIA
AND D_MOVIMIENTO.TIPOMOVIMIENTO = MOVIMIENTO.TIPOMOVIMIENTO
AND D_MOVIMIENTO.MOVIMIENTO     = MOVIMIENTO.NUMERO
INNER JOIN TERCERO
ON MOVIMIENTO.COMPANIA = TERCERO.COMPANIA
AND MOVIMIENTO.TERCERO   = TERCERO.NIT
AND MOVIMIENTO.SUCURSAL = TERCERO.SUCURSAL
INNER JOIN DEPENDENCIA
ON MOVIMIENTO.COMPANIA   = DEPENDENCIA.COMPANIA 
AND MOVIMIENTO.DEPENDENCIA_DESTINO = DEPENDENCIA.CODIGO
LEFT JOIN DOCASOCIADO
ON MOVIMIENTO.TIPOMOVASOCIADO = DOCASOCIADO.CODIGO
INNER JOIN RESPONSABLE
ON MOVIMIENTO.COMPA]') || TO_CLOB(q'[NIA         = RESPONSABLE.COMPANIA 
AND MOVIMIENTO.RESPONSABLE_DESTINO           = RESPONSABLE.CEDULA
AND MOVIMIENTO.SUCURSAL_RESDESTINO           = RESPONSABLE.SUCURSAL
INNER JOIN TERCERO TER_RESP
ON RESPONSABLE.COMPANIA = TER_RESP.COMPANIA
AND RESPONSABLE.SUCURSAL = TER_RESP.SUCURSAL
AND RESPONSABLE.CEDULA = TER_RESP.NIT
INNER JOIN TIPOMOVIMIENTO
ON MOVIMIENTO.COMPANIA        = TIPOMOVIMIENTO.COMPANIA
AND MOVIMIENTO.TIPOMOVIMIENTO = TIPOMOVIMIENTO.CODIGO
INNER JOIN AUXILIAR
ON MOVIMIENTO.COMPANIA = AUXILIAR.COMPANIA 
AND MOVIMIENTO.ANO  = AUXILIAR.ANO
AND MOVIMIENTO.AUXILIAR  = AUXILIAR.CODIGO
WHERE D_MOVIMIENTO.COMPANIA   = s$compania$s
AND D_MOVIMIENTO.TIPOMOVIMIENTO = 's$tipoMovimiento$s'
AND D_MOVIMIENTO.MOVIMIENTO BETWEEN s$movimientoInicial$s AND s$movimientoFinal$s
ORDER BY D_MOVIMIENTO.COMPANIA,
  D_MOVIMIENTO.TIPOMOVIMIENTO,
  D_MOVIMIENTO.MOVIMIENTO,
  D_MOVIMIENTO.ELEMENTO ASC,
  D_MOVIMIENTO.SERIE ASC]') CONSULTA, 10 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);