MERGE INTO CONSULTAS FIN USING (SELECT '002418CIERRECONTABLECONSUMO' INFORME ,TO_CLOB(q'[SELECT M.TIPOMOVIMIENTO, M.NUMERO,
 '0' GRUPO,
(CASE 
    WHEN T.CLASE = 'E'
    THEN A.CUENTADEBITO
    ELSE A.CUENTACREDITO
END) AS CUENTA_CONTABLE, 
(CASE 
    WHEN T.CLASE = 'E'
    THEN 'INGRESO'
    ELSE 'EGRESO'
END) AS TIPO_MOVIMIENTO,

(CASE 
    WHEN T.CLASE = 'E'
    THEN M.VALORTOTAL
    ELSE 0.00
END) AS DEBITOS,
(CASE 
    WHEN T.CLASE = 'S'
    THEN M.VALORTOTAL
    ELSE 0.00  
END) AS CREDITOS
FROM MOVIMIENTO M INNER JOIN TIPOMOVIMIENTO T
ON M.COMPANIA = T.COMPANIA 
AND M.TIPOMOVIMIENTO = T.CODIGO
INNER JOIN D_MOVIMIENTO DM 
ON M.COMPANIA = DM.COMPANIA
AND M.TIPOMOVIMIENTO = DM.TIPOMOVIMIENTO
AND M.NUMERO = DM.MOVIMIENTO
LEFT JOIN ALMACENCONTABILIDAD A 
ON DM.COMPANIA = A.COMPANIA
AND SUBSTR(DM.ELEMENTO,3) = A.CODIGOELEMENTO
AND DM.TIPOMOVIMIENTO = A.TIPOMOVIMIENTO
AND TO_NUMBER(TO_CHAR(DM.FECHA, 'YYYY')) = A.ANO
WHERE M.COMPANIA = s$compania$s
AND T.TIPOELEMENTO = 'C'
AND M.FECHA BETWEEN 's$fechaini$s' AND 's$fechafin$s'
GROUP BY M.TIPOMOVIMIENTO, M.NUMERO, 
(CASE 
    WHEN T.CLASE = 'E'
    THEN A.CUENTADEBITO
    ELSE A.CUENTACREDITO
END), 
(CASE 
    WHEN T.CLASE = 'E'
    THEN 'INGRESO'
    ELSE 'EGRESO'
END),

(CASE 
    WHEN T.CLASE = 'E'
    THEN M.VALORTOTAL
    ELSE 0.00
END),
(CASE 
    WHEN T.CLASE = 'S'
    THEN M.VALORTOTAL
    ELSE 0.00  
END)
ORDER BY 
CUENTA_CONTABLE ASC,
TIPO_MOVIMIENTO,
M.NUMERO ASC
]') CONSULTA, 10 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);