MERGE INTO CONSULTAS FIN USING (SELECT '002494SaldoEntrElemSinPromediar' INFORME ,TO_CLOB(q'[SELECT CODIGOPROYECTO PROYECTO,
    BODEGA,
    ELEMENTO,
    NOMBRELARGO DESCRIPCION,  
    CUENTADEBITO CUENTA_CONTABLE,
    SUM(CANT_ENTRADA) CANTIDAD,
    SUM(VAL_UNITARIO_ENT) VAL_UNITARIO,
    SUM(VAL_TOTAL_ENT) VAL_TOTAL,
    TIPO_INGRESO,
    INGRESO,
    VIG_INGRESO,
    (CASE WHEN SUM(CANT_ENTRADA - CANT_SALIDA) IS NULL 
        THEN SUM(CANT_ENTRADA)
        ELSE SUM(CANT_ENTRADA - CANT_SALIDA)
    END) SALDO_CANT,
    MOVASOCIADO,
    OPERACION,
    AUXILIAR,
    RUEDA
FROM(
    SELECT D_MOVIMIENTO.CODIGOPROYECTO,
        (CASE WHEN MOVIMIENTO.CLASE_BODEGA_DESTINO IN (20)
            THEN BODEGA_DESTINO
        END) BODEGA,
        D_MOVIMIENTO.ELEMENTO,
        INVENTARIO.NOMBRELARGO,
        ALMACENCONTABILIDAD.CUENTADEBITO,
        SUM(D_MOVIMIENTO.CANTIDAD) CANT_ENTRADA,
        SUM(D_MOVIMIENTO.VALORUNITARIO) VAL_UNITARIO_ENT,
        SUM(D_MOVIMIENTO.VALORTOTAL) VAL_TOTAL_ENT,
        SUM(SALDO.CANTIDAD) CANT_SALIDA,
        (TIPOMOVIMIENTO.CODIGO || ' - ' || TIPOMOVIMIENTO.NOMBRE) TIPO_INGRESO,
        D_MOVIMIENTO.MOVIMIENTO INGRESO,
        TO_NUMBER(TO_CHAR(D_MOVIMIENTO.FECHA, 'YYYY')) VIG_INGRESO,
        D_MOVIMIENTO.MOVASOCIADO,
        D_MOVIMIENTO.OPERACION,
        D_MOVIMIENTO.AUXILIAR,
        D_MOVIMIENTO.RUEDA
FROM MOVIMIENTO
INNER JOIN D_MOVIMIENTO
ON MOVIMIENTO.COMPANIA = D_MOVIMIENTO.COMPANIA
AND MOVIMIENTO.TIPOMOVIMIENTO = D_MOVIMIENTO.TIPOMOVIMIENTO
AND MOVIMIENTO.NUMERO = D_MOVIMIENTO.MOVIMIENTO
INNER JOIN INVENTARIO
ON D_MOVIMIENTO.COMPANIA = INVENTARIO.COMPANIA
AND D_MOVIMIENTO.ELEMENTO = INVENTARIO.CODIGOELEMENTO
LEFT JOIN ALMACENCONTABILIDAD
ON D_MOVIMIENTO.COMPANIA = ALMACENCONTABILIDAD.COMPANIA
AND SUBSTR(D_MOVIMIENTO.ELEMENTO,1,PCK_SYSMAN_UTL.FC_PAR(D_MOVIMIENTO.COMPANIA,'DIGITOS AGRUPACION INVENTARIO',PCK_DATOS.FC_MODULOALMACEN,SYSDATE)) = ALMACENCONTABILIDAD.CODIGOELEMENTO
AND D_MOVIMIENTO.TIPOMOVIMIENTO = ALMACENCONTABILIDAD.TIPOMOVIMIENTO
AND TO_NUMBER(TO_CHAR(D_MOVIMIENTO.FECHA, 'YYYY')) =  ALMACENCONTABILIDAD.ANO
INNER JOIN TIPOMOVIMIENTO
ON TIPOMOVIMIENTO.COMPANIA = D_MOVIMIENTO.COMPANIA
AND TIPOMOVIMIENTO.CODIGO = D_MOVIMIENTO.TIPOMOVIMIENTO
LEFT JOIN(
    SELECT D_MOVIMIENTO.COMPANIA,
        D_MOVIMIENTO.CODIGOPROYECTO,
        (CASE WHEN MOVIMIENTO.CLASE_BODEGA_ORIGEN IN (20)
            THEN BODEGA_ORIGEN
        END) BODEGA,
        D_MOVIMIENTO.ELEMENTO,
    SUM(D_MOVIMIENTO.CANTIDAD) CANTIDAD,
    D_MOVIMIENTO.MOVASOCIADO,
    D_MOVIMIENTO.OPERACION,
    D_MOVIMIENTO.AUXILIAR,
    D_MOVIMIENTO.RUEDA
FROM MOVIMIENTO
INNER JOIN D_MOVIMIENTO
ON MOVIMIENTO.COMPANIA = D_MOVIMIENTO.COMPANIA
AND MOVIMIENTO.TIPOMOVIMIENTO = D_MOVIMIENTO.TIPOMOVIMIENTO
AND MOVIMIENTO.NUMERO = D_MOVIMIENTO.MOVIMIENTO
INNER JOIN INVENTARIO
ON D_MOVIMIENTO.COMPANIA = INVENTARIO.COMPANIA
AND D_MOVIMIENTO.ELEMENTO = INVENTARIO.CODIGOELEMENTO
WHERE MOVIMIENTO.COMPANIA = s$compania$s
AND INVENTARIO.TIPO IN('C')
AND D_MOVIMIENTO.FECHA <= s$fechaCorte$s
AND (CASE WHEN MOVIMIENTO.CLASE_BODEGA_ORIGEN IN (20)
        THEN BO]') || TO_CLOB(q'[DEGA_ORIGEN
    END) IS NOT NULL
GROUP BY D_MOVIMIENTO.COMPANIA,
    D_MOVIMIENTO.CODIGOPROYECTO,
    (CASE WHEN MOVIMIENTO.CLASE_BODEGA_ORIGEN IN (20)
        THEN BODEGA_ORIGEN
    END),
    D_MOVIMIENTO.ELEMENTO,
    D_MOVIMIENTO.MOVASOCIADO,
    D_MOVIMIENTO.OPERACION,
    D_MOVIMIENTO.AUXILIAR,
    D_MOVIMIENTO.RUEDA
) SALDO
ON D_MOVIMIENTO.COMPANIA = SALDO.COMPANIA
AND D_MOVIMIENTO.CODIGOPROYECTO = SALDO.CODIGOPROYECTO
AND (CASE WHEN MOVIMIENTO.CLASE_BODEGA_DESTINO IN (20)
        THEN BODEGA_DESTINO
    END) = SALDO.BODEGA
AND D_MOVIMIENTO.ELEMENTO = SALDO.ELEMENTO
AND D_MOVIMIENTO.MOVASOCIADO = SALDO.MOVASOCIADO
AND D_MOVIMIENTO.OPERACION = SALDO.OPERACION
AND D_MOVIMIENTO.AUXILIAR = SALDO.AUXILIAR
AND D_MOVIMIENTO.RUEDA = SALDO.RUEDA
WHERE MOVIMIENTO.COMPANIA = s$compania$s
AND INVENTARIO.TIPO IN('C')
AND D_MOVIMIENTO.FECHA <= s$fechaCorte$s
AND (CASE WHEN MOVIMIENTO.CLASE_BODEGA_DESTINO IN (20)
        THEN BODEGA_DESTINO
    END) IS NOT NULL
GROUP BY D_MOVIMIENTO.CODIGOPROYECTO,
    (CASE WHEN MOVIMIENTO.CLASE_BODEGA_DESTINO IN (20)
        THEN BODEGA_DESTINO
    END),
    D_MOVIMIENTO.ELEMENTO,
    INVENTARIO.NOMBRELARGO,
    ALMACENCONTABILIDAD.CUENTADEBITO,
    (TIPOMOVIMIENTO.CODIGO || ' - ' || TIPOMOVIMIENTO.NOMBRE),
    D_MOVIMIENTO.MOVIMIENTO,
    TO_NUMBER(TO_CHAR(D_MOVIMIENTO.FECHA, 'YYYY')),
    D_MOVIMIENTO.MOVASOCIADO,
    D_MOVIMIENTO.OPERACION,
    D_MOVIMIENTO.AUXILIAR,
    D_MOVIMIENTO.RUEDA)
WHERE CODIGOPROYECTO BETWEEN s$proyectoIni$s AND s$proyectoFin$s
AND BODEGA BETWEEN s$bodegaIni$s AND s$bodegaFin$s
AND ELEMENTO BETWEEN s$elementoIni$s AND s$elementoFin$s
GROUP BY CODIGOPROYECTO,
    BODEGA,
    ELEMENTO,
    NOMBRELARGO,  
    CUENTADEBITO,
    TIPO_INGRESO,
    INGRESO,
    VIG_INGRESO,
    MOVASOCIADO,
    OPERACION,
    AUXILIAR,
    RUEDA
ORDER BY CODIGOPROYECTO,
    BODEGA,
    ELEMENTO]') CONSULTA, 10 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, 'JCROJAS' CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);