MERGE INTO CONSULTAS FIN USING (SELECT '002595PazySalvoPorTerceroTocan' INFORME ,TO_CLOB(q'[SELECT DEPENDENCIA.NOMBRE DEPENDENCIA, 
TERCERO.NOMBRE NOMBRE_RESPONSABLE, 
RESPONSABLE.CEDULA, 
RESPONSABLE.CARGO, 
DEPENDENCIA_RESPONSABLE.RESPONSABLE
FROM DEPENDENCIA_RESPONSABLE 
  LEFT JOIN DEPENDENCIA ON DEPENDENCIA_RESPONSABLE.COMPANIA = DEPENDENCIA.COMPANIA
    AND DEPENDENCIA_RESPONSABLE.DEPENDENCIA = DEPENDENCIA.CODIGO
  LEFT JOIN RESPONSABLE ON DEPENDENCIA_RESPONSABLE.COMPANIA = RESPONSABLE.COMPANIA
    AND DEPENDENCIA_RESPONSABLE.RESPONSABLE = RESPONSABLE.CEDULA
    AND DEPENDENCIA_RESPONSABLE.SUCURSAL = RESPONSABLE.SUCURSAL
  INNER JOIN TERCERO ON RESPONSABLE.COMPANIA = TERCERO.COMPANIA
    AND RESPONSABLE.CEDULA = TERCERO.NIT
    AND RESPONSABLE.SUCURSAL = TERCERO.SUCURSAL
WHERE DEPENDENCIA_RESPONSABLE.COMPANIA = s$compania$s
AND RESPONSABLE.CEDULA = 's$responsable$s']') CONSULTA, 10 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);
