MERGE INTO CONSULTAS FIN USING (SELECT '002727CInvIndivDevoluResponFl' INFORME ,TO_CLOB(q'[SELECT SUBSTR(DEVOLUTIVO.ELEMENTO,0,3) AGRUPACION, 
    DEVOLUTIVO.DEPENDENCIA CODIGO_DEPENDENCIA, 
    DEPENDENCIA.NOMBRE DEPENDENCIA, 
    ESTADODEVOLUTIVO.DESCRIPCION,
    DEPENDENCIA_RESPONSABLE.SUPERVISOR,
    DEPENDENCIA_RESPONSABLE.SUCURSAL_SUPERVISOR,
    TERCERO_SUP.NOMBRE NOMBRE_SUPERVISOR,
    DEVOLUTIVO.RESPONSABLE DOCUMENTO_RESPONSABLE,
    INVENTARIO.NOMBRELARGO ELEMENTO,
    PCK_ALMACEN.FC_NOMBREINVENTARIO(DEVOLUTIVO.COMPANIA,SUBSTR(DEVOLUTIVO.ELEMENTO,0,3),0) GRUPO,
    CASE WHEN DEVOLUTIVO.MARCA IS NULL OR DEVOLUTIVO.MARCA = '.'
       THEN DEVOLUTIVO.DESCRIPCION
       ELSE 'Marca: '||DEVOLUTIVO.MARCA||' '||DEVOLUTIVO.DESCRIPCION 
    END NOMBRELARGO,
    TERCERO.NOMBRE RESPONSABLE,
    DEVOLUTIVO.SERIE, 
    DEVOLUTIVO.SERIEDEVOLUTIVO,
    DEVOLUTIVO.VALOR VALOR_TOTAL,
    NVL(DEPRECIACION.VLRLIBROS,DEVOLUTIVO.VALOR) VLR_LIBROS
FROM DEVOLUTIVO 
LEFT JOIN INVENTARIO
ON DEVOLUTIVO.COMPANIA = INVENTARIO.COMPANIA
AND DEVOLUTIVO.ELEMENTO = INVENTARIO.CODIGOELEMENTO
LEFT JOIN TERCERO 
ON DEVOLUTIVO.COMPANIA = TERCERO.COMPANIA         
AND DEVOLUTIVO.RESPONSABLE = TERCERO.NIT 
AND DEVOLUTIVO.SUCURSAL_RESPONSABLE = TERCERO.SUCURSAL 
LEFT JOIN DEPENDENCIA 
ON DEVOLUTIVO.COMPANIA = DEPENDENCIA.COMPANIA 
AND DEVOLUTIVO.DEPENDENCIA = DEPENDENCIA.CODIGO
LEFT JOIN DEPENDENCIA_RESPONSABLE  
ON DEVOLUTIVO.COMPANIA = DEPENDENCIA_RESPONSABLE.COMPANIA
AND DEVOLUTIVO.DEPENDENCIA = DEPENDENCIA_RESPONSABLE.DEPENDENCIA
AND DEVOLUTIVO.RESPONSABLE = DEPENDENCIA_RESPONSABLE.RESPONSABLE
AND DEVOLUTIVO.SUCURSAL_RESPONSABLE = DEPENDENCIA_RESPONSABLE.SUCURSAL
LEFT JOIN TERCERO TERCERO_SUP
ON DEPENDENCIA_RESPONSABLE.COMPANIA = TERCERO_SUP.COMPANIA         
AND DEPENDENCIA_RESPONSABLE.SUPERVISOR = TERCERO_SUP.NIT 
AND DEPENDENCIA_RESPONSABLE.SUCURSAL_SUPERVISOR = TERCERO_SUP.SUCURSAL 
LEFT JOIN ESTADODEVOLUTIVO 
ON DEVOLUTIVO.ESTADO = ESTADODEVOLUTIVO.ESTADO
LEFT JOIN(
    SELECT DEPRECIAR.COMPANIA,
        DEPRECIAR.ELEMENTO,
        DEPRECIAR.SERIE,
        CASE WHEN PCK_SYSMAN_UTL.FC_PAR(DEPRECIAR.COMPANIA,'MANEJA NIIF EN ALMACEN',10,DEPRECIAR.PERIODO)='SI'
            THEN DEPRECIAR.NIIF_VLRLIBROS
            ELSE DEPRECIAR.VLRLIBROS
        END VLRLIBROS
    FROM DEPRECIAR 
    INNER JOIN(SELECT COMPANIA, 
                   ELEMENTO, 
                   SERIE, 
                   MAX(PERIODO) PERIODO
               FROM DEPRECIAR
               WHERE COMPANIA = s$compania$s
                  AND DEPRECIAR.PERIODO <= s$fechaCorte$s
               GROUP BY COMPANIA, 
                  ELEMENTO, 
                  SERIE) ULTIMO
    ON DEPRECIAR.COMPANIA = ULTIMO.COMPANIA
    AND DEPRECIAR.ELEMENTO = ULTIMO.ELEMENTO
    AND DEPRECIAR.SERIE = ULTIMO.SERIE
    AND DEPRECIAR.PERIODO = ULTIMO.PERIODO
    WHERE DEPRECIAR.COMPANIA = s$compania$s
        AND DEPRECIAR.PERIODO <= s$fechaCorte$s) DEPRECIACION
ON DEVOLUTIVO.COMPANIA = DEPRECIACION.COMPANIA
AND DEVOLUTIVO.ELEMENTO = DEPRECIACION.ELEMEN]') || TO_CLOB(q'[TO
AND DEVOLUTIVO.SERIE = DEPRECIACION.SERIE
WHERE DEVOLUTIVO.COMPANIA    = s$compania$s
  AND DEVOLUTIVO.RESPONSABLE = 's$responsable$s'
  AND DEVOLUTIVO.PLACAANULADA IN (0)]') CONSULTA, 10 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);