MERGE INTO CONSULTAS FIN USING (SELECT '002818IIamortizacionMesDependencia_CON' INFORME ,TO_CLOB(q'[SELECT DISTINCT
  DEPRECIAR.ELEMENTO,
  DEPRECIAR.SERIE,
  TO_CHAR(DEVOLUTIVO.FECHAADQUISICION , 'DD/MM/YYYY') AS FECHA_ADQUISICION,
  INVENTARIO.NOMBRELARGO ||' '|| SUBSTR(DEVOLUTIVO.DESCRIPCION,1,3500) || CASE WHEN TRIM(DEVOLUTIVO.MARCA) IS NULL THEN '' ELSE ' MARCA: ' ||DEVOLUTIVO.MARCA END NOMBRELARGOS,
  CASE  WHEN PCK_SYSMAN_UTL.FC_PAR(DEPRECIAR.COMPANIA,'MANEJA NIIF EN ALMACEN',10,DEPRECIAR.PERIODO)='SI'
             THEN DEPRECIAR.NIIF_VLRELEMENTO
             ELSE DEPRECIAR.VLRELEMENTO
             END VLRELEMENTO,
  CASE  WHEN PCK_SYSMAN_UTL.FC_PAR(DEPRECIAR.COMPANIA,'MANEJA NIIF EN ALMACEN',10,DEPRECIAR.PERIODO)='SI'
             THEN DEPRECIAR.NIIF_COSTOAJUSTADO
             ELSE DEPRECIAR.COSTOAJUSTADO
             END COSTOAJUSTADO,
    CASE WHEN TO_DATE('s$ultimoDia$s','DD/MM/YYYY')>= REEXPRESARVIDAUTIL.FECHACAMBIO
            THEN REEXPRESARVIDAUTIL.DETERIORO
            ELSE DEVOLUTIVO.DETERIORO
     END DETERIORO,
  CASE  WHEN PCK_SYSMAN_UTL.FC_PAR(DEPRECIAR.COMPANIA,'MANEJA NIIF EN ALMACEN',10,DEPRECIAR.PERIODO)='SI'
             THEN DEPRECIAR.NIIF_VLRDEPRECIACION
             ELSE DEPRECIAR.VLRDEPRECIACION
             END VLRDEPRECIACION,
  CASE  WHEN PCK_SYSMAN_UTL.FC_PAR(DEPRECIAR.COMPANIA,'MANEJA NIIF EN ALMACEN',10,DEPRECIAR.PERIODO)='SI'
             THEN DEPRECIAR.NIIF_DEPACUMULADA
             ELSE DEPRECIAR.DEPACUMULADA
             END DEPACUMULADA,
  CASE  WHEN PCK_SYSMAN_UTL.FC_PAR(DEPRECIAR.COMPANIA,'MANEJA NIIF EN ALMACEN',10,DEPRECIAR.PERIODO)='SI'
             THEN DEPRECIAR.NIIF_VLRLIBROS
             ELSE DEPRECIAR.VLRLIBROS
             END VLRLIBROS,
  CASE  WHEN PCK_SYSMAN_UTL.FC_PAR(DEPRECIAR.COMPANIA,'MANEJA NIIF EN ALMACEN',10,DEPRECIAR.PERIODO)='SI'
            THEN NIIF_INVENTARIOCONTA.CUENTACREDITO
            ELSE INVENTARIOCONTABILIDAD.DEPRECCREDITOS
            END CODIGOCUENTA,
  CASE  WHEN PCK_SYSMAN_UTL.FC_PAR(DEPRECIAR.COMPANIA,'MANEJA NIIF EN ALMACEN',10,DEPRECIAR.PERIODO)='SI'
            THEN PLAN_CONTABLE.NOMBRE
            ELSE PLANCONTABLE.NOMBRE
            END    NOMBRECUENTA,
  SUBSTR(DEPRECIAR.ELEMENTO, 1, s$agrupacion$s) AGRUPACION,
  PCK_ALMACEN_COM1.FC_DEPRECIACIONCOMODATO(DEPRECIAR.COMPANIA,'s$elementoInicial$s', 's$elementoFinal$s', s$anio$s, s$mes$s, ''''||SUBSTR(DEPRECIAR.ELEMENTO, 1, 3)||'''', 1) DEPRECIACION,
  PCK_ALMACEN.FC_NOMBREINVENTARIO(DEPRECIAR.COMPANIA, SUBSTR(DEPRECIAR.ELEMENTO, 1, s$agrupacion$s),0) NOMBREINVENTARIO,
  CASE WHEN PCK_SYSMAN_UTL.FC_PAR(DEPRECIAR.COMPANIA,'MANEJA NIIF EN ALMACEN',10,DEPRECIAR.PERIODO)='SI'
        THEN DEVOLUTIVO.NIIF_VIDA_UTIL
        ELSE CASE WHEN DEVOLUTIVO.MESESVIDAUTILPLACA NOT IN(0)
                THEN DEVOLUTIVO.MESESVIDAUTILPLACA
                ELSE ACTDEPRECIABLE.MESESVIDAUTIL
             END
    END MESES_VIDA_UTIL,
    BODEGA.NOMBRE NOMBRE_BODEGA,
    DEVOLUTIVO.SALVAMENTO VLRRESIDUAL
FROM DEPRECIAR
  INNER JOIN DEVOLUTIVO
    ON DEPRECIAR.COMPANIA = DEVOLUTIVO.COMPANIA
    AND DEPRECIAR.ELEMENTO = DEVOLUTIVO.ELEMENTO
  ]') || TO_CLOB(q'[  AND DEPRECIAR.SERIE = DEVOLUTIVO.SERIE
  LEFT JOIN INVENTARIO
    ON DEPRECIAR.COMPANIA = INVENTARIO.COMPANIA
    AND DEPRECIAR.ELEMENTO = INVENTARIO.CODIGOELEMENTO
LEFT JOIN NIIF_INVENTARIOCONTA ON
    DEPRECIAR.COMPANIA = NIIF_INVENTARIOCONTA.COMPANIA
    AND SUBSTR(DEPRECIAR.ELEMENTO, 1, s$agrupacion$s) = NIIF_INVENTARIOCONTA.CODIGOELEMENTO
    AND DEPRECIAR.ANO = NIIF_INVENTARIOCONTA.ANO
    AND DEPRECIAR.BODEGA = NIIF_INVENTARIOCONTA.BODEGA
    AND DEPRECIAR.NIIF_TIPO_ACTIVO = NIIF_INVENTARIOCONTA.TIPOACTIVO
    AND DEPRECIAR.CENTRO_COSTO = NIIF_INVENTARIOCONTA.CENTRO_COSTO
  LEFT JOIN PLAN_CONTABLE
    ON NIIF_INVENTARIOCONTA.COMPANIA = PLAN_CONTABLE.COMPANIA
    AND NIIF_INVENTARIOCONTA.CUENTACREDITO = PLAN_CONTABLE.CODIGO
    AND NIIF_INVENTARIOCONTA.ANO = PLAN_CONTABLE.ANO
  LEFT JOIN INVENTARIOCONTABILIDAD ON
    DEPRECIAR.COMPANIA = INVENTARIOCONTABILIDAD.COMPANIA
    AND SUBSTR(DEPRECIAR.ELEMENTO, 1, s$agrupacion$s) = INVENTARIOCONTABILIDAD.CODIGOELEMENTO
    AND DEPRECIAR.ANO = INVENTARIOCONTABILIDAD.ANO
   LEFT JOIN PLAN_CONTABLE PLANCONTABLE
    ON INVENTARIOCONTABILIDAD.COMPANIA = PLANCONTABLE.COMPANIA
    AND INVENTARIOCONTABILIDAD.DEPRECCREDITO = PLANCONTABLE.CODIGO
    AND INVENTARIOCONTABILIDAD.ANO = PLANCONTABLE.ANO
  INNER JOIN BODEGA
    ON DEPRECIAR.COMPANIA = BODEGA.COMPANIA
    AND DEPRECIAR.BODEGA = BODEGA.CODIGO
  LEFT JOIN (
         SELECT
             RV.COMPANIA,
             RV.ELEMENTO,
             RV.SERIE,
             RV.FECHACAMBIO,
             REEXVIDA.VIDAUTIL,
             RV.NIIF_COSTOAJUSTADO,
             RV.DETERIORO,
             RV.NIIF_VLRACUMULADO
         FROM
             (SELECT REEXPRESARVIDAUTIL.COMPANIA,
                     REEXPRESARVIDAUTIL.ELEMENTO,
                     REEXPRESARVIDAUTIL.SERIE,
                     MAX(REEXPRESARVIDAUTIL.FECHACAMBIO) FECHACAMBIO,
                     DEPRECIAR.NIIF_COSTOAJUSTADO,
                     SUM(REEXPRESARVIDAUTIL.DETERIORO) DETERIORO,
                     DEPRECIAR.NIIF_VLRACUMULADO
                 FROM REEXPRESARVIDAUTIL
                  LEFT JOIN DEPRECIAR ON REEXPRESARVIDAUTIL.COMPANIA = DEPRECIAR.COMPANIA
                                       AND REEXPRESARVIDAUTIL.ELEMENTO = DEPRECIAR.ELEMENTO
                                       AND REEXPRESARVIDAUTIL.SERIE = DEPRECIAR.SERIE
                                       AND TO_DATE('s$ultimoDia$s','DD/MM/YYYY') = DEPRECIAR.PERIODO
                 WHERE
                     REEXPRESARVIDAUTIL.FECHACAMBIO <= TO_DATE('s$ultimoDia$s','DD/MM/YYYY')
                 GROUP BY
                     REEXPRESARVIDAUTIL.COMPANIA,
                     REEXPRESARVIDAUTIL.ELEMENTO,
                     REEXPRESARVIDAUTIL.SERIE,
                     DEPRECIAR.NIIF_COSTOAJUSTADO,
                     DEPRECIAR.NIIF_VLRACUMULADO
             ) RV
             INNER JOIN REEXPRESARVIDAUTIL REEXVIDA ON RV.COMPANIA = REEXVIDA.COMPANIA
                                                       AND RV.ELEMENTO = REEXVIDA.ELEMENTO
          ]') || TO_CLOB(q'[                                             AND RV.SERIE = REEXVIDA.SERIE
                                                       AND RV.FECHACAMBIO = REEXVIDA.FECHACAMBIO
     ) REEXPRESARVIDAUTIL ON DEVOLUTIVO.COMPANIA = REEXPRESARVIDAUTIL.COMPANIA
                             AND DEVOLUTIVO.ELEMENTO = REEXPRESARVIDAUTIL.ELEMENTO
                             AND DEVOLUTIVO.SERIE = REEXPRESARVIDAUTIL.SERIE
    LEFT JOIN ACTDEPRECIABLE
    ON INVENTARIO.TIPOACTIVO = ACTDEPRECIABLE.CODIGO
WHERE DEPRECIAR.COMPANIA=s$compania$s
  AND DEPRECIAR.ELEMENTO BETWEEN 's$elementoInicial$s' AND 's$elementoFinal$s'
  AND TO_CHAR(DEPRECIAR.PERIODO,'DD/MM/YYYY')='s$ultimoDia$s'
  AND TO_DATE(TO_CHAR(NVL(FECHAANULADA,TO_DATE('31/12/3000')), 'DD/MM/YYYY'), 'DD/MM/YYYY')>TO_DATE('s$ultimoDia$s', 'DD/MM/YYYY')
  AND TO_DATE(TO_CHAR(DEVOLUTIVO.FECHAADQUISICION, 'DD/MM/YYYY'), 'DD/MM/YYYY')<=TO_DATE('s$ultimoDia$s', 'DD/MM/YYYY')
  AND INVENTARIO.DIGITOS_AGRUPACION_INVENTARIO =-1]') CONSULTA, 10 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);
MERGE INTO CONSULTAS_SUB FIN USING (SELECT '000519IDepreciarMesDependencia_CON' INFORME_PADRE, '002818IIamortizacionMesDependencia_CON' INFORME_HIJO, 'PR_SQL_SUB_AMORT_MES_DEP' PARAMETRO ,NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (FIN.INFORME_PADRE = INI.INFORME_PADRE AND INI.INFORME_HIJO = FIN.INFORME_HIJO)  WHEN MATCHED THEN  UPDATE SET FIN.PARAMETRO = INI.PARAMETRO , FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME_PADRE,INFORME_HIJO, PARAMETRO,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME_PADRE,INI.INFORME_HIJO, INI.PARAMETRO,INI.CREATED_BY,SYSDATE);