SELECT * FROM (
    SELECT  TO_CHAR(ORDENDECOMPRA.FECHA,'YYYY') ANIO ,
     		TIPOORDENDECOMPRA.NOMBRE, 
     		NVL(ORDENDECOMPRA.VALORTOTAL,0) VALORTOTAL
    FROM ORDENDECOMPRA 
        INNER JOIN TIPOORDENDECOMPRA 
            ON  ORDENDECOMPRA.COMPANIA   = TIPOORDENDECOMPRA.COMPANIA 
            AND ORDENDECOMPRA.CLASEORDEN = TIPOORDENDECOMPRA.CODIGO 
    WHERE ORDENDECOMPRA.COMPANIA         = 's$compania$s' 
      AND ORDENDECOMPRA.DEPENDENCIA      = 's$dependencia$s'
      AND TO_NUMBER(TO_CHAR(ORDENDECOMPRA.FECHA,'YYYY')) 
          BETWEEN s$anioInicial$s AND s$anioFinal$s      
) P PIVOT (SUM(VALORTOTAL) FOR ANIO IN(s$pivotConsulta2$s))
