SELECT * FROM (
    SELECT  TIPOORDENDECOMPRA.NOMBRE,
          	ORDENDECOMPRA.VALORTOTAL,
          	TO_CHAR(ORDENDECOMPRA.FECHA,'YYYY') ANIO
    FROM ORDENDECOMPRA 
        INNER JOIN TIPOORDENDECOMPRA 
            ON   ORDENDECOMPRA.COMPANIA 	= TIPOORDENDECOMPRA.COMPANIA
            AND  ORDENDECOMPRA.CLASEORDEN 	= TIPOORDENDECOMPRA.CODIGO 
  WHERE ORDENDECOMPRA.COMPANIA        =   's$compania$s' 
    AND ORDENDECOMPRA.CLASEORDEN      =   'CCS'
    AND ORDENDECOMPRA.DEPENDENCIA     =   's$dependencia$s'
    AND TO_NUMBER(TO_CHAR(ORDENDECOMPRA.FECHA,'YYYY')) BETWEEN s$anioInicial$s  AND s$anioFinal$s
  GROUP BY ORDENDECOMPRA.DEPENDENCIA,
          ORDENDECOMPRA.VALORTOTAL,
          TIPOORDENDECOMPRA.NOMBRE,
          TO_CHAR(ORDENDECOMPRA.FECHA,'YYYY')
) P PIVOT (SUM(VALORTOTAL) FOR ANIO IN (s$pivotConsulta$s))
