SELECT 	
  INVENTARIO.COMPANIA, 
  INVENTARIO.CODIGOELEMENTO "CODIGO ELEMENTO", 
  DEVOLUTIVO.SERIE,  
  INVENTARIO.NOMBRELARGO "NOMBRE ELEMENTO",
  DEVOLUTIVO.DEPENDENCIA,	
  DEPENDENCIA.NOMBRE "NOMBRE DEPENDENCIA", 
  DEVOLUTIVO.RESPONSABLE,
  TERCERO.NOMBRE "NOMBRE RESPONSABLE" 
FROM INVENTARIO 
 INNER JOIN DEVOLUTIVO 
      ON  INVENTARIO.COMPANIA       = DEVOLUTIVO.COMPANIA
    AND INVENTARIO.CODIGOELEMENTO = DEVOLUTIVO.ELEMENTO 
 INNER JOIN DEPENDENCIA 
      ON  DEVOLUTIVO.COMPANIA    = DEPENDENCIA.COMPANIA 
    AND DEVOLUTIVO.DEPENDENCIA = DEPENDENCIA.CODIGO
 INNER JOIN RESPONSABLE 
      ON  DEVOLUTIVO.COMPANIA             = RESPONSABLE.COMPANIA
    AND DEVOLUTIVO.RESPONSABLE          = RESPONSABLE.CEDULA
    AND DEVOLUTIVO.SUCURSAL_RESPONSABLE = RESPONSABLE.SUCURSAL
  INNER JOIN TERCERO
     ON TERCERO.COMPANIA = RESPONSABLE.COMPANIA
    AND TERCERO.NIT      = RESPONSABLE.CEDULA
    AND TERCERO.SUCURSAL = RESPONSABLE.SUCURSAL
s$variableInner$s	
WHERE DEVOLUTIVO.COMPANIA = s$compania$s
      AND s$condicion$s
