SELECT D_MOVIMIENTO.COMPONENTE,
  D_MOVIMIENTO.ELEMENTO,
  D_MOVIMIENTO.SERIE PLACA,
  INVENTARIO.NOMBRELARGO,
  D_MOVIMIENTO.CANTIDAD,
  D_MOVIMIENTO.SALDOCANT,
  D_MOVIMIENTO.VLRUNITARIO_ANTESIVA "VLR UNIT ANTES DE IVA",
  D_MOVIMIENTO.PORCIVA "PORCENTAJE IVA",
  D_MOVIMIENTO.VALORUNITARIO,
  D_MOVIMIENTO.VALORTOTAL "VLR TOTAL",
  D_MOVIMIENTO.ESPECIFICACION,
  D_MOVIMIENTO.MARCA,
  D_MOVIMIENTO.SERIEDEVOLUTIVO,
  D_MOVIMIENTO.VALORBASE "VLR BASE IVA",
  D_MOVIMIENTO.VLRUNITARIOPROM "VLR UNITARIO PROM",
  D_MOVIMIENTO.VALORANTERIOR "VLR ANTERIOR",
  TO_CHAR(D_MOVIMIENTO.FECHA,'DD/MM/YYYY') FECHA,
  D_MOVIMIENTO.VALORDOCAS "VLR DOC ASOCIADO",
  TO_CHAR(D_MOVIMIENTO.HORA,'HH24:MI:SS') HORA,
  D_MOVIMIENTO.AJUSTECENTAVOS,
  (
  CASE D_MOVIMIENTO.APLICANIIF
    WHEN 0
    THEN 'NO'
    ELSE 'SI'
  END) APLICANIIF,
  D_MOVIMIENTO.NIIF_TIPO_ACTIVO,
  D_MOVIMIENTO.VIDAUTILPLACA,
  D_MOVIMIENTO.VIDAUTILPLACANIIF,
  D_MOVIMIENTO.ENTREGA,
  D_MOVIMIENTO.PREPARACION,
  D_MOVIMIENTO.COMPROBACION,
  D_MOVIMIENTO.INSTALACION,
  D_MOVIMIENTO.NIIF_VALOR_TOTAL,
  D_MOVIMIENTO.DETERIORO,
  D_MOVIMIENTO.REVELACIONES,
  D_MOVIMIENTO.SALVAMENTO
FROM D_MOVIMIENTO
INNER JOIN INVENTARIO
ON D_MOVIMIENTO.COMPANIA        = INVENTARIO.COMPANIA
AND D_MOVIMIENTO.ELEMENTO       = INVENTARIO.CODIGOELEMENTO
WHERE D_MOVIMIENTO.COMPANIA     = s$compania$s
AND D_MOVIMIENTO.TIPOMOVIMIENTO = 's$tipo$s'
AND D_MOVIMIENTO.MOVIMIENTO     = s$numero$s
