MERGE INTO CONSULTAS FIN USING (SELECT '800597InventarioSuministrosVencimiento' INFORME ,TO_CLOB(q'[SELECT INVENTARIO.CODIGOELEMENTO AS CODIGO_ELEMENTO
,INVENTARIO.NOMBRELARGO AS NOMBRE_ELEMENTO
,INVENTARIO.UNIDAD
,INVENTARIO.REFERENCIA
,CASE WHEN V_MOVIMIENTO_VENCIMIENTO.LOTE = '-1.-' THEN '' ELSE V_MOVIMIENTO_VENCIMIENTO.LOTE END LOTE
,TO_CHAR(D_MOVIMIENTO.FECHA_VENCIMIENTO, 'DD/MM/YYYY') AS FECHA_VENCIMIENTO
,CASE WHEN V_MOVIMIENTO_VENCIMIENTO.FUENTEDERECURSO = '-1.-' THEN '' ELSE V_MOVIMIENTO_VENCIMIENTO.FUENTEDERECURSO END FUENTEDERECURSO
,NVL(V_MOVIMIENTO_VENCIMIENTO.ENTRADAS,0) ENTRADAS
,NVL(V_MOVIMIENTO_VENCIMIENTO.SALIDAS,0) SALIDAS
,NVL(V_MOVIMIENTO_VENCIMIENTO.SALDO,0) EXISTENCIA

FROM (

SELECT D_MOVIMIENTO.COMPANIA, D_MOVIMIENTO.ELEMENTO,
MAX(D_MOVIMIENTO.FECHA_VENCIMIENTO) FECHA_VENCIMIENTO, TO_CHAR(MAX(D_MOVIMIENTO.FECHA), 'DD/MM/YYYY') FECHA
FROM D_MOVIMIENTO
WHERE D_MOVIMIENTO.COMPANIA = s$compania$s
AND D_MOVIMIENTO.ELEMENTO BETWEEN 's$elementoIni$s' AND 's$elementoFin$s
'
GROUP BY D_MOVIMIENTO.COMPANIA, D_MOVIMIENTO.ELEMENTO
ORDER BY D_MOVIMIENTO.COMPANIA, D_MOVIMIENTO.ELEMENTO

) D_MOVIMIENTO INNER JOIN INVENTARIO
ON D_MOVIMIENTO.COMPANIA = INVENTARIO.COMPANIA
AND D_MOVIMIENTO.ELEMENTO = INVENTARIO.CODIGOELEMENTO
LEFT JOIN (
SELECT ENTRADAS.COMPANIA
, ENTRADAS.ELEMENTO
, I.NOMBRELARGO
, U.NOMBRE UNIDAD
, ENTRADAS.LOTE
, ENTRADAS.FUENTEDERECURSO
, SUM(ENTRADAS.ENTRADA) ENTRADAS , SUM(NVL(SALIDAS.SALIDA,0)) SALIDAS
, SUM(ENTRADAS.ENTRADA) - SUM(NVL(SALIDAS.SALIDA,0)) SALDO
FROM ( SELECT D_MOVIMIENTO.COMPANIA
, D_MOVIMIENTO.ELEMENTO
, NVL(D_MOVIMIENTO.LOTE,'-1.-') LOTE
, NVL(D_MOVIMIENTO.FUENTEDERECURSO,'-1.-')FUENTEDERECURSO
, SUM(D_MOVIMIENTO.CANTIDAD) ENTRADA
FROM D_MOVIMIENTO INNER JOIN TIPOMOVIMIENTO
ON TIPOMOVIMIENTO.COMPANIA=D_MOVIMIENTO.COMPANIA
AND TIPOMOVIMIENTO.CODIGO=D_MOVIMIENTO.TIPOMOVIMIENTO
WHERE TIPOMOVIMIENTO.CLASE IN ('E')
AND TIPOMOVIMIENTO.TIPOELEMENTO IN ('C')
AND D_MOVIMIENTO.FECHA <= s$fecha$s
GROUP BY D_MOVIMIENTO.COMPANIA
, D_MOVIMIENTO.ELEMENTO
, D_MOVIMIENTO.LOTE, D_MOVIMIENTO.FUENTEDERECURSO
) ENTRADAS
LEFT JOIN ( SELECT D_MOVIMIENTO.COMPANIA
, D_MOVIMIENTO.ELEMENTO
, NVL(D_MOVIMIENTO.LOTE,'-1.-')LOTE ,NVL(D_MOVIMIENTO.FUENTEDERECURSO,'-1.-')FUENTEDERECURSO
, SUM(D_MOVIMIENTO.CANTIDAD) SALIDA
FROM D_MOVIMIENTO INNER JOIN TIPOMOVIMIENTO
ON TIPOMOVIMIENTO.COMPANIA=D_MOVIMIENTO.COMPANIA
AND TIPOMOVIMIENTO.CODIGO=D_MOVIMIENTO.TIPOMOVIMIENTO
WHERE TIPOMOVIMIENTO.CLASE IN ('S')
AND TIPOMOVIMIENTO.TIPOELEMENTO IN ('C')
AND D_MOVIMIENTO.FECHA <= s$fecha$s
GROUP BY D_MOVIMIENTO.COMPANIA
, D_MOVIMIENTO.ELEMENTO
, NVL(D_MOVIMIENTO.LOTE,'-1.-') ,NVL(D_MOVIMIENTO.FUENTEDERECURSO,'-1.-')
)SALIDAS
ON ENTRADAS.COMPANIA = SALIDAS.COMPANIA
AND ENTRADAS.ELEMENTO = SALIDAS.ELEMENTO
AND ENTRADAS.LOTE = SALIDAS.LOTE
AND ENTRADAS.FUENTEDERECURSO = SALIDAS.FUENTEDERECURSO
INNER JOIN INVENTARIO I
ON ENTRADAS.COMPANIA=I.COMPANIA
AND ENTRADAS.ELEMENTO=I.CODIGOELEMENTO
INNER JOIN UNIDAD U
ON I.UNIDAD = U.UNIDAD
GROUP BY ENTRADAS.COMPANIA
, ENTRADAS.ELEMEN]') || TO_CLOB(q'[TO
, I.NOMBRELARGO
, U.NOMBRE
, ENTRADAS.LOTE
, ENTRADAS.FUENTEDERECURSO

ORDER BY ENTRADAS.COMPANIA
, ENTRADAS.ELEMENTO
, ENTRADAS.LOTE
, ENTRADAS.FUENTEDERECURSO 

) V_MOVIMIENTO_VENCIMIENTO
ON INVENTARIO.COMPANIA = V_MOVIMIENTO_VENCIMIENTO.COMPANIA
AND INVENTARIO.CODIGOELEMENTO = V_MOVIMIENTO_VENCIMIENTO.ELEMENTO

WHERE INVENTARIO.COMPANIA = s$compania$s
AND INVENTARIO.CODIGOELEMENTO BETWEEN 's$elementoIni$s' AND 's$elementoFin$s'
s$conSaldo$s
ORDER BY s$orden$s]') CONSULTA, 10 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);