MERGE INTO CONSULTAS FIN USING (SELECT '800580CDocAlmacenEspPlano' INFORME ,TO_CLOB(q'[SELECT  D_MOVIMIENTO.COMPANIA,
        TO_CHAR(MOVIMIENTO.FECHA, 'DD/MM/YYYY') FECHA,
        D_MOVIMIENTO.TIPOMOVIMIENTO ||' '|| TIPOMOVIMIENTO.NOMBRE ||' No. '||MOVIMIENTO.NUMERO AS CPTE_MOV,
        D_MOVIMIENTO.TIPOMOVIMIENTO,
        TIPOMOVIMIENTO.NOMBRE AS NOMBREMOVIMIENTO,
        MOVIMIENTO.NUMERO,
        D_MOVIMIENTO.ELEMENTO,
        DECODE(MOVIMIENTO.CLASE_BODEGA_DESTINO,20,GRUPO.NIIF_CUENTAACTIVO,40,GRUPO.NIIF_CUENTAACTIVOI,50,GRUPO.NIIF_CUENTAACTIVOR,GRUPO.NIIF_CUENTAACTIVOS) CUENTAACTIVO,
        INVENTARIO.NOMBRELARGO NOMBRE_ELEMENTO,
        INVENTARIO.UNIDAD,
        CASE WHEN TIPOMOVIMIENTO.CLASE = 'E' THEN D_MOVIMIENTO.CANTIDAD ELSE 0 END CANT_ENTRADAS,
        CASE WHEN TIPOMOVIMIENTO.CLASE ='E' THEN D_MOVIMIENTO.VALORTOTAL ELSE 0 END VLR_ENTRADAS,
        CASE WHEN TIPOMOVIMIENTO.CLASE <>'E' THEN D_MOVIMIENTO.CANTIDAD ELSE 0 END CANT_SALIDAS,
        CASE WHEN TIPOMOVIMIENTO.CLASE <>'E' THEN D_MOVIMIENTO.VALORTOTAL ELSE 0 END  VLR_SALIDAS,
        CASE WHEN TIPOMOVIMIENTO.CLASE = 'E' THEN  TERCERO.NOMBRE ELSE TERCERO_ORIGEN.NOMBRE END PROVEEDOR,
        TERCERO_DESTINO.NOMBRE DESTINATARIO,    
        V_ORDENDECOMPRA_RUBRO.RUBRO AS RUBROREGISTRO,
        MOVIMIENTO.CENTRODECOSTO,
        D_MOVIMIENTO.FUENTEDERECURSO
FROM    D_MOVIMIENTO
INNER JOIN MOVIMIENTO
   ON D_MOVIMIENTO.COMPANIA       = MOVIMIENTO.COMPANIA
  AND D_MOVIMIENTO.MOVIMIENTO     = MOVIMIENTO.NUMERO
  AND D_MOVIMIENTO.TIPOMOVIMIENTO = MOVIMIENTO.TIPOMOVIMIENTO
INNER JOIN TIPOMOVIMIENTO
   ON D_MOVIMIENTO.COMPANIA       = TIPOMOVIMIENTO.COMPANIA
  AND D_MOVIMIENTO.TIPOMOVIMIENTO = TIPOMOVIMIENTO.CODIGO
INNER JOIN INVENTARIO
   ON D_MOVIMIENTO.COMPANIA  = INVENTARIO.COMPANIA
  AND D_MOVIMIENTO.ELEMENTO  = INVENTARIO.CODIGOELEMENTO
LEFT JOIN INVENTARIO GRUPO
      ON D_MOVIMIENTO.COMPANIA=GRUPO.COMPANIA
       AND SUBSTR(D_MOVIMIENTO.ELEMENTO,1,PCK_SYSMAN_UTL.FC_PAR(D_MOVIMIENTO.COMPANIA,'DIGITOS AGRUPACION INVENTARIO',-1,D_MOVIMIENTO.FECHA))=GRUPO.CODIGOELEMENTO
INNER JOIN TERCERO
   ON MOVIMIENTO.COMPANIA   = TERCERO.COMPANIA
  AND MOVIMIENTO.SUCURSAL   = TERCERO.SUCURSAL
  AND MOVIMIENTO.TERCERO    = TERCERO.NIT
INNER JOIN TERCERO TERCERO_ORIGEN
   ON MOVIMIENTO.COMPANIA   = TERCERO_ORIGEN.COMPANIA
  AND MOVIMIENTO.RESPONSABLE_ORIGEN   =  TERCERO_ORIGEN.NIT  
  AND MOVIMIENTO.SUCURSAL_RESORIGEN   = TERCERO_ORIGEN.SUCURSAL
INNER JOIN TERCERO TERCERO_DESTINO
   ON MOVIMIENTO.COMPANIA   = TERCERO_DESTINO.COMPANIA
  AND MOVIMIENTO.RESPONSABLE_DESTINO   =  TERCERO_DESTINO.NIT  
  AND MOVIMIENTO.SUCURSAL_RESDESTINO   = TERCERO_DESTINO.SUCURSAL
LEFT JOIN ORDENDECOMPRA
  ON MOVIMIENTO.COMPANIA        = ORDENDECOMPRA.COMPANIA
 AND MOVIMIENTO.MOVASOCIADO     = ORDENDECOMPRA.NUMERO
 AND MOVIMIENTO.TIPOMOVASOCIADO = ORDENDECOMPRA.CLASEORDEN
 LEFT JOIN V_ORDENDECOMPRA_RUBRO
   ON ORDENDECOMPRA.COMPANIA   = V_ORDENDECOMPRA_RUBRO.COMPANIA
  AND ORDENDECOMPRA.CLASEORDEN = V_ORDENDECOMPRA_RUBRO.CLASEORDEN
  AND ORDENDECOMPRA.NUMERO     = V_ORDENDECOMPRA_RUBRO.NUMERO
WHERE D_MOVIMIENT]') || TO_CLOB(q'[O.COMPANIA = 's$compania$s'
AND D_MOVIMIENTO.TIPOMOVIMIENTO BETWEEN 's$tipoInicial$s' AND 's$tipoFinal$s'
AND TRUNC(D_MOVIMIENTO.FECHA) BETWEEN s$fechaInicial$s AND s$fechaFinal$s
AND D_MOVIMIENTO.IND_REG NOT IN (0) 
ORDER BY   TO_DATE(TO_CHAR(D_MOVIMIENTO.FECHA, 'DD/MM/YYYY') || ' ' || TO_CHAR(D_MOVIMIENTO.HORA, 'HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') ASC]') CONSULTA, 10 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);