MERGE INTO CONSULTAS FIN USING (SELECT '800579CDocAlmacenPlano' INFORME ,TO_CLOB(q'[SELECT 	D_MOVIMIENTO.COMPANIA,
		TO_CHAR(D_MOVIMIENTO.FECHA, 'DD/MM/YYYY') AS FECHA,
		D_MOVIMIENTO.TIPOMOVIMIENTO,
		TIPOMOVIMIENTO.NOMBRECORTO AS NOMBREMOVIMIENTO,
		MOVIMIENTO.NUMERO,
		MOVIMIENTO.DESCRIPCION AS DESCRIPCION,
		D_MOVIMIENTO.ELEMENTO,
		D_MOVIMIENTO.SERIE PLACA,
		INVENTARIO.NOMBRELARGO NOMBRE_ELEMENTO,
		INVENTARIO.UNIDAD,
		CASE WHEN TIPOMOVIMIENTO.CLASE = 'E' THEN D_MOVIMIENTO.CANTIDAD ELSE 0 END CANT_ENTRADAS,
		CASE WHEN TIPOMOVIMIENTO.CLASE = 'E' THEN D_MOVIMIENTO.VALORTOTAL ELSE 0 END VLR_ENTRADAS,
		CASE WHEN TIPOMOVIMIENTO.CLASE = 'S' THEN D_MOVIMIENTO.CANTIDAD ELSE 0 END CANT_SALIDAS,
		CASE WHEN TIPOMOVIMIENTO.CLASE = 'S' THEN D_MOVIMIENTO.VALORTOTAL ELSE 0 END VLR_SALIDAS,
		CASE WHEN TIPOMOVIMIENTO.CLASE = 'T' THEN D_MOVIMIENTO.CANTIDAD ELSE 0 END CANT_TRASLADOS,
		CASE WHEN TIPOMOVIMIENTO.CLASE = 'T' THEN D_MOVIMIENTO.VALORTOTAL ELSE 0 END VLR_TRASLADOS,
		NVL(TERCERO.NOMBRE, ' ' ) TERCERO,
		D_MOVIMIENTO.CENTRODECOSTO,
        D_MOVIMIENTO.FUENTEDERECURSO
FROM 	D_MOVIMIENTO
		INNER JOIN MOVIMIENTO
     ON D_MOVIMIENTO.COMPANIA        = MOVIMIENTO.COMPANIA
    AND D_MOVIMIENTO.TIPOMOVIMIENTO  = MOVIMIENTO.TIPOMOVIMIENTO
    AND D_MOVIMIENTO.MOVIMIENTO      = MOVIMIENTO.NUMERO
  INNER JOIN TIPOMOVIMIENTO
     ON D_MOVIMIENTO.COMPANIA        = TIPOMOVIMIENTO.COMPANIA
    AND D_MOVIMIENTO.TIPOMOVIMIENTO  = TIPOMOVIMIENTO.CODIGO
  INNER JOIN INVENTARIO
     ON D_MOVIMIENTO.COMPANIA  = INVENTARIO.COMPANIA
    AND D_MOVIMIENTO.ELEMENTO  = INVENTARIO.CODIGOELEMENTO
  INNER JOIN TERCERO
     ON MOVIMIENTO.COMPANIA  = TERCERO.COMPANIA
    AND MOVIMIENTO.TERCERO   = TERCERO.NIT
    AND MOVIMIENTO.SUCURSAL  = TERCERO.SUCURSAL
  LEFT JOIN RESPONSABLE
     ON TERCERO.COMPANIA  = RESPONSABLE.COMPANIA
    AND TERCERO.NIT   = RESPONSABLE.CEDULA
    AND TERCERO.SUCURSAL  = RESPONSABLE.SUCURSAL
WHERE 	D_MOVIMIENTO.COMPANIA =  s$compania$s
		AND D_MOVIMIENTO.TIPOMOVIMIENTO BETWEEN 's$tipoInicial$s' AND 's$tipoFinal$s'
		AND TRUNC(D_MOVIMIENTO.FECHA) BETWEEN s$fechaInicial$s AND s$fechaFinal$s
		AND D_MOVIMIENTO.IND_REG  NOT IN (0)
		AND D_MOVIMIENTO.TIPOMOVIMIENTO NOT IN ('SDF')
ORDER BY D_MOVIMIENTO.FECHA ASC]') CONSULTA, 10 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);