MERGE INTO CONSULTAS FIN USING (SELECT '800634InventarioFisicoSaldoLibros' INFORME ,TO_CLOB(q'[WITH ULTIMOMOVIMIENTO AS (
  SELECT 
    D_MOVIMIENTO.COMPANIA,
    D_MOVIMIENTO.TIPOMOVIMIENTO,
    D_MOVIMIENTO.MOVIMIENTO,
    D_MOVIMIENTO.ELEMENTO,
    D_MOVIMIENTO.SERIE,
    TO_TIMESTAMP(TO_CHAR(D_MOVIMIENTO.FECHA, 'DD/MM/YYYY') || ' ' || TO_CHAR(D_MOVIMIENTO.HORA, 'HH24:MI:SS'), 'DD/MM/YYYY HH24:MI:SS') AS FECHA_HORA,
    MOVIMIENTO.CLASE_BODEGA_ORIGEN,
    MOVIMIENTO.CLASE_BODEGA_DESTINO,
    MOVIMIENTO.BODEGA_ORIGEN,
    MOVIMIENTO.BODEGA_DESTINO,
    TIPOMOVIMIENTO.CLASE,
    BODEGA.NO_EXPLOTADOS,
    BODEGA.MANTENIMIENTO,
    MOVIMIENTO.DEPENDENCIA_DESTINO,
    MOVIMIENTO.RESPONSABLE_DESTINO,
    MOVIMIENTO.SUCURSAL_RESDESTINO,
    CASE 
      WHEN TIPOMOVIMIENTO.CLASE = 'S' THEN MOVIMIENTO.CLASE_BODEGA_ORIGEN 
      ELSE MOVIMIENTO.CLASE_BODEGA_DESTINO 
    END AS CLASE_BODEGA_RELEVANTE
  FROM D_MOVIMIENTO D_MOVIMIENTO
  INNER JOIN (
    SELECT
      COMPANIA,
      ELEMENTO,
      SERIE,
      MAX(TO_TIMESTAMP(TO_CHAR(FECHA, 'DD/MM/YYYY') || ' ' || TO_CHAR(HORA, 'HH24:MI:SS'), 'DD/MM/YYYY HH24:MI:SS')) AS FECHA_HORA
    FROM D_MOVIMIENTO
    WHERE IND_REG <> 0
      AND TO_TIMESTAMP(TO_CHAR(FECHA, 'DD/MM/YYYY') || ' ' || TO_CHAR(HORA, 'HH24:MI:SS'), 'DD/MM/YYYY HH24:MI:SS') <= TO_TIMESTAMP(TO_CHAR(s$fecha$s, 'DD/MM/YYYY')||'23:59:59', 'DD/MM/YYYY HH24:MI:SS')
    GROUP BY COMPANIA, ELEMENTO, SERIE
  ) ULTIMO ON D_MOVIMIENTO.COMPANIA = ULTIMO.COMPANIA
    AND D_MOVIMIENTO.ELEMENTO = ULTIMO.ELEMENTO
    AND D_MOVIMIENTO.SERIE = ULTIMO.SERIE
    AND TO_TIMESTAMP(TO_CHAR(D_MOVIMIENTO.FECHA, 'DD/MM/YYYY') || ' ' || TO_CHAR(D_MOVIMIENTO.HORA, 'HH24:MI:SS'), 'DD/MM/YYYY HH24:MI:SS') = ULTIMO.FECHA_HORA
  INNER JOIN MOVIMIENTO MOVIMIENTO ON D_MOVIMIENTO.COMPANIA = MOVIMIENTO.COMPANIA
    AND D_MOVIMIENTO.TIPOMOVIMIENTO = MOVIMIENTO.TIPOMOVIMIENTO
    AND D_MOVIMIENTO.MOVIMIENTO = MOVIMIENTO.NUMERO
  INNER JOIN TIPOMOVIMIENTO TIPOMOVIMIENTO ON MOVIMIENTO.COMPANIA = TIPOMOVIMIENTO.COMPANIA
    AND MOVIMIENTO.TIPOMOVIMIENTO = TIPOMOVIMIENTO.CODIGO
  INNER JOIN BODEGA BODEGA ON MOVIMIENTO.COMPANIA = BODEGA.COMPANIA
    AND MOVIMIENTO.BODEGA_DESTINO = BODEGA.CODIGO
)
SELECT DISTINCT
  DEPENDENCIA.CODIGO,    
  DEPENDENCIA.NOMBRE AS DEPENDENCIA,
  SUBSTR(DEVOLUTIVO.ELEMENTO, 1, s$digito$s ) || ' ' || ICUENTA.NOMBRELARGO AS GRUPO,
  CASE 
    WHEN ULTIMOMOVIMIENTO.CLASE_BODEGA_RELEVANTE = '20' THEN
      CASE 
        WHEN ULTIMOMOVIMIENTO.MANTENIMIENTO <> 0 THEN NVL(ICUENTA.CUENTAACTIVOMAN, ICUENTA.CUENTAACTIVO)
        WHEN ULTIMOMOVIMIENTO.NO_EXPLOTADOS <> 0 THEN NVL(ICUENTA.CUENTAACTIVONEXP, ICUENTA.CUENTAACTIVO)
        ELSE ICUENTA.CUENTAACTIVO
      END
    WHEN ULTIMOMOVIMIENTO.CLASE_BODEGA_RELEVANTE = '30' THEN ICUENTA.CUENTAACTIVOS
    WHEN ULTIMOMOVIMIENTO.CLASE_BODEGA_RELEVANTE = '40' THEN ICUENTA.CUENTAACTIVOI
    WHEN ULTIMOMOVIMIENTO.CLASE_BODEGA_RELEVANTE = '50' THEN ICUENTA.CUENTAACTIVOR
    WHEN ULTIMOMOVIMIENTO.CLASE_BODEGA_RELEVANTE = '70' THEN ICUENTA.CUENTAACTIVOS
   ]') || TO_CLOB(q'[ WHEN ULTIMOMOVIMIENTO.CLASE_BODEGA_RELEVANTE = '90' THEN ICUENTA.CUENTAACTIVOC
    ELSE ''
  END AS CUENTA,
  TO_CHAR(DEVOLUTIVO.FECHAADQUISICION, 'DD/MM/YYYY') AS FECHACOMPRA,
  DEVOLUTIVO.SERIE AS PLACA,
  INVENTARIO.NOMBRELARGO AS NOMBRE,
  DEVOLUTIVO.SERIEDEVOLUTIVO AS SERIE,
  ESTADODEVOLUTIVO.DESCRIPCION AS ESTADO,
  DEVOLUTIVO.DESCRIPCION,
  NVL(DEPRECIAR.NIIF_VLRELEMENTO, DEVOLUTIVO.VALOR) AS TVALOR,
  NVL(DEPRECIAR.NIIF_VLRLIBROS, DEVOLUTIVO.NIIF_VLRLIBROS) AS "VALOR EN LIBROS",
  NVL(REEXP.VIDAUTIL, DEVOLUTIVO.NIIF_VIDA_UTIL) AS "VIDA UTIL NIIF",
  CASE 
    WHEN DEVOLUTIVO.PLACAANULADA = 0 OR (DEVOLUTIVO.PLACAANULADA <> 0 AND DEVOLUTIVO.FECHAANULADA > s$fecha$s) THEN 0 
    ELSE -1 
  END AS PLACAANULADA
FROM DEVOLUTIVO
LEFT JOIN ESTADODEVOLUTIVO ON DEVOLUTIVO.ESTADO = ESTADODEVOLUTIVO.ESTADO
INNER JOIN INVENTARIO ON DEVOLUTIVO.COMPANIA = INVENTARIO.COMPANIA
  AND DEVOLUTIVO.ELEMENTO = INVENTARIO.CODIGOELEMENTO
LEFT JOIN ACTDEPRECIABLE ON ACTDEPRECIABLE.CODIGO = INVENTARIO.TIPOACTIVO
LEFT JOIN DEPRECIAR DEPRECIAR ON DEVOLUTIVO.COMPANIA = DEPRECIAR.COMPANIA
  AND DEVOLUTIVO.ELEMENTO = DEPRECIAR.ELEMENTO
  AND DEVOLUTIVO.SERIE = DEPRECIAR.SERIE
  AND DEPRECIAR.COMPANIA = 's$compania$s'
  AND DEPRECIAR.ANO = EXTRACT(YEAR FROM s$fecha$s)
  AND DEPRECIAR.MES = EXTRACT(MONTH FROM s$fecha$s)
LEFT JOIN (
  SELECT SERIE, VIDAUTIL
  FROM (
    SELECT SERIE, VIDAUTIL, FECHACAMBIO,
           ROW_NUMBER() OVER (PARTITION BY SERIE ORDER BY FECHACAMBIO DESC) AS RN
    FROM REEXPRESARVIDAUTIL
    WHERE COMPANIA = 's$compania$s'
      AND EXTRACT(YEAR FROM FECHACAMBIO) = EXTRACT(YEAR FROM s$fecha$s)
      AND EXTRACT(MONTH FROM FECHACAMBIO) = EXTRACT(MONTH FROM s$fecha$s)
  ) WHERE RN = 1
) REEXP ON REEXP.SERIE = DEVOLUTIVO.SERIE
INNER JOIN ULTIMOMOVIMIENTO ON ULTIMOMOVIMIENTO.COMPANIA = DEVOLUTIVO.COMPANIA
  AND ULTIMOMOVIMIENTO.ELEMENTO = DEVOLUTIVO.ELEMENTO
  AND ULTIMOMOVIMIENTO.SERIE = DEVOLUTIVO.SERIE
INNER JOIN MOVIMIENTO MOVIMIENTO ON ULTIMOMOVIMIENTO.COMPANIA = MOVIMIENTO.COMPANIA
  AND ULTIMOMOVIMIENTO.TIPOMOVIMIENTO = MOVIMIENTO.TIPOMOVIMIENTO
  AND ULTIMOMOVIMIENTO.MOVIMIENTO = MOVIMIENTO.NUMERO
INNER JOIN DEPENDENCIA ON DEPENDENCIA.COMPANIA = ULTIMOMOVIMIENTO.COMPANIA
  AND DEPENDENCIA.CODIGO = ULTIMOMOVIMIENTO.DEPENDENCIA_DESTINO
INNER JOIN RESPONSABLE ON ULTIMOMOVIMIENTO.COMPANIA = RESPONSABLE.COMPANIA
  AND ULTIMOMOVIMIENTO.RESPONSABLE_DESTINO = RESPONSABLE.CEDULA
  AND ULTIMOMOVIMIENTO.SUCURSAL_RESDESTINO = RESPONSABLE.SUCURSAL
INNER JOIN TERCERO ON RESPONSABLE.COMPANIA = TERCERO.COMPANIA
  AND RESPONSABLE.CEDULA = TERCERO.NIT
  AND RESPONSABLE.SUCURSAL = TERCERO.SUCURSAL
INNER JOIN INVENTARIO ICUENTA ON DEVOLUTIVO.COMPANIA = ICUENTA.COMPANIA
  AND SUBSTR(DEVOLUTIVO.ELEMENTO, 1, s$digito$s ) = ICUENTA.CODIGOELEMENTO
WHERE DEVOLUTIVO.COMPANIA = 's$compania$s'
  AND (
    DEVOLUTIVO.PLACAANULADA = 0 
    OR (DEVOLUTIVO.PLACAANULADA <> 0 AND DEVOLUTIVO.FECHAANULADA > s$fecha$s)
 ]') || TO_CLOB(q'[ )
ORDER BY DEPENDENCIA.CODIGO, DEPENDENCIA.NOMBRE]') CONSULTA, 10 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);