com.sysman.package.pattern   =@package(\\s)*:[\\w_\\s]*
com.sysman.package.replace   =:(\\s)*[\\w\\s]*
com.sysman.get.functionality.pattern  	 = (FUNCTION | PROCEDURE)[\\w_\\s]*([@/*\t\\s\n\\w\\(\\.\\_\\,\\:\\-\\=\\)]*)([\\);]*)
com.sysman.get.functionality.pattern1  	 = @get(\\s)*:[\\w_\\s]*
com.sysman.get.functionality.pattern2  	 = :(\\s)*[\\w\\s]*
com.sysman.post.functionality.pattern  	 = (FUNCTION | PROCEDURE)[\\w_\\s]*([@/*\t\\s\n\\w\\(\\.\\_\\,\\:\\-\\=\\)]*)([\\);]*)
com.sysman.post.functionality.pattern1 	 = @post(\\s)*:[\\w_\\s]*
com.sysman.post.functionality.pattern2 	 = :(\\s)*[\\w\\s]*
com.sysman.put.functionality.pattern   	 = (FUNCTION | PROCEDURE)[\\w_\\s]*([@/*\t\\s\n\\w\\(\\.\\_\\,\\:\\-\\=\\)]*)([\\);]*)
com.sysman.put.functionality.pattern1  	 = @put(\\s)*:[\\w_\\s]*
com.sysman.put.functionality.pattern2    = :(\\s)*[\\w\\s]*
com.sysman.delete.functionality.pattern  = (FUNCTION | PROCEDURE)[\\w_\\s]*([@/*\t\\s\n\\w\\(\\.\\_\\,\\:\\-\\=\\)]*)([\\);]*)
com.sysman.delete.functionality.pattern1 = @delete(\\s)*:[\\w_\\s]*
com.sysman.delete.functionality.pattern2 = :(\\s)*[\\w\\s]*
#com.sysman.procedure.pattern =PROCEDURE[\\w_\\s]*([@/*\t\\s\n\\w\\(\\.\\_\\,\\:\\-\\=\\)]*)\\);
#com.sysman.procedure.pattern1 = @procedure(\\s)*:[\\w_\\s]*
#com.sysman.procedure.pattern2 = :(\\s)*[\\w\\s]*


