com.sysman.params.pattern1.pattern =\\+([a-zA-Z0-9\\s]*)\\+
com.sysman.params.pattern1.replace =\n\t\t\tMap<String,Object> param = new TreeMap<>();\r
com.sysman.params.pattern1.param   =\t\t\tparam.put({0},String.valueOf({1}));\r
com.sysman.params.pattern2.pattern =\\+([a-z\\wñÑ\\d+//.]*)get([(\\\\\"\\s]*)([a-zA-Z0-9]*)([\\\\\"\\s\\)]*)([\\+;]*{0,1})
com.sysman.params.pattern2.replace =\n\t\t\tMap<String,Object> param = new TreeMap<>();\r
com.sysman.params.pattern2.param   =\t\t\tparam.put({0},String.valueOf({1}));\r
com.sysman.params.pattern3.pattern =\\+([a-z\\wñÑ\\d+//.\\s()]*).get([(\\\\\"\\s]*)([a-zA-Z0-9]*)([\\\\\"\\s\\)]*)([\\+;]*{0,1})
com.sysman.params.pattern3.replace =\n\t\t\tMap<String,Object> param = new TreeMap<>();\r
com.sysman.params.pattern3.param   =\t\t\tparam.put({0},String.valueOf({1}));\r