MERGE INTO CONSULTAS FIN USING (SELECT '000458SubPAA' INFORME ,TO_CLOB(q'[SELECT  INVENTARIO.CODIGOELEMENTO, 
        INVENTARIO.CUBS, 
        DETALLE_PLAN_COMPRAS.ESPECIFICACION, 
        PCK_SYSMAN_UTL.FC_NOMBRE_MES(DETALLE_PLAN_COMPRAS.MES) AS MES,
        NVL(DURACION_ESTIMADA_DEL_CONTRATO,0) ||' '|| 'Meses' AS DURACION, 
        TIPOADJUDICACION.DESCRIPCION TIPO_CONTRATACION,
        PLAN_DE_COMPRAS.VLRPROGRAMADO AS VALORESTIMADO, 
        PLAN_DE_COMPRAS.VLRPROGRAMADO AS VALORESTIMADOVIGENCIA, 
        CASE WHEN REQUIERE_VIGENCIA_FUTURA=0 
          THEN 'NO' ELSE 'SI' END AS REQUIERE_VIGENCIA, 
        PLAN_DE_COMPRAS.VLRPROGRAMADO, 
        TERCERO.NOMBRE || ' ' || RESPONSABLE.CARGO AS RESPONSABLE, 
        INVENTARIO.CODIGOCUBS, 
        DETALLE_PLAN_COMPRAS.FUENTE_DE_RECURSOS, 
        PLAN_DE_COMPRAS.ESTADO_VF, 
        FUENTE_RECURSOS.NOMBRE AS NOMBREFUENTE, 
        COMPANIA.CONTACTO
FROM INVENTARIO 
  INNER JOIN DETALLE_PLAN_COMPRAS 
    ON INVENTARIO.COMPANIA = DETALLE_PLAN_COMPRAS.COMPANIA 
    AND INVENTARIO.CODIGOELEMENTO = DETALLE_PLAN_COMPRAS.CODIGO 
  INNER JOIN DEPENDENCIA_RESPONSABLE 
    ON DETALLE_PLAN_COMPRAS.COMPANIA = DEPENDENCIA_RESPONSABLE.COMPANIA 
    AND DETALLE_PLAN_COMPRAS.DEPENDENCIA = DEPENDENCIA_RESPONSABLE.DEPENDENCIA
    AND DETALLE_PLAN_COMPRAS.RESPONSABLE = DEPENDENCIA_RESPONSABLE.RESPONSABLE
    AND DETALLE_PLAN_COMPRAS.SUCURSAL = DEPENDENCIA_RESPONSABLE.SUCURSAL 
  INNER JOIN PLAN_DE_COMPRAS 
    ON DETALLE_PLAN_COMPRAS.COMPANIA = PLAN_DE_COMPRAS.COMPANIA 
    AND DETALLE_PLAN_COMPRAS.ANO = PLAN_DE_COMPRAS.ANO 
    AND DETALLE_PLAN_COMPRAS.RUBRO = PLAN_DE_COMPRAS.CODIGO 
  INNER JOIN RESPONSABLE 
    ON DEPENDENCIA_RESPONSABLE.COMPANIA = RESPONSABLE.COMPANIA 
    AND DEPENDENCIA_RESPONSABLE.RESPONSABLE = RESPONSABLE.CEDULA
    AND	DEPENDENCIA_RESPONSABLE.SUCURSAL = RESPONSABLE.SUCURSAL
  INNER JOIN TERCERO 
    ON RESPONSABLE.COMPANIA = TERCERO.COMPANIA 
    AND RESPONSABLE.CEDULA = TERCERO.NIT
    AND RESPONSABLE.SUCURSAL = TERCERO.SUCURSAL
  INNER JOIN FUENTE_RECURSOS 
    ON DETALLE_PLAN_COMPRAS.COMPANIA = FUENTE_RECURSOS.COMPANIA
    AND DETALLE_PLAN_COMPRAS.ANO = FUENTE_RECURSOS.ANO 
    AND DETALLE_PLAN_COMPRAS.FUENTE_DE_RECURSOS = FUENTE_RECURSOS.CODIGO  
     INNER JOIN AUXILIAR 
    ON DETALLE_PLAN_COMPRAS.COMPANIA = AUXILIAR.COMPANIA
    AND DETALLE_PLAN_COMPRAS.ANO = AUXILIAR.ANO 
    AND DETALLE_PLAN_COMPRAS.AUXILIAR = AUXILIAR.CODIGO  
      INNER JOIN CENTRO_COSTO 
    ON DETALLE_PLAN_COMPRAS.COMPANIA = CENTRO_COSTO.COMPANIA
    AND DETALLE_PLAN_COMPRAS.ANO = CENTRO_COSTO.ANO 
    AND DETALLE_PLAN_COMPRAS.CENTRO_COSTO = CENTRO_COSTO.CODIGO  
    INNER JOIN REFERENCIA 
    ON DETALLE_PLAN_COMPRAS.COMPANIA = REFERENCIA.COMPANIA
    AND DETALLE_PLAN_COMPRAS.ANO = REFERENCIA.ANO 
    AND DETALLE_PLAN_COMPRAS.REFERENCIA = REFERENCIA.CODIGO  
  INNER JOIN DECLARACIONESTRATEGICA 
    ON PLAN_DE_COMPRAS.COMPANIA = DECLARACIONESTRATEGICA.COMPANIA
    AND PLAN_DE_COMPRAS.ANO = DECLARACIONESTRATEGICA.ANO
  INN]') || TO_CLOB(q'[ER JOIN COMPANIA 
    ON INVENTARIO.COMPANIA = COMPANIA.CODIGO
LEFT JOIN TIPOADJUDICACION 
    ON DETALLE_PLAN_COMPRAS.COMPANIA = TIPOADJUDICACION.COMPANIA
    AND DETALLE_PLAN_COMPRAS.TIPO_CONTRATACION = TIPOADJUDICACION.CODIGO
WHERE INVENTARIO.COMPANIA =  s$compania$s
  AND PLAN_DE_COMPRAS.ANO = s$anio$s
GROUP BY  INVENTARIO.CODIGOELEMENTO, 
          INVENTARIO.CUBS, 
          DETALLE_PLAN_COMPRAS.ESPECIFICACION, 
          PCK_SYSMAN_UTL.FC_NOMBRE_MES(DETALLE_PLAN_COMPRAS.MES), 
          NVL(DURACION_ESTIMADA_DEL_CONTRATO,0) ||' '|| 'Meses', 
          TIPOADJUDICACION.DESCRIPCION, 
          CASE WHEN REQUIERE_VIGENCIA_FUTURA = 0 
            THEN 'NO' ELSE 'SI' END , 
          PLAN_DE_COMPRAS.VLRPROGRAMADO, 
          TERCERO.NOMBRE || ' ' || RESPONSABLE.CARGO, 
          INVENTARIO.CODIGOCUBS, 
          DETALLE_PLAN_COMPRAS.ESPECIFICACION, 
          DETALLE_PLAN_COMPRAS.FUENTE_DE_RECURSOS, 
          PLAN_DE_COMPRAS.ESTADO_VF, 
          FUENTE_RECURSOS.NOMBRE, 
          COMPANIA.CONTACTO, 
          PLAN_DE_COMPRAS.VLRPROGRAMADO, 
          PLAN_DE_COMPRAS.VLRPROGRAMADO, 
          INVENTARIO.COMPANIA]') CONSULTA, 40 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);