SELECT 	D_ORDENDECOMPRA.ELEMENTO,
        INVENTARIO.NOMBRELARGO,
        D_ORDENDECOMPRA.CLASEORDEN, 
        ORDENDECOMPRA.NUMERO, 
        ORDENDECOMPRA.FECHA, 
       	TERCERO.NOMBRE NOMBRETERCERO, 
        TERCERO.NIT, 
      	SUM(D_ORDENDECOMPRA.CANTIDAD) AS SUMADECANTIDAD,
        SUM(D_ORDENDECOMPRA.VALORUNITARIO) AS SUMADEVALORUNITARIO,
        SUM(D_ORDENDECOMPRA.VLRTOTAL) AS SUMADEVLRTOTAL
FROM D_ORDENDECOMPRA 
	LEFT JOIN INVENTARIO 
		ON D_ORDENDECOMPRA.COMPANIA   = INVENTARIO.COMPANIA
		AND D_ORDENDECOMPRA.ELEMENTO  = INVENTARIO.CODIGOELEMENTO 
	INNER JOIN ORDENDECOMPRA 
		ON D_ORDENDECOMPRA.COMPANIA        = ORDENDECOMPRA.COMPANIA
		AND D_ORDENDECOMPRA.CLASEORDEN     = ORDENDECOMPRA.CLASEORDEN
		AND D_ORDENDECOMPRA.ORDENDECOMPRA  = ORDENDECOMPRA.NUMERO
	LEFT JOIN TERCERO 
		ON ORDENDECOMPRA.COMPANIA  = TERCERO.COMPANIA
		AND ORDENDECOMPRA.TERCERO  = TERCERO.NIT
		AND ORDENDECOMPRA.SUCURSAL = TERCERO.SUCURSAL
WHERE D_ORDENDECOMPRA.COMPANIA = s$compania$s 
  AND ORDENDECOMPRA.FECHA 	   BETWEEN s$fechaInicial$s    AND s$fechaFinal$s 
  AND D_ORDENDECOMPRA.ELEMENTO BETWEEN s$elementoInicial$s AND s$elementoFinal$s 
GROUP BY D_ORDENDECOMPRA.ELEMENTO,
         INVENTARIO.NOMBRELARGO,
         D_ORDENDECOMPRA.CLASEORDEN, 
         ORDENDECOMPRA.NUMERO, 
         ORDENDECOMPRA.FECHA, 
         TERCERO.NOMBRE, 
         TERCERO.NIT
ORDER BY ORDENDECOMPRA.NUMERO
