SELECT 
    ACTDETPLAN_COMPRAS.ACTUALIZACION,
    ACTDETPLAN_COMPRAS.CANTIDAD,
    ACTDETPLAN_COMPRAS.COD_DETALLE,
    ACTDETPLAN_COMPRAS.CODIGO,
    ACTDETPLAN_COMPRAS.MES,
    ACTDETPLAN_COMPRAS.COMPANIA,
    ACTDETPLAN_COMPRAS.RUBRO,
    ACTDETPLAN_COMPRAS.TIPO,
    ACTDETPLAN_COMPRAS.VALORTOTAL,
    ACTDETPLAN_COMPRAS.VALOR_UNITARIO,
    ACTPLAN_DE_COMPRAS.FECHA, 
    ACTPLAN_DE_COMPRAS.NUMEROOFICIO, 
    INVENTARIO.NOMBRELARGO, 
    DEPENDENCIA.NOMBRE DEPENDENCIA_NOMBRE, 
    PLAN_DE_COMPRAS.NOMBRE NOMBRE, 
    ACTDETPLAN_COMPRAS.SUBPROYECTO 
FROM ACTDETPLAN_COMPRAS 
  LEFT JOIN DEPENDENCIA 
    ON ACTDETPLAN_COMPRAS.COMPANIA = DEPENDENCIA.COMPANIA
    AND ACTDETPLAN_COMPRAS.DEPENDENCIA = DEPENDENCIA.CODIGO
  LEFT JOIN INVENTARIO 
    ON ACTDETPLAN_COMPRAS.COMPANIA = INVENTARIO.COMPANIA
    AND ACTDETPLAN_COMPRAS.CODIGO = INVENTARIO.CODIGOELEMENTO
  LEFT JOIN PLAN_DE_COMPRAS 
    ON ACTDETPLAN_COMPRAS.COMPANIA = PLAN_DE_COMPRAS.COMPANIA
    AND ACTDETPLAN_COMPRAS.RUBRO = PLAN_DE_COMPRAS.CODIGO 
    AND ACTDETPLAN_COMPRAS.ANO = PLAN_DE_COMPRAS.ANO
  LEFT JOIN ACTPLAN_DE_COMPRAS 
    ON ACTDETPLAN_COMPRAS.COMPANIA = ACTPLAN_DE_COMPRAS.COMPANIA
    AND ACTDETPLAN_COMPRAS.ACTUALIZACION = ACTPLAN_DE_COMPRAS.ACTUALIZACION 
    AND ACTDETPLAN_COMPRAS.ANO = ACTPLAN_DE_COMPRAS.ANO 
WHERE ACTDETPLAN_COMPRAS.COMPANIA = s$compania$s
  AND ACTDETPLAN_COMPRAS.ACTUALIZACION = s$actualizacion$s
