MERGE INTO CONSULTAS FIN USING (SELECT '800366OtrosServiciosRIPS' INFORME ,TO_CLOB(q'[SELECT DISTINCT
	AF.CONSECUTIVO_RIPS CUENTA,
	AF.COD_PREST_SERV_SALUD,
	AF.NOMBRE_RAZON_SOCIAL,
	AF.TIPO_IDENTI_PREST_SERV_SALUD,
	AF.NUM_IDENTIF_PRESTADOR,
	AF.NUM_FACTURA,
	TO_CHAR(AF.FECHA_EXP_FACTURA,'DD/MM/YYYY') FECHA_EXP_FACTURA,
	TO_CHAR(AF.FECHA_INICIAL,'DD/MM/YYYY') FECHA_INICIAL,
	TO_CHAR(AF.FECHA_FINAL,'DD/MM/YYYY') FECHA_FINAL,
	AF.COD_ENTIDAD_ADMINISTRADORA,
	AF.NOMBRE_ENTIDAD_ADMINISTRADORA,
	AF.NUMERO_CONTRATO,
	AF.PLAN_BENEFICIOS,
	AF.NUMERO_POLIZA,
	AF.VALOR_TOT_PAGO_COMPARTIDO,
	AF.VALOR_COMISION,
	AF.VALOR_TOTAL_DESCUENTOS,
	AF.VALOR_NETO_A_PAGAR_ENTI_CONTR,
	CASE  WHEN AF.VALIDADO=0 THEN 'NO' WHEN AF.VALIDADO<>0 THEN 'SI' END VALIDADO_AF,
	AF.OBSERVACION_VALIDACION OBSERVACION_AF,
	AT.TIPO_IDENTIFICACION_USUARIO,
	AT.NUM_IDENTI_USUARIO_SISTEMA,
	AT.NUMERO_AUTORIZACION,
	AT.TIPO_SERVICIO,
	AT.CODIGO_SERVICIO,
	AT.NOMBRE_SERVICIO,
	AT.CANTIDAD,
	AT.VALOR_UNI_MATERIAL_INSUMO,
	AT.VALOR_TOTAL_MATERIAL_INSUMO,
	CASE  WHEN AT.VALIDADO=0 THEN 'NO' WHEN AT.VALIDADO<>0 THEN 'SI' END VALIDADO_AT,
	AT.OBSERVACION_VALIDACION OBSERVACION_AT
FROM
	CM_ARCHIVO_TRANSACCIONES AF
INNER JOIN CM_ARCHIVO_OTROS_SERVICIOS AT 
ON AT.COMPANIA=AF.COMPANIA 
AND AT.NUM_FACTURA=AF.NUM_FACTURA 
/*AND AF.COD_PREST_SERV_SALUD=AT.COD_PREST_SERV_SALUD */
AND AF.CONSECUTIVO_RIPS = AT.CONSECUTIVO_RIPS
WHERE
	AF.COMPANIA ='s$compania$s' 
	AND TO_CHAR(AF.CONSECUTIVO_RIPS) BETWEEN 's$conseucutivoInicial$s' AND 's$conseucutivoFinal$s' 
	AND AF.NUM_IDENTIF_PRESTADOR BETWEEN 's$terceroInicial$s' AND 's$terceroFinal$s'
	AND AF.NUM_FACTURA BETWEEN 's$facturaInicial$s' AND 's$facturaFinal$s'
	AND TO_CHAR(AF.FECHA_EXP_FACTURA,'DD/MM/YYYY') BETWEEN TO_DATE('s$fechaInicial$s', 'DD/MM/YYYY') AND TO_DATE('s$fechaFinal$s', 'DD/MM/YYYY')
	AND AT.NUM_IDENTI_USUARIO_SISTEMA BETWEEN 's$numIdentInicial$s' AND 's$numIdentFinal$s'
    ORDER BY CUENTA]') CONSULTA, 84 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);
    COMMIT;