MERGE INTO CONSULTAS FIN USING (SELECT '800368ConsultasRIPS' INFORME ,TO_CLOB(q'[SELECT 
	AF.CONSECUTIVO_RIPS CUENTA,
	AF.COD_PREST_SERV_SALUD,
	AF.NOMBRE_RAZON_SOCIAL,
	AF.TIPO_IDENTI_PREST_SERV_SALUD,
	AF.NUM_IDENTIF_PRESTADOR,
	AF.NUM_FACTURA,
	TO_CHAR(AF.FECHA_EXP_FACTURA,'DD/MM/YYYY') FECHA_EXP_FACTURA,
	TO_CHAR(AF.FECHA_INICIAL,'DD/MM/YYYY') FECHA_INICIAL,
	TO_CHAR(AF.FECHA_FINAL,'DD/MM/YYYY') FECHA_FINAL,
	AF.COD_ENTIDAD_ADMINISTRADORA,
	AF.NOMBRE_ENTIDAD_ADMINISTRADORA,
	AF.NUMERO_CONTRATO,
	AF.PLAN_BENEFICIOS,
	AF.NUMERO_POLIZA,
	AF.VALOR_TOT_PAGO_COMPARTIDO,
	AF.VALOR_COMISION,
	AF.VALOR_TOTAL_DESCUENTOS,
	AF.VALOR_NETO_A_PAGAR_ENTI_CONTR,
	CASE  WHEN AF.VALIDADO=0 THEN 'NO' WHEN AF.VALIDADO<>0 THEN 'SI' END VALIDADO_AF,
	AF.OBSERVACION_VALIDACION OBSERVACION_AF,
	AC.TIPO_IDENTIFICACION_USUARIO,
	AC.NUM_IDENTI_USUARIO_SISTEMA,
	TO_CHAR(AC.FECHA_CONSULTA,'DD/MM/YYYY') FECHA_CONSULTA,
	AC.NUMERO_AUTORIZACION,
	AC.CODIGO_CONSULTA,
	AC.FINALIDAD_CONSULTA,
	AC.CAUSA_EXTERNA,
	AC.COD_DIAGNOSTICO_PRINCIPAL,
	AC.COD_DIAGNOSTICO_RELACIONADO_1,
	AC.COD_DIAGNOSTICO_RELACIONADO_2,
	AC.COD_DIAGNOSTICO_RELACIONADO_3,
	AC.TIPO_DIAGNOSTICO_PRINCIPAL,
	AC.VALOR_CONSULTA,
	AC.VALOR_CUOTA_MODERADORA,
	AC.VALOR_NETO_A_PAGAR,
	CASE  WHEN AC.VALIDADO=0 THEN 'NO' WHEN AC.VALIDADO<>0 THEN 'SI' END VALIDADO_AC,
	AC.OBSERVACION_VALIDACION OBSERVACION_AC
FROM
	CM_ARCHIVO_TRANSACCIONES AF
INNER JOIN CM_ARCHIVO_CONSULTA AC 
ON AC.COMPANIA=AF.COMPANIA 
AND AC.NUM_FACTURA=AF.NUM_FACTURA 
/*AND AF.COD_PREST_SERV_SALUD=AC.COD_PREST_SERV_SALUD */
AND AF.CONSECUTIVO_RIPS = AC.CONSECUTIVO_RIPS
WHERE
	AF.COMPANIA ='s$compania$s' 
	AND TO_CHAR(AF.CONSECUTIVO_RIPS) BETWEEN 's$conseucutivoInicial$s' AND 's$conseucutivoFinal$s' 
        AND AF.NUM_IDENTIF_PRESTADOR BETWEEN 's$terceroInicial$s' AND 's$terceroFinal$s'
	AND AF.NUM_FACTURA BETWEEN 's$facturaInicial$s' AND 's$facturaFinal$s'
	AND TO_CHAR(AF.FECHA_EXP_FACTURA,'DD/MM/YYYY') BETWEEN TO_DATE('s$fechaInicial$s', 'DD/MM/YYYY') AND TO_DATE('s$fechaFinal$s', 'DD/MM/YYYY')
	AND AC.NUM_IDENTI_USUARIO_SISTEMA BETWEEN 's$numIdentInicial$s' AND 's$numIdentFinal$s'
    ORDER BY CUENTA]') CONSULTA, 84 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);
    COMMIT;