MERGE INTO CONSULTAS FIN USING (SELECT '800367UsuariosRIPS' INFORME ,TO_CLOB(q'[SELECT 
 US.TIPO_IDENTIFICACION_USUARIO,
 US.NUM_IDENTI_USUARIO_SISTEMA,
 US.TIPO_USUARIO,
 US.PRIMER_APELLIDO_USUA,
 US.SEGUNDO_APELLIDO_USUA,
 US.PRIMER_NOMBRE_USUA,
 US.SEGUNDO_NOMBRE_USUA,
 US.EDAD,
 US.UNIDAD_DE_MEDIDA_EDAD,
 US.SEXO,
 US.COD_DEPART_RESI_HABITUAL,
 US.COD_MUNI_RESIDENCIA_HABITUAL,
 US.ZONA_RESIDENCIA_HABITUAL,
 AUX.NUM_FACTURA,
 AUX.HOSPITALIZACION, 
 AUX.RECIEN_NACIDOS, 
 AUX.URGE_OBSERVACION, 
 AUX.CONSULTAS,
 AUX.MEDICAMENTOS,
 AUX.PROCEDIMIENTOS,
 AUX.OTROS_SERVICIOS,
 AF.VALOR_COMISION,
 AF.VALOR_TOT_PAGO_COMPARTIDO,
 AF.VALOR_TOTAL_DESCUENTOS,
 AF.VALOR_NETO_A_PAGAR_ENTI_CONTR,
 CASE  WHEN US.VALIDADO=0 THEN 'NO' WHEN US.VALIDADO<>0 THEN 'SI' END VALIDADO_US,
 US.OBSERVACION_VALIDACION OBSERVACION_US

FROM CM_ARCHIVO_USUARIOS US
INNER JOIN 

(SELECT  SUM.NUM_IDENTI_USUARIO_SISTEMA,
SUM.NUM_FACTURA,
CASE WHEN AH.NUM_IDENTI_USUARIO_SISTEMA IS NULL THEN 'NO' ELSE 'SI' END HOSPITALIZACION,
CASE WHEN AN.NUMERO_IDENTI_MADRE IS NULL THEN 'NO' ELSE 'SI' END RECIEN_NACIDOS,
CASE WHEN AU.NUM_IDENTI_USUARIO_SISTEMA IS NULL THEN 'NO' ELSE 'SI' END URGE_OBSERVACION,
SUM(CONSULTAS) CONSULTAS, 
SUM(SUM.MEDICAMENTOS) MEDICAMENTOS,
SUM(SUM.PROCEDIMIENTOS) PROCEDIMIENTOS,
SUM(SUM.OTROS_SERVICIOS) OTROS_SERVICIOS

FROM

(SELECT COMPANIA,
 NUM_IDENTI_USUARIO_SISTEMA,
 NUM_FACTURA,
 VALOR_NETO_A_PAGAR CONSULTAS, 
 0 MEDICAMENTOS,
 0 PROCEDIMIENTOS,
 0 OTROS_SERVICIOS
 FROM CM_ARCHIVO_CONSULTA

 UNION 

 SELECT COMPANIA,
 NUM_IDENTI_USUARIO_SISTEMA,
 NUM_FACTURA,
 0 CONSULTAS, 
 VALOR_TOTAL_MEDICAMENTO MEDICAMENTOS,
 0 PROCEDIMIENTOS,
 0 OTROS_SERVICIOS
 FROM CM_ARCHIVO_MEDICAMENTOS

 UNION 

 SELECT COMPANIA,
 NUM_IDENTI_USUARIO_SISTEMA,
 NUM_FACTURA,
 0 CONSULTAS, 
 0 MEDICAMENTOS,
 VALOR_PROCEDIMIENTO PROCEDIMIENTOS,

 0 OTROS_SERVICIOS
 FROM CM_ARCHIVO_PROCEDIMIENTOS

 UNION 

 SELECT COMPANIA,
 NUM_IDENTI_USUARIO_SISTEMA,
 NUM_FACTURA,
 0 CONSULTAS, 
 0 MEDICAMENTOS,
 0 PROCEDIMIENTOS,
 VALOR_TOTAL_MATERIAL_INSUMO OTROS_SERVICIOS
 FROM CM_ARCHIVO_OTROS_SERVICIOS) SUM
LEFT JOIN CM_ARCHIVO_HOSPITALIZACION AH ON SUM.COMPANIA = AH.COMPANIA 
AND SUM.NUM_IDENTI_USUARIO_SISTEMA=AH.NUM_IDENTI_USUARIO_SISTEMA 
AND SUM.NUM_FACTURA=AH.NUM_FACTURA
LEFT JOIN CM_ARCHIVO_RECIEN_NACIDOS AN ON SUM.COMPANIA = AN.COMPANIA AND SUM.NUM_IDENTI_USUARIO_SISTEMA=AN.NUMERO_IDENTI_MADRE AND SUM.NUM_FACTURA=AN.NUM_FACTURA
LEFT JOIN CM_ARCHIVO_URGE_OBSERVACION AU ON SUM.COMPANIA = AU.COMPANIA AND SUM.NUM_IDENTI_USUARIO_SISTEMA=AU.NUM_IDENTI_USUARIO_SISTEMA AND SUM.NUM_FACTURA=AU.NUM_FACTURA
GROUP BY SUM.NUM_IDENTI_USUARIO_SISTEMA,
SUM.NUM_FACTURA,
CASE WHEN AH.NUM_IDENTI_USUARIO_SISTEMA IS NULL THEN 'NO' ELSE 'SI' END,
CASE WHEN AN.NUMERO_IDENTI_MADRE IS NULL THEN 'NO' ELSE 'SI' END,
CASE WHEN AU.NUM_IDENTI_USUARIO_SISTEMA IS NULL THEN 'NO' ELSE 'SI' END) AUX ON US.NUM_IDENTI_USUARIO_SISTEMA=AUX.NUM_IDENTI_USUARIO_SISTEMA
INNER JOIN CM_ARCHIVO_TRANSACCIONES AF 
ON AF.C]') || TO_CLOB(q'[OMPANIA =  US.COMPANIA 
AND AUX.NUM_FACTURA = AF.NUM_FACTURA
    WHERE AF.COMPANIA ='s$compania$s' 
 AND TO_CHAR(AF.CONSECUTIVO_RIPS) BETWEEN 's$conseucutivoInicial$s' AND 's$conseucutivoFinal$s' 
    AND AF.NUM_IDENTIF_PRESTADOR BETWEEN 's$terceroInicial$s' AND 's$terceroFinal$s'
 AND AF.NUM_FACTURA BETWEEN 's$facturaInicial$s' AND 's$facturaFinal$s'
    AND TO_CHAR(AF.FECHA_EXP_FACTURA,'DD/MM/YYYY') BETWEEN TO_DATE('s$fechaInicial$s', 'DD/MM/YYYY') AND TO_DATE('s$fechaFinal$s', 'DD/MM/YYYY')
 AND US.NUM_IDENTI_USUARIO_SISTEMA BETWEEN 's$numIdentInicial$s' AND 's$numIdentFinal$s'
]') CONSULTA, 84 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);
COMMIT;