MERGE INTO CONSULTAS FIN USING (SELECT '800539InformeAuditoriasCuentasMedicasFT024' INFORME ,TO_CLOB(q'[SELECT NIT "NIT EPS", 
       PERIODO, 
       TIPO_CUENTA "TIPO DE CUENTA", 
       VALOR_RADICADO "VALOR RADICADO", 
       VALOR_APROBADO "VALOR APROBADO", 
       VALOR_PAGADO "VALOR PAGADO", 
       VALOR_GIRADO "VALOR GIRADO", 
       PORCENTAJE_GLOSA "PORCENTAJE GLOSA", 
       VALOR_DESCUENTO "VALOR DESCUENTO", 
       SALDO 
FROM (
SELECT CM_IMPORTARRIPS.NIT, 
       TO_CHAR(CM_IMPORTARRIPS.FECHA,'YYYYMM') PERIODO,
       '2' TIPO_CUENTA,
       CM_AUDITORIA_GLOSAS.NUM_FACTURA,
       SUM(CM_AUDITORIA_GLOSAS.VALOR_NETO_A_PAGAR_ENTI_CONTR) VALOR_RADICADO,
       SUM(CM_AUDITORIA_GLOSAS.TOTAL_APROBADO_PAGAR) VALOR_APROBADO,
       0 VALOR_PAGADO,
       0 VALOR_GIRADO,
       0 PORCENTAJE_GLOSA,
       SUM(CM_AUDITORIA_GLOSAS.VALOR_ACEPTADO_PAGADOR) VALOR_DESCUENTO,
       SUM(CM_AUDITORIA_GLOSAS.VALOR_NETO_A_PAGAR_ENTI_CONTR-CM_AUDITORIA_GLOSAS.VALOR_ACEPTADO_PAGADOR-0 ) SALDO 
FROM CM_IMPORTARRIPS
INNER JOIN CM_AUDITORIA_GLOSAS 
        ON CM_IMPORTARRIPS.CONSECUTIVO = CM_AUDITORIA_GLOSAS.CONSECUTIVO_ARCHIVO
       AND CM_IMPORTARRIPS.COMPANIA = CM_AUDITORIA_GLOSAS.COMPANIA
     WHERE CM_IMPORTARRIPS.CLASECUENTA BETWEEN 's$ClaseCuentaInicial$s' AND 's$ClaseCuentaFinal$s'
       AND TO_CHAR(CM_IMPORTARRIPS.FECHA,'DD/MM/YYYY') BETWEEN TO_DATE('s$FechaInicial$s', 'DD/MM/YYYY') AND TO_DATE('s$FechaFinal$s', 'DD/MM/YYYY')
  GROUP BY CM_IMPORTARRIPS.NIT,
           CM_IMPORTARRIPS.FECHA,
           '2',
           CM_AUDITORIA_GLOSAS.NUM_FACTURA,
           0,
           0,
           0
  ORDER BY CM_IMPORTARRIPS.NIT,CM_IMPORTARRIPS.FECHA )]') CONSULTA, 84 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, 'ADMIN' CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);