SELECT     TIPO_COMPROBANTE.COMPANIA, 
           TIPO_COMPROBANTE.CODIGO, 
           TIPO_COMPROBANTE.NOMBRE, 
           TIPO_COMPROBANTE.PIDE_RETENCION, 
           TIPO_COMPROBANTE.TIPO_DOCUMENTO, 
           TIPO_COMPROBANTE.CLASE_CONTABLE, 
           NVL(TIPO_COMPROBANTE.FORMATO,' ') FORMATO, 
           TIPO_COMPROBANTE.COMPRELACIONADO
 FROM      TIPO_COMPROBANTE 
 WHERE     TIPO_COMPROBANTE.COMPANIA = s$compania$s
