MERGE INTO CONSULTAS FIN USING (SELECT '000588BalancePrueba' INFORME ,TO_CLOB(q'[SELECT  SUBSTR(SALDOAUX.CODIGO,1,1) CLASE, 
        SALDOAUX.CODIGO, 
        SALDOAUX.DEBITO, 
        SALDOAUX.CREDITO, 
        SALDOAUX.NOMBRE,
        SALDOAUX.COMPANIA, 
        SALDOAUX.TERCERO,
        CASE WHEN (SALDOAUX.NATURALEZA = 'D' AND (SALDOAUX.SALDOANT)>=0) 
                OR (SALDOAUX.NATURALEZA = 'C' AND (SALDOAUX.SALDOANT)<0)   
              THEN ABS(SALDOAUX.SALDOANT)
              ELSE 0 END SALDOANTDEBITO,
         CASE WHEN (SALDOAUX.NATURALEZA = 'C' AND (SALDOAUX.SALDOANT)>=0) 
                OR (SALDOAUX.NATURALEZA = 'D' AND (SALDOAUX.SALDOANT)<0)   
              THEN ABS(SALDOAUX.SALDOANT)
              ELSE 0 END SALDOANTCREDITO,        
         CASE WHEN (SALDOAUX.NATURALEZA = 'D' AND (SALDOAUX.SALDOFIN)>=0) 
                OR (SALDOAUX.NATURALEZA = 'C' AND (SALDOAUX.SALDOFIN)<0)   
              THEN ABS(SALDOAUX.SALDOFIN)
              ELSE 0 END SALDONUEDEBITO,
         CASE WHEN (SALDOAUX.NATURALEZA = 'C' AND (SALDOAUX.SALDOFIN)>=0) 
                OR (SALDOAUX.NATURALEZA = 'D' AND (SALDOAUX.SALDOFIN)<0)   
              THEN ABS(SALDOAUX.SALDOFIN)
              ELSE 0 END SALDONUECREDITO, 
        SUBSTR((CASE WHEN SUBSTR(SALDOAUX.CODIGO,1,1)='0'
             THEN 'z'||SALDOAUX.CODIGO
             ELSE SALDOAUX.CODIGO
             END),1,1) AS CLASEORDEN,
        SALDOAUX.ORDEN ORDENCUENTAS,
           CASE WHEN SUBSTR(SALDOAUX.CODIGO,1,1)='0'
             THEN 'z'||SALDOAUX.CODIGO
             ELSE SALDOAUX.CODIGO
             END AS ORDEN,
           SALDOAUX.CENTRO_COSTO,
           SALDOAUX.REFERENCIA, 
           SALDOAUX.AUXILIAR,
           SALDOAUX.FUENTE_RECURSOS    
FROM (s$baseBalance$s) SALDOAUX 
LEFT JOIN SALDO_AUX_CONTABLE  
  ON SALDOAUX.COMPANIA = SALDO_AUX_CONTABLE.COMPANIA 
  AND SALDOAUX.ANO       = SALDO_AUX_CONTABLE.ANO      
  AND SALDOAUX.CODIGO    = SALDO_AUX_CONTABLE.CODIGO  
  AND SALDOAUX.CENTRO_COSTO = SALDO_AUX_CONTABLE.CENTRO_COSTO  
  AND SALDOAUX.TERCERO = SALDO_AUX_CONTABLE.TERCERO  
  AND SALDOAUX.AUXILIAR = SALDO_AUX_CONTABLE.AUXILIAR  
  AND SALDOAUX.REFERENCIA = SALDO_AUX_CONTABLE.REFERENCIA  
  AND SALDOAUX.FUENTE_RECURSOS = SALDO_AUX_CONTABLE.FUENTE_RECURSO 
WHERE LENGTH(SALDOAUX.CODIGO) <= s$digitos$s
   AND (SALDOAUX.DEBITO         + SALDOAUX.CREDITO 
      + ABS(SALDOAUX.SALDOANT)  + ABS(SALDOAUX.SALDOFIN) 
      ) <>
      CASE WHEN s$saldoCero$s = 0
      THEN 0
      ELSE SALDOAUX.DEBITO         + SALDOAUX.CREDITO 
         + ABS(SALDOAUX.SALDOANT)  + ABS(SALDOAUX.SALDOFIN)
         + 1 
      END

      and
     (CASE WHEN (SALDOAUX.NATURALEZA = 'D' AND (SALDOAUX.SALDOFIN)>=0 AND (ABS(SALDOAUX.SALDOANT) >=0  OR SALDOAUX.DEBITO > 0) ) 
                OR (SALDOAUX.NATURALEZA = 'C' AND (SALDOAUX.SALDOFIN)<=0  AND (ABS(SALDOAUX.SALDOANT) >=0  OR SALDOAUX.CREDITO < 0))   
              THEN ABS(SALDOAUX.SALDOFIN) + 1
              ELSE 0 END +
         CASE WHEN (SALDOAUX.NATURALEZA = 'C' AND (SALDOAUX.SALDO]') || TO_CLOB(q'[FIN)>=0 AND (ABS(SALDOAUX.SALDOANT) >=0  OR SALDOAUX.CREDITO > 0) ) 
                OR (SALDOAUX.NATURALEZA = 'D' AND (SALDOAUX.SALDOFIN)<=0 AND (ABS(SALDOAUX.SALDOANT) >=0 OR SALDOAUX.DEBITO < 0))   
              THEN ABS(SALDOAUX.SALDOFIN) + 1
              ELSE 0 END 
      )>0]') CONSULTA, 1 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);