SELECT  COMPANIA, 
        ANO, 
        CODIGO,
        NATURALEZA,
        NOMBRE NOMBRE,
        CODIGO ORDEN,
        CODIGO CLASE,
        DEBITO,
        CREDITO,
        SALDOANT,  
        SALDOFIN
FROM (

SELECT 
        PLAN_CONTABLE.COMPANIA, 
        PLAN_CONTABLE.ANO, 
        PLAN_CONTABLE.CODIGO,
        PLAN_CONTABLE.NATURALEZA,
        (CASE WHEN 0  BETWEEN s$mesIni$s AND s$mesFin$s  THEN PLAN_CONTABLE.DEBITO0  ELSE 0 END
          + CASE WHEN 1  BETWEEN s$mesIni$s AND s$mesFin$s  THEN PLAN_CONTABLE.DEBITO1  ELSE 0 END
          + CASE WHEN 2  BETWEEN s$mesIni$s AND s$mesFin$s  THEN PLAN_CONTABLE.DEBITO2  ELSE 0 END
          + CASE WHEN 3  BETWEEN s$mesIni$s AND s$mesFin$s  THEN PLAN_CONTABLE.DEBITO3  ELSE 0 END
          + CASE WHEN 4  BETWEEN s$mesIni$s AND s$mesFin$s  THEN PLAN_CONTABLE.DEBITO4  ELSE 0 END
          + CASE WHEN 5  BETWEEN s$mesIni$s AND s$mesFin$s  THEN PLAN_CONTABLE.DEBITO5  ELSE 0 END
          + CASE WHEN 6  BETWEEN s$mesIni$s AND s$mesFin$s  THEN PLAN_CONTABLE.DEBITO6  ELSE 0 END
          + CASE WHEN 7  BETWEEN s$mesIni$s AND s$mesFin$s  THEN PLAN_CONTABLE.DEBITO7  ELSE 0 END
          + CASE WHEN 8  BETWEEN s$mesIni$s AND s$mesFin$s  THEN PLAN_CONTABLE.DEBITO8  ELSE 0 END
          + CASE WHEN 9  BETWEEN s$mesIni$s AND s$mesFin$s  THEN PLAN_CONTABLE.DEBITO9  ELSE 0 END
          + CASE WHEN 10 BETWEEN s$mesIni$s AND s$mesFin$s  THEN PLAN_CONTABLE.DEBITO10 ELSE 0 END
          + CASE WHEN 11 BETWEEN s$mesIni$s AND s$mesFin$s  THEN PLAN_CONTABLE.DEBITO11 ELSE 0 END
          + CASE WHEN 12 BETWEEN s$mesIni$s AND s$mesFin$s  THEN PLAN_CONTABLE.DEBITO12 ELSE 0 END
          + CASE WHEN 13 BETWEEN s$mesIni$s AND s$mesFin$s  THEN PLAN_CONTABLE.DEBITO13 ELSE 0 END
          ) DEBITO,
        (CASE WHEN 0  BETWEEN s$mesIni$s AND s$mesFin$s  THEN PLAN_CONTABLE.CREDITO0  ELSE 0 END
          + CASE WHEN 1  BETWEEN s$mesIni$s AND s$mesFin$s  THEN PLAN_CONTABLE.CREDITO1  ELSE 0 END
          + CASE WHEN 2  BETWEEN s$mesIni$s AND s$mesFin$s  THEN PLAN_CONTABLE.CREDITO2  ELSE 0 END
          + CASE WHEN 3  BETWEEN s$mesIni$s AND s$mesFin$s  THEN PLAN_CONTABLE.CREDITO3  ELSE 0 END
          + CASE WHEN 4  BETWEEN s$mesIni$s AND s$mesFin$s  THEN PLAN_CONTABLE.CREDITO4  ELSE 0 END
          + CASE WHEN 5  BETWEEN s$mesIni$s AND s$mesFin$s  THEN PLAN_CONTABLE.CREDITO5  ELSE 0 END
          + CASE WHEN 6  BETWEEN s$mesIni$s AND s$mesFin$s  THEN PLAN_CONTABLE.CREDITO6  ELSE 0 END
          + CASE WHEN 7  BETWEEN s$mesIni$s AND s$mesFin$s  THEN PLAN_CONTABLE.CREDITO7  ELSE 0 END
          + CASE WHEN 8  BETWEEN s$mesIni$s AND s$mesFin$s  THEN PLAN_CONTABLE.CREDITO8  ELSE 0 END
          + CASE WHEN 9  BETWEEN s$mesIni$s AND s$mesFin$s  THEN PLAN_CONTABLE.CREDITO9  ELSE 0 END
          + CASE WHEN 10 BETWEEN s$mesIni$s AND s$mesFin$s  THEN PLAN_CONTABLE.CREDITO10 ELSE 0 END
          + CASE WHEN 11 BETWEEN s$mesIni$s AND s$mesFin$s  THEN PLAN_CONTABLE.CREDITO11 ELSE 0 END
          + CASE WHEN 12 BETWEEN s$mesIni$s AND s$mesFin$s  THEN PLAN_CONTABLE.CREDITO12 ELSE 0 END
          + CASE WHEN 13 BETWEEN s$mesIni$s AND s$mesFin$s  THEN PLAN_CONTABLE.CREDITO13 ELSE 0 END
          ) CREDITO,
            CASE WHEN 0  = s$mesIni$s -1  THEN PLAN_CONTABLE.SALDO0  ELSE 0 END
          + CASE WHEN 1  = s$mesIni$s -1  THEN PLAN_CONTABLE.SALDO1  ELSE 0 END
          + CASE WHEN 2  = s$mesIni$s -1  THEN PLAN_CONTABLE.SALDO2  ELSE 0 END
          + CASE WHEN 3  = s$mesIni$s -1  THEN PLAN_CONTABLE.SALDO3  ELSE 0 END
          + CASE WHEN 4  = s$mesIni$s -1  THEN PLAN_CONTABLE.SALDO4  ELSE 0 END
          + CASE WHEN 5  = s$mesIni$s -1  THEN PLAN_CONTABLE.SALDO5  ELSE 0 END
          + CASE WHEN 6  = s$mesIni$s -1  THEN PLAN_CONTABLE.SALDO6  ELSE 0 END
          + CASE WHEN 7  = s$mesIni$s -1  THEN PLAN_CONTABLE.SALDO7  ELSE 0 END
          + CASE WHEN 8  = s$mesIni$s -1  THEN PLAN_CONTABLE.SALDO8  ELSE 0 END
          + CASE WHEN 9  = s$mesIni$s -1  THEN PLAN_CONTABLE.SALDO9  ELSE 0 END
          + CASE WHEN 10 = s$mesIni$s -1  THEN PLAN_CONTABLE.SALDO10 ELSE 0 END
          + CASE WHEN 11 = s$mesIni$s -1  THEN PLAN_CONTABLE.SALDO11 ELSE 0 END
          + CASE WHEN 12 = s$mesIni$s -1  THEN PLAN_CONTABLE.SALDO12 ELSE 0 END
          + CASE WHEN 13 = s$mesIni$s -1  THEN PLAN_CONTABLE.SALDO13 ELSE 0 END
          SALDOANT,
            CASE WHEN 0  = s$mesFin$s  THEN PLAN_CONTABLE.SALDO0  ELSE 0 END
          + CASE WHEN 1  = s$mesFin$s  THEN PLAN_CONTABLE.SALDO1  ELSE 0 END
          + CASE WHEN 2  = s$mesFin$s  THEN PLAN_CONTABLE.SALDO2  ELSE 0 END
          + CASE WHEN 3  = s$mesFin$s  THEN PLAN_CONTABLE.SALDO3  ELSE 0 END
          + CASE WHEN 4  = s$mesFin$s  THEN PLAN_CONTABLE.SALDO4  ELSE 0 END
          + CASE WHEN 5  = s$mesFin$s  THEN PLAN_CONTABLE.SALDO5  ELSE 0 END
          + CASE WHEN 6  = s$mesFin$s  THEN PLAN_CONTABLE.SALDO6  ELSE 0 END
          + CASE WHEN 7  = s$mesFin$s  THEN PLAN_CONTABLE.SALDO7  ELSE 0 END
          + CASE WHEN 8  = s$mesFin$s  THEN PLAN_CONTABLE.SALDO8  ELSE 0 END
          + CASE WHEN 9  = s$mesFin$s  THEN PLAN_CONTABLE.SALDO9  ELSE 0 END
          + CASE WHEN 10 = s$mesFin$s  THEN PLAN_CONTABLE.SALDO10 ELSE 0 END
          + CASE WHEN 11 = s$mesFin$s  THEN PLAN_CONTABLE.SALDO11 ELSE 0 END
          + CASE WHEN 12 = s$mesFin$s  THEN PLAN_CONTABLE.SALDO12 ELSE 0 END
          + CASE WHEN 13 = s$mesFin$s  THEN PLAN_CONTABLE.SALDO13 ELSE 0 END
          SALDOFIN,                  
        PLAN_CONTABLE.NOMBRE NOMBRE,
        PLAN_CONTABLE.CODIGO ORDEN,
        PLAN_CONTABLE.CODIGO CLASE
  FROM  PLAN_CONTABLE 
WHERE PLAN_CONTABLE.COMPANIA = s$compania$s
  AND PLAN_CONTABLE.ANO      = s$anio$s
  AND PLAN_CONTABLE.CODIGO  BETWEEN 's$codigoInicial$s' AND 's$codigoFinal$s'
  AND LENGTH(PLAN_CONTABLE.CODIGO) =1
  
 ) SALDOAUX
