SELECT  TERCERO.NIT NIT,
		DETALLE_COMPROBANTE_CNT.TERCERO,
        DETALLE_COMPROBANTE_CNT.SUCURSAL, 
        DETALLE_COMPROBANTE_CNT.FECHA,
        TERCERO.NOMBRE TERCERONOMBRE, 
        TIPO_COMPROBANTE.NOMBRE TIPO_COMPROBANTE_NOM,
        DETALLE_COMPROBANTE_CNT.COMPROBANTE, 
        PLAN_CONTABLE.CLASECUENTA,
        DETALLE_COMPROBANTE_CNT.BASE_GRAVABLE, 
        DETALLE_COMPROBANTE_CNT.CENTRO_COSTO CENTRODECOSTO, 
        DETALLE_COMPROBANTE_CNT.AUXILIAR CODAUXILIAR,
        PLAN_CONTABLE.CODIGO  CODIGO_CUENTA ,
        PLAN_CONTABLE.NOMBRE CUENTANOMBRE,
		DETALLE_COMPROBANTE_CNT.DESCRIPCION  DESCRIPCION_DET,
		COMPROBANTE_CNT.DESCRIPCION COMPROBANTE_CNTDESCRIPCION,
        DETALLE_COMPROBANTE_CNT.VALOR_DEBITO, 
        DETALLE_COMPROBANTE_CNT.VALOR_CREDITO, 
        DETALLE_COMPROBANTE_CNT.COMPANIA, 
        DETALLE_COMPROBANTE_CNT.TIPO_CPTE
		
FROM DETALLE_COMPROBANTE_CNT 
  INNER JOIN COMPROBANTE_CNT 
    ON  DETALLE_COMPROBANTE_CNT.COMPANIA   = COMPROBANTE_CNT.COMPANIA 
    AND DETALLE_COMPROBANTE_CNT.ANO        = COMPROBANTE_CNT.ANO 
    AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE  = COMPROBANTE_CNT.TIPO 
    AND DETALLE_COMPROBANTE_CNT.COMPROBANTE = COMPROBANTE_CNT.NUMERO 
  INNER JOIN PLAN_CONTABLE
    ON  DETALLE_COMPROBANTE_CNT.COMPANIA     = PLAN_CONTABLE.COMPANIA 
    AND DETALLE_COMPROBANTE_CNT.ANO          = PLAN_CONTABLE.ANO 
    AND DETALLE_COMPROBANTE_CNT.CUENTA       = PLAN_CONTABLE.CODIGO 
  INNER JOIN TERCERO 
    ON  DETALLE_COMPROBANTE_CNT.COMPANIA     = TERCERO.COMPANIA 
    AND DETALLE_COMPROBANTE_CNT.TERCERO      = TERCERO.NIT
    AND DETALLE_COMPROBANTE_CNT.SUCURSAL     = TERCERO.SUCURSAL 
  INNER JOIN TIPO_COMPROBANTE 
    ON  DETALLE_COMPROBANTE_CNT.COMPANIA  = TIPO_COMPROBANTE.COMPANIA 
    AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE = TIPO_COMPROBANTE.CODIGO 
WHERE DETALLE_COMPROBANTE_CNT.COMPANIA = '001'
  AND DETALLE_COMPROBANTE_CNT.TERCERO  BETWEEN 's$terceroInicial$s'
                                          AND 's$terceroFinal$s' 
  AND DETALLE_COMPROBANTE_CNT.SUCURSAL BETWEEN 's$sucursalInicial$s'
                                          AND 's$sucursalFinal$s' 
  AND DETALLE_COMPROBANTE_CNT.FECHA    BETWEEN s$fechaInicial$s 
                                          AND s$fechaFinal$s 
  AND DETALLE_COMPROBANTE_CNT.ID  BETWEEN 's$codigoInicial$s'
                                               AND 's$codigoFinal$s'
