SELECT SUBSTR(PLAN_CONTABLE.CODIGO,1,1)  CLASE,
       PLAN_CONTABLE.COMPANIA,
       PLAN_CONTABLE.ANO,
       CASE WHEN PLAN_CONTABLE.CCBALANCE IS NULL 
            THEN CENTRO_COSTOCCBALANCE.NOMBRE||' \ '||PLAN_CONTABLENOM.NOMBRE 
            ELSE '' 
       END NOMBRE,
       PCK_SYSMAN_UTL.FC_CODIGO_CNT_CCYOPAL( PLAN_CONTABLE.COMPANIA,PLAN_CONTABLE.ANO,PLAN_CONTABLE.CODIGO,CENTRO_COSTOESP.CODIGO,'','','','','') AS CODIGO,
       REPLACE(PCK_SYSMAN_UTL.FC_CODIGO_CNT_CCYOPAL( PLAN_CONTABLE.COMPANIA,PLAN_CONTABLE.ANO,PLAN_CONTABLE.CODIGO,CENTRO_COSTOESP.CODIGO,'','','','',''),' ','') CODIGOCOMP, 
       SUBSTR((CASE WHEN SUBSTR(PLAN_CONTABLE.CODIGO,1,1)='0'
             THEN 'z'||PLAN_CONTABLE.CODIGO
             ELSE PLAN_CONTABLE.CODIGO
             END),1,1) AS CLASEORDEN,
        CASE WHEN SUBSTR(PLAN_CONTABLE.CODIGO,1,1)='0'
             THEN 'z'||PLAN_CONTABLE.CODIGO
             ELSE PLAN_CONTABLE.CODIGO
             END AS ORDEN,
       (PLAN_CONTABLE.DEBITOs$mestrabajo$s*CENTRO_COSTOESP.PORCENTAJE)/100 AS DEBITO,
       (PLAN_CONTABLE.CREDITOs$mestrabajo$s*CENTRO_COSTOESP.PORCENTAJE)/100  AS CREDITO,
       (CASE WHEN PLAN_CONTABLE.NATURALEZA='D' AND PLAN_CONTABLE.SALDOs$mestrabajo-1$s >=0
              THEN PLAN_CONTABLE.SALDOs$mestrabajo-1$s
                 ELSE 0
                 END  + CASE WHEN PLAN_CONTABLE.NATURALEZA='C' AND PLAN_CONTABLE.SALDOs$mestrabajo-1$s <0
                             THEN -PLAN_CONTABLE.SALDOs$mestrabajo-1$s
                             ELSE 0
                             END) *CENTRO_COSTOESP.PORCENTAJE/100 AS SALDOANTDEBITO,
      ((CASE WHEN PLAN_CONTABLE.NATURALEZA='C' AND PLAN_CONTABLE.SALDOs$mestrabajo-1$s >=0
                  THEN PLAN_CONTABLE.SALDOs$mestrabajo-1$s
                  ELSE 0
                  END  + CASE WHEN PLAN_CONTABLE.NATURALEZA='D'  AND PLAN_CONTABLE.SALDOs$mestrabajo-1$s  <0
                             THEN -PLAN_CONTABLE.SALDOs$mestrabajo-1$s
                             ELSE 0
                             END)*CENTRO_COSTOESP.PORCENTAJE)/100 AS SALDOANTCREDITO,
       ((CASE WHEN PLAN_CONTABLE.NATURALEZA='D' AND PLAN_CONTABLE.SALDOs$mestrabajo-1$s >=0
              THEN PLAN_CONTABLE.SALDOs$mestrabajo-1$s
              ELSE 0
              END  + CASE WHEN PLAN_CONTABLE.NATURALEZA='C' AND PLAN_CONTABLE.SALDOs$mestrabajo-1$s <0
                          THEN -PLAN_CONTABLE.SALDOs$mestrabajo-1$s
                          ELSE 0
                          END)*CENTRO_COSTOESP.PORCENTAJE)/100 AS SALDONUEDEBITO, 
        ((CASE WHEN PLAN_CONTABLE.NATURALEZA='C' AND PLAN_CONTABLE.SALDOs$mestrabajo-1$s >=0
               THEN PLAN_CONTABLE.SALDOs$mestrabajo-1$s
               ELSE 0
               END  + CASE WHEN PLAN_CONTABLE.NATURALEZA='D' AND PLAN_CONTABLE.SALDOs$mestrabajo-1$s  <0
                           THEN -PLAN_CONTABLE.SALDOs$mestrabajo-1$s
                           ELSE 0
                           END)*CENTRO_COSTOESP.PORCENTAJE)/100 AS SALDONUECREDITO   
FROM V_PLAN_CONTABLE PLAN_CONTABLE
       LEFT JOIN CENTRO_COSTOESP
           ON  PLAN_CONTABLE.COMPANIA = CENTRO_COSTOESP.COMPANIA
           AND PLAN_CONTABLE.ANO      = CENTRO_COSTOESP.ANO
              INNER JOIN CENTRO_COSTO CENTRO_COSTOCCBALANCE
                  ON  CENTRO_COSTOESP.COMPANIA       = CENTRO_COSTOCCBALANCE.COMPANIA
                  AND CENTRO_COSTOESP.ANO            = CENTRO_COSTOCCBALANCE.ANO
                  AND CENTRO_COSTOESP.CODIGO         = CENTRO_COSTOCCBALANCE.CODIGO
    INNER JOIN V_PLAN_CONTABLE PLAN_CONTABLENOM
      ON  PLAN_CONTABLE.COMPANIA           = PLAN_CONTABLENOM.COMPANIA
      AND PLAN_CONTABLE.ANO                = PLAN_CONTABLENOM.ANO
      AND SUBSTR(PLAN_CONTABLE.CODIGO,1,1) = PLAN_CONTABLENOM.CODIGO
    LEFT JOIN TERCERO 
        ON  PLAN_CONTABLE.COMPANIA = TERCERO.COMPANIA 
        AND PLAN_CONTABLE.TERCERO  = TERCERO.NIT 
        AND PLAN_CONTABLE.SUCURSAL = TERCERO.SUCURSAL 
    LEFT JOIN AUXILIAR 
        ON  PLAN_CONTABLE.COMPANIA = AUXILIAR.COMPANIA 
        AND PLAN_CONTABLE.ANO      = AUXILIAR.ANO   
        AND PLAN_CONTABLE.AUXILIAR = AUXILIAR.CODIGO 
    LEFT JOIN CENTRO_COSTO 
        ON  PLAN_CONTABLE.COMPANIA     = CENTRO_COSTO.COMPANIA    
        AND PLAN_CONTABLE.ANO          = CENTRO_COSTO.ANO     
        AND PLAN_CONTABLE.CENTRO_COSTO = CENTRO_COSTO.CODIGO 
WHERE PLAN_CONTABLE.ANO       =  s$anoTrabajo$s
  AND PLAN_CONTABLE.CCBALANCE IS NULL 
  AND LENGTH(PLAN_CONTABLE.CODIGO) <= s$digitos$s 
  AND CENTRO_COSTOESP.MES           = s$mestrabajo$s
  AND PLAN_CONTABLE.MOVIMIENTO NOT IN (0)
  s$condAuxiliar$s
  s$condCentroCosto$s
  s$condTercero$s 
  s$condSaldoCero$s
UNION ALL
SELECT SUBSTR(PLAN_CONTABLE.CODIGO,1,1)  CLASE, 
       PLAN_CONTABLE.COMPANIA,
       PLAN_CONTABLE.ANO,
       CASE WHEN PLAN_CONTABLE.CCBALANCE IS NOT NULL 
            THEN CENTRO_COSTOCCBALANCE.NOMBRE||' \ '||PLAN_CONTABLENOM.NOMBRE 
            ELSE '' 
       END NOMBRE,
       PCK_SYSMAN_UTL.FC_CODIGO_CNT_CCYOPAL( PLAN_CONTABLE.COMPANIA,PLAN_CONTABLE.ANO,PLAN_CONTABLE.CODIGO,CENTRO_COSTOESP.CODIGO,'','','','','') AS CODIGO,
       REPLACE(PCK_SYSMAN_UTL.FC_CODIGO_CNT_CCYOPAL( PLAN_CONTABLE.COMPANIA,PLAN_CONTABLE.ANO,PLAN_CONTABLE.CODIGO,CENTRO_COSTOESP.CODIGO,'','','','',''),' ','') CODIGOCOMP, 
       SUBSTR((CASE WHEN SUBSTR(PLAN_CONTABLE.CODIGO,1,1)='0'
             THEN 'z'||PLAN_CONTABLE.CODIGO
             ELSE PLAN_CONTABLE.CODIGO
             END),1,1) AS CLASEORDEN,
       CASE WHEN SUBSTR(PLAN_CONTABLE.CODIGO,1,1)='0'
             THEN 'z'||PLAN_CONTABLE.CODIGO
             ELSE PLAN_CONTABLE.CODIGO
             END AS ORDEN,
       (PLAN_CONTABLE.DEBITOs$mestrabajo$s*CENTRO_COSTOESP.PORCENTAJE)/100 AS DEBITO,
       (PLAN_CONTABLE.CREDITOs$mestrabajo$s*CENTRO_COSTOESP.PORCENTAJE)/100 AS CREDITO,
       (CASE WHEN PLAN_CONTABLE.NATURALEZA='D' AND PLAN_CONTABLE.SALDOs$mestrabajo-1$s >=0
              THEN PLAN_CONTABLE.SALDOs$mestrabajo-1$s
                 ELSE 0
                 END  + CASE WHEN PLAN_CONTABLE.NATURALEZA='C' AND PLAN_CONTABLE.SALDOs$mestrabajo-1$s <0
                             THEN -PLAN_CONTABLE.SALDOs$mestrabajo-1$s
                             ELSE 0
                             END) *CENTRO_COSTOESP.PORCENTAJE/100 AS SALDOANTDEBITO,
      ((CASE WHEN PLAN_CONTABLE.NATURALEZA='C' AND PLAN_CONTABLE.SALDOs$mestrabajo-1$s >=0
                  THEN PLAN_CONTABLE.SALDOs$mestrabajo-1$s
                  ELSE 0
                  END  + CASE WHEN PLAN_CONTABLE.NATURALEZA='D'  AND PLAN_CONTABLE.SALDOs$mestrabajo-1$s  <0
                             THEN -PLAN_CONTABLE.SALDOs$mestrabajo-1$s
                             ELSE 0
                             END)*CENTRO_COSTOESP.PORCENTAJE)/100 AS SALDOANTCREDITO,
       ((CASE WHEN PLAN_CONTABLE.NATURALEZA='D' AND PLAN_CONTABLE.SALDOs$mestrabajo-1$s >=0
              THEN PLAN_CONTABLE.SALDOs$mestrabajo-1$s
              ELSE 0
              END  + CASE WHEN PLAN_CONTABLE.NATURALEZA='C' AND PLAN_CONTABLE.SALDOs$mestrabajo-1$s <0
                          THEN -PLAN_CONTABLE.SALDOs$mestrabajo-1$s
                          ELSE 0
                          END)*CENTRO_COSTOESP.PORCENTAJE)/100 AS SALDONUEDEBITO, 
        ((CASE WHEN PLAN_CONTABLE.NATURALEZA='C' AND PLAN_CONTABLE.SALDOs$mestrabajo-1$s >=0
               THEN PLAN_CONTABLE.SALDOs$mestrabajo-1$s
               ELSE 0
               END  + CASE WHEN PLAN_CONTABLE.NATURALEZA='D' AND PLAN_CONTABLE.SALDOs$mestrabajo-1$s  <0
                           THEN -PLAN_CONTABLE.SALDOs$mestrabajo-1$s
                           ELSE 0
                           END)*CENTRO_COSTOESP.PORCENTAJE)/100 AS SALDONUECREDITO  
FROM V_PLAN_CONTABLE PLAN_CONTABLE
       LEFT JOIN CENTRO_COSTOESP
           ON  PLAN_CONTABLE.COMPANIA  = CENTRO_COSTOESP.COMPANIA
           AND PLAN_CONTABLE.ANO       = CENTRO_COSTOESP.ANO
           AND PLAN_CONTABLE.CCBALANCE = CENTRO_COSTOESP.CODIGO
              INNER JOIN CENTRO_COSTO CENTRO_COSTOCCBALANCE
                  ON  CENTRO_COSTOESP.COMPANIA       = CENTRO_COSTOCCBALANCE.COMPANIA
                  AND CENTRO_COSTOESP.ANO            = CENTRO_COSTOCCBALANCE.ANO
                  AND CENTRO_COSTOESP.CODIGO         = CENTRO_COSTOCCBALANCE.CODIGO
    INNER JOIN V_PLAN_CONTABLE PLAN_CONTABLENOM
      ON  PLAN_CONTABLE.COMPANIA           = PLAN_CONTABLENOM.COMPANIA
      AND PLAN_CONTABLE.ANO                = PLAN_CONTABLENOM.ANO
      AND SUBSTR(PLAN_CONTABLE.CODIGO,1,1) = PLAN_CONTABLENOM.CODIGO
    LEFT JOIN TERCERO 
        ON  PLAN_CONTABLE.COMPANIA = TERCERO.COMPANIA 
        AND PLAN_CONTABLE.TERCERO  = TERCERO.NIT 
        AND PLAN_CONTABLE.SUCURSAL = TERCERO.SUCURSAL 
    LEFT JOIN AUXILIAR 
        ON  PLAN_CONTABLE.COMPANIA = AUXILIAR.COMPANIA 
        AND PLAN_CONTABLE.ANO      = AUXILIAR.ANO   
        AND PLAN_CONTABLE.AUXILIAR = AUXILIAR.CODIGO 
    LEFT JOIN CENTRO_COSTO 
        ON  PLAN_CONTABLE.COMPANIA     = CENTRO_COSTO.COMPANIA    
        AND PLAN_CONTABLE.ANO          = CENTRO_COSTO.ANO     
        AND PLAN_CONTABLE.CENTRO_COSTO = CENTRO_COSTO.CODIGO 
WHERE PLAN_CONTABLE.ANO       =  s$anoTrabajo$s
  AND PLAN_CONTABLE.CCBALANCE IS NOT NULL 
  AND LENGTH(PLAN_CONTABLE.CODIGO) <= s$digitos$s 
  AND CENTRO_COSTOESP.MES           = s$mestrabajo$s
  AND PLAN_CONTABLE.MOVIMIENTO NOT IN (0)
  s$condAuxiliar$s
  s$condCentroCosto$s
  s$condTercero$s 
  s$condSaldoCero$s
ORDER BY 1,2,4
