MERGE INTO CONSULTAS FIN USING (SELECT '000640LISCOMPROBANTESTESORERIA' INFORME ,TO_CLOB(q'[SELECT  COMPROBANTE_CNT.COMPANIA,
        UPPER(TIPO_COMPROBANTE.NOMBRE)NOMBRE,
        COMPROBANTE_CNT.NUMERO,
        COMPROBANTE_CNT.FECHA,
        COMPROBANTE_CNT.DESCRIPCION,
        COMPROBANTE_CNT.NRO_DOCUMENTO,
        COMPROBANTE_CNT.VLR_DOCUMENTO,
        DETALLE_COMPROBANTE_CNT.CUENTA,
        V_PLAN_CONTABLE.NOMBRE NOMBRECUENTA,
        CASE WHEN DETALLE_COMPROBANTE_CNT.CENTRO_COSTO = 's$centroCosto$s' THEN ' ' ELSE DETALLE_COMPROBANTE_CNT.CENTRO_COSTO END  AS CODCENTROCOSTO,
        CASE WHEN DETALLE_COMPROBANTE_CNT.TERCERO      = 's$tercero$s' THEN ' ' ELSE DETALLE_COMPROBANTE_CNT.TERCERO      END  AS CODTERCERO,
        TERCERO.NOMBRE NOMBRETERCERO,
        CASE WHEN DETALLE_COMPROBANTE_CNT.AUXILIAR     = 's$auxiliar$s' THEN ' ' ELSE DETALLE_COMPROBANTE_CNT.AUXILIAR     END AS CODAUXILIAR, 
        DETALLE_COMPROBANTE_CNT.VALOR_DEBITO,
        DETALLE_COMPROBANTE_CNT.VALOR_CREDITO,
        DETALLE_COMPROBANTE_CNT.TIPO_CPTE TIPO
FROM DETALLE_COMPROBANTE_CNT
  INNER JOIN PLAN_CONTABLE V_PLAN_CONTABLE
    ON  DETALLE_COMPROBANTE_CNT.COMPANIA      = V_PLAN_CONTABLE.COMPANIA 
    AND DETALLE_COMPROBANTE_CNT.ANO           = V_PLAN_CONTABLE.ANO 
    AND DETALLE_COMPROBANTE_CNT.CUENTA        = V_PLAN_CONTABLE.CODIGO
  INNER JOIN COMPROBANTE_CNT 
    ON  DETALLE_COMPROBANTE_CNT.COMPANIA      = COMPROBANTE_CNT.COMPANIA
    AND DETALLE_COMPROBANTE_CNT.ANO           = COMPROBANTE_CNT.ANO 
    AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE     = COMPROBANTE_CNT.TIPO 
    AND DETALLE_COMPROBANTE_CNT.COMPROBANTE   = COMPROBANTE_CNT.NUMERO 
  INNER JOIN TIPO_COMPROBANTE 
    ON  DETALLE_COMPROBANTE_CNT.COMPANIA      = TIPO_COMPROBANTE.COMPANIA 
    AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE     = TIPO_COMPROBANTE.CODIGO 
  INNER JOIN TERCERO 
    ON  DETALLE_COMPROBANTE_CNT.COMPANIA      = TERCERO.COMPANIA
    AND DETALLE_COMPROBANTE_CNT.TERCERO       = TERCERO.NIT 
    AND DETALLE_COMPROBANTE_CNT.SUCURSAL      = TERCERO.SUCURSAL
WHERE DETALLE_COMPROBANTE_CNT.COMPANIA = s$compania$s  
  AND TIPO_COMPROBANTE.CLASE_CONTABLE IN ('I','E','S','B','D','A','J','L','G')
  AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE BETWEEN s$tipoInicial$s AND s$tipoFinal$s 
  AND DETALLE_COMPROBANTE_CNT.FECHA BETWEEN s$fechaInicial$s AND s$fechaFinal$s
  AND DETALLE_COMPROBANTE_CNT.TERCERO BETWEEN s$terceroInicial$s AND s$terceroFinal$s
ORDER BY  DETALLE_COMPROBANTE_CNT.COMPANIA,
         DETALLE_COMPROBANTE_CNT.ANO,
          DETALLE_COMPROBANTE_CNT.TIPO_CPTE, 
          DETALLE_COMPROBANTE_CNT.COMPROBANTE, 
          DETALLE_COMPROBANTE_CNT.CONSECUTIVO]') CONSULTA, 1 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);
