 SELECT V_PLAN_CONTABLE.COMPANIA, 
      -LPAD((CASE WHEN CLASECUENTA='0' THEN 'Z' ||PLAN_CONTABLE.CODIGO ELSE PLAN_CONTABLE.CODIGO END) ,1) AS CLASEORDEN,  
       V_PLAN_CONTABLE.TERCERO || TERCERO.DIGITOVERIFICACION AS NITCOMPLETO, 
       (CASE WHEN V_PLAN_CONTABLE.NATURALEZA='D' AND V_PLAN_CONTABLE.SALDO4 >=0 THEN V_PLAN_CONTABLE.SALDO4 ELSE 0 END)+ 
       (CASE WHEN V_PLAN_CONTABLE.NATURALEZA='C' AND V_PLAN_CONTABLE.SALDO4 <0 THEN -V_PLAN_CONTABLE.SALDO4 ELSE 0 END) SALDOANTDEBITO, 
       (CASE WHEN V_PLAN_CONTABLE.NATURALEZA='C' AND V_PLAN_CONTABLE.SALDO4 >=0 THEN V_PLAN_CONTABLE.SALDO4 ELSE 0 END)+ 
       (CASE WHEN V_PLAN_CONTABLE.NATURALEZA='D' AND V_PLAN_CONTABLE.SALDO4 <0 THEN -V_PLAN_CONTABLE.SALDO4 ELSE 0 END) SALDOANTCREDITO, 
       (CASE WHEN V_PLAN_CONTABLE.NATURALEZA='D' AND V_PLAN_CONTABLE.SALDO5 >=0 THEN V_PLAN_CONTABLE.SALDO5 ELSE 0 END)+ 
       (CASE WHEN V_PLAN_CONTABLE.NATURALEZA='C' AND V_PLAN_CONTABLE.SALDO5 <0 THEN -V_PLAN_CONTABLE.SALDO5 ELSE 0 END) SALDONUEDEBITO,  
       (CASE WHEN V_PLAN_CONTABLE.NATURALEZA='C' AND V_PLAN_CONTABLE.SALDO5 >=0 THEN V_PLAN_CONTABLE.SALDO5 ELSE 0 END)+ 
       (CASE WHEN V_PLAN_CONTABLE.NATURALEZA='D' AND V_PLAN_CONTABLE.SALDO5 <0 THEN -V_PLAN_CONTABLE.SALDO5 ELSE 0 END) SALDONUECREDITO, 
       DETALLE_COMPROBANTE_CNT.FECHA,  
       DETALLE_COMPROBANTE_CNT.COMPROBANTE,  
       DETALLE_COMPROBANTE_CNT.DESCRIPCION, 
       DETALLE_COMPROBANTE_CNT.VALOR_DEBITO, 
       DETALLE_COMPROBANTE_CNT.VALOR_CREDITO,  
       TIPO_COMPROBANTE.NOMBRE, 
       TERCERO.NOMBRE NOMTERCERO1,  
       DETALLE_COMPROBANTE_CNT.NRO_DOCUMENTO, 
       V_PLAN_CONTABLE.ID,  
       V_PLAN_CONTABLE.CODIGO, 
       (CASE WHEN CLASECUENTA='0' THEN 'Z' || PLAN_CONTABLE.CODIGO ELSE PLAN_CONTABLE.CODIGO END) AS ORDEN, 
       V_PLAN_CONTABLE.CODIGO || (CASE WHEN V_PLAN_CONTABLE.CENTRO_COSTO IS NULL THEN ' ' ELSE '' END) || 
       (CASE WHEN V_PLAN_CONTABLE.TERCERO IS NULL THEN ' ' ELSE '' END) || (CASE WHEN V_PLAN_CONTABLE.AUXILIAR IS NULL THEN ' ' ELSE '' END) || 
       PLAN_CONTABLE.NOMBRE ORDENCUENTAS, 
       DETALLE_COMPROBANTE_CNT.TIPO_CPTE,  
       PLAN_CONTABLE.NOMBRE PLAN_CONTABLE_NOMBRE,  
       V_PLAN_CONTABLE.CODIGO,  
       V_PLAN_CONTABLE.CENTRO_COSTO,  
       V_PLAN_CONTABLE.AUXILIAR,  
       TIPO_COMPROBANTE.NOMBRE NOMBRETIPOCON, 
       V_PLAN_CONTABLE.DEBITO5  DEBITO,  
       V_PLAN_CONTABLE.CREDITO5  CREDITO, 
       V_PLAN_CONTABLE.ANO        
FROM SALDO_AUX_CONTABLE V_PLAN_CONTABLE 
INNER JOIN PLAN_CONTABLE
  ON  V_PLAN_CONTABLE.COMPANIA = PLAN_CONTABLE.COMPANIA
  AND V_PLAN_CONTABLE.ANO = PLAN_CONTABLE.ANO
  AND V_PLAN_CONTABLE.CODIGO = PLAN_CONTABLE.CODIGO
INNER JOIN TERCERO  
ON V_PLAN_CONTABLE.COMPANIA = TERCERO.COMPANIA 
AND V_PLAN_CONTABLE.TERCERO = TERCERO.NIT 
AND V_PLAN_CONTABLE.SUCURSAL = TERCERO.SUCURSAL 
INNER JOIN DETALLE_COMPROBANTE_CNT 
ON V_PLAN_CONTABLE.ID = DETALLE_COMPROBANTE_CNT.ID
AND V_PLAN_CONTABLE.ANO = DETALLE_COMPROBANTE_CNT.ANO 
AND V_PLAN_CONTABLE.COMPANIA = DETALLE_COMPROBANTE_CNT.COMPANIA 
INNER JOIN TIPO_COMPROBANTE  
ON DETALLE_COMPROBANTE_CNT.COMPANIA = TIPO_COMPROBANTE.COMPANIA 
AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE = TIPO_COMPROBANTE.CODIGO 
WHERE V_PLAN_CONTABLE.COMPANIA = s$compania$s 

AND PLAN_CONTABLE.MAN_AUX_TER NOT IN (0)
AND V_PLAN_CONTABLE.ANO = s$anoTrabajo$s 
AND V_PLAN_CONTABLE.CODIGO BETWEEN  's$codigoInicial$s'  
AND  's$codigoFinal$s' 
AND EXTRACT (MONTH FROM DETALLE_COMPROBANTE_CNT.FECHA) = s$mesTrabajo$s 
AND DETALLE_COMPROBANTE_CNT.TERCERO BETWEEN 's$terceroInicial$s' AND 's$terceroFinal$s'  
AND (V_PLAN_CONTABLE.SALDOs$mesTrabajo$s  NOT IN (0)  
OR V_PLAN_CONTABLE.DEBITOs$mesTrabajo$s NOT IN (0)
OR V_PLAN_CONTABLE.CREDITOs$mesTrabajo$s NOT IN (0)
OR V_PLAN_CONTABLE.SALDOs$mesAnterior$s NOT IN (0)) 
ORDER BY V_PLAN_CONTABLE.COMPANIA, 
V_PLAN_CONTABLE.ANO, 
V_PLAN_CONTABLE.ID
