SELECT COMPROBANTE_CNT.FECHA, 
       TERCERO.NOMBRE, 
       COMPROBANTE_CNT.TEXTO || ' ' || COMPROBANTE_CNT.DESCRIPCION AS DETALLE, 
       COMPROBANTE_CNT.VLRAGIRAR, 
         (SELECT  LISTAGG(CUENTA,', ') WITHIN GROUP (ORDER BY CUENTA) RUBROS
            FROM DETALLE_COMPROBANTE_PPTAL
           WHERE COMPANIA   =  COMPROBANTE_CNT.COMPANIA
            AND ANO         = COMPROBANTE_CNT.ANO 
            AND TIPO_CPTE   = COMPROBANTE_CNT.TIPO
            AND COMPROBANTE =  COMPROBANTE_CNT.NUMERO) AS CODIGO, 
       COMPROBANTE_CNT.COMPANIA, 
       COMPROBANTE_CNT.ANO, 
       COMPROBANTE_CNT.TIPO, 
       COMPROBANTE_CNT.NUMERO
  FROM COMPROBANTE_CNT 
      LEFT JOIN TIPO_COMPROBANTE 
        ON COMPROBANTE_CNT.COMPANIA = TIPO_COMPROBANTE.COMPANIA 
       AND COMPROBANTE_CNT.TIPO     = TIPO_COMPROBANTE.CODIGO  
      LEFT JOIN TERCERO 
        ON COMPROBANTE_CNT.COMPANIA = TERCERO.COMPANIA 
       AND COMPROBANTE_CNT.TERCERO  = TERCERO.NIT
       AND COMPROBANTE_CNT.SUCURSAL = TERCERO.SUCURSAL
  WHERE COMPROBANTE_CNT.COMPANIA                  = s$compania$s 
  AND TIPO_COMPROBANTE.CLASE_CONTABLE             = 'E' 
  AND EXTRACT (MONTH FROM  COMPROBANTE_CNT.FECHA) = s$mes$s 
  AND EXTRACT (YEAR FROM  COMPROBANTE_CNT.FECHA)  = s$anio$s  
  ORDER BY COMPROBANTE_CNT.FECHA
