SELECT PLAN_CONTABLE.COMPANIA,  
       PLAN_CONTABLE.ANO,  
       PLAN_CONTABLE.CODIGO CODIGOCTA,  
       PLAN_CONTABLE.NOMBRE NOMBRECTA,  
       SUBSTR(PLAN_CONTABLE.CODIGO,1,1) CLASE, 
       SUBSTR(PLAN_CONTABLE.CODIGO,1,1)||PLAN_CONTABLE.NOMBRE ORDEN, 
       SUM(SALDO_AUX_CONTABLE.DEBITOs$mesTrabajo$s)   DEBITO,  
       SUM(SALDO_AUX_CONTABLE.CREDITOs$mesTrabajo$s)  CREDITO, 
       SUM(CASE WHEN PLAN_CONTABLE.NATURALEZA='D' AND PLAN_CONTABLE.SALDOs$mesTrabajo-1$s>=0  
            THEN PLAN_CONTABLE.SALDOs$mesTrabajo-1$s 
            ELSE 0 
            END+ 
       CASE WHEN PLAN_CONTABLE.NATURALEZA='C' AND PLAN_CONTABLE.SALDOs$mesTrabajo-1$s<0 
            THEN -PLAN_CONTABLE.SALDOs$mesTrabajo-1$s 
            ELSE 0  
            END) SALDOANTDEBITO, 
       SUM(CASE WHEN PLAN_CONTABLE.NATURALEZA='C' AND PLAN_CONTABLE.SALDOs$mesTrabajo-1$s>=0  
            THEN PLAN_CONTABLE.SALDOs$mesTrabajo-1$s 
            ELSE 0 
            END+ 
       CASE WHEN PLAN_CONTABLE.NATURALEZA='D' AND PLAN_CONTABLE.SALDOs$mesTrabajo-1$s<0 
            THEN -PLAN_CONTABLE.SALDOs$mesTrabajo-1$s 
            ELSE 0  
            END) SALDOANTCREDITO,  
       SUM(CASE WHEN PLAN_CONTABLE.NATURALEZA='D' AND PLAN_CONTABLE.SALDOs$mesTrabajo$s>=0  
            THEN PLAN_CONTABLE.SALDOs$mesTrabajo$s 
            ELSE 0 
            END+ 
       CASE WHEN PLAN_CONTABLE.NATURALEZA='C' AND PLAN_CONTABLE.SALDOs$mesTrabajo$s<0 
            THEN -PLAN_CONTABLE.SALDOs$mesTrabajo$s 
            ELSE 0  
            END) SALDONUEDEBITO,  
       SUM(CASE WHEN PLAN_CONTABLE.NATURALEZA='C' AND PLAN_CONTABLE.SALDOs$mesTrabajo$s>=0  
            THEN PLAN_CONTABLE.SALDOs$mesTrabajo$s 
            ELSE 0 
            END+ 
       CASE WHEN PLAN_CONTABLE.NATURALEZA='D' AND PLAN_CONTABLE.SALDOs$mesTrabajo$s<0 
            THEN -PLAN_CONTABLE.SALDOs$mesTrabajo$s 
            ELSE 0  
            END) SALDONUECREDITO       
FROM PLAN_CONTABLE INNER JOIN SALDO_AUX_CONTABLE 
    ON SALDO_AUX_CONTABLE.COMPANIA                                        = PLAN_CONTABLE.COMPANIA 
   AND SALDO_AUX_CONTABLE.ANO                                             = PLAN_CONTABLE.ANO 
   AND SUBSTR(SALDO_AUX_CONTABLE.CODIGO, 1, LENGTH(PLAN_CONTABLE.CODIGO)) = PLAN_CONTABLE.CODIGO 
WHERE PLAN_CONTABLE.COMPANIA = s$compania$s  
  AND PLAN_CONTABLE.ANO      = s$anio$s  
  AND PLAN_CONTABLE.CODIGO   BETWEEN 's$cuentaInicial$s'  AND 's$cuentaFinal$s'  
  AND SALDO_AUX_CONTABLE.CENTRO_COSTO BETWEEN 's$centroInicial$s' AND 's$centroFinal$s'  
  AND LENGTH(PLAN_CONTABLE.CODIGO)=1  
GROUP BY PLAN_CONTABLE.COMPANIA,  
         PLAN_CONTABLE.ANO,  
         PLAN_CONTABLE.CODIGO,  
         PLAN_CONTABLE.NOMBRE,  
         SUBSTR(PLAN_CONTABLE.CODIGO,1,1), 
         SUBSTR(PLAN_CONTABLE.CODIGO,1,1)||PLAN_CONTABLE.NOMBRE
