SELECT  V_DETALLE_AUXILIAR_CNT.TIPO_CPTE,
        V_DETALLE_AUXILIAR_CNT.TIPO_COMPROBANTE_NOM,
        V_DETALLE_AUXILIAR_CNT.COMPROBANTE,
        V_DETALLE_AUXILIAR_CNT.FECHA,
        V_DETALLE_AUXILIAR_CNT.CENTRO_COSTO_DET,
        V_DETALLE_AUXILIAR_CNT.CENTRO_COSTO_DET_NOM,
        V_DETALLE_AUXILIAR_CNT.TERCERO_DET,
        V_DETALLE_AUXILIAR_CNT.DESCRIPCION,
        V_DETALLE_AUXILIAR_CNT.CODIGO_CUENTA,
        (TRIM(V_DETALLE_AUXILIAR_CNT.CUENTANOMBRE) || 
        (CASE 
            WHEN V_DETALLE_AUXILIAR_CNT.CENTRO_COSTO_DET = PCK_DATOS.FC_CONS_CENTRO()
            THEN '' 
            ELSE (' / '||V_DETALLE_AUXILIAR_CNT.CENTRO_COSTO_DET_NOM) 
        END) || 
        (CASE 
            WHEN V_DETALLE_AUXILIAR_CNT.TERCERO_DET = PCK_DATOS.FC_CONS_TERCERO() 
            THEN '' 
            ELSE (' / '||V_DETALLE_AUXILIAR_CNT.TERCERO_DET_NOM) 
        END)|| 
        (CASE 
            WHEN V_DETALLE_AUXILIAR_CNT.AUXILIAR_DET = PCK_DATOS.FC_CONS_AUXILIAR()
            THEN '' 
            ELSE (' / '||V_DETALLE_AUXILIAR_CNT.AUXILIAR_DET_NOM) 
        END) || 
        (CASE 
            WHEN V_DETALLE_AUXILIAR_CNT.REFERENCIA_DET = PCK_DATOS.FC_CONS_REFERENCIA() 
            THEN '' 
            ELSE (' / '||V_DETALLE_AUXILIAR_CNT.REFERENCIA_DET_NOM) 
        END)) AS NOMBRECUENTA,
        V_DETALLE_AUXILIAR_CNT.VALOR_DEBITO,
        V_DETALLE_AUXILIAR_CNT.VALOR_CREDITO
FROM V_DETALLE_AUXILIAR_CNT
WHERE V_DETALLE_AUXILIAR_CNT.COMPANIA  = s$compania$s
    AND V_DETALLE_AUXILIAR_CNT.ANO     = s$ano$s 
    AND V_DETALLE_AUXILIAR_CNT.TIPO_CPTE    = 's$tipoCpte$s' 
    AND V_DETALLE_AUXILIAR_CNT.COMPROBANTE  BETWEEN 's$numeroPptoInicial$s' AND 's$numeroPptoFinal$s'
