SELECT DETALLE_COMPROBANTE_CNT.COMPANIA,
    DETALLE_COMPROBANTE_CNT.CUENTA CODIGO_CUENTA,
    DETALLE_COMPROBANTE_CNT.TIPO_CPTE, 
    DETALLE_COMPROBANTE_CNT.FECHA,
    TIPO_COMPROBANTE.NOMBRE  TIPO_COMPROBANTE_NOM,
    PLAN_CONTABLE.NOMBRE CUENTANOMBRE, 
    SUM(DETALLE_COMPROBANTE_CNT.VALOR_DEBITO)  SUMADEVALOR_DEBITO, 
    SUM(DETALLE_COMPROBANTE_CNT.VALOR_CREDITO) SUMADEVALOR_CREDITO  
FROM  DETALLE_COMPROBANTE_CNT 
 INNER JOIN TIPO_COMPROBANTE 
  ON  DETALLE_COMPROBANTE_CNT.COMPANIA  = TIPO_COMPROBANTE.COMPANIA  
  AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE = TIPO_COMPROBANTE.CODIGO  
 INNER JOIN PLAN_CONTABLE 
  ON  DETALLE_COMPROBANTE_CNT.COMPANIA = PLAN_CONTABLE.COMPANIA 
  AND DETALLE_COMPROBANTE_CNT.ANO      = PLAN_CONTABLE.ANO 
  AND DETALLE_COMPROBANTE_CNT.CUENTA   = PLAN_CONTABLE.CODIGO 
WHERE DETALLE_COMPROBANTE_CNT.COMPANIA = s$compania$s 
  AND DETALLE_COMPROBANTE_CNT.FECHA 	BETWEEN TO_DATE('s$fechaInicial$s') AND TO_DATE('s$fechaFinal$s')
  AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE BETWEEN 's$tipoInicial$s' 			AND 's$tipoFinal$s'
  AND DETALLE_COMPROBANTE_CNT.CUENTA 	BETWEEN 's$cuentaInicial$s' 		AND 's$cuentaFinal$s'
GROUP BY DETALLE_COMPROBANTE_CNT.COMPANIA,
    DETALLE_COMPROBANTE_CNT.CUENTA,
    DETALLE_COMPROBANTE_CNT.TIPO_CPTE, 
    DETALLE_COMPROBANTE_CNT.FECHA,
    TIPO_COMPROBANTE.NOMBRE,
    PLAN_CONTABLE.NOMBRE
