MERGE INTO CONSULTAS FIN USING (SELECT '000757FlujoCaja' INFORME ,TO_CLOB(q'[SELECT  PLAN_ANTERIOR.COMPANIA,  
        PLAN_ANTERIOR.CODIGO,  
        PLAN_ANTERIOR.NOMBRE,  
        PLAN_ANTERIOR.SALDOs$mesTrabajo$s  SALDO_ANTERIOR,  
        PLAN_NUEVO.SALDOs$mesComparar$s  SALDO_NUEVO,  
        PLAN_NUEVO.SALDOs$mesComparar$s - PLAN_ANTERIOR.SALDOs$mesTrabajo$s VARIACION, 
        SUBSTR(PLAN_ANTERIOR.CODIGO,1,1)  CLASE  
, 
        PLAN_ANTERIOR.COD_FLUJOCAJA, 
        CASE WHEN PLAN_ANTERIOR.COD_FLUJOCAJA = '1' THEN PLAN_NUEVO.SALDOs$mesComparar$s ELSE 0 END NUEVO1, 
        CASE WHEN PLAN_ANTERIOR.COD_FLUJOCAJA = '2' THEN PLAN_NUEVO.SALDOs$mesComparar$s ELSE 0 END NUEVO2, 
        CASE WHEN PLAN_ANTERIOR.COD_FLUJOCAJA = '3' THEN PLAN_NUEVO.SALDOs$mesComparar$s ELSE 0 END NUEVO3, 
        CASE WHEN PLAN_ANTERIOR.COD_FLUJOCAJA = '4' THEN PLAN_NUEVO.SALDOs$mesComparar$s ELSE 0 END NUEVO4, 
        CASE WHEN PLAN_ANTERIOR.COD_FLUJOCAJA = '5' THEN PLAN_NUEVO.SALDOs$mesComparar$s ELSE 0 END NUEVO5, 
        CASE WHEN PLAN_ANTERIOR.COD_FLUJOCAJA = '6' THEN PLAN_NUEVO.SALDOs$mesComparar$s ELSE 0 END NUEVO6, 
        CASE WHEN PLAN_ANTERIOR.COD_FLUJOCAJA = '1' THEN PLAN_ANTERIOR.SALDOs$mesTrabajo$s ELSE 0 END ANTERIOR1, 
        CASE WHEN PLAN_ANTERIOR.COD_FLUJOCAJA = '2' THEN PLAN_ANTERIOR.SALDOs$mesTrabajo$s ELSE 0 END ANTERIOR2, 
        CASE WHEN PLAN_ANTERIOR.COD_FLUJOCAJA = '3' THEN PLAN_ANTERIOR.SALDOs$mesTrabajo$s ELSE 0 END ANTERIOR3, 
        CASE WHEN PLAN_ANTERIOR.COD_FLUJOCAJA = '4' THEN PLAN_ANTERIOR.SALDOs$mesTrabajo$s ELSE 0 END ANTERIOR4, 
        CASE WHEN PLAN_ANTERIOR.COD_FLUJOCAJA = '5' THEN PLAN_ANTERIOR.SALDOs$mesTrabajo$s ELSE 0 END ANTERIOR5, 
        CASE WHEN PLAN_ANTERIOR.COD_FLUJOCAJA = '6' THEN PLAN_ANTERIOR.SALDOs$mesTrabajo$s ELSE 0 END ANTERIOR6, 
        CASE WHEN PLAN_ANTERIOR.COD_FLUJOCAJA = '1' THEN 'INGRESOS DE ACTIVIDADES DE OPERACIÓN' ELSE  
          CASE WHEN PLAN_ANTERIOR.COD_FLUJOCAJA = '2' THEN 'GASTOS DE ACTIVIDADES OPERACION' ELSE  
            CASE WHEN PLAN_ANTERIOR.COD_FLUJOCAJA = '3' THEN 'INGRESOS DE ACTIVIDADES DE INVERSION' ELSE      
              CASE WHEN PLAN_ANTERIOR.COD_FLUJOCAJA = '4' THEN 'GASTOS DE ACTIVIDADES DE INVERSION' ELSE      
                CASE WHEN PLAN_ANTERIOR.COD_FLUJOCAJA = '5' THEN 'INGRESOS DE ACTIVIDADES DE FINANCIACION' ELSE  
                  CASE WHEN PLAN_ANTERIOR.COD_FLUJOCAJA = '6' THEN 'INGRESOS DE ACTIVIDADES DE FINANCIACION'  END END END END END END NOMBRECLASE,  
        CASE WHEN PLAN_ANTERIOR.COD_FLUJOCAJA = '1' THEN 'EFECTIVO ORIGINADO EN LAS ACTIVIDADES DE OPERACIÓN' ELSE  
          CASE WHEN PLAN_ANTERIOR.COD_FLUJOCAJA = '2' THEN 'EFECTIVO APLICADO EN LAS ACTIVIDADES DE OPERACIÓN' ELSE  
            CASE WHEN PLAN_ANTERIOR.COD_FLUJOCAJA = '3' THEN 'EFECTIVO ORIGINADO EN LAS ACTIVIDADES DE INVERSION' ELSE      
              CASE WHEN PLAN_ANTERIOR.COD_FLUJOCAJA = '4' THEN 'EFECTIVO APLICADO EN LAS ACTIVIDADES DE INVERSION' ELSE      
                CASE WHEN PLAN_ANTERIOR.COD_FLUJOCAJA = '5' THE]') || TO_CLOB(q'[N 'EFECTIVO ORIGINADO EN LAS ACTIVIDADES DE OPERACIÓN' ELSE  
                  CASE WHEN PLAN_ANTERIOR.COD_FLUJOCAJA = '6' THEN 'EFECTIVO APLICADO EN LAS ACTIVIDADES DE FINANCIACION' END END END END END END NOMBRESUMATORIA           
FROM V_PLAN_CONTABLE PLAN_ANTERIOR  
  LEFT JOIN V_PLAN_CONTABLE  PLAN_NUEVO 
  ON PLAN_ANTERIOR.COMPANIA = PLAN_NUEVO.COMPANIA   
  AND PLAN_ANTERIOR.ID = PLAN_NUEVO.ID 
WHERE PLAN_ANTERIOR.COMPANIA='s$compania$s' 
AND PLAN_ANTERIOR.ANO=s$anoTrabajo$s 
AND LENGTH(PLAN_ANTERIOR.CODIGO)<=  s$digitos$s  
AND PLAN_ANTERIOR.CODIGO BETWEEN 's$codigoInicial$s' AND 's$codigoFinal$s' 
AND PLAN_NUEVO.ANO=s$anoComparar$s 
AND (TRUNC(PLAN_ANTERIOR.SALDOs$mesTrabajo$s*100+0.501)<>0 OR TRUNC(PLAN_NUEVO.SALDOs$mesComparar$s*100+0.501)<>0) 
AND (PLAN_ANTERIOR.MOVIMIENTO_PADRE + PLAN_ANTERIOR.MAN_CEN_CTO_PADRE + PLAN_ANTERIOR.MAN_AUX_TER_PADRE + PLAN_ANTERIOR.MAN_AUX_REF_PADRE + PLAN_ANTERIOR.MAN_AUX_GEN_PADRE + PLAN_ANTERIOR.MAN_AUX_FUE_PADRE ) = 0
AND (PLAN_NUEVO.MOVIMIENTO_PADRE + PLAN_NUEVO.MAN_CEN_CTO_PADRE + PLAN_NUEVO.MAN_AUX_TER_PADRE + PLAN_NUEVO.MAN_AUX_REF_PADRE + PLAN_ANTERIOR.MAN_AUX_GEN_PADRE + PLAN_NUEVO.MAN_AUX_FUE_PADRE ) = 0]') CONSULTA, 1 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);