SELECT  
    COMPANIA,
    CASE VALOR_DEBITO WHEN 0 THEN 1 ELSE 0 END AS CAMPO1,
    TIPO_CPTE AS TIPO,
    CUENTANOMBRE PLAN_CONTABLE_NOMBRE,
    TERCERO_NOM NOMBRETERCERO,
    COMPROBANTE NUMERO,
    FECHA,
    DESCRIPCION,
    NRO_DOCUMENTO,
    VLR_DOCUMENTO,
    VALOR_DEBITO,
    TIPO_COMPROBANTE_NOM TIPO_COMPROBANTE_NOMBRE,
    CODIGO_CUENTA,
    VALOR_CREDITO,
    TERCERO CODTERCERO,      
    CENTRO_COSTO CodCentroCosto,
    CENTRO_COSTO_NOM CENTRO_COSTO_NOMBRE, 
    AUXILIAR_NOM Auxiliar_NOMBRE,
    CENTRO_COSTO_NOM NOMBRECENTROCOSTO,
    CASE WHEN VALOR_DEBITO NOT IN (0)
         THEN 0
         ELSE 1
         END CAMPO1,
    CODIGO_CUENTA||CASE WHEN CENTRO_COSTO_DET IS NULL
                        THEN ''
                        ELSE CENTRO_COSTO_NOM
                        END
                 ||CASE WHEN TERCERO_DET IS NULL
                        THEN ''
                        ELSE TERCERO_NOM
                        END 
                 ||CASE WHEN AUXILIAR_DET IS NULL
                        THEN ''
                        ELSE AUXILIAR_NOM
                        END 
                  ||CUENTANOMBRE AS IDORDEN  
FROM  V_DETALLE_AUXILIAR_CNT 
   INNER JOIN COMPANIA  
     ON V_DETALLE_AUXILIAR_CNT.COMPANIA = COMPANIA.CODIGO 
WHERE 
V_DETALLE_AUXILIAR_CNT.COMPANIA = s$compania$s   
  AND V_DETALLE_AUXILIAR_CNT.FECHA BETWEEN s$fechaInicial$s AND s$fechaFinal$s
  AND V_DETALLE_AUXILIAR_CNT.TIPO_CPTE BETWEEN s$tipoInicial$s AND s$tipoFinal$s
  AND V_DETALLE_AUXILIAR_CNT.TERCERO BETWEEN s$terceroInicial$s AND s$terceroFinal$s
  ORDER BY V_DETALLE_AUXILIAR_CNT.COMPANIA,
 V_DETALLE_AUXILIAR_CNT.ANO,
  V_DETALLE_AUXILIAR_CNT.TIPO_CPTE,
   V_DETALLE_AUXILIAR_CNT.COMPROBANTE, 
   V_DETALLE_AUXILIAR_CNT.CONSECUTIVO
