
      SELECT
COMPANIA,
 CODIGO, 
        PLAN_CONTABLE_NOMBRE,  
        (SALDOANT)SALDOANT,  
        (NETO) NETO,  
        (SALDO) SALDO  
        FROM (
SELECT BASE_BALANCE.COMPANIA, 
       s$mesTrabajo$s AS MES,  
       BASE_BALANCE.CODIGO ID, 
      BASE_BALANCE.ANO, 
    SUBSTR(  BASE_BALANCE.CODIGO,0,1) CODIGO, 
       PLAN_CONTABLE.NOMBRE AS PLAN_CONTABLE_NOMBRE,  
       BASE_BALANCE.SALDOs$mesTrabajo1$s AS SALDOANT,  
       BASE_BALANCE.NETOs$mesTrabajo$s AS NETO,  
       BASE_BALANCE.SALDOs$mesTrabajo$s AS SALDO, 
       BASE_BALANCE.NATURALEZA, 
       LPAD(ORDEN,1) AS CLASEORDEN, 
       (CASE WHEN BASE_BALANCE.NATURALEZA='C' THEN BASE_BALANCE.SALDOs$mesTrabajo1$s ELSE (BASE_BALANCE.SALDOs$mesTrabajo1$s*-1) END) SALDOANT1, 
       (CASE WHEN BASE_BALANCE.NATURALEZA='C' THEN BASE_BALANCE.NETOs$mesTrabajo$s ELSE (BASE_BALANCE.NETOs$mesTrabajo$s*-1) END) NETO1, 
       (CASE WHEN BASE_BALANCE.NATURALEZA='C' THEN BASE_BALANCE.SALDOs$mesTrabajo$s ELSE (BASE_BALANCE.SALDOs$mesTrabajo$s*-1) END) SALDO1 
 FROM (s$baseBalance$s) BASE_BALANCE
INNER JOIN PLAN_CONTABLE 
ON BASE_BALANCE.COMPANIA=PLAN_CONTABLE.COMPANIA
AND BASE_BALANCE.ANO=PLAN_CONTABLE.ANO
AND SUBSTR(BASE_BALANCE.CODIGO,0,1)=PLAN_CONTABLE.CODIGO 
WHERE BASE_BALANCE.SALDOs$mesTrabajo$s NOT IN (0) 

AND LENGTH(BASE_BALANCE.CODIGO)<=1 


 ORDER BY BASE_BALANCE.COMPANIA, BASE_BALANCE.ANO, BASE_BALANCE.CODIGO)
