SELECT TIPOCUENTA 
, 
    ID, 
    NOMBRE 
, 
    SALDOINICIAL, 
    CONSIGNACION, 
    NOTACREDITO, 
    CHEQUEANULADO, 
    GIRO, 
    NOTADEBITO, 
    INGRESOCAJA1,     
    RECIBODECAJAANULADO, 
    EGRESOCAJA, 
    INGRESOCAJA, 
    (SALDOINICIAL + CONSIGNACION + NOTACREDITO + CHEQUEANULADO - GIRO - NOTADEBITO + INGRESOCAJA - EGRESOCAJA) AS SALDOFINAL 
FROM 
    (SELECT (CASE WHEN CLASECUENTA = 'J' THEN 'CAJAS' ELSE 'BANCOS' END) AS TIPOCUENTA,   
        ID, 
        CUENTANOMBRE AS NOMBRE, 
        SALDO_ANT AS SALDOINICIAL, 
        SUM((CASE WHEN CLASE_CONTABLE = 'S' AND CLASECUENTA = 'B' THEN DEBITO-CREDITO ELSE 0 END)) AS CONSIGNACION, 
        SUM((CASE WHEN CLASE_CONTABLE = 'B' THEN DEBITO-CREDITO ELSE 0 END)) AS NOTACREDITO, 
        SUM((CASE WHEN CLASE_CONTABLE = 'A' OR CLASE_CONTABLE = 'D' THEN DEBITO-CREDITO ELSE 0 END)) AS CHEQUEANULADO, 
        SUM((CASE WHEN CLASE_CONTABLE = 'E' AND CLASECUENTA = 'B' THEN CREDITO-DEBITO ELSE 0 END)) AS GIRO, 
        SUM((CASE WHEN CLASE_CONTABLE = 'G' AND CLASECUENTA NOT IN('J') THEN CREDITO-DEBITO ELSE 0 END)) AS NOTADEBITO, 
        SUM((CASE WHEN CLASE_CONTABLE = 'I' AND CLASECUENTA IN('B', 'J') THEN DEBITO ELSE 0 END)) AS INGRESOCAJA1,     
        SUM((CASE WHEN CLASE_CONTABLE = 'J' AND CLASECUENTA = 'J' THEN CREDITO ELSE 0 END)) AS RECIBODECAJAANULADO, 
        SUM((CASE WHEN CLASE_CONTABLE = 'J' AND CLASECUENTA <> 'J' THEN CREDITO ELSE 0 END)) AS EGRESOCAJA, 
        SUM((CASE WHEN CLASE_CONTABLE = 'I' AND CLASECUENTA IN('B', 'J') THEN DEBITO ELSE 0 END)) -  
        SUM((CASE WHEN CLASE_CONTABLE = 'J' AND CLASECUENTA = 'J' THEN CREDITO ELSE 0 END)) AS INGRESOCAJA 
    FROM (SELECT 
      COMPANIA, 
      ANO, 
      CODIGO_CUENTA ID, 
      SALDO_ANT, 
      CUENTANOMBRE, 
      SUM(VALOR_DEBITO)  AS DEBITO, 
      SUM(VALOR_CREDITO) AS CREDITO, 
      CLASECUENTA, 
      CLASE_CONTABLE 
    FROM(s$baseAux$s  
              AND SIN_DET.FECHA = TO_DATE('s$fecha$s','DD/MM/YYYY') 

        AND CLASECUENTA IN ('B','J') 
    )  
    GROUP BY COMPANIA, ANO, CODIGO_CUENTA, CUENTANOMBRE,  
     CLASECUENTA, CLASE_CONTABLE,SALDO_ANT) 
    GROUP BY (CASE WHEN CLASECUENTA = 'J' THEN 'CAJAS' ELSE 'BANCOS' END),   
        ID, 
        CUENTANOMBRE, 
        SALDO_ANT) 
WHERE (SALDOINICIAL + CONSIGNACION + NOTACREDITO + CHEQUEANULADO - GIRO - NOTADEBITO + INGRESOCAJA - EGRESOCAJA) <> 0
