MERGE INTO CONSULTAS FIN USING (SELECT '000808RelacionDeIngresosEsp' INFORME ,TO_CLOB(q'[SELECT DETALLE_COMPROBANTE_PPTAL.COMPANIA, 
       COMPROBANTE_PPTAL.FECHA,  
       TO_CHAR(COMPROBANTE_PPTAL.FECHA,'YYYYMMDD') FECHACOMPARAR,  
       TIPO_COMPROBPP.CLASE,   
       DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE||'-'||DETALLE_COMPROBANTE_PPTAL.COMPROBANTE COMPROBANTE,   
       DETALLE_COMPROBANTE_PPTAL.CUENTA,  
       TERCERO.NOMBRE,  
       (DETALLE_COMPROBANTE_PPTAL.VALOR_CREDITO-DETALLE_COMPROBANTE_PPTAL.VALOR_DEBITO)  VALORINGRESO,  
       COMPROBANTE_PPTAL.DESCRIPCION  
FROM DETALLE_COMPROBANTE_PPTAL  
  INNER JOIN TIPO_COMPROBPP  
    ON  DETALLE_COMPROBANTE_PPTAL.COMPANIA  = TIPO_COMPROBPP.COMPANIA  
    AND DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE = TIPO_COMPROBPP.CODIGO  
  INNER JOIN TERCERO   
    ON  DETALLE_COMPROBANTE_PPTAL.COMPANIA = TERCERO.COMPANIA 
    AND DETALLE_COMPROBANTE_PPTAL.TERCERO  = TERCERO.NIT    
    AND DETALLE_COMPROBANTE_PPTAL.SUCURSAL = TERCERO.SUCURSAL  
  INNER JOIN COMPROBANTE_PPTAL   
    ON  DETALLE_COMPROBANTE_PPTAL.COMPANIA = COMPROBANTE_PPTAL.COMPANIA 
    AND DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE = COMPROBANTE_PPTAL.TIPO 
    AND DETALLE_COMPROBANTE_PPTAL.ANO = COMPROBANTE_PPTAL.ANO  
    AND DETALLE_COMPROBANTE_PPTAL.COMPROBANTE = COMPROBANTE_PPTAL.NUMERO   
WHERE DETALLE_COMPROBANTE_PPTAL.COMPANIA = s$compania$s   
  AND COMPROBANTE_PPTAL.FECHA BETWEEN TO_DATE('s$fechaInicial$s','DD/MM/YYYY')  
AND TO_DATE('s$fechaFinal$s','DD/MM/YYYY')   
  AND TIPO_COMPROBPP.CLASE IN ('ING','DIN')   
  AND DETALLE_COMPROBANTE_PPTAL.CUENTA BETWEEN 's$cuentaInicial$s'  
AND 's$cuentaFinal$s']') CONSULTA, 1 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);