SELECT BASE.COMPANIA, 
       BASE.ANO, 
       BASE.CODIGO_CUENTA  CODIGO, 
       BASE.CUENTANOMBRE   NOMBRE, 
       AVG(BASE.SALDO) PROMEDIODESALDOINICIAL   
FROM (          
  s$baseAuxiliar$s              
	) BASE
WHERE BASE.COMPANIA     = s$compania$s
  AND BASE.CLASECUENTA IN ('B') 
GROUP BY BASE.COMPANIA, 
         BASE.ANO, 
         BASE.CODIGO_CUENTA, 
         BASE.CUENTANOMBRE
