MERGE INTO CONSULTAS FIN USING (SELECT '000800RelacionDeEgresosEspecial' INFORME ,TO_CLOB(q'[SELECT LISRELACIONDEEGRESOSESPTOT.COMPANIA, 
       LISRELACIONDEEGRESOSESPTOT.ANO, 
       LISRELACIONDEEGRESOSESPTOT.TIPO_CPTE, 
       LISRELACIONDEEGRESOSESPTOT.COMPROBANTE, 
       LISRELACIONDEEGRESOSESPTOT.FECHA, 
       LISRELACIONDEEGRESOSESPTOT.CUENTA CODIGO_CUENTA, 
       LISRELACIONDEEGRESOSESPTOT.NOMBRE, 
       LISRELACIONDEEGRESOSESPTOT.TERCERO, 
       LISRELACIONDEEGRESOSESPTOT.SUCURSAL,
       TERCERO.NOMBRE TERCERO_NOM,
       LISRELACIONDEEGRESOSESPTOT.DESCRIPCION, 
       LISRELACIONDEEGRESOSESPTOT.VALOR_CREDITO VALORCREDITO, 
       LISRELACIONDEEGRESOSESPTOT.VLR_DOCUMENTO VALORDOC, 
       LISRELACIONDEEGRESOSESPTOT.NRO_DOCUMENTO, 
       SUM(LISRELACIONDEEGRESOSESPTOT.RETEFUENTE) RETEFUENTE, 
       SUM(LISRELACIONDEEGRESOSESPTOT.RETEIVA)    RETEIVA, 
       SUM(LISRELACIONDEEGRESOSESPTOT.OTROS)      OTROS, 
       SUM(CASE WHEN PLAN_CONTABLE.CLASECUENTA='I'
                THEN LISRELACIONDEEGRESOSESPTOT.OTROS
                ELSE 0
                END) AS OTROSFINAL,
       (SELECT LISTAGG(CUENTA,', ') WITHIN GROUP(ORDER BY CUENTA) RUBRO
         FROM DETALLE_COMPROBANTE_PPTAL 
         WHERE DETALLE_COMPROBANTE_PPTAL.COMPANIA    = LISRELACIONDEEGRESOSESPTOT.COMPANIA 
           AND DETALLE_COMPROBANTE_PPTAL.ANO         = LISRELACIONDEEGRESOSESPTOT.ANO 
           AND DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE   = LISRELACIONDEEGRESOSESPTOT.TIPO_CPTE 
           AND DETALLE_COMPROBANTE_PPTAL.COMPROBANTE = LISRELACIONDEEGRESOSESPTOT.COMPROBANTE ) AS RUBROS   
FROM(
SELECT LISRELACIONDEEGRESOSESPEGR.COMPANIA, 
       LISRELACIONDEEGRESOSESPEGR.ANO, 
       LISRELACIONDEEGRESOSESPEGR.TIPO_CPTE, 
       LISRELACIONDEEGRESOSESPEGR.COMPROBANTE, 
       LISRELACIONDEEGRESOSESPEGR.FECHA, 
       LISRELACIONDEEGRESOSESPEGR.NOMBRE, 
       LISRELACIONDEEGRESOSESPEGR.TERCERO, 
       LISRELACIONDEEGRESOSESPEGR.CUENTA,
       LISRELACIONDEEGRESOSESPEGR.SUCURSAL, 
       LISRELACIONDEEGRESOSESPEGR.DESCRIPCION, 
       LISRELACIONDEEGRESOSESPEGR.VALOR_CREDITO, 
       LISRELACIONDEEGRESOSESPEGR.VLR_DOCUMENTO, 
       LISRELACIONDEEGRESOSESPEGR.NRO_DOCUMENTO, 
       DETALLE_COMPROBANTE_CNT.CUENTA AS CTAIMP,   
       0 AS RETEFUENTE, 
       0 AS RETEIVA, 
       0 AS Otros 
FROM
(
SELECT LISRELACIONDEEGRESOSESPEGRT.* 
FROM (
WITH LISRELACIONDEEGRESOSESP AS (
      SELECT DETALLE_COMPROBANTE_CNT.COMPANIA, 
             DETALLE_COMPROBANTE_CNT.ANO, 
             DETALLE_COMPROBANTE_CNT.TIPO_CPTE, 
             DETALLE_COMPROBANTE_CNT.COMPROBANTE, 
             COMPROBANTE_CNT.FECHA, 
             DETALLE_COMPROBANTE_CNT.TIPO_CPTE_AFECT, 
             DETALLE_COMPROBANTE_CNT.CMPTE_AFECTADO, 
             DETALLE_COMPROBANTE_CNT.CUENTA, 
             PLAN_CONTABLE.NOMBRE, 
             COMPROBANTE_CNT.DESCRIPCION, 
             COMPROBANTE_CNT.TERCERO, 
             COMPROBANTE_CNT.SUCURSAL, 
             COMPROBANTE_CNT.NRO_DOCUMENTO, 
             COMPROBANTE_CNT.VLR_DOCUMENTO, 
             COMPROBANTE_CNT.VLRAGIRAR, 
             SUM(DETALLE_COMPROBA]') || TO_CLOB(q'[NTE_CNT.VALOR_CREDITO) VALOR_CREDITO 
     FROM DETALLE_COMPROBANTE_CNT 
      INNER JOIN PLAN_CONTABLE 
    	ON  DETALLE_COMPROBANTE_CNT.COMPANIA = PLAN_CONTABLE.COMPANIA 
    	AND DETALLE_COMPROBANTE_CNT.ANO      = PLAN_CONTABLE.ANO 
    	AND DETALLE_COMPROBANTE_CNT.CUENTA   = PLAN_CONTABLE.CODIGO 
      INNER JOIN TIPO_COMPROBANTE 
        ON  DETALLE_COMPROBANTE_CNT.COMPANIA  = TIPO_COMPROBANTE.COMPANIA 
        AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE = TIPO_COMPROBANTE.CODIGO 
      INNER JOIN COMPROBANTE_CNT 
        ON  DETALLE_COMPROBANTE_CNT.COMPANIA    = COMPROBANTE_CNT.COMPANIA 
        AND DETALLE_COMPROBANTE_CNT.ANO         = COMPROBANTE_CNT.ANO 
        AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE   = COMPROBANTE_CNT.TIPO 
        AND DETALLE_COMPROBANTE_CNT.COMPROBANTE = COMPROBANTE_CNT.NUMERO 
    WHERE DETALLE_COMPROBANTE_CNT.COMPANIA = s$compania$s
      AND DETALLE_COMPROBANTE_CNT.FECHA BETWEEN TO_DATE('s$fechaInicial$s','DD/MM/YYYY') 
                                            AND TO_DATE('s$fechaFinal$s','DD/MM/YYYY') 
      AND TIPO_COMPROBANTE.CLASE_CONTABLE IN('E') 
      AND DETALLE_COMPROBANTE_CNT.VALOR_CREDITO > 0 
    GROUP BY DETALLE_COMPROBANTE_CNT.COMPANIA, 
             DETALLE_COMPROBANTE_CNT.ANO, 
             DETALLE_COMPROBANTE_CNT.TIPO_CPTE, 
             DETALLE_COMPROBANTE_CNT.COMPROBANTE, 
             COMPROBANTE_CNT.FECHA, 
             DETALLE_COMPROBANTE_CNT.TIPO_CPTE_AFECT, 
             DETALLE_COMPROBANTE_CNT.CMPTE_AFECTADO, 
             DETALLE_COMPROBANTE_CNT.CUENTA, 
             PLAN_CONTABLE.NOMBRE, 
             COMPROBANTE_CNT.DESCRIPCION, 
             COMPROBANTE_CNT.TERCERO, 
             COMPROBANTE_CNT.SUCURSAL, 
             COMPROBANTE_CNT.VLR_DOCUMENTO, 
             COMPROBANTE_CNT.VLRAGIRAR, 
             COMPROBANTE_CNT.NRO_DOCUMENTO)
    SELECT LISRELACIONDEEGRESOSESP.COMPANIA, 
           LISRELACIONDEEGRESOSESP.ANO, 
           LISRELACIONDEEGRESOSESP.TIPO_CPTE, 
           LISRELACIONDEEGRESOSESP.TIPO_CPTE_AFECT,
           LISRELACIONDEEGRESOSESP.CMPTE_AFECTADO,
           LISRELACIONDEEGRESOSESP.COMPROBANTE, 
           LISRELACIONDEEGRESOSESP.FECHA, 
           LISRELACIONDEEGRESOSESP.CUENTA, 
           LISRELACIONDEEGRESOSESP.NOMBRE, 
           LISRELACIONDEEGRESOSESP.TERCERO, 
           LISRELACIONDEEGRESOSESP.SUCURSAL, 
           LISRELACIONDEEGRESOSESP.DESCRIPCION, 
           LISRELACIONDEEGRESOSESP.VALOR_CREDITO, 
           LISRELACIONDEEGRESOSESP.VLR_DOCUMENTO, 
           LISRELACIONDEEGRESOSESP.VLRAGIRAR,
           LISRELACIONDEEGRESOSESP.NRO_DOCUMENTO  
    FROM LISRELACIONDEEGRESOSESP 
      INNER JOIN DETALLE_COMPROBANTE_CNT 
        ON  LISRELACIONDEEGRESOSESP.COMPANIA    = DETALLE_COMPROBANTE_CNT.COMPANIA 
        AND LISRELACIONDEEGRESOSESP.ANO         = DETALLE_COMPROBANTE_CNT.ANO 
        AND LISRELACIONDEEGRESOSESP.TIPO_CPTE   = DETALLE_COMPROBANTE_CNT.TIPO_CPTE 
        AND LISRELACIONDEEGRESOSESP.COMPROBANTE = DETALLE_COMPROBANTE_CNT.COMPROBANTE 
    WHERE ]') || TO_CLOB(q'[NVL(DETALLE_COMPROBANTE_CNT.CMPTE_AFECTADO,0) IN(0) 
    GROUP BY LISRELACIONDEEGRESOSESP.COMPANIA, 
             LISRELACIONDEEGRESOSESP.ANO, 
             LISRELACIONDEEGRESOSESP.TIPO_CPTE, 
             LISRELACIONDEEGRESOSESP.COMPROBANTE, 
             LISRELACIONDEEGRESOSESP.TIPO_CPTE_AFECT,
             LISRELACIONDEEGRESOSESP.CMPTE_AFECTADO,
             LISRELACIONDEEGRESOSESP.FECHA, 
             LISRELACIONDEEGRESOSESP.CUENTA, 
             LISRELACIONDEEGRESOSESP.NOMBRE, 
             LISRELACIONDEEGRESOSESP.TERCERO, 
             LISRELACIONDEEGRESOSESP.SUCURSAL, 
             LISRELACIONDEEGRESOSESP.DESCRIPCION, 
             LISRELACIONDEEGRESOSESP.VALOR_CREDITO, 
             LISRELACIONDEEGRESOSESP.VLR_DOCUMENTO, 
             LISRELACIONDEEGRESOSESP.VLRAGIRAR, 
             LISRELACIONDEEGRESOSESP.NRO_DOCUMENTO) LISRELACIONDEEGRESOSESPEGRT
LEFT JOIN
(
SELECT LISRELACIONDEEGRESOSESP.COMPANIA, 
       LISRELACIONDEEGRESOSESP.ANO, 
       LISRELACIONDEEGRESOSESP.TIPO_CPTE, 
       LISRELACIONDEEGRESOSESP.COMPROBANTE, 
       LISRELACIONDEEGRESOSESP.FECHA, 
       LISRELACIONDEEGRESOSESP.CUENTA, 
       LISRELACIONDEEGRESOSESP.NOMBRE, 
       LISRELACIONDEEGRESOSESP.TERCERO, 
       LISRELACIONDEEGRESOSESP.SUCURSAL, 
       LISRELACIONDEEGRESOSESP.DESCRIPCION, 
       LISRELACIONDEEGRESOSESP.VALOR_CREDITO, 
       LISRELACIONDEEGRESOSESP.VLR_DOCUMENTO, 
       LISRELACIONDEEGRESOSESP.VLRAGIRAR, 
       LISRELACIONDEEGRESOSESP.NRO_DOCUMENTO, 
       DETALLE_COMPROBANTE_CNT.TIPO_CPTE_AFECT, 
       DETALLE_COMPROBANTE_CNT.CMPTE_AFECTADO 
FROM (
      SELECT DETALLE_COMPROBANTE_CNT.COMPANIA, 
             DETALLE_COMPROBANTE_CNT.ANO, 
             DETALLE_COMPROBANTE_CNT.TIPO_CPTE, 
             DETALLE_COMPROBANTE_CNT.COMPROBANTE, 
             COMPROBANTE_CNT.FECHA, 
             DETALLE_COMPROBANTE_CNT.TIPO_CPTE_AFECT, 
             DETALLE_COMPROBANTE_CNT.CMPTE_AFECTADO, 
             DETALLE_COMPROBANTE_CNT.CUENTA, 
             PLAN_CONTABLE.NOMBRE, 
             COMPROBANTE_CNT.DESCRIPCION, 
             COMPROBANTE_CNT.TERCERO, 
             COMPROBANTE_CNT.SUCURSAL, 
             COMPROBANTE_CNT.NRO_DOCUMENTO, 
             COMPROBANTE_CNT.VLR_DOCUMENTO, 
             COMPROBANTE_CNT.VLRAGIRAR, 
             SUM(DETALLE_COMPROBANTE_CNT.VALOR_CREDITO) VALOR_CREDITO 
     FROM DETALLE_COMPROBANTE_CNT 
      INNER JOIN PLAN_CONTABLE 
    	  ON  DETALLE_COMPROBANTE_CNT.COMPANIA = PLAN_CONTABLE.COMPANIA 
    	  AND DETALLE_COMPROBANTE_CNT.ANO      = PLAN_CONTABLE.ANO 
    	  AND DETALLE_COMPROBANTE_CNT.CUENTA   = PLAN_CONTABLE.CODIGO 
      INNER JOIN TIPO_COMPROBANTE 
        ON  DETALLE_COMPROBANTE_CNT.COMPANIA  = TIPO_COMPROBANTE.COMPANIA 
        AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE = TIPO_COMPROBANTE.CODIGO 
      INNER JOIN COMPROBANTE_CNT 
        ON  DETALLE_COMPROBANTE_CNT.COMPANIA    = COMPROBANTE_CNT.COMPANIA 
        AND DETALLE_COMPROBANTE_CNT.ANO         = COMPROBANTE_CNT.ANO 
        AND DETALLE_COMPROBANTE_CNT.TIPO_]') || TO_CLOB(q'[CPTE   = COMPROBANTE_CNT.TIPO 
        AND DETALLE_COMPROBANTE_CNT.COMPROBANTE = COMPROBANTE_CNT.NUMERO 
    WHERE DETALLE_COMPROBANTE_CNT.COMPANIA = s$compania$s
      AND DETALLE_COMPROBANTE_CNT.FECHA BETWEEN TO_DATE('s$fechaInicial$s','DD/MM/YYYY') 
                                            AND TO_DATE('s$fechaFinal$s','DD/MM/YYYY') 
      AND TIPO_COMPROBANTE.CLASE_CONTABLE IN('E') 
      AND DETALLE_COMPROBANTE_CNT.VALOR_CREDITO > 0 
    GROUP BY DETALLE_COMPROBANTE_CNT.COMPANIA, 
             DETALLE_COMPROBANTE_CNT.ANO, 
             DETALLE_COMPROBANTE_CNT.TIPO_CPTE, 
             DETALLE_COMPROBANTE_CNT.COMPROBANTE, 
             COMPROBANTE_CNT.FECHA, 
             DETALLE_COMPROBANTE_CNT.TIPO_CPTE_AFECT, 
             DETALLE_COMPROBANTE_CNT.CMPTE_AFECTADO, 
             DETALLE_COMPROBANTE_CNT.CUENTA, 
             PLAN_CONTABLE.NOMBRE, 
             COMPROBANTE_CNT.DESCRIPCION, 
             COMPROBANTE_CNT.TERCERO, 
             COMPROBANTE_CNT.SUCURSAL, 
             COMPROBANTE_CNT.VLR_DOCUMENTO, 
             COMPROBANTE_CNT.VLRAGIRAR, 
             COMPROBANTE_CNT.NRO_DOCUMENTO)  LISRELACIONDEEGRESOSESP 
INNER JOIN DETALLE_COMPROBANTE_CNT 
 ON  LISRELACIONDEEGRESOSESP.COMPANIA = DETALLE_COMPROBANTE_CNT.COMPANIA 
 AND LISRELACIONDEEGRESOSESP.ANO = DETALLE_COMPROBANTE_CNT.ANO 
 AND LISRELACIONDEEGRESOSESP.TIPO_CPTE = DETALLE_COMPROBANTE_CNT.TIPO_CPTE 
 AND LISRELACIONDEEGRESOSESP.COMPROBANTE = DETALLE_COMPROBANTE_CNT.COMPROBANTE 
WHERE NVL(DETALLE_COMPROBANTE_CNT.CMPTE_AFECTADO, 0) NOT IN (0) 
GROUP BY LISRELACIONDEEGRESOSESP.COMPANIA, 
         LISRELACIONDEEGRESOSESP.ANO, 
         LISRELACIONDEEGRESOSESP.TIPO_CPTE, 
         LISRELACIONDEEGRESOSESP.COMPROBANTE, 
         LISRELACIONDEEGRESOSESP.FECHA, 
         LISRELACIONDEEGRESOSESP.CUENTA, 
         LISRELACIONDEEGRESOSESP.NOMBRE, 
         LISRELACIONDEEGRESOSESP.TERCERO, 
         LISRELACIONDEEGRESOSESP.SUCURSAL, 
         LisRelacionDeEgresosEsp.Descripcion,
         LISRELACIONDEEGRESOSESP.VALOR_CREDITO, 
         LISRELACIONDEEGRESOSESP.VLR_DOCUMENTO, 
         LISRELACIONDEEGRESOSESP.VLRAGIRAR, 
         LISRELACIONDEEGRESOSESP.NRO_DOCUMENTO, 
         DETALLE_COMPROBANTE_CNT.TIPO_CPTE_AFECT, 
         DETALLE_COMPROBANTE_CNT.CMPTE_AFECTADO)
LISRELACIONDEEGRESOSESPCOM
  ON  LISRELACIONDEEGRESOSESPEGRT.COMPANIA    = LISRELACIONDEEGRESOSESPCOM.COMPANIA 
  AND LISRELACIONDEEGRESOSESPEGRT.ANO         = LISRELACIONDEEGRESOSESPCOM.ANO 
  AND LISRELACIONDEEGRESOSESPEGRT.TIPO_CPTE   = LISRELACIONDEEGRESOSESPCOM.TIPO_CPTE
  AND LISRELACIONDEEGRESOSESPEGRT.COMPROBANTE = LISRELACIONDEEGRESOSESPCOM.COMPROBANTE 
WHERE LISRELACIONDEEGRESOSESPCOM.COMPROBANTE IS NULL
) LISRELACIONDEEGRESOSESPEGR
INNER JOIN DETALLE_COMPROBANTE_CNT 
  ON  LISRELACIONDEEGRESOSESPEGR.COMPANIA    = DETALLE_COMPROBANTE_CNT.COMPANIA 
  AND LISRELACIONDEEGRESOSESPEGR.ANO         = DETALLE_COMPROBANTE_CNT.ANO 
  AND LISRELACIONDEEGRESOSESPEGR.TIPO_CPTE   = DETALLE_COMPROBANTE_CNT.TIPO_CPTE 
  AND LISRELACIO]') || TO_CLOB(q'[NDEEGRESOSESPEGR.COMPROBANTE = DETALLE_COMPROBANTE_CNT.COMPROBANTE
WHERE DETALLE_COMPROBANTE_CNT.VALOR_CREDITO NOT IN (0) 
UNION ALL
SELECT LISRELACIONDEEGRESOSESPCOM.COMPANIA, 
       LISRELACIONDEEGRESOSESPCOM.ANO, 
       LISRELACIONDEEGRESOSESPCOM.TIPO_CPTE, 
       LISRELACIONDEEGRESOSESPCOM.COMPROBANTE, 
       LISRELACIONDEEGRESOSESPCOM.FECHA, 
       LISRELACIONDEEGRESOSESPCOM.NOMBRE, 
       LISRELACIONDEEGRESOSESPCOM.TERCERO, 
       LISRELACIONDEEGRESOSESPCOM.CUENTA,
       LISRELACIONDEEGRESOSESPCOM.SUCURSAL, 
       LISRELACIONDEEGRESOSESPCOM.DESCRIPCION, 
       LISRELACIONDEEGRESOSESPCOM.VALOR_CREDITO, 
       LISRELACIONDEEGRESOSESPCOM.VLR_DOCUMENTO, 
       LISRELACIONDEEGRESOSESPCOM.NRO_DOCUMENTO, 
       DETALLE_COMPROBANTE_CNT.CUENTA AS CTAIMP,   
       SUM(CASE WHEN SUBSTR(DETALLE_COMPROBANTE_CNT.CUENTA,0,6) BETWEEN '243600' AND '243690' 
                      AND SUBSTR(DETALLE_COMPROBANTE_CNT.CUENTA,1,6) NOT IN('243625')
                THEN DETALLE_COMPROBANTE_CNT.VALOR_CREDITO-DETALLE_COMPROBANTE_CNT.VALOR_DEBITO
                ELSE 0
                END) AS RETEFUENTE, 
       SUM(CASE WHEN SUBSTR(DETALLE_COMPROBANTE_CNT.CUENTA,0,6) IN ('243625') 
                THEN DETALLE_COMPROBANTE_CNT.VALOR_CREDITO-DETALLE_COMPROBANTE_CNT.VALOR_DEBITO
                ELSE 0
                END) AS RETEIVA, 
       SUM(CASE WHEN SUBSTR(DETALLE_COMPROBANTE_CNT.CUENTA,0,6) NOT BETWEEN '243601' AND '243690'
                THEN DETALLE_COMPROBANTE_CNT.VALOR_CREDITO-DETALLE_COMPROBANTE_CNT.VALOR_DEBITO
                ELSE 0
                END) AS Otros 
FROM (SELECT LISRELACIONDEEGRESOSESP.COMPANIA, 
       LISRELACIONDEEGRESOSESP.ANO, 
       LISRELACIONDEEGRESOSESP.TIPO_CPTE, 
       LISRELACIONDEEGRESOSESP.COMPROBANTE, 
       LISRELACIONDEEGRESOSESP.FECHA, 
       LISRELACIONDEEGRESOSESP.CUENTA, 
       LISRELACIONDEEGRESOSESP.NOMBRE, 
       LISRELACIONDEEGRESOSESP.TERCERO,
       LISRELACIONDEEGRESOSESP.SUCURSAL, 
       LISRELACIONDEEGRESOSESP.DESCRIPCION, 
       LISRELACIONDEEGRESOSESP.VALOR_CREDITO, 
       LISRELACIONDEEGRESOSESP.VLR_DOCUMENTO, 
       LISRELACIONDEEGRESOSESP.VLRAGIRAR, 
       LISRELACIONDEEGRESOSESP.NRO_DOCUMENTO, 
       DETALLE_COMPROBANTE_CNT.TIPO_CPTE_AFECT, 
       DETALLE_COMPROBANTE_CNT.CMPTE_AFECTADO 
FROM (
      SELECT DETALLE_COMPROBANTE_CNT.COMPANIA, 
             DETALLE_COMPROBANTE_CNT.ANO, 
             DETALLE_COMPROBANTE_CNT.TIPO_CPTE, 
             DETALLE_COMPROBANTE_CNT.COMPROBANTE, 
             COMPROBANTE_CNT.FECHA, 
             DETALLE_COMPROBANTE_CNT.TIPO_CPTE_AFECT, 
             DETALLE_COMPROBANTE_CNT.CMPTE_AFECTADO, 
             DETALLE_COMPROBANTE_CNT.CUENTA, 
             PLAN_CONTABLE.NOMBRE, 
             COMPROBANTE_CNT.DESCRIPCION, 
             COMPROBANTE_CNT.TERCERO, 
             COMPROBANTE_CNT.SUCURSAL, 
             COMPROBANTE_CNT.NRO_DOCUMENTO, 
             COMPROBANTE_CNT.VLR_DOCUMENTO, 
             COMPROBANTE_CNT.VLRAGIRAR, 
             SUM(DETALLE_CO]') || TO_CLOB(q'[MPROBANTE_CNT.VALOR_CREDITO) VALOR_CREDITO 
     FROM DETALLE_COMPROBANTE_CNT 
      INNER JOIN PLAN_CONTABLE 
    	ON  DETALLE_COMPROBANTE_CNT.COMPANIA = PLAN_CONTABLE.COMPANIA 
    	AND DETALLE_COMPROBANTE_CNT.ANO      = PLAN_CONTABLE.ANO 
    	AND DETALLE_COMPROBANTE_CNT.CUENTA   = PLAN_CONTABLE.CODIGO 
      INNER JOIN TIPO_COMPROBANTE 
        ON  DETALLE_COMPROBANTE_CNT.COMPANIA  = TIPO_COMPROBANTE.COMPANIA 
        AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE = TIPO_COMPROBANTE.CODIGO 
      INNER JOIN COMPROBANTE_CNT 
        ON  DETALLE_COMPROBANTE_CNT.COMPANIA    = COMPROBANTE_CNT.COMPANIA 
        AND DETALLE_COMPROBANTE_CNT.ANO         = COMPROBANTE_CNT.ANO 
        AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE   = COMPROBANTE_CNT.TIPO 
        AND DETALLE_COMPROBANTE_CNT.COMPROBANTE = COMPROBANTE_CNT.NUMERO 
    WHERE DETALLE_COMPROBANTE_CNT.COMPANIA = s$compania$s
      AND DETALLE_COMPROBANTE_CNT.FECHA BETWEEN TO_DATE('s$fechaInicial$s','DD/MM/YYYY') 
                                            AND TO_DATE('s$fechaFinal$s','DD/MM/YYYY') 
      AND TIPO_COMPROBANTE.CLASE_CONTABLE IN('E') 
      AND DETALLE_COMPROBANTE_CNT.VALOR_CREDITO > 0 
    GROUP BY DETALLE_COMPROBANTE_CNT.COMPANIA, 
             DETALLE_COMPROBANTE_CNT.ANO, 
             DETALLE_COMPROBANTE_CNT.TIPO_CPTE, 
             DETALLE_COMPROBANTE_CNT.COMPROBANTE, 
             COMPROBANTE_CNT.FECHA, 
             DETALLE_COMPROBANTE_CNT.TIPO_CPTE_AFECT, 
             DETALLE_COMPROBANTE_CNT.CMPTE_AFECTADO, 
             DETALLE_COMPROBANTE_CNT.CUENTA, 
             PLAN_CONTABLE.NOMBRE, 
             COMPROBANTE_CNT.DESCRIPCION, 
             COMPROBANTE_CNT.TERCERO, 
             COMPROBANTE_CNT.SUCURSAL, 
             COMPROBANTE_CNT.VLR_DOCUMENTO, 
             COMPROBANTE_CNT.VLRAGIRAR, 
             COMPROBANTE_CNT.NRO_DOCUMENTO)  LISRELACIONDEEGRESOSESP 
LEFT JOIN DETALLE_COMPROBANTE_CNT 
 ON  LISRELACIONDEEGRESOSESP.COMPANIA = DETALLE_COMPROBANTE_CNT.COMPANIA 
 AND LISRELACIONDEEGRESOSESP.ANO = DETALLE_COMPROBANTE_CNT.ANO 
 AND LISRELACIONDEEGRESOSESP.TIPO_CPTE = DETALLE_COMPROBANTE_CNT.TIPO_CPTE 
 AND LISRELACIONDEEGRESOSESP.COMPROBANTE = DETALLE_COMPROBANTE_CNT.COMPROBANTE 
WHERE NVL(DETALLE_COMPROBANTE_CNT.CMPTE_AFECTADO, 0) NOT IN (0) 
GROUP BY LISRELACIONDEEGRESOSESP.COMPANIA, 
         LISRELACIONDEEGRESOSESP.ANO, 
         LISRELACIONDEEGRESOSESP.TIPO_CPTE, 
         LISRELACIONDEEGRESOSESP.COMPROBANTE, 
         LISRELACIONDEEGRESOSESP.FECHA, 
         LISRELACIONDEEGRESOSESP.CUENTA, 
         LISRELACIONDEEGRESOSESP.NOMBRE, 
         LISRELACIONDEEGRESOSESP.TERCERO,
         LISRELACIONDEEGRESOSESP.SUCURSAL, 
         LisRelacionDeEgresosEsp.Descripcion, 
         LISRELACIONDEEGRESOSESP.VALOR_CREDITO, 
         LISRELACIONDEEGRESOSESP.VLR_DOCUMENTO, 
         LISRELACIONDEEGRESOSESP.VLRAGIRAR, 
         LISRELACIONDEEGRESOSESP.NRO_DOCUMENTO, 
         DETALLE_COMPROBANTE_CNT.TIPO_CPTE_AFECT, 
         DETALLE_COMPROBANTE_CNT.CMPTE_AFECTADO) LISRELACIONDEEGRESOSESPCOM]') || TO_CLOB(q'[ 
LEFT JOIN DETALLE_COMPROBANTE_CNT 
ON  LISRELACIONDEEGRESOSESPCOM.COMPANIA = DETALLE_COMPROBANTE_CNT.COMPANIA 
AND LISRELACIONDEEGRESOSESPCOM.ANO = DETALLE_COMPROBANTE_CNT.ANO 
AND LISRELACIONDEEGRESOSESPCOM.TIPO_CPTE_AFECT = DETALLE_COMPROBANTE_CNT.TIPO_CPTE 
AND LISRELACIONDEEGRESOSESPCOM.CMPTE_AFECTADO = DETALLE_COMPROBANTE_CNT.COMPROBANTE
WHERE DETALLE_COMPROBANTE_CNT.TIPO_CPTE IS NOT NULL 
GROUP BY LISRELACIONDEEGRESOSESPCOM.COMPANIA, 
         LISRELACIONDEEGRESOSESPCOM.ANO, 
         LISRELACIONDEEGRESOSESPCOM.TIPO_CPTE, 
         LISRELACIONDEEGRESOSESPCOM.COMPROBANTE, 
         LISRELACIONDEEGRESOSESPCOM.FECHA, 
         LISRELACIONDEEGRESOSESPCOM.NOMBRE, 
         LISRELACIONDEEGRESOSESPCOM.TERCERO, 
         LISRELACIONDEEGRESOSESPCOM.SUCURSAL, 
         LISRELACIONDEEGRESOSESPCOM.DESCRIPCION, 
         LISRELACIONDEEGRESOSESPCOM.VALOR_CREDITO, 
         LISRELACIONDEEGRESOSESPCOM.VLR_DOCUMENTO, 
          LISRELACIONDEEGRESOSESPCOM.CUENTA,
         LISRELACIONDEEGRESOSESPCOM.NRO_DOCUMENTO, 
         DETALLE_COMPROBANTE_CNT.CUENTA, 
         DETALLE_COMPROBANTE_CNT.TIPO_CPTE, 
         DETALLE_COMPROBANTE_CNT.COMPROBANTE 
UNION ALL
SELECT LISRELACIONDEEGRESOSESPCOM.COMPANIA, 
       LISRELACIONDEEGRESOSESPCOM.ANO, 
       LISRELACIONDEEGRESOSESPCOM.TIPO_CPTE, 
       LISRELACIONDEEGRESOSESPCOM.COMPROBANTE, 
       LISRELACIONDEEGRESOSESPCOM.FECHA, 
       LISRELACIONDEEGRESOSESPCOM.NOMBRE, 
       LISRELACIONDEEGRESOSESPCOM.TERCERO, 
       LISRELACIONDEEGRESOSESPCOM.CUENTA,
       LISRELACIONDEEGRESOSESPCOM.SUCURSAL, 
       LISRELACIONDEEGRESOSESPCOM.DESCRIPCION, 
       LISRELACIONDEEGRESOSESPCOM.VALOR_CREDITO, 
       LISRELACIONDEEGRESOSESPCOM.VLR_DOCUMENTO, 
       LISRELACIONDEEGRESOSESPCOM.NRO_DOCUMENTO, 
       DETALLE_COMPROBANTE_CNT.CUENTA AS CTAIMP,   
       SUM(CASE WHEN SUBSTR(DETALLE_COMPROBANTE_CNT.CUENTA,0,6) BETWEEN '243600' AND '243690' 
                      AND SUBSTR(DETALLE_COMPROBANTE_CNT.CUENTA,1,6) NOT IN '243625'
                THEN DETALLE_COMPROBANTE_CNT.VALOR_CREDITO-DETALLE_COMPROBANTE_CNT.VALOR_DEBITO
                ELSE 0
                END) AS RETEFUENTE, 
       SUM(CASE WHEN SUBSTR(DETALLE_COMPROBANTE_CNT.CUENTA,0,6) IN ('243625')
                THEN DETALLE_COMPROBANTE_CNT.VALOR_CREDITO-DETALLE_COMPROBANTE_CNT.VALOR_DEBITO
                ELSE 0
                END) AS RETEIVA, 
       SUM(CASE WHEN SUBSTR(DETALLE_COMPROBANTE_CNT.CUENTA,0,6) NOT BETWEEN '243601' AND '243690'
                THEN DETALLE_COMPROBANTE_CNT.VALOR_CREDITO-DETALLE_COMPROBANTE_CNT.VALOR_DEBITO
                ELSE 0
                END) AS OTROS   
FROM (SELECT LISRELACIONDEEGRESOSESP.COMPANIA, 
       LISRELACIONDEEGRESOSESP.ANO, 
       LISRELACIONDEEGRESOSESP.TIPO_CPTE, 
       LISRELACIONDEEGRESOSESP.COMPROBANTE, 
       LISRELACIONDEEGRESOSESP.FECHA, 
       LISRELACIONDEEGRESOSESP.CUENTA, 
       LISRELACIONDEEGRESOSESP.NOMBRE, 
       LISRELACIONDEEGRESOSESP.TERCERO, 
       LISRELACIONDEEGRESOSESP.SUCURSAL, 
]') || TO_CLOB(q'[       LISRELACIONDEEGRESOSESP.DESCRIPCION, 
       LISRELACIONDEEGRESOSESP.VALOR_CREDITO, 
       LISRELACIONDEEGRESOSESP.VLR_DOCUMENTO, 
       LISRELACIONDEEGRESOSESP.VLRAGIRAR, 
       LISRELACIONDEEGRESOSESP.NRO_DOCUMENTO, 
       DETALLE_COMPROBANTE_CNT.TIPO_CPTE_AFECT, 
       DETALLE_COMPROBANTE_CNT.CMPTE_AFECTADO 
FROM (
      SELECT DETALLE_COMPROBANTE_CNT.COMPANIA, 
             DETALLE_COMPROBANTE_CNT.ANO, 
             DETALLE_COMPROBANTE_CNT.TIPO_CPTE, 
             DETALLE_COMPROBANTE_CNT.COMPROBANTE, 
             COMPROBANTE_CNT.FECHA, 
             DETALLE_COMPROBANTE_CNT.TIPO_CPTE_AFECT, 
             DETALLE_COMPROBANTE_CNT.CMPTE_AFECTADO, 
             DETALLE_COMPROBANTE_CNT.CUENTA, 
             PLAN_CONTABLE.NOMBRE, 
             COMPROBANTE_CNT.DESCRIPCION, 
             COMPROBANTE_CNT.TERCERO, 
             COMPROBANTE_CNT.SUCURSAL, 
             COMPROBANTE_CNT.NRO_DOCUMENTO, 
             COMPROBANTE_CNT.VLR_DOCUMENTO, 
             COMPROBANTE_CNT.VLRAGIRAR, 
             SUM(DETALLE_COMPROBANTE_CNT.VALOR_CREDITO) VALOR_CREDITO 
     FROM DETALLE_COMPROBANTE_CNT 
      INNER JOIN PLAN_CONTABLE 
    	ON  DETALLE_COMPROBANTE_CNT.COMPANIA = PLAN_CONTABLE.COMPANIA 
    	AND DETALLE_COMPROBANTE_CNT.ANO      = PLAN_CONTABLE.ANO 
    	AND DETALLE_COMPROBANTE_CNT.CUENTA   = PLAN_CONTABLE.CODIGO 
      INNER JOIN TIPO_COMPROBANTE 
        ON  DETALLE_COMPROBANTE_CNT.COMPANIA  = TIPO_COMPROBANTE.COMPANIA 
        AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE = TIPO_COMPROBANTE.CODIGO 
      INNER JOIN COMPROBANTE_CNT 
        ON  DETALLE_COMPROBANTE_CNT.COMPANIA    = COMPROBANTE_CNT.COMPANIA 
        AND DETALLE_COMPROBANTE_CNT.ANO         = COMPROBANTE_CNT.ANO 
        AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE   = COMPROBANTE_CNT.TIPO 
        AND DETALLE_COMPROBANTE_CNT.COMPROBANTE = COMPROBANTE_CNT.NUMERO 
    WHERE DETALLE_COMPROBANTE_CNT.COMPANIA = s$compania$s
      AND DETALLE_COMPROBANTE_CNT.FECHA BETWEEN TO_DATE('s$fechaInicial$s','DD/MM/YYYY') 
                                            AND TO_DATE('s$fechaFinal$s','DD/MM/YYYY') 
      AND TIPO_COMPROBANTE.CLASE_CONTABLE IN('E') 
      AND DETALLE_COMPROBANTE_CNT.VALOR_CREDITO > 0 
    GROUP BY DETALLE_COMPROBANTE_CNT.COMPANIA, 
             DETALLE_COMPROBANTE_CNT.ANO, 
             DETALLE_COMPROBANTE_CNT.TIPO_CPTE, 
             DETALLE_COMPROBANTE_CNT.COMPROBANTE, 
             COMPROBANTE_CNT.FECHA, 
             DETALLE_COMPROBANTE_CNT.TIPO_CPTE_AFECT, 
             DETALLE_COMPROBANTE_CNT.CMPTE_AFECTADO, 
             DETALLE_COMPROBANTE_CNT.CUENTA, 
             PLAN_CONTABLE.NOMBRE, 
             COMPROBANTE_CNT.DESCRIPCION, 
             COMPROBANTE_CNT.TERCERO, 
             COMPROBANTE_CNT.SUCURSAL, 
             COMPROBANTE_CNT.VLR_DOCUMENTO, 
             COMPROBANTE_CNT.VLRAGIRAR, 
             COMPROBANTE_CNT.NRO_DOCUMENTO)  LISRELACIONDEEGRESOSESP 
INNER JOIN DETALLE_COMPROBANTE_CNT 
 ON  LISRELACIONDEEGRESOSESP.COMPANIA    = DETALLE_COMPROBANTE_CNT.COMPANIA 
 ]') || TO_CLOB(q'[AND LISRELACIONDEEGRESOSESP.ANO         = DETALLE_COMPROBANTE_CNT.ANO 
 AND LISRELACIONDEEGRESOSESP.TIPO_CPTE   = DETALLE_COMPROBANTE_CNT.TIPO_CPTE 
 AND LISRELACIONDEEGRESOSESP.COMPROBANTE = DETALLE_COMPROBANTE_CNT.COMPROBANTE 
WHERE NVL(DETALLE_COMPROBANTE_CNT.CMPTE_AFECTADO, 0) NOT IN (0) 
GROUP BY LISRELACIONDEEGRESOSESP.COMPANIA, 
         LISRELACIONDEEGRESOSESP.ANO, 
         LISRELACIONDEEGRESOSESP.TIPO_CPTE, 
         LISRELACIONDEEGRESOSESP.COMPROBANTE, 
         LISRELACIONDEEGRESOSESP.FECHA, 
         LISRELACIONDEEGRESOSESP.CUENTA, 
         LISRELACIONDEEGRESOSESP.NOMBRE, 
         LISRELACIONDEEGRESOSESP.TERCERO, 
         LISRELACIONDEEGRESOSESP.SUCURSAL, 
         LisRelacionDeEgresosEsp.Descripcion, 
         LISRELACIONDEEGRESOSESP.VALOR_CREDITO, 
         LISRELACIONDEEGRESOSESP.VLR_DOCUMENTO, 
         LISRELACIONDEEGRESOSESP.VLRAGIRAR, 
         LISRELACIONDEEGRESOSESP.NRO_DOCUMENTO,
         DETALLE_COMPROBANTE_CNT.TIPO_CPTE_AFECT, 
         DETALLE_COMPROBANTE_CNT.CMPTE_AFECTADO) LISRELACIONDEEGRESOSESPCOM 
LEFT JOIN DETALLE_COMPROBANTE_CNT 
  ON  LISRELACIONDEEGRESOSESPCOM.COMPANIA        = DETALLE_COMPROBANTE_CNT.COMPANIA 
  AND LISRELACIONDEEGRESOSESPCOM.ANO-1           = DETALLE_COMPROBANTE_CNT.ANO 
  AND LISRELACIONDEEGRESOSESPCOM.TIPO_CPTE_AFECT = DETALLE_COMPROBANTE_CNT.TIPO_CPTE 
  AND LISRELACIONDEEGRESOSESPCOM.CMPTE_AFECTADO  = DETALLE_COMPROBANTE_CNT.COMPROBANTE
WHERE DETALLE_COMPROBANTE_CNT.TIPO_CPTE IS NOT NULL 
GROUP BY LISRELACIONDEEGRESOSESPCOM.COMPANIA, 
         LISRELACIONDEEGRESOSESPCOM.ANO, 
         LISRELACIONDEEGRESOSESPCOM.TIPO_CPTE, 
         LISRELACIONDEEGRESOSESPCOM.COMPROBANTE, 
         LISRELACIONDEEGRESOSESPCOM.FECHA, 
         LISRELACIONDEEGRESOSESPCOM.NOMBRE, 
         LISRELACIONDEEGRESOSESPCOM.TERCERO, 
         LISRELACIONDEEGRESOSESPCOM.SUCURSAL, 
         LISRELACIONDEEGRESOSESPCOM.DESCRIPCION, 
         LISRELACIONDEEGRESOSESPCOM.VALOR_CREDITO, 
         LISRELACIONDEEGRESOSESPCOM.VLR_DOCUMENTO, 
         LISRELACIONDEEGRESOSESPCOM.NRO_DOCUMENTO, 
         LISRELACIONDEEGRESOSESPCOM.CUENTA,
         DETALLE_COMPROBANTE_CNT.CUENTA, 
         DETALLE_COMPROBANTE_CNT.TIPO_CPTE, 
         DETALLE_COMPROBANTE_CNT.COMPROBANTE
) LISRELACIONDEEGRESOSESPTOT 
  LEFT JOIN PLAN_CONTABLE 
    ON LISRELACIONDEEGRESOSESPTOT.COMPANIA = PLAN_CONTABLE.COMPANIA 
   AND LISRELACIONDEEGRESOSESPTOT.ANO      = PLAN_CONTABLE.ANO 
   AND LISRELACIONDEEGRESOSESPTOT.CTAIMP   = PLAN_CONTABLE.CODIGO  
  LEFT JOIN TERCERO 
    ON  LISRELACIONDEEGRESOSESPTOT.COMPANIA = TERCERO.COMPANIA
    AND LISRELACIONDEEGRESOSESPTOT.TERCERO  = TERCERO.NIT 
    AND LISRELACIONDEEGRESOSESPTOT.Sucursal = Tercero.Sucursal          
GROUP BY LISRELACIONDEEGRESOSESPTOT.COMPANIA, 
         LISRELACIONDEEGRESOSESPTOT.ANO, 
         LISRELACIONDEEGRESOSESPTOT.TIPO_CPTE, 
         LISRELACIONDEEGRESOSESPTOT.COMPROBANTE, 
         LISRELACIONDEEGRESOSESPTOT.FECHA, 
         LISRELACIONDEEGRESOSESPTOT.CUENTA, 
         LISRELACIONDEEGRE]') || TO_CLOB(q'[SOSESPTOT.NOMBRE, 
         LISRELACIONDEEGRESOSESPTOT.TERCERO, 
         LISRELACIONDEEGRESOSESPTOT.SUCURSAL, 
         TERCERO.NOMBRE, 
         LISRELACIONDEEGRESOSESPTOT.DESCRIPCION, 
         LISRELACIONDEEGRESOSESPTOT.VALOR_CREDITO, 
         LISRELACIONDEEGRESOSESPTOT.VLR_DOCUMENTO, 
         LISRELACIONDEEGRESOSESPTOT.NRO_DOCUMENTO
ORDER BY  COMPROBANTE, 
         FECHA]') CONSULTA, 1 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);