SELECT V_DETALLE_AUXILIAR_CNT.COMPANIA,
    ANO,
    TIPO_CPTE AS TIPO,
    COMPROBANTE AS NUMERO,
    VLR_DOCUMENTO,
    FECHA_VCN_DOC,
    CODIGO_CUENTA AS NRO_DOCUMENTO,
   TERCERO_COM TERCERO,
   TERCERO_COM_NOM TERCERO_NOM,
   TERCERO_DET_NOM TERCERO_DET_NOM,
    FECHA,
    DESCRIPCION,
    DIRECCION,
    TELEFONOS,
    CUENTANOMBRE AS NOMBRECONCEPTO,
    VALOR_CREDITO,
    (CASE WHEN VALOR_DEBITO>0 THEN 'a' || CODIGO_CUENTA ELSE 'z' || CODIGO_CUENTA END) AS SEC
FROM V_DETALLE_AUXILIAR_CNT
WHERE V_DETALLE_AUXILIAR_CNT.COMPANIA  ='s$companiaInforme$s'
    AND V_DETALLE_AUXILIAR_CNT.ANO     = s$ano$s 
    AND V_DETALLE_AUXILIAR_CNT.TIPO_CPTE   = 's$tipoCpte$s' 
    AND V_DETALLE_AUXILIAR_CNT.COMPROBANTE s$numeroCpte$s
ORDER BY V_DETALLE_AUXILIAR_CNT.COMPANIA,
    V_DETALLE_AUXILIAR_CNT.ANO,
    V_DETALLE_AUXILIAR_CNT.TIPO_CPTE,
    V_DETALLE_AUXILIAR_CNT.COMPROBANTE,
    V_DETALLE_AUXILIAR_CNT.CONSECUTIVO
