SELECT  DCPTAL1.COMPANIA 
      , DCPTAL1.ANO
      , DCPTAL1.TIPO_CPTE
      , DCPTAL1.COMPROBANTE
      , AFECTADO.CMPTE_AFECTADO NOMDIS
      , DCPTAL1.CMPTE_AFECTADO NOMRESERVA
      , DCPTAL1.CUENTA
      , PLAN_PRESUPUESTAL.NOMBRE  NOMBRECUENTA
      , SUM(CASE WHEN PLAN_PRESUPUESTAL.NATURALEZA ='C' 
              THEN DCPTAL1.VALOR_CREDITO - DCPTAL1.VALOR_DEBITO 
              ELSE DCPTAL1.VALOR_DEBITO  - DCPTAL1.VALOR_CREDITO END) VALOR
FROM DETALLE_COMPROBANTE_PPTAL DCPTAL1 INNER JOIN PLAN_PRESUPUESTAL 
  ON DCPTAL1.COMPANIA = PLAN_PRESUPUESTAL.COMPANIA 
 AND DCPTAL1.ANO      = PLAN_PRESUPUESTAL.ANO 
 AND DCPTAL1.CUENTA   = PLAN_PRESUPUESTAL.CODIGO 
LEFT JOIN DETALLE_COMPROBANTE_PPTAL AFECTADO
  ON DCPTAL1.COMPANIA        = AFECTADO.COMPANIA 
 AND DCPTAL1.ANO_AFECT       = AFECTADO.ANO 
 AND DCPTAL1.TIPO_CPTE_AFECT = AFECTADO.TIPO_CPTE 
 AND DCPTAL1.CMPTE_AFECTADO  = AFECTADO.COMPROBANTE 
 AND DCPTAL1.CONSECUTIVOPPTO = AFECTADO.CONSECUTIVO
WHERE DCPTAL1.COMPANIA    = $P{PR_COMPANIA}
  AND DCPTAL1.ANO         = $P{PR_ANO} 
  AND DCPTAL1.TIPO_CPTE   = $P{PR_TIPO_CPTE}
  AND DCPTAL1.COMPROBANTE = $P{PR_COMPROBANTE}
GROUP BY  DCPTAL1.COMPANIA 
        , DCPTAL1.ANO
        , DCPTAL1.TIPO_CPTE
        , DCPTAL1.COMPROBANTE
        , AFECTADO.CMPTE_AFECTADO
        , DCPTAL1.CMPTE_AFECTADO
        , DCPTAL1.CUENTA
        , PLAN_PRESUPUESTAL.NOMBRE 
