SELECT 
      V_DETALLE_AUXILIAR_CNT.NRO_DOCUMENTO,
      V_DETALLE_AUXILIAR_CNT.VALOR_CREDITO,
      TERCERO_1.NIT,
      TERCERO_1.NOMBRE AS NOMBRETERCERO,
      TERCERO_1.DIRECCION,
      TO_CHAR(COMPROBANTE_CNT.FECHA_VCN_DOC,'DD/MM/YYYY')FECHA_VCN_DOC,
      COMPROBANTE_CNT.NUMERO,
      TO_CHAR(COMPROBANTE_CNT.FECHA,'DD/MM/YYYY') FECHA,
      COMPROBANTE_CNT.DESCRIPCION,
      TERCERO_1.TELEFONOS,
      V_DETALLE_AUXILIAR_CNT.COMPROBANTE,
      COMPROBANTE_CNT.TIPO,
      NVL(V_DETALLE_AUXILIAR_CNT.VLR_DOCUMENTO,0)AS VLR_DOCUMENTO,
      V_PLAN_CONTABLE.NOMBRE,
      CASE
          WHEN V_DETALLE_AUXILIAR_CNT.CENTRO_COSTO = PCK_DATOS.FC_CONS_CENTRO()
          THEN NULL
          ELSE V_DETALLE_AUXILIAR_CNT.CENTRO_COSTO
      END CODCENTRO,
      CASE
          WHEN V_DETALLE_AUXILIAR_CNT.VALOR_DEBITO<>0
          THEN 'A' || V_DETALLE_AUXILIAR_CNT.CODIGO_CUENTA
          ELSE 'Z' || V_DETALLE_AUXILIAR_CNT.CODIGO_CUENTA
      END SEC
FROM ((TIPO_COMPROBANTE
INNER JOIN COMPROBANTE_CNT
          ON (TIPO_COMPROBANTE.COMPANIA = COMPROBANTE_CNT.COMPANIA)
         AND (TIPO_COMPROBANTE.CODIGO  = COMPROBANTE_CNT.TIPO))
INNER JOIN (COMPANIA
INNER JOIN ((V_PLAN_CONTABLE
INNER JOIN V_DETALLE_AUXILIAR_CNT
   ON (V_PLAN_CONTABLE.ID        = V_DETALLE_AUXILIAR_CNT.CODIGO_CUENTA)
  AND (V_PLAN_CONTABLE.COMPANIA = V_DETALLE_AUXILIAR_CNT.COMPANIA)
  AND (V_PLAN_CONTABLE.ANO      = V_DETALLE_AUXILIAR_CNT.ANO))
LEFT JOIN TERCERO
  ON (TERCERO.NIT              = V_DETALLE_AUXILIAR_CNT.TERCERO)
 AND (TERCERO.SUCURSAL        = V_DETALLE_AUXILIAR_CNT.SUCURSAL)
 AND (TERCERO.COMPANIA        = V_DETALLE_AUXILIAR_CNT.COMPANIA))
  ON COMPANIA.CODIGO           = V_PLAN_CONTABLE.COMPANIA)
  ON (COMPROBANTE_CNT.COMPANIA = V_DETALLE_AUXILIAR_CNT.COMPANIA)
 AND (COMPROBANTE_CNT.ANO     = V_DETALLE_AUXILIAR_CNT.ANO)
 AND (COMPROBANTE_CNT.TIPO    = V_DETALLE_AUXILIAR_CNT.TIPO_CPTE)
 AND (COMPROBANTE_CNT.NUMERO  = V_DETALLE_AUXILIAR_CNT.COMPROBANTE))
LEFT JOIN TERCERO TERCERO_1
  ON (TERCERO_1.NIT                        = COMPROBANTE_CNT.TERCERO)
 AND (TERCERO_1.SUCURSAL                  = COMPROBANTE_CNT.SUCURSAL)
 AND (TERCERO_1.COMPANIA                  = COMPROBANTE_CNT.COMPANIA)
WHERE (((V_DETALLE_AUXILIAR_CNT.COMPANIA)='s$companiaInforme$s')
  AND ((V_DETALLE_AUXILIAR_CNT.ANO)        =s$ano$s)
  AND ((V_DETALLE_AUXILIAR_CNT.TIPO_CPTE)  ='s$tipoCpte$s')
  AND ((V_DETALLE_AUXILIAR_CNT.COMPROBANTE) BETWEEN s$numeroPptoInicial$s AND s$numeroPptoFinal$s)
  AND ((V_DETALLE_AUXILIAR_CNT.VALOR_CREDITO)>0))
ORDER BY V_DETALLE_AUXILIAR_CNT.COMPANIA,
   		 V_DETALLE_AUXILIAR_CNT.ANO,
    	 V_DETALLE_AUXILIAR_CNT.TIPO_CPTE,
    	 V_DETALLE_AUXILIAR_CNT.COMPROBANTE,
    	 V_DETALLE_AUXILIAR_CNT.CONSECUTIVO
