SELECT V_DETALLE_AUXILIAR_CNT.ANO ANOCOMP,
  CASE
    WHEN V_DETALLE_AUXILIAR_CNT.CODIGOPOSTAL_DET IS NULL
    OR V_DETALLE_AUXILIAR_CNT.CODIGOPOSTAL_DET    =''
    THEN PCK_SYSMAN_UTL.FC_PAR(V_DETALLE_AUXILIAR_CNT.COMPANIA,'CODIGO POSTAL',1,SYSDATE,-1)
    ELSE V_DETALLE_AUXILIAR_CNT.CODIGOPOSTAL_DET
  END CODIGOPOSTAL,
  V_DETALLE_AUXILIAR_CNT.COMPANIA COMP,
  V_DETALLE_AUXILIAR_CNT.DESCRIPCION,
  COMPROBANTE_CNT.FECHA,
 DETALLE_COMPROBANTE_CNT.COMPROBANTE,
  V_DETALLE_AUXILIAR_CNT.NRO_DOCUMENTO,
  V_DETALLE_AUXILIAR_CNT.TERCERO_COM TERCERO,
  V_DETALLE_AUXILIAR_CNT.CREATED_BY   CREADOR,
  DETALLE_COMPROBANTE_CNT.CUENTA,
  COMPANIA.DIRECCION,
  V_DETALLE_AUXILIAR_CNT.FECHA_VCN_DOC,
  COMPROBANTE_CNT.NUMEROCONTRATO NOCONTRATO,
  V_DETALLE_AUXILIAR_CNT.TERCERO_COM_NOM NOMBRETERCERO1,
  V_DETALLE_AUXILIAR_CNT.COMPROBANTE NUMCOMP,
  V_DETALLE_AUXILIAR_CNT.COMPROBANTE NUMERO,
  CASE
    WHEN V_DETALLE_AUXILIAR_CNT.VALOR_DEBITO <> 0
    THEN 'A'
      || DETALLE_COMPROBANTE_CNT.CUENTA
    ELSE 'Z'
      || DETALLE_COMPROBANTE_CNT.CUENTA
  END SEC,
  V_DETALLE_AUXILIAR_CNT.DIRECCION_DET TERCERODIRE,
  V_DETALLE_AUXILIAR_CNT.TEXTO,
  V_DETALLE_AUXILIAR_CNT.TIPO_CPTE TIPO,
  V_DETALLE_AUXILIAR_CNT.TIPO_COMPROBANTE_NOM NOMBRE,
  V_DETALLE_AUXILIAR_CNT.TIPO_CPTE TIPOCOMP,
  TIPOORDENDECOMPRA.NOMBRE TIPOCONTRATOS,
  V_DETALLE_AUXILIAR_CNT.CUENTANOMBRE TOTALNOMBRE,
  V_DETALLE_AUXILIAR_CNT.VALOR_CREDITO,
  V_DETALLE_AUXILIAR_CNT.VALOR_DEBITO,
  V_DETALLE_AUXILIAR_CNT.VLR_DOCUMENTO,
  V_DETALLE_AUXILIAR_CNT.VLRAGIRAR,
  PCK_CONTABILIDAD2.FC_LLENARFORMATOCHEQUETOTAL(DETALLE_COMPROBANTE_CNT.COMPANIA, COMPANIA.NOMBRE, 1, DETALLE_COMPROBANTE_CNT.ANO, DETALLE_COMPROBANTE_CNT.TIPO_CPTE, DETALLE_COMPROBANTE_CNT.COMPROBANTE) FORMATO,
  DETALLE_COMPROBANTE_CNT.CMPTE_AFECTADO NUMEROAAFECTAR,
  DETALLE_COMPROBANTE_CNT.TIPO_CPTE_AFECT TIPOAAFECTAR
FROM V_DETALLE_AUXILIAR_CNT
INNER JOIN COMPROBANTE_CNT
ON COMPROBANTE_CNT.COMPANIA = V_DETALLE_AUXILIAR_CNT.COMPANIA
AND COMPROBANTE_CNT.ANO     = V_DETALLE_AUXILIAR_CNT.ANO
AND COMPROBANTE_CNT.TIPO    = V_DETALLE_AUXILIAR_CNT.TIPO_CPTE
AND COMPROBANTE_CNT.NUMERO  = V_DETALLE_AUXILIAR_CNT.COMPROBANTE
INNER JOIN DETALLE_COMPROBANTE_CNT
ON DETALLE_COMPROBANTE_CNT.COMPANIA     = V_DETALLE_AUXILIAR_CNT.COMPANIA
AND DETALLE_COMPROBANTE_CNT.ANO         = V_DETALLE_AUXILIAR_CNT.ANO
AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE   = V_DETALLE_AUXILIAR_CNT.TIPO_CPTE
AND DETALLE_COMPROBANTE_CNT.COMPROBANTE = V_DETALLE_AUXILIAR_CNT.COMPROBANTE
AND DETALLE_COMPROBANTE_CNT.MES         = V_DETALLE_AUXILIAR_CNT.MES
AND DETALLE_COMPROBANTE_CNT.CONSECUTIVO = V_DETALLE_AUXILIAR_CNT.CONSECUTIVO
INNER JOIN COMPANIA
ON DETALLE_COMPROBANTE_CNT.COMPANIA = COMPANIA.CODIGO
LEFT JOIN TIPOORDENDECOMPRA
ON COMPROBANTE_CNT.TIPOCONTRATO       = TIPOORDENDECOMPRA.CODIGO
AND COMPROBANTE_CNT.COMPANIA          = TIPOORDENDECOMPRA.COMPANIA
WHERE DETALLE_COMPROBANTE_CNT.COMPANIA=  s$compania$s
AND DETALLE_COMPROBANTE_CNT.ANO       = s$ano$s
AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE = 's$tipoCpte$s'
AND DETALLE_COMPROBANTE_CNT.COMPROBANTE BETWEEN s$numeroPptoInicial$s AND s$numeroPptoFinal$s
