MERGE INTO CONSULTAS FIN USING (SELECT '001529EGRRetencionesIDSN' INFORME ,TO_CLOB(q'[SELECT COMPROBANTE_CNTRETENCION.COMPANIA,
  COMPROBANTE_CNTRETENCION.ANO,
  COMPROBANTE_CNTRETENCION.TIPO,
  COMPROBANTE_CNTRETENCION.NUMERO,
  COMPROBANTE_CNTRETENCION.TIPORETENCION,
  COMPROBANTE_CNTRETENCION.CODIGORETENCION,
  RETENCIONES.PCT_APLICAR,
  CASE
    WHEN LEY1450 <> 0
    THEN VALORBASELEY1607
    ELSE COMPROBANTE_CNTRETENCION.VALORBASE
  END VALORBASE,
  TIPORETENCION.NOMBRE,
  COMPROBANTE_CNTRETENCION.VALOR RETENIDO,
  COMPROBANTE_CNTRETENCION.VALOR
FROM COMPROBANTE_CNTRETENCION
LEFT JOIN COMPROBANTE_CNT
ON COMPROBANTE_CNTRETENCION.COMPANIA = COMPROBANTE_CNT.COMPANIA
AND COMPROBANTE_CNTRETENCION.ANO     = COMPROBANTE_CNT.ANO
AND COMPROBANTE_CNTRETENCION.TIPO    = COMPROBANTE_CNT.TIPO
AND COMPROBANTE_CNTRETENCION.NUMERO  = COMPROBANTE_CNT.NUMERO
LEFT JOIN COMPROBANTE_CNTAFECTADOS
ON COMPROBANTE_CNTAFECTADOS.COMPANIA           = COMPROBANTE_CNT.COMPANIA
AND COMPROBANTE_CNTAFECTADOS.ANO_AFECT         = COMPROBANTE_CNT.ANO
AND COMPROBANTE_CNTAFECTADOS.TIPO_CPTE_AFECT   = COMPROBANTE_CNT.TIPO
AND COMPROBANTE_CNTAFECTADOS.COMPROBANTE_AFECT = COMPROBANTE_CNT.NUMERO
LEFT JOIN RETENCIONES
ON COMPROBANTE_CNTRETENCION.COMPANIA         = RETENCIONES.COMPANIA
AND COMPROBANTE_CNTRETENCION.ANO             = RETENCIONES.ANO
AND COMPROBANTE_CNTRETENCION.TIPORETENCION   = RETENCIONES.TIPO
AND COMPROBANTE_CNTRETENCION.CODIGORETENCION = RETENCIONES.CODIGO
LEFT JOIN TIPORETENCION
ON COMPROBANTE_CNTRETENCION.TIPORETENCION = TIPORETENCION.CODIGO
WHERE COMPROBANTE_CNTRETENCION.COMPANIA   = $P{PR_COMPANIA}
AND COMPROBANTE_CNTRETENCION.ANO          = $P{PR_ANO}
AND COMPROBANTE_CNTRETENCION.TIPO         = $P{PR_TIPO}
AND COMPROBANTE_CNTRETENCION.NUMERO       = $P{PR_COMPROBANTE}
ORDER BY COMPROBANTE_CNTRETENCION.TIPORETENCION,
  COMPROBANTE_CNTRETENCION.CODIGORETENCION]') CONSULTA, 1 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);
  

MERGE INTO CONSULTAS_SUB FIN USING (SELECT '001744EGRIDSN' INFORME_PADRE, '001529EGRRetencionesIDSN' INFORME_HIJO, 'PR_STRSQL_EGRRETENCIONES' PARAMETRO ,NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (FIN.INFORME_PADRE = INI.INFORME_PADRE AND INI.INFORME_HIJO = FIN.INFORME_HIJO)  WHEN MATCHED THEN  UPDATE SET FIN.PARAMETRO = INI.PARAMETRO , FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME_PADRE,INFORME_HIJO, PARAMETRO,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME_PADRE,INI.INFORME_HIJO, INI.PARAMETRO,INI.CREATED_BY,SYSDATE);	  