SELECT
	DETALLE_COMPROBANTE_PPTAL.COMPANIA COMP,
	DETALLE_COMPROBANTE_PPTAL.ANO ANOCOMP,
	DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE TIPOCOMP,
	DETALLE_COMPROBANTE_PPTAL.COMPROBANTE NUMCOMP,
	DETALLE_COMPROBANTE_PPTAL.CUENTA,
	PLAN_PRESUPUESTAL.NOMBRE || '  /  ' || FUENTE_RECURSOS.NOMBRE NOM,
	SUM(DETALLE_COMPROBANTE_PPTAL.VALOR_DEBITO) DEBITO,
	SUM(DETALLE_COMPROBANTE_PPTAL.VALOR_CREDITO) CREDITO,
	CASE
		WHEN PLAN_PRESUPUESTAL.NATURALEZA = 'C' THEN SUM(DETALLE_COMPROBANTE_PPTAL.VALOR_CREDITO) - SUM(DETALLE_COMPROBANTE_PPTAL.VALOR_DEBITO)
		ELSE SUM(DETALLE_COMPROBANTE_PPTAL.VALOR_DEBITO) - SUM(DETALLE_COMPROBANTE_PPTAL.VALOR_CREDITO)
	END VLR,
	PLAN_PRESUPUESTAL.NATURALEZA,
	DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE_AFECT,
	DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE_AFECT TIPO_CPTE_AFECT1,
	DETALLE_COMPROBANTE_PPTAL.CMPTE_AFECTADO NUMRESERVA,
	NVL(DETALLE_COMPROBANTE_PPTAL_1.CMPTE_AFECTADO, 0) NUMDIS,
	DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE_AFECT,
	DETALLE_COMPROBANTE_PPTAL.AUXILIAR,
	AUXILIAR.NOMBRE
FROM
	DETALLE_COMPROBANTE_PPTAL
INNER JOIN PLAN_PRESUPUESTAL
    ON
	DETALLE_COMPROBANTE_PPTAL.COMPANIA = PLAN_PRESUPUESTAL.COMPANIA
	AND DETALLE_COMPROBANTE_PPTAL.ANO = PLAN_PRESUPUESTAL.ANO
	AND DETALLE_COMPROBANTE_PPTAL.CUENTA = PLAN_PRESUPUESTAL.CODIGO
INNER JOIN AUXILIAR
    ON
	DETALLE_COMPROBANTE_PPTAL.COMPANIA = AUXILIAR.COMPANIA
	AND DETALLE_COMPROBANTE_PPTAL.AUXILIAR = AUXILIAR.CODIGO
	AND DETALLE_COMPROBANTE_PPTAL.ANO = AUXILIAR.ANO
LEFT JOIN FUENTE_RECURSOS
ON
	DETALLE_COMPROBANTE_PPTAL.COMPANIA = FUENTE_RECURSOS.COMPANIA
	AND DETALLE_COMPROBANTE_PPTAL.FUENTE_RECURSO = FUENTE_RECURSOS.CODIGO
	AND DETALLE_COMPROBANTE_PPTAL.ANO = FUENTE_RECURSOS.ANO
LEFT JOIN DETALLE_COMPROBANTE_PPTAL DETALLE_COMPROBANTE_PPTAL_1 
    ON
	DETALLE_COMPROBANTE_PPTAL.COMPANIA = DETALLE_COMPROBANTE_PPTAL_1.COMPANIA
	AND DETALLE_COMPROBANTE_PPTAL.ANO = DETALLE_COMPROBANTE_PPTAL_1.ANO
	AND DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE_AFECT = DETALLE_COMPROBANTE_PPTAL_1.TIPO_CPTE
	AND DETALLE_COMPROBANTE_PPTAL.CMPTE_AFECTADO = DETALLE_COMPROBANTE_PPTAL_1.COMPROBANTE
	AND DETALLE_COMPROBANTE_PPTAL.CONSECUTIVOPPTO = DETALLE_COMPROBANTE_PPTAL_1.CONSECUTIVO
WHERE
	DETALLE_COMPROBANTE_PPTAL.COMPANIA = $P{PR_COMP}
	AND DETALLE_COMPROBANTE_PPTAL.ANO = $P{PR_ANOCOMP}
	AND DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE = $P{PR_TIPOCOMP}
	AND DETALLE_COMPROBANTE_PPTAL.COMPROBANTE BETWEEN $P{PR_NUMCOMP} AND $P{PR_NUMCOMP}
GROUP BY
	DETALLE_COMPROBANTE_PPTAL.COMPANIA ,
	DETALLE_COMPROBANTE_PPTAL.ANO ,
	DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE ,
	DETALLE_COMPROBANTE_PPTAL.COMPROBANTE ,
	DETALLE_COMPROBANTE_PPTAL.CUENTA,
	PLAN_PRESUPUESTAL.NOMBRE || '  /  ' || FUENTE_RECURSOS.NOMBRE ,
	PLAN_PRESUPUESTAL.NATURALEZA,
	DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE_AFECT,
	DETALLE_COMPROBANTE_PPTAL.CMPTE_AFECTADO ,
	DETALLE_COMPROBANTE_PPTAL_1.CMPTE_AFECTADO ,
	DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE_AFECT,
	DETALLE_COMPROBANTE_PPTAL.CMPTE_AFECTADO ,
	DETALLE_COMPROBANTE_PPTAL.AUXILIAR,
	AUXILIAR.NOMBRE