SELECT 
  V_DETALLE_AUXILIAR_CNT.DESCRIPCION DESCRIPCION_COMPROBANTE,
  TO_CHAR(V_DETALLE_AUXILIAR_CNT.FECHA_COMPROBANTE,'DD/MM/YYYY') FECHA_COMPROBANTE,
  V_DETALLE_AUXILIAR_CNT.CODIGO_CUENTA_DET CUENTA,
  V_DETALLE_AUXILIAR_CNT.VLR_DOCUMENTO,
  V_DETALLE_AUXILIAR_CNT.VALOR_CREDITO,
  V_DETALLE_AUXILIAR_CNT.CUENTANOMBRE TOTALNOMBRE,
  V_DETALLE_AUXILIAR_CNT.TIPO_CPTE TIPO,
  V_DETALLE_AUXILIAR_CNT.TEXTO,
  V_DETALLE_AUXILIAR_CNT.TERCERO_COM_TEL TELEFONOS,
  'NO ED_' || V_DETALLE_AUXILIAR_CNT.COMPROBANTE NUMER,
  V_DETALLE_AUXILIAR_CNT.COMPROBANTE_DET COMPROBANTE,
  V_DETALLE_AUXILIAR_CNT.TERCERO_COM_DIR DIRECCION,
TO_CHAR(V_DETALLE_AUXILIAR_CNT.FECHA_VCN_DOC,'DD/MM/YYYY')FECHA_VCN_DOC ,
  V_DETALLE_AUXILIAR_CNT.TERCERO_COM NITTERCERO,
  V_DETALLE_AUXILIAR_CNT.TERCERO_COM_NOM AS NOMBRETERCERO1
FROM V_DETALLE_AUXILIAR_CNT
 WHERE V_DETALLE_AUXILIAR_CNT.COMPANIA  = s$compania$s
   AND V_DETALLE_AUXILIAR_CNT.ANO       = s$ano$s 
   AND V_DETALLE_AUXILIAR_CNT.TIPO_CPTE = 's$tipoCpte$s'
   AND V_DETALLE_AUXILIAR_CNT.COMPROBANTE BETWEEN s$numeroPptoInicial$s AND s$numeroPptoFinal$s
ORDER BY V_DETALLE_AUXILIAR_CNT.CODIGO_CUENTA_DET
