SELECT    
        DETALLE_COMPROBANTE_CNT.COMPANIA,
        DETALLE_COMPROBANTE_CNT.ANO,
        TO_CHAR(DETALLE_COMPROBANTE_CNT.FECHA,'DD/MM/YYYY') FECHA,
        DETALLE_COMPROBANTE_CNT.ANO_AFECT,
        DETALLE_COMPROBANTE_CNT.AUXILIAR,
        DETALLE_COMPROBANTE_CNT.REFERENCIA,
        DETALLE_COMPROBANTE_CNT.FUENTE_RECURSO,
        DETALLE_COMPROBANTE_CNT.COMPROBANTE,
        DETALLE_COMPROBANTE_CNT.VALORTOTAL,
        DETALLE_COMPROBANTE_CNT.VALOR_DEBITO,
        DETALLE_COMPROBANTE_CNT.VALOR_CREDITO,
        DETALLE_COMPROBANTE_CNT.NRO_DOCUMENTO,
        DETALLE_COMPROBANTE_CNT.BASE_GRAVABLE,
        COMPROBANTE_CNT.VLR_BASE,
        COMPROBANTE_CNT.VLR_BASEIVA,
        DETALLE_COMPROBANTE_CNT.CUENTA,
        COMPROBANTE_CNT.DESCRIPCION,
        COMPROBANTE_CNT.NUMERO,
        COMPROBANTE_CNT.TERCERO,
        COMPROBANTE_CNT.VLRAGIRAR,
        COMPROBANTE_CNT.CENTRO_COSTO,
        PLAN_CONTABLE.NOMBRE PNOMBRE, 
        DECODE(DETALLE_COMPROBANTE_CNT.CMPTE_AFECTADO,NULL, COMPROBANTE_CNTAFECTADOS.COMPROBANTE_AFECT,DETALLE_COMPROBANTE_CNT.CMPTE_AFECTADO) AS DOCAFECTADO, 
        DECODE(DETALLE_COMPROBANTE_CNT.TIPO_CPTE_AFECT,NULL,COMPROBANTE_CNTAFECTADOS.TIPO_CPTE_AFECT,DETALLE_COMPROBANTE_CNT.TIPO_CPTE_AFECT) AS TIPOAFECTADO, 
        DECODE(DETALLE_COMPROBANTE_CNT.TIPO_CPTE_AFECT,NULL,COMPROBANTE_CNTAFECTADOS.TIPO_CPTE_AFECT,DETALLE_COMPROBANTE_CNT.TIPO_CPTE_AFECT) ||' 
        '||  DECODE(DETALLE_COMPROBANTE_CNT.CMPTE_AFECTADO,NULL, COMPROBANTE_CNTAFECTADOS.COMPROBANTE_AFECT,DETALLE_COMPROBANTE_CNT.CMPTE_AFECTADO) AS AFECTAA, 
        DECODE(DETALLE_COMPROBANTE_CNT.TERCERO,PCK_DATOS.FC_CONS_TERCERO,' ', TERCERO.NOMBRE) AS NOMBRETERCERO,
        TIPO_COMPROBANTE.CODIGO TNOMBRE, 
        DECODE(DETALLE_COMPROBANTE_CNT.AUXILIAR,PCK_DATOS.FC_CONS_AUXILIAR,' ',AUXILIAR.NOMBRE) AS NOMBREAUXILIAR, 
        DECODE(DETALLE_COMPROBANTE_CNT.CENTRO_COSTO, PCK_DATOS.FC_CONS_CENTRO,' ',CENTRO_COSTO.NOMBRE) AS NOMBRECENTROCOSTO, 
        DECODE(DETALLE_COMPROBANTE_CNT.TERCERO,PCK_DATOS.FC_CONS_TERCERO,' ',DETALLE_COMPROBANTE_CNT.TERCERO) AS CODTERCERO, 
        DECODE(DETALLE_COMPROBANTE_CNT.AUXILIAR,PCK_DATOS.FC_CONS_AUXILIAR,' ',DETALLE_COMPROBANTE_CNT.AUXILIAR) AS CODAUXILIAR, 
        DECODE(DETALLE_COMPROBANTE_CNT.CENTRO_COSTO,PCK_DATOS.FC_CONS_CENTRO,' ',DETALLE_COMPROBANTE_CNT.CENTRO_COSTO) AS CODCENTROCOSTO, 
        DECODE(DETALLE_COMPROBANTE_CNT.NRO_DOCUMENTO,NULL,COMPROBANTE_CNT.NRO_DOCUMENTO,DETALLE_COMPROBANTE_CNT.NRO_DOCUMENTO) AS NODOCUMENTO, 
        DECODE(DETALLE_COMPROBANTE_CNT.DESCRIPCION,NULL,COMPROBANTE_CNT.DESCRIPCION,DETALLE_COMPROBANTE_CNT.DESCRIPCION) AS DESCRIP
FROM DETALLE_COMPROBANTE_CNT 
  INNER JOIN TIPO_COMPROBANTE 
    ON DETALLE_COMPROBANTE_CNT.COMPANIA = TIPO_COMPROBANTE.COMPANIA
    AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE = TIPO_COMPROBANTE.CODIGO
  INNER JOIN AUXILIAR 
    ON DETALLE_COMPROBANTE_CNT.COMPANIA = AUXILIAR.COMPANIA
    AND DETALLE_COMPROBANTE_CNT.ANO = AUXILIAR.ANO
    AND DETALLE_COMPROBANTE_CNT.AUXILIAR = AUXILIAR.CODIGO
  INNER JOIN CENTRO_COSTO 
    ON DETALLE_COMPROBANTE_CNT.COMPANIA = CENTRO_COSTO.COMPANIA
    AND DETALLE_COMPROBANTE_CNT.ANO = CENTRO_COSTO.ANO
    AND DETALLE_COMPROBANTE_CNT.CENTRO_COSTO = CENTRO_COSTO.CODIGO
  INNER JOIN PLAN_CONTABLE 
    ON DETALLE_COMPROBANTE_CNT.COMPANIA = PLAN_CONTABLE.COMPANIA 
    AND DETALLE_COMPROBANTE_CNT.ANO = PLAN_CONTABLE.ANO 
    AND DETALLE_COMPROBANTE_CNT.CUENTA = PLAN_CONTABLE.CODIGO 
  INNER JOIN TERCERO 
    ON DETALLE_COMPROBANTE_CNT.COMPANIA = TERCERO.COMPANIA
    AND DETALLE_COMPROBANTE_CNT.TERCERO = TERCERO.NIT 
    AND DETALLE_COMPROBANTE_CNT.SUCURSAL = TERCERO.SUCURSAL
  INNER JOIN COMPROBANTE_CNT 
    ON DETALLE_COMPROBANTE_CNT.COMPANIA = COMPROBANTE_CNT.COMPANIA 
    AND DETALLE_COMPROBANTE_CNT.ANO = COMPROBANTE_CNT.ANO
    AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE = COMPROBANTE_CNT.TIPO
    AND DETALLE_COMPROBANTE_CNT.COMPROBANTE = COMPROBANTE_CNT.NUMERO
  LEFT JOIN COMPROBANTE_CNTAFECTADOS 
    ON COMPROBANTE_CNTAFECTADOS.COMPANIA = DETALLE_COMPROBANTE_CNT.COMPANIA
    AND COMPROBANTE_CNTAFECTADOS.ANO = DETALLE_COMPROBANTE_CNT.ANO
    AND COMPROBANTE_CNTAFECTADOS.TIPO_CPTE = DETALLE_COMPROBANTE_CNT.TIPO_CPTE
    AND COMPROBANTE_CNTAFECTADOS.COMPROBANTE = DETALLE_COMPROBANTE_CNT.COMPROBANTE
    AND COMPROBANTE_CNTAFECTADOS.ANO_AFECT = DETALLE_COMPROBANTE_CNT.ANO_AFECT
    AND COMPROBANTE_CNTAFECTADOS.TIPO_CPTE_AFECT = DETALLE_COMPROBANTE_CNT.TIPO_CPTE_AFECT
    AND COMPROBANTE_CNTAFECTADOS.COMPROBANTE_AFECT = DETALLE_COMPROBANTE_CNT.CMPTE_AFECTADO
WHERE DETALLE_COMPROBANTE_CNT.COMPANIA = 's$compania$s'
AND DETALLE_COMPROBANTE_CNT.CUENTA BETWEEN 's$cuentaInicial$s' AND 's$cuentaFinal$s' 
AND TO_DATE(TO_CHAR(DETALLE_COMPROBANTE_CNT.FECHA,'DD/MM/YYYY'))  BETWEEN s$fechaInicial$s AND s$fechaFinal$s        
AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE BETWEEN 's$comprobanteInicial$s' AND 's$comprobanteFinal$s'
AND DETALLE_COMPROBANTE_CNT.CENTRO_COSTO BETWEEN 's$centroCostoInicial$s' AND 's$centroCostoFinal$s'
AND DETALLE_COMPROBANTE_CNT.TERCERO BETWEEN  's$terceroInicial$s' AND 's$terceroFinal$s'
ORDER BY    DETALLE_COMPROBANTE_CNT.CUENTA, DETALLE_COMPROBANTE_CNT.FECHA, DETALLE_COMPROBANTE_CNT.COMPROBANTE
