SELECT DISTINCT COMPROBANTE_CNTRETENCION.COMPANIA COMP,
  COMPROBANTE_CNTRETENCION.ANO ANOCOMP,
  COMPROBANTE_CNTRETENCION.TIPO TIPOCOMP,
  COMPROBANTE_CNTRETENCION.NUMERO NUMCOMP,
  RETENCIONES.NOMBRE,
  RETENCIONES.PCT_APLICAR,
  (
  CASE
    WHEN ALEY1450 <> 0
    THEN VALORBASELEY1607
    ELSE COMPROBANTE_CNTRETENCION.VALORBASE
  END) VALORBASE
FROM COMPROBANTE_CNTRETENCION
LEFT JOIN RETENCIONES
ON COMPROBANTE_CNTRETENCION.COMPANIA         = RETENCIONES.COMPANIA
AND COMPROBANTE_CNTRETENCION.ANO             = RETENCIONES.ANO
AND COMPROBANTE_CNTRETENCION.TIPORETENCION   = RETENCIONES.TIPO
AND COMPROBANTE_CNTRETENCION.CODIGORETENCION = RETENCIONES.CODIGO
WHERE COMPROBANTE_CNTRETENCION.ANO          = s$ano$s
AND COMPROBANTE_CNTRETENCION.TIPO         = 's$tipoCpte$s'
AND COMPROBANTE_CNTRETENCION.NUMERO = $P{PR_NUMCOMP}