SELECT DCT0.COMPANIA COMP,
  DCT0.ANO ANOCOMP,
  DCT0.TIPO_CPTE TIPOCOMP,
  DCT1.COMPROBANTE NUMCOMP,
  DCT0.COMPROBANTE,
  DCT0.CUENTA CODIGO_CUENTA,
  CASE WHEN PLAN_CONTABLE.MAN_CEN_CTO NOT IN (0) THEN CENTRO_COSTO.CODIGO || '/' || CENTRO_COSTO.NOMBRE ELSE '' END CENTRO,
  PLAN_CONTABLE.NOMBRE ||
       CASE WHEN  PLAN_CONTABLE.MAN_AUX_TER <>0 THEN '/' || TERCERO.NOMBRE ELSE NULL END  ||
       CASE WHEN  PLAN_CONTABLE.MAN_AUX_GEN <>0 THEN '/' || AUXILIAR.NOMBRE ELSE NULL END ||
       CASE WHEN  PLAN_CONTABLE.MAN_CEN_CTO <>0 THEN '/' || CENTRO_COSTO.NOMBRE ELSE NULL END TOTALNOMBRE,
  DCT0.VALOR_DEBITO,
  DCT0.VALOR_CREDITO
FROM DETALLE_COMPROBANTE_CNT DCT1
INNER JOIN DETALLE_COMPROBANTE_CNT DCT0 
ON DCT1.COMPANIA         = DCT0.COMPANIA
AND DCT1.ANO_AFECT       = DCT0.ANO
AND DCT1.TIPO_CPTE_AFECT = DCT0.TIPO_CPTE
AND DCT1.CMPTE_AFECTADO  = DCT0.COMPROBANTE
LEFT JOIN CENTRO_COSTO
ON DCT0.COMPANIA         = CENTRO_COSTO.COMPANIA
AND DCT0.ANO             = CENTRO_COSTO.ANO
AND DCT0.CENTRO_COSTO    = CENTRO_COSTO.CODIGO
LEFT JOIN PLAN_CONTABLE
ON  DCT0.COMPANIA        = PLAN_CONTABLE.COMPANIA 
AND DCT0.ANO             = PLAN_CONTABLE.ANO 
AND DCT0.CUENTA          = PLAN_CONTABLE.CODIGO
LEFT JOIN AUXILIAR
ON DCT1.COMPANIA         = AUXILIAR.COMPANIA
AND DCT1.ANO             = AUXILIAR.ANO
AND DCT1.AUXILIAR        = AUXILIAR.CODIGO
LEFT JOIN TERCERO
ON DCT1.COMPANIA         = TERCERO.COMPANIA
AND DCT1.TERCERO         = TERCERO.NIT
AND DCT1.SUCURSAL        = TERCERO.SUCURSAL
WHERE DCT1.ANO = s$ano$s
AND DCT1.TIPO_CPTE  = '$P!{PR_TIPO_COMPROBANTE_AFECT}'
AND DCT1.COMPROBANTE BETWEEN '$P!{PR_COMPROBANTE}' AND '$P!{PR_COMPROBANTE}'