SELECT DISTINCT TIPO_COMPROBANTE.NOMBRE,
  COMPROBANTE_CNT.NUMERO,
  TO_CHAR(COMPROBANTE_CNT.FECHA, 'DD/MM/YYYY') FECHA,
  TERCERO_1.NOMBRE NOMBRETERCERO1,
  COMPROBANTE_CNT.TERCERO,
  COMPROBANTE_CNT.NRO_DOCUMENTO,
  TO_CHAR(COMPROBANTE_CNT.FECHA_VCN_DOC, 'DD/MM/YYYY') FECHA_VCN_DOC,
  COMPROBANTE_CNT.VLR_DOCUMENTO,
  COMPROBANTE_CNT.DESCRIPCION,
  COMPROBANTE_CNT.TEXTO,
  DETALLE_COMPROBANTE_CNT.NRO_DOCUMENTO NRO_DOCUMENTO_DCNT,
  DETALLE_COMPROBANTE_CNT.CUENTAPPTAL,
  DETALLE_COMPROBANTE_CNT.CUENTA CODIGO_CUENTA,
  TRIM(PLAN_CONTABLE.NOMBRE)
  ||
  CASE
    WHEN(
      CASE
        WHEN DETALLE_COMPROBANTE_CNT.CENTRO_COSTO = '9999999999'
        THEN ''
        ELSE DETALLE_COMPROBANTE_CNT.CENTRO_COSTO
      END) = ''
    THEN ''
    ELSE ' / '
      || CENTRO_COSTO.NOMBRE
  END
  ||
  CASE
    WHEN(
      CASE
        WHEN DETALLE_COMPROBANTE_CNT.TERCERO ='99999999999'
        THEN ''
        ELSE DETALLE_COMPROBANTE_CNT.TERCERO
      END) = ''
    THEN ''
    ELSE ' / '
      || TERCERO.NOMBRE
  END
  ||
  CASE
    WHEN (
      CASE
        WHEN DETALLE_COMPROBANTE_CNT.AUXILIAR ='9999999999999999'
        THEN ''
        ELSE DETALLE_COMPROBANTE_CNT.AUXILIAR
      END) = ''
    THEN ''
    ELSE ' / '
      || AUXILIAR.NOMBRE
  END TOTALNOMBRE,
  DETALLE_COMPROBANTE_CNT.VALOR_DEBITO,
  DETALLE_COMPROBANTE_CNT.VALOR_CREDITO
FROM DETALLE_COMPROBANTE_CNT
LEFT JOIN TIPO_COMPROBANTE
ON DETALLE_COMPROBANTE_CNT.COMPANIA   = TIPO_COMPROBANTE.COMPANIA
AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE = TIPO_COMPROBANTE.CODIGO
LEFT JOIN COMPROBANTE_CNT
ON DETALLE_COMPROBANTE_CNT.COMPANIA     = COMPROBANTE_CNT.COMPANIA
AND DETALLE_COMPROBANTE_CNT.COMPROBANTE = COMPROBANTE_CNT.NUMERO
AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE   = COMPROBANTE_CNT.TIPO
AND DETALLE_COMPROBANTE_CNT.ANO         = COMPROBANTE_CNT.ANO
LEFT JOIN TERCERO TERCERO_1
ON COMPROBANTE_CNT.COMPANIA  = TERCERO_1.COMPANIA
AND COMPROBANTE_CNT.SUCURSAL = TERCERO_1.SUCURSAL
AND COMPROBANTE_CNT.TERCERO  = TERCERO_1.NIT
LEFT JOIN PLAN_CONTABLE
ON DETALLE_COMPROBANTE_CNT.COMPANIA = PLAN_CONTABLE.COMPANIA
AND DETALLE_COMPROBANTE_CNT.CUENTA  = PLAN_CONTABLE.CODIGO
AND DETALLE_COMPROBANTE_CNT.ANO     = PLAN_CONTABLE.ANO
LEFT JOIN CENTRO_COSTO
ON DETALLE_COMPROBANTE_CNT.COMPANIA      = CENTRO_COSTO.COMPANIA
AND DETALLE_COMPROBANTE_CNT.CENTRO_COSTO = CENTRO_COSTO.CODIGO
LEFT JOIN TERCERO
ON DETALLE_COMPROBANTE_CNT.COMPANIA  = TERCERO.COMPANIA
AND DETALLE_COMPROBANTE_CNT.SUCURSAL = TERCERO.SUCURSAL
AND DETALLE_COMPROBANTE_CNT.TERCERO  = TERCERO.NIT
LEFT JOIN AUXILIAR
ON DETALLE_COMPROBANTE_CNT.COMPANIA   = AUXILIAR.COMPANIA
AND DETALLE_COMPROBANTE_CNT.AUXILIAR  = AUXILIAR.CODIGO
WHERE DETALLE_COMPROBANTE_CNT.ANO     = s$ano$s
AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE = 's$tipoCpte$s'
AND DETALLE_COMPROBANTE_CNT.COMPROBANTE BETWEEN s$numeroPptoInicial$s AND s$numeroPptoFinal$s