MERGE INTO CONSULTAS FIN USING (SELECT '002348EGRALC_CASTILLA' INFORME ,TO_CLOB(q'[SELECT  REPLACE(REPLACE(REPLACE(REPLACE(
                V_DETALLE_AUXILIAR_CNT.FORMATO
               ,'VALOR',V_DETALLE_AUXILIAR_CNT.VLRAGIRAR)
               ,'BENEFICIARIO',V_DETALLE_AUXILIAR_CNT.TERCERO_NOM) 
               ,'MONTOCOMPLETO', PCK_SYSMAN_UTL.FC_VALOR_LETRAS(V_DETALLE_AUXILIAR_CNT.VLRAGIRAR))
               ,'FECHALARGA', replace(to_char(V_DETALLE_AUXILIAR_CNT.FECHA,'DAY,dd / MONTH / yyyy'),'/','de')
              )AS CHEQUE,
	V_DETALLE_AUXILIAR_CNT.COMPANIA,
        V_DETALLE_AUXILIAR_CNT.ANO,
        V_DETALLE_AUXILIAR_CNT.TIPO_CPTE AS TIPO, 
        V_DETALLE_AUXILIAR_CNT.TIPO_COMPROBANTE_NOM, 
        V_DETALLE_AUXILIAR_CNT.COMPROBANTE, 
        V_DETALLE_AUXILIAR_CNT.FECHA, 
        V_DETALLE_AUXILIAR_CNT.TERCERO_COM TERCERO, 
        V_DETALLE_AUXILIAR_CNT.NRO_DOCUMENTO, 
        V_DETALLE_AUXILIAR_CNT.FECHA_VCN_DOC, 
        V_DETALLE_AUXILIAR_CNT.DESCRIPCION, 
        V_DETALLE_AUXILIAR_CNT.TEXTO, 
        NVL(V_DETALLE_AUXILIAR_CNT.VLRAGIRAR,0) AS VLRAGIRAR, 
        V_DETALLE_AUXILIAR_CNT.TERCERO_COM_NOM TERCERO_NOM, 
        V_DETALLE_AUXILIAR_CNT.TERCERO_COM_DIR DIRECCION, 
        (CASE 
            WHEN V_DETALLE_AUXILIAR_CNT.VALOR_DEBITO <> 0
            THEN 'A' || V_DETALLE_AUXILIAR_CNT.CODIGO_CUENTA 
            ELSE 'Z' || V_DETALLE_AUXILIAR_CNT.CODIGO_CUENTA
        END) AS SEC,
        (CASE 
            WHEN V_DETALLE_AUXILIAR_CNT.TERCERO_COM_POS IS NULL 
                OR V_DETALLE_AUXILIAR_CNT.TERCERO_COM_POS = ''
            THEN PCK_SYSMAN_UTL.FC_PAR(V_DETALLE_AUXILIAR_CNT.COMPANIA,
                                      'CODIGO POSTAL',
                                      s$modulo$s,
                                      SYSDATE)
            ELSE V_DETALLE_AUXILIAR_CNT.TERCERO_COM_POS
        END) AS CODIGOPOSTAL,
        V_DETALLE_AUXILIAR_CNT.NRO_DOCUMENTO,
        V_DETALLE_AUXILIAR_CNT.CUENTAPPTAL AS CODIGO_PPTAL, 
        V_DETALLE_AUXILIAR_CNT.CODIGO_CUENTA,
        (TRIM(V_DETALLE_AUXILIAR_CNT.CUENTANOMBRE) || 
        (CASE 
            WHEN V_DETALLE_AUXILIAR_CNT.CENTRO_COSTO_DET = PCK_DATOS.FC_CONS_CENTRO()
            THEN '' 
            ELSE (' / '||V_DETALLE_AUXILIAR_CNT.CENTRO_COSTO_DET_NOM) 
        END) || 
        (CASE 
            WHEN V_DETALLE_AUXILIAR_CNT.TERCERO_DET = PCK_DATOS.FC_CONS_TERCERO() 
            THEN '' 
            ELSE (' / '||V_DETALLE_AUXILIAR_CNT.TERCERO_DET_NOM) 
        END)|| 
        (CASE 
            WHEN V_DETALLE_AUXILIAR_CNT.AUXILIAR_DET = PCK_DATOS.FC_CONS_AUXILIAR()
            THEN '' 
            ELSE (' / '||V_DETALLE_AUXILIAR_CNT.AUXILIAR_DET_NOM) 
        END) || 
        (CASE 
            WHEN V_DETALLE_AUXILIAR_CNT.REFERENCIA_DET = PCK_DATOS.FC_CONS_REFERENCIA() 
            THEN '' 
            ELSE (' / '||V_DETALLE_AUXILIAR_CNT.REFERENCIA_DET_NOM) 
        END)) AS TOTALNOMBRE,
        V_DETALLE_AUXILIAR_CNT.VALOR_DEBITO,
        V_DETALLE_AUXILIAR_CNT.VALOR_CREDITO
FROM V_DET]') || TO_CLOB(q'[ALLE_AUXILIAR_CNT
WHERE V_DETALLE_AUXILIAR_CNT.COMPANIA       = s$compania$s
    AND V_DETALLE_AUXILIAR_CNT.ANO          = s$ano$s 
    AND V_DETALLE_AUXILIAR_CNT.TIPO_CPTE    = 's$tipoCpte$s' 
  AND V_DETALLE_AUXILIAR_CNT.COMPROBANTE BETWEEN 's$numeroPptoInicial$s' AND 's$numeroPptoFinal$s']') CONSULTA, 1 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, 'MROSERO' CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);