MERGE INTO CONSULTAS FIN USING (SELECT '002385SubNotaBancarias' INFORME ,TO_CLOB(q'[SELECT  NRO_DOCUMENTO,VALOR_DEBITO,VALOR_CREDITO,FECHA,TIPO_CPTE,COMPROBANTE 
FROM    DETALLE_COMPROBANTE_CNT    
INNER JOIN TIPO_COMPROBANTE TC
 ON DETALLE_COMPROBANTE_CNT.COMPANIA =  TC.COMPANIA
AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE = TC.CODIGO
WHERE   TC.COMPANIA =  s$compania$s
AND     TC.CLASE_CONTABLE IN (s$strTipos$s)  
AND     CUENTA = 's$cuenta$s'  
s$condicion$s
ORDER BY  
        TIPO_CPTE, COMPROBANTE, CONSECUTIVO]') CONSULTA, 1 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);
        
        MERGE INTO CONSULTAS_SUB FIN USING (SELECT '002383Conciliacionbancaria' INFORME_PADRE, '002385SubNotaBancarias' INFORME_HIJO, 'PR_STRSQL_NOTABANCARIAS' PARAMETRO ,'MROSERO' CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (FIN.INFORME_PADRE = INI.INFORME_PADRE AND INI.INFORME_HIJO = FIN.INFORME_HIJO)  WHEN MATCHED THEN  UPDATE SET FIN.PARAMETRO = INI.PARAMETRO , FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME_PADRE,INFORME_HIJO, PARAMETRO,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME_PADRE,INI.INFORME_HIJO, INI.PARAMETRO,INI.CREATED_BY,SYSDATE);
        