MERGE INTO CONSULTAS FIN USING (SELECT '002477SubBalancePorTerceroResumen' INFORME ,TO_CLOB(q'[SELECT  
      CLASE,
      COMPANIA,
      NOMBRE,  
      CREDITOMES,   
      DEBITOMES, 
      SALDOANTDEBITO, 
      SALDOANTCREDITO, 
      SALDONUEDEBITO, 
      SALDONUECREDITO
   FROM (s$baseTercero$s) RESUMEN 
   WHERE LENGTH(CODIGO) = 1 
        AND  s$mayorizar$s NOT IN (0)
UNION ALL
SELECT  
    RESUMEN.CLASE,
    RESUMEN.COMPANIA, 
    PLAN_CONTABLE.NOMBRE,
    SUM(RESUMEN.CREDITOMES)   CREDITOMES,   
    SUM(RESUMEN.DEBITOMES)   DEBITOMES, 
    SUM(RESUMEN.SALDOANTDEBITO)   SALDOANTDEBITO, 
    SUM(RESUMEN.SALDOANTCREDITO)   SALDOANTCREDITO, 
    SUM(RESUMEN.SALDONUEDEBITO)   SALDONUEDEBITO, 
    SUM(RESUMEN.SALDONUECREDITO)   SALDONUECREDITO
   FROM (s$baseTercero$s) RESUMEN 
  INNER JOIN PLAN_CONTABLE
     ON RESUMEN.COMPANIA = PLAN_CONTABLE.COMPANIA
    AND RESUMEN.CLASE    = PLAN_CONTABLE.CODIGO
 WHERE PLAN_CONTABLE.COMPANIA  = s$compania$s  
   AND PLAN_CONTABLE.ANO       = s$anio$s 
   AND PLAN_CONTABLE.CODIGO  BETWEEN 's$codigoInicial$s' AND 's$codigoFinal$s'  
   AND s$mayorizar$s  IN (0)
 GROUP BY  RESUMEN.CLASE,
           RESUMEN.COMPANIA,
           PLAN_CONTABLE.NOMBRE]') CONSULTA, 1 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);

MERGE INTO CONSULTAS_SUB FIN USING (SELECT '000690BalancePorTercero' INFORME_PADRE, '002477SubBalancePorTerceroResumen' INFORME_HIJO, 'PR_STRSQL_BALANCEPRUEBA' PARAMETRO ,NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (FIN.INFORME_PADRE = INI.INFORME_PADRE AND INI.INFORME_HIJO = FIN.INFORME_HIJO)  WHEN MATCHED THEN  UPDATE SET FIN.PARAMETRO = INI.PARAMETRO , FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME_PADRE,INFORME_HIJO, PARAMETRO,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME_PADRE,INI.INFORME_HIJO, INI.PARAMETRO,INI.CREATED_BY,SYSDATE);