MERGE INTO CONSULTAS FIN USING (SELECT '002582COMCAQM' INFORME ,TO_CLOB(q'[SELECT V_DETALLE_AUXILIAR_CNT.COMPANIA COMP,
  V_DETALLE_AUXILIAR_CNT.ANO ANOCOMP,
  V_DETALLE_AUXILIAR_CNT.COMPROBANTE NUMERO,
  V_DETALLE_AUXILIAR_CNT.FECHA FECHACPCNT,
  V_DETALLE_AUXILIAR_CNT.DESCRIPCION DESCRIPCIONCPCNT,
  V_DETALLE_AUXILIAR_CNT.TEXTO,
  V_DETALLE_AUXILIAR_CNT.FECHA_VCN_DOC,
  V_DETALLE_AUXILIAR_CNT.NRO_DOCUMENTO NRODOCUMENTOCPCNT,
  V_DETALLE_AUXILIAR_CNT.TERCERO_COM TERCEROCPCNT,
  V_DETALLE_AUXILIAR_CNT.COMPROBANTE NUMCOMP,
  V_DETALLE_AUXILIAR_CNT.TIPO_CPTE TIPOCOMP,
 V_DETALLE_AUXILIAR_CNT.VLRAGIRAR  VLRAGIRAR,
  PCK_SYSMAN_UTL.FC_VALOR_LETRAS(V_DETALLE_AUXILIAR_CNT.VLRAGIRAR) VLRAGIRARL,
  V_DETALLE_AUXILIAR_CNT.VLR_DOCUMENTO   VLR_DOCUMENTO ,
  CASE
    WHEN V_DETALLE_AUXILIAR_CNT.CENTRO_COSTO IS NULL
    THEN ' '
    ELSE V_DETALLE_AUXILIAR_CNT.CENTRO_COSTO
  END
  || ' / '
  || V_DETALLE_AUXILIAR_CNT.CENTRO_COSTO_NOM CENTRO,
  V_DETALLE_AUXILIAR_CNT.VALOR_DEBITO VALOR_DEBITO,
  V_DETALLE_AUXILIAR_CNT.VALOR_CREDITO VALOR_CREDITO,
  V_DETALLE_AUXILIAR_CNT.CODIGO_CUENTA  CODIGO_CUENTA,
  V_DETALLE_AUXILIAR_CNT.CUENTANOMBRE TOTALNOMBRE,
  CASE
    WHEN V_DETALLE_AUXILIAR_CNT.VALOR_DEBITO <> 0
    THEN 'A '
      || PCK_SYSMAN_UTL.FC_CODIGO_CNT (V_DETALLE_AUXILIAR_CNT.COMPANIA, V_DETALLE_AUXILIAR_CNT.ANO,V_DETALLE_AUXILIAR_CNT.CUENTA_COMP, V_DETALLE_AUXILIAR_CNT.CENTRO_COSTO, V_DETALLE_AUXILIAR_CNT.TERCERO,V_DETALLE_AUXILIAR_CNT.SUCURSAL, V_DETALLE_AUXILIAR_CNT.AUXILIAR, V_DETALLE_AUXILIAR_CNT.REFERENCIA, V_DETALLE_AUXILIAR_CNT.FUENTE_RECURSOS)
    ELSE 'Z '
      || PCK_SYSMAN_UTL.FC_CODIGO_CNT (V_DETALLE_AUXILIAR_CNT.COMPANIA, V_DETALLE_AUXILIAR_CNT.ANO,V_DETALLE_AUXILIAR_CNT.CUENTA_COMP, V_DETALLE_AUXILIAR_CNT.CENTRO_COSTO, V_DETALLE_AUXILIAR_CNT.TERCERO,V_DETALLE_AUXILIAR_CNT.SUCURSAL, V_DETALLE_AUXILIAR_CNT.AUXILIAR, V_DETALLE_AUXILIAR_CNT.REFERENCIA, V_DETALLE_AUXILIAR_CNT.FUENTE_RECURSOS)
  END SEC,
  V_DETALLE_AUXILIAR_CNT.TERCERO_DET_NOM NOMTERCERO,
  V_DETALLE_AUXILIAR_CNT.DIGITOVERIFICACION,
  V_DETALLE_AUXILIAR_CNT.TERCERO_COM_NOM NOMBRETERCERO,
  V_DETALLE_AUXILIAR_CNT.TERCERO_COM_DIR DIRECCION1,
  V_DETALLE_AUXILIAR_CNT.TERCERO_COM_TEL TELEFONOS1,
  V_DETALLE_AUXILIAR_CNT.TERCERO_COM_TIPOID TIPOID,
  ORDENADOR.NOMBRE NOMBREORD,
  ORDENADOR.CARGO CARGOORD,
V_DETALLE_AUXILIAR_CNT.TIPO_COMPROBANTE_NOM NOMBRETPCOM,
  CASE WHEN COMPROBANTE_CNT.MODIFIED_BY IS NULL THEN
  USUARIO1.NOMBRE1||' '||USUARIO1.NOMBRE2||' '||USUARIO1.APELLIDO1||' '||USUARIO1.APELLIDO2 ELSE
  USUARIO.NOMBRE1||' '||USUARIO.NOMBRE2||' '||USUARIO.APELLIDO1||' '||USUARIO.APELLIDO2 END CREADOR
FROM V_DETALLE_AUXILIAR_CNT
LEFT JOIN ORDENADOR
ON V_DETALLE_AUXILIAR_CNT.COMPANIA          = ORDENADOR.COMPANIA
AND V_DETALLE_AUXILIAR_CNT.ORDENADOR        = ORDENADOR.CEDULA
LEFT JOIN COMPROBANTE_CNT
ON V_DETALLE_AUXILIAR_CNT.COMPANIA          = COMPROBANTE_CNT.COMPANIA
AND V_DETALLE_AUXILIAR_CNT.ANO              = COMPROBANTE_CNT.ANO
AND V_DETALLE_AUXILIAR_CNT.TIPO_CPTE        = COMPROBANTE_CNT.TIPO
AND V_DETALLE_AUXILIAR_CNT.COMPROBANTE      = COMPROB]') || TO_CLOB(q'[ANTE_CNT.NUMERO
LEFT JOIN USUARIO
ON COMPROBANTE_CNT.MODIFIED_BY = USUARIO.CODIGO
LEFT JOIN USUARIO USUARIO1
ON V_DETALLE_AUXILIAR_CNT.CREATED_BY = USUARIO1.CODIGO
WHERE V_DETALLE_AUXILIAR_CNT.COMPANIA    = s$compania$s
  AND V_DETALLE_AUXILIAR_CNT.ANO         = s$ano$s
  AND V_DETALLE_AUXILIAR_CNT.TIPO_CPTE   = 's$tipoCpte$s'
  AND V_DETALLE_AUXILIAR_CNT.COMPROBANTE BETWEEN s$numeroPptoInicial$s AND s$numeroPptoFinal$s]') CONSULTA, 1 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);

MERGE INTO CONSULTAS_SUB FIN USING (SELECT '002582COMCAQM' INFORME_PADRE, '001891SubCOMCAQ' INFORME_HIJO, 'PR_STRSQL_INFORMESUBCOM_DC' PARAMETRO ,NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (FIN.INFORME_PADRE = INI.INFORME_PADRE AND INI.INFORME_HIJO = FIN.INFORME_HIJO)  WHEN MATCHED THEN  UPDATE SET FIN.PARAMETRO = INI.PARAMETRO , FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME_PADRE,INFORME_HIJO, PARAMETRO,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME_PADRE,INI.INFORME_HIJO, INI.PARAMETRO,INI.CREATED_BY,SYSDATE);

MERGE INTO CONSULTAS_SUB FIN USING (SELECT '002582COMCAQM' INFORME_PADRE, '001892SubCOM' INFORME_HIJO, 'PR_STRSQL_COMRETENCIONES' PARAMETRO ,NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (FIN.INFORME_PADRE = INI.INFORME_PADRE AND INI.INFORME_HIJO = FIN.INFORME_HIJO)  WHEN MATCHED THEN  UPDATE SET FIN.PARAMETRO = INI.PARAMETRO , FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME_PADRE,INFORME_HIJO, PARAMETRO,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME_PADRE,INI.INFORME_HIJO, INI.PARAMETRO,INI.CREATED_BY,SYSDATE);