MERGE INTO CONSULTAS FIN USING (SELECT '002575COM_SINCHI_Sub' INFORME ,TO_CLOB(q'[SELECT  DETALLE_COMPROBANTE_PPTAL.COMPROBANTE  NUMCOMP,
        DETALLE_COMPROBANTE_PPTAL.CUENTA,
        DETALLE_COMPROBANTE_PPTAL.CENTRO_COSTO,
        DETALLE_COMPROBANTE_PPTAL.REFERENCIA AS REFERENCIADO,
        NVL(DETALLE_COMPROBANTE_PPTAL_1.CMPTE_AFECTADO,0) NUMDISP, 
        DETALLE_COMPROBANTE_PPTAL.CMPTE_AFECTADO NUMRESERVA,
        CASE
            WHEN DETALLE_COMPROBANTE_PPTAL.FUENTE_RECURSO = '99999999999999999999' THEN ''
            ELSE DETALLE_COMPROBANTE_PPTAL.FUENTE_RECURSO
        END AS ACTIVIDAD,
         CASE
                WHEN DETALLE_COMPROBANTE_PPTAL.AUXILIAR = '99999999999999999999' THEN ''
                ELSE DETALLE_COMPROBANTE_PPTAL.AUXILIAR
        END AS RESPONSABLE,
        PLAN_PRESUPUESTAL.NOMBRE,
        SUM(CASE WHEN DETALLE_COMPROBANTE_PPTAL.VALOR_DEBITO IN(0)
                 THEN DETALLE_COMPROBANTE_PPTAL.VALOR_CREDITO - DETALLE_COMPROBANTE_PPTAL.VALOR_DEBITO
                 ELSE DETALLE_COMPROBANTE_PPTAL.VALOR_DEBITO - DETALLE_COMPROBANTE_PPTAL.VALOR_CREDITO
            END) VALOR
FROM DETALLE_COMPROBANTE_PPTAL
  INNER JOIN V_PLAN_PRESUPUESTAL PLAN_PRESUPUESTAL
    ON DETALLE_COMPROBANTE_PPTAL.COMPANIA           = PLAN_PRESUPUESTAL.COMPANIA
    AND DETALLE_COMPROBANTE_PPTAL.ANO               = PLAN_PRESUPUESTAL.ANO
    AND DETALLE_COMPROBANTE_PPTAL.ID                 = PLAN_PRESUPUESTAL.ID
  INNER JOIN AUXILIAR
    ON DETALLE_COMPROBANTE_PPTAL.COMPANIA   = AUXILIAR.COMPANIA
    AND DETALLE_COMPROBANTE_PPTAL.ANO       = AUXILIAR.ANO
    AND DETALLE_COMPROBANTE_PPTAL.AUXILIAR  = AUXILIAR.CODIGO
     LEFT JOIN DETALLE_COMPROBANTE_PPTAL  DETALLE_COMPROBANTE_PPTAL_1 
    ON DETALLE_COMPROBANTE_PPTAL.COMPANIA        = DETALLE_COMPROBANTE_PPTAL_1.COMPANIA
    AND DETALLE_COMPROBANTE_PPTAL.ANO             = DETALLE_COMPROBANTE_PPTAL_1.ANO
    AND DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE_AFECT = DETALLE_COMPROBANTE_PPTAL_1.TIPO_CPTE
    AND DETALLE_COMPROBANTE_PPTAL.CMPTE_AFECTADO  = DETALLE_COMPROBANTE_PPTAL_1.COMPROBANTE 
    AND DETALLE_COMPROBANTE_PPTAL.CONSECUTIVOPPTO = DETALLE_COMPROBANTE_PPTAL_1.CONSECUTIVO  
WHERE DETALLE_COMPROBANTE_PPTAL.COMPANIA    = $P{PR_COMPANIA}
  AND DETALLE_COMPROBANTE_PPTAL.ANO         = $P{PR_ANO}
  AND DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE   = $P{PR_TIPO}
  AND DETALLE_COMPROBANTE_PPTAL.COMPROBANTE BETWEEN $P{PR_NUMERO} AND $P{PR_NUMERO}
GROUP BY
  DETALLE_COMPROBANTE_PPTAL.COMPANIA,
  DETALLE_COMPROBANTE_PPTAL.COMPROBANTE,
  PLAN_PRESUPUESTAL.NOMBRE,
  DETALLE_COMPROBANTE_PPTAL.CENTRO_COSTO,
  DETALLE_COMPROBANTE_PPTAL.REFERENCIA,
  DETALLE_COMPROBANTE_PPTAL.FUENTE_RECURSO,
  DETALLE_COMPROBANTE_PPTAL.AUXILIAR,
  DETALLE_COMPROBANTE_PPTAL_1.CMPTE_AFECTADO,
  DETALLE_COMPROBANTE_PPTAL.CMPTE_AFECTADO,
  DETALLE_COMPROBANTE_PPTAL.CUENTA]') CONSULTA, 1 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, 'jdsalcedo' CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);
  
  MERGE INTO CONSULTAS_SUB FIN USING (SELECT '002574COM_SINCHI' INFORME_PADRE, '002575COM_SINCHI_Sub' INFORME_HIJO, 'PR_STRSQL_COM_SINCHI_SUB' PARAMETRO ,'jdsalcedo' CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (FIN.INFORME_PADRE = INI.INFORME_PADRE AND INI.INFORME_HIJO = FIN.INFORME_HIJO)  WHEN MATCHED THEN  UPDATE SET FIN.PARAMETRO = INI.PARAMETRO , FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME_PADRE,INFORME_HIJO, PARAMETRO,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME_PADRE,INI.INFORME_HIJO, INI.PARAMETRO,INI.CREATED_BY,SYSDATE);