MERGE INTO CONSULTAS FIN USING (SELECT '002580BalancePorCentroCostoM' INFORME ,TO_CLOB(q'[SELECT COMPANIA, ANO, CLASE, CODIGO, NOMBRE, NOMBRE_TERCERO, NOMBRE_CENTRO_COSTO, CENTRO_COSTO, AUXILIAR, FUENTE_RECURSO, 
TERCERO, REFERENCIA, SALDOANTDEBITO, SALDOANTCREDITO, DEBITOMES, CREDITOMES, SALDONUEDEBITO, SALDONUECREDITO
FROM (
SELECT SALDO.COMPANIA,
SALDO.ANO,
SUBSTR(PLAN.CODIGO,1,1) CLASE,
PLAN.CODIGO,
PLAN.NOMBRE,
CASE WHEN   PLAN.MAN_AUX_TER  IN (0)
THEN '' ELSE NOMBRE_TERCERO END NOMBRE_TERCERO,
CASE WHEN   PLAN.MAN_CEN_CTO IN (0)
THEN '' ELSE NOMBRE_CENTRO_COSTO END NOMBRE_CENTRO_COSTO ,
CASE WHEN PLAN.MAN_CEN_CTO NOT IN (0) THEN SALDO.CENTRO_COSTO ELSE ' ' END CENTRO_COSTO,
'' AUXILIAR,
'' FUENTE_RECURSO,
CASE WHEN PLAN.MAN_AUX_TER NOT IN (0) THEN SALDO.TERCERO ELSE ' ' END TERCERO,
'' REFERENCIA,
SUM(SALDO.SALDOANTDEBITO)SALDOANTDEBITO,
SUM(SALDO.SALDOANTCREDITO)SALDOANTCREDITO,
SUM(SALDO.DEBITOMES)DEBITOMES,
SUM(SALDO.CREDITOMES)CREDITOMES,
SUM(SALDO.SALDONUEDEBITO)SALDONUEDEBITO,
SUM(SALDO.SALDONUECREDITO)SALDONUECREDITO
FROM PLAN_CONTABLE PLAN INNER JOIN (
SELECT V_PLAN_CONTABLE.COMPANIA,
V_PLAN_CONTABLE.CENTRO_COSTO,
V_PLAN_CONTABLE.AUXILIAR,
V_PLAN_CONTABLE.FUENTE_RECURSO,
V_PLAN_CONTABLE.TERCERO,
V_PLAN_CONTABLE.REFERENCIA,
TERCERO.NOMBRE NOMBRE_TERCERO,
CENTRO_COSTO.NOMBRE  NOMBRE_CENTRO_COSTO,
V_PLAN_CONTABLE.ANO,
V_PLAN_CONTABLE.CODIGO,
V_PLAN_CONTABLE.ID,
CASE WHEN V_PLAN_CONTABLE.NATURALEZA='D' AND V_PLAN_CONTABLE.SALDOs$mesAnterior$s >=0 THEN V_PLAN_CONTABLE.SALDOs$mesAnterior$s ELSE 0 END +
CASE WHEN V_PLAN_CONTABLE.NATURALEZA='C' AND V_PLAN_CONTABLE.SALDOs$mesAnterior$s <0 THEN -V_PLAN_CONTABLE.SALDOs$mesAnterior$s ELSE 0 END  AS SALDOANTDEBITO,
CASE WHEN V_PLAN_CONTABLE.NATURALEZA='C' AND V_PLAN_CONTABLE.SALDOs$mesAnterior$s >=0 THEN V_PLAN_CONTABLE.SALDOs$mesAnterior$s ELSE 0 END  +
CASE WHEN V_PLAN_CONTABLE.NATURALEZA='D' AND V_PLAN_CONTABLE.SALDOs$mesAnterior$s <0 THEN -V_PLAN_CONTABLE.SALDOs$mesAnterior$s ELSE 0 END  AS SALDOANTCREDITO,
V_PLAN_CONTABLE.DEBITOs$mesActual$s   AS DEBITOMES,
V_PLAN_CONTABLE.CREDITOs$mesActual$s  AS CREDITOMES,
CASE WHEN V_PLAN_CONTABLE.NATURALEZA='D' AND V_PLAN_CONTABLE.SALDOs$mesActual$s >=0 THEN V_PLAN_CONTABLE.SALDOs$mesActual$s ELSE 0 END +
CASE WHEN V_PLAN_CONTABLE.NATURALEZA='C' AND V_PLAN_CONTABLE.SALDOs$mesActual$s <0 THEN -V_PLAN_CONTABLE.SALDOs$mesActual$s ELSE 0 END  AS SALDONUEDEBITO,
CASE WHEN V_PLAN_CONTABLE.NATURALEZA='C' AND V_PLAN_CONTABLE.SALDOs$mesActual$s >=0 THEN V_PLAN_CONTABLE.SALDOs$mesActual$s ELSE 0 END +
CASE WHEN V_PLAN_CONTABLE.NATURALEZA='D' AND V_PLAN_CONTABLE.SALDOs$mesActual$s <0 THEN -V_PLAN_CONTABLE.SALDOs$mesActual$s ELSE 0 END  AS SALDONUECREDITO,
V_PLAN_CONTABLE.NOMBRE
FROM V_PLAN_CONTABLE
LEFT JOIN TERCERO
      ON V_PLAN_CONTABLE.COMPANIA = TERCERO.COMPANIA
      AND V_PLAN_CONTABLE.TERCERO = TERCERO.NIT
      AND V_PLAN_CONTABLE.SUCURSAL = TERCERO.SUCURSAL

LEFT JOIN CENTRO_COSTO
       ON V_PLAN_CONTABLE.COMPANIA = CENTRO_COSTO.COMPANIA
      AND V_PLAN_CONTABLE.ANO = CENTRO_COSTO.ANO
      AND V_PLAN_CONTABLE.CENTRO_COSTO =  CENTRO_COSTO]') || TO_CLOB(q'[.CODIGO
WHERE V_PLAN_CONTABLE.COMPANIA = s$compania$s 
AND V_PLAN_CONTABLE.ANO= s$anio$s
AND V_PLAN_CONTABLE.CODIGO BETWEEN 's$codigoInicial$s' AND 's$codigoFinal$s'  
AND V_PLAN_CONTABLE.MOVIMIENTO NOT IN(0) 
AND V_PLAN_CONTABLE.CENTRO_COSTO BETWEEN 's$centroInicial$s' AND 's$centroFinal$s'  
AND SUBSTR(V_PLAN_CONTABLE.CODIGO,1,1) NOT IN('0')
ORDER BY V_PLAN_CONTABLE.COMPANIA,
 V_PLAN_CONTABLE.ANO,
 V_PLAN_CONTABLE.ID) SALDO  
 ON PLAN.COMPANIA = SALDO.COMPANIA
AND PLAN.ANO      = SALDO.ANO     
AND PLAN.CODIGO   = CASE WHEN 0 <> s$condicionMayorizar$s THEN SUBSTR(SALDO.CODIGO, 1, LENGTH(PLAN.CODIGO)) ELSE SALDO.CODIGO END
GROUP BY SALDO.COMPANIA,
CASE WHEN PLAN.MAN_CEN_CTO NOT IN (0) THEN SALDO.CENTRO_COSTO ELSE ' ' END,
CASE WHEN PLAN.MAN_AUX_TER NOT IN (0) THEN SALDO.TERCERO ELSE ' ' END,
SALDO.ANO,
PLAN.CODIGO,
PLAN.NOMBRE,
CASE WHEN   PLAN.MAN_AUX_TER  IN (0)
THEN '' ELSE SALDO.NOMBRE_TERCERO END,
CASE WHEN   PLAN.MAN_CEN_CTO IN (0)
THEN '' ELSE NOMBRE_CENTRO_COSTO END

UNION ALL

SELECT SALDO.COMPANIA,
SALDO.ANO,
SUBSTR(PLAN.CODIGO,1,1) CLASE,
PLAN.CODIGO,
PLAN.NOMBRE,
'' NOMBRE_TERCERO,
CASE WHEN   PLAN.MAN_CEN_CTO IN (0)
THEN '' ELSE NOMBRE_CENTRO_COSTO END NOMBRE_CENTRO_COSTO ,
CASE WHEN PLAN.MAN_CEN_CTO NOT IN (0) THEN SALDO.CENTRO_COSTO ELSE ' ' END CENTRO_COSTO,
'' AUXILIAR,
'' FUENTE_RECURSO,
'' TERCERO,
'' REFERENCIA,
SUM(SALDO.SALDOANTDEBITO)SALDOANTDEBITO,
SUM(SALDO.SALDOANTCREDITO)SALDOANTCREDITO,
SUM(SALDO.DEBITOMES)DEBITOMES,
SUM(SALDO.CREDITOMES)CREDITOMES,
SUM(SALDO.SALDONUEDEBITO)SALDONUEDEBITO,
SUM(SALDO.SALDONUECREDITO)SALDONUECREDITO
FROM PLAN_CONTABLE PLAN INNER JOIN (
SELECT V_PLAN_CONTABLE.COMPANIA,
CENTRO_COSTO_P.CODIGO CENTRO_COSTO,
CENTRO_COSTO_P.NOMBRE  NOMBRE_CENTRO_COSTO,
V_PLAN_CONTABLE.ANO,
V_PLAN_CONTABLE.CODIGO,
V_PLAN_CONTABLE.ID,
CASE WHEN V_PLAN_CONTABLE.NATURALEZA='D' AND V_PLAN_CONTABLE.SALDOs$mesAnterior$s >=0 THEN V_PLAN_CONTABLE.SALDOs$mesAnterior$s ELSE 0 END +
CASE WHEN V_PLAN_CONTABLE.NATURALEZA='C' AND V_PLAN_CONTABLE.SALDOs$mesAnterior$s <0 THEN -V_PLAN_CONTABLE.SALDOs$mesAnterior$s ELSE 0 END  AS SALDOANTDEBITO,
CASE WHEN V_PLAN_CONTABLE.NATURALEZA='C' AND V_PLAN_CONTABLE.SALDOs$mesAnterior$s >=0 THEN V_PLAN_CONTABLE.SALDOs$mesAnterior$s ELSE 0 END  +
CASE WHEN V_PLAN_CONTABLE.NATURALEZA='D' AND V_PLAN_CONTABLE.SALDOs$mesAnterior$s <0 THEN -V_PLAN_CONTABLE.SALDOs$mesAnterior$s ELSE 0 END  AS SALDOANTCREDITO,
V_PLAN_CONTABLE.DEBITOs$mesActual$s   AS DEBITOMES,
V_PLAN_CONTABLE.CREDITOs$mesActual$s  AS CREDITOMES,
CASE WHEN V_PLAN_CONTABLE.NATURALEZA='D' AND V_PLAN_CONTABLE.SALDOs$mesActual$s >=0 THEN V_PLAN_CONTABLE.SALDOs$mesActual$s ELSE 0 END +
CASE WHEN V_PLAN_CONTABLE.NATURALEZA='C' AND V_PLAN_CONTABLE.SALDOs$mesActual$s <0 THEN -V_PLAN_CONTABLE.SALDOs$mesActual$s ELSE 0 END  AS SALDONUEDEBITO,
CASE WHEN V_PLAN_CONTABLE.NATURALEZA='C' AND V_PLAN_CONTABLE.SALDOs$mesActual$s >=0 THEN V_PLAN_CONTABLE.SALDOs$mesActual$s ELSE 0 END +
CASE WHEN V_PLAN_CONTABLE.NATURALEZA='D' AND V_PLAN_CONTABLE.SA]') || TO_CLOB(q'[LDOs$mesActual$s <0 THEN -V_PLAN_CONTABLE.SALDOs$mesActual$s ELSE 0 END  AS SALDONUECREDITO,
V_PLAN_CONTABLE.NOMBRE
FROM V_PLAN_CONTABLE
LEFT JOIN TERCERO
      ON V_PLAN_CONTABLE.COMPANIA = TERCERO.COMPANIA
      AND V_PLAN_CONTABLE.TERCERO = TERCERO.NIT
      AND V_PLAN_CONTABLE.SUCURSAL = TERCERO.SUCURSAL

LEFT JOIN CENTRO_COSTO
       ON V_PLAN_CONTABLE.COMPANIA = CENTRO_COSTO.COMPANIA
      AND V_PLAN_CONTABLE.ANO = CENTRO_COSTO.ANO
      AND V_PLAN_CONTABLE.CENTRO_COSTO =  CENTRO_COSTO.CODIGO

LEFT JOIN (SELECT COMPANIA, ANO, CODIGO, NOMBRE 
FROM CENTRO_COSTO
WHERE MOVIMIENTO = 0
AND ANO = s$anio$s) CENTRO_COSTO_P
ON V_PLAN_CONTABLE.COMPANIA = CENTRO_COSTO.COMPANIA
      AND V_PLAN_CONTABLE.ANO = CENTRO_COSTO.ANO
      AND SUBSTR(V_PLAN_CONTABLE.CENTRO_COSTO, 1, LENGTH(CENTRO_COSTO_P.CODIGO)) = CENTRO_COSTO_P.CODIGO 

WHERE V_PLAN_CONTABLE.COMPANIA = s$compania$s 
AND V_PLAN_CONTABLE.ANO= s$anio$s
AND V_PLAN_CONTABLE.CODIGO BETWEEN 's$codigoInicial$s' AND 's$codigoFinal$s'  
AND V_PLAN_CONTABLE.MOVIMIENTO NOT IN(0) 
AND V_PLAN_CONTABLE.CENTRO_COSTO BETWEEN 's$centroInicial$s' AND 's$centroFinal$s'  
AND SUBSTR(V_PLAN_CONTABLE.CODIGO,1,1) NOT IN('0')
ORDER BY V_PLAN_CONTABLE.COMPANIA,
 V_PLAN_CONTABLE.ANO,
 V_PLAN_CONTABLE.ID

 ) SALDO  
 ON PLAN.COMPANIA = SALDO.COMPANIA
AND PLAN.ANO      = SALDO.ANO     
AND PLAN.CODIGO   = SALDO.CODIGO
WHERE PLAN.MAN_CEN_CTO NOT IN (0)
GROUP BY SALDO.COMPANIA,
CASE WHEN PLAN.MAN_CEN_CTO NOT IN (0) THEN SALDO.CENTRO_COSTO ELSE ' ' END,
SALDO.ANO,
PLAN.CODIGO,
PLAN.NOMBRE,
CASE WHEN   PLAN.MAN_CEN_CTO IN (0)
THEN '' ELSE NOMBRE_CENTRO_COSTO END

UNION ALL

SELECT SALDO.COMPANIA,
SALDO.ANO,
SUBSTR(PLAN.CODIGO,1,1) CLASE,
PLAN.CODIGO,
PLAN.NOMBRE,
' ' NOMBRE_TERCERO,
' ' NOMBRE_CENTRO_COSTO ,
' ' CENTRO_COSTO,
' ' AUXILIAR,
' ' FUENTE_RECURSO,
' ' TERCERO,
' ' REFERENCIA,
SUM(SALDO.SALDOANTDEBITO)SALDOANTDEBITO,
SUM(SALDO.SALDOANTCREDITO)SALDOANTCREDITO,
SUM(SALDO.DEBITOMES)DEBITOMES,
SUM(SALDO.CREDITOMES)CREDITOMES,
SUM(SALDO.SALDONUEDEBITO)SALDONUEDEBITO,
SUM(SALDO.SALDONUECREDITO)SALDONUECREDITO
FROM PLAN_CONTABLE PLAN INNER JOIN (
SELECT V_PLAN_CONTABLE.COMPANIA,
CENTRO_COSTO_P.CODIGO CENTRO_COSTO,
CENTRO_COSTO_P.NOMBRE  NOMBRE_CENTRO_COSTO,
V_PLAN_CONTABLE.ANO,
V_PLAN_CONTABLE.CODIGO,
V_PLAN_CONTABLE.ID,
CASE WHEN V_PLAN_CONTABLE.NATURALEZA='D' AND V_PLAN_CONTABLE.SALDOs$mesAnterior$s >=0 THEN V_PLAN_CONTABLE.SALDOs$mesAnterior$s ELSE 0 END +
CASE WHEN V_PLAN_CONTABLE.NATURALEZA='C' AND V_PLAN_CONTABLE.SALDOs$mesAnterior$s <0 THEN -V_PLAN_CONTABLE.SALDOs$mesAnterior$s ELSE 0 END  AS SALDOANTDEBITO,
CASE WHEN V_PLAN_CONTABLE.NATURALEZA='C' AND V_PLAN_CONTABLE.SALDOs$mesAnterior$s >=0 THEN V_PLAN_CONTABLE.SALDOs$mesAnterior$s ELSE 0 END  +
CASE WHEN V_PLAN_CONTABLE.NATURALEZA='D' AND V_PLAN_CONTABLE.SALDOs$mesAnterior$s <0 THEN -V_PLAN_CONTABLE.SALDOs$mesAnterior$s ELSE 0 END  AS SALDOANTCREDITO,
V_PLAN_CONTABLE.DEBITOs$mesActual$s   AS DEBITOMES,
V_PLAN_CONTABLE.CREDITOs$mesActual$s  AS CREDITOMES,
CASE W]') || TO_CLOB(q'[HEN V_PLAN_CONTABLE.NATURALEZA='D' AND V_PLAN_CONTABLE.SALDOs$mesActual$s >=0 THEN V_PLAN_CONTABLE.SALDOs$mesActual$s ELSE 0 END +
CASE WHEN V_PLAN_CONTABLE.NATURALEZA='C' AND V_PLAN_CONTABLE.SALDOs$mesActual$s <0 THEN -V_PLAN_CONTABLE.SALDOs$mesActual$s ELSE 0 END  AS SALDONUEDEBITO,
CASE WHEN V_PLAN_CONTABLE.NATURALEZA='C' AND V_PLAN_CONTABLE.SALDOs$mesActual$s >=0 THEN V_PLAN_CONTABLE.SALDOs$mesActual$s ELSE 0 END +
CASE WHEN V_PLAN_CONTABLE.NATURALEZA='D' AND V_PLAN_CONTABLE.SALDOs$mesActual$s <0 THEN -V_PLAN_CONTABLE.SALDOs$mesActual$s ELSE 0 END  AS SALDONUECREDITO,
V_PLAN_CONTABLE.NOMBRE
FROM V_PLAN_CONTABLE
LEFT JOIN TERCERO
      ON V_PLAN_CONTABLE.COMPANIA = TERCERO.COMPANIA
      AND V_PLAN_CONTABLE.TERCERO = TERCERO.NIT
      AND V_PLAN_CONTABLE.SUCURSAL = TERCERO.SUCURSAL

LEFT JOIN CENTRO_COSTO
       ON V_PLAN_CONTABLE.COMPANIA = CENTRO_COSTO.COMPANIA
      AND V_PLAN_CONTABLE.ANO = CENTRO_COSTO.ANO
      AND V_PLAN_CONTABLE.CENTRO_COSTO =  CENTRO_COSTO.CODIGO

LEFT JOIN (SELECT COMPANIA, ANO, CODIGO, NOMBRE 
FROM CENTRO_COSTO
WHERE MOVIMIENTO = 0
AND ANO = 2024) CENTRO_COSTO_P
ON V_PLAN_CONTABLE.COMPANIA = CENTRO_COSTO.COMPANIA
      AND V_PLAN_CONTABLE.ANO = CENTRO_COSTO.ANO
      AND SUBSTR(V_PLAN_CONTABLE.CENTRO_COSTO, 1, LENGTH(CENTRO_COSTO_P.CODIGO)) = CENTRO_COSTO_P.CODIGO 

WHERE V_PLAN_CONTABLE.COMPANIA = s$compania$s 
AND V_PLAN_CONTABLE.ANO= s$anio$s
AND V_PLAN_CONTABLE.CODIGO BETWEEN 's$codigoInicial$s' AND 's$codigoFinal$s'  
AND V_PLAN_CONTABLE.MOVIMIENTO IN(0) 
AND SUBSTR(V_PLAN_CONTABLE.CODIGO,1,1) NOT IN('0')
ORDER BY V_PLAN_CONTABLE.COMPANIA,
 V_PLAN_CONTABLE.ANO,
 V_PLAN_CONTABLE.ID

 ) SALDO  
 ON PLAN.COMPANIA = SALDO.COMPANIA
AND PLAN.ANO      = SALDO.ANO     
AND PLAN.CODIGO   = SALDO.CODIGO
WHERE PLAN.MAN_CEN_CTO + PLAN.MAN_AUX_TER NOT IN (0)
GROUP BY SALDO.COMPANIA,
SALDO.ANO,
PLAN.CODIGO,
PLAN.NOMBRE,
CASE WHEN   PLAN.MAN_CEN_CTO IN (0)
THEN '' ELSE NOMBRE_CENTRO_COSTO END

)
ORDER BY CODIGO, CENTRO_COSTO, TERCERO]') CONSULTA, 1 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);

MERGE INTO CONSULTAS_SUB FIN USING (SELECT '002580BalancePorCentroCostoM' INFORME_PADRE, '000688SubBalancePorCentroCosto' INFORME_HIJO, 'PR_STRSQL_BALANCEPRUEBA' PARAMETRO ,NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (FIN.INFORME_PADRE = INI.INFORME_PADRE AND INI.INFORME_HIJO = FIN.INFORME_HIJO)  WHEN MATCHED THEN  UPDATE SET FIN.PARAMETRO = INI.PARAMETRO , FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME_PADRE,INFORME_HIJO, PARAMETRO,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME_PADRE,INI.INFORME_HIJO, INI.PARAMETRO,INI.CREATED_BY,SYSDATE);

