MERGE INTO CONSULTAS FIN USING (SELECT '002573InformeDeRetencionesLis_SINCHI' INFORME ,TO_CLOB(q'[SELECT 	DETALLE_COMPROBANTE_CNT.COMPANIA COMPANIA,
        DETALLE_COMPROBANTE_CNT.ANO ANO,  
        DETALLE_COMPROBANTE_CNT.CUENTA,  
        PLAN_CONTABLE.NOMBRE NOMBRECUENTA,  
        DETALLE_COMPROBANTE_CNT.TERCERO TERCERO,  
        TERCERO.NOMBRE NOMBRETERCERO,  
        TERCERO.DIRECCION ,  
        TERCERO.TELEFONOS TELEFONO,  
        CIUDAD.NOMBRE CIUDAD,  
        SUM(DETALLE_COMPROBANTE_CNT.BASE_GRAVABLE) BASERETENCION,  
        SUM(CASE WHEN CLASE_CONTABLE ='E' THEN VALOR_CREDITO ELSE VALOR_CREDITO - VALOR_DEBITO END) VALORRETENCION,
        PLAN_CONTABLE.CLASECUENTA, 
        NVL(MIN(RETENCIONES.PCT_APLICAR) KEEP (DENSE_RANK FIRST ORDER BY ROWNUM),0) PORCRETENCION,  
        TERCERO.DIRECCION||' '||CIUDAD.NOMBRE DIRECCIONYCIUDAD,
        DETALLE_COMPROBANTE_CNT.REFERENCIA,
        REFERENCIA.NOMBRE NOMBRE_REFERENCIA,
        DETALLE_COMPROBANTE_CNT.BANCO_RETENCION CTA_BANCARIA,
        PLAN_BANCO.NOMBRE NOMBRE_BANCO
FROM DETALLE_COMPROBANTE_CNT  
  LEFT JOIN PLAN_CONTABLE  
    ON  DETALLE_COMPROBANTE_CNT.COMPANIA  = PLAN_CONTABLE.COMPANIA  
    AND DETALLE_COMPROBANTE_CNT.ANO       = PLAN_CONTABLE.ANO  
    AND DETALLE_COMPROBANTE_CNT.CUENTA    = PLAN_CONTABLE.CODIGO  
  LEFT JOIN TERCERO  
   ON  DETALLE_COMPROBANTE_CNT.COMPANIA = TERCERO.COMPANIA  
   AND DETALLE_COMPROBANTE_CNT.TERCERO  = TERCERO.NIT  
   AND DETALLE_COMPROBANTE_CNT.SUCURSAL = TERCERO.SUCURSAL  
  LEFT JOIN CIUDAD  
   ON  TERCERO.PAIS         = CIUDAD.PAIS  
   AND TERCERO.DEPARTAMENTO = CIUDAD.DEPARTAMENTO  
   AND TERCERO.CIUDAD       = CIUDAD.CODIGO  
  LEFT JOIN TIPO_COMPROBANTE  
   ON  DETALLE_COMPROBANTE_CNT.COMPANIA  = TIPO_COMPROBANTE.COMPANIA   
   AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE = TIPO_COMPROBANTE.CODIGO    
  LEFT JOIN RETENCIONES  
    ON  DETALLE_COMPROBANTE_CNT.COMPANIA = RETENCIONES.COMPANIA  
    AND DETALLE_COMPROBANTE_CNT.ANO      = RETENCIONES.ANO  
    AND DETALLE_COMPROBANTE_CNT.CUENTA   = RETENCIONES.CUENTA_CREDITO  
 LEFT JOIN REFERENCIA
 ON DETALLE_COMPROBANTE_CNT.COMPANIA = REFERENCIA.COMPANIA
AND DETALLE_COMPROBANTE_CNT.ANO = REFERENCIA.ANO
AND DETALLE_COMPROBANTE_CNT.REFERENCIA = REFERENCIA.CODIGO
LEFT JOIN PLAN_CONTABLE  PLAN_BANCO
    ON  DETALLE_COMPROBANTE_CNT.COMPANIA  = PLAN_BANCO.COMPANIA  
    AND DETALLE_COMPROBANTE_CNT.ANO       = PLAN_BANCO.ANO  
    AND DETALLE_COMPROBANTE_CNT.BANCO_RETENCION    = PLAN_BANCO.CODIGO
WHERE DETALLE_COMPROBANTE_CNT.COMPANIA = s$compania$s
  AND DETALLE_COMPROBANTE_CNT.FECHA BETWEEN s$fechaInicial$s
		                                AND s$fechaFinal$s  
  AND DETALLE_COMPROBANTE_CNT.CUENTA BETWEEN 's$cuentaInicial$s'  
		                                 AND 's$cuentaFinal$s'         
 AND DETALLE_COMPROBANTE_CNT.REFERENCIA BETWEEN 's$referenciaInicial$s' AND 's$referenciaFin$s'
 AND (DETALLE_COMPROBANTE_CNT.BANCO_RETENCION IS NULL
	OR DETALLE_COMPROBANTE_CNT.BANCO_RETENCION BETWEEN 's$bancoIni$s'
		                                 AND 's$bancoFin$s')
  AND DETALLE_COMPROBANTE_CNT.TERCERO BETWEEN 's$terceroInicial$s' 
                                     AND 's$terceroFinal$s'
  AND PLAN_CONTABLE.CLASECUENTA IN ('I')  
GROUP BY  DETALLE_COMPROBANTE_CNT.COMPANIA,
         DETALLE_COMPROBANTE_C]') || TO_CLOB(q'[NT.ANO,  
         DETALLE_COMPROBANTE_CNT.CUENTA,  
         PLAN_CONTABLE.NOMBRE,  
         DETALLE_COMPROBANTE_CNT.TERCERO,  
         TERCERO.NOMBRE,  
         TERCERO.DIRECCION,  
         TERCERO.TELEFONOS,  
         CIUDAD.NOMBRE,  
         PLAN_CONTABLE.CLASECUENTA,  
         TERCERO.DIRECCION||' '||CIUDAD.NOMBRE,
         DETALLE_COMPROBANTE_CNT.REFERENCIA,
         REFERENCIA.NOMBRE,
        DETALLE_COMPROBANTE_CNT.BANCO_RETENCION,
        PLAN_BANCO.NOMBRE]') CONSULTA, 1 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);