MERGE INTO CONSULTAS FIN USING (SELECT '002627INFORMEBANCOOCCIDENTE' INFORME ,TO_CLOB(q'[SELECT  COUNT(*) OVER () AS TOTAL_REGISTROS,
    SUM(CONSULTAPLANOSOCCIDENTE.VALORTRANSACCION) OVER () AS TOTALVALOR,
    CONSULTAPLANOSOCCIDENTE.COMPANIA,
        CONSULTAPLANOSOCCIDENTE.CUENTAORIGEN,
        CONSULTAPLANOSOCCIDENTE.FECHADEPAGO,
        CONSULTAPLANOSOCCIDENTE.NOMBREBENEFICIARIO,
        CONSULTAPLANOSOCCIDENTE.NIT,
        CONSULTAPLANOSOCCIDENTE.COMPROBANTE,
        CONSULTAPLANOSOCCIDENTE.FORMAPAGOINF,
        CONSULTAPLANOSOCCIDENTE.VALORTRANSACCION,
        CONSULTAPLANOSOCCIDENTE.DESCRIPCION,
        CONSULTAPLANOSOCCIDENTE.BANCODESTINO,
        CONSULTAPLANOSOCCIDENTE.CUENTADESTINO,
        TERCEROPAGOS.TIPOCUENTA,
        CONSULTAPLANOSOCCIDENTE.NRO_DOCUMENTO,
        CONSULTAPLANOSOCCIDENTE.ARCHIVO_GENERADO
    FROM
      (SELECT s$cuentaCliente$s      AS CUENTAORIGEN,
        COMPROBANTE_CNT.CUENTABANCO AS CUENTADESTINO,
        CASE
          WHEN NVL(COMPROBANTE_CNT.PAGOAPODERADO,0) NOT IN (0)
          THEN APODERADO.NOMBRE
          ELSE TERCERO.NOMBRE
        END AS NOMBREBENEFICIARIO,
        CASE
          WHEN NVL(COMPROBANTE_CNT.PAGOAPODERADO,0) NOT IN (0)
          THEN APODERADO.NIT
          ELSE TERCERO.NIT
        END AS NIT,
        CASE
          WHEN NVL(COMPROBANTE_CNT.PAGOAPODERADO,0) NOT IN (0)
          THEN APODERADO.SUCURSAL
          ELSE TERCERO.SUCURSAL
        END AS SUCURSAL,
        CASE
          WHEN NVL(COMPROBANTE_CNT.PAGOAPODERADO,0) NOT IN (0)
          THEN APODERADO.DIGITOVERIFICACION
          ELSE TERCERO.DIGITOVERIFICACION
        END AS DIGITOVERIFICA,
        CASE
          WHEN NVL(COMPROBANTE_CNT.PAGOAPODERADO,0) NOT IN (0)
          THEN APODERADO.TIPOID
          ELSE TERCERO.TIPOID
        END AS TIPODOC,
        CASE WHEN COMPROBANTE_CNT.CUENTABANCO IS NOT NULL THEN
            TO_CHAR(COMPROBANTE_CNT.BANCO)
        ELSE '023'
        END AS BANCODESTINO,
        CASE
          WHEN (
            CASE
              WHEN NVL(PAGO_EFECTIVO,0) <> 0
              THEN '4'
              ELSE
                CASE
                  WHEN NRO_DOCUMENTO IS NOT NULL
                  THEN '1'
                  ELSE
                    CASE
                      WHEN COMPROBANTE_CNT.BANCO IN ('023')
                      THEN '2'
                      ELSE '3'
                    END
                END
            END) IN ('1: Pago en Cheque ','2: Pago abono a cuenta  - Banco de Occidente ','4: Pago en efectivo')
          THEN '023'
          ELSE TO_CHAR(COMPROBANTE_CNT.BANCO)
        END                           AS BANCODESTINOINF,
        COMPROBANTE_CNT.FECHAPAGADOGN AS FECHADEPAGO,
        CASE
          WHEN NVL(PAGO_EFECTIVO,0) <> 0
          THEN '4'
          ELSE
            CASE
              WHEN NRO_DOCUMENTO IS NOT NULL
              THEN '1'
              ELSE
                CASE
                  WHEN COMPROBANTE_CNT.BANCO IN ('023')
                  THEN '2'
                  ELSE '3'
                END
            END
        END AS FORMAPAGO,
        CASE
   ]') || TO_CLOB(q'[       WHEN NVL(PAGO_EFECTIVO,0) <> 0
          THEN '4: Pago en efectivo'
          ELSE
            CASE
              WHEN NVL(NRO_DOCUMENTO,'')<>''
              THEN '1: Pago en Cheque '
              ELSE
                CASE
                  WHEN NVL(CUENTABANCO,'') IN ('')
                  THEN ''
                  ELSE
                    CASE
                      WHEN COMPROBANTE_CNT.BANCO IN('s$numeroBanco$s')
                      THEN '2: Pago abono a cuenta  - Banco de Occidente '
                      ELSE
                        CASE
                          WHEN s$cuentaCliente$s <> CUENTABANCO
                          THEN '3: Abono a cuenta otras entidades'
                          ELSE ''
                        END
                    END
                END
            END
        END                       AS FORMAPAGOINF,
        COMPROBANTE_CNT.VLRAGIRAR AS VALORTRANSACCION,
        COMPROBANTE_CNT.NUMERO    AS COMPROBANTE,
        COMPROBANTE_CNT.DESCRIPCION,
        COMPROBANTE_CNT.CONSFACTURA AS NRO_DOCUMENTO,
        COMPROBANTE_CNT.PAGOENPLANO,
        CASE
            WHEN COMPROBANTE_CNT.ENVIADO = 0 THEN
            'NO'
        ELSE 
            'SI'
        END AS ARCHIVO_GENERADO,
        COMPROBANTE_CNT.COMPANIA,
        COMPROBANTE_CNT.BANCO,
        COMPROBANTE_CNT.CUENTABANCO
      FROM COMPROBANTE_CNT
      LEFT JOIN TERCERO
      ON COMPROBANTE_CNT.COMPANIA  = TERCERO.COMPANIA
      AND COMPROBANTE_CNT.TERCERO  = TERCERO.NIT
      AND COMPROBANTE_CNT.SUCURSAL = TERCERO.SUCURSAL
      LEFT JOIN TERCERO APODERADO
      ON TERCERO.COMPANIA            = APODERADO.COMPANIA
      AND TERCERO.NITAPODERADO       = APODERADO.NIT
      AND TERCERO.SUCURSALAPODERADO  = APODERADO.SUCURSAL
      WHERE COMPROBANTE_CNT.COMPANIA = s$compania$s
      AND COMPROBANTE_CNT.ANO        = s$ano$s
      AND COMPROBANTE_CNT.TIPO       = 's$tipoEgreso$s'
      AND COMPROBANTE_CNT.CUENTA BETWEEN 's$cuentaInicial$s'  AND 's$cuentaFinal$s'
      AND COMPROBANTE_CNT.NUMERO BETWEEN 's$egresoInicial$s' AND 's$egresoFinal$s'
      AND COMPROBANTE_CNT.PAGOENPLANO NOT IN (0)
      s$filtro$s
      ORDER BY COMPROBANTE_CNT.TIPO
      ) CONSULTAPLANOSOCCIDENTE
    LEFT JOIN TERCEROPAGOS
    ON CONSULTAPLANOSOCCIDENTE.NIT          = TERCEROPAGOS.NIT
    AND CONSULTAPLANOSOCCIDENTE.SUCURSAL    = TERCEROPAGOS.SUCURSAL
    AND CONSULTAPLANOSOCCIDENTE.COMPANIA    = TERCEROPAGOS.COMPANIA
    AND CONSULTAPLANOSOCCIDENTE.BANCO       = TERCEROPAGOS.BANCO
    AND CONSULTAPLANOSOCCIDENTE.CUENTABANCO = TERCEROPAGOS.CUENTA]') CONSULTA, 1 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, 'MPEREZ' CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);