MERGE INTO CONSULTAS FIN USING (SELECT '002893SubCOMCOS' INFORME ,TO_CLOB(q'[SELECT DISTINCT DETALLE_COMPROBANTE_PPTAL.COMPANIA COMP,
  DETALLE_COMPROBANTE_PPTAL.ANO ANOCOMP,
  DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE TIPOCOMP,
  DETALLE_COMPROBANTE_PPTAL.COMPROBANTE NUMCOMP,
  DC_PPTAL.CMPTE_AFECTADO NUMDISP,
  DETALLE_COMPROBANTE_PPTAL.CMPTE_AFECTADO NUMRESERVA,
  DETALLE_COMPROBANTE_PPTAL.CUENTA,
  PLAN_PRESUPUESTAL.NOMBRE,
  SUM(
  CASE
    WHEN DETALLE_COMPROBANTE_PPTAL.VALOR_DEBITO=0
    THEN DETALLE_COMPROBANTE_PPTAL.VALOR_CREDITO-DETALLE_COMPROBANTE_PPTAL.VALOR_DEBITO
    ELSE DETALLE_COMPROBANTE_PPTAL.VALOR_DEBITO -DETALLE_COMPROBANTE_PPTAL.VALOR_CREDITO
  END) VALOR,
   DETALLE_COMPROBANTE_PPTAL.CODIGO_CPC,
   CASE WHEN (NVL(DC_PPTAL.Valor_debito,0) - NVL(DC_PPTAL.Valor_credito,0)
      - (NVL(DC_PPTAL.Debito_afectado,0) - NVL(DC_PPTAL.Credito_afectado,0))
      + (NVL(DC_PPTAL.Modificacion_debito,0) - NVL(DC_PPTAL.Modificacion_credito,0)) > 0) THEN (NVL(DC_PPTAL.Valor_debito,0) - NVL(DC_PPTAL.Valor_credito,0)
      - (NVL(DC_PPTAL.Debito_afectado,0) - NVL(DC_PPTAL.Credito_afectado,0))
      + (NVL(DC_PPTAL.Modificacion_debito,0) - NVL(DC_PPTAL.Modificacion_credito,0))) 
      ELSE
      0
      END
    SALDORES
FROM DETALLE_COMPROBANTE_PPTAL
INNER JOIN PLAN_PRESUPUESTAL
ON DETALLE_COMPROBANTE_PPTAL.COMPANIA = PLAN_PRESUPUESTAL.COMPANIA
AND DETALLE_COMPROBANTE_PPTAL.ANO     = PLAN_PRESUPUESTAL.ANO
AND DETALLE_COMPROBANTE_PPTAL.CUENTA  = PLAN_PRESUPUESTAL.CODIGO                                                            
INNER JOIN DETALLE_COMPROBANTE_PPTAL DC_PPTAL
ON DETALLE_COMPROBANTE_PPTAL.COMPANIA = DC_PPTAL.COMPANIA
AND DETALLE_COMPROBANTE_PPTAL.ANO_AFECT = DC_PPTAL.ANO
AND DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE_AFECT = DC_PPTAL.TIPO_CPTE
AND DETALLE_COMPROBANTE_PPTAL.CMPTE_AFECTADO = DC_PPTAL.COMPROBANTE
AND DETALLE_COMPROBANTE_PPTAL.CONSECUTIVOPPTO = DC_PPTAL.CONSECUTIVO																																	 
GROUP BY DETALLE_COMPROBANTE_PPTAL.COMPANIA,
  DETALLE_COMPROBANTE_PPTAL.ANO,
  DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE,
  DETALLE_COMPROBANTE_PPTAL.COMPROBANTE,
  DC_PPTAL.CMPTE_AFECTADO,
  DETALLE_COMPROBANTE_PPTAL.CMPTE_AFECTADO,
  DETALLE_COMPROBANTE_PPTAL.CUENTA,
  PLAN_PRESUPUESTAL.NOMBRE,
  DETALLE_COMPROBANTE_PPTAL.CODIGO_CPC,
  CASE WHEN (NVL(DC_PPTAL.Valor_debito,0) - NVL(DC_PPTAL.Valor_credito,0)
      - (NVL(DC_PPTAL.Debito_afectado,0) - NVL(DC_PPTAL.Credito_afectado,0))
      + (NVL(DC_PPTAL.Modificacion_debito,0) - NVL(DC_PPTAL.Modificacion_credito,0)) > 0) THEN (NVL(DC_PPTAL.Valor_debito,0) - NVL(DC_PPTAL.Valor_credito,0)
      - (NVL(DC_PPTAL.Debito_afectado,0) - NVL(DC_PPTAL.Credito_afectado,0))
      + (NVL(DC_PPTAL.Modificacion_debito,0) - NVL(DC_PPTAL.Modificacion_credito,0))) 
      ELSE
      0
      END
HAVING DETALLE_COMPROBANTE_PPTAL.COMPANIA = s$compania$s
AND DETALLE_COMPROBANTE_PPTAL.ANO       = s$ano$s
AND DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE    = 's$tipoCpte$s'
AND DETALLE_COMPROBANTE_PPTAL.COMPROBANTE  = $P{PR_NUMCOMP}]') CONSULTA, 1 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, 'calarcon' CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);

MERGE INTO CONSULTAS_SUB FIN USING (SELECT '002892COMCOS' INFORME_PADRE, '002893SubCOMCOS' INFORME_HIJO, 'PR_STRSQL_SUBMOV_PRESUPUESTAL' PARAMETRO ,NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (FIN.INFORME_PADRE = INI.INFORME_PADRE AND INI.INFORME_HIJO = FIN.INFORME_HIJO)  WHEN MATCHED THEN  UPDATE SET FIN.PARAMETRO = INI.PARAMETRO , FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME_PADRE,INFORME_HIJO, PARAMETRO,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME_PADRE,INI.INFORME_HIJO, INI.PARAMETRO,INI.CREATED_BY,SYSDATE);
