MERGE INTO CONSULTAS FIN USING (SELECT '002847LisAuxiliares_SINCIERRE' INFORME ,TO_CLOB(q'[SELECT    
        DETALLE_COMPROBANTE_CNT.CUENTA,
        PLAN_CONTABLE.NOMBRE PNOMBRE,
        DETALLE_COMPROBANTE_CNT.FECHA,
        DETALLE_COMPROBANTE_CNT.COMPROBANTE,
        DETALLE_COMPROBANTE_CNT.ANO_AFECT,
        DETALLE_COMPROBANTE_CNT.AUXILIAR,
        DECODE(DETALLE_COMPROBANTE_CNT.AUXILIAR,PCK_DATOS.FC_CONS_AUXILIAR,' ',AUXILIAR.NOMBRE) AS NOMBREAUXILIAR, 
        DECODE(DETALLE_COMPROBANTE_CNT.CENTRO_COSTO, PCK_DATOS.FC_CONS_CENTRO,' ',CENTRO_COSTO.NOMBRE) AS NOMBRECENTROCOSTO, 
        DECODE(DETALLE_COMPROBANTE_CNT.TERCERO,PCK_DATOS.FC_CONS_TERCERO,' ', TERCERO.NOMBRE) AS NOMBRETERCERO,
        DECODE(DETALLE_COMPROBANTE_CNT.TERCERO,PCK_DATOS.FC_CONS_TERCERO,' ',DETALLE_COMPROBANTE_CNT.TERCERO) AS CODTERCERO,
        DECODE(DETALLE_COMPROBANTE_CNT.TIPO_CPTE_AFECT,NULL,COMPROBANTE_CNTAFECTADOS.TIPO_CPTE_AFECT,DETALLE_COMPROBANTE_CNT.TIPO_CPTE_AFECT) ||' 
        '||  DECODE(DETALLE_COMPROBANTE_CNT.CMPTE_AFECTADO,NULL, COMPROBANTE_CNTAFECTADOS.COMPROBANTE_AFECT,DETALLE_COMPROBANTE_CNT.CMPTE_AFECTADO) AS AFECTAA, 
        DECODE(DETALLE_COMPROBANTE_CNT.NRO_DOCUMENTO,NULL,COMPROBANTE_CNT.NRO_DOCUMENTO,DETALLE_COMPROBANTE_CNT.NRO_DOCUMENTO) AS NODOCUMENTO, 
        COMPROBANTE_CNT.DESCRIPCION,
        DETALLE_COMPROBANTE_CNT.VALOR_DEBITO,
        DETALLE_COMPROBANTE_CNT.VALOR_CREDITO,
        DETALLE_COMPROBANTE_CNT.BASE_GRAVABLE,
        DETALLE_COMPROBANTE_CNT.CUENTA,
        PLAN_CONTABLE.NOMBRE PNOMBRE,
                TIPO_COMPROBANTE.NOMBRE TNOMBRE,
                COMPROBANTE_CNT.DESCRIPCION DESCRIP,
                PLAN_CONTABLE.COMPANIA
FROM DETALLE_COMPROBANTE_CNT 
  INNER JOIN TIPO_COMPROBANTE 
    ON DETALLE_COMPROBANTE_CNT.COMPANIA = TIPO_COMPROBANTE.COMPANIA
    AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE = TIPO_COMPROBANTE.CODIGO
  INNER JOIN AUXILIAR 
    ON DETALLE_COMPROBANTE_CNT.COMPANIA = AUXILIAR.COMPANIA
    AND DETALLE_COMPROBANTE_CNT.ANO = AUXILIAR.ANO
    AND DETALLE_COMPROBANTE_CNT.AUXILIAR = AUXILIAR.CODIGO
  INNER JOIN CENTRO_COSTO 
    ON DETALLE_COMPROBANTE_CNT.COMPANIA = CENTRO_COSTO.COMPANIA
    AND DETALLE_COMPROBANTE_CNT.CENTRO_COSTO = CENTRO_COSTO.CODIGO
    AND DETALLE_COMPROBANTE_CNT.ANO = CENTRO_COSTO.ANO
  INNER JOIN PLAN_CONTABLE 
    ON DETALLE_COMPROBANTE_CNT.COMPANIA = PLAN_CONTABLE.COMPANIA 
    AND DETALLE_COMPROBANTE_CNT.CUENTA = PLAN_CONTABLE.CODIGO 
    AND DETALLE_COMPROBANTE_CNT.ANO = PLAN_CONTABLE.ANO 
  INNER JOIN TERCERO 
    ON DETALLE_COMPROBANTE_CNT.COMPANIA = TERCERO.COMPANIA
    AND DETALLE_COMPROBANTE_CNT.TERCERO = TERCERO.NIT 
    AND DETALLE_COMPROBANTE_CNT.SUCURSAL = TERCERO.SUCURSAL
  INNER JOIN COMPROBANTE_CNT 
    ON DETALLE_COMPROBANTE_CNT.COMPANIA = COMPROBANTE_CNT.COMPANIA 
    AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE = COMPROBANTE_CNT.TIPO
    AND DETALLE_COMPROBANTE_CNT.ANO = COMPROBANTE_CNT.ANO
    AND DETALLE_COMPROBANTE_CNT.COMPROBANTE = COMPROBANTE_CNT.NUMERO
  LEFT JOIN COMPROBANTE_CNTAFECTADOS 
    ON COMPROBANTE_CNTAFECTADOS.COMPANIA = DETALLE_COMPROBANTE_CNT.COMPANIA
    AND COMPROBANTE_CNTAFECTADOS.ANO = DETALLE_COMPROBANTE_CNT.ANO
    AND COMPROB]') || TO_CLOB(q'[ANTE_CNTAFECTADOS.TIPO_CPTE = DETALLE_COMPROBANTE_CNT.TIPO_CPTE
    AND COMPROBANTE_CNTAFECTADOS.COMPROBANTE = DETALLE_COMPROBANTE_CNT.COMPROBANTE
    AND COMPROBANTE_CNTAFECTADOS.ANO_AFECT = DETALLE_COMPROBANTE_CNT.ANO_AFECT
    AND COMPROBANTE_CNTAFECTADOS.TIPO_CPTE_AFECT = DETALLE_COMPROBANTE_CNT.TIPO_CPTE_AFECT
    AND COMPROBANTE_CNTAFECTADOS.COMPROBANTE_AFECT = DETALLE_COMPROBANTE_CNT.CMPTE_AFECTADO
WHERE       DETALLE_COMPROBANTE_CNT.COMPANIA = 's$compania$s'
AND       DETALLE_COMPROBANTE_CNT.CUENTA BETWEEN 's$cuentaInicial$s' AND 's$cuentaFinal$s' 
AND       TO_DATE(TO_CHAR(DETALLE_COMPROBANTE_CNT.FECHA,'DD/MM/YYYY'))  BETWEEN s$fechaInicial$s AND s$fechaFinal$s        
AND       DETALLE_COMPROBANTE_CNT.TIPO_CPTE BETWEEN 's$comprobanteInicial$s' AND 's$comprobanteFinal$s'
AND DETALLE_COMPROBANTE_CNT.CENTRO_COSTO BETWEEN 's$centroCostoInicial$s' AND 's$centroCostoFinal$s'
AND DETALLE_COMPROBANTE_CNT.TERCERO BETWEEN  's$terceroInicial$s' AND 's$terceroFinal$s'
AND TIPO_COMPROBANTE.CLASE_CONTABLE NOT IN('Z')

ORDER BY    DETALLE_COMPROBANTE_CNT.CUENTA, DETALLE_COMPROBANTE_CNT.FECHA, DETALLE_COMPROBANTE_CNT.COMPROBANTE]') CONSULTA, 1 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);