MERGE INTO CONSULTAS FIN USING (SELECT '002908SubEGRRetenciones' INFORME ,TO_CLOB(q'[SELECT COMPROBANTE_CNTRETENCION.COMPANIA,
    COMPROBANTE_CNTRETENCION.ANO,
    COMPROBANTE_CNTRETENCION.TIPO,
    COMPROBANTE_CNTRETENCION.NUMERO COMPROBANTE,
    COMPROBANTE_CNTRETENCION.CODIGORETENCION TIPORETENCION,
    RETENCIONES.NOMBRE,
    RETENCIONES.PCT_APLICAR,
    COMPROBANTE_CNTRETENCION.VALORBASE,
    COMPROBANTE_CNTRETENCION.VALOR
FROM COMPROBANTE_CNTRETENCION
INNER JOIN RETENCIONES
ON COMPROBANTE_CNTRETENCION.COMPANIA = RETENCIONES.COMPANIA
AND COMPROBANTE_CNTRETENCION.ANO = RETENCIONES.ANO
AND COMPROBANTE_CNTRETENCION.TIPORETENCION = RETENCIONES.TIPO
AND COMPROBANTE_CNTRETENCION.CODIGORETENCION = RETENCIONES.CODIGO
WHERE COMPROBANTE_CNTRETENCION.COMPANIA = $P{PR_COMPANIA}
    AND COMPROBANTE_CNTRETENCION.ANO = $P{PR_ANO}
    AND COMPROBANTE_CNTRETENCION.TIPO = $P{PR_TIPO}
    AND COMPROBANTE_CNTRETENCION.NUMERO BETWEEN $P{PR_COMPROBANTE} AND $P{PR_COMPROBANTE}]') CONSULTA, 1 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);
	
	MERGE INTO CONSULTAS_SUB FIN USING (SELECT '002906EGR_DC' INFORME_PADRE, '002908SubEGRRetenciones' INFORME_HIJO, 'PR_STRSQL_SECUNDARIO171' PARAMETRO ,NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (FIN.INFORME_PADRE = INI.INFORME_PADRE AND INI.INFORME_HIJO = FIN.INFORME_HIJO)  WHEN MATCHED THEN  UPDATE SET FIN.PARAMETRO = INI.PARAMETRO , FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME_PADRE,INFORME_HIJO, PARAMETRO,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME_PADRE,INI.INFORME_HIJO, INI.PARAMETRO,INI.CREATED_BY,SYSDATE);