MERGE INTO CONSULTAS FIN USING (SELECT '002970DescuadradoCentroCosto' INFORME ,TO_CLOB(q'[SELECT      SUM(DETALLE_COMPROBANTE_CNT.VALOR_DEBITO) AS SUMADEVALOR_DEBITO,
            SUM(DETALLE_COMPROBANTE_CNT.VALOR_CREDITO) AS SUMADEVALOR_CREDITO,
            DETALLE_COMPROBANTE_CNT.ANO AS ANO,
            DETALLE_COMPROBANTE_CNT.TIPO_CPTE AS TIPO,
            DETALLE_COMPROBANTE_CNT.COMPROBANTE AS NUMERO,
            TO_CHAR(DETALLE_COMPROBANTE_CNT.FECHA,'YYYY') || '/' || UPPER(PCK_SYSMAN_UTL.FC_NOMBRE_MES(DETALLE_COMPROBANTE_CNT.MES)) AS FECHA,
            TIPO_COMPROBANTE.NOMBRE AS NOMBRE,
            (SUM(DETALLE_COMPROBANTE_CNT.VALOR_DEBITO)-SUM(DETALLE_COMPROBANTE_CNT.VALOR_CREDITO)) AS DIFERENCIA,
            DETALLE_COMPROBANTE_CNT.COMPANIA AS COMPANIA,
            CASE WHEN (SUBSTR(CUENTA,1,1)<='7' AND SUBSTR(CUENTA,1,1) NOT IN('0'))
                 THEN 'B'
                 ELSE 'O'
                 END AS TIPOCTA,
            DETALLE_COMPROBANTE_CNT.CENTRO_COSTO
 FROM       DETALLE_COMPROBANTE_CNT
 LEFT JOIN  TIPO_COMPROBANTE ON (DETALLE_COMPROBANTE_CNT.COMPANIA = TIPO_COMPROBANTE.COMPANIA 
      AND   DETALLE_COMPROBANTE_CNT.TIPO_CPTE = TIPO_COMPROBANTE.CODIGO) 
 WHERE      DETALLE_COMPROBANTE_CNT.COMPANIA = 's$compania$s'
  AND       DETALLE_COMPROBANTE_CNT.ANO   = s$anio$s
  AND       TO_NUMBER(TO_CHAR(FECHA,'MM')) BETWEEN s$mesInicial$s AND s$mesFinal$s
 GROUP BY   DETALLE_COMPROBANTE_CNT.ANO,
            DETALLE_COMPROBANTE_CNT.TIPO_CPTE,
            DETALLE_COMPROBANTE_CNT.COMPROBANTE,
            TO_CHAR(DETALLE_COMPROBANTE_CNT.FECHA,'YYYY') || '/' || UPPER(PCK_SYSMAN_UTL.FC_NOMBRE_MES(DETALLE_COMPROBANTE_CNT.MES)),
            TIPO_COMPROBANTE.NOMBRE, DETALLE_COMPROBANTE_CNT.COMPANIA,
            CASE WHEN (SUBSTR(CUENTA,1,1)<='7' AND SUBSTR(CUENTA,1,1) NOT IN('0'))
                 THEN 'B'
                 ELSE 'O'
                 END,
          DETALLE_COMPROBANTE_CNT.CENTRO_COSTO
 HAVING     ABS(SUM(DETALLE_COMPROBANTE_CNT.VALOR_DEBITO)-SUM(DETALLE_COMPROBANTE_CNT.VALOR_CREDITO))>0.001]') CONSULTA, 1 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);
 