SELECT SUM(DETALLE_COMPROBANTE_CNT.VALOR_CREDITO) AS RETENCION 
FROM PLAN_CONTABLE 
 INNER JOIN COMPROBANTE_CNT 
  ON  PLAN_CONTABLE.COMPANIA    = DETALLE_COMPROBANTE_CNT.COMPANIA 
  AND PLAN_CONTABLE.ANO         = DETALLE_COMPROBANTE_CNT.ANO 
  AND PLAN_CONTABLE.NATURALEZA  = DETALLE_COMPROBANTE_CNT.NATURALEZA
  AND PLAN_CONTABLE.CODIGO      = DETALLE_COMPROBANTE_CNT.CUENTA 
 INNER JOIN DETALLE_COMPROBANTE_CNT 
  ON  COMPROBANTE_CNT.COMPANIA = DETALLE_COMPROBANTE_CNT.COMPANIA 
  AND COMPROBANTE_CNT.ANO      = DETALLE_COMPROBANTE_CNT.ANO 
  AND COMPROBANTE_CNT.TIPO     = DETALLE_COMPROBANTE_CNT.TIPO_CPTE 
  AND COMPROBANTE_CNT.NUMERO   = DETALLE_COMPROBANTE_CNT.COMPROBANTE 
 INNER JOIN TERCERO 
  ON  TERCERO.COMPANIA = COMPROBANTE_CNT.COMPANIA 
  AND TERCERO.NIT      = COMPROBANTE_CNT.TERCERO 
  AND TERCERO.SUCURSAL = COMPROBANTE_CNT.SUCURSAL 
 INNER JOIN TIPO_COMPROBANTE 
  ON  COMPROBANTE_CNT.TIPO     = TIPO_COMPROBANTE.CODIGO 
  AND COMPROBANTE_CNT.COMPANIA = TIPO_COMPROBANTE.COMPANIA 
WHERE DETALLE_COMPROBANTE_CNT.CUENTA IN (s$cuentasContablesRet1607$s) 
  AND  + filtroNitONombre +  = 's$tercero1$s'
  AND COMPROBANTE_CNT.FECHA BETWEEN TO_DATE('s$strFechaInicial$s','MMDDYYYY') 
AND TO_DATE('s$strFechaFinal$s','MMDDYYYY') 
AND TIPO_COMPROBANTE.CLASE_CONTABLE NOT IN ('Z')
