MERGE INTO CONSULTAS FIN USING (SELECT '800046BaseBalancesAuxiliares' INFORME ,TO_CLOB(q'[SELECT PLAN.COMPANIA, 
        PLAN.ANO, 
        PLAN.CODIGO,
        PLAN.NATURALEZA,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO 
             THEN SALDO.DEBITOA
             ELSE PLAN.DEBITO0 
        END DEBITOA,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO 
             THEN SALDO.CREDITOA
             ELSE PLAN.CREDITO0
        END CREDITOA,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO
             THEN SALDO.DEBITOM
             ELSE
             (CASE WHEN 1  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.DEBITO1  ELSE 0 END
             + CASE WHEN 2  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.DEBITO2  ELSE 0 END
             + CASE WHEN 3  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.DEBITO3  ELSE 0 END
             + CASE WHEN 4  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.DEBITO4  ELSE 0 END
             + CASE WHEN 5  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.DEBITO5  ELSE 0 END
             + CASE WHEN 6  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.DEBITO6  ELSE 0 END
             + CASE WHEN 7  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.DEBITO7  ELSE 0 END
             + CASE WHEN 8  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.DEBITO8  ELSE 0 END
             + CASE WHEN 9  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.DEBITO9  ELSE 0 END
             + CASE WHEN 10 BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.DEBITO10 ELSE 0 END
             + CASE WHEN 11 BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.DEBITO11 ELSE 0 END
             + CASE WHEN 12 BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.DEBITO12 ELSE 0 END
             + CASE WHEN 13 BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.DEBITO13 ELSE 0 END)
        END DEBITOM,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO
             THEN SALDO.CREDITOM
             ELSE
             (CASE WHEN 1  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.CREDITO1  ELSE 0 END
             + CASE WHEN 2  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.CREDITO2  ELSE 0 END
             + CASE WHEN 3  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.CREDITO3  ELSE 0 END
             + CASE WHEN 4  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.CREDITO4  ELSE 0 END
             + CASE WHEN 5  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.CREDITO5  ELSE 0 END
             + CASE WHEN 6  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.CREDITO6  ELSE 0 END
             + CASE WHEN 7  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.CREDITO7  ELSE 0 END
             + CASE WHEN 8  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.CREDITO8  ELSE 0 END
             + CASE WHEN 9  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.CREDITO9  ELSE 0 END
             + CASE WHEN 10 BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.CREDITO10 ELSE 0 END
             + CASE WHEN 11 BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.CREDITO11 ELSE 0 END
             + CASE WHEN 12 BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.CREDITO12 ELSE 0 END
             + CASE WHEN 13 BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.C]') || TO_CLOB(q'[REDITO13 ELSE 0 END)
        END CREDITOM,
        SUM(SALDO.DEBITO )   DEBITO, 
        SUM(SALDO.CREDITO)   CREDITO, 
        SUM(SALDO.SALDOANT)  SALDOANT, 
        SUM(SALDO.SALDOFIN)  SALDOFIN,    
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO THEN SALDO.TERCERO                ELSE NULL END TERCERO,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO THEN SALDO.AUXILIAR               ELSE NULL END AUXILIAR,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO THEN SALDO.CENTRO_COSTO           ELSE NULL END CENTRO_COSTO,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO THEN SALDO.REFERENCIA             ELSE NULL END REFERENCIA,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO THEN SALDO.FUENTE_RECURSOS        ELSE NULL END FUENTE_RECURSOS,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO THEN SALDO.TERCERO_NOMBRE         ELSE NULL END TERCERO_NOMBRE,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO THEN SALDO.AUXILIAR_NOMBRE        ELSE NULL END AUXILIAR_NOMBRE,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO THEN SALDO.CENTRO_COSTO_NOMBRE    ELSE NULL END CENTRO_COSTO_NOMBRE,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO THEN SALDO.REFERENCIA_NOMBRE      ELSE NULL END REFERENCIA_NOMBRE,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO THEN SALDO.FUENTE_RECURSOS_NOMBRE ELSE NULL END FUENTE_RECURSOS_NOMBRE,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO THEN SALDO.NOMBRE ELSE PLAN.NOMBRE END NOMBRE,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO THEN SALDO.ORDEN ELSE PLAN.CODIGO END ORDEN,       
		PLAN.SALDOs$mestrabajo$s						
FROM PLAN_CONTABLE PLAN INNER JOIN 
(
    SELECT  /* INDEX(PLAN_CONTABLE PK_PLAN_CONTABLE) 
            INDEX (SALDO_AUX_CONTABLE SALDO_AUX_CONTABLE_PLAN) 
            INDEX (TERCERO PK_TERCERO) 
            INDEX (CENTRO_COSTO PK_CENTRO_COSTO) 
            INDEX (AUXILIAR     PK_AUXILIAR) 
            INDEX (FUENTE_RECURSOS PK_FUENTE_RECURSOS) 
            INDEX (REFERENCIA PK_REFERENCIA)  */ 
            PLAN_CONTABLE.COMPANIA, 
            PLAN_CONTABLE.ANO, 
            PLAN_CONTABLE.CODIGO,     
            SUM(SALDO_AUX_CONTABLE.DEBITO0) DEBITOA,
            SUM(SALDO_AUX_CONTABLE.CREDITO0) CREDITOA,
           SUM(CASE WHEN 1  BETWEEN s$mesIni$s AND s$mesFinal$s THEN SALDO_AUX_CONTABLE.DEBITO1  ELSE 0 END
           + CASE WHEN 2  BETWEEN s$mesIni$s AND s$mesFinal$s THEN SALDO_AUX_CONTABLE.DEBITO2  ELSE 0 END
           + CASE WHEN 3  BETWEEN s$mesIni$s AND s$mesFinal$s THEN SALDO_AUX_CONTABLE.DEBITO3  ELSE 0 END
           + CASE WHEN 4  BETWEEN s$mesIni$s AND s$mesFinal$s THEN SALDO_AUX_CONTABLE.DEBITO4  ELSE 0 END
           + CASE WHEN 5  BETWEEN s$mesIni$s AND s$mesFinal$s THEN SALDO_AUX_CONTABLE.DEBITO5  ELSE 0 END
           + CASE WHEN 6  BETWEEN s$mesIni$s AND s$mesFinal$s THEN SALDO_AUX_CONTABLE.DEBITO6  ELSE 0 END
           + CASE WHEN 7  BETWEEN s$mesIni$s AND s$mesFinal$s THEN SALDO_AUX_CONTABLE.DEBITO7  ELSE 0 END
           + CASE WHEN 8  BETWEEN s$mesIni$s AND s$mesFinal$s THEN SALDO_AUX_CONTABLE.DEBITO8  ELSE 0 END
           + CASE WHEN]') || TO_CLOB(q'[ 9  BETWEEN s$mesIni$s AND s$mesFinal$s THEN SALDO_AUX_CONTABLE.DEBITO9  ELSE 0 END
           + CASE WHEN 10 BETWEEN s$mesIni$s AND s$mesFinal$s THEN SALDO_AUX_CONTABLE.DEBITO10 ELSE 0 END
           + CASE WHEN 11 BETWEEN s$mesIni$s AND s$mesFinal$s THEN SALDO_AUX_CONTABLE.DEBITO11 ELSE 0 END
           + CASE WHEN 12 BETWEEN s$mesIni$s AND s$mesFinal$s THEN SALDO_AUX_CONTABLE.DEBITO12 ELSE 0 END
           + CASE WHEN 13 BETWEEN s$mesIni$s AND s$mesFinal$s THEN SALDO_AUX_CONTABLE.DEBITO13 ELSE 0 END
           ) DEBITOM,
           SUM(CASE WHEN 1  BETWEEN s$mesIni$s AND s$mesFinal$s THEN SALDO_AUX_CONTABLE.CREDITO1  ELSE 0 END
           + CASE WHEN 2  BETWEEN s$mesIni$s AND s$mesFinal$s THEN SALDO_AUX_CONTABLE.CREDITO2  ELSE 0 END
           + CASE WHEN 3  BETWEEN s$mesIni$s AND s$mesFinal$s THEN SALDO_AUX_CONTABLE.CREDITO3  ELSE 0 END
           + CASE WHEN 4  BETWEEN s$mesIni$s AND s$mesFinal$s THEN SALDO_AUX_CONTABLE.CREDITO4  ELSE 0 END
           + CASE WHEN 5  BETWEEN s$mesIni$s AND s$mesFinal$s THEN SALDO_AUX_CONTABLE.CREDITO5  ELSE 0 END
           + CASE WHEN 6  BETWEEN s$mesIni$s AND s$mesFinal$s THEN SALDO_AUX_CONTABLE.CREDITO6  ELSE 0 END
           + CASE WHEN 7  BETWEEN s$mesIni$s AND s$mesFinal$s THEN SALDO_AUX_CONTABLE.CREDITO7  ELSE 0 END
           + CASE WHEN 8  BETWEEN s$mesIni$s AND s$mesFinal$s THEN SALDO_AUX_CONTABLE.CREDITO8  ELSE 0 END
           + CASE WHEN 9  BETWEEN s$mesIni$s AND s$mesFinal$s THEN SALDO_AUX_CONTABLE.CREDITO9  ELSE 0 END
           + CASE WHEN 10 BETWEEN s$mesIni$s AND s$mesFinal$s THEN SALDO_AUX_CONTABLE.CREDITO10 ELSE 0 END
           + CASE WHEN 11 BETWEEN s$mesIni$s AND s$mesFinal$s THEN SALDO_AUX_CONTABLE.CREDITO11 ELSE 0 END
           + CASE WHEN 12 BETWEEN s$mesIni$s AND s$mesFinal$s THEN SALDO_AUX_CONTABLE.CREDITO12 ELSE 0 END
           + CASE WHEN 13 BETWEEN s$mesIni$s AND s$mesFinal$s THEN SALDO_AUX_CONTABLE.CREDITO13 ELSE 0 END
           ) CREDITOM,
           SUM(CASE WHEN 0  BETWEEN s$mesIni$s AND s$mesFin$s  THEN SALDO_AUX_CONTABLE.DEBITO0  ELSE 0 END
           + CASE WHEN 1  BETWEEN s$mesIni$s AND s$mesFin$s  THEN SALDO_AUX_CONTABLE.DEBITO1  ELSE 0 END
           + CASE WHEN 2  BETWEEN s$mesIni$s AND s$mesFin$s  THEN SALDO_AUX_CONTABLE.DEBITO2  ELSE 0 END
           + CASE WHEN 3  BETWEEN s$mesIni$s AND s$mesFin$s  THEN SALDO_AUX_CONTABLE.DEBITO3  ELSE 0 END
           + CASE WHEN 4  BETWEEN s$mesIni$s AND s$mesFin$s  THEN SALDO_AUX_CONTABLE.DEBITO4  ELSE 0 END
           + CASE WHEN 5  BETWEEN s$mesIni$s AND s$mesFin$s  THEN SALDO_AUX_CONTABLE.DEBITO5  ELSE 0 END
           + CASE WHEN 6  BETWEEN s$mesIni$s AND s$mesFin$s  THEN SALDO_AUX_CONTABLE.DEBITO6  ELSE 0 END
           + CASE WHEN 7  BETWEEN s$mesIni$s AND s$mesFin$s  THEN SALDO_AUX_CONTABLE.DEBITO7  ELSE 0 END
           + CASE WHEN 8  BETWEEN s$mesIni$s AND s$mesFin$s  THEN SALDO_AUX_CONTABLE.DEBITO8  ELSE 0 END
           + CASE WHEN 9  BETWEEN s$mesIni$s AND s$mesFin$s  THEN SALDO_AUX_CONTABLE.DEBITO9  ELSE 0 END
  ]') || TO_CLOB(q'[         + CASE WHEN 10 BETWEEN s$mesIni$s AND s$mesFin$s  THEN SALDO_AUX_CONTABLE.DEBITO10 ELSE 0 END
           + CASE WHEN 11 BETWEEN s$mesIni$s AND s$mesFin$s  THEN SALDO_AUX_CONTABLE.DEBITO11 ELSE 0 END
           + CASE WHEN 12 BETWEEN s$mesIni$s AND s$mesFin$s  THEN SALDO_AUX_CONTABLE.DEBITO12 ELSE 0 END
           + CASE WHEN 13 BETWEEN s$mesIni$s AND s$mesFin$s  THEN SALDO_AUX_CONTABLE.DEBITO13 ELSE 0 END
           ) DEBITO,
         SUM(CASE WHEN 0  BETWEEN s$mesIni$s AND s$mesFin$s  THEN SALDO_AUX_CONTABLE.CREDITO0  ELSE 0 END
           + CASE WHEN 1  BETWEEN s$mesIni$s AND s$mesFin$s  THEN SALDO_AUX_CONTABLE.CREDITO1  ELSE 0 END
           + CASE WHEN 2  BETWEEN s$mesIni$s AND s$mesFin$s  THEN SALDO_AUX_CONTABLE.CREDITO2  ELSE 0 END
           + CASE WHEN 3  BETWEEN s$mesIni$s AND s$mesFin$s  THEN SALDO_AUX_CONTABLE.CREDITO3  ELSE 0 END
           + CASE WHEN 4  BETWEEN s$mesIni$s AND s$mesFin$s  THEN SALDO_AUX_CONTABLE.CREDITO4  ELSE 0 END
           + CASE WHEN 5  BETWEEN s$mesIni$s AND s$mesFin$s  THEN SALDO_AUX_CONTABLE.CREDITO5  ELSE 0 END
           + CASE WHEN 6  BETWEEN s$mesIni$s AND s$mesFin$s  THEN SALDO_AUX_CONTABLE.CREDITO6  ELSE 0 END
           + CASE WHEN 7  BETWEEN s$mesIni$s AND s$mesFin$s  THEN SALDO_AUX_CONTABLE.CREDITO7  ELSE 0 END
           + CASE WHEN 8  BETWEEN s$mesIni$s AND s$mesFin$s  THEN SALDO_AUX_CONTABLE.CREDITO8  ELSE 0 END
           + CASE WHEN 9  BETWEEN s$mesIni$s AND s$mesFin$s  THEN SALDO_AUX_CONTABLE.CREDITO9  ELSE 0 END
           + CASE WHEN 10 BETWEEN s$mesIni$s AND s$mesFin$s  THEN SALDO_AUX_CONTABLE.CREDITO10 ELSE 0 END
           + CASE WHEN 11 BETWEEN s$mesIni$s AND s$mesFin$s  THEN SALDO_AUX_CONTABLE.CREDITO11 ELSE 0 END
           + CASE WHEN 12 BETWEEN s$mesIni$s AND s$mesFin$s  THEN SALDO_AUX_CONTABLE.CREDITO12 ELSE 0 END
           + CASE WHEN 13 BETWEEN s$mesIni$s AND s$mesFin$s  THEN SALDO_AUX_CONTABLE.CREDITO13 ELSE 0 END
           ) CREDITO,
          SUM(CASE WHEN 0  = s$mesIni$s -1  THEN SALDO_AUX_CONTABLE.SALDO0  ELSE 0 END
           + CASE WHEN 1  = s$mesIni$s -1  THEN SALDO_AUX_CONTABLE.SALDO1  ELSE 0 END
           + CASE WHEN 2  = s$mesIni$s -1  THEN SALDO_AUX_CONTABLE.SALDO2  ELSE 0 END
           + CASE WHEN 3  = s$mesIni$s -1  THEN SALDO_AUX_CONTABLE.SALDO3  ELSE 0 END
           + CASE WHEN 4  = s$mesIni$s -1  THEN SALDO_AUX_CONTABLE.SALDO4  ELSE 0 END
           + CASE WHEN 5  = s$mesIni$s -1  THEN SALDO_AUX_CONTABLE.SALDO5  ELSE 0 END
           + CASE WHEN 6  = s$mesIni$s -1  THEN SALDO_AUX_CONTABLE.SALDO6  ELSE 0 END
           + CASE WHEN 7  = s$mesIni$s -1  THEN SALDO_AUX_CONTABLE.SALDO7  ELSE 0 END
           + CASE WHEN 8  = s$mesIni$s -1  THEN SALDO_AUX_CONTABLE.SALDO8  ELSE 0 END
           + CASE WHEN 9  = s$mesIni$s -1  THEN SALDO_AUX_CONTABLE.SALDO9  ELSE 0 END
           + CASE WHEN 10 = s$mesIni$s -1  THEN SALDO_AUX_CONTABLE.SALDO10 ELSE 0 END
           + CASE WHEN 11 = s$mesIni$s -1  THEN SALDO_AUX_CONTABLE.SALDO11 ELSE 0 END
           + CASE WHEN]') || TO_CLOB(q'[ 12 = s$mesIni$s -1  THEN SALDO_AUX_CONTABLE.SALDO12 ELSE 0 END
           + CASE WHEN 13 = s$mesIni$s -1  THEN SALDO_AUX_CONTABLE.SALDO13 ELSE 0 END
           ) SALDOANT,
            SUM(CASE WHEN 0  = s$mesFin$s  THEN SALDO_AUX_CONTABLE.SALDO0  ELSE 0 END
           + CASE WHEN 1  = s$mesFin$s  THEN SALDO_AUX_CONTABLE.SALDO1  ELSE 0 END
           + CASE WHEN 2  = s$mesFin$s  THEN SALDO_AUX_CONTABLE.SALDO2  ELSE 0 END
           + CASE WHEN 3  = s$mesFin$s  THEN SALDO_AUX_CONTABLE.SALDO3  ELSE 0 END
           + CASE WHEN 4  = s$mesFin$s  THEN SALDO_AUX_CONTABLE.SALDO4  ELSE 0 END
           + CASE WHEN 5  = s$mesFin$s  THEN SALDO_AUX_CONTABLE.SALDO5  ELSE 0 END
           + CASE WHEN 6  = s$mesFin$s  THEN SALDO_AUX_CONTABLE.SALDO6  ELSE 0 END
           + CASE WHEN 7  = s$mesFin$s  THEN SALDO_AUX_CONTABLE.SALDO7  ELSE 0 END
           + CASE WHEN 8  = s$mesFin$s  THEN SALDO_AUX_CONTABLE.SALDO8  ELSE 0 END
           + CASE WHEN 9  = s$mesFin$s  THEN SALDO_AUX_CONTABLE.SALDO9  ELSE 0 END
           + CASE WHEN 10 = s$mesFin$s  THEN SALDO_AUX_CONTABLE.SALDO10 ELSE 0 END
           + CASE WHEN 11 = s$mesFin$s  THEN SALDO_AUX_CONTABLE.SALDO11 ELSE 0 END
           + CASE WHEN 12 = s$mesFin$s  THEN SALDO_AUX_CONTABLE.SALDO12 ELSE 0 END
           + CASE WHEN 13 = s$mesFin$s  THEN SALDO_AUX_CONTABLE.SALDO13 ELSE 0 END
           ) SALDOFIN,
             CASE WHEN 0 <> s$manTer$s AND PLAN_CONTABLE.CODIGO = SALDO_AUX_CONTABLE.CODIGO  THEN SALDO_AUX_CONTABLE.TERCERO        ELSE NULL END TERCERO,
            CASE WHEN 0 <> s$manAux$s AND PLAN_CONTABLE.CODIGO = SALDO_AUX_CONTABLE.CODIGO  THEN SALDO_AUX_CONTABLE.AUXILIAR       ELSE NULL END AUXILIAR, 
            CASE WHEN 0 <> s$manCen$s AND PLAN_CONTABLE.CODIGO = SALDO_AUX_CONTABLE.CODIGO  THEN SALDO_AUX_CONTABLE.CENTRO_COSTO   ELSE NULL END CENTRO_COSTO,
            CASE WHEN 0 <> s$manRef$s AND PLAN_CONTABLE.CODIGO = SALDO_AUX_CONTABLE.CODIGO  THEN SALDO_AUX_CONTABLE.REFERENCIA     ELSE NULL END REFERENCIA,
            CASE WHEN 0 <> s$manFue$s AND PLAN_CONTABLE.CODIGO = SALDO_AUX_CONTABLE.CODIGO  THEN SALDO_AUX_CONTABLE.FUENTE_RECURSO ELSE NULL END FUENTE_RECURSOS,
            CASE WHEN 0 <> s$manTer$s AND PLAN_CONTABLE.CODIGO = SALDO_AUX_CONTABLE.CODIGO  THEN TERCERO.NOMBRE         ELSE NULL END TERCERO_NOMBRE,
            CASE WHEN 0 <> s$manAux$s AND PLAN_CONTABLE.CODIGO = SALDO_AUX_CONTABLE.CODIGO  THEN AUXILIAR.NOMBRE        ELSE NULL END AUXILIAR_NOMBRE, 
            CASE WHEN 0 <> s$manCen$s AND PLAN_CONTABLE.CODIGO = SALDO_AUX_CONTABLE.CODIGO  THEN CENTRO_COSTO.NOMBRE    ELSE NULL END CENTRO_COSTO_NOMBRE,
            CASE WHEN 0 <> s$manRef$s AND PLAN_CONTABLE.CODIGO = SALDO_AUX_CONTABLE.CODIGO  THEN REFERENCIA.NOMBRE      ELSE NULL END REFERENCIA_NOMBRE,
            CASE WHEN 0 <> s$manFue$s AND PLAN_CONTABLE.CODIGO = SALDO_AUX_CONTABLE.CODIGO  THEN FUENTE_RECURSOS.NOMBRE ELSE NULL END FUENTE_RECURSOS_NOMBRE,
            NVL(CASE WHEN PLAN_CONTABLE.CODIGO <> SALDO_AUX_CONTABLE.CODIGO OR PLA]') || TO_CLOB(q'[N_CONTABLE.MOVIMIENTO<>0  THEN PLAN_CONTABLE.NOMBRE ELSE
            PLAN_CONTABLE.NOMBRE ||
            CASE WHEN 0 <> s$manTer$s AND PLAN_CONTABLE.MAN_AUX_TER <>0 THEN '/' || TERCERO.NOMBRE         ELSE NULL END ||
            CASE WHEN 0 <> s$manAux$s AND PLAN_CONTABLE.MAN_AUX_GEN <>0 THEN '/' || AUXILIAR.NOMBRE        ELSE NULL END ||
            CASE WHEN 0 <> s$manCen$s AND PLAN_CONTABLE.MAN_CEN_CTO <>0 THEN '/' || CENTRO_COSTO.NOMBRE    ELSE NULL END ||
            CASE WHEN 0 <> s$manRef$s AND PLAN_CONTABLE.MAN_AUX_REF <>0 THEN '/' || REFERENCIA.NOMBRE      ELSE NULL END ||
            CASE WHEN 0 <> s$manFue$s AND PLAN_CONTABLE.MAN_AUX_FUE <>0 THEN '/' || FUENTE_RECURSOS.NOMBRE ELSE NULL END  
            END, PLAN_CONTABLE.NOMBRE) NOMBRE,
            PLAN_CONTABLE.CODIGO ||
                CASE WHEN 0 <> s$manTer$s AND PLAN_CONTABLE.MAN_AUX_TER <>0 THEN '/' || SALDO_AUX_CONTABLE.TERCERO        ELSE NULL END ||
                CASE WHEN 0 <> s$manAux$s AND PLAN_CONTABLE.MAN_AUX_GEN <>0 THEN '/' || SALDO_AUX_CONTABLE.AUXILIAR       ELSE NULL END ||
                CASE WHEN 0 <> s$manCen$s AND PLAN_CONTABLE.MAN_CEN_CTO <>0 THEN '/' || SALDO_AUX_CONTABLE.CENTRO_COSTO   ELSE NULL END ||
                CASE WHEN 0 <> s$manRef$s AND PLAN_CONTABLE.MAN_AUX_REF <>0 THEN '/' || SALDO_AUX_CONTABLE.REFERENCIA     ELSE NULL END ||
                CASE WHEN 0 <> s$manFue$s AND PLAN_CONTABLE.MAN_AUX_FUE <>0 THEN '/' || SALDO_AUX_CONTABLE.FUENTE_RECURSO ELSE NULL END ORDEN,
			PLAN_CONTABLE.SALDOs$mestrabajo$s								  
      FROM  PLAN_CONTABLE INNER JOIN SALDO_AUX_CONTABLE 
            ON PLAN_CONTABLE.COMPANIA = SALDO_AUX_CONTABLE.COMPANIA
          AND PLAN_CONTABLE.ANO       = SALDO_AUX_CONTABLE.ANO     
          AND PLAN_CONTABLE.CODIGO    = SALDO_AUX_CONTABLE.CODIGO
        INNER JOIN TERCERO 
          ON SALDO_AUX_CONTABLE.COMPANIA = TERCERO.COMPANIA 
         AND SALDO_AUX_CONTABLE.TERCERO  = TERCERO.NIT 
         AND SALDO_AUX_CONTABLE.SUCURSAL = TERCERO.SUCURSAL
        INNER JOIN CENTRO_COSTO 
          ON SALDO_AUX_CONTABLE.COMPANIA     = CENTRO_COSTO.COMPANIA 
         AND SALDO_AUX_CONTABLE.ANO          = CENTRO_COSTO.ANO 
         AND SALDO_AUX_CONTABLE.CENTRO_COSTO = CENTRO_COSTO.CODIGO
        INNER JOIN AUXILIAR 
          ON SALDO_AUX_CONTABLE.COMPANIA = AUXILIAR.COMPANIA 
         AND SALDO_AUX_CONTABLE.ANO      = AUXILIAR.ANO 
         AND SALDO_AUX_CONTABLE.AUXILIAR = AUXILIAR.CODIGO 
        INNER JOIN FUENTE_RECURSOS 
          ON SALDO_AUX_CONTABLE.COMPANIA       = FUENTE_RECURSOS.COMPANIA 
         AND SALDO_AUX_CONTABLE.ANO            = FUENTE_RECURSOS.ANO 
         AND SALDO_AUX_CONTABLE.FUENTE_RECURSO = FUENTE_RECURSOS.CODIGO 
        INNER JOIN REFERENCIA 
          ON SALDO_AUX_CONTABLE.COMPANIA   = REFERENCIA.COMPANIA 
         AND SALDO_AUX_CONTABLE.ANO        = REFERENCIA.ANO 
         AND SALDO_AUX_CONTABLE.REFERENCIA = REFERENCIA.CODIGO 
    WHERE PLAN_CONTABLE.COMPANIA = s$compania$s
      AND PLAN_CONTABLE.ANO ]') || TO_CLOB(q'[     = s$anio$s
      AND PLAN_CONTABLE.CODIGO  BETWEEN 's$codigoInicial$s' AND 's$codigoFinal$s'
      AND PLAN_CONTABLE.MAN_AUX_TER = CASE WHEN 0 = s$manTer$s THEN  PLAN_CONTABLE.MAN_AUX_TER ELSE -1 END  
      AND PLAN_CONTABLE.MAN_AUX_GEN = CASE WHEN 0 = s$manAux$s THEN  PLAN_CONTABLE.MAN_AUX_GEN ELSE -1 END
      AND PLAN_CONTABLE.MAN_CEN_CTO = CASE WHEN 0 = s$manCen$s THEN  PLAN_CONTABLE.MAN_CEN_CTO ELSE -1 END
      AND PLAN_CONTABLE.MAN_AUX_REF = CASE WHEN 0 = s$manRef$s THEN  PLAN_CONTABLE.MAN_AUX_REF ELSE -1 END
      AND PLAN_CONTABLE.MAN_AUX_FUE = CASE WHEN 0 = s$manFue$s THEN  PLAN_CONTABLE.MAN_AUX_FUE ELSE -1 END  
      AND SALDO_AUX_CONTABLE.TERCERO        BETWEEN CASE WHEN 0 <> s$manTer$s THEN 's$terceroInicial$s'    ELSE SALDO_AUX_CONTABLE.TERCERO        END AND CASE WHEN 0 <> s$manTer$s THEN 's$terceroFinal$s'     ELSE SALDO_AUX_CONTABLE.TERCERO        END  
      AND SALDO_AUX_CONTABLE.AUXILIAR       BETWEEN CASE WHEN 0 <> s$manAux$s THEN 's$auxiliarInicial$s'   ELSE SALDO_AUX_CONTABLE.AUXILIAR       END AND CASE WHEN 0 <> s$manAux$s THEN 's$auxiliarFinal$s'    ELSE SALDO_AUX_CONTABLE.AUXILIAR       END
      AND SALDO_AUX_CONTABLE.CENTRO_COSTO   BETWEEN CASE WHEN 0 <> s$manCen$s THEN 's$centroInicial$s'     ELSE SALDO_AUX_CONTABLE.CENTRO_COSTO   END AND CASE WHEN 0 <> s$manCen$s THEN 's$centroFinal$s'       ELSE SALDO_AUX_CONTABLE.CENTRO_COSTO   END
      AND SALDO_AUX_CONTABLE.REFERENCIA     BETWEEN CASE WHEN 0 <> s$manRef$s THEN 's$referenciaInicial$s' ELSE SALDO_AUX_CONTABLE.REFERENCIA     END AND CASE WHEN 0 <> s$manRef$s THEN 's$referenciaFinal$s' ELSE SALDO_AUX_CONTABLE.REFERENCIA     END
      AND SALDO_AUX_CONTABLE.FUENTE_RECURSO BETWEEN CASE WHEN 0 <> s$manFue$s THEN 's$fuenteInicial$s'     ELSE SALDO_AUX_CONTABLE.FUENTE_RECURSO END AND CASE WHEN 0 <> s$manFue$s THEN 's$fuenteFinal$s'      ELSE SALDO_AUX_CONTABLE.FUENTE_RECURSO END
    GROUP BY  PLAN_CONTABLE.COMPANIA, 
              PLAN_CONTABLE.ANO, 
              PLAN_CONTABLE.CODIGO,
              CASE WHEN 0 <> s$manTer$s AND PLAN_CONTABLE.CODIGO = SALDO_AUX_CONTABLE.CODIGO  THEN SALDO_AUX_CONTABLE.TERCERO        ELSE NULL END,
              CASE WHEN 0 <> s$manAux$s AND PLAN_CONTABLE.CODIGO = SALDO_AUX_CONTABLE.CODIGO  THEN SALDO_AUX_CONTABLE.AUXILIAR       ELSE NULL END, 
              CASE WHEN 0 <> s$manCen$s AND PLAN_CONTABLE.CODIGO = SALDO_AUX_CONTABLE.CODIGO  THEN SALDO_AUX_CONTABLE.CENTRO_COSTO   ELSE NULL END,
              CASE WHEN 0 <> s$manRef$s AND PLAN_CONTABLE.CODIGO = SALDO_AUX_CONTABLE.CODIGO  THEN SALDO_AUX_CONTABLE.REFERENCIA     ELSE NULL END,
              CASE WHEN 0 <> s$manFue$s AND PLAN_CONTABLE.CODIGO = SALDO_AUX_CONTABLE.CODIGO  THEN SALDO_AUX_CONTABLE.FUENTE_RECURSO ELSE NULL END,
              CASE WHEN 0 <> s$manTer$s AND PLAN_CONTABLE.CODIGO = SALDO_AUX_CONTABLE.CODIGO  THEN TERCERO.NOMBRE         ELSE NULL END,
              CASE WHEN 0 <> s$manAux$s AND PLAN_CONTABLE.CODIGO = SALDO_AUX_CONTABLE.CODIGO  THEN AUXILIAR.NOMBRE     ]') || TO_CLOB(q'[ELSE NULL END,
              CASE WHEN 0 <> s$manCen$s AND PLAN_CONTABLE.CODIGO = SALDO_AUX_CONTABLE.CODIGO  THEN CENTRO_COSTO.NOMBRE    ELSE NULL END,
              CASE WHEN 0 <> s$manRef$s AND PLAN_CONTABLE.CODIGO = SALDO_AUX_CONTABLE.CODIGO  THEN REFERENCIA.NOMBRE      ELSE NULL END,
              CASE WHEN 0 <> s$manFue$s AND PLAN_CONTABLE.CODIGO = SALDO_AUX_CONTABLE.CODIGO  THEN FUENTE_RECURSOS.NOMBRE ELSE NULL END,
              NVL(CASE WHEN PLAN_CONTABLE.CODIGO <> SALDO_AUX_CONTABLE.CODIGO OR PLAN_CONTABLE.MOVIMIENTO<>0  THEN PLAN_CONTABLE.NOMBRE ELSE
                PLAN_CONTABLE.NOMBRE ||
                CASE WHEN 0 <> s$manTer$s AND PLAN_CONTABLE.MAN_AUX_TER <>0 THEN '/' || TERCERO.NOMBRE         ELSE NULL END ||
                CASE WHEN 0 <> s$manAux$s AND PLAN_CONTABLE.MAN_AUX_GEN <>0 THEN '/' || AUXILIAR.NOMBRE        ELSE NULL END ||
                CASE WHEN 0 <> s$manCen$s AND PLAN_CONTABLE.MAN_CEN_CTO <>0 THEN '/' || CENTRO_COSTO.NOMBRE    ELSE NULL END ||
                CASE WHEN 0 <> s$manRef$s AND PLAN_CONTABLE.MAN_AUX_REF <>0 THEN '/' || REFERENCIA.NOMBRE      ELSE NULL END ||
                CASE WHEN 0 <> s$manFue$s AND PLAN_CONTABLE.MAN_AUX_FUE <>0 THEN '/' || FUENTE_RECURSOS.NOMBRE ELSE NULL END  
              END, PLAN_CONTABLE.NOMBRE),
              PLAN_CONTABLE.CODIGO ||
                CASE WHEN 0 <> s$manTer$s AND PLAN_CONTABLE.MAN_AUX_TER <>0 THEN '/' || SALDO_AUX_CONTABLE.TERCERO        ELSE NULL END ||
                CASE WHEN 0 <> s$manAux$s AND PLAN_CONTABLE.MAN_AUX_GEN <>0 THEN '/' || SALDO_AUX_CONTABLE.AUXILIAR       ELSE NULL END ||
                CASE WHEN 0 <> s$manCen$s AND PLAN_CONTABLE.MAN_CEN_CTO <>0 THEN '/' || SALDO_AUX_CONTABLE.CENTRO_COSTO   ELSE NULL END ||
                CASE WHEN 0 <> s$manRef$s AND PLAN_CONTABLE.MAN_AUX_REF <>0 THEN '/' || SALDO_AUX_CONTABLE.REFERENCIA     ELSE NULL END ||
                CASE WHEN 0 <> s$manFue$s AND PLAN_CONTABLE.MAN_AUX_FUE <>0 THEN '/' || SALDO_AUX_CONTABLE.FUENTE_RECURSO ELSE NULL END,
			PLAN_CONTABLE.SALDOs$mestrabajo$s									
) SALDO
 ON PLAN.COMPANIA = SALDO.COMPANIA
AND PLAN.ANO      = SALDO.ANO     
AND PLAN.CODIGO   = CASE WHEN 0 <> s$mayoriza$s THEN SUBSTR(SALDO.CODIGO, 1, LENGTH(PLAN.CODIGO)) ELSE SALDO.CODIGO END
WHERE PLAN.COMPANIA = s$compania$s
AND PLAN.ANO      = s$anio$s
GROUP BY PLAN.COMPANIA, 
        PLAN.ANO, 
        PLAN.CODIGO,
        PLAN.NATURALEZA,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO 
             THEN SALDO.DEBITOA
             ELSE PLAN.DEBITO0 
        END,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO 
             THEN SALDO.CREDITOA
             ELSE PLAN.CREDITO0
        END,]') || TO_CLOB(q'[
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO
             THEN SALDO.DEBITOM
             ELSE
             (CASE WHEN 1  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.DEBITO1  ELSE 0 END
             + CASE WHEN 2  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.DEBITO2  ELSE 0 END
             + CASE WHEN 3  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.DEBITO3  ELSE 0 END
             + CASE WHEN 4  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.DEBITO4  ELSE 0 END
             + CASE WHEN 5  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.DEBITO5  ELSE 0 END
             + CASE WHEN 6  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.DEBITO6  ELSE 0 END
             + CASE WHEN 7  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.DEBITO7  ELSE 0 END
             + CASE WHEN 8  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.DEBITO8  ELSE 0 END
             + CASE WHEN 9  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.DEBITO9  ELSE 0 END
             + CASE WHEN 10 BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.DEBITO10 ELSE 0 END
             + CASE WHEN 11 BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.DEBITO11 ELSE 0 END
             + CASE WHEN 12 BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.DEBITO12 ELSE 0 END
             + CASE WHEN 13 BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.DEBITO13 ELSE 0 END)
        END,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO
             THEN SALDO.CREDITOM
             ELSE
             (CASE WHEN 1  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.CREDITO1  ELSE 0 END
             + CASE WHEN 2  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.CREDITO2  ELSE 0 END
             + CASE WHEN 3  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.CREDITO3  ELSE 0 END
             + CASE WHEN 4  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.CREDITO4  ELSE 0 END
             + CASE WHEN 5  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.CREDITO5  ELSE 0 END
             + CASE WHEN 6  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.CREDITO6  ELSE 0 END
             + CASE WHEN 7  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.CREDITO7  ELSE 0 END
             + CASE WHEN 8  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.CREDITO8  ELSE 0 END
             + CASE WHEN 9  BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.CREDITO9  ELSE 0 END
             + CASE WHEN 10 BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.CREDITO10 ELSE 0 END
             + CASE WHEN 11 BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.CREDITO11 ELSE 0 END
             + CASE WHEN 12 BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.CREDITO12 ELSE 0 END
             + CASE WHEN 13 BETWEEN s$mesIni$s AND s$mesFinal$s THEN PLAN.CREDITO13 ELSE 0 END)
        END,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO THEN SALDO.TERCERO                ELSE NULL END ,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO THEN SALDO.AUXILIAR               ELSE NULL END ,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO THEN SALDO.CENTRO_COSTO           ELSE NULL END ,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO THEN SALDO.REFERENCIA             ELSE NULL END ,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO THEN SALDO.FUENTE_RECURSOS        ELSE NULL END ,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO THEN SALDO.TERCERO_NOMBRE         ELSE NULL END ,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO THEN SALDO.AUXILIAR_NOMBRE        ELSE NULL END ,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO THEN SALDO.CENTRO_COSTO_NOMBRE    ELSE NULL END ,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO THEN SALDO.REFERENCIA_NOMBRE      ELSE NULL END ,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO THEN SALDO.FUENTE_RECURSOS_NOMBRE ELSE NULL END ,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO THEN SALDO.NOMBRE                 ELSE PLAN.NOMBRE END ,
        CASE WHEN PLAN.CODIGO = SALDO.CODIGO THEN SALDO.ORDEN                  ELSE PLAN.CODIGO END,
		PLAN.SALDOs$mestrabajo$s]')CONSULTA, 1 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);