SELECT  CODIGO,
        NOMBRE,
        NATURALEZA,
        CLASECUENTA,
        TO_CHAR(MOVIMIENTO)  AS MOVIMIENTO,
        TO_CHAR(MAN_CEN_CTO) AS MAN_CEN_CTO,
        TO_CHAR(MAN_AUX_TER) AS MAN_AUX_TER,
        TO_CHAR(MAN_AUX_GEN) AS MAN_AUX_GEN,
        TO_CHAR(MAN_AUX_REF) AS MAN_AUX_REF,
        TO_CHAR(MAN_AUX_FUE) AS MAN_AUX_FUE
FROM PLAN_CONTABLE
WHERE COMPANIA = 's$companiaTrabajo$s' 
   AND ANO = s$anoTrabajo$s
ORDER BY codigo
