MERGE INTO CONSULTAS FIN USING (SELECT '800192NuevoFormatoNomina' INFORME ,TO_CLOB(q'[SELECT
    CASE WHEN NVL(COMPROBANTE_CNT.PAGOAPODERADO,0) = -1
        THEN TO_CHAR(
                CASE APODERADO.TIPOID
                    WHEN 'C' THEN 1
                    WHEN 'R' THEN 2
                    WHEN 'N' THEN 3
                    WHEN 'T' THEN 4
                    WHEN 'E' THEN 6
                END
               )
        ELSE TO_CHAR(
                CASE TERCERO.TIPOID
                    WHEN 'C' THEN 1
                    WHEN 'R' THEN 2
                    WHEN 'N' THEN 3
                    WHEN 'T' THEN 4
                    WHEN 'E' THEN 6
                END
               )
    END TIPO_DOCUMENTO_DEL_BENEFICIARIO,
    CASE WHEN NVL(COMPROBANTE_CNT.PAGOAPODERADO,0) = -1
        THEN APODERADO.NIT
        ELSE TERCERO.NIT
    END DOCUMENTO_DEL_BENEFICIARIO,
    CASE WHEN COMPROBANTE_CNT.PAGOAPODERADO NOT IN 0
        THEN SUBSTR(APODERADO.NOMBRE,1,18)
        ELSE SUBSTR(TERCERO.NOMBRE,1,18)
    END NOMBRE_BENEFICIARIO,
    TO_CHAR(
        CASE WHEN TERCEROPAGOS.TIPOCUENTA = 'A'
            THEN 37
            ELSE 27
        END
    ) TIPO_TRANSACCION,
    BANCO.BANCOASOBANCARIA AS CODIGO_BANCO,
    TERCEROPAGOS.CUENTA AS NO_CUENTA_BENEFICIERIO,
    TERCERO.DIRECCIONEMAIL AS EMAIL,
    '' AS DOCUMENTO_AUTORIZADO,
    '' AS REFERENCIA,
    TERCERO.TELEFONOS AS CELULAR_BENFICIARIO,
    COMPROBANTE_CNT.VLRAGIRAR AS VALOR_TRANSACCION,
    TO_CHAR(SYSDATE, 'YYYY-MM-DD') AS FECHA_DE_APLICACION 
FROM COMPROBANTE_CNT
INNER JOIN DETALLE_COMPROBANTE_CNT
    ON DETALLE_COMPROBANTE_CNT.COMPANIA = COMPROBANTE_CNT.COMPANIA
    AND DETALLE_COMPROBANTE_CNT.ANO = COMPROBANTE_CNT.ANO
    AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE = COMPROBANTE_CNT.TIPO
    AND DETALLE_COMPROBANTE_CNT.COMPROBANTE = COMPROBANTE_CNT.NUMERO
INNER JOIN TERCERO
    ON DETALLE_COMPROBANTE_CNT.COMPANIA = TERCERO.COMPANIA
    AND DETALLE_COMPROBANTE_CNT.TERCERO = TERCERO.NIT
    AND DETALLE_COMPROBANTE_CNT.SUCURSAL = TERCERO.SUCURSAL
LEFT JOIN TERCERO APODERADO
    ON TERCERO.COMPANIA = APODERADO.COMPANIA
    AND TERCERO.NITAPODERADO = APODERADO.NIT
    AND TERCERO.SUCURSALAPODERADO = APODERADO.SUCURSAL
LEFT JOIN TERCEROPAGOS
    ON TERCEROPAGOS.COMPANIA = COMPROBANTE_CNT.COMPANIA
    AND TERCEROPAGOS.NIT = COMPROBANTE_CNT.TERCERO
    AND TERCEROPAGOS.SUCURSAL = COMPROBANTE_CNT.SUCURSAL
    AND TERCEROPAGOS.BANCO = COMPROBANTE_CNT.BANCO
    AND TERCEROPAGOS.CUENTA = COMPROBANTE_CNT.CUENTABANCO
LEFT JOIN BANCO
    ON TERCEROPAGOS.COMPANIA = BANCO.COMPANIA
    AND TERCEROPAGOS.BANCO = BANCO.BANCO
    WHERE COMPROBANTE_CNT.COMPANIA = s$compania$s
    AND COMPROBANTE_CNT.ANO        = s$ano$s
    AND COMPROBANTE_CNT.TIPO       = 's$tipo$s'
    AND DETALLE_COMPROBANTE_CNT.CUENTA BETWEEN 's$cuentaInicial$s' AND 's$cuentaFinal$s'
    AND COMPROBANTE_CNT.NUMERO BETWEEN s$numeroInicial$s AND s$numeroFinal$s
    AND COMPROBANTE_CNT.PAGOENPLANO IN (-1)
    AND COMPROBANTE_CNT.ENVIADO IN (0)
    AND NVL(TERCEROPAGOS.BANCO,'0') NOT IN ('0')]') CONSULTA, 1 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);