SELECT NOMBRECOMPLETO, 
NUMERO_DCTO, 
EXPEDIDA,
CASE WHEN FECHA_RESOLUCION IS NOT NULL THEN (SUBSTR(FECHA_RESOLUCION,1,2) ||' de '|| 
PCK_SYSMAN_UTL.FC_NOMBRE_MES(PCK_SYSMAN_UTL.FC_MES(FECHA_RESOLUCION)) ||' de '||
PCK_SYSMAN_UTL.FC_ANIO(FECHA_RESOLUCION)) ELSE ' ' END FECHA_RESOLUCION,
SUBSTR(FECHA_INGRESO,1,2) ||' de '|| 
CASE WHEN FECHA_INGRESO IS NOT NULL THEN (PCK_SYSMAN_UTL.FC_NOMBRE_MES(PCK_SYSMAN_UTL.FC_MES(FECHA_INGRESO)) ||' de '||
PCK_SYSMAN_UTL.FC_ANIO(FECHA_INGRESO)) ELSE ' ' END FECHA_INGRESO, 
CASE WHEN FECHA_RETIRO IS NOT NULL THEN (SUBSTR(FECHA_RETIRO,1,2) ||' de '|| 
PCK_SYSMAN_UTL.FC_NOMBRE_MES(PCK_SYSMAN_UTL.FC_MES(FECHA_RETIRO)) ||' de '||
PCK_SYSMAN_UTL.FC_ANIO(FECHA_RETIRO)) ELSE ' ' END FECHA_RETIRO,
CASE WHEN FECHA_RADICADO_RET IS NOT NULL THEN (SUBSTR(FECHA_RADICADO_RET,1,2) ||' de '|| 
PCK_SYSMAN_UTL.FC_NOMBRE_MES(PCK_SYSMAN_UTL.FC_MES(FECHA_RADICADO_RET)) ||' de '||
PCK_SYSMAN_UTL.FC_ANIO(FECHA_RADICADO_RET)) ELSE ' ' END FECHA_RADICADO_RET,
CODIGOCARGO,
NOMBRE_DEL_CARGO,
GRADO,
ACTA_POSESION,
SUBSTR(FECHA_ACTA_POSESION,1,2) ||' de '|| 
PCK_SYSMAN_UTL.FC_NOMBRE_MES(PCK_SYSMAN_UTL.FC_MES(FECHA_ACTA_POSESION)) ||' de '||
PCK_SYSMAN_UTL.FC_ANIO(FECHA_ACTA_POSESION) FECHA_ACTA_POSESION,
SALARIO,
PCK_SYSMAN_UTL.FC_VALOR_LETRAS(SALARIO) AS SALARIOLETRAS,
C2, 
C79, 
C80, 
C150, 
C151, 
C155,
C158, 
C160, 
C175,
(C2+C79+C80+C150+C151+C155+C158+C160+C175) TOTAL,
PCK_SYSMAN_UTL.FC_VALOR_LETRAS(C2+C79+C80+C150+C151+C155+C158+C160+C175) AS VNETOLETRAS
FROM(
SELECT  NOVEDADES.ID_DE_CONCEPTO, 
        NOVEDADES.VALOR, 
HISTORICOS.COMPANIA, 
HISTORICOS.ANO, 
HISTORICOS.MES, 
HISTORICOS.PERIODO, 
HISTORICOS.ID_DE_EMPLEADO, 
UPPER(PERSONAL.NOMBRES || ' ' ||PERSONAL.APELLIDO1 || ' '||  PERSONAL.APELLIDO2) NOMBRECOMPLETO,
PERSONAL.NUMERO_DCTO, 
CASE WHEN EX.NOMBRE IS NOT NULL THEN INITCAP(EX.NOMBRE || ', ' ||DPTO.NOMBRE) ELSE '' END EXPEDIDA,
TO_CHAR(PERSONAL.FECHA_DE_INGRESO,'DD/MM/YYYY')FECHA_INGRESO,
TO_CHAR(PERSONAL.FECHA_DE_RETIRO,'DD/MM/YYYY')FECHA_RETIRO, 
TO_CHAR(PERSONAL.FECHA_RADICADO_RET,'DD/MM/YYYY')FECHA_RADICADO_RET,
TRUNC(LAST_DAY(TO_CHAR(PERSONAL.FECHA_DE_RETIRO,'DD/MM/YYYY'))) FECHA_RESOLUCION,
PERSONAL.ID_DE_CARGO CODIGOCARGO,
CARGOS.NOMBRE_DEL_CARGO, 
PERSONAL.ACTA_POSESION,
PERSONAL.FECHA_ACTA_POSESION,
CA.GRADO GRADO,
SALARIO_BASE_IBC SALARIO,
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('002') THEN HISTORICOS.VALOR ELSE 0 END) AS C2,
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('079') THEN HISTORICOS.VALOR ELSE 0 END) AS C79,
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('080') THEN HISTORICOS.VALOR ELSE 0 END) AS C80,
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('150') THEN HISTORICOS.VALOR ELSE 0 END) AS C150, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('151') THEN HISTORICOS.VALOR ELSE 0 END) AS C151, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('155') THEN HISTORICOS.VALOR ELSE 0 END) AS C155, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('158') THEN HISTORICOS.VALOR ELSE 0 END) AS C158,
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('160') THEN HISTORICOS.VALOR ELSE 0 END) AS C160, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('175') THEN HISTORICOS.VALOR ELSE 0 END) AS C175
FROM NOVEDADES 
INNER JOIN HISTORICOS 
    ON  NOVEDADES.ID_DE_EMPLEADO = HISTORICOS.ID_DE_EMPLEADO
    AND NOVEDADES.PERIODO = HISTORICOS.PERIODO 
    AND NOVEDADES.MES = HISTORICOS.MES 
    AND NOVEDADES.ANO = HISTORICOS.ANO 
    AND NOVEDADES.ID_DE_PROCESO = HISTORICOS.ID_DE_PROCESO 
    AND NOVEDADES.COMPANIA = HISTORICOS.COMPANIA 
INNER JOIN PERSONAL 
    ON NOVEDADES.ID_DE_EMPLEADO = PERSONAL.ID_DE_EMPLEADO 
    AND NOVEDADES.COMPANIA = PERSONAL.COMPANIA 
LEFT JOIN CIUDAD EX
ON EX.PAIS = PERSONAL.PAIS_CED
AND EX.DEPARTAMENTO = PERSONAL.DEPARTAMENTO_CED
AND EX.CODIGO = PERSONAL.EXPEDIDA
LEFT JOIN DEPARTAMENTO DPTO
ON EX.PAIS = DPTO.PAIS
AND EX.DEPARTAMENTO = DPTO.CODIGO
INNER JOIN CARGOS 
    ON PERSONAL.ID_DE_CARGO = CARGOS.ID_DE_CARGO 
    AND PERSONAL.COMPANIA = CARGOS.COMPANIA 
LEFT JOIN CATEGORIA CA
 ON PERSONAL.COMPANIA = CA.COMPANIA
AND PERSONAL.ESCALAFON = CA.ESCALAFON
AND PERSONAL.ID_DE_CATEGORIA  = CA.ID_DE_CATEGORIA
AND PERSONAL.ANO = CA.ANO
INNER JOIN CONCEPTOS 
    ON HISTORICOS.ID_DE_CONCEPTO = CONCEPTOS.ID_DE_CONCEPTO 
    AND HISTORICOS.COMPANIA = CONCEPTOS.COMPANIA 
INNER JOIN CENTRO_COSTO
ON PERSONAL.COMPANIA = CENTRO_COSTO.COMPANIA
AND PERSONAL.ANO = CENTRO_COSTO.ANO
AND PERSONAL.ID_CENTRO_DE_COSTO = CENTRO_COSTO.CODIGO 
WHERE (CONCEPTOS.CLASE=3 OR CONCEPTOS.CLASE=4 OR CONCEPTOS.CLASE=5 OR CONCEPTOS.CLASE=6 OR CONCEPTOS.CLASE=7)
GROUP BY NOVEDADES.ID_DE_CONCEPTO, NOVEDADES.VALOR, HISTORICOS.COMPANIA, HISTORICOS.ANO, HISTORICOS.MES, HISTORICOS.PERIODO, 
HISTORICOS.ID_DE_EMPLEADO, PERSONAL.NOMBRES || ' ' ||PERSONAL.APELLIDO1 || ' '||  PERSONAL.APELLIDO2, 
PERSONAL.NUMERO_DCTO, CASE WHEN EX.NOMBRE IS NOT NULL THEN INITCAP(EX.NOMBRE || ', ' ||DPTO.NOMBRE) ELSE '' END,
PERSONAL.FECHA_DE_INGRESO, PERSONAL.FECHA_DE_RETIRO, PERSONAL.FECHA_RADICADO_RET, 
PERSONAL.ID_DE_CARGO,PERSONAL.ACTA_POSESION,
PERSONAL.FECHA_ACTA_POSESION,
CARGOS.NOMBRE_DEL_CARGO, 
CA.GRADO,
SALARIO_BASE_IBC
HAVING NOVEDADES.ID_DE_CONCEPTO='404' 
AND NOVEDADES.VALOR=1 
AND HISTORICOS.COMPANIA=s$compania$s
AND HISTORICOS.ANO=s$ano$s
AND HISTORICOS.MES=s$mes$s 
AND HISTORICOS.PERIODO=s$periodo$s
AND HISTORICOS.ID_DE_EMPLEADO=s$idEmpleado$s) 