#GENERAL
PR_MANEJA_PREFACTURACION=MANEJA PREFACTURACIÓN
PR_PERCERTRETENCION=PERIODO DE CERTIFICADOS DE RETENCI\u00D3N
PR_MANEJA_720=APLICA RESOLUCION CRA 720
PR_PERIODO_INICIO_720=PERIODO INICIO RES 720 ASEO
PR_CICLO_EXCLUIDO_720=RES 720 CICLO EXCLUIDO
PR_UNIDADES_INDEPENDIENTES=MANEJA UNIDADES INDEPENDIENTES
PR_MANEJA_RIEGO=FACTURACION DE RIEGO
PR_MANEJA_TERCERIZADO=MANEJA PROCESO TERCERIZADO
PR_DESACTIVA_URBANO=PERMITE DESACTIVAR ASEO URBANO
PR_CAMBIAR_NOMBRE_ACUEDUCTO=CAMBIAR NOMBRE SERVICIO ACUEDUCTO
PR_NOMBRE_ACUEDUCTO=NOMBRE SERVICIO A REMPLAZAR ACUEDUCTO
PR_UNIDAD_ACUEDUCTO=UNIDAD PARA ACUEDUCTO
PR_CAMBIAR_NOMBRE_ALCANTARILLADO=CAMBIAR NOMBRE SERVICIO ALCANTARILLADO
PR_NOMBRE_ALCANTARILLADO=NOMBRE SERVICIO A REMPLAZAR ALCANTARILLADO
PR_UNIDAD_ALCANTARILLADO=UNIDAD PARA ALCANTARILLADO
PR_CAMBIAR_NOMBRE_ASEO=CAMBIAR NOMBRE SERVICIO ASEO
PR_NOMBRE_ASEO=NOMBRE SERVICIO A REMPLAZAR ASEO
PR_UNIDAD_ASEO=UNIDAD PARA ASEO
PR_CAMBIAR_NOMBRE_ALUMBRADO=CAMBIAR NOMBRE SERVICIO ALUMBRADO
PR_NOMBRE_ALUMBRADO=NOMBRE SERVICIO A REMPLAZAR ALUMBRADO
PR_MANEJA_RIEGO=FACTURACION DE RIEGO
PR_APLICA_RES_151=APLICA RESOLUCIÓN 151 DEL 2001
PR_DESVIACION_SITIO=MANEJA DESVIACION SIGNIFICATIVA EN SITIO
PR_BORRA_COMENTARIOS=PERMITE BORRAR COMENTARIOS
PR_USO_ESPECIAL_ALUMBRADO=USO ESPECIAL PARA ALUMBRADO
PR_USO_ESPECIAL_CAR=USO ESPECIAL PARA CAR
PR_SEPARAR_ALUMBRADO=SEPARAR CATEGORIA DE ALUMBRADO
PR_GRUPO_MODIFICADOR=GRUPO MODIFICACIONES USUARIO
PR_MANEJA_TERCERIZADO=MANEJA PROCESO TERCERIZADO
PR_CONCEPTOS_EXTERNOS=MANEJO CONCEPTOS EXTERNOS
PR_ASEO_POR_PESO=COBRAR ASEO POR PESO
PR_TRAMO_EXCEDENTE=MANEJA TRAMO EXCEDENTE
PR_MANEJA351=MANEJA RES/ 351
PR_SUB_SOBRE_DESHABITADOS=MANEJA SUBSIDIO Y SOBREPRECIO A DESHABITADOS
PR_CAMBIO_ESTADO=MANEJA FECHA CAMBIO ESTADO EN INF. CALCULO
PR_MODIFICA_INF_CALCULO=CONTROLA MODIFICADORES INFORMACION DE CALCULO
PR_HISTORICOS_AFORO=MANEJA HISTORICOS DE PROBLEMAS AFORO
PR_ANALISIS_FISICOQUIMICO=MANEJA ANÁLISIS FISICOQUÍMICO-BACTERIOLÓGICO
PR_MANEJA_INTERES_RECARGO=MANEJA INTERES Y RECARGO POR TARIFA
PR_MANEJA_PORCE_SUB_CONT_FACTURA=MANEJA PORCENTAJE DE SUBS. Y CONTR. EN FACTURA
PR_COBRAR_ASEO_PESO=COBRAR ASEO POR PESO
PR_DESC_METRAJE_ACU=DESCONTAR METRAJE ACUEDUCTO
PR_TARIFAS_PROPIAS=VISUALIZA TARIFAS PROPIAS
PR_GRUPO_MODIFICADOR=GRUPO MODIFICACIONES USUARIO
PR_NOVEDADES_EXTERNAS=PERMITE CARGAR Y RECAUDAR NOVEDADES EXTERNAS
PR_OBLIGATORIOS_USUARIO=CAMPOS REQUERIDOS AL REGISTRO DE USUARIO
PR_SINCRONIZAR_FRECUENCIA=SINCRONIZAR FRECUENCIA DE RECOLECCION
PR_TARIFA668=APLICA CONCEPTO 668 DE 2011
PR_CLASIFICACION668=CLASIFICACIONES SUPERSERVICIOS CON 668 DE 2011
PR_HOGAR_COMUNITARIO_TARIFAS=CONTROLA HOGAR COMUNITARIO DESDE TARIFAS
PR_ASEODESH_COMPONENTE=MANEJA ASEO DESHABITADO POR COMPONENTES
PR_SUBSOBRE_TASA_AMB=MANEJA SUBSIDIO Y SOBREPRECIO TASAS AMBIENTALES
PR_RECARGO_SEGUNDAFECHA_USOESTRATO=MANEJA RECARGO SEGUNDA FECHA POR USO Y ESTRATO
PR_TARIFA_MANUAL720=RES 720 TARIFAS MANUALES
PR_PROGRESIVIDAD720=RES 720 APLICA PROGRESIVIDAD
PR_PERIODO_CONF_PGR720=RES 720 PERIODO CONFIGURACION PROGRESIVIDAD
PR_PROGRESIVIDAD_VARIADA720=RES 720 PROGRESIVIDAD VARIADA
PR_RES688=APLICA RESOLUCION 688 DE AC Y ALC
PR_MANPREFACTURACION=MANEJA PREFACTURACIÓN
PR_TAMANOCHEQUE=PERMITE ELEGIR TAMAÑO LETRA CHEQUE
PR_PRESENTAR_EQUI_2=PRESENTAR CÓDIGO EQUIVALENTE 2
PR_COMPROBANTEPPTAL_VENCIMIENTO=MANEJA VENCIMIENTO ULTIMO DIA DEL AÑO
PR_MANEJA_PREFACTURACION=MANEJA PREFACTURACIÓN
PR_NUMERO_MAXIMO_CONCEPTOS=NUMERO MAXIMO CONCEPTOS
PR_GRUPOS_MODIFICADORES_DEUDA=GRUPOS MODIFICADORES DEUDA
PR_ANO_MX_PRESCRIPCION=AÑO MAXIMO DE PRESCRIPCION
PR_PROCESO_UNICO_CRITICA_DESVIACION=PROCESO UNICO DE CRITICA Y DESVIACIÓN
PR_CONFIGURA_IDENTIFICACION_EVALUACION=CONFIGURA IDENTIFICACIÓN, PREPARACIÓN Y EVALUACIÓN DEL PROYECTO