MERGE INTO CONSULTAS FIN USING (SELECT '002064AvanceFisicoCuatrenioTun' INFORME ,TO_CLOB(q'[SELECT AVANCE_FISICO.AVANCE_PDM,
  AVANCE_FISICO.EJE,
  AVANCE_FISICO.NOMBRE_EJE,
  AVANCE_FISICO.AVANCE_EJE,
  AVANCE_FISICO.POLITICA,
  AVANCE_FISICO.NOMBRE_POLITICA,
  CASE
    WHEN AVANCE_POLITICA IS NULL
    THEN 'NP'
    ELSE TO_CHAR(AVANCE_POLITICA)
  END AS AVANCE_POL,
  AVANCE_FISICO.PROGRAMA,
  AVANCE_FISICO.NOMBRE_PROGRAMA,
  CASE
    WHEN AVANCE_PROGRAMA IS NULL
    THEN 'NP'
    ELSE TO_CHAR(AVANCE_PROGRAMA)
  END AS AVANCE_PROG,
  AVANCE_FISICO.SUBPROGRAMA,
  AVANCE_FISICO.NOMBRE_SUBPROGRAMA,
  CASE
    WHEN AVANCE_SUBPROGRAMA IS NULL
    THEN 'NP'
    ELSE TO_CHAR(AVANCE_SUBPROGRAMA)
  END AS AVANCE_SUBP,
  AVANCE_FISICO.COD_INDICADOR_PRODUCTO,
  AVANCE_FISICO.DESCRIPCION_INDICADOR,
  AVANCE_FISICO.LB,
  AVANCE_FISICO.META_CUATRENIO,
  AVANCE_FISICO.TIPO_META_INDICADOR,
  AVANCE_FISICO.REFERENTE,
  AVANCE_FISICO.AVANCE_VIG1,
  AVANCE_FISICO.AVANCE_VIG2,
  AVANCE_FISICO.AVANCE_VIG3,
  AVANCE_FISICO.AVANCE_VIG4,
  CASE
    WHEN PORCENTAJE_AVANCE IS NULL
    THEN 'NP'
    ELSE TO_CHAR(PORCENTAJE_AVANCE)
  END AS PORC_AVANCE
FROM AVANCE_FISICO
GROUP BY AVANCE_FISICO.AVANCE_PDM,
  AVANCE_FISICO.EJE,
  AVANCE_FISICO.NOMBRE_EJE,
  AVANCE_FISICO.AVANCE_EJE,
  AVANCE_FISICO.POLITICA,
  AVANCE_FISICO.NOMBRE_POLITICA,
  CASE
    WHEN AVANCE_POLITICA IS NULL
    THEN 'NP'
    ELSE TO_CHAR(AVANCE_POLITICA)
  END,
  AVANCE_FISICO.PROGRAMA,
  AVANCE_FISICO.NOMBRE_PROGRAMA,
  CASE
    WHEN AVANCE_PROGRAMA IS NULL
    THEN 'NP'
    ELSE TO_CHAR(AVANCE_PROGRAMA)
  END,
  AVANCE_FISICO.SUBPROGRAMA,
  AVANCE_FISICO.NOMBRE_SUBPROGRAMA,
  CASE
    WHEN AVANCE_SUBPROGRAMA IS NULL
    THEN 'NP'
    ELSE TO_CHAR(AVANCE_SUBPROGRAMA)
  END,
  AVANCE_FISICO.COD_INDICADOR_PRODUCTO,
  AVANCE_FISICO.DESCRIPCION_INDICADOR,
  AVANCE_FISICO.LB,
  AVANCE_FISICO.META_CUATRENIO,
  AVANCE_FISICO.TIPO_META_INDICADOR,
  AVANCE_FISICO.REFERENTE,
  AVANCE_FISICO.AVANCE_VIG1,
  AVANCE_FISICO.AVANCE_VIG2,
  AVANCE_FISICO.AVANCE_VIG3,
  AVANCE_FISICO.AVANCE_VIG4,
  CASE
    WHEN PORCENTAJE_AVANCE IS NULL
    THEN 'NP'
    ELSE TO_CHAR(PORCENTAJE_AVANCE)
  END
ORDER BY AVANCE_FISICO.EJE,
  AVANCE_FISICO.POLITICA,
  AVANCE_FISICO.PROGRAMA,
  AVANCE_FISICO.SUBPROGRAMA,
  AVANCE_FISICO.COD_INDICADOR_PRODUCTO]') CONSULTA, 67 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);