create or replace PACKAGE PCK_NOMINA_SEGSOCI AS 

PROCEDURE PR_CALCULARAUTOLIQUIDACION 
  (
    UN_COMPANIA VARCHAR2
  );

PROCEDURE PR_PARAFISCALES 
  (
    UN_COMPANIA VARCHAR2
  );

PROCEDURE PR_REVISAR_LNR_PERIODO
  (
    UN_COMPANIA VARCHAR2
  );

PROCEDURE PR_SUMACONCEPTOSPARAFISCALES
  (
    UN_COMPANIA   IN PCK_SUBTIPOS.TI_COMPANIA
  );

PROCEDURE PR_SUMACONCEPTOSIBC
  (
    UN_COMPANIA VARCHAR2
  );

PROCEDURE PR_SUMACONCEPTOSIBCAC
  (
    UN_COMPANIA VARCHAR2
  );

-- TICKET 7736122 ECABRERA: SE CREA FUNCION PARA SUMATORIA CONCEPTOS CLASE REMUNERACION CON INDICADOR DE REPORTEEPS
FUNCTION FC_SUMAREMUNSS
(
UN_COMPANIA VARCHAR2
) RETURN NUMBER;
-- TICKET 7736122 FIN --

FUNCTION FC_PORCENRIESGO
  (
    UN_COMPANIA   VARCHAR2,
    UN_IDEMPLEADO NUMBER
  )
RETURN NUMBER;

FUNCTION FC_APORTE
  (
    UN_IBC         NUMBER, 
    UN_DIAS        NUMBER, 
    UN_DECIMALES   NUMBER, 
    UN_PORCENTAJE  NUMBER
  )
RETURN NUMBER;

FUNCTION FC_BASE
  (
    UN_IBC   		  NUMBER,
    UN_DIAS 		  NUMBER,
    UN_DECIMALES 	NUMBER,
    UN_FRACCION   BOOLEAN DEFAULT FALSE,
    UN_PLANO_SOI  BOOLEAN DEFAULT FALSE
  )
RETURN NUMBER;

-- TICKET 7733203 ECABRERA: SE CREA FUNCION PARA SUMATORIA ONCEPTOS EN UN INTERVALO CON INDICADOR DE REPORTEEPS
FUNCTION FC_SUMACONCEPTOS
(
UN_COMPANIA 	VARCHAR2,
UN_CONCEPTO_INI NUMBER,
UN_CONCEPTO_FIN NUMBER,
UN_INDSS    	BOOLEAN
) RETURN NUMBER;
-- TICKET 7733203 FIN --

FUNCTION FC_FSP_ADI_REFORMA
  (
    UN_COMPANIA   IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_ANO        IN PCK_SUBTIPOS.TI_ANIO,
    UN_ESTADO     IN VARCHAR2,
    UN_BASECN112  IN NUMBER
  ) RETURN NUMBER;
END PCK_NOMINA_SEGSOCI;