create or replace PACKAGE PCK_SERVICIOS_PUBLICOS_COM7 AS 
--Paquete únicamente para la función de cálculo de servicios públicos
TYPE PARAMETRO_VALOR IS RECORD (VALOR PARAMETRO.VALOR%TYPE);
TYPE TTARIFAS IS RECORD (
  COMPANIA                    SP_TARIFAS.COMPANIA%TYPE
  ,ANO                        SP_TARIFAS.ANO%TYPE 
  ,PERIODO                    SP_TARIFAS.PERIODO%TYPE
  ,USO                        SP_TARIFAS.USO%TYPE
  ,CARGOFIJO                  SP_TARIFAS.CARGOFIJO%TYPE
  ,METROS_NO_COBRADOS         SP_TARIFAS.METROS_NO_COBRADOS%TYPE
  ,CONSUMOBASICO              SP_TARIFAS.CONSUMOBASICO%TYPE
  ,CONSUMOCOMPLEMENTARIO      SP_TARIFAS.CONSUMOCOMPLEMENTARIO%TYPE
  ,CONSUMOSUNTUARIO           SP_TARIFAS.CONSUMOSUNTUARIO%TYPE
  ,M3SINMEDICION              SP_TARIFAS.M3SINMEDICION%TYPE
  ,CONSUMOPROM_USOS_ESTRATOS  SP_TARIFAS.CONSUMOPROM_USOS_ESTRATOS%TYPE
  ,SINMEDICION                SP_TARIFAS.SINMEDICION%TYPE
  ,SINMEDICIONALC             SP_TARIFAS.SINMEDICIONALC%TYPE
  ,SUBSINMEDICION             SP_TARIFAS.SUBSINMEDICION%TYPE
  ,SOBRESINMEDICION           SP_TARIFAS.SOBRESINMEDICION%TYPE
  ,SUBALCSINMEDICION          SP_TARIFAS.SUBALCSINMEDICION%TYPE
  ,SOBREALCSINMEDICION        SP_TARIFAS.SOBREALCSINMEDICION%TYPE
  ,PRECIO_METROS_NO_COBRADOS  SP_TARIFAS.PRECIO_METROS_NO_COBRADOS%TYPE
  ,TARIFABASICO               SP_TARIFAS.TARIFABASICO%TYPE
  ,TARIFACOMPLEMENTARIO       SP_TARIFAS.TARIFACOMPLEMENTARIO%TYPE
  ,TARIFASUNTUARIO            SP_TARIFAS.TARIFASUNTUARIO%TYPE
  ,VALORTASAAMBIENTALAC       SP_TARIFAS.VALORTASAAMBIENTALAC%TYPE
  ,SUB_TASAAMBIENTALAC        SP_TARIFAS.SUB_TASAAMBIENTALAC%TYPE
  ,SOBRE_TASAAMBIENTALAC      SP_TARIFAS.SOBRE_TASAAMBIENTALAC%TYPE
  ,COSTOM3AC                  SP_TARIFAS.COSTOM3AC%TYPE
  ,FIJOALCANTARILLADO         SP_TARIFAS.FIJOALCANTARILLADO%TYPE
  ,ALCBASICO                  SP_TARIFAS.ALCBASICO%TYPE
  ,ALCCOMPLEMENTARIO          SP_TARIFAS.ALCCOMPLEMENTARIO%TYPE
  ,ALCSUNTUARIO               SP_TARIFAS.ALCSUNTUARIO%TYPE
  ,VALORTASAAMBIENTALALC      SP_TARIFAS.VALORTASAAMBIENTALALC%TYPE
  ,SUB_TASAAMBIENTALALC       SP_TARIFAS.SUB_TASAAMBIENTALALC%TYPE
  ,SOBRE_TASAAMBIENTALALC     SP_TARIFAS.SOBRE_TASAAMBIENTALALC%TYPE
  ,COSTOM3AL                  SP_TARIFAS.COSTOM3AL%TYPE
  ,PORCALCANTARILLADO         SP_TARIFAS.PORCALCANTARILLADO%TYPE
  ,SUBBASICO                  SP_TARIFAS.SUBBASICO%TYPE
  ,SUBCOMPLEMENTARIO          SP_TARIFAS.SUBCOMPLEMENTARIO%TYPE
  ,SOBREFIJO                  SP_TARIFAS.SOBREFIJO%TYPE
  ,SOBREBASICO                SP_TARIFAS.SOBREBASICO%TYPE
  ,SOBRECOMPLEMENTARIO        SP_TARIFAS.SOBRECOMPLEMENTARIO%TYPE
  ,SOBRESUNTUARIO             SP_TARIFAS.SOBRESUNTUARIO%TYPE
  ,SUBFIJO                    SP_TARIFAS.SUBFIJO%TYPE
  ,SUBSUNTUARIO               SP_TARIFAS.SUBSUNTUARIO%TYPE
  ,SUBALCBASICO               SP_TARIFAS.SUBALCBASICO%TYPE
  ,SUBALCCOMPLEMENTARIO       SP_TARIFAS.SUBALCCOMPLEMENTARIO%TYPE
  ,SUBALCSUNTUARIO            SP_TARIFAS.SUBALCSUNTUARIO%TYPE
  ,SOBREALCBASICO             SP_TARIFAS.SOBREALCBASICO%TYPE
  ,SOBREALCCOMPLEMENTARIO     SP_TARIFAS.SOBREALCCOMPLEMENTARIO%TYPE
  ,SOBREALCSUNTUARIO          SP_TARIFAS.SOBREALCSUNTUARIO%TYPE
  ,SOBREALCFIJO               SP_TARIFAS.SOBREALCFIJO%TYPE
  ,SUBALCFIJO                 SP_TARIFAS.SUBALCFIJO%TYPE
  ,CCS_720                    SP_TARIFAS.CCS_720%TYPE
  ,SUBCCS_720                 SP_TARIFAS.SUBCCS_720%TYPE
  ,SOBRECCS_720               SP_TARIFAS.SOBRECCS_720%TYPE
  ,CBLS_720                   SP_TARIFAS.CBLS_720%TYPE
  ,SUBCBLS_720                SP_TARIFAS.SUBCBLS_720%TYPE
  ,SOBRECBLS_720              SP_TARIFAS.SOBRECBLS_720%TYPE
  ,CLUS_720                   SP_TARIFAS.CLUS_720%TYPE
  ,SUBCLUS_720                SP_TARIFAS.SUBCLUS_720%TYPE
  ,SOBRECLUS_720              SP_TARIFAS.SOBRECLUS_720%TYPE
  ,CRT_720                    SP_TARIFAS.CRT_720%TYPE
  ,SUBCRT_720                 SP_TARIFAS.SUBCRT_720%TYPE
  ,SOBRECRT_720               SP_TARIFAS.SOBRECRT_720%TYPE
  ,CDF_720                    SP_TARIFAS.CDF_720%TYPE
  ,SUBCDF_720                 SP_TARIFAS.SUBCDF_720%TYPE
  ,SOBRECDF_720               SP_TARIFAS.SOBRECDF_720%TYPE
  ,CTL_720                    SP_TARIFAS.CTL_720%TYPE
  ,SUBCTL_720                 SP_TARIFAS.SUBCTL_720%TYPE
  ,SOBRECTL_720               SP_TARIFAS.SOBRECTL_720%TYPE
  ,VBA_720                    SP_TARIFAS.VBA_720%TYPE
  ,SUBVBA_720                 SP_TARIFAS.SUBVBA_720%TYPE
  ,SOBREVBA_720               SP_TARIFAS.SOBREVBA_720%TYPE
  ,DES_CCS_720                SP_TARIFAS.DES_CCS_720%TYPE
  ,DES_SUBCCS_720             SP_TARIFAS.DES_SUBCCS_720%TYPE
  ,DES_SOBRECCS_720           SP_TARIFAS.DES_SOBRECCS_720%TYPE
  ,DES_CBLS_720     					SP_TARIFAS.DES_CBLS_720%TYPE		
  ,DES_SUBCBLS_720	    			SP_TARIFAS.DES_SUBCBLS_720%TYPE
  ,DES_SOBRECBLS_720		    	SP_TARIFAS.DES_SOBRECBLS_720%TYPE
  ,DES_CLUS_720					      SP_TARIFAS.DES_CLUS_720%TYPE
  ,DES_SUBCLUS_720				    SP_TARIFAS.DES_SUBCLUS_720%TYPE
  ,DES_SOBRECLUS_720			    SP_TARIFAS.DES_SOBRECLUS_720%TYPE
  ,DES_CRT_720					      SP_TARIFAS.DES_CRT_720%TYPE
  ,DES_SUBCRT_720				      SP_TARIFAS.DES_SUBCRT_720%TYPE
  ,DES_SOBRECRT_720				    SP_TARIFAS.DES_SOBRECRT_720%TYPE
  ,DES_CDF_720					      SP_TARIFAS.DES_CDF_720%TYPE
  ,DES_SUBCDF_720				      SP_TARIFAS.DES_SUBCDF_720%TYPE
  ,DES_SOBRECDF_720				    SP_TARIFAS.DES_SOBRECDF_720%TYPE
  ,DES_CTL_720					      SP_TARIFAS.DES_CTL_720%TYPE
  ,DES_SUBCTL_720				      SP_TARIFAS.DES_SUBCTL_720%TYPE
  ,DES_SOBRECTL_720				    SP_TARIFAS.DES_SOBRECTL_720%TYPE
  ,DES_VBA_720					      SP_TARIFAS.DES_VBA_720%TYPE
  ,DES_SUBVBA_720				      SP_TARIFAS.DES_SUBVBA_720%TYPE
  ,DES_SOBREVBA_720				    SP_TARIFAS.DES_SOBREVBA_720%TYPE
  ,VALORFREC1                 SP_TARIFAS.VALORFREC1%TYPE
  ,VALORFREC2                 SP_TARIFAS.VALORFREC2%TYPE
  ,VALORFREC3                 SP_TARIFAS.VALORFREC3%TYPE
  ,VALORFREC4                 SP_TARIFAS.VALORFREC4%TYPE
  ,VALORFREC5                 SP_TARIFAS.VALORFREC5%TYPE
  ,VALORFREC6                 SP_TARIFAS.VALORFREC6%TYPE
  ,VALORFREC7                 SP_TARIFAS.VALORFREC7%TYPE
  ,VALORFREC8                 SP_TARIFAS.VALORFREC8%TYPE
  ,VALORFREC9                 SP_TARIFAS.VALORFREC9%TYPE
  ,SUBFREC1                   SP_TARIFAS.SUBFREC1%TYPE
  ,SUBFREC2                   SP_TARIFAS.SUBFREC2%TYPE
  ,SUBFREC3                   SP_TARIFAS.SUBFREC3%TYPE
  ,SUBFREC4                   SP_TARIFAS.SUBFREC4%TYPE
  ,SUBFREC5                   SP_TARIFAS.SUBFREC5%TYPE
  ,SUBFREC6                   SP_TARIFAS.SUBFREC6%TYPE
  ,SUBFREC7                   SP_TARIFAS.SUBFREC7%TYPE
  ,SUBFREC8                   SP_TARIFAS.SUBFREC8%TYPE
  ,SUBFREC9                   SP_TARIFAS.SUBFREC9%TYPE
  ,SOBREFREC1                 SP_TARIFAS.SOBREFREC1%TYPE
  ,SOBREFREC2                 SP_TARIFAS.SOBREFREC2%TYPE
  ,SOBREFREC3                 SP_TARIFAS.SOBREFREC3%TYPE
  ,SOBREFREC4                 SP_TARIFAS.SOBREFREC4%TYPE
  ,SOBREFREC5                 SP_TARIFAS.SOBREFREC5%TYPE
  ,SOBREFREC6                 SP_TARIFAS.SOBREFREC6%TYPE
  ,SOBREFREC7                 SP_TARIFAS.SOBREFREC7%TYPE
  ,SOBREFREC8                 SP_TARIFAS.SOBREFREC8%TYPE
  ,SOBREFREC9                 SP_TARIFAS.SOBREFREC9%TYPE

  ,ASEODOMICILIARIO           SP_TARIFAS.ASEODOMICILIARIO%TYPE
  ,ASEOCONSUMO                SP_TARIFAS.ASEOCONSUMO%TYPE
  ,RECTRANSBARRIDOLIMP        SP_TARIFAS.RECTRANSBARRIDOLIMP%TYPE
  ,DISPFINALBARRIDOLIMP       SP_TARIFAS.DISPFINALBARRIDOLIMP%TYPE
  ,PESOASEO1                  SP_TARIFAS.PESOASEO1%TYPE
  ,ASEOUNICO                  SP_TARIFAS.ASEOUNICO%TYPE
  ,TARIFAASEO1                SP_TARIFAS.TARIFAASEO1%TYPE
  ,SOBREASEOTARIFA1           SP_TARIFAS.SOBREASEOTARIFA1%TYPE
  ,SUBASEOTARIFA1             SP_TARIFAS.SUBASEOTARIFA1%TYPE
  ,PESOASEO2                  SP_TARIFAS.PESOASEO2%TYPE
  ,TARIFAASEO2                SP_TARIFAS.TARIFAASEO2%TYPE
  ,SOBREASEOTARIFA2           SP_TARIFAS.SOBREASEOTARIFA2%TYPE
  ,SUBASEOTARIFA2             SP_TARIFAS.SUBASEOTARIFA2%TYPE
  ,PESOASEO3                  SP_TARIFAS.PESOASEO3%TYPE
  ,TARIFAASEO3                SP_TARIFAS.TARIFAASEO3%TYPE
  ,SOBREASEOTARIFA3           SP_TARIFAS.SOBREASEOTARIFA3%TYPE
  ,SUBASEOTARIFA3             SP_TARIFAS.SUBASEOTARIFA3%TYPE
  ,ASEOBARRIDO                SP_TARIFAS.ASEOBARRIDO%TYPE
  ,TRAMOEXCEDENTE             SP_TARIFAS.TRAMOEXCEDENTE%TYPE
  ,DES_ASEOUNICO              SP_TARIFAS.DES_ASEOUNICO%TYPE
  ,DES_ASEDOMICILIARIO        SP_TARIFAS.DES_ASEDOMICILIARIO%TYPE
  ,DES_ASEBARRIDO             SP_TARIFAS.DES_ASEBARRIDO%TYPE
  ,DES_ASEOCONSUMO            SP_TARIFAS.DES_ASEOCONSUMO%TYPE
  ,ASEODESHABITADOS           SP_TARIFAS.ASEODESHABITADOS%TYPE
  ,DESCSEPARACIONENFUENTE     SP_TARIFAS.DESCSEPARACIONENFUENTE%TYPE
  ,DESCNOPUERTAPUERTA         SP_TARIFAS.DESCNOPUERTAPUERTA%TYPE
  ,DES_TRAMOEXCEDENTE         SP_TARIFAS.DES_TRAMOEXCEDENTE%TYPE
  ,COSTOM3AS                  SP_TARIFAS.COSTOM3AS%TYPE
  ,COSTOM3REC                 SP_TARIFAS.COSTOM3REC%TYPE
  ,COSTOM3PN                  SP_TARIFAS.COSTOM3PN%TYPE
  ,SUBASEOBARRIDO             SP_TARIFAS.SUBASEOBARRIDO%TYPE
  ,SOBREASEOBARRIDO           SP_TARIFAS.SOBREASEOBARRIDO%TYPE
  ,SUBTRAMOEX                 SP_TARIFAS.SUBTRAMOEX%TYPE
  ,SOBRETRAMOEX               SP_TARIFAS.SOBRETRAMOEX%TYPE
  ,DES_SUBASEOUNICO           SP_TARIFAS.DES_SUBASEOUNICO%TYPE
  ,DES_SOBREASEOUNICO         SP_TARIFAS.DES_SOBREASEOUNICO%TYPE
  ,SOBREASEOUNICO             SP_TARIFAS.SOBREASEOUNICO%TYPE
  ,SUBASEOUNICO               SP_TARIFAS.SUBASEOUNICO%TYPE
  ,SUBASEODOMICILIARIO        SP_TARIFAS.SUBASEODOMICILIARIO%TYPE
  ,SOBREASEODOMICILIARIO      SP_TARIFAS.SOBREASEODOMICILIARIO%TYPE
  ,SUBASEOCONSUMO             SP_TARIFAS.SUBASEOCONSUMO%TYPE
  ,SOBREASEOCONSUMO           SP_TARIFAS.SOBREASEOCONSUMO%TYPE
  ,DES_SUBASEDOMICILIARIO     SP_TARIFAS.DES_SUBASEDOMICILIARIO%TYPE
  ,DES_SOBREASEDOMICILIARIO   SP_TARIFAS.DES_SOBREASEDOMICILIARIO%TYPE
  ,DES_SUBASEBARRIDO          SP_TARIFAS.DES_SUBASEBARRIDO%TYPE
  ,DES_SOBREASEBARRIDO        SP_TARIFAS.DES_SOBREASEBARRIDO%TYPE
  ,DES_SUBASEOCONSUMO         SP_TARIFAS.DES_SUBASEOCONSUMO%TYPE
  ,DES_SOBREASEOCONSUMO       SP_TARIFAS.DES_SOBREASEOCONSUMO%TYPE
  ,DES_SUBTRAMOEXCEDENTE      SP_TARIFAS.DES_SUBTRAMOEXCEDENTE%TYPE
  ,DES_SOBRETRAMOEXCEDENTE    SP_TARIFAS.DES_SOBRETRAMOEXCEDENTE%TYPE
  ,SUBASEO_DESHABITADO        SP_TARIFAS.SUBASEO_DESHABITADO%TYPE
  ,SOBREASEO_DESHABITADO      SP_TARIFAS.SOBREASEO_DESHABITADO%TYPE
  ,COSTOFIJOAC                SP_TARIFAS.COSTOFIJOAC%TYPE
  ,COSTOFIJOAL                SP_TARIFAS.COSTOFIJOAL%TYPE
  ,USOSUPERSERVICIOS          SP_TARIFAS.USOSUPERSERVICIOS%TYPE
  ,POR_RECARGO668             SP_TARIFAS.POR_RECARGO668%TYPE
  ,RECARGOFIJOMORA            SP_TARIFAS.RECARGOFIJOMORA%TYPE
  ,PORCENTAJEFECHA2           SP_TARIFAS.PORCENTAJEFECHA2%TYPE
  ,RECARGOFIJO                SP_TARIFAS.RECARGOFIJO%TYPE

  ,CCS							          SP_TARIFAS.COSTO_CCS_720%TYPE
  ,CBLS							          SP_TARIFAS.COSTO_CBLS_720%TYPE
  ,CLUS							          SP_TARIFAS.COSTO_CLUS_720%TYPE
  ,CRT							          SP_TARIFAS.COSTO_CRT_720%TYPE
  ,CDF							          SP_TARIFAS.COSTO_CDF_720%TYPE
  ,CTL							          SP_TARIFAS.COSTO_CTL_720%TYPE
  ,TRBL							          SP_TARIFAS.COSTO_TRBL_720%TYPE
  ,TRLU							          SP_TARIFAS.COSTO_TRLU_720%TYPE
  ,TRRA							          SP_TARIFAS.COSTO_TRRA_720%TYPE
  ,VBA							          SP_TARIFAS.COSTO_VBA_720%TYPE
  ,FCS							          SP_TARIFAS.COSTO_FCS_720%TYPE
  ,FCS1							          SP_TARIFAS.COSTO_FCS1_720%TYPE
  );

TYPE TUSUARIO IS RECORD (
   COMPANIA                   SP_USUARIO.COMPANIA%TYPE 
  ,CICLO                      SP_USUARIO.CICLO%TYPE
  ,ANO                        SP_USUARIO.ANO%TYPE
  ,PERIODO                    SP_USUARIO.PERIODO%TYPE
  ,CODIGORUTA                 SP_USUARIO.CODIGORUTA%TYPE
  ,CODIGOINTERNO              SP_USUARIO.CODIGOINTERNO%TYPE
  ,USO                        SP_USUARIO.USO%TYPE
  ,ESTRATO                    SP_USUARIO.ESTRATO%TYPE
  ,CONSUMOMANUAL              SP_USUARIO.CONSUMOMANUAL%TYPE
  ,BANCOPERPROCESO            SP_USUARIO.BANCOPERPROCESO%TYPE
  ,FIMM                       SP_USUARIO.FIMM%TYPE
  ,TIPOLECTURA                SP_USUARIO.TIPOLECTURA%TYPE
  ,ESTADO                     SP_USUARIO.ESTADO%TYPE
  ,PERIODOSNOCOBROFAC         SP_USUARIO.PERIODOSNOCOBROFAC%TYPE
  ,CONSUMO1                   SP_USUARIO.CONSUMO1%TYPE
  ,CONSUMO2                   SP_USUARIO.CONSUMO2%TYPE
  ,CONSUMO3                   SP_USUARIO.CONSUMO3%TYPE
  ,CONSUMO4                   SP_USUARIO.CONSUMO4%TYPE
  ,CONSUMO5                   SP_USUARIO.CONSUMO5%TYPE
  ,CONSUMO6                   SP_USUARIO.CONSUMO6%TYPE
  ,PROBLEMALECTURA            SP_USUARIO.PROBLEMALECTURA%TYPE
  ,LECTURA                    SP_USUARIO.LECTURA%TYPE        
  ,LECTURA1                   SP_USUARIO.LECTURA1%TYPE
  ,LECTURA2                   SP_USUARIO.LECTURA2%TYPE
  ,LECTURA3                   SP_USUARIO.LECTURA3%TYPE
  ,LECTURA4                   SP_USUARIO.LECTURA4%TYPE
  ,LECTURA5                   SP_USUARIO.LECTURA5%TYPE
  ,LECTURA6                   SP_USUARIO.LECTURA6%TYPE
  ,CHAPETAS                   SP_USUARIO.CHAPETAS%TYPE
  ,INDDESHABITADO             SP_USUARIO.INDDESHABITADO%TYPE       
  ,TIPOCALCULO                SP_USUARIO.TIPOCALCULO%TYPE
  ,CRITICACONSUMO             SP_USUARIO.CRITICACONSUMO%TYPE
  ,ANOCAMBIOMEDIDOR           SP_USUARIO.ANOCAMBIOMEDIDOR%TYPE
  ,CONSUMOMEDIDORANT          SP_USUARIO.CONSUMOMEDIDORANT%TYPE
  ,INDMEDCAMBIADO             SP_USUARIO.INDMEDCAMBIADO%TYPE
  ,PORCENTAJEAPLICAR          SP_USUARIO.PORCENTAJEAPLICAR%TYPE
  ,CONSUMOACU                 SP_USUARIO.CONSUMOACU%TYPE
  ,ACUMULADO                  SP_USUARIO.ACUMULADO%TYPE
  ,ACUMULADOPER               SP_USUARIO.ACUMULADOPER%TYPE
  ,PERIODOSINLECTURA          SP_USUARIO.PERIODOSINLECTURA%TYPE
  ,INDCALCULADO               SP_USUARIO.INDCALCULADO%TYPE
  ,DESCONTADO                 SP_USUARIO.DESCONTADO%TYPE
  ,CARGOS_FIJOS_CERO          SP_USUARIO.CARGOS_FIJOS_CERO%TYPE
  ,DESVIOSIGNIFICATIVO        SP_USUARIO.DESVIOSIGNIFICATIVO%TYPE
  ,METROSDESVIACION           SP_USUARIO.METROSDESVIACION%TYPE
  ,TOTALIZADOR                SP_USUARIO.TOTALIZADOR%TYPE
  ,NUMERODIGITOS              SP_USUARIO.NUMERODIGITOS%TYPE
  ,PERIODOCAMBIOMEDIDOR       SP_USUARIO.PERIODOCAMBIOMEDIDOR%TYPE
  ,ACUEDUCTO                  SP_USUARIO.ACUEDUCTO%TYPE
  ,PORMICRO                   SP_USUARIO.PORMICRO%TYPE
  ,INQUILINATOS               SP_USUARIO.INQUILINATOS%TYPE
  ,TOTFACTURAPERACTUAL        SP_USUARIO.TOTFACTURAPERACTUAL%TYPE
  ,TOTFACTURAPAGO2            SP_USUARIO.TOTFACTURAPAGO2%TYPE
  ,INDPREPARADO               SP_USUARIO.INDPREPARADO%TYPE
  ,BANCOPERANTERIOR           SP_USUARIO.BANCOPERANTERIOR%TYPE
  ,PERIODOSATRASO             SP_USUARIO.PERIODOSATRASO%TYPE
  ,CONSUMO                    SP_USUARIO.CONSUMO%TYPE
  ,CONSUMOPROM                SP_USUARIO.CONSUMOPROM%TYPE
  ,CONSUMOALC                 SP_USUARIO.CONSUMOALC%TYPE
  ,CONSUMOBASICO              SP_USUARIO.CONSUMOBASICO%TYPE
  ,CONSUMOCOMPLEMENTARIO      SP_USUARIO.CONSUMOCOMPLEMENTARIO%TYPE
  ,CONSUMOSUNTUARIO           SP_USUARIO.CONSUMOSUNTUARIO%TYPE
  ,CONSUMOBASICOALC           SP_USUARIO.CONSUMOBASICOALC%TYPE
  ,CONSUMOCOMPLEMENTARIOALC   SP_USUARIO.CONSUMOCOMPLEMENTARIOALC%TYPE
  ,CONSUMOSUNTUARIOALC        SP_USUARIO.CONSUMOSUNTUARIOALC%TYPE
  ,ANOENTRADANUEVOUSUARIO     SP_USUARIO.ANOENTRADANUEVOUSUARIO%TYPE
  ,PERENTRADANUEVOUSUARIO     SP_USUARIO.PERENTRADANUEVOUSUARIO%TYPE
  ,SUBSINMEDICION             SP_USUARIO.SUBSINMEDICION%TYPE
  ,SOBRESINMEDICION           SP_USUARIO.SOBRESINMEDICION%TYPE
  ,SUB_TASAAMBIENTALAC        SP_USUARIO.SUB_TASAAMBIENTALAC%TYPE
  ,SOBRE_TASAAMBIENTALAC      SP_USUARIO.SOBRE_TASAAMBIENTALAC%TYPE
  ,COSTOCONSUMOAC             SP_USUARIO.COSTOCONSUMOAC%TYPE
  ,CARGOFIJO                  SP_USUARIO.CARGOFIJO%TYPE
  ,ACSINMEDICION              SP_USUARIO.ACSINMEDICION%TYPE
  ,VALCONSUMO                 SP_USUARIO.VALCONSUMO%TYPE
  ,VALCONSUMOPROM             SP_USUARIO.VALCONSUMOPROM%TYPE
  ,TOTALACUEDUCTO             SP_USUARIO.TOTALACUEDUCTO%TYPE
  ,SUBALCSINMEDICION          SP_USUARIO.SUBALCSINMEDICION%TYPE
  ,SOBREALCSINMEDICION        SP_USUARIO.SOBREALCSINMEDICION%TYPE
  ,SUB_TASAAMBIENTALALC       SP_USUARIO.SUB_TASAAMBIENTALALC%TYPE
  ,COSTOCONSUMOAL             SP_USUARIO.COSTOCONSUMOAL%TYPE
  ,CARGOFIJOAL                SP_USUARIO.CARGOFIJOAL%TYPE
  ,ALSINMEDICION              SP_USUARIO.ALSINMEDICION%TYPE
  ,ALCANTARILLADO             SP_USUARIO.ALCANTARILLADO%TYPE
  ,ASEO                       SP_USUARIO.ASEO%TYPE
  ,SOBRE_TASAAMBIENTALALC     SP_USUARIO.SOBRE_TASAAMBIENTALALC%TYPE
  ,TOTALALCANTARILLADO        SP_USUARIO.TOTALALCANTARILLADO%TYPE
  ,VALORBASICO                SP_USUARIO.VALORBASICO%TYPE
  ,VALORCOMPLEMENTARIO        SP_USUARIO.VALORCOMPLEMENTARIO%TYPE
  ,VALORSUNTUARIO             SP_USUARIO.VALORSUNTUARIO%TYPE
  ,SUBFIJO                    SP_USUARIO.SUBFIJO%TYPE
  ,SUBCONSUMOAC               SP_USUARIO.SUBCONSUMOAC%TYPE
  ,SUBACUEDUCTO               SP_USUARIO.SUBACUEDUCTO%TYPE
  ,SOBREFIJO                  SP_USUARIO.SOBREFIJO%TYPE
  ,SOBRECONSUMOAC             SP_USUARIO.SOBRECONSUMOAC%TYPE
  ,SOBREACUEDUCTO             SP_USUARIO.SOBREACUEDUCTO%TYPE
  ,SUBSIDIO                   SP_USUARIO.SUBSIDIO%TYPE
  ,SOBREPRECIO                SP_USUARIO.SOBREPRECIO%TYPE
  ,VALORALCBASICO             SP_USUARIO.VALORALCBASICO%TYPE
  ,VALORALCCOMPLEMENTARIO     SP_USUARIO.VALORALCCOMPLEMENTARIO%TYPE
  ,VALORALCSUNTUARIO          SP_USUARIO.VALORALCSUNTUARIO%TYPE
  ,SUBFIJOALC                 SP_USUARIO.SUBFIJOALC%TYPE
  ,SUBCONSUMOAL               SP_USUARIO.SUBCONSUMOAL%TYPE
  ,SUBALCANTARILLADO          SP_USUARIO.SUBALCANTARILLADO%TYPE
  ,SOBREALCANTARILLADO        SP_USUARIO.SOBREALCANTARILLADO%TYPE
  ,SOBREFIJOALC               SP_USUARIO.SOBREFIJOALC%TYPE
  ,SOBRECONSUMOAL             SP_USUARIO.SOBRECONSUMOAL%TYPE
  ,TOTALASEO                  SP_USUARIO.TOTALASEO%TYPE
  ,TAFNA_720                  SP_USUARIO.TAFNA_720%TYPE
  ,TAFA_720                   SP_USUARIO.TAFA_720%TYPE
  ,SUBCCS_720                 SP_USUARIO.SUBCCS_720%TYPE
  ,SOBCCS_720                 SP_USUARIO.SOBCCS_720%TYPE
  ,SUBCBLS_720                SP_USUARIO.SUBCBLS_720%TYPE
  ,SOBCBLS_720                SP_USUARIO.SOBCBLS_720%TYPE
  ,SUBCLUS_720                SP_USUARIO.SUBCLUS_720%TYPE
  ,SOBCLUS_720                SP_USUARIO.SOBCLUS_720%TYPE
  ,SUBCRT_720                 SP_USUARIO.SUBCRT_720%TYPE
  ,SOBCRT_720                 SP_USUARIO.SOBCRT_720%TYPE
  ,SUBCDF_720                 SP_USUARIO.SUBCDF_720%TYPE
  ,SOBCDF_720                 SP_USUARIO.SOBCDF_720%TYPE
  ,SUBCTL_720                 SP_USUARIO.SUBCTL_720%TYPE
  ,SOBCTL_720                 SP_USUARIO.SOBCTL_720%TYPE
  ,SUBVBA_720                 SP_USUARIO.SUBVBA_720%TYPE
  ,SOBVBA_720                 SP_USUARIO.SOBVBA_720%TYPE
  ,FRECUENCIAASEOSEMANA       SP_USUARIO.FRECUENCIAASEOSEMANA%TYPE
  ,PESOASEO                   SP_USUARIO.PESOASEO%TYPE
  ,ESTRATOASEO                SP_USUARIO.ESTRATOASEO%TYPE
  ,APARTAMENTO                SP_USUARIO.APARTAMENTO%TYPE
  ,ASEOBARRIDO                SP_USUARIO.ASEOBARRIDO%TYPE
  ,CALCULODESH                SP_USUARIO.CALCULODESH%TYPE
  ,SEPARACIONENFUENTE         SP_USUARIO.SEPARACIONENFUENTE%TYPE
  ,NOPUERTAPUERTA             SP_USUARIO.NOPUERTAPUERTA%TYPE
  ,VDESHABITADO               SP_USUARIO.VDESHABITADO%TYPE
  ,NOTADEBITO                 SP_USUARIO.NOTADEBITO%TYPE
  ,VASEOUNICO                 SP_USUARIO.VASEOUNICO%TYPE
  ,VASEODOMICILIARIO          SP_USUARIO.VASEODOMICILIARIO%TYPE
  ,VASEOBARRIDO               SP_USUARIO.VASEOBARRIDO%TYPE
  ,VASEOCONSUMO               SP_USUARIO.VASEOCONSUMO%TYPE
  ,COSTOREALASEO              SP_USUARIO.COSTOREALASEO%TYPE
  ,SUBBARR_LIM                SP_USUARIO.SUBBARR_LIM%TYPE
  ,SOBBARR_LIM                SP_USUARIO.SOBBARR_LIM%TYPE
  ,SUBMANEJO_REC              SP_USUARIO.SUBMANEJO_REC%TYPE
  ,SOBMANEJO_REC              SP_USUARIO.SOBMANEJO_REC%TYPE
  ,SUBRECOLECCION             SP_USUARIO.SUBRECOLECCION%TYPE
  ,SOBRECOLECCION             SP_USUARIO.SOBRECOLECCION%TYPE
  ,SUBTRAMO                   SP_USUARIO.SUBTRAMO%TYPE
  ,SOBTRAMO                   SP_USUARIO.SOBTRAMO%TYPE
  ,SOBDESHABITADO             SP_USUARIO.SOBDESHABITADO%TYPE
  ,SUBDESHABITADO             SP_USUARIO.SUBDESHABITADO%TYPE
  ,SUBDISP_FINAL              SP_USUARIO.SUBDISP_FINAL%TYPE
  ,SOBDISP_FINAL              SP_USUARIO.SOBDISP_FINAL%TYPE
  ,SUBASEO                    SP_USUARIO.SUBASEO%TYPE
  ,SOBREASEO                  SP_USUARIO.SOBREASEO%TYPE
  ,VTRAMOEXCEDENTE            SP_USUARIO.VTRAMOEXCEDENTE%TYPE
  ,VALASEOCCS_720             SP_USUARIO.VALASEOCCS_720%TYPE
  ,VALASEOCBLS_720            SP_USUARIO.VALASEOCBLS_720%TYPE
  ,VALASEOCLUS_720            SP_USUARIO.VALASEOCLUS_720%TYPE
  ,VALASEOCRT_720             SP_USUARIO.VALASEOCRT_720%TYPE
  ,VALASEOCDF_720             SP_USUARIO.VALASEOCDF_720%TYPE
  ,VALASEOCTL_720             SP_USUARIO.VALASEOCTL_720%TYPE
  ,VALASEOVBA_720             SP_USUARIO.VALASEOVBA_720%TYPE
  ,INDFACTURADO               SP_USUARIO.INDFACTURADO%TYPE
  ,DEUDAASEO                  SP_USUARIO.DEUDAASEO%TYPE
  ,RECARGOASEO                SP_USUARIO.RECARGOASEO%TYPE
  ,AJUSTEDECENAASEO           SP_USUARIO.AJUSTEDECENAASEO%TYPE
  ,TOTFACTURAASEO             SP_USUARIO.TOTFACTURAASEO%TYPE
  ,TOTFACTURAASEOPAGO2        SP_USUARIO.TOTFACTURAASEOPAGO2%TYPE
  ,FACTURA                    SP_USUARIO.FACTURA%TYPE
  ,COSTOFIJOAC                SP_USUARIO.COSTOFIJOAC%TYPE
  ,COSTOM3AC                  SP_USUARIO.COSTOM3AC%TYPE
  ,TARIFAM3BASICOAC           SP_USUARIO.TARIFAM3BASICOAC%TYPE
  ,TARIFAM3COMPLEMENTARIOAC   SP_USUARIO.TARIFAM3COMPLEMENTARIOAC%TYPE
  ,TARIFAM3SUNTUARIOAC        SP_USUARIO.TARIFAM3SUNTUARIOAC%TYPE
  ,COSTOM3AL                  SP_USUARIO.COSTOM3AL%TYPE
  ,COSTOFIJOAL                SP_USUARIO.COSTOFIJOAL%TYPE
  ,TARIFAM3BASICOAL           SP_USUARIO.TARIFAM3BASICOAL%TYPE
  ,TARIFAM3COMPLEMENTARIOAL   SP_USUARIO.TARIFAM3COMPLEMENTARIOAL%TYPE
  ,TARIFAM3SUNTUARIOAL        SP_USUARIO.TARIFAM3SUNTUARIOAL%TYPE
  ,DEUDAINICIAL               SP_USUARIO.DEUDAINICIAL%TYPE
  ,LECTURAANTINICIAL          SP_USUARIO.LECTURAANTINICIAL%TYPE
  ,LECTURAINICIAL             SP_USUARIO.LECTURAINICIAL%TYPE
  ,PERIODOSATRASOINICIAL      SP_USUARIO.PERIODOSATRASOINICIAL%TYPE
  ,EMPRESAASEOEXT             SP_USUARIO.EMPRESAASEOEXT%TYPE
  ,PINTADEUDATERCE            SP_USUARIO.PINTADEUDATERCE%TYPE
  ,ALUMBRADO                  SP_USUARIO.ALUMBRADO%TYPE
  ,FIJOALUMBRADO              SP_USUARIO.FIJOALUMBRADO%TYPE
  ,ESTRATOALUMBRADO           SP_USUARIO.ESTRATOALUMBRADO%TYPE
  ,HOGAR_COMUNITARIO          SP_USUARIO.HOGAR_COMUNITARIO %TYPE
  ,APLICA_RES493              SP_USUARIO.APLICA_RES493%TYPE
  ,PERIODOSNOCOBROFIN         SP_USUARIO.PERIODOSNOCOBROFIN%TYPE
  ,TOTALDEUDA                 SP_USUARIO.TOTALDEUDA%TYPE
  ,NOTACREDITO                SP_USUARIO.NOTACREDITO%TYPE
  ,RECARGOACUEDUCTO           SP_USUARIO.RECARGOACUEDUCTO%TYPE
  ,RECARGOALC                 SP_USUARIO.RECARGOALC%TYPE
  ,RECARGOALUMBRADO           SP_USUARIO.RECARGOALUMBRADO%TYPE
  ,SINDESCUENTO               SP_USUARIO.SINDESCUENTO%TYPE
  ,INCENTIVO                  SP_USUARIO.INCENTIVO%TYPE
  ,ABONOS                     SP_USUARIO.ABONOS%TYPE
  ,INDFINANINICIAL            SP_USUARIO.INDFINANINICIAL%TYPE
  ,NOFECHAPAGOPERANTERIOR     SP_USUARIO.NOFECHAPAGOPERANTERIOR%TYPE
  ,TOTFACTURAPERANTERIOR      SP_USUARIO.TOTFACTURAPERANTERIOR%TYPE
  ,TOTALALUMBRADO             SP_USUARIO.TOTALALUMBRADO%TYPE
  ,DEUDAALUMBRADO             SP_USUARIO.DEUDAALUMBRADO%TYPE
  ,TOTALFACTURAALUMBRADO      SP_USUARIO.TOTALFACTURAALUMBRADO%TYPE
  ,CREDITOABONADO             SP_USUARIO.CREDITOABONADO%TYPE
  -- Variables no se actualizan en la tabla usuario
  ,COBRADOS                   SP_TARIFAS.METROS_NO_COBRADOS%TYPE
  ,NUMSALDOS                  PCK_SUBTIPOS.TI_ENTERO_LARGO

);

TYPE TFACTURADO IS RECORD (
   FACTURADO       SP_FACTURADO.VALOR_FACTURADO%TYPE      DEFAULT 0
  ,DEUDA           SP_FACTURADO.DEUDA%TYPE                DEFAULT 0
  ,FACTURADOANT    SP_FACTURADO.VALOR_FACTURADOANT%TYPE   DEFAULT 0
  ,DEUDAANT        SP_FACTURADO.DEUDAANT%TYPE             DEFAULT 0
  ,FACTURADOIN     SP_FACTURADO.VALOR_FACTURADOIN%TYPE    DEFAULT 0
  ,DEUDAIN         SP_FACTURADO.DEUDAIN%TYPE              DEFAULT 0

);

TYPE TCONCEPTOS IS RECORD (
   INTERES        SP_CONCEPTOS.INTERES%TYPE               DEFAULT 0
  ,IVA            SP_CONCEPTOS.IVA%TYPE                   DEFAULT 0
  ,RECARGO        SP_CONCEPTOS.RECARGO%TYPE               DEFAULT 0
  ,SERVICIO       SP_CONCEPTOS.SERVICIO%TYPE              DEFAULT 0
  ,VALOR          SP_CONCEPTOS.VALOR%TYPE                 DEFAULT 0
  ,DESCUENTO      SP_CONCEPTOS.PORC_DESCUENTO%TYPE        DEFAULT 0
);

TYPE TI_PARAMETRO IS TABLE OF PARAMETRO_VALOR INDEX BY VARCHAR2(50);
TYPE TI_USUARIO IS TABLE OF TUSUARIO INDEX BY BINARY_INTEGER;
TYPE TI_FACTURADO IS TABLE OF TFACTURADO INDEX BY BINARY_INTEGER;
TYPE TI_CONCEPTO IS TABLE OF TCONCEPTOS INDEX BY BINARY_INTEGER;


/* TODO enter package declarations (types, exceptions, methods etc) here */ 
--1
  FUNCTION FC_CALCULOFACTURACION
  (
    UN_COMPANIA              IN PCK_SUBTIPOS.TI_COMPANIA
   ,UN_INTCICLO              IN PCK_SUBTIPOS.TI_CICLO
   ,UN_STRCODIGOINICIAL      IN SP_USUARIO.CODIGORUTA%TYPE
   ,UN_STRCODIGOFINAL        IN SP_USUARIO.CODIGORUTA%TYPE
   ,UN_ENSERIE               IN PCK_SUBTIPOS.TI_LOGICO DEFAULT 0
   ,UN_FINAL                 IN PCK_SUBTIPOS.TI_LOGICO DEFAULT 0
   ,UN_USUARIO               IN SP_USUARIO.CREATED_BY%TYPE :=''
  ) RETURN VARCHAR2;
--2
  FUNCTION FC_CARGARPARFACTU 
  (
    UN_COMPANIA     IN PCK_SUBTIPOS.TI_COMPANIA
   ,UN_NIT		      IN COMPANIA.NITCOMPANIA%TYPE
  )RETURN  TI_PARAMETRO;

--3
  FUNCTION FC_CARGATARIFAS
  (
   UN_COMPANIA               IN     PCK_SUBTIPOS.TI_COMPANIA
  ,UN_ANO                    IN     SP_USUARIO.ANO%TYPE
  ,UN_PERIODO                IN     SP_USUARIO.PERIODO%TYPE
  ,UN_USO                    IN     SP_USUARIO.USO%TYPE
  ,UN_ESTRATO                IN     SP_USUARIO.ESTRATO%TYPE
  ,UN_VALIDATARIFA           IN OUT VARCHAR2
  ) RETURN  TTARIFAS;

--4
  FUNCTION FC_TIPOCALCULO
  (
     UN_COMPANIA       IN     PCK_SUBTIPOS.TI_COMPANIA
    ,UN_RSUSUARIO      IN OUT TUSUARIO
    ,UN_CONSUMOMANUSU  IN     PCK_SUBTIPOS.TI_LOGICO
    ,UN_PARAMETROS     IN     TI_PARAMETRO
  ) RETURN VARCHAR2;
--5
  FUNCTION FC_VALIDAUSAURIOCALC
  (
   UN_COMPANIA       IN     PCK_SUBTIPOS.TI_COMPANIA
  ,UN_RSUSUARIO      IN     TUSUARIO
  ,UN_PARAMETROS     IN     TI_PARAMETRO
  ,UN_CODERROR       IN OUT PCK_SUBTIPOS.TI_ENTERO
  ,UN_USUARIO        IN SP_USUARIO.CREATED_BY%TYPE :=''
  ) RETURN VARCHAR2;
--6
  FUNCTION FC_CONSUMOS
  (
    UN_COMPANIA            IN      PCK_SUBTIPOS.TI_COMPANIA
   ,UN_RSUSUARIO           IN OUT  TUSUARIO
   ,UN_TIPOCALCULO         IN      SP_USUARIO.TIPOCALCULO%TYPE
   ,UN_CONSUMOMANUSU       IN      PCK_SUBTIPOS.TI_LOGICO DEFAULT 0
   ,UN_PARAMETROS          IN      TI_PARAMETRO
   ,UN_MENSAJEFRAUDE       IN OUT  VARCHAR2
   ,UN_ENSERIE             IN      PCK_SUBTIPOS.TI_LOGICO
   ,UN_RSTARIFA            IN      TTARIFAS
   ,UN_CONSUMODEFINITIVO   IN      PCK_SUBTIPOS.TI_LOGICO  DEFAULT -1

  ) RETURN NUMBER;
--7
  FUNCTION FC_CONSUMOTOTALIZADOR
  (
   UN_COMPANIA            IN PCK_SUBTIPOS.TI_COMPANIA
  ,UN_RSUSUARIO           IN TUSUARIO
  ,UN_TOTACONCODIGO       IN PCK_SUBTIPOS.TI_LOGICO DEFAULT 0
  ) RETURN NUMBER;
--8  
  FUNCTION FC_CONSUMOMACROMEDIDOR
  (
   UN_COMPANIA            IN PCK_SUBTIPOS.TI_COMPANIA
  ,UN_RSUSUARIO           IN TUSUARIO
  ) RETURN NUMBER;
--9
  FUNCTION FC_CALCULOACUEDUCTO
  (
   UN_COMPANIA            IN      PCK_SUBTIPOS.TI_COMPANIA
  ,UN_RSUSUARIO           IN OUT  TUSUARIO
  ,UN_RSTARIFA            IN      TTARIFAS
  ,UN_TIPOCALCULO         IN      SP_USUARIO.TIPOCALCULO%TYPE
  ,UN_PARAMETROS          IN      TI_PARAMETRO
  ,UN_FACTURADOACT        IN OUT  TI_FACTURADO
   ) RETURN NUMBER;
--10   
  FUNCTION FC_CALCULOALCANTARILLADO
  (
   UN_COMPANIA            IN      PCK_SUBTIPOS.TI_COMPANIA
  ,UN_RSUSUARIO           IN OUT  TUSUARIO
  ,UN_RSTARIFA            IN      TTARIFAS
  ,UN_TIPOCALCULO         IN      SP_USUARIO.TIPOCALCULO%TYPE
  ,UN_PARAMETROS          IN      TI_PARAMETRO
  ,UN_FACTURADOACT        IN OUT  TI_FACTURADO
  ) RETURN NUMBER;

--11
  PROCEDURE PR_ARMAHISTORIADESVIACION
  (
   UN_COMPANIA           IN PCK_SUBTIPOS.TI_COMPANIA
  ,UN_RSUSUARIO          IN TUSUARIO
  ,UN_FACTURADOACT       IN TI_FACTURADO
  ,UN_FACTURADO          IN PCK_SUBTIPOS.TI_LOGICO DEFAULT 0
  ,UN_BOLPORMICRO        IN PCK_SUBTIPOS.TI_LOGICO
  ,UN_BOLCONMANUAL       IN PCK_SUBTIPOS.TI_LOGICO
  ,UN_PARAMETROS         IN TI_PARAMETRO
  ,UN_USUARIO            IN SP_USUARIO.CREATED_BY%TYPE :=''
  );

--12
  FUNCTION FC_CALCULOASEO
 (
   UN_COMPANIA               IN      PCK_SUBTIPOS.TI_COMPANIA
  ,UN_RSUSUARIO              IN OUT  TUSUARIO
  ,UN_RSTARIFA               IN      TTARIFAS
  ,UN_PARAMETROS             IN      TI_PARAMETRO
  ,UN_FACTACT                IN OUT  TI_FACTURADO
  ,UN_USUARIO                IN      SP_USUARIO.CREATED_BY%TYPE :=''
  ) RETURN NUMBER;

 --13
  PROCEDURE PR_LIMPIASUBSOBRE
  (
   UN_RSUSUARIO          IN OUT TUSUARIO
  ,UN_SERVICIO           SP_SERVICIO.NOMBRE%TYPE
  );

--14  
  FUNCTION FC_CALCULOMULTIUSUARIOS
 (
   UN_COMPANIA            IN      PCK_SUBTIPOS.TI_COMPANIA
  ,UN_RSUSUARIO           IN OUT  TUSUARIO
  ,UN_PARAMETROS          IN      TI_PARAMETRO
  ,UN_FACTURADOACT        IN OUT  TI_FACTURADO
  ,UN_VALIDATARIFA        IN OUT  VARCHAR2
  ,UN_USUARIO             IN      SP_USUARIO.CREATED_BY%TYPE :=''
  ) RETURN NUMBER;

--15
  FUNCTION FC_CALCULOFINANCIABLES
 (
   UN_COMPANIA            IN      PCK_SUBTIPOS.TI_COMPANIA
  ,UN_INTCICLO            IN      PCK_SUBTIPOS.TI_CICLO
  ,UN_CODIGORUTA          IN      SP_USUARIO.CODIGORUTA%TYPE
  ,UN_ANIO                IN      SP_USUARIO.ANO%TYPE
  ,UN_PERIODO             IN      SP_USUARIO.PERIODO%TYPE
  ,UN_FACTURADOACT        IN OUT  TI_FACTURADO
  ,UN_PARAMETROS          IN      TI_PARAMETRO
  ,UN_CONCEPTOS           IN      TI_CONCEPTO
  ,UN_NUMEROFINAN         IN OUT  PCK_SUBTIPOS.TI_ENTERO_LARGO
 ) RETURN NUMBER;

--16 
  FUNCTION FC_CALCULORECARGOS
 (
   UN_COMPANIA            IN      PCK_SUBTIPOS.TI_COMPANIA
  ,UN_RSUSUARIO           IN OUT  TUSUARIO
  ,UN_FACTURADOACT        IN OUT  TI_FACTURADO
  ,UN_PARAMETROS          IN      TI_PARAMETRO
  ,UN_CONCEPTOS           IN      TI_CONCEPTO
  ,UN_RSTARIFA            IN      TTARIFAS
 ) RETURN NUMBER;

--17
  FUNCTION FC_AJUSTEALPESO
 (
   UN_VALOR             IN SP_FACTURADO.VALOR_FACTURADO%TYPE
  ,UN_AJUSTEDECENA      IN NUMBER
  ,UN_REDONDEOPORENCIMA IN PCK_SUBTIPOS.TI_PARAMETRO
 ) RETURN NUMBER;

--18 
  FUNCTION FC_DESCUENTOCONCEPTO
 (
   UN_COMPANIA          IN PCK_SUBTIPOS.TI_COMPANIA
  ,UN_INTCICLO          IN PCK_SUBTIPOS.TI_CICLO
  ,UN_CODIGORUTA        IN SP_USUARIO.CODIGORUTA%TYPE
  ,UN_ANIO              IN SP_USUARIO.ANO%TYPE
  ,UN_PERIODO           IN SP_USUARIO.PERIODO%TYPE
  ,UN_SOLOELIMINA       IN PCK_SUBTIPOS.TI_LOGICO DEFAULT 0
  ,UN_CONCEPTOS         IN TI_CONCEPTO
  ,UN_FACTURADOACT      IN TI_FACTURADO
 ) RETURN NUMBER;

--19
  FUNCTION FC_DESCUENTOCONTROL
 (
  UN_COMPANIADES          IN PCK_SUBTIPOS.TI_COMPANIA
 ,UN_INTCICLODES          IN PCK_SUBTIPOS.TI_CICLO
 ,UN_CODIGORUTADES        IN SP_USUARIO.CODIGORUTA%TYPE
 ,UN_ANIODES              IN SP_USUARIO.ANO%TYPE
 ,UN_PERIODODES           IN SP_USUARIO.PERIODO%TYPE
 ,UN_FACTURADOACT         IN TI_FACTURADO
 ,UN_USUARIO              IN SP_USUARIO.CREATED_BY%TYPE :=''
 ) RETURN NUMBER;

--20
  FUNCTION FC_DESCUENTOCONTROLTOTFACTURA
 (
   UN_COMPANIADEST          IN PCK_SUBTIPOS.TI_COMPANIA
  ,UN_INTCICLODEST          IN PCK_SUBTIPOS.TI_CICLO
  ,UN_CODIGORUTADEST        IN SP_USUARIO.CODIGORUTA%TYPE
  ,UN_ANIODEST              IN SP_USUARIO.ANO%TYPE
  ,UN_PERIODODEST           IN SP_USUARIO.PERIODO%TYPE
  ,UN_FACTURADOACTT         IN TI_FACTURADO
  ,UN_TOTALFACTURA          IN SP_USUARIO.TOTFACTURAPERACTUAL%TYPE
  ,UN_USUARIO               IN SP_USUARIO.CREATED_BY%TYPE :=''

 ) RETURN NUMBER;

--21
  FUNCTION FC_CALCULOPRODUCTIVIDAD
 (
   UN_COMPANIA         IN PCK_SUBTIPOS.TI_COMPANIA
  ,UN_STRUSUARIO       IN SP_USUARIO.CODIGORUTA%TYPE
  ,UN_INTCICLO         IN PCK_SUBTIPOS.TI_CICLO
  ,UN_INTANO           IN SP_USUARIO.ANO%TYPE
  ,UN_STRPERIODO       IN SP_USUARIO.PERIODO%TYPE
  ,UN_TOTASEO          IN SP_FACTURADO.VALOR_FACTURADO%TYPE
  ,UN_USUARIO          IN SP_USUARIO.CREATED_BY%TYPE :=''
 ) RETURN NUMBER;

--22
  PROCEDURE PR_ACTUALIZAFACTURADOS
 ( 
   UN_COMPANIA           IN     PCK_SUBTIPOS.TI_COMPANIA
  ,UN_RSUSUARIO          IN     TUSUARIO
  ,UN_FACTURADOACT       IN OUT TI_FACTURADO
  ,UN_PRIMERAVEZ         IN     PCK_SUBTIPOS.TI_LOGICO       DEFAULT 0
  ,UN_PARAMETROS         IN     TI_PARAMETRO
  ,UN_USUARIO            IN SP_USUARIO.CREATED_BY%TYPE :=''
  );

--23  
  FUNCTION FC_MODIFICACIONESFACTURADO
 (
   UN_COMPANIA           IN PCK_SUBTIPOS.TI_COMPANIA
  ,UN_CODIGORUTA         IN SP_USUARIO.CODIGORUTA%TYPE
  ,UN_ANIO               IN SP_USUARIO.ANO%TYPE
  ,UN_PERIODO            IN SP_USUARIO.PERIODO%TYPE
  ,UN_INTCICLO           IN PCK_SUBTIPOS.TI_CICLO
 ) RETURN NUMBER;

--24
  PROCEDURE PR_DISTRIBUIRCUOTA12
 (
   UN_COMPANIA           IN PCK_SUBTIPOS.TI_COMPANIA
  ,UN_CODIGORUTA         IN SP_USUARIO.CODIGORUTA%TYPE
  ,UN_ANIO               IN SP_USUARIO.ANO%TYPE
  ,UN_PERIODO            IN SP_USUARIO.PERIODO%TYPE
  ,UN_CICLO              IN PCK_SUBTIPOS.TI_CICLO
  ,UN_USUARIO            IN SP_USUARIO.CREATED_BY%TYPE :=''
 );

--25
  PROCEDURE PR_DISTRIBUIRDEUDA12
 (
   UN_COMPANIA           IN PCK_SUBTIPOS.TI_COMPANIA
  ,UN_CODIGORUTA         IN SP_USUARIO.CODIGORUTA%TYPE
  ,UN_ANIO               IN SP_USUARIO.ANO%TYPE
  ,UN_PERIODO            IN SP_USUARIO.PERIODO%TYPE
  ,UN_CICLO              IN PCK_SUBTIPOS.TI_CICLO
  ,UN_USUARIO            IN SP_USUARIO.CREATED_BY%TYPE :=''
 );

--26
  FUNCTION FC_DISTRIBUIRSALDOSCREDITO
 (
   UN_COMPANIA           IN PCK_SUBTIPOS.TI_COMPANIA
  ,UN_CICLO              IN PCK_SUBTIPOS.TI_CICLO
  ,UN_CODIGORUTA         IN SP_USUARIO.CODIGORUTA%TYPE
  ,UN_ANO                IN SP_USUARIO.ANO%TYPE
  ,UN_PERIODO            IN SP_USUARIO.PERIODO%TYPE
  ,UN_NOTACREDITO        IN SP_USUARIO.NOTACREDITO%TYPE
  ,UN_FACTURADO          IN PCK_SUBTIPOS.TI_LOGICO DEFAULT 0
  ,UN_USUARIO            IN SP_USUARIO.CREATED_BY%TYPE :=''
 ) RETURN NUMBER;

--27
  PROCEDURE PR_VALORDESSALDOCREDITO
 (
   UN_COMPANIA           IN PCK_SUBTIPOS.TI_COMPANIA
  ,UN_ANO                IN SP_USUARIO.ANO%TYPE
  ,UN_PERIODO            IN SP_USUARIO.PERIODO%TYPE
  ,UN_CODIGORUTA         IN SP_USUARIO.CODIGORUTA%TYPE
  ,UN_CICLO              IN PCK_SUBTIPOS.TI_CICLO
  ,UN_TOTFACT            IN SP_USUARIO.CREDITOABONADO%TYPE
  ,UN_USUARIO            IN SP_USUARIO.CREATED_BY%TYPE :=''
 );

--28
  PROCEDURE PR_INSERTAERRORCALCULO
 (
   UN_COMPANIA           IN PCK_SUBTIPOS.TI_COMPANIA
  ,UN_CODIGORUTA         IN SP_USUARIO.CODIGORUTA%TYPE
  ,UN_CICLO              IN SP_USUARIO.CICLO%TYPE
  ,UN_CODIGOERRORINTERNO IN SP_ERRORCALCULO.CODIGOERROR%TYPE
  ,UN_MENSAJE            IN SP_ERRORCALCULO.MENSAJE%TYPE
  ,UN_USUARIO            IN SP_USUARIO.CREATED_BY%TYPE :=''
 );

--29
   PROCEDURE PR_RANGOUSUARIOSCICLO 
  (
    UN_COMPANIA         IN PCK_SUBTIPOS.TI_COMPANIA
  );

--30
  PROCEDURE PR_ACTUALIZAR_MEDIDORES
  (
      UN_COMPANIA 		    IN  PCK_SUBTIPOS.TI_COMPANIA,
      UN_CICLO            IN  SP_USUARIO.CICLO%TYPE,
      UN_CODIGORUTA       IN  SP_USUARIO.CODIGORUTA%TYPE,
      UN_MEDIDOR          IN  SP_USUARIO.MEDIDOR%TYPE,
      UN_USUARIO          IN  PCK_SUBTIPOS.TI_USUARIO
  );


--31
  FUNCTION FC_SUSCRIPTORTGR
  (
     UN_COMPANIA                IN SP_USUARIO.COMPANIA%TYPE
    ,UN_CICLO                   IN SP_USUARIO.CICLO%TYPE
    ,UN_CODIGORUTA              IN SP_USUARIO.CODIGORUTA%TYPE
    ,UN_CODIGOINTERNO           IN SP_USUARIO.CODIGOINTERNO%TYPE
    ,UN_ANO                     IN SP_USUARIO.ANO%TYPE
    ,UN_PERIODO                 IN SP_USUARIO.PERIODO%TYPE
    ,UN_ANTESTADO               IN SP_USUARIO.ESTADO%TYPE :=''
    ,UN_NUEESTADO               IN SP_USUARIO.ESTADO%TYPE :=''
    ,UN_VALIDACAMBIOMATRICULA   IN PCK_SUBTIPOS.TI_LOGICO := 0
    ,UN_TOTALDEUDA              IN SP_USUARIO.TOTALDEUDA%TYPE :=0
    ,UN_BANCOPERPROCESO         IN SP_USUARIO.BANCOPERPROCESO%TYPE := ''
    ,UN_ANTHOGARCOMUNI          IN SP_USUARIO.HOGAR_COMUNITARIO%TYPE :=0
    ,UN_NUEHOGARCOMUNI          IN SP_USUARIO.HOGAR_COMUNITARIO%TYPE :=0
    ,UN_TOTFACTURA              IN SP_USUARIO.TOTFACTURAPERACTUAL%TYPE :=0
    ,UN_USO                     IN SP_USUARIO.USO%TYPE :=''
    ,UN_ESTRATO                 IN SP_USUARIO.ESTRATO%TYPE :=''
    ,UN_ANTMATRICULA            IN SP_USUARIO.MATRICULA%TYPE :=''
    ,UN_NUEMATRICULA            IN SP_USUARIO.MATRICULA%TYPE :=''
    ,UN_TIPOPREDIO              IN SP_USUARIO.TIPOPREDIO%TYPE :=''
    ,UN_CLASESOLICITUD          IN SP_USUARIO.CLASESOLICITUD%TYPE := ''
    ,UN_CAMBIOINDASEO           IN PCK_SUBTIPOS.TI_LOGICO :=0
    ,UN_CAMBIOASEOBARRIDO       IN PCK_SUBTIPOS.TI_LOGICO :=0
    ,UN_EMPRESAASEOEXT          IN SP_USUARIO.EMPRESAASEOEXT%TYPE :=''
    ,UN_PINTADEUDATERCE         IN SP_USUARIO.PINTADEUDATERCE%TYPE :=0
    ,UN_SOLICITUD               IN SP_USUARIO.SOLICITUD%TYPE := ''
    ,UN_VALIDACAMBIOCODEXTERNO  IN PCK_SUBTIPOS.TI_LOGICO := 0
    ,UN_NUECODIGO_EXTERNO       IN SP_USUARIO.CODIGO_EXTERNO%TYPE := ''
    ,UN_DBLTOTAL                IN OUT PCK_SUBTIPOS.TI_DOBLE
    ,UN_INSERTAFACTUSUARIO      IN PCK_SUBTIPOS.TI_LOGICO := 0
    ,UN_ACCION                  IN VARCHAR2
    ,UN_USUARIO                 IN SP_USUARIO.CREATED_BY%TYPE :=''
    ) RETURN NUMBER;

--32
  FUNCTION FC_ACTUALIZARSUSPENDIDOS
  (
     UN_COMPANIA                IN SP_USUARIO.COMPANIA%TYPE
    ,UN_CICLO                   IN SP_USUARIO.CICLO%TYPE
    ,UN_CODIGORUTA              IN SP_USUARIO.CODIGORUTA%TYPE
    ,UN_CODIGOINTERNO           IN SP_USUARIO.CODIGOINTERNO%TYPE
    ,UN_ANO                     IN SP_USUARIO.ANO%TYPE
    ,UN_PERIODO                 IN SP_USUARIO.PERIODO%TYPE
    ,UN_BANCOPAGO               IN SP_USUARIO.BANCOPERPROCESO%TYPE
    ,UN_DESDETRIGGER            IN PCK_SUBTIPOS.TI_LOGICO := 0
    ,UN_USUARIO                 IN SP_USUARIO.MODIFIED_BY%TYPE
  ) RETURN NUMBER;

--33
  FUNCTION FC_CREARCODIGOINTERNO
  (
     UN_COMPANIA      IN SP_USUARIO.COMPANIA%TYPE
    ,UN_CICLO         IN SP_USUARIO.CICLO%TYPE
    ,UN_NUMREGISTRO   IN OUT SP_USUARIO.NUMEROREGISTRO%TYPE
  )RETURN VARCHAR2;


END PCK_SERVICIOS_PUBLICOS_COM7;