create or replace PACKAGE PCK_PRECONTRACTUAL1 AS 

  /* TODO enter package declarations (types, exceptions, methods etc) here */
  -- 1
	FUNCTION FC_ACTUALIZARFORMULAS
	(
		UN_COMPANIA       	IN PCK_SUBTIPOS.TI_COMPANIA,
		UN_CAMPO          	IN VARIABLETRANSACCION.VALOR%TYPE,
		UN_VALOR          	IN VARIABLETRANSACCION.VALOR%TYPE,
		UN_TIPOCONTRATO   	IN VARIABLETRANSACCION.TIPOCONTRATO%TYPE,
		UN_CONSECUTIVO    	IN VARIABLETRANSACCION.TRANSACCION%TYPE,
		UN_USUARIO 			    IN PCK_SUBTIPOS.TI_USUARIO
	) 
	RETURN VARCHAR2;

  --2
  PROCEDURE PR_COPIARESTUDIOPREVIO
  (
    UN_COMPANIA     PCK_SUBTIPOS.TI_COMPANIA,
    UN_CODESTUDIO   ES_EST_PROY.COD_ESTUDIO%TYPE,
    UN_USUARIO      PCK_SUBTIPOS.TI_USUARIO,
    UN_CONSECUTIVO  ES_EST_PROY.COD_ESTUDIO%TYPE);

  --3
  PROCEDURE PR_PROPONENTE_ETAPAS
  (
    UN_COMPANIA          PCK_SUBTIPOS.TI_COMPANIA,
    UN_TIPOCONTRATO      PCK_SUBTIPOS.TI_STRSQL,
    UN_TRANSACCION       PCK_SUBTIPOS.TI_STRSQL,
    UN_CONSECUTIVO       PCK_SUBTIPOS.TI_ENTERO_LARGO,
    UN_PROPONENTE        PCK_SUBTIPOS.TI_USUARIO,
    UN_SUCURSAL          PCK_SUBTIPOS.TI_SUCURSAL,
    UN_COTIZAINVENTARIO  PCK_SUBTIPOS.TI_LOGICO
  );

  --4
  FUNCTION FC_CAMBIARESTUDIOPREVIO 
  (
    UN_COMPANIA          IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_TIPOCONTRATO      IN TIPOCONTRATO_PR.TIPOCONTRATO%TYPE,
    UN_TRANSACCION       IN TRANSACCION.CONSECUTIVO%TYPE,
    UN_ESTUDIOPREVIO     IN TRANSACCION.ESTUDIOPREVIO%TYPE,
    UN_USUARIO           IN PCK_SUBTIPOS.TI_USUARIO
  )
  RETURN PCK_SUBTIPOS.TI_LOGICO;

  --5
  PROCEDURE PR_ACTUALIZARESTUDIOPREVIO 
  (
    UN_COMPANIA          IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_TIPOCONTRATO      IN TIPOCONTRATO_PR.TIPOCONTRATO%TYPE,
    UN_TRANSACCION       IN TRANSACCION.CONSECUTIVO%TYPE,
    UN_ESTUDIOPREVIO     IN TRANSACCION.ESTUDIOPREVIO%TYPE,
    UN_USUARIO           IN PCK_SUBTIPOS.TI_USUARIO
  );

  --6
  PROCEDURE PR_ACTUALIZARINFOPROPONENTES
  (
    UN_COMPANIA          IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_TIPOCONTRATO      IN TIPOCONTRATO_PR.TIPOCONTRATO%TYPE,
    UN_TRANSACCION       IN TRANSACCION.CONSECUTIVO%TYPE,
    UN_CONSECACTUAL      IN PRE_REQUISITOS_ETAPA.CONSECUTIVODETALLE%TYPE,
    UN_CONSECSIGUIENTE   IN PRE_REQUISITOS_ETAPA.CONSECUTIVODETALLE%TYPE,
    UN_USUARIO           IN PCK_SUBTIPOS.TI_USUARIO
  );

 -- 7
  PROCEDURE PR_CREARDETALLESTX
  (
      UN_COMPANIA              IN PCK_SUBTIPOS.TI_COMPANIA,
      UN_TIPOCONTRATO          IN TIPOCONTRATO_PR.TIPOCONTRATO%TYPE,
      UN_TRANSACCION           IN TRANSACCION.CONSECUTIVO%TYPE,
      UN_FECHAINICIO           IN DATE,
      UN_USUARIO               IN PCK_SUBTIPOS.TI_USUARIO
  ); 

-- 8
PROCEDURE PR_CARGAR_CODIGO_UNSPSC
(
 UN_COMPANIA      IN PCK_SUBTIPOS.TI_COMPANIA,
 UN_CAMBIOS       IN CLOB,
 UN_USUARIO       IN PCK_SUBTIPOS.TI_USUARIO
);

PROCEDURE PR_INSERTAR_ACUERDOSCOMERP3
(
UN_COMPANIA      IN   ES_ESTPREVIO.COMPANIA%TYPE,
UN_NRO_ESTUDIO   IN   ES_ESTPREVIO.COD_ESTUDIO%TYPE,
UN_TIPO_CONTRATO IN   ES_ESTPREVIO.TIPO_CONTRATO%TYPE,
UN_USUARIO       IN   VARCHAR2
);

PROCEDURE PR_CREARRIESGO_DEFECTO
(
  UN_COMPANIA       IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_T_RIESGO       IN ES_RIESGO.COD_T_RIESGO%TYPE,
  UN_USUARIO        IN PCK_SUBTIPOS.TI_USUARIO
);

END PCK_PRECONTRACTUAL1;