create or replace PACKAGE PCK_NOMINA_PROC01 AS 

FUNCTION FC_PROC01 
(
  UN_COMPANIA  IN PCK_SUBTIPOS.TI_COMPANIA
)
RETURN BOOLEAN;

PROCEDURE PR_CALCULARPROVISIONES ;

FUNCTION FC_REVISARVACOTROPERIODO 
RETURN PCK_SUBTIPOS.TI_LOGICO;

FUNCTION FC_REVISARDIAS_MAYOR30 
RETURN PCK_SUBTIPOS.TI_LOGICO;

PROCEDURE PR_TRAERINT_CESANTIAS31DIC
(
 UN_COMPANIA  IN  PCK_SUBTIPOS.TI_COMPANIA,
 UN_ANO  IN  PCK_SUBTIPOS.TI_ANIO,
 UN_MES  IN  PCK_SUBTIPOS.TI_MES,
 UN_PERIODO   IN  PCK_SUBTIPOS.TI_PERIODO_NOMI,
 UN_EMPLEADO   IN PCK_SUBTIPOS.TI_ID_DE_EMPLEADO
);


FUNCTION FC_ESTPERIODO
(
 UN_PROCESO  IN  PERIODOS.ID_DE_PROCESO%TYPE,
 UN_ANO  IN  PCK_SUBTIPOS.TI_ANIO,
 UN_MES  IN  PCK_SUBTIPOS.TI_MES,
 UN_PERIODO   IN  PCK_SUBTIPOS.TI_PERIODO_NOMI
) RETURN NUMBER;

FUNCTION FC_ACUMPERIODO
(
 UN_PROCESO  IN  PERIODOS.ID_DE_PROCESO%TYPE,
 UN_ANO  IN  PCK_SUBTIPOS.TI_ANIO,
 UN_MES  IN  PCK_SUBTIPOS.TI_MES,
 UN_PERIODO   IN  PCK_SUBTIPOS.TI_PERIODO_NOMI
) RETURN NUMBER;

FUNCTION FC_INIFININCAPACIDADT(
        UN_EMPLEADO VARCHAR2, 
        UN_PARAMETRO VARCHAR2, 
        UN_TIPO     VARCHAR2) 
RETURN DATE;

FUNCTION FC_PERIODOSMES
(
 UN_PROCESO  IN  PCK_SUBTIPOS.TI_COMPANIA,
 UN_ANO  IN  PCK_SUBTIPOS.TI_ANIO,
 UN_MES  IN  PCK_SUBTIPOS.TI_MES,
 UN_PERIODO  IN  PCK_SUBTIPOS.TI_PERIODO_NOMI
 ) RETURN NUMBER;

PROCEDURE PR_CALCULARVIATICOS;

PROCEDURE PR_ACTIVARCUOTASDIFVACACIONES
(
UN_ANO  IN  PCK_SUBTIPOS.TI_ANIO,
UN_MES  IN  PCK_SUBTIPOS.TI_MES,
UN_PERIODO   IN  PCK_SUBTIPOS.TI_PERIODO_NOMI,
UN_EMPLEADO   IN PCK_SUBTIPOS.TI_ID_DE_EMPLEADO,
UN_CANTIDAD IN NUMBER,
UN_PERACTIVAR IN NUMBER
);

FUNCTION FC_ACUMNOVEDADES   (
    UN_ANO1       NUMBER,
    UN_MES1       NUMBER,
    UN_PERIODO1   NUMBER,
    UN_ANO2       NUMBER,
    UN_MES2       NUMBER,
    UN_PERIODO2   NUMBER,
    UN_CODIGO     NUMBER
  )
RETURN NUMBER;

FUNCTION FC_ACUMNOVEDADES_PROC   (
    UN_ANO1       NUMBER,
    UN_MES1       NUMBER,
    UN_PERIODO1   NUMBER,
    UN_ANO2       NUMBER,
    UN_MES2       NUMBER,
    UN_PERIODO2   NUMBER,
    UN_CODIGO     NUMBER,
    UN_PROCESO    NUMBER,
    UN_CONCEPTO   NUMBER
  )
RETURN NUMBER;

PROCEDURE PR_ACTUALIZARNOVEDADES_CN (
Concepto IN NUMBER
);
PROCEDURE PR_REVISARATEP2REGISTROS;

PROCEDURE PR_INCAPACIDADES350;

FUNCTION FC_CONCEPTOAPLICASS
(
  UN_CONCEPTO IN NUMBER
) RETURN NUMBER;

FUNCTION FC_DIASTOMADOSVACACIONES
(
UN_EMPLEADO IN VARCHAR2
)
RETURN NUMBER;

PROCEDURE PR_ACTUALIZARNOVEDADES133;

PROCEDURE PR_ACTNOVEDADESSEGURIDADSOCIAL;

PROCEDURE PR_PARAFISCALESEXONERADO;

PROCEDURE PR_CALCULARINCAPACIDADES;

FUNCTION FC_SUMACON_RANGO(UN_CON1 IN NUMBER, UN_CON2 IN NUMBER)  
RETURN NUMBER;

PROCEDURE PR_ACTUALIZARNOVEDADES348;

PROCEDURE PR_ACTUALIZARNOVEDADESCITAGUI;

PROCEDURE PR_CALCULARRETENCION;

FUNCTION FC_BUSCAR_SUMA_IBCCAUSANTE(UN_CIA IN VARCHAR2, UN_EMPLEADO IN VARCHAR2, UN_FECHAINIC IN Date)
RETURN NUMBER;

PROCEDURE PR_CALCULARVIATICOS_IDSN;

PROCEDURE PR_DUP_CUO_NOVSIEAUNEMP(UN_EMP IN VARCHAR2, UN_CAN IN NUMBER);

FUNCTION FC_NUMERODECUOTAS(UN_FECHAINICIAL IN Date, UN_FECHAFINAL IN Date)  
RETURN PCK_SUBTIPOS.TI_DOBLE;

PROCEDURE PR_DUPCUOINFIBOY11092017;

PROCEDURE PR_REVDIASENVACINTER;

PROCEDURE PR_ACTUALIZARNOVEDADESSS;

PROCEDURE PR_ACTUALIZARNOVEDADES_SUELDO;

PROCEDURE PR_CALCULAR_HORAS_EXTRAS; 

PROCEDURE PR_ACTUALIZANOVEDADESTODAS ;

PROCEDURE PR_TRAERSUELDOENCARGO
(
        UN_ANIO      IN PCK_SUBTIPOS.TI_ANIO,
        UN_ESCALAFON IN VARCHAR2,
        UN_CATEGORIA IN VARCHAR2
);

PROCEDURE PR_ACTUALIZARNOVEDADESGR;

FUNCTION FC_TIPOAPORTANTE(UN_COMPANIA IN VARCHAR2, UN_PAR IN NUMBER) RETURN VARCHAR2;

FUNCTION FC_ULTIMOVALORDELCONCEPTO(UN_SEMPLEADO IN VARCHAR2 , UN_CONCEPTO IN VARCHAR2, UN_PAR IN NUMBER) 
RETURN VARCHAR2; 

FUNCTION FC_SUMACONP 

  (
	UN_CONCEPTO1 IN PCK_SUBTIPOS.TI_ENTERO,
  	UN_CONCEPTO2 IN PCK_SUBTIPOS.TI_ENTERO    
  )
RETURN NUMBER;

PROCEDURE PR_REV_CAM_SUEL_PERI;


PROCEDURE PR_BUSCARENCARGORETRO
    (UN_COMPANIA  IN PCK_SUBTIPOS.TI_COMPANIA
    ,UN_EMPLEADO  IN PCK_SUBTIPOS.TI_ID_DE_EMPLEADO
    ,UN_MES IN  PCK_SUBTIPOS.TI_MES
);

PROCEDURE PR_CALCULARSUBSIDIODEALIM;

PROCEDURE PR_LIQUID_AU_ALI_CEN;

PROCEDURE PR_CALCULARSUBSIDIODETRAN;

PROCEDURE PR_CALPRIANTIGUESPCARIBABARE;

PROCEDURE PR_ACTUALIZARNOVEDADESAPAGAR;

PROCEDURE PR_CALCULARPRIMAANTIGUEDADCDM;

PROCEDURE PR_CALCULAR_PRIANTIGUE;

PROCEDURE PR_LIQUIDAR_BR;

PROCEDURE  PR_CALCPRIMAANTIGUEDADALCCHIQ;

PROCEDURE PR_CALCULARPRIMASEMESTRALSTR;

PROCEDURE PR_PROCEDIMIENTOSPROYECCIONES
( UN_COMPANIA  VARCHAR2);

FUNCTION FC_SUMACONCEPTOSBASE40
RETURN NUMBER;

FUNCTION FC_SUMACONCEPTOSBASE40A
RETURN NUMBER;

FUNCTION FC_SUMACONCEPTOSBASE40NO
RETURN NUMBER;

FUNCTION FC_SUMACONCEPTOSBASE40ANO
RETURN NUMBER;

PROCEDURE PR_ACTUALIZARNOVEDADESTODASENC;

PROCEDURE PR_AUXMARCHA;

PROCEDURE PR_REVISARRETIRO(UN_COMPANIA   IN  PCK_SUBTIPOS.TI_COMPANIA );

FUNCTION FC_REVISARTOPES40PORCIENTO
  (
   UN_PAR40 IN PCK_SUBTIPOS.TI_ENTERO
   )
RETURN NUMBER;

PROCEDURE PR_BONIFIDIRLCALDE;

PROCEDURE PR_OTROSS_PROCESOS;

FUNCTION FC_ACPROPEXACTA
(

	UN_FECHAINICIAL IN DATE, 
	UN_FECHAFINAL IN DATE,
	UN_CONCEPTO IN PCK_SUBTIPOS.TI_ENTERO,
	UN_DEPENDE IN PCK_SUBTIPOS.TI_ENTERO,
	UN_TIPODIAS IN VARCHAR2,
	UN_CEDULA IN VARCHAR2,
	UN_FECHAINICIONOMINA IN DATE,
	UN_FECHAFINNOMINA IN DATE,
	UN_TIPONOMINA IN VARCHAR2:=''


	) RETURN NUMBER;


PROCEDURE PR_CALCULARQUINQUENIO;


PROCEDURE PR_ACTUALIZARNOVEDADESEAAAM ;

PROCEDURE PR_CALCULARQUINQUENIOTODOS;

FUNCTION FC_ANTIGUEDADANUAL
(UN_ANOS NUMBER) 
RETURN NUMBER;


PROCEDURE PR_CALCPRIMAANTIANUALDUITAMA;

PROCEDURE PR_CALCULARNIIF_BASP(UN_FECB IN DATE);

PROCEDURE PR_ACTUALIZARNOVEDADESBASP;

FUNCTION FC_ACUMCONCEPTOLICENCIAS(UN_CONCEPTO IN VARCHAR2, UN_ANO1 IN NUMBER, UN_MES1 IN NUMBER, UN_PER1 IN NUMBER, UN_ANO2 IN NUMBER, UN_MES2 IN NUMBER, UN_PER2 IN NUMBER, UN_CODIGO IN VARCHAR2, UN_SPROCESO IN NUMBER) 
	RETURN NUMBER;

PROCEDURE PR_CALCULARBONIFICACIONANUAL;
PROCEDURE PR_CALCULAR_BASP;

FUNCTION FC_VALORULTIMAPRIMASEMESTRAL(
        UN_EMPLEADO IN PCK_SUBTIPOS.TI_ID_DE_EMPLEADO
        )
RETURN PCK_SUBTIPOS.TI_DOBLE ;


PROCEDURE PR_TOTALIZARDEVENGOS;

PROCEDURE PR_TOTALIZARDESCUENTOS;

PROCEDURE PR_TOTALIZARNETO;


FUNCTION FC_VALORULTIMABONIFICACION
(
	UN_ID_EMPLEADO IN PCK_SUBTIPOS.TI_ENTERO
) 
RETURN PCK_SUBTIPOS.TI_DOBLE;

FUNCTION FC_VALULTIMAPRIMADEVACACIONES
(
	UN_ID_EMPLEADO IN PCK_SUBTIPOS.TI_ENTERO
	) 
RETURN PCK_SUBTIPOS.TI_DOBLE;


FUNCTION FC_ULTPRIMA_VAC_CORTOLIMA
(
    UN_ID_EMPLEADO IN PCK_SUBTIPOS.TI_ENTERO
    ) 
RETURN PCK_SUBTIPOS.TI_DOBLE;


PROCEDURE PR_CALCPRIMASEMESTRALAUDITORIA;

FUNCTION FC_IBC_MES_ANTERIOR(UN_COMPANIA IN VARCHAR2, UN_PROCESO IN NUMBER, UN_ANOMA IN NUMBER, UN_MESMA IN NUMBER, UN_SEMPLEADO IN PCK_SUBTIPOS.TI_ID_DE_EMPLEADO) 
RETURN NUMBER;

PROCEDURE PR_CALCPRIMAANTIGUEDADSOG
(
UN_VALRETIRO IN BOOLEAN
);

FUNCTION FC_DETALLEPLANTILLA
(
UN_COMPANIA IN  MODELO_PLANTILLA.COMPANIA%TYPE,
UN_CODIGO   IN  MODELO_PLANTILLA.CODIGO%TYPE,
UN_PROCESO  IN  VARCHAR2,
UN_ANO      IN  VARCHAR2,
UN_MES      IN  VARCHAR2,
UN_PERIODO  IN  VARCHAR2,
UN_EMPLEADO IN  VARCHAR2
) RETURN CLOB;

FUNCTION FC_DIASLRE_ENCARGO RETURN NUMBER;

PROCEDURE PR_PUTLISTAVALOR
(
UN_COMPANIA    IN  PCK_SUBTIPOS.TI_COMPANIA,
UN_LISTA       IN  VARCHAR2,
UN_VALOR       IN  NUMBER
);

FUNCTION FC_AUSENTISMO1DAQUINCENA
(
UN_COMPANIA  IN PCK_SUBTIPOS.TI_COMPANIA,
UN_ANO       IN  PCK_SUBTIPOS.TI_ANIO,
UN_MES       IN  PCK_SUBTIPOS.TI_MES,
UN_EMPLEADO  IN PCK_SUBTIPOS.TI_ID_DE_EMPLEADO
) RETURN BOOLEAN;

FUNCTION FC_AUSENTISMO2DAQUINCENA   
(
UN_COMPANIA  IN PCK_SUBTIPOS.TI_COMPANIA,
UN_ANO       IN  PCK_SUBTIPOS.TI_ANIO,
UN_MES       IN  PCK_SUBTIPOS.TI_MES,
UN_EMPLEADO  IN PCK_SUBTIPOS.TI_ID_DE_EMPLEADO
) RETURN BOOLEAN;
FUNCTION FC_DIASGEN_ENCARGO(
UN_ID_CONCEPTO IN CONCEPTOS.ID_DE_CONCEPTO%TYPE
) RETURN NUMBER; 
PROCEDURE PR_BON_ESPE_INTEGRAL;
END PCK_NOMINA_PROC01;