create or replace PACKAGE               PCK_PRESUPUESTO_COM4 AS 

FUNCTION FC_AFECTACIONES_A_FECHA_PPTO(UN_COMPANIA       IN PCK_SUBTIPOS.TI_COMPANIA 
                                     ,UN_ANIO           IN PCK_SUBTIPOS.TI_ANIO
                                     ,UN_TIPO           IN PCK_SUBTIPOS.TI_TIPOCOMPROBANTEPPTAL
                                     ,UN_COMPROBANTE    IN PCK_SUBTIPOS.TI_NUMEROCOMPROBANTEPPTAL
                                     ,UN_CONSECUTIVO    IN PCK_SUBTIPOS.TI_CONSECUTIVOPPTAL
                                     ,UN_FECHA          IN DATE 
                                    )
RETURN NUMBER;

FUNCTION FC_CADENAAFECTACION(UN_COMPANIA       IN PCK_SUBTIPOS.TI_COMPANIA 
                            ,UN_ANIO           IN PCK_SUBTIPOS.TI_ANIO
                            ,UN_TIPO           IN PCK_SUBTIPOS.TI_TIPOCOMPROBANTEPPTAL
                            ,UN_COMPROBANTE    IN PCK_SUBTIPOS.TI_NUMEROCOMPROBANTEPPTAL
                            ,UN_CONSECUTIVO    IN PCK_SUBTIPOS.TI_CONSECUTIVOPPTAL
                            ,UN_FECHA          IN DATE 
                            )
RETURN VARCHAR2;


PROCEDURE PR_ACTUALIZAR_SALDOPPTAL_MOV(UN_COMPANIA       IN PCK_SUBTIPOS.TI_COMPANIA 
                                      ,UN_ANIO           IN PCK_SUBTIPOS.TI_ANIO
                                      ,UN_TIPO           IN PCK_SUBTIPOS.TI_TIPOCOMPROBANTEPPTAL
                                      ,UN_COMPROBANTE    IN PCK_SUBTIPOS.TI_NUMEROCOMPROBANTEPPTAL
                                      ,UN_CONSECUTIVO    IN PCK_SUBTIPOS.TI_CONSECUTIVOPPTAL
                                      ,UN_FECHA          IN DATE 
                                     );

PROCEDURE PR_CONGELARSALDOSMAN(UN_COMPANIA        IN PCK_SUBTIPOS.TI_COMPANIA 
                              ,UN_ANIO            IN PCK_SUBTIPOS.TI_ANIO
                              ,UN_TIPO            IN PCK_SUBTIPOS.TI_TIPOCOMPROBANTEPPTAL
                              ,UN_COMPROBANTE_INI IN PCK_SUBTIPOS.TI_NUMEROCOMPROBANTEPPTAL
                              ,UN_COMPROBANTE_FIN IN PCK_SUBTIPOS.TI_NUMEROCOMPROBANTEPPTAL
                              );
 FUNCTION FC_GENERAR_PLANO_SECRETARIA
(
 UN_COMPANIA         PCK_SUBTIPOS.TI_COMPANIA,
 UN_FECHAINICIAL     PCK_SUBTIPOS.TI_FECHA, 
 UN_FECHAFINAL       PCK_SUBTIPOS.TI_FECHA,  
 UN_TIPOCOMP         PCK_SUBTIPOS.TI_CLASECOMPROPPTO,
 UN_CPTEINICIAL      PCK_SUBTIPOS.TI_NUMEROCOMPROBANTEPPTAL,
 UN_CPTEFINAL        PCK_SUBTIPOS.TI_NUMEROCOMPROBANTEPPTAL,
 UN_RESPONSABLEPPTO  PCK_SUBTIPOS.TI_TERCERO
)
RETURN CLOB;

FUNCTION  FC_GENERAR_PLANO_ORDEN_PAGO
(
 UN_COMPANIA         PCK_SUBTIPOS.TI_COMPANIA,
 UN_FECHAINICIAL     PCK_SUBTIPOS.TI_FECHA, 
 UN_FECHAFINAL       PCK_SUBTIPOS.TI_FECHA,  
 UN_TIPOCOMP         PCK_SUBTIPOS.TI_CLASECOMPROPPTO,
 UN_RESPONSABLEPPTO  PCK_SUBTIPOS.TI_TERCERO,
 UN_CPTEINICIAL      PCK_SUBTIPOS.TI_NUMEROCOMPROBANTEPPTAL,
 UN_CPTEFINAL        PCK_SUBTIPOS.TI_NUMEROCOMPROBANTEPPTAL,
 UN_VIGENCIA         VARCHAR2
)
RETURN CLOB;
FUNCTION  FC_GENERAR_PLANO_OP_RESERVA
(
 UN_COMPANIA         PCK_SUBTIPOS.TI_COMPANIA,
 UN_FECHAINICIAL     PCK_SUBTIPOS.TI_FECHA, 
 UN_FECHAFINAL       PCK_SUBTIPOS.TI_FECHA,  
 UN_TIPOCOMP         PCK_SUBTIPOS.TI_CLASECOMPROPPTO,
 UN_VIGENCIA         VARCHAR2,   --- TICKET7738447 MPEREZ
 UN_RESPONSABLEPPTO  PCK_SUBTIPOS.TI_TERCERO,
 UN_CPTEINICIAL      PCK_SUBTIPOS.TI_NUMEROCOMPROBANTEPPTAL,
 UN_CPTEFINAL        PCK_SUBTIPOS.TI_NUMEROCOMPROBANTEPPTAL
)
RETURN CLOB;

PROCEDURE PR_INSERTAPPTO
(
     UN_COMPANIA      IN PCK_SUBTIPOS.TI_COMPANIA
    ,UN_CLASEORDEN    IN COMPROBANTE_PPTAL.TIPOCONTRATO%TYPE
    ,UN_NUMERO        IN COMPROBANTE_PPTAL.NUMEROCONTRATO%TYPE
    ,UN_CLASEDISP     IN ORDENDECOMPRAPPTO.TIPOPPTO%TYPE 
    ,UN_NUMERODISPSEL IN ORDENDECOMPRAPPTO.NUMEROPPTO%TYPE  
    ,UN_TERCERO       IN PCK_SUBTIPOS.TI_TERCERO 
    ,UN_SUCURSAL      IN PCK_SUBTIPOS.TI_SUCURSAL  
    ,UN_USUARIO       IN PCK_SUBTIPOS.TI_USUARIO 
);

PROCEDURE PR_CARGAR_COMP_DETALLE_PPTAL
( 
  UN_COMPANIA    IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_CADENAPLAN  IN CLOB,
  UN_USUARIO     IN PCK_SUBTIPOS.TI_USUARIO
);  

PROCEDURE PR_CARGAR_PMR_FUENTE 
( 
  UN_COMPANIA     IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_CADENA       IN CLOB,
  UN_USUARIO      IN PCK_SUBTIPOS.TI_USUARIO
);


PROCEDURE PR_CARGAR_TIPO_CLASIFICADORES
( 
  UN_COMPANIA    IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_CADENAPLAN  IN CLOB,
  UN_USUARIO     IN PCK_SUBTIPOS.TI_USUARIO
);  

 FUNCTION FC_ACT_CLASIFICADORESPPTAL 
(  UN_COMPANIA       IN PCK_SUBTIPOS.TI_COMPANIA 
  ,UN_ANIO           IN PCK_SUBTIPOS.TI_ANIO
  ,UN_USUARIO        IN PCK_SUBTIPOS.TI_USUARIO
)  RETURN NUMBER;

FUNCTION FC_ACT_CLASI_AUX
   
(  UN_COMPANIA       IN PCK_SUBTIPOS.TI_COMPANIA 
  ,UN_ANIO           IN PCK_SUBTIPOS.TI_ANIO
  ,UN_USUARIO        IN PCK_SUBTIPOS.TI_USUARIO
)RETURN NUMBER;

PROCEDURE PR_ACT_CLASI_ARBOL   
(  UN_COMPANIA       IN PCK_SUBTIPOS.TI_COMPANIA 
  ,UN_ANIO           IN PCK_SUBTIPOS.TI_ANIO  
  ,UN_USUARIO        IN PCK_SUBTIPOS.TI_USUARIO
);

PROCEDURE PR_ACTLZ_SITUACION_FONDOS
(
    UN_COMPANIA       IN PCK_SUBTIPOS.TI_COMPANIA 
    ,UN_ANIO           IN PCK_SUBTIPOS.TI_ANIO
);

PROCEDURE PR_ACT_FUENTE_DETALLE

(  UN_COMPANIA       IN PCK_SUBTIPOS.TI_COMPANIA 
  ,UN_ANIO           IN PCK_SUBTIPOS.TI_ANIO
  ,UN_USUARIO        IN PCK_SUBTIPOS.TI_USUARIO
);

FUNCTION FC_ACT_CLAS_CADENA_PPTAL  
    
(  UN_COMPANIA       IN PCK_SUBTIPOS.TI_COMPANIA 
  ,UN_ANIO           IN PCK_SUBTIPOS.TI_ANIO      
  ,UN_USUARIO        IN PCK_SUBTIPOS.TI_USUARIO
) RETURN NUMBER;

PROCEDURE PR_CARGAR_CLASIFICADORES_HIJO( 
  UN_COMPANIA    IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_CADENAPLAN  IN CLOB,
  UN_USUARIO     IN PCK_SUBTIPOS.TI_USUARIO
); 

--7710306 mrosero
FUNCTION FC_GENERALIBROREGISTROSSQL

(
UN_STRSQL CLOB
 
)
RETURN CLOB;

FUNCTION FC_CARGA_RECLASIFICA_CIERRE 
(
    UN_COMPANIA   IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_ANO      IN PCK_SUBTIPOS.TI_ANIO,
    UN_CLASE      IN PCK_SUBTIPOS.TI_CLASECOMPROPPTO,
    UN_CADENA     IN CLOB,    
    UN_USUARIO    IN PCK_SUBTIPOS.TI_USUARIO
 )
 RETURN VARCHAR2;

  
 
PROCEDURE PR_ACTUALIZAR_AUX_EN_INGRESO(
 UN_COMPANIA       IN PCK_SUBTIPOS.TI_COMPANIA 
,UN_ANIO           IN PCK_SUBTIPOS.TI_ANIO
,UN_RUBRO    IN VARCHAR2
,UN_CENTROCOSTO_INI  IN VARCHAR2
,UN_CENTROCOSTO_FIN  IN VARCHAR2
,UN_AUXILIAR_INI      IN VARCHAR2
,UN_AUXILIAR_FIN      IN VARCHAR2
,UN_REFERENCIA_INI    IN VARCHAR2
,UN_REFERENCIA_FIN    IN VARCHAR2
,UN_FUENTERECURSO_INI IN VARCHAR2
,UN_FUENTERECURSO_FIN IN VARCHAR2
);

PROCEDURE PR_CARGAR_MOV_PPTALES
( 
  UN_COMPANIA    IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_CADENAH     IN CLOB,
  UN_CADENAD     IN CLOB,
  UN_USUARIO     IN PCK_SUBTIPOS.TI_USUARIO
); 
PROCEDURE PR_ACT_ARBOL_APROINI
(
    UN_COMPANIA       IN PCK_SUBTIPOS.TI_COMPANIA
    ,UN_ANIO           IN PCK_SUBTIPOS.TI_ANIO
);

FUNCTION FC_CARGAR_AUXILIARES(
    UN_TABLA                  IN VARCHAR2,
    UN_CADENA                 IN CLOB,
    UN_USUARIO                IN VARCHAR2
  )  RETURN CLOB;

END PCK_PRESUPUESTO_COM4;