create or replace PACKAGE PCK_CIRCULAR_UNICA AS 

  /* TODO enter package declarations (types, exceptions, methods etc) here */ 
  
  PROCEDURE PR_PREPARAR_CODIGOS 
  (
    UN_COMPANIA     IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_ANIO_INI     IN PCK_SUBTIPOS.TI_ANIO,
    UN_ANIO_FIN     IN PCK_SUBTIPOS.TI_ANIO,
    UN_USUARIO      IN PCK_SUBTIPOS.TI_USUARIO,
    UN_OPCION IN PCK_SUBTIPOS.TI_ENTERO
  );
  
  FUNCTION FC_ACTUALIZAR_VIG_PLANPPTAL 
  (
   UN_COMPANIA      IN PCK_SUBTIPOS.TI_COMPANIA,
   UN_ANIO_INI      IN PCK_SUBTIPOS.TI_ANIO,
   UN_ANIO_FIN      IN PCK_SUBTIPOS.TI_ANIO,
   UN_USUARIO       IN PCK_SUBTIPOS.TI_USUARIO
  )
  
  RETURN CLOB;

  FUNCTION FC_CARGAR_CONFIG_PRESUPUESTAL(
    UN_TABLA        IN VARCHAR2,
    UN_CADENA       IN CLOB,
    UN_USUARIO      IN VARCHAR2,
    UN_COMPANIA     IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_ANO          IN ANO.NUMERO%TYPE
  )  RETURN CLOB;

END PCK_CIRCULAR_UNICA;