create or replace PACKAGE PCK_HOJAS_DE_VIDA AS 

  /* TODO enter package declarations (types, exceptions, methods etc) here */ 

--1 
PROCEDURE PR_CONSECEVAL
(
  UN_COMPANIA            IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_NUMERODCTOINICIAL   IN NAT_DATOS_PERSONALES.NUMERO_DCTO%TYPE,
  UN_NUMERODCTOFINAL     IN NAT_DATOS_PERSONALES.NUMERO_DCTO%TYPE,
  UN_FECHAINICIAL        IN NAT_EVALUACION.EV_FECHDESDEEVAL%TYPE,
  UN_FECHAFINAL          IN NAT_EVALUACION.EV_FECHDESDEEVAL%TYPE,
  UN_USUARIO             IN PCK_SUBTIPOS.TI_USUARIO
);

  --2
  PROCEDURE PR_VALIDARFILTROSIMPRESIONHV
  (
    UN_IND_LISTADO     IN PCK_SUBTIPOS.TI_LOGICO DEFAULT 0,      -- Indicador listado.
    UN_IND_FECHAS      IN PCK_SUBTIPOS.TI_LOGICO DEFAULT 0,      -- Indicador entre fechas.
    UN_IND_ESTADO      IN PCK_SUBTIPOS.TI_LOGICO DEFAULT 0,      -- Indicador estado actual.
    UN_IND_CONSOLIDADO IN PCK_SUBTIPOS.TI_LOGICO DEFAULT 0,      -- Indicador consolidado.
    UN_IND_HISTORIAL   IN PCK_SUBTIPOS.TI_LOGICO DEFAULT 0,      -- Indicador historial unico.
    UN_FECHAINICIAL    IN DATE,                                  -- Fecha inicial 
    UN_FECHAFINAL      IN DATE,                                  -- Fecha final.
    UN_EMPLEADOINI_NUM IN NAT_DATOS_PERSONALES.NUMERO_DCTO%TYPE, -- Numero del documento empleado inicial.
    UN_EMPLEADOFIN_NUM IN NAT_DATOS_PERSONALES.NUMERO_DCTO%TYPE, -- Numero del documento empleado final.
    UN_INFORME         IN VARCHAR2,
    UN_ESTADO          IN VARCHAR2
  );  
--3
PROCEDURE PR_VALIDARESTUDIOS
(
    UN_COMPANIA       IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_NUMERO_DCTO  IN PCK_SUBTIPOS.TI_TERCERO,
    UN_SUCURSAL       IN PCK_SUBTIPOS.TI_SUCURSAL
);
-- 4
FUNCTION FC_CERRARCONVOCATORIA
(
    UN_COMPANIA     IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_CONVOCATORIA IN NAT_CALIFICACION_PRUEBAS.NRO_CONVOCATORIA%TYPE,
    UN_USUARIO      IN PCK_SUBTIPOS.TI_USUARIO
)
RETURN VARCHAR2;

--5
PROCEDURE PR_CALIFICAR_EVALUACION
(
    UN_COMPANIA           IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_ID_EMPLEADO        IN PERSONAL.ID_DE_EMPLEADO%TYPE,
    UN_EVALUACION         IN EV_DETALLE_EVALUACION.NUMERO_EVALUACION%TYPE,
    UN_CLASE_EVALUACION   IN EV_CRITERIO_GRUPO.CLASE_EVALUACION %TYPE,
    UN_USUARIO            IN PCK_SUBTIPOS.TI_USUARIO
);

--6
PROCEDURE PR_ACT_CAMPOS_NULOS
(
    UN_COMPANIA            IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_NUMERO_DCTO         IN PERSONAL.NUMERO_DCTO%TYPE  
);

--7
PROCEDURE PR_ACT_CAMPOS_NULOS_NU
(
    UN_COMPANIA            IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_NUMERO_DCTO         IN PERSONAL.NUMERO_DCTO%TYPE,
    UN_SUCURSAL            IN PCK_SUBTIPOS.TI_SUCURSAL,
    UN_USUARIO             IN PCK_SUBTIPOS.TI_USUARIO
);    

--8
PROCEDURE PR_DETALLE_EVALUACION
(
    UN_COMPANIA               IN  PCK_SUBTIPOS.TI_COMPANIA,
    UN_EVALUACION             IN  EV_DETALLE_EVALUACION.NUMERO_EVALUACION%TYPE,
    UN_CLASE_EVALUACION       IN  EV_CRITERIO_GRUPO.CLASE_EVALUACION%TYPE,
    UN_CEDULA_EVALUADO        IN  EV_SUBDETALLE_EVALUACION.CEDULA_EVALUADO%TYPE,
    UN_CEDULA_EVALUADOR       IN  EV_SUBDETALLE_EVALUACION.CEDULA_EVALUADOR%TYPE,
    UN_SUCURSAL_EVALUADO      IN  EV_SUBDETALLE_EVALUACION.SUCURSAL_EVALUADO%TYPE,
    UN_SUCURSAL_EVALUADOR     IN  EV_SUBDETALLE_EVALUACION.SUCURSAL_EVALUADOR%TYPE,
    UN_ESCALAFON_EVALUADOR    IN  EV_SUBDETALLE_EVALUACION.ESCALAFON_EVALUADOR%TYPE,
    UN_ESCALAFON_EVALUADO     IN  EV_SUBDETALLE_EVALUACION.ESCALAFON_EVALUADO%TYPE,
    UN_TIPO_EVALUACION        IN  EV_SUBDETALLE_EVALUACION.TIPO_EVALUACION%TYPE,
    UN_CARGO_EVALUADOR        IN  EV_SUBDETALLE_EVALUACION.CARGO_EVALUADOR%TYPE,
    UN_CARGO_EVALUADO         IN  EV_SUBDETALLE_EVALUACION.CARGO_EVALUADO%TYPE,
    UN_CODIGO_EVALUADOR       IN  EV_DETALLE_EVALUACION.CODIGO_EMPLEADO_EVALUADOR%TYPE,
    UN_CODIGO_EVALUADO        IN  EV_DETALLE_EVALUACION.CODIGO_EMPLEADO_EVALUADO%TYPE,
    UN_EVALUADOR_COMISION     IN  EV_DETALLE_EVALUACION.EVALUADOR_COMISION%TYPE,
    UN_USUARIO                IN  PCK_SUBTIPOS.TI_USUARIO
);

PROCEDURE PR_ACTUALIZAR_DETA_PROFESIONES
(
  UN_COMPANIA         IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_NUMERO_DCTO      IN VARCHAR2,
  UN_SUCURSAL         IN VARCHAR2,
  UN_ID_DE_EMPLEADO   IN NUMBER,
  UN_USUARIO          IN VARCHAR2
  );


PROCEDURE PR_ACTUALIZAR_PUNTAJE
(
    UN_COMPANIA               IN  PCK_SUBTIPOS.TI_COMPANIA,
    UN_EVALUACION             IN  EV_DETALLE_EVALUACION.NUMERO_EVALUACION%TYPE,
    UN_CLASE_EVALUACION       IN  EV_CRITERIO_GRUPO.CLASE_EVALUACION%TYPE,
    UN_TIPO_EVALUACION        IN  EV_SUBDETALLE_EVALUACION.TIPO_EVALUACION%TYPE,
    UN_CRITERIO_EVALUADO      IN  EV_SUBDETALLE_EVALUACION.CRITERIO_EVALUADO%TYPE,
    UN_CRITERIO_SELECCIONADO  IN  EV_SUBDETALLE_EVALUACION.CRITERIO_EVALUADO%TYPE,
    UN_CEDULA_EVALUADO        IN  EV_SUBDETALLE_EVALUACION.CEDULA_EVALUADO%TYPE,
    UN_CEDULA_EVALUADOR       IN  EV_SUBDETALLE_EVALUACION.CEDULA_EVALUADOR%TYPE,
    UN_SUCURSAL_EVALUADO      IN  EV_SUBDETALLE_EVALUACION.SUCURSAL_EVALUADO%TYPE,
    UN_SUCURSAL_EVALUADOR     IN  EV_SUBDETALLE_EVALUACION.SUCURSAL_EVALUADOR%TYPE,
    UN_ESCOMPROMISO           IN  PCK_SUBTIPOS.TI_LOGICO,  
    UN_USUARIO                IN  PCK_SUBTIPOS.TI_USUARIO
);

PROCEDURE PR_ACT_INSCR_ACTIV(

  UN_COMPANIA       IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_EVENTO       IN VARCHAR2,
  UN_TIPO_EV        IN VARCHAR2,
  UN_FECHA_EV       IN DATE,
  UN_NUMERO_DCTO    IN PCK_SUBTIPOS.TI_TERCERO,
  UN_SUCURSAL     IN PCK_SUBTIPOS.TI_SUCURSAL,
  UN_USUARIO      IN PCK_SUBTIPOS.TI_USUARIO
);

--11
PROCEDURE PR_ACTEXPLABORALPERSONALES(
  UN_COMPANIA        IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_NUMERO_DCTO     IN NAT_DATOS_PERSONALES.NUMERO_DCTO%TYPE, 
  UN_SUCURSAL        IN NAT_DATOS_PERSONALES.SUCURSAL%TYPE, 
  UN_CLASE           IN NAT_EXPERIENCIA_LABORAL.CLASE%TYPE, 
  UN_ANO             IN NAT_EXPERIENCIA_LABORAL.ANOSERVICIO%TYPE, 
    UN_MES             IN NAT_EXPERIENCIA_LABORAL.MESESERVICIO%TYPE,
  UN_DIA             IN NAT_EXPERIENCIA_LABORAL.DIASERVICIO%TYPE,
  UN_USUARIO         IN PCK_SUBTIPOS.TI_USUARIO
  );

--12
PROCEDURE PR_INSERTARACTIVIDADES
(
    UN_COMPANIA         IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_TIPO_TRANSACCION IN PCK_SUBTIPOS.TI_ENTERO,
    UN_TRANSACCION      IN PCK_SUBTIPOS.TI_LONG,
    UN_USUARIO          IN PCK_SUBTIPOS.TI_USUARIO
);

--13
PROCEDURE PR_ACTUALIZAPLANTILLA 
(
    UN_COMPANIA         IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_TIPOTRANSACCION  IN  SST_TIPO_ACTIVIDAD.TIPO_TRANSACCION%TYPE,
    UN_ACTIVIDAD        IN SST_TIPO_ACTIVIDAD.CODIGO%TYPE
);
--14
PROCEDURE PR_DOCUMENTOSPRESENTADOS 
(
    UN_COMPANIA   IN    PCK_SUBTIPOS.TI_COMPANIA,
    UN_SUCURSAL   IN    DOCUMENTOS_PRESENTADOS.SUCURSAL%TYPE,
    UN_TERCERO    IN    DOCUMENTOS_PRESENTADOS.NUMERO_DCTO%TYPE ,   
    UN_USUARIO    IN    PCK_SUBTIPOS.TI_USUARIO
);
--15
PROCEDURE PR_EXPERIENCIALABORAL 
(
    UN_COMPANIA    IN    PCK_SUBTIPOS.TI_COMPANIA, 
    UN_TERCERO     IN    PCK_SUBTIPOS.TI_USUARIO,
    UN_SUCURSAL    IN    PCK_SUBTIPOS.TI_SUCURSAL,
    UN_USUARIO     IN    PCK_SUBTIPOS.TI_USUARIO
);

--16
FUNCTION FC_INSERCPERSONAL

(
    UN_COMPANIA    IN  PCK_SUBTIPOS.TI_COMPANIA,
    UN_TERCERO     IN  NAT_DATOS_PERSONALES.NUMERO_DCTO%TYPE,
    UN_SUCURSAL    IN  PCK_SUBTIPOS.TI_SUCURSAL,
    UN_USUARIO     IN  PCK_SUBTIPOS.TI_USUARIO 
) RETURN PCK_SUBTIPOS.TI_ENTERO;

PROCEDURE PR_ACTUALIZARCORREOSINSCRITOS
(
  UN_COMPANIA         IN NAT_APERTURA_INSCRITOS.COMPANIA%TYPE,
  UN_NRO_CONVOCATORIA IN NAT_APERTURA_INSCRITOS.NRO_CONVOCATORIA%TYPE,
  UN_OPCION           IN NUMBER
);

--17
PROCEDURE PR_CARGACONVOMANUAL
(
  UN_COMPANIA            IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_NUMEROMANUAL        IN EV_MANUAL.NUMERO_MANUAL%TYPE,
  UN_VERSION             IN EV_MANUAL.VERSION%TYPE,
  UN_NROCONVOCATORIA     IN NAT_APERTURA.NRO_CONVOCATORIA%TYPE, 
  UN_USUARIO             IN PCK_SUBTIPOS.TI_USUARIO
);

PROCEDURE PR_GENERARCOMPROMISOS
(
    UN_COMPANIA           IN  PCK_SUBTIPOS.TI_COMPANIA,    
    UN_EVALUACION         IN  EV_COMPROMISOS_LABORALES.NUMERO_EVALUACION%TYPE,
    UN_CLASE              IN  EV_COMPROMISOS_LABORALES.CLASE_EVALUACION%TYPE,
    UN_ANO                IN  EV_COMPROMISOS_LABORALES.ANO%TYPE,
    UN_EVALUADO           IN  EV_COMPROMISOS_LABORALES.CEDULA_EVALUADO%TYPE,
    UN_SUCURSALEVALUADO   IN  EV_COMPROMISOS_LABORALES.SUCURSAL_EVALUADO%TYPE,
    UN_PERIODO            IN  EV_DETALLE_COMPACORDADOS.PERIODO%TYPE,
    UN_TIPO               IN  EV_COMPROMISOS_LABORALES.TIPO_EVALUACION%TYPE,
    UN_USUARIO            IN  PCK_SUBTIPOS.TI_USUARIO
);


PROCEDURE PR_HEREDAREVIDENCIAS
(
  UN_COMPANIA           IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_EVALUACION         IN EV_SUBDETALLE_EVALUACION.EVALUACION%TYPE,
  UN_CEDULA_EVALUADO    IN EV_SUBDETALLE_EVALUACION.CEDULA_EVALUADO%TYPE,
  UN_CEDULA_EVALUADOR   IN EV_SUBDETALLE_EVALUACION.CEDULA_EVALUADOR%TYPE,
  UN_CLASE              IN EV_SUBDETALLE_EVALUACION.CLASE_EVALUACION%TYPE,
  UN_TIPO               IN EV_SUBDETALLE_EVALUACION.TIPO_EVALUACION%TYPE,
  UN_ANO                IN EV_COMPROMISOS_LABORALES.ANO%TYPE,
  UN_OPCION             IN PCK_SUBTIPOS.TI_ENTERO,
  UN_USUARIO            IN PCK_SUBTIPOS.TI_USUARIO
);


PROCEDURE PR_HEREDAREVALUACION
(
    UN_COMPANIA           IN  PCK_SUBTIPOS.TI_COMPANIA,
    UN_EVALUACION         IN  EV_COMPROMISOS_LABORALES.NUMERO_EVALUACION%TYPE,
    UN_CLASE              IN  EV_COMPROMISOS_LABORALES.CLASE_EVALUACION%TYPE,
    UN_ANO                IN  EV_COMPROMISOS_LABORALES.ANO%TYPE,
    UN_EVALUADO           IN  EV_COMPROMISOS_LABORALES.CEDULA_EVALUADO%TYPE,
    UN_SUCURSALEVALUADO   IN  EV_COMPROMISOS_LABORALES.SUCURSAL_EVALUADO%TYPE,
    UN_EVALUADOR          IN  EV_COMPROMISOS_LABORALES.CEDULA_EVALUADO%TYPE,
    UN_SUCURSALEVALUADOR  IN  EV_COMPROMISOS_LABORALES.SUCURSAL_EVALUADO%TYPE,
    UN_TIPO               IN  EV_COMPROMISOS_LABORALES.TIPO_EVALUACION%TYPE,
    UN_USUARIO            IN  PCK_SUBTIPOS.TI_USUARIO
);

PROCEDURE PR_ACTCORREOSAUTOSERVICIO
(
  UN_COMPANIA         IN NAT_APERTURA_INSCRITOS.COMPANIA%TYPE,
  UN_CONSECUTIVO      IN AUT_SOLICITUDES.CONSECUTIVO%TYPE,
  UN_CLASE            IN AUT_SOLICITUDES.CLASE_SOLICITUD%TYPE,
  UN_OPCION           IN NUMBER
);


FUNCTION FC_CREARUTANEXOS
(
    UN_COMPANIA     IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_MODULO       IN PCK_SUBTIPOS.TI_MODULO,
    UN_CEDULA       IN PCK_SUBTIPOS.TI_NRODOCUMENTO,
    UN_CODIGORUTA   IN NIVEL_AGRUPAMIENTO.CODIGO%TYPE
 )
RETURN VARCHAR2;

FUNCTION FC_GLOSADESCRIPCION 
(
        UN_COD_GEN_GLOSA   IN VARCHAR2,
        UN_COD_ESP_GLOSA   IN VARCHAR2,
        UN_ID_GLOSA        IN VARCHAR2,
        UN_NRO_FACTURA     IN VARCHAR2
        
)
RETURN CLOB;

PROCEDURE PR_ACTUALIZAEXPLABORALPER
(
  UN_COMPANIA        IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_NUMERO_DCTO     IN NAT_DATOS_PERSONALES.NUMERO_DCTO%TYPE,
  UN_CODIGO_PER      IN NAT_DATOS_PERSONALES.CODIGO%TYPE,
  UN_SUCURSAL        IN NAT_DATOS_PERSONALES.SUCURSAL%TYPE,
  UN_USUARIO         IN PCK_SUBTIPOS.TI_USUARIO
);

PROCEDURE PR_FONDOS_HV_NOM
(
  UN_COMPANIA              IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_ID_DE_EMPLEADO        IN PERSONAL.ID_DE_EMPLEADO%TYPE
);

END PCK_HOJAS_DE_VIDA;