create or replace PACKAGE "PCK_ALMACEN_COM4" AS

  GL_ERROR_NUM                NUMBER:=52000;
  GL_MSG                      ERRORES.DESCRIPCION%TYPE;

TYPE PARAMETRO_VALOR IS RECORD (VALOR PARAMETRO.VALOR%TYPE);

TYPE PAAGSANO IS RECORD(
    ANIO				    MES.ANO%TYPE,
    NUMERO				  MES.NUMERO%TYPE,
    PAAG_MENSUAL	  MES.PAAG_MENSUAL%TYPE,
    SALARIOMINIMO	  ANO.SALARIOMINIMO%TYPE,
    CUANTIAMINIMA	  ANO.CUANTIAMINIMA%TYPE
);

TYPE PAAGS IS TABLE OF PAAGSANO INDEX BY BINARY_INTEGER;

-- 1
FUNCTION FC_ACTUALIZAR_RESPONSABLE
(
  UN_COMPANIA          IN PCK_SUBTIPOS.TI_COMPANIA -- Código de la compañia
, UN_ID                IN VARCHAR2                 -- ID del PREDIO o VIA
, UN_SERIE_PLACA       IN PCK_SUBTIPOS.TI_ENTERO_LARGO   -- Serie-Placa
, UN_CODIGO_INVENTARIO IN VARCHAR2                 -- Código de Inventario
, UN_PREDIO            IN PCK_SUBTIPOS.TI_LOGICO   -- Diferente de cero para saber si es Predio
, UN_USUARIO  		     IN PCK_SUBTIPOS.TI_USUARIO  -- Usuario que ingreso a la aplicación
) RETURN NUMBER;

-- 2
FUNCTION FC_VIDAUTILRESTANTE
(
  UN_COMPANIA          IN PCK_SUBTIPOS.TI_COMPANIA  -- Código de la compañia
, UN_PLACA             IN PCK_SUBTIPOS.TI_ENTERO_LARGO    -- Código de la placa
) RETURN NUMBER;

FUNCTION FC_CALDEPRECIARIIH
(
  UN_COMPANIA            IN PCK_SUBTIPOS.TI_COMPANIA,  -- Código de la compañia
  UN_STRELEMENTOINICIAL  IN VARCHAR2,                  -- Código del elemento
  UN_STRELEMENTOFINAL    IN VARCHAR2,                  -- Código del elemento
  UN_PLACAINICIAL        IN PCK_SUBTIPOS.TI_ENTERO_LARGO,    -- Código de la placa
  UN_PLACAFINAL          IN PCK_SUBTIPOS.TI_ENTERO_LARGO     -- Código de la placa
 )
 RETURN CLOB;

 FUNCTION FC_CALDEPRECIARIIH_NIIF
(
  UN_COMPANIA            IN PCK_SUBTIPOS.TI_COMPANIA,  -- Código de la compañia
  UN_STRELEMENTOINICIAL  IN VARCHAR2,                  -- Código del elemento
  UN_STRELEMENTOFINAL    IN VARCHAR2,                  -- Código del elemento
  UN_PLACAINICIAL        IN PCK_SUBTIPOS.TI_ENTERO_LARGO,    -- Código de la placa
  UN_PLACAFINAL          IN PCK_SUBTIPOS.TI_ENTERO_LARGO     -- Código de la placa
 )
 RETURN CLOB;

FUNCTION FC_VERIFICARCUENTAALMACEN
 (
  UN_COMPANIA            IN PCK_SUBTIPOS.TI_COMPANIA,  -- Código de la compañia
  UN_FECHA_INICIAL       DATE,      -- Fecha Inicial del periodo
  UN_FECHA_FINAL         DATE       -- Fecha Final del periodo
 )
 RETURN CLOB;

 FUNCTION FC_CALDEPRECIARH
(
   UN_COMPANIA            IN PCK_SUBTIPOS.TI_COMPANIA, -- Código de la compañia
    UN_ANOINICIAL          IN PCK_SUBTIPOS.TI_ANIO ,  -- Código del elemento
    UN_MESINICIAL          IN PCK_SUBTIPOS.TI_MES ,  -- Código del elemento
    UN_ANOFINAL            IN PCK_SUBTIPOS.TI_ANIO ,  -- Código de la placa
    UN_MESFINAL            IN PCK_SUBTIPOS.TI_MES ,  -- Código de la placa
    UN_STRELEMENTOINICIAL  IN VARCHAR2,                 -- Código del elemento
    UN_STRELEMENTOFINAL    IN VARCHAR2,                 -- Código del elemento
    UN_PLACAINICIAL        IN PCK_SUBTIPOS.TI_ENTERO_LARGO ,  -- Código de la placa
    UN_PLACAFINAL          IN PCK_SUBTIPOS.TI_ENTERO_LARGO     -- Código de la placa
 )
 RETURN CLOB;

 FUNCTION FC_CALDEPRECIARH_NIIF
(
    UN_COMPANIA              IN PCK_SUBTIPOS.TI_COMPANIA,  -- Código de la compañia
    UN_ANOINICIAL          IN PCK_SUBTIPOS.TI_ANIO,    -- Código del elemento
    UN_MESINICIAL          IN PCK_SUBTIPOS.TI_MES,    -- Código del elemento
    UN_ANOFINAL            IN PCK_SUBTIPOS.TI_ANIO,    -- Código de la placa
    UN_MESFINAL            IN PCK_SUBTIPOS.TI_MES,    -- Código de la placa
    UN_STRELEMENTOINICIAL  IN VARCHAR2,                  -- Código del elemento
    UN_STRELEMENTOFINAL    IN VARCHAR2,                  -- Código del elemento
    UN_PLACAINICIAL        IN PCK_SUBTIPOS.TI_ENTERO_LARGO,    -- Código de la placa
    UN_PLACAFINAL          IN PCK_SUBTIPOS.TI_ENTERO_LARGO     -- Código de la placa
 )
 RETURN CLOB;

FUNCTION FC_DEPRECIACIONES_POSTERIORES
(
  UN_COMPANIA        IN COMPANIA.CODIGO%TYPE,
  UN_ANO             IN ANO.NUMERO%TYPE,
  UN_MES             IN MES.NUMERO%TYPE,
  UN_ELEMENTOINICIAL IN DEVOLUTIVO.ELEMENTO%TYPE,
  UN_ELEMENTOFINAL   IN DEVOLUTIVO.ELEMENTO%TYPE,
  UN_PLACAINICIAL    IN DEVOLUTIVO.SERIE%TYPE,
  UN_PLACAFINAL      IN DEVOLUTIVO.SERIE%TYPE
)
RETURN NUMBER;

FUNCTION FC_AC_RESPONSABLE_PREDIOSVIAS(
    UN_COMPANIA      IN PCK_SUBTIPOS.TI_COMPANIA, -- Código de la compañia
    UN_PREDIO        IN PCK_SUBTIPOS.TI_LOGICO,   -- Diferente de cero para saber si es Predio
    UN_USUARIO  		 IN PCK_SUBTIPOS.TI_USUARIO   -- Usuario que ingreso a la aplicación
  )
RETURN PCK_SUBTIPOS.TI_ENTERO;

FUNCTION FC_ACTUALIZAR_VIDAUTILR(
    UN_COMPANIA          IN PCK_SUBTIPOS.TI_COMPANIA,    -- Código de la compañia
    UN_PREDIO            IN PCK_SUBTIPOS.TI_LOGICO,      -- Diferente de cero para saber si es Predio
    UN_USUARIO      		 IN PCK_SUBTIPOS.TI_USUARIO      -- Usuario que ingreso a la aplicación
  )
RETURN PCK_SUBTIPOS.TI_ENTERO;
--11
PROCEDURE PR_REGISTRARADICIONPREDIAL
(
     UN_COMPANIA         IN PCK_SUBTIPOS.TI_COMPANIA
    ,UN_SELECCION        IN ADICIONES.ID_PREDIO%TYPE
    ,UN_SERIE            IN ADICIONES.SERIE_PLACA%TYPE
    ,UN_ELEMENTO         IN ADICIONES.COD_INVENTARIO%TYPE
    ,UN_FECHAMOVIMIENTO  IN ADICIONES.FECHA%TYPE
    ,UN_NUMEROMOVIMIENTO IN ADICIONES.NUMERO_MOV%TYPE
    ,UN_TIPOMOVIMIENTO   IN ADICIONES.TIPO_MOVIMIENTO%TYPE
    ,UN_TIPOINMUEBLE     IN ADICIONES.TIPO_INMUEBLE%TYPE
    ,UN_VALORTOTAL       IN ADICIONES.VALOR_CONSTRUCCION%TYPE
    ,UN_ORDENA           IN ADICIONES.RESPONSABLE_ORDENA%TYPE
    ,UN_ANIOCONSTRUCCION IN ADICIONES.ANO_CONSTRUCCION%TYPE
    ,UN_SUCURSAL         IN ADICIONES.SUCURSAL%TYPE
    ,UN_DESCRIPCION      IN ADICIONES.DESCRIPCION%TYPE
    ,UN_USUARIO          IN PCK_SUBTIPOS.TI_USUARIO
);

--12
FUNCTION FC_ACTUALIZARDESDEEXCEL
(
    UN_COMPANIA IN PCK_SUBTIPOS.TI_COMPANIA
   ,UN_PLANO    IN CLOB
   ,UN_USUARIO  IN PCK_SUBTIPOS.TI_USUARIO
)RETURN NUMBER;

-- 13. cambiarNumeroMovimiento
PROCEDURE PR_CAMBIAR_NUMERO_MOVIMIENTO
(
  UN_COMPANIA                     IN PCK_SUBTIPOS.TI_COMPANIA
, UN_USUARIO                      IN PCK_SUBTIPOS.TI_USUARIO
, UN_TIPO_MOVIMIENTO              IN MOVIMIENTO.TIPOMOVIMIENTO%TYPE
, UN_NUMERO_MOVIMIENTO            IN MOVIMIENTO.NUMERO%TYPE
, UN_NUMERO_NUEVO                 IN MOVIMIENTO.NUMERO%TYPE
);

-- 14. tieneMovimientosSinRegistrar
FUNCTION FC_TIENE_DETMOV_SIN_REGISTRAR
(
  UN_COMPANIA                     IN PCK_SUBTIPOS.TI_COMPANIA
, UN_TIPO_MOVIMIENTO              IN D_MOVIMIENTO.TIPOMOVIMIENTO%TYPE
, UN_NUMERO_MOVIMIENTO            IN D_MOVIMIENTO.MOVIMIENTO%TYPE
)RETURN PCK_SUBTIPOS.TI_LOGICO;

-- 15. traerTipoFormato
FUNCTION FC_TRAER_TIPO_FORMATO
(
  UN_COMPANIA                     IN PCK_SUBTIPOS.TI_COMPANIA
, UN_TIPO_MOVIMIENTO              IN TIPOMOVIMIENTO.CODIGO%TYPE
)RETURN VARCHAR2;

-- 16. traerNombreDocumentoAsociado
FUNCTION FC_TRAER_NOMBRE_DOCASOCIADO
(
  UN_COMPANIA                     IN PCK_SUBTIPOS.TI_COMPANIA
, UN_COD_DOCUMENTO                IN DOCASOCIADO.CODIGO%TYPE
)RETURN VARCHAR2;

-- 17. numRequisiciones
FUNCTION FC_NUMREQUISICIONES
(
   UN_COMPANIA          IN PCK_SUBTIPOS.TI_COMPANIA,
   UN_TIPOMOVIMIENTO    IN MOVIMIENTO.TIPOMOVIMIENTO%TYPE,
   UN_MOVIMIENTOINICIAL IN MOVIMIENTO.NUMERO%TYPE,
   UN_MOVIMIENTOFINAL   IN MOVIMIENTO.NUMERO%TYPE
 )RETURN VARCHAR2;

-- 18. subirInventario
PROCEDURE PR_SUBIR_INVENTARIO
(
   UN_COMPANIA               IN PCK_SUBTIPOS.TI_COMPANIA,
   UN_INVENTARIOS            IN CLOB,
   UN_DEPENDENCIAS           IN CLOB,
   UN_RESPONSABLES           IN CLOB,
   UN_ORDENESCOMPRA          IN CLOB,
   UN_CLASEORDEN             IN ORDENDECOMPRA.CLASEORDEN%TYPE,
   UN_USUARIO                IN PCK_SUBTIPOS.TI_USUARIO
);

--19 movimientos inventario inicial
FUNCTION FC_MOVINVENTARIOINICIAL  
(
  UN_COMPANIA               IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_CLASEORDEN             IN ORDENDECOMPRA.CLASEORDEN%TYPE,
  UN_USUARIO                IN PCK_SUBTIPOS.TI_USUARIO
)
RETURN VARCHAR2;

--20 Verifica el valor de cuantía mínima

FUNCTION FC_CORREGIRCUANTIAMIN
(
   UN_COMPANIA          IN    PCK_SUBTIPOS.TI_COMPANIA,
    UN_ELEMENTOINICIAL  IN    VARCHAR2,  
    UN_ELEMENTOFINAL    IN    VARCHAR2,  
    UN_SERIEINICIAL     IN    PCK_SUBTIPOS.TI_ENTERO_LARGO,
    UN_SERIEFINAL       IN PCK_SUBTIPOS.TI_ENTERO_LARGO 
) RETURN NUMBER;

FUNCTION FC_VALIDAR_REQUISICION 

(
UN_COMPANIA              IN ORDENDESUMINISTRO.COMPANIA%TYPE,
UN_DEPENDENCIA           IN ORDENDESUMINISTRO.DEPENDENCIA%TYPE,
UN_TERCERO               IN ORDENDESUMINISTRO.TERCERO%TYPE,
UN_ANO                   IN D_DEPENDENCIA_RESPONSABLE.ANO%TYPE,
UN_SUCURSAL                   IN D_DEPENDENCIA_RESPONSABLE.SUCURSAL%TYPE,
UN_ACCION                IN VARCHAR2,
UN_NUEVO_VALOR_ESTIMADO  IN ORDENDESUMINISTRO.VALORESTIMADO%TYPE,
UN_NUMERO                IN ORDENDESUMINISTRO.VALORESTIMADO%TYPE
)
RETURN NUMBER;

PROCEDURE PR_ACTUALIZAR_PLACAS
  (
    UN_COMPANIA  IN PCK_SUBTIPOS.TI_COMPANIA, 
    UN_USUARIO   IN PCK_SUBTIPOS.TI_USUARIO      
  );

PROCEDURE PR_LOADFILE_CAMBIOPLACA
(
 UN_COMPANIA      IN PCK_SUBTIPOS.TI_COMPANIA,
 UN_CAMBIOS       IN CLOB,
 UN_USUARIO       IN PCK_SUBTIPOS.TI_USUARIO,
 UN_CAMBIO        IN D_CAMBIOSDEPLACA.CAMBIO%TYPE
);

PROCEDURE PR_CAMBIOS_DE_PLACA
(
 UN_COMPANIA      IN PCK_SUBTIPOS.TI_COMPANIA,
 UN_USUARIO       IN PCK_SUBTIPOS.TI_USUARIO,
 UN_CAMBIO        IN D_CAMBIOSDEPLACA.CAMBIO%TYPE,
 UN_OPCION        IN NUMBER
);

FUNCTION FC_CAMBIARPLACA
(
  UN_COMPANIA       IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_ELEMENTO_OLD   IN D_CAMBIOSDEPLACA.ELEMENTO%TYPE,
  UN_SERIE_OLD      IN D_CAMBIOSDEPLACA.SERIE%TYPE,
  UN_ELEMENTO_NEW   IN D_CAMBIOSDEPLACA.ELEMENTO%TYPE,
  UN_SERIE_NEW      IN D_CAMBIOSDEPLACA.SERIE%TYPE,
  UN_SINDEPRECIAR   IN PCK_SUBTIPOS.TI_LOGICO,
  UN_USUARIO        IN PCK_SUBTIPOS.TI_USUARIO,
  UN_CAMBIO         IN D_CAMBIOSDEPLACA.CAMBIO%TYPE
)
RETURN PCK_SUBTIPOS.TI_LOGICO;


FUNCTION FC_VALIDARINVENTARIO
(
   UN_COMPANIA               IN PCK_SUBTIPOS.TI_COMPANIA,
   UN_INVENTARIOS            IN CLOB,
   UN_DEPENDENCIAS           IN CLOB,
   UN_RESPONSABLES           IN CLOB,
   UN_ORDENESCOMPRA          IN CLOB
)
RETURN CLOB;
FUNCTION FC_GENERAR_PLANO_SECRETARIA 
(
  
 UN_COMPANIA         PCK_SUBTIPOS.TI_COMPANIA,
 UN_FECHAINICIAL     PCK_SUBTIPOS.TI_FECHA, 
 UN_FECHAFINAL       PCK_SUBTIPOS.TI_FECHA,  
 UN_TIPOCOMP         PCK_SUBTIPOS.TI_CLASECOMPROPPTO,
 UN_RESPONSABLEPPTO  PCK_SUBTIPOS.TI_TERCERO
)
RETURN CLOB;

END PCK_ALMACEN_COM4;