create or replace PACKAGE "PCK_ALMACEN" AS

  /* TODO enter package declarations (types, exceptions, methods etc) here */
  GL_ERROR_NUM                NUMBER:=52000;
  GL_MSG                      ERRORES.DESCRIPCION%TYPE;

  TYPE CUENTA IS RECORD (CUENTA VARCHAR2(32000),
                         DEBITO NUMBER,
                         CREDITO NUMBER,
                         TERCERO VARCHAR2(32000),
                         SUCURSAL VARCHAR2(32000),
                         CENTROCOSTO VARCHAR2(32000),
                         AUXILIAR VARCHAR2(32000),
                         BASEGRAVABLE NUMBER);

  TYPE CUENTAS IS TABLE OF CUENTA INDEX BY BINARY_INTEGER;

  TYPE SALDO IS RECORD  (CANTIDAD NUMBER,
                         VALORES NUMBER);

  TYPE SALDOS IS TABLE OF SALDO INDEX BY BINARY_INTEGER;

--01

  FUNCTION FC_HALLAPREDECESOR
    (
    UN_COMPANIA     IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_CAMPO        IN VARCHAR2,
    UN_VALOR_CAMPO  IN VARCHAR2,
    UN_TABLA        IN VARCHAR2,
    UN_OPCION       IN PCK_SUBTIPOS.TI_ENTERO DEFAULT NULL
    )
  RETURN VARCHAR2;

--03
  FUNCTION FC_VERIFICAR_NOMBRE_DEVOLUTIVO
  (
    UN_OPCION       IN PCK_SUBTIPOS.TI_ENTERO,
    UN_CONCODIGO    IN PCK_SUBTIPOS.TI_ENTERO,
    UN_CODIGO       IN VARCHAR2,
    UN_COMPANIA     IN VARCHAR2
  )
  RETURN VARCHAR2;

--04
  FUNCTION FC_VERIFICAR_PLACA
  (
    UN_COMPANIA   IN  VARCHAR2
  )
  RETURN CLOB;

   FUNCTION FC_GENCONSECUTIVOPOLIZAS
  (
    UN_NOMBRETABLA          IN VARCHAR2,
    UN_CONDICION            IN VARCHAR2,
    UN_NOMBRECAMPO          IN VARCHAR2,
    UN_INICIAL              IN VARCHAR2
  )
  RETURN VARCHAR2;

  FUNCTION FC_GUARDARPOLIZA
  (
    UN_COMPANIA             IN  PCK_SUBTIPOS.TI_COMPANIA,
    UN_ASEGURADORA          IN VARCHAR2,
    UN_NUMPOLIZA            IN VARCHAR2,
    UN_SUCURSAL             IN VARCHAR2,
    UN_FECHAI               IN DATE,
    UN_FECHAF               IN DATE,
    UN_GRUPO                IN VARCHAR2,
    UN_ELEMENTO             IN VARCHAR2,
    UN_PLACA                IN VARCHAR2,
    UN_RIESGO               IN VARCHAR2,
    UN_USUARIO            IN  PCK_SUBTIPOS.TI_USUARIO
  )
  RETURN NUMBER;

  FUNCTION FC_ACTUALIZAELEMENTOINVENTARIO
   (
    UN_COMPANIA           IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_CODIGOANT          IN VARCHAR2,
    UN_CODIGONUEVO        IN VARCHAR2,
    UN_TIPOCAMBIO         IN VARCHAR2
   )
   RETURN VARCHAR2;

  PROCEDURE PR_REVISARAFECTACIONMOV
   (
    UN_COMPANIA            IN PCK_SUBTIPOS.TI_COMPANIA, -- Código de la compañia
    UN_TIPO                IN VARCHAR2,                 -- Tipo de movimiento registrado
    UN_NUMERO              IN PCK_SUBTIPOS.TI_ENTERO_LARGO    -- Número del movimiento realizado
   );

  PROCEDURE PR_REVERSAREQUISICION
  (
  UN_COMPANIA           IN PCK_SUBTIPOS.TI_COMPANIA, -- Código de la compania
  UN_NUMERO             IN PCK_SUBTIPOS.TI_ENTERO_LARGO,    -- Número de la requisición
  UN_USUARIO               IN PCK_SUBTIPOS.TI_USUARIO
  );

  --9
  PROCEDURE PR_CAMBIARHORAMOVIMIENTO
  (
    UN_COMPANIA             IN PCK_SUBTIPOS.TI_COMPANIA,         --Código de la compania
    UN_TIPOMOVIMIENTO       IN D_MOVIMIENTO.TIPOMOVIMIENTO%TYPE, --Tipo de movimiento
    UN_NUMERO               IN PCK_SUBTIPOS.TI_ENTERO_LARGO,     --Número de movimiento
    UN_HORANUEVA            IN VARCHAR2,                         --Nueva hora asignada al movimiento
    UN_FORMATOHORA          IN VARCHAR2,                         --Formato de fecha asignado al movimiento
    UN_USUARIO              IN PCK_SUBTIPOS.TI_USUARIO           --USUARIO QUE INGRESO A LA APP
  );

  PROCEDURE PR_CAMBIARFECHAMOVIMIENTO
  (
  UN_COMPANIA              IN PCK_SUBTIPOS.TI_COMPANIA,       --Código de la compania
  UN_TIPOMOVIMIENTO        IN VARCHAR2,                          --Tipo de movimiento
  UN_NUMERO                IN PCK_SUBTIPOS.TI_ENTERO_LARGO,   --Numero Movimiento
  UN_FECHAACTUAL           IN DATE,                               --Fecha actual del movimiento
  UN_USUARIO               IN PCK_SUBTIPOS.TI_USUARIO
  );

  PROCEDURE PR_REVISADEVOLUTIVO
  (
  UN_COMPANIA              IN PCK_SUBTIPOS.TI_COMPANIA, --Código de la compania
  UN_PLACAINICIAL          IN PCK_SUBTIPOS.TI_ENTERO_LARGO,   --Número de serie inicial
  UN_PLACAFINAL            IN PCK_SUBTIPOS.TI_ENTERO_LARGO    --Número de serie final
  );

 FUNCTION FC_RETRESPONSABLE
 (
 UN_COMPANIA               IN PCK_SUBTIPOS.TI_COMPANIA,  --Código de la compania
 UN_DEPENDENCIA            IN VARCHAR2,                     --Código de la dependencia
 UN_MODULO                 IN PCK_SUBTIPOS.TI_MODULO     --Módulo
 )
 RETURN VARCHAR2;


 FUNCTION FC_NOMBREINVENTARIO
  (
  UN_COMPANIA              IN PCK_SUBTIPOS.TI_COMPANIA,    -- CÓDIGO DE LA COMPANIA
  UN_ELEMENTO              IN VARCHAR2,                    -- CÓDIGO DE LA DEPENDENCIA
  UN_OPCION                IN PCK_SUBTIPOS.TI_LOGICO,       -- MÓDULO
  UN_NOMCORTO              IN PCK_SUBTIPOS.TI_LOGICO DEFAULT 0
  )
RETURN VARCHAR2;


FUNCTION FC_ULTIMODEFECHASALIDA
  (
  UN_COMPANIA              IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_ELEMENTO              IN VARCHAR2,
  UN_FECHA                 IN DATE
  )
  RETURN DATE;


FUNCTION FC_VALIDATRANSACCIONALMHW
  (
  UN_COMPANIA               IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_BODEGAORIGEN           IN VARCHAR2,
  UN_BODEGADESTINO          IN VARCHAR2
  )
RETURN NUMBER;

PROCEDURE PR_GRABAPROVEEDORESGRAL
  (
  UN_COMPANIA               IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_TIPOMOVIMIENTO         IN VARCHAR2,
  UN_NUMERO                 IN VARCHAR2
  );

FUNCTION FC_INTERFACEALMACENUNOAUNO
  (
  UN_COMPANIA               IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_TIPOMOVIMIENTO         IN VARCHAR2,
  UN_NUMERO                 IN PCK_SUBTIPOS.TI_ENTERO_LARGO,
  UN_FECHA                  IN DATE,
  UN_DESCRIPCION            IN VARCHAR2,
  UN_DIGITOS                IN PCK_SUBTIPOS.TI_ENTERO,
  UN_TERCERO                IN VARCHAR2,
  UN_SUCURSAL               IN VARCHAR2,
  UN_CENTROCOSTO            IN VARCHAR2,
  UN_CREADOR                IN VARCHAR2,
  UN_VALORDOCUMENTO         IN PCK_SUBTIPOS.TI_DOBLE
  )RETURN NUMBER;

FUNCTION FC_INTERFACEUNOAUNO
  (
  UN_COMPANIA               IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_TIPO                   IN VARCHAR2,
  UN_NUMERO                 IN PCK_SUBTIPOS.TI_ENTERO_LARGO,
  UN_FECHA                  IN DATE,
  UN_DESCRIPCION            IN VARCHAR2,
  UN_TERCERO                IN VARCHAR2,
  UN_SUCURSAL               IN VARCHAR2,
  UN_CUENTAS                IN CUENTAS,
  UN_CREADOR                IN VARCHAR2,
  UN_VALORDOCUMENTO         IN PCK_SUBTIPOS.TI_DOBLE,
  UN_BASEGRAVABLE           IN PCK_SUBTIPOS.TI_DOBLE
  )
  RETURN NUMBER;

FUNCTION FC_GRABADEVOLUTIVOS
  (
  UN_COMPANIA                 IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_TIPOMOVIMIENTO           IN VARCHAR2,
  UN_NUMERO                   IN PCK_SUBTIPOS.TI_ENTERO_LARGO,
  UN_TIPO                     IN VARCHAR2,
  UN_DEPENDENCIA_DESTINO      IN VARCHAR2,
  UN_RESPONSABLE_DESTINO      IN VARCHAR2,
  UN_SUCURSAL_RESPONSABLE     IN VARCHAR2,
  UN_INVENTARIO_INICIAL       IN PCK_SUBTIPOS.TI_LOGICO,
  UN_FECHA                    IN DATE
  )
  RETURN NUMBER;

FUNCTION FC_REVISARPEPS
  (
  UN_COMPANIA                 IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_FECHAINICIAL             IN DATE,
  UN_FECHAFINAL               IN DATE,
  UN_ELEMENTOINICIAL          IN VARCHAR2,
  UN_PLACAINICIAL             IN PCK_SUBTIPOS.TI_ENTERO_LARGO,
  UN_ACTUALIZAR               IN PCK_SUBTIPOS.TI_LOGICO,
  UN_INFORMAR                 IN PCK_SUBTIPOS.TI_LOGICO
  )
  RETURN CLOB;

FUNCTION FC_REVISASIHAYMOVIMIENTO
  (
  UN_COMPANIA                 IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_TIPOMOVIMIENTO           IN VARCHAR2,
  UN_TIPOMOV                  IN VARCHAR2,
  UN_MOVIMIENTO               IN PCK_SUBTIPOS.TI_ENTERO_LARGO
  )
  RETURN NUMBER;

FUNCTION FC_DATOSBODEGAH
  (
  UN_COMPANIA                 IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_OPCION                   IN PCK_SUBTIPOS.TI_ENTERO
  )
  RETURN VARCHAR2;

--17
FUNCTION FC_ALCAMBIAR_VLRDMOV
(
  UN_COMPANIA   IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_TIPOMOV    IN VARCHAR2,
  UN_NUMMOV     IN PCK_SUBTIPOS.TI_ENTERO_LARGO
)
RETURN VARCHAR2;

PROCEDURE PR_REVISARPEPS
  (
  UN_COMPANIA                 IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_FECHAINICIAL             IN DATE,
  UN_FECHAFINAL               IN DATE,
  UN_ELEMENTOINICIAL          IN VARCHAR2,
  UN_SALDOQ                   IN PCK_SUBTIPOS.TI_DOBLE,
  UN_TIPOMOVIMIENTO_AFECT     IN VARCHAR2,
  UN_MOVIMIENTO_AFECT         IN PCK_SUBTIPOS.TI_ENTERO_LARGO,
  UN_CLASE                    IN VARCHAR2,
  UN_TIPOELEMENTO             IN VARCHAR2										  								 
  );

 FUNCTION FC_INSERTARDETALLES
 (
  UN_COMPANIA                 IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_FECHAINICIAL             IN DATE,
  UN_FECHAFINAL               IN DATE,
  UN_ELEMENTOINICIAL          IN VARCHAR2,
  UN_CANTIDAD                 IN PCK_SUBTIPOS.TI_DOBLE,
  UN_CODIGO                   IN PCK_SUBTIPOS.TI_ENTERO_LARGO,
  UN_SERIE                    IN PCK_SUBTIPOS.TI_ENTERO_LARGO,
  UN_TIPOMOVIMIENTO           IN VARCHAR2,
  UN_MOVIMIENTO               IN PCK_SUBTIPOS.TI_ENTERO_LARGO,
  UN_ESPECIFICACION           IN VARCHAR2,
  UN_TERCERO                  IN VARCHAR2,
  UN_SUCURSAL                 IN VARCHAR2,
  UN_VALORUNITARIO            IN PCK_SUBTIPOS.TI_DOBLE,
  UN_VALORTOTAL               IN PCK_SUBTIPOS.TI_DOBLE,
  UN_PORCIVA                  IN PCK_SUBTIPOS.TI_DOBLE,
  UN_PORCIMPCONSUMO           IN PCK_SUBTIPOS.TI_DOBLE,
  UN_VALORUNITARIO_ANTESIVA   IN PCK_SUBTIPOS.TI_DOBLE,
  UN_CENTRODECOSTO            IN VARCHAR2,
  UN_TIPOMOVIMIENTO_AFECT     IN VARCHAR2,
  UN_MOVIMIENTO_AFECT         IN PCK_SUBTIPOS.TI_ENTERO_LARGO,													 
  UN_CODIGO_AFECT             IN PCK_SUBTIPOS.TI_ENTERO_LARGO,
  UN_FUENTER                  IN D_MOVIMIENTO.FUENTEDERECURSO%TYPE,
  UN_REFERENCIA               IN D_MOVIMIENTO.REFERENCIA_CNT%TYPE,
  UN_AUXILIAR                 IN D_MOVIMIENTO.AUXILIAR%TYPE,
  UN_PROYECTO                 IN D_MOVIMIENTO.CODIGOPROYECTO%TYPE,
  UN_LOTE                     IN D_MOVIMIENTO.LOTE%TYPE
  )
  RETURN VARCHAR2;

  FUNCTION FC_BUSCAEXISTENCIA
  (
    UN_COMPANIA  IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_ELEMENTO  IN VARCHAR2
  )
  RETURN NUMBER;

FUNCTION FC_DEVUELVESALDOPEPS
  (
  UN_COMPANIA                 IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_TIPOMOVIMIENTO           IN VARCHAR2,
  UN_TIPOMOVIMIENTO_AFECT     IN VARCHAR2,
  UN_ELEMENTO                 IN VARCHAR2,
  UN_MOVIMIENTO               IN PCK_SUBTIPOS.TI_ENTERO_LARGO,
  UN_CODIGO                   IN PCK_SUBTIPOS.TI_ENTERO_LARGO,
  UN_CANTIDAD_NUEVA           IN PCK_SUBTIPOS.TI_DOBLE,
  UN_CANTIDAD_AFECTADA        IN PCK_SUBTIPOS.TI_DOBLE,
  UN_SERIE                    IN PCK_SUBTIPOS.TI_ENTERO_LARGO
  )
  RETURN VARCHAR2;


PROCEDURE PR_CORRECCIONDEVALOR
(
  UN_COMPANIA                 IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_TIPOMOVIMIENTO           IN TIPOMOVIMIENTO.CODIGO%TYPE,
  UN_MOVIMIENTO               IN PCK_SUBTIPOS.TI_ENTERO_LARGO, 
  UN_ELEMENTO                 IN PCK_SUBTIPOS.TI_ELEMENTO,
  UN_SERIE                    IN PCK_SUBTIPOS.TI_SERIE,
  UN_VALORUNITARIO            IN PCK_SUBTIPOS.TI_DOBLE,
  UN_VALORUNITARIOENTRADA     IN PCK_SUBTIPOS.TI_DOBLE,
  UN_ESPECIFICACION           IN D_MOVIMIENTO.ESPECIFICACION%TYPE
);



PROCEDURE PR_KARDEXSALDOPEPS
  (
  UN_COMPANIA          IN       VARCHAR2
  );

PROCEDURE PR_MOVIMIENTOSPOSTERIORES
  (
    UN_COMPANIA               IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_FECHA                  IN DATE,
    UN_HORA                   IN DATE,
    UN_ELEMENTO               IN VARCHAR2,
    UN_SERIE                  IN PCK_SUBTIPOS.TI_ENTERO_LARGO
  );

FUNCTION FC_ACTUALIZADEVOLUTIVO
 (
  UN_COMPANIA                 IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_ELEMENTO                 IN VARCHAR2,
  UN_SERIE                    IN PCK_SUBTIPOS.TI_ENTERO_LARGO
  )
RETURN NUMBER;

FUNCTION FC_ACTUALIZAVALORTOTAL
 (
  UN_COMPANIA                 IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_TIPOMOVIMIENTO           IN VARCHAR2,
  UN_MOVIMIENTO               IN PCK_SUBTIPOS.TI_ENTERO_LARGO,
  UN_PORCIVA                  IN PCK_SUBTIPOS.TI_DOBLE,
  UN_VALORUNITARIO            IN PCK_SUBTIPOS.TI_DOBLE,
  UN_CANTIDAD_NUEVA           IN PCK_SUBTIPOS.TI_DOBLE,
  UN_CODIGO                   IN PCK_SUBTIPOS.TI_ENTERO_LARGO
  )
RETURN PCK_SUBTIPOS.TI_LOGICO;

FUNCTION FC_REVERSARMOVIMIENTO
 (
  UN_COMPANIA                 IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_TIPOMOVIMIENTO           IN VARCHAR2,
  UN_MOVIMIENTO               IN PCK_SUBTIPOS.TI_ENTERO_LARGO
  )
  RETURN CLOB;

  --35
  FUNCTION FC_VERIFICAESTADOALM
  (
    UN_COMPANIA                IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_ANO                     IN PCK_SUBTIPOS.TI_ANIO,
    UN_MES                     IN PCK_SUBTIPOS.TI_MES DEFAULT NULL
  )
  RETURN PCK_SUBTIPOS.TI_LOGICO;

  --36 
  FUNCTION FC_ACTUALIZAR_SALDOPEPS
  (
    UN_COMPANIA         IN PCK_SUBTIPOS.TI_COMPANIA, 
    UN_ANOINICIAL       IN PCK_SUBTIPOS.TI_ANIO,
    UN_MESINICIAL       IN PCK_SUBTIPOS.TI_MES,
    UN_ANOFINAL         IN PCK_SUBTIPOS.TI_ANIO,
    UN_MESFINAL         IN PCK_SUBTIPOS.TI_MES,
    UN_ELEMENTOINICIAL  IN VARCHAR2,
    UN_ELEMENTOFINAL    IN VARCHAR2
  )
  RETURN VARCHAR;

  FUNCTION FC_BUSCAEXISTENCIAFL
  (
    UN_COMPANIA                 IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_ELEMENTO                 IN VARCHAR2,
    UN_LOTE                     IN D_MOVIMIENTO.LOTE%TYPE,
    UN_FUENTE                   IN D_MOVIMIENTO.FUENTEDERECURSO%TYPE
  )
  RETURN NUMBER;

END PCK_ALMACEN;
