create or replace PACKAGE PCK_PREDIAL_COM8 AS 

--1
FUNCTION FC_ANULAR_PRESCRIPCION
(
    UN_COMPANIA      IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_CODIGO        IN IP_FACTURADOS.CODIGO%TYPE,
    UN_NUMERO_ORDEN  IN PCK_SUBTIPOS.TI_NUMORDEN,
    UN_FECHAANTERIOR IN DATE,
    UN_RESOLUCIONANT IN IP_FACTURADOS.OBSERVACIONES%TYPE,
    UN_USUARIO       IN PCK_SUBTIPOS.TI_USUARIO,
    UN_OBSERVACION   IN PCK_SUBTIPOS.TI_PARAMETRO,
    UN_RESOLUCION    IN PCK_SUBTIPOS.TI_PARAMETRO,
    UN_PRESCRIPCION  IN PCK_SUBTIPOS.TI_ENTERO
) RETURN PCK_SUBTIPOS.TI_LOGICO;

--2
FUNCTION FC_VALIDARTIPOUNO
(
    UN_LINEATEXTO   IN VARCHAR2,
    UN_DEPARTAMENTO IN IP_IGAC_TIPO_UNO.DEPARTAMENTO%TYPE,
    UN_MUNICIPIO    IN IP_IGAC_TIPO_UNO.MUNICIPIO%TYPE 
)RETURN PCK_SUBTIPOS.TI_LOGICO;

--3
FUNCTION FC_INSERTAREGISTROIGACUNO
(
    UN_COMPANIA         IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_CADENA           IN CLOB,
    UN_ANOFECHA         IN PCK_SUBTIPOS.TI_ANIO,
    UN_USUARIO        	IN PCK_SUBTIPOS.TI_USUARIO,
    UN_CODIGOPAIS			  IN PAISES.PAIS%TYPE,
    UN_DEPARTAMENTO     IN DEPARTAMENTO.CODIGO%TYPE,
    UN_MUNICIPIO        IN CIUDAD.CODIGO%TYPE,
    UN_IND_TOTAL        IN PCK_SUBTIPOS.TI_LOGICO,
    UN_NOMBRECOMPANIA   IN COMPANIA.NOMBRE%TYPE
)RETURN PCK_SUBTIPOS.TI_LOGICO;

--4
FUNCTION FC_INGRESARIGACTIPOUNO (
    UN_COMPANIA       	IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_ARCHIVOTEXTO   	IN PCK_SUBTIPOS.TI_STRSQL,
    UN_ANOFECHA			    IN PCK_SUBTIPOS.TI_ANIO,
    UN_LISTADOCUMENTOS 	IN VARCHAR2,
    UN_LINEAS 			    IN PCK_SUBTIPOS.TI_LONG,
    UN_USUARIO        	IN PCK_SUBTIPOS.TI_USUARIO,
    UN_CODIGOPAIS			  IN PAISES.PAIS%TYPE
)RETURN PCK_SUBTIPOS.TI_LOGICO;

--5
FUNCTION FC_ACTUALIZARAPORTERECIBO 
(
    UN_COMPANIA           IN PCK_SUBTIPOS.TI_COMPANIA, 
    UN_USUARIO            IN PCK_SUBTIPOS.TI_USUARIO,
    UN_CONCEPTO           IN VARCHAR2,
    UN_VALORAPORTE        IN PCK_SUBTIPOS.TI_DOBLE,
    UN_PREVAL             IN PCK_SUBTIPOS.TI_DOBLE,
    UN_PROYECTO           IN PCK_SUBTIPOS.TI_LONG,
    UN_NUMEROORDEN        IN PCK_SUBTIPOS.TI_NUMORDEN,
    UN_FACTURA            IN PCK_SUBTIPOS.TI_DOCNUM,
    UN_INDAPORTE          IN PCK_SUBTIPOS.TI_LOGICO
)
RETURN PCK_SUBTIPOS.TI_ENTERO;
--6
FUNCTION FC_VALIDA_CFG_TARIFAS 
(
      UN_IND_TIPOESTRATO IN PCK_SUBTIPOS.TI_LOGICO
     ,UN_TIPO_INICIAL    IN IP_TIPO_PREDIO.CODIGO%TYPE
     ,UN_TIPO_FINAL      IN IP_TIPO_PREDIO.CODIGO%TYPE
     ,UN_IND_ESTRATO     IN PCK_SUBTIPOS.TI_LOGICO
     ,UN_ESTRATO_INICIAL IN IP_TABLA_ESTRATOS.CODIGO_ESTRATO%TYPE
     ,UN_ESTRATO_FINAL   IN IP_TABLA_ESTRATOS.CODIGO_ESTRATO%TYPE
)
RETURN PCK_SUBTIPOS.TI_LOGICO;

--7
FUNCTION FC_REGISTRAR_CERTIFICADO
(
  UN_COMPANIA 		    IN    PCK_SUBTIPOS.TI_COMPANIA,
  UN_FORMULARIO       IN    VARCHAR2,
  UN_PREDIO           IN    IP_CERTIFICADOCATAS.CODIGOPREDIO%TYPE,
  UN_DIRECCION        IN    IP_CERTIFICADOCATAS.DIRECCION%TYPE,
  UN_NOMBRE           IN    IP_CERTIFICADOCATAS.NOMBRE%TYPE,
  UN_CEDULA           IN    IP_CERTIFICADOCATAS.NIT%TYPE,
  UN_NUMORDEN         IN    IP_CERTIFICADOCATAS.NUMERO_ORDEN%TYPE,
  UN_VALOR            IN    IP_CERTIFICADOCATAS.VALOR%TYPE,
  UN_SUCURSAL         IN    IP_CERTIFICADOCATAS.SUCURSAL%TYPE,
  UN_USUARIO          IN    PCK_SUBTIPOS.TI_USUARIO,
  UN_RECIBO           IN    IP_CERTIFICADOPS.REC_VALORIZACION%TYPE,
  UN_DESTINO          IN    IP_CERTIFICADOPS.DESTINO%TYPE,
  UN_BANCO            IN    IP_CERTIFICADOPS.PAG_BAN%TYPE,
  UN_FECHA            IN    IP_CERTIFICADOPS.PAG_FEC%TYPE,
  UN_ANIO             IN    IP_CERTIFICADOPS.PAGO_ANO%TYPE
)RETURN VARCHAR2;
--8

FUNCTION FC_APLICARTODAS_CFGTARIFAS
(
    UN_COMPANIA IN PCK_SUBTIPOS.TI_COMPANIA
   ,UN_USUARIO  IN PCK_SUBTIPOS.TI_USUARIO
)RETURN PCK_SUBTIPOS.TI_LOGICO;
--9
FUNCTION FC_APLICAR_CFGTARIFA
(
    UN_COMPANIA IN PCK_SUBTIPOS.TI_COMPANIA
   ,UN_ID       IN IP_CONFIGURACIONTARIFAS.ID%TYPE
   ,UN_USUARIO  IN PCK_SUBTIPOS.TI_USUARIO 
)RETURN PCK_SUBTIPOS.TI_LOGICO;

--10

PROCEDURE PR_EXINTXDUPLICIDADCAT
  (
    UN_COMPANIA        IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_NUMEROORDEN     IN PCK_SUBTIPOS.TI_NUMORDEN,
    UN_PREDIO          IN PCK_SUBTIPOS.TI_CODPREDIO,
    UN_ANOINICIAL      IN PCK_SUBTIPOS.TI_ENTERO,
    UN_ANOFINAL        IN PCK_SUBTIPOS.TI_ENTERO,
    UN_RESOLUCION      IN PCK_SUBTIPOS.TI_PARAMETRO,
    UN_ELABORADOPOR    IN IP_USUARIOS_PREDIAL.OBSERVACIO%TYPE,
    UN_FIRMADOPOR      IN IP_USUARIOS_PREDIAL.OBSERVACIO%TYPE,
    UN_FECHARESOLUCION IN VARCHAR2,
    UN_TIPOEXENCION    IN PCK_SUBTIPOS.TI_LOGICO,
    UN_USUARIO         IN PCK_SUBTIPOS.TI_USUARIO  );

--11
FUNCTION FC_PREPARAR_PERIODO
(
    UN_COMPANIA      IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_USUARIO       IN PCK_SUBTIPOS.TI_USUARIO,
    UN_ANO           IN PCK_SUBTIPOS.TI_ANIO,
    UN_MES           IN PCK_SUBTIPOS.TI_MES,
    UN_PERIODO_BASE  IN PCK_SUBTIPOS.TI_CAMPOS,
    UN_NUMERO_ORDEN  IN PCK_SUBTIPOS.TI_CAMPOS

) RETURN PCK_SUBTIPOS.TI_ENTERO;    

--12
PROCEDURE PR_REGISTRARPAGOSWEB
  (
  	UN_COMPANIA     IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_REFERENCIA   IN VARCHAR2,
    UN_PREDIO       IN PCK_SUBTIPOS.TI_CODPREDIO,
    UN_NUMEROORDEN  IN PCK_SUBTIPOS.TI_NUMORDEN,
    UN_PYS     		IN VARCHAR2,
    UN_INSCRITO     IN VARCHAR2,
    UN_NITINSCRITO  IN VARCHAR2,
    UN_USUARIO      IN PCK_SUBTIPOS.TI_USUARIO,
    UN_ELIMINAR     IN VARCHAR2
  );


--13
FUNCTION FC_ACTUALIZAR_INCR_AUTOAVALUO
  (
      UN_COMPANIA    IN PCK_SUBTIPOS.TI_COMPANIA,
      UN_NUMEROORDEN IN PCK_SUBTIPOS.TI_NUMORDEN,
      UN_USUARIO     IN PCK_SUBTIPOS.TI_USUARIO

  ) RETURN PCK_SUBTIPOS.TI_ENTERO_LARGO;

--14
FUNCTION FC_GENERAR_AUTOAVALUO
  (
       UN_COMPANIA         IN    PCK_SUBTIPOS.TI_COMPANIA,
       UN_NUMERO_ORDEN     IN    IP_AUTOAVALUO.NUMERO_ORDEN%TYPE,
       UN_USUARIO        	 IN    PCK_SUBTIPOS.TI_USUARIO
  ) RETURN PCK_SUBTIPOS.TI_LOGICO;

--15
FUNCTION FC_ASIGNA_TARIFA 
  (
      UN_COMPANIA IN    PCK_SUBTIPOS.TI_COMPANIA,
      UN_TRPCOD   IN  IP_TARIFAS.TRPCOD%TYPE,
      UN_TRPANO   IN  IP_TARIFAS.TRPANO%TYPE,
      UN_AVALUO   IN  IP_TARIFAS.TRPVAL%TYPE 
  )RETURN VARCHAR2;
--16
FUNCTION FC_REGISTRAR_PAGOSDOBLES
  (
     UN_USUARIO        IN PCK_SUBTIPOS.TI_USUARIO,
     UN_COMPANIA       IN PCK_SUBTIPOS.TI_COMPANIA,
     UN_NUMERO_ORDEN   IN PCK_SUBTIPOS.TI_PARAMETRO,
     UN_CODIGO         IN PCK_SUBTIPOS.TI_PARAMETRO,
     UN_FACTURA        IN PCK_SUBTIPOS.TI_PARAMETRO,
     UN_PAGOD_BANCO    IN PCK_SUBTIPOS.TI_PARAMETRO,
     UN_PAGOD_PAQUETE  IN PCK_SUBTIPOS.TI_PARAMETRO,
     UN_PAGOD_ANO      IN PCK_SUBTIPOS.TI_ANIO,
     UN_PAGOD_FECHA    IN DATE     
  )
RETURN PCK_SUBTIPOS.TI_ENTERO;

--17
FUNCTION FC_ACTUALIZAINDACTIVO
(
     UN_COMPANIA   IN PCK_SUBTIPOS.TI_COMPANIA
    ,UN_TIPO       IN IP_NUMEROSDEFACTURA.TIPO%TYPE
    ,UN_IND_ACTIVO IN PCK_SUBTIPOS.TI_LOGICO 
    ,UN_USUARIO    IN PCK_SUBTIPOS.TI_USUARIO
)RETURN PCK_SUBTIPOS.TI_LOGICO;

--18
FUNCTION FC_VALIDARCONSECUTIVO  
(
    UN_COMPANIA    IN PCK_SUBTIPOS.TI_COMPANIA
   ,UN_SECUENCIA   IN IP_NUMEROSDEFACTURA.SECUENCIA%TYPE
   ,UN_CONSECUTIVO IN IP_NUMEROSDEFACTURA.CONSECUTIVO%TYPE 
   ,UN_TIPO        IN IP_NUMEROSDEFACTURA.TIPO%TYPE 	 
)RETURN PCK_SUBTIPOS.TI_LOGICO;

--19
FUNCTION FC_ENCABEZADO_COLUMNA 
(
 UN_COMPANIA      IN  PCK_SUBTIPOS.TI_COMPANIA,
 UN_NIT           IN  COMPANIA.NITCOMPANIA%TYPE,
 UN_CODIGO        IN  PCK_SUBTIPOS.TI_ENTERO, 
 UN_ANIO          IN  PCK_SUBTIPOS.TI_ANIO   DEFAULT NULL
)RETURN VARCHAR2;

--20
FUNCTION FC_PREPARARLISTADOGRAL  
(
  UN_COMPANIA             IN  PCK_SUBTIPOS.TI_COMPANIA,
  UN_CLAVE                IN  PCK_SUBTIPOS.TI_LOGICO,
  UN_PALABRACLAVE         IN  PCK_SUBTIPOS.TI_USUARIO,
  UN_NOMBRES              IN  PCK_SUBTIPOS.TI_LOGICO,
  UN_NOMBREINICIAL        IN  IP_USUARIOS_PREDIAL.NOMBRE%TYPE,
  UN_NOMBREFINAL          IN  IP_USUARIOS_PREDIAL.NOMBRE%TYPE,
  UN_DIRECCIONINICIAL     IN  IP_USUARIOS_PREDIAL.DIRECCION%TYPE,
  UN_DIRECCIONFINAL       IN  IP_USUARIOS_PREDIAL.DIRECCION%TYPE,
  UN_INDICADOR            IN  PCK_SUBTIPOS.TI_LOGICO,
  UN_SOLOPREDIOS          IN  PCK_SUBTIPOS.TI_LOGICO,
  UN_ORDENADO             IN  PCK_SUBTIPOS.TI_LOGICO 
)
RETURN CLOB;

--21
FUNCTION FC_VALORDESCUENTOESPECIAL
(  
    UN_COMPANIA     IN PCK_SUBTIPOS.TI_COMPANIA
   ,UN_PREDIO       IN PCK_SUBTIPOS.TI_CODPREDIO
   ,UN_NUMERO_ORDEN IN PCK_SUBTIPOS.TI_NUMORDEN
) RETURN PCK_SUBTIPOS.TI_DOBLE;

--22
FUNCTION FC_PORC_DESC_LOTES
(
	 UN_COMPANIA IN PCK_SUBTIPOS.TI_COMPANIA 
	,UN_PREDIO   IN PCK_SUBTIPOS.TI_CODPREDIO
	,UN_FECHA_EV IN DATE
) RETURN PCK_SUBTIPOS.TI_DOBLE;

--23
FUNCTION FC_MJSDSCTOESP
( 
	 UN_COMPANIA IN PCK_SUBTIPOS.TI_COMPANIA 
	,UN_PREDIO   IN PCK_SUBTIPOS.TI_CODPREDIO
	,UN_FECHA_EV IN DATE
) RETURN IP_DESCUENTOS_ESPECIALES.TITULO_RANGO%TYPE;

--24
FUNCTION FC_GENERAPLANOFACTURACION
(
     UN_COMPANIA      IN PCK_SUBTIPOS.TI_COMPANIA
    ,UN_CODIGOINICIAL IN PCK_SUBTIPOS.TI_CODPREDIO
    ,UN_CODIGOFINAL   IN PCK_SUBTIPOS.TI_CODPREDIO
    ,UN_NOMBREINICIAL IN IP_USUARIOS_PREDIAL.NOMBRE%TYPE
    ,UN_NOMBREFINAL   IN IP_USUARIOS_PREDIAL.NOMBRE%TYPE
    ,UN_ANIOINICIAL   IN PCK_SUBTIPOS.TI_ANIO
    ,UN_ANIOFINAL     IN PCK_SUBTIPOS.TI_ANIO
    ,UN_HASTAANIO     IN PCK_SUBTIPOS.TI_ANIO
    ,UN_NITINICIAL    IN IP_USUARIOS_PREDIAL.NIT%TYPE
    ,UN_NITFINAL      IN IP_USUARIOS_PREDIAL.NIT%TYPE
    ,UN_NUMERO_ORDEN  IN PCK_SUBTIPOS.TI_NUMORDEN 
    ,UN_ORDEN         IN VARCHAR2 
    ,UN_VALORINFERIOR IN PCK_SUBTIPOS.TI_DOBLE
    ,UN_VALORSUPERIOR IN PCK_SUBTIPOS.TI_DOBLE
)
 RETURN CLOB ;

--25
FUNCTION FC_GENERAPLANOFACTURACIONASO98
(
	 UN_COMPANIA      IN PCK_SUBTIPOS.TI_COMPANIA  
	,UN_CODIGOINICIAL IN PCK_SUBTIPOS.TI_CODPREDIO
	,UN_CODIGOFINAL   IN PCK_SUBTIPOS.TI_CODPREDIO
) RETURN CLOB;

--26
FUNCTION FC_GENERAPLANOPUNTOS
(
      UN_COMPANIA      IN PCK_SUBTIPOS.TI_COMPANIA
    , UN_NUMERO_ORDEN  IN PCK_SUBTIPOS.TI_NUMORDEN  
	  , UN_CODIGOINICIAL IN PCK_SUBTIPOS.TI_CODPREDIO
	  , UN_CODIGOFINAL   IN PCK_SUBTIPOS.TI_CODPREDIO
)RETURN CLOB;

--27
FUNCTION FC_NOMBRECOPROPIETARIO 
( 
	   UN_COMPANIA     IN PCK_SUBTIPOS.TI_COMPANIA
    ,UN_CODIGOPRED   IN PCK_SUBTIPOS.TI_CODPREDIO
    ,UN_NUMERO_ORDEN IN PCK_SUBTIPOS.TI_NUMORDEN
) RETURN IP_USUARIOS_PREDIAL.NOMBRE%TYPE;

--28
FUNCTION FC_ANIOS_PAGOS
(
	 UN_COMPANIA     IN PCK_SUBTIPOS.TI_COMPANIA
	,UN_CODIGO       IN PCK_SUBTIPOS.TI_CODPREDIO
  ,UN_NUMERO_ORDEN IN PCK_SUBTIPOS.TI_NUMORDEN
) RETURN VARCHAR2;

--29
FUNCTION FC_CALCULA_USUARIOSAFACTURAR
(
      UN_COMPANIA         IN PCK_SUBTIPOS.TI_COMPANIA
    , UN_NUMERO_ORDEN     IN PCK_SUBTIPOS.TI_NUMORDEN
    , UN_CODIGOINICIAL    IN PCK_SUBTIPOS.TI_CODPREDIO
    , UN_CODIGOFINAL      IN PCK_SUBTIPOS.TI_CODPREDIO
    , UN_DIRECCIONINICIAL IN IP_USUARIOS_PREDIAL.DIRECCION%TYPE
    , UN_DIRECCIONFINAL   IN IP_USUARIOS_PREDIAL.DIRECCION%TYPE
    , UN_NOMBREINICIAL    IN IP_USUARIOS_PREDIAL.NOMBRE%TYPE
    , UN_NOMBREFINAL      IN IP_USUARIOS_PREDIAL.NOMBRE%TYPE
    , UN_NITINICIAL       IN IP_USUARIOS_PREDIAL.NIT%TYPE
    , UN_NITFINAL         IN IP_USUARIOS_PREDIAL.NIT%TYPE 
    , UN_ANIOINICIAL      IN PCK_SUBTIPOS.TI_ANIO
    , UN_ANIOFINAL        IN PCK_SUBTIPOS.TI_ANIO
    , UN_VALORINFERIOR    IN PCK_SUBTIPOS.TI_DOBLE
    , UN_VALORSUPERIOR    IN PCK_SUBTIPOS.TI_DOBLE
    , UN_HASTAANO         IN PCK_SUBTIPOS.TI_ANIO
    , UN_TIPOPREDIO       IN VARCHAR2
)RETURN PCK_SUBTIPOS.TI_ENTERO_LARGO;

--30
FUNCTION FC_FACTURARLOTEPREDIAL
(
      UN_COMPANIA         IN PCK_SUBTIPOS.TI_COMPANIA
    , UN_NITCOMPANIA      IN COMPANIA.NITCOMPANIA%TYPE 
    , UN_SIGLACOMPANIA    IN COMPANIA.SIGLACOMPANIA%TYPE
    , UN_NUMERO_ORDEN     IN PCK_SUBTIPOS.TI_NUMORDEN
    , UN_CODIGOINICIAL    IN PCK_SUBTIPOS.TI_CODPREDIO
    , UN_CODIGOFINAL      IN PCK_SUBTIPOS.TI_CODPREDIO
    , UN_DIRECCIONINICIAL IN IP_USUARIOS_PREDIAL.DIRECCION%TYPE
    , UN_DIRECCIONFINAL   IN IP_USUARIOS_PREDIAL.DIRECCION%TYPE
    , UN_NOMBREINICIAL    IN IP_USUARIOS_PREDIAL.NOMBRE%TYPE
    , UN_NOMBREFINAL      IN IP_USUARIOS_PREDIAL.NOMBRE%TYPE
    , UN_NITINICIAL       IN IP_USUARIOS_PREDIAL.NIT%TYPE
    , UN_NITFINAL         IN IP_USUARIOS_PREDIAL.NIT%TYPE 
    , UN_ANIOINICIAL      IN PCK_SUBTIPOS.TI_ANIO
    , UN_ANIOFINAL        IN PCK_SUBTIPOS.TI_ANIO
    , UN_VALORINFERIOR    IN PCK_SUBTIPOS.TI_DOBLE
    , UN_VALORSUPERIOR    IN PCK_SUBTIPOS.TI_DOBLE
    , UN_HASTAANO         IN PCK_SUBTIPOS.TI_ANIO
    , UN_FECHALIMITE      IN DATE
    , UN_TIPOPREDIO       IN VARCHAR2 
    , UN_USUARIO          IN PCK_SUBTIPOS.TI_USUARIO

)  RETURN VARCHAR2;

--31

FUNCTION FC_VALIDARFACTURAMF
(
    UN_COMPANIA     IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_NUMERO_ORDEN IN PCK_SUBTIPOS.TI_NUMORDEN,
    UN_FECHAPAGO    IN DATE,
    UN_NUMFACTURA   IN IP_RECIBOS_DE_PAGO.DOCNUM%TYPE,
    UN_USUARIO      IN PCK_SUBTIPOS.TI_USUARIO 

)   RETURN PCK_SUBTIPOS.TI_LOGICO;

--32

FUNCTION FC_VALIDAPAGO 

(
    UN_COMPANIA       	IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_NUMERO_ORDEN     IN PCK_SUBTIPOS.TI_NUMORDEN,
    UN_PAQUETE          IN IP_RECIBOS_DE_PAGO.PAQUETEPAG%TYPE,
    UN_PAGOBANCO        IN IP_RECIBOS_DE_PAGO.PAG_BANPAG%TYPE,
    UN_PREFECHAVAR      IN DATE,
    UN_CODIGO           IN IP_RECIBOS_DE_PAGO.PRECOD%TYPE,
    UN_NUMFACTURA       IN IP_RECIBOS_DE_PAGO.DOCNUM%TYPE,
    UN_USUARIO          IN PCK_SUBTIPOS.TI_USUARIO

)   RETURN PCK_SUBTIPOS.TI_LOGICO;

--33
PROCEDURE PR_ACTUALIZAR_ANTESPAGOSDOBLES (
   UN_COMPANIA     PCK_SUBTIPOS.TI_COMPANIA
  ,UN_VALOR        IP_PAGOSDOBLES.VALOR%TYPE
  ,UN_CODIGO       IP_FACTURADOS.CODIGO%TYPE
  ,UN_NUMERO_ORDEN IP_FACTURADOS.NUMERO_ORDEN%TYPE
  ,UN_ANIOEXC      PCK_SUBTIPOS.TI_ANIO
);

END PCK_PREDIAL_COM8;