create or replace PACKAGE "PCK_PREDIAL_COM2" AS 

  /* TODO enter package declarations (types, exceptions, methods etc) here */ 

  GL_ERROR_NUM                NUMBER:=52000;  
  GL_MSG                      ERRORES.DESCRIPCION%TYPE;
  --1
  FUNCTION FC_MODIFICARRECIBOS
  (
    UN_COMPANIA             IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_MODIFICACION         IN VARCHAR2,
    UN_TIPORECIBO           IN VARCHAR2,
    UN_TIPOMODIFICACION     IN VARCHAR2,
    UN_FECHAMODIFICACION    IN DATE,
    UN_CODIGO               IN PCK_SUBTIPOS.TI_CODPREDIO,
    UN_FACTURA              IN PCK_SUBTIPOS.TI_DOCNUM DEFAULT NULL,
    UN_FECHA                IN DATE,
    UN_BANCO                IN IP_BANCOS.CODIGOBANCO%TYPE,
    UN_PAQUETE              IN VARCHAR2,
    UN_VALOR                IN PCK_SUBTIPOS.TI_DOBLE,
    UN_ANULAR               IN PCK_SUBTIPOS.TI_DOCNUM DEFAULT NULL,
    UN_ACTIVAR              IN PCK_SUBTIPOS.TI_DOCNUM DEFAULT NULL,
    UN_CAMPOANTERIOR        IN VARCHAR2,
    UN_USUARIO              IN PCK_SUBTIPOS.TI_USUARIO
  )RETURN VARCHAR2;

  --2
  FUNCTION FC_CAMBIARVALORES
  (
    UN_COMPANIA             IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_TIPORECIBO           IN VARCHAR2,
    UN_TIPOMODIFICACION     IN VARCHAR2,
    UN_BANCO                IN IP_BANCOS.CODIGOBANCO%TYPE,
    UN_CODIGO               IN PCK_SUBTIPOS.TI_CODPREDIO,
    UN_FACTURA              IN PCK_SUBTIPOS.TI_DOCNUM DEFAULT NULL,
    UN_FECHA                IN DATE,
    UN_VALOR                IN PCK_SUBTIPOS.TI_DOBLE,
    UN_PAQUETE              IN VARCHAR2,
    UN_PREFEC               IN DATE,
    UN_PAG_BAN              IN IP_BANCOS.CODIGOBANCO%TYPE,
    UN_PAQUETERS            IN VARCHAR2,
    UN_ACTIVAR              IN PCK_SUBTIPOS.TI_DOCNUM,
    UN_ACUERDO              IN VARCHAR2, 
    UN_NC_ACUERDO           IN VARCHAR2,
    UN_USUARIO              IN PCK_SUBTIPOS.TI_USUARIO
  )RETURN VARCHAR2;

  --3
  PROCEDURE PR_ARREGLARCUPONES
  (
    UN_COMPANIA      IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_FECHA         IN DATE,
    UN_BANCO         IN IP_BANCOS.CODIGOBANCO%TYPE,
    UN_PAQUETE       IN VARCHAR2,
    UN_USUARIO        IN PCK_SUBTIPOS.TI_USUARIO
  );
--4
  FUNCTION FC_ACT_ULTVIGCANCELADA
  ( 
  UN_COMPANIA                 IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_CODINICIAL               IN PCK_SUBTIPOS.TI_CODPREDIO,
  UN_CODFINAL                 IN PCK_SUBTIPOS.TI_CODPREDIO,
  UN_MODCOD                   IN IP_AUDITORIA.MODCOD%TYPE, 
  UN_USUARIO                  IN PCK_SUBTIPOS.TI_USUARIO, 
  UN_DESCRIPCION              IN IP_AUDITORIA.DESCRIPCION%TYPE
  )  
  RETURN VARCHAR2;
--5
  PROCEDURE PR_VALIDARCODIGOANT

(
  UN_COMPANIA                IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_CODIGO_ANTERIOR         IN PCK_SUBTIPOS.TI_CODPREDIO,
  UN_CODIGO_NUEVO            IN PCK_SUBTIPOS.TI_CODPREDIO   
);

--6
PROCEDURE PR_HAGATRASLADO 
(
  UN_COMPANIA           IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_CODIGO_ANTERIOR    IN PCK_SUBTIPOS.TI_CODPREDIO,
  UN_CODIGO_NUEVO       IN PCK_SUBTIPOS.TI_CODPREDIO,
  UN_USUARIO            IN PCK_SUBTIPOS.TI_USUARIO,
  UN_OPCION_REGISTRO    IN PCK_SUBTIPOS.TI_LOGICO
);

--7
PROCEDURE PR_REGISTRARPAGOANOANTE
  (
    UN_COMPANIA				  IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_V_50					  IN VARCHAR2,
    UN_V_DAMNIFICADOS		  IN VARCHAR2,
    UN_FECHACORTE			  IN VARCHAR2,
    UN_CODPREDIO			  IN PCK_SUBTIPOS.TI_CODPREDIO,
    UN_CODIGOBANCO			  IN IP_BANCOS.CODIGOBANCO%TYPE,
    UN_ANOFIN				  IN PCK_SUBTIPOS.TI_ANIO,
    UN_NRORECIBO			  IN PCK_SUBTIPOS.TI_DOCNUM,
    UN_TOTALPAGADO			  IN PCK_SUBTIPOS.TI_DOBLE,
    UN_TARIFAAP				  IN VARCHAR2,
    UN_TRPCOD				  IN VARCHAR2,
    UN_OBSERVACIONES		  IN VARCHAR2,
    UN_USUARIO				  IN PCK_SUBTIPOS.TI_USUARIO
  );

--8
PROCEDURE PR_AUSUBAVALUOSDOS
(
	UN_COMPANIA				  IN PCK_SUBTIPOS.TI_COMPANIA,
	UN_RESOLUCION			  IN VARCHAR2,
	UN_PREANO				  IN PCK_SUBTIPOS.TI_ANIO,
	UN_CODIGO				  IN PCK_SUBTIPOS.TI_CODPREDIO,
	UN_ULTIMO_ANIO			  IN PCK_SUBTIPOS.TI_ANIO,
	UN_AVALUO				  IN PCK_SUBTIPOS.TI_DOBLE,
	UN_TRPCOD				  IN VARCHAR2
);

--9
FUNCTION FC_CLICKPROPIETARIOS
(
  UN_COMPANIA 		  IN PCK_SUBTIPOS.TI_COMPANIA,
	UN_PAIS 		      IN VARCHAR2,
	UN_DEPARTAMENTO   IN VARCHAR2,
	UN_MUNICIPIO 	    IN VARCHAR2,
	UN_RESOLUCION 	  IN VARCHAR2,
  UN_CONSECUTIVO 	  IN NUMBER,
	UN_ANO 			      IN PCK_SUBTIPOS.TI_ANIO,
	UN_CODIGO 		    IN PCK_SUBTIPOS.TI_CODPREDIO,
  UN_USUARIO 			  IN PCK_SUBTIPOS.TI_USUARIO
)
RETURN VARCHAR2;

--10
FUNCTION FC_ACEPTARPROPIETARIOS
(
	UN_RESOLUCION		IN VARCHAR2,
  UN_PAIS      			IN VARCHAR2,
  UN_DEPARTAMENTO 		IN VARCHAR2,
  UN_MUNICIPIO 			IN VARCHAR2,
  UN_ANO 				IN PCK_SUBTIPOS.TI_ANIO,
  UN_CODIGO 			IN PCK_SUBTIPOS.TI_CODPREDIO,
  UN_USUARIO 			IN PCK_SUBTIPOS.TI_USUARIO,
  UN_COMPANIA			IN PCK_SUBTIPOS.TI_COMPANIA
)
RETURN NUMBER;

--11
FUNCTION FC_ACTUALIZA_NUM_ORDEN
(
    UN_COMPANIA     IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_CODIGO 			IN PCK_SUBTIPOS.TI_CODPREDIO,
    UN_USUARIO			IN PCK_SUBTIPOS.TI_USUARIO
)
RETURN VARCHAR2;

--12
FUNCTION FC_REGISTRAR
(
  UN_DEPARTAMENTO		IN VARCHAR2,
	UN_MUNICIPIO		IN VARCHAR2,
	UN_RESOLUCION		IN VARCHAR2,
	UN_RADICACION		IN VARCHAR2,
	UN_COMPANIA			IN PCK_SUBTIPOS.TI_COMPANIA,
	UN_USUARIO			IN PCK_SUBTIPOS.TI_USUARIO,
	UN_PAGO_ANO 		IN PCK_SUBTIPOS.TI_ANIO,
  UN_PAG_VAL 			IN PCK_SUBTIPOS.TI_DOBLE,
  UN_PAG_BAN 			IN VARCHAR2,
  UN_NUM_COM 			IN PCK_SUBTIPOS.TI_DOCNUM,
  UN_CODPADRE			IN PCK_SUBTIPOS.TI_CODPREDIO,
  UN_PAGFEC			    IN VARCHAR2,
  UN_TRPPOR			    IN PCK_SUBTIPOS.TI_DOBLE
)
RETURN VARCHAR2;

PROCEDURE PR_INCREMENTARAVALUOS
(
  UN_COMPANIA 	  IN PCK_SUBTIPOS.TI_COMPANIA,
	UN_CODIGO       IN PCK_SUBTIPOS.TI_CODPREDIO,
	UN_NUMERO_ORDEN IN PCK_SUBTIPOS.TI_NUMORDEN,
	UN_AVALUO   	  IN PCK_SUBTIPOS.TI_DOBLE,
	UN_AVALUO_ANO 	IN PCK_SUBTIPOS.TI_DOBLE DEFAULT 0,
  UN_ANO          IN PCK_SUBTIPOS.TI_ANIO
);

--14
FUNCTION FC_ARMACONSULTAESTADOCUENTA
(
	UN_COMPANIA     	  IN PCK_SUBTIPOS.TI_COMPANIA,
	UN_NIT 				      IN VARCHAR2,
	UN_CODPREDIO    	  IN PCK_SUBTIPOS.TI_CODPREDIO,
	UN_PROPIETARIO  	  IN VARCHAR2,
	UN_PORUNUSUARIO 	  IN PCK_SUBTIPOS.TI_LOGICO,
	UN_PORPREDIO    	  IN PCK_SUBTIPOS.TI_LOGICO,
	UN_NUMORDEN     	  IN PCK_SUBTIPOS.TI_NUMORDEN,
	UN_NOMBRECOMPANIA 	IN VARCHAR2
)
RETURN CLOB ;

FUNCTION FC_DIFERIR_ENC_MOD
(
  UN_COMPANIA     IN  PCK_SUBTIPOS.TI_COMPANIA,
  UN_PROCESO      IN  PCK_SUBTIPOS.TI_ID_DE_PROCESO,
  UN_ID_EMPLEADO  IN  PCK_SUBTIPOS.TI_ID_DE_EMPLEADO,
  UN_OPCION       IN  VARCHAR2                       DEFAULT NULL,
  UN_FECHAINICIO  IN  DATE,
  UN_FECHAFINAL   IN  DATE,
  UN_PORGASTO     IN  PCK_SUBTIPOS.TI_PORCENTAJE     DEFAULT 0,
  UN_SALARIO      IN  PCK_SUBTIPOS.TI_DOBLE          DEFAULT 0,
  UN_USUARIO      IN PCK_SUBTIPOS.TI_USUARIO,
  UN_PERIODO      IN PCK_SUBTIPOS.TI_PERIODO_NOMI
  )
  RETURN NUMBER;

END PCK_PREDIAL_COM2;