create or replace PACKAGE PCK_SERVICIOS_PUBLICOS_COM1 AS 
  /* TODO enter package declarations (types, exceptions, methods etc) here */ 

  --1
  FUNCTION FC_MEDIDORDUDOSO
  (
    UN_COMPANIA       PCK_SUBTIPOS.TI_COMPANIA,
    UN_CICLO          PCK_SUBTIPOS.TI_CICLO 
  ) 
  RETURN NUMBER;

  --2
  FUNCTION FC_ACTUALIZAMEDIDORSINESTFEC
  (
    UN_COMPANIA  IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_CICLO     IN PCK_SUBTIPOS.TI_CICLO,
    UN_USUARIO   IN PCK_SUBTIPOS.TI_USUARIO
  ) 
  RETURN PCK_SUBTIPOS.TI_LOGICO ;

  --3
  FUNCTION FC_NITVALIDAR 
  (
    UN_COMPANIA       PCK_SUBTIPOS.TI_COMPANIA,
    UN_NIT            VARCHAR2
  )
  RETURN VARCHAR2;

  --4
  FUNCTION FC_AUTORIZACION_PERSUASIVO
  (
    UN_COMPANIA       PCK_SUBTIPOS.TI_COMPANIA,
    UN_NIT            VARCHAR2
  )
  RETURN NUMBER;

  --5
  PROCEDURE PR_CAMBIORUTA
  (
    UN_NUE_COMPANIA   PCK_SUBTIPOS.TI_COMPANIA,
    UN_ANT_COMPANIA   PCK_SUBTIPOS.TI_COMPANIA,
    UN_NUE_CICLO      PCK_SUBTIPOS.TI_CICLO,
    UN_ANT_CICLO      PCK_SUBTIPOS.TI_CICLO,
    UN_NUE_CODIGORUTA PCK_SUBTIPOS.TI_CODIGORUTA,
    UN_ANT_CODIGORUTA PCK_SUBTIPOS.TI_CODIGORUTA,
    UN_USUARIO        PCK_SUBTIPOS.TI_USUARIO
  );

  --6
  FUNCTION FC_CAMBIOCICLO
  (
    UN_COMPANIA       PCK_SUBTIPOS.TI_COMPANIA,
    UN_NUE_CICLO      PCK_SUBTIPOS.TI_CICLO,
    UN_NUE_CODIGORUTA PCK_SUBTIPOS.TI_CODIGORUTA,
    UN_ANO            PCK_SUBTIPOS.TI_ANIO,
    UN_PERIODO        PCK_SUBTIPOS.TI_PERIODO,
    UN_ANT_COMPANIA   PCK_SUBTIPOS.TI_COMPANIA,
    UN_ANT_CICLO      PCK_SUBTIPOS.TI_CICLO,
    UN_ANT_CODIGORUTA PCK_SUBTIPOS.TI_CODIGORUTA, 
    UN_USUARIO        PCK_SUBTIPOS.TI_USUARIO
  )
  RETURN VARCHAR2;

  --7 
  PROCEDURE PR_ACTUALIZARRANGOS
  (
    UN_COMPANIA       PCK_SUBTIPOS.TI_COMPANIA,
    UN_CICLO          PCK_SUBTIPOS.TI_CICLO 
  );

  --8
  PROCEDURE PR_REVERSARPORPAQUETE
  (
    UN_COMPANIA       PCK_SUBTIPOS.TI_COMPANIA,
    UN_FECHA          DATE,
    UN_BANCO          PCK_SUBTIPOS.TI_BANCO,
    UN_PAQUETE        SP_HISTORIA_EXTERNA.PAQUETE_PAGO%TYPE 
  );

  --9
  PROCEDURE PR_REVERSARPORPAQUETECONV
  (
    UN_COMPANIA       PCK_SUBTIPOS.TI_COMPANIA,
    UN_FECHA          DATE,
    UN_BANCO          PCK_SUBTIPOS.TI_BANCO,
    UN_PAQUETE        SP_HISTORIA_EXTERNA.PAQUETE_PAGO%TYPE 
  );

  --10
  PROCEDURE PR_ELIMINARECPRODPAQUETE
  (
    UN_COMPANIA       PCK_SUBTIPOS.TI_COMPANIA, 
    UN_FECHA          DATE,
    UN_BANCO          PCK_SUBTIPOS.TI_BANCO,
    UN_PAQUETE        SP_HISTORIA_EXTERNA.PAQUETE_PAGO%TYPE
  );

  --11
  FUNCTION FC_BORRAREGPAGOS
  (
    UN_COMPANIA       PCK_SUBTIPOS.TI_COMPANIA,
    UN_FECHA          DATE,
    UN_BANCO          PCK_SUBTIPOS.TI_BANCO,
    UN_PAQUETE        SP_HISTORIA_EXTERNA.PAQUETE_PAGO%TYPE
  ) 
  RETURN VARCHAR2;

  --12
  FUNCTION FC_HAYPERIODOSCERRADOS
  (
    UN_COMPANIA       PCK_SUBTIPOS.TI_COMPANIA,
    UN_FECHA          DATE,
    UN_BANCO          PCK_SUBTIPOS.TI_BANCO,
    UN_PAQUETE        SP_HISTORIA_EXTERNA.PAQUETE_PAGO%TYPE
  )
  RETURN NUMBER;

  --13
  FUNCTION FC_DEVOLUCIONDECAJA
  (
    UN_COMPANIA       PCK_SUBTIPOS.TI_COMPANIA,
    UN_TIPO           SP_TIPOMOVIMIENTOCAJA.CODIGO%TYPE,
    UN_CLASE          VARCHAR2,
    UN_FECHA          DATE,
    UN_DBLVALOR       PCK_SUBTIPOS.TI_DOBLE,
    UN_USUARIO        PCK_SUBTIPOS.TI_USUARIO,
    UN_TIPOANULAR     SP_MOVIMIENTOCAJA.TIPO%TYPE 
  )
  RETURN VARCHAR2;

  --14
  FUNCTION FC_BORRARPAGO
  (
    UN_COMPANIA       PCK_SUBTIPOS.TI_COMPANIA,
    UN_FECHA          DATE,
    UN_BANCO          PCK_SUBTIPOS.TI_BANCO,
    UN_NUMEROPAQUETE  SP_HISTORIA_EXTERNA.PAQUETE_PAGO%TYPE,
    UN_CICLO          PCK_SUBTIPOS.TI_CICLO ,
    UN_CODIGORUTA     PCK_SUBTIPOS.TI_CODIGORUTA,
    UN_OPERACION      VARCHAR2,
    UN_CONSECUTIVO    SP_PAGO.CONSECUTIVO%TYPE,
    UN_GRUPO          VARCHAR2,
    UN_VALORPAGO      PCK_SUBTIPOS.TI_DOBLE,
    UN_USUARIO        PCK_SUBTIPOS.TI_USUARIO
  )
  RETURN VARCHAR2;

  --15
  PROCEDURE PR_ELIMINARECPROD(
    UN_COMPANIA       PCK_SUBTIPOS.TI_COMPANIA,
    UN_CICLO          PCK_SUBTIPOS.TI_CICLO,
    UN_USUARIO        PCK_SUBTIPOS.TI_USUARIO,
    UN_FECHA          DATE,
    UN_BANCO          PCK_SUBTIPOS.TI_BANCO,
    UN_PAQUETE        SP_RECAUDO_PRODUCTIVIDAD.PAQUETE%TYPE,
    UN_OPERACION      SP_RECAUDO_PRODUCTIVIDAD.OPERACION%TYPE
  );


END PCK_SERVICIOS_PUBLICOS_COM1;