create or replace PACKAGE PCK_FACT_GENERAL AS 

--1

FUNCTION FC_CONCEPTOAFINVENTARIO(
  UN_COMPANIA           IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_ANO                IN PCK_SUBTIPOS.TI_ENTERO,
  UN_TIPOCOBRO          IN PCK_SUBTIPOS.TI_TIPO_COBRO,
  UN_CONCEPTO           IN SF_CONCEPTOS.CODIGO%TYPE
)RETURN PCK_SUBTIPOS.TI_LOGICO ;
--2
FUNCTION FC_MANEJAINVENTARIO(

  UN_COMPANIA   IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_ANO        IN PCK_SUBTIPOS.TI_ANIO,
  UN_TIPOCOBRO  IN PCK_SUBTIPOS.TI_TIPO_COBRO
)
RETURN PCK_SUBTIPOS.TI_LOGICO;

--3
FUNCTION FC_AFECTARINVENTARIO(
  UN_COMPANIA 	      IN PCK_SUBTIPOS.TI_COMPANIA,
	UN_TIPOASOCIADO   	IN SF_FACTURA.TIPO_FACTURA%TYPE,
	UN_NUMEROASOCIADO   IN SF_FACTURA.NUMERO_FACTURA%TYPE,
  UN_TIPOMOVIMIENTO   IN MOVIMIENTO.TIPOMOVIMIENTO%TYPE,
  UN_FECHAMOV         IN DATE,
  UN_DEPENDENCIA      IN MOVIMIENTO.DEPENDENCIA_DESTINO%TYPE,
  UN_TIPOCOBRO        IN PCK_SUBTIPOS.TI_TIPO_COBRO,
  UN_BODEGAORIGEN     IN MOVIMIENTO.BODEGA_ORIGEN%TYPE,
  UN_BODEGADESTINO    IN MOVIMIENTO.BODEGA_DESTINO%TYPE,
  UN_USUARIO          IN PCK_SUBTIPOS.TI_USUARIO
  )
RETURN PCK_SUBTIPOS.TI_LONG;

--4  
PROCEDURE PR_ELIMINAR_RECAUDO
(
  UN_COMPANIA                 IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_TIPOFACTURA              IN SF_FACTURA.TIPO_FACTURA%TYPE,
  UN_NUMEROFACTURA            IN SF_FACTURA.NUMERO_FACTURA%TYPE,
  UN_USUARIO                  IN PCK_SUBTIPOS.TI_USUARIO
);

  --5
  PROCEDURE PR_REVERSARFACTURACION 
  (
    UN_COMPANIA       IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_ANIO           IN PCK_SUBTIPOS.TI_ANIO,
    UN_TIPOCOBRO      IN SF_OBJETO_COBRO.TIPOCOBRO%TYPE,
    UN_FACTURA        IN SF_FACTURA.NUMERO_FACTURA%TYPE,
    UN_CODCOBRO       IN SF_OBJETO_COBRO.CODIGO_COBRO%TYPE,
    UN_USUARIO        IN PCK_SUBTIPOS.TI_USUARIO
  );

--6
 FUNCTION FC_BUSCARABONOSREGISTRAR
(
  UN_COMPANIA     IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_NROFACTURA   IN PCK_SUBTIPOS.TI_ENTERO_LARGO,
  UN_TIPOFACTURA  IN SF_FACTURA.TIPO_FACTURA%TYPE,
  UN_TIPOCOBRO    IN PCK_SUBTIPOS.TI_TIPO_COBRO,
  UN_ANOCOBRO     IN PCK_SUBTIPOS.TI_ANIO,
  UN_USUARIO      IN PCK_SUBTIPOS.TI_USUARIO
)RETURN PCK_SUBTIPOS.TI_ENTERO;

--7
FUNCTION FC_DIFERIRFACTURA
(
  UN_COMPANIA     IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_TIPOFAC      IN PCK_SUBTIPOS.TI_PARAMETRO,
  UN_NROFACT      IN PCK_SUBTIPOS.TI_ENTERO_LARGO,
  UN_TASA         IN PCK_SUBTIPOS.TI_DOBLE,
  UN_TERCERO      IN PCK_SUBTIPOS.TI_TERCERO,
  UN_SUCURSAL     IN PCK_SUBTIPOS.TI_SUCURSAL,
  UN_CENCOSTO     IN PCK_SUBTIPOS.TI_CENTRO_COSTO,
  UN_AUXILIAR     IN PCK_SUBTIPOS.TI_AUXILIAR,
  UN_NCUOTAS      IN PCK_SUBTIPOS.TI_ENTERO,
  UN_CUOTAINICIAL IN PCK_SUBTIPOS.TI_DOBLE,
  UN_TIPOCOBRO    IN PCK_SUBTIPOS.TI_TIPO_COBRO,
  UN_USUARIO      IN PCK_SUBTIPOS.TI_USUARIO
)RETURN CLOB;

--8
PROCEDURE PR_CALCULARMENSUALIDADABONOCAJ(
  UN_COMPANIA      IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_TIPOABONO     IN PCK_SUBTIPOS.TI_PARAMETRO,
  UN_NROABONO      IN PCK_SUBTIPOS.TI_ENTERO_LARGO,
  UN_PRIMERFECHA   IN DATE,
  UN_FECHADECORTE  IN DATE,
  UN_MONTO         IN PCK_SUBTIPOS.TI_DOBLE,
  UN_MONTOINTERES  IN PCK_SUBTIPOS.TI_DOBLE,
  UN_NCUOTAS       IN PCK_SUBTIPOS.TI_ENTERO,
  UN_TASAINTERES   IN PCK_SUBTIPOS.TI_DOBLE,
  UN_TASARECARGO   IN PCK_SUBTIPOS.TI_DOBLE,
  UN_TASAGRADIENTE IN PCK_SUBTIPOS.TI_DOBLE,
  UN_BLSIMPLE      IN PCK_SUBTIPOS.TI_LOGICO,
  UN_USUARIO       IN PCK_SUBTIPOS.TI_USUARIO
);

--9
PROCEDURE PR_CALCULARMENSUALIDADSIMPLE
(
  UN_COMPANIA     IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_TIPOABONO    IN PCK_SUBTIPOS.TI_PARAMETRO,
  UN_NROABONO     IN PCK_SUBTIPOS.TI_DOBLE,
  UN_MONTOCAPITAL IN PCK_SUBTIPOS.TI_DOBLE,
  UN_MONTOINTERES IN PCK_SUBTIPOS.TI_DOBLE,
  UN_NROCUOTAS    IN PCK_SUBTIPOS.TI_ENTERO,
  UN_TASAINTERES  IN PCK_SUBTIPOS.TI_DOBLE,
  UN_FECHAINICIAL IN DATE,
  UN_USUARIO      IN PCK_SUBTIPOS.TI_USUARIO
);

--10
PROCEDURE PR_AJUSTARCUOTAS(
  UN_COMPANIA  PCK_SUBTIPOS.TI_COMPANIA,
  UN_USUARIO   PCK_SUBTIPOS.TI_USUARIO
);

--11
PROCEDURE  PR_CALCUMENSUALIDADABONOPORC
(
UN_COMPANIA      IN PCK_SUBTIPOS.TI_COMPANIA,
UN_TIPOABONO     IN PCK_SUBTIPOS.TI_PARAMETRO,
UN_NROABONO      IN PCK_SUBTIPOS.TI_DOBLE,
UN_PRIMERFECHA   IN DATE,
UN_FECHADECORTE  IN DATE,
UN_MONTO         IN PCK_SUBTIPOS.TI_DOBLE,
UN_MONTOINTERES  IN PCK_SUBTIPOS.TI_DOBLE,
UN_NCUOTAS       IN PCK_SUBTIPOS.TI_ENTERO,
UN_TASAINTERES   IN PCK_SUBTIPOS.TI_DOBLE,
UN_TASARECARGO   IN PCK_SUBTIPOS.TI_DOBLE,
UN_TASAGRADIENTE IN PCK_SUBTIPOS.TI_DOBLE,
UN_BLSIMPLE      IN PCK_SUBTIPOS.TI_LOGICO,
UN_USUARIO       IN PCK_SUBTIPOS.TI_USUARIO
);

--12
PROCEDURE PR_CALCULARMENSUALIDADABONO
(
 UN_COMPANIA      IN PCK_SUBTIPOS.TI_COMPANIA,
 UN_TIPOABONO     IN PCK_SUBTIPOS.TI_PARAMETRO,
 UN_NROABONO      IN PCK_SUBTIPOS.TI_DOBLE,
 UN_PRIMERFECHA   IN DATE,
 UN_FECHADECORTE  IN DATE,
 UN_MONTO         IN PCK_SUBTIPOS.TI_DOBLE,
 UN_MONTOINTERES  IN PCK_SUBTIPOS.TI_DOBLE,
 UN_NCUOTAS       IN PCK_SUBTIPOS.TI_ENTERO,
 UN_TASAINTERES   IN PCK_SUBTIPOS.TI_DOBLE,
 UN_TASARECARGO   IN PCK_SUBTIPOS.TI_DOBLE,
 UN_TASAGRADIENTE IN PCK_SUBTIPOS.TI_DOBLE,
 UN_BLSIMPLE      IN PCK_SUBTIPOS.TI_LOGICO,
 UN_USUARIO       IN PCK_SUBTIPOS.TI_USUARIO
 );

--13
FUNCTION FC_MANEJADERCONEXIONCONCEPTO 
(
  UN_COMPANIA   IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_ANO        IN PCK_SUBTIPOS.TI_ANIO,
  UN_TIPOCOBRO  IN PCK_SUBTIPOS.TI_TIPO_COBRO,
  UN_CONCEPTO   IN PCK_SUBTIPOS.TI_PARAMETRO
)RETURN PCK_SUBTIPOS.TI_LOGICO;

--14
FUNCTION FC_CONSULTARABONO(
  UN_COMPANIA           IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_TIPOABONO          IN SF_DETALLE_ABONO.TIPO_ABONO%TYPE,
  UN_ABONO              IN SF_DETALLE_ABONO.CODIGO_ABONO%TYPE

)RETURN VARCHAR2;

--15
PROCEDURE PR_ACTPAGOSABONOS(
  UN_COMPANIA           IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_TIPOABONO          IN SF_DETALLE_ABONO.TIPO_ABONO%TYPE,
  UN_ABONO              IN SF_DETALLE_ABONO.CODIGO_ABONO%TYPE,
  UN_TIPOFACTURA        IN SF_FACTURA.TIPO_FACTURA%TYPE,
  UN_NOFACTURA          IN SF_FACTURA.NUMERO_FACTURA%TYPE,
  UN_CODIGOCOBRO        IN SF_FACTURA.CODIGO_COBRO%TYPE,    
  UN_FECHAPAGO          IN SF_FACTURA.FECHA_PAGO%TYPE,
  UN_TIPOCPTPAGO        IN SF_FACTURA.TIPOCPTE_PAGO%TYPE,
  UN_CPTEPAGO           IN SF_FACTURA.NROCPTE_PAGO%TYPE,  
  UN_BANCOPAGO          IN SF_FACTURA.BANCO_PAGO%TYPE,
  UN_USUARIO            IN PCK_SUBTIPOS.TI_USUARIO

);

 --17
  FUNCTION FC_CONSULTARTIPOCOMP 
  (
    UN_COMPANIA               IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_ANIO                   IN PCK_SUBTIPOS.TI_ANIO,
    UN_TIPOCOBRO              IN PCK_SUBTIPOS.TI_TIPO_COBRO,
    UN_MODULO                 IN PCK_SUBTIPOS.TI_MODULO
  )
  RETURN VARCHAR2;
 --18
 FUNCTION FC_ACT_VALOR_ELEMENTO
  (
    UN_COMPANIA      IN  PCK_SUBTIPOS.TI_COMPANIA,
    UN_ANIO          IN PCK_SUBTIPOS.TI_ANIO,
    UN_TIPOCOBRO     IN VARCHAR2,
    UN_ELEMENTO      IN VARCHAR2,
    UN_PORC_UTILIDAD IN PCK_SUBTIPOS.TI_PORCENTAJE,
    UN_USUARIO       IN PCK_SUBTIPOS.TI_USUARIO
  )
RETURN PCK_SUBTIPOS.TI_ENTERO_LARGO ;

--19
PROCEDURE PR_FACTURAR_SERIE
(   UN_COMPANIA                IN PCK_SUBTIPOS.TI_COMPANIA, 
    UN_ANIO                    IN SF_CONTRATOS.ANO%TYPE, 
    UN_TIPOCOBRO               IN SF_CONTRATOS.TIPO%TYPE,
    UN_CONTRATOINICIAL         IN SF_CONTRATOS.NUMERO%TYPE,
    UN_CONTRATOFINAL           IN SF_CONTRATOS.NUMERO%TYPE,
    UN_LUGAR                   IN VARCHAR2,
    UN_FECHAFACTURA            IN SF_OBJETO_COBRO.FECHA_SOLICITUD%TYPE ,
    UN_USUARIO                 IN PCK_SUBTIPOS.TI_USUARIO 
);

--20
PROCEDURE PR_FINANCIARPREDIAL(
    UN_COMPANIA                IN PCK_SUBTIPOS.TI_COMPANIA, 
    UN_ANIO                    IN SF_CONTRATOS.ANO%TYPE, 
    UN_TIPOCOBRO               IN SF_CONTRATOS.TIPO%TYPE,
    UN_CODIGOPREDIO            IN TEMPORALDEUDAPREDIO.CODIGO_PREDIO%TYPE,
    UN_ANIOSFINANCIAR          IN VARCHAR2,
    UN_TERCERO                 IN SF_OBJETO_COBRO.TERCERO%TYPE,
    UN_SUCURSAL                IN SF_OBJETO_COBRO.SUCURSAL%TYPE,
    UN_USUARIO                 IN PCK_SUBTIPOS.TI_USUARIO 
);

FUNCTION FC_CARGAR_RECUADOCAUSACION
( 
  UN_COMPANIA     IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_CADENAPLANO  IN CLOB,
  UN_TIPOCOBRO    IN PCK_SUBTIPOS.TI_TIPO_COBRO,  
  UN_ANIO         IN PCK_SUBTIPOS.TI_ANIO,
  UN_TERCERO      IN SF_DETALLE_FACTURA.TERCERO%TYPE,
  UN_USUARIO      IN PCK_SUBTIPOS.TI_USUARIO,
  UN_LOTE         IN NUMBER DEFAULT 0 --JMILLAN 17/09/2024
)RETURN CLOB;

--22 
FUNCTION FC_TASAANUAL
(
    UN_COMPANIA     IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_ANIO         IN PCK_SUBTIPOS.TI_ANIO, 
    UN_TIPOCOBRO    IN PCK_SUBTIPOS.TI_TIPO_COBRO,
    UN_FECHACORTE   IN DATE
)RETURN NUMBER;

--23
FUNCTION FC_TASAMENSUAL
(
    UN_COMPANIA     IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_ANIO         IN PCK_SUBTIPOS.TI_ANIO, 
    UN_TIPOCOBRO    IN PCK_SUBTIPOS.TI_TIPO_COBRO,
    UN_FECHACORTE   IN DATE
)RETURN NUMBER;

--24
FUNCTION FC_TASADIARIA
(
    UN_COMPANIA     IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_ANIO         IN PCK_SUBTIPOS.TI_ANIO, 
    UN_TIPOCOBRO    IN PCK_SUBTIPOS.TI_TIPO_COBRO,
    UN_FECHACORTE   IN DATE
)RETURN NUMBER;

--25
FUNCTION FC_FACTURAR_CONCEPTOSLIQUIDA
(
    UN_COMPANIA     IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_ANIO         IN PCK_SUBTIPOS.TI_ANIO,
    UN_TIPOFACTURA  IN SF_FACTURA.TIPO_FACTURA%TYPE,
    UN_TERCERO      IN PCK_SUBTIPOS.TI_TERCERO,
    UN_CONCEPTO     IN VARCHAR2,
    UN_DESCRIPCION  IN SF_FACTURA.OBSERVACIONES%TYPE,
    UN_USUARIO      IN PCK_SUBTIPOS.TI_USUARIO
)
RETURN VARCHAR2;

END PCK_FACT_GENERAL;