create or replace PACKAGE "PCK_PARST" AS 


TYPE TYP_PARAMETROS IS TABLE OF VARCHAR2(4000) INDEX BY VARCHAR2(500);
LSTPAR TYP_PARAMETROS;

--28/02/2015 -- DEFINIR LAS VARIABLES GLOBALES PARA EL MANEJO DE LOS PARAMETROS DE SISTEMA A UTILIZAR EN EL PROCESO
/*
  GL_NOMINAMENSUAL                  PARAMETRO.VALOR%TYPE;
  GL_PORCENTAJEDEDUCIBLEMAXVOL      PARAMETRO.VALOR%TYPE;
  GL_PORCENTAJEDEDUCIBLESALUD       PARAMETRO.VALOR%TYPE;
  GL_DESCTRANSPORTEBASEPARAF        PARAMETRO.VALOR%TYPE;
  GL_PRCALCULOPRIMADEVACACIONES     PARAMETRO.VALOR%TYPE;
  GL_PRCALCULODEQUINQUENIO          PARAMETRO.VALOR%TYPE;
  GL_PRCALCULOPRIMADEJUNIO          PARAMETRO.VALOR%TYPE;
  GL_PRCALCULOPRIMADENAVIDAD        PARAMETRO.VALOR%TYPE;
  GL_PRCALCULOCESANTIASFNA          PARAMETRO.VALOR%TYPE;
  GL_PRCALCULODECESANTIAS           PARAMETRO.VALOR%TYPE;
  GL_LIQVACACIONESDENTRODENOMINA    PARAMETRO.VALOR%TYPE;
  GL_LIQHORASEXTRAS                 PARAMETRO.VALOR%TYPE;
  GL_TRAERAPORTESVOLUNTMESANT       PARAMETRO.VALOR%TYPE;
  GL_LIQPRIMATECNICAQUINCENAL       PARAMETRO.VALOR%TYPE;
  GL_LIQGASTOSDEREPRESENTACION      PARAMETRO.VALOR%TYPE;
  GL_LIQDESCUENTODEESTAMPILLAS      PARAMETRO.VALOR%TYPE;
  GL_LIQBONIFANUALXSERVPRESTADOS    PARAMETRO.VALOR%TYPE;
  GL_PAGARBONIFANUALMESDEING        PARAMETRO.VALOR%TYPE;
  GL_LIQBONIFPECIALDERECREACION     PARAMETRO.VALOR%TYPE;
  GL_LMTPRIMADEALIMENTDOCENTES      PARAMETRO.VALOR%TYPE;
  GL_ACTIVARRETCALCRETROACYAUTOL    PARAMETRO.VALOR%TYPE;
  GL_MANEJAMODULOEMBARGOS           PARAMETRO.VALOR%TYPE;
  GL_DESCONTARTRANSPDEBASPARAFIS    PARAMETRO.VALOR%TYPE;
  GL_PROVISIONESNORMALES            PARAMETRO.VALOR%TYPE;
  GL_CODCPTOAJUSTESPRIMADEVAC       PARAMETRO.VALOR%TYPE;
  GL_SUMACPTSAUTOLIQUIDPORPAR       PARAMETRO.VALOR%TYPE;
  GL_CALCULARETENCIONSOLOALRETRO    PARAMETRO.VALOR%TYPE;
  GL_HASTAQUEMESREALIZARRETRO       PARAMETRO.VALOR%TYPE;
  GL_CODIGOCONCEPTOAJUSTESBASP      PARAMETRO.VALOR%TYPE;
  GL_CODCPTOAJUSTESPRIMASEM         PARAMETRO.VALOR%TYPE;
  GL_CODCTOAJUSTESPRIMANAVIDAD      PARAMETRO.VALOR%TYPE;
  GL_PERIODONOMINAADICIONAL         PARAMETRO.VALOR%TYPE;
  GL_DESCONTARCOOPERATIVNOMADNAL    PARAMETRO.VALOR%TYPE;
  GL_CALCPARAFISCALESNOMINAADNAL    PARAMETRO.VALOR%TYPE;
  GL_REDONDDSCTOSSALYPENEMPL        PARAMETRO.VALOR%TYPE;
  GL_REDONDA10DSCTOFSPSEGSOCIAL     PARAMETRO.VALOR%TYPE;
  GL_CODFONDODEPENSIONSEGSOCIAL     PARAMETRO.VALOR%TYPE;
  GL_PORCENTAJEFIJODEBASP           PARAMETRO.VALOR%TYPE;
  GL_PAGARINCAPACIDADES100CIENTO    PARAMETRO.VALOR%TYPE;
  GL_PORCAPAGARSOBREINCAPACIDAD     PARAMETRO.VALOR%TYPE;
  GL_CODIGOCPTOMESADAPENSIONAL      PARAMETRO.VALOR%TYPE;
  GL_DISCINCAPACIDADESDE1A3DIAS     PARAMETRO.VALOR%TYPE;
  GL_LIQRBASPCONLAFECHADEBONIF      PARAMETRO.VALOR%TYPE;
  GL_PROPVACACIONESSEGSOCIAL        PARAMETRO.VALOR%TYPE;
  GL_DESCUENTOSINDICATOQUINCENAL    PARAMETRO.VALOR%TYPE;
  GL_DESDEMESREALIZARRETROACTIVO    PARAMETRO.VALOR%TYPE;
  GL_SUMOTRSCPTOSDEAUTOLIQ          PARAMETRO.VALOR%TYPE;
  GL_CALCRIESGOSSINLICDE_L_C_R      PARAMETRO.VALOR%TYPE;
  GL_APMINIMOCONIBCPERSENINCAPAC    PARAMETRO.VALOR%TYPE;
  GL_ELIMSEGSOCIALENPERDELIQUID     PARAMETRO.VALOR%TYPE;
  GL_PORCENTAJESALUDDECRETO1122     PARAMETRO.VALOR%TYPE;
  GL_VALORUVTACTUAL                 PARAMETRO.VALOR%TYPE;
  GL_LIQRTEFTEPER05RETRO            PARAMETRO.VALOR%TYPE;
  GL_PORCRTEFTE                     PARAMETRO.VALOR%TYPE;

PROCEDURE CARGAR_PARAMETROSISTEMA
  (
    UN_COMPANIA VARCHAR2
  );
*/
PROCEDURE PR_INICIALIZAR_PARSISTEMA

  (
    UN_COMPANIA VARCHAR2,
    UN_MODULO NUMBER,
    UN_FECHA_PAR DATE:=SYSDATE
  );

FUNCTION FC_PAR
  (
    UN_PARAMETRO VARCHAR2,
    UN_VLOMISION VARCHAR2
  )
RETURN VARCHAR2;
END PCK_PARST;