create or replace PACKAGE PCK_SERVICIOS_PUBLICOS_COM4 AS 

  FUNCTION FC_AUTORIZACION_FACTURAPAGADA
  (
    UN_COMPANIA IN PCK_SUBTIPOS.TI_COMPANIA
   ,UN_NIT      IN VARCHAR2 
  )
    RETURN NUMBER;

  FUNCTION FC_ESTA_BLOQUEADO
  (
    UN_COMPANIA IN PCK_SUBTIPOS.TI_COMPANIA
   ,UN_CICLO    IN PCK_SUBTIPOS.TI_CICLO
  )
  RETURN NUMBER;

  FUNCTION FC_AUTORIZACION_CONVENIOS
  (
    UN_COMPANIA IN PCK_SUBTIPOS.TI_COMPANIA
   ,UN_NIT      IN VARCHAR2
  )
  RETURN NUMBER;

  FUNCTION FC_PERMISO_ACCION
  (
    UN_COMPANIA  IN PCK_SUBTIPOS.TI_COMPANIA
   ,UN_ACCION    IN VARCHAR2 
   ,UN_USUARIO   IN PCK_SUBTIPOS.TI_USUARIO
   ,UN_PARAMETRO IN PCK_SUBTIPOS.TI_PARAMETRO DEFAULT NULL
  )
  RETURN NUMBER;

  FUNCTION FC_OBTENER_COMENTARIOS_PERIODO
  ( 
    UN_COMPANIA    IN PCK_SUBTIPOS.TI_COMPANIA
   ,UN_COMENTARIOS IN SP_USUARIO.COMENTARIOS%TYPE
   ,UN_ANO         IN PCK_SUBTIPOS.TI_ANIO
   ,UN_PERIODO     IN PCK_SUBTIPOS.TI_PERIODO
  )
  RETURN VARCHAR2;

  FUNCTION FC_ARMACONSULTAPLANOSEXP
  (
    UN_COMPANIA      IN PCK_SUBTIPOS.TI_COMPANIA
   ,UN_CICLO         IN PCK_SUBTIPOS.TI_CICLO
   ,UN_CODIGOINICIAL IN PCK_SUBTIPOS.TI_CODIGORUTA
   ,UN_CODIGOFINAL   IN PCK_SUBTIPOS.TI_CODIGORUTA
  )
  RETURN VARCHAR2;

  FUNCTION FC_PLANOS_ASOBANCARIA
  (
    UN_COMPANIA             IN PCK_SUBTIPOS.TI_COMPANIA
   ,UN_CICLO                IN PCK_SUBTIPOS.TI_CICLO
   ,UN_CODIGOINICIAL        IN PCK_SUBTIPOS.TI_CODIGORUTA
   ,UN_CODIGOFINAL          IN PCK_SUBTIPOS.TI_CODIGORUTA
   ,UN_USUARIO              IN PCK_SUBTIPOS.TI_USUARIO
   ,UN_CHECKATH             IN PCK_SUBTIPOS.TI_LOGICO
  )
    RETURN CLOB;

  FUNCTION FC_FIMMCABEZA
  (
    UN_COMPANIA              IN PCK_SUBTIPOS.TI_COMPANIA
   ,UN_CICLO                 IN PCK_SUBTIPOS.TI_CICLO
   ,UN_STRDIASAFACTURAR      IN PCK_SUBTIPOS.TI_ENTERO
   ,UN_DIASDESDE             IN PCK_SUBTIPOS.TI_ENTERO
   ,UN_DIASHASTA             IN PCK_SUBTIPOS.TI_ENTERO
   ,UN_CODIGOINICIAL         IN PCK_SUBTIPOS.TI_CODIGORUTA
   ,UN_CODIGOFINAL           IN PCK_SUBTIPOS.TI_CODIGORUTA
   ,UN_FECHAEMISION          IN DATE 
   ,UN_USUARIO               IN PCK_SUBTIPOS.TI_USUARIO
  )
  RETURN CLOB;

  FUNCTION FC_FIMMCUERPO
  (
    UN_COMPANIA              IN PCK_SUBTIPOS.TI_COMPANIA
   ,UN_CICLO                 IN PCK_SUBTIPOS.TI_CICLO
   ,UN_DIASPRIMERVENC        IN PCK_SUBTIPOS.TI_ENTERO
   ,UN_CODIGOINICIAL         IN PCK_SUBTIPOS.TI_CODIGORUTA
   ,UN_CODIGOFINAL           IN PCK_SUBTIPOS.TI_CODIGORUTA
   ,UN_FECHAEMISION          IN DATE 
   ,UN_FECHAVENCIMIENTO      IN DATE 
   ,UN_INDEMISIONFIJA        IN PCK_SUBTIPOS.TI_LOGICO
   ,UN_INDVENCIMIENTOFIJO    IN PCK_SUBTIPOS.TI_LOGICO
   ,UN_USUARIO               IN PCK_SUBTIPOS.TI_USUARIO
  )
  RETURN CLOB;

  FUNCTION FC_NOMBREPER
  (
    UN_COMPANIA     IN PCK_SUBTIPOS.TI_COMPANIA
   ,UN_ANO          IN PCK_SUBTIPOS.TI_ANIO
   ,UN_PERIODO      IN PCK_SUBTIPOS.TI_PERIODO
   ,UN_FRECUENCIA   VARCHAR2
  )
  RETURN VARCHAR2;

  FUNCTION FC_FIMMSOLOLECTURACABEZA
  (
    UN_COMPANIA              IN PCK_SUBTIPOS.TI_COMPANIA
   ,UN_CICLO                 IN PCK_SUBTIPOS.TI_CICLO
   ,UN_STRDIASAFACTURAR      IN PCK_SUBTIPOS.TI_ENTERO
   ,UN_DIASDESDE             IN PCK_SUBTIPOS.TI_ENTERO
   ,UN_DIASHASTA             IN PCK_SUBTIPOS.TI_ENTERO
   ,UN_CODIGOINICIAL         IN PCK_SUBTIPOS.TI_CODIGORUTA
   ,UN_CODIGOFINAL           IN PCK_SUBTIPOS.TI_CODIGORUTA
  )
  RETURN CLOB;

  FUNCTION FC_FIMMSOLOLECTURACUERPO
  (
    UN_COMPANIA              IN PCK_SUBTIPOS.TI_COMPANIA
   ,UN_CICLO                 IN PCK_SUBTIPOS.TI_CICLO
   ,UN_CODIGOINICIAL         IN PCK_SUBTIPOS.TI_CODIGORUTA
   ,UN_CODIGOFINAL           IN PCK_SUBTIPOS.TI_CODIGORUTA
  )
  RETURN CLOB;

  PROCEDURE PR_REGISTRARPROCESO
     /*
          NAME              : PR_REGISTRARPROCESO -- EN ACCESS REGISTARPROCESO
          AUTHORS           : SYSMAN LTDA
          AUTHOR MIGRACION  : JÉSSICA LISSETH RAMÍREZ BRICEÑO
          DATE MIGRADOR     : 27/12/2016
          TIME              : 04:35 PM
          DESCRIPTION       : 
      */
  (
    UN_COMPANIA     IN PCK_SUBTIPOS.TI_COMPANIA
   ,UN_PROCESO      IN VARCHAR2 
   ,UN_DESCRIPCION  IN VARCHAR2 
   ,UN_PARAMETROS   IN VARCHAR2 
   ,UN_RESULTADOS   IN VARCHAR2 
   ,UN_ESTADO       IN VARCHAR2 
   ,UN_USUARIO      IN PCK_SUBTIPOS.TI_USUARIO  
   ,UN_FECHA        IN DATE
  );

END PCK_SERVICIOS_PUBLICOS_COM4;