create or replace PACKAGE "PCK_CONTABILIDAD3" AS 
	GL_ERROR_NUM        NUMBER := 1300;  
	GL_MSG              ERRORES.DESCRIPCION%TYPE; 
	GL_VARCAUSACION     NUMBER := 0;  

FUNCTION FC_CALCULAR_INCONSISTENCIAS
(
	UN_COMPANIA   	IN PCK_SUBTIPOS.TI_COMPANIA, 
	UN_ANIO       	IN PCK_SUBTIPOS.TI_ANIO 
) 
RETURN VARCHAR2;

FUNCTION FC_NIIF_LOTES
(
	UN_COMPANIA     IN PCK_SUBTIPOS.TI_COMPANIA, 
	UN_MES_INICIAL  IN PCK_SUBTIPOS.TI_MES, 
	UN_MES_FINAL    IN PCK_SUBTIPOS.TI_MES, 
	UN_TIPO_INICIAL IN PCK_SUBTIPOS.TI_TIPOCOMPROBANTE, 
	UN_TIPO_FINAL   IN PCK_SUBTIPOS.TI_TIPOCOMPROBANTE, 
	UN_ANIO         IN PCK_SUBTIPOS.TI_ANIO, 
	UN_USUARIO      IN VARCHAR2 
) 
RETURN VARCHAR2;

FUNCTION FC_PREDECESOR
(
	UN_COMPANIA     IN PCK_SUBTIPOS.TI_COMPANIA,
	UN_ANIO         IN PCK_SUBTIPOS.TI_ANIO, 
	UN_CODIGO       IN PCK_SUBTIPOS.TI_CODIGOCONTA      
)
RETURN VARCHAR2;

FUNCTION FC_CREARCUENTANIIF
(
	UN_COMPANIANIIF	IN PCK_SUBTIPOS.TI_COMPANIA,  
	UN_COMPANIA     IN PCK_SUBTIPOS.TI_COMPANIA, 
  UN_ANO_FUENTE   IN PCK_SUBTIPOS.TI_ANIO,
  UN_ANO_DESTINO  IN PCK_SUBTIPOS.TI_ANIO,
	UN_CODIGO       IN PCK_SUBTIPOS.TI_CODIGOCONTA,
  UN_USUARIO 		  IN PCK_SUBTIPOS.TI_USUARIO
)
RETURN NUMBER; 

PROCEDURE PR_EQUIVALENTENIIIF
(
	UN_COMPANIA     IN PCK_SUBTIPOS.TI_COMPANIA, 
	UN_ANO_FUENTE   IN PCK_SUBTIPOS.TI_ANIO,
  UN_ANO_DESTINO  IN PCK_SUBTIPOS.TI_ANIO
);

PROCEDURE PR_SUBIRSALDOSNIIF
(
	UN_COMPANIA		  IN PCK_SUBTIPOS.TI_COMPANIA,  
	UN_COMPANIANIIF IN PCK_SUBTIPOS.TI_COMPANIA, 
 	UN_ANO_FUENTE   IN PCK_SUBTIPOS.TI_ANIO,
 	UN_ANO_DESTINO  IN PCK_SUBTIPOS.TI_ANIO,
  UN_CLAVE        IN PCK_SUBTIPOS.TI_LOGICO,
  UN_USUARIO      IN PCK_SUBTIPOS.TI_USUARIO
); 

PROCEDURE PR_RECLASIFICARNIIF
(
	  UN_COMPANIA       		IN PCK_SUBTIPOS.TI_COMPANIA, 
	  UN_ANO 		      		  IN PCK_SUBTIPOS.TI_ANIO,
    UN_TIPO           		IN PCK_SUBTIPOS.TI_TIPOCOMPROBANTE,
    UN_NUMEROREGISTRO 		IN PCK_SUBTIPOS.TI_ENTERO,
    UN_CONSECUTIVO        IN PCK_SUBTIPOS.TI_ENTERO_LARGO,
    UN_FECHA 		  		    IN DATE,
    UN_USUARIO 		  		  IN PCK_SUBTIPOS.TI_USUARIO
);

FUNCTION FC_INCONS_PLANOBANCOLOMBIA
(
   UN_COMPANIA        IN PCK_SUBTIPOS.TI_COMPANIA, 
   UN_ANO             IN PCK_SUBTIPOS.TI_ANIO,
   UN_TIPO            IN COMPROBANTE_CNT.TIPO%TYPE,
   UN_CUENTA_INICIAL  IN COMPROBANTE_CNT.CUENTA%TYPE,
   UN_CUENTA_FINAL    IN COMPROBANTE_CNT.CUENTA%TYPE,
   UN_NUMERO_INICIAL  IN COMPROBANTE_CNT.NUMERO%TYPE,
   UN_NUMERO_FINAL    IN COMPROBANTE_CNT.NUMERO%TYPE,
   UN_USUARIO         IN PCK_SUBTIPOS.TI_USUARIO
)
RETURN CLOB; 

FUNCTION FC_ASOBANCARIA_IMPORTARCT

(
  UN_COMPANIA   IN    PCK_SUBTIPOS.TI_COMPANIA,
  UN_USUARIO    IN    PCK_SUBTIPOS.TI_USUARIO,
  UN_CADENA     IN    CLOB
) RETURN CLOB ;

FUNCTION FC_GENERARINGRESOSTASAS 

(
  UN_COMPANIA       IN PCK_SUBTIPOS.TI_COMPANIA, 
  UN_USUARIO        IN PCK_SUBTIPOS.TI_USUARIO, 
  UN_ANO            IN PCK_SUBTIPOS.TI_ANIO,
  UN_TIPOCPTE       IN COMPROBANTE_CNT.TIPO%TYPE,
  UN_NROCPTE        IN COMPROBANTE_CNT.NUMERO%TYPE,
  UN_FECHARECAUDO   IN VARCHAR2,    
  UN_TIPOCPTEREC    IN COMPROBANTE_CNT.TIPO%TYPE,
  UN_VLRCPTE        IN PCK_SUBTIPOS.TI_DOBLE,
  UN_FECHAVCTO      IN COMPROBANTE_CNT.FECHA%TYPE, 
  UN_BANCOREC       IN COMPROBANTE_CNT.BANCO%TYPE,
  UN_NATCTABANCO    IN PLAN_CONTABLE.NATURALEZA%TYPE,
  UN_CUENTABANCO    IN COMPROBANTE_CNT.CUENTA%TYPE
) RETURN  VARCHAR2 ;

PROCEDURE PR_RECLASIFICARNIIF_MENSUAL
(
  UN_COMPANIA       IN PCK_SUBTIPOS.TI_COMPANIA, 
  UN_ANO            IN PCK_SUBTIPOS.TI_ANIO,
  UN_TIPO           IN PCK_SUBTIPOS.TI_TIPOCOMPROBANTE,
  UN_NUMEROREGISTRO IN PCK_SUBTIPOS.TI_ENTERO,
  UN_CONSECUTIVO    IN PCK_SUBTIPOS.TI_ENTERO_LARGO,
  UN_FECHA          IN DATE,
  UN_USUARIO        IN PCK_SUBTIPOS.TI_USUARIO
);

PROCEDURE PR_ACTPAGOS_FACT
(
  UN_COMPANIA           IN PCK_SUBTIPOS.TI_COMPANIA, 
  UN_FECHA_INI          IN DATE,
  UN_FECHA_FIN          IN DATE,
  UN_TIPO_COBRO_INI     IN SF_FACTURA.TIPOCOBRO%TYPE,
  UN_TIPO_COBRO_FIN     IN SF_FACTURA.TIPOCOBRO%TYPE,
  UN_FACTURA_INI        IN SF_FACTURA.NUMERO_FACTURA%TYPE,  
  UN_FACTURA_FIN        IN SF_FACTURA.NUMERO_FACTURA%TYPE,
  UN_GENERAL            IN VARCHAR2
);

FUNCTION FC_CAUSACIONAUTOMATICA 
(
    UN_COMPANIA         IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_ANO              IN PCK_SUBTIPOS.TI_ANIO,
    UN_TIPO             IN COMPROBANTE_CNT.TIPO%TYPE,
    UN_NUMERO           IN PCK_SUBTIPOS.TI_NUMEROCOMPROBANTECNT,   
    UN_USUARIO          IN PCK_SUBTIPOS.TI_USUARIO,
    UN_VARIABLE         IN NUMBER
) 
RETURN PCK_SUBTIPOS.TI_LOGICO;

PROCEDURE PR_VALCAUSACIONAUTOMATICA
(
    UN_COMPANIA         IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_ANO              IN PCK_SUBTIPOS.TI_ANIO,
    UN_TIPO             IN COMPROBANTE_CNT.TIPO%TYPE,
    UN_NUMERO           IN PCK_SUBTIPOS.TI_NUMEROCOMPROBANTECNT,   
    UN_USUARIO          IN PCK_SUBTIPOS.TI_USUARIO
); 

FUNCTION FC_PASAR_TASAS_INT
(
  UN_ANIO_INI       IN PCK_SUBTIPOS.TI_ANIO,
  UN_ANIO_FIN       IN PCK_SUBTIPOS.TI_ANIO,
  UN_USUARIO        IN VARCHAR2
)
RETURN NUMBER;

FUNCTION FC_GENERAR_PLANO_SUDAMERIS
(
   UN_COMPANIA                  IN PCK_SUBTIPOS.TI_COMPANIA,        
   UN_ANO                       IN PCK_SUBTIPOS.TI_ANIO,           
   UN_EGRESO_INICIAL            IN COMPROBANTE_CNT.NUMERO%TYPE,    
   UN_EGRESO_FINAL              IN COMPROBANTE_CNT.NUMERO%TYPE,    
   UN_FECHA_PAGO                IN VARCHAR2,                       
   UN_CUENTA_DEBITAR            IN VARCHAR2,                        
   UN_CUENTA_PRINCIPAL_AFILIADA IN NUMBER,                          
   UN_CODIGO_BANCO              IN VARCHAR2,                        
   UN_TIPO_EGRESO               IN COMPROBANTE_CNT.TIPO%TYPE,      
   UN_CUENTA_INICIAL            IN COMPROBANTE_CNT.CUENTA%TYPE,   
   UN_CUENTA_FINAL              IN COMPROBANTE_CNT.CUENTA%TYPE,    
   UN_IDENTIFICADOR             IN NUMBER,                          
   UN_CODIGO_VERIFICACION       IN NUMBER,                          
   UN_TIPO_CUENTA_CLIENTE       IN VARCHAR2,                        
   UN_CLASE_TRANSACCION         IN VARCHAR2                         
) RETURN CLOB;

FUNCTION FC_GENERAR_PLANO_ITAU
(
   UN_COMPANIA                  IN PCK_SUBTIPOS.TI_COMPANIA,        
   UN_ANO                       IN PCK_SUBTIPOS.TI_ANIO,           
   UN_EGRESO_INICIAL            IN COMPROBANTE_CNT.NUMERO%TYPE,     
   UN_EGRESO_FINAL              IN COMPROBANTE_CNT.NUMERO%TYPE,     
   UN_FECHA_PAGO                IN VARCHAR2,                        
   UN_CUENTA_DEBITAR            IN VARCHAR2,                        
   UN_CUENTA_PRINCIPAL_AFILIADA IN NUMBER,                          
   UN_CODIGO_BANCO              IN VARCHAR2,                        
   UN_TIPO_EGRESO               IN COMPROBANTE_CNT.TIPO%TYPE,       
   UN_CUENTA_INICIAL            IN COMPROBANTE_CNT.CUENTA%TYPE,     
   UN_CUENTA_FINAL              IN COMPROBANTE_CNT.CUENTA%TYPE,     
   UN_IDENTIFICADOR             IN NUMBER,                          
   UN_CODIGO_VERIFICACION       IN NUMBER,                          
   UN_TIPO_CUENTA_CLIENTE       IN VARCHAR2,                        
   UN_NIT_CLIENTE               IN VARCHAR2                                              
) RETURN CLOB;

FUNCTION FC_PASAR_PROVEDORES
(
  UN_COMPANIA          IN  VARCHAR2,
  UN_ANO_ORIGEN        IN  INTEGER,
  UN_ANO_DESTINO       IN  INTEGER
) RETURN CLOB;

FUNCTION FC_PASAR_REF_SERV_CTA
(
  UN_COMPANIA          IN  VARCHAR2,
  UN_ANO_ORIGEN        IN  INTEGER,
  UN_ANO_DESTINO       IN  INTEGER
) RETURN CLOB;

FUNCTION FC_CARGUE_MASIVO_RETENCION
(
    UN_COMPANIA  IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_CADENA    IN CLOB,
    UN_MES       IN NUMBER,
    UN_DIA       IN NUMBER,
    UN_USUARIO   IN PCK_SUBTIPOS.TI_USUARIO
)
RETURN CLOB;

END PCK_CONTABILIDAD3;