create or replace PACKAGE PCK_EXOGENAS AS 

  /* TODO enter package declarations (types, exceptions, methods etc) here */ 
PROCEDURE PR_CONCEPTOSPORFORMATO
  (	
    UN_COMPANIA IN PCK_SUBTIPOS.TI_COMPANIA, 
    UN_ANO 		  IN PCK_SUBTIPOS.TI_ANIO,
    UN_FORMATO 	IN VARCHAR2,
    UN_USUARIO 	IN PCK_SUBTIPOS.TI_USUARIO
  );
  
PROCEDURE PR_MIGRAR_PLAN_DE_CUENTAS (
PRM_ANO_INICIAL NUMBER,
PRM_COMPANIA VARCHAR2, 
PRM_FORMATO VARCHAR2);

PROCEDURE PR_ACTUALIZAR_CONF_EXOGENAS (
UN_ANO NUMBER,
UN_COMPANIA VARCHAR2, 
UN_FORMATO VARCHAR2,
UN_USUARIO VARCHAR2);

FUNCTION FC_ACT_TERCEROS_EXOGENAS(
    UN_COMPANIA    IN PCK_SUBTIPOS.TI_COMPANIA,
    UN_CADENAPLAN  IN CLOB,
    UN_USUARIO     IN PCK_SUBTIPOS.TI_USUARIO
)RETURN CLOB;

FUNCTION FC_ACT_MASIVA_CONCEPTOS_EXO
( 
  UN_COMPANIA    IN PCK_SUBTIPOS.TI_COMPANIA,
  UN_ANIO        IN PCK_SUBTIPOS.TI_ANIO,
  UN_CADENAPLAN  IN CLOB,
  UN_USUARIO     IN PCK_SUBTIPOS.TI_USUARIO
)  
RETURN CLOB;

FUNCTION FC_COPIAR_CONCEPTO_EXOGENA(
    UN_COMPANIA          IN  VARCHAR2,
    UN_ANO_DESTINO       IN  INTEGER,
    UN_ANO_ORIGEN        IN  INTEGER,
    UN_COMPANIA_DESTINO  IN  VARCHAR2,
    UN_FORMATO           IN  VARCHAR2
)
RETURN CLOB;

END PCK_EXOGENAS;