SELECT VARIABLE_PROPONENTE.CODIGO, 
       VARIABLE_PROPONENTE.DESCRIPCION, 
       DECODE(VARIABLE_PROPONENTE.TIPO , '1', 'Texto' , '2' , 'Memo' , '3' , 'Numérico' , '4' , 'Fecha' , '5' , 'Formula' , '6' , 'Otro') AS TIPO, 
       DECODE(VARIABLE_PROPONENTE.ESCONSTANTE,'-1' , 'Si' , '0' , 'No') AS ESCONSTANTE, 
       VARIABLE_PROPONENTE.VRPREDETERMINADO 
FROM VARIABLE_PROPONENTE 
WHERE VARIABLE_PROPONENTE.COMPANIA = s$compania$s
