create or replace TRIGGER "TR_ELIMINAR_MODELO_TABLA" 
BEFORE DELETE ON MODELO_TABLA 
FOR EACH ROW
BEGIN
  DELETE FROM MODELO_VARIABLES WHERE PLANTILLA = :OLD.PLANTILLA AND TRUNC(FECHA) = TRUNC(:OLD.FECHA) AND DESCRIPCION = :OLD.NOMBRE AND TIPO = 'T';
END;
