SELECT
    COMPANIA,
    TO_CHAR(NUMERO_DOCUMENTO) AS COMPROBANTE,
    FECHA_DE_REGISTRO AS FECHA,
    RUBRO,
    DESCRIPCION AS NOMBRE,
    FUENTE AS FUENTE,
    '001' AS CODSUCURSAL,
    IDENTIFICACION AS CODTERCERO,
    NOMBRE_RAZON_SOCIAL AS NOMBRETERCERO,
    OBJETO_DEL_COMPROMISO AS DESCRIPCION,
    VALOR_INICIAL AS MOVIMIENTO,
    ( VALORACTUAL - SALDO_POR_UTILIZAR ) AS AFECTACION,
    VALOR_OPERACIONES AS MODIFICACION,
    SALDO_POR_UTILIZAR AS SALDO
FROM
    SIIF_OBLIGACIONES
WHERE COMPANIA =s$compania$s
 AND   TO_NUMBER(TO_CHAR(FECHA_DE_REGISTRO,'YYYY') ) =s$anio$s
 AND   TO_NUMBER(TO_CHAR(FECHA_DE_REGISTRO,'MM') ) =s$mes$s
ORDER BY SIIF_OBLIGACIONES.RUBRO,
   SIIF_OBLIGACIONES.NUMERO_DOCUMENTO
