SELECT
    COMPANIA,
    TO_CHAR(NUMERO_DOCUMENTO) AS COMPROBANTE,
    FECHA_DE_REGISTRO AS FECHA,
    RUBRO,
    FUENTE,
    DESCRIPCION,
    '999999999999999999' AS CODTERCERO,
    'VARIOS' AS NOMBRETERCERO,
    VALOR_INICIAL AS MOVIMIENTO,
    ( VALOR_ACTUAL - SALDO_POR_COMPROMETER ) AS AFECTACION,
    VALOR_OPERACIONES AS MODIFICACION,
    SALDO_POR_COMPROMETER AS SALDO
FROM
    SIIF_DISPONIBILIDADES
WHERE COMPANIA = s$compania$s
 AND  TO_NUMBER(TO_CHAR(FECHA_DE_REGISTRO,'YYYY')) = s$anio$s
 AND  TO_NUMBER(TO_CHAR(FECHA_DE_REGISTRO,'MM')) = s$mes$s
ORDER BY RUBRO,
         NUMERO_DOCUMENTO
