SELECT  
      TERCERO.COMPANIA
     ,PCK_SYSMAN_UTL.FC_MINIT(TERCERO.COMPANIA,312) NIT_RETENEDOR_ESPACIOS 
     ,PCK_SYSMAN_UTL.FC_MINIT(TERCERO.COMPANIA,31)  NIT_RETENEDOR 
     ,PCK_SYSMAN_UTL.FC_MINIT(TERCERO.COMPANIA,1) DV_RETENEDOR
     ,TIPOS_DOCUMENTOS.CODIGODIAN TIPO_DOCUMENTO
     ,TERCERO.NIT NUMERO_DOCUMENTO
     ,COMPANIA.NOMBRE RAZON_SOCIAL_RETENEDOR
     ,TERCERO.APELLIDO1
     ,TERCERO.APELLIDO2
     ,TERCERO.NOMBRE1
     ,TERCERO.NOMBRE2
     ,(TRIM(TERCERO.NOMBRE1)  || ' ' ||TRIM(TERCERO.NOMBRE2)) NOMBRES
     ,DETALLE_COMPROBANTE_CNT.ANO
     ,CIUDAD.CODIGODANE CODIGOCIUDAD
     ,CIUDAD.NOMBRE NOMBRECIUDAD
     ,DEPARTAMENTO.CODIGODANE CODIGODEPARTAMENTO
     ,ANO.VALORUVT
     ,ANO.PATRIMONIOBRUTO_UVT
     ,ROUND(ANO.VALORUVT * ANO.PATRIMONIOBRUTO_UVT,-3) PATRIMONIOBRUTO_VALOR
     ,ANO.INGRESOSTOTALES_UVT
     ,ROUND(ANO.VALORUVT * ANO.INGRESOSTOTALES_UVT,-3) INGRESOSTOTALES_VALOR
     ,ANO.CONSUMOTARJETACRE_UVT
     ,ROUND(ANO.VALORUVT * ANO.CONSUMOTARJETACRE_UVT,-3) CONSUMOTARJETACRE_VALOR
     ,ANO.COMPRASYCONSUMO_UVT
     ,ROUND(ANO.VALORUVT * ANO.COMPRASYCONSUMO_UVT,-3) COMPRASYCONSUMO_VALOR
     ,ANO.CONSIGNACIONESBANCARIAS_UVT
     ,ROUND(ANO.VALORUVT * ANO.CONSIGNACIONESBANCARIAS_UVT,-3) CONSIGNACIONESBANCARIAS_VALOR,
     SUM(NVL(VALOR_RETENCION.RETENCION,0))VALORRETENCION,
     SUM(NVL(RETE.PAGOS,0))RETE,
     MIN(CASE
        WHEN TRUNC(COMPROBANTE_CNT.FECHA) BETWEEN TO_DATE('01/01/' || DETALLE_COMPROBANTE_CNT.ANO, 'DD/MM/YYYY') AND TO_DATE('31/12/' || DETALLE_COMPROBANTE_CNT.ANO, 'DD/MM/YYYY')
        THEN COMPROBANTE_CNT.FECHA
        ELSE TO_DATE('01/01/' || DETALLE_COMPROBANTE_CNT.ANO, 'DD/MM/YYYY')
      END) FECHAINICIAL 
     ,MAX(CASE
        WHEN TRUNC(COMPROBANTE_CNT.FECHA -1) BETWEEN TO_DATE('01/01/' || DETALLE_COMPROBANTE_CNT.ANO, 'DD/MM/YYYY') AND TO_DATE('31/12/' || DETALLE_COMPROBANTE_CNT.ANO, 'DD/MM/YYYY')
        THEN COMPROBANTE_CNT.FECHA -1
        ELSE TO_DATE('31/12/' || DETALLE_COMPROBANTE_CNT.ANO, 'DD/MM/YYYY')
      END) FECHAFINAL
    , EXTRACT(YEAR FROM MIN(CASE
        WHEN TRUNC(COMPROBANTE_CNT.FECHA) BETWEEN TO_DATE('01/01/' || DETALLE_COMPROBANTE_CNT.ANO, 'DD/MM/YYYY') AND TO_DATE('31/12/' || DETALLE_COMPROBANTE_CNT.ANO, 'DD/MM/YYYY')
        THEN COMPROBANTE_CNT.FECHA
        ELSE TO_DATE('01/01/' || DETALLE_COMPROBANTE_CNT.ANO, 'DD/MM/YYYY')
      END) ) ANO_INICIAL
    , EXTRACT(MONTH FROM MIN(CASE
        WHEN TRUNC(COMPROBANTE_CNT.FECHA) BETWEEN TO_DATE('01/01/' || DETALLE_COMPROBANTE_CNT.ANO, 'DD/MM/YYYY') AND TO_DATE('31/12/' || DETALLE_COMPROBANTE_CNT.ANO, 'DD/MM/YYYY')
        THEN COMPROBANTE_CNT.FECHA
        ELSE TO_DATE('01/01/' || DETALLE_COMPROBANTE_CNT.ANO, 'DD/MM/YYYY')
      END) ) MES_INICIAL
    , EXTRACT(DAY FROM MIN(CASE
        WHEN TRUNC(COMPROBANTE_CNT.FECHA) BETWEEN TO_DATE('01/01/' || DETALLE_COMPROBANTE_CNT.ANO, 'DD/MM/YYYY') AND TO_DATE('31/12/' || DETALLE_COMPROBANTE_CNT.ANO, 'DD/MM/YYYY')
        THEN COMPROBANTE_CNT.FECHA
        ELSE TO_DATE('01/01/' || DETALLE_COMPROBANTE_CNT.ANO, 'DD/MM/YYYY')
      END) ) DIA_INICIAL
    , EXTRACT(YEAR FROM MAX(CASE
        WHEN TRUNC(COMPROBANTE_CNT.FECHA -1) BETWEEN TO_DATE('01/01/' || DETALLE_COMPROBANTE_CNT.ANO, 'DD/MM/YYYY') AND TO_DATE('31/12/' || DETALLE_COMPROBANTE_CNT.ANO, 'DD/MM/YYYY')
        THEN COMPROBANTE_CNT.FECHA -1
        ELSE TO_DATE('31/12/' || DETALLE_COMPROBANTE_CNT.ANO, 'DD/MM/YYYY')
      END) ) ANO_FINAL
    , EXTRACT(MONTH FROM MAX(CASE
        WHEN TRUNC(COMPROBANTE_CNT.FECHA -1) BETWEEN TO_DATE('01/01/' || DETALLE_COMPROBANTE_CNT.ANO, 'DD/MM/YYYY') AND TO_DATE('31/12/' || DETALLE_COMPROBANTE_CNT.ANO, 'DD/MM/YYYY')
        THEN COMPROBANTE_CNT.FECHA -1
        ELSE TO_DATE('31/12/' || DETALLE_COMPROBANTE_CNT.ANO, 'DD/MM/YYYY')
      END) ) MES_FINAL
    , EXTRACT(DAY FROM MAX(CASE
        WHEN TRUNC(COMPROBANTE_CNT.FECHA -1) BETWEEN TO_DATE('01/01/' || DETALLE_COMPROBANTE_CNT.ANO, 'DD/MM/YYYY') AND TO_DATE('31/12/' || DETALLE_COMPROBANTE_CNT.ANO, 'DD/MM/YYYY')
        THEN COMPROBANTE_CNT.FECHA -1
        ELSE TO_DATE('31/12/' || DETALLE_COMPROBANTE_CNT.ANO, 'DD/MM/YYYY')
      END) ) DIA_FINAL
FROM COMPANIA 
  INNER JOIN  TERCERO 
    ON COMPANIA.CODIGO = TERCERO.COMPANIA
  LEFT JOIN TIPOS_DOCUMENTOS 
    ON TERCERO.COMPANIA = TIPOS_DOCUMENTOS.COMPANIA
   AND TERCERO.TIPOID   = TIPOS_DOCUMENTOS.DCTO_IDENTIDAD
  LEFT JOIN DEPARTAMENTO
    ON DEPARTAMENTO.PAIS   = COMPANIA.PAIS
   AND DEPARTAMENTO.CODIGO = COMPANIA.DEPARTAMENTO
  LEFT JOIN CIUDAD 
    ON CIUDAD.PAIS         = COMPANIA.PAIS
   AND CIUDAD.DEPARTAMENTO = COMPANIA.DEPARTAMENTO
   AND CIUDAD.CODIGO       = COMPANIA.CIUDAD
  LEFT JOIN DETALLE_COMPROBANTE_CNT
   ON TERCERO.COMPANIA         = DETALLE_COMPROBANTE_CNT.COMPANIA
   AND TERCERO.NIT = DETALLE_COMPROBANTE_CNT.TERCERO
   AND TERCERO.SUCURSAL       = DETALLE_COMPROBANTE_CNT.SUCURSAL 
  INNER JOIN COMPROBANTE_CNT 
    ON COMPROBANTE_CNT.COMPANIA = DETALLE_COMPROBANTE_CNT.COMPANIA 
    AND COMPROBANTE_CNT.ANO = DETALLE_COMPROBANTE_CNT.ANO 
    AND COMPROBANTE_CNT.TIPO = DETALLE_COMPROBANTE_CNT.TIPO_CPTE
    AND COMPROBANTE_CNT.NUMERO = DETALLE_COMPROBANTE_CNT.COMPROBANTE   
  INNER JOIN ANO
    ON DETALLE_COMPROBANTE_CNT.COMPANIA = ANO.COMPANIA
    AND DETALLE_COMPROBANTE_CNT.ANO      = ANO.NUMERO
  LEFT JOIN (SELECT   DETALLE_COMPROBANTE_CNT.COMPANIA,
                      DETALLE_COMPROBANTE_CNT.ANO,
                      DETALLE_COMPROBANTE_CNT.TIPO_CPTE,
                      DETALLE_COMPROBANTE_CNT.COMPROBANTE,
                      DETALLE_COMPROBANTE_CNT.CONSECUTIVO,
                      SUM(DETALLE_COMPROBANTE_CNT.VALOR_CREDITO)  RETENCION
              FROM PLAN_CONTABLE 
                INNER JOIN DETALLE_COMPROBANTE_CNT
                 ON  PLAN_CONTABLE.COMPANIA = DETALLE_COMPROBANTE_CNT.COMPANIA
                 AND PLAN_CONTABLE.ANO = DETALLE_COMPROBANTE_CNT.ANO
                 AND PLAN_CONTABLE.CODIGO= DETALLE_COMPROBANTE_CNT.CUENTA
                 AND PLAN_CONTABLE.NATURALEZA = DETALLE_COMPROBANTE_CNT.NATURALEZA
                INNER JOIN COMPROBANTE_CNT 
                  ON COMPROBANTE_CNT.COMPANIA = DETALLE_COMPROBANTE_CNT.COMPANIA 
                  AND COMPROBANTE_CNT.ANO = DETALLE_COMPROBANTE_CNT.ANO 
                  AND COMPROBANTE_CNT.TIPO = DETALLE_COMPROBANTE_CNT.TIPO_CPTE
                  AND COMPROBANTE_CNT.NUMERO = DETALLE_COMPROBANTE_CNT.COMPROBANTE    
                INNER JOIN TERCERO 
                  ON  TERCERO.COMPANIA = DETALLE_COMPROBANTE_CNT.COMPANIA  
                  AND TERCERO.NIT = DETALLE_COMPROBANTE_CNT.TERCERO   
                  AND TERCERO.SUCURSAL = DETALLE_COMPROBANTE_CNT.SUCURSAL 
              INNER JOIN TIPO_COMPROBANTE 
                 ON COMPROBANTE_CNT.TIPO = TIPO_COMPROBANTE.CODIGO 
                 AND COMPROBANTE_CNT.COMPANIA = TIPO_COMPROBANTE.COMPANIA 
              WHERE DETALLE_COMPROBANTE_CNT.COMPANIA = s$compania$s
                AND   DETALLE_COMPROBANTE_CNT.ANO = s$anio$s
                AND INSTR(PCK_SYSMAN_UTL.FC_COLOCARCOMILLAS(PCK_SYSMAN_UTL.FC_PAR(DETALLE_COMPROBANTE_CNT.COMPANIA,'CUENTAS CONTABLES DE RETENCION 1607 SIN CODIFICAR',1,DETALLE_COMPROBANTE_CNT.FECHA)), '' || DETALLE_COMPROBANTE_CNT.CUENTA || '',1)=0
                 AND  DETALLE_COMPROBANTE_CNT.TERCERO BETWEEN 's$cedulaInicial$s' AND 's$cedulaFinal$s'            
                  AND  COMPROBANTE_CNT.FECHA BETWEEN s$fecha1$s AND s$fecha2$s
                AND TIPO_COMPROBANTE.CLASE_CONTABLE NOT IN('Z') 
              GROUP BY   DETALLE_COMPROBANTE_CNT.COMPANIA,
                      DETALLE_COMPROBANTE_CNT.ANO,
                      DETALLE_COMPROBANTE_CNT.TIPO_CPTE,
                      DETALLE_COMPROBANTE_CNT.COMPROBANTE,
                      DETALLE_COMPROBANTE_CNT.CONSECUTIVO )VALOR_RETENCION 
    ON  DETALLE_COMPROBANTE_CNT.COMPANIA = VALOR_RETENCION.COMPANIA
    AND DETALLE_COMPROBANTE_CNT.ANO =VALOR_RETENCION.ANO
    AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE = VALOR_RETENCION.TIPO_CPTE
    AND DETALLE_COMPROBANTE_CNT.COMPROBANTE =VALOR_RETENCION.COMPROBANTE
    AND DETALLE_COMPROBANTE_CNT.CONSECUTIVO   =  VALOR_RETENCION.CONSECUTIVO   
  LEFT JOIN (SELECT   DETALLE_COMPROBANTE_CNT.COMPANIA,
                      DETALLE_COMPROBANTE_CNT.ANO,
                      DETALLE_COMPROBANTE_CNT.TIPO_CPTE,
                      DETALLE_COMPROBANTE_CNT.COMPROBANTE,
                      DETALLE_COMPROBANTE_CNT.CONSECUTIVO,
                    SUM(DETALLE_COMPROBANTE_CNT.VALOR_DEBITO) PAGOS
              FROM DETALLE_COMPROBANTE_CNT INNER JOIN PLAN_CONTABLE 
                             ON DETALLE_COMPROBANTE_CNT.COMPANIA = PLAN_CONTABLE.COMPANIA 
                             AND DETALLE_COMPROBANTE_CNT.ANO = PLAN_CONTABLE.ANO 
                             AND DETALLE_COMPROBANTE_CNT.CUENTA = PLAN_CONTABLE.CODIGO
                        INNER JOIN TERCERO 
                           ON DETALLE_COMPROBANTE_CNT.COMPANIA = TERCERO.COMPANIA 
                           AND DETALLE_COMPROBANTE_CNT.TERCERO = TERCERO.NIT
                           AND DETALLE_COMPROBANTE_CNT.SUCURSAL = TERCERO.SUCURSAL
                       INNER JOIN CLASECUENTA 
                      ON PLAN_CONTABLE.CLASECUENTA = CLASECUENTA.CODIGO
                     INNER JOIN COMPROBANTE_CNT 
                  ON COMPROBANTE_CNT.COMPANIA = DETALLE_COMPROBANTE_CNT.COMPANIA 
                  AND COMPROBANTE_CNT.ANO = DETALLE_COMPROBANTE_CNT.ANO 
                  AND COMPROBANTE_CNT.TIPO = DETALLE_COMPROBANTE_CNT.TIPO_CPTE
                  AND COMPROBANTE_CNT.NUMERO = DETALLE_COMPROBANTE_CNT.COMPROBANTE     
              WHERE DETALLE_COMPROBANTE_CNT.COMPANIA = s$compania$s
                        AND   DETALLE_COMPROBANTE_CNT.ANO = s$anio$s
                        AND  COMPROBANTE_CNT.FECHA BETWEEN s$fecha1$s AND s$fecha2$s
                       AND PLAN_CONTABLE.CLASECUENTA IN ('G','R','V') 
                        AND  DETALLE_COMPROBANTE_CNT.TERCERO BETWEEN 's$cedulaInicial$s' AND 's$cedulaFinal$s'        
              GROUP BY DETALLE_COMPROBANTE_CNT.COMPANIA,
                      DETALLE_COMPROBANTE_CNT.ANO,
                      DETALLE_COMPROBANTE_CNT.TIPO_CPTE,
                      DETALLE_COMPROBANTE_CNT.COMPROBANTE,
                      DETALLE_COMPROBANTE_CNT.CONSECUTIVO)RETE
    ON  DETALLE_COMPROBANTE_CNT.COMPANIA = RETE.COMPANIA
    AND DETALLE_COMPROBANTE_CNT.ANO =RETE.ANO
    AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE = RETE.TIPO_CPTE
    AND DETALLE_COMPROBANTE_CNT.COMPROBANTE =RETE.COMPROBANTE
    AND DETALLE_COMPROBANTE_CNT.CONSECUTIVO   =  RETE.CONSECUTIVO   
WHERE  DETALLE_COMPROBANTE_CNT.COMPANIA =s$compania$s
  AND DETALLE_COMPROBANTE_CNT.ANO       = s$anio$s
  AND TERCERO.NIT BETWEEN 's$cedulaInicial$s' AND 's$cedulaFinal$s'   
  AND INSTR(PCK_SYSMAN_UTL.FC_COLOCARCOMILLAS(PCK_SYSMAN_UTL.FC_PAR(DETALLE_COMPROBANTE_CNT.COMPANIA,'CUENTAS CONTABLES DE RETENCION 1607 SIN CODIFICAR',1,DETALLE_COMPROBANTE_CNT.FECHA)), '' || DETALLE_COMPROBANTE_CNT.CUENTA || '',1)=0
  AND COMPROBANTE_CNT.FECHA BETWEEN s$fecha1$s AND s$fecha2$s
GROUP BY TERCERO.COMPANIA
     ,COMPANIA.NITCOMPANIA
     ,TERCERO.NIT 
     ,TIPOS_DOCUMENTOS.CODIGODIAN
     ,COMPANIA.NOMBRE
     ,TERCERO.APELLIDO1
     ,TERCERO.APELLIDO2
     ,TERCERO.NOMBRE1
     ,TERCERO.NOMBRE2
     ,(TRIM(TERCERO.NOMBRE1)  || ' ' ||TRIM(TERCERO.NOMBRE2)) 
     ,DETALLE_COMPROBANTE_CNT.ANO
     ,CIUDAD.CODIGODANE 
     ,CIUDAD.NOMBRE 
     ,DEPARTAMENTO.CODIGODANE
     ,ANO.VALORUVT
     ,ANO.PATRIMONIOBRUTO_UVT
     ,ANO.INGRESOSTOTALES_UVT
     ,ANO.CONSUMOTARJETACRE_UVT
     ,ANO.COMPRASYCONSUMO_UVT
     ,ANO.CONSIGNACIONESBANCARIAS_UVT
