CREATE OR REPLACE PACKAGE                "PCK_SYSMAN_UTL" AS 

GL_ERROR_NUM  NUMBER:=3000;                       -- 11/02/2015 - Variable que se usa para almacenar el c¿o del error presentando, par¿tro de la funci¿VALUAR_ERROR
GL_ERROR_MSG  VARCHAR2(32000);                    -- 23/01/2015 - Variable que se usa para almacenar el mensaje del error presentando, par¿tro de la funci¿VALUAR_ERROR
GL_RTA        VARCHAR2(32000);                    -- 23/01/2015 - Variable que se usa para almacenar el resulatado de la ejecuci¿e funciones

TYPE T_SPLIT is TABLE OF VARCHAR2(100) INDEX BY BINARY_INTEGER;

 FUNCTION FC_IIF
	(
    UN_CONDICION	BOOLEAN,   
	  UN_SI		      VARCHAR2,  
	  UN_NO     		VARCHAR2 DEFAULT NULL   
	)
RETURN VARCHAR2;

 FUNCTION FC_IIF
	(
    UN_CONDICION	VARCHAR2,
	  UN_SI		      VARCHAR2,
	  UN_NO     		VARCHAR2 DEFAULT NULL
	)
RETURN VARCHAR2;

FUNCTION FC_IIF
	(
    UN_CONDICION	Boolean,
	  UN_SI		      DATE,
	  UN_NO     		DATE DEFAULT NULL
	)
RETURN DATE;
      
FUNCTION FC_IIF
	(
    UN_CONDICION	Boolean,
	  UN_SI		      NUMBER,
	  UN_NO     		NUMBER DEFAULT 0
	)
RETURN NUMBER; 

FUNCTION FC_IIF
	(
    UN_CONDICION	Boolean
	)
RETURN BOOLEAN; 

FUNCTION FC_EVAL 
  (
    Cadena VARCHAR2   
  ) 
RETURN NUMBER;

FUNCTION FC_EVALC 
  (
    CADENA VARCHAR2
  ) 
RETURN NUMBER; 

FUNCTION FC_EVALUAR_ERROR 
  (
    UN_CODERROR     NUMBER := NULL,
    UN_TXTERROR     VARCHAR2 := NULL,
    UN_TABLAERROR   VARCHAR2,
    UN_SQLERROR     VARCHAR2,
    UN_ERROR_ORA    VARCHAR2
  )
RETURN VARCHAR2 ;



 FUNCTION FC_IIF
	(
    UN_CONDICION	VARCHAR2  
	)
RETURN VARCHAR2;

FUNCTION FC_SPLIT_SYS 
  (
  UN_LISTA       VARCHAR2,
  UN_DELIMITADOR VARCHAR2 :=','
  )
  RETURN T_SPLIT;


FUNCTION FC_LISTA_CAMPOS
  (
   UN_TABLA      VARCHAR2,
   UN_EXCLUIDOS  VARCHAR2 DEFAULT '',
   UN_CAMPOSCLOB NUMBER DEFAULT 0,
   UN_CONDOMINIO NUMBER DEFAULT 0
)
RETURN VARCHAR2;

FUNCTION FC_LISTA_CAMPOS
  (
   UN_TABLA      VARCHAR2,
   UN_EXCLUIDOS  VARCHAR2 DEFAULT '',
   UN_CAMPOSCLOB NUMBER DEFAULT 0,
   UN_CONDOMINIO NUMBER DEFAULT 0,
   UN_VIRTUAL    NUMBER DEFAULT 0
)
RETURN VARCHAR2;

FUNCTION FC_EXISTECAMPO
  (
  
   UN_TABLA      VARCHAR2,
   UN_CAMPO      VARCHAR2
)
RETURN BOOLEAN;

FUNCTION FC_SDATE
  (
    UN_FECHA  DATE
  )
  RETURN VARCHAR2;


FUNCTION FC_SDATE
  (
    UN_FECHA  VARCHAR2,
    UN_FORMATO VARCHAR2
  )
  RETURN VARCHAR2; 
  
  
FUNCTION FC_DCH
	(
	  UN_NUMERO	VARCHAR2 DEFAULT '0'
	)
RETURN NUMBER
DETERMINISTIC
; 

FUNCTION FC_MESESCOMPLETOS 
  (
    UN_FECHA1 DATE,
    UN_FECHA2 DATE
  )
RETURN NUMBER;


FUNCTION FC_DIA  
  ( 
    UN_FECHA DATE
   )
RETURN NUMBER;

FUNCTION FC_MES  
  ( 
    UN_FECHA DATE
   )
RETURN NUMBER;

FUNCTION FC_VIGENCIA  
  ( 
    UN_FECHA DATE
   )
RETURN NUMBER;

FUNCTION FC_DIASMESCOMERCIAL
  (
    UN_FECHAIN  DATE,
    UN_FECHAFIN DATE
  )
RETURN NUMBER;


FUNCTION FC_EXISTETABLA
  (
   UN_TABLA      VARCHAR2
  )
RETURN BOOLEAN ;

FUNCTION FC_WEEKDAY
  (
    UN_FECHA   DATE,
    UN_ARRANCA NUMBER DEFAULT 1
  ) 
RETURN NUMBER ;

FUNCTION FC_VALOR_LETRAS
  (
    UN_NUMT NUMBER,
    UN_CTVS NUMBER DEFAULT 0
  ) 
RETURN VARCHAR2;

FUNCTION FC_ROUND
  ( 
    UN_VALOR NUMBER,
    UN_PRECISION NUMBER DEFAULT 0
  )
RETURN NUMBER;

FUNCTION FC_DURACION
  (
    UN_TIEMPOI DATE,
    UN_TIEMPOF DATE
  )
RETURN VARCHAR2;

--30
FUNCTION FC_GENCONSECUTIVO
	(
		UN_TABLA    IN PCK_SUBTIPOS.TI_TABLA,
		UN_CRITERIO IN PCK_SUBTIPOS.TI_CONDICION,
		UN_CAMPO    IN VARCHAR2
	)
RETURN NUMBER;
--31
FUNCTION FC_GENCONSECUTIVO
	(
		UN_TABLA    IN PCK_SUBTIPOS.TI_TABLA,
		UN_CRITERIO IN PCK_SUBTIPOS.TI_CONDICION,
		UN_CAMPO    IN VARCHAR2,
		UN_INICIAL  IN VARCHAR2
	)
RETURN NUMBER;

FUNCTION FC_NOMBRE_MES
  (
    UN_NUMERO_MES   NUMBER
  )  
RETURN VARCHAR2
DETERMINISTIC;

FUNCTION FC_STRZERO 
  (
  UN_NUMERO NUMBER,
  UN_LONGITUD NUMBER
  )
RETURN VARCHAR;
FUNCTION FC_STRZERO 
  (
  UN_NUMERO VARCHAR2,
  UN_LONGITUD NUMBER
  )
RETURN VARCHAR;



FUNCTION FC_PADC
  (
    UN_CADENA     VARCHAR2,
    UN_LONGITUD   NUMBER,
    UN_CARACTER   VARCHAR2 DEFAULT ' '
   )
  RETURN VARCHAR2;
  
  
FUNCTION FC_AGREGARCOLUMNAS
  (
    UN_QUERY                VARCHAR2,
    UN_PLANTILLA            NUMBER
  )
  RETURN VARCHAR2;
  
  
  
  FUNCTION FC_VACIARCOLUMNAS
  (
    UN_QUERY                VARCHAR2
  )
RETURN VARCHAR2;


  FUNCTION FC_ENCRIPTARMD5
  (
    UN_CADENA            VARCHAR2
  )
RETURN VARCHAR2;

FUNCTION FC_COLOCARCOMILLAS(
 
   UN_CADENA           VARCHAR2
) 
RETURN VARCHAR2;

FUNCTION FC_COPIAR_PLANTILLA (
    UN_PLANTILLA_ORIGEN  IN VARCHAR2,
    UN_PLANTILLA_DESTINO IN VARCHAR2,
    UN_FECHA_ORIGEN      IN DATE,
    UN_NOMBRE            IN VARCHAR2,
    UN_TIPO              IN NUMBER,
    UN_PLANTILLA         IN VARCHAR2
) RETURN VARCHAR2;



END PCK_SYSMAN_UTL;