
package com.sysman.util.soap.es.delogica.saaf.ws.consultaestados.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultaEstadosFacturasWS", targetNamespace = "http://impl.consultaestados.ws.saaf.delogica.es/")
public class ConsultaEstadosFacturasWS
    extends Service
{

   private final static QName CONSULTAESTADOSFACTURASWS_QNAME = new QName("http://impl.consultaestados.ws.saaf.delogica.es/", "ConsultaEstadosFacturasWS");

    public ConsultaEstadosFacturasWS() {
        super(__getWsdlLocation(), CONSULTAESTADOSFACTURASWS_QNAME);
    }

    public ConsultaEstadosFacturasWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTAESTADOSFACTURASWS_QNAME, features);
    }

    public ConsultaEstadosFacturasWS(URL wsdlLocation) {
        super(wsdlLocation, CONSULTAESTADOSFACTURASWS_QNAME);
    }

    public ConsultaEstadosFacturasWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTAESTADOSFACTURASWS_QNAME, features);
    }

    public ConsultaEstadosFacturasWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaEstadosFacturasWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultaEstadosFacturasWSService
     */
    @WebEndpoint(name = "ConsultaEstadosFacturasWSPort")
    public ConsultaEstadosFacturasWSService getConsultaEstadosFacturasWSPort() {
        return super.getPort(new QName("http://impl.consultaestados.ws.saaf.delogica.es/", "ConsultaEstadosFacturasWSPort"), ConsultaEstadosFacturasWSService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaEstadosFacturasWSService
     */
    @WebEndpoint(name = "ConsultaEstadosFacturasWSPort")
    public ConsultaEstadosFacturasWSService getConsultaEstadosFacturasWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.consultaestados.ws.saaf.delogica.es/", "ConsultaEstadosFacturasWSPort"), ConsultaEstadosFacturasWSService.class, features);
    }

    private static URL __getWsdlLocation() {
    	return null;
    }

}
