
package com.sysman.util.soap.es.delogica.saaf.ws.consultaestados.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConsultaEstadosFacturasWSService", targetNamespace = "http://impl.consultaestados.ws.saaf.delogica.es/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultaEstadosFacturasWSService {


    /**
     * 
     * @param request
     * @return
     *     returns es.delogica.saaf.ws.consultaestados.impl.ConsultaEstadosFacturasResponse
     * @throws SAAFException_Exception
     */
    @WebMethod(action = "urn:ConsultaFacturasModificadas")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaFacturasModificadas", targetNamespace = "http://impl.consultaestados.ws.saaf.delogica.es/", className = "es.delogica.saaf.ws.consultaestados.impl.ConsultaFacturasModificadas")
    @ResponseWrapper(localName = "consultaFacturasModificadasResponse", targetNamespace = "http://impl.consultaestados.ws.saaf.delogica.es/", className = "es.delogica.saaf.ws.consultaestados.impl.ConsultaFacturasModificadasResponse")
    public ConsultaEstadosFacturasResponse consultaFacturasModificadas(
        @WebParam(name = "request", targetNamespace = "http://impl.consultaestados.ws.saaf.delogica.es/")
        ConsultaFacturasModificadasRequest request)
        throws SAAFException_Exception
    ;

    /**
     * 
     * @param request
     * @return
     *     returns es.delogica.saaf.ws.consultaestados.impl.ConsultaEstadosFicherosYFacturasResponse
     * @throws SAAFException_Exception
     */
    @WebMethod(action = "urn:GetEstadosFacturasConFicheros")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEstadosFacturasConFicheros", targetNamespace = "http://impl.consultaestados.ws.saaf.delogica.es/", className = "es.delogica.saaf.ws.consultaestados.impl.GetEstadosFacturasConFicheros")
    @ResponseWrapper(localName = "getEstadosFacturasConFicherosResponse", targetNamespace = "http://impl.consultaestados.ws.saaf.delogica.es/", className = "es.delogica.saaf.ws.consultaestados.impl.GetEstadosFacturasConFicherosResponse")
    public ConsultaEstadosFicherosYFacturasResponse getEstadosFacturasConFicheros(
        @WebParam(name = "request", targetNamespace = "http://impl.consultaestados.ws.saaf.delogica.es/")
        ConsultaEstadosFacturasRequest request)
        throws SAAFException_Exception
    ;

    /**
     * 
     * @param request
     * @return
     *     returns es.delogica.saaf.ws.consultaestados.impl.FacturaResult
     * @throws SAAFException_Exception
     */
    @WebMethod(action = "urn:EntregaFactura")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "entregaFactura", targetNamespace = "http://impl.consultaestados.ws.saaf.delogica.es/", className = "es.delogica.saaf.ws.consultaestados.impl.EntregaFactura")
    @ResponseWrapper(localName = "entregaFacturaResponse", targetNamespace = "http://impl.consultaestados.ws.saaf.delogica.es/", className = "es.delogica.saaf.ws.consultaestados.impl.EntregaFacturaResponse")
    public FacturaResult entregaFactura(
        @WebParam(name = "request", targetNamespace = "http://impl.consultaestados.ws.saaf.delogica.es/")
        EntregaFacturaRequest request)
        throws SAAFException_Exception
    ;

    /**
     * 
     * @param request
     * @return
     *     returns es.delogica.saaf.ws.consultaestados.impl.ConsultaEstadosFacturasResponse
     * @throws SAAFException_Exception
     */
    @WebMethod(action = "urn:GetEstadosFacturas")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEstadosFacturas", targetNamespace = "http://impl.consultaestados.ws.saaf.delogica.es/", className = "es.delogica.saaf.ws.consultaestados.impl.GetEstadosFacturas")
    @ResponseWrapper(localName = "getEstadosFacturasResponse", targetNamespace = "http://impl.consultaestados.ws.saaf.delogica.es/", className = "es.delogica.saaf.ws.consultaestados.impl.GetEstadosFacturasResponse")
    public ConsultaEstadosFacturasResponse getEstadosFacturas(
        @WebParam(name = "request", targetNamespace = "http://impl.consultaestados.ws.saaf.delogica.es/")
        ConsultaEstadosFacturasRequest request)
        throws SAAFException_Exception
    ;

}
