package com.sysman.util.soap.es.delogica.saaf.ws.consultaestados.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConsultaEstadosNominasWSService", targetNamespace = "http://impl.consultaestados.ws.saaf.delogica.es/")
@XmlSeeAlso({ ObjectFactory.class })
public interface ConsultaEstadosNominasWSService {

	/**
	 * 
	 * @param request
	 * @return returns
	 *         es.delogica.saaf.ws.consultaestados.impl.ConsultaEstadosNominasResponse
	 * @throws SAAFException_Exception
	 */
	@WebMethod(action = "urn:GetEstadosNominas")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getEstadosNominas", targetNamespace = "http://impl.consultaestados.ws.saaf.delogica.es/", className = "es.delogica.saaf.ws.consultaestados.impl.GetEstadosNominas")
	@ResponseWrapper(localName = "getEstadosNominasResponse", targetNamespace = "http://impl.consultaestados.ws.saaf.delogica.es/", className = "es.delogica.saaf.ws.consultaestados.impl.GetEstadosNominasResponse")
	public ConsultaEstadosNominasResponse getEstadosNominas(
			@WebParam(name = "request", targetNamespace = "http://impl.consultaestados.ws.saaf.delogica.es/") ConsultaEstadosNominasRequest request)
			throws SAAFException_Exception;

	/**
	 * 
	 * @param request
	 * @return returns
	 *         es.delogica.saaf.ws.consultaestados.impl.ConsultaEstadosFicherosYNominasResponse
	 * @throws SAAFException_Exception
	 */
	@WebMethod(action = "urn:GetEstadosNominasConFicheros")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getEstadosNominasConFicheros", targetNamespace = "http://impl.consultaestados.ws.saaf.delogica.es/", className = "es.delogica.saaf.ws.consultaestados.impl.GetEstadosNominasConFicheros")
	@ResponseWrapper(localName = "getEstadosNominasConFicherosResponse", targetNamespace = "http://impl.consultaestados.ws.saaf.delogica.es/", className = "es.delogica.saaf.ws.consultaestados.impl.GetEstadosNominasConFicherosResponse")
	public ConsultaEstadosFicherosYNominasResponse getEstadosNominasConFicheros(
			@WebParam(name = "request", targetNamespace = "http://impl.consultaestados.ws.saaf.delogica.es/") ConsultaEstadosNominasRequest request)
			throws SAAFException_Exception;

}
