package com.sysman.util.soap.es.delogica.saaf.ws.consultaestados.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultaEstadosNominasWS", targetNamespace = "http://impl.consultaestados.ws.saaf.delogica.es/", wsdlLocation = "https://pruebas.invoway.com/INVOWAYLATAM/services/ConsultaEstadosNominasWSPort?wsdl")
public class ConsultaEstadosNominasWS extends Service {

	private final static URL CONSULTAESTADOSNOMINASWS_WSDL_LOCATION;
	private final static WebServiceException CONSULTAESTADOSNOMINASWS_EXCEPTION;
	private final static QName CONSULTAESTADOSNOMINASWS_QNAME = new QName(
			"http://impl.consultaestados.ws.saaf.delogica.es/", "ConsultaEstadosNominasWS");

	static {
		URL url = null;
		WebServiceException e = null;
		try {
			url = new URL("https://pruebas.invoway.com/INVOWAYLATAM/services/ConsultaEstadosNominasWSPort?wsdl");
		} catch (MalformedURLException ex) {
			e = new WebServiceException(ex);
		}
		CONSULTAESTADOSNOMINASWS_WSDL_LOCATION = url;
		CONSULTAESTADOSNOMINASWS_EXCEPTION = e;
	}

	public ConsultaEstadosNominasWS() {
		super(__getWsdlLocation(), CONSULTAESTADOSNOMINASWS_QNAME);
	}

	public ConsultaEstadosNominasWS(WebServiceFeature... features) {
		super(__getWsdlLocation(), CONSULTAESTADOSNOMINASWS_QNAME, features);
	}

	public ConsultaEstadosNominasWS(URL wsdlLocation) {
		super(wsdlLocation, CONSULTAESTADOSNOMINASWS_QNAME);
	}

	public ConsultaEstadosNominasWS(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, CONSULTAESTADOSNOMINASWS_QNAME, features);
	}

	public ConsultaEstadosNominasWS(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ConsultaEstadosNominasWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * 
	 * @return returns ConsultaEstadosNominasWSService
	 */
	@WebEndpoint(name = "ConsultaEstadosNominasWSPort")
	public ConsultaEstadosNominasWSService getConsultaEstadosNominasWSPort() {
		return super.getPort(
				new QName("http://impl.consultaestados.ws.saaf.delogica.es/", "ConsultaEstadosNominasWSPort"),
				ConsultaEstadosNominasWSService.class);
	}

	/**
	 * 
	 * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *                 on the proxy. Supported features not in the
	 *                 <code>features</code> parameter will have their default
	 *                 values.
	 * @return returns ConsultaEstadosNominasWSService
	 */
	@WebEndpoint(name = "ConsultaEstadosNominasWSPort")
	public ConsultaEstadosNominasWSService getConsultaEstadosNominasWSPort(WebServiceFeature... features) {
		return super.getPort(
				new QName("http://impl.consultaestados.ws.saaf.delogica.es/", "ConsultaEstadosNominasWSPort"),
				ConsultaEstadosNominasWSService.class, features);
	}

	private static URL __getWsdlLocation() {
		if (CONSULTAESTADOSNOMINASWS_EXCEPTION != null) {
			throw CONSULTAESTADOSNOMINASWS_EXCEPTION;
		}
		return CONSULTAESTADOSNOMINASWS_WSDL_LOCATION;
	}

}
