
package com.sysman.util.soap.es.delogica.saaf.ws.consultaestados.impl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SAAFException", targetNamespace = "http://impl.consultaestados.ws.saaf.delogica.es/")
public class SAAFException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SAAFException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SAAFException_Exception(String message, SAAFException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SAAFException_Exception(String message, SAAFException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: es.delogica.saaf.ws.consultaestados.impl.SAAFException
     */
    public SAAFException getFaultInfo() {
        return faultInfo;
    }

}
