MERGE INTO CONSULTAS FIN USING (SELECT '000089NominaSTR' INFORME ,TO_CLOB(q'[SELECT DISTINCT 
    DENSE_RANK() OVER (ORDER BY V_VOLANTES.ID_DE_EMPLEADO) CONS_GRUPO0,  
    V_VOLANTES.Compania, 
    V_VOLANTES.ID_CENTRO_DE_COSTO AS ID_Centro_de_Costo,
    V_VOLANTES.NOMBRE_CENTRO_DE_COSTO AS Nombre_Centro_de_Costo,
    V_VOLANTES.NOMBRECOMPLETO AS NombreCompleto,
    V_VOLANTES.ID_de_Empleado, 
    V_VOLANTES.SALARIOBASEHISTORICO AS Salario_Base,
    V_VOLANTES.Clase, 
    V_VOLANTES.Nombre_Concepto,
    V_VOLANTES.Cuenta, 
    V_VOLANTES.ID_de_Proceso, 
    V_VOLANTES.NOMBRE_DE_CARGO,
    V_VOLANTES.Ano, 
    PCK_SYSMAN_UTL.FC_NOMBRE_MES(V_VOLANTES.Mes) AS Mes,
    V_VOLANTES.Periodo, 
    V_VOLANTES.ID_de_Concepto, 
    V_VOLANTES.Fecha, 
    V_VOLANTES.Cantidad, 
    V_VOLANTES.Devengos, 
    V_VOLANTES.Descuentos, 
    V_VOLANTES.DEPENDENCIA AS CODIGO, 
    V_VOLANTES.SALARIOENCARGOHISTORICO AS SUELDO_ENCARGO, 
    V_VOLANTES.Nombre_DEPENDENCIA, 
    V_VOLANTES.Banco, 
    V_VOLANTES.NOMBRE_BANCO, 
    V_VOLANTES.Nombre_de_Cargo,
    V_VOLANTES.ID_de_Cargo, 
    V_VOLANTES.Numero_Dcto,
    V_VOLANTES.Fecha_de_Ingreso,
   TRIM(TO_CHAR(NVL(V_VOLANTES.DEDUCIBLE,0), '999,999,990.90')) AS DEDUCIBLE,   
   PCK_NOMINA_COM1.FC_MINOVEDAD(s$compania$s,V_VOLANTES.ID_de_Proceso,V_VOLANTES.Ano,V_VOLANTES.Mes,V_VOLANTES.Id_de_Empleado,V_VOLANTES.PERIODO) MINOVEDAD 
FROM 
    V_VOLANTES 
WHERE 
    V_VOLANTES.COMPANIA =   s$compania$s
            AND 
            V_VOLANTES.CLASE IN( 3,5) 
        AND 
        V_VOLANTES.ID_DE_PROCESO = s$proceso$s
            AND 
        V_VOLANTES.ANO = s$anio$s
            AND 
        V_VOLANTES.MES = s$mes$s
            AND 
        V_VOLANTES.PERIODO = s$periodo$s
s$CONDADICIONAL$s
ORDER BY 
    ID_Centro_de_Costo,
    NOMBRECOMPLETO, 
    ID_DE_EMPLEADO, 
    CLASE, 
    ID_DE_CONCEPTO]') CONSULTA, 6 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);