SELECT PERSONAL.ID_DE_EMPLEADO, 
	     PERSONAL.NOMBRECOMPLETO  NOMCOMPLETO, 
	     PERSONAL.NUMERO_DCTO,
	     MIN(V_FONDO_DE_PENSION_VOL.ID_DEL_FONDO) KEEP (DENSE_RANK FIRST ORDER BY ROWNUM) FONDO_PENSION_VOL, 
	     MIN(V_FONDO_DE_PENSION_VOL.NIT) KEEP (DENSE_RANK FIRST ORDER BY ROWNUM) NIT, 
	     MIN(V_FONDO_DE_PENSION_VOL.NOMBRE_DEL_FONDO) KEEP (DENSE_RANK FIRST ORDER BY ROWNUM) NOMBRE_DEL_FONDO, 
	     MIN(HISTORICOS.ID_DE_CONCEPTO) KEEP (DENSE_RANK FIRST ORDER BY ROWNUM) PRIMERODEID_DE_CONCEPTO,
	     SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = 112 THEN VALOR ELSE 0 END)  IBC, 
	     SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = 124 THEN VALOR ELSE 0 END)  AVP, 
	     SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = 124 THEN VALOR ELSE 0 END) + 
	     SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = 127 THEN VALOR ELSE 0 END)  AVP1, 
	     ROUND(SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = 302 THEN VALOR ELSE 0 END) / 
	    	     (SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = 124 THEN VALOR ELSE 0 END) + 
	            SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = 127 THEN VALOR ELSE 0 END)
             ) * 
	    	     SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = 124 THEN VALOR ELSE 0 END), 0)  BEN_TRB,
	     MIN(PERSONAL.CUENTA_VIVIENDA) KEEP (DENSE_RANK FIRST ORDER BY ROWNUM) CUENTA_VIVIENDA,
	     HISTORICOS.ID_DE_PROCESO, 
	     HISTORICOS.ANO, 
	     HISTORICOS.MES 
FROM HISTORICOS INNER JOIN PERSONAL 
  ON HISTORICOS.COMPANIA 	    = PERSONAL.COMPANIA 
 AND HISTORICOS.ID_DE_EMPLEADO = PERSONAL.ID_DE_EMPLEADO 
INNER JOIN V_FONDO_DE_PENSION_VOL 
   ON PERSONAL.COMPANIA 	        = V_FONDO_DE_PENSION_VOL.COMPANIA  
  AND PERSONAL.FONDO_PENSION_VOL 	= V_FONDO_DE_PENSION_VOL.ID_DEL_FONDO 
WHERE HISTORICOS.COMPANIA 		  = s$compania$s
 AND  HISTORICOS.ID_DE_PROCESO  = s$procesoNomina$s
 AND  HISTORICOS.ANO            = s$anioNomina$s
 AND  HISTORICOS.MES            = s$mesNomina$s
 AND  HISTORICOS.ID_DE_CONCEPTO IN (112, 124, 302,127) 
 AND  PERSONAL.ID_DE_EMPLEADO   <> 0 
GROUP BY PERSONAL.ID_DE_EMPLEADO, 
         PERSONAL.NUMERO_DCTO, 
         PERSONAL.NOMBRECOMPLETO, 
         HISTORICOS.ID_DE_PROCESO, 
         HISTORICOS.ANO, 
         HISTORICOS.MES  
 HAVING  SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = 124 THEN VALOR ELSE 0 END) > 0
