SELECT 
   HISTORICOS.ID_DE_PROCESO, 
   HISTORICOS.ANO, 
   HISTORICOS.MES, 
   HISTORICOS.PERIODO, 
   SUM(HISTORICOS.VALOR)  SUMADEVALOR, 
   CONCEPTOS.NOMBRE_CONCEPTO,
   CONCEPTOS.NITCONCEPTO
FROM HISTORICOS INNER JOIN CONCEPTOS 
 ON  HISTORICOS.COMPANIA       = CONCEPTOS.COMPANIA 
 AND HISTORICOS.ID_DE_CONCEPTO = CONCEPTOS.ID_DE_CONCEPTO 
 INNER JOIN V_ACUMULADOS 
 ON HISTORICOS.COMPANIA = V_ACUMULADOS.COMPANIA
AND HISTORICOS.ID_DE_PROCESO = V_ACUMULADOS.ID_DE_PROCESO 
AND HISTORICOS.ANO = V_ACUMULADOS.ANO
AND HISTORICOS.MES = V_ACUMULADOS.MES
AND HISTORICOS.PERIODO = V_ACUMULADOS.PERIODO
AND HISTORICOS.ID_DE_EMPLEADO = V_ACUMULADOS.ID_DE_EMPLEADO
AND HISTORICOS.ID_DE_CONCEPTO = V_ACUMULADOS.ID_DE_CONCEPTO
WHERE HISTORICOS.COMPANIA		= s$compania$s
  AND HISTORICOS.ID_DE_PROCESO  = s$procesoNomina$s
  AND HISTORICOS.ANO            = s$anioNomina$s
  AND HISTORICOS.MES            = s$mesNomina$s
  AND HISTORICOS.PERIODO        = s$periodoNomina$s
  AND HISTORICOS.ID_DE_CONCEPTO BETWEEN 600 AND 698 
GROUP BY 
   HISTORICOS.ID_DE_PROCESO, 
   HISTORICOS.ANO, 
   HISTORICOS.MES, 
   HISTORICOS.PERIODO, 
   CONCEPTOS.NOMBRE_CONCEPTO,
   CONCEPTOS.NITCONCEPTO
ORDER BY 
   CONCEPTOS.NOMBRE_CONCEPTO
