SELECT    
  PERSONAL.NOMBRECOMPLETO,   
  PERSONAL.NUMERO_DCTO,   
  PERSONAL.FECHA_VEN_SUPERVIVIENCIA,   
  PERSONAL.FECHA_SUPERVIVIENCIA   
  FROM    PERSONAL  
  WHERE   PERSONAL.COMPANIA = s$compania$s  
    AND   (PERSONAL.FECHA_SUPERVIVIENCIA BETWEEN s$rangoInicial$s AND LAST_DAY(s$rangoInicial$s) 
	 OR  PERSONAL.FECHA_VEN_SUPERVIVIENCIA BETWEEN s$rangoInicial$s AND LAST_DAY(s$rangoInicial$s))   
  ORDER BY PERSONAL.FECHA_VEN_SUPERVIVIENCIA, PERSONAL.FECHA_SUPERVIVIENCIA
