MERGE INTO CONSULTAS FIN USING (SELECT '000002ListadoFactoresPrestaciones' INFORME ,TO_CLOB(q'[SELECT ID_DE_CONCEPTO,  
    NOMBRE_CONCEPTO,  
    (CASE WHEN FACTOR_CESANTIAS NOT IN(0) 
          THEN 'X' 
          ELSE  ' ' 
    END) FACTOR_CESANTIAS,  
    (CASE WHEN FACTOR_CESANTIASCONSOLIDADAS NOT IN(0) 
          THEN 'X' 
          ELSE ' '
    END) FACTOR_CESANTIASCONSOLIDADAS,  
    (CASE WHEN FACTOR_PRIMAJUNIO NOT IN(0) 
          THEN 'X' 
          ELSE ' ' 
    END) FACTOR_PRIMAJUNIO,  
    (CASE WHEN FACTOR_PRIMANAVIDAD NOT IN(0) 
          THEN 'X' 
          ELSE ' ' 
    END) FACTOR_PRIMANAVIDAD,  
    (CASE WHEN FACTOR_VACACIONES NOT IN(0) 
          THEN 'X' 
          ELSE ' ' 
    END) FACTOR_VACACIONES,  
    (CASE WHEN FACTOR_PRIMAVACACIONES NOT IN(0) 
          THEN 'X' 
          ELSE  ' ' 
    END) FACTOR_PRIMAVACACIONES,  
    (CASE WHEN FACTOR_PRIMAANTIGUEDAD NOT IN(0) 
          THEN 'X' 
          ELSE ' ' 
    END) FACTOR_PRIMAANTIGUEDAD
FROM CONCEPTOS  
WHERE COMPANIA = s$compania$s 
AND (FACTOR_CESANTIAS NOT IN(0) 
    OR FACTOR_CESANTIASCONSOLIDADAS NOT IN(0) 
    OR FACTOR_PRIMAJUNIO NOT IN(0) 
    OR FACTOR_PRIMANAVIDAD NOT IN(0) 
    OR FACTOR_VACACIONES NOT IN(0) 
    OR FACTOR_PRIMAVACACIONES NOT IN(0) 
    OR FACTOR_PRIMAANTIGUEDAD NOT IN(0))]') CONSULTA, 6 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);