SELECT 
  PERSONAL.NOMBRECOMPLETO, 
  CARGOS.NOMBRE_DEL_CARGO 
 FROM PERSONAL 
  INNER JOIN CARGOS ON PERSONAL.COMPANIA = CARGOS.COMPANIA AND PERSONAL.ID_DE_CARGO = CARGOS.ID_DE_CARGO 
 WHERE PERSONAL.COMPANIA= s$compania$s
  AND PERSONAL.ID_DE_EMPLEADO = s$idEmpleado$s
