SELECT V_VOLANTES.COMPANIA, V_VOLANTES.ID_DE_PROCESO, V_VOLANTES.ANO, V_VOLANTES.MES, V_VOLANTES.PERIODO,  V_VOLANTES.CLASE, V_VOLANTES.ID_DE_EMPLEADO, 
V_VOLANTES.ID_DE_CONCEPTO, V_VOLANTES.NOMBRE_CONCEPTO, V_VOLANTES.DEVENGOS,  V_VOLANTES.DESCUENTOS, CASE WHEN V_VOLANTES.CANTIDAD IS NULL THEN ' ' ELSE TO_CHAR(V_VOLANTES.CANTIDAD) END CANTIDAD
FROM   V_VOLANTES
WHERE  V_VOLANTES.COMPANIA = $P{PR_COMPANIA} 
  AND  V_VOLANTES.ID_DE_PROCESO = $P{PR_ID_DE_PROCESO} 
  AND  V_VOLANTES.ANO = $P{PR_ANO} 
  AND  V_VOLANTES.MES = $P{PR_MES} 
  AND  V_VOLANTES.PERIODO = $P{PR_PERIODO} 
   AND V_VOLANTES.ID_DE_EMPLEADO = $P{PR_ID_DE_EMPLEADO}
   AND V_VOLANTES.CLASE IN(3,5)
  ORDER BY V_VOLANTES.CLASE, ID_DE_CONCEPTO	
