SELECT DISTINCT
        PERSONAL.NOMBRECOMPLETO AS NOMCOMPLETO, 
        PERSONAL.ID_DE_EMPLEADO, 
        PERSONAL.ESTADO_ACTUAL,
        V_CAJA_COMPENSACION.CAJA_COMPENSACION AS IDFONDO,
        V_CAJA_COMPENSACION.NIT, 
        V_CAJA_COMPENSACION.NOMBRE_CAJA AS NOMBREFONDO,
        PERSONAL.NUMERO_DCTO, 
        PERSONAL.FECHACAJACOMPENSACION AS FECHAFONDO
   FROM PERSONAL 
   LEFT JOIN V_CAJA_COMPENSACION ON 
   PERSONAL.CAJA_COMPENSACION = V_CAJA_COMPENSACION.CAJA_COMPENSACION AND 
   PERSONAL.COMPANIA = V_CAJA_COMPENSACION.COMPANIA
   WHERE PERSONAL.ID_DE_EMPLEADO NOT IN (0)
   AND PERSONAL.ESTADO_ACTUAL NOT IN (3)
   AND PERSONAL.COMPANIA= s$compania$s
