SELECT DISTINCT 
        PERSONAL.NOMBRECOMPLETO AS NOMCOMPLETO, 
        PERSONAL.ID_DE_EMPLEADO, 
        PERSONAL.ESTADO_ACTUAL, 
        V_FONDO_DE_PENSION_AFC.FONDO_AFC AS IDFONDO, 
        V_FONDO_DE_PENSION_AFC.NOMBRE_FONDO_AFC AS NOMBREFONDO,
        V_FONDO_DE_PENSION_AFC.NIT, 
        PERSONAL.NUMERO_DCTO, 
        PERSONAL.FECHA_AFC AS FECHAFONDO
   FROM PERSONAL 
   LEFT JOIN V_FONDO_DE_PENSION_AFC ON 
   PERSONAL.FONDO_AFC = V_FONDO_DE_PENSION_AFC.FONDO_AFC AND 
   PERSONAL.COMPANIA = V_FONDO_DE_PENSION_AFC.COMPANIA
   WHERE PERSONAL.ID_DE_EMPLEADO NOT IN (0)
     AND PERSONAL.ESTADO_ACTUAL NOT IN (3)
     AND PERSONAL.COMPANIA= s$compania$s
