SELECT Trim(PERSONAL.NOMBRECOMPLETO) AS NOMBRECOMPLETO,
	PERSONAL.NUMERO_DCTO,
	RETEFUENTE_CALCULOS.COMPANIA,
	RETEFUENTE_CALCULOS.ID_DE_PROCESO,
	RETEFUENTE_CALCULOS.ANO,
	RETEFUENTE_CALCULOS.MES,
	CASE WHEN PERSONAL.PROCESORETENCION = 1 AND RETEFUENTE_CALCULOS.PERIODO = 4 THEN RETEFUENTE_CALCULOS.PERIODO ELSE 3 END PERIODO ,
	RETEFUENTE_CALCULOS.ID_DE_EMPLEADO,
	RETEFUENTE_CALCULOS.ID,
	CASE RETEFUENTE_CALCULOS.DECLARANTES384 WHEN -1 THEN 'Si' ELSE 'No' END AS DECLARANTES384,
	RETEFUENTE_CALCULOS.VALOR_UVT,
	RETEFUENTE_CALCULOS.ART_APLICADO,
	RETEFUENTE_CALCULOS.PORCENTAJE_APLICADO ,

	SUM(RETEFUENTE_CALCULOS.PAGOS_BRUTOS) PAGOS_BRUTOS,
	SUM(RETEFUENTE_CALCULOS.OTROS_PAGOS) OTROS_PAGOS,
	SUM(RETEFUENTE_CALCULOS.VALOR_PRIMA_NAVIDAD) VALOR_PRIMA_NAVIDAD,
	SUM(RETEFUENTE_CALCULOS.TOTAL_PAGOS) TOTAL_PAGOS,
	SUM(RETEFUENTE_CALCULOS.NG_1_1_ALIMENTACION) NG_1_1_ALIMENTACION,
	SUM(RETEFUENTE_CALCULOS.NG_1_2_TRANSPORTE) NG_1_2_TRANSPORTE,
	SUM(RETEFUENTE_CALCULOS.NG_1_3_VIATICOS) NG_1_3_VIATICOS,
	SUM(RETEFUENTE_CALCULOS.NG_1_4_OTROS) NG_1_4_OTROS,
	SUM(RETEFUENTE_CALCULOS.DED_2_1_VIIVENDA) DED_2_1_VIIVENDA,
	SUM(RETEFUENTE_CALCULOS.DED_2_2_MEDICINA) DED_2_2_MEDICINA,
	SUM(RETEFUENTE_CALCULOS.DED_2_3_PERSONASACARGO) DED_2_3_PERSONASACARGO,
	SUM(RETEFUENTE_CALCULOS.DED_2_4_PROMEDIOSALUD) DED_2_4_PROMEDIOSALUD,
	SUM(RETEFUENTE_CALCULOS.DED_2_5_TOTAL_DEDUCIBLES) DED_2_5_TOTAL_DEDUCIBLES,
	SUM(RETEFUENTE_CALCULOS.DED_3_1_PENSIONYFSP) DED_3_1_PENSIONYFSP,
	SUM(RETEFUENTE_CALCULOS.DED_3_2_AP_VOL_PENSION) DED_3_2_AP_VOL_PENSION,
	SUM(RETEFUENTE_CALCULOS.DED_3_3_AP_VOL_AFC) DED_3_3_AP_VOL_AFC,
	SUM(RETEFUENTE_CALCULOS.DED_3_4_INDEMNIZACIONES) DED_3_4_INDEMNIZACIONES,
	SUM(DED_3_1_PENSIONYFSP + DED_3_3_AP_VOL_AFC + DED_3_4_INDEMNIZACIONES + DED_3_5_INTCESANTIAS + DED_3_2_AP_VOL_PENSION) AS TOTAL_RENTAS_EXENTAS,
	
	SUM(RETEFUENTE_CALCULOS.DED_3_5_INTCESANTIAS) DED_3_5_INTCESANTIAS,
	SUM(RETEFUENTE_CALCULOS.DED_3_6_TOTAL_DEDUCCIONES) DED_3_6_TOTAL_DEDUCCIONES,
	SUM(RETEFUENTE_CALCULOS.SUBTOTAL) SUBTOTAL,
	SUM(RETEFUENTE_CALCULOS.SUBTOTAL2) SUBTOTAL2,
	SUM(RETEFUENTE_CALCULOS.DED_4_25_EXENTO) DED_4_25_EXENTO,
	SUM(RETEFUENTE_CALCULOS.BASE_GRAVABLE) BASE_GRAVABLE,
	
	SUM(RETEFUENTE_CALCULOS.RETENCION_APLICADA) RETENCION_APLICADA,
	SUM(RETEFUENTE_CALCULOS.MENOS_SS_384) MENOS_SS_384,
	SUM(RETEFUENTE_CALCULOS.SUBTOTAL1_384) SUBTOTAL1_384,
	SUM(RETEFUENTE_CALCULOS.PROMEDIO_UVT) PROMEDIO_UVT,
	SUM(RETEFUENTE_CALCULOS.TOTAL_UVT) TOTAL_UVT,
	SUM(RETEFUENTE_CALCULOS.RETENCION_MINIMIA384) RETENCION_MINIMIA384,
	SUM(RETEFUENTE_CALCULOS.RETE383) RETE383,	
	SUM(RETEFUENTE_CALCULOS.BASE1_DEPURACION) BASE1_DEPURACION,
	SUM(RETEFUENTE_CALCULOS.BASE2_MINIMA60) BASE2_MINIMA60,
	SUM(RETEFUENTE_CALCULOS.BASE3_LIMINTE420) BASE3_LIMINTE420,
	SUM(RETEFUENTE_CALCULOS.BASE4_SUMA_DEDYRENTAS) BASE4_SUMA_DEDYRENTAS,
	SUM(RETEFUENTE_CALCULOS.BASE5_LIMITE40) BASE5_LIMITE40,  
	SUM(RETEFUENTE_CALCULOS.BASE6_DIFERENCIA) BASE6_DIFERENCIA
	
FROM RETEFUENTE_CALCULOS
LEFT JOIN personal
ON RETEFUENTE_CALCULOS.COMPANIA                = personal.COMPANIA
AND RETEFUENTE_CALCULOS.ID_DE_EMPLEADO  = personal.ID_DE_EMPLEADO
WHERE RETEFUENTE_CALCULOS.COMPANIA        = s$compania$s
AND RETEFUENTE_CALCULOS.ID_DE_PROCESO  = s$proceso$s
AND RETEFUENTE_CALCULOS.ANO                       = s$ano1$s
AND RETEFUENTE_CALCULOS.MES                       = s$mes1$s
AND RETEFUENTE_CALCULOS.RETENCION_APLICADA NOT IN (0)
s$CONDTODOS$s

GROUP BY Trim(PERSONAL.NOMBRECOMPLETO) ,
	PERSONAL.NUMERO_DCTO,
	RETEFUENTE_CALCULOS.COMPANIA,
	RETEFUENTE_CALCULOS.ID_DE_PROCESO,
	RETEFUENTE_CALCULOS.ANO,
	RETEFUENTE_CALCULOS.MES,
	CASE WHEN PERSONAL.PROCESORETENCION = 1 AND RETEFUENTE_CALCULOS.PERIODO = 4 THEN RETEFUENTE_CALCULOS.PERIODO ELSE 3 END ,
	RETEFUENTE_CALCULOS.ID_DE_EMPLEADO,
	RETEFUENTE_CALCULOS.ID,
	CASE RETEFUENTE_CALCULOS.DECLARANTES384 WHEN -1 THEN 'Si' ELSE 'No' END ,
	RETEFUENTE_CALCULOS.VALOR_UVT,
	RETEFUENTE_CALCULOS.ART_APLICADO,
	RETEFUENTE_CALCULOS.PORCENTAJE_APLICADO

ORDER BY RETEFUENTE_CALCULOS.COMPANIA,
  RETEFUENTE_CALCULOS.ID_DE_PROCESO,
  RETEFUENTE_CALCULOS.ANO,
  RETEFUENTE_CALCULOS.MES
