MERGE INTO CONSULTAS FIN USING (SELECT '000187ListadoBANB' INFORME ,TO_CLOB(q'[SELECT DISTINCT PERSONAL.NOMBRECOMPLETO NOMBRECOMP,
  PERSONAL.NUMERO_DCTO,
  PERSONAL.FECHA_DE_INGRESO,
  PERSONAL.INGRESO_DISTRITO,
  PERSONAL.ID_CENTRO_DE_COSTO,
  PERSONAL.ID_DE_CARGO,
  PERSONAL.ESCALAFON,
  PERSONAL.ID_DE_CATEGORIA,
  PERSONAL.DEPENDENCIA,
  PERSONAL.FECHAQUINQUENIO,
  PERSONAL.ACTOQUINQUENIO,
  PERSONAL.FECHADELACTOQUINQUENIO,
  CATEGORIA.SALARIO_BASE,
  CARGOS.NOMBRE_DEL_CARGO,
  DEPENDENCIA.NOMBRE,
  CENTRO_COSTO.NOMBRE NOMBRE_CENTRO_DE_COSTO,
  PERSONAL.COMPANIA,
  PCK_SYSMAN_UTL.FC_STRZERO(TO_CHAR(TRUNC(PERSONAL.FECHA_CUMPLIMIENTO_BONIFICACIO),'MM'),2) AN,
  PERSONAL.FECHA_CUMPLIMIENTO_BONIFICACIO
FROM PERSONAL
LEFT JOIN CATEGORIA
ON PERSONAL.COMPANIA         = CATEGORIA.COMPANIA
AND PERSONAL.ESCALAFON       = CATEGORIA.ESCALAFON
AND PERSONAL.ID_DE_CATEGORIA = CATEGORIA.ID_DE_CATEGORIA
LEFT JOIN DEPENDENCIA
ON PERSONAL.COMPANIA     = DEPENDENCIA.COMPANIA
AND PERSONAL.DEPENDENCIA = DEPENDENCIA.CODIGO
LEFT JOIN CARGOS
ON PERSONAL.COMPANIA     = CARGOS.COMPANIA
AND PERSONAL.ID_DE_CARGO = CARGOS.ID_DE_CARGO
LEFT JOIN CENTRO_COSTO
ON PERSONAL.COMPANIA                                                                           = CENTRO_COSTO.COMPANIA
AND PERSONAL.ID_CENTRO_DE_COSTO                                                                = CENTRO_COSTO.CODIGO
AND PERSONAL.ANO                                                                               = CENTRO_COSTO.ANO
WHERE PERSONAL.COMPANIA                                                                       IN (s$compania$s)
AND PCK_SYSMAN_UTL.FC_STRZERO(TO_CHAR(TRUNC(PERSONAL.FECHA_CUMPLIMIENTO_BONIFICACIO),'MM'),2) IN (s$mes1$s)
AND PERSONAL.ID_DE_EMPLEADO NOT                                                               IN (0)
AND PERSONAL.ESTADO_ACTUAL NOT                                                                IN (3,2)
AND CATEGORIA.ANO IN (s$anio$s)
AND EXTRACT (YEAR FROM PERSONAL.FECHA_CUMPLIMIENTO_BONIFICACIO) NOT                           IN (s$anio$s)
ORDER BY 1]') CONSULTA, 6 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);