MERGE INTO CONSULTAS FIN USING ( SELECT '000167PagoCajasCompensacionmensual' AS INFORME_VAL, TO_CLOB(q'[SELECT 
        PCK_SYSMAN_UTL.FC_NOMBRE_MES(TO_CHAR(SYSDATE,'MM')) MES_ACTUAL, 
        TO_CHAR(SYSDATE,'DD') DIA_ACTUAL, 
        TO_CHAR(SYSDATE,'YYYY') ANIO_ACTUAL, 
        CAJA_COMPENSACION, 
        NIT, 
        NOMBRE_CAJA, 
        COMPANIA, 
        ID_DE_PROCESO, 
        ANO,
        MES, 
        PERIODO, 
        NOMBRE_CONCEPTO, 
        APORTE, 
        APORTE_ICBF,
        APORTE_SENA, 
        APORTE_ESAP, 
        APORTE_INSTITUTOS,
        BASE_PARAFISCAL, 
        TRANSPORTE, 
        TOTAL,
        SUMA, 
        ID_DE_CONCEPTO, 
        REGIMEN,
        BASE_PARAFISCAL2,
        CASE WHEN (TOTAL-SUMA<>0) THEN 'R' ELSE '' END AS DIFERENCIA FROM (
                SELECT V_CAJA_COMPENSACION.CAJA_COMPENSACION, 
                V_CAJA_COMPENSACION.NIT, 
                V_CAJA_COMPENSACION.NOMBRE_CAJA, 
                HISTORICOS.COMPANIA, 
                HISTORICOS.ID_DE_PROCESO, 
                HISTORICOS.ANO,
                HISTORICOS.MES, 
                HISTORICOS.PERIODO, 
                MAX(CONCEPTOS.NOMBRE_CONCEPTO) KEEP (DENSE_RANK LAST ORDER BY ROWNUM) AS NOMBRE_CONCEPTO, 
                SUM(CASE HISTORICOS.ID_DE_CONCEPTO WHEN 101 THEN HISTORICOS.VALOR ELSE 0 END) AS APORTE, 
                SUM(CASE HISTORICOS.ID_DE_CONCEPTO WHEN 102 THEN HISTORICOS.VALOR ELSE 0 END) AS APORTE_ICBF,
                SUM(CASE HISTORICOS.ID_DE_CONCEPTO WHEN 103 THEN HISTORICOS.VALOR ELSE 0 END) AS APORTE_SENA, 
                SUM(CASE HISTORICOS.ID_DE_CONCEPTO WHEN 104 THEN HISTORICOS.VALOR ELSE 0 END) AS  APORTE_ESAP, 
                SUM(CASE HISTORICOS.ID_DE_CONCEPTO WHEN 105 THEN HISTORICOS.VALOR ELSE 0 END) AS  APORTE_INSTITUTOS,
                SUM(CASE HISTORICOS.ID_DE_CONCEPTO WHEN 108 THEN HISTORICOS.VALOR ELSE 0 END) AS BASE_PARAFISCAL, 
                s$CAMPOTRANSPORTE$s 
                PCK_SYSMAN_UTL.FC_ROUND((SUM(CASE HISTORICOS.ID_DE_CONCEPTO WHEN 108 THEN HISTORICOS.VALOR ELSE 0 END))*9/100,0) AS TOTAL,
                SUM(CASE HISTORICOS.ID_DE_CONCEPTO WHEN 101 THEN HISTORICOS.VALOR ELSE 0 END) + SUM(CASE HISTORICOS.ID_DE_CONCEPTO WHEN 102 THEN HISTORICOS.VALOR ELSE 0 END) + SUM(CASE HISTORICOS.ID_DE_CONCEPTO WHEN 103 THEN HISTORICOS.VALOR ELSE 0 END) + SUM(CASE HISTORICOS.ID_DE_CONCEPTO WHEN 104 THEN HISTORICOS.VALOR ELSE 0 END) + SUM(CASE HISTORICOS.ID_DE_CONCEPTO WHEN 105 THEN HISTORICOS.VALOR ELSE 0 END) AS SUMA,
                MAX(HISTORICOS.ID_DE_CONCEPTO) KEEP (DENSE_RANK LAST ORDER BY ROWNUM) AS ID_DE_CONCEPTO, 
                MAX(CASE PERSONAL.ID_DE_TIPO WHEN '02' THEN 'INTEGRAL' ELSE (CASE PERSONAL.REGIMEN WHEN 1 THEN 'RETROACTIVAS' ELSE 'LEY 50' END) END) KEEP (DENSE_RANK LAST ORDER BY ROWNUM) AS REGIMEN,
                s$CAMPOPARAFISCAL2$s
                FROM ((HISTORICOS LEFT JOIN PERSONAL ON 
                (HISTORICOS.COMPANIA = PERSONAL.COMPANIA) AND 
                (HISTORICOS.ID_DE_EMPLEADO = PERSONAL.ID_DE_EMPLEADO)) LEFT JOIN 
                V_CAJA_COMPENSACION ON 
                (PERS]') || TO_CLOB(q'[ONAL.COMPANIA = V_CAJA_COMPENSACION.COMPANIA) AND 
                (PERSONAL.CAJA_COMPENSACION = V_CAJA_COMPENSACION.CAJA_COMPENSACION)) LEFT JOIN 
                CONCEPTOS ON 
                (HISTORICOS.ID_DE_CONCEPTO = CONCEPTOS.ID_DE_CONCEPTO) AND 
                (HISTORICOS.COMPANIA = CONCEPTOS.COMPANIA)
                WHERE 
                HISTORICOS.COMPANIA= s$compania$s 
                AND HISTORICOS.ID_DE_PROCESO= s$proceso$s 
                AND HISTORICOS.ANO= s$ano1$s 
                AND HISTORICOS.MES= s$mes1$s 
                 s$CONDPERIODO$s  
                 s$COND$s 
                GROUP BY V_CAJA_COMPENSACION.CAJA_COMPENSACION, 
                V_CAJA_COMPENSACION.NIT, 
                V_CAJA_COMPENSACION.NOMBRE_CAJA,
                HISTORICOS.COMPANIA, 
                HISTORICOS.ID_DE_PROCESO, 
                HISTORICOS.ANO, 
                HISTORICOS.MES, 
                HISTORICOS.PERIODO, 
                PERSONAL.ID_CENTRO_DE_COSTO)  ]') AS CONSULTA_VAL, 6 AS APLICACION_VAL, TO_CLOB(q'[]') AS CONSULTA_OPCIONAL_VAL, (SELECT MIN(ROWID) FROM CONSULTAS WHERE INFORME = '000167PagoCajasCompensacionmensual') AS RID_DESTINO  FROM DUAL ) INI ON (FIN.ROWID = INI.RID_DESTINO)  WHEN MATCHED THEN   UPDATE SET FIN.CONSULTA = INI.CONSULTA_VAL, FIN.APLICACION = INI.APLICACION_VAL, FIN.CONSULTA_OPCIONAL = INI.CONSULTA_OPCIONAL_VAL, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN   INSERT (INFORME, CONSULTA, APLICACION, CONSULTA_OPCIONAL, DATE_CREATED)   VALUES (INI.INFORME_VAL, INI.CONSULTA_VAL, INI.APLICACION_VAL, INI.CONSULTA_OPCIONAL_VAL, SYSDATE);