SELECT VACACIONES.COMPANIA, 
    PERSONAL.NOMBRECOMPLETO, 
    VACACIONES.ID_DE_PROCESO, 
    VACACIONES.ANO, 
    VACACIONES.MES, 
    VACACIONES.PERIODO, 
    VACACIONES.ID_DE_EMPLEADO, 
    VACACIONES.ID_DE_CONCEPTO, 
    VACACIONES.FECHA_INICIO, 
    VACACIONES.FECHA_FINAL, 
    VACACIONES.INICIO_DISFRUTE, 
    VACACIONES.FINAL_DISFRUTE, 
    VACACIONES.ACTO, 
    VACACIONES.FECHA_ACTO,
    VACACIONES.DIAS, 
    CASE WHEN   VACACIONES.ENDINERO <> 0 THEN 'x' ELSE ' 'END ENDINERO,  
    VACACIONES.FECHAPAGO, 
    VACACIONES.DIASHABILES, 
    VACACIONES.NUMPERIODOS, 
    VACACIONES.INDRTVAC, 
    VACACIONES.FECHARTVAC, 
    VACACIONES.DIASRTVAC,
    VACACIONES.F_PAGORTVAC, 
    VACACIONES.DIASDINERO, 
    VACACIONES.DIASPENDIENTESDEDISFRUTE
FROM VACACIONES LEFT JOIN PERSONAL ON 
    VACACIONES.COMPANIA 	  = PERSONAL.COMPANIA 
    AND VACACIONES.ID_DE_EMPLEADO = PERSONAL.ID_DE_EMPLEADO
WHERE VACACIONES.COMPANIA=s$compania$s
ORDER BY PERSONAL.NOMBRECOMPLETO, VACACIONES.FECHA_INICIO
