SELECT 
   SUM(CASE WHEN H.ID_DE_CONCEPTO = 499
   	        THEN H.VALOR 
   	        ELSE 0
   	   END) PROVCESANTIAS
  ,SUM(CASE WHEN H.ID_DE_CONCEPTO = 002
  	        THEN H.VALOR
  	        ELSE 0
  	   END) SUELDO
  ,H.ID_DE_EMPLEADO
  ,P.NOMBRECOMPLETO
  ,P.NUMERO_DCTO
  ,H.ID_DE_PROCESO
  ,H.MES
  ,PCK_SYSMAN_UTL.FC_NOMBRE_MES(H.MES) NOMBREMES
  ,SUM(CASE WHEN H.ID_DE_CONCEPTO = 496
  	        THEN H.VALOR
  	        ELSE 0
  	   END) PROVINTCESANTIAS 
FROM PERSONAL P
  INNER JOIN HISTORICOS H
     ON P.COMPANIA       = H.COMPANIA 
    AND P.ID_DE_EMPLEADO = H.ID_DE_EMPLEADO
    AND P.ANO            = H.ANO
WHERE H.COMPANIA      =  s$compania$s
  AND H.ID_DE_PROCESO = s$idProceso$s
  AND H.ID_DE_CONCEPTO IN (499,496,002) 
  AND H.ANO     BETWEEN s$anioInicial$s AND s$anioFinal$s
  AND H.MES     BETWEEN s$mesInicial$s  AND s$mesFinal$s
  AND H.PERIODO BETWEEN s$perInicial$s  AND s$perFinal$s
GROUP BY 
   H.ID_DE_EMPLEADO
  ,P.NOMBRECOMPLETO
  ,P.NUMERO_DCTO
  ,H.ID_DE_PROCESO
  ,H.MES
  ,PCK_SYSMAN_UTL.FC_NOMBRE_MES(H.MES)
HAVING 
  SUM(CASE WHEN H.ID_DE_CONCEPTO = 499
           THEN H.VALOR
           ELSE 0
      END) <> 0 
  AND 
  SUM(CASE WHEN H.ID_DE_CONCEPTO = 002
  	       THEN H.VALOR
  	       ELSE 0
  	  END) <> 0
