MERGE INTO CONSULTAS FIN USING (SELECT '000403ListadoRteFteMes' INFORME ,TO_CLOB(q'[SELECT 
      PERSONAL_HISTORICO.ID_DE_EMPLEADO EMPLEADO, 
      PERSONAL_HISTORICO.NOMBRECOMPLETO NOMBRECOMPLETO, 
      PERSONAL_HISTORICO.NUMERO_DCTO NUMERODCTO, 
      HISTORICOS.ANO,
      HISTORICOS.MES,
      SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = '097' THEN VALOR ELSE 0 END) DEVENGADO, 
      SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = '110' THEN VALOR ELSE 0 END) BASERETENCION, 
      SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = '125' THEN VALOR ELSE 0 END) RETENCION, 
      SUM(HISTORICOS.VALOR) ACUMRTEFTE, 
      SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = '302' THEN VALOR ELSE 0 END) BENEFICIOT
FROM PERSONAL_HISTORICO
LEFT JOIN HISTORICOS  
  ON  PERSONAL_HISTORICO.COMPANIA = HISTORICOS.COMPANIA   
  AND PERSONAL_HISTORICO.ID_DE_PROCESO = HISTORICOS.ID_DE_PROCESO
  AND PERSONAL_HISTORICO.ANO = HISTORICOS.ANO
  AND PERSONAL_HISTORICO.MES = HISTORICOS.MES
  AND PERSONAL_HISTORICO.PERIODO = HISTORICOS.PERIODO
  AND PERSONAL_HISTORICO.ID_DE_EMPLEADO = HISTORICOS.ID_DE_EMPLEADO 
WHERE HISTORICOS.COMPANIA = s$compania$s
  AND HISTORICOS.ID_DE_CONCEPTO IN('125','097','302','110')
  AND HISTORICOS.ANO = s$anioNomina$s 
  AND HISTORICOS.MES= s$mesNomina$s
GROUP BY PERSONAL_HISTORICO.ID_DE_EMPLEADO, 
         PERSONAL_HISTORICO.NOMBRECOMPLETO, 
         PERSONAL_HISTORICO.NUMERO_DCTO, 
         HISTORICOS.ANO,
         HISTORICOS.MES]') CONSULTA, 6 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);
