SELECT V_ACUMULADOS.COMPANIA PRIMERODECOMPANIA, 
       V_ACUMULADOS.ESCALAFON  ESCALAFON,
       V_ACUMULADOS.CLASE  CLASE, 
       V_ACUMULADOS.ID_DE_CONCEPTO ID_DE_CONCEPTO,
       V_ACUMULADOS.PERIODO PRIMERODEACUMULADO, 
       CONCEPTOS.FACTOR_CESANTIASCONSOLIDADAS FACTOR_CESANTIASCONSOLIDADAS,
       V_ACUMULADOS.FONDO_CESANTIAS,
       V_ACUMULADOS.NOMBRE_ESCALAFON  NOMBREESCALAFON,
       CLASE_NOMBRE_MAYU CLASECONCEPTO, 
       V_ACUMULADOS.NOMBRE_CONCEPTO  NOMBRE_CONCEPTO,
 SUM(V_ACUMULADOS.VALOR) SUMA_DE_VALOR
FROM V_ACUMULADOS 
	INNER JOIN CONCEPTOS 
	ON V_ACUMULADOS.ID_DE_CONCEPTO = CONCEPTOS.ID_DE_CONCEPTO
	AND V_ACUMULADOS.COMPANIA = CONCEPTOS.COMPANIA
WHERE V_ACUMULADOS.COMPANIA= s$compania$s
AND CONCEPTOS.CLASE IN (3,4,5,6,7,8)
AND CONCEPTOS.FACTOR_CESANTIASCONSOLIDADAS <> 0
AND V_ACUMULADOS.FONDO_CESANTIAS=  's$fondoCesantias$s'  
AND LPAD(V_ACUMULADOS.ID_DE_PROCESO, 2, 0) || LPAD(V_ACUMULADOS.ANO, 4, 0) || LPAD(V_ACUMULADOS.MES, 2, 0) || LPAD(V_ACUMULADOS.PERIODO, 2, 0) BETWEEN 's$fechaInicial$s'  AND 's$fechaFinal$s' 
GROUP BY 
V_ACUMULADOS.COMPANIA,
V_ACUMULADOS.ESCALAFON, 
V_ACUMULADOS.CLASE,
V_ACUMULADOS.ID_DE_CONCEPTO,
V_ACUMULADOS.PERIODO, 
CONCEPTOS.FACTOR_CESANTIASCONSOLIDADAS, 
V_ACUMULADOS.FONDO_CESANTIAS, 
V_ACUMULADOS.NOMBRE_ESCALAFON, 
CLASE_NOMBRE_MAYU,
V_ACUMULADOS.NOMBRE_CONCEPTO, 
V_ACUMULADOS.ESCALAFON,
V_ACUMULADOS.CLASE  
ORDER BY V_ACUMULADOS.ESCALAFON,
         V_ACUMULADOS.CLASE,
         V_ACUMULADOS.ID_DE_CONCEPTO
