SELECT 
    ESCALAFON, 
    ID_DE_CONCEPTO  ID_DE_CONCEPTO, 
    CLASE, 
    NOMBRE_ESCALAFON  NOMBREESCALAFON, 
    CLASE_NOMBRE_MAYU CLASECONCEPTO, 
    NOMBRE_CONCEPTO  NOMBRE_CONCEPTO, 
    SUM(V_ACUMULADOS.VALOR)  SUMA_DE_VALOR, 
    CASE WHEN V_ACUMULADOS.TIPOACTIVIDAD IS NULL THEN ' ' ELSE V_ACUMULADOS.TIPOACTIVIDAD END TIPOACTIVIDAD
FROM V_ACUMULADOS
WHERE V_ACUMULADOS.COMPANIA = s$compania$s
  AND V_ACUMULADOS.CLASE IN (3, 4, 5, 6, 7, 8)  
  AND (LPAD(ID_DE_PROCESO, 2, 0) || LPAD(V_ACUMULADOS.ANO, 4, 0) || LPAD(V_ACUMULADOS.MES,2, 0) || LPAD(V_ACUMULADOS.PERIODO, 2, 0) BETWEEN  's$fechaInicial$s'  AND 's$fechaFinal$s') 
  GROUP BY ESCALAFON,
  ID_DE_CONCEPTO,
  CLASE,
  NOMBRE_ESCALAFON,
  CLASE_NOMBRE_MAYU, 
  NOMBRE_CONCEPTO,
  V_ACUMULADOS.TIPOACTIVIDAD
