SELECT
  PERSONAL.NUMERO_DCTO,
  (PERSONAL.APELLIDO1 || ' ' || PERSONAL.APELLIDO2 || ' ' || PERSONAL.NOMBRES) NOMBRECOMPLETO,
  PERSONAL.CUENTA,
  BANCOS_NOMINA.BANCO,
  HISTORICOS.VALOR SUMADEVALOR,
    CASE
    WHEN PERSONAL.TIPOCUENTA IN ('A')
    THEN 'Ahorros'
    WHEN PERSONAL.TIPOCUENTA IN ('C')
    THEN 'Corriente'
    ELSE ''
  END TIPOCUENTA
FROM PERSONAL
  INNER JOIN BANCOS_NOMINA
     ON PERSONAL.BANCO             = BANCOS_NOMINA.BANCO
    AND PERSONAL.COMPANIA          = BANCOS_NOMINA.COMPANIA
  INNER JOIN HISTORICOS
     ON PERSONAL.COMPANIA          = HISTORICOS.COMPANIA
    AND PERSONAL.ID_DE_EMPLEADO    = HISTORICOS.ID_DE_EMPLEADO
WHERE HISTORICOS.COMPANIA      = s$compania$s 
  AND HISTORICOS.ID_DE_PROCESO = s$proceso$s 
  AND HISTORICOS.ANO           = s$anio$s 
  AND HISTORICOS.MES           = s$mes$s 
  AND HISTORICOS.PERIODO       = s$periodo$s 
  AND HISTORICOS.ID_DE_CONCEPTO IN (144)
  AND PERSONAL.BANCO IN ('0','00','98','99')
ORDER BY PERSONAL.CUENTA
