SELECT 
    HISTORICOS.ID_DE_EMPLEADO CODIGO,
    CENTRO_COSTO.CODIGO ID_CENTRO_DE_COSTO,
    CENTRO_COSTO.NOMBRE NOMBRE_CENTRO_DE_COSTO,
    MAX(HISTORICOS.ANO)       ANO,
    MAX(HISTORICOS.PERIODO)   PERIODO,
    MAX(PERSONAL.NOMBRECOMPLETO) NOM_EMPLEADO,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('009') THEN HISTORICOS.VALOR ELSE 0 END) C009,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('001') THEN HISTORICOS.VALOR ELSE 0 END) C001,
	SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('002') THEN HISTORICOS.VALOR ELSE 0 END) C002,
	SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('177') THEN HISTORICOS.VALOR ELSE 0 END) C177,
	SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('150') THEN HISTORICOS.VALOR ELSE 0 END) C150,
	SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('130') THEN HISTORICOS.VALOR ELSE 0 END) C130,
	SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('131') THEN HISTORICOS.VALOR ELSE 0 END) C131,
	SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('132') THEN HISTORICOS.VALOR ELSE 0 END) C132,
	SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('160') THEN HISTORICOS.VALOR ELSE 0 END) C160,
	SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('158') THEN HISTORICOS.VALOR ELSE 0 END) C158,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('151') THEN HISTORICOS.VALOR ELSE 0 END) C151,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('175') THEN HISTORICOS.VALOR ELSE 0 END) C175,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('174') THEN HISTORICOS.VALOR ELSE 0 END) C174,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('155') THEN HISTORICOS.VALOR ELSE 0 END) C155,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('362') THEN HISTORICOS.VALOR ELSE 0 END) C362,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('097') THEN HISTORICOS.VALOR ELSE 0 END) C097,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('125') THEN HISTORICOS.VALOR ELSE 0 END) C125,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('799') THEN HISTORICOS.VALOR ELSE 0 END) C799,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('140') THEN HISTORICOS.VALOR ELSE 0 END) C140,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('144') THEN HISTORICOS.VALOR ELSE 0 END) C144,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('699') THEN HISTORICOS.VALOR ELSE 0 END - 
        CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('637') THEN HISTORICOS.VALOR ELSE 0 END -
        CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('635') THEN HISTORICOS.VALOR ELSE 0 END + 
        CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('124') THEN HISTORICOS.VALOR ELSE 0 END +
        CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('127') THEN HISTORICOS.VALOR ELSE 0 END + 
        CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('120') THEN HISTORICOS.VALOR ELSE 0 END + 
        CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('123') THEN HISTORICOS.VALOR ELSE 0 END + 
        CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('224') THEN HISTORICOS.VALOR ELSE 0 END) TOTALDSTOS,
	SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('129') THEN HISTORICOS.VALOR ELSE 0 END + 
		CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('635') THEN HISTORICOS.VALOR ELSE 0 END)SINDICATO

FROM HISTORICOS
  INNER JOIN CONCEPTOS
    ON HISTORICOS.COMPANIA        = CONCEPTOS.COMPANIA 
    AND HISTORICOS.ID_DE_CONCEPTO = CONCEPTOS.ID_DE_CONCEPTO
  INNER JOIN PERIODOS
    ON HISTORICOS.COMPANIA        = PERIODOS.COMPANIA
    AND HISTORICOS.ID_DE_PROCESO  = PERIODOS.ID_DE_PROCESO
    AND HISTORICOS.ANO            = PERIODOS.ANO
    AND HISTORICOS.MES            = PERIODOS.MES
    AND HISTORICOS.PERIODO        = PERIODOS.PERIODO 
  INNER JOIN PERSONAL 
    ON HISTORICOS.COMPANIA          = PERSONAL.COMPANIA  
    AND HISTORICOS.ID_DE_EMPLEADO   = PERSONAL.ID_DE_EMPLEADO 
  INNER JOIN CENTRO_COSTO
    ON PERSONAL.COMPANIA            = CENTRO_COSTO.COMPANIA
    AND PERSONAL.ANO                = CENTRO_COSTO.ANO
    AND PERSONAL.ID_CENTRO_DE_COSTO = CENTRO_COSTO.CODIGO
WHERE HISTORICOS.COMPANIA		    =	s$compania$s
  AND HISTORICOS.ID_DE_PROCESO		=	s$proceso$s
  AND HISTORICOS.ANO 			    =	s$ano$s
  AND HISTORICOS.MES 		      	=	s$mes$s
  AND HISTORICOS.PERIODO		    =	s$periodo$s
  s$estadoPersonal$s
  AND PERIODOS.ACUMULADO NOT IN(0)
GROUP BY   
    HISTORICOS.ID_DE_EMPLEADO ,
    CENTRO_COSTO.CODIGO,
    CENTRO_COSTO.NOMBRE
