SELECT 
    PERSONAL_HISTORICO.FONDO_RIESGOS, 
    PERSONAL_HISTORICO.NOMBRE_FONDORIESGOS, 
    PERSONAL_HISTORICO.NOMBRECOMPLETO, 
    PERSONAL_HISTORICO.NUMERO_DCTO, 
    V_FONDO_DE_RIESGOS.NIT AS  CEDULA, 
    PERSONAL_HISTORICO.SALARIO_BASE_IBC, 
    SUM(CASE WHEN V_ACUMULADOS.ID_DE_CONCEPTO=209 THEN V_ACUMULADOS.VALOR ELSE 0 END)  C209,
    SUM(CASE WHEN V_ACUMULADOS.ID_DE_CONCEPTO=212 THEN V_ACUMULADOS.VALOR ELSE 0 END)  C212,
    PERSONAL_HISTORICO.FACTOR_RIESGO  PORRIESGO, 
    SUM(CASE WHEN V_ACUMULADOS.ID_DE_CONCEPTO=111 THEN V_ACUMULADOS.VALOR ELSE 0 END)  C111,
    SUM(CASE WHEN V_ACUMULADOS.ID_DE_CONCEPTO=397 THEN V_ACUMULADOS.VALOR ELSE 0 END)  C397
FROM V_ACUMULADOS 
  INNER JOIN PERSONAL_HISTORICO 
     ON  V_ACUMULADOS.COMPANIA = PERSONAL_HISTORICO.COMPANIA
    AND  V_ACUMULADOS.ID_DE_PROCESO = PERSONAL_HISTORICO.ID_DE_PROCESO
    AND  V_ACUMULADOS.ANO = PERSONAL_HISTORICO.ANO
    AND  V_ACUMULADOS.MES = PERSONAL_HISTORICO.MES
    AND  V_ACUMULADOS.PERIODO = PERSONAL_HISTORICO.PERIODO
    AND  V_ACUMULADOS.ID_DE_EMPLEADO = PERSONAL_HISTORICO.ID_DE_EMPLEADO
INNER JOIN V_FONDO_DE_RIESGOS
    ON PERSONAL_HISTORICO.COMPANIA=V_FONDO_DE_RIESGOS.COMPANIA
   AND PERSONAL_HISTORICO.FONDO_RIESGOS=V_FONDO_DE_RIESGOS.FONDO_RIESGOS
WHERE V_ACUMULADOS.COMPANIA = s$compania$s
  AND V_ACUMULADOS.ID_DE_PROCESO = s$idProceso$s
  AND V_ACUMULADOS.ANO = s$ano$s
  AND V_ACUMULADOS.MES = s$mes$s
  AND V_ACUMULADOS.PERIODO = s$periodo$s  
GROUP BY 
    PERSONAL_HISTORICO.FONDO_RIESGOS, 
    PERSONAL_HISTORICO.NOMBRE_FONDORIESGOS, 
    PERSONAL_HISTORICO.NOMBRECOMPLETO, 
    PERSONAL_HISTORICO.NUMERO_DCTO, 
    PERSONAL_HISTORICO.SALARIO_BASE_IBC, 
    PERSONAL_HISTORICO.FACTOR_RIESGO,
    V_FONDO_DE_RIESGOS.NIT
