SELECT PERSONAL.INGRESO_DISTRITO,
  PERSONAL.ID_DE_EMPLEADO,
  PERSONAL.NOMBRECOMPLETO,
  PERSONAL.NUMERO_DCTO,
  HISTORICOS.ID_DE_PROCESO,
  HISTORICOS.ANO,
  PERSONAL.FECHA_DE_INGRESO,
  PCK_SYSMAN_UTL.FC_NOMBRE_MES(HISTORICOS.MES) NOMBREMES,
  HISTORICOS.PERIODO,
  SUM(
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '912'
    THEN HISTORICOS.VALOR
    ELSE 0
  END) LICENCIAS,
  SUM(
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '169'
    THEN HISTORICOS.VALOR
    ELSE 0
  END) INTCES1,
  SUM(
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '911'
    THEN HISTORICOS.VALOR
    ELSE 0
  END) PARCIAL,
  SUM(
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '900'
    THEN HISTORICOS.VALOR
    ELSE 0
  END) SALARIO,
  SUM(
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '902'
    THEN HISTORICOS.VALOR
    ELSE 0
  END) EXTRAS,
  SUM(
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '901'
    THEN HISTORICOS.VALOR
    ELSE 0
  END) BONIFICACION,
  SUM(
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '906'
    THEN HISTORICOS.VALOR
    ELSE 0
  END) PSERVICIOS,
  SUM(
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '903'
    THEN HISTORICOS.VALOR
    ELSE 0
  END) TRANSP,
  SUM(
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '909'
    THEN HISTORICOS.VALOR
    ELSE 0
  END) VPT,
  0 DIASNT,
  SUM(
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '910'
    THEN HISTORICOS.VALOR
    ELSE 0
  END) DIAST,
  SUM(
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '907'
    THEN HISTORICOS.VALOR
    ELSE 0
  END) PVAC,
  SUM(
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '904'
    THEN HISTORICOS.VALOR
    ELSE 0
  END) ALIMENTACION,
  SUM(
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '908'
    THEN HISTORICOS.VALOR
    ELSE 0
  END) GASTOSREP,
  SUM(
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '901'
    THEN HISTORICOS.VALOR
    ELSE 0
  END) VIATICOS,
  SUM(
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '905'
    THEN HISTORICOS.VALOR
    ELSE 0
  END) PNAVIDAD,
  SUM(
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '277'
    THEN HISTORICOS.VALOR
    ELSE 0
  END) + SUM(
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '911'
    THEN HISTORICOS.VALOR
    ELSE 0
  END) CONSOLIDADAS,
  SUM(
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '277'
    THEN HISTORICOS.VALOR
    ELSE 0
  END) CES,
  SUM(
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '269'
    THEN HISTORICOS.VALOR
    ELSE 0
  END) INTERESESC,
  SUM (
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '913'
    THEN HISTORICOS.VALOR
    ELSE 0
  END) BASECES,
  SUM(
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '277'
    THEN (HISTORICOS.VALOR*12/100)
    ELSE 0
  END) INTCES,
  V_FONDO_DE_CESANTIAS.FONDO_CESANTIAS,
  V_FONDO_DE_CESANTIAS.NIT,
  V_FONDO_DE_CESANTIAS.NOMBRE_FONDO_CESANTIAS,
  CENTRO_COSTO.CODIGO ID_CENTRO_DE_COSTO,
  CENTRO_COSTO.NOMBRE NOMBRE_CENTRO_DE_COSTO,
  SUM(
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '972'
    THEN HISTORICOS.VALOR
    ELSE 0
  END) CES31052000,
  SUM(
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '477'
    THEN HISTORICOS.VALOR
    ELSE 0
  END) MES13,
  SUM(
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '915'
    THEN HISTORICOS.VALOR
    ELSE 0
  END) APLICADAS,
  SUM(
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '478'
    THEN HISTORICOS.VALOR
    ELSE 0
  END) ACUMULADOALMES,
  SUM(
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '915'
    THEN HISTORICOS.VALOR
    ELSE 0
  END) + SUM(
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '477'
    THEN HISTORICOS.VALOR
    ELSE 0
  END) + SUM(
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '483'
    THEN HISTORICOS.VALOR
    ELSE 0
  END) + SUM(
  CASE
    WHEN HISTORICOS.ID_DE_CONCEPTO = '277'
    THEN HISTORICOS.VALOR
    ELSE 0
  END) TOTALCESANTIAS
FROM HISTORICOS
INNER JOIN PERSONAL
ON HISTORICOS.COMPANIA        = PERSONAL.COMPANIA
AND HISTORICOS.ID_DE_EMPLEADO = PERSONAL.ID_DE_EMPLEADO
INNER JOIN V_FONDO_DE_CESANTIAS
ON PERSONAL.COMPANIA         = V_FONDO_DE_CESANTIAS.COMPANIA
AND PERSONAL.FONDO_CESANTIAS = V_FONDO_DE_CESANTIAS.FONDO_CESANTIAS
INNER JOIN CENTRO_COSTO
ON PERSONAL.COMPANIA            = CENTRO_COSTO.COMPANIA
AND PERSONAL.ID_CENTRO_DE_COSTO = CENTRO_COSTO.CODIGO
AND PERSONAL.ANO                = CENTRO_COSTO.ANO
WHERE HISTORICOS.COMPANIA       = s$compania$s
AND HISTORICOS.ANO              = s$ano$s
AND HISTORICOS.MES              = s$mes$s
AND PERSONAL.FONDO_CESANTIAS   IN ('CES58')
AND HISTORICOS.ID_DE_CONCEPTO  IN('900' ,'901' ,'902' ,'903' ,'904' ,'905' ,'906' ,'907' ,'908' ,'909' ,'910' ,'911' ,'912' ,'913' ,'971' ,'269' ,'972' ,'477' ,'915' ,'478' ,'483' ,'277')
GROUP BY PERSONAL.INGRESO_DISTRITO,
  PERSONAL.FECHA_DE_INGRESO,
  PERSONAL.ID_DE_EMPLEADO,
  PERSONAL.NOMBRECOMPLETO,
  PERSONAL.NUMERO_DCTO,
  HISTORICOS.ID_DE_PROCESO,
  HISTORICOS.ANO,
  PCK_SYSMAN_UTL.FC_NOMBRE_MES(HISTORICOS.MES),
  PERSONAL.FONDO_CESANTIAS,
  CENTRO_COSTO.CODIGO,
  CENTRO_COSTO.NOMBRE,
  V_FONDO_DE_CESANTIAS.FONDO_CESANTIAS,
  V_FONDO_DE_CESANTIAS.NIT,
  V_FONDO_DE_CESANTIAS.NOMBRE_FONDO_CESANTIAS,
  HISTORICOS.PERIODO,
  0
ORDER BY PERSONAL.NOMBRECOMPLETO
