SELECT 
D.ANIO,
  D.ID_DE_EMPLEADO,
  P.NOMBRECOMPLETO,
  D.FECHA_INICIO,
  D.FECHA_FINAL,
  D.LICENCIAS_SUSPENSIONES,
  D.FECHA_INICIO_DISFRUTE,
  D.FECHA_ESTIMADA_REGRESO,
  D.DIAS_ESTIMADOS_DISFRUTE
FROM D_VACACIONES D
  INNER JOIN PERSONAL P
    ON D.COMPANIA        = P.COMPANIA
    AND D.ID_DE_EMPLEADO = P.ID_DE_EMPLEADO
WHERE D.COMPANIA     = s$compania$s 
  AND D.ANIO         = s$anio$s 
  AND D.FECHA_INICIO_DISFRUTE IS NOT NULL
