MERGE INTO CONSULTAS FIN USING (SELECT '001852FACTORESCESANTIASGOBCAQUETA' INFORME ,TO_CLOB(q'[SELECT HISTORICOS.COMPANIA,
    MIN(PERSONAL.INGRESO_DISTRITO)KEEP (DENSE_RANK FIRST ORDER BY ROWNUM) AS INGRESO_DISTRITO,
    MIN(PERSONAL.FECHA_DE_INGRESO)KEEP (DENSE_RANK FIRST ORDER BY ROWNUM) AS FECHA_DE_INGRESO,
    PERSONAL.ID_DE_EMPLEADO,
    PERSONAL.NOMBRECOMPLETO,
    PERSONAL.NUMERO_DCTO,
    PERSONAL.FECHA_DE_INGRESO,
    HISTORICOS.ID_DE_PROCESO,
    HISTORICOS.ANO,
    HISTORICOS.MES,
    HISTORICOS.PERIODO,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('912') THEN HISTORICOS.VALOR ELSE 0 END) AS LICENCIAS,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('169') THEN HISTORICOS.VALOR ELSE 0 END) AS INTCES1,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('911') THEN HISTORICOS.VALOR ELSE 0 END) AS PARCIAL,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('900') THEN HISTORICOS.VALOR ELSE 0 END) AS SALARIO,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('902') THEN HISTORICOS.VALOR ELSE 0 END) AS EXTRAS,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('909') THEN HISTORICOS.VALOR ELSE 0 END) AS BONIFICACION,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('909') THEN HISTORICOS.VALOR ELSE 0 END) AS CN909,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('906') THEN HISTORICOS.VALOR ELSE 0 END) AS PSERVICIOS,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('903') THEN HISTORICOS.VALOR ELSE 0 END) AS TRANSP,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('359') THEN HISTORICOS.VALOR ELSE 0 END) AS DIASNT,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('910') THEN HISTORICOS.VALOR ELSE 0 END) AS DIAST,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('907') THEN HISTORICOS.VALOR ELSE 0 END) AS PVAC,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('904') THEN HISTORICOS.VALOR ELSE 0 END) AS ALIMENTACION,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('908') THEN HISTORICOS.VALOR ELSE 0 END) AS VPP,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('901') THEN HISTORICOS.VALOR ELSE 0 END) AS VPA,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('901') THEN HISTORICOS.VALOR ELSE 0 END) AS VIATICOS,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('905') THEN HISTORICOS.VALOR ELSE 0 END) AS PNAVIDAD,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('277') THEN HISTORICOS.VALOR ELSE 0 END)+SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('911') THEN HISTORICOS.VALOR ELSE 0 END) AS CONSOLIDADAS,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('277') THEN HISTORICOS.VALOR ELSE 0 END)CES,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('269') THEN HISTORICOS.VALOR ELSE 0 END) AS INTERESESC,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('913') THEN HISTORICOS.VALOR ELSE 0 END) AS BASECES,
    ROUND(SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN('277') THEN HISTORICOS.VALOR ELSE 0 END)*12/100,0) AS INTCES,
    V_FONDO_DE_CESANTIAS.FONDO_CESANTIAS,
    V_FONDO_DE_CESANTIAS.NIT,
    V_FONDO_DE_CESANTIAS.NOMBRE_FONDO_CESANTIAS,
    CENTRO_COSTO.CODIGO AS ID_CENTRO_DE_COSTO,
    CENTRO_COSTO.NOMBRE AS NOMBRE_CENTRO_DE_COSTO,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('972') T]') || TO_CLOB(q'[HEN HISTORICOS.VALOR ELSE 0 END) AS CES31052000,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('973') THEN HISTORICOS.VALOR ELSE 0 END) AS DIAS31052000,
    PERSONAL.REGIMEN,
    PERSONAL.DIASINTERRUPCION
FROM HISTORICOS
INNER JOIN PERSONAL
   ON HISTORICOS.COMPANIA       = PERSONAL.COMPANIA
  AND HISTORICOS.ID_DE_EMPLEADO = PERSONAL.ID_DE_EMPLEADO
INNER JOIN PERSONAL_HISTORICO 
   ON HISTORICOS.COMPANIA=PERSONAL_HISTORICO.COMPANIA
   AND HISTORICOS.ID_DE_PROCESO=PERSONAL_HISTORICO.ID_DE_PROCESO
   AND HISTORICOS.ANO=PERSONAL_HISTORICO.ANO
   AND HISTORICOS.MES=PERSONAL_HISTORICO.MES
   AND HISTORICOS.PERIODO=PERSONAL_HISTORICO.PERIODO
   AND HISTORICOS.ID_DE_EMPLEADO=PERSONAL_HISTORICO.ID_DE_EMPLEADO
INNER JOIN CENTRO_COSTO
   ON PERSONAL_HISTORICO.COMPANIA           = CENTRO_COSTO.COMPANIA
   AND PERSONAL_HISTORICO.ANO = CENTRO_COSTO.ANO
  AND PERSONAL_HISTORICO.ID_CENTRO_DE_COSTO = CENTRO_COSTO.CODIGO
INNER JOIN V_FONDO_DE_CESANTIAS
   ON PERSONAL.COMPANIA        = V_FONDO_DE_CESANTIAS.COMPANIA
  AND PERSONAL.FONDO_CESANTIAS = V_FONDO_DE_CESANTIAS.FONDO_CESANTIAS
INNER JOIN CONCEPTOS
   ON HISTORICOS.COMPANIA       =  CONCEPTOS.COMPANIA
  AND HISTORICOS.ID_DE_CONCEPTO = CONCEPTOS.ID_DE_CONCEPTO
WHERE HISTORICOS.COMPANIA = s$compania$s
  AND HISTORICOS.PERIODO  = s$periodo$s
  AND HISTORICOS.ANO      = s$ano$s
  AND HISTORICOS.MES      = s$mes$s
  AND HISTORICOS.ID_DE_CONCEPTO IN ('900','901','902','903','904','905','906','907','908','909','910','911','912','913','971','269','277','972','973','971','914','969')
GROUP BY HISTORICOS.COMPANIA,
PERSONAL.ID_DE_EMPLEADO,
PERSONAL.NOMBRECOMPLETO,
PERSONAL.NUMERO_DCTO,
PERSONAL.FECHA_DE_INGRESO,
HISTORICOS.ID_DE_PROCESO,
HISTORICOS.ANO,
HISTORICOS.MES,
HISTORICOS.PERIODO,
V_FONDO_DE_CESANTIAS.FONDO_CESANTIAS,
V_FONDO_DE_CESANTIAS.NIT,
V_FONDO_DE_CESANTIAS.NOMBRE_FONDO_CESANTIAS,
CENTRO_COSTO.CODIGO,
CENTRO_COSTO.NOMBRE,
PERSONAL.REGIMEN,
PERSONAL.DIASINTERRUPCION
ORDER BY PERSONAL.NOMBRECOMPLETO]') CONSULTA, 6 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);
