MERGE INTO CONSULTAS FIN USING (SELECT '001844FACTORESVACACIONESGOBCAQUETA' INFORME ,TO_CLOB(q'[SELECT   PERSONAL.COMPANIA,
PERSONAL.NOMBRECOMPLETO, 
CARGOS.NOMBRE_DEL_CARGO, 
PERSONAL.NUMERO_DCTO,  
PERSONAL.FECHA_DE_INGRESO,
VACACIONES.FECHA_INICIO,
VACACIONES.FECHA_FINAL,
VACACIONES.INICIO_DISFRUTE,
VACACIONES.FINAL_DISFRUTE,
PERSONAL.ID_DE_EMPLEADO,
VACACIONES.ACTO,
VACACIONES.FECHA_ACTO,
CIUDAD.NOMBRE AS NOMBRECIUDAD,
ROUND((PCK_SYSMAN_UTL.FC_EDAD(PERSONAL.FECHA_DE_INGRESO,VACACIONES.INICIO_DISFRUTE)/365),0) ANTIGUEDAD,
DEPENDENCIA.NOMBRE,
(PERSONAL.FINAL_DISFRUTE + 1) AS FECHA_REINTEGROHABIL,
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (977) THEN HISTORICOS.VALOR ELSE 0 END) FACTOR2,
  SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (980) THEN HISTORICOS.VALOR ELSE 0 END) FACTOR3,
  SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (978) THEN HISTORICOS.VALOR ELSE 0 END) FACTOR7,
  SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (979) THEN HISTORICOS.VALOR ELSE 0 END) FACTOR8,
  SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (981) THEN HISTORICOS.VALOR ELSE 0 END) FACTOR9,
  SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (975) THEN HISTORICOS.VALOR ELSE 0 END) FACTOR10,
  SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (982) THEN HISTORICOS.VALOR ELSE 0 END) FACTOR11,
  SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (984) THEN HISTORICOS.VALOR ELSE 0 END) FACTOR12,
  SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (164) THEN HISTORICOS.VALOR ELSE 0 END) NUMPER,
  SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (35) THEN HISTORICOS.VALOR ELSE 0 END) DIASVAC,
  SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (93) THEN HISTORICOS.VALOR ELSE 0 END) DIASPRIMA,
  SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (94) THEN HISTORICOS.VALOR ELSE 0 END) DIASCAL,
  SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (96) THEN HISTORICOS.VALOR ELSE 0 END) DIASDINERO,
  SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (151) THEN HISTORICOS.VALOR ELSE 0 END) BONRECRE,
  SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (155) THEN HISTORICOS.VALOR ELSE 0 END) PRIMVAC,
  SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (162) THEN HISTORICOS.VALOR ELSE 0 END) DIASHAB,
  SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (170) THEN HISTORICOS.VALOR ELSE 0 END) PANTIGUEDAD,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('174') THEN HISTORICOS.VALOR ELSE 0 END) SALVAC,
  SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (175) THEN HISTORICOS.VALOR ELSE 0 END) VACDINERO,
  SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (976) THEN HISTORICOS.VALOR ELSE 0 END) EXTRASPV,
  SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN(977, 980, 978, 979, 981, 975, 982, 984, 170, 976) THEN HISTORICOS.VALOR ELSE 0 END) TOTALFACTOR,
  SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (174,175,155,151) THEN HISTORICOS.VALOR ELSE 0 END) AS TOTALPAGO,
  MAX(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (151) THEN 
                TO_NUMBER(PCK_SYSMAN_UTL.FC_PAR(HISTORICOS.COMPANIA,'NUMERO DE DIAS PARA BONIFICACION DE RECREACION', 6, 
                TO_DATE('01/' || HISTORICOS.MES || '/' || HISTORICOS.ANO,'DD/MM/YYYY'))) ELSE 0 END 
                )  KEEP (]') || TO_CLOB(q'[DENSE_RANK LAST ORDER BY ROWNUM) DIASRECRE
FROM HISTORICOS
INNER JOIN PERSONAL
ON HISTORICOS.COMPANIA  = PERSONAL.COMPANIA
AND HISTORICOS.ID_DE_EMPLEADO = PERSONAL.ID_DE_EMPLEADO
INNER JOIN DEPENDENCIA
 ON PERSONAL.COMPANIA     = DEPENDENCIA.COMPANIA
AND PERSONAL.DEPENDENCIA = DEPENDENCIA.CODIGO
INNER JOIN CARGOS
 ON PERSONAL.COMPANIA     = CARGOS.COMPANIA
AND PERSONAL.ID_DE_CARGO = CARGOS.ID_DE_CARGO
LEFT JOIN CIUDAD
 ON PERSONAL.DEPARTAMENTO_CED = CIUDAD.DEPARTAMENTO
AND PERSONAL.EXPEDIDA    = CIUDAD.CODIGO
AND PERSONAL.PAIS_CED        = CIUDAD.PAIS
INNER JOIN CATEGORIA
 ON PERSONAL.COMPANIA         = CATEGORIA.COMPANIA
AND PERSONAL.ESCALAFON       = CATEGORIA.ESCALAFON
AND PERSONAL.ID_DE_CATEGORIA = CATEGORIA.ID_DE_CATEGORIA
AND PERSONAL.ANO             = CATEGORIA.ANO
INNER JOIN VACACIONES 
ON PERSONAL.COMPANIA = VACACIONES.COMPANIA
AND PERSONAL.ID_DE_EMPLEADO = VACACIONES.ID_DE_EMPLEADO
WHERE VACACIONES.COMPANIA   = s$compania$s
AND PERSONAL.ID_DE_EMPLEADO = s$empleado$s
AND VACACIONES.ANO          = s$ano$s
AND VACACIONES.MES          = s$mes$s
GROUP BY PERSONAL.COMPANIA,
PERSONAL.NOMBRECOMPLETO, 
CARGOS.NOMBRE_DEL_CARGO, 
PERSONAL.NUMERO_DCTO,  
PERSONAL.FECHA_DE_INGRESO,
VACACIONES.FECHA_INICIO,
VACACIONES.FECHA_FINAL,
VACACIONES.INICIO_DISFRUTE,
VACACIONES.FINAL_DISFRUTE,
PERSONAL.ID_DE_EMPLEADO,
VACACIONES.ACTO,
VACACIONES.FECHA_ACTO,
CIUDAD.NOMBRE,
ROUND((PCK_SYSMAN_UTL.FC_EDAD(PERSONAL.FECHA_DE_INGRESO,VACACIONES.INICIO_DISFRUTE)/365),0),
DEPENDENCIA.NOMBRE,
(PERSONAL.FINAL_DISFRUTE + 1)
ORDER BY PERSONAL.NOMBRECOMPLETO]') CONSULTA, 6 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);
