SELECT PERSONAL.COMPANIA,
  PERSONAL.ID_DE_EMPLEADO,
  PERSONAL.NOMBRECOMPLETO,
  CARGOS.NOMBRE_DEL_CARGO,
PERSONAL.FECHA_DE_INGRESO,
  PERSONAL.NUMERO_DCTO,
  ROUND((PCK_SYSMAN_UTL.FC_EDAD(PERSONAL.FECHA_DE_INGRESO,VACACIONES.INICIO_DISFRUTE)/365),0) ANTIGUEDAD1,
  DEPENDENCIA.NOMBRE,
  CIUDAD.NOMBRE AS NOMBRECIUDAD,
  VACACIONES.ACTO,
  TO_CHAR(VACACIONES.FECHA_ACTO,'DD/MM/YYYY') AS FECHA_ACTO,
  VACACIONES.FINAL_DISFRUTE,
PERSONAL.FINAL_DISFRUTE + 1 AS FECHA_REINTEGROHABIL,
  VACACIONES.FECHA_INICIO,
VACACIONES.FECHA_FINAL,
VACACIONES.INICIO_DISFRUTE,
VACACIONES.FINAL_DISFRUTE
FROM PERSONAL
INNER JOIN DEPENDENCIA
 ON PERSONAL.COMPANIA     = DEPENDENCIA.COMPANIA
AND PERSONAL.DEPENDENCIA = DEPENDENCIA.CODIGO
INNER JOIN CARGOS
 ON PERSONAL.COMPANIA     = CARGOS.COMPANIA
AND PERSONAL.ID_DE_CARGO = CARGOS.ID_DE_CARGO
LEFT JOIN CIUDAD
 ON PERSONAL.DEPARTAMENTO_CED = CIUDAD.DEPARTAMENTO
AND PERSONAL.EXPEDIDA    = CIUDAD.CODIGO
AND PERSONAL.PAIS_CED        = CIUDAD.PAIS
INNER JOIN CATEGORIA
 ON PERSONAL.COMPANIA         = CATEGORIA.COMPANIA
AND PERSONAL.ESCALAFON       = CATEGORIA.ESCALAFON
AND PERSONAL.ID_DE_CATEGORIA = CATEGORIA.ID_DE_CATEGORIA
AND PERSONAL.ANO             = CATEGORIA.ANO
INNER JOIN VACACIONES 
ON PERSONAL.COMPANIA = VACACIONES.COMPANIA
AND PERSONAL.ID_DE_EMPLEADO = VACACIONES.ID_DE_EMPLEADO
WHERE VACACIONES.COMPANIA   = s$compania$s
AND PERSONAL.ID_DE_EMPLEADO = s$empleado$s
AND VACACIONES.ANO          = s$ano$s
AND VACACIONES.MES          = s$mes$s
ORDER BY PERSONAL.NOMBRECOMPLETO
