SELECT 
  MIN(CONCEPTOS.CLASE) KEEP (DENSE_RANK FIRST ORDER BY ROWNUM) AS CLASE,
  HISTORICOS.ID_DE_CONCEPTO,
  MIN(CASE CONCEPTOS.CLASE WHEN 3 THEN  'VALOR DEVENGOS'
                           WHEN 5 THEN  'VALOR DESCUENTOS'
                           WHEN 4 THEN  'VALOR TOTAL DEVENGOS'
                           WHEN 6 THEN  'VALOR TOTAL DESCUENTOS'
                           WHEN 7 THEN  'VALOR NETO A PAGAR'
                          WHEN  99 THEN 'BASES'
                                ELSE 'CONCEPTOS CONTABLES' END) KEEP (DENSE_RANK FIRST ORDER BY ROWNUM)  CLASECONCEPTO,
  MIN(CONCEPTOS.NOMBRE_CONCEPTO) KEEP (DENSE_RANK FIRST ORDER BY ROWNUM) AS NOMBRE_CONCEPTO,
  SUM(HISTORICOS.VALOR) AS SUMADEVALOR,
  SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO >= ('490') AND HISTORICOS.ID_DE_CONCEPTO <= ('499') THEN HISTORICOS.VALOR ELSE 0 END) PROVISIONES  
FROM HISTORICOS
INNER JOIN CONCEPTOS
   ON HISTORICOS.COMPANIA       = CONCEPTOS.COMPANIA
  AND HISTORICOS.ID_DE_CONCEPTO = CONCEPTOS.ID_DE_CONCEPTO
INNER JOIN PERIODOS
   ON HISTORICOS.COMPANIA      = PERIODOS.COMPANIA
  AND HISTORICOS.ID_DE_PROCESO = PERIODOS.ID_DE_PROCESO
  AND HISTORICOS.ANO           = PERIODOS.ANO
  AND HISTORICOS.MES           = PERIODOS.MES
  AND HISTORICOS.PERIODO       = PERIODOS.PERIODO
WHERE HISTORICOS.COMPANIA  = s$compania$s
  AND PERIODOS.ACUMULADO  NOT IN (0)
  AND HISTORICOS.ID_DE_PROCESO || HISTORICOS.ANO || HISTORICOS.MES || HISTORICOS.PERIODO BETWEEN 's$proceso$s' || 's$ano$s' || 's$mes$s' || 's$periodo$s' AND 's$proceso$s' || 's$ano$s' || 's$mes$s' || 's$periodo$s'
GROUP BY HISTORICOS.ID_DE_CONCEPTO,
  PERIODOS.NOM_PERIODO,
  HISTORICOS.ANO, 
  HISTORICOS.MES,
  HISTORICOS.PERIODO,
  HISTORICOS.ID_DE_PROCESO || HISTORICOS.ANO || HISTORICOS.MES || HISTORICOS.PERIODO
HAVING MIN(CONCEPTOS.CLASE) KEEP (DENSE_RANK FIRST ORDER BY ROWNUM) IN (3,4,5,6,7,8,99)
