SELECT  VI.COMPANIA ,
  VI.ANO ,
  VI.CODSOLICITUD ,
  VI.NUMSOLICITUD ,
  TO_CHAR(VI.FECHA,'DD/MM/YYYY')FECHA ,
  TT.NOMBRE NOMBRERESPONSABLE,
  R.CARGO NOMBRE_CARGO_RESPONSABLE,
  T.NOMBRE NOMBRETERCERO,
  VI.TERCERO ,
  CG.NOMBRE_DEL_CARGO,
  DP.NOMBRE NOMBREDEPENDENCIA,
  CID.NOMBRE CIUDAD_DESTINO,
  TO_CHAR(VI.FECHAINICIO,'DD/MM/YYYY')FECHAINICIO ,
  TO_CHAR(VI.FECHAFIN,'DD/MM/YYYY') FECHAFIN,
  TO_CHAR(VI.FECHA_LEGALIZACION, 'DD/MM/YYYY') FECHA_LEGALIZACION,
  TO_CHAR(VI.RESUMEN_ACTIVIDADES)RESUMEN_ACTIVIDADES
FROM VI_VIATICOS VI
INNER JOIN TERCERO T
ON VI.COMPANIA  = T.COMPANIA
AND VI.TERCERO  = T.NIT
AND VI.SUCURSAL = T.SUCURSAL
LEFT JOIN PERSONAL P
ON T.COMPANIA       = P.COMPANIA
AND T.NIT           = P.NUMERO_DCTO
AND P.ESTADO_ACTUAL = 1
AND T.SUCURSAL      = P.SUCURSAL
LEFT JOIN CARGOS CG
ON P.COMPANIA     = CG.COMPANIA
AND P.ID_DE_CARGO = CG.ID_DE_CARGO
INNER JOIN DEPENDENCIA DP
ON VI.COMPANIA     = DP.COMPANIA
AND VI.DEPENDENCIA = DP.CODIGO
INNER JOIN DEPENDENCIA_RESPONSABLE DPR
ON VI.COMPANIA          = DPR.COMPANIA
AND VI.DEPENDENCIA      = DPR.DEPENDENCIA
AND VI.JEFE_DEPENDENCIA = DPR.RESPONSABLE
INNER JOIN RESPONSABLE R
ON R.COMPANIA  = DPR.COMPANIA
AND R.CEDULA   = DPR.RESPONSABLE
AND R.SUCURSAL = DPR.SUCURSAL
INNER JOIN TERCERO TT
ON R.COMPANIA  = TT.COMPANIA
AND R.CEDULA   = TT.NIT
AND R.SUCURSAL = TT.SUCURSAL
INNER JOIN CIUDAD CID
ON VI.CIUDAD_DESTINO        = CID.CODIGO
AND VI.DEPARTAMENTO_DESTINO = CID.DEPARTAMENTO
AND VI.PAIS_DESTINO         = CID.PAIS
WHERE VI.COMPANIA           = s$compania$s
AND VI.CODSOLICITUD         = s$solicitud$s
