MERGE INTO CONSULTAS FIN USING ( SELECT '001922ResumenAutoPension' AS INFORME_VAL, TO_CLOB(q'[SELECT 
  PERSONAL_HISTORICO.NOMBRE_FONDOPENSION, 
  V_FONDO_DE_PENSIONES.NIT NITFONDO,   
  SUM(CASE WHEN V_ACUMULADOS.ID_DE_CONCEPTO IN (112) THEN V_ACUMULADOS.VALOR ELSE 0 END)  IBC, 
  SUM(CASE WHEN V_ACUMULADOS.ID_DE_CONCEPTO IN (118) THEN V_ACUMULADOS.VALOR ELSE 0 END)   PENSIONEMPLEADO, 
  SUM(CASE WHEN V_ACUMULADOS.ID_DE_CONCEPTO IN (117) THEN V_ACUMULADOS.VALOR ELSE 0 END)   PENSIONPATRONO, 
  SUM(CASE WHEN V_ACUMULADOS.ID_DE_CONCEPTO IN (115) THEN V_ACUMULADOS.VALOR ELSE 0 END)   SOLIDARIDAD, 
  SUM(CASE WHEN V_ACUMULADOS.ID_DE_CONCEPTO IN (120) THEN V_ACUMULADOS.VALOR ELSE 0 END)   ADICIONALSOLIDARIDAD,
  PERSONAL_HISTORICO.ID_CENTRO_DE_COSTO,
  PERSONAL_HISTORICO.NOMBRE_CENTRO_DE_COSTO
FROM V_ACUMULADOS 
  INNER JOIN PERSONAL_HISTORICO 
     ON  V_ACUMULADOS.COMPANIA = PERSONAL_HISTORICO.COMPANIA
    AND  V_ACUMULADOS.ID_DE_PROCESO = PERSONAL_HISTORICO.ID_DE_PROCESO
    AND  V_ACUMULADOS.ANO = PERSONAL_HISTORICO.ANO
    AND  V_ACUMULADOS.MES = PERSONAL_HISTORICO.MES
    AND  V_ACUMULADOS.PERIODO = PERSONAL_HISTORICO.PERIODO
    AND  V_ACUMULADOS.ID_DE_EMPLEADO = PERSONAL_HISTORICO.ID_DE_EMPLEADO
  INNER JOIN V_FONDO_DE_PENSIONES
     ON PERSONAL_HISTORICO.COMPANIA = V_FONDO_DE_PENSIONES.COMPANIA
    AND PERSONAL_HISTORICO.ID_DEL_FONDO = V_FONDO_DE_PENSIONES.ID_DEL_FONDO
WHERE V_ACUMULADOS.COMPANIA = s$compania$s
  AND V_ACUMULADOS.ID_DE_PROCESO = s$idProceso$s
  AND V_ACUMULADOS.ANO = s$ano$s
  AND V_ACUMULADOS.MES = s$rangoMes$s  
  GROUP BY PERSONAL_HISTORICO.NOMBRE_FONDOPENSION,
        V_FONDO_DE_PENSIONES.NIT,        
        PERSONAL_HISTORICO.ID_CENTRO_DE_COSTO,
    PERSONAL_HISTORICO.NOMBRE_CENTRO_DE_COSTO]') AS CONSULTA_VAL, 6 AS APLICACION_VAL, TO_CLOB(q'[]') AS CONSULTA_OPCIONAL_VAL, (SELECT MIN(ROWID) FROM CONSULTAS WHERE INFORME = '001922ResumenAutoPension') AS RID_DESTINO  FROM DUAL ) INI ON (FIN.ROWID = INI.RID_DESTINO)  WHEN MATCHED THEN   UPDATE SET FIN.CONSULTA = INI.CONSULTA_VAL, FIN.APLICACION = INI.APLICACION_VAL, FIN.CONSULTA_OPCIONAL = INI.CONSULTA_OPCIONAL_VAL, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN   INSERT (INFORME, CONSULTA, APLICACION, CONSULTA_OPCIONAL, DATE_CREATED)   VALUES (INI.INFORME_VAL, INI.CONSULTA_VAL, INI.APLICACION_VAL, INI.CONSULTA_OPCIONAL_VAL, SYSDATE);
