SELECT  
    MAX(HISTORICOS.ID_DE_PROCESO) KEEP (DENSE_RANK LAST ORDER BY ROWNUM) ID_DE_PROCESO,
    MAX(HISTORICOS.ANO) KEEP (DENSE_RANK LAST ORDER BY ROWNUM) ANO,
    PCK_SYSMAN_UTL.FC_NOMBRE_MES(HISTORICOS.MES) MES,
    MAX(HISTORICOS.PERIODO) KEEP (DENSE_RANK LAST ORDER BY ROWNUM) PERIODO,
    MAX(PERSONAL.NUMERO_DCTO) AS CEDULA, 
    MAX(PERSONAL.ID_DE_CARGO)  AS CARGO,
    PERSONAL.NOMBRECOMPLETO NOM_EMPLEADO,
    CENTRO_COSTO.CODIGO ID_CENTRO_DE_COSTO,
    CENTRO_COSTO.NOMBRE NOMBRE_CENTRO_DE_COSTO,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('001') THEN HISTORICOS.VALOR ELSE 0 END) C001,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('009') THEN HISTORICOS.VALOR ELSE 0 END) C009,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('097') THEN HISTORICOS.VALOR ELSE 0 END) C097,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('125') THEN HISTORICOS.VALOR ELSE 0 END) C125,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('140') THEN HISTORICOS.VALOR ELSE 0 END) C140,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('144') THEN HISTORICOS.VALOR ELSE 0 END) C144,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('151') THEN HISTORICOS.VALOR ELSE 0 END) C151,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('155') THEN HISTORICOS.VALOR ELSE 0 END) C155,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('174') THEN HISTORICOS.VALOR ELSE 0 END) C174,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('175') THEN HISTORICOS.VALOR ELSE 0 END) C175,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('362') THEN HISTORICOS.VALOR ELSE 0 END) C362,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('799') THEN HISTORICOS.VALOR ELSE 0 END) C799,
    SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('699') THEN HISTORICOS.VALOR ELSE 0 END -  
        CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('637') THEN HISTORICOS.VALOR ELSE 0 END - 
        CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('635') THEN HISTORICOS.VALOR ELSE 0 END +
        CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('124') THEN HISTORICOS.VALOR ELSE 0 END +
        CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('127') THEN HISTORICOS.VALOR ELSE 0 END +
        CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('120') THEN HISTORICOS.VALOR ELSE 0 END +
        CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('123') THEN HISTORICOS.VALOR ELSE 0 END +
        CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('224') THEN HISTORICOS.VALOR ELSE 0 END)TOTALDSTOS
FROM HISTORICOS 
 INNER JOIN PERIODOS
   ON HISTORICOS.COMPANIA        = PERIODOS.COMPANIA
  AND HISTORICOS.ID_DE_PROCESO  = PERIODOS.ID_DE_PROCESO
  AND HISTORICOS.ANO            = PERIODOS.ANO
  AND HISTORICOS.MES            = PERIODOS.MES
  AND HISTORICOS.PERIODO        = PERIODOS.PERIODO 
 INNER JOIN PERSONAL 
   ON HISTORICOS.COMPANIA        = PERSONAL.COMPANIA  
  AND HISTORICOS.ID_DE_EMPLEADO = PERSONAL.ID_DE_EMPLEADO 
 INNER JOIN CENTRO_COSTO
   ON PERSONAL.COMPANIA           = CENTRO_COSTO.COMPANIA
  AND PERSONAL.ID_CENTRO_DE_COSTO = CENTRO_COSTO.CODIGO 
  AND HISTORICOS.ANO     = CENTRO_COSTO.ANO 
 WHERE HISTORICOS.COMPANIA    = s$compania$s
   AND HISTORICOS.ID_DE_PROCESO = s$proceso$s 
   AND HISTORICOS.ANO    = s$ano$s
   AND HISTORICOS.MES    = s$mes$s
   AND HISTORICOS.PERIODO = s$periodo$s 
   AND PERIODOS.ACUMULADO NOT IN(0) 
 GROUP BY  HISTORICOS.ID_DE_PROCESO,
    HISTORICOS.ANO,
    HISTORICOS.MES,
    HISTORICOS.PERIODO,
    PERSONAL.NUMERO_DCTO, 
    PERSONAL.ID_DE_CARGO,
    PERSONAL.NOMBRECOMPLETO,
    CENTRO_COSTO.CODIGO,
    CENTRO_COSTO.NOMBRE
