WITH PRIMATECNICAAUDITORIA AS
               (SELECT NOVEDADES.COMPANIA,NOVEDADES.ID_DE_EMPLEADO, 
               SUM (case when NOVEDADES.ID_DE_CONCEPTO = 085 then  NOVEDADES.VALOR else  0 end) VPT, 
               SUM (case when NOVEDADES.ID_DE_CONCEPTO = 086 then NOVEDADES.VALOR  else  0 end) VPTNO,
               SUM (case when NOVEDADES.ID_DE_CONCEPTO = 087 then  NOVEDADES.VALOR else 0 end) VPTNACION,
               SUM (case when NOVEDADES.ID_DE_CONCEPTO = 062 then NOVEDADES.VALOR else 0 end) VRGR,
               SUM (case when NOVEDADES.ID_DE_CONCEPTO = 188 then NOVEDADES.VALOR else 0 end) AS VRPTAG, 
               SUM (case when NOVEDADES.ID_DE_CONCEPTO = 189 then NOVEDADES.VALOR else 0 end) AS VRPTDA, 
               SUM (case when NOVEDADES.ID_DE_CONCEPTO = 191 then NOVEDADES.VALOR else 0 end) AS VRPTAGD
               FROM NOVEDADES
               WHERE NOVEDADES.ANO=0
               AND NOVEDADES.MES=0
               AND NOVEDADES.PERIODO=0
               AND NOVEDADES.ID_DE_CONCEPTO IN (085,086, 087, 062, 188, 189, 191)
               AND NOVEDADES.COMPANIA= s$compania$s
               GROUP BY NOVEDADES.COMPANIA, NOVEDADES.ID_DE_EMPLEADO)
               SELECT DISTINCT 
                   BANCOS_NOMINA.NOMBRE BANCOS_NOMBRE, 
                   PERSONAL.NOMBRECOMPLETO  NOMBRECOMPLETO, 
                   TIPOS_DE_EMPLEADO.NOMBRE_TIPO, 
                   CARGOS.NOMBRE_DEL_CARGO, 
                   DEPENDENCIA.NOMBRE  NOMBREDEPENDENCIA, 
                   DEPENDENCIA.NOMBRE NOMBRED,
                   CATEGORIA.NOMBRE_CATEGORIA, 
                   CASE WHEN PERSONAL.ESTADO_ACTUAL=2 AND CATEGORIA.SALARIO_BASE = 0 THEN PCK_NOMINA_COM5.FC_MIMESADA(PERSONAL.ID_DE_EMPLEADO, s$compania$s) ELSE CATEGORIA.SALARIO_BASE END as SALARIO_BASE,
                   Categoria.Salario_Base*Categoria.GastosRepresentacion/100 Gastos, 
                   ESCALAFON.CODIGO, 
                   CASE WHEN PERSONAL.SEXO = 'M' THEN 1 ELSE
                       CASE WHEN  PERSONAL.SEXO = 'F'  THEN 2 ELSE 3
                       END
                   END  VALORSEXO, 
                   ESTADO_CIVIL.DESCRIPCION, 
                   PERSONAL.ESTADO_ACTUAL, 
                   PERSONAL.FECHA_DE_RETIRO, 
                   nvl((CATEGORIA.SALARIO_BASE*VPT/100),0)  VRPT,
                   PERSONAL.ANO, 
                   PERSONAL.ID_DE_EMPLEADO  ID_DE_EMPLEADO, 
                   CATEGORIA.CODIGOGRADO, 
                   CATEGORIA.SALARIO_RETROACTIVO, 
                   CATEGORIA.VLR_INCREMENTO, 
                   PRIMATECNICAAUDITORIA.VPT  PVPT, 
                   PRIMATECNICAAUDITORIA.VRGR, 
                   PRIMATECNICAAUDITORIA.VRPTAG,
                   PRIMATECNICAAUDITORIA.VRPTDA, 
                   PRIMATECNICAAUDITORIA.VRPTAGD,
                   CATEGORIA.SALARIOANTERIOR, 
                   PERSONAL.FECHA_DE_INGRESO, 
                   PERSONAL.NUMERO_DCTO, 
                   PERSONAL.ID_DE_CATEGORIA, 
                   PERSONAL.BANCO  BANCO, 
                   PERSONAL.CUENTA  CUENTA, 
                   PERSONAL.ID_CENTRO_DE_COSTO  ID_CENTRO_DE_COSTO, 
                   PERSONAL.DEPENDENCIA 
               FROM  PERSONAL  LEFT JOIN DEPENDENCIA ON PERSONAL.DEPENDENCIA = DEPENDENCIA.CODIGO AND PERSONAL.COMPANIA = DEPENDENCIA.COMPANIA 
               LEFT JOIN TIPOS_DE_EMPLEADO ON PERSONAL.ID_DE_TIPO = TIPOS_DE_EMPLEADO.ID_DE_TIPO AND PERSONAL.COMPANIA = TIPOS_DE_EMPLEADO.COMPANIA 
               LEFT JOIN CENTRO_COSTO ON PERSONAL.ID_CENTRO_DE_COSTO = CENTRO_COSTO.CODIGO AND PERSONAL.COMPANIA = CENTRO_COSTO.COMPANIA
			   AND PERSONAL.ANO = CENTRO_COSTO.ANO
               LEFT JOIN BANCOS_NOMINA ON PERSONAL.BANCO = BANCOS_NOMINA.BANCO AND PERSONAL.COMPANIA = BANCOS_NOMINA.COMPANIA
               LEFT JOIN ESTADO_CIVIL ON PERSONAL.ESTADO_CIVIL = ESTADO_CIVIL.ESTADO_CIVIL AND PERSONAL.COMPANIA = ESTADO_CIVIL.COMPANIA
               LEFT JOIN CARGOS ON PERSONAL.COMPANIA = CARGOS.COMPANIA 
				   AND CASE WHEN PERSONAL.CARGO_ENCARGO IS NOT NULL THEN  PERSONAL.CARGO_ENCARGO
				   ELSE PERSONAL.ID_DE_CARGO
				   END=CARGOS.ID_DE_CARGO                           
               LEFT JOIN CATEGORIA ON PERSONAL.ANO = CATEGORIA.ANO 
				   AND PERSONAL.COMPANIA = CATEGORIA.COMPANIA 
				   AND CASE WHEN PERSONAL.CARGO_ENCARGO IS NOT NULL THEN  CATEGORIA.ESCALAFON
				   ELSE PERSONAL.ESCALAFON
				   END=CATEGORIA.ESCALAFON   
				   AND CARGOS.NOMBRE_DEL_CARGO = CATEGORIA.NOMBRE_CATEGORIA
				   AND CASE WHEN PERSONAL.CARGO_ENCARGO IS NOT NULL THEN  CATEGORIA.ID_DE_CATEGORIA
				   ELSE PERSONAL.ID_DE_CATEGORIA
				   END=CATEGORIA.ID_DE_CATEGORIA
				   AND CARGOS.NOMBRE_DEL_CARGO = CATEGORIA.NOMBRE_CATEGORIA
			   LEFT JOIN ESCALAFON ON PERSONAL.COMPANIA = ESCALAFON.COMPANIA 
				   AND CASE WHEN PERSONAL.CARGO_ENCARGO IS NOT NULL THEN  ESCALAFON.CODIGO
				   ELSE PERSONAL.ESCALAFON
				   END=ESCALAFON.CODIGO  
				   AND CARGOS.NOMBRE_DEL_CARGO = CATEGORIA.NOMBRE_CATEGORIA
                   And PERSONAL.ESCALAFON = ESCALAFON.CODIGO 
               LEFT JOIN PRIMATECNICAAUDITORIA ON Personal.ID_DE_EMPLEADO = PRIMATECNICAAUDITORIA.ID_DE_EMPLEADO AND Personal.COMPANIA = PRIMATECNICAAUDITORIA.COMPANIA
               LEFT JOIN FORMANOMBRAMIENTO ON PERSONAL.DE_CARRERA = FORMANOMBRAMIENTO.IDFORMA AND PERSONAL.COMPANIA = FORMANOMBRAMIENTO.COMPANIA 
               WHERE Personal.COMPANIA=  s$compania$s 
               And Personal.ID_DE_EMPLEADO<>0 
               And (Personal.FECHA_DE_RETIRO Is Null  Or (Personal.ESTADO_ACTUAL=2 
               And Personal.FECHA_DE_RETIRO Is Not Null ))
               
               s$condicion$s
               