SELECT PERSONAL.ID_DE_EMPLEADO, 
NOMBRECOMPLETO,
PERSONAL.NUMERO_DCTO, 
TO_CHAR(PERSONAL.FECHA_DE_INGRESO,'DD/MM/YYYY') AS FECHA_DE_INGRESO, 
CENTRO_COSTO.NOMBRE AS NOMBRE_CENTRO_DE_COSTO,
DEPENDENCIA.NOMBRE, 
CARGOS.NOMBRE_DEL_CARGO AS NOMBRE_DEL_CARGO, 
HISTORICOS.ID_DE_PROCESO, 
HISTORICOS.ANO, 
HISTORICOS.MES, 
HISTORICOS.PERIODO, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='001' THEN HISTORICOS.VALOR ELSE 0 END) AS SUELDOBON, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='150' THEN HISTORICOS.VALOR ELSE 0 END) AS BONIFICACION, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='161' THEN HISTORICOS.VALOR ELSE 0 END) AS PORCEN, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='882' THEN HISTORICOS.VALOR ELSE 0 END) AS GREPBON, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='860' THEN HISTORICOS.VALOR ELSE 0 END) AS DIASLICBON, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='001' THEN HISTORICOS.VALOR ELSE 0 END)+SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='882' THEN HISTORICOS.VALOR ELSE 0 END)+SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='872' THEN HISTORICOS.VALOR ELSE 0 END) AS TOTAL, 
MAX(TO_CHAR(HISTORICOS.FECHA,'DD/MM/YYYY')) AS FECHA, 
PERSONAL.ID_CENTRO_DE_COSTO, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='872' THEN HISTORICOS.VALOR ELSE 0 END) AS PANTIG, 
PERSONAL.ID_DE_CARGO,
PERSONAL.ID_DE_CARGOESCALERA, 
PERSONAL.ID_DE_CARGO_TEMPORAL, 
CARGOSE.NOMBRE_DEL_CARGO AS NOMBRE_DEL_CARGO_ESCALERA, 
CARGOST.NOMBRE_DEL_CARGO AS NOMBRE_DEL_CARGOTEMPORAL
FROM HISTORICOS 
INNER JOIN PERSONAL 
ON PERSONAL.COMPANIA=HISTORICOS.COMPANIA
AND PERSONAL.ID_DE_EMPLEADO = HISTORICOS.ID_DE_EMPLEADO
INNER JOIN DEPENDENCIA
ON DEPENDENCIA.CODIGO = PERSONAL.DEPENDENCIA
AND DEPENDENCIA.COMPANIA=PERSONAL.COMPANIA
INNER JOIN CENTRO_COSTO 
ON CENTRO_COSTO.CODIGO= PERSONAL.ID_CENTRO_DE_COSTO 
AND CENTRO_COSTO.COMPANIA=PERSONAL.COMPANIA
AND CENTRO_COSTO.ANO= HISTORICOS.ANO
LEFT JOIN CARGOS 
ON CARGOS.ID_DE_CARGO = PERSONAL.ID_DE_CARGO 
AND CARGOS.COMPANIA=PERSONAL.COMPANIA
LEFT JOIN CARGOS CARGOST
ON CARGOST.ID_DE_CARGO = PERSONAL.ID_DE_CARGO_TEMPORAL 
AND CARGOST.COMPANIA=PERSONAL.COMPANIA
LEFT JOIN CARGOS CARGOSE
ON CARGOSE.ID_DE_CARGO = PERSONAL.ID_DE_CARGOESCALERA 
AND CARGOSE.COMPANIA=PERSONAL.COMPANIA
WHERE 
(HISTORICOS.ID_DE_CONCEPTO IN (001,882,150,161,860,872))
AND HISTORICOS.COMPANIA=s$compania$s
AND HISTORICOS.ANO=s$ano$s
AND HISTORICOS.MES=s$mes$s
AND HISTORICOS.PERIODO=s$periodo$s
AND HISTORICOS.ID_DE_PROCESO= s$idProceso$s
GROUP BY PERSONAL.ID_DE_EMPLEADO, 
PERSONAL.NOMBRECOMPLETO, 
PERSONAL.NUMERO_DCTO, 
PERSONAL.FECHA_DE_INGRESO, 
CENTRO_COSTO.NOMBRE, 
DEPENDENCIA.NOMBRE, CARGOS.NOMBRE_DEL_CARGO, 
HISTORICOS.ID_DE_PROCESO, 
HISTORICOS.ANO, 
HISTORICOS.MES, 
HISTORICOS.PERIODO, 
PERSONAL.ID_CENTRO_DE_COSTO, 
PERSONAL.ID_DE_CARGOESCALERA, 
PERSONAL.ID_DE_CARGO_TEMPORAL, 
CARGOSE.NOMBRE_DEL_CARGO,
CARGOST.NOMBRE_DEL_CARGO,
PERSONAL.ID_DE_CARGO
HAVING SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='150' THEN HISTORICOS.VALOR ELSE 0 END)>0
ORDER BY NOMBRECOMPLETO