SELECT 
  PERSONAL.ID_DE_EMPLEADO,
   TRIM(APELLIDO1) || ' ' || TRIM(APELLIDO2) || ' ' || TRIM(NOMBRES) AS NOMCOMPLETO,
      PERSONAL.NUMERO_DCTO AS NUMERO_DCTO,
      TO_CHAR(PERSONAL.FECHA_DE_INGRESO,'DD/MM/YYYY') AS FECHA_DE_INGRESO,
       PERSONAL.FECHATERCONTRATO AS FECHATERCONTRATO,
        CENTRO_COSTO.NOMBRE AS NOMBRE_CENTRO_DE_COSTO,
        CARGOS.NOMBRE_DEL_CARGO,
        HISTORICOS.ID_DE_PROCESO,
        HISTORICOS.ANO, HISTORICOS.MES,
        HISTORICOS.PERIODO,
        SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='158' THEN HISTORICOS.VALOR ELSE 0 END ) AS PRIMANAV, 
        SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='930' THEN HISTORICOS.VALOR ELSE 0 END ) AS SUELDOPRIMADIC,
         SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='931' THEN HISTORICOS.VALOR ELSE 0 END) AS PRIMASEMESTRAL,
         SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='159' THEN HISTORICOS.VALOR ELSE 0 END ) AS PRIMADIC,
         SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='932' THEN HISTORICOS.VALOR ELSE 0 END) AS PRIMAVAC, 
         SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='933' THEN HISTORICOS.VALOR ELSE 0 END) AS TRANSPRIMADIC,
         SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='934' THEN HISTORICOS.VALOR ELSE 0 END) AS ALIMENPRIMADIC,
        SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='935' THEN HISTORICOS.VALOR ELSE 0 END) AS GASTOSREP,
        SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='939' THEN HISTORICOS.VALOR ELSE 0 END) AS BON,
        SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='940' THEN HISTORICOS.VALOR ELSE 0 END) AS VPT,
        SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='936' THEN HISTORICOS.VALOR ELSE 0 END) AS DIASPRIMADIC,
        SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='937' THEN HISTORICOS.VALOR ELSE 0 END) AS DIASCOMPRIMADIC,
        SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='938' THEN HISTORICOS.VALOR ELSE 0 END) AS DIASLICPRIMADIC,
        SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='942' THEN HISTORICOS.VALOR ELSE 0 END) AS EXTRAS,
        SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='140' THEN HISTORICOS.VALOR ELSE 0 END) AS DESCUENTOS,
        SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='144' THEN HISTORICOS.VALOR ELSE 0 END) AS NETO, 
        SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='150' THEN HISTORICOS.VALOR ELSE 0 END) AS BASP,
        0 AS CERO, 
        CENTRO_COSTO.CODIGO AS ID_CENTRO_DE_COSTO,
        SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='170' THEN HISTORICOS.VALOR ELSE 0 END) AS PANTIG,
        SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='605' THEN HISTORICOS.VALOR ELSE 0 END) AS C605,
        SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='614' THEN HISTORICOS.VALOR ELSE 0 END) AS C614,
        SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='947' THEN HISTORICOS.VALOR ELSE 0 END) AS EXTRASPSEM
FROM HISTORICOS 
	LEFT JOIN PERSONAL
	ON HISTORICOS.COMPANIA = PERSONAL.COMPANIA
	AND HISTORICOS.ID_DE_EMPLEADO = PERSONAL.ID_DE_EMPLEADO
LEFT JOIN DEPENDENCIA
ON PERSONAL.COMPANIA = DEPENDENCIA.COMPANIA 
AND PERSONAL.DEPENDENCIA = DEPENDENCIA.CODIGO
LEFT JOIN CARGOS 
ON PERSONAL.COMPANIA = CARGOS.COMPANIA
AND PERSONAL.ID_DE_CARGO = CARGOS.ID_DE_CARGO
LEFT JOIN CENTRO_COSTO 
ON PERSONAL.COMPANIA = CENTRO_COSTO.COMPANIA
 AND PERSONAL.ID_CENTRO_DE_COSTO = CENTRO_COSTO.CODIGO
 AND PERSONAL.ANO= CENTRO_COSTO.ANO
WHERE (HISTORICOS.ID_DE_CONCEPTO='158'
 OR HISTORICOS.ID_DE_CONCEPTO='930' 
 OR HISTORICOS.ID_DE_CONCEPTO='931' 
 OR HISTORICOS.ID_DE_CONCEPTO='932' 
 OR HISTORICOS.ID_DE_CONCEPTO='933' 
 OR HISTORICOS.ID_DE_CONCEPTO='934' 
 OR HISTORICOS.ID_DE_CONCEPTO='935' 
 OR HISTORICOS.ID_DE_CONCEPTO='936' 
 OR HISTORICOS.ID_DE_CONCEPTO='937' 
 OR HISTORICOS.ID_DE_CONCEPTO='938' 
 OR HISTORICOS.ID_DE_CONCEPTO='939' 
 OR HISTORICOS.ID_DE_CONCEPTO='940' 
 OR HISTORICOS.ID_DE_CONCEPTO='942' 
 OR HISTORICOS.ID_DE_CONCEPTO='140' 
 OR HISTORICOS.ID_DE_CONCEPTO='144' 
 OR HISTORICOS.ID_DE_CONCEPTO='159' 
 OR HISTORICOS.ID_DE_CONCEPTO='150' 
 OR HISTORICOS.ID_DE_CONCEPTO='140' 
 OR HISTORICOS.ID_DE_CONCEPTO='097'
 OR HISTORICOS.ID_DE_CONCEPTO='163' 
 OR HISTORICOS.ID_DE_CONCEPTO='170' 
 OR HISTORICOS.ID_DE_CONCEPTO='160' 
 OR HISTORICOS.ID_DE_CONCEPTO='605' 
 OR HISTORICOS.ID_DE_CONCEPTO='614' 
 OR HISTORICOS.ID_DE_CONCEPTO='947' )
AND HISTORICOS.COMPANIA=s$compania$s
AND HISTORICOS.ID_DE_PROCESO=s$proceso$s
AND HISTORICOS.ANO=s$anio$s
AND HISTORICOS.MES=s$mes$s
AND HISTORICOS.PERIODO=s$periodo$s
GROUP BY 
PERSONAL.ID_DE_EMPLEADO, 
 TRIM(APELLIDO1) || ' ' || TRIM(APELLIDO2) || ' ' || TRIM(NOMBRES), 
PERSONAL.NUMERO_DCTO, 
PERSONAL.FECHA_DE_INGRESO, 
PERSONAL.FECHATERCONTRATO, 
CENTRO_COSTO.NOMBRE,  
CARGOS.NOMBRE_DEL_CARGO, 
HISTORICOS.ID_DE_PROCESO, 
HISTORICOS.ANO, 
HISTORICOS.MES, 
HISTORICOS.PERIODO, 
CENTRO_COSTO.CODIGO, 
DEPENDENCIA.NOMBRE
HAVING SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO= '158' THEN HISTORICOS.VALOR ELSE 0 END)>0
AND SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO= '144' THEN HISTORICOS.VALOR ELSE 0 END)>0
