SELECT PERSONAL.ID_DE_EMPLEADO, 
TRIM(APELLIDO1) || ' ' || TRIM(APELLIDO2) || ' ' || TRIM(NOMBRES) AS NOMCOMPLETO, 
PERSONAL.FONDO_CESANTIAS, 
PERSONAL.NUMERO_DCTO, 
TO_CHAR(PERSONAL.FECHA_DE_INGRESO,'DD/MM/YYYY') AS FECHA_DE_INGRESO,
CENTRO_COSTO.NOMBRE AS NOMBRE_CENTRO_DE_COSTO, 
DEPENDENCIA.NOMBRE, 
CARGOS.NOMBRE_DEL_CARGO, 
CARGOS.CODIGOCARGO, 
CARGOS.GRADO, 
HISTORICOS.ID_DE_PROCESO, 
HISTORICOS.ANO, 
HISTORICOS.MES, 
HISTORICOS.PERIODO, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='277' THEN HISTORICOS.VALOR ELSE 0 END)+SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='483' THEN HISTORICOS.VALOR ELSE 0 END) AS CES, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='169' THEN HISTORICOS.VALOR ELSE 0 END) AS INTCES, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='901' THEN HISTORICOS.VALOR ELSE 0 END) AS SUELDOCES, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='906' THEN HISTORICOS.VALOR ELSE 0 END) AS ANTIGUEDAD, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='908' THEN HISTORICOS.VALOR ELSE 0 END) AS GASTOS, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='903' THEN HISTORICOS.VALOR ELSE 0 END) AS TRANSCES, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='904' THEN HISTORICOS.VALOR ELSE 0 END) AS ALIMENCES, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='902' THEN HISTORICOS.VALOR ELSE 0 END) AS PRIMANAVCES, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='988' THEN HISTORICOS.VALOR ELSE 0 END) AS PRIMAJUNCES, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='907' THEN HISTORICOS.VALOR ELSE 0 END) AS PRIMAVACCES, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='913' THEN HISTORICOS.VALOR ELSE 0 END) AS PRIMATEC, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='914' THEN HISTORICOS.VALOR ELSE 0 END) AS BONIF, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='913' THEN HISTORICOS.VALOR ELSE 0 END) AS SUELDOBASE, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='905' THEN HISTORICOS.VALOR ELSE 0 END) AS PRIMALOCCES, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='909' THEN HISTORICOS.VALOR ELSE 0 END) AS QUINQUENIOCES, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='956' THEN HISTORICOS.VALOR ELSE 0 END) AS DIASCES, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='277' THEN HISTORICOS.VALOR ELSE 0 END)+SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='483' THEN HISTORICOS.VALOR ELSE 0 END)+SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='911' THEN HISTORICOS.VALOR ELSE 0 END) AS BASE, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='911' THEN HISTORICOS.VALOR ELSE 0 END) AS ANTICIPOSCES, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='911' THEN HISTORICOS.VALOR ELSE 0 END)+SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='277' THEN HISTORICOS.VALOR ELSE 0 END)+SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='483' THEN HISTORICOS.VALOR ELSE 0 END) AS SOBTOTAL, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='912' THEN HISTORICOS.VALOR ELSE 0 END) AS DIASLICCES, 
ROUND(SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='988' THEN HISTORICOS.VALOR ELSE 0 END)/12,0) AS DOCPJUN, 
ROUND(SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='907' THEN HISTORICOS.VALOR ELSE 0 END)/12,0) AS DOCPVAC, 
ROUND(SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='909' THEN HISTORICOS.VALOR ELSE 0 END)/12,0) AS DOCQUIN, 
ROUND(SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='902' THEN HISTORICOS.VALOR ELSE 0 END)/12,0) AS DOCPNAV, 
ROUND(SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='914' THEN HISTORICOS.VALOR ELSE 0 END)/12,0) AS DOCBON, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='913' THEN HISTORICOS.VALOR ELSE 0 END) AS PROMEDIOCES, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='912' THEN HISTORICOS.VALOR ELSE 0 END)+SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='956' THEN HISTORICOS.VALOR ELSE 0 END) AS TOTALDIAS, 
MAX(TO_CHAR(HISTORICOS.FECHA,'DD/MM/YYYY')) AS FECHALIQ, 
PERSONAL.ID_CENTRO_DE_COSTO, 
TO_CHAR(PERSONAL.FECHA_DE_RETIRO,'DD/MM/YYYY') AS FECHA_DE_RETIRO,
0 AS RECARGOCES, 
0 AS EXTRASCES, 
PERSONAL.ID_DE_CARGOESCALERA,
PERSONAL.ID_DE_CARGO_TEMPORAL, 
CARGOSE.NOMBRE_DEL_CARGO AS NOMBRE_DEL_CARGO_ESCALERA, 
CARGOST.NOMBRE_DEL_CARGO AS NOMBRE_DEL_CARGOTEMPORAL,
PERSONAL.ID_DE_CARGO
FROM HISTORICOS
LEFT JOIN PERSONAL 
ON PERSONAL.COMPANIA = HISTORICOS. COMPANIA
AND PERSONAL.ID_DE_EMPLEADO = HISTORICOS.ID_DE_EMPLEADO
LEFT JOIN DEPENDENCIA
ON DEPENDENCIA.CODIGO = PERSONAL.DEPENDENCIA
AND DEPENDENCIA.COMPANIA = PERSONAL.COMPANIA
LEFT JOIN CENTRO_COSTO 
ON CENTRO_COSTO.CODIGO = PERSONAL.ID_CENTRO_DE_COSTO 
AND CENTRO_COSTO.COMPANIA = PERSONAL.COMPANIA
AND CENTRO_COSTO.ANO = HISTORICOS.ANO
LEFT JOIN CARGOS CARGOST
ON CARGOST.ID_DE_CARGO  = PERSONAL.ID_DE_CARGO_TEMPORAL 
AND CARGOST.COMPANIA    = PERSONAL.COMPANIA
LEFT JOIN CARGOS CARGOSE
ON CARGOSE.ID_DE_CARGO  = PERSONAL.ID_DE_CARGOESCALERA 
AND CARGOSE.COMPANIA    = PERSONAL.COMPANIA
LEFT JOIN CARGOS 
ON CARGOS.ID_DE_CARGO = PERSONAL.ID_DE_CARGO 
AND CARGOS.COMPANIA=PERSONAL.COMPANIA
LEFT JOIN V_FONDO_DE_CESANTIAS 
ON V_FONDO_DE_CESANTIAS.FONDO_CESANTIAS = PERSONAL.FONDO_CESANTIAS
WHERE 
(HISTORICOS.ID_DE_CONCEPTO='169' 
OR HISTORICOS.ID_DE_CONCEPTO='169' 
OR HISTORICOS.ID_DE_CONCEPTO='177' 
OR HISTORICOS.ID_DE_CONCEPTO='277' 
OR HISTORICOS.ID_DE_CONCEPTO='169' 
OR HISTORICOS.ID_DE_CONCEPTO='169' 
OR HISTORICOS.ID_DE_CONCEPTO='900' 
OR HISTORICOS.ID_DE_CONCEPTO='901' 
OR HISTORICOS.ID_DE_CONCEPTO='902' 
OR HISTORICOS.ID_DE_CONCEPTO='903' 
OR HISTORICOS.ID_DE_CONCEPTO='904' 
OR HISTORICOS.ID_DE_CONCEPTO='905' 
OR HISTORICOS.ID_DE_CONCEPTO='906' 
OR HISTORICOS.ID_DE_CONCEPTO='907' 
OR HISTORICOS.ID_DE_CONCEPTO='908' 
OR HISTORICOS.ID_DE_CONCEPTO='909' 
OR HISTORICOS.ID_DE_CONCEPTO='956' 
OR HISTORICOS.ID_DE_CONCEPTO='988' 
OR HISTORICOS.ID_DE_CONCEPTO='911' 
OR HISTORICOS.ID_DE_CONCEPTO='912' 
OR HISTORICOS.ID_DE_CONCEPTO='913' 
OR HISTORICOS.ID_DE_CONCEPTO='914' 
OR HISTORICOS.ID_DE_CONCEPTO='913' 
OR HISTORICOS.ID_DE_CONCEPTO='177' 
OR HISTORICOS.ID_DE_CONCEPTO='177' 
OR HISTORICOS.ID_DE_CONCEPTO='483')
AND HISTORICOS.ANO=s$anioNomina$s
AND HISTORICOS.MES=s$mesNomina$s
AND HISTORICOS.PERIODO=s$periodoNomina$s
AND HISTORICOS.ID_DE_PROCESO=s$procesoNomina$s
GROUP BY PERSONAL.ID_DE_EMPLEADO, 
TRIM(APELLIDO1) || ' ' || TRIM(APELLIDO2) || ' ' || TRIM(NOMBRES), 
PERSONAL.FONDO_CESANTIAS, 
PERSONAL.NUMERO_DCTO, 
PERSONAL.FECHA_DE_INGRESO, 
CENTRO_COSTO.NOMBRE,  
DEPENDENCIA.NOMBRE, 
CARGOS.NOMBRE_DEL_CARGO, 
CARGOS.CODIGOCARGO, 
CARGOS.GRADO, 
HISTORICOS.ID_DE_PROCESO, 
HISTORICOS.ANO, 
HISTORICOS.MES, 
HISTORICOS.PERIODO, 
PERSONAL.ID_CENTRO_DE_COSTO, 
CARGOS.NOMBRE_DEL_CARGO, 
CARGOS.CODIGOCARGO, 
CARGOS.GRADO, 
PERSONAL.FECHA_DE_RETIRO, 
PERSONAL.ID_DE_CARGOESCALERA,
PERSONAL.ID_DE_CARGO_TEMPORAL, 
CARGOSE.NOMBRE_DEL_CARGO, 
CARGOST.NOMBRE_DEL_CARGO,
PERSONAL.ID_DE_CARGO
HAVING PERSONAL.FONDO_CESANTIAS>='1' 	
AND SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='277' THEN HISTORICOS.VALOR ELSE 0 END)+SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO='483' THEN HISTORICOS.VALOR ELSE 0 END)<>0
ORDER BY TRIM(APELLIDO1) || ' ' || TRIM(APELLIDO2) || ' ' || TRIM(NOMBRES)