MERGE INTO CONSULTAS FIN USING (SELECT '002364ListadoParafiscalesDependenciasAgrupado' INFORME ,TO_CLOB(q'[SELECT 	HISTORICOS.COMPANIA, 
		HISTORICOS.ID_DE_PROCESO, 
		HISTORICOS.ANO, 
		PCK_SYSMAN_UTL.FC_NOMBRE_MES(HISTORICOS.MES) AS MES, 
		SUM(DECODE(HISTORICOS.ID_DE_CONCEPTO,108,VALOR,0)) AS FACTOR, 
		SUM(DECODE(HISTORICOS.ID_DE_CONCEPTO,107,VALOR,0)) AS FACTOR1, 
		SUM(DECODE(HISTORICOS.ID_DE_CONCEPTO,101,VALOR,0)) AS COMPENSACION, 
		SUM(DECODE(HISTORICOS.ID_DE_CONCEPTO,102,VALOR,0)) AS BIENESTAR, 
		SUM(DECODE(HISTORICOS.ID_DE_CONCEPTO,103,VALOR,0)) AS SENA, 
		SUM(DECODE(HISTORICOS.ID_DE_CONCEPTO,104,VALOR,0)) AS ESAP, 
		SUM(DECODE(HISTORICOS.ID_DE_CONCEPTO,105,VALOR,0)) AS INSTITUTOS, 
		PERSONAL.DEPENDENCIA CODIGO, 
		DEPENDENCIA.NOMBRE NOMBRE, 
		SUBSTR(DEPENDENCIA.NOMBRE,1,INSTR(DEPENDENCIA.NOMBRE,' ')) DEPTO,
		PCK_SYSMAN_UTL.FC_ROUND(
					(SUM(DECODE(HISTORICOS.ID_DE_CONCEPTO,108,VALOR,0))*9/100)- 
					(
					SUM(DECODE(HISTORICOS.ID_DE_CONCEPTO,101,VALOR,0)) + 
					SUM(DECODE(HISTORICOS.ID_DE_CONCEPTO,102,VALOR,0)) +
					SUM(DECODE(HISTORICOS.ID_DE_CONCEPTO,103,VALOR,0)) +
					SUM(DECODE(HISTORICOS.ID_DE_CONCEPTO,104,VALOR,0)) +
					SUM(DECODE(HISTORICOS.ID_DE_CONCEPTO,105,VALOR,0)) 
					)
					,0
					)  AS AJUSTECALCULO 
  FROM 	HISTORICOS 	INNER JOIN PERSONAL ON  HISTORICOS.COMPANIA = PERSONAL.COMPANIA 
											AND HISTORICOS.ID_DE_EMPLEADO = PERSONAL.ID_DE_EMPLEADO 
					INNER JOIN DEPENDENCIA ON DEPENDENCIA.COMPANIA   = PERSONAL.COMPANIA 
											AND DEPENDENCIA.CODIGO     = PERSONAL.DEPENDENCIA 
 
 WHERE  HISTORICOS.COMPANIA				= 's$compania$s' 
		AND HISTORICOS.ID_DE_PROCESO    = s$procesoNomina$s
		AND HISTORICOS.ANO              = s$anioNomina$s
		AND HISTORICOS.MES              = s$mesNomina$s
		AND HISTORICOS.ID_DE_CONCEPTO   IN (101 ,102,103,104,105,108,107)  
 GROUP BY 	HISTORICOS.COMPANIA, 
			HISTORICOS.ID_DE_PROCESO, 
			HISTORICOS.ANO, 
			HISTORICOS.MES, 
			PERSONAL.DEPENDENCIA, 
			DEPENDENCIA.NOMBRE
 ORDER BY DEPENDENCIA.NOMBRE]') CONSULTA, 6 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);