MERGE INTO CONSULTAS FIN USING (SELECT '00249LISTADOPARAFISCALESSTRNUEVOCCOK' INFORME ,TO_CLOB(q'[SELECT COMPA1
      ,ANIO2
      ,NOMBREMES
      ,PERI
      ,PROCESO
      ,FACTOR
      ,FACTOR_PARAFISCAL
      ,NOMBRE_CONCEPTO
      ,CONCEPTO
      ,CENTRO_COSTO
      ,NOMBRE_CENTRO_COSTO
      ,COMPENSACION
      ,BIENESTAR
      ,SENA
      ,ESAP
      ,INSTITUTOS
      ,BASEPARAFISCAL
      ,REDONDEAR
FROM HISTORICOS
LEFT JOIN (
SELECT  
HISTORICOS.ANO ANIO2, 
HISTORICOS.MES MESRE,
UPPER(PCK_SYSMAN_UTL.FC_NOMBRE_MES(MES))  NOMBREMES,
HISTORICOS.PERIODO PERI,
HISTORICOS.ID_DE_PROCESO PROCESO,
SUM(HISTORICOS.VALOR) AS FACTOR, 
CONCEPTOS.FACTOR_PARAFISCAL,
CONCEPTOS.NOMBRE_CONCEPTO, 
HISTORICOS.ID_DE_CONCEPTO CONCEPTO,
CENTRO_COSTO.CODIGO CENTRO_COSTO,
CENTRO_COSTO.NOMBRE NOMBRE_CENTRO_COSTO,
HISTORICOS.COMPANIA COMPA1
FROM ((HISTORICOS 
LEFT JOIN CONCEPTOS 
ON (HISTORICOS.ID_DE_CONCEPTO = CONCEPTOS.ID_DE_CONCEPTO) 
AND (HISTORICOS.COMPANIA = CONCEPTOS.COMPANIA)) 
LEFT JOIN PERSONAL 
ON (HISTORICOS.COMPANIA = PERSONAL.COMPANIA) 
AND (HISTORICOS.ID_DE_EMPLEADO = PERSONAL.ID_DE_EMPLEADO)) 
LEFT JOIN CENTRO_COSTO 
ON (PERSONAL.COMPANIA = CENTRO_COSTO.COMPANIA)
AND PERSONAL.ANO = CENTRO_COSTO.ANO
AND (PERSONAL.ID_CENTRO_DE_COSTO = CENTRO_COSTO.CODIGO)
WHERE (((CONCEPTOS.CLASE)=3
OR (CONCEPTOS.CLASE)=8))
AND HISTORICOS.ID_DE_PROCESO =s$proceso$s
AND HISTORICOS.ANO = s$ano1$s
AND HISTORICOS.MES = s$mes1$s
AND HISTORICOS.PERIODO = s$periodo1$s
AND CONCEPTOS.FACTOR_PARAFISCAL <>0
s$centroP$s
AND HISTORICOS.COMPANIA =s$compania$s
GROUP BY HISTORICOS.ID_DE_PROCESO,
HISTORICOS.ANO, HISTORICOS.MES,
HISTORICOS.PERIODO, 
CONCEPTOS.FACTOR_PARAFISCAL,
CONCEPTOS.NOMBRE_CONCEPTO,
HISTORICOS.ID_DE_CONCEPTO, 
CENTRO_COSTO.CODIGO,
CENTRO_COSTO.NOMBRE, 
HISTORICOS.COMPANIA
)PRUEBA
    ON HISTORICOS.COMPANIA = PRUEBA.COMPA1
    AND HISTORICOS.ANO = PRUEBA.ANIO2 
    AND HISTORICOS.ID_DE_PROCESO = PRUEBA.PROCESO
LEFT JOIN(
SELECT HISTORICOS.COMPANIA,
CENTRO_COSTO.CODIGO,
CENTRO_COSTO.NOMBRE NOMBRE_CENTROCOSTO,
HISTORICOS.ID_DE_PROCESO,
HISTORICOS.ANO,
HISTORICOS.MES, 
HISTORICOS.PERIODO, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = '101' THEN VALOR ELSE 0 END) AS COMPENSACION,
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = '102' THEN VALOR ELSE 0 END) AS BIENESTAR, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = '103' THEN VALOR ELSE 0 END) AS SENA, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = '104' THEN VALOR ELSE 0 END) AS ESAP, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = '105' THEN VALOR ELSE 0 END) AS INSTITUTOS, 
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = '108' THEN VALOR ELSE 0 END) AS BASEPARAFISCAL,
  ROUND(SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = '101' THEN VALOR ELSE 0 END ) +
              SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = '102' THEN VALOR ELSE 0 END ) +
              SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = '103' THEN VALOR ELSE 0 END ) +
              SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = '105' THEN VALOR ELSE 0 END ) +
              SUM(CASE WHEN HISTORICOS.ID_DE_CONC]') || TO_CLOB(q'[EPTO = '104' THEN VALOR ELSE 0 END ) ,0) AS REDONDEAR
FROM HISTORICOS 
LEFT JOIN PERSONAL
ON HISTORICOS.COMPANIA = PERSONAL.COMPANIA 
AND HISTORICOS.ID_DE_EMPLEADO = PERSONAL.ID_DE_EMPLEADO 
LEFT JOIN CENTRO_COSTO 
ON (PERSONAL.COMPANIA = CENTRO_COSTO.COMPANIA)
AND PERSONAL.ANO = CENTRO_COSTO.ANO
AND (PERSONAL.ID_CENTRO_DE_COSTO = CENTRO_COSTO.CODIGO)
WHERE 
 HISTORICOS.COMPANIA = s$compania$s 
AND HISTORICOS.ANO = s$ano1$s
AND HISTORICOS.MES = s$mes1$s
AND HISTORICOS.PERIODO =s$periodo1$s
s$centroP$s
AND HISTORICOS.ID_DE_CONCEPTO IN (101, 102, 103, 104, 105, 108)
GROUP BY HISTORICOS.COMPANIA,
CENTRO_COSTO.CODIGO, 
CENTRO_COSTO.NOMBRE,
HISTORICOS.ID_DE_PROCESO, 
HISTORICOS.ANO, HISTORICOS.MES, 
HISTORICOS.PERIODO) CONCEPT
       ON PRUEBA.COMPA1 = CONCEPT.COMPANIA
    AND PRUEBA.ANIO2 = CONCEPT.ANO 
    AND PRUEBA.CENTRO_COSTO = CONCEPT.CODIGO
WHERE  HISTORICOS.COMPANIA = s$compania$s
    AND HISTORICOS.ANO = s$ano1$s
    AND HISTORICOS.MES = s$mes1$s
    AND HISTORICOS.PERIODO = s$periodo1$s
    --AND PRUEBA.CENTRO_COSTO = s$CentroCosto$s
    AND HISTORICOS.ID_DE_PROCESO = s$proceso$s
GROUP BY COMPA1
      ,ANIO2
      ,NOMBREMES
      ,PERI
      ,PROCESO
      ,FACTOR
      ,FACTOR_PARAFISCAL
      ,NOMBRE_CONCEPTO
      ,CONCEPTO
      ,CENTRO_COSTO
      ,NOMBRE_CENTRO_COSTO
      ,COMPENSACION
      ,BIENESTAR
      ,SENA
      ,ESAP
      ,INSTITUTOS
      ,BASEPARAFISCAL
      ,REDONDEAR
ORDER BY CONCEPTO ASC]') CONSULTA, 6 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);