MERGE INTO CONSULTAS FIN USING (SELECT '002469PlanillaPensionxCDC' INFORME ,TO_CLOB(q'[SELECT  V_FONDO_DE_PENSIONES.NOMBRE_DEL_FONDO,
        V_FONDO_DE_PENSIONES.ID_DEL_FONDO AS ID_DEL_FONDO,
        V_ACUMULADOS.ID_CENTRO_DE_COSTO AS IDCENTROCOSTO,
        V_ACUMULADOS.NOMBRE_CENTRO_DE_COSTO AS NOMCENTROCOSTO,
        V_ACUMULADOS.NUMERO_DCTO          AS CEDULA,
        V_ACUMULADOS.NOMBRECOMPLETO       AS NOM_EMPLEADO,
        V_ACUMULADOS.SALARIO_BASE_IBC     AS SALARIO_BASE_IBC,
        V_ACUMULADOS.COMPANIA,
        V_ACUMULADOS.ID_DE_PROCESO                     AS ID_DE_PROCESO,
        V_ACUMULADOS.ANO                               AS ANO,
        PCK_SYSMAN_UTL.FC_NOMBRE_MES(V_ACUMULADOS.MES) AS MES,
        V_ACUMULADOS.COMPANIA                          AS COMPANIAHFA,
        SUM(DECODE(V_ACUMULADOS.ID_DE_CONCEPTO,134,V_ACUMULADOS.VALOR,0)) AS C134,
        SUM(DECODE(V_ACUMULADOS.ID_DE_CONCEPTO,112,V_ACUMULADOS.VALOR,0)) AS C112,
        SUM(DECODE(V_ACUMULADOS.ID_DE_CONCEPTO,117,V_ACUMULADOS.VALOR,0)) AS C117,
        SUM(DECODE(V_ACUMULADOS.ID_DE_CONCEPTO,118,V_ACUMULADOS.VALOR,0)) AS C118,
        SUM(DECODE(V_ACUMULADOS.ID_DE_CONCEPTO,115,V_ACUMULADOS.VALOR,0)) AS C115,
        SUM(DECODE(V_ACUMULADOS.ID_DE_CONCEPTO,120,V_ACUMULADOS.VALOR,0)) AS C120,
        SUM(DECODE(V_ACUMULADOS.ID_DE_CONCEPTO,124,V_ACUMULADOS.VALOR,0)) AS C124,
        SUM(DECODE(V_ACUMULADOS.ID_DE_CONCEPTO,131,V_ACUMULADOS.VALOR,0)) AS C131,
        SUM(CASE WHEN V_ACUMULADOS.ID_DE_CONCEPTO IN (117,118,124) THEN V_ACUMULADOS.VALOR ELSE 0 END) AS C117C118,
        SUM(DECODE(V_ACUMULADOS.ID_DE_CONCEPTO,131,V_ACUMULADOS.VALOR,118,V_ACUMULADOS.VALOR,0)) AS C131YC118,
        SUM(CASE WHEN V_ACUMULADOS.ID_DE_CONCEPTO IN (117,118,124,115,120) THEN V_ACUMULADOS.VALOR ELSE 0 END ) AS TOTAL,
        V_ACUMULADOS.ID_DE_EMPLEADO,
        V_FONDO_DE_PENSIONES.CODAIFP,
        V_FONDO_DE_PENSIONES.NIT
FROM    V_ACUMULADOS
        INNER JOIN V_FONDO_DE_PENSIONES
            ON V_ACUMULADOS.COMPANIA         = V_FONDO_DE_PENSIONES.COMPANIA
            AND V_ACUMULADOS.FONDO_PENSION   = V_FONDO_DE_PENSIONES.ID_DEL_FONDO
WHERE   V_ACUMULADOS.COMPANIA      =s$compania$s
		AND V_ACUMULADOS.ID_DE_CONCEPTO IN (112,131,132,134,117,118,115,120)
		AND V_ACUMULADOS.ID_DE_PROCESO   = s$procesoNomina$s
		AND V_ACUMULADOS.ANO             = s$anioNomina$s
		AND V_ACUMULADOS.MES             =s$mesNomina$s
		AND V_ACUMULADOS.PERIODO         =s$periodoNomina$s
GROUP BY V_FONDO_DE_PENSIONES.NOMBRE_DEL_FONDO,
        V_FONDO_DE_PENSIONES.ID_DEL_FONDO,
        V_ACUMULADOS.ID_CENTRO_DE_COSTO,
        V_ACUMULADOS.NOMBRE_CENTRO_DE_COSTO,
        V_ACUMULADOS.NUMERO_DCTO ,
        V_ACUMULADOS.NOMBRECOMPLETO ,
        V_ACUMULADOS.SALARIO_BASE_IBC,
        V_ACUMULADOS.COMPANIA,
        V_ACUMULADOS.ID_DE_PROCESO,
        V_ACUMULADOS.ANO ,
        V_ACUMULADOS.MES,
        V_ACUMULADOS.COMPANIA,
        V_ACUMULADOS.ID_DE_EMPLEADO,
        V_FONDO_DE_PENSIONES.CODAIFP,
        V_FONDO_DE_PENSIONES.NIT
ORDER BY V_FONDO_DE_PENSIONES.ID_DEL_FONDO, V_ACUMULADOS.ID_CENTRO_DE_COSTO, LPAD(V_ACUMULADOS.NUMERO_DCTO,30,'0')]') CONSULTA, 6 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);
COMMIT;
