MERGE INTO CONSULTAS FIN USING (SELECT '002411PlanillaDevengosEstandar' INFORME ,TO_CLOB(q'[SELECT DISTINCT
PERSONAL.FONDO_SALUD,
PERSONAL.FONDO_RIESGOS,
s$companiaNombre$s NOMBRE_EMPRESA,
PERSONAL.ID_DEL_FONDO, 
V_FONDO_DE_PENSIONES.NOMBRE_DEL_FONDO,
V_FONDO_DE_RIESGOS.NOMBRE_FONDO_RIESGOS, 
V_FONDO_DE_SALUD.NOMBRE_FONDO_SALUD,
PERSONAL.DEPENDENCIA  DEPENDENCIA,
DEPENDENCIA.NOMBRE  NOMBREDEPENDENCIA, 
PERSONAL.SALARIO_BASE_IBC  SALARIO_BASE_IBC, 
HISTORICOS.ID_DE_PROCESO  PROCESO,
HISTORICOS.ANO  ANO,
HISTORICOS.MES  MES, 
PCK_SYSMAN_UTL.FC_NOMBRE_MES(Historicos.MES)  NOMBRE_MES,
PERSONAL.ID_DE_CARGO  CARGO,
CARGOS.NOMBRE_DEL_CARGO  NOMBRECARGO,
HISTORICOS.PERIODO  PERIODO, 
PERSONAL.NOMBRECOMPLETO  NOM_EMPLEADO,
PERSONAL.NUMERO_DCTO  CEDULA, 
SUM(CASE WHEN CONCEPTOS.CLASE = 3 THEN HISTORICOS.VALOR ELSE 0 END) DEVENGOS,
SUM(CASE WHEN CONCEPTOS.CLASE = 5 THEN HISTORICOS.VALOR ELSE 0 END) DESCUENTOS,
CENTRO_COSTO.CODIGO  ID_CENTRO_COSTO,
CENTRO_COSTO.NOMBRE  NOMBRE_CENTRO_COSTO,
SUM(CASE WHEN CONCEPTOS.CLASE = 3 THEN HISTORICOS.VALOR ELSE 0 END) -
SUM(CASE WHEN CONCEPTOS.CLASE = 5 THEN HISTORICOS.VALOR ELSE 0 END) NETO,
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = '109' THEN HISTORICOS.VALOR ELSE 0 END) AS PORRIESGO,
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = '111' THEN HISTORICOS.VALOR ELSE 0 END) AS C111,
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = '209' THEN HISTORICOS.VALOR ELSE 0 END) AS C209,
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = '212' THEN HISTORICOS.VALOR ELSE 0 END) AS C212,
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('155') THEN HISTORICOS.VALOR ELSE 0 END)  AS "C155",
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('150') THEN HISTORICOS.VALOR ELSE 0 END)  AS "C150",
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('151') THEN HISTORICOS.VALOR ELSE 0 END)  AS "C151",
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('123') THEN HISTORICOS.VALOR ELSE 0 END)  AS "C123",
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('175') THEN HISTORICOS.VALOR ELSE 0 END)  AS "C175",
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('362') THEN HISTORICOS.VALOR ELSE 0 END)  AS "C362",
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('174') THEN HISTORICOS.VALOR ELSE 0 END)  AS "C174",
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('001') THEN HISTORICOS.VALOR ELSE 0 END)  AS "C001",
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('178') THEN HISTORICOS.VALOR ELSE 0 END)  AS "C178",
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('799') THEN HISTORICOS.VALOR ELSE 0 END)  AS "C799",
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('132') THEN HISTORICOS.VALOR ELSE 0 END)  AS "C132",
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('131') THEN HISTORICOS.VALOR ELSE 0 END)  AS "C131",
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('079') THEN HISTORICOS.VALOR ELSE 0 END)  AS "C079",
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN ('009') THEN HISTORICOS.VALOR ELSE 0 END)  AS "C009",
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (144) THEN HISTORICOS.VALOR ELSE 0 END)  AS "C144",
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (140) THEN HISTORICOS.VALOR ELSE 0 END)  AS "C140",
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPT]') || TO_CLOB(q'[O IN (097) THEN HISTORICOS.VALOR ELSE 0 END)  AS "C097",
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (699) THEN HISTORICOS.VALOR ELSE 0 END)  +
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (124) THEN HISTORICOS.VALOR ELSE 0 END)  +
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (127) THEN HISTORICOS.VALOR ELSE 0 END)  +
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (129) THEN HISTORICOS.VALOR ELSE 0 END)  AS "C699",
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (125) THEN HISTORICOS.VALOR ELSE 0 END)  AS "C125",
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (130) THEN HISTORICOS.VALOR ELSE 0 END)  AS "C130",
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (002) THEN HISTORICOS.VALOR ELSE 0 END)  AS "C002",
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (080) THEN HISTORICOS.VALOR ELSE 0 END)  AS "C080",
SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (170) THEN HISTORICOS.VALOR ELSE 0 END)  AS "C170",
ESTABLECIMIENTOS_DOCENTES.CODIGO AS ID_FUENTE,
ESTABLECIMIENTOS_DOCENTES.NOMBRE AS FUENTE
FROM HISTORICOS 
LEFT JOIN PERIODOS 
ON HISTORICOS.PERIODO = PERIODOS.PERIODO
AND HISTORICOS.MES = PERIODOS.MES
AND HISTORICOS.ANO = PERIODOS.ANO
AND HISTORICOS.ID_DE_PROCESO = PERIODOS.ID_DE_PROCESO
AND HISTORICOS.COMPANIA = PERIODOS.COMPANIA
LEFT JOIN CONCEPTOS 
ON HISTORICOS.ID_DE_CONCEPTO = CONCEPTOS.ID_DE_CONCEPTO
AND HISTORICOS.COMPANIA = CONCEPTOS.COMPANIA
LEFT JOIN PERSONAL 
ON HISTORICOS.ID_DE_EMPLEADO = PERSONAL.ID_DE_EMPLEADO
AND HISTORICOS.COMPANIA = PERSONAL.COMPANIA
LEFT JOIN V_FONDO_DE_RIESGOS 
ON PERSONAL.FONDO_RIESGOS = V_FONDO_DE_RIESGOS.FONDO_RIESGOS 
AND PERSONAL.COMPANIA = V_FONDO_DE_RIESGOS.COMPANIA
LEFT JOIN V_FONDO_DE_PENSIONES 
ON PERSONAL.ID_DEL_FONDO = V_FONDO_DE_PENSIONES.ID_DEL_FONDO
AND PERSONAL.COMPANIA = V_FONDO_DE_PENSIONES.COMPANIA
LEFT JOIN V_FONDO_DE_SALUD 
ON PERSONAL.FONDO_SALUD = V_FONDO_DE_SALUD.FONDO_SALUD
AND PERSONAL.COMPANIA = V_FONDO_DE_SALUD.COMPANIA 
LEFT JOIN DEPENDENCIA 
ON PERSONAL.DEPENDENCIA = DEPENDENCIA.CODIGO
AND PERSONAL.COMPANIA = DEPENDENCIA.COMPANIA
LEFT JOIN CARGOS
ON PERSONAL.ID_DE_CARGO = CARGOS.ID_DE_CARGO
AND PERSONAL.COMPANIA = CARGOS.COMPANIA
LEFT JOIN CENTRO_COSTO 
ON PERSONAL.ID_CENTRO_DE_COSTO = CENTRO_COSTO.CODIGO
AND PERSONAL.COMPANIA = CENTRO_COSTO.COMPANIA
AND CENTRO_COSTO.ANO = HISTORICOS.ANO
LEFT JOIN ESTABLECIMIENTOS_DOCENTES 
ON PERSONAL.COMPANIA = ESTABLECIMIENTOS_DOCENTES.COMPANIA 
AND PERSONAL.CODIGO_ESTABLECIMIENTO = ESTABLECIMIENTOS_DOCENTES.CODIGO
WHERE HISTORICOS.COMPANIA = s$compania$s
AND HISTORICOS.ID_DE_PROCESO = s$proceso$s
AND HISTORICOS.PERIODO = s$periodo$s
AND HISTORICOS.ANO = s$ano$s
AND HISTORICOS.MES = s$mes$s
AND PERIODOS.ACUMULADO NOT IN (0) 
AND HISTORICOS.ID_DE_CONCEPTO IN ('209','212', '111', '109','155','150','151','123','175','362','174','001','178','799','132','131','079','009','144','140','097','699','125','130','002','080','124','127','129','170')
GROUP BY PERSONAL.FONDO_SALUD, PERSONAL.FONDO_RIESGOS, PERSONAL.ID_DEL_FONDO, V_FONDO_DE_PENSIONES.NOMBRE_DEL_FONDO, V_FONDO_DE_RIESGOS.NOMBR]') || TO_CLOB(q'[E_FONDO_RIESGOS, 
V_FONDO_DE_SALUD.NOMBRE_FONDO_SALUD, PERSONAL.DEPENDENCIA, DEPENDENCIA.NOMBRE, PERSONAL.SALARIO_BASE_IBC, HISTORICOS.ID_DE_PROCESO, 
HISTORICOS.ANO, HISTORICOS.MES, PERSONAL.ID_DE_CARGO, CARGOS.NOMBRE_DEL_CARGO, HISTORICOS.PERIODO, 
PERSONAL.NOMBRECOMPLETO, PERSONAL.NUMERO_DCTO, CENTRO_COSTO.CODIGO, CENTRO_COSTO.NOMBRE, ESTABLECIMIENTOS_DOCENTES.CODIGO, 
ESTABLECIMIENTOS_DOCENTES.NOMBRE]') CONSULTA, 6 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);