MERGE INTO CONSULTAS FIN USING (SELECT '002760Planilla_cesantias_STR' INFORME ,TO_CLOB(q'[SELECT PERSONAL_HISTORICO.NOMBRECOMPLETO  NOMCOMPLETO,
       PERSONAL_HISTORICO.ANO,
       PERSONAL_HISTORICO.MES,
       PERSONAL_HISTORICO.ID_DE_EMPLEADO,      
       PERSONAL_HISTORICO.NUMERO_DCTO, 
       PERSONAL_HISTORICO.FECHA_DE_INGRESO, 
       PERSONAL_HISTORICO.FECHAFONDOCESANTIA, 
       PERSONAL_HISTORICO.REGIMEN REGIMEN, 
       PERSONAL_HISTORICO.ID_CENTRO_DE_COSTO,  
       PERSONAL_HISTORICO.NOMBRE_CENTRO_DE_COSTO,
       V_FONDO_DE_CESANTIAS.NIT, 
       V_FONDO_DE_CESANTIAS.NOMBRE_FONDO_CESANTIAS NOMBRE_FONDO_CESANTIAS,
       SUM(CASE WHEN  HISTORICOS.ID_DE_CONCEPTO = 277 THEN  HISTORICOS.VALOR ELSE 0 END) + 
       SUM(CASE WHEN  HISTORICOS.ID_DE_CONCEPTO = 483 THEN  HISTORICOS.VALOR ELSE 0  END)  +
       SUM(CASE WHEN  HISTORICOS.ID_DE_CONCEPTO = 484 THEN  HISTORICOS.VALOR ELSE 0 END)  CES,
       TRUNC ( SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = 910 THEN  HISTORICOS.VALOR ELSE 0 END))  DT, 
       SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = 911 THEN  HISTORICOS.VALOR ELSE 0 END)  ANT, 
       SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = 912 THEN  HISTORICOS.VALOR ELSE 0 END)  DNT,
       SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = 913 THEN  HISTORICOS.VALOR ELSE 0  END)  BASE,
       HISTORICOS.COMPANIA
       FROM HISTORICOS   
       LEFT JOIN PERSONAL_HISTORICO  
       ON HISTORICOS.COMPANIA = PERSONAL_HISTORICO.COMPANIA       
       AND HISTORICOS.ANO=PERSONAL_HISTORICO.ANO
       AND HISTORICOS.MES=PERSONAL_HISTORICO.MES 
       AND HISTORICOS.PERIODO=PERSONAL_HISTORICO.PERIODO
       AND  HISTORICOS.ID_DE_EMPLEADO = PERSONAL_HISTORICO.ID_DE_EMPLEADO          
       LEFT JOIN V_FONDO_DE_CESANTIAS  
       ON  PERSONAL_HISTORICO.COMPANIA = V_FONDO_DE_CESANTIAS.COMPANIA
       AND  PERSONAL_HISTORICO.FONDO_CESANTIAS = V_FONDO_DE_CESANTIAS.FONDO_CESANTIAS  
       WHERE HISTORICOS.ID_DE_CONCEPTO IN (277,910,911,912 ,913 ,269 ,483,484 ) 
       AND PERSONAL_HISTORICO.COMPANIA = s$compania$s 
       AND  HISTORICOS.ANO = s$ano$s
       AND HISTORICOS.MES =  s$mes$s
       AND PERSONAL_HISTORICO.REGIMEN IN (1,2)
       GROUP BY
       PERSONAL_HISTORICO.NOMBRECOMPLETO,
       PERSONAL_HISTORICO.ANO,
       PERSONAL_HISTORICO.MES,
       PERSONAL_HISTORICO.ID_DE_EMPLEADO,      
       PERSONAL_HISTORICO.NUMERO_DCTO, 
       PERSONAL_HISTORICO.FECHA_DE_INGRESO, 
       PERSONAL_HISTORICO.FECHAFONDOCESANTIA, 
       PERSONAL_HISTORICO.REGIMEN, 
       PERSONAL_HISTORICO.ID_CENTRO_DE_COSTO,  
       PERSONAL_HISTORICO.NOMBRE_CENTRO_DE_COSTO,
       V_FONDO_DE_CESANTIAS.NIT, 
       V_FONDO_DE_CESANTIAS.NOMBRE_FONDO_CESANTIAS,
       HISTORICOS.COMPANIA
       HAVING  
        (
           (SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = '277' THEN VALOR ELSE 0 END) + 
            SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = '483' THEN VALOR ELSE 0 END) + 
            SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = '484' THEN VALOR ELSE 0 END)) <> 0
        )]') CONSULTA, 6 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);