SELECT HISTORICOS.ANO,
        HISTORICOS.MES,
        HISTORICOS.ID_DE_EMPLEADO, 	
       (SUM(CASE WHEN CONCEPTOS.FACTOR_PARAFISCAL<>0 
 	   	  THEN HISTORICOS.VALOR 
 	   	  ELSE 0 
 	   	  END)) SUMAF,
        ( SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO=108 
 	   	  THEN HISTORICOS.VALOR 
 	   	  ELSE 0 
 	   	  END)) PARAF108, 
        PCK_SYSMAN_UTL.FC_ROUND(SUM(CASE WHEN CONCEPTOS.FACTOR_PARAFISCAL<>0 
                                  THEN HISTORICOS.VALOR 
                                  ELSE 0 
                                  END -
                                  CASE WHEN HISTORICOS.ID_DE_CONCEPTO=108 
 	                                THEN HISTORICOS.VALOR 
                                  ELSE 0 
 	                                END)
                                  +
                                  SUM(CASE WHEN PCK_SYSMAN_UTL.FC_PAR(PERSONAL_HISTORICO.COMPANIA,'AJUSTAR APORTES PARAFISCALES MES COMPLETO',6, SYSDATE)='SI'
                                  THEN (PERSONAL_HISTORICO.SALARIO_BASE_IBC/30*(CASE WHEN HISTORICOS.ID_DE_CONCEPTO=035 
                                                          THEN HISTORICOS.VALOR 
                                                          ELSE 0 
                                                          END)
                           ) ELSE 0 END
                    )- 
                   SUM (CASE WHEN PCK_SYSMAN_UTL.FC_PAR(PERSONAL_HISTORICO.COMPANIA,'AJUSTAR APORTES PARAFISCALES MES COMPLETO',6, SYSDATE)='SI' 
                         THEN (CASE WHEN HISTORICOS.ID_DE_CONCEPTO=174 
                               THEN HISTORICOS.VALOR 
                               ELSE 0 
                               END)
                         ELSE 0 
                           END)) DIF,
        (SUM(CASE WHEN PCK_SYSMAN_UTL.FC_PAR(PERSONAL_HISTORICO.COMPANIA,'AJUSTAR APORTES PARAFISCALES MES COMPLETO',6, SYSDATE)='SI' 
 	   	   THEN (PERSONAL_HISTORICO.SALARIO_BASE_IBC/30*(CASE WHEN HISTORICOS.ID_DE_CONCEPTO=035
                                        	THEN HISTORICOS.VALOR 
                                          ELSE 0 
                                          END))-
                                          CASE WHEN HISTORICOS.ID_DE_CONCEPTO=174 
                                          THEN HISTORICOS.VALOR 
                                          ELSE 0 
                                          END
 	   	   ELSE 0 
 	   	   END)) AS DIFVAC,
 	       PERSONAL_HISTORICO.NOMBRE_TIPO,
 	       PERSONAL_HISTORICO.TIPOVINCULACION, 
 	       PERSONAL_HISTORICO.ESTADO_ACTUAL, 
 	       PERSONAL_HISTORICO.NOMBRECOMPLETO,
       (SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO=212
 	   	   THEN HISTORICOS.VALOR 
 	   	   ELSE 0 
 	   	   END)) RIESGO212,
         (PCK_NOMINA_SEGSOCI.FC_PORCENRIESGO(PERSONAL_HISTORICO.COMPANIA,HISTORICOS.ID_DE_EMPLEADO)) PORCENTAJE,
         (SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO=111 
 	   	   THEN HISTORICOS.VALOR 
 	   	   ELSE 0 
 	   	   END)) APORTE,
         ((SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO=212
 	   	    THEN HISTORICOS.VALOR 
 	   	    ELSE 0 
 	   	    END))*(PCK_NOMINA_SEGSOCI.FC_PORCENRIESGO(PERSONAL_HISTORICO.COMPANIA,HISTORICOS.ID_DE_EMPLEADO))/100) APORTESIN,
          (PCK_SYSMAN_UTL.FC_ROUND((SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO=111 
 	   	   THEN HISTORICOS.VALOR 
 	   	   ELSE 0 
 	   	   END))-((SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO=212 
 	   	             THEN HISTORICOS.VALOR 
 	   	             ELSE 0 
                   END))*(PCK_NOMINA_SEGSOCI.FC_PORCENRIESGO(PERSONAL_HISTORICO.COMPANIA, HISTORICOS.ID_DE_EMPLEADO))/100),0)) DIFAPORTE        
 FROM HISTORICOS
 INNER JOIN CONCEPTOS
      ON HISTORICOS.COMPANIA = CONCEPTOS.COMPANIA 
      AND HISTORICOS.ID_DE_CONCEPTO = CONCEPTOS.ID_DE_CONCEPTO
 LEFT JOIN PERSONAL_HISTORICO
      ON HISTORICOS.ID_DE_EMPLEADO = PERSONAL_HISTORICO.ID_DE_EMPLEADO 
      AND HISTORICOS.COMPANIA = PERSONAL_HISTORICO.COMPANIA 
      AND HISTORICOS.ID_DE_PROCESO = PERSONAL_HISTORICO.ID_DE_PROCESO
      AND HISTORICOS.ANO = PERSONAL_HISTORICO.ANO
      AND HISTORICOS.MES = PERSONAL_HISTORICO.MES
      AND HISTORICOS.PERIODO = PERSONAL_HISTORICO.PERIODO
      AND HISTORICOS.ID_DE_EMPLEADO = PERSONAL_HISTORICO.ID_DE_EMPLEADO
 WHERE  HISTORICOS.ANO= s$ano2$s                                  
  AND HISTORICOS.MES= s$mes2$s
  AND (HISTORICOS.COMPANIA= s$compania$s
  AND CONCEPTOS.FACTOR_PARAFISCAL<>0
  AND CONCEPTOS.CLASE IN (3, 99) 
  OR HISTORICOS.ID_DE_CONCEPTO IN (109, 111, 212, 035, 108))
  group by HISTORICOS.ANO,
  HISTORICOS.MES,
  HISTORICOS.ID_DE_EMPLEADO,
  PERSONAL_HISTORICO.NOMBRE_TIPO,
  PERSONAL_HISTORICO.TIPOVINCULACION, 
  PERSONAL_HISTORICO.ESTADO_ACTUAL,
  PERSONAL_HISTORICO.NOMBRECOMPLETO, 
  (PCK_NOMINA_SEGSOCI.FC_PORCENRIESGO(PERSONAL_HISTORICO.COMPANIA,HISTORICOS.ID_DE_EMPLEADO))
