SELECT  HISTORICOS.COMPANIA, 
        HISTORICOS.ID_DE_PROCESO, 
        TO_CHAR( HISTORICOS.ANO) ANO,
        HISTORICOS.MES, 
        HISTORICOS.ID_DE_EMPLEADO, 
        SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = 112 
                 THEN HISTORICOS.VALOR 
                 ELSE 0 END) C112, 
        SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = 132 
                 THEN HISTORICOS.VALOR 
                 ELSE 0 END) C132, 
        SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = 115 
                 THEN HISTORICOS.VALOR 
                 ELSE 0 END) C115, 
        SUM(ROUND((CASE WHEN HISTORICOS.ID_DE_CONCEPTO = 112 
                        THEN HISTORICOS.VALOR 
                        ELSE 0 END) * 1/100,
            -2)) FSP, 
        SUM(((CASE WHEN HISTORICOS.ID_DE_CONCEPTO = 112 
                   THEN HISTORICOS.VALOR 
                   ELSE 0 END)*1/100)
              -
             (CASE WHEN HISTORICOS.ID_DE_CONCEPTO = 132 
                   THEN HISTORICOS.VALOR 
                   ELSE 0 END)) AS DIF, 
        PERSONAL.APELLIDO1, 
        PERSONAL.APELLIDO2, 
        PERSONAL.NOMBRES, 
        PERSONAL.ID_DEL_FONDO
  FROM  HISTORICOS 
    LEFT JOIN PERSONAL 
       ON HISTORICOS.ID_DE_EMPLEADO = PERSONAL.ID_DE_EMPLEADO 
      AND HISTORICOS.COMPANIA           = PERSONAL.COMPANIA
  WHERE HISTORICOS.COMPANIA         =  s$compania$s 
    AND HISTORICOS.ANO            	=  s$anioNomina$s 
    AND HISTORICOS.MES            	=  s$mesNomina$s 
    AND HISTORICOS.ID_DE_CONCEPTO IN (132, 112, 115)
  GROUP BY  HISTORICOS.COMPANIA, 
      HISTORICOS.ID_DE_PROCESO, 
      HISTORICOS.ANO, 
      HISTORICOS.MES, 
      HISTORICOS.ID_DE_EMPLEADO, 
      PERSONAL.APELLIDO1, 
      PERSONAL.APELLIDO2, 
      PERSONAL.NOMBRES, 
      PERSONAL.ID_DEL_FONDO
  HAVING SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO = 112 THEN HISTORICOS.VALOR ELSE 0 END) 
         > 
         (PCK_NOMINA_COM1.FC_PARAMETRO(s$compania$s,20) * 4)
  ORDER BY SUM((CASE WHEN HISTORICOS.ID_DE_CONCEPTO = 112 
                     THEN HISTORICOS.VALOR 
                     ELSE 0 END) * 1/100
                -
               (CASE WHEN HISTORICOS.ID_DE_CONCEPTO = 132 
                     THEN HISTORICOS.VALOR 
                     ELSE 0 END))
