SELECT
  PERSONAL.NUMERO_DCTO,
  SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (125) THEN VALOR ELSE 0 END ) AS RETFTE,
  SUM(CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (144) THEN VALOR ELSE 0 END) AS  TOTAL,
  (PERSONAL.APELLIDO1 || ' ' || PERSONAL.APELLIDO2 || ' ' || PERSONAL.NOMBRES) AS NOMBRECOMPLETO,
  BANCOS_NOMINA.NOMBREBANCO,
  CASE WHEN PERSONAL.TIPOCUENTA LIKE 'C' THEN 'Corriente' ELSE 'Ahorros' END TIPOCUENTA,
  PERSONAL.CUENTA,
  's$conceptoPago$s' CONCEPTO 
FROM PERSONAL
  INNER JOIN BANCO BANCOS_NOMINA
    ON PERSONAL.COMPANIA 			= BANCOS_NOMINA.COMPANIA
   AND PERSONAL.BANCO   			= BANCOS_NOMINA.BANCO
  INNER JOIN HISTORICOS
    ON PERSONAL.COMPANIA            = HISTORICOS.COMPANIA 
   AND PERSONAL.ID_DE_EMPLEADO      = HISTORICOS.ID_DE_EMPLEADO
WHERE PERSONAL.COMPANIA                 = s$compania$s 
  AND HISTORICOS.ID_DE_PROCESO          = s$idProceso$s 
  AND HISTORICOS.ANO                    = s$anio$s 
  AND HISTORICOS.MES                    = s$mes$s 
  AND HISTORICOS.PERIODO                = s$periodo$s 
  AND HISTORICOS.ID_DE_CONCEPTO IN (144,125)  
GROUP BY PERSONAL.NUMERO_DCTO,
  (PERSONAL.APELLIDO1 || ' ' || PERSONAL.APELLIDO2 || ' ' || PERSONAL.NOMBRES) ,
  BANCOS_NOMINA.NOMBREBANCO,
    CASE WHEN PERSONAL.TIPOCUENTA LIKE 'C' THEN 'Corriente' ELSE 'Ahorros' END,
  PERSONAL.CUENTA,
  's$conceptoPago$s' 
HAVING  SUM( CASE WHEN HISTORICOS.ID_DE_CONCEPTO IN (125) THEN VALOR ELSE 0 END) IN (0)    
