SELECT *
FROM
  (SELECT 
    P.CODIGO,
    P.NOMBREESCALAFON,
    P.ID_DE_TIPO,
    P.CEDULA,
    P.NOMBREEMPLEADO,
    P.CARGO,
    P.NOMBRECARGO,
    P.DEPENDENCIA,
    P.NOMBREDEPENDENCIA,
    P.DEVENGOS,
    P.DESCUENTOS,
    P.NETO,
    V_ACUMULADOS.CLASE
    || '_'
    || V_ACUMULADOS.ID_DE_CONCEPTO PER,
    V_ACUMULADOS.VALOR
  FROM
    (SELECT V_ACUMULADOS.COMPANIA, V_ACUMULADOS.ANO, V_ACUMULADOS.MES, V_ACUMULADOS.ID_DE_EMPLEADO CODIGO,
      V_ACUMULADOS.ESCALAFON ESCALAFON,
      V_ACUMULADOS.NOMBRE_ESCALAFON NOMBREESCALAFON,
      PERSONAL.ID_DE_TIPO,
      V_ACUMULADOS.NUMERO_DCTO CEDULA,
      V_ACUMULADOS.APELLIDO1
      || ' '
      || V_ACUMULADOS.APELLIDO2
      || ' '
      || V_ACUMULADOS.NOMBRES NOMBREEMPLEADO,
      V_ACUMULADOS.ID_DE_CARGO CARGO,
      V_ACUMULADOS.NOMBRE_DE_CARGO NOMBRECARGO,
      V_ACUMULADOS.DEPENDENCIA,
      V_ACUMULADOS.NOMBRE_DEPENDENCIA NOMBREDEPENDENCIA,
      SUM(V_ACUMULADOS.DEVENGOS) DEVENGOS,
      SUM(V_ACUMULADOS.DESCUENTOS) DESCUENTOS,
      SUM(DEVENGOS - DESCUENTOS) NETO
    FROM V_ACUMULADOS
    INNER JOIN PERSONAL
    ON V_ACUMULADOS.COMPANIA        = PERSONAL.COMPANIA
    AND V_ACUMULADOS.ID_DE_EMPLEADO = PERSONAL.ID_DE_EMPLEADO
    WHERE V_ACUMULADOS.COMPANIA = 's$compania$s'
    AND V_ACUMULADOS.ANO          = s$anio$s
    AND V_ACUMULADOS.MES            = s$mes$s
    AND V_ACUMULADOS.CLASE BETWEEN 3 AND 7
    GROUP BY V_ACUMULADOS.COMPANIA,V_ACUMULADOS.ANO, V_ACUMULADOS.MES, V_ACUMULADOS.ID_DE_EMPLEADO,
      V_ACUMULADOS.ESCALAFON,
      V_ACUMULADOS.NOMBRE_ESCALAFON,
      PERSONAL.ID_DE_TIPO,
      V_ACUMULADOS.NUMERO_DCTO,
      V_ACUMULADOS.APELLIDO1
      || ' '
      || V_ACUMULADOS.APELLIDO2
      || ' '
      || V_ACUMULADOS.NOMBRES,
      V_ACUMULADOS.ID_DE_CARGO,
      V_ACUMULADOS.NOMBRE_DE_CARGO,
      V_ACUMULADOS.DEPENDENCIA,
      V_ACUMULADOS.NOMBRE_DEPENDENCIA
    ) P
  INNER JOIN V_ACUMULADOS
  ON V_ACUMULADOS.COMPANIA = P.COMPANIA
 AND V_ACUMULADOS.ID_DE_EMPLEADO = P.CODIGO
WHERE   V_ACUMULADOS.COMPANIA = 's$compania$s'
    AND V_ACUMULADOS.ANO          = s$anio$s
    AND V_ACUMULADOS.MES            = s$mes$s
    AND V_ACUMULADOS.CLASE BETWEEN 3 AND 7
  )PIVOT (SUM(VALOR) FOR PER IN ('s$condicionpivot$s)) 
