SELECT 
   C.ID_DE_CONCEPTO COD_CONCEPTO
  ,C.NOMBRE_CONCEPTO
  ,C.CLASE
  ,C.CTA_DBT_ADMINISTRACION
  ,NVL(C.CTA_CRD_ADMINISTRACION,' ') CTA_CRD_ADMINISTRACION
  ,C.CTA_DBT_VENTAS
  ,NVL(C.CTA_CRD_VENTAS,' ') CTA_CRD_VENTAS
  ,C.CTA_DBT_PRODUCCION
  ,NVL(C.CTA_CRD_PRODUCCION,' ') CTA_CRD_PRODUCCION
  ,C.CTA_DBT_OTRO
  ,NVL(C.CTA_CRD_OTRO    ,' ') CTA_CRD_OTRO
  ,NVL(C.CTA_DBT_SUPERNUM,' ') CTA_DBT_SUPERNUM
  ,NVL(C.CTA_CRD_SUPERNUM,' ') CTA_CRD_SUPERNUM
  ,C.TERCERO
  ,C.SUCURSAL
  ,T.NOMBRE NOMBRE_TERCERO
  ,C.NITDE
  ,C.PORCDC
  ,C.TIPODEFONDO
FROM CONCEPTOS C
  INNER JOIN TERCERO T
     ON C.COMPANIA = T.COMPANIA
    AND C.TERCERO  = T.NIT
    AND C.SUCURSAL = T.SUCURSAL
WHERE C.COMPANIA= s$compania$s
  AND C.CLASE IN(3,5,8,7)
  AND NOT (C.CTA_DBT_ADMINISTRACION || 
  	       C.CTA_CRD_ADMINISTRACION || 
  	       C.CTA_CRD_PRODUCCION     || 
  	       C.CTA_DBT_PRODUCCION     || 
  	       C.CTA_CRD_VENTAS         || 
  	       C.CTA_DBT_VENTAS         || 
  	       C.CTA_CRD_SUPERNUM       || 
  	       C.CTA_DBT_SUPERNUM) IS NULL
ORDER BY 
   C.ID_DE_CONCEPTO
  ,C.NOMBRE_CONCEPTO
  ,C.CLASE
