SELECT HISTORICOS.COMPANIA,
  CONCEPTOS.CLASE,
  SUM(HISTORICOS.VALOR) AS SUMADEVALOR,
  HISTORICOS.ID_DE_CONCEPTO,
  CONCEPTOS.RUBROS_SIIF,
  CONCEPTOS.DOC_SIIF_CONCEPTO,
  CONCEPTOS.SIIF_POSICION_DESCUENTO AS EXPR1,
  CONCEPTOS.NITCONCEPTO,
  CONCEPTOS.TERCERO,
  CONCEPTOS.NOMBRE_CONCEPTO,
  HISTORICOS.ANO
FROM HISTORICOS
INNER JOIN CONCEPTOS
ON HISTORICOS.COMPANIA        = CONCEPTOS.COMPANIA
AND HISTORICOS.ID_DE_CONCEPTO = CONCEPTOS.ID_DE_CONCEPTO
WHERE HISTORICOS.COMPANIA  = 's$compania$s'  
AND CONCEPTOS.CLASE          IN (8) 
AND (HISTORICOS.ID_DE_CONCEPTO < 490 
  OR  HISTORICOS.ID_DE_CONCEPTO  > 499) 
AND HISTORICOS.ANO      = s$anio$s 
GROUP BY HISTORICOS.COMPANIA,
  CONCEPTOS.CLASE,
  HISTORICOS.ID_DE_CONCEPTO,
  CONCEPTOS.RUBROS_SIIF,
  CONCEPTOS.DOC_SIIF_CONCEPTO,
  CONCEPTOS.SIIF_POSICION_DESCUENTO,
  CONCEPTOS.NITCONCEPTO,
  CONCEPTOS.TERCERO,
  CONCEPTOS.NOMBRE_CONCEPTO,   
  HISTORICOS.ANO 
ORDER BY HISTORICOS.ID_DE_CONCEPTO
