SELECT 
  TO_CHAR(VI_VIATICOS.ANO) ANO ,
  CASE
    WHEN VI_VIATICOS.TIPOCOMISION = 1
    THEN 'Exterior'
    ELSE 'Interior'
  END TIPOCOMISION,
  VI_VIATICOS.TSOLICITUD ,
  VI_TIPOSOLICITUD.DESCRIPCION CLASE_COMISION,
  TO_CHAR(VI_VIATICOS.CODSOLICITUD) CODSOLICITUD,
  TO_CHAR(VI_VIATICOS.FECHA,'DD/MM/YYYY') FECHA ,
  VI_VIATICOS.NUMSOLICITUD ,
  CASE
    WHEN VI_VIATICOS.ESTADO IN ('P')
    THEN 'Pendiente'
    WHEN VI_VIATICOS.ESTADO IN ('A')
    THEN 'Aprobado'
    WHEN VI_VIATICOS.ESTADO IN ('N')
    THEN 'No Aprobado'
    WHEN VI_VIATICOS.ESTADO IN ('C')
    THEN 'Cancelado '
  END ESTADO_SOLICITUD ,
  VI_VIATICOS.NRO_RADICADO_DOC NRO_RADICADO_GES_DOC ,
  TO_CHAR(VI_VIATICOS.FECHA_RADICADO_DOC,'DD/MM/YYYY') FECHA_RADICADO_GES_DOC,
  VI_VIATICOS.TERCERO ,
  T.NOMBRE NOMBRETERCERO,
  VI_VIATICOS.DEPENDENCIA ,
  DP.NOMBRE NOMBREDEPENDENCIA,
  VI_VIATICOS.JEFE_DEPENDENCIA ,
  VI_VIATICOS.SUCURSAL_JEFE,
  TT.NOMBRE NOMBRERESPONSABLE,
  TO_CHAR(VI_VIATICOS.FECHA_NACIMIENTO,'DD/MM/YYYY') FECHA_NACIMIENTO ,
  VI_VIATICOS.PAIS_EXPE,
  VI_VIATICOS.DEPARTAMENTO_EXPE,
  VI_VIATICOS.CIUDAD_EXPE,
  C.NOMBRE NOMBRE_EXPE,
  VI_VIATICOS.BANCO,
  B.NOMBREBANCO,
  VI_VIATICOS.TELEFONOS,
  VI_VIATICOS.CTA_BANCARIA,
  VI_VIATICOS.CORREO_ELECTRONICO,
  VI_VIATICOS.SALARIO_COMISIONADO,
  VI_VIATICOS.PAIS_ORIGEN ,
  PAISO.NOMBRE NOMBRE_PAIS_ORIGEN,
  VI_VIATICOS.DEPARTAMENTO_ORIGEN ,
  DPTOO.NOMBRE NOMBRE_DPTO_ORIGEN,
  VI_VIATICOS.CIUDAD_ORIGEN ,
  CIUDADO.NOMBRE NOMBRE_CIUDAD_ORIGEN,
  VI_VIATICOS.PAIS_DESTINO ,
  PAISD.NOMBRE NOMBRE_PAIS_DESTINO,
  VI_VIATICOS.DEPARTAMENTO_DESTINO ,
  DPTOD.NOMBRE NOMBRE_DPTO_DESTINO,
  VI_VIATICOS.CIUDAD_DESTINO ,
  CIUDADD.NOMBRE NOMBRE_CIUDAD_DESTINO,
  VI_VIATICOS.PAIS_REGRESO,
  PAISR.NOMBRE NOMBRE_PAIS_REGRESO,
  VI_VIATICOS.DEPARTAMENTO_REGRESO,
  DPTOR.NOMBRE NOMBRE_DPTO_REGRESO,
  VI_VIATICOS.CIUDAD_REGRESO,
  CIUDADR.NOMBRE NOMBRE_CIUDAD_REGRESO,
  CASE
    WHEN VI_VIATICOS.ZONA_EXTERIOR = 1
    THEN 'Centro América,El Caribe y Surámerica Excepto Brasil,Chile,Argentina y Puerto Rico'
    WHEN VI_VIATICOS.ZONA_EXTERIOR = 2
    THEN 'Estados Unidos,Canadá,Chile,Brasil,África y Puerto Rico'
    WHEN VI_VIATICOS.ZONA_EXTERIOR = 3
    THEN 'Europa,Asia,Oceanía,Mexico y Argentina'
  END ZONA_EXTERIOR,
  VI_VIATICOS.DESTINO_CORRERIA,
  VI_VIATICOS.CLASE_TRANSPORTE,
  CT.DESCRIPCION NOMBRECLASETRANSPORTE,
  VI_VIATICOS.DESCRIPCION_TRANS,
  VI_VIATICOS.VALOR_TRANSPORTE ,
  CASE VI_VIATICOS.SABADO WHEN -1 THEN 'SI' ELSE 'NO' END SABADO,
  CASE VI_VIATICOS.DOMINGO WHEN -1 THEN 'SI' ELSE 'NO' END DOMINGO,
  CASE VI_VIATICOS.FESTIVO WHEN -1 THEN 'SI' ELSE 'NO' END FESTIVO,
  TO_CHAR(VI_VIATICOS.FECHAINICIO,'DD/MM/YYYY') FECHAINICIO ,
  TO_CHAR(VI_VIATICOS.FECHAFIN,'DD/MM/YYYY') FECHAFIN ,
  TO_CHAR(VI_VIATICOS.HORA_SALIDA,'HH24:MI:SS') HORA_SALIDA ,
  TO_CHAR(VI_VIATICOS.HORA_REGRESO,'HH24:MI:SS') HORA_REGRESO,
  VI_VIATICOS.NODIAS ,
  VI_VIATICOS.GENERA_VIATICOS,
  CASE VI_VIATICOS.SOLICITA_TIQUETE WHEN -1 THEN 'SI' ELSE 'NO' END SOLICITA_TIQUETE,
  VI_VIATICOS.OBJETO ,
  VI_VIATICOS.OBSERVACION OBSERVACION_SOLICITUD_COMISION,
  VI_VIATICOS.OBSERVACIONCOMITE ,
  --APROBACION SOLICITUD
  TO_CHAR(VI_VIATICOS.FECHA_APROBACION,'DD/MM/YYYY') FECHA_APROBACION,
  --GESTION TALENTO HUMANO
  CASE VI_VIATICOS.PERNOCTA WHEN -1 THEN 'SI' ELSE 'NO' END PERNOCTA_ULTIMA_NOCHE,
  VI_VIATICOS.VALOR_DIARIO_COMISION,
  VI_VIATICOS.VALORTOTALVIATICO ,
  VI_VIATICOS.DIAS_TRANSITO,
  --DATOS VUELO
  PCK_SYSMAN_UTL.FC_PAR(VI_VIATICOS.COMPANIA,'NUMERO DE CERTIFICADO DE DISPONIBILIDAD PRESUPUESTAL',6,SYSDATE,0) NUMERO_CDP,
  PCK_SYSMAN_UTL.FC_PAR(VI_VIATICOS.COMPANIA,'NUMERO DEL REGISTRO PRESUPUESTAL DE VIATICOS',6,SYSDATE,0) NUMERO_RPV,
  PCK_SYSMAN_UTL.FC_PAR(VI_VIATICOS.COMPANIA,'NUMERO DEL REGISTRO PRESUPUESTAL DEL TRANSPORTE',6,SYSDATE,0) NUMERO_RPT,
  VI_VIATICOS.VALOR_RESERVA_INICIAL ,
  VI_VIATICOS.VALOR_TIQUETE_EMITIDO ,
  VI_VIATICOS.NUMERO_LOCALIZADOR ,
  VI_VIATICOS.ITINERARIO ,
  TO_CHAR(VI_VIATICOS.FECHA_FACTURA_TIQUETE,'DD/MM/YYYY') FECHA_FACTURA_TIQUETE,
  VI_VIATICOS.VALOR_FACTURA_TIQUETE ,
  VI_VIATICOS.VALOR_DESCUENTO_AGENCIA ,
  VI_VIATICOS.NUMERO_RADICADO ,
  TO_CHAR(VI_VIATICOS.FECHA_RADICADO,'DD/MM/YYYY') FECHA_RADICADO,
  TO_CHAR(VI_VIATICOS.FECHA_AUT_FACTURA,'DD/MM/YYYY') FECHA_AUT_FACTURA ,
  VI_VIATICOS.NUMERO_RADICADO_AUTO,
  --Tramite Mintic
  CASE
    WHEN VI_VIATICOS.ESTADO_MINTIC IN ('P')
    THEN 'Pendiente'
    WHEN VI_VIATICOS.ESTADO_MINTIC IN ('A')
    THEN 'Aprobado'
    WHEN VI_VIATICOS.ESTADO_MINTIC IN ('N')
    THEN 'No Aprobado'
    WHEN VI_VIATICOS.ESTADO_MINTIC IN ('C')
    THEN 'Cancelado '
  END ESTADO_MINTIC,
  TO_CHAR(VI_VIATICOS.FECHA_APROBA_MINTIC,'DD/MM/YYYY') FECHA_APROBA_MINTIC,
  VI_VIATICOS.NRO_RADICADO_DOC_MINTIC,
  VI_VIATICOS.NUMERO_OFICIO_MINTIC,
  TO_CHAR(VI_VIATICOS.FECHA_RADICADO_MINTIC,'DD/MM/YYYY')FECHA_RADICADO_MINTIC,
  CASE
    WHEN VI_VIATICOS.AVAL_COORDINADOR IN ('A')
    THEN 'Aprobado'
    WHEN VI_VIATICOS.AVAL_COORDINADOR IN ('N')
    THEN 'No Aprobado'
  END AVAL_COORDINADOR,
  VI_VIATICOS.NUMERO_RESOLUCION_MINTIC,
  TO_CHAR(VI_VIATICOS.FECHA_RESOLUCION_MINTIC,'DD/MM/YYYY') FECHA_RESOLUCION_MINTIC,
  --LIQUIDAR EN PESOS
  VI_VIATICOS.VALOR_TASA_CAMBIO,
  TO_CHAR(VI_VIATICOS.FECHA_TASA_CAMBIO,'DD/MM/YYYY') FECHA_TASA_CAMBIO,
  VI_VIATICOS.VALOR_TOTAL_PESOS,
  --RECEPCION VIATICOS
  TO_CHAR(VI_VIATICOS.FECHA_LEGALIZACION,'DD/MM/YYYY') FECHA_LEGALIZACION,
  TO_CHAR(VI_VIATICOS.FECHA_AUT_SIIF_NACION,'DD/MM/YYYY') FECHA_AUT_SIIF_NACION ,
  VI_VIATICOS.NUMERO_COM_DESEMBOLSO_SIIF ,
  TO_CHAR(VI_VIATICOS.FECHA_COM_DESEMBOLSO_SIIF,'DD/MM/YYYY') FECHA_COM_DESEMBOLSO_SIIF,
  VI_VIATICOS.NUMERO_COM_DESEM_TRANSPORTE,
  TO_CHAR(VI_VIATICOS.FECHA_DESEMBOLSO_TRANSPORTE,'DD/MM/YYYY') FECHA_DESEMBOLSO_TRANSPORTE ,
  --SOLICITUD LEGALIZACION
  CASE
    WHEN VI_VIATICOS.ESTADO_LEGALIZACION IN ('P')
    THEN 'Pendiente'
    WHEN VI_VIATICOS.ESTADO_LEGALIZACION IN ('A')
    THEN 'Aprobado'
    WHEN VI_VIATICOS.ESTADO_LEGALIZACION IN ('N')
    THEN 'No Aprobado'
  END ESTADO_LEGALIZACION,
  VI_VIATICOS.RESUMEN_ACTIVIDADES ,
  --APROBACION LEGALIZACION
  TO_CHAR(VI_VIATICOS.FECHA_APROBA_LEGA,'DD/MM/YYYY') FECHA_APROBA_LEGA,
  CASE VI_VIATICOS.LEGALIZADO_PLAZO WHEN -1 THEN 'SI' ELSE 'NO' END LEGALIZADO_EN_PLAZO,
  VI_VIATICOS.OBSERVACION_LEGALIZACION ,
  --RECEPCION LEGALIZACION
  VI_VIATICOS.VALOR_VIATICO_LEGALIZADO,
  VI_VIATICOS.VALOR_TRANSPORTE_LEGALIZADO,
  VI_VIATICOS.VALOR_REEMBOLSADO,
  TO_CHAR(VI_VIATICOS.FECHA_REEMBOLSO,'DD/MM/YYYY') FECHA_REEMBOLSO,
  VI_VIATICOS.VALOR_TRANSPORTE_REEMBOLSO,
  TO_CHAR(VI_VIATICOS.FECHA_TRANS_REEMBOLSO,'DD/MM/YYYY') FECHA_TRANS_REEMBOLSO,
  TO_CHAR(VI_VIATICOS.FECHA_GRABACION_SIIF,'DD/MM/YYYY') FECHA_GRABACION_SIIF
FROM VI_VIATICOS
  INNER JOIN VI_TIPOSOLICITUD
    ON VI_VIATICOS.COMPANIA    = VI_TIPOSOLICITUD.COMPANIA
    AND VI_VIATICOS.TSOLICITUD = VI_TIPOSOLICITUD.CODTIPO
  INNER JOIN TERCERO T
    ON VI_VIATICOS.COMPANIA  = T.COMPANIA
    AND VI_VIATICOS.TERCERO  = T.NIT
    AND VI_VIATICOS.SUCURSAL = T.SUCURSAL
  INNER JOIN DEPENDENCIA DP
    ON VI_VIATICOS.COMPANIA     = DP.COMPANIA
    AND VI_VIATICOS.DEPENDENCIA = DP.CODIGO
  INNER JOIN DEPENDENCIA_RESPONSABLE DPR
    ON VI_VIATICOS.COMPANIA          = DPR.COMPANIA
    AND VI_VIATICOS.DEPENDENCIA      = DPR.DEPENDENCIA
    AND VI_VIATICOS.JEFE_DEPENDENCIA = DPR.RESPONSABLE
  INNER JOIN RESPONSABLE R
    ON R.COMPANIA  = DPR.COMPANIA
    AND R.CEDULA   = DPR.RESPONSABLE
    AND R.SUCURSAL = DPR.SUCURSAL
  INNER JOIN TERCERO TT
    ON R.COMPANIA  = TT.COMPANIA
    AND R.CEDULA   = TT.NIT
    AND R.SUCURSAL = TT.SUCURSAL
  LEFT JOIN BANCO B
    ON B.COMPANIA = VI_VIATICOS.COMPANIA
    AND B.BANCO   = VI_VIATICOS.BANCO
  LEFT JOIN VI_CLASE_TRANSPORTE CT
    ON CT.COMPANIA = VI_VIATICOS.COMPANIA
    AND CT.CODIGO  = VI_VIATICOS.CLASE_TRANSPORTE
  LEFT JOIN CIUDAD C
    ON VI_VIATICOS.CIUDAD_EXPE        = C.CODIGO
    AND VI_VIATICOS.DEPARTAMENTO_EXPE = C.DEPARTAMENTO
    AND VI_VIATICOS.PAIS_EXPE         = C.PAIS
  LEFT JOIN PAISES PAISO
    ON VI_VIATICOS.PAIS_ORIGEN = PAISO.PAIS
  LEFT JOIN DEPARTAMENTO DPTOO
    ON VI_VIATICOS.PAIS_ORIGEN          = DPTOO.PAIS
    AND VI_VIATICOS.DEPARTAMENTO_ORIGEN = DPTOO.CODIGO
  LEFT JOIN CIUDAD CIUDADO
    ON VI_VIATICOS.PAIS_ORIGEN          = CIUDADO.PAIS
    AND VI_VIATICOS.DEPARTAMENTO_ORIGEN = CIUDADO.DEPARTAMENTO
    AND VI_VIATICOS.CIUDAD_ORIGEN       = CIUDADO.CODIGO
  LEFT JOIN PAISES PAISD
    ON VI_VIATICOS.PAIS_DESTINO = PAISD.PAIS
  LEFT JOIN DEPARTAMENTO DPTOD
    ON VI_VIATICOS.PAIS_DESTINO          = DPTOD.PAIS
    AND VI_VIATICOS.DEPARTAMENTO_DESTINO = DPTOD.CODIGO
  LEFT JOIN CIUDAD CIUDADD
    ON VI_VIATICOS.PAIS_DESTINO          = CIUDADD.PAIS
    AND VI_VIATICOS.DEPARTAMENTO_DESTINO = CIUDADD.DEPARTAMENTO
    AND VI_VIATICOS.CIUDAD_DESTINO       = CIUDADD.CODIGO
  LEFT JOIN PAISES PAISD
    ON VI_VIATICOS.PAIS_DESTINO = PAISD.PAIS
  LEFT JOIN DEPARTAMENTO DPTOD
    ON VI_VIATICOS.PAIS_DESTINO          = DPTOD.PAIS
    AND VI_VIATICOS.DEPARTAMENTO_DESTINO = DPTOD.CODIGO
  LEFT JOIN CIUDAD CIUDADD
    ON VI_VIATICOS.PAIS_DESTINO          = CIUDADD.PAIS
    AND VI_VIATICOS.DEPARTAMENTO_DESTINO = CIUDADD.DEPARTAMENTO
    AND VI_VIATICOS.CIUDAD_DESTINO       = CIUDADD.CODIGO
  LEFT JOIN PAISES PAISR
    ON VI_VIATICOS.PAIS_REGRESO = PAISR.PAIS
  LEFT JOIN DEPARTAMENTO DPTOR
    ON VI_VIATICOS.PAIS_REGRESO          = DPTOR.PAIS
    AND VI_VIATICOS.DEPARTAMENTO_REGRESO = DPTOR.CODIGO
  LEFT JOIN CIUDAD CIUDADR
    ON VI_VIATICOS.PAIS_REGRESO          = CIUDADR.PAIS
    AND VI_VIATICOS.DEPARTAMENTO_REGRESO = CIUDADR.DEPARTAMENTO
    AND VI_VIATICOS.CIUDAD_REGRESO       = CIUDADR.CODIGO
WHERE VI_VIATICOS.COMPANIA = s$compania$s
  AND VI_VIATICOS.TIPOCOMISION = 's$tipo$s'
  AND EXTRACT (MONTH FROM VI_VIATICOS.FECHA) BETWEEN s$mesInicial$s AND s$mesFinal$s
ORDER BY VI_VIATICOS.CODSOLICITUD
