MERGE INTO CONSULTAS FIN USING (SELECT '800605ActualizarMesadaPensional' INFORME ,TO_CLOB(q'[SELECT  PERSONAL.COMPANIA
        ,PERSONAL.NUMERO_DCTO NRO_DOC 
        ,PERSONAL.NOMBRECOMPLETO NOMBRE_EMPLEADO
        ,PERSONAL.PORC_INC_MESADA "% ULTIMO INCREMENTO"
        ,TO_CHAR(PERSONAL.ANO_MESADA_ANT) AS "AÑO ANTERIOR"
        ,PERSONAL.ANO "AÑO ACTUAL"
        ,PERSONAL.MESADA_PENSIONAL_ANT AS "VLR MESADA ANTERIOR"
        ,PERSONAL.MESADA_PENSIONAL AS "VLR MESADA ACTUAL"
        ,PERSONAL.VR_MESPENSION2421_ANT AS "VLR MESADA 2421 ANTERIOR"        
        ,PERSONAL.VR_MESPENSION2421 AS "VLR MESADA 2421 ACTUAL"
        ,PERSONAL.RIESGO_PENSION_ANT AS "% SALUD ANTERIOR"
        ,PERSONAL.RIESGO_PENSION AS "% SALUD ACTUAL"           
FROM PERSONAL
WHERE   PERSONAL.COMPANIA = 's$compania$s'
        AND PERSONAL.ID_DE_EMPLEADO != 0
        AND PERSONAL.ESTADO_ACTUAL = 2
        AND PERSONAL.FECHA_DE_RETIRO IS NULL
ORDER BY PERSONAL.NOMBRECOMPLETO]') CONSULTA, 6 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);
