MERGE INTO CONSULTAS FIN USING (SELECT '800641Consultar100PorCiento' INFORME ,TO_CLOB(q'[SELECT
	    DISTPERSONAL.COMPANIA,
	    DISTPERSONAL.ANO,
	    DISTPERSONAL.MES,
	    DISTPERSONAL.PERIODO,
	    DISTPERSONAL.ID_DE_EMPLEADO,
	    SUM(DISTPERSONAL.PORCENTAJE) AS SUMADEPORCENTAJE
	FROM DISTPERSONAL
	WHERE DISTPERSONAL.COMPANIA = s$compania$s
	         AND   DISTPERSONAL.ANO  = s$anio$s
	         AND   DISTPERSONAL.MES  = s$mes$s
	         AND   DISTPERSONAL.PERIODO  = s$periodo$s
	GROUP BY
	    DISTPERSONAL.COMPANIA,
	    DISTPERSONAL.ANO,
	    DISTPERSONAL.MES,
	    DISTPERSONAL.PERIODO,
	    DISTPERSONAL.ID_DE_EMPLEADO
	HAVING SUM(DISTPERSONAL.PORCENTAJE)  <> 100 ]') CONSULTA, 6 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);