MERGE INTO CONSULTAS FIN USING (SELECT '800669InformeVinculacionJovenes' INFORME ,TO_CLOB(q'[SELECT ROW_NUMBER() OVER (ORDER BY NUMERO_DCTO) "No", 
TIPOS_DOCUMENTOS.DESCRIPCION "Tipo de Documento",
NUMERO_DCTO "No Identificación",
NOMBRECOMPLETO "Nombre Completo",
GENEROS.NOMBRE "Sexo",
TO_CHAR(FECHANCTO,'YYYY-MM-DD') "Fecha de Nacimiento",
PCK_SYSMAN_UTL.FC_EDAD(FECHANCTO) "Edad",
PAISES.NOMBRE "Nacionalidad",
INITCAP(DEPARTAMENTO.NOMBRE) "Departamento de Nacimiento",
INITCAP(CIUDAD.NOMBRE) "Municipio de Nacimiento",
ESTADO_CIVIL.DESCRIPCION "Estado Civil ",
NVL(N_HIJOS,0) "No De Hijos",
NOMBREFORMA "Servidor Público o Contratista",
TIPO_SERVIDOR_PUBLICO.NOMBRE "Tipo de Servidor Público",
TO_CHAR(FECHA_DE_INGRESO,'YYYY-MM-DD') "Fecha de Vinculación Cargo Actual o Firma de Contrato",
CASE WHEN PROGRAMA_JOVEN NOT IN (0) THEN 'Si' ELSE 'No' END "¿El joven fue beneficiario del programa Estado Joven?",
ESCALAFON.NOMBRE AS "Nivel Jerárquico Del Empleo",
CATEGORIA.SALARIO_BASE "Asignación Salarial u Honorarios",
NIVEL_EDUCATIVO.NOMBRE_PROFESION "Máximo nivel De Educación",
PROFESIONES.NOMBRE_PROFESION "Disciplina o Profesión",
INITCAP(DEPARTAMENTO_LAB.NOMBRE) "Departamento en el que Desempeña sus funciones",
CASE WHEN PERSONAL.DISCAPACIDAD NOT IN (0) THEN 'Si' ELSE 'No' END "Cuenta el Joven con algun tipo de Discapacidad",
DISCAPACIDAD.NOMBRE "¿Cuál?"
FROM PERSONAL
INNER JOIN CATEGORIA
 ON PERSONAL.COMPANIA = CATEGORIA.COMPANIA
AND PERSONAL.ANO = CATEGORIA.ANO
AND PERSONAL.ESCALAFON = CATEGORIA.ESCALAFON
AND PERSONAL.ID_DE_CATEGORIA = CATEGORIA.ID_DE_CATEGORIA
INNER JOIN FORMANOMBRAMIENTO
 ON PERSONAL.COMPANIA = FORMANOMBRAMIENTO.COMPANIA
AND PERSONAL.DE_CARRERA = FORMANOMBRAMIENTO.IDFORMA
INNER JOIN ESCALAFON
 ON PERSONAL.COMPANIA = ESCALAFON.COMPANIA
AND PERSONAL.ESCALAFON = ESCALAFON.CODIGO
INNER JOIN TIPOS_DOCUMENTOS
 ON PERSONAL.COMPANIA = TIPOS_DOCUMENTOS.COMPANIA
AND PERSONAL.DCTO_IDENTIDAD = TIPOS_DOCUMENTOS.DCTO_IDENTIDAD
INNER JOIN ESTADO_CIVIL
 ON PERSONAL.COMPANIA = ESTADO_CIVIL.COMPANIA
AND PERSONAL.ESTADO_CIVIL = ESTADO_CIVIL.ESTADO_CIVIL
INNER JOIN GENEROS
 ON PERSONAL.SEXO = GENEROS.CODIGO
INNER JOIN PAISES 
ON PERSONAL.PAIS_NAC = PAISES.PAIS
INNER JOIN DEPARTAMENTO
 ON PERSONAL.PAIS_NAC = DEPARTAMENTO.PAIS
AND PERSONAL.DEPARTAMENTO_NAC = DEPARTAMENTO.CODIGO
INNER JOIN CIUDAD
 ON PERSONAL.PAIS_NAC = CIUDAD.PAIS
AND PERSONAL.DEPARTAMENTO_NAC = CIUDAD.DEPARTAMENTO
AND PERSONAL.CIUDAD_NAC = CIUDAD.CODIGO
INNER JOIN DEPARTAMENTO DEPARTAMENTO_LAB
 ON PERSONAL.PAIS_LABORA = DEPARTAMENTO_LAB.PAIS
AND PERSONAL.DEPARTAMENTO_LABORA = DEPARTAMENTO_LAB.CODIGO
LEFT JOIN TIPO_SERVIDOR_PUBLICO
 ON PERSONAL.SERVIDOR_PUBLICO = TIPO_SERVIDOR_PUBLICO.CODIGO
LEFT JOIN DISCAPACIDAD
 ON PERSONAL.TIPO_DISCAPACIDAD = DISCAPACIDAD.CODIGO
LEFT JOIN PROFESIONES
 ON PERSONAL.PROFESION = PROFESIONES.CODIGOPROF
AND 'P' = PROFESIONES.TIPO
 LEFT JOIN PROFESIONES NIVEL_EDUCATIVO
 ON PERSONAL.NIVEL_EDUCATIVO = NIVEL_EDUCATIVO.CODIGOPROF
AND 'N' = NIVEL_EDUCATIVO.TIPO
WHERE PERSONAL.COMPANIA = s$co]') || TO_CLOB(q'[mpania$s
AND FECHA_DE_INGRESO BETWEEN TO_DATE('s$fechaInicial$s','DD/MM/YYYY') AND TO_DATE('s$fechaFinal$s','DD/MM/YYYY')
s$estado$s
ORDER BY 
NUMERO_DCTO]') CONSULTA, 6 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);