MERGE INTO CONSULTAS FIN USING (SELECT '800721ReporteAusentismoIncapacidades' INFORME ,TO_CLOB(q'[SELECT I.ID_DE_EMPLEADO, P.NUMERO_DCTO, P.NOMBRECOMPLETO, T.DESCRIPCION TIPO_NOVEDAD,  I.DIAS, TO_CHAR(I.FECHA_INICIO ,'DD/MM/YYYY') FECHA_INICIO, TO_CHAR(I.FECHA_FIN ,'DD/MM/YYYY') FECHA_FINAL
FROM INCAPACIDADES I
INNER JOIN PERSONAL P
 ON P.COMPANIA = I.COMPANIA
AND P.ID_DE_EMPLEADO = I.ID_DE_EMPLEADO
INNER JOIN TIPO_INCAPACIDAD T
 ON T.COMPANIA = I.COMPANIA
AND T.INCAPACIDAD = I.INCAPACIDAD
WHERE I.COMPANIA = s$compania$s
AND P.ESTADO_ACTUAL IN (s$estado$s)
AND (I.FECHA_INICIO <= TO_DATE('s$fechaInicial$s','DD/MM/YYYY') AND I.FECHA_FIN >= TO_DATE('s$fechaFinal$s','DD/MM/YYYY'))
ORDER BY NUMERO_DCTO, NOMBRECOMPLETO]') CONSULTA, 6 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);
COMMIT;