WITH LISTADO_COMFABOY_NETOS AS(
     SELECT HISTORICOS.COMPANIA,
            HISTORICOS.ID_DE_EMPLEADO ID_DE_EMPLEADO, 
            MAX(HISTORICOS.ID_DE_CONCEPTO) KEEP (DENSE_RANK LAST ORDER BY ROWNUM) ID_DE_CONCEPTO, 
            SUM(HISTORICOS.VALOR) VALOR
       FROM HISTORICOS  
            LEFT JOIN CONCEPTOS 
                   ON HISTORICOS.ID_DE_CONCEPTO = CONCEPTOS.ID_DE_CONCEPTO 
                  AND HISTORICOS.COMPANIA = CONCEPTOS.COMPANIA
      WHERE HISTORICOS.COMPANIA      = s$compania$s
        AND HISTORICOS.ID_DE_PROCESO = s$idProceso$s
        AND HISTORICOS.ANO           = s$anio$s
        AND HISTORICOS.MES           = s$mes$s
        AND HISTORICOS.PERIODO       = s$periodo$s
        AND CONCEPTOS.CLASE          = s$clase$s
      GROUP BY HISTORICOS.COMPANIA, HISTORICOS.ID_DE_EMPLEADO
)
SELECT 's$afiliacion$s' AFILIACION, 
       PERSONAL.NOMBRECOMPLETO NOMBRE_DEL_TRABAJADOR,
       PERSONAL.NUMERO_DCTO CEDULA, 
       SUM(CASE HISTORICOS.ID_DE_CONCEPTO WHEN 2  THEN HISTORICOS.VALOR ELSE 0 END
         + CASE HISTORICOS.ID_DE_CONCEPTO WHEN 62 THEN HISTORICOS.VALOR ELSE 0 END) SUELDO, 
       SUM(CASE HISTORICOS.ID_DE_CONCEPTO WHEN 61 THEN HISTORICOS.VALOR ELSE 0 END
         + CASE HISTORICOS.ID_DE_CONCEPTO WHEN 62 THEN HISTORICOS.VALOR ELSE 0 END) GASTOSREP,
       SUM(CASE HISTORICOS.ID_DE_CONCEPTO WHEN 79 THEN HISTORICOS.VALOR ELSE 0 END
         + CASE HISTORICOS.ID_DE_CONCEPTO WHEN 0 THEN HISTORICOS.VALOR ELSE 0 END) PRIMA_ALIMENTACION,
       SUM(CASE HISTORICOS.ID_DE_CONCEPTO WHEN 0 THEN HISTORICOS.VALOR ELSE 0 END) VIATICOS, 
       SUM(HISTORICOS.VALOR)
         -(SUM(CASE HISTORICOS.ID_DE_CONCEPTO WHEN 35 THEN HISTORICOS.VALOR ELSE 0 END
             + CASE HISTORICOS.ID_DE_CONCEPTO WHEN 50 THEN HISTORICOS.VALOR ELSE 0 END 
             + CASE HISTORICOS.ID_DE_CONCEPTO WHEN 51 THEN HISTORICOS.VALOR ELSE 0 END 
             + CASE HISTORICOS.ID_DE_CONCEPTO WHEN 49 THEN HISTORICOS.VALOR ELSE 0 END 
             + CASE HISTORICOS.ID_DE_CONCEPTO WHEN 54 THEN HISTORICOS.VALOR ELSE 0 END 
             + CASE HISTORICOS.ID_DE_CONCEPTO WHEN 60 THEN HISTORICOS.VALOR ELSE 0 END
             + CASE HISTORICOS.ID_DE_CONCEPTO WHEN 61 THEN HISTORICOS.VALOR ELSE 0 END
             + CASE HISTORICOS.ID_DE_CONCEPTO WHEN 62 THEN HISTORICOS.VALOR ELSE 0 END 
             + CASE HISTORICOS.ID_DE_CONCEPTO WHEN 79 THEN HISTORICOS.VALOR ELSE 0 END 
             + CASE HISTORICOS.ID_DE_CONCEPTO WHEN 2  THEN HISTORICOS.VALOR ELSE 0 END)) OTROS, 
       SUM(HISTORICOS.VALOR) VALOR,
       MAX((PCK_NOMINA_COM1.FC_ACUMCONCEPTO_VALOR(UN_COMPANIA     => HISTORICOS.COMPANIA,
                                                  UN_CONCEPTO     => 9,
                                                  UN_ANO1         => HISTORICOS.ANO,
                                                  UN_MES1         => HISTORICOS.MES,
                                                  UN_PER1         => HISTORICOS.PERIODO,
                                                  UN_ANO2         => HISTORICOS.ANO, 
                                                  UN_MES2         => HISTORICOS.MES, 
                                                  UN_PER2         => HISTORICOS.PERIODO,
                                                  UN_IDDEEMPLEADO => HISTORICOS.ID_DE_EMPLEADO))*8) KEEP (DENSE_RANK LAST ORDER BY ROWNUM) NO_HORAS, 
       TO_CHAR(MAX(PERSONAL.FECHA_DE_INGRESO) KEEP (DENSE_RANK LAST ORDER BY ROWNUM),'DD/MM/YYYY') FECHA_DE_INGRESO, 
       TO_CHAR(MAX(PERSONAL.FECHA_DE_RETIRO) KEEP (DENSE_RANK LAST ORDER BY ROWNUM),'DD/MM/YYYY') FECHA_DE_RETIRO, 
       HISTORICOS.ANO ||''|| HISTORICOS.MES AS PERIODO, 
       SUM(CASE HISTORICOS.ID_DE_CONCEPTO WHEN 35 THEN HISTORICOS.VALOR ELSE 0 END
         + CASE HISTORICOS.ID_DE_CONCEPTO WHEN 50 THEN HISTORICOS.VALOR ELSE 0 END 
         + CASE HISTORICOS.ID_DE_CONCEPTO WHEN 51 THEN HISTORICOS.VALOR ELSE 0 END 
         + CASE HISTORICOS.ID_DE_CONCEPTO WHEN 49 THEN HISTORICOS.VALOR ELSE 0 END 
         + CASE HISTORICOS.ID_DE_CONCEPTO WHEN 54 THEN HISTORICOS.VALOR ELSE 0 END 
         + CASE HISTORICOS.ID_DE_CONCEPTO WHEN 60 THEN HISTORICOS.VALOR ELSE 0 END
         + CASE HISTORICOS.ID_DE_CONCEPTO WHEN 61 THEN HISTORICOS.VALOR ELSE 0 END
         + CASE HISTORICOS.ID_DE_CONCEPTO WHEN 62 THEN HISTORICOS.VALOR ELSE 0 END 
         + CASE HISTORICOS.ID_DE_CONCEPTO WHEN 79 THEN HISTORICOS.VALOR ELSE 0 END 
         + CASE HISTORICOS.ID_DE_CONCEPTO WHEN 2  THEN HISTORICOS.VALOR ELSE 0 END) NOSUMAN
  FROM HISTORICOS 
       LEFT JOIN CONCEPTOS 
              ON HISTORICOS.ID_DE_CONCEPTO = CONCEPTOS.ID_DE_CONCEPTO
             AND HISTORICOS.COMPANIA = CONCEPTOS.COMPANIA
       LEFT JOIN LISTADO_COMFABOY_NETOS 
              ON HISTORICOS.ID_DE_EMPLEADO = LISTADO_COMFABOY_NETOS.ID_DE_EMPLEADO 
             AND HISTORICOS.COMPANIA = LISTADO_COMFABOY_NETOS.COMPANIA
       LEFT JOIN PERSONAL 
              ON HISTORICOS.COMPANIA = PERSONAL.COMPANIA 
             AND HISTORICOS.ID_DE_EMPLEADO = PERSONAL.ID_DE_EMPLEADO
 WHERE HISTORICOS.COMPANIA = s$compania$s
   AND CONCEPTOS.CLASE     = s$claseConc$s
   AND CONCEPTOS.FACTOR_PARAFISCAL NOT IN(0)
   AND HISTORICOS.ANO      = s$anio$s
   AND HISTORICOS.MES      = s$mes$s
 GROUP BY 's$afiliacion$s', 
          PERSONAL.NOMBRECOMPLETO, 
          PERSONAL.NUMERO_DCTO,
          HISTORICOS.ANO, 
          HISTORICOS.MES
 ORDER BY PERSONAL.NOMBRECOMPLETO     
