MERGE INTO CONSULTAS FIN USING (SELECT '900030CertificadoIngresosRentenciones' INFORME ,TO_CLOB(q'[SELECT 
  'CERTIFICADO DE INGRESOS Y RENTENCIONES' DOCUMENTOENVIADO,
  CASE WHEN NVL(ENVIO_CORREO_DIAN.ENVIO_CORREO_DIAN,0) > 0 THEN 'SI' ELSE 'NO' END ENVIADO,
  PERSONAL.NOMBRECOMPLETO,
  PERSONAL.ID_DE_EMPLEADO,
  PERSONAL.NUMERO_DCTO,
  PERSONAL.COMPANIA,
  PERSONAL.EMAIL_CORPORATIVO
,
  s$FECHA$s AS ANO
  FROM 
  PERSONAL 
  LEFT JOIN 
  ENVIO_CORREO_DIAN
  ON 
  ENVIO_CORREO_DIAN.COMPANIA = PERSONAL.COMPANIA AND 
  ENVIO_CORREO_DIAN.ID_DE_EMPLEADO = PERSONAL.ID_DE_EMPLEADO
  AND ENVIO_CORREO_DIAN.ANO = TO_NUMBER(EXTRACT(YEAR FROM TO_DATE(TO_CHAR('01/01/'||s$FECHA$s),'DD-MM-YYYY')))
  WHERE PERSONAL.COMPANIA = 
 s$COMPANIA$s AND PERSONAL.ID_DE_EMPLEADO NOT IN ( 0 ) AND (PERSONAL.ESTADO_ACTUAL = 
 s$ESTADO$s OR ( PERSONAL.ESTADO_ACTUAL=s$ESTADO$s AND FECHA_DE_RETIRO >= TO_DATE(TO_CHAR('01/01/'||s$FECHA$s),
 'DD/MM/YYYY') ) ) AND PERSONAL.ID_DE_EMPLEADO = CASE WHEN ( 
 s$ID_DE_EMPLEADO$s ) = 0 THEN PERSONAL.ID_DE_EMPLEADO ELSE TO_NUMBER(s$ID_DE_EMPLEADO$s) END ORDER BY PERSONAL.ID_DE_EMPLEADO]') CONSULTA, 6 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);