CREATE OR REPLACE VIEW DO_PPTALCOMPORTAMIENTOMES
AS SELECT T.*,
    LAST_DAY(TO_DATE('01/' || LPAD(MES,2,0) || '/' || ANO, 'DD/MM/YYYY')) FECHA
FROM (
     SELECT ACTUAL.COMPANIA, ACTUAL.ANO, 
           ACTUAL.MES, 
           LPAD(MES.NUMERO,2,0) || '-' || MES.NOMBRE MES_NOMBRE,
           LENGTH(ACTUAL.ID) NIVEL,
           ACTUAL.CODIGO, 
           ACTUAL.ID, 
           ACTUAL.NOMBRE, 
           ACTUAL.FUENTE_RECURSO, 
           FUENTE_RECURSOS.NOMBRE FUENTE_NOM,
           TIPOVIGENCIA.NOMBRE TIPOVIGENCIA,
           ACTUAL.VIGENCIA, 
           TIPODESTINO.NOMBRE DESTINO,
           --SUM(ACTUAL.APRDEFINITIVA) OVER (Partition BY ACTUAL.COMPANIA, ACTUAL.ANO, ACTUAL.ID ORDER BY ACTUAL.COMPANIA, ACTUAL.ANO, ACTUAL.MES, ACTUAL.ID)- ACTUAL.APRDEFINITIVA APRANTERIOR,
           SUM(ACTUAL.APROPIADO) OVER (Partition BY ACTUAL.COMPANIA, ACTUAL.ANO, ACTUAL.ID ORDER BY ACTUAL.COMPANIA, ACTUAL.ANO, ACTUAL.MES, ACTUAL.ID) APROPIADO,
           ACTUAL.ADICION, 
           ACTUAL.REDUCCION, 
           ACTUAL.TRASLADO, 
           SUM(ACTUAL.APRDEFINITIVA) OVER (Partition BY ACTUAL.COMPANIA, ACTUAL.ANO, ACTUAL.ID ORDER BY ACTUAL.COMPANIA, ACTUAL.ANO, ACTUAL.MES, ACTUAL.ID)  APRDEFINITIVA,
           SUM(ACTUAL.EJECUCIONPPT) OVER (Partition BY ACTUAL.COMPANIA, ACTUAL.ANO, ACTUAL.ID ORDER BY ACTUAL.COMPANIA, ACTUAL.ANO, ACTUAL.MES, ACTUAL.ID) PAGOSEJECUTADOS,
           SUM(ACTUAL.APRDEFINITIVA - ACTUAL.DISPONIBILIDAD) OVER (Partition BY ACTUAL.COMPANIA, ACTUAL.ANO, ACTUAL.ID ORDER BY ACTUAL.COMPANIA, ACTUAL.ANO, ACTUAL.MES, ACTUAL.ID) SALDOAEJECUTAR
    FROM V_RESUMENPPTO_BASE ACTUAL INNER JOIN MES
      ON ACTUAL.COMPANIA =  MES.COMPANIA
     AND ACTUAL.ANO      =  MES.ANO
     AND ACTUAL.MES      =  MES.NUMERO
     LEFT JOIN FUENTE_RECURSOS
      ON ACTUAL.COMPANIA       =  FUENTE_RECURSOS.COMPANIA
     AND ACTUAL.ANO            =  FUENTE_RECURSOS.ANO
     AND ACTUAL.FUENTE_RECURSO =  FUENTE_RECURSOS.CODIGO
     LEFT JOIN TIPOVIGENCIA
      ON ACTUAL.TIPOVIGENCIA = TIPOVIGENCIA.CODIGO
     LEFT JOIN TIPODESTINO
      ON ACTUAL.DESTINO = TIPODESTINO.CODIGO
  ) T
  WHERE T.MES BETWEEN 1 AND 12;
  
COMMENT ON TABLE DO_PPTALCOMPORTAMIENTOMES IS 'Consulta para el Dasboard ';