SELECT 
  TO_CHAR(SYSDATE, 'DD')||LOWER(' de ')||PCK_SYSMAN_UTL.FC_NOMBRE_MES(TO_CHAR(SYSDATE, 'MM'))||LOWER(' de ')||TO_CHAR(SYSDATE,'YYYY') FECHA_ACTUAL,
  P.NOMBRECOMPLETO,
  P.NUMERO_DCTO,
  CD1.NOMBRE AS EXPEDIDA,
  P.ID_DE_EMPLEADO,
  TO_CHAR(P.FECHA_DE_INGRESO, 'DD')||LOWER(' de ')||PCK_SYSMAN_UTL.FC_NOMBRE_MES(TO_CHAR(P.FECHA_DE_INGRESO, 'MM'))||LOWER(' de ')||TO_CHAR(P.FECHA_DE_INGRESO,'YYYY') AS FECHA_INGRESO,
  C.NOMBRE_DEL_CARGO AS CARGO,
  E.NOMBRE           AS NIVEL,
  DP.NOMBRE          AS DEPENDENCIA,
  CT.SALARIO_BASE    AS SALARIOBASE,
  P.ANO,
  FM.NOMBREFORMA AS FORMA_NOMBRAMIENTO,
  CD.NOMBRE AS CIUDAD,
  TO_CHAR(SYSDATE, 'DD') DIA_FECHA_ACTUAL,
  TO_CHAR(SYSDATE, 'Month') LMES_FECHA_ACTUAL,
  TO_CHAR(SYSDATE, 'YYYY') ANO_FECHA_ACTUAL  ,
 PCK_SYSMAN_UTL.FC_PAR(AUS.COMPANIA, 'CODIGO TABLA RETENCION', 6, SYSDATE) CODIGO_TAB_RETENCION,
  PCK_SYSMAN_UTL.FC_PAR(AUS.COMPANIA, 'NOMBRE DE QUIEN FIRMA CERTIFICADO DE SALARIOS', 6, SYSDATE) FIRMA_CERTIFICADO, 
  PCK_SYSMAN_UTL.FC_PAR(AUS.COMPANIA, 'CARGO DE QUIEN FIRMA CERTIFICADO DE SALARIOS', 6, SYSDATE) CARGO_CERTIFICADO,
  PCK_SYSMAN_UTL.FC_PAR(AUS.COMPANIA, 'ELABORADO POR EN CERTIFICACIONES', 6, SYSDATE) ELABORADO_CERTIFICADO 
FROM PERSONAL P
INNER JOIN CARGOS C
  ON P.COMPANIA             = C.COMPANIA
  AND P.ID_DE_CARGO         = C.ID_DE_CARGO
INNER JOIN CATEGORIA CT
  ON P.COMPANIA             = CT.COMPANIA
  AND P.ESCALAFON           = CT.ESCALAFON
  AND P.ANO                 = CT.ANO
  AND P.ID_DE_CATEGORIA     = CT.ID_DE_CATEGORIA
INNER JOIN COMPANIA CP
 ON P.COMPANIA              = CP.CODIGO
INNER JOIN CIUDAD CD
 ON  CP.PAIS                = CD.PAIS
 AND CP.DEPARTAMENTO        = CD.DEPARTAMENTO
 AND CP.CIUDAD              = CD.CODIGO
LEFT JOIN CIUDAD CD1
 ON  P.PAIS_CED             = CD1.PAIS
 AND P.DEPARTAMENTO_CED     = CD1.DEPARTAMENTO
 AND P.EXPEDIDA             = CD1.CODIGO
INNER JOIN DEPENDENCIA DP
 ON P.COMPANIA              = DP.COMPANIA
 AND P.DEPENDENCIA          = DP.CODIGO
INNER JOIN FORMANOMBRAMIENTO FM
 ON  P.COMPANIA             = FM.COMPANIA
 AND P.DE_CARRERA           = FM.IDFORMA
INNER JOIN ESCALAFON E
 ON  P.COMPANIA             = E.COMPANIA
 AND P.ESCALAFON            = E.CODIGO
INNER JOIN AUT_SOLICITUDES AUS
 ON  P.COMPANIA             = AUS.COMPANIA
 AND P.ID_DE_EMPLEADO       = AUS.ID_DEMPLEADO
WHERE AUS.COMPANIA            = s$compania$s
  AND AUS.CONSECUTIVO         = s$consecutivo$s
  AND AUS.CLASE_SOLICITUD     = s$claseSolicitud$s