SELECT NAT_FUNCIONES_AREAS.CODIGOAREA,
  NAT_FUNCIONES_AREAS.IDCARGO,
  NAT_FUNCIONES_AREAS.IDFUNCION,
  NAT_FUNCIONES_AREAS.ANO,
  NAT_FUNCIONES_AREAS.DESCRIPCION_FUNCION_AREAS,
  NAT_FUNCIONES_AREAS.FECHA_CREACION
FROM NAT_FUNCIONES_AREAS
WHERE NAT_FUNCIONES_AREAS.COMPANIA = s$compania$s 
AND NAT_FUNCIONES_AREAS.CODIGOAREA = s$codigoarea$s
AND NAT_FUNCIONES_AREAS.IDCARGO      = s$idcargo$s
