SELECT 
  AC_CONSECUTIVO
 ,AC_CLASE
 ,AC_SECTOR
 ,AC_NOMBENTI
 ,AC_ANOS
 ,AC_MESES
FROM NAT_ACTIVIDADES 
WHERE COMPANIA    = $P!{PR_COMPANIA} 
  AND DP_NUMEDOCU = $P!{PR_NUMERO_DCTO} 
  AND SUCURSAL    = $P!{PR_SUCURSAL}       
ORDER BY AC_CONSECUTIVO
