SELECT DISTINCT 
  COMPANIA
 ,DP_NUMEDOCU
 ,DP_TIPODOCU
 ,SC_CARGOV
 ,SC_CARGON
 ,SC_NUME
 ,SC_TIPODOCUACTO
 ,SC_FECHRESODECR
FROM NAT_SUPRESION_CARGO
WHERE COMPANIA    = $P!{PR_COMPANIA}
  AND DP_NUMEDOCU = $P!{PR_DP_NUMEDOCU}
  AND SUCURSAL    = $P!{PR_SUCURSAL}
ORDER BY DP_NUMEDOCU DESC
