SELECT NAT_PUBLICACIONES.DP_TIPODOCU,
  NAT_PUBLICACIONES.DP_NUMEDOCU,
  NAT_PUBLICACIONES.PU_CONSECUTIVO,
  NAT_PUBLICACIONES.PU_TIPO,
  NAT_PUBLICACIONES.PU_DESCRIPCION,
  NAT_DATOS_PERSONALES.APELLIDO1,
  NAT_DATOS_PERSONALES.APELLIDO2,
  NAT_DATOS_PERSONALES.NOMBRES,
  NAT_DATOS_PERSONALES.NUMEROCARPETA
FROM NAT_PUBLICACIONES
LEFT JOIN NAT_DATOS_PERSONALES
ON NAT_PUBLICACIONES.COMPANIA    = NAT_DATOS_PERSONALES.COMPANIA
AND NAT_PUBLICACIONES.DP_NUMEDOCU= NAT_DATOS_PERSONALES.NUMERO_DCTO
WHERE NAT_PUBLICACIONES.COMPANIA = s$compania$s
AND NAT_DATOS_PERSONALES.NUMEROCARPETA BETWEEN 's$carpetaInicial$s' AND 's$carpetaFinal$s'
