SELECT 
  TRIM(NOMBRE) || ' ' || TRIM(APELLIDO1) || ' ' || TRIM(APELLIDO2) NOMBRECOMPLETO
 ,PARENTESCO.DESCRIPCION PARENTESCO
 ,FAMILIARES.FECHANCTO
 ,FAMILIARES.OCUPACION
 ,TIPOS_DOCUMENTOS.DESCRIPCION TIPODOC
 ,FAMILIARES.IDENTIFICACION
FROM FAMILIARES
  LEFT JOIN PARENTESCO
    ON FAMILIARES.COMPANIA   = PARENTESCO.COMPANIA
   AND FAMILIARES.PARENTESCO = PARENTESCO.PARENTESCO
  LEFT JOIN TIPOS_DOCUMENTOS
    ON FAMILIARES.COMPANIA       = TIPOS_DOCUMENTOS.COMPANIA
   AND FAMILIARES.DCTO_IDENTIDAD = TIPOS_DOCUMENTOS.DCTO_IDENTIDAD
WHERE FAMILIARES.COMPANIA              = $P!{PR_COMPANIA} 
  AND FAMILIARES.DCTO_EMPLEADO      = $P!{PR_DCTO_EMPLEADO}
  AND FAMILIARES.SUCURSAL_EMPLEADO  = $P!{PR_SUCURSAL}
