SELECT
  ENCARGOS.COMPANIA
 ,ENCARGOS.EC_GASTOSREPRESENTACION
 ,ENCARGOS.TIPOACTO
 ,ENCARGOS.TIPO_NOVEDAD
 ,ENCARGOS.SUELDOMENSUAL
 ,NVL(ENCARGOS.ACTA,' ') ACTA
 ,ENCARGOS.ACTO
 ,ENCARGOS.CARGO
 ,ENCARGOS.CLASE_ENCARGO
 ,ENCARGOS.DEPENDENCIA
 ,ENCARGOS.DETALLE_ENCARGOC
 ,ENCARGOS.DETALLE_ENCARGOF
 ,ENCARGOS.DOCSOPORTEFECHA
 ,ENCARGOS.DOCSOPORTENUMERO
 ,ENCARGOS.DOCSOPORTETIPO
 ,ENCARGOS.EC_AUXA
 ,ENCARGOS.EC_AUXT
 ,ENCARGOS.EC_PRIMAALTAGESTION
 ,ENCARGOS.EC_PRIMATECNICAFACTOR
 ,ENCARGOS.EC_PRIMATECNICANFACTOR
 ,ENCARGOS.ESCALAFON
 ,NVL(TO_CHAR(TRUNC(ENCARGOS.FECHAACTA),'DD/MM/YYYY'),' ') FECHAACTA
 ,ENCARGOS.FECHAACTO
 ,ENCARGOS.FECHAEFECTIVIDAD
 ,ENCARGOS.FECHAFINAL
 ,ENCARGOS.FECHAINICIO
 ,ENCARGOS.FECHAPAGO
 ,ENCARGOS.ID_DE_CARGO
 ,ENCARGOS.ID_DE_CATEGORIA
 ,ENCARGOS.ID_DE_EMPLEADO
 ,ENCARGOS.ID_DE_PROCESO
 ,ENCARGOS.MOTIVOENCARGO
 ,DATOS.NUMERO_DCTO
FROM NAT_DATOS_PERSONALES DATOS
  INNER JOIN ENCARGOS
	 ON DATOS.COMPANIA    = ENCARGOS.COMPANIA
	AND DATOS.NUMERO_DCTO = ENCARGOS.NUMERO_DCTO
	AND DATOS.SUCURSAL    = ENCARGOS.SUCURSAL
WHERE DATOS.COMPANIA    = $P!{PR_COMPANIA}
  AND DATOS.NUMERO_DCTO = $P!{PR_NUMERO_DCTO}
  AND DATOS.SUCURSAL    = $P!{PR_SUCURSAL}
ORDER BY ENCARGOS.FECHAEFECTIVIDAD DESC
