WITH PAISDEPTOCIUDAD AS 
(SELECT  PAISES.PAIS,
        DEPARTAMENTO.CODIGO DEPARTAMENTO,
        CIUDAD.CODIGO CIUDAD,
        PAISES.NOMBRE  NOMPAIS,
        DEPARTAMENTO.NOMBRE  NOMDEPTO,
        CIUDAD.NOMBRE  NOMCIUDAD
FROM PAISES
  LEFT JOIN DEPARTAMENTO
    ON PAISES.PAIS = DEPARTAMENTO.PAIS
  LEFT JOIN CIUDAD
    ON DEPARTAMENTO.PAIS  = CIUDAD.PAIS
    AND DEPARTAMENTO.CODIGO = CIUDAD.DEPARTAMENTO)
SELECT  PAISDEPTOCIUDAD.NOMPAIS PAISNACIMIENTO, 
        PAISDEPTOCIUDAD.NOMDEPTO DEPARTAMENTONACMIENTO, 
        PAISDEPTOCIUDAD.NOMCIUDAD CIUDADNACIMIENTO, 
        NAT_DATOS_PERSONALES.APELLIDO1,
        NAT_DATOS_PERSONALES.APELLIDO2,
        NAT_DATOS_PERSONALES.NOMBRES,
        CASE WHEN NAT_DATOS_PERSONALES.SEXO IN ('M') THEN 'x' ELSE '' END SEXOM,
        CASE WHEN NAT_DATOS_PERSONALES.SEXO IN ('F') THEN 'x' ELSE '' END SEXOF,
        CASE WHEN NAT_DATOS_PERSONALES.NACIONALIDAD IN ('C') THEN 'x' ELSE '' END NACC,
        CASE WHEN NAT_DATOS_PERSONALES.NACIONALIDAD IN ('D') THEN 'x' ELSE '' END NACD,
        CASE WHEN NAT_DATOS_PERSONALES.NACIONALIDAD IN ('E') THEN 'x' ELSE '' END NACE,
        CASE WHEN NAT_DATOS_PERSONALES.DCTO_IDENTIDAD IN ('C') THEN 'x' ELSE '' END DOCC,
        CASE WHEN NAT_DATOS_PERSONALES.DCTO_IDENTIDAD IN ('T') THEN 'x' ELSE '' END DOCT,
        CASE WHEN NAT_DATOS_PERSONALES.DCTO_IDENTIDAD IN ('E') THEN 'x' ELSE '' END DOCCE,
        CASE WHEN NAT_DATOS_PERSONALES.DCTO_IDENTIDAD IN ('O') THEN 'x' ELSE '' END DOCO,
        NAT_DATOS_PERSONALES.NUMERO_DCTO,
        NAT_DATOS_PERSONALES.FECHANCTO,
        CASE NAT_DATOS_PERSONALES.ESTADO_CIVIL  
          WHEN '01' THEN 'SOLTERO'
          WHEN '02' THEN 'CASADO'
          WHEN '03' THEN 'UNION LIBRE'
          WHEN '04' THEN 'VIUDO(A)'
          WHEN '05' THEN 'SEPARADO'
          WHEN '06' THEN 'DIVORCIADO(A)'
          ELSE ''
        END  ESTADO_CIVIL,
        NAT_DATOS_PERSONALES.RH,
        NAT_DATOS_PERSONALES.NUMLIBMILITAR,
        PAISDEPTOCIUDAD_1.NOMPAIS RESPAIS, 
        PAISDEPTOCIUDAD_1.NOMDEPTO RESDEPT, 
        PAISDEPTOCIUDAD_1.NOMCIUDAD RESCIUDAD, 
          NAT_DATOS_PERSONALES.TELEFONOS,
        NAT_DATOS_PERSONALES.DIRECCION,
        NAT_DATOS_PERSONALES.NUMEROCARPETA,
        NAT_DATOS_PERSONALES.CODIGO
FROM NAT_DATOS_PERSONALES 
  LEFT JOIN PAISDEPTOCIUDAD 
    ON NAT_DATOS_PERSONALES.PAISNCTO 			= PAISDEPTOCIUDAD.PAIS  
    AND NAT_DATOS_PERSONALES.DEPTONCTO 			= PAISDEPTOCIUDAD.DEPARTAMENTO 
    AND NAT_DATOS_PERSONALES.MUNICIPIONCTO 		= PAISDEPTOCIUDAD.CIUDAD 
  LEFT JOIN PAISDEPTOCIUDAD PAISDEPTOCIUDAD_1 
    ON NAT_DATOS_PERSONALES.PAISRESIDE 			= PAISDEPTOCIUDAD_1.PAIS 
    AND NAT_DATOS_PERSONALES.DEPTORESIDE 		= PAISDEPTOCIUDAD_1.DEPARTAMENTO 
    AND NAT_DATOS_PERSONALES.MUNICIPIORESIDE 	= PAISDEPTOCIUDAD_1.CIUDAD 
WHERE NAT_DATOS_PERSONALES.COMPANIA     		= $P!{PR_COMPANIA} 
 AND NAT_DATOS_PERSONALES.NUMERO_DCTO   		= $P!{PR_NUMERO_DCTO} 
 AND NAT_DATOS_PERSONALES.SUCURSAL     			= $P!{PR_SUCURSAL} 
ORDER BY NAT_DATOS_PERSONALES.NUMERO_DCTO
