SELECT
 DISTINCT
  NO_TIPODOCUACTO
 ,NO_NUME
 ,NO_CAUSA
 ,NO_ACTAPOSE
 ,NO_FECHAEFECTIVIDAD
 ,NO_TIPO
 ,EN_FECHDESDE
 ,NO_FECHRESODECR
 ,EN_FECHHASTA
 ,NO_CARGOA
 ,NO_DEPEANTE
 ,NO_SALARIOA
 ,NO_CARGON
 ,DP_NUMEDOCU
 ,NO_DEPENUEV
 ,NO_SALARION
 ,NVL(TO_CHAR(TRUNC(NO_FECHACTAPOSE),'DD/MM/YYYY'),' ') NO_FECHACTAPOSE
FROM NAT_NOMBRAMIENTO
WHERE COMPANIA    = $P!{PR_COMPANIA}
  AND DP_NUMEDOCU = $P!{PR_NUMERO_DCTO}
  AND SUCURSAL    = $P!{PR_SUCURSAL}
