WITH PAISDEPTOCIUDAD AS(
SELECT 
  P.PAIS
 ,D.CODIGO DEPARTAMENTO
 ,C.CODIGO CIUDAD
 ,P.NOMBRE NOMPAIS
 ,D.NOMBRE NOMDEPTO
 ,C.NOMBRE NOMCIUDAD
FROM PAISES P
  INNER JOIN DEPARTAMENTO D
    ON P.PAIS = D.PAIS
  INNER JOIN CIUDAD C
    ON D.CODIGO = C.DEPARTAMENTO
   AND D.PAIS   = C.PAIS
)
SELECT 
  NCTO.NOMPAIS
 ,NCTO.NOMDEPTO    
 ,NCTO.NOMCIUDAD   
 ,RESIDE.NOMPAIS   RESPAIS
 ,RESIDE.NOMDEPTO  RESDEPT
 ,RESIDE.NOMCIUDAD RESCIUDAD
 ,DATOS.APELLIDO1
 ,DATOS.APELLIDO2
 ,DATOS.NOMBRES
 ,DATOS.DCTO_IDENTIDAD
 ,DATOS.NACIONALIDAD
 ,DATOS.SEXO
 ,DATOS.NUMLIBMILITAR
 ,DATOS.FECHANCTO
 ,E.DESCRIPCION ESTADO_CIVIL
 ,DATOS.RH
 ,DATOS.TELEFONOS
 ,DATOS.DIRECCION
 ,DATOS.NUMERO_DCTO
FROM NAT_DATOS_PERSONALES DATOS
  LEFT JOIN PAISDEPTOCIUDAD NCTO
    ON DATOS.PAISNCTO      = NCTO.PAIS
   AND DATOS.DEPTONCTO     = NCTO.DEPARTAMENTO
   AND DATOS.MUNICIPIONCTO = NCTO.CIUDAD
  LEFT JOIN PAISDEPTOCIUDAD RESIDE
    ON DATOS.PAISRESIDE      = RESIDE.PAIS
   AND DATOS.DEPTORESIDE     = RESIDE.DEPARTAMENTO
   AND DATOS.MUNICIPIORESIDE = RESIDE.CIUDAD
  INNER JOIN ESTADO_CIVIL E
    ON DATOS.COMPANIA     = E.COMPANIA
   AND DATOS.ESTADO_CIVIL = E.ESTADO_CIVIL
WHERE DATOS.COMPANIA = s$compania$s
  AND DATOS.FECHARETIRO IS NOT NULL 
  AND DATOS.NUMERO_DCTO BETWEEN s$empleadoInicial$s AND s$empleadoFinal$s
ORDER BY DATOS.NUMERO_DCTO 
