SELECT DISTINCT  SST_D_CRONOGRAMA.CONSECUTIVO,
        SST_D_CRONOGRAMA.ID_EMPLEADO,
        SST_TIPORACI.NOMBRE,
        SST_D_CRONOGRAMA.CEDULA,
        SST_D_CRONOGRAMA.SUCURSAL,
        PERSONAL.NOMBRECOMPLETO NOMBREREP
FROM SST_D_CRONOGRAMA
  LEFT JOIN PERSONAL 
    ON SST_D_CRONOGRAMA.COMPANIA = PERSONAL.COMPANIA
    AND SST_D_CRONOGRAMA.CEDULA = PERSONAL.NUMERO_DCTO
    AND SST_D_CRONOGRAMA.SUCURSAL = PERSONAL.SUCURSAL
  LEFT JOIN SST_TIPORACI
    ON SST_D_CRONOGRAMA.TIPO_RACI         = SST_TIPORACI.CODIGO
WHERE SST_D_CRONOGRAMA.COMPANIA           = $P!{PR_COMPANIA}
  AND SST_D_CRONOGRAMA.CONSECUTIVO        = $P!{PR_CONSECUTIVO}
  AND SST_D_CRONOGRAMA.CODIGO_ACTIVIDAD   = $P!{PR_CODIGOACTIVIDAD}
