WITH PAISDEPTOCIUDAD AS(
SELECT 
  P.PAIS
 ,D.CODIGO DEPARTAMENTO
 ,C.CODIGO CIUDAD
 ,P.NOMBRE NOMPAIS
 ,D.NOMBRE NOMDEPTO
 ,C.NOMBRE NOMCIUDAD
FROM PAISES P
  INNER JOIN DEPARTAMENTO D
    ON P.PAIS = D.PAIS
  INNER JOIN CIUDAD C
    ON D.CODIGO = C.DEPARTAMENTO
   AND D.PAIS   = C.PAIS
)
SELECT 
  D.NUMEROCARPETA
 ,D.CODIGO
 ,D.NUMERO_DCTO
 ,(D.APELLIDO1 ||' '|| D.APELLIDO2 ||' '|| D.NOMBRES) NOMBREPERSONA
 ,C.CO_TIPODOCUACTO
 ,C.CO_NUME
 ,C.CO_FECHRESODECR
 ,CARGOS.NOMBRE_DEL_CARGO                             CO_CARGO
 ,C.CO_ENTI
 ,PDC.NOMPAIS                                         CO_PAIS
 ,PDC.NOMDEPTO                                        CO_DPTO
 ,PDC.NOMCIUDAD                                       CO_MUNI
 ,C.CO_FECHDESDE
 ,C.CO_FECHHASTA
 ,C.CO_DESC
FROM NAT_DATOS_PERSONALES D
 INNER JOIN NAT_COMISION C
    ON D.COMPANIA    = C.COMPANIA
   AND D.NUMERO_DCTO = C.CO_NUMEDOCU
   AND D.SUCURSAL    = C.SUCURSAL
  LEFT JOIN PAISDEPTOCIUDAD PDC
    ON C.COPAIS = PDC.PAIS
   AND C.CODPTO = PDC.DEPARTAMENTO
   AND C.COMUNI = PDC.CIUDAD
  LEFT JOIN CARGOS
    ON C.COMPANIA = CARGOS.COMPANIA
   AND C.CO_CARGO = CARGOS.ID_DE_CARGO
WHERE D.COMPANIA = s$compania$s
  AND D.NUMERO_DCTO BETWEEN s$empleadoInicial$s AND s$empleadoFinal$s
