  SELECT CARGOS.ID_DE_CARGO,
    DEPENDENCIA.NOMBRE NOMBRE_DEPENDENCIA,
    SST_ELEMENTO_PROTECCION.NOMBRE,
    PERSONAL.ID_DE_EMPLEADO,
    CARGOS.ID_DE_CARGO,
    DEPENDENCIA.NOMBRE   CODIGO,
    ELEMENTO_PROTECCION_PERSONAL.FECHAENTREGA,
      CASE WHEN TERCERO.NOMBRE1 IS NULL THEN '' ELSE
           TERCERO.NOMBRE1 ||' ' END ||
      CASE WHEN TERCERO.NOMBRE2 IS NULL THEN '' ELSE
           TERCERO.NOMBRE2 ||' ' END ||
      CASE WHEN TERCERO.APELLIDO1 IS NULL THEN '' ELSE
           TERCERO.APELLIDO1 ||' ' END ||
      CASE WHEN TERCERO.APELLIDO2 IS NULL THEN '' ELSE
           TERCERO.APELLIDO2 ||' ' END  NOMBRE_EMPLEADO,
    ELEMENTO_PROTECCION_PERSONAL.CONSECUTIVO,
    SST_ELEMENTO_PROTECCION.CODIGOELEMENTO,
    CARGOS.NOMBRE_DEL_CARGO,
    ELEMENTO_PROTECCION_PERSONAL.OBSERVACION,
    CASE WHEN s$ordenar$s IN (1) 
     THEN ELEMENTO_PROTECCION_PERSONAL.DEPENDENCIA 
     ELSE TO_CHAR(PERSONAL.ID_DE_EMPLEADO)
     END AGRUPACION,
      CASE WHEN s$ordenar$s IN (1) 
     THEN 'POR DEPENDENCIA'
     ELSE 'POR PERSONA'
     END MOSTRAR
  FROM PERSONAL
    INNER JOIN DEPENDENCIA
      ON PERSONAL.COMPANIA = DEPENDENCIA.COMPANIA
      AND PERSONAL.DEPENDENCIA = DEPENDENCIA.CODIGO
    INNER JOIN CARGOS
      ON PERSONAL.COMPANIA = CARGOS.COMPANIA
      AND PERSONAL.ID_DE_CARGO = CARGOS.ID_DE_CARGO
      AND PERSONAL.ESCALAFON  = CARGOS.ESCALAFON
    INNER JOIN ELEMENTO_PROTECCION_PERSONAL
      ON PERSONAL.COMPANIA = ELEMENTO_PROTECCION_PERSONAL.COMPANIA
      AND PERSONAL.ID_DE_EMPLEADO = ELEMENTO_PROTECCION_PERSONAL.ID_DE_EMPLEADO
    INNER JOIN SST_ELEMENTO_PROTECCION
      ON ELEMENTO_PROTECCION_PERSONAL.COMPANIA = SST_ELEMENTO_PROTECCION.COMPANIA
      AND ELEMENTO_PROTECCION_PERSONAL.ELEMENTO   = SST_ELEMENTO_PROTECCION.CODIGOELEMENTO
      INNER JOIN TERCERO
        ON PERSONAL.COMPANIA = TERCERO.COMPANIA
        AND PERSONAL.NUMERO_DCTO = TERCERO.NIT
        AND PERSONAL.SUCURSAL = TERCERO.SUCURSAL
  WHERE SST_ELEMENTO_PROTECCION.COMPANIA     = s$compania$s
    AND SST_ELEMENTO_PROTECCION.CODIGOELEMENTO BETWEEN s$codigoElemento$s AND s$codigoElementoFinal$s
    AND ELEMENTO_PROTECCION_PERSONAL.FECHAENTREGA BETWEEN TO_DATE('s$fechaInicial$s','DD/MM/YYYY') AND TO_DATE('s$fechaFinal$s','DD/MM/YYYY')
    AND DEPENDENCIA.CODIGO BETWEEN s$codigoDependencia$s AND s$codigoDependenciaFinal$s
    AND CARGOS.ID_DE_CARGO = s$codigoCargo$s
  GROUP BY CARGOS.ID_DE_CARGO,
    DEPENDENCIA.NOMBRE,
    SST_ELEMENTO_PROTECCION.NOMBRE,
    PERSONAL.ID_DE_EMPLEADO,
    CARGOS.ID_DE_CARGO,
    DEPENDENCIA.CODIGO,
    ELEMENTO_PROTECCION_PERSONAL.FECHAENTREGA,
      CASE WHEN TERCERO.NOMBRE1 IS NULL THEN '' ELSE
           TERCERO.NOMBRE1 ||' ' END ||
      CASE WHEN TERCERO.NOMBRE2 IS NULL THEN '' ELSE
           TERCERO.NOMBRE2 ||' ' END ||
      CASE WHEN TERCERO.APELLIDO1 IS NULL THEN '' ELSE
           TERCERO.APELLIDO1 ||' ' END ||
      CASE WHEN TERCERO.APELLIDO2 IS NULL THEN '' ELSE
           TERCERO.APELLIDO2 ||' ' END,
    ELEMENTO_PROTECCION_PERSONAL.CONSECUTIVO,
    SST_ELEMENTO_PROTECCION.CODIGOELEMENTO,
    CARGOS.NOMBRE_DEL_CARGO,
    ELEMENTO_PROTECCION_PERSONAL.OBSERVACION,
    CASE WHEN s$ordenar$s IN (1) 
     THEN ELEMENTO_PROTECCION_PERSONAL.DEPENDENCIA 
     ELSE TO_CHAR(PERSONAL.ID_DE_EMPLEADO)END
  ORDER BY ELEMENTO_PROTECCION_PERSONAL.CONSECUTIVO,
    DEPENDENCIA.CODIGO
