SELECT 
DISTINCT
  SST_TRANSACCIONES.COMPANIA,
  SST_TIPO_TRANSACCION.CODIGO,
  UPPER(SST_TIPO_TRANSACCION.NOMBRE)AS NOMBRET,
  SST_TRANSACCIONES.CONSECUTIVO,
  SST_TRANSACCIONES.FECHA,
  SST_TRANSACCIONES.HORA_INICIO HORA,
  SST_CLASE_EVENTO.NOMBRE AS NOMBRECLASE,
  SST_TRANSACCIONES.DESCRIPCION,
  SST_TRANSACCIONES.ID_EMPLEADO,
  PERSONAL.NOMBRES || ' '|| PERSONAL.APELLIDO1 || ' '|| PERSONAL.APELLIDO2 AS NOMBREP,
  SST_TRANSACCIONES.CEDULA,
  SST_TRANSACCIONES.SUCURSAL,
  SST_TRANSACCIONES.TEXTO,
  SST_D_TRANSACCIONES.CONSECUTIVO CONSECUTIVODET,
  SST_TRANSACCIONES.CLASE_AGENTE,
  SST_CLASE_AGENTE.NOMBRE NOMBRECLASEAGENTE,
  SST_AGENTES.NOMBRE NOMBREAGENTE,
  SST_TRANSACCIONES.AGENTE
FROM SST_TRANSACCIONES
  INNER JOIN SST_TIPO_TRANSACCION
    ON SST_TRANSACCIONES.COMPANIA                   = SST_TIPO_TRANSACCION.COMPANIA     
   AND SST_TRANSACCIONES.TIPO_TRANSACCION           = SST_TIPO_TRANSACCION.CODIGO
  INNER JOIN SST_CLASE_EVENTO
    ON  SST_TRANSACCIONES.COMPANIA                  = SST_CLASE_EVENTO.COMPANIA
   AND SST_TRANSACCIONES.TIPO_TRANSACCION           = SST_CLASE_EVENTO.TIPO_TRANSACCION 
   AND SST_TRANSACCIONES.CLASE_EVENTO               = SST_CLASE_EVENTO.CODIGO 
  INNER JOIN PERSONAL
    ON SST_TRANSACCIONES.COMPANIA                   = PERSONAL.COMPANIA
   AND SST_TRANSACCIONES.ID_EMPLEADO                = PERSONAL.ID_DE_EMPLEADO
   AND SST_TRANSACCIONES.CEDULA                     = PERSONAL.NUMERO_DCTO
   AND SST_TRANSACCIONES.SUCURSAL                   = PERSONAL.SUCURSAL
  LEFT JOIN SST_D_TRANSACCIONES
    ON   SST_TRANSACCIONES.COMPANIA                 = SST_D_TRANSACCIONES.COMPANIA 
    AND  SST_TRANSACCIONES.TIPO_TRANSACCION         = SST_D_TRANSACCIONES.TIPO_TRANSACCION
    AND  SST_TRANSACCIONES.CONSECUTIVO              = SST_D_TRANSACCIONES.CONSECUTIVO
  LEFT JOIN SST_TRANSACCION_ACTIVIDAD
    ON SST_TRANSACCIONES.COMPANIA                   = SST_TRANSACCION_ACTIVIDAD.COMPANIA
    AND SST_TRANSACCIONES.TIPO_TRANSACCION          = SST_TRANSACCION_ACTIVIDAD.TIPO_TRANSACCION
    AND SST_TRANSACCIONES.CONSECUTIVO               = SST_TRANSACCION_ACTIVIDAD.TRANSACCION
  LEFT JOIN SST_TIPO_ACTIVIDAD
    ON SST_TRANSACCION_ACTIVIDAD.COMPANIA           = SST_TIPO_ACTIVIDAD.COMPANIA
    AND SST_TRANSACCION_ACTIVIDAD.TIPO_TRANSACCION  = SST_TIPO_ACTIVIDAD.TIPO_TRANSACCION  
    AND SST_TRANSACCION_ACTIVIDAD.ACTIVIDAD         = SST_TIPO_ACTIVIDAD.CODIGO
  LEFT JOIN SST_CLASE_AGENTE
    ON SST_TRANSACCIONES.COMPANIA       = SST_CLASE_AGENTE.COMPANIA
    AND SST_TRANSACCIONES.CLASE_AGENTE  = SST_CLASE_AGENTE.CODIGO  
  LEFT JOIN   SST_AGENTES
    ON SST_CLASE_AGENTE.COMPANIA        = SST_AGENTES.COMPANIA 
    AND SST_CLASE_AGENTE.CODIGO         = SST_AGENTES.CLASE  
WHERE SST_TRANSACCIONES.COMPANIA        = s$compania$s
  AND SST_TIPO_TRANSACCION.CODIGO  BETWEEN s$tipoTransaccionInicial$s AND s$tipoTransaccionFinal$s
  AND SST_TRANSACCIONES.CEDULA BETWEEN 's$terceroInicial$s' AND 's$terceroFinal$s'
  AND SST_TRANSACCIONES.CLASE_EVENTO BETWEEN s$claseEventoInicial$s AND s$claseEventoFinal$s
  AND SST_TRANSACCIONES.FECHA BETWEEN TO_DATE('s$fechaInicial$s','DD/MM/YYYY') AND TO_DATE('s$fechaFinal$s','DD/MM/YYYY')
  s$condicionActividad$s
  s$condicionAgente$s
ORDER BY SST_TRANSACCIONES.CONSECUTIVO 
