SELECT DISTINCT
    COMPANIA,
    CODIGO TIPO_TRANSACCION,
    NOMBRET NOMBRE,
    NVL(CLASE_AGENTE,' ' ) CLASE_AGENTE,
    NVL(NOMBRECLASEAGENTE,' ') NOMBRECLASE,
    COUNT(AGENTE) CANTIDAD
FROM (s$consultaBase$s)TRANSACCION
WHERE COMPANIA          = $P!{PR_COMPANIA} 
GROUP BY COMPANIA,
    CODIGO ,
    NOMBRET ,
    NVL(CLASE_AGENTE,' ' ) ,
    NVL(NOMBRECLASEAGENTE,' ') 
ORDER BY CODIGO   
