SELECT CODIGO,
s$nombre$s
SECCION_PRESUPUESTAL,
VIGENCIA_GASTO,
SECTOR,
PROGRAMA,
BPIN,
APROPIACION_INICIAL,
APROPIACION_DEFINITIVA
FROM(
SELECT PLAN_PRESUPUESTAL.CODIGO,
       CUIPO_CODIGO_CCEPT.NOMBRE,
       PLAN_PPTAL_CONFIG.SECCION_PPTAL_CUIPO SECCION_PRESUPUESTAL,
       CASE WHEN PLAN_PPTAL_CONFIG.TIPOVIGENCIA = 'RA' THEN
               '2.0'
           ELSE CASE WHEN PLAN_PPTAL_CONFIG.TIPOVIGENCIA = 'RC' THEN 
                '3.0'
             ELSE '1.0' END
       END  VIGENCIA_GASTO,
       PLAN_PPTAL_CONFIG.SECTOR_CUIPO "SECTOR",
       PLAN_PPTAL_CONFIG.PROGRAMA_CUIPO "PROGRAMA",
       PLAN_PPTAL_CONFIG.CODIGO_BPIN_SGR "BPIN",
       SUM(SAL.APROPIACION_DEBITO) APROPIACION_INICIAL,
       SUM(SAL.APROPIACION_DEBITO + SAL.ADICION + SAL.REDUCCION +(SAL.TRASLADO_DEBITO - SAL.TRASLADO_CREDITO)+(SAL.APLAZAM_DEBITO
       - SAL.APLAZAM_CREDITO))"APROPIACION_DEFINITIVA"
FROM CUIPO_CODIGO_CCEPT
INNER JOIN PLAN_PRESUPUESTAL ON CUIPO_CODIGO_CCEPT.COMPANIA = PLAN_PRESUPUESTAL.COMPANIA
                                AND CUIPO_CODIGO_CCEPT.ANO = PLAN_PRESUPUESTAL.ANO
                                AND CUIPO_CODIGO_CCEPT.CODIGO = PLAN_PRESUPUESTAL.CODIGO
INNER JOIN PLAN_PPTAL_CONFIG ON PLAN_PPTAL_CONFIG.COMPANIA = PLAN_PRESUPUESTAL.COMPANIA
                                AND PLAN_PPTAL_CONFIG.CODIGO = PLAN_PRESUPUESTAL.CODIGO
                                AND PLAN_PPTAL_CONFIG.ANO = PLAN_PRESUPUESTAL.ANO
INNER JOIN SALDO_AUX_PPTAL SAL ON PLAN_PRESUPUESTAL.COMPANIA = SAL.COMPANIA
                                  AND PLAN_PRESUPUESTAL.ANO = SAL.ANO
                                  AND PLAN_PRESUPUESTAL.CODIGO = SAL.CODIGO
WHERE CUIPO_CODIGO_CCEPT.COMPANIA = s$compania$s
      AND PLAN_PRESUPUESTAL.ANO = s$anio$s
      AND SAL.MES  <= s$mesfinal$s
      AND PLAN_PRESUPUESTAL.NATURALEZA = 'D'
      AND PLAN_PRESUPUESTAL.REGALIAS IN(0)
GROUP BY PLAN_PRESUPUESTAL.CODIGO,
         CUIPO_CODIGO_CCEPT.NOMBRE,
         PLAN_PPTAL_CONFIG.SECCION_PPTAL_CUIPO,
         CASE WHEN PLAN_PPTAL_CONFIG.TIPOVIGENCIA = 'RA' THEN '2.0' ELSE 
                 CASE WHEN PLAN_PPTAL_CONFIG.TIPOVIGENCIA = 'RC' THEN '3.0'
                     ELSE '1.0'
                 END
         END,
         PLAN_PPTAL_CONFIG.SECTOR_CUIPO,
         PLAN_PPTAL_CONFIG.PROGRAMA_CUIPO,
         PLAN_PPTAL_CONFIG.CODIGO_BPIN_SGR
   HAVING SUM(Sal.Apropiacion_DEBITO) <>0 
       OR SUM(Sal.Apropiacion_DEBITO + Sal.Adicion +Sal.Reduccion + (SAL.TRASLADO_DEBITO- SAL.TRASLADO_CREDITO) + (Sal.Aplazam_Debito -Sal.Aplazam_Credito)) <>0          
       )CUIPO
       ORDER BY CODIGO