MERGE INTO CONSULTAS FIN USING (SELECT '800435GCN2009BDMESEMESTRAL' INFORME ,TO_CLOB(q'[WITH CONSULTA AS (SELECT  CASE WHEN DEUDORES.DEUDORES >0 THEN '2' ELSE '1' END CONCEPTO,
                    CASE WHEN  TERCERO.NATURALEZA = 'J' THEN '2' ELSE '1' END TIPODEUDOR,
                 DETALLE_COMPROBANTE_CNT.TIPO_CPTE||'-'|| DETALLE_COMPROBANTE_CNT.COMPROBANTE NUMERO ,
                   DETALLE_COMPROBANTE_CNT.TERCERO NIT,   
                  CASE WHEN  TERCERO.TIPOID = 'C' THEN 1    
                       WHEN  TERCERO.TIPOID = 'N' THEN 2 
                       WHEN  TERCERO.TIPOID = 'T' THEN 3  
                       WHEN  TERCERO.TIPOID = 'E' THEN 4 END TIPOID  ,
                   TERCERO.NOMBRE  ,
                   SUM((DETALLE_COMPROBANTE_CNT.VALOR_DEBITO-DETALLE_COMPROBANTE_CNT.VALOR_CREDITO)
                -CASE WHEN DETALLE_COMPROBANTE_CNT.FECHA_ABONOINICIAL<= TO_DATE('s$fecha$s') THEN DETALLE_COMPROBANTE_CNT.ABONOINICIAL ELSE 0 END)
              -NVL(AFEC.VALOR_AFECTACION,0)  VALOR,
                   'N/A' ESTADO ,
                   ANO.SALARIOMINIMO
            FROM COMPROBANTE_CNT
            INNER JOIN TERCERO ON COMPROBANTE_CNT.COMPANIA = TERCERO.COMPANIA
            AND COMPROBANTE_CNT.TERCERO = TERCERO.NIT  
            AND COMPROBANTE_CNT.SUCURSAL = TERCERO.SUCURSAL
            INNER JOIN TIPO_COMPROBANTE ON COMPROBANTE_CNT.COMPANIA = TIPO_COMPROBANTE.COMPANIA
                                           AND COMPROBANTE_CNT.TIPO = TIPO_COMPROBANTE.CODIGO
            INNER JOIN DETALLE_COMPROBANTE_CNT ON COMPROBANTE_CNT.COMPANIA =  DETALLE_COMPROBANTE_CNT.COMPANIA
            AND COMPROBANTE_CNT.ANO = DETALLE_COMPROBANTE_CNT.ANO
            AND COMPROBANTE_CNT.TIPO = DETALLE_COMPROBANTE_CNT.TIPO_CPTE
            AND COMPROBANTE_CNT.NUMERO = DETALLE_COMPROBANTE_CNT.COMPROBANTE	
            INNER JOIN PLAN_CONTABLE ON PLAN_CONTABLE.COMPANIA = DETALLE_COMPROBANTE_CNT.COMPANIA
                                        AND   PLAN_CONTABLE.CODIGO = DETALLE_COMPROBANTE_CNT.CUENTA
                                        AND   PLAN_CONTABLE.ANO = DETALLE_COMPROBANTE_CNT.ANO
              LEFT JOIN (SELECT COUNT(*)DEUDORES,
                   DEUDOR_SOLIDARIO.COMPANIA,
                   DEUDOR_SOLIDARIO.NIT_DEUDORPRINCIPAL,
                   DEUDOR_SOLIDARIO.SUCURSAL_DEUDORPRINCIPAL
            FROM DEUDOR_SOLIDARIO
            INNER JOIN TERCERO ON DEUDOR_SOLIDARIO.COMPANIA = TERCERO.COMPANIA
                                  AND NIT_DEUDORPRINCIPAL = TERCERO.NIT
                                  AND SUCURSAL_DEUDORPRINCIPAL = TERCERO.SUCURSAL
            GROUP BY DEUDOR_SOLIDARIO.COMPANIA,
                     DEUDOR_SOLIDARIO.NIT_DEUDORPRINCIPAL,
                     DEUDOR_SOLIDARIO.SUCURSAL_DEUDORPRINCIPAL) DEUDORES ON TERCERO.COMPANIA = DEUDORES.COMPANIA
                        AND  DEUDORES.NIT_DEUDORPRINCIPAL = TERCERO.NIT
                        AND DEUDORES.SUCURSAL_DEUDORPRINCIPAL = TERCERO.SUCURSAL
            INNER JOIN ANO ON ANO.COMPANIA = COMPROBANTE_CNT.COMPANIA
            AND ANO.NUMERO = s$anio$s
    ]') || TO_CLOB(q'[              LEFT JOIN (SELECT DET.COMPANIA,
                      DET.TERCERO,
                      DET.SUCURSAL,
                      DET.CMPTE_AFECTADO AS FACTURA,
                      DET.TIPO_CPTE_AFECT AS TIPO_FACTURA,
                      DET.CUENTA,
                      SUM((NVL(DET.VALOR_CREDITO,0)-NVL(DET.VALOR_DEBITO,0))) VALOR_AFECTACION,
                      SUM((NVL(DET.VALOR_DEBITO,0))) DEBITO_AFECTADO,
                      SUM((NVL(DET.VALOR_CREDITO,0))) CREDITO_AFECTADO
               FROM  TIPO_COMPROBANTE TC INNER JOIN COMPROBANTE_CNT CN
                  ON CN.COMPANIA = TC.COMPANIA
                 AND CN.TIPO     = TC.CODIGO
               INNER JOIN  DETALLE_COMPROBANTE_CNT DET
                  ON CN.NUMERO = DET.COMPROBANTE
                 AND CN.TIPO = DET.TIPO_CPTE
                 AND CN.ANO = DET.ANO
                 AND CN.COMPANIA = DET.COMPANIA
              INNER JOIN PLAN_CONTABLE PLAN
                ON PLAN.COMPANIA = DET.COMPANIA
                AND PLAN.ANO      = DET.ANO
                AND PLAN.CODIGO  = DET.CUENTA               
              WHERE DET.COMPANIA = 's$compania$s'
                 AND DET.ANO <= s$anio$s
                 --PILAS CON FECHA
                 AND DET.FECHA <= TO_DATE('s$fecha$s','DD/MM/YYYY')
                 AND TC.CLASE_CONTABLE In ('I','B','N','C')
                 AND DET.CMPTE_AFECTADO<>0
                 AND PLAN.CLASECUENTA In ('A','C')
             GROUP BY DET.COMPANIA,
                      DET.TERCERO,
                      DET.SUCURSAL,
                      DET.CMPTE_AFECTADO,
                      DET.TIPO_CPTE_AFECT,
                      DET.CUENTA   
        ) AFEC
        ON DETALLE_COMPROBANTE_CNT.CUENTA      = AFEC.CUENTA
       AND DETALLE_COMPROBANTE_CNT.COMPROBANTE = AFEC.FACTURA
       AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE   = AFEC.TIPO_FACTURA
       AND DETALLE_COMPROBANTE_CNT.COMPANIA    = AFEC.COMPANIA
       AND DETALLE_COMPROBANTE_CNT.TERCERO     = AFEC.TERCERO
       AND DETALLE_COMPROBANTE_CNT.SUCURSAL    = AFEC.SUCURSAL    
            WHERE COMPROBANTE_CNT.COMPANIA = 's$compania$s'
                  AND TIPO_COMPROBANTE.CLASE_CONTABLE IN('V')
                  AND PLAN_CONTABLE.CLASECUENTA IN ('C')
                  GROUP BY  
                   CASE WHEN DEUDORES.DEUDORES >0 THEN '2' ELSE '1' END ,
                    CASE WHEN  TERCERO.NATURALEZA = 'J' THEN '2' ELSE '1' END,
                   DETALLE_COMPROBANTE_CNT.TIPO_CPTE, DETALLE_COMPROBANTE_CNT.COMPROBANTE ,
                   DETALLE_COMPROBANTE_CNT.TERCERO,                
                   DETALLE_COMPROBANTE_CNT.SUCURSAL,  
                   COMPROBANTE_CNT.FECHA_VCN_DOC,
                   ANO.SALARIOMINIMO,
                   CASE WHEN  TERCERO.TIPOID = 'C' THEN 1    
                       WHEN  TERCERO.TIPOID = 'N' THEN 2 
                       WHEN  TE]') || TO_CLOB(q'[RCERO.TIPOID = 'T' THEN 3  
                       WHEN  TERCERO.TIPOID = 'E' THEN 4 END,
                   TERCERO.NOMBRE,
                   'N/A',
                    TERCERO.NATURALEZA,
                    '',
                    CASE WHEN  TERCERO.NATURALEZA = 'J' THEN 'Juridica' ELSE 'Natural' END,
                    CASE WHEN DETALLE_COMPROBANTE_CNT.FECHA_ABONOINICIAL<= TO_DATE('s$fecha$s') THEN DETALLE_COMPROBANTE_CNT.ABONOINICIAL ELSE 0 END,
                      NVL(AFEC.VALOR_AFECTACION,0) 
                   HAVING SUM((DETALLE_COMPROBANTE_CNT.VALOR_DEBITO-DETALLE_COMPROBANTE_CNT.VALOR_CREDITO)
                -CASE WHEN DETALLE_COMPROBANTE_CNT.FECHA_ABONOINICIAL<= TO_DATE('s$fecha$s') THEN DETALLE_COMPROBANTE_CNT.ABONOINICIAL ELSE 0 END)
              -NVL(AFEC.VALOR_AFECTACION,0) > 0
              AND MONTHS_BETWEEN( TO_DATE('s$fecha$s'),COMPROBANTE_CNT.FECHA_VCN_DOC) > 6
                   ORDER BY DETALLE_COMPROBANTE_CNT.TERCERO,  DETALLE_COMPROBANTE_CNT.COMPROBANTE DESC)
				    SELECT CONSULTA.CONCEPTO,
                    CONSULTA.TIPODEUDOR,
                    CONSULTA.NUMERO ,
                    CONSULTA.NIT,       
                   CONSULTA.TIPOID  ,
                  CONSULTA.NOMBRE  ,                   
                    CONSULTA.VALOR,
                   CONSULTA.ESTADO    FROM CONSULTA
                 INNER JOIN (SELECT SUM(VALOR), CONCEPTO,
                    TIPODEUDOR,                    
                    NIT,       
                   TIPOID  ,
                  NOMBRE  ,                                       
                   ESTADO   FROM CONSULTA
                   GROUP BY CONCEPTO,
                    TIPODEUDOR,                    
                    NIT,       
                   TIPOID  ,
                  NOMBRE  ,                                       
                   ESTADO ,
                   SALARIOMINIMO
                   HAVING SUM(VALOR)> SALARIOMINIMO* 5  )SC ON  CONSULTA.CONCEPTO = SC.CONCEPTO
                   AND CONSULTA.TIPODEUDOR = SC.TIPODEUDOR
                   AND CONSULTA.NIT = SC.NIT
                   AND CONSULTA.TIPOID = SC.TIPOID
                   AND CONSULTA.NOMBRE = SC.NOMBRE
                   AND CONSULTA.ESTADO = SC.ESTADO]') CONSULTA, 99 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);

commit;