WITH CUENTAMEDIDOR AS
  (SELECT SP_MEDIDOR.COMPANIA,
    SP_MEDIDOR.CODIGO,
    COUNT(SP_MEDIDOR.CODIGO) AS REPETIDOS
  FROM SP_MEDIDOR
  WHERE SP_MEDIDOR.Compania = 's$compania$s'
  GROUP BY SP_MEDIDOR.COMPANIA,
    SP_MEDIDOR.CODIGO
  HAVING COUNT(SP_MEDIDOR.CODIGO)>1
  ORDER BY SP_MEDIDOR.CODIGO
  )
SELECT SP_MEDIDOR.COMPANIA,
  cuentamedidor.CODIGO,
  SP_USUARIO.CODIGOINTERNO,
  SP_MEDIDOR.CODIGORUTA,
  SP_USUARIO.PRIMERAPELLIDO
  || ' '
  || SP_USUARIO.SEGUNDOAPELLIDO
  || ' '
  ||SP_USUARIO.NOMBRES AS NOMBRE,
  SP_USUARIO.DirTecnica,
  cuentamedidor.REPETIDOS,
  CASE
    WHEN NVL(SP_USUARIO.PRIMERAPELLIDO
      || ' '
      || SP_USUARIO.SEGUNDOAPELLIDO
      || ' '
      ||SP_USUARIO.NOMBRES,'')=''
    THEN 'Sin Asignar'
    ELSE SP_USUARIO.PRIMERAPELLIDO
      || ' '
      || SP_USUARIO.SEGUNDOAPELLIDO
      || ' '
      ||SP_USUARIO.NOMBRES
  END AS NOMBRES
FROM cuentamedidor
INNER JOIN SP_MEDIDOR
ON cuentamedidor.CODIGO    = SP_MEDIDOR.CODIGO
AND cuentamedidor.COMPANIA = SP_MEDIDOR.COMPANIA
LEFT JOIN SP_USUARIO
ON SP_MEDIDOR.COMPANIA    = SP_USUARIO.COMPANIA
AND SP_MEDIDOR.CICLO      = SP_USUARIO.CICLO
AND SP_MEDIDOR.CODIGORUTA = SP_USUARIO.CODIGORUTA
