SELECT TO_CHAR(SS.FECHASOLICITUD,'DD/MM/YYYY') FECHASOLICITUD, 
 	SS.NUMERO, 
 	SS.NOMBRE, 
 	SS.DIRTECNICA, 
 	SS.DIRGUIA, 
   	SS.USUARIO, 
   	NVL(SUM(SF.VALOR), 0) AS SUMADEVALOR,
    NVL(SUM(SF.INICIAL), 0) AS SUMADEINICIAL,
    MIN(SF.CUOTAS)  KEEP (DENSE_RANK FIRST ORDER BY ROWNUM) AS PRIMERODECUOTAS,
    SS.NIT, 
    (CASE WHEN SS.ACTIVADO IN (0)
        THEN ' '
      ELSE 'X'
    END) ACTIVADO
FROM SP_SOLICITUDSERVICIO SS 
LEFT JOIN SP_SOLICITUDFINANCIABLES SF
	ON SS.NUMERO 		  = SF.SOLICITUD
	AND SS.CLASESOLICITUD = SF.CLASESOLICITUD 
	AND SS.COMPANIA 	  = SF.COMPANIA
WHERE SS.COMPANIA =s$compania$s 
	AND FECHASOLICITUD BETWEEN s$fechaInicial$s AND s$fechaFinal$s
GROUP BY SS.FECHASOLICITUD, 
 	SS.NUMERO, 
 	SS.NOMBRE, 
 	SS.DIRGUIA,
   	SS.DIRTECNICA, 
   	SS.NIT, 
    SF.CUOTAS,
   	SS.USUARIO,
    SS.ACTIVADO 
ORDER BY SS.FECHASOLICITUD, 
	SS.NUMERO
