SELECT 1 TIPO,
  SP_RECAUDOS.COMPANIA,
  TO_CHAR(SP_RECAUDOS.FECHA,'DD/MM/YYYY') FECHA,
  SP_RECAUDOS.BANCO,
  SP_RECAUDOS.NUMEROPAQUETE,
  '0' CODIGORUTA,
  SP_RECAUDOS.VALORREGISTRADO-(SUM(SP_D_RECAUDO.VALORDEUDA+SP_D_RECAUDO.VALORPAGOPERIODO+SP_D_RECAUDO.VALORFINACT+SP_D_RECAUDO.VALORFINANT+SP_D_RECAUDO.VALORABONOACT+SP_D_RECAUDO.VALORABONOANT-SP_D_RECAUDO.CREDITOABONADO)) AS DIFERENCIA,
  'Hay diferencia entre el recaudo y el detalle' DESCRIPCION,
  SP_BANCOS.NOMBRE
FROM SP_RECAUDOS
INNER JOIN SP_D_RECAUDO
ON SP_RECAUDOS.COMPANIA       = SP_D_RECAUDO.COMPANIA
AND SP_RECAUDOS.FECHA         = SP_D_RECAUDO.FECHA
AND SP_RECAUDOS.BANCO         = SP_D_RECAUDO.BANCO
AND SP_RECAUDOS.NUMEROPAQUETE = SP_D_RECAUDO.NUMEROPAQUETE
LEFT JOIN SP_BANCOS
ON SP_RECAUDOS.COMPANIA       = SP_BANCOS.COMPANIA
AND SP_RECAUDOS.BANCO         = SP_BANCOS.CODIGO
WHERE SP_RECAUDOS.COMPANIA     = s$compania$s
AND SP_RECAUDOS.FECHA BETWEEN s$fechaInicial$s AND s$fechaFinal$s
AND SP_D_RECAUDO.CONCEPTO <> 17
GROUP BY SP_RECAUDOS.COMPANIA,
  SP_RECAUDOS.FECHA,
  SP_RECAUDOS.BANCO,
  SP_RECAUDOS.NUMEROPAQUETE,
  SP_RECAUDOS.VALORREGISTRADO,
  SP_BANCOS.NOMBRE
HAVING SP_RECAUDOS.VALORREGISTRADO-(SUM(SP_D_RECAUDO.VALORDEUDA+SP_D_RECAUDO.VALORPAGOPERIODO+SP_D_RECAUDO.VALORFINACT+SP_D_RECAUDO.VALORFINANT+SP_D_RECAUDO.VALORABONOACT+SP_D_RECAUDO.VALORABONOANT-SP_D_RECAUDO.CREDITOABONADO))<>0 

UNION ALL
SELECT 2 TIPO,
SP_RECAUDOS.COMPANIA,
  TO_CHAR(SP_RECAUDOS.FECHA,'DD/MM/YYYY') FECHA,
  SP_RECAUDOS.BANCO,
  SP_RECAUDOS.NUMEROPAQUETE,
  '0' CODIGORUTA,
  SP_RECAUDOS.VALORREGISTRADO AS DIFERENCIA,
  'Hay un recaudo sin detalle' DESCRIPCION,
  SP_BANCOS.NOMBRE
FROM SP_RECAUDOS
LEFT JOIN SP_D_RECAUDO
ON SP_RECAUDOS.COMPANIA       = SP_D_RECAUDO.COMPANIA
AND SP_RECAUDOS.FECHA         = SP_D_RECAUDO.FECHA
AND SP_RECAUDOS.BANCO         = SP_D_RECAUDO.BANCO
AND SP_RECAUDOS.NUMEROPAQUETE = SP_D_RECAUDO.NUMEROPAQUETE
LEFT JOIN SP_BANCOS
ON SP_RECAUDOS.COMPANIA       = SP_BANCOS.COMPANIA
AND SP_RECAUDOS.BANCO         = SP_BANCOS.CODIGO
WHERE SP_RECAUDOS.COMPANIA     = s$compania$s
AND SP_RECAUDOS.FECHA BETWEEN s$fechaInicial$s AND s$fechaFinal$s
AND SP_RECAUDOS.VALORREGISTRADO <> 0
AND (SP_D_RECAUDO.COMPANIA)     IS NULL
GROUP BY SP_RECAUDOS.COMPANIA,
  SP_RECAUDOS.FECHA,
  SP_RECAUDOS.BANCO,
  SP_RECAUDOS.NUMEROPAQUETE,
  SP_RECAUDOS.VALORREGISTRADO,
  SP_BANCOS.NOMBRE

UNION ALL
SELECT 3 TIPO,
SP_D_RECAUDO.COMPANIA,
  TO_CHAR(SP_D_RECAUDO.FECHA,'DD/MM/YYYY') FECHA,
  SP_D_RECAUDO.BANCO,
  SP_D_RECAUDO.NUMEROPAQUETE,
   '0' CODIGORUTA,
  SUM(SP_D_RECAUDO.VALORDEUDA+SP_D_RECAUDO.VALORPAGOPERIODO+SP_D_RECAUDO.VALORFINACT+SP_D_RECAUDO.VALORFINANT+SP_D_RECAUDO.VALORABONOACT+SP_D_RECAUDO.VALORABONOANT-SP_D_RECAUDO.CREDITOABONADO) AS DIFERENCIA,
  'Hay detalle de recaudo sin recaudos' DESCRIPCION,
  SP_BANCOS.NOMBRE
FROM SP_D_RECAUDO
LEFT JOIN SP_RECAUDOS
ON SP_D_RECAUDO.COMPANIA       = SP_RECAUDOS.COMPANIA
AND SP_D_RECAUDO.FECHA         = SP_RECAUDOS.FECHA
AND SP_D_RECAUDO.BANCO         = SP_RECAUDOS.BANCO
AND SP_D_RECAUDO.NUMEROPAQUETE = SP_RECAUDOS.NUMEROPAQUETE
LEFT JOIN SP_BANCOS
ON SP_D_RECAUDO.COMPANIA       = SP_BANCOS.COMPANIA
AND SP_D_RECAUDO.BANCO         = SP_BANCOS.CODIGO
WHERE SP_D_RECAUDO.COMPANIA     = s$compania$s
AND SP_D_RECAUDO.FECHA BETWEEN s$fechaInicial$s AND s$fechaFinal$s
AND SP_RECAUDOS.COMPANIA IS NULL
GROUP BY SP_D_RECAUDO.COMPANIA,
  SP_D_RECAUDO.FECHA,
  SP_D_RECAUDO.BANCO,
  SP_D_RECAUDO.NUMEROPAQUETE,
  SP_BANCOS.NOMBRE
HAVING SUM(SP_D_RECAUDO.VALORDEUDA+SP_D_RECAUDO.VALORPAGOPERIODO+SP_D_RECAUDO.VALORFINACT+SP_D_RECAUDO.VALORFINANT+SP_D_RECAUDO.VALORABONOACT+SP_D_RECAUDO.VALORABONOANT-SP_D_RECAUDO.CREDITOABONADO)<>0
