WITH CUENTACATASTRO AS(
SELECT COMPANIA,
  CICLO,
  CODIGOCATASTRAL,
  COUNT(CODIGOCATASTRAL) AS REPETIDOS
FROM SP_USUARIO
WHERE COMPANIA = s$compania$s
AND CICLO      = s$ciclo$s
GROUP BY COMPANIA,
  CICLO,
  CODIGOCATASTRAL
HAVING COUNT(CODIGOCATASTRAL) > 1
ORDER BY COUNT(CODIGOCATASTRAL)
)

SELECT CUENTACATASTRO.COMPANIA,
  CUENTACATASTRO.CICLO,
  SP_USUARIO.CODIGORUTA,
  TRIM(SP_USUARIO.PRIMERAPELLIDO
  || ' '
  || SP_USUARIO.SEGUNDOAPELLIDO
  || ' '
  || SP_USUARIO.NOMBRES) AS NOMBRES,
  SP_USUARIO.CODIGOINTERNO,
  SP_USUARIO.DIRTECNICA,
  SP_USUARIO.CODIGOCATASTRAL
FROM CUENTACATASTRO
LEFT JOIN SP_USUARIO
ON CUENTACATASTRO.COMPANIA       		= SP_USUARIO.COMPANIA
AND CUENTACATASTRO.CICLO          		= SP_USUARIO.CICLO
AND  CUENTACATASTRO.CODIGOCATASTRAL 	= SP_USUARIO.CODIGOCATASTRAL
ORDER BY SP_USUARIO.DIRTECNICA,
  SP_USUARIO.CODIGOCATASTRAL
