SELECT COMPANIA,
  CICLO, 
  CODIGOINTERNO,
  CODIGORUTA, 
  TRIM(PRIMERAPELLIDO || ' ' || SEGUNDOAPELLIDO || ' ' || NOMBRES) NOMBRES,
  CODIGOCATASTRAL 
FROM SP_USUARIO
WHERE COMPANIA= s$compania$s
AND CICLO = s$ciclo$s 
AND CODIGOCATASTRAL IS NULL
 ORDER BY CODIGORUTA,
  TRIM(PRIMERAPELLIDO || ' ' || SEGUNDOAPELLIDO || ' ' || NOMBRES)
