SELECT SP_USUARIO.COMPANIA, 
  SP_USUARIO.CICLO, 
  SP_USUARIO.CODIGORUTA, 
  SP_USUARIO.CODIGOINTERNO, 
  SP_USUARIO.ANO, 
  SP_USUARIO.PERIODO, 
  SP_ESTADOSCOBRO.DESCRIPCION AS TIPOCOBRO, 
  TRIM(SP_USUARIO.PRIMERAPELLIDO 
  || ' ' 
  || SP_USUARIO.SEGUNDOAPELLIDO 
  || ' ' 
  || SP_USUARIO.NOMBRES) AS NOMBRES, 
  SP_USUARIO.PERIODOSATRASO, 
  SP_USUARIO.MEDIDOR, 
  SP_USUARIO.ESTADO, 
  SP_USUARIO.CHAPETAS, 
  SP_USUARIO.LECTURA1, 
  SP_USUARIO.TOTALDEUDA 
FROM SP_USUARIO INNER JOIN SP_ESTADOSCOBRO 
       ON SP_USUARIO.COMPANIA  = SP_ESTADOSCOBRO.COMPANIA 
      AND SP_USUARIO.TIPOCOBRO = SP_ESTADOSCOBRO.CODIGO 
WHERE SP_USUARIO.COMPANIA            = s$compania$s 
AND SP_USUARIO.CICLO                 = 's$ciclo$s' 
AND NVL(SP_USUARIO.TIPOCOBRO,'NNN') IN (s$estados$s)
