SELECT SP_USUARIO.CICLO,
  SP_USUARIO.CODIGORUTA,
  TRIM(SP_USUARIO.PRIMERAPELLIDO
  ||' '
  ||SP_USUARIO.SEGUNDOAPELLIDO
  ||' '
  ||SP_USUARIO.NOMBRES) NOMBRES,
  SP_MEDIDOR.CODIGO MEDIDOR,
  SP_USUARIO.DIRTECNICA,
  SP_USUARIO.CODIGOINTERNO
FROM SP_USUARIO
INNER JOIN SP_MEDIDOR
ON SP_USUARIO.COMPANIA                         = SP_MEDIDOR.COMPANIA
AND SP_USUARIO.MEDIDOR                         = SP_MEDIDOR.CONSECUTIVO
WHERE SP_USUARIO.COMPANIA                      = 's$compania$s'
AND SP_USUARIO.CICLO                           = 's$ciclo$s'
AND (REGEXP_COUNT(SP_MEDIDOR.CODIGO,'([0-9])') < 2
OR REGEXP_COUNT(SP_MEDIDOR.CODIGO,'([^0-9])')  > 4)
