SELECT SP_USUARIO.CICLO,
	   SP_USUARIO.CODIGORUTA,
	   SP_USUARIO.PRIMERAPELLIDO, 
	   SP_USUARIO.SEGUNDOAPELLIDO, 
	   SP_USUARIO.FECHARENTRADANUEVOUSUARIO, 
	   SP_USUARIO.LECTURA1, 
	   SP_USUARIO.LECTURA, 
	   SP_USUARIO.CONSUMO, 
	   SP_USUARIO.LECTURA2, 
	   SP_USUARIO.NOMBRES, 
	   SP_USUARIO.DIRTECNICA, 
	   SP_USUARIO.INDDESHABITADO, 
	   CASE WHEN SP_USUARIO.LECTURA - SP_USUARIO.LECTURA1 <> 0 THEN 'Debe Revisar' ELSE '' END AS OBSERVACIONES
FROM SP_USUARIO
WHERE SP_USUARIO.COMPANIA=s$compania$s
	AND SP_USUARIO.INDDESHABITADO NOT IN 0
	AND SP_USUARIO.CICLO=s$ciclo$s
ORDER BY SP_USUARIO.COMPANIA, SP_USUARIO.CICLO, SP_USUARIO.CODIGORUTA
