SELECT SS.NUMERO, 
	SS.NOMBRE,
 	SS.DIRTECNICA,
  	SS.TELEFONO, 
  	TO_CHAR(FECHASOLICITUD, 'DD/MM/YYYY') FECHASOLICITUD, 
  	SPS.NOMBRE AS TIPODEMATRICULA, 
  	NVL(PRIMERAPELLIDO,' ')||' '|| NVL(SEGUNDOAPELLIDO,' ') ||' '||NVL(NOMBRES,' ') AS NOMBRECOMPLETO
FROM SP_SOLICITUDPORSERVICIO SPS
	INNER JOIN SP_SOLICITUDSERVICIO SS
		ON SPS.COMPANIA = SS.COMPANIA
		AND SPS.CODIGO = SS.CLASESOLICITUD
WHERE SS.COMPANIA =s$compania$s
	AND SS.FECHASOLICITUD BETWEEN s$fechaInicial$s AND s$fechaFinal$s
ORDER BY SS.CLASESOLICITUD,
 	SS.NUMERO
