SELECT SP_USUARIO.COMPANIA,
       SP_USUARIO.CICLO,
       SP_USUARIO.CODIGORUTA,
       SP_USUARIO.CODIGOINTERNO,
       (SP_USUARIO.NOMBRES ||' '||SP_USUARIO.PRIMERAPELLIDO||' '||SP_USUARIO.SEGUNDOAPELLIDO) NOMBRECOMPLETO,
       SP_USUARIO.DIRTECNICA,
       SP_USUARIO.NIT,
       SP_USUARIO.ANO,
       SP_USUARIO.PERIODO,
       SP_USUARIO.USO,
       SP_USUARIO.ESTRATO,
       SP_USUARIO.ESTRATOASEO,
       VASEOUNICO,
       VASEODOMICILIARIO,
       VASEOBARRIDO,
       VASEOCONSUMO,
       SUBASEO,
       SOBREASEO,
       PESOASEO,
       INDDESHABITADO,
       SP_USUARIO.VASEOUNICO+SP_USUARIO.VASEODOMICILIARIO+SP_USUARIO.VASEOBARRIDO+SP_USUARIO.VASEOCONSUMO+NVL(AUXEXCEDENTE.VALOR_FACTURADO,0)+NVL(AUXDESHABITADO.VALOR_FACTURADO,0) TOTAL, 
       NVL(AUXEXCEDENTE.VALOR_FACTURADO,0) TRAMOEXCEDENTE, 
       NVL(AUXDESHABITADO.VALOR_FACTURADO,0) VALDESHABITADO,
       (SP_USUARIO.VASEOUNICO+SP_USUARIO.VASEODOMICILIARIO+SP_USUARIO.VASEOBARRIDO+SP_USUARIO.VASEOCONSUMO)+SUBASEO-SOBREASEO+NVL(AUXEXCEDENTE.VALOR_FACTURADO,0)+NVL(AUXDESHABITADO.VALOR_FACTURADO,0) PLENA 
  FROM SP_USUARIO
    LEFT JOIN ( SELECT
                  SP_FACTURADO.COMPANIA,
                  SP_FACTURADO.CICLO,
                  SP_FACTURADO.CODIGORUTA,
                  SP_FACTURADO.ANO,
                  SP_FACTURADO.PERIODO,
                  SP_FACTURADO.VALOR_FACTURADO,
                  SP_CONCEPTOS.CODIGO
                FROM SP_FACTURADO 
                  INNER JOIN SP_CONCEPTOS
                     ON SP_FACTURADO.COMPANIA = SP_CONCEPTOS.COMPANIA
                    AND SP_FACTURADO.CONCEPTO = SP_CONCEPTOS.CODIGO
                WHERE SP_CONCEPTOS.CODIGO=48
                  AND SP_CONCEPTOS.NOMBRE LIKE '*DESHABITADO*'
                  AND SP_FACTURADO.VALOR_FACTURADO<>0
                  ) AUXDESHABITADO
       ON SP_USUARIO.COMPANIA = AUXDESHABITADO.COMPANIA
      AND SP_USUARIO.CICLO = AUXDESHABITADO.CICLO
      AND SP_USUARIO.CODIGORUTA = AUXDESHABITADO.CODIGORUTA
      AND SP_USUARIO.ANO = AUXDESHABITADO.ANO
      AND SP_USUARIO.PERIODO = AUXDESHABITADO.PERIODO
    LEFT JOIN ( SELECT
                  SP_FACTURADO.COMPANIA,
                  SP_FACTURADO.CICLO,
                  SP_FACTURADO.CODIGORUTA,
                  SP_FACTURADO.ANO,
                  SP_FACTURADO.PERIODO,
                  SP_FACTURADO.VALOR_FACTURADO,
                  SP_CONCEPTOS.CODIGO
                FROM SP_FACTURADO 
                  INNER JOIN SP_CONCEPTOS
                     ON SP_FACTURADO.COMPANIA = SP_CONCEPTOS.COMPANIA
                    AND SP_FACTURADO.CONCEPTO = SP_CONCEPTOS.CODIGO
                WHERE SP_CONCEPTOS.NOMBRE LIKE '*EXCEDENTE*'
                  AND SP_FACTURADO.VALOR_FACTURADO<>0
                  ) AUXEXCEDENTE
       ON SP_USUARIO.COMPANIA = AUXEXCEDENTE.COMPANIA
      AND SP_USUARIO.CICLO = AUXEXCEDENTE.CICLO
      AND SP_USUARIO.CODIGORUTA = AUXEXCEDENTE.CODIGORUTA
      AND SP_USUARIO.ANO = AUXEXCEDENTE.ANO
      AND SP_USUARIO.PERIODO = AUXEXCEDENTE.PERIODO
  WHERE SP_USUARIO.COMPANIA = s$compania$s
   AND SP_USUARIO.CODIGORUTA BETWEEN 's$codigoInicial$s' AND 's$codigoFinal$s'
   AND SP_USUARIO.CICLO BETWEEN s$cicloInicial$s AND s$cicloFinal$s
   AND SP_USUARIO.ESTADO <> 'R' 
   AND SP_USUARIO.ASEO NOT IN (0)
