SELECT AUDMODIFSINSOPORTE.CICLO, 
       AUDMODIFSINSOPORTE.CODIGORUTA,
       AUDMODIFSINSOPORTE.CUENTA,
       '' NOMBRELARGO,
       AUDMODIFSINSOPORTE.CAMPO,
       AUDMODIFSINSOPORTE.VALORINICIAL,
       AUDMODIFSINSOPORTE.VALORFINAL, 
       AUDMODIFSINSOPORTE.CODIGO,
       (PRIMERAPELLIDO||' '||SEGUNDOAPELLIDO||' '||NOMBRES) NOMBREUSUARIO
  FROM (SELECT AUDMODIFICADOS.COMPANIA,
               AUDMODIFICADOS.CICLO,
               AUDMODIFICADOS.CODIGORUTA,
               AUDMODIFICADOS.CUENTA,
               AUDMODIFICADOS.HORA,
               AUDMODIFICADOS.FORMULARIO,
               AUDMODIFICADOS.CAMPO,
               AUDMODIFICADOS.VALORINICIAL,
               AUDMODIFICADOS.VALORFINAL,
               AUDMODIFICADOS.CODIGO, 
               AUDMODIFICADOS.ANO,
               AUDMODIFICADOS.PERIODO
          FROM SP_AUDITORIAMNUMOD AUDMODIFICADOS
            LEFT JOIN SP_ORDENTRABAJO 
                ON AUDMODIFICADOS.COMPANIA = SP_ORDENTRABAJO.COMPANIA
               AND AUDMODIFICADOS.CODIGORUTA = SP_ORDENTRABAJO.CODIGORUTA 
               AND AUDMODIFICADOS.CICLO = SP_ORDENTRABAJO.CICLO 
               AND AUDMODIFICADOS.HORA = SP_ORDENTRABAJO.FECHASOLICITUD
        WHERE SP_ORDENTRABAJO.COMPANIA IS NULL
          AND UPPER(AUDMODIFICADOS.FORMULARIO) IN ('FACTURA','USUARIOS')) AUDMODIFSINSOPORTE 
    LEFT JOIN SP_USUARIO
       ON AUDMODIFSINSOPORTE.COMPANIA = SP_USUARIO.COMPANIA 
      AND AUDMODIFSINSOPORTE.CICLO = SP_USUARIO.CICLO
      AND AUDMODIFSINSOPORTE.CODIGORUTA = SP_USUARIO.CODIGORUTA
WHERE AUDMODIFSINSOPORTE.COMPANIA = s$compania$s
  AND HORA BETWEEN TO_DATE('s$fechaInicial$s','DD/MM/YYYY') AND TO_DATE('s$fechaFinal$s','DD/MM/YYYY')
