SELECT F.COMPANIA,
 	F.CICLO,
  	F.CODIGORUTA, 
  	F.ANO, 
  	F.PERIODO, 
  	F.CONCEPTO, 
  	F.MONTOFINANCIAR, 
  	F.NUMEROCUOTAS, 
  	F.SALDOFINANCIABLE, 
  	F.VALORCUOTA, 
  	F.INTERES, 
  	F.NROCUOTA, 
  	CO.NOMBRE, 
  	TO_CHAR(F.ANO,'0000') || TO_CHAR(F.PERIODO,'00') AS PERANO,
  	NVL(U.PRIMERAPELLIDO,' ')||' '||NVL(U.SEGUNDOAPELLIDO,' ')||' '||NVL(U.NOMBRES,' ') NOMBRECOMPLETO,  
  	C.NOMBRE AS NOMBRECONCEPTO, 
  	NVL(F.USUARIO,' ') USUARIO, 
  	TO_CHAR(F.FECHABLOQUEADO,'DD/MM/YYYY')  FECHACREACION,
    NVL(TO_CHAR(F.HORA,'HH:MI'),' ') HORA,
    NVL(F.USUARIOBLOQUEO, ' ') NOMBRELARGO
FROM COMPANIA CO
	INNER JOIN SP_FINANCIABLES F
		ON CO.CODIGO = F.COMPANIA
	LEFT JOIN SP_USUARIO U
		ON F.COMPANIA 	 = U.COMPANIA
		AND F.CICLO 	 = U.CICLO
		AND F.CODIGORUTA = U.CODIGORUTA
	INNER JOIN SP_CONCEPTOS C
		ON F.COMPANIA  = C.COMPANIA
		AND F.CONCEPTO = C.CODIGO
WHERE F.COMPANIA=s$compania$s
	AND F.CICLO 	 		  BETWEEN s$cicloInicial$s 	AND s$cicloFinal$s
	AND F.CODIGORUTA 		  BETWEEN 's$codigoInicial$s' 	AND 's$codigoFinal$s'
	AND F.CONCEPTO 	 		  BETWEEN s$conceptoInicial$s 	AND s$conceptoFinal$s
	AND F.ANO*100 + F.PERIODO BETWEEN s$fechaInicial$s 	AND s$fechaFinal$s
