SELECT  SP_USUARIO.PERIODOSATRASO, 
        COUNT(SP_USUARIO.PERIODOSATRASO) AS TOT 
FROM SP_USUARIO 
WHERE SP_USUARIO.COMPANIA = s$compania$s
  AND SP_USUARIO.CICLO = s$ciclo$s
  s$cond$s
GROUP BY SP_USUARIO.PERIODOSATRASO
ORDER BY SP_USUARIO.PERIODOSATRASO
