SELECT COMPANIA,
       CICLO,
       CODIGORUTA,
       CODIGOINTERNO,
       (NOMBRES ||' '||PRIMERAPELLIDO||' '||SEGUNDOAPELLIDO) NOMBRECOMPLETO,
       DIRTECNICA,
       NIT,
       ANO,
       PERIODO,
       USO,
       ESTRATO,
       ESTRATOASEO, 
       CARGOFIJO FIJO,
       SUBFIJO SUBSIDIOFIJO,
       SOBREFIJO SOBFIJO,
       (CARGOFIJO+SUBFIJO-SOBREFIJO) SUBTOTALFIJO, 
       VALORBASICO BASICO,
       VALORCOMPLEMENTARIO COMPLEMENTARIO,
       VALORSUNTUARIO SUNTUARIO,
       VALORBASICO+VALORCOMPLEMENTARIO+VALORSUNTUARIO TOTCONSUMO,
       SUBCONSUMOAC SUBCONSUMO,
       SOBRECONSUMOAC SOBRECONSUMO
  FROM SP_USUARIO 
 WHERE SP_USUARIO.COMPANIA = s$compania$s
   AND SP_USUARIO.CODIGORUTA BETWEEN 's$codigoInicial$s' AND 's$codigoFinal$s'
   AND SP_USUARIO.CICLO BETWEEN s$cicloInicial$s AND s$cicloFinal$s
   AND SP_USUARIO.ESTADO <> 'R' 
   AND SP_USUARIO.ACUEDUCTO NOT IN (0)
