SELECT QRY_COBERTURAMICRO.COMPANIA,
  QRY_COBERTURAMICRO.ANO,
  QRY_COBERTURAMICRO.PERIODO,
  QRY_COBERTURAMICRO.CODIGORUTA,
  QRY_COBERTURAMICRO.CODIGOINTERNO,
  SP_USOS.NOMBRE                                                AS USO,
  SP_ESTRATOS.NOMBRE                                            AS ESTRATO,
  CASE WHEN ACTIVOS =1 THEN 'SI' ELSE CASE WHEN ACTIVOS=0 THEN 'NO' ELSE 'VARIOS' END END    AS ACTIVO,
  CASE WHEN CONMEDIDOR=1 THEN 'SI' ELSE CASE WHEN CONMEDIDOR=0 THEN 'NO' ELSE 'VARIOS' END END AS CONMEDIDOR,
  CASE WHEN SINMEDIDOR=1 THEN 'SI' ELSE CASE WHEN SINMEDIDOR=0 THEN 'NO' ELSE 'VARIOS' END END AS SINMEDIDOR
FROM ((s$subConsulta$s)QRY_COBERTURAMICRO
INNER JOIN SP_ESTRATOS
ON (QRY_COBERTURAMICRO.ESTRATO   = SP_ESTRATOS.CODIGO)
AND (QRY_COBERTURAMICRO.USO      = SP_ESTRATOS.USO)
AND (QRY_COBERTURAMICRO.COMPANIA = SP_ESTRATOS.COMPANIA))
INNER JOIN SP_USOS
ON (QRY_COBERTURAMICRO.USO       = SP_USOS.CODIGO)
AND (QRY_COBERTURAMICRO.COMPANIA = SP_USOS.COMPANIA)
ORDER BY   QRY_COBERTURAMICRO.PERIODO
