SELECT SP_USUARIO.ANO,
       SP_USUARIO.PERIODO,
       SP_USUARIO.CODIGORUTA,
       SP_USUARIO.CODIGOINTERNO,
       SP_USUARIO.SUBASEO,
       SP_USUARIO.SUBACUEDUCTO,
       SP_USUARIO.SUBALCANTARILLADO,
       SP_USUARIO.SOBREASEO,
       SP_USUARIO.SOBREACUEDUCTO,
       SP_USUARIO.SOBREALCANTARILLADO,
       SP_USUARIO.CODIGODANE,
       SP_USUARIO.ESTRATOASEO,
       SP_USUARIO.CICLO,
       SP_USUARIO.USO,
       SP_USUARIO.ESTRATO,
       (PRIMERAPELLIDO||' '||SEGUNDOAPELLIDO||' '||NOMBRES) NOMBREUSUARIO,
       SP_USOS.NOMBRE NOMBREUSO,
       SP_ESTRATOS.NOMBRE NOMBREESTRATO
  FROM SP_USUARIO 
    LEFT JOIN SP_ESTRATOS 
       ON SP_USUARIO.COMPANIA = SP_ESTRATOS.COMPANIA
      AND SP_USUARIO.ESTRATO = SP_ESTRATOS.CODIGO
      AND SP_USUARIO.USO = SP_ESTRATOS.USO 
    LEFT JOIN SP_USOS 
       ON SP_ESTRATOS.COMPANIA = SP_USOS.COMPANIA
      AND SP_ESTRATOS.USO = SP_USOS.CODIGO 
 WHERE SP_USUARIO.COMPANIA = s$compania$s
   AND SP_USUARIO.CICLO BETWEEN s$cicloInicial$s AND s$cicloFinal$s
   AND SP_USUARIO.CODIGORUTA BETWEEN 's$codigoInicial$s' AND 's$codigoFinal$s'
   AND SP_USUARIO.ESTADO<>'R'
   AND (SP_USUARIO.SUBACUEDUCTO<>0 OR SP_USUARIO.SUBALCANTARILLADO<>0 OR SP_USUARIO.SOBREASEO<>0 OR SP_USUARIO.SOBREACUEDUCTO<>0 OR SP_USUARIO.SOBREALCANTARILLADO<>0 OR SP_USUARIO.SUBASEO<>0)
ORDER BY SP_USUARIO.CICLO, SP_USUARIO.CODIGORUTA
