SELECT F.COMPANIA,
	F.ANO||F.PERIODO AS PER,
	F.ANO,
	F.PERIODO,
	SUM(F.DEUDA+F.VALORFINANT-F.VALORABONOANT) AS DEUDADEFINITIVA, 
	SUM(F.VALOR_FACTURADO+F.VALORFINACT-F.VALORABONOACT-F.CREDITOABONADO) AS FACTURADODEFINITIVO, 
	SUM(F.VALOR_FACTURADO+F.DEUDA+F.VALORFINANT+F.VALORFINACT-F.VALORABONOANT-F.VALORABONOACT-F.CREDITOABONADO) AS TOTALAPAGAR, 
	U.PERIODOSATRASO,
	U.USO,
	US.NOMBRE NOMBREUSO,
	U.ESTRATO,
	E.NOMBRE NOMBREESTRATO
	s$columnaServicio$s
	s$columnasConcepto$s
FROM SP_FACTURADO F
	INNER JOIN SP_USUARIO U
		ON F.COMPANIA 	 = U.COMPANIA
		AND F.CICLO 	 = U.CICLO
		AND F.CODIGORUTA = U.CODIGORUTA
		AND F.ANO 		 = U.ANO
		AND F.PERIODO 	 = U.PERIODO
	INNER JOIN SP_CONCEPTOS C
		ON F.COMPANIA  = C.COMPANIA
		AND F.CONCEPTO = C.CODIGO
	INNER JOIN SP_USOS US
		ON U.COMPANIA = US.COMPANIA
		AND U.USO = US.CODIGO	
	INNER JOIN SP_ESTRATOS E
		ON U.COMPANIA = E.COMPANIA
		AND U.USO = E.USO
		AND U.ESTRATO = E.CODIGO	
WHERE F.COMPANIA = s$compania$s
	AND F.CICLO BETWEEN s$cicloInicial$s AND s$cicloFinal$s
	AND U.PERIODOSATRASO BETWEEN s$periodoAtrasoInicial$s AND s$periodoAtrasoFinal$s
	AND U.BANCOPERPROCESO IS NULL
	AND (F.CONCEPTO BETWEEN 0 AND 48 
		OR F.CONCEPTO BETWEEN 201 AND 207
		OR F.CONCEPTO BETWEEN 246 AND 249)
	AND F.CONCEPTO NOT IN(12,17)
	s$condicionTot$s 
	AND TO_CHAR(U.USO,'00')||TO_CHAR(U.ESTRATO,'00') BETWEEN s$usoEstratoInicial$s AND s$usoEstratoFinal$s
	s$condicionEstado$s
GROUP BY F.COMPANIA, 
	F.ANO||F.PERIODO,
	F.ANO,
	F.PERIODO,
	U.PERIODOSATRASO,
	U.USO,
	US.NOMBRE,
	U.ESTRATO,
	E.NOMBRE
	s$columnaServicio$s 
	s$agruparConcepto$s
s$ordenAgrupar$s







