SELECT 
    SP_PLANOSDIGITAL.CICLO, 
    SP_PLANOSDIGITAL.ANO  , 
    SP_PLANOSDIGITAL.PERIODO  , 
    SP_PLANOSDIGITAL.CICLO || SP_PLANOSDIGITAL.ANO || SP_PLANOSDIGITAL.PERIODO CAB,
    SP_USUARIO.NOMBRES || ' ' || SP_USUARIO.PRIMERAPELLIDO || ' ' || SP_USUARIO.SEGUNDOAPELLIDO  NOMBREUSUARIO, 
   SP_PLANOSDIGITAL.MAECOD,    
   SP_PLANOSDIGITAL.TIPO_LEC, 
    SP_PLANOSDIGITAL.IND_FACT, 
    SP_PLANOSDIGITAL.COD_ERROR, 
    SP_PLANOSDIGITAL.MAECNS, 
    SP_PLANOSDIGITAL.MAELEC0, 
    SP_PLANOSDIGITAL.USUARIO, 
       s$fechaCampo$s  FECHASELECCION
FROM SP_PLANOSDIGITAL 
  LEFT JOIN SP_USUARIO 
    ON  SP_PLANOSDIGITAL.COMPANIA = SP_USUARIO.COMPANIA
    AND SP_PLANOSDIGITAL.CICLO = SP_USUARIO.CICLO
    AND SP_PLANOSDIGITAL.MAECOD1 = SP_USUARIO.CODIGOINTERNO
WHERE  SP_PLANOSDIGITAL.COMPANIA = s$compania$s
AND   s$condicionFecha$s
AND    LPAD(SP_PLANOSDIGITAL.ANO, 4,'0') || LPAD(SP_PLANOSDIGITAL.PERIODO, 2, '0') BETWEEN LPAD(s$anoInicial$s, 4,'0') || LPAD(s$periodoInicial$s, 2, '0') AND LPAD(s$anoFinal$s, 4,'0') || LPAD(s$periodoFinal$s, 2, '0')
