SELECT SP_USOS.NOMBRE USO, 
       SP_USOS.CODIGO CODIGO_USO, 
       NVL(NUM_USUARIOS_URB.SASEO,0) URB_ASEO, 
       NVL(NUM_USUARIOS_URB.SALCANTARILLADO,0) URB_ALC, 
       NVL(NUM_USUARIOS_URB.SACUEDUCTO,0) URB_ACUEDUCTO, 
       NVL(NUM_USUARIOS_RURAL.SASEO,0) RURAL_ASEO, 
       NVL(NUM_USUARIOS_RURAL.SALCANTARILLADO,0) RURAL_ALC, 
       NVL(NUM_USUARIOS_RURAL.SACUEDUCTO,0) RURAL_ACUEDUCTO,
       NVL(NUM_USUARIOS_URB.SACUEDUCTO,0) + NVL(NUM_USUARIOS_RURAL.SACUEDUCTO,0) TACUEDUCTO, 
       NVL(NUM_USUARIOS_URB.SALCANTARILLADO,0) + NVL(NUM_USUARIOS_RURAL.SALCANTARILLADO,0) TALC, 
       NVL(NUM_USUARIOS_URB.SASEO,0) + NVL(NUM_USUARIOS_RURAL.SASEO,0) TASEO
FROM SP_USOS 
  LEFT JOIN (SELECT  
              SP_USUARIO.COMPANIA, 
              SP_USUARIO.CICLO, 
              SP_USUARIO.ANO, 
              SP_USUARIO.PERIODO,
              SP_USOS.NOMBRE,
              SP_USOS.CODIGO,
              SP_USOS.CODIGO AS CODUSO, 
              SUM(CASE WHEN SP_USUARIO.ASEO <> 0 THEN 1 ELSE 0 END) AS SASEO, 
              SUM(CASE WHEN SP_USUARIO.ALCANTARILLADO <> 0 THEN 1 ELSE 0 END) AS SALCANTARILLADO, 
              SUM(CASE WHEN SP_USUARIO.ACUEDUCTO <>0 THEN 1 ELSE 0 END ) AS SACUEDUCTO
      FROM SP_USUARIO 
        INNER JOIN SP_USOS 
          ON SP_USUARIO.COMPANIA = SP_USOS.COMPANIA 
          AND SP_USUARIO.USO = SP_USOS.CODIGO 
      WHERE SP_USUARIO.COMPANIA= s$compania$s
        AND SP_USUARIO.CICLO= s$ciclo$s 
        AND SP_USUARIO.ANO = s$ano$s 
        AND SP_USUARIO.PERIODO = s$periodo$s
        AND SP_USUARIO.NOTADEBITO='R' 
        AND SP_USOS.CODIGO BETWEEN s$usoInicial$s AND s$usoFinal$s
      GROUP BY  SP_USUARIO.COMPANIA, 
                SP_USUARIO.CICLO, 
                SP_USUARIO.ANO, 
                SP_USUARIO.PERIODO,
                SP_USOS.NOMBRE,
                SP_USOS.CODIGO
      ORDER BY TO_NUMBER(SP_USOS.CODIGO)) NUM_USUARIOS_RURAL
    ON  SP_USOS.COMPANIA = NUM_USUARIOS_RURAL.COMPANIA 
    AND SP_USOS.CODIGO = NUM_USUARIOS_RURAL.CODIGO 
  LEFT JOIN (SELECT  
              SP_USUARIO.COMPANIA, 
              SP_USUARIO.CICLO, 
              SP_USUARIO.ANO, 
              SP_USUARIO.PERIODO,
              SP_USOS.NOMBRE,
              SP_USOS.CODIGO,
              SP_USOS.CODIGO AS CODUSO, 
              SUM(CASE WHEN SP_USUARIO.ASEO <> 0 THEN 1 ELSE 0 END) AS SASEO, 
              SUM(CASE WHEN SP_USUARIO.ALCANTARILLADO <> 0 THEN 1 ELSE 0 END) AS SALCANTARILLADO, 
              SUM(CASE WHEN SP_USUARIO.ACUEDUCTO <>0 THEN 1 ELSE 0 END ) AS SACUEDUCTO
      FROM SP_USUARIO 
        INNER JOIN SP_USOS 
          ON SP_USUARIO.COMPANIA = SP_USOS.COMPANIA 
          AND SP_USUARIO.USO = SP_USOS.CODIGO 
      WHERE SP_USUARIO.COMPANIA= s$compania$s
        AND SP_USUARIO.CICLO= s$ciclo$s
        AND SP_USUARIO.ANO = s$ano$s 
        AND SP_USUARIO.PERIODO = s$periodo$s
        AND SP_USUARIO.NOTADEBITO='U' 
        AND SP_USOS.CODIGO BETWEEN s$usoInicial$s AND s$usoFinal$s
      GROUP BY  SP_USUARIO.COMPANIA, 
                SP_USUARIO.CICLO, 
                SP_USUARIO.ANO, 
                SP_USUARIO.PERIODO,
                SP_USOS.NOMBRE,
                SP_USOS.CODIGO
      ORDER BY TO_NUMBER(SP_USOS.CODIGO))NUM_USUARIOS_URB 
    ON SP_USOS.COMPANIA = NUM_USUARIOS_URB.COMPANIA 
    AND SP_USOS.CODIGO = NUM_USUARIOS_URB.CODIGO
GROUP BY SP_USOS.NOMBRE, 
         SP_USOS.CODIGO, 
         NVL(NUM_USUARIOS_URB.SASEO,0), 
         NVL(NUM_USUARIOS_URB.SALCANTARILLADO,0), 
         NVL(NUM_USUARIOS_URB.SACUEDUCTO,0), 
         NVL(NUM_USUARIOS_RURAL.SASEO,0), 
         NVL(NUM_USUARIOS_RURAL.SALCANTARILLADO,0), 
         NVL(NUM_USUARIOS_RURAL.SACUEDUCTO,0), 
         NVL(NUM_USUARIOS_URB.SACUEDUCTO,0) + NVL(NUM_USUARIOS_RURAL.SACUEDUCTO,0), 
         NVL(NUM_USUARIOS_URB.SALCANTARILLADO,0) + NVL(NUM_USUARIOS_RURAL.SALCANTARILLADO,0), 
         NVL(NUM_USUARIOS_URB.SASEO,0) + NVL (NUM_USUARIOS_RURAL.SASEO,0)    
ORDER BY SP_USOS.NOMBRE
