SELECT * 
FROM 
  (SELECT COMPANIA, 
    CLASIFICACIONSUI, 
    CONCEPTOIN, 
    SERV, 
    TOTALCARTERA, 
    SUM(VALPERIODO) OVER(PARTITION BY COMPANIA,CLASIFICACIONSUI,SERV)VALPERIODO 
  FROM 
    (SELECT COMPANIA, 
      CLASIFICACIONSUI, 
      CONCEPTOIN, 
      SERV, 
      SUM(TOTALCARTERA) TOTALCARTERA, 
      SUM(VALPERIODO) VALPERIODO 
    FROM 
      (SELECT SP_USUARIO.COMPANIA, 
        SP_ESTRATOS.CLASIFICACIONSUI, 
        s$conceptoIn$s CONCEPTOIN, 
        CASE 
          WHEN SERVICIO='01' 
          THEN 'ACUEDUCTO' 
          ELSE 
            CASE 
              WHEN SERVICIO='02' 
              THEN 'ALCANTARILLADO' 
              ELSE 
                CASE 
                  WHEN SERVICIO='03' 
                  THEN 'ASEO' 
                  ELSE 'OTROS' 
                END 
            END 
        END   AS SERV, 
        (SP_FACTURADO.VALOR_FACTURADO + SP_FACTURADO.VALORFINACT - SP_FACTURADO.VALORABONOACT)  AS VALPERIODO, 
        (SP_FACTURADO.DEUDA + SP_FACTURADO.VALORFINANT - SP_FACTURADO.VALORABONOANT - SP_FACTURADO.CREDITOABONADO) AS TOTALCARTERA 
      FROM (SP_USUARIO 
      INNER JOIN (SP_FACTURADO 
        INNER JOIN SP_CONCEPTOS 
          ON  SP_FACTURADO.COMPANIA  = SP_CONCEPTOS.COMPANIA 
          AND SP_FACTURADO.CONCEPTO = SP_CONCEPTOS.CODIGO) 
        ON  SP_USUARIO.COMPANIA    = SP_FACTURADO.COMPANIA 
        AND SP_USUARIO.CICLO      = SP_FACTURADO.CICLO 
        AND SP_USUARIO.CODIGORUTA = SP_FACTURADO.CODIGORUTA 
        AND SP_USUARIO.ANO        = SP_FACTURADO.ANO 
        AND SP_USUARIO.PERIODO    = SP_FACTURADO.PERIODO) 
      LEFT JOIN SP_ESTRATOS 
        ON  SP_USUARIO.COMPANIA  = SP_ESTRATOS.COMPANIA 
        AND SP_USUARIO.ESTRATO  = SP_ESTRATOS.CODIGO 
        AND SP_USUARIO.USO      = SP_ESTRATOS.USO 
      WHERE SP_USUARIO.COMPANIA='s$compania$s'  
        AND SP_USUARIO.CICLO BETWEEN 's$cicloInicial$s' AND 's$cicloFinal$s' 
        AND SP_USUARIO.BANCOPERPROCESO IS NULL  
        s$incluirSuspendidosRetiros$s 
        AND (SP_FACTURADO.CONCEPTO BETWEEN 1 AND 48 
        OR  SP_FACTURADO.CONCEPTO  IN (201,202,203,204,205,206,207,246,247,248,249)) 
        AND SP_FACTURADO.CONCEPTO NOT IN (12,17) 
      ) 
    GROUP BY COMPANIA, 
      CLASIFICACIONSUI, 
      CONCEPTOIN, 
      SERV 
    ) 
  )PIVOT (SUM(TOTALCARTERA) FOR (CONCEPTOIN ) s$inPivot$s)
