SELECT HISTORICOFACTURA.ABONOACT,   
       HISTORICOFACTURA.ACUEDUCTO,   
       HISTORICOFACTURA.ALCANTARILLADO, 
       HISTORICOFACTURA.ALCBASICO,   
       HISTORICOFACTURA.ALCCOMPLEMENTARIO,  
       HISTORICOFACTURA.ANO,   
       HISTORICOFACTURA.ASEO,   
       HISTORICOFACTURA.CARGOFIJO,   
       HISTORICOFACTURA.CICLO,  
       HISTORICOFACTURA.CODIGO,   
       HISTORICOFACTURA.CODIGOANTERIOR,    
       HISTORICOFACTURA.CODIGOCATASTRAL,   
       HISTORICOFACTURA.CODIGOINTERNO,   
       HISTORICOFACTURA.CODIGORUTA,   
       HISTORICOFACTURA.COMPANIA,   
       HISTORICOFACTURA.CONSUMO,    
       HISTORICOFACTURA.CONSUMO1,  
       HISTORICOFACTURA.CONSUMO2,    
       HISTORICOFACTURA.CONSUMO3,    
       HISTORICOFACTURA.CONSUMO4,   
       HISTORICOFACTURA.CONSUMO5,   
       HISTORICOFACTURA.CONSUMO6,  
       HISTORICOFACTURA.CONSUMOBASICO,   
       HISTORICOFACTURA.CONSUMOBASICOALC,   
       HISTORICOFACTURA.CONSUMOCOMPLEMENTARIO,    
       HISTORICOFACTURA.CONSUMOCOMPLEMENTARIOALC,   
       HISTORICOFACTURA.CONSUMOPROM,   
       HISTORICOFACTURA.CONSUMOSUNTUARIO,   
       HISTORICOFACTURA.CONSUMOSUNTUARIOALC,   
       HISTORICOFACTURA.DEUDA,  
       HISTORICOFACTURA.DIRCORRESPONDENCIA,    
       HISTORICOFACTURA.DIRTECNICA,    
       HISTORICOFACTURA.ESTADO,    
       HISTORICOFACTURA.ESTRATO,    
       HISTORICOFACTURA.FACTURA,   
       TO_DATE(HISTORICOFACTURA.FECHAEXPEDICION) FECHAEXPEDICION,   
       TO_DATE(HISTORICOFACTURA.FECHALIMITE) FECHALIMITE,    
       TO_DATE(HISTORICOFACTURA.FECHALIMITE1) FECHALIMITE1,   
       TO_DATE(HISTORICOFACTURA.FECHALIMITE2) FECHALIMITE2,   
       HISTORICOFACTURA.FECHASPERIODO,   
       HISTORICOFACTURA.FECHASUSPENSION,  
       HISTORICOFACTURA.LECTURA,  
       HISTORICOFACTURA.LECTURA1,   
       HISTORICOFACTURA.LECTURA2,   
       HISTORICOFACTURA.LECTURA3,   
       HISTORICOFACTURA.LECTURA4,    
       HISTORICOFACTURA.LECTURA5,   
       HISTORICOFACTURA.LECTURA6,   
       HISTORICOFACTURA.LECTURAAFORO,   
       HISTORICOFACTURA.LECTURAINICIAL, 
       HISTORICOFACTURA.MEDIDOR,   
       HISTORICOFACTURA.NIT,  
       HISTORICOFACTURA.NOMBRES,    
       HISTORICOFACTURA.NOMBREUSO,  
       HISTORICOFACTURA.OBSERVACION1,    
       HISTORICOFACTURA.PAGO1,  
       HISTORICOFACTURA.PAGO2,
       HISTORICOFACTURA.PERIODO, 
       HISTORICOFACTURA.PERIODOSATRASO,  
       HISTORICOFACTURA.PRIMERAPELLIDO,   
       HISTORICOFACTURA.RAN1,    
       HISTORICOFACTURA.RAN2,    
       HISTORICOFACTURA.RAN3,  
       HISTORICOFACTURA.RECARGOACUEDUCTO,    
       HISTORICOFACTURA.RECARGOALC,   
       HISTORICOFACTURA.RECARGOASEO,   
       HISTORICOFACTURA.RECAUDADOANTERIOR,    
       HISTORICOFACTURA.SEGUNDOAPELLIDO,    
       HISTORICOFACTURA.TAFA_720,    
       HISTORICOFACTURA.TAFNA_720,  
       HISTORICOFACTURA.TARIFABASICO,    
       HISTORICOFACTURA.TARIFACOMPLEMENTARIO,  
       HISTORICOFACTURA.TARIFAM3SUNTUARIOAC TARIFASUNTUARIOAC, 
       HISTORICOFACTURA.TARIFASUNTUARIO,  
       HISTORICOFACTURA.TARSOBREBAS,    
       HISTORICOFACTURA.TARSUBBAS,   
       HISTORICOFACTURA.TIPOLECTURA,    
       HISTORICOFACTURA.TOTALACUEDUCTO,    
       HISTORICOFACTURA.TOTALALCANTARILLADO,    
       HISTORICOFACTURA.TOTALASEO,    
       HISTORICOFACTURA.TOTALDEUDA,   
       HISTORICOFACTURA.TOTFACTURAPERACTUAL,   
       HISTORICOFACTURA.TOTFACTURAPERANTERIOR,  
       HISTORICOFACTURA.USO,    
       HISTORICOFACTURA.VASEOBARRIDO,   
       HISTORICOFACTURA.VASEOCONSUMO,   
       HISTORICOFACTURA.VASEODOMICILIARIO,   
       HISTORICOFACTURA.VASEOUNICO,  
       HISTORICOFACTURA.VTRAMOEXCEDENTE,   
       HISTORICOFACTURA.NOMBRES || HISTORICOFACTURA.PRIMERAPELLIDO || HISTORICOFACTURA.SEGUNDOAPELLIDO AS NOMBRECOMPLETO,
       HISTORIA_EXTERNA.SUBOSOBRE AS TERSUBOSOBRE,
       NVL(HISTORIA_EXTERNA.VALORASEO,0) AS TERVALORASEO,
       HISTORIA_EXTERNA.HISTORICO1,
       HISTORIA_EXTERNA.HISTORICO2,
       HISTORIA_EXTERNA.HISTORICO3,
       HISTORIA_EXTERNA.HISTORICO5,
       HISTORIA_EXTERNA.HISTORICO6,
       HISTORIA_EXTERNA.HISTORICO4,
       CASE WHEN PINTA NOT IN (0) 
            THEN HISTORIA_EXTERNA.FRECUENCIA_ASEO
            ELSE FRE_RECO_SYS 
       END AS FREC_RECO,
       CASE WHEN PINTA NOT IN (0) 
            THEN HISTORIA_EXTERNA.FRECUENCIA_BARRIDO
            ELSE FREC_BARRI_SYS 
       END AS FREC_BARRI,
       CASE WHEN PINTA NOT IN (0) 
            THEN TO_NUMBER(HISTORIA_EXTERNA.TDI_ASEO) 
            ELSE PESOASEO_SYS END                AS PESOASEO,
       CASE WHEN PINTA NOT IN (0) 
            THEN HISTORIA_EXTERNA.HISTORICO1 
            ELSE VALASEO1_SYS 
       END AS VALASEO1,
       CASE WHEN PINTA NOT IN (0) 
            THEN HISTORIA_EXTERNA.HISTORICO2 
            ELSE VALASEO2_SYS
       END AS VALASEO2,
       CASE WHEN PINTA NOT IN (0) 
            THEN HISTORIA_EXTERNA.HISTORICO3 
            ELSE VALASEO3_SYS 
       END AS VALASEO3,
       CASE WHEN PINTA NOT IN (0) 
            THEN HISTORIA_EXTERNA.HISTORICO4 
            ELSE VALASEO4_SYS
       END AS VALASEO4,
       CASE WHEN PINTA NOT IN (0) 
            THEN HISTORIA_EXTERNA.HISTORICO5 
            ELSE VALASEO5_SYS
       END AS VALASEO5,
       CASE WHEN PINTA NOT IN (0) 
            THEN HISTORIA_EXTERNA.HISTORICO6 
            ELSE VALASEO6_SYS
       END AS VALASEO6,
       HISTORIA_EXTERNA.UNIDADES_RESID,
       HISTORIA_EXTERNA.VALORDEU,
       HISTORIA_EXTERNA.VALORASEO_SINSUBOSOBRE,
       HISTORIA_EXTERNA.SUBOSOBRE_DES,
       HISTORIA_EXTERNA.INTMORA,
       HISTORIA_EXTERNA.VALORASEO,
       HISTORIA_EXTERNA.BARRIDO_TBL,
       HISTORIA_EXTERNA.RECOLECCION_TRT,
       HISTORIA_EXTERNA.TRAMOEXCE_TTE,
       HISTORIA_EXTERNA.DISPOFINAL_TDT,
       HISTORIA_EXTERNA.MANEJOREC_TFR,
       HISTORIA_EXTERNA.REF01,
       HISTORIA_EXTERNA.REF02,
       HISTORIA_EXTERNA.REF03,
       HISTORIA_EXTERNA.REF04,
       HISTORIA_EXTERNA.REF05,
       HISTORIA_EXTERNA.SUBOSOBRE,
       HISTORIA_EXTERNA.TEX01,
       HISTORIA_EXTERNA.TEX02,
       HISTORIA_EXTERNA.TEX03,
       ESTRATOS.NOMBRE AS NOMBREESTRATO,
       0 AS PAGA,
       TARIFASCOSTOS.COSTO_CCS_720 + TARIFASCOSTOS.COSTO_CBLS_720 + TARIFASCOSTOS.COSTO_CLUS_720 AS CTF_COMP,
       TARIFASCOSTOS.COSTO_CRT_720 + TARIFASCOSTOS.COSTO_CDF_720 + TARIFASCOSTOS.COSTO_CTL_720   AS CVNA_COMP,
       TARIFASCOSTOS.COSTO_TRBL_720 AS TRBL_COMP,
       TARIFASCOSTOS.COSTO_TRLU_720 AS TRLU_COMP,
       CASE WHEN  HISTORICOFACTURA.TAFNA_720 NOT IN (0)
            THEN HISTORICOFACTURA.TAFNA_720 
            ELSE TARIFASCOSTOS.COSTO_TRNA_720 
       END AS TRNA_COMP,
       TARIFASCOSTOS.COSTO_TRRA_720 AS TRRA_COMP,
       TARIFASCOSTOS.COSTO_VBA_720 AS VBA_COMP,
       CASE WHEN HISTORICOFACTURA.TAFA_720 NOT IN(0)
              OR HISTORICOFACTURA.TAFNA_720 NOT IN (0) 
            THEN HISTORICOFACTURA.TAFA_720 
            ELSE TARIFASCOSTOS.COSTO_TRA_720 
       END AS TRA_COMP,
       TARIFASCOSTOS.COSTO_FCS_720 AS FCS_COMP,
       TARIFASCOSTOS.COSTO_FCS1_720 AS FCS1_COMP,
       CASE WHEN NVL(HISTORIA_EXTERNA.VALORASEO,0) = 0 
            THEN -1 
            ELSE 0 
       END AS ASEOUNIDADESR,    
       CASE WHEN CASE WHEN NVL(HISTORIA_EXTERNA.VALORASEO,0) = 0 
                      THEN -1 
                      ELSE 0 
                 END NOT IN (0) 
            THEN TARIFASCOSTOS.COSTO_CCS_720 + TARIFASCOSTOS.COSTO_CBLS_720 + TARIFASCOSTOS.COSTO_CLUS_720  
            ELSE HISTORIA_EXTERNA.COSTO_CCS_720 + HISTORIA_EXTERNA.COSTO_CBLS_720 + HISTORIA_EXTERNA.COSTO_CLUS_720
       END AS CTF,
       CASE WHEN CASE WHEN NVL(HISTORIA_EXTERNA.VALORASEO,0) = 0 
                      THEN -1 
                      ELSE 0 
                 END NOT IN (0) 
            THEN TARIFASCOSTOS.COSTO_CRT_720 + TARIFASCOSTOS.COSTO_CDF_720 + TARIFASCOSTOS.COSTO_CTL_720 
            ELSE HISTORIA_EXTERNA.COSTO_CRT_720 + HISTORIA_EXTERNA.COSTO_CDF_720 + HISTORIA_EXTERNA.COSTO_CTL_720
       END AS CVNA,
       CASE WHEN CASE WHEN NVL(HISTORIA_EXTERNA.VALORASEO,0) = 0 
                      THEN -1 
                      ELSE 0 
                 END NOT IN (0) 
            THEN TARIFASCOSTOS.COSTO_TRBL_720 
            ELSE HISTORIA_EXTERNA.COSTO_TRBL_720 
       END AS TRBL,
       CASE WHEN CASE WHEN NVL(HISTORIA_EXTERNA.VALORASEO,0) = 0 
                      THEN -1 
                      ELSE 0 
                 END NOT IN (0)
            THEN TARIFASCOSTOS.COSTO_TRLU_720 
            ELSE HISTORIA_EXTERNA.COSTO_TRLU_720
       END AS TRLU,
       CASE WHEN CASE WHEN NVL(HISTORIA_EXTERNA.VALORASEO,0) = 0 
                      THEN -1 
                      ELSE 0 
                 END NOT IN (0) 
            THEN CASE WHEN  HISTORICOFACTURA.TAFNA_720 NOT IN (0) 
                      THEN HISTORICOFACTURA.TAFNA_720
                      ELSE TARIFASCOSTOS.COSTO_TRNA_720 
                 END 
            ELSE HISTORIA_EXTERNA.COSTO_TRNA_720
       END AS TRNA,
       CASE WHEN CASE WHEN NVL(HISTORIA_EXTERNA.VALORASEO,0) = 0 
                      THEN -1 
                      ELSE 0 
                 END NOT IN (0) 
            THEN TARIFASCOSTOS.COSTO_TRRA_720
            ELSE HISTORIA_EXTERNA.COSTO_TRRA_720
       END AS TRRA,
       CASE WHEN CASE WHEN NVL(HISTORIA_EXTERNA.VALORASEO,0) = 0 
                      THEN -1 
                      ELSE 0 
                 END NOT IN (0) 
            THEN TARIFASCOSTOS.COSTO_VBA_720 
            ELSE HISTORIA_EXTERNA.COSTO_VBA_720
       END AS VBA,
       CASE WHEN CASE WHEN NVL(HISTORIA_EXTERNA.VALORASEO,0) = 0 
                      THEN -1 
                      ELSE 0 
                 END NOT IN (0)
            THEN CASE WHEN  HISTORICOFACTURA.TAFA_720 NOT IN(0) OR HISTORICOFACTURA.TAFNA_720 NOT IN (0) 
                      THEN HISTORICOFACTURA.TAFA_720
                      ELSE TARIFASCOSTOS.COSTO_TRA_720 END 
            ELSE HISTORIA_EXTERNA.COSTO_TRA_720
       END AS TRA,
       CASE WHEN CASE WHEN NVL(HISTORIA_EXTERNA.VALORASEO,0) = 0 
                      THEN -1 
                      ELSE 0 
                 END NOT IN (0) 
            THEN TARIFASCOSTOS.COSTO_FCS_720 
            ELSE HISTORIA_EXTERNA.COSTO_FCS_720
       END AS FCS,
       CASE WHEN CASE WHEN NVL(HISTORIA_EXTERNA.VALORASEO,0) = 0 
                      THEN -1 
                      ELSE 0 
                 END NOT IN (0) 
            THEN TARIFASCOSTOS.COSTO_FCS1_720 
            ELSE HISTORIA_EXTERNA.COSTO_FCS1_720
       END AS FCS1,
       0 AS DESVIOSIGNIFICATIVO,
       TO_CHAR(PCK_CODIGODEBARRAS.FC_IMPRIMIRCODIGODEBARRAS(
                                    CHR(205)||CHR(102)
                                    ||'415'
                                    ||NVL(PCK_SYSMAN_UTL.FC_PAR(
                                                     UN_COMPANIA  => HISTORICOFACTURA.COMPANIA
                                                    ,UN_NOMBRE    => 'CODIGO DE SERVICIO EAN'
                                                    ,UN_MODULO    => PCK_DATOS.FC_MODULOSERVICIOSPUBLICOS
                                                    ,UN_FECHA_PAR => SYSDATE),'9999999999999')
                                    ||'8020'
                                    ||'3900'
                                    ||TRIM(TO_CHAR(HISTORICOFACTURA.CODIGOINTERNO, '0000000000'))
                                    ||CASE WHEN PCK_SYSMAN_UTL.FC_PAR(
                                                               UN_COMPANIA  => HISTORICOFACTURA.COMPANIA
                                                              ,UN_NOMBRE    => 'INCLUYE FECHA EN BARRAS EAN'
                                                              ,UN_MODULO    => PCK_DATOS.FC_MODULOSERVICIOSPUBLICOS
                                                              ,UN_FECHA_PAR => SYSDATE) = 'SI'
                                           THEN CHR(102)||'96'||TO_CHAR(HISTORICOFACTURA.FECHALIMITE2,'YYYYMMDD')
                                           ELSE '' 
                                      END
                                    )) CODIGODEBARRAS_BIN,
       NVL(UNIDADESRESIDENCIALES.TOTALRESIDENCIALES,0) NUMUNIDADES,
       NVL(TOTALCONVENIOS.TOTAL,0) TOTCONVENIO,
       HISTORIA_EXTERNA.VALORASEO TOT_ASEO_TER, 
       MEDIDOR.DIAMETRO DIAMETROMEDIDOR,
       CASE WHEN HISTORICOFACTURA.ACUEDUCTO NOT IN (0) 
            THEN HISTORICOFACTURA.CARGOFIJO + HISTORICOFACTURA.SUBFIJO - HISTORICOFACTURA.SOBREFIJO
            ELSE 0
       END TARIFACARGOFIJOACU,    
       NVL(TOTALCONVENIOS.TOTAL,0) TOTALCONVENIOS,
       '(415)'
         ||NVL(PCK_SYSMAN_UTL.FC_PAR(
                              UN_COMPANIA  => HISTORICOFACTURA.COMPANIA
                             ,UN_NOMBRE    => 'CODIGO DE SERVICIO EAN'
                             ,UN_MODULO    => PCK_DATOS.FC_MODULOSERVICIOSPUBLICOS
                             ,UN_FECHA_PAR => SYSDATE),'9999999999999')
          ||'(8020)'
          ||'(3900)'
          ||TRIM(TO_CHAR(HISTORICOFACTURA.CODIGOINTERNO, '0000000000'))
          ||CASE WHEN PCK_SYSMAN_UTL.FC_PAR(
                                     UN_COMPANIA  => HISTORICOFACTURA.COMPANIA
                                    ,UN_NOMBRE    => 'INCLUYE FECHA EN BARRAS EAN'
                                    ,UN_MODULO    => PCK_DATOS.FC_MODULOSERVICIOSPUBLICOS
                                    ,UN_FECHA_PAR => SYSDATE) = 'SI'
                 THEN CHR(102)||'96'||TO_CHAR(HISTORICOFACTURA.FECHALIMITE2,'YYYYMMDD')
                 ELSE '' 
            END BARRAS,
       PCK_SERVICIOS_PUBLICOS_COM8.FC_ESCRIBIRPERIODOCORTO(UN_COMPANIA => HISTORICOFACTURA.COMPANIA,
                                                           UN_PERIODO  => HISTORICOFACTURA.PERIODO,
                                                           UN_ANIO     => HISTORICOFACTURA.ANO) PERIODOFACTURA,
       TO_CHAR(CASE WHEN s$marca$s IN (3) OR HISTORICOFACTURA.ABONOACT NOT IN (0) 
                    THEN HISTORICOFACTURA.ABONOACT
                    ELSE HISTORICOFACTURA.TOTFACTURAPERACTUAL
               END
               + NVL(HISTORIA_EXTERNA.VALORASEO,0),'$999,999,999,999,999,999.99') TOTFACTURAPERACTUAL1,
       CASE WHEN HISTORICOFACTURA.ACUEDUCTO NOT IN (0)
            THEN HISTORICOFACTURA.TARIFABASICO + HISTORICOFACTURA.SUBBASICO - HISTORICOFACTURA.SOBREBASICO
            ELSE 0
       END TARIFABASICOACU,
       CASE WHEN HISTORICOFACTURA.ACUEDUCTO NOT IN (0)
            THEN HISTORICOFACTURA.TARIFACOMPLEMENTARIO + HISTORICOFACTURA.SUBCOMPLEMENTARIO - HISTORICOFACTURA.SOBRECOMPLEMENTARIO
            ELSE 0
       END TARIFACOMPLEMACU,
       CASE WHEN HISTORICOFACTURA.ACUEDUCTO  NOT IN (0)
            THEN HISTORICOFACTURA.TARIFASUNTUARIO + HISTORICOFACTURA.SUBSUNTUARIO - HISTORICOFACTURA.SOBRESUNTUARIO
            ELSE 0
       END TARIFASUNTUARIOACU,
       CASE WHEN HISTORICOFACTURA.ACUEDUCTO NOT IN (0)
            THEN CASE WHEN HISTORICOFACTURA.ACUEDUCTO NOT IN (0)
                      THEN HISTORICOFACTURA.TARIFABASICO + HISTORICOFACTURA.SUBBASICO - HISTORICOFACTURA.SOBREBASICO
                      ELSE 0
                 END * HISTORICOFACTURA.CONSUMOBASICO
            ELSE 0
       END VALORBASICOACU,    
       CASE WHEN HISTORICOFACTURA.ACUEDUCTO NOT IN (0)
            THEN CASE WHEN HISTORICOFACTURA.ACUEDUCTO NOT IN (0)
                      THEN HISTORICOFACTURA.TARIFACOMPLEMENTARIO + HISTORICOFACTURA.SUBCOMPLEMENTARIO - HISTORICOFACTURA.SOBRECOMPLEMENTARIO 
                      ELSE 0
                 END * HISTORICOFACTURA.CONSUMOCOMPLEMENTARIO
            ELSE 0
       END VALORCOMPLEMACU, 
       CASE WHEN HISTORICOFACTURA.ACUEDUCTO NOT IN (0)
            THEN CASE WHEN HISTORICOFACTURA.ACUEDUCTO  NOT IN (0)
                      THEN HISTORICOFACTURA.TARIFASUNTUARIO + HISTORICOFACTURA.SUBSUNTUARIO - HISTORICOFACTURA.SOBRESUNTUARIO
                      ELSE 0
                 END * HISTORICOFACTURA.CONSUMOSUNTUARIO
            ELSE 0
       END VALORSUNTUARIOACU,    
       CASE WHEN HISTORICOFACTURA.ACUEDUCTO NOT IN (0)
            THEN 1 * CASE WHEN HISTORICOFACTURA.ACUEDUCTO NOT IN (0) 
                          THEN HISTORICOFACTURA.CARGOFIJO + HISTORICOFACTURA.SUBFIJO - HISTORICOFACTURA.SOBREFIJO
                          ELSE 0
                     END
            ELSE 0
       END VALORCARGOFIJOACU,
       NVL(UNIDADESRESIDENCIALES.TOTALOTROS,0) NUMUNIDADES2,
       NVL(TOTALCONVENIOS.TOTAL,0) TOT_CONVENIO, 
       CASE WHEN HISTORICOFACTURA.ALCANTARILLADO NOT IN (0)
            THEN HISTORICOFACTURA.ALCBASICO + HISTORICOFACTURA.SUBALCBASICO - HISTORICOFACTURA.SOBREALCBASICO
            ELSE 0
       END TARIFABASICOALC,
       CASE WHEN HISTORICOFACTURA.ALCANTARILLADO NOT IN (0)
            THEN HISTORICOFACTURA.ALCCOMPLEMENTARIO + HISTORICOFACTURA.SUBALCCOMPLEMENTARIO - HISTORICOFACTURA.SOBREALCCOMPLEMENTARIO
            ELSE 0
       END TARIFACOMPLEMALC,
       CASE WHEN HISTORICOFACTURA.ALCANTARILLADO NOT IN (0)
            THEN HISTORICOFACTURA.ALCCOMPLEMENTARIO + HISTORICOFACTURA.SUBALCCOMPLEMENTARIO - HISTORICOFACTURA.SOBREALCCOMPLEMENTARIO
            ELSE 0
       END TARIFASUNTUARIOALC,
       CASE WHEN HISTORICOFACTURA.ALCANTARILLADO NOT IN (0)
            THEN HISTORICOFACTURA.CONSUMOCOMPLEMENTARIOALC 
                 * CASE WHEN HISTORICOFACTURA.ALCANTARILLADO NOT IN (0)
                        THEN HISTORICOFACTURA.ALCCOMPLEMENTARIO + HISTORICOFACTURA.SUBALCCOMPLEMENTARIO - HISTORICOFACTURA.SOBREALCCOMPLEMENTARIO
                        ELSE 0
                   END
            ELSE 0
       END VALORCOMPLEMALC,
       HISTORICOFACTURA.SOBREACUEDUCTO - HISTORICOFACTURA.SUBACUEDUCTO SUBSIDIOACU,
       HISTORICOFACTURA.SOBREALCANTARILLADO - HISTORICOFACTURA.SUBALCANTARILLADO SUBSIDIOALC,
       MEDIDOR.TIPO TIPOMEDIDOR,
       MEDIDOR.MARCA MARCAMEDIDOR,
       NVL(TOTALFACTURA.VALORTOTAL,0)  TOTALSUBREPORTE1,
       PCK_SERVICIOS_PUBLICOS_COM8.FC_ESCRIBIRPERIODOCORTO(HISTORICOFACTURA.COMPANIA,(HISTORICOFACTURA.PERIODO-1),HISTORICOFACTURA.ANO) PERIODO1,  
       PCK_SERVICIOS_PUBLICOS_COM8.FC_ESCRIBIRPERIODOCORTO(HISTORICOFACTURA.COMPANIA,(HISTORICOFACTURA.PERIODO-2),HISTORICOFACTURA.ANO) PERIODO2, 
       PCK_SERVICIOS_PUBLICOS_COM8.FC_ESCRIBIRPERIODOCORTO(HISTORICOFACTURA.COMPANIA,(HISTORICOFACTURA.PERIODO-3),HISTORICOFACTURA.ANO) PERIODO3, 
       PCK_SERVICIOS_PUBLICOS_COM8.FC_ESCRIBIRPERIODOCORTO(HISTORICOFACTURA.COMPANIA,(HISTORICOFACTURA.PERIODO-4),HISTORICOFACTURA.ANO) PERIODO4, 
       PCK_SERVICIOS_PUBLICOS_COM8.FC_ESCRIBIRPERIODOCORTO(HISTORICOFACTURA.COMPANIA,(HISTORICOFACTURA.PERIODO-5),HISTORICOFACTURA.ANO) PERIODO5, 
       PCK_SERVICIOS_PUBLICOS_COM8.FC_ESCRIBIRPERIODOCORTO(HISTORICOFACTURA.COMPANIA,(HISTORICOFACTURA.PERIODO-6),HISTORICOFACTURA.ANO) PERIODO6,   
       HISTORICOFACTURA.VALASEO1_SYS VALASEO1, 
       HISTORICOFACTURA.VALASEO2_SYS VALASEO2,    
       HISTORICOFACTURA.VALASEO3_SYS VALASEO3,   
       HISTORICOFACTURA.VALASEO4_SYS VALASEO4,   
       HISTORICOFACTURA.VALASEO5_SYS VALASEO5,  
       HISTORICOFACTURA.VALASEO6_SYS VALASEO6,
       NVL(HISTORICOFACTURA.RECARGOALC,0) + NVL(HISTORICOFACTURA.RECARGOASEO,0) + NVL(HISTORICOFACTURA.RECARGOACUEDUCTO,0) TOTALRECARGOS,   
       CASE WHEN HISTORICOFACTURA.ALCANTARILLADO NOT IN (0)
            THEN (HISTORICOFACTURA.CONSUMOBASICOALC 
                  * CASE WHEN HISTORICOFACTURA.ALCANTARILLADO NOT IN (0)
                         THEN HISTORICOFACTURA.ALCBASICO + HISTORICOFACTURA.SUBALCBASICO - HISTORICOFACTURA.SOBREALCBASICO
                         ELSE 0
                    END)
            ELSE 0
       END VALORBASICOALC,
       CASE WHEN HISTORICOFACTURA.ALCANTARILLADO NOT IN (0)
            THEN HISTORICOFACTURA.CONSUMOSUNTUARIOALC 
                 * CASE WHEN HISTORICOFACTURA.ALCANTARILLADO NOT IN (0)
                        THEN HISTORICOFACTURA.ALCCOMPLEMENTARIO + HISTORICOFACTURA.SUBALCCOMPLEMENTARIO - HISTORICOFACTURA.SOBREALCCOMPLEMENTARIO
                        ELSE 0
                   END
            ELSE 0
       END VALORSUNTUARIOALC,
       CASE WHEN HISTORICOFACTURA.ALCANTARILLADO NOT IN (0)
            THEN (HISTORICOFACTURA.CONSUMOBASICOALC 
                  * CASE WHEN HISTORICOFACTURA.ALCANTARILLADO NOT IN (0)
                         THEN HISTORICOFACTURA.ALCBASICO + HISTORICOFACTURA.SUBALCBASICO - HISTORICOFACTURA.SOBREALCBASICO
                         ELSE 0
                     END)
            ELSE 0
       END 
       + CASE WHEN HISTORICOFACTURA.ALCANTARILLADO NOT IN (0)
              THEN HISTORICOFACTURA.CONSUMOCOMPLEMENTARIOALC 
                   * CASE WHEN HISTORICOFACTURA.ALCANTARILLADO NOT IN (0)
                          THEN HISTORICOFACTURA.ALCCOMPLEMENTARIO + HISTORICOFACTURA.SUBALCCOMPLEMENTARIO - HISTORICOFACTURA.SOBREALCCOMPLEMENTARIO
                          ELSE 0
                     END
              ELSE 0
         END 
        + CASE WHEN HISTORICOFACTURA.ALCANTARILLADO NOT IN (0)
               THEN HISTORICOFACTURA. CONSUMOSUNTUARIOALC 
                    * CASE WHEN HISTORICOFACTURA.ALCANTARILLADO NOT IN (0)
                           THEN HISTORICOFACTURA.ALCCOMPLEMENTARIO + HISTORICOFACTURA.SUBALCCOMPLEMENTARIO - HISTORICOFACTURA.SOBREALCCOMPLEMENTARIO
                           ELSE 0
                      END
               ELSE 0
          END 
        + CASE WHEN HISTORICOFACTURA.ALCANTARILLADO NOT IN (0)
               THEN 1 * CASE WHEN HISTORICOFACTURA.ALCANTARILLADO NOT IN (0)
                             THEN HISTORICOFACTURA.FIJOALCANTARILLADO + HISTORICOFACTURA.SUBALCFIJO - HISTORICOFACTURA.SOBREALCFIJO
                             ELSE 0
                        END
               ELSE 0
       END SUBTOTALALC,
       CASE WHEN HISTORICOFACTURA.ACUEDUCTO NOT IN (0)
            THEN CASE WHEN HISTORICOFACTURA.ACUEDUCTO NOT IN (0)
                      THEN HISTORICOFACTURA.TARIFABASICO + HISTORICOFACTURA.SUBBASICO - HISTORICOFACTURA.SOBREBASICO
                      ELSE 0
                 END * HISTORICOFACTURA.CONSUMOBASICO
            ELSE 0
       END
       + CASE WHEN HISTORICOFACTURA.ACUEDUCTO NOT IN (0)
              THEN CASE WHEN HISTORICOFACTURA.ACUEDUCTO NOT IN (0)
                        THEN HISTORICOFACTURA.TARIFACOMPLEMENTARIO + HISTORICOFACTURA.SUBCOMPLEMENTARIO - HISTORICOFACTURA.SOBRECOMPLEMENTARIO 
                        ELSE 0
                   END * HISTORICOFACTURA.CONSUMOCOMPLEMENTARIO
                ELSE 0
         END
       + CASE WHEN HISTORICOFACTURA.ACUEDUCTO NOT IN (0)
              THEN CASE WHEN HISTORICOFACTURA.ACUEDUCTO  NOT IN (0)
                        THEN HISTORICOFACTURA.TARIFASUNTUARIO + HISTORICOFACTURA.SUBSUNTUARIO - HISTORICOFACTURA.SOBRESUNTUARIO
                        ELSE 0
                   END * HISTORICOFACTURA.CONSUMOSUNTUARIO
              ELSE 0
         END
       + CASE WHEN HISTORICOFACTURA.ACUEDUCTO NOT IN (0)
              THEN 1 * CASE WHEN HISTORICOFACTURA.ACUEDUCTO NOT IN (0) 
                            THEN HISTORICOFACTURA.CARGOFIJO + HISTORICOFACTURA.SUBFIJO - HISTORICOFACTURA.SOBREFIJO
                            ELSE 0
                       END
              ELSE 0
         END SUBTOTALACU,
       CASE WHEN HISTORICOFACTURA.ALCANTARILLADO NOT IN (0)
            THEN 1* CASE WHEN HISTORICOFACTURA.ALCANTARILLADO NOT IN (0)
                         THEN HISTORICOFACTURA.FIJOALCANTARILLADO + HISTORICOFACTURA.SUBALCFIJO - HISTORICOFACTURA.SOBREALCFIJO
                         ELSE 0
                    END
            ELSE 0
       END VALORCARGOFIJOALC,
       CASE WHEN HISTORICOFACTURA.ALCANTARILLADO NOT IN (0)
            THEN HISTORICOFACTURA.FIJOALCANTARILLADO + HISTORICOFACTURA.SUBALCFIJO - HISTORICOFACTURA.SOBREALCFIJO
            ELSE 0
       END TARIFACARGOFIJOALC,
       HISTORICOFACTURA.PROBLEMA PRIMERPROBLEMA,
       CASE WHEN NVL(HISTORICOFACTURA.RECAUDADOANTERIOR,0) IN (0)
            THEN PCK_SERVICIOS_PUBLICOS_COM8.FC_ULTIMOPAGO(HISTORICOFACTURA.COMPANIA,HISTORICOFACTURA.CODIGORUTA,HISTORICOFACTURA.FECHAEXPEDICION)
            ELSE RECAUDADOANTERIOR
       END ULTIMOPAGO,
       CASE WHEN  s$marca$s IN (4) 
            THEN 'FINANCIACIÓN' 
            ELSE 
                 CASE WHEN s$marca$s IN (3) OR HISTORICOFACTURA.ABONOACT NOT IN (0) 
                      THEN 'ABONO O PAGO PARCIAL'
                      ELSE CASE WHEN HISTORICOFACTURA.PERIODOSATRASO = 1
                                THEN 'SERVICIO PARA SUSPENSIÓN'
                                ELSE CASE WHEN HISTORICOFACTURA.PERIODOSATRASO > 1
                                          THEN 'SERVICIO PARA CORTE'
                                          ELSE ''
                                     END     
                           END  
                 END          
       END MARCADEAGUA,
       (SELECT FECHA       
          FROM SP_PAGO       
         WHERE CODIGOINTERNO  = HISTORICOFACTURA.CODIGOINTERNO 
           AND ANO = HISTORICOFACTURA.ANO 
           AND PERIODO = HISTORICOFACTURA.PERIODO)  FECHAPAGOPERPROCESO
  FROM SP_HISTORICOFACTURA HISTORICOFACTURA
       LEFT JOIN SP_HISTORIA_EXTERNA HISTORIA_EXTERNA
              ON HISTORICOFACTURA.COMPANIA       = HISTORIA_EXTERNA.COMPANIA
             AND HISTORICOFACTURA.CICLO          = HISTORIA_EXTERNA.CICLO
             AND HISTORICOFACTURA.CODIGORUTA     = HISTORIA_EXTERNA.CODIGORUTA
             AND HISTORICOFACTURA.ANO            = HISTORIA_EXTERNA.ANO
             AND HISTORICOFACTURA.PERIODO        = HISTORIA_EXTERNA.PERIODO
             AND HISTORICOFACTURA.EMPRESAASEOEXT = HISTORIA_EXTERNA.ID_EMPRESA
       INNER JOIN SP_ESTRATOS ESTRATOS
               ON HISTORICOFACTURA.COMPANIA = ESTRATOS.COMPANIA   
              AND HISTORICOFACTURA.ESTRATO  = ESTRATOS.CODIGO   
              AND HISTORICOFACTURA.USO      = ESTRATOS.USO      
       INNER JOIN SP_TARIFAS TARIFASCOSTOS
               ON HISTORICOFACTURA.COMPANIA = TARIFASCOSTOS.COMPANIA   
              AND HISTORICOFACTURA.ANO      = TARIFASCOSTOS.ANO   
              AND HISTORICOFACTURA.PERIODO  = TARIFASCOSTOS.PERIODO   
              AND HISTORICOFACTURA.USO      = TARIFASCOSTOS.USO   
              AND HISTORICOFACTURA.ESTRATO  = TARIFASCOSTOS.ESTRATO   
       INNER JOIN SP_MEDIDOR MEDIDOR
               ON  HISTORICOFACTURA.COMPANIA = MEDIDOR.COMPANIA 
              AND HISTORICOFACTURA.MEDIDOR  = MEDIDOR.CONSECUTIVO 
       LEFT JOIN (SELECT HISTORIA_CONVENIOS.COMPANIA,  
                         HISTORIA_CONVENIOS.CICLO,   
                         HISTORIA_CONVENIOS.CODIGORUTA,   
                         HISTORIA_CONVENIOS.ANO,  
                         HISTORIA_CONVENIOS.PERIODO, 
                         SUM(HISTORIA_CONVENIOS.TOTAL) TOTAL
                    FROM SP_EMPRESAS_CONVENIO EMPRESAS_CONVENIO 
                         INNER JOIN SP_HISTORIA_CONVENIOS HISTORIA_CONVENIOS 
                                 ON  EMPRESAS_CONVENIO.COMPANIA = HISTORIA_CONVENIOS.COMPANIA
                                AND EMPRESAS_CONVENIO.ID        = HISTORIA_CONVENIOS.ID_EMPRESA 
                   WHERE EMPRESAS_CONVENIO.COMPANIA   = s$compania$s
                   GROUP BY HISTORIA_CONVENIOS.COMPANIA,   
                            HISTORIA_CONVENIOS.CICLO, 
                            HISTORIA_CONVENIOS.CODIGORUTA, 
                            HISTORIA_CONVENIOS.ANO, 
                            HISTORIA_CONVENIOS.PERIODO) TOTALCONVENIOS
              ON  HISTORICOFACTURA.COMPANIA  = TOTALCONVENIOS.COMPANIA 
             AND HISTORICOFACTURA.CICLO      = TOTALCONVENIOS.CICLO 
             AND HISTORICOFACTURA.ANO        = TOTALCONVENIOS.ANO 
             AND HISTORICOFACTURA.PERIODO    = TOTALCONVENIOS.PERIODO   
             AND HISTORICOFACTURA.CODIGORUTA = TOTALCONVENIOS.CODIGORUTA  
       LEFT JOIN (SELECT SUM(CASE WHEN USO = '01' THEN 1 ELSE 0 END) AS TOTALRESIDENCIALES,
                         SUM(CASE WHEN USO NOT IN ('01') THEN 1 ELSE 0 END) AS TOTALOTROS,
                         CODIGORUTA,
                         COMPANIA
                    FROM SP_UNIDADESRESIDENCIALES
                   WHERE COMPANIA   = s$compania$s
                     AND CODIGORUTA = 's$codigoRuta$s'
                   GROUP BY CODIGORUTA, COMPANIA) UNIDADESRESIDENCIALES
              ON  HISTORICOFACTURA.COMPANIA   = UNIDADESRESIDENCIALES.COMPANIA
             AND HISTORICOFACTURA.CODIGORUTA = UNIDADESRESIDENCIALES.CODIGORUTA   
       LEFT JOIN (WITH TEMP_HISTORIA AS   
                    (SELECT HISTORIA.COMPANIA,   
                            HISTORIA.CICLO,    
                            HISTORIA.CODIGORUTA,    
                            HISTORIA.ANO,    
                            HISTORIA.PERIODO,   
                            HISTORIA.CODIGOINTERNO,   
                            CONCEPTO.CODIGO CONCEPTO,   
                            CONCEPTO.NOMBRE,   
                            CASE CONCEPTO.CODIGO   
                                WHEN 1  THEN C1   
                                WHEN 2  THEN C2    
                                WHEN 3  THEN C3   
                                WHEN 4  THEN C4  
                                WHEN 5  THEN C5  
                                WHEN 6  THEN C6  
                                WHEN 7  THEN C7   
                                WHEN 8  THEN C8   
                                WHEN 9  THEN C9   
                                WHEN 10 THEN C10  
                                WHEN 11 THEN C11  
                                WHEN 12 THEN C12  
                                WHEN 13 THEN C13   
                                WHEN 14 THEN C14   
                                WHEN 15 THEN C15  
                                WHEN 16 THEN C16   
                                WHEN 17 THEN C17  
                                WHEN 18 THEN C18   
                                WHEN 19 THEN C19   
                                WHEN 20 THEN C20   
                                WHEN 21 THEN C21  
                                WHEN 22 THEN C22  
                                WHEN 23 THEN C23  
                                WHEN 24 THEN C24  
                                WHEN 25 THEN C25   
                                WHEN 26 THEN C26   
                                WHEN 27 THEN C27  
                                WHEN 28 THEN C28  
                                WHEN 29 THEN C29  
                                WHEN 30 THEN C30  
                                WHEN 31 THEN C31   
                                WHEN 32 THEN C32   
                                WHEN 33 THEN C33   
                                WHEN 34 THEN C34   
                                WHEN 35 THEN C35   
                                WHEN 36 THEN C36   
                                WHEN 37 THEN C37   
                                WHEN 38 THEN C38   
                                WHEN 39 THEN C39  
                                WHEN 40 THEN C40   
                                WHEN 41 THEN C41  
                                WHEN 42 THEN C42  
                                WHEN 43 THEN C43   
                                WHEN 44 THEN C44   
                                WHEN 45 THEN C45  
                                WHEN 46 THEN C46  
                                WHEN 47 THEN C47  
                                WHEN 48 THEN C48  
                                WHEN 49 THEN C49   
                                WHEN 50 THEN C50   
                                WHEN 246 THEN C246  
                                WHEN 247 THEN C247  
                                WHEN 248 THEN C248  
                                WHEN 249 THEN C249  
                                WHEN 250 THEN C250  
                            END VALOR    
                       FROM SP_HISTORIA HISTORIA   
                            INNER JOIN SP_CONCEPTOS CONCEPTO   
                                    ON HISTORIA.COMPANIA = CONCEPTO.COMPANIA   
                      WHERE HISTORIA.COMPANIA   = s$compania$s   
                        AND HISTORIA.CICLO      = s$ciclo$s    
                        AND HISTORIA.CODIGORUTA = 's$codigoRuta$s'   
                        AND HISTORIA.ANO        = s$anio$s   
                        AND HISTORIA.PERIODO    = 's$periodo$s'   
                        AND (CODIGO BETWEEN 1 AND 50 OR CODIGO BETWEEN 246 AND 250))  
                    SELECT TEMP_HISTORIA.COMPANIA,
                           TEMP_HISTORIA.CICLO,
                           TEMP_HISTORIA.CODIGORUTA,
                           TEMP_HISTORIA.ANO,
                           TEMP_HISTORIA.PERIODO,
                           TEMP_HISTORIA.CONCEPTO,
                           CONCEPTOS.NOMBRE,
                           TEMP_HISTORIA.VALOR AS VALOR,
                           SUM(TEMP_HISTORIA.VALOR) VALORTOTAL
                      FROM TEMP_HISTORIA
                      INNER JOIN SP_CONCEPTOS CONCEPTOS
                              ON TEMP_HISTORIA.COMPANIA         = CONCEPTOS.COMPANIA
                             AND TEMP_HISTORIA.CONCEPTO        = CONCEPTOS.CODIGO
                     WHERE (TEMP_HISTORIA.COMPANIA   = s$compania$s
                       AND TEMP_HISTORIA.CONCEPTO    NOT IN (1,2,3,4,5,16,20,21,22,33,39,46,48)
                       AND TEMP_HISTORIA.CONCEPTO    <= 50
                       AND TEMP_HISTORIA.VALOR       NOT IN (0))
                        OR (TEMP_HISTORIA.COMPANIA   = s$compania$s
                       AND TEMP_HISTORIA.CONCEPTO    IN (246,247,248,249)
                       AND TEMP_HISTORIA.VALOR       NOT IN (0))
                       AND TEMP_HISTORIA.COMPANIA   = s$compania$s   
                       AND TEMP_HISTORIA.CICLO      = s$ciclo$s
                       AND TEMP_HISTORIA.CODIGORUTA = 's$codigoRuta$s'
                       AND TEMP_HISTORIA.ANO        = s$anio$s   
                       AND TEMP_HISTORIA.PERIODO    = 's$periodo$s'   
                     GROUP BY TEMP_HISTORIA.COMPANIA,
                              TEMP_HISTORIA.CICLO,
                              TEMP_HISTORIA.CODIGORUTA,
                              TEMP_HISTORIA.ANO,
                              TEMP_HISTORIA.PERIODO,
                              TEMP_HISTORIA.CONCEPTO,
                              CONCEPTOS.NOMBRE,
                              TEMP_HISTORIA.VALOR ) TOTALFACTURA
              ON  HISTORICOFACTURA.COMPANIA   = TOTALFACTURA.COMPANIA 
              AND HISTORICOFACTURA.ANO        = TOTALFACTURA.ANO  
              AND HISTORICOFACTURA.CICLO      = TOTALFACTURA.CICLO 
              AND HISTORICOFACTURA.PERIODO    = TOTALFACTURA.PERIODO 
              AND HISTORICOFACTURA.CODIGORUTA = TOTALFACTURA.CODIGORUTA    
                      
       INNER JOIN COMPANIA
               ON HISTORICOFACTURA.COMPANIA = COMPANIA.CODIGO
 WHERE HISTORICOFACTURA.COMPANIA   = s$compania$s   
   AND HISTORICOFACTURA.CICLO      = s$ciclo$s      
   AND HISTORICOFACTURA.CODIGORUTA = 's$codigoRuta$s'   
   AND HISTORICOFACTURA.ANO        = s$anio$s   
   AND HISTORICOFACTURA.PERIODO    = 's$periodo$s'   
   AND HISTORICOFACTURA.TOTFACTURAPERACTUAL + NVL(HISTORIA_EXTERNA.VALORASEO,0)      > s$deudaMayorA$s      
 ORDER BY HISTORICOFACTURA.CODIGORUTA
