SELECT SP_FINANCIABLESDEDEUDA.ANO, 
  SP_FINANCIABLESDEDEUDA.PERIODO, 
  SP_FINANCIABLESDEDEUDA.CICLO, 
  SP_FINANCIABLESDEDEUDA.FECHA, 
  SP_FINANCIABLESDEDEUDA.USUARIOSISTEMA, 
  SP_FINANCIABLESDEDEUDA.VRAFINANCIAR, 
  SP_FINANCIABLESDEDEUDA.ABONOINICIAL, 
  (SP_FINANCIABLESDEDEUDA.VRAFINANCIAR - nvl(SP_FINANCIABLESDEDEUDA.ABONOINICIAL,0)) AS FINACIA, 
  SP_FINANCIABLESDEDEUDA.NOCUOTAS, 
  SP_FINANCIABLESDEDEUDA.VALORCUOTA, 
  DECODE(SP_FINANCIABLESDEDEUDA.INDANULADO,0,'','X') AS INDANULADO
,
  SP_FINANCIABLESDEDEUDA.USUARIO AS CODRUTA, 
  (SP_USUARIO.PRIMERAPELLIDO || ' ' || SP_USUARIO.SEGUNDOAPELLIDO || ' ' || SP_USUARIO.NOMBRES) AS NOMBREUSUARIO, 
  SP_USUARIO.CODIGOINTERNO,  
  SP_USUARIO.DIRTECNICA, 
  SP_USUARIO.NIT, 
  CASE WHEN QRFINAL.FECHAU IS NULL THEN QRYULTIMOPAGO.FECHAPAGO ELSE QRFINAL.FECHAU END AS FECHAPAGO, 
  CASE WHEN QRFINAL.FECHAU IS NULL  THEN SUBSTR(QRYULTIMOPAGO.PER,1,4) ELSE TO_CHAR(QRFINAL.ANO) END AS ANOPAGO, 
  CASE WHEN QRFINAL.FECHAU IS NULL  THEN SUBSTR(QRYULTIMOPAGO.PER,5,2) ELSE QRFINAL.PERIODO END AS PERPAGO, 
  QRFINAL.SALDOFINANCIABLE - QRFINAL.VALORCUOTA  AS SALDOFINANCIABLE, 
  SP_FINANCIABLESDEDEUDA.NOCUOTAS-nvl(QRFINAL.NROCUOTA,0)  AS NROCUOTA 
FROM ((SP_FINANCIABLESDEDEUDA 
LEFT JOIN SP_USUARIO 
  ON  (SP_FINANCIABLESDEDEUDA.COMPANIA = SP_USUARIO.COMPANIA) 
  AND (SP_FINANCIABLESDEDEUDA.CICLO   = SP_USUARIO.CICLO) 
  AND (SP_FINANCIABLESDEDEUDA.USUARIO = SP_USUARIO.CODIGORUTA)) 
LEFT JOIN ( 
    SELECT SP_HISTORIA.COMPANIA, 
      SP_HISTORIA.CICLO, 
      SP_HISTORIA.CODIGORUTA, 
      MAX(SP_HISTORIA.ANO || SP_HISTORIA.PERIODO)  AS PER, 
      MAX(SP_HISTORIA.FECHAPAGOPERPROCESO) AS FECHAPAGO 
    FROM SP_HISTORIA 
    WHERE SP_HISTORIA.COMPANIA   ='s$compania$s' 
      s$condicionCicloQryUltimoPago$s 
      AND SP_HISTORIA.FECHAPAGOPERPROCESO IS NOT NULL 
      AND SP_HISTORIA.C12  <> 0 
      GROUP BY SP_HISTORIA.COMPANIA,SP_HISTORIA.CICLO,SP_HISTORIA.CODIGORUTA) QRYULTIMOPAGO 
  ON  (SP_FINANCIABLESDEDEUDA.COMPANIA=QRYULTIMOPAGO.COMPANIA) 
  AND (SP_FINANCIABLESDEDEUDA.CICLO  =QRYULTIMOPAGO.CICLO) 
  AND (SP_FINANCIABLESDEDEUDA.USUARIO=QRYULTIMOPAGO.CODIGORUTA) 
  AND (SP_FINANCIABLESDEDEUDA.ANO || SP_FINANCIABLESDEDEUDA.PERIODO) <=QRYULTIMOPAGO.PER) 
LEFT JOIN ( 
    SELECT SP_FINANCIABLES.COMPANIA, 
      SP_FINANCIABLES.CICLO, 
      SP_FINANCIABLES.CODIGORUTA, 
      SP_FINANCIABLES.MONTOFINANCIAR, 
      SP_FINANCIABLES.NUMEROCUOTAS AS CUOTASINI, 
      SP_FINANCIABLES.NROCUOTA, 
      SP_FINANCIABLES.SALDOFINANCIABLE, 
      SP_FINANCIABLES.ANOINICIAL,  
      SP_FINANCIABLES.PERIODOINICIAL, 
      SP_FINANCIABLES.DATE_CREATED FECHACREACION, 
      SP_FINANCIABLES.VALORCUOTA, 
      SP_USUARIO.ANO, 
      SP_USUARIO.PERIODO, 
      SP_USUARIO.FECHAPAGOPERPROCESO AS FECHAU 
    FROM SP_FINANCIABLES 
    INNER JOIN SP_USUARIO 
      ON  (SP_FINANCIABLES.COMPANIA   = SP_USUARIO.COMPANIA) 
      AND (SP_FINANCIABLES.CICLO     = SP_USUARIO.CICLO) 
      AND (SP_FINANCIABLES.CODIGORUTA= SP_USUARIO.CODIGORUTA) 
    WHERE SP_FINANCIABLES.COMPANIA ='s$compania$s' 
      s$condicionCicloQrFinal$s 
      AND SP_FINANCIABLES.CODIGORUTA BETWEEN 's$codigoInicial$s' AND 's$codigoFinal$s' 
      AND (SP_FINANCIABLES.ANOINICIAL || SP_FINANCIABLES.PERIODOINICIAL)  
      BETWEEN 's$periodoInicialCompleto$s' AND 's$periodoFinalCompleto$s' 
      AND SP_FINANCIABLES.CONCEPTO=12) QRFINAL 
  ON  (SP_FINANCIABLESDEDEUDA.COMPANIA  = QRFINAL.COMPANIA) 
  AND (SP_FINANCIABLESDEDEUDA.CICLO    = QRFINAL.CICLO) 
  AND (SP_FINANCIABLESDEDEUDA.USUARIO  = QRFINAL.CODIGORUTA) 
  AND (SP_FINANCIABLESDEDEUDA.FECHA    = QRFINAL.FECHACREACION) 
  AND (QRFINAL.MONTOFINANCIAR    =SP_FINANCIABLESDEDEUDA.VRAFINANCIAR - SP_FINANCIABLESDEDEUDA.ABONOINICIAL) 
WHERE SP_FINANCIABLESDEDEUDA.COMPANIA='s$compania$s' 
  AND SP_FINANCIABLESDEDEUDA.USUARIO BETWEEN 's$codigoInicial$s' AND 's$codigoFinal$s' 
  AND (SP_FINANCIABLESDEDEUDA.ANO || SP_FINANCIABLESDEDEUDA.PERIODO) 
  BETWEEN 's$periodoInicialCompleto$s' AND 's$periodoFinalCompleto$s' 
  s$condicionCiclo$s 
  s$condicionFiltroPor$s
