SELECT TO_CHAR(D.FECHA,'DD/MM/YYYY') FECHA,
	B.NOMBRE BANCO,
	D.CODIGORUTA,
	NVL(U.PRIMERAPELLIDO,' ') ||' '|| NVL(U.SEGUNDOAPELLIDO,' ')||' '|| NVL(U.NOMBRES,' ') NOMBREUSUARIO,
	U.BANCOPERPROCESO,
	TO_CHAR(U.FECHAPAGOPERPROCESO,'DD/MM/YYYY') FECHAPAGOPERPROCESO,
	TO_CHAR(P.HORA,'HH24:MI:SS') HORA,
	SUM(D.VALOR) VLRCONCEPTO
FROM SP_D_PAGOSDOBLES D
		INNER JOIN SP_CONCEPTOS C
			ON D.COMPANIA = C.COMPANIA 
			AND D.CONCEPTO= C.CODIGO
		INNER JOIN SP_USUARIO U
			ON D.COMPANIA  	 = U.COMPANIA
			AND D.CODIGORUTA = U.CODIGORUTA
		INNER JOIN SP_PAGO P
			ON D.COMPANIA 		= P.COMPANIA
			AND D.FECHA    		= P.FECHA
			AND D.NUMEROPAQUETE = P.NUMEROPAQUETE
			AND D.BANCO    		= P.BANCO
			AND D.CODIGORUTA 	= P.CODIGORUTA
		INNER JOIN SP_BANCOS B
			ON B.COMPANIA = D.COMPANIA
			AND B.CODIGO  = D.BANCO
WHERE D.COMPANIA 	  =s$compania$s
	AND P.OPERACION='D'
	AND D.FECHA BETWEEN s$fechaInicial$s AND s$fechaFinal$s
	AND D.BANCO BETWEEN s$bancoInicial$s AND s$bancoFinal$s
GROUP BY TO_CHAR(D.FECHA,'DD/MM/YYYY'),
	B.NOMBRE,
	D.CODIGORUTA,
	NVL(U.PRIMERAPELLIDO,' ') ||' '|| NVL(U.SEGUNDOAPELLIDO,' ')||' '|| NVL(U.NOMBRES,' '),
	U.BANCOPERPROCESO,
	TO_CHAR(U.FECHAPAGOPERPROCESO,'DD/MM/YYYY'),
	TO_CHAR(P.HORA,'HH24:MI:SS')
