SELECT D.CONCEPTO, 
	C.NOMBRE AS NOMBRECONCEPTO,
	D.VALOR AS VALORTOT,
	D.VALORACT,
	D.VALORANT,
	D.VALORACT+D.VALORANT AS VALORTOTCALC,
   	TRUNC(A.FECHA) FECHA,
	B.NOMBRE NOMBREBANCO,
  A.BANCO
FROM SP_ABONOS A
	INNER JOIN SP_D_ABONOS D
		ON A.COMPANIA 	 = D.COMPANIA
		AND A.CICLO 	 = D.CICLO
		AND A.CODIGORUTA = D.CODIGORUTA
		AND A.ANO 		 = D.ANO
		AND A.PERIODO 	 = D.PERIODO
		AND A.CONSECUTIVO= D.CONSECUTIVO
	INNER JOIN SP_CONCEPTOS C
		ON D.COMPANIA = C.COMPANIA
		AND D.CONCEPTO= C.CODIGO
	INNER JOIN SP_BANCOS B
		ON A.COMPANIA = B.COMPANIA
		AND A.BANCO   = B.CODIGO
WHERE A.COMPANIA=s$compania$s
	AND A.FECHA 		 	  BETWEEN s$fechaInicial$s AND s$fechaFinal$s
  	AND A.ANO||' '||A.PERIODO BETWEEN s$periodoInicial$s AND s$periodoFinal$s
  	AND (D.CONCEPTO   BETWEEN 1 AND 48 
		OR D.CONCEPTO BETWEEN 201 AND 207
		OR D.CONCEPTO BETWEEN 246 AND 249) 
	AND D.VALORACT+D.VALORANT<>0
