SELECT TO_CHAR(D.FECHA,'DD/MM/YYYY') FECHA,
 	B.NOMBRE BANCO,
 	D.CODIGORUTA,
 	D.CONCEPTO,
 	C.NOMBRE AS NOMBRECONCEPTO,
 	D.VALOR AS VLRCONCEPTO,
 	NVL(U.PRIMERAPELLIDO,' ') ||' '|| NVL(U.SEGUNDOAPELLIDO,' ')||' '|| NVL(U.NOMBRES,' ') NOMBREUSUARIO,
 	B1.NOMBRE BANCOPERPROCESO,
 	TO_CHAR(U.FECHAPAGOPERPROCESO,'DD/MM/YYYY') FECHAPAGOPERPROCESO
FROM SP_D_PAGOSDOBLES D
	INNER JOIN SP_CONCEPTOS C
		ON D.COMPANIA = C.COMPANIA 
		AND D.CONCEPTO= C.CODIGO
	INNER JOIN SP_USUARIO U
		ON D.COMPANIA  	 = U.COMPANIA
		AND D.CODIGORUTA = U.CODIGORUTA
	INNER JOIN SP_BANCOS B
		ON B.COMPANIA = D.COMPANIA
		AND B.CODIGO  = D.BANCO
    INNER JOIN SP_BANCOS B1
    	ON B1.COMPANIA = U.COMPANIA
    	AND B1.CODIGO  = U.BANCOPERPROCESO
WHERE D.COMPANIA=s$compania$s
	AND D.FECHA BETWEEN s$fechaInicial$s AND s$fechaFinal$s
	AND D.BANCO BETWEEN s$bancoInicial$s AND s$bancoFinal$s
