SELECT 

CONCEPTO,
SP_ORDENTRABAJO.NUMORDEN NUMORDEN
, SP_ORDENTRABAJO.CODIGORUTA
, SP_ORDENTRABAJO.COMPANIA
,SP_ORDENTRABAJO.CLASEDOC
,SP_ORDENTRABAJO.PRESENTACION
,SP_ORDENTRABAJO.OPERADOR
,SP_ORDENTRABAJO.AFORADOR
,
NVL(SP_ORDENTRABAJO.PRIMERAPELLIDO,' ')
 PRIMERAPELLIDO
,NVL(SP_ORDENTRABAJO.SEGUNDOAPELLIDO 
,' ') SEGUNDOAPELLIDO 
, NVL(SP_ORDENTRABAJO.NOMBRES,' ')
 NOMBRES
,SP_ORDENTRABAJO.DIRTECNICA DIRTECNICA
,SP_ORDENTRABAJO.TIPOREQUERIMIENTO TIPOREQUERIMIENTO
,
TRUNC(SP_ORDENTRABAJO.FECHASOLICITUD) FECHASOLICITUD
,SP_ORDENTRABAJO.HORASOLICITUD
,SP_D_ORDENTRABAJO.NUMERO
,SP_CLASEPROBLEMA.NOMBRE CLASEPROBLEMA
,SP_D_ORDENTRABAJO.PROBLEMA PROBLEMA
,SP_PROBLEMA.NOMBRE NOMBREPROBLEMA
,NVL(SP_D_ORDENTRABAJO.SOLUCION
,' ') SOLUCION
,NVL(SP_D_ORDENTRABAJO.OBSERVACIONES
,' ') OBSERVACIONES
,TRUNC(SP_D_ORDENTRABAJO.FECHASOLUCION) FECHASOLUCION
,
(CASE WHEN SP_D_ORDENTRABAJO.INDFAVOREMPRESA = 0 THEN '' ELSE 'X' END)INDFAVOREMPRESA
,SP_D_ORDENTRABAJO.VRFACTURADOANT
,SP_D_ORDENTRABAJO.NUEVOVALOR
,SP_D_ORDENTRABAJO.TOTALFACTURAANT
,SP_D_ORDENTRABAJO.TOTFACTURADO
,SP_D_ORDENTRABAJO.CONCEPTO
,(CASE WHEN SP_D_ORDENTRABAJO.FECHASOLUCION IS NULL THEN 0 ELSE PCK_SYSMAN_UTL.FC_DIASHABIL(SP_ORDENTRABAJO.COMPANIA,SP_ORDENTRABAJO.FECHASOLICITUD,NVL(SP_D_ORDENTRABAJO.FECHASOLUCION,SYSDATE))END) DIASSOLUCION
FROM SP_OrdenTrabajo INNER JOIN SP_D_OrdenTrabajo LEFT JOIN SP_ClaseProblema ON SP_D_OrdenTrabajo.CLASEPROBLEMA = SP_ClaseProblema.CLASEPROBLEMA AND SP_D_OrdenTrabajo.COMPANIA = SP_ClaseProblema.COMPANIA
LEFT JOIN SP_Problema ON SP_D_OrdenTrabajo.PROBLEMA = SP_Problema.CODIGO AND SP_D_OrdenTrabajo.CLASEPROBLEMA = SP_Problema.CLASEPROBLEMA AND SP_D_OrdenTrabajo.COMPANIA = SP_Problema.COMPANIA ON SP_OrdenTrabajo.NUMORDEN = SP_D_OrdenTrabajo.ORDENTRABAJO
AND SP_OrdenTrabajo.CLASEDOC = SP_D_OrdenTrabajo.CLASEDOC AND SP_OrdenTrabajo.COMPANIA = SP_D_OrdenTrabajo.COMPANIA
WHERE SP_ORDENTRABAJO.COMPANIA= s$compania$s AND  SP_ORDENTRABAJO.CODIGORUTA BETWEEN 's$codigoInicial$s' AND 's$codigoFinal$s'
AND SP_ORDENTRABAJO.FECHASOLICITUD BETWEEN TO_DATE('s$fechaInicial$s') AND TO_DATE('s$fechaFinal$s')
AND LPAD(SP_D_ORDENTRABAJO.CLASEPROBLEMA,3)|| SP_D_ORDENTRABAJO.PROBLEMA BETWEEN LPAD('s$claseProblemaInicial$s',3) || 's$problemaInicial$s
'
AND LPAD('s$claseProblemaFinal$s',3) || 's$problemaFinal$s'
s$ciclo$s s$presentacion$s s$claseDoc$s
 s$usuario$s
ORDER BY SP_ORDENTRABAJO.TIPOREQUERIMIENTO
