SELECT PCK_SERVICIOS_PUBLICOS.FC_NOMBREPERIODO(UN_COMPANIA => s$compania$s, UN_ANO => DEUDA.ANO, UN_PERIODO => DEUDA.PERIODO, UN_FRECUENCIA => NULL) NOMBREPERIODO,
  DEUDA.CONCEPTO,
  SUM(DEUDA.VALOR_FACTURADO) AS SUMAVALORFACTURADO,
  SUM(DEUDA.DEUDA)                       AS SUMADEUDA,
  CONCEPTOS.NOMBRE
FROM SP_D_DEUDAFACTURADAFINANCIADA DEUDA
  LEFT JOIN SP_CONCEPTOS CONCEPTOS
     ON DEUDA.COMPANIA = CONCEPTOS.COMPANIA
    AND DEUDA.CONCEPTO = CONCEPTOS.CODIGO
WHERE DEUDA.COMPANIA = s$compania$s
  AND (DEUDA.CONCEPTO BETWEEN 1 AND 49
   OR DEUDA.CONCEPTO  IN (246,247,248,249))
  AND (DEUDA.ANO || DEUDA.PERIODO) BETWEEN (s$anioInicial$s || 's$periodoInicial$s') AND (s$anioFinal$s || 's$periodoFinal$s')
 s$filtro$s
GROUP BY PCK_SERVICIOS_PUBLICOS.FC_NOMBREPERIODO(UN_COMPANIA => s$compania$s, UN_ANO => DEUDA.ANO, UN_PERIODO => DEUDA.PERIODO, UN_FRECUENCIA => NULL),
  DEUDA.CONCEPTO,
  CONCEPTOS.NOMBRE
