WITH TERCEROS AS 
(
  SELECT HISTORIA_EXTERNA.COMPANIA,
    HISTORIA_EXTERNA.FECHA_PAGO,
    HISTORIA_EXTERNA.BANCO_PAGO,
    HISTORIA_EXTERNA.PAQUETE_PAGO,
    SUM(HISTORIA_EXTERNA.VALORASEO) AS TOTALTERCERIZADO
  FROM SP_HISTORIA_EXTERNA HISTORIA_EXTERNA
  WHERE  HISTORIA_EXTERNA.COMPANIA = s$compania$s
    AND TRUNC(HISTORIA_EXTERNA.FECHA_PAGO) BETWEEN s$fechaInicial$s AND s$fechaFinal$s
  GROUP BY HISTORIA_EXTERNA.COMPANIA,
    HISTORIA_EXTERNA.FECHA_PAGO,
    HISTORIA_EXTERNA.BANCO_PAGO,
    HISTORIA_EXTERNA.PAQUETE_PAGO
  ORDER BY HISTORIA_EXTERNA.BANCO_PAGO
), RAYCO AS 
(
  SELECT HISTORIA_CONVENIOS.COMPANIA,
    HISTORIA_CONVENIOS.FECHA_PAGO,
    HISTORIA_CONVENIOS.BANCO_PAGO,
    HISTORIA_CONVENIOS.PAQUETE_PAGO,
    SUM(HISTORIA_CONVENIOS.TOTAL) AS TOTALRAYCO
  FROM SP_HISTORIA_CONVENIOS HISTORIA_CONVENIOS
  WHERE HISTORIA_CONVENIOS.COMPANIA = s$compania$s
    AND TRUNC(HISTORIA_CONVENIOS.FECHA_PAGO) BETWEEN s$fechaInicial$s AND s$fechaFinal$s
  GROUP BY HISTORIA_CONVENIOS.COMPANIA,
    HISTORIA_CONVENIOS.FECHA_PAGO,
    HISTORIA_CONVENIOS.BANCO_PAGO,
    HISTORIA_CONVENIOS.PAQUETE_PAGO
  ORDER BY HISTORIA_CONVENIOS.BANCO_PAGO
)
SELECT RECAUDOS.BANCO,
  SUM(RECAUDOS.VALORREGISTRADO)       AS VALORREGISTRADOF,
  SUM(RAYCO.TOTALRAYCO)               AS TOTALRAYCOF,
  NVL(SUM(TERCEROS.TOTALTERCERIZADO),0)      AS TOTALTERCERIZADOF,
  SUM(NVL(VALORREGISTRADO,0)   +
      NVL(TOTALTERCERIZADO,0))    AS TOTALH,
  SP_BANCOS.NOMBRE
FROM (SP_RECAUDOS RECAUDOS
  LEFT JOIN TERCEROS
     ON RECAUDOS.COMPANIA      = TERCEROS.COMPANIA
    AND RECAUDOS.FECHA         = TERCEROS.FECHA_PAGO
    AND RECAUDOS.BANCO         = TERCEROS.BANCO_PAGO
    AND RECAUDOS.NUMEROPAQUETE = TERCEROS.PAQUETE_PAGO)
  LEFT JOIN RAYCO
     ON RECAUDOS.COMPANIA      = RAYCO.COMPANIA
    AND RECAUDOS.FECHA         = RAYCO.FECHA_PAGO
    AND RECAUDOS.BANCO         = RAYCO.BANCO_PAGO
    AND RECAUDOS.NUMEROPAQUETE = RAYCO.PAQUETE_PAGO
  INNER JOIN SP_BANCOS 
     ON RECAUDOS.COMPANIA  = SP_BANCOS.COMPANIA
    AND RECAUDOS.BANCO     = SP_BANCOS.CODIGO
WHERE RECAUDOS.COMPANIA = s$compania$s
  AND TRUNC(RECAUDOS.FECHA) BETWEEN s$fechaInicial$s AND s$fechaFinal$s
GROUP BY RECAUDOS.BANCO, 
  SP_BANCOS.NOMBRE
ORDER BY RECAUDOS.BANCO
