SELECT COMPANIA, PROBLEMA, CLASEPROBLEMA, NOMBREPROBLEMA, Count(CLASEPROBLEMA)  TOTALPROBLEMAS,
Sum(CASE WHEN INDFAVOREMPRESA IS NULL THEN 0 ELSE 1 END) EMPRESA,
((Sum(CASE WHEN FECHASOLUCION IS NULL THEN 0 ELSE 1 END ))-(Sum (CASE WHEN INDFAVOREMPRESA IS NULL THEN 0 ELSE 1 END)))  USUARIO,
Sum(CASE WHEN FECHASOLUCION IS NULL THEN 0 ELSE 1 END ) SOLUCIONADOS,
(Count(CLASEPROBLEMA))-(Sum(CASE WHEN FECHASOLUCION IS NULL THEN 0 ELSE 1 END )) PENDIENTE,
Sum(DIASSOLUCION) DIASSOLUCION,
(CASE WHEN TIPOREQUERIMIENTO IS NULL THEN 'NA' ELSE TIPOREQUERIMIENTO END)TIPOREQUERIMIENTO1,  TIPOREQUERIMIENTO
FROM(
SELECT TO_CHAR(SP_ORDENTRABAJO.FECHASOLICITUD,'DD/MM/YYYY') FECHASOLICITUD, 
SP_ORDENTRABAJO.COMPANIA,
SP_CLASEPROBLEMA.NOMBRE CLASEPROBLEMA,
SP_D_ORDENTRABAJO.PROBLEMA PROBLEMA,
SP_PROBLEMA.NOMBRE NOMBREPROBLEMA,
SP_ORDENTRABAJO.TIPOREQUERIMIENTO,
SP_D_ORDENTRABAJO.INDFAVOREMPRESA,
TO_CHAR( SP_D_ORDENTRABAJO.FECHASOLUCION,'DD/MM/YYYY') FECHASOLUCION, 
(CASE WHEN SP_D_ORDENTRABAJO.FECHASOLUCION IS NULL THEN 0 ELSE PCK_SYSMAN_UTL.FC_DIASHABIL(SP_ORDENTRABAJO.COMPANIA,SP_ORDENTRABAJO.FECHASOLICITUD,NVL(SP_D_ORDENTRABAJO.FECHASOLUCION,SYSDATE))END) DIASSOLUCION
FROM SP_USUARIO INNER JOIN SP_ORDENTRABAJO INNER JOIN  SP_D_ORDENTRABAJO LEFT JOIN SP_CLASEPROBLEMA ON  SP_D_ORDENTRABAJO.CLASEPROBLEMA = SP_CLASEPROBLEMA.CLASEPROBLEMA AND  SP_D_ORDENTRABAJO.COMPANIA = SP_CLASEPROBLEMA.COMPANIA
LEFT JOIN SP_PROBLEMA ON  SP_D_ORDENTRABAJO.PROBLEMA = SP_PROBLEMA.CODIGO
AND  SP_D_ORDENTRABAJO.CLASEPROBLEMA = SP_PROBLEMA.CLASEPROBLEMA
AND  SP_D_ORDENTRABAJO.COMPANIA = SP_PROBLEMA.COMPANIA ON SP_ORDENTRABAJO.NUMORDEN =  SP_D_ORDENTRABAJO.ORDENTRABAJO
AND SP_ORDENTRABAJO.CLASEDOC =  SP_D_ORDENTRABAJO.CLASEDOC AND SP_ORDENTRABAJO.COMPANIA =  SP_D_ORDENTRABAJO.COMPANIA
ON SP_USUARIO.CODIGORUTA = SP_OrdenTrabajo.CODIGORUTA AND SP_USUARIO.CICLO = SP_OrdenTrabajo.CICLO AND SP_USUARIO.COMPANIA = SP_OrdenTrabajo.COMPANIA
WHERE SP_ORDENTRABAJO.COMPANIA= s$compania$s AND SP_ORDENTRABAJO.CODIGORUTA BETWEEN 's$codigoInicial$s' AND 's$codigoFinal$s'
AND SP_ORDENTRABAJO.FECHASOLICITUD BETWEEN TO_DATE('s$fechaInicial$s') AND TO_DATE('s$fechaFinal$s')
AND LPAD( SP_D_ORDENTRABAJO.CLASEPROBLEMA,3)||  SP_D_ORDENTRABAJO.PROBLEMA BETWEEN LPAD('s$claseProblemaInicial$s',3) || 's$problemaInicial$s'
AND LPAD('s$claseProblemaFinal$s',3) || 's$problemaFinal$s'
s$ciclo$s s$presentacion$s s$claseDoc$s s$dependencia$s
ORDER BY SP_ORDENTRABAJO.NUMORDEN)
GROUP BY COMPANIA, PROBLEMA, CLASEPROBLEMA, NOMBREPROBLEMA,TIPOREQUERIMIENTO
