WITH LISTADOFACTURACION AS(
     SELECT 
	FACTURADO.COMPANIA, 
	FACTURADO.CICLO, 
	FACTURADO.CODIGORUTA, 
	FACTURADO.ANO, 
	FACTURADO.PERIODO, 
	SUM(CASE WHEN CONCEPTO=1 THEN VALOR_FACTURADO ELSE 0 END) FIJOACUEDUCTO, 
	SUM(CASE WHEN CONCEPTO=2 THEN VALOR_FACTURADO ELSE 0 END) CONSUMOACUEDUCTO, 
	SUM(CASE WHEN CONCEPTO=5 THEN VALOR_FACTURADO ELSE 0 END) PROMEDIOACUEDUCTO, 
	SUM(CASE WHEN CONCEPTO IN (3,20,21,22,48) THEN VALOR_FACTURADO ELSE 0 END) ASEO, 
	SUM(CASE WHEN CONCEPTO=12 THEN VALOR_FACTURADO ELSE 0 END) DIFERIDO, 
	SUM(CASE WHEN CONCEPTO=17 THEN VALOR_FACTURADO ELSE 0 END) SALDOCREDITO, 
	SUM(CASE WHEN CONCEPTO=18 THEN VALOR_FACTURADO ELSE 0 END) ALUMBRADO, 
	SUM(CASE WHEN CONCEPTO IN (10,19) THEN VALOR_FACTURADO ELSE 0 END) SINMEDICION, 
	SUM(CASE WHEN CONCEPTO IN (6,7,8,9) THEN VALOR_FACTURADO ELSE 0 END) MATERIALES, 
	SUM(CASE WHEN CONCEPTO=16 THEN VALOR_FACTURADO ELSE 0 END) RECARGOSAC, 
	SUM(CASE WHEN CONCEPTO=23 THEN VALOR_FACTURADO ELSE 0 END) RECARGOSAS, 
	SUM(CASE WHEN CONCEPTO=31 THEN VALOR_FACTURADO ELSE 0 END) RECARGOSAL, 
	SUM(CASE WHEN CONCEPTO=249 THEN VALOR_FACTURADO ELSE 0 END) AJUSTES, 
	SUM(CASE WHEN CONCEPTO=250 THEN VALOR_FACTURADO ELSE 0 END) DEUDAANT, 
	SUM(CASE WHEN CONCEPTO IN (4) THEN VALOR_FACTURADO ELSE 0 END) ALCANTARILLADOFIJO, 
	SUM(CASE WHEN CONCEPTO IN (24,33) THEN VALOR_FACTURADO ELSE 0 END) ALCANTARILLADO, 
	SUM(CASE WHEN CONCEPTO IN (11,13,14,15,246) THEN VALOR_FACTURADO ELSE 0 END) OTROS, 
	SUM(CASE WHEN CONCEPTO=247 THEN VALOR_FACTURADO ELSE 0 END) SEGUNDAFECHA
    FROM SP_FACTURADO FACTURADO
	GROUP BY FACTURADO.COMPANIA, FACTURADO.CICLO, FACTURADO.CODIGORUTA, FACTURADO.ANO, FACTURADO.PERIODO
)
SELECT 
  USUARIO.CODIGORUTA,
  USUARIO.CODIGOINTERNO,
  NVL(USUARIO.PRIMERAPELLIDO,' ') ||' '|| NVL(USUARIO.SEGUNDOAPELLIDO,' ')||' '|| NVL(USUARIO.NOMBRES,' ') "NOMBRE USUARIO",
  USUARIO.DIRTECNICA "DIRECCION TECNICA",
  BARRIOS.NOMBRE BARRIO,
  USUARIO.USO,
  USUARIO.ESTRATO,
  TO_CHAR(USUARIO.LECTURA1) "LECTURA ANT",
  TO_CHAR(USUARIO.LECTURA) "LECTURA ACT",
  TO_CHAR(USUARIO.CONSUMO) "CONS ACU",
  TO_CHAR(USUARIO.CONSUMOPROM) "CONS PRO",
  LISTADOFACTURACION.FIJOACUEDUCTO "FIJO ACUED",
  LISTADOFACTURACION.CONSUMOACUEDUCTO "CONS ACUED",
  LISTADOFACTURACION.PROMEDIOACUEDUCTO  "PROM ACUED",
  LISTADOFACTURACION.ASEO,
  LISTADOFACTURACION.DIFERIDO,
  LISTADOFACTURACION.SALDOCREDITO,
  LISTADOFACTURACION.SINMEDICION,
  LISTADOFACTURACION.MATERIALES,
  LISTADOFACTURACION.RECARGOSAC,
  LISTADOFACTURACION.RECARGOSAS,
  LISTADOFACTURACION.RECARGOSAL,
  LISTADOFACTURACION.AJUSTES,
  LISTADOFACTURACION.DEUDAANT,
  LISTADOFACTURACION.ALCANTARILLADO,
  USUARIO.FECHAPAGOPERPROCESO,
  USUARIO.TOTFACTURAPERACTUAL,
  LISTADOFACTURACION.OTROS,
  TO_CHAR(ABONOS.FECHA,'DD/MM/YYYY') "FECHA ABONO",
  ABONOS.VALOR "VALOR ABONO",
  ABONOS.BANCO "BANCO ABONO",
  CASE WHEN ABONOS.VALOR>0 THEN '888' ELSE '' END "PAQUETE ABONO"
FROM SP_USUARIO USUARIO
LEFT JOIN SP_ABONOS ABONOS
	ON USUARIO.COMPANIA    = ABONOS.COMPANIA
	AND USUARIO.CICLO      = ABONOS.CICLO
	AND USUARIO.CODIGORUTA = ABONOS.CODIGORUTA
	AND USUARIO.ANO        = ABONOS.ANO
	AND USUARIO.PERIODO    = ABONOS.PERIODO
LEFT JOIN LISTADOFACTURACION
	ON USUARIO.COMPANIA    = LISTADOFACTURACION.COMPANIA
	AND USUARIO.CICLO      = LISTADOFACTURACION.CICLO
	AND USUARIO.CODIGORUTA = LISTADOFACTURACION.CODIGORUTA
	AND USUARIO.ANO        = LISTADOFACTURACION.ANO
	AND USUARIO.PERIODO    = LISTADOFACTURACION.PERIODO
LEFT JOIN BARRIOS
	ON USUARIO.BARRIO=BARRIOS.CODIGO
WHERE USUARIO.COMPANIA = s$compania$s 
s$condicion$s
AND USUARIO.CODIGORUTA BETWEEN s$codigoInicial$s AND s$codigoFinal$s
AND USUARIO.USO||USUARIO.ESTRATO BETWEEN s$usoIni$s||s$estratoIni$s AND s$usoFin$s
||s$estratoFin$s                 
AND USUARIO.BARRIO BETWEEN s$barrioIni$s AND s$barrioFin$s
s$condicionOrdenCodRuta$s 
