SELECT
 COMPONENTES_ACTIVIDADES.NOMBREACTIVIDAD ACTIVIDAD
FROM
	BP_D_NOVEDADPROYECTO
INNER JOIN COMPONENTES_ACTIVIDADES ON
	BP_D_NOVEDADPROYECTO.COMPANIA = COMPONENTES_ACTIVIDADES.COMPANIA
	AND BP_D_NOVEDADPROYECTO.PROYECTO = COMPONENTES_ACTIVIDADES.CODIGOPROYECTO
	AND BP_D_NOVEDADPROYECTO.COMPONENTE = COMPONENTES_ACTIVIDADES.COMPONENTE
	AND BP_D_NOVEDADPROYECTO.TIPOCOMPONENTE = COMPONENTES_ACTIVIDADES.TIPOCOMPONENTE
	AND BP_D_NOVEDADPROYECTO.ACTIVIDAD = COMPONENTES_ACTIVIDADES.ACTIVIDAD
WHERE
	BP_D_NOVEDADPROYECTO.COMPANIA = '$P!{PR_COMPANIA}'
	AND BP_D_NOVEDADPROYECTO.TIPOT = '$P!{PR_TIPOT}'
	AND BP_D_NOVEDADPROYECTO.CLASET = '$P!{PR_CLASET}'
	AND BP_D_NOVEDADPROYECTO.NOVEDAD = '$P!{PR_CONSECUTIVO}'
