SELECT DISTINCT 
BP_D_NOVEDADPROYECTO.COMPONENTE || ' ' || COMPONENTES.NOMBRECOMPONENTE PRODUCTO
FROM
	BP_D_NOVEDADPROYECTO
LEFT JOIN COMPONENTES ON
	BP_D_NOVEDADPROYECTO.COMPANIA = COMPONENTES.COMPANIA
	AND BP_D_NOVEDADPROYECTO.PROYECTO = COMPONENTES.CODIGOPROYECTO
	AND BP_D_NOVEDADPROYECTO.COMPONENTE = COMPONENTES.CODIGO
WHERE
	BP_D_NOVEDADPROYECTO.COMPANIA = '$P!{PR_COMPANIA}'
	AND BP_D_NOVEDADPROYECTO.TIPOT = '$P!{PR_TIPOT}'
	AND BP_D_NOVEDADPROYECTO.CLASET = '$P!{PR_CLASET}'
	AND BP_D_NOVEDADPROYECTO.NOVEDAD = '$P!{PR_CONSECUTIVO}'