SELECT PROYECTOS.CODIGOBPIM, 
  PROYECTOS.NOMBREPROYECTO, 
  PROYECTOS.VALORTOTAL, 
  PROYECTOS.VALORPROGRAMADO, 
  PROYECTOS.VALORSOLICITADO, 
  PROYECTOS.VALOREJECUTADO, 
  CASE WHEN VALORPROGRAMADO=0 THEN 0 ELSE VALOREJECUTADO/VALORPROGRAMADO END AVANCE
FROM PROYECTOS
WHERE PROYECTOS.COMPANIA=s$compania$s
AND PROYECTOS.CODIGO BETWEEN 's$proyectoInicial$s' AND 's$proyectoFin$s'
