MERGE INTO CONSULTAS FIN USING (SELECT '000180RPTPROYECTOSSECTORES' INFORME ,TO_CLOB(q'[SELECT PROYECTOS.COMPANIA, 
	PROYECTOS.CODIGO, 
	PROYECTOS.CODIGOBPIM, 
	PROYECTOS.NOMBREPROYECTO, 
	PROYECTOS.OBJETO OBJETOPROYECTO, 
	PROYECTOS.VALORSOLICITADO, 
	PROYECTOS.VALORTOTAL,
	PROYECTOS.VALOREJECUTADO,
	PROYECTOS.CODIGO||BP_PROYECTOSRUBROS.DIMENSION||BP_PROYECTOSRUBROS.SECTOR||BP_PROYECTOSRUBROS.PROGRAMA||BP_PROYECTOSRUBROS.SUBPROGRAMA AGRUP,
	DEPENDENCIA.NOMBRE NOMBRESECRETARIA,
	BP_PROYECTOSRUBROS.DIMENSION DIMENSION_ID, 
	PLAN_PRESUPUESTAL.NOMBRE NOMBREDIMENSION, 
	BP_PROYECTOSRUBROS.SECTOR SECTOR_ID, 
	PLAN_PRESUPUESTAL_1.NOMBRE NOMBRESECTOR, 
	BP_PROYECTOSRUBROS.PROGRAMA PROGRAMA_ID, 
	PLAN_PRESUPUESTAL_2.NOMBRE NOMBREPROGRAMA, 
	BP_PROYECTOSRUBROS.SUBPROGRAMA SUBPROGRAMA_ID, 
	PLAN_PRESUPUESTAL_3.NOMBRE NOMBRESUBPROGRAMA,
	FUENTE_RECURSOS.NOMBRE NOMBREFUENTERECURSOS
FROM PROYECTOS 
	INNER JOIN DEPENDENCIA 
		ON PROYECTOS.COMPANIA = DEPENDENCIA.COMPANIA
		AND PROYECTOS.DEPENDENCIA = DEPENDENCIA.CODIGO
	INNER JOIN BP_PROYECTOSRUBROS
		ON PROYECTOS.COMPANIA = BP_PROYECTOSRUBROS.COMPANIA
		AND PROYECTOS.CODIGO = BP_PROYECTOSRUBROS.PROYECTO
        INNER JOIN PLAN_PRESUPUESTAL PLAN_PRESUPUESTAL 
		ON BP_PROYECTOSRUBROS.COMPANIA = PLAN_PRESUPUESTAL.COMPANIA
		AND BP_PROYECTOSRUBROS.DIMENSION = PLAN_PRESUPUESTAL.CODIGO
		AND BP_PROYECTOSRUBROS.VIGENCIA = PLAN_PRESUPUESTAL.ANO
	INNER JOIN PLAN_PRESUPUESTAL PLAN_PRESUPUESTAL_1 
		ON BP_PROYECTOSRUBROS.COMPANIA = PLAN_PRESUPUESTAL_1.COMPANIA
		AND BP_PROYECTOSRUBROS.SECTOR = PLAN_PRESUPUESTAL_1.CODIGO
		AND BP_PROYECTOSRUBROS.VIGENCIA = PLAN_PRESUPUESTAL_1.ANO
	INNER JOIN PLAN_PRESUPUESTAL PLAN_PRESUPUESTAL_2 
		ON BP_PROYECTOSRUBROS.COMPANIA = PLAN_PRESUPUESTAL_2.COMPANIA
		AND BP_PROYECTOSRUBROS.PROGRAMA = PLAN_PRESUPUESTAL_2.CODIGO
		AND BP_PROYECTOSRUBROS.VIGENCIA = PLAN_PRESUPUESTAL_2.ANO
	INNER JOIN PLAN_PRESUPUESTAL PLAN_PRESUPUESTAL_3 
		ON BP_PROYECTOSRUBROS.COMPANIA = PLAN_PRESUPUESTAL_3.COMPANIA
		AND BP_PROYECTOSRUBROS.SUBPROGRAMA = PLAN_PRESUPUESTAL_3.CODIGO
		AND BP_PROYECTOSRUBROS.VIGENCIA = PLAN_PRESUPUESTAL_3.ANO
	INNER JOIN FUENTE_RECURSOS 
		ON BP_PROYECTOSRUBROS.COMPANIA = FUENTE_RECURSOS.COMPANIA
		AND BP_PROYECTOSRUBROS.FUENTERECURSOSRUBRO = FUENTE_RECURSOS.CODIGO
		AND BP_PROYECTOSRUBROS.VIGENCIA = FUENTE_RECURSOS.ANO
WHERE PROYECTOS.COMPANIA	=s$compania$s
	AND PROYECTOS.CODIGO BETWEEN 's$proyectoInicial$s' AND 's$proyectoFin$s'
	AND BP_PROYECTOSRUBROS.DIMENSION			= CASE WHEN 's$dimension$s' = 'TODOS' THEN BP_PROYECTOSRUBROS.DIMENSION ELSE 's$dimension$s' END
	AND BP_PROYECTOSRUBROS.SECTOR				= CASE WHEN 's$sector$s' = 'TODOS' THEN BP_PROYECTOSRUBROS.SECTOR ELSE 's$sector$s' END
	AND BP_PROYECTOSRUBROS.PROGRAMA				= CASE WHEN 's$programa$s' = 'TODOS' THEN BP_PROYECTOSRUBROS.PROGRAMA ELSE 's$programa$s' END
	AND BP_PROYECTOSRUBROS.SUBPROGRAMA			= CASE WHEN 's$subprograma$s' = 'TODOS' THEN BP_PROYECTOSRUBROS.SUBPROGRAMA ELSE 's$subprograma$s' END
	AND PROYECTOS.DEPENDENCIA	= CASE WHEN 's$dependencia$s' = 'TODAS' THEN ]') || TO_CLOB(q'[PROYECTOS.DEPENDENCIA ELSE 's$dependencia$s' END
  ORDER BY PROYECTOS.CODIGO,BP_PROYECTOSRUBROS.DIMENSION,BP_PROYECTOSRUBROS.SECTOR,BP_PROYECTOSRUBROS.PROGRAMA,BP_PROYECTOSRUBROS.SUBPROGRAMA]') CONSULTA, 52 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);