SELECT 
COMPONENTES.NOMBRECOMPONENTE COMPONENTE,
BP_ACTIVIDADES.NOMBRE ACTIVIDAD,
BP_ACTIVIDADES.CODIGO CODACTIVIDAD,
CASE WHEN SUM(CASE WHEN PROGRAMACION.TIPOESTADO IN ('P','R') THEN PROGRAMACION.CANTIDAD ELSE 0 END)=0 THEN 0 ELSE BP_D_NOVEDADPROYECTO.CANTIDAD/SUM(CASE WHEN PROGRAMACION.TIPOESTADO IN ('P','R') THEN PROGRAMACION.CANTIDAD ELSE 0 END) END AVANCE_FISICO,
SUM(CASE WHEN PROGRAMACION.TIPOESTADO IN ('P','R') THEN PROGRAMACION.VALORTOTAL ELSE 0 END) VALORPROGRAMADO,
COMPONENTES_ACTIVIDADES.VALOREJECUTADO,
CASE WHEN SUM(CASE WHEN PROGRAMACION.TIPOESTADO IN ('P','R') THEN PROGRAMACION.VALORTOTAL ELSE 0 END)=0 THEN 0 ELSE PROYECTOS.VALOREJECUTADO/SUM(CASE WHEN PROGRAMACION.TIPOESTADO IN ('P','R') THEN PROGRAMACION.VALORTOTAL ELSE 0 END) END AVANCE_PESOS1,
BP_PLAN_INDICATIVO.ID,
BP_PLAN_INDICATIVO.DESCRIPCION, 
BP_D_NOVEDADPROYECTO.ESPECIFICACION,
PROYECTOS.NOMBREPROYECTO,
PROYECTOS.CODIGOBPIM, 
BP_D_NOVEDADPROYECTO.PROYECTO,
PROYECTOS.OBJETO 
FROM BP_D_NOVEDADPROYECTO 
	INNER JOIN BPNOVEDADPROYECTO 
		ON BP_D_NOVEDADPROYECTO.COMPANIA = BPNOVEDADPROYECTO.COMPANIA
		AND BP_D_NOVEDADPROYECTO.TIPOT = BPNOVEDADPROYECTO.TIPOT
		AND BP_D_NOVEDADPROYECTO.CLASET = BPNOVEDADPROYECTO.CLASET
		AND BP_D_NOVEDADPROYECTO.NOVEDAD = BPNOVEDADPROYECTO.CODIGO 
		AND BP_D_NOVEDADPROYECTO.DEPENDENCIA = BPNOVEDADPROYECTO.DEPENDENCIA
	INNER JOIN PROYECTOS 
		ON BP_D_NOVEDADPROYECTO.COMPANIA = PROYECTOS.COMPANIA
		AND BP_D_NOVEDADPROYECTO.PROYECTO = PROYECTOS.CODIGO 
	LEFT JOIN COMPONENTES_ACTIVIDADES 
		ON BP_D_NOVEDADPROYECTO.COMPANIA = COMPONENTES_ACTIVIDADES.COMPANIA
		AND BP_D_NOVEDADPROYECTO.PROYECTO = COMPONENTES_ACTIVIDADES.CODIGOPROYECTO
		AND BP_D_NOVEDADPROYECTO.COMPONENTE = COMPONENTES_ACTIVIDADES.COMPONENTE
		AND BP_D_NOVEDADPROYECTO.TIPOCOMPONENTE = COMPONENTES_ACTIVIDADES.TIPOCOMPONENTE
		AND BP_D_NOVEDADPROYECTO.ACTIVIDAD = COMPONENTES_ACTIVIDADES.ACTIVIDAD
	LEFT JOIN COMPONENTES 
		ON COMPONENTES_ACTIVIDADES.COMPANIA = COMPONENTES.COMPANIA
		AND COMPONENTES_ACTIVIDADES.CODIGOPROYECTO = COMPONENTES.CODIGOPROYECTO
		AND COMPONENTES_ACTIVIDADES.COMPONENTE = COMPONENTES.CODIGO
		AND COMPONENTES_ACTIVIDADES.TIPOCOMPONENTE = COMPONENTES.TIPOCOMPONENTE
	LEFT JOIN BP_ACTIVIDADES 
		ON COMPONENTES_ACTIVIDADES.COMPANIA = BP_ACTIVIDADES.COMPANIA
		AND COMPONENTES_ACTIVIDADES.ACTIVIDAD = BP_ACTIVIDADES.CODIGO
	LEFT JOIN BP_PLAN_INDICATIVO 
		ON BP_D_NOVEDADPROYECTO.COMPANIA = BP_PLAN_INDICATIVO.COMPANIA
		AND BP_D_NOVEDADPROYECTO.ID_META_PRODUCTO = BP_PLAN_INDICATIVO.ID
		AND BP_D_NOVEDADPROYECTO.VIGENCIA_PLAN_INDICATIVO = BP_PLAN_INDICATIVO.VIGENCIA_INICIAL
	LEFT JOIN PROGRAMACION 
		ON COMPONENTES_ACTIVIDADES.COMPANIA = PROGRAMACION.COMPANIA
		AND COMPONENTES_ACTIVIDADES.CODIGOPROYECTO = PROGRAMACION.CODIGOPROYECTO
		AND COMPONENTES_ACTIVIDADES.COMPONENTE = PROGRAMACION.CODIGOCOMPONENTE
		AND COMPONENTES_ACTIVIDADES.TIPOCOMPONENTE = PROGRAMACION.TIPOCOMPONENTE
		AND COMPONENTES_ACTIVIDADES.ACTIVIDAD = PROGRAMACION.CODIGOACTIVIDAD
WHERE PROYECTOS.COMPANIA=s$compania$s
	AND BP_D_NOVEDADPROYECTO.PROYECTO BETWEEN 's$proyectoInicial$s' AND 's$proyectoFin$s'
	AND BP_D_NOVEDADPROYECTO.TIPOT = 's$novedad$s'  
	AND BP_D_NOVEDADPROYECTO.CLASET = 'B'
	AND BPNOVEDADPROYECTO.ESTADO IN ('V','AP')
	AND BPNOVEDADPROYECTO.VOBOBP<>0
GROUP BY COMPONENTES.NOMBRECOMPONENTE, BP_ACTIVIDADES.NOMBRE, BP_D_NOVEDADPROYECTO.CANTIDAD, PROGRAMACION.TIPOESTADO, COMPONENTES_ACTIVIDADES.VALOREJECUTADO, BP_PLAN_INDICATIVO.ID, 
BP_PLAN_INDICATIVO.DESCRIPCION, BP_D_NOVEDADPROYECTO.ESPECIFICACION, PROYECTOS.NOMBREPROYECTO, PROYECTOS.CODIGOBPIM, BP_D_NOVEDADPROYECTO.PROYECTO, PROYECTOS.VALOREJECUTADO,
PROYECTOS.OBJETO,BP_ACTIVIDADES.CODIGO