WITH TMP_QRYPROGACTIVIDADES AS (SELECT COMPONENTES.COMPANIA, 
    COMPONENTES.CODIGOPROYECTO, 
    COMPONENTES.NOMBRECOMPONENTE, 
    COMPONENTES_ACTIVIDADES.ACTIVIDAD, 
    COMPONENTES.UNIDAD, 
    COMPONENTES.CANTIDAD, 
    PROGRAMACION.VALORTOTAL, 
    COMPONENTES_ACTIVIDADES.COMPONENTE, 
    SUM(CASE WHEN PROGRAMACION.TIPOESTADO='P' OR PROGRAMACION.TIPOESTADO='RP' THEN VALOR1 ELSE 0 END) ENEMAR, 
    SUM(CASE WHEN PROGRAMACION.TIPOESTADO='P' OR PROGRAMACION.TIPOESTADO='RP' THEN VALOR2 ELSE 0 END) ABRMAY, 
    SUM(CASE WHEN PROGRAMACION.TIPOESTADO='P' OR PROGRAMACION.TIPOESTADO='RP' THEN VALOR3 ELSE 0 END) JULSEP, 
    SUM(CASE WHEN PROGRAMACION.TIPOESTADO='P' OR PROGRAMACION.TIPOESTADO='RP' THEN VALOR4 ELSE 0 END) OCTDIC, 
    PROGRAMACION.FECHA,
    PROGRAMACION.TIPOESTADO, 
    PROGRAMACION.VIGENCIA,
    CASE WHEN 's$vigencia$s'='TODAS' THEN 's$vigencia$s' ELSE TO_CHAR(COMPONENTES.VIGENCIA) END V, 
    CASE WHEN COMPONENTES_ACTIVIDADES.DESCRIPCION IS NULL THEN COMPONENTES_ACTIVIDADES.NOMBREACTIVIDAD ELSE COMPONENTES_ACTIVIDADES.DESCRIPCION END NOMBREACTIVIDAD1, 
    CASE WHEN PROGRAMACION.TIPOESTADO='E' THEN VALOR1 ELSE 0 END ENEMAR_E1, 
    CASE WHEN PROGRAMACION.TIPOESTADO='E' THEN VALOR2 ELSE 0 END ABRMAY_E1, 
    CASE WHEN PROGRAMACION.TIPOESTADO='E' THEN VALOR3 ELSE 0 END JULSEP_E1, 
    CASE WHEN PROGRAMACION.TIPOESTADO='E' THEN VALOR4 ELSE 0 END OCTDIC_E1, 
    NVL(COMPONENTES.VALORTOTALSOLICITADO,0) VALORTOTALSOLICITADO1, 
    NVL(COMPONENTES.VALORTOTAL,0) - NVL(COMPONENTES.VALORTOTALSOLICITADO,0) SALDO, 
    PROGRAMACION.VALORTOTAL VALORTOTAL_P
    FROM (COMPONENTES 
		LEFT JOIN COMPONENTES_ACTIVIDADES ON (COMPONENTES.COMPANIA = COMPONENTES_ACTIVIDADES.COMPANIA) 
            AND (COMPONENTES.CODIGOPROYECTO = COMPONENTES_ACTIVIDADES.CODIGOPROYECTO) 
            AND (COMPONENTES.CODIGO = COMPONENTES_ACTIVIDADES.COMPONENTE) 
            AND (COMPONENTES.TIPOCOMPONENTE = COMPONENTES_ACTIVIDADES.TIPOCOMPONENTE) 
            AND (COMPONENTES.VIGENCIA = COMPONENTES_ACTIVIDADES.VIGENCIA)) 
        LEFT JOIN PROGRAMACION ON (COMPONENTES_ACTIVIDADES.COMPANIA = PROGRAMACION.COMPANIA) 
            AND (COMPONENTES_ACTIVIDADES.CODIGOPROYECTO = PROGRAMACION.CODIGOPROYECTO) 
            AND (COMPONENTES_ACTIVIDADES.COMPONENTE = PROGRAMACION.CODIGOCOMPONENTE) 
            AND (COMPONENTES_ACTIVIDADES.TIPOCOMPONENTE = PROGRAMACION.TIPOCOMPONENTE) 
            AND (COMPONENTES_ACTIVIDADES.ACTIVIDAD = PROGRAMACION.CODIGOACTIVIDAD) 
            AND (COMPONENTES_ACTIVIDADES.VIGENCIA = PROGRAMACION.VIGENCIA)
    WHERE COMPONENTES.COMPANIA=s$compania$s 
        AND (CASE WHEN 's$vigencia$s'='TODAS' THEN 's$vigencia$s' ELSE TO_CHAR(NVL(COMPONENTES.VIGENCIA,'')) END )='s$vigencia$s'  
        AND (COMPONENTES.CODIGOPROYECTO BETWEEN 's$proyectoInicial$s' AND 's$proyectoFin$s')
		AND PROGRAMACION.TIPOESTADO='P'
    GROUP BY COMPONENTES.COMPANIA, COMPONENTES.CODIGOPROYECTO, COMPONENTES.NOMBRECOMPONENTE, COMPONENTES_ACTIVIDADES.ACTIVIDAD, 
             COMPONENTES.UNIDAD, COMPONENTES.CANTIDAD, PROGRAMACION.VALORTOTAL, COMPONENTES_ACTIVIDADES.COMPONENTE, PROGRAMACION.FECHA, 
             PROGRAMACION.CODIGOPROYECTO, PROGRAMACION.TIPOESTADO, PROGRAMACION.VIGENCIA, 
             COMPONENTES.VIGENCIA, 
             COMPONENTES_ACTIVIDADES.NOMBREACTIVIDAD, 
			 COMPONENTES_ACTIVIDADES.DESCRIPCION, 
		CASE WHEN PROGRAMACION.TIPOESTADO='E' THEN VALOR1 ELSE 0 END, 
		CASE WHEN PROGRAMACION.TIPOESTADO='E' THEN VALOR2 ELSE 0 END, 
		CASE WHEN PROGRAMACION.TIPOESTADO='E' THEN VALOR3 ELSE 0 END, 
		CASE WHEN PROGRAMACION.TIPOESTADO='E' THEN VALOR4 ELSE 0 END, 
		COMPONENTES.VALORTOTALSOLICITADO, 
		COMPONENTES.VALORTOTAL,
		COMPONENTES.VALORTOTALSOLICITADO, 
		PROGRAMACION.VALORTOTAL) SELECT 
    TMP_QRYPROGACTIVIDADES.COMPANIA, 
    TMP_QRYPROGACTIVIDADES.COMPONENTE, 
    TMP_QRYPROGACTIVIDADES.NOMBRECOMPONENTE, 
    TMP_QRYPROGACTIVIDADES.ACTIVIDAD, 
    TMP_QRYPROGACTIVIDADES.UNIDAD, 
    SUM(TMP_QRYPROGACTIVIDADES.CANTIDAD)  CANTIDAD, 
    SUM(TMP_QRYPROGACTIVIDADES.VALORTOTAL)  VALORTOTAL, 
    SUM(ENEMAR)  ENEMAR1, 
    SUM(ABRMAY)  ABRMAY1, 
    SUM(JULSEP)  JULSEP1, 
    SUM(OCTDIC)  OCTDIC1, 
    TMP_QRYPROGACTIVIDADES.CODIGOPROYECTO  CODIGOPROYECTO, 
    TMP_QRYPROGACTIVIDADES.VIGENCIA, 
    TMP_QRYPROGACTIVIDADES.V, 
    TMP_QRYPROGACTIVIDADES.NOMBREACTIVIDAD1, 
    SUM(ENEMAR_E1)  ENEMAR_E1_1, 
    SUM(ABRMAY_E1)  ABRMAY_E1_1, 
    SUM(JULSEP_E1)  JULSEP_E1_1, 
    SUM(OCTDIC_E1)  OCTDIC_E1_1, 
    SUM(VALORTOTALSOLICITADO1)  VALORTOTALSOLICITADO1_1, 
    SUM(TMP_QRYPROGACTIVIDADES.SALDO)  SALDO, 
    SUM(VALORTOTAL_P)  VALORTOTAL_P1 
FROM 
    TMP_QRYPROGACTIVIDADES 
WHERE TMP_QRYPROGACTIVIDADES.COMPANIA=$P{PR_COMPANIA}
    AND TMP_QRYPROGACTIVIDADES.CODIGOPROYECTO=$P{PR_CODIGOPROYECTO}
    AND TMP_QRYPROGACTIVIDADES.V=$P{PR_V}
GROUP BY 
    TMP_QRYPROGACTIVIDADES.COMPANIA, 
    TMP_QRYPROGACTIVIDADES.COMPONENTE, 
    TMP_QRYPROGACTIVIDADES.NOMBRECOMPONENTE, 
    TMP_QRYPROGACTIVIDADES.ACTIVIDAD, 
    TMP_QRYPROGACTIVIDADES.UNIDAD, 
    TMP_QRYPROGACTIVIDADES.COMPONENTE, 
    TMP_QRYPROGACTIVIDADES.VIGENCIA, 
    TMP_QRYPROGACTIVIDADES.V, 
    TMP_QRYPROGACTIVIDADES.NOMBREACTIVIDAD1,
    TMP_QRYPROGACTIVIDADES.CODIGOPROYECTO
