SELECT 
   PROYECTOS.CODIGO
  ,PROYECTOS.NOMBREPROYECTO
  ,PROGRAMACION.COMPANIA
  ,PROGRAMACION.CODIGOPROYECTO
  ,PROGRAMACION.TIPOESTADO
  ,PROGRAMACION.CODIGOCOMPONENTE
  ,COMPONENTES.NOMBRECOMPONENTE
  ,PROGRAMACION.CODIGOACTIVIDAD
  ,BP_ACTIVIDADES.NOMBRE NOMBREACTIVIDAD
  ,PROGRAMACION.VIGENCIA
  ,PROGRAMACION.FECHA
  ,PROGRAMACION.TIPOT_QUEAPRUEBA
  ,PROGRAMACION.CLASET_QUEAPRUEBA
  ,PROGRAMACION.CODIGO_QUEAPRUEBA
  ,PROGRAMACION.DEPENDENCIA_QUEAPRUEBA
  ,PROGRAMACION.CODIGOITEM_QUEAPRUEBA
  ,PROGRAMACION.VALORTOTAL 
FROM PROYECTOS 
  INNER JOIN PROGRAMACION 
     ON PROYECTOS.COMPANIA = PROGRAMACION.COMPANIA 
    AND PROYECTOS.CODIGO   = PROGRAMACION.CODIGOPROYECTO 
  INNER JOIN BP_ACTIVIDADES 
     ON PROGRAMACION.COMPANIA        = BP_ACTIVIDADES.COMPANIA 
    AND PROGRAMACION.CODIGOACTIVIDAD = BP_ACTIVIDADES.CODIGO 
  INNER JOIN COMPONENTES 
     ON PROGRAMACION.COMPANIA         = COMPONENTES.COMPANIA 
    AND PROGRAMACION.CODIGOPROYECTO   = COMPONENTES.CODIGOPROYECTO 
    AND PROGRAMACION.CODIGOCOMPONENTE = COMPONENTES.CODIGO 
    AND PROGRAMACION.TIPOCOMPONENTE   = COMPONENTES.TIPOCOMPONENTE 
WHERE PROYECTOS.COMPANIA = s$compania$s 
  AND PROGRAMACION.CODIGOPROYECTO BETWEEN s$proyInicial$s AND s$proyFinal$s
  AND PROGRAMACION.TIPOESTADO IN('E')
  AND PROGRAMACION.VIGENCIA       BETWEEN s$anioInicial$s AND s$anioFinal$s
