WITH FUENTES_FINANCIACION_TOTAL AS (
SELECT BP_PROYFUENTESFINANCIACION.COMPANIA, 
  BP_PROYFUENTESFINANCIACION.PROYECTO, 
  BP_PROYFUENTESFINANCIACION.VIGENCIAFUENTE, 
  SUM(CASE WHEN NVL(BP_PROYFUENTESFINANCIACION.CODIGOFUENTE,'')='007' THEN VALOR ELSE 0 END) NACION, 
  SUM(CASE WHEN NVL(BP_PROYFUENTESFINANCIACION.CODIGOFUENTE,'')='009' THEN VALOR ELSE 0 END) MUNICIPIO, 
  SUM(CASE WHEN NVL(BP_PROYFUENTESFINANCIACION.CODIGOFUENTE,'')='008' THEN VALOR ELSE 0 END) DPTO, 
  SUM(CASE WHEN NVL(BP_PROYFUENTESFINANCIACION.CODIGOFUENTE,'')<>'008' 
      AND NVL(BP_PROYFUENTESFINANCIACION.CODIGOFUENTE,'')<>'009' 
        AND NVL(BP_PROYFUENTESFINANCIACION.CODIGOFUENTE,'')<>'011' 
          AND NVL(BP_PROYFUENTESFINANCIACION.CODIGOFUENTE,'')<>'007' THEN VALOR ELSE 0 END) OTROS,
  CASE WHEN 's$vigencia$s'='TODOS' THEN 's$vigencia$s' ELSE TO_CHAR(BP_PROYFUENTESFINANCIACION.VIGENCIAFUENTE) END RTA
FROM BP_PROYFUENTESFINANCIACION
WHERE COMPANIA = s$compania$s
GROUP BY BP_PROYFUENTESFINANCIACION.COMPANIA, 
  BP_PROYFUENTESFINANCIACION.PROYECTO, 
  BP_PROYFUENTESFINANCIACION.VIGENCIAFUENTE,
  CASE WHEN 's$vigencia$s'='TODOS' THEN 's$vigencia$s' ELSE TO_CHAR(BP_PROYFUENTESFINANCIACION.VIGENCIAFUENTE) END 
ORDER BY BP_PROYFUENTESFINANCIACION.PROYECTO,
SUM(CASE WHEN NVL(BP_PROYFUENTESFINANCIACION.CODIGOFUENTE,'')='007' THEN VALOR ELSE 0 END) DESC, 
  SUM(CASE WHEN NVL(BP_PROYFUENTESFINANCIACION.CODIGOFUENTE,'')='009' THEN VALOR ELSE 0 END) DESC, 
  SUM(CASE WHEN NVL(BP_PROYFUENTESFINANCIACION.CODIGOFUENTE,'')='008' THEN VALOR ELSE 0 END) DESC, 
  SUM(CASE WHEN NVL(BP_PROYFUENTESFINANCIACION.CODIGOFUENTE,'')<>'008' 
      AND NVL(BP_PROYFUENTESFINANCIACION.CODIGOFUENTE,'')<>'009' 
        AND NVL(BP_PROYFUENTESFINANCIACION.CODIGOFUENTE,'')<>'011' 
          AND NVL(BP_PROYFUENTESFINANCIACION.CODIGOFUENTE,'')<>'007' THEN VALOR ELSE 0 END) DESC
)
SELECT PROYECTOS.COMPANIA, 
  PROYECTOS.CODIGO, 
  CASE WHEN 's$dependencia$s' = 'X' THEN 's$dependencia$s' ELSE PROYECTOS.DEPENDENCIA END DEP, 
  CASE WHEN 's$estadoActual$s' = 'X' THEN 's$estadoActual$s' ELSE PROYECTOS.ESTADOACTUAL END ESTADO, 
  CASE 's$enviado$s' WHEN '1' THEN ENVIADONACION WHEN '2' THEN ENVIADODPTO WHEN '3' THEN ENVIADOOTRAENTIDAD WHEN 'X' THEN -1+NVL(PROYECTOS.ENVIADONACION,0)+NVL(PROYECTOS.ENVIADODPTO,0)+NVL(PROYECTOS.ENVIADOOTRAENTIDAD,0) ELSE 0 END ENVIADO1, 
  CASE PROYECTOS.ESTADOACTUAL WHEN 'E' THEN 'Ejecución' WHEN 'S' THEN 'Sin ejecutar' WHEN 'P' THEN 'Ejecutado parcialmente' WHEN  'T' THEN 'Ejecutado' WHEN 'X' THEN 'Todos' ELSE 'Sin estado'END ESTADOACTUAL, 
  PROYECTOS.VIGENCIAINICIO, 
  PROYECTOS.VIGENCIAFIN, 
  PROYECTOS.FECHAREGISTRO, 
  PROYECTOS.CODIGOBPIM, 
  PROYECTOS.NOMBREPROYECTO, 
  NVL(PROYECTOS.VALORTOTAL,0) VALORTOTAL_1, 
  PROYECTOS.VALORANNO1, 
  PROYECTOS.VALORANNO2, 
  PROYECTOS.VALORANNO3, 
  PROYECTOS.VALORANNO4, 
  PROYECTOS.PORCEJECUCION, 
  TERCERO.NOMBRE NOMBRE_RESPONSABLE, 
  DEPENDENCIA.NOMBRE NOMBRE_DEPENDENCIA, 
  SUM(FUENTES_FINANCIACION_TOTAL.NACION) NACION, 
  SUM(FUENTES_FINANCIACION_TOTAL.MUNICIPIO) MUNICIPIO,
  SUM(FUENTES_FINANCIACION_TOTAL.DPTO) DPTO, 
  SUM(FUENTES_FINANCIACION_TOTAL.OTROS) OTROS, 
  CASE WHEN 's$vigencia$s'='TODOS' THEN 's$vigencia$s' ELSE TO_CHAR(FUENTES_FINANCIACION_TOTAL.VIGENCIAFUENTE) END VV, 
  PROYECTOS.OTRAENTIDAD,
  SUM(CASE 's$enviado$s' WHEN '1' THEN NACION WHEN '2' THEN  DPTO WHEN '3' THEN OTROS WHEN 'X' THEN NACION+MUNICIPIO+DPTO+OTROS END) VALOR_FIANCIADO, 
  CASE 's$enviado$s' WHEN '1' THEN FECHAENVIONACION WHEN '2' THEN FECHAENVIODPTO WHEN '3' THEN FECHAENVIOOTRAENTIDAD WHEN 'X' THEN '01/01/9999' END FECHA_ENVIO, 
  CASE 's$enviado$s' WHEN '1' THEN ESTADONACION WHEN '2' THEN ESTADODPTO WHEN '3' THEN ESTADOOTRAENTIDAD WHEN 'X' THEN 0 END ESTADO_ENVIO
FROM PROYECTOS 
	LEFT JOIN RESPONSABLE ON PROYECTOS.COMPANIA = RESPONSABLE.COMPANIA
		AND PROYECTOS.RESPONSABLE = RESPONSABLE.CEDULA
		AND PROYECTOS.SUCURSAL = RESPONSABLE.SUCURSAL
	INNER JOIN TERCERO ON RESPONSABLE.COMPANIA = TERCERO.COMPANIA
		AND RESPONSABLE.CEDULA = TERCERO.NIT
		AND RESPONSABLE.SUCURSAL = TERCERO.SUCURSAL
  LEFT JOIN DEPENDENCIA ON PROYECTOS.COMPANIA = DEPENDENCIA.COMPANIA
		AND PROYECTOS.DEPENDENCIA = DEPENDENCIA.CODIGO
  LEFT JOIN FUENTES_FINANCIACION_TOTAL ON PROYECTOS.COMPANIA = FUENTES_FINANCIACION_TOTAL.COMPANIA
    AND PROYECTOS.CODIGO = FUENTES_FINANCIACION_TOTAL.PROYECTO
WHERE PROYECTOS.COMPANIA=s$compania$s
	AND PROYECTOS.DEPENDENCIA= CASE WHEN 's$dependencia$s' = 'X' THEN TO_CHAR(PROYECTOS.DEPENDENCIA) ELSE 's$dependencia$s' END
	AND PROYECTOS.ESTADOACTUAL=CASE WHEN 's$estadoActual$s' = 'X' THEN TO_CHAR(PROYECTOS.ESTADOACTUAL) ELSE 's$estadoActual$s' END
	AND FUENTES_FINANCIACION_TOTAL.VIGENCIAFUENTE= CASE WHEN 's$vigencia$s' = 'TODAS' THEN TO_CHAR(FUENTES_FINANCIACION_TOTAL.VIGENCIAFUENTE) ELSE 's$vigencia$s' END
	AND (CASE 's$enviado$s' WHEN '1' THEN ENVIADONACION WHEN '2' THEN ENVIADODPTO WHEN '3' THEN ENVIADOOTRAENTIDAD WHEN 'X' THEN -1+NVL(PROYECTOS.ENVIADONACION,0)+NVL(PROYECTOS.ENVIADODPTO,0)+NVL(PROYECTOS.ENVIADOOTRAENTIDAD,0) END<>0)
  GROUP BY PROYECTOS.COMPANIA, PROYECTOS.CODIGO, 
  PROYECTOS.DEPENDENCIA, 
  PROYECTOS.ESTADOACTUAL, 
  ENVIADONACION, ENVIADODPTO,ENVIADOOTRAENTIDAD,
  PROYECTOS.VIGENCIAINICIO, 
  PROYECTOS.VIGENCIAFIN, 
  PROYECTOS.FECHAREGISTRO, 
  PROYECTOS.CODIGOBPIM, 
  PROYECTOS.NOMBREPROYECTO, 
  PROYECTOS.VALORTOTAL,
  PROYECTOS.VALORANNO1, 
  PROYECTOS.VALORANNO2, 
  PROYECTOS.VALORANNO3, 
  PROYECTOS.VALORANNO4, 
  PROYECTOS.PORCEJECUCION, 
  TERCERO.NOMBRE, 
  DEPENDENCIA.NOMBRE, 
  FUENTES_FINANCIACION_TOTAL.VIGENCIAFUENTE, 
  PROYECTOS.OTRAENTIDAD,
  FECHAENVIONACION, FECHAENVIODPTO, FECHAENVIOOTRAENTIDAD,
  ESTADONACION,ESTADODPTO,ESTADOOTRAENTIDAD
  ORDER BY PROYECTOS.CODIGO
