WITH PLAN_PRESUPUESTAL_TMP AS (
  SELECT BP_PROYECTOSRUBROS.COMPANIA, 
        BP_PROYECTOSRUBROS.PROYECTO,
        MAX(PLAN_PRESUPUESTAL.NOMBRE) KEEP (DENSE_RANK LAST ORDER BY ROWNUM) NOMBREDIMENSION,
        MAX(PLAN_PRESUPUESTAL_1.NOMBRE) KEEP (DENSE_RANK LAST ORDER BY ROWNUM) NOMBRESECTOR,
        MAX(PLAN_PRESUPUESTAL_2.NOMBRE) KEEP (DENSE_RANK LAST ORDER BY ROWNUM) NOMBREPROGRAMA,
        MAX(PLAN_PRESUPUESTAL_3.NOMBRE) KEEP (DENSE_RANK LAST ORDER BY ROWNUM) NOMBRESUBPROGRAMA
  FROM BP_PROYECTOSRUBROS LEFT JOIN V_PLAN_PRESUPUESTAL PLAN_PRESUPUESTAL ON 
      BP_PROYECTOSRUBROS.COMPANIA         = PLAN_PRESUPUESTAL.COMPANIA
    AND BP_PROYECTOSRUBROS.DIMENSION      = PLAN_PRESUPUESTAL.ID
  LEFT JOIN V_PLAN_PRESUPUESTAL  PLAN_PRESUPUESTAL_1 ON 
      BP_PROYECTOSRUBROS.COMPANIA         = PLAN_PRESUPUESTAL_1.COMPANIA
    AND BP_PROYECTOSRUBROS.SECTOR         = PLAN_PRESUPUESTAL_1.ID
  LEFT JOIN V_PLAN_PRESUPUESTAL  PLAN_PRESUPUESTAL_2 ON 
      BP_PROYECTOSRUBROS.COMPANIA         = PLAN_PRESUPUESTAL_2.COMPANIA
    AND BP_PROYECTOSRUBROS.PROGRAMA       = PLAN_PRESUPUESTAL_2.ID
  LEFT JOIN V_PLAN_PRESUPUESTAL  PLAN_PRESUPUESTAL_3 ON 
      BP_PROYECTOSRUBROS.COMPANIA         = PLAN_PRESUPUESTAL_3.COMPANIA
    AND BP_PROYECTOSRUBROS.SUBPROGRAMA    = PLAN_PRESUPUESTAL_3.ID
  WHERE BP_PROYECTOSRUBROS.COMPANIA       = s$compania$s
    AND BP_PROYECTOSRUBROS.PROYECTO BETWEEN 's$proyectoInicial$s' AND 's$proyectoFin$s'
  GROUP BY BP_PROYECTOSRUBROS.COMPANIA, 
  BP_PROYECTOSRUBROS.PROYECTO
)
SELECT PROYECTOS.COMPANIA, 
        PROYECTOS.CODIGO CODIGO, 
        PROYECTOS.CODIGOBPIM, 
        PROYECTOS.RESPONSABLE, 
        TERCERO.NOMBRE RESPOSABLENOMBRE, 
        PROYECTOS.DEPENDENCIA, 
        PROYECTOS.NOMBREPROYECTO, 
        TO_CHAR(PROYECTOS.FECHAREGISTRO, 'DD/MM/YYYY') FECHAREGISTRO,
        VIGENCIAINICIO|| ' A '||VIGENCIAFIN VIGENCIANOMBRE, 
        MAX(PLAN_PRESUPUESTAL_TMP.NOMBREDIMENSION) KEEP (DENSE_RANK LAST ORDER BY ROWNUM) NOMBREDIMENSION,
        MAX(PLAN_PRESUPUESTAL_TMP.NOMBRESECTOR) KEEP (DENSE_RANK LAST ORDER BY ROWNUM) NOMBRESECTOR,
        MAX(PLAN_PRESUPUESTAL_TMP.NOMBREPROGRAMA) KEEP (DENSE_RANK LAST ORDER BY ROWNUM) NOMBREPROGRAMA,
        MAX(PLAN_PRESUPUESTAL_TMP.NOMBRESUBPROGRAMA) KEEP (DENSE_RANK LAST ORDER BY ROWNUM) NOMBRESUBPROGRAMA,
        SUM(PROYECTOS.VALORSOLICITADO) VALORSOLICITADO, 
        SUM(NVL(PROYECTOS.VALORTOTAL,0)) VALORTOTAL1, 
        DEPENDENCIA.NOMBRE NOMBRE_DEPENDENCIA
FROM PROYECTOS LEFT JOIN RESPONSABLE ON 
			PROYECTOS.COMPANIA			= RESPONSABLE.COMPANIA
		AND PROYECTOS.RESPONSABLE		= RESPONSABLE.CEDULA 
		AND PROYECTOS.SUCURSAL	 		= RESPONSABLE.SUCURSAL
  INNER JOIN TERCERO ON 
		RESPONSABLE.CEDULA				= TERCERO.NIT
    AND RESPONSABLE.SUCURSAL			= TERCERO.SUCURSAL
	LEFT JOIN PLAN_PRESUPUESTAL_TMP ON 
			PROYECTOS.COMPANIA			= PLAN_PRESUPUESTAL_TMP.COMPANIA 
		AND PROYECTOS.CODIGO			= PLAN_PRESUPUESTAL_TMP.PROYECTO 
	LEFT JOIN DEPENDENCIA ON 
			PROYECTOS.COMPANIA			= DEPENDENCIA.COMPANIA
		AND PROYECTOS.DEPENDENCIA		= DEPENDENCIA.CODIGO
WHERE PROYECTOS.COMPANIA				= s$compania$s
	AND PROYECTOS.CODIGO BETWEEN 's$proyectoInicial$s' AND 's$proyectoFin$s'
	AND CASE WHEN 's$vigenciaInicial$s' = 'TODAS' THEN TO_CHAR(PROYECTOS.VIGENCIAINICIO) ELSE 's$vigenciaInicial$s' END BETWEEN TO_CHAR(PROYECTOS.VIGENCIAINICIO) AND TO_CHAR(PROYECTOS.VIGENCIAFIN)
GROUP BY PROYECTOS.COMPANIA, 
  PROYECTOS.CODIGO, 
  PROYECTOS.CODIGOBPIM, 
  PROYECTOS.RESPONSABLE, 
  TERCERO.NOMBRE, 
  PROYECTOS.DEPENDENCIA,
  PROYECTOS.NOMBREPROYECTO, 
  PROYECTOS.FECHAREGISTRO, 
  VIGENCIAINICIO|| ' A '||VIGENCIAFIN, 
  DEPENDENCIA.NOMBRE
