SELECT DISTINCT BP_D_NOVEDADPROYECTO.COMPANIA, 
BP_D_NOVEDADPROYECTO.PROYECTO, 
BPTIPONOVEDAD.CLASENOVEDAD, 
CASE WHEN 's$vigencia$s'='TODAS' THEN 's$vigencia$s' ELSE TO_CHAR(BPNOVEDADPROYECTO.VIGENCIA) END V, 
BP_D_NOVEDADPROYECTO.TIPOT TIPOTNOVEDAD,
BP_D_NOVEDADPROYECTO.CLASET CLASETNOVEDAD, 
BP_D_NOVEDADPROYECTO.NOVEDAD, 
BP_D_NOVEDADPROYECTO.DEPENDENCIA, 
BP_D_NOVEDADPROYECTO.CODIGO CODIGONOVEDAD, 
BP_D_NOVEDADPROYECTO.VALORSOLICITADO, 
BP_D_NOVEDADPROYECTO.RUBROPRESUPUESTAL, 
BP_D_NOVEDADPROYECTO.LOCALIZACION, 
BP_D_NOVEDADPROYECTO.COMPONENTE, 
BPNOVEDADPROYECTO.TIPOT, 
CASE BPNOVEDADPROYECTO.ESTADO WHEN 'V' THEN 'Vigente' WHEN 'A' THEN 'Anulada' WHEN 'N' THEN 'No Aprobado' WHEN 'C' THEN 'Cambio' ELSE 'Otro' END ESTADO, 
BPNOVEDADPROYECTO.FECHA, 
BPNOVEDADPROYECTO.FECHA_ENVIO_BPPIM FECHABPIM, 
BPNOVEDADPROYECTO.CODIGO, 
BPNOVEDADPROYECTO.NUMERORADICADO, 
BPNOVEDADPROYECTO.OBJETO, 
BPNOVEDADPROYECTO.TIEMPOEJECUCION, 
BPNOVEDADPROYECTO.AFECTADO, 
COMPONENTES.NOMBRECOMPONENTE, 
NVL(COMPONENTES_ACTIVIDADES.NOMBREACTIVIDAD,'') NOMBREACTIVIDAD1, 
DEPENDENCIA.NOMBRE DEPENDENCIANOMBRE, 
BPNOVEDADPROYECTO.VOBOBP
FROM BP_D_NOVEDADPROYECTO 
  INNER JOIN BPNOVEDADPROYECTO 
      ON BP_D_NOVEDADPROYECTO.COMPANIA = BPNOVEDADPROYECTO.COMPANIA  
    AND BP_D_NOVEDADPROYECTO.NOVEDAD = BPNOVEDADPROYECTO.CODIGO
    AND BP_D_NOVEDADPROYECTO.CLASET = BPNOVEDADPROYECTO.CLASET
    AND BP_D_NOVEDADPROYECTO.TIPOT = BPNOVEDADPROYECTO.TIPOT
    AND BP_D_NOVEDADPROYECTO.DEPENDENCIA = BPNOVEDADPROYECTO.DEPENDENCIA
  INNER JOIN COMPONENTES 
      ON BP_D_NOVEDADPROYECTO.COMPANIA = COMPONENTES.COMPANIA
    AND BP_D_NOVEDADPROYECTO.PROYECTO = COMPONENTES.CODIGOPROYECTO 
    AND BP_D_NOVEDADPROYECTO.COMPONENTE = COMPONENTES.CODIGO
  INNER JOIN COMPONENTES_ACTIVIDADES 
      ON BP_D_NOVEDADPROYECTO.COMPANIA = COMPONENTES_ACTIVIDADES.COMPANIA
    AND BP_D_NOVEDADPROYECTO.COMPONENTE = COMPONENTES_ACTIVIDADES.COMPONENTE
    AND BP_D_NOVEDADPROYECTO.PROYECTO = COMPONENTES_ACTIVIDADES.CODIGOPROYECTO 
    AND BP_D_NOVEDADPROYECTO.ACTIVIDAD = COMPONENTES_ACTIVIDADES.ACTIVIDAD
  INNER JOIN DEPENDENCIA 
      ON BPNOVEDADPROYECTO.COMPANIA = DEPENDENCIA.COMPANIA
    AND BPNOVEDADPROYECTO.DEPENDENCIA = DEPENDENCIA.CODIGO
  INNER JOIN BPTIPONOVEDAD 
      ON BP_D_NOVEDADPROYECTO.COMPANIA = BPTIPONOVEDAD.COMPANIA
    AND BP_D_NOVEDADPROYECTO.TIPOT = BPTIPONOVEDAD.TIPOT
    AND BP_D_NOVEDADPROYECTO.CLASET = BPTIPONOVEDAD.CLASET
WHERE BP_D_NOVEDADPROYECTO.COMPANIA=$P{PR_COMPANIA} 
  AND BP_D_NOVEDADPROYECTO.PROYECTO = $P{PR_PROYECTO}  
  AND BPTIPONOVEDAD.CLASENOVEDAD='S'
  AND BPNOVEDADPROYECTO.ESTADO <> 'A'
  AND BPNOVEDADPROYECTO.VOBOBP <> 0 
 AND BPNOVEDADPROYECTO.VIGENCIA=CASE WHEN 's$vigencia$s' = 'TODAS' THEN TO_CHAR(BPNOVEDADPROYECTO.VIGENCIA) ELSE 's$vigencia$s' END
