MERGE INTO CONSULTAS FIN USING (SELECT '001772SubSolicitudCDPTOCANPR' INFORME ,TO_CLOB(q'[SELECT  BP_D_NOVEDADPROYECTO.RUBROPRESUPUESTAL RUBROPRESUPUESTAL,
        PLAN_PRESUPUESTAL.NOMBRE AS NOMBRE_PRESUPUESTAL,
        FUENTE_RECURSOS.CODIGO || ' ' || FUENTE_RECURSOS.NOMBRE          AS FUENTE,
        BP_D_NOVEDADPROYECTO.CODIGOCCPET  || ' ' || CCPET_CUIPO.NOMBRE AS CCPET, 
        BP_D_NOVEDADPROYECTO.CODIGOCPCDANE || ' ' || COD_CPC_CUIPO.NOMBRE AS CPCDANE,
        BP_D_NOVEDADPROYECTO.VALORSOLICITADO,
        METAPRODUCTO.DESCRIPCION DESCRIPCION_METAPRODUCTO
FROM BP_D_NOVEDADPROYECTO
  INNER JOIN  PLAN_PRESUPUESTAL
    ON BP_D_NOVEDADPROYECTO.COMPANIA           = PLAN_PRESUPUESTAL.COMPANIA
    AND BP_D_NOVEDADPROYECTO.ANORUBRO          = PLAN_PRESUPUESTAL.ANO
    AND BP_D_NOVEDADPROYECTO.RUBROPRESUPUESTAL             = PLAN_PRESUPUESTAL.CODIGO
    INNER JOIN FUENTE_RECURSOS
    ON BP_D_NOVEDADPROYECTO.COMPANIA         = FUENTE_RECURSOS.COMPANIA
    AND BP_D_NOVEDADPROYECTO.ANORUBRO         = FUENTE_RECURSOS.ANO
   AND BP_D_NOVEDADPROYECTO.FUENTERECURSOS        = FUENTE_RECURSOS.CODIGO
   LEFT JOIN BP_PLAN_INDICATIVO METAPRODUCTO
   ON BP_D_NOVEDADPROYECTO.COMPANIA                  = METAPRODUCTO.COMPANIA
  AND BP_D_NOVEDADPROYECTO.ID_META_PRODUCTO          = METAPRODUCTO.ID
  AND BP_D_NOVEDADPROYECTO.VIGENCIA_PLAN_INDICATIVO  = METAPRODUCTO.VIGENCIA_INICIAL
  LEFT JOIN TIPOCLASIFICADOR COD_CPC_CUIPO
           ON  BP_D_NOVEDADPROYECTO.COMPANIA = COD_CPC_CUIPO.COMPANIA
           AND BP_D_NOVEDADPROYECTO.ANORUBRO = COD_CPC_CUIPO.ANO
           AND '007'=COD_CPC_CUIPO.CLASECLASIFICADOR
           AND BP_D_NOVEDADPROYECTO.CODIGOCPCDANE = COD_CPC_CUIPO.CODIGO
    LEFT JOIN TIPOCLASIFICADOR CCPET_CUIPO
           ON  BP_D_NOVEDADPROYECTO.COMPANIA = CCPET_CUIPO.COMPANIA
           AND BP_D_NOVEDADPROYECTO.ANORUBRO = CCPET_CUIPO.ANO
           AND '006'=CCPET_CUIPO.CLASECLASIFICADOR
           AND BP_D_NOVEDADPROYECTO.CODIGOCCPET = CCPET_CUIPO.CODIGO
WHERE BP_D_NOVEDADPROYECTO.COMPANIA      = '$P!{PR_COMPANIA}'
  AND  BP_D_NOVEDADPROYECTO.TIPOT        = '$P!{PR_TIPOT}'
  AND BP_D_NOVEDADPROYECTO.CLASET        = '$P!{PR_CLASET}'
  AND BP_D_NOVEDADPROYECTO.NOVEDAD       = $P!{PR_CONSECUTIVO}
  AND BP_D_NOVEDADPROYECTO.DEPENDENCIA   = '$P!{PR_DEPENDENCIA}']') CONSULTA, 52 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);