SELECT BP_PLAN_INDICATIVO.DESCRIPCION DIM,
       SUBSTR(BP_PROYECTO_PLAN_INDICATIVO.ID_PLAN_P,0,s$digitodim$s) IDDIM
  FROM PROYECTOS
 INNER JOIN BP_PROYECTO_PLAN_INDICATIVO
    ON PROYECTOS.CODIGO    = BP_PROYECTO_PLAN_INDICATIVO.PROYECTO
   AND PROYECTOS.COMPANIA = BP_PROYECTO_PLAN_INDICATIVO.COMPANIA
 INNER JOIN BP_PLAN_INDICATIVO
    ON BP_PROYECTO_PLAN_INDICATIVO.VIGENCIA_PLAN_P        = BP_PLAN_INDICATIVO.VIGENCIA_INICIAL
   AND SUBSTR(BP_PROYECTO_PLAN_INDICATIVO.ID_PLAN_P,0,s$digitodim$s) = BP_PLAN_INDICATIVO.ID
   AND BP_PROYECTO_PLAN_INDICATIVO.COMPANIA              = BP_PLAN_INDICATIVO.COMPANIA
 WHERE PROYECTOS.COMPANIA  = s$compania$s
   AND PROYECTOS.CODIGO    = s$codigo$s
