SELECT
	DISTINCT (NVL(USUARIO.NOMBRE1, '') || ' ' || NVL(USUARIO.NOMBRE2, '') || ' ' || NVL(USUARIO.APELLIDO1, '') || ' ' || NVL(USUARIO.APELLIDO2, '')) ELABORO,
	BPNOVEDADPROYECTO.COMPANIA,
	BP_D_NOVEDADPROYECTO.TIPOT,
	BP_D_NOVEDADPROYECTO.CLASET,
	BPNOVEDADPROYECTO.CODIGO CONSECUTIVO,
	BPTIPONOVEDAD.CODIGODOC,
	BPTIPONOVEDAD.VERSIONDOC,
	TO_CHAR(BPTIPONOVEDAD.FECHAVERSIONDOC, 'DD/MM/YYYY') FECHA_DOC,
	DEPENDENCIA.NOMBRE DEPENDENCIANOM,
	DEPENDENCIA.CODIGO DEPENDENCIA,
	TO_CHAR(BPNOVEDADPROYECTO.FECHA, 'DD') DIA,
	TO_CHAR(BPNOVEDADPROYECTO.FECHA, 'MM') MES,
	TO_CHAR(BPNOVEDADPROYECTO.FECHA, 'YYYY') ANO,
	BPNOVEDADPROYECTO.CODIGO,
	BPNOVEDADPROYECTO.OBJETO,
	EJE.DESCRIPCION LINEA_ESTRAT,
	PROGRA.DESCRIPCION PROGRAMA,
	PROYECTOS.NOMBREPROYECTO PROYECTO,
	PROYECTOS.CODIGOBPIM,
	(BP_D_NOVEDADPROYECTO.COMPONENTE || ' ' || COMPONENTES.NOMBRECOMPONENTE) PRODUCTO,
	(BP_D_NOVEDADPROYECTO.ACTIVIDAD || ' ' || COMPONENTES_ACTIVIDADES.NOMBREACTIVIDAD) ACTIVIDAD,
	(BP_D_NOVEDADPROYECTO.ID_META_PRODUCTO || ' ' || BP_PROYECTO_PLAN_INDICATIVO.DESCRIPCION_META) META_PRODUCTO,
	CASE
		WHEN NVL(PERTIN_NOV.APPT, 0) <> 0 THEN 'X'
		ELSE ' '
	END SI_APPT,
	CASE
		WHEN NVL(PERTIN_NOV.APPT, 0) = 0 THEN 'X'
		ELSE ' '
	END NO_APPT,
	CASE
		WHEN NVL(PERTIN_NOV.APBOT, 0) <> 0 THEN 'X'
		ELSE ' '
	END SI_APBOT,
	CASE
		WHEN NVL(PERTIN_NOV.APBOT, 0) = 0 THEN 'X'
		ELSE ' '
	END NO_APBOT,
	PERTIN_NOV.APPT_CUAL,
	PERTIN_NOV.APBOT_CUAL,
	BP_D_NOVEDADPROYECTO.RUBROPRESUPUESTAL RUBRO,
	BP_D_NOVEDADPROYECTO.FUENTERECURSOS FUENTE,
	PLAN_PRESUPUESTAL.NOMBRE NOMBRE_RUBRO,
	BP_D_NOVEDADPROYECTO.VALORSOLICITADO
FROM
	BPNOVEDADPROYECTO
INNER JOIN BPTIPONOVEDAD ON
	BPNOVEDADPROYECTO.COMPANIA = BPTIPONOVEDAD.COMPANIA
	AND BPNOVEDADPROYECTO.TIPOT = BPTIPONOVEDAD.TIPOT
	AND BPNOVEDADPROYECTO.CLASET = BPTIPONOVEDAD.CLASET
INNER JOIN DEPENDENCIA ON
	BPNOVEDADPROYECTO.COMPANIA = DEPENDENCIA.COMPANIA
	AND BPNOVEDADPROYECTO.DEPENDENCIA = DEPENDENCIA.CODIGO
INNER JOIN BP_D_NOVEDADPROYECTO ON
	BPNOVEDADPROYECTO.COMPANIA = BP_D_NOVEDADPROYECTO.COMPANIA
	AND BPNOVEDADPROYECTO.CODIGO = BP_D_NOVEDADPROYECTO.NOVEDAD
	AND BPNOVEDADPROYECTO.TIPOT = BP_D_NOVEDADPROYECTO.TIPOT
	AND BPNOVEDADPROYECTO.CLASET = BP_D_NOVEDADPROYECTO.CLASET
	AND BPNOVEDADPROYECTO.DEPENDENCIA = BP_D_NOVEDADPROYECTO.DEPENDENCIA
INNER JOIN BP_PLAN_INDICATIVO EJE ON
	BP_D_NOVEDADPROYECTO.COMPANIA = EJE.COMPANIA
	AND SUBSTR(BP_D_NOVEDADPROYECTO.ID_META_PRODUCTO, 1, 's$eje$s') = EJE.ID
	AND BP_D_NOVEDADPROYECTO.VIGENCIA_PLAN_INDICATIVO = EJE.VIGENCIA_INICIAL
INNER JOIN BP_PLAN_INDICATIVO PROGRA ON
	BP_D_NOVEDADPROYECTO.COMPANIA = PROGRA.COMPANIA
	AND SUBSTR(BP_D_NOVEDADPROYECTO.ID_META_PRODUCTO, 1, 's$programa$s') = PROGRA.ID
	AND BP_D_NOVEDADPROYECTO.VIGENCIA_PLAN_INDICATIVO = PROGRA.VIGENCIA_INICIAL
INNER JOIN COMPONENTES ON
	BP_D_NOVEDADPROYECTO.COMPANIA = COMPONENTES.COMPANIA
	AND BP_D_NOVEDADPROYECTO.PROYECTO = COMPONENTES.CODIGOPROYECTO
	AND BP_D_NOVEDADPROYECTO.COMPONENTE = COMPONENTES.CODIGO
INNER JOIN COMPONENTES_ACTIVIDADES ON
	BP_D_NOVEDADPROYECTO.COMPANIA = COMPONENTES_ACTIVIDADES.COMPANIA
	AND BP_D_NOVEDADPROYECTO.PROYECTO = COMPONENTES_ACTIVIDADES.CODIGOPROYECTO
	AND BP_D_NOVEDADPROYECTO.ACTIVIDAD = COMPONENTES_ACTIVIDADES.ACTIVIDAD
INNER JOIN BP_PROYECTO_PLAN_INDICATIVO ON
	BP_D_NOVEDADPROYECTO.COMPANIA = BP_PROYECTO_PLAN_INDICATIVO.COMPANIA
	AND BP_D_NOVEDADPROYECTO.PROYECTO = BP_PROYECTO_PLAN_INDICATIVO.PROYECTO
	AND BP_D_NOVEDADPROYECTO.ID_META_PRODUCTO = BP_PROYECTO_PLAN_INDICATIVO.ID_PLAN_P
	AND BP_D_NOVEDADPROYECTO.ACTIVIDAD = BP_PROYECTO_PLAN_INDICATIVO.ACTIVIDAD
INNER JOIN BP_PERTINENCIA_NOVEDAD PERTIN_NOV ON
	BPNOVEDADPROYECTO.COMPANIA = PERTIN_NOV.COMPANIA
	AND BPNOVEDADPROYECTO.CODIGO = PERTIN_NOV.NOVEDAD
	AND BPNOVEDADPROYECTO.TIPOT = PERTIN_NOV.TIPONOVEDAD
	AND BPNOVEDADPROYECTO.CLASET = PERTIN_NOV.CLASENOVEDAD
	AND BPNOVEDADPROYECTO.DEPENDENCIA = PERTIN_NOV.DEPENDENCIA
INNER JOIN PLAN_PRESUPUESTAL ON
	BP_D_NOVEDADPROYECTO.COMPANIA = PLAN_PRESUPUESTAL.COMPANIA
	AND BP_D_NOVEDADPROYECTO.RUBROPRESUPUESTAL = PLAN_PRESUPUESTAL.CODIGO
	AND BP_D_NOVEDADPROYECTO.ANORUBRO = PLAN_PRESUPUESTAL.ANO
INNER JOIN USUARIO ON
	BPNOVEDADPROYECTO.CREATED_BY = USUARIO.CODIGO
INNER JOIN PROYECTOS ON
	BP_D_NOVEDADPROYECTO.COMPANIA = PROYECTOS.COMPANIA
	AND BP_D_NOVEDADPROYECTO.PROYECTO = PROYECTOS.CODIGO
WHERE
	BPNOVEDADPROYECTO.COMPANIA = s$compania$s
	AND BPNOVEDADPROYECTO.CODIGO = s$codigo$s
	AND BPNOVEDADPROYECTO.TIPOT = 's$tipot$s'
	AND BPNOVEDADPROYECTO.CLASET = 's$claset$s'
