SELECT DISTINCT
    PROYECTOS.CODIGOBPIM,
    PROYECTOS.NOMBREPROYECTO
  FROM BP_D_NOVEDADPROYECTO
  INNER JOIN BPNOVEDADPROYECTO
  ON BP_D_NOVEDADPROYECTO.COMPANIA     = BPNOVEDADPROYECTO.COMPANIA
  AND BP_D_NOVEDADPROYECTO.TIPOT       = BPNOVEDADPROYECTO.TIPOT
  AND BP_D_NOVEDADPROYECTO.CLASET      = BPNOVEDADPROYECTO.CLASET
  AND BP_D_NOVEDADPROYECTO.NOVEDAD     = BPNOVEDADPROYECTO.CODIGO
  AND BP_D_NOVEDADPROYECTO.DEPENDENCIA = BPNOVEDADPROYECTO.DEPENDENCIA
  INNER JOIN PROYECTOS
  ON BP_D_NOVEDADPROYECTO.COMPANIA  = PROYECTOS.COMPANIA
  AND BP_D_NOVEDADPROYECTO.PROYECTO = PROYECTOS.CODIGO
  WHERE BPNOVEDADPROYECTO.COMPANIA     = '$P!{PR_COMPANIA}'
  AND BPNOVEDADPROYECTO.TIPOT           = '$P!{PR_TIPOT}'
  AND BPNOVEDADPROYECTO.CLASET          = '$P!{PR_CLASET}'
    AND BPNOVEDADPROYECTO.CODIGO          = $P!{PR_CONSECUTIVO}
  ORDER BY PROYECTOS.CODIGOBPIM