MERGE INTO CONSULTAS FIN USING (SELECT '002365CertificadoCDPCastilla' INFORME ,TO_CLOB(q'[SELECT   BPNOVEDADPROYECTO.CODIGO SOLICITUD  
        ,BPNOVEDADPROYECTO.OBJETO OBJETO_PROYECTO
        ,PROYECTOS.NOMBREPROYECTO NOMBRE_PROYECTO
        ,PROYECTOS.CODIGOBPIM CODIGO_BPIM
        ,PCK_SYSMAN_UTL.FC_DIA(PROYECTOS.fecha_actualizacion) DIA_REGISTRO
        ,PCK_SYSMAN_UTL.FC_NOMBRE_MES(PCK_SYSMAN_UTL.FC_MES(PROYECTOS.fecha_actualizacion)) MES_REGISTRO
        ,PCK_SYSMAN_UTL.FC_ANIO(PROYECTOS.fecha_actualizacion) ANIO_REGISTRO  
        ,PCK_SYSMAN_UTL.FC_DIA(BPNOVEDADPROYECTO.FECHA) DIA_SOLICITUD
        ,PCK_SYSMAN_UTL.FC_NOMBRE_MES(PCK_SYSMAN_UTL.FC_MES(BPNOVEDADPROYECTO.FECHA)) MES_SOLICITUD
        ,PCK_SYSMAN_UTL.FC_ANIO(BPNOVEDADPROYECTO.FECHA) ANIO_SOLICITUD
        ,TERCERO.NOMBRE1||' '||TERCERO.NOMBRE2||' '||TERCERO.APELLIDO1||' '||TERCERO.APELLIDO2 NOMBRE_RESPONSABLE    
        ,BPNOVEDADPROYECTO.CARGORESPONSABLE CARGO_RESPONSABLE,
        BPNOVEDADPROYECTO.COMPANIA
FROM BPNOVEDADPROYECTO 
INNER JOIN BP_D_NOVEDADPROYECTO ON
	BPNOVEDADPROYECTO.COMPANIA = BP_D_NOVEDADPROYECTO.COMPANIA
	AND BPNOVEDADPROYECTO.CODIGO = BP_D_NOVEDADPROYECTO.NOVEDAD
	AND BPNOVEDADPROYECTO.TIPOT = BP_D_NOVEDADPROYECTO.TIPOT
	AND BPNOVEDADPROYECTO.CLASET = BP_D_NOVEDADPROYECTO.CLASET
	AND BPNOVEDADPROYECTO.DEPENDENCIA = BP_D_NOVEDADPROYECTO.DEPENDENCIA
INNER JOIN PROYECTOS ON
	BP_D_NOVEDADPROYECTO.COMPANIA = PROYECTOS.COMPANIA
	AND BP_D_NOVEDADPROYECTO.PROYECTO = PROYECTOS.CODIGO
INNER JOIN TERCERO ON  
    BPNOVEDADPROYECTO.RESPONSABLE = TERCERO.NIT 
    AND BPNOVEDADPROYECTO.COMPANIA = TERCERO.COMPANIA 
    AND BPNOVEDADPROYECTO.SUCURSAL = TERCERO.SUCURSAL
WHERE BPNOVEDADPROYECTO.COMPANIA = s$compania$s
 AND BPNOVEDADPROYECTO.CODIGO = 's$codigo$s' 
AND BPNOVEDADPROYECTO.TIPOT  = 'CDP'
AND BPNOVEDADPROYECTO.CLASET = 'B']') CONSULTA, 52 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);