MERGE INTO CONSULTAS FIN USING (SELECT '002357CDPSOGA' INFORME ,TO_CLOB(q'[SELECT PCK_SYSMAN_UTL.FC_VALOR_LETRAS(BPNOVEDADPROYECTO.VALORTOTAL,0) AS VALORTOTAL_LETRAS,
    TO_CHAR(BPNOVEDADPROYECTO.FECHA,'DD/MM/YYYY') FECHA,
        BPNOVEDADPROYECTO.DEPENDENCIA,
        BPNOVEDADPROYECTO.OBJETO,
        TO_CHAR(BPNOVEDADPROYECTO.CODIGO) CONSECUTIVO,
        BPNOVEDADPROYECTO.COMPANIA,
        BPNOVEDADPROYECTO.CODIGO SOLICITUD,
        DEPENDENCIA.NOMBRE NOMBREDEPEN,
        BPNOVEDADPROYECTO.CARGORESPONSABLE,
        TERCERO.NOMBRE NOMBRERESPON,
        BPNOVEDADPROYECTO.VALORTOTAL,
    BPNOVEDADPROYECTO.VALORSOLICITADO VALORAPROBADO
        FROM BPNOVEDADPROYECTO
INNER JOIN DEPENDENCIA
    ON DEPENDENCIA.COMPANIA = BPNOVEDADPROYECTO.COMPANIA
    AND DEPENDENCIA.CODIGO  = BPNOVEDADPROYECTO.DEPENDENCIA
INNER JOIN TERCERO
    ON TERCERO.COMPANIA  = BPNOVEDADPROYECTO.COMPANIA
    AND TERCERO.NIT      = BPNOVEDADPROYECTO.RESPONSABLE
    AND TERCERO.SUCURSAL = BPNOVEDADPROYECTO.SUCURSAL    
 WHERE BPNOVEDADPROYECTO.COMPANIA     = s$compania$s
    AND BPNOVEDADPROYECTO.TIPOT           = 's$tipot$s'
    AND BPNOVEDADPROYECTO.CLASET          = 's$claset$s'
    AND BPNOVEDADPROYECTO.CODIGO          = s$consecutivo$s]') CONSULTA, 52 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, 'dcastiblanco' CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);