MERGE INTO CONSULTAS FIN USING (SELECT '002620SolicitudCajica' INFORME ,TO_CLOB(q'[SELECT 
EJE.DESCRIPCION  AS LINEA_ESTRATEGICA,
(SELECT VALOR FROM PARAMETRO WHERE NOMBRE='NOMBRE SECRETARIO PLANEACION' AND COMPANIA=s$compania$s) NOMBRE_SECRETARIO,
(SELECT VALOR FROM PARAMETRO WHERE NOMBRE='NOMBRE PROFESIONAL UNIVERSITARIO CDP' AND COMPANIA=s$compania$s) NOMBRE_PROFESIONAL,
SUBPROGRAMA.DESCRIPCION  AS SUBPROGRAMA,
SUBPROGRAMA.DESCRIPCION  AS SUBPROGRAMA_PLAN,
SECTORDVD.DESCRIPCION AS DIMENSION,
PROGRAMA.DESCRIPCION_TEXTO_BP AS PROGRAMA,
BP_D_NOVEDADPROYECTO.SECTOR,
ACTIVIDAD.NOMBRE NOMBREACTIVIDAD,
SECTORES.DESCRIPCION AS DESC_SECTORPROG,
 BPNOVEDADPROYECTO.COMPANIA,
    BPNOVEDADPROYECTO.TIPOT,
    BPNOVEDADPROYECTO.CLASET,
    BPNOVEDADPROYECTO.CODIGO  CONSECUTIVO,
    BPNOVEDADPROYECTO.DEPENDENCIA,
    DEPENDENCIA.NOMBRE AS NOMBREDEP,
    BPNOVEDADPROYECTO.FECHA,
    TO_CHAR(BPNOVEDADPROYECTO.VALORTOTAL,'999,999,999,999,999.99') VALORTOTAL_SOL,
    PCK_SYSMAN_UTL.FC_VALOR_LETRAS(BPNOVEDADPROYECTO.VALORTOTAL,0) AS VALORLETRAS,
    TO_CHAR(BPNOVEDADPROYECTO.FECHA,'DD')DIA,
    TRIM(TO_CHAR(BPNOVEDADPROYECTO.FECHA, 'Month', 'NLS_DATE_LANGUAGE=SPANISH')) MES,
    TO_CHAR(BPNOVEDADPROYECTO.FECHA,'YYYY')ANIO,
    METAPRODUCTO.DESCRIPCION_INDICADOR_MEDIDA DESCRIPCION_METAPRODUCTO,
    TRIM(SUBSTR(METAPRODUCTO.DESCRIPCION, INSTR(METAPRODUCTO.DESCRIPCION, '-') + 1)) AS DESCRIPCION_METAPRODUCT,
    TRIM(SUBSTR(METAPRODUCTO.DESCRIPCION, 1, INSTR(METAPRODUCTO.DESCRIPCION, '-') - 1)) AS INDICADORPRODUCTO,
    PROYECTOS.CODIGOBPIM,
    PROYECTOS.NOMBREPROYECTO AS NOMBREPROYECTO,
    TRIM(UPPER(TO_CHAR(PROYECTOS.FECHAREGISTRO, 'FMMonth "DE" YYYY', 'NLS_DATE_LANGUAGE=SPANISH'))) FECHAREGISTRO_PRO,
    BPNOVEDADPROYECTO.OBJETO ||' '|| NVL(BPNOVEDADPROYECTO.OBSERVACIONES,' ') AS OBJETO,
    BPNOVEDADPROYECTO.OBSERVACIONES,
    BPNOVEDADPROYECTO.VIGENCIA,
    TO_CHAR(BPTIPONOVEDAD.FECHAVERSIONDOC, 'DD/MM/YYYY') FECHAVERSIONDOC,
    BPTIPONOVEDAD.VERSIONDOC,
    BPTIPONOVEDAD.CODIGODOC,
    BPTIPONOVEDAD.TITULOFORMATO,
  BPNOVEDADPROYECTO.CARGORESPONSABLE,
     TERCERO.NOMBRE,    
   BP_D_NOVEDADPROYECTO.RUBROPRESUPUESTAL RUBRO,
   BP_D_NOVEDADPROYECTO.FUENTERECURSOS,
   FUENTE_RECURSOS.NOMBRE NOMBRE_FUENTE,
   TO_CHAR(BP_D_NOVEDADPROYECTO.VALORSOLICITADO,'999,999,999,999,999.99') VALORSOLICITADO,
   BP_D_NOVEDADPROYECTO.SECTORRUBRO,
   COD_SECTOR.NOMBRE NOM_SECTORRUBRO, 
   BP_D_NOVEDADPROYECTO.PROGRAMARUBRO,
   COD_PROGRAMA.NOMBRE NOM_PROGRAMARUBRO, 
   BP_D_NOVEDADPROYECTO.CODIGOCCPET,
   COD_CCEPT.NOMBRE NOMBRE_CCPET,
   BPNOVEDADPROYECTO.NUMERORADICADO,
   USUARIO_C.NOMBRE1 || ' ' || USUARIO_C.NOMBRE2 || ' ' || USUARIO_C.APELLIDO1 || ' ' || USUARIO_C.APELLIDO2 AS CREATED_BY,
   USUARIO_M.NOMBRE1 || ' ' || USUARIO_M.NOMBRE2 || ' ' || USUARIO_M.APELLIDO1 || ' ' || USUARIO_M.APELLIDO2 AS MODIFIED_BY
FROM  BPNOVEDADPROYECTO
INNER JOIN    BP_D_NOVEDADPROYECTO  
   ON BPNOVEDADPROYECTO.COMPANIA    = BP_D_NOVEDADPROYECTO.COMPANIA 
  AND BPNOVEDADPROYECTO.TIPOT       = BP_D_NOVEDADPROYECTO.TIPOT
  AND BPNOVEDADPROYECTO.CLASET      = BP_D_NOVEDADPROYECTO.CLASET
  AND BPNOVEDADPROYECTO.CODIGO      = BP_D_NOVEDADPROYECTO.NOVEDAD 
  AND BPNOVEDADPROYECTO.DEPENDENCIA = B]') || TO_CLOB(q'[P_D_NOVEDADPROYECTO.DEPENDENCIA
INNER JOIN PROYECTOS 
   ON BP_D_NOVEDADPROYECTO.COMPANIA = PROYECTOS.COMPANIA 
  AND BP_D_NOVEDADPROYECTO.PROYECTO = PROYECTOS.CODIGO
LEFT JOIN BP_PLAN_INDICATIVO METAPRODUCTO
   ON BP_D_NOVEDADPROYECTO.COMPANIA                  = METAPRODUCTO.COMPANIA 
  AND BP_D_NOVEDADPROYECTO.ID_META_PRODUCTO          = METAPRODUCTO.ID
  AND BP_D_NOVEDADPROYECTO.VIGENCIA_PLAN_INDICATIVO  = METAPRODUCTO.VIGENCIA_INICIAL
LEFT JOIN BP_PLAN_INDICATIVO EJE
   ON BP_D_NOVEDADPROYECTO.COMPANIA                       = EJE.COMPANIA
  AND SUBSTR(BP_D_NOVEDADPROYECTO.ID_META_PRODUCTO,1,'s$eje$s') = EJE.ID
  AND BP_D_NOVEDADPROYECTO.VIGENCIA_PLAN_INDICATIVO       = EJE.VIGENCIA_INICIAL
LEFT JOIN BP_PLAN_INDICATIVO SECTOR
   ON BP_D_NOVEDADPROYECTO.COMPANIA                       = SECTOR.COMPANIA 
  AND SUBSTR(BP_D_NOVEDADPROYECTO.ID_META_PRODUCTO,1,'s$sector$s') = SECTOR.ID
  AND BP_D_NOVEDADPROYECTO.VIGENCIA_PLAN_INDICATIVO       = SECTOR.VIGENCIA_INICIAL
LEFT JOIN BP_PLAN_INDICATIVO PROGRAMA
   ON BP_D_NOVEDADPROYECTO.COMPANIA                       = PROGRAMA.COMPANIA 
  AND SUBSTR(BP_D_NOVEDADPROYECTO.ID_META_PRODUCTO,1,'s$programa$s') = PROGRAMA.ID
  AND BP_D_NOVEDADPROYECTO.VIGENCIA_PLAN_INDICATIVO       = PROGRAMA.VIGENCIA_INICIAL
LEFT JOIN BP_PLAN_INDICATIVO SUBPROGRAMA
   ON BP_D_NOVEDADPROYECTO.COMPANIA                       = SUBPROGRAMA.COMPANIA 
  AND SUBSTR(BP_D_NOVEDADPROYECTO.ID_META_PRODUCTO,1,'s$subprograma$s') = SUBPROGRAMA.ID
  AND BP_D_NOVEDADPROYECTO.VIGENCIA_PLAN_INDICATIVO       = SUBPROGRAMA.VIGENCIA_INICIAL
  LEFT JOIN BP_PLAN_INDICATIVO INDICAPRODUCTO
   ON BP_D_NOVEDADPROYECTO.COMPANIA                        = INDICAPRODUCTO.COMPANIA 
  AND SUBSTR(BP_D_NOVEDADPROYECTO.ID_META_PRODUCTO,1,'12') = INDICAPRODUCTO.ID
  AND BP_D_NOVEDADPROYECTO.VIGENCIA_PLAN_INDICATIVO        = INDICAPRODUCTO.VIGENCIA_INICIAL 
LEFT JOIN UNIDADPROYECTOS  
   ON METAPRODUCTO.COMPANIA                       = UNIDADPROYECTOS.COMPANIA 
  AND METAPRODUCTO.UNIDAD_MEDIDA                  = UNIDADPROYECTOS.UNIDAD
 INNER JOIN TERCERO
  ON BPNOVEDADPROYECTO.COMPANIA       = TERCERO.COMPANIA
  AND BPNOVEDADPROYECTO.RESPONSABLE    = TERCERO.NIT
INNER JOIN BPTIPONOVEDAD
      ON BPNOVEDADPROYECTO.COMPANIA = BPTIPONOVEDAD.COMPANIA 
      AND BPNOVEDADPROYECTO.TIPOT   = BPTIPONOVEDAD.TIPOT
      AND BPNOVEDADPROYECTO.CLASET  = BPTIPONOVEDAD.CLASET
    INNER JOIN DEPENDENCIA
      ON BPNOVEDADPROYECTO.COMPANIA = DEPENDENCIA.COMPANIA 
      AND BPNOVEDADPROYECTO.DEPENDENCIA   = DEPENDENCIA.CODIGO
      LEFT JOIN SECTORES
      ON BP_D_NOVEDADPROYECTO.COMPANIA = SECTORES.COMPANIA
      AND BP_D_NOVEDADPROYECTO.SECTOR = SECTORES.CODIGO
      LEFT JOIN SECTORES SECTORDVD
      ON METAPRODUCTO.COMPANIA = SECTORDVD.COMPANIA
      AND METAPRODUCTO.SECTOR = SECTORDVD.CODIGO
 INNER JOIN BP_ACTIVIDADES ACTIVIDAD
  ON BP_D_NOVEDADPROYECTO.ACTIVIDAD=ACTIVIDAD.CODIGO
  AND BP_D_NOVEDADPROYECTO.COMPANIA=ACTIVIDAD.COMPANIA
  LEFT JOIN FUENTE_RECURSOS
ON FUENTE_RECURSOS.COMPANIA =BP_D_NOVEDADPROYECTO.COMPANIA
AND FUENTE_RECURSOS.ANO = BP_D_NOVEDADPROYECTO.ANORUBRO
AND FUENTE_RECURSOS.CODIGO = BP_D_NO]') || TO_CLOB(q'[VEDADPROYECTO.FUENTERECURSOS
 LEFT JOIN TIPOCLASIFICADOR COD_CCEPT
 ON  BP_D_NOVEDADPROYECTO.COMPANIA = COD_CCEPT.COMPANIA
 AND BP_D_NOVEDADPROYECTO.ANORUBRO = COD_CCEPT.ANO
 AND '006' = COD_CCEPT.CLASECLASIFICADOR
 AND BP_D_NOVEDADPROYECTO.CODIGOCCPET = COD_CCEPT.CODIGO
 LEFT JOIN TIPOCLASIFICADOR COD_SECTOR
 ON  BP_D_NOVEDADPROYECTO.COMPANIA = COD_SECTOR.COMPANIA
 AND BP_D_NOVEDADPROYECTO.ANORUBRO = COD_SECTOR.ANO
 AND '001' = COD_SECTOR.CLASECLASIFICADOR
 AND BP_D_NOVEDADPROYECTO.SECTORRUBRO = COD_SECTOR.CODIGO
  LEFT JOIN TIPOCLASIFICADOR COD_PROGRAMA
 ON  BP_D_NOVEDADPROYECTO.COMPANIA = COD_PROGRAMA.COMPANIA
 AND BP_D_NOVEDADPROYECTO.ANORUBRO = COD_PROGRAMA.ANO
 AND '002' = COD_PROGRAMA.CLASECLASIFICADOR
 AND BP_D_NOVEDADPROYECTO.PROGRAMARUBRO = COD_PROGRAMA.CODIGO 
 LEFT JOIN USUARIO USUARIO_C
 ON USUARIO_C.CODIGO = BPNOVEDADPROYECTO.CREATED_BY
  LEFT JOIN USUARIO USUARIO_M
 ON USUARIO_M.CODIGO = BPNOVEDADPROYECTO.MODIFIED_BY
WHERE BPNOVEDADPROYECTO.COMPANIA      = s$compania$s
    AND BPNOVEDADPROYECTO.TIPOT       = 's$tipot$s'   
    AND BPNOVEDADPROYECTO.CODIGO = s$consecutivo$s]') CONSULTA, 52 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);