MERGE INTO CONSULTAS FIN USING (SELECT '002756SCDBPMELGAR' INFORME ,TO_CLOB(q'[SELECT BPTIPONOVEDAD.TITULOFORMATO,
    BPTIPONOVEDAD.CODIGODOC,
    BPTIPONOVEDAD.VERSIONDOC,
    TO_CHAR(BPTIPONOVEDAD.FECHAVERSIONDOC,'DD/MM/YYYY') FECHAVERSIONDOC,
    TO_CHAR(BPNOVEDADPROYECTO.FECHA,'DD') DIASOL,
    TO_CHAR(BPNOVEDADPROYECTO.FECHA,'MM') MESSOL,
    TO_CHAR(BPNOVEDADPROYECTO.FECHA,'YYYY') ANOSOL,
    BPNOVEDADPROYECTO.CODIGO CONSECUTIVO,
    BPNOVEDADPROYECTO.VALORTOTAL VALORTOTAL_SOL,
    PCK_SYSMAN_UTL.FC_VALOR_LETRAS(BPNOVEDADPROYECTO.VALORTOTAL,0) VALORLETRAS, 
    BPNOVEDADPROYECTO.OBJETO,
    BP_D_NOVEDADPROYECTO.RUBROPRESUPUESTAL RUBRO,
    PLAN_PRESUPUESTAL.NOMBRE NOMBRERUBRO,
    BP_D_NOVEDADPROYECTO.FUENTERECURSOS,
    BP_D_NOVEDADPROYECTO.PROYECTO,
    BP_D_NOVEDADPROYECTO.VALORAPROBADO,
    TERCERO.NOMBRE NOMBRE_SECRETARIO,
    RESPONSABLE.CARGO CARGO_SECRETARIO,
    TERCEROU.NOMBRE PROYECTADOPOR,
    RESPONSABLEU.CARGO CARGOPROYECTADO
FROM BPNOVEDADPROYECTO
INNER JOIN BPTIPONOVEDAD
ON BPNOVEDADPROYECTO.COMPANIA = BPTIPONOVEDAD.COMPANIA
AND BPNOVEDADPROYECTO.TIPOT = BPTIPONOVEDAD.TIPOT
AND BPNOVEDADPROYECTO.CLASET = BPTIPONOVEDAD.CLASET
LEFT JOIN BP_D_NOVEDADPROYECTO
ON BPNOVEDADPROYECTO.COMPANIA = BP_D_NOVEDADPROYECTO.COMPANIA  
AND BPNOVEDADPROYECTO.TIPOT = BP_D_NOVEDADPROYECTO.TIPOT
AND BPNOVEDADPROYECTO.CLASET = BP_D_NOVEDADPROYECTO.CLASET
AND BPNOVEDADPROYECTO.CODIGO = BP_D_NOVEDADPROYECTO.NOVEDAD
AND BPNOVEDADPROYECTO.DEPENDENCIA = BP_D_NOVEDADPROYECTO.DEPENDENCIA
LEFT JOIN PLAN_PRESUPUESTAL 
ON BP_D_NOVEDADPROYECTO.COMPANIA = PLAN_PRESUPUESTAL.COMPANIA
AND BP_D_NOVEDADPROYECTO.ANORUBRO = PLAN_PRESUPUESTAL.ANO
AND BP_D_NOVEDADPROYECTO.RUBROPRESUPUESTAL = PLAN_PRESUPUESTAL.CODIGO
LEFT JOIN TERCERO
ON BPNOVEDADPROYECTO.COMPANIA = TERCERO.COMPANIA
AND BPNOVEDADPROYECTO.RESPONSABLE = TERCERO.NIT
AND BPNOVEDADPROYECTO.SUCURSAL = TERCERO.SUCURSAL
LEFT JOIN RESPONSABLE
ON BPNOVEDADPROYECTO.COMPANIA = RESPONSABLE.COMPANIA
AND BPNOVEDADPROYECTO.RESPONSABLE = RESPONSABLE.CEDULA
AND BPNOVEDADPROYECTO.SUCURSAL = RESPONSABLE.SUCURSAL
LEFT JOIN USUARIO
ON BPNOVEDADPROYECTO.CREATED_BY = USUARIO.CODIGO
LEFT JOIN TERCERO TERCEROU
ON USUARIO.CEDULA = TERCEROU.NIT
AND USUARIO.SUCURSAL = TERCEROU.SUCURSAL 
AND s$compania$s = TERCEROU.COMPANIA 
LEFT JOIN RESPONSABLE RESPONSABLEU
ON USUARIO.CEDULA = RESPONSABLEU.CEDULA 
AND USUARIO.SUCURSAL = RESPONSABLEU.SUCURSAL
AND s$compania$s = RESPONSABLEU.COMPANIA 
WHERE BPNOVEDADPROYECTO.COMPANIA = s$compania$s
    AND BPNOVEDADPROYECTO.TIPOT = 's$tipot$s'
    AND BPNOVEDADPROYECTO.CLASET = 's$claset$s'
    AND BPNOVEDADPROYECTO.CODIGO = 's$consecutivo$s']') CONSULTA, 52 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);