MERGE INTO CONSULTAS FIN USING (SELECT '002959SolicitudCDPTP' INFORME ,TO_CLOB(q'[SELECT
    EJE.DESCRIPCION                             AS LINEA_ESTRATEGICA,
    METARESULTADO.DESCRIPCION                   AS INDICADOR_BIENESTAR,
    SECTOR.DESCRIPCION                          AS DIMENSION,
    PROGRAMA.DESCRIPCION                        AS PROGRAMA,
    BP_D_NOVEDADPROYECTO.SECTOR,
    SECTORES.DESCRIPCION                        AS DESC_SECTORPROG,
    BPNOVEDADPROYECTO.COMPANIA,
    BPNOVEDADPROYECTO.TIPOT,
    BPNOVEDADPROYECTO.CLASET,
    TERCERO.NOMBRE                              AS RESPONSABLESELECCIONADO,
    DEPEN_SEG.NOMBRE                            AS CARGORESPONSABLE,
    BPNOVEDADPROYECTO.CREATED_BY                AS NOMBREUSUARIO,
    CIUDAD.NOMBRE                               AS CIUDAD,
BPNOVEDADPROYECTO.CODIGO CONSECUTIVO,
    BPNOVEDADPROYECTO.DEPENDENCIA,
    DEPENDENCIA.NOMBRE                          AS NOMBREDEP,
    BPNOVEDADPROYECTO.FECHA,
    TO_CHAR(BPNOVEDADPROYECTO.FECHA, 'DD') DIA,
    TRIM(TO_CHAR(BPNOVEDADPROYECTO.FECHA, 'Month')) MES,
    TO_CHAR(BPNOVEDADPROYECTO.FECHA, 'YYYY') ANIO,
    METAPRODUCTO.DESCRIPCION_INDICADOR_MEDIDA   DESCRIPCION_METAPRODUCTO,
    METAPRODUCTO.DESCRIPCION                    DESCRIPCION_METAPRODUCT,
    PROYECTOS.CODIGOBPIM,
    PROYECTOS.NOMBREPROYECTO                    AS NOMBREPROYECTO,
    BPNOVEDADPROYECTO.OBJETO,
    BPNOVEDADPROYECTO.OBSERVACIONES,
    BPNOVEDADPROYECTO.VIGENCIA,
    BP_D_NOVEDADPROYECTO.VALORSOLICITADO        AS TOTAL_VALORSOLICITADO,
    TO_CHAR(BPTIPONOVEDAD.FECHAVERSIONDOC, 'DD/MM/YYYY') FECHAVERSIONDOC,
    BPTIPONOVEDAD.VERSIONDOC,
    BPTIPONOVEDAD.CODIGODOC,
    BPTIPONOVEDAD.TITULOFORMATO,
    CASE
        WHEN NVL(PCK_SYSMAN_UTL.FC_PAR(BPNOVEDADPROYECTO.COMPANIA, 'PERMITE LEYENDA DE FIRMA EN SOLICITUD DE CDP', 52, SYSDATE,
        - 1), 'NO') IN ('SI')
        THEN - 1
        ELSE   0
    END AS ORIGINAL_FIRMADO,
    BPNOVEDADPROYECTO.TIPOT_AFECTAR COMP_AFECT,
    BPNOVEDADPROYECTO.DOCUMENTO_AFECTAR SOL_AFECT
FROM
    BPNOVEDADPROYECTO
    INNER JOIN COMPANIA ON BPNOVEDADPROYECTO.COMPANIA = COMPANIA.CODIGO
INNER JOIN CIUDAD ON COMPANIA.CIUDAD = CIUDAD.CODIGO
                      AND COMPANIA.PAIS = CIUDAD.PAIS
    INNER JOIN TERCERO ON TERCERO.COMPANIA = BPNOVEDADPROYECTO.COMPANIA
                     AND TERCERO.SUCURSAL = BPNOVEDADPROYECTO.SUCURSAL
                     AND TERCERO.NIT = BPNOVEDADPROYECTO.RESPONSABLE
    INNER JOIN BP_D_NOVEDADPROYECTO ON BPNOVEDADPROYECTO.COMPANIA = BP_D_NOVEDADPROYECTO.COMPANIA
                                       AND BPNOVEDADPROYECTO.TIPOT = BP_D_NOVEDADPROYECTO.TIPOT
                                       AND BPNOVEDADPROYECTO.CLASET = BP_D_NOVEDADPROYECTO.CLASET
                                       AND BPNOVEDADPROYECTO.CODIGO = BP_D_NOVEDADPROYECTO.NOVEDAD
                                       AND BPNOVEDADPROYECTO.DEPENDENCIA = BP_D_NOVEDADPROYECTO.DEPENDENCIA
    INNER JOIN PROYECTOS ON BP_D_NOVEDADPROYECTO.COMPANIA = PROYECTOS]') || TO_CLOB(q'[.COMPANIA
                            AND BP_D_NOVEDADPROYECTO.PROYECTO = PROYECTOS.CODIGO
                      AND COMPANIA.DEPARTAMENTO = CIUDAD.DEPARTAMENTO
    LEFT JOIN BP_PLAN_INDICATIVO   METAPRODUCTO ON BP_D_NOVEDADPROYECTO.COMPANIA = METAPRODUCTO.COMPANIA
                                                 AND BP_D_NOVEDADPROYECTO.ID_META_PRODUCTO = METAPRODUCTO.ID
                                                 AND BP_D_NOVEDADPROYECTO.VIGENCIA_PLAN_INDICATIVO = METAPRODUCTO.VIGENCIA_INICIAL
    LEFT JOIN BP_PLAN_INDICATIVO   EJE ON BP_D_NOVEDADPROYECTO.COMPANIA = EJE.COMPANIA
                                        AND SUBSTR(BP_D_NOVEDADPROYECTO.ID_META_PRODUCTO, 1, 's$eje$s') = EJE.ID
                                        AND BP_D_NOVEDADPROYECTO.VIGENCIA_PLAN_INDICATIVO = EJE.VIGENCIA_INICIAL
    LEFT JOIN BP_PLAN_INDICATIVO   SECTOR ON BP_D_NOVEDADPROYECTO.COMPANIA = SECTOR.COMPANIA
                                           AND SUBSTR(BP_D_NOVEDADPROYECTO.ID_META_PRODUCTO, 1, 's$sector$s') = SECTOR.ID
                                           AND BP_D_NOVEDADPROYECTO.VIGENCIA_PLAN_INDICATIVO = SECTOR.VIGENCIA_INICIAL
    LEFT JOIN BP_PLAN_INDICATIVO   PROGRAMA ON BP_D_NOVEDADPROYECTO.COMPANIA = PROGRAMA.COMPANIA
                                             AND SUBSTR(BP_D_NOVEDADPROYECTO.ID_META_PRODUCTO, 1, 's$programa$s') = PROGRAMA.ID
                                             AND BP_D_NOVEDADPROYECTO.VIGENCIA_PLAN_INDICATIVO = PROGRAMA.VIGENCIA_INICIAL
    LEFT JOIN BP_PLAN_INDICATIVO   METARESULTADO ON BP_D_NOVEDADPROYECTO.COMPANIA = METARESULTADO.COMPANIA
         AND SUBSTR(BP_D_NOVEDADPROYECTO.ID_META_PRODUCTO, 1, 's$metaresultado$s') = METARESULTADO
.ID
                     AND BP_D_NOVEDADPROYECTO.VIGENCIA_PLAN_INDICATIVO = METARESULTADO.VIGENCIA_INICIAL
    LEFT JOIN UNIDADPROYECTOS ON METAPRODUCTO.COMPANIA = UNIDADPROYECTOS.COMPANIA
                                 AND METAPRODUCTO.UNIDAD_MEDIDA = UNIDADPROYECTOS.UNIDAD
    INNER JOIN BPTIPONOVEDAD ON BPNOVEDADPROYECTO.COMPANIA = BPTIPONOVEDAD.COMPANIA
                                AND BPNOVEDADPROYECTO.TIPOT = BPTIPONOVEDAD.TIPOT
                                AND BPNOVEDADPROYECTO.CLASET = BPTIPONOVEDAD.CLASET
    INNER JOIN DEPENDENCIA ON BP_D_NOVEDADPROYECTO.COMPANIA = DEPENDENCIA.COMPANIA
                              AND BP_D_NOVEDADPROYECTO.DEPENDENCIA = DEPENDENCIA.CODIGO
    LEFT JOIN SECTORES ON BP_D_NOVEDADPROYECTO.COMPANIA = SECTORES.COMPANIA
                          AND BP_D_NOVEDADPROYECTO.SECTOR = SECTORES.CODIGO
    LEFT JOIN DEPENDENCIA DEPEN_SEG ON BPNOVEDADPROYECTO.COMPANIA = DEPEN_SEG.COMPANIA
                             AND BPNOVEDADPROYECTO.DEPENDENCIA = DEPEN_SEG.CODIGO
WHERE
    BPNOVEDADPROYECTO.COMPANIA = s$compania$s
    AND BPNOVEDADPROYECTO.TIPOT = 's$tipot$s'
    AND BPNOVEDADPROYECTO.CODIGO = s$consecutivo$s]') CONSULTA, 52 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, 'JCROJAS' CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);

MERGE INTO CONSULTAS_SUB FIN USING (SELECT '002959SolicitudCDPTP' INFORME_PADRE, '002960SubSolicitudCDPTPPR' INFORME_HIJO, 'PR_STRSQL_SUB_SOLICITUDSDP_TP_PR' PARAMETRO ,'JCROJAS' CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (FIN.INFORME_PADRE = INI.INFORME_PADRE AND INI.INFORME_HIJO = FIN.INFORME_HIJO)  WHEN MATCHED THEN  UPDATE SET FIN.PARAMETRO = INI.PARAMETRO , FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME_PADRE,INFORME_HIJO, PARAMETRO,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME_PADRE,INI.INFORME_HIJO, INI.PARAMETRO,INI.CREATED_BY,SYSDATE);
MERGE INTO CONSULTAS_SUB FIN USING (SELECT '002959SolicitudCDPTP' INFORME_PADRE, '002961SubIndProductoTP' INFORME_HIJO, 'PR_STRSQL_SUB_INDPRODUCTO_TP' PARAMETRO ,'JCROJAS' CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (FIN.INFORME_PADRE = INI.INFORME_PADRE AND INI.INFORME_HIJO = FIN.INFORME_HIJO)  WHEN MATCHED THEN  UPDATE SET FIN.PARAMETRO = INI.PARAMETRO , FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME_PADRE,INFORME_HIJO, PARAMETRO,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME_PADRE,INI.INFORME_HIJO, INI.PARAMETRO,INI.CREATED_BY,SYSDATE);
MERGE INTO CONSULTAS_SUB FIN USING (SELECT '002959SolicitudCDPTP' INFORME_PADRE, '002962SubMetaProductoTP' INFORME_HIJO, 'PR_STRSQL_SUB_METAPRODUCTO_TP' PARAMETRO ,'JCROJAS' CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (FIN.INFORME_PADRE = INI.INFORME_PADRE AND INI.INFORME_HIJO = FIN.INFORME_HIJO)  WHEN MATCHED THEN  UPDATE SET FIN.PARAMETRO = INI.PARAMETRO , FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME_PADRE,INFORME_HIJO, PARAMETRO,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME_PADRE,INI.INFORME_HIJO, INI.PARAMETRO,INI.CREATED_BY,SYSDATE);
MERGE INTO CONSULTAS_SUB FIN USING (SELECT '002959SolicitudCDPTP' INFORME_PADRE, '002963SubActividadesTP' INFORME_HIJO, 'PR_STRSQL_SUB_ACTIVIDAD_TP' PARAMETRO ,'JCROJAS' CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (FIN.INFORME_PADRE = INI.INFORME_PADRE AND INI.INFORME_HIJO = FIN.INFORME_HIJO)  WHEN MATCHED THEN  UPDATE SET FIN.PARAMETRO = INI.PARAMETRO , FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME_PADRE,INFORME_HIJO, PARAMETRO,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME_PADRE,INI.INFORME_HIJO, INI.PARAMETRO,INI.CREATED_BY,SYSDATE);