SELECT PROYECTOS.CODIGO FICHAEBI,
       PROYECTOS.NOMBREPROYECTO,
       PROYECTOS.VALORTOTAL,
       TO_CHAR(PROYECTOS.FECHAREGISTRO,'DD/MM/YYYY') FECHAREGISTRO,
       '31/12/'||PROYECTOS.VIGENCIAFIN VIGENCIAFIN,
       PROYECTOS.OBJETO,
       PROYECTOS.PRODUCTO,
       CASE WHEN PROYECTOS.CODIGO IS NOT NULL 
            THEN 'X'
            ELSE ' '
            END RAD,
       CASE WHEN PROYECTOS.IREGISTRADO  NOT IN (0)
            THEN 'X' 
            ELSE  ' '
            END REG,
       CASE WHEN PROYECTOS.CONPROGRAMACION NOT IN (0)
            THEN 'X' 
            ELSE ' '
            END PRI,
       DEPENDENCIA.NOMBRE 
FROM PROYECTOS
  LEFT JOIN DEPENDENCIA
     ON  PROYECTOS.COMPANIA    = DEPENDENCIA.COMPANIA
     AND PROYECTOS.DEPENDENCIA = DEPENDENCIA.CODIGO
WHERE PROYECTOS.COMPANIA      = s$compania$s 
  AND PROYECTOS.FECHAREGISTRO BETWEEN 's$fechaInicial$s' 
                                               AND  's$fechaFinal$s'
