WITH CONSULTA AS(
  SELECT DISTINCT UPPER(APLICACIONES.NOMBRE) NOMBRE_APLICACION,
  MENU.CODIGO,
  MENU.NOMBRE OPCIONES_MENU,
  UPPER(FORMULARIO_APLICACION.RUTA) RUTA_ACCESO
  FROM MENU
  INNER JOIN GRUPO_MENU
  ON MENU.APLICACION        = GRUPO_MENU.APLICACION
  AND MENU.CODIGO           = GRUPO_MENU.MENU
  INNER JOIN FORMULARIO
  ON MENU.PARAMETRO = TO_CHAR(FORMULARIO.CODIGO_FORMULARIO)
  INNER JOIN FORMULARIO_APLICACION
  ON FORMULARIO.CODIGO_FORMULARIO = FORMULARIO_APLICACION.FORMULARIO
  INNER JOIN APLICACIONES
  ON FORMULARIO_APLICACION.APLICACION = APLICACIONES.APLICACION
  WHERE GRUPO_MENU.COMPANIA = 's$compania$s'
  AND UPPER(FORMULARIO_APLICACION.RUTA) IS NOT NULL
  ORDER BY UPPER(APLICACIONES.NOMBRE) , TO_CHAR(MENU.CODIGO),
  MENU.CODIGO 
)
SELECT 
CONSULTA.NOMBRE_APLICACION,
CONSULTA.OPCIONES_MENU,
CONSULTA.RUTA_ACCESO
FROM CONSULTA
