SELECT COMPROBANTE_PPTAL.COMPANIA,
  COMPROBANTE_PPTAL.NUMERO,
  COMPROBANTE_PPTAL.DESCRIPCION,
  COMPROBANTE_PPTAL.TERCERO,
  COMPROBANTE_PPTAL.SUCURSAL,
  TERCERO.NOMBRE,
  TIPO_COMPROBPP.NOMBRE         			NOMBRETIPO,
  TIPO_COMPROBPP.TIPOAFECTA,
  PLAN_PRESUPUESTAL.NOMBRE        			NOMBREPLAN,
  TO_DATE(TO_CHAR(DETALLE_COMPROBANTE_PPTAL.FECHA,'DD/MM/YYYY'),'DD/MM/YYYY') FECHA,
  DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE,
  DETALLE_COMPROBANTE_PPTAL.CUENTA CODIGO_CUENTA,
  DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE_AFECT,
  DETALLE_COMPROBANTE_PPTAL.CMPTE_AFECTADO,
  DETALLE_COMPROBANTE_PPTAL.VALOR_DEBITO,
  DETALLE_COMPROBANTE_PPTAL.VALOR_CREDITO,
  DETALLE_COMPROBANTE_PPTAL.COMPROBANTE,
  TERCERO_1.NOMBRE          			NOMBRETERCERO,
  COMPROBANTE_PPTAL.TERCERO               		CODTERCERO,
  COMPROBANTE_PPTAL.SUCURSAL          		CODSUCURSAL,
  DETALLE_COMPROBANTE_PPTAL.CONSECUTIVO
FROM ((((DETALLE_COMPROBANTE_PPTAL
INNER JOIN TERCERO TERCERO_1 ON 
  DETALLE_COMPROBANTE_PPTAL.COMPANIA = TERCERO_1.COMPANIA AND
  DETALLE_COMPROBANTE_PPTAL.TERCERO  = TERCERO_1.NIT AND
  DETALLE_COMPROBANTE_PPTAL.SUCURSAL  = TERCERO_1.SUCURSAL)
LEFT JOIN  PLAN_PRESUPUESTAL ON
  DETALLE_COMPROBANTE_PPTAL.COMPANIA = PLAN_PRESUPUESTAL.COMPANIA AND
  DETALLE_COMPROBANTE_PPTAL.ANO      = PLAN_PRESUPUESTAL.ANO AND
  DETALLE_COMPROBANTE_PPTAL.CUENTA    = PLAN_PRESUPUESTAL.CODIGO)
INNER JOIN COMPROBANTE_PPTAL ON
  DETALLE_COMPROBANTE_PPTAL.COMPANIA   = COMPROBANTE_PPTAL.COMPANIA AND
  DETALLE_COMPROBANTE_PPTAL.ANO        = COMPROBANTE_PPTAL.ANO AND
  DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE  = COMPROBANTE_PPTAL.TIPO AND
  DETALLE_COMPROBANTE_PPTAL.COMPROBANTE = COMPROBANTE_PPTAL.NUMERO)
INNER JOIN TERCERO ON
  COMPROBANTE_PPTAL.COMPANIA           = TERCERO.COMPANIA AND
  COMPROBANTE_PPTAL.TERCERO            = TERCERO.NIT AND
  COMPROBANTE_PPTAL.SUCURSAL            = TERCERO.SUCURSAL)
INNER JOIN TIPO_COMPROBPP ON
  DETALLE_COMPROBANTE_PPTAL.COMPANIA = TIPO_COMPROBPP.COMPANIA AND
  DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE = TIPO_COMPROBPP.CODIGO
WHERE DETALLE_COMPROBANTE_PPTAL.COMPANIA=s$compania$s
  AND TRUNC(DETALLE_COMPROBANTE_PPTAL.FECHA)
 
      BETWEEN s$fechaInicial$s AND s$fechaFinal$s
  AND DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE 
      BETWEEN 's$tipoInicial$s' AND 's$tipoFinal$s'
