SELECT  DETALLE_COMPROBANTE_PPTAL.COMPANIA, 
        COMPROBANTE_PPTAL.DEPENDENCIA, 
        DEPENDENCIA.NOMBRE NOMBREDEPENDENCIA,
        DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE, 
        TIPO_COMPROBPP.NOMBRE NOMBRETIPO, 
        DETALLE_COMPROBANTE_PPTAL.COMPROBANTE, 
        DETALLE_COMPROBANTE_PPTAL.FECHA, 
        CASE WHEN s$tipoCuenta$s = 1
             THEN 'CÓDIGO CUENTA'
             ELSE 'FID-UNE-PROG-SPR-PROY-DIS-REC'
             END  TITULOCUENTA,
        DETALLE_COMPROBANTE_PPTAL.DESCRIPCION, 
        (DETALLE_COMPROBANTE_PPTAL.MODIFICACION_DEBITO - DETALLE_COMPROBANTE_PPTAL.MODIFICACION_CREDITO)  MODIFICACION, 
        (DETALLE_COMPROBANTE_PPTAL.DEBITO_AFECTADO - DETALLE_COMPROBANTE_PPTAL.CREDITO_AFECTADO)  AFECTACION, 
        (DETALLE_COMPROBANTE_PPTAL.VALOR_DEBITO - DETALLE_COMPROBANTE_PPTAL.VALOR_CREDITO) -(DETALLE_COMPROBANTE_PPTAL.DEBITO_AFECTADO - DETALLE_COMPROBANTE_PPTAL.CREDITO_AFECTADO) +(DETALLE_COMPROBANTE_PPTAL.MODIFICACION_DEBITO - DETALLE_COMPROBANTE_PPTAL.MODIFICACION_CREDITO)  SALDO, 
        CASE WHEN s$tipoCuenta$s = 1
             THEN DETALLE_COMPROBANTE_PPTAL.CUENTA
             ELSE LPAD(NVL(V_PLAN_PRESUPUESTAL.NIVEL1, ''), 3) || '-' || LPAD(NVL(V_PLAN_PRESUPUESTAL.NIVEL2, ''), 3) || '-' || LPAD(NVL(V_PLAN_PRESUPUESTAL.NIVEL3, ''), 3) || '-' || LPAD(NVL(V_PLAN_PRESUPUESTAL.NIVEL4, ''), 3) || '-' || LPAD(NVL(V_PLAN_PRESUPUESTAL.NIVEL5, ''), 3) || '-' || LPAD(NVL(V_PLAN_PRESUPUESTAL.NIVEL6, ''), 3) || '-' || LPAD(NVL(V_PLAN_PRESUPUESTAL.NIVEL7, ''), 3)
             END  RUBRO, 
        V_PLAN_PRESUPUESTAL.NOMBRE NOMBREPLAN, 
        DETALLE_COMPROBANTE_PPTAL.CUENTA CODIGO_CUENTA, 
        DETALLE_COMPROBANTE_PPTAL.ANO,    
        TIPO_COMPROBPP.CLASE, 
        DETALLE_COMPROBANTE_PPTAL.VALOR_DEBITO, 
        DETALLE_COMPROBANTE_PPTAL.VALOR_CREDITO, 
        DETALLE_COMPROBANTE_PPTAL.DEBITO_AFECTADO, 
        DETALLE_COMPROBANTE_PPTAL.CREDITO_AFECTADO, 
        DETALLE_COMPROBANTE_PPTAL.MODIFICACION_DEBITO, 
        DETALLE_COMPROBANTE_PPTAL.MODIFICACION_CREDITO,         
        DETALLE_COMPROBANTE_PPTAL.TERCERO  CODTERCERO, 
        DETALLE_COMPROBANTE_PPTAL.SUCURSAL  CODSUCURSAL, 
        TERCERO.NOMBRE NOMBRETERCERO,        
        (DETALLE_COMPROBANTE_PPTAL.VALOR_DEBITO - DETALLE_COMPROBANTE_PPTAL.VALOR_CREDITO)  MOVIMIENTO    
FROM DETALLE_COMPROBANTE_PPTAL 
INNER JOIN TERCERO 
 ON  DETALLE_COMPROBANTE_PPTAL.COMPANIA     = TERCERO.COMPANIA
 AND DETALLE_COMPROBANTE_PPTAL.TERCERO      = TERCERO.NIT 
 AND DETALLE_COMPROBANTE_PPTAL.SUCURSAL     = TERCERO.SUCURSAL
INNER JOIN V_PLAN_PRESUPUESTAL 
 ON  DETALLE_COMPROBANTE_PPTAL.COMPANIA     = V_PLAN_PRESUPUESTAL.COMPANIA 
 AND DETALLE_COMPROBANTE_PPTAL.ANO          = V_PLAN_PRESUPUESTAL.ANO 
 AND DETALLE_COMPROBANTE_PPTAL.ID       = V_PLAN_PRESUPUESTAL.ID 
INNER JOIN TIPO_COMPROBPP 
 ON  DETALLE_COMPROBANTE_PPTAL.COMPANIA     = TIPO_COMPROBPP.COMPANIA 
 AND DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE    = TIPO_COMPROBPP.CODIGO 
INNER JOIN COMPROBANTE_PPTAL 
 ON  DETALLE_COMPROBANTE_PPTAL.COMPANIA     = COMPROBANTE_PPTAL.COMPANIA
 AND DETALLE_COMPROBANTE_PPTAL.ANO          = COMPROBANTE_PPTAL.ANO 
 AND DETALLE_COMPROBANTE_PPTAL.COMPROBANTE  = COMPROBANTE_PPTAL.NUMERO 
 AND DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE    = COMPROBANTE_PPTAL.TIPO 
LEFT JOIN DEPENDENCIA 
 ON  COMPROBANTE_PPTAL.COMPANIA             = DEPENDENCIA.COMPANIA 
 AND COMPROBANTE_PPTAL.DEPENDENCIA          = DEPENDENCIA.CODIGO 
WHERE DETALLE_COMPROBANTE_PPTAL.COMPANIA =  s$compania$s 
AND   TIPO_COMPROBPP.CLASE = 'DIS'
AND   TRUNC(DETALLE_COMPROBANTE_PPTAL.FECHA) BETWEEN  TO_DATE('s$fechaInicial$s','DD/MM/YYYY') AND TO_DATE('s$fechaFinal$s','DD/MM/YYYY') 
AND (ROUND((DETALLE_COMPROBANTE_PPTAL.VALOR_DEBITO - DETALLE_COMPROBANTE_PPTAL.VALOR_CREDITO) -
           (DETALLE_COMPROBANTE_PPTAL.DEBITO_AFECTADO - DETALLE_COMPROBANTE_PPTAL.CREDITO_AFECTADO) +
           (DETALLE_COMPROBANTE_PPTAL.MODIFICACION_DEBITO - DETALLE_COMPROBANTE_PPTAL.MODIFICACION_CREDITO), 2)) <> 0    
ORDER BY 
    DETALLE_COMPROBANTE_PPTAL.COMPANIA, 
    DETALLE_COMPROBANTE_PPTAL.ANO, 
    DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE, 
    DETALLE_COMPROBANTE_PPTAL.COMPROBANTE
