SELECT
  DETALLE_COMPROBANTE_CNT.COMPANIA, 
  DETALLE_COMPROBANTE_CNT.TIPO_CPTE, 
  DETALLE_COMPROBANTE_CNT.COMPROBANTE, 
  DETALLE_COMPROBANTE_CNT.FECHA,  
 ' s$nombre$s' NOMBRE,
  TERCERO.NIT CODTERCERO,
  DETALLE_COMPROBANTE_CNT.CODIGO_PPTAL,
  DETALLE_COMPROBANTE_CNT.CUENTAPPTAL,
  TERCERO.SUCURSAL CODSUCURSAL,
  DETALLE_COMPROBANTE_CNT.DESCRIPCION,   
  DETALLE_COMPROBANTE_CNT.TIPO_DOCUMENTO,  
  DETALLE_COMPROBANTE_CNT.NRO_DOCUMENTO,
  DETALLE_COMPROBANTE_CNT.CUENTA CODIGO_CUENTA,   
  CENTRO_COSTO.CODIGO CODCENTROCOSTO,  
  CENTRO_COSTO.NOMBRE CENTRO_COSTO_NOMBRE,  
  AUXILIAR.CODIGO CODAUXILIAR, 
  AUXILIAR.NOMBRE AUXILIAR_NOMBRE, 
  (CASE WHEN 's$naturaleza$s' = 'D' THEN DETALLE_COMPROBANTE_CNT.EJECUCION_DEBITO - DETALLE_COMPROBANTE_CNT.EJECUCION_CREDITO ELSE DETALLE_COMPROBANTE_CNT.EJECUCION_CREDITO - DETALLE_COMPROBANTE_CNT.EJECUCION_DEBITO END ) VALOR 
FROM DETALLE_COMPROBANTE_CNT 
  INNER JOIN TERCERO 
     ON DETALLE_COMPROBANTE_CNT.COMPANIA = TERCERO.COMPANIA  
    AND DETALLE_COMPROBANTE_CNT.TERCERO = TERCERO.NIT  
    AND DETALLE_COMPROBANTE_CNT.SUCURSAL = TERCERO.SUCURSAL  
  INNER JOIN AUXILIAR     
     ON DETALLE_COMPROBANTE_CNT.COMPANIA = AUXILIAR.COMPANIA 
    AND DETALLE_COMPROBANTE_CNT.AUXILIAR = AUXILIAR.CODIGO   
    AND DETALLE_COMPROBANTE_CNT.ANO = AUXILIAR.ANO
  INNER JOIN CENTRO_COSTO    
     ON DETALLE_COMPROBANTE_CNT.COMPANIA = CENTRO_COSTO.COMPANIA   
    AND DETALLE_COMPROBANTE_CNT.CENTRO_COSTO = CENTRO_COSTO.CODIGO
    AND DETALLE_COMPROBANTE_CNT.ANO = CENTRO_COSTO.ANO 
  INNER JOIN COMPROBANTE_CNT  
     ON DETALLE_COMPROBANTE_CNT.COMPANIA = COMPROBANTE_CNT.COMPANIA  
    AND DETALLE_COMPROBANTE_CNT.TIPO_CPTE = COMPROBANTE_CNT.TIPO    
    AND DETALLE_COMPROBANTE_CNT.ANO = COMPROBANTE_CNT.ANO     
    AND DETALLE_COMPROBANTE_CNT.COMPROBANTE = COMPROBANTE_CNT.NUMERO
WHERE DETALLE_COMPROBANTE_CNT.COMPANIA = s$compania$s 
  AND DETALLE_COMPROBANTE_CNT.ANO = s$anio$s
  AND SUBSTR(DETALLE_COMPROBANTE_CNT.CUENTAPPTAL,0,LENGTH('s$codigo$s' )) = 's$codigo$s'  
  AND LENGTH(DETALLE_COMPROBANTE_CNT.CUENTAPPTAL) >= LENGTH('s$codigo$s') 
  AND EXTRACT (MONTH FROM DETALLE_COMPROBANTE_CNT.FECHA) BETWEEN s$mesInicial$s AND s$mesFinal$s
ORDER BY DETALLE_COMPROBANTE_CNT.TIPO_CPTE, DETALLE_COMPROBANTE_CNT.COMPROBANTE, DETALLE_COMPROBANTE_CNT.FECHA
