SELECT DETALLE_COMPROBANTE_PPTAL.CUENTA, 
       PLAN_PRESUPUESTAL.NOMBRE, 
       EXTRACT (MONTH FROM DETALLE_COMPROBANTE_PPTAL.FECHA) AS MES, 
       SUM(CASE WHEN PLAN_PRESUPUESTAL.NATURALEZA= 'D'
                THEN VALOR_CREDITO
                ELSE VALOR_DEBITO
            END)  DISMINUCION, 
       SUM(CASE WHEN PLAN_PRESUPUESTAL.NATURALEZA = 'C'
                THEN VALOR_CREDITO
                ELSE VALOR_DEBITO
            END) ADICION, 
       PLAN_PRESUPUESTAL.NATURALEZA, 
       TRIM(TO_CHAR(DETALLE_COMPROBANTE_PPTAL.FECHA, 'MONTH')) AS MESNOMBRE, 
       EXTRACT (YEAR FROM DETALLE_COMPROBANTE_PPTAL.FECHA) AS ANO, 
       DETALLE_COMPROBANTE_PPTAL.FECHA
FROM DETALLE_COMPROBANTE_PPTAL 
      INNER JOIN TIPO_COMPROBPP 
              ON DETALLE_COMPROBANTE_PPTAL.COMPANIA    = TIPO_COMPROBPP.COMPANIA 
             AND DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE   = TIPO_COMPROBPP.CODIGO
      INNER JOIN PLAN_PRESUPUESTAL 
              ON DETALLE_COMPROBANTE_PPTAL.COMPANIA    = PLAN_PRESUPUESTAL.COMPANIA 
             AND DETALLE_COMPROBANTE_PPTAL.ANO         = PLAN_PRESUPUESTAL.ANO
             AND DETALLE_COMPROBANTE_PPTAL.CUENTA      = PLAN_PRESUPUESTAL.CODIGO
      INNER JOIN COMPROBANTE_PPTAL 
              ON DETALLE_COMPROBANTE_PPTAL.COMPANIA    = COMPROBANTE_PPTAL.COMPANIA
             AND DETALLE_COMPROBANTE_PPTAL.ANO         = COMPROBANTE_PPTAL.ANO
             AND DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE   = COMPROBANTE_PPTAL.TIPO 
	     AND DETALLE_COMPROBANTE_PPTAL.COMPROBANTE = COMPROBANTE_PPTAL.NUMERO 
WHERE DETALLE_COMPROBANTE_PPTAL.COMPANIA                  = s$compania$s
  AND DETALLE_COMPROBANTE_PPTAL.CUENTA BETWEEN 's$cuentaInicial$s' AND 's$cuentaFinal$s' 
  AND EXTRACT (YEAR FROM DETALLE_COMPROBANTE_PPTAL.FECHA) = s$anio$s
  AND COMPROBANTE_PPTAL.FECHA BETWEEN TO_DATE('s$fechaInicial$s') AND TO_DATE('s$fechaFinal$s')
  AND TIPO_COMPROBPP.CLASE = 'MOP'
GROUP BY DETALLE_COMPROBANTE_PPTAL.CUENTA, 
         PLAN_PRESUPUESTAL.NOMBRE, 
         EXTRACT (MONTH FROM DETALLE_COMPROBANTE_PPTAL.FECHA), 
         PLAN_PRESUPUESTAL.NATURALEZA, 
         EXTRACT (YEAR FROM DETALLE_COMPROBANTE_PPTAL.FECHA), 
         DETALLE_COMPROBANTE_PPTAL.FECHA, 
         COMPROBANTE_PPTAL.FECHA
ORDER BY DETALLE_COMPROBANTE_PPTAL.CUENTA, EXTRACT (MONTH FROM DETALLE_COMPROBANTE_PPTAL.FECHA)
