MERGE INTO CONSULTAS FIN USING ( SELECT '000915FCAGREJECUCIONPACC' AS INFORME_VAL, TO_CLOB(q'[SELECT REPLACE(PLAN_PRESUPUESTAL.ID,'                   ',' ') ID,
       PLAN_PRESUPUESTAL.NOMBRE,
       SUBSTR(PLAN_PRESUPUESTAL.ID,0,1) CLASE,
       CASE
         WHEN s$miles$s NOT IN (0)
         THEN PCK_SYSMAN_UTL.FC_ROUND(SUM(SALDO_PLAN_PPTAL.PAC_APROPIADO),-3)/1000
         ELSE SUM(SALDO_PLAN_PPTAL.PAC_APROPIADO)
       END PACINICIALF,
       CASE
         WHEN s$miles$s NOT IN (0)
         THEN PCK_SYSMAN_UTL.FC_ROUND(SUM(SALDO_PLAN_PPTAL.MODIF_PAC_DEBITO),-3)/1000
         ELSE SUM(SALDO_PLAN_PPTAL.MODIF_PAC_DEBITO)
       END PACADICIONF,
       CASE
         WHEN s$miles$s NOT IN (0)
         THEN PCK_SYSMAN_UTL.FC_ROUND(SUM(SALDO_PLAN_PPTAL.MODIF_PAC_CREDITO),-3)/1000
         ELSE SUM(SALDO_PLAN_PPTAL.MODIF_PAC_CREDITO)
       END PACREDUCCIONF,
       CASE
         WHEN s$miles$s NOT IN (0)
         THEN PCK_SYSMAN_UTL.FC_ROUND(SUM(SALDO_PLAN_PPTAL.PAC_APROPIADO),-3)/1000
         ELSE SUM(SALDO_PLAN_PPTAL.PAC_APROPIADO)
       END+CASE
         WHEN s$miles$s NOT IN (0)
         THEN PCK_SYSMAN_UTL.FC_ROUND(SUM(SALDO_PLAN_PPTAL.MODIF_PAC_DEBITO),-3)/1000
         ELSE SUM(SALDO_PLAN_PPTAL.MODIF_PAC_DEBITO)
       END-CASE
         WHEN s$miles$s NOT IN (0)
         THEN PCK_SYSMAN_UTL.FC_ROUND(SUM(SALDO_PLAN_PPTAL.MODIF_PAC_CREDITO),-3)/1000
         ELSE SUM(SALDO_PLAN_PPTAL.MODIF_PAC_CREDITO)
       END PACTOTALF,
       CASE
         WHEN s$miles$s NOT IN (0)
         THEN PCK_SYSMAN_UTL.FC_ROUND(SUM(SALDO_PLAN_PPTAL.MODIF_PAC_CREDITO),-3)/1000
         ELSE SUM(SALDO_PLAN_PPTAL.MODIF_PAC_CREDITO)
       END PACREDUCCIONF,
       CASE
         WHEN s$miles$s NOT IN (0)
         THEN PCK_SYSMAN_UTL.FC_ROUND(SUM(SALDO_PLAN_PPTAL.PAC_APROPIADO),-3)/1000
         ELSE SUM(SALDO_PLAN_PPTAL.PAC_APROPIADO)
       END+CASE
         WHEN s$miles$s NOT IN (0)
         THEN PCK_SYSMAN_UTL.FC_ROUND(SUM(SALDO_PLAN_PPTAL.MODIF_PAC_DEBITO),-3)/1000
         ELSE SUM(SALDO_PLAN_PPTAL.MODIF_PAC_DEBITO)
       END-CASE
         WHEN s$miles$s NOT IN (0)
         THEN PCK_SYSMAN_UTL.FC_ROUND(SUM(SALDO_PLAN_PPTAL.MODIF_PAC_CREDITO),-3)/1000
         ELSE SUM(SALDO_PLAN_PPTAL.MODIF_PAC_CREDITO)
       END PACPROGRAMADOF,
       CASE
         WHEN s$miles$s NOT IN (0)
         THEN PCK_SYSMAN_UTL.FC_ROUND(SUM(EJE_PPT_DEBITO-EJE_PPT_CREDITO),-3)/1000
         ELSE SUM(EJE_PPT_DEBITO-EJE_PPT_CREDITO)
       END PAGOSACUMF,
       CASE
         WHEN s$miles$s NOT IN (0)
         THEN PCK_SYSMAN_UTL.FC_ROUND(SUM(SALDO_PLAN_PPTAL.PAC_APROPIADO),-3)/1000
         ELSE SUM(SALDO_PLAN_PPTAL.PAC_APROPIADO)
       END+CASE
         WHEN s$miles$s NOT IN (0)
         THEN PCK_SYSMAN_UTL.FC_ROUND(SUM(SALDO_PLAN_PPTAL.MODIF_PAC_DEBITO),-3)/1000
         ELSE SUM(SALDO_PLAN_PPTAL.MODIF_PAC_DEBITO)
       END-CASE
         WHEN s$miles$s NOT IN (0)
         THEN PCK_SYSMAN_UTL.FC_ROUND(SUM(SALDO_PLAN_PPTAL.MODIF_PAC_CREDITO),-3)/1000
         ELSE SUM(SALDO_PLAN_PPTAL.MODIF_PAC_CREDITO)
       END
       - CASE
         WHEN s$miles$s NOT IN (0)
         THEN]') || TO_CLOB(q'[ PCK_SYSMAN_UTL.FC_ROUND(SUM(EJE_PPT_DEBITO-EJE_PPT_CREDITO),-3)/1000
         ELSE SUM(EJE_PPT_DEBITO-EJE_PPT_CREDITO)
       END SALDO
FROM V_PLAN_PRESUPUESTAL PLAN_PRESUPUESTAL
  INNER JOIN V_SALDO_PLAN_PPTAL SALDO_PLAN_PPTAL
    ON PLAN_PRESUPUESTAL.COMPANIA   = SALDO_PLAN_PPTAL.COMPANIA
    AND PLAN_PRESUPUESTAL.ANO       = SALDO_PLAN_PPTAL.ANO
    AND PLAN_PRESUPUESTAL.ID        = SALDO_PLAN_PPTAL.ID
WHERE SALDO_PLAN_PPTAL.COMPANIA    = s$compania$s
  AND SALDO_PLAN_PPTAL.ANO         = s$anio$s
  AND PLAN_PRESUPUESTAL.NATURALEZA = 'D'
  AND SALDO_PLAN_PPTAL.MES           BETWEEN s$mesInicial$s AND s$mesFinal$s
  AND SALDO_PLAN_PPTAL.CODIGO        BETWEEN 's$cuentaInicial$s' AND 's$cuentaFinal$s'
  s$centroCostoCond$s
  s$fuenteCond$s
GROUP BY SALDO_PLAN_PPTAL.COMPANIA,
         SALDO_PLAN_PPTAL.ANO,
         PLAN_PRESUPUESTAL.ID,
         PLAN_PRESUPUESTAL.NOMBRE]') AS CONSULTA_VAL, 3 AS APLICACION_VAL, TO_CLOB(q'[]') AS CONSULTA_OPCIONAL_VAL, (SELECT MIN(ROWID) FROM CONSULTAS WHERE INFORME = '000915FCAGREJECUCIONPACC') AS RID_DESTINO  FROM DUAL ) INI ON (FIN.ROWID = INI.RID_DESTINO)  WHEN MATCHED THEN   UPDATE SET FIN.CONSULTA = INI.CONSULTA_VAL, FIN.APLICACION = INI.APLICACION_VAL, FIN.CONSULTA_OPCIONAL = INI.CONSULTA_OPCIONAL_VAL, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN   INSERT (INFORME, CONSULTA, APLICACION, CONSULTA_OPCIONAL, DATE_CREATED)   VALUES (INI.INFORME_VAL, INI.CONSULTA_VAL, INI.APLICACION_VAL, INI.CONSULTA_OPCIONAL_VAL, SYSDATE);