SELECT  PLAN_PRESUPUESTAL.COMPANIA,
        PLAN_PRESUPUESTAL.ANO,
        PLAN_PRESUPUESTAL.CODIGO CUENTA,
        PLAN_PRESUPUESTAL.CODIGO,
        SUBSTR(PLAN_PRESUPUESTAL.CODIGO,0,1) GRUPO,
        SUM(APROPIACIONESINICIALES.APROPIACIONINICIAL) VALOR,
        PLAN_PRESUPUESTAL.NOMBRE
FROM APROPIACIONESINICIALES
  INNER JOIN PLAN_PRESUPUESTAL
    ON  APROPIACIONESINICIALES.COMPANIA = PLAN_PRESUPUESTAL.COMPANIA
    AND APROPIACIONESINICIALES.ANO      = PLAN_PRESUPUESTAL.ANO
    AND SUBSTR(APROPIACIONESINICIALES.CODIGO,1,LENGTH(PLAN_PRESUPUESTAL.CODIGO))   = PLAN_PRESUPUESTAL.CODIGO
WHERE APROPIACIONESINICIALES.COMPANIA =  s$compania$s
AND APROPIACIONESINICIALES.ANO        = s$anio$s
GROUP BY PLAN_PRESUPUESTAL.COMPANIA
, PLAN_PRESUPUESTAL.ANO
, PLAN_PRESUPUESTAL.CODIGO
, PLAN_PRESUPUESTAL.NOMBRE





