MERGE INTO CONSULTAS FIN USING (SELECT '000957LisEjecPACREO' INFORME ,TO_CLOB(q'[SELECT SP.COMPANIA,
  SP.ID,  
  P.CODIGO,
  P.NOMBRE,
  P.ANO,
  P.CENTRO_COSTO,
  P.AUXILIAR,
  P.REFERENCIA,
  P.FUENTE_RECURSO,
  SUM(CASE WHEN P.NATURALEZA='D' THEN SP.MODIF_PAC_DEBITO ELSE SP.MODIF_PAC_CREDITO END) AS MODIFADICION,
  SUM(CASE WHEN P.NATURALEZA='D' THEN SP.MODIF_PAC_CREDITO ELSE SP.MODIF_PAC_DEBITO END) AS MODIFREDUCCION,    
  SUM(SP.PAC_APROPIADO) AS PAC_APROPIADO,
  s$columnas$s   
  SUM(SP.PAC_APROPIADO) + SUM(CASE WHEN P.NATURALEZA='D' THEN (SP.MODIF_PAC_DEBITO - SP.MODIF_PAC_CREDITO) ELSE (SP.MODIF_PAC_CREDITO - MODIF_PAC_DEBITO) END) AS PACDEFINITIVO
FROM V_PLAN_PRESUPUESTAL P
INNER JOIN V_SALDO_PLAN_PPTAL SP
ON (P.COMPANIA = SP.COMPANIA)
AND (P.ANO = SP.ANO)
AND (P.ID = SP.ID)
WHERE SP.COMPANIA = s$compania$s
AND SP.ANO = s$anio$s
AND SP.MES <= s$mes$s
AND SP.ID >= s$cuentaInicial$s AND SP.ID <= s$cuentaFinal$s
  s$centroCosto$s
  s$auxiliar$s
  s$referencia$s
  s$fuenteRecurso$s
GROUP BY SP.COMPANIA,
  SP.ID,  
  P.CODIGO,
  P.NOMBRE,
  P.ANO,
  P.CENTRO_COSTO,
  P.AUXILIAR,
  P.REFERENCIA,
  P.FUENTE_RECURSO]') CONSULTA, 3 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, 'MROSERO' CREATED_BY, '19/07/22 08:29:53,000000000 PM' MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);