SELECT 
  DCP.AUXILIAR CODAUXILIAR,
  DCP.CENTRO_COSTO CODCENTROCOSTO,
  DCP.SUCURSAL CODSUCURSAL,
  DCP.TERCERO CODTERCERO,
  's$naturaleza$s' NATURALEZA,
  's$nombre$s' NOMBRE,
  TER.NOMBRE NOMTER,
  CASE WHEN 's$naturaleza$s' = 'D' THEN DCP.VALOR_DEBITO-DCP.VALOR_CREDITO ELSE DCP.VALOR_CREDITO-DCP.VALOR_DEBITO END VALORUNICO,
  DCP.COMPANIA,
  DCP.CUENTA CODIGO_CUENTA,
  DCP.COMPROBANTE, 
  DCP.FECHA,
 
  DCP.TIPO_CPTE,
  DCP.COMPROBANTE,
  CP.DESCRIPCION
FROM DETALLE_COMPROBANTE_PPTAL DCP 
  INNER JOIN CENTRO_COSTO CC 
     ON DCP.COMPANIA = CC.COMPANIA
    AND DCP.CENTRO_COSTO = CC.CODIGO
    AND DCP.ANO = CC.ANO
  INNER JOIN TERCERO TER 
     ON DCP.COMPANIA = TER.COMPANIA
    AND DCP.TERCERO = TER.NIT
    AND DCP.SUCURSAL = TER.SUCURSAL
  INNER JOIN AUXILIAR 
     ON DCP.COMPANIA = AUXILIAR.COMPANIA
    AND DCP.AUXILIAR = AUXILIAR.CODIGO
    AND DCP.ANO = AUXILIAR.ANO
  INNER JOIN COMPROBANTE_PPTAL CP 
     ON DCP.COMPANIA = CP.COMPANIA 
    AND DCP.ANO = CP.ANO
    AND DCP.TIPO_CPTE = CP.TIPO
    AND DCP.COMPROBANTE = CP.NUMERO
WHERE DCP.COMPANIA = s$compania$s
  AND SUBSTR(DCP.ID,0,LENGTH('s$codigo$s')) = 's$codigo$s' 
  AND LENGTH(DCP.ID) >= LENGTH('s$codigo$s') 
  AND DCP.ANO = s$anio$s
  AND  EXTRACT (MONTH FROM DCP.FECHA) BETWEEN s$mesInicial$s AND s$mesFinal$s
ORDER BY DCP.TIPO_CPTE, DCP.COMPROBANTE, DCP.FECHA, CP.FECHA 
