WITH LIBROREGISTROINGRESOSESP AS(
SELECT 
  SALDO_PLAN_PPTAL.COMPANIA,
  PLAN_PRESUPUESTAL.ANO,
  SALDO_PLAN_PPTAL.ID CUENTA,
  PLAN_PRESUPUESTAL.NOMBRE,
  SUM(CASE WHEN PLAN_PRESUPUESTAL.NATURALEZA='D' THEN APROPIACION_DEBITO-APROPIACION_CREDITO ELSE APROPIACION_CREDITO-APROPIACION_DEBITO END) AS APROPIADO,
  SUM(CASE WHEN PLAN_PRESUPUESTAL.NATURALEZA='D' THEN EJE_PPT_DEBITO-EJE_PPT_CREDITO ELSE (EJE_PPT_CREDITO-EJE_PPT_DEBITO)+MODIF_INGRESOS END) AS EJECUCIONPPT,
  SUM(SALDO_PLAN_PPTAL.ADICION)+SUM(CASE WHEN PLAN_PRESUPUESTAL.NATURALEZA='D' THEN TRASLADO_DEBITO-TRASLADO_CREDITO ELSE TRASLADO_CREDITO-TRASLADO_DEBITO END)+SUM(SALDO_PLAN_PPTAL.REDUCCION)+SUM(CASE WHEN PLAN_PRESUPUESTAL.NATURALEZA='D'THEN APLAZAM_DEBITO    -APLAZAM_CREDITO ELSE APLAZAM_CREDITO-APLAZAM_DEBITO END) MODIFICACIONACUM
FROM V_PLAN_PRESUPUESTAL PLAN_PRESUPUESTAL
INNER JOIN V_SALDO_PLAN_PPTAL SALDO_PLAN_PPTAL
ON PLAN_PRESUPUESTAL.COMPANIA      = SALDO_PLAN_PPTAL.COMPANIA
AND PLAN_PRESUPUESTAL.ANO          = SALDO_PLAN_PPTAL.ANO
AND PLAN_PRESUPUESTAL.ID           = SALDO_PLAN_PPTAL.ID
WHERE PLAN_PRESUPUESTAL.COMPANIA = s$compania$s
AND PLAN_PRESUPUESTAL.ANO        =s$anio$s
AND PLAN_PRESUPUESTAL.ID
  BETWEEN 's$cuentaInicial$s' AND 's$cuentaFinal$s'
AND SALDO_PLAN_PPTAL.MES <= s$mes$s
AND PLAN_PRESUPUESTAL.NATURALEZA='C'
GROUP BY
  SALDO_PLAN_PPTAL.COMPANIA,
  PLAN_PRESUPUESTAL.ANO,
  SALDO_PLAN_PPTAL.ID,
  PLAN_PRESUPUESTAL.NOMBRE
)

SELECT 
  SALDO_PLAN_PPTAL.COMPANIA,
  LIBROREGISTROINGRESOSESP.CUENTA,
  LIBROREGISTROINGRESOSESP.NOMBRE,
  LIBROREGISTROINGRESOSESP.APROPIADO,
  LIBROREGISTROINGRESOSESP.MODIFICACIONACUM,
  EJE_PPT_CREDITO-EJE_PPT_DEBITO+MODIF_INGRESOS AS EJECUCIONPPTMES,
  LIBROREGISTROINGRESOSESP.EJECUCIONPPT,
  LIBROREGISTROINGRESOSESP.APROPIADO + LIBROREGISTROINGRESOSESP.MODIFICACIONACUM - LIBROREGISTROINGRESOSESP.EJECUCIONPPT AS SALDOPORRECAUDAR
FROM LIBROREGISTROINGRESOSESP
LEFT JOIN V_SALDO_PLAN_PPTAL SALDO_PLAN_PPTAL
ON LIBROREGISTROINGRESOSESP.CUENTA    = SALDO_PLAN_PPTAL.ID
AND LIBROREGISTROINGRESOSESP.ANO      = SALDO_PLAN_PPTAL.ANO
AND LIBROREGISTROINGRESOSESP.COMPANIA = SALDO_PLAN_PPTAL.COMPANIA
WHERE SALDO_PLAN_PPTAL.MES  = s$mes$s
ORDER BY LIBROREGISTROINGRESOSESP.CUENTA
