SELECT DEPENDENCIA.NOMBRE DEPENDENCIA,
  TERSOLICITANTE.NOMBRE SOLICITANTE,
  TO_CHAR(DETALLE_COMPROBANTE_PPTAL.FECHA,'DD/MM/YYYY') DET_COMP_PPTALFECHA,
  PLAN_PRESUPUESTAL.NOMBRE PLAN_PPTAL_NOMBRE,
  DETALLE_COMPROBANTE_PPTAL.CUENTA CODIGO_CUENTA,
  TERCERO.NIT,
  LUGAR.NOMBRE LUGAR,
  TERCERO.NOMBRE NOMBRETERCERO,
  DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE,
  DETALLE_COMPROBANTE_PPTAL.COMPROBANTE,
  SUM(DETALLE_COMPROBANTE_PPTAL.MODIFICACION_DEBITO) MODIFICACION_DEBITO1,
  SUM(DETALLE_COMPROBANTE_PPTAL.MODIFICACION_CREDITO) MODIFICACION_CREDITO1,
  DETALLE_COMPROBANTE_PPTAL.COMPANIA,
  SUM(
  CASE
    WHEN TIPO_COMPROBPP.CLASE NOT IN ('EGR')
    THEN (
      CASE
        WHEN PLAN_PRESUPUESTAL.NATURALEZA='D'
        THEN DETALLE_COMPROBANTE_PPTAL.VALOR_DEBITO  -DETALLE_COMPROBANTE_PPTAL.VALOR_CREDITO-(DETALLE_COMPROBANTE_PPTAL.DEBITO_AFECTADO-DETALLE_COMPROBANTE_PPTAL.CREDITO_AFECTADO)+(DETALLE_COMPROBANTE_PPTAL.MODIFICACION_DEBITO-DETALLE_COMPROBANTE_PPTAL.MODIFICACION_CREDITO)
        ELSE (DETALLE_COMPROBANTE_PPTAL.VALOR_CREDITO-DETALLE_COMPROBANTE_PPTAL.VALOR_DEBITO)-(DETALLE_COMPROBANTE_PPTAL.CREDITO_AFECTADO-DETALLE_COMPROBANTE_PPTAL.DEBITO_AFECTADO)+(DETALLE_COMPROBANTE_PPTAL.MODIFICACION_CREDITO-DETALLE_COMPROBANTE_PPTAL.MODIFICACION_DEBITO)
      END)
    ELSE 0
  END) SALDOPOREJECUTAR,
  PROYECTOS_PPTAL.NOMBRE PROYECTOS_PPTALNOMBRE,
  COMPROBANTE_PPTAL.COD_PROYECTO_PPTAL,
  DETALLE_COMPROBANTE_PPTAL.DESCRIPCION,
  SUM(DETALLE_COMPROBANTE_PPTAL.VALOR_DEBITO) VALORDEBITO,
  SUM(DETALLE_COMPROBANTE_PPTAL.VALOR_CREDITO) VALORCREDITO
FROM DETALLE_COMPROBANTE_PPTAL
INNER JOIN COMPROBANTE_PPTAL
ON DETALLE_COMPROBANTE_PPTAL.COMPANIA     = COMPROBANTE_PPTAL.COMPANIA
AND DETALLE_COMPROBANTE_PPTAL.ANO         = COMPROBANTE_PPTAL.ANO
AND DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE   = COMPROBANTE_PPTAL.TIPO
AND DETALLE_COMPROBANTE_PPTAL.COMPROBANTE = COMPROBANTE_PPTAL.NUMERO
LEFT JOIN PLAN_PRESUPUESTAL
ON DETALLE_COMPROBANTE_PPTAL.COMPANIA       = PLAN_PRESUPUESTAL.COMPANIA
AND DETALLE_COMPROBANTE_PPTAL.ANO           = PLAN_PRESUPUESTAL.ANO
AND DETALLE_COMPROBANTE_PPTAL.CUENTA        = PLAN_PRESUPUESTAL.CODIGO
LEFT JOIN TIPO_COMPROBPP
ON  DETALLE_COMPROBANTE_PPTAL.COMPANIA   = TIPO_COMPROBPP.COMPANIA
AND DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE = TIPO_COMPROBPP.CODIGO
LEFT JOIN TERCERO
ON DETALLE_COMPROBANTE_PPTAL.COMPANIA  = TERCERO.COMPANIA
AND DETALLE_COMPROBANTE_PPTAL.TERCERO  = TERCERO.NIT
AND DETALLE_COMPROBANTE_PPTAL.SUCURSAL = TERCERO.SUCURSAL
LEFT JOIN TERCERO TERSOLICITANTE
ON COMPROBANTE_PPTAL.COMPANIA        = TERSOLICITANTE.COMPANIA
AND COMPROBANTE_PPTAL.CODSOLICITANTE = TERSOLICITANTE.NIT
AND COMPROBANTE_PPTAL.SUCSOLICITANTE = TERSOLICITANTE.SUCURSAL
LEFT JOIN PROYECTOS_PPTAL
ON COMPROBANTE_PPTAL.COMPANIA            = PROYECTOS_PPTAL.COMPANIA
AND COMPROBANTE_PPTAL.ANO                = PROYECTOS_PPTAL.ANO
AND COMPROBANTE_PPTAL.COD_PROYECTO_PPTAL = PROYECTOS_PPTAL.CODIGO
LEFT JOIN DEPENDENCIA
ON COMPROBANTE_PPTAL.DEPENDENCIA = DEPENDENCIA.CODIGO
AND COMPROBANTE_PPTAL.COMPANIA   = DEPENDENCIA.COMPANIA
LEFT JOIN LUGAR
ON COMPROBANTE_PPTAL.COMPANIA            = LUGAR.COMPANIA
AND COMPROBANTE_PPTAL.LUGAR              = LUGAR.CODIGO
WHERE DETALLE_COMPROBANTE_PPTAL.COMPANIA = s$compania$s
AND COMPROBANTE_PPTAL.COD_PROYECTO_PPTAL BETWEEN 's$proyectoInicial$s' AND 's$proyectoFinal$s'
AND DETALLE_COMPROBANTE_PPTAL.FECHA      BETWEEN s$fechaInicial$s AND s$fechaFinal$s
AND COMPROBANTE_PPTAL.TIPO               BETWEEN 's$tipoInicial$s' AND 's$tipoFinal$s'
AND DETALLE_COMPROBANTE_PPTAL.CUENTA     BETWEEN 's$cuentaInicial$s' AND 's$cuentaFinal$s'
AND DETALLE_COMPROBANTE_PPTAL.TERCERO    BETWEEN 's$terceroInicial$s' AND 's$terceroFinal$s'
GROUP BY DEPENDENCIA.NOMBRE,
  TERSOLICITANTE.NOMBRE,
  DETALLE_COMPROBANTE_PPTAL.FECHA,
  PLAN_PRESUPUESTAL.NOMBRE,
  DETALLE_COMPROBANTE_PPTAL.CUENTA,
  TERCERO.NIT,
  LUGAR.NOMBRE,
  TERCERO.NOMBRE,
  DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE,
  DETALLE_COMPROBANTE_PPTAL.COMPROBANTE,
  DETALLE_COMPROBANTE_PPTAL.COMPANIA,
  PROYECTOS_PPTAL.NOMBRE,
  COMPROBANTE_PPTAL.COD_PROYECTO_PPTAL,
  DETALLE_COMPROBANTE_PPTAL.DESCRIPCION
