SELECT V_SALDO_PLAN_PPTAL.COMPANIA,
  V_SALDO_PLAN_PPTAL.CODIGO CUENTA,
  V_PLAN_PRESUPUESTAL.NOMBRE,
  LPAD(V_SALDO_PLAN_PPTAL.CODIGO, 1) CLASE,
  SUM(APROPIACION_DEBITO  - APROPIACION_CREDITO) APROPIACIONINICIAL,
  SUM((V_SALDO_PLAN_PPTAL.ADICION + V_SALDO_PLAN_PPTAL.TRASLADO_DEBITO + V_SALDO_PLAN_PPTAL.REDUCCION) - (V_SALDO_PLAN_PPTAL.TRASLADO_CREDITO)) CANCELACIONESF,
  SUM((APROPIACION_DEBITO  - APROPIACION_CREDITO) + (V_SALDO_PLAN_PPTAL.ADICION + V_SALDO_PLAN_PPTAL.TRASLADO_DEBITO + V_SALDO_PLAN_PPTAL.REDUCCION) - (V_SALDO_PLAN_PPTAL.TRASLADO_CREDITO)) RESERVADEFINITIVAF,
  SUM(EJE_PPT_DEBITO - EJE_PPT_CREDITO)  PAGOSACUMF,
  SUM(((APROPIACION_DEBITO  - APROPIACION_CREDITO) + (V_SALDO_PLAN_PPTAL.ADICION + V_SALDO_PLAN_PPTAL.TRASLADO_DEBITO + V_SALDO_PLAN_PPTAL.REDUCCION) - (V_SALDO_PLAN_PPTAL.TRASLADO_CREDITO)) - (EJE_PPT_DEBITO - EJE_PPT_CREDITO)) SALDOAPAGARF
FROM V_PLAN_PRESUPUESTAL
	LEFT JOIN V_SALDO_PLAN_PPTAL
	        ON V_PLAN_PRESUPUESTAL.COMPANIA   = V_SALDO_PLAN_PPTAL.COMPANIA
	      AND V_PLAN_PRESUPUESTAL.ANO             = V_SALDO_PLAN_PPTAL.ANO
	      AND V_PLAN_PRESUPUESTAL.ID                 = V_SALDO_PLAN_PPTAL.ID
WHERE V_SALDO_PLAN_PPTAL.COMPANIA	= s$compania$s
  AND V_SALDO_PLAN_PPTAL.ANO       	 	= s$ano$s
  AND V_SALDO_PLAN_PPTAL.MES BETWEEN 0 AND s$mes$s
  AND V_PLAN_PRESUPUESTAL.NATURALEZA   = 'D'
  AND V_PLAN_PRESUPUESTAL.INFORME NOT IN (0)
  AND V_SALDO_PLAN_PPTAL.ID BETWEEN 's$cuentaInicial$s' AND 's$cuentaFinal$s' 
  AND V_PLAN_PRESUPUESTAL.TIPOVIGENCIA IN('RA')
  AND LENGTH(V_PLAN_PRESUPUESTAL.ID) BETWEEN 0 AND NVL(s$nivel$s, 6)
GROUP BY V_SALDO_PLAN_PPTAL.COMPANIA,
  V_SALDO_PLAN_PPTAL.ANO,
  V_SALDO_PLAN_PPTAL.CODIGO,
  V_PLAN_PRESUPUESTAL.NOMBRE,
  V_PLAN_PRESUPUESTAL.APROPIACIONINICIAL,
  LENGTH(V_PLAN_PRESUPUESTAL.ID),
  V_PLAN_PRESUPUESTAL.NATURALEZA
