SELECT TIPO_COMPROBPP.COMPANIA,
  TIPO_COMPROBPP.CODIGO, 
  TIPO_COMPROBPP.NOMBRE, 
  TIPO_COMPROBPP.FORMATO, 
  CLASECNTPRES.DESCRIPCION 
FROM CLASECNTPRES 
 INNER JOIN TIPO_COMPROBPP  
  ON CLASECNTPRES.CODIGO = TIPO_COMPROBPP.CLASE 
 INNER JOIN COMPANIA 
  ON COMPANIA.CODIGO = TIPO_COMPROBPP.COMPANIA 
WHERE TIPO_COMPROBPP.COMPANIA = s$compania$s
