SELECT COMPANIA,
  ANO,
  TIPO,
  COMPROBANTE NUMERO,
  FECHA,
  TERCERO,
  SUCURSAL,
  TERCERO_COM_NOM NOMBRE,
  TIPO_COMPROBANTE_NOM  NOMBRETIPO,
  CUENTANOMBRE AS NOMBRECUENTA,
  DESCRIPCION,
  CUENTA,
  VALOR_CREDITO AS CONTRACREDITO,
  VALOR_DEBITO  AS CREDITO  
FROM V_DETALLE_AUXILIAR_PPTAL
WHERE COMPANIA = s$compania$s
    AND ANO    = s$ano$s
    AND TIPO   = 's$tipoCpte$s'
    AND COMPROBANTE BETWEEN s$numeroPptoInicial$s AND s$numeroPptoFinal$s
