SELECT TIPO_COMPROBPP.NOMBRE as TIPO_COMPROBPP_NOMBRE,
  DETALLE_COMPROBANTE_PPTAL.COMPROBANTE,
  COMPROBANTE_PPTAL.FECHA,
  COMPROBANTE_PPTAL.TERCERO,
  COMPROBANTE_PPTAL.SUCURSAL,
  TERCERO_1.NOMBRE as TERCERO_NOMBRE,
  DETALLE_COMPROBANTE_PPTAL.DESCRIPCION,
  DETALLE_COMPROBANTE_PPTAL.CUENTA as codigo_cuenta,
  V_PLAN_PRESUPUESTAL.NOMBRE as PLAN_PRESUPUESTAL_NOMBRE,
  DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE,
  CASE
    WHEN DETALLE_COMPROBANTE_PPTAL.VALOR_DEBITO = 0
      THEN DETALLE_COMPROBANTE_PPTAL.VALOR_CREDITO
    ELSE DETALLE_COMPROBANTE_PPTAL.VALOR_DEBITO
  END VALORCOMPROBANTE
FROM ((COMPROBANTE_PPTAL
  INNER JOIN TIPO_COMPROBPP
    ON COMPROBANTE_PPTAL.COMPANIA = TIPO_COMPROBPP.COMPANIA
    AND COMPROBANTE_PPTAL.TIPO = TIPO_COMPROBPP.CODIGO)
      LEFT JOIN TERCERO TERCERO_1
      ON COMPROBANTE_PPTAL.COMPANIA = TERCERO_1.COMPANIA
      AND COMPROBANTE_PPTAL.TERCERO = TERCERO_1.NIT
      AND  COMPROBANTE_PPTAL.SUCURSAL = TERCERO_1.SUCURSAL)
        LEFT JOIN (((DETALLE_COMPROBANTE_PPTAL
            Left JOIN TERCERO
              ON TERCERO.COMPANIA = DETALLE_COMPROBANTE_PPTAL.COMPANIA
              AND TERCERO.NIT = DETALLE_COMPROBANTE_PPTAL.TERCERO
              AND TERCERO.SUCURSAL = DETALLE_COMPROBANTE_PPTAL.SUCURSAL)
                LEFT JOIN DETALLE_COMPROBANTE_PPTAL DETALLE_COMPROBANTE_PPTAL_1
                  ON DETALLE_COMPROBANTE_PPTAL.COMPANIA = DETALLE_COMPROBANTE_PPTAL_1.COMPANIA
                  AND DETALLE_COMPROBANTE_PPTAL.ANO = DETALLE_COMPROBANTE_PPTAL_1.ANO
                  AND DETALLE_COMPROBANTE_PPTAL.CUENTA = DETALLE_COMPROBANTE_PPTAL_1.CUENTA
                  AND DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE_AFECT = DETALLE_COMPROBANTE_PPTAL_1.TIPO_CPTE
                  AND DETALLE_COMPROBANTE_PPTAL.CMPTE_AFECTADO = DETALLE_COMPROBANTE_PPTAL_1.COMPROBANTE
                  AND DETALLE_COMPROBANTE_PPTAL.CONSECUTIVOPPTO = DETALLE_COMPROBANTE_PPTAL_1.CONSECUTIVO) 
                  LEFT JOIN V_PLAN_PRESUPUESTAL
                    ON DETALLE_COMPROBANTE_PPTAL.COMPANIA = V_PLAN_PRESUPUESTAL.COMPANIA
                    AND DETALLE_COMPROBANTE_PPTAL.ID = V_PLAN_PRESUPUESTAL.ID
                    AND DETALLE_COMPROBANTE_PPTAL.ANO = V_PLAN_PRESUPUESTAL.ANO) 
          ON COMPROBANTE_PPTAL.COMPANIA = DETALLE_COMPROBANTE_PPTAL.COMPANIA
          AND COMPROBANTE_PPTAL.ANO = DETALLE_COMPROBANTE_PPTAL.ANO
          AND COMPROBANTE_PPTAL.TIPO = DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE
          AND COMPROBANTE_PPTAL.NUMERO = DETALLE_COMPROBANTE_PPTAL.COMPROBANTE
WHERE DETALLE_COMPROBANTE_PPTAL.COMPROBANTE IS NOT NULL
  AND COMPROBANTE_PPTAL.COMPANIA = s$compania$s
  AND COMPROBANTE_PPTAL.ANO = 's$ano$s'
  AND COMPROBANTE_PPTAL.TIPO = 's$tipoCpte$s'
  AND COMPROBANTE_PPTAL.NUMERO BETWEEN 's$numeroPptoInicial$s' AND 's$numeroPptoFinal$s'
