SELECT 
   V_DETALLE.COMPROBANTE
  ,V_DETALLE.TIPO_COMPROBANTE_NOM 
  ,V_DETALLE.FECHA
  ,V_DETALLE.TERCERO_COM_NOM
  ,V_DETALLE.TERCERO_COM
  ,V_DETALLE.DESCRIPCION_DET
  ,V_DETALLE.TIPO
  ,V_DETALLE.CUENTA
  ,V_DETALLE.CUENTANOMBRE
  ,V_DETALLE.TIPO_CPTE_AFECT
  ,V_DETALLE.CMPTE_AFECTADO
  ,V_DETALLE.VALOR_DEBITO
  ,V_DETALLE.VALOR_CREDITO
  ,(V_DETALLE.VALOR_DEBITO        - V_DETALLE.VALOR_CREDITO       ) + 
   (V_DETALLE.MODIFICACION_DEBITO - V_DETALLE.MODIFICACION_CREDITO) - 
   (V_DETALLE.DEBITO_AFECTADO     - V_DETALLE.CREDITO_AFECTADO    ) VALORDISPONIBLE
FROM V_DETALLE_AUXILIAR_PPTAL V_DETALLE
WHERE V_DETALLE.COMPANIA    = s$compania$s
  AND V_DETALLE.ANO         = s$ano$s
  AND V_DETALLE.TIPO        = 's$tipoCpte$s'
  AND V_DETALLE.COMPROBANTE BETWEEN s$numeroPptoInicial$s  AND s$numeroPptoFinal$s
