SELECT 
  V_PLAN_PRESUPUESTAL.ID CUENTA,
  V_PLAN_PRESUPUESTAL.FUENTE_RECURSO,  
  V_PLAN_PRESUPUESTAL.NOMBRE,  
  SUM(SALDOS.APROPIADO)       APROPIADO,
  SUM(SALDOS.ADICION)         ADICION,
  SUM(SALDOS.REDUCCION)       REDUCCION,  
  SUM(SALDOS.CREDITOS)        CREDITOS,
  SUM(SALDOS.CONTRACREDITOS)  CONTRACREDITOS,
  SUM(SALDOS.APLAZAMIENTOS)   APLAZAMIENTOS,
  SUM(SALDOS.DESAPLAZAMIENTO) DESAPLAZAMIENTO,
  SUM(SALDOS.TOTALAPROPIADO)  TOTALAPROPIADO,
  SUM(SALDOS.DISPONIBILIDADMES) DISPONIBILIDADMES,
  SUM(SALDOS.DISPONIBILIDADES) DISPONIBILIDADES,
  SUM(SALDOS.REGISTROSMES) RESERVASMES,
  SUM(SALDOS.REGISTROS) RESERVASACUM,
  SUM(SALDOS.OBLIGACIONESMES) REGISTROOBLIGACIONMES,
  SUM(SALDOS.OBLIGACIONES) REGISACUM,
  SUM(SALDOS.PAGOSANTERIORES) PAGOSANTERIORES,
  SUM(SALDOS.PAGOSMES) PAGOSMES,
  SUM(SALDOS.PAGOSTOTALES) PAGOSACUMULADOS,
  SUM(SALDOS.TOTALAPROPIADO -SALDOS.APROPIADO ) MODIFICACIONES
FROM V_PLAN_PRESUPUESTAL INNER JOIN
(
SELECT 
  SALDO_AUX_PPTAL.COMPANIA,
  SALDO_AUX_PPTAL.ANO,
  SALDO_AUX_PPTAL.ID,
  SALDO_AUX_PPTAL.FUENTE_RECURSO,  

  SUM(CASE WHEN SALDO_AUX_PPTAL.NATURALEZA='D' 
           THEN APROPIACION_DEBITO - APROPIACION_CREDITO 
           ELSE APROPIACION_CREDITO - APROPIACION_DEBITO 
           END)  APROPIADO,
  SUM(SALDO_AUX_PPTAL.ADICION)   ADICION,
  SUM(SALDO_AUX_PPTAL.REDUCCION) REDUCCION,    
  
  SUM(SALDO_AUX_PPTAL.TRASLADO_DEBITO) CREDITOS,    
  SUM(SALDO_AUX_PPTAL.TRASLADO_CREDITO) CONTRACREDITOS,      
  
  SUM(CASE WHEN SALDO_AUX_PPTAL.NATURALEZA='D' 
      THEN APLAZAM_CREDITO ELSE APLAZAM_DEBITO END)  APLAZAMIENTOS,
  
  SUM(CASE WHEN SALDO_AUX_PPTAL.NATURALEZA='D' 
      THEN APLAZAM_DEBITO ELSE APLAZAM_CREDITO END)  DESAPLAZAMIENTO,      
  
  SUM(CASE WHEN SALDO_AUX_PPTAL.NATURALEZA='D' 
      THEN APLAZAM_DEBITO     - APLAZAM_CREDITO     
      ELSE APLAZAM_CREDITO    - APLAZAM_DEBITO     END)  APLAZAMIENTOFINAL,
  
  SUM(CASE WHEN SALDO_AUX_PPTAL.NATURALEZA='D' THEN APROPIACION_DEBITO - APROPIACION_CREDITO ELSE APROPIACION_CREDITO - APROPIACION_DEBITO END
      + SALDO_AUX_PPTAL.ADICION + SALDO_AUX_PPTAL.REDUCCION  
      + CASE WHEN SALDO_AUX_PPTAL.NATURALEZA='D' THEN APLAZAM_DEBITO     - APLAZAM_CREDITO     ELSE APLAZAM_CREDITO     - APLAZAM_DEBITO     END  
      + CASE WHEN SALDO_AUX_PPTAL.NATURALEZA='D' THEN TRASLADO_DEBITO    - TRASLADO_CREDITO    ELSE TRASLADO_CREDITO    - TRASLADO_DEBITO     END
  ) TOTALAPROPIADO,
  
  SUM(CASE WHEN SALDO_AUX_PPTAL.MES = s$mes$s THEN SALDO_AUX_PPTAL.DISPONIBILIDAD ELSE 0 END) DISPONIBILIDADMES,

  SUM(SALDO_AUX_PPTAL.DISPONIBILIDAD) DISPONIBILIDADES,

  SUM(SALDO_AUX_PPTAL.REG_CONTRACT + SALDO_AUX_PPTAL.REG_NO_CONTRACT 
    + SALDO_AUX_PPTAL.MODIF_REG_CONT + SALDO_AUX_PPTAL.MODIF_REG_NOCONT    
  ) REGISTROS,

  SUM(CASE WHEN SALDO_AUX_PPTAL.MES = s$mes$s THEN SALDO_AUX_PPTAL.REG_CONTRACT + SALDO_AUX_PPTAL.REG_NO_CONTRACT 
                                                 + SALDO_AUX_PPTAL.MODIF_REG_CONT + SALDO_AUX_PPTAL.MODIF_REG_NOCONT ELSE 0 END) REGISTROSMES,
  
  SUM(CASE WHEN SALDO_AUX_PPTAL.NATURALEZA='D' THEN EJE_PPT_DEBITO-EJE_PPT_CREDITO ELSE EJE_PPT_CREDITO-EJE_PPT_DEBITO END + 
  SALDO_AUX_PPTAL.MODIF_INGRESOS_EFECTIVO +
  SALDO_AUX_PPTAL.MODIF_INGRESOS_PAPELES)  AS PAGOSTOTALES,  
  
  
  SUM(CASE WHEN SALDO_AUX_PPTAL.MES = s$mes$s THEN
  (CASE WHEN SALDO_AUX_PPTAL.NATURALEZA='D' THEN EJE_PPT_DEBITO-EJE_PPT_CREDITO ELSE EJE_PPT_CREDITO-EJE_PPT_DEBITO END) + 
  SALDO_AUX_PPTAL.MODIF_INGRESOS_EFECTIVO +
  SALDO_AUX_PPTAL.MODIF_INGRESOS_PAPELES  ELSE 0 END) AS PAGOSMES,

  SUM(CASE WHEN SALDO_AUX_PPTAL.MES < s$mes$s THEN
  (CASE WHEN SALDO_AUX_PPTAL.NATURALEZA='D' THEN EJE_PPT_DEBITO-EJE_PPT_CREDITO ELSE EJE_PPT_CREDITO-EJE_PPT_DEBITO END) + 
  SALDO_AUX_PPTAL.MODIF_INGRESOS_EFECTIVO +
  SALDO_AUX_PPTAL.MODIF_INGRESOS_PAPELES  ELSE 0 END) AS PAGOSANTERIORES,

  SUM(CASE WHEN SALDO_AUX_PPTAL.MES = s$mes$s THEN SALDO_AUX_PPTAL.REGISTRO_OBLIGACION + SALDO_AUX_PPTAL.MODIF_REGISTRO_OBLIGACION ELSE 0 END) OBLIGACIONESMES,
  SUM(SALDO_AUX_PPTAL.REGISTRO_OBLIGACION + SALDO_AUX_PPTAL.MODIF_REGISTRO_OBLIGACION) OBLIGACIONES
  
FROM  SALDO_AUX_PPTAL 
WHERE SALDO_AUX_PPTAL.COMPANIA = s$compania$s
AND SALDO_AUX_PPTAL.ANO        = s$anio$s
AND SALDO_AUX_PPTAL.MES       <= s$mes$s
AND SALDO_AUX_PPTAL.ID BETWEEN 's$cuentaInicial$s' AND 's$cuentaFinal$s'
AND SALDO_AUX_PPTAL.NATURALEZA = 'D'
GROUP BY SALDO_AUX_PPTAL.COMPANIA,
  SALDO_AUX_PPTAL.ANO,
  SALDO_AUX_PPTAL.ID,
  SALDO_AUX_PPTAL.FUENTE_RECURSO
) SALDOS
 ON V_PLAN_PRESUPUESTAL.COMPANIA = SALDOS.COMPANIA
AND V_PLAN_PRESUPUESTAL.ANO      = SALDOS.ANO
AND V_PLAN_PRESUPUESTAL.ID       = SUBSTR(SALDOS.ID, 1, LENGTH(V_PLAN_PRESUPUESTAL.ID))
GROUP BY V_PLAN_PRESUPUESTAL.COMPANIA,  
         V_PLAN_PRESUPUESTAL.ID ,
         V_PLAN_PRESUPUESTAL.CODIGO,
         V_PLAN_PRESUPUESTAL.NOMBRE,
         V_PLAN_PRESUPUESTAL.FUENTE_RECURSO
ORDER BY V_PLAN_PRESUPUESTAL.COMPANIA,
         V_PLAN_PRESUPUESTAL.ID
