SELECT VDPPTAL.COMPANIA,
  VDPPTAL.NOMBRE_DEP,
  VDPPTAL.CARGO,
  VDPPTAL.CUENTA,
  VDPPTAL.CUENTANOMBRE,
  VDPPTAL.DESCRIPCION,
  COMPROBANTE_PPTAL.FECHA_VENCIMIENTO,
  VDPPTAL.VALOR_DEBITO,
  VDPPTAL.SALDO SALDOCUENTA,
  VDPPTAL.TERCERO,
  VDPPTAL.COMPROBANTE,
  VDPPTAL.FECHA,
  VDPPTAL.TERCERO_COM_NOM,
  PLAN_PRESUPUESTAL.NOMBRE,
  VDPPTAL.TIPO,
  VDPPTAL.SUCURSAL
FROM V_DETALLE_AUXILIAR_PPTAL VDPPTAL
INNER JOIN COMPROBANTE_PPTAL 
    ON VDPPTAL.COMPANIA =  COMPROBANTE_PPTAL.COMPANIA
    AND VDPPTAL.ANO = COMPROBANTE_PPTAL.ANO
    AND VDPPTAL.TIPO = COMPROBANTE_PPTAL.TIPO
    AND VDPPTAL.COMPROBANTE = COMPROBANTE_PPTAL.NUMERO
  INNER JOIN PLAN_PRESUPUESTAL 
    ON VDPPTAL.COMPANIA = PLAN_PRESUPUESTAL.COMPANIA
    AND VDPPTAL.ANO = PLAN_PRESUPUESTAL.ANO
    AND VDPPTAL.CUENTA = PLAN_PRESUPUESTAL.CODIGO
WHERE VDPPTAL.COMPANIA = s$compania$s
  AND VDPPTAL.ANO =s$ano$s
 AND VDPPTAL.TIPO ='s$tipoCpte$s'
 AND VDPPTAL.COMPROBANTE BETWEEN s$numeroPptoInicial$s AND s$numeroPptoFinal$s

