WITH LISEJECUCIONINGRESOS_PAES AS
  (SELECT V_RESUMENPPTO_BASE.COMPANIA,
    V_RESUMENPPTO_BASE.ANO,
    V_RESUMENPPTO_BASE.ID CUENTA,
    SUM(V_RESUMENPPTO_BASE.APROPIADO)      AS APROPIADO,
    SUM(V_RESUMENPPTO_BASE.APLAZAMIENTO)   AS APLAZAMIENTO,
    SUM(V_RESUMENPPTO_BASE.TRASLADO)       AS TRASLADO,
    SUM(V_RESUMENPPTO_BASE.ADICION)        AS ADICION,
    SUM(ABS(V_RESUMENPPTO_BASE.REDUCCION)) AS REDUCCION,
    V_RESUMENPPTO_BASE.NATURALEZA,
    V_RESUMENPPTO_BASE.CODIGO,
    V_RESUMENPPTO_BASE.NOMBRE,
    SUM(V_RESUMENPPTO_BASE.ADICION + V_RESUMENPPTO_BASE.TRASLADO + V_RESUMENPPTO_BASE.REDUCCION + V_RESUMENPPTO_BASE.APLAZAMIENTO) AS MODIFICACIONES,
    SUM(V_RESUMENPPTO_BASE.APROPIACIONVIGENTE)                                                                                     AS TOTALPRESUPUESTO,
    SUM(V_RESUMENPPTO_BASE.EJECUCIONPPT        +V_RESUMENPPTO_BASE.TOTALMODIFINGRESOS)                                                    AS RECAUDOSACUMULADOS,
    SUM(V_RESUMENPPTO_BASE.APROPIACIONVIGENTE) -SUM(V_RESUMENPPTO_BASE.EJECUCIONPPT +V_RESUMENPPTO_BASE.TOTALMODIFINGRESOS)               AS PORRECAUDAR,
    SUM(V_RESUMENPPTO_BASE.TRASLADO_DEBITO     +V_RESUMENPPTO_BASE.APLAZAM_DEBITO)                                                        AS CREDITOS,
    SUM(V_RESUMENPPTO_BASE.TRASLADO_CREDITO    +V_RESUMENPPTO_BASE.APLAZAM_CREDITO)                                                       AS CONTRACREDITOS
  FROM V_RESUMENPPTO_BASE
  WHERE V_RESUMENPPTO_BASE.COMPANIA = s$compania$s
  AND V_RESUMENPPTO_BASE.ANO        =s$ano$s
  AND V_RESUMENPPTO_BASE.MES BETWEEN 0 AND s$mes$s
  AND V_RESUMENPPTO_BASE.ID BETWEEN 's$codigoInicial$s' AND 's$codigoFinal$s'
  AND V_RESUMENPPTO_BASE.NATURALEZA='C'
  GROUP BY V_RESUMENPPTO_BASE.COMPANIA,
    V_RESUMENPPTO_BASE.ANO,
    V_RESUMENPPTO_BASE.ID,
    V_RESUMENPPTO_BASE.NATURALEZA,
    V_RESUMENPPTO_BASE.CODIGO,
    V_RESUMENPPTO_BASE.NOMBRE
  ORDER BY V_RESUMENPPTO_BASE.COMPANIA,
    V_RESUMENPPTO_BASE.ANO,
    V_RESUMENPPTO_BASE.ID
  )
SELECT LISEJECUCIONINGRESOS_PAES.COMPANIA,
 LISEJECUCIONINGRESOS_PAES.CUENTA,
  LISEJECUCIONINGRESOS_PAES.NOMBRE,
  LISEJECUCIONINGRESOS_PAES.APROPIADO,
  LISEJECUCIONINGRESOS_PAES.ADICION,
  LISEJECUCIONINGRESOS_PAES.REDUCCION,
  LISEJECUCIONINGRESOS_PAES.CREDITOS,
  LISEJECUCIONINGRESOS_PAES.CONTRACREDITOS,
  LISEJECUCIONINGRESOS_PAES.TOTALPRESUPUESTO,
  LISEJECUCIONINGRESOS_PAES.RECAUDOSACUMULADOS,
  LISEJECUCIONINGRESOS_PAES.PORRECAUDAR,
  V_SALDO_PLAN_PPTAL.EJE_PPT_CREDITO - V_SALDO_PLAN_PPTAL.EJE_PPT_DEBITO+ V_SALDO_PLAN_PPTAL.MODIF_INGRESOS_EFECTIVO+V_SALDO_PLAN_PPTAL.MODIF_INGRESOS_PAPELES AS RECAUDOSMES
FROM LISEJECUCIONINGRESOS_PAES
LEFT JOIN V_SALDO_PLAN_PPTAL
ON LISEJECUCIONINGRESOS_PAES.COMPANIA                                                                                                                              = V_SALDO_PLAN_PPTAL.COMPANIA
AND LISEJECUCIONINGRESOS_PAES.ANO                                                                                                                                  = V_SALDO_PLAN_PPTAL.ANO
AND LISEJECUCIONINGRESOS_PAES.CUENTA                                                                                                                               = V_SALDO_PLAN_PPTAL.ID
WHERE APROPIADO+ABS(MODIFICACIONES)+TOTALPRESUPUESTO+RECAUDOSACUMULADOS+PORRECAUDAR+(EJE_PPT_CREDITO-EJE_PPT_DEBITO+MODIF_INGRESOS_EFECTIVO+MODIF_INGRESOS_PAPELES)>0
AND V_SALDO_PLAN_PPTAL.MES                                                                                                                                         =s$mes$s
ORDER BY LISEJECUCIONINGRESOS_PAES.COMPANIA,
  LISEJECUCIONINGRESOS_PAES.ANO,
  LISEJECUCIONINGRESOS_PAES.CUENTA 
