 SELECT 
CUENTA CODIGO,
NOMBRE, 
PPTODEFINITIVO PPTO_INICIAL,
ENE, 
FEB,
MAR, 
ABR, 
MAY,
JUN, 
JUL,
AGO,
SEP,
OCT, 
NOV, 
DIC,
(ENE+FEB+MAR+ABR+MAY+JUN+JUL+AGO+SEP+OCT+NOV+DIC) TOTAL_RECAUDOS, 
PPTODEFINITIVO - (ENE+FEB+MAR+ABR+MAY+JUN+JUL+AGO+SEP+OCT+NOV+DIC) SALDO_POR_RECAUDAR
FROM 
(s$consultaBase$s)
ORDER BY CUENTA
