MERGE INTO CONSULTAS FIN USING (SELECT '001814LisDispAbiertasF_Excel' INFORME ,TO_CLOB(q'[SELECT
    RUBRO,
    AUXILIAR "AUXILIAR GENERAL",
    CENTRO_COSTO "CENTRO DE COSTO",
    REFERENCIA,
    FUENTE_RECURSO "FUENTE DE RECURSOS",
    NOMBREPLAN NOMBRE,
    TIPO_CPTE TIPO,
    TO_CHAR(COMPROBANTE) COMPROBANTE,
    TO_CHAR(FECHA,'DD/MM/YYYY') FECHA,
    CODTERCERO TERCERO,
    CODSUCURSAL SUCURSAL,
    NOMBRETERCERO NOMBRE_TERCERO,
    DESCRIPCION,
    MOVIMIENTO,
    MODIFICACION,
    AFECTACION,
    SALDO
FROM
    (s$consultaBase$s)
ORDER BY TIPO_CPTE, RUBRO, COMPROBANTE, FECHA]') CONSULTA, 3 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, 'MPEREZ' MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);
