MERGE INTO CONSULTAS FIN USING (SELECT '001904Ejec_Gastos_comparativa' INFORME ,TO_CLOB(q'[SELECT 
  V_PLAN_PRESUPUESTAL.COMPANIA,
  V_PLAN_PRESUPUESTAL.ANO,
  V_PLAN_PRESUPUESTAL.CODIGO,
  V_PLAN_PRESUPUESTAL.ID CUENTA,
  V_PLAN_PRESUPUESTAL.NOMBRE,  
  V_PLAN_PRESUPUESTAL.NATURALEZA,
  V_PLAN_PRESUPUESTAL.FUENTE_RECURSO,  
  SUM(SALDOS.APROPIADO)         APROPIADO,
  SUM(SALDOS.TOTALAPROPIADO)    TOTALAPROPIADO,
  SUM(SALDOS.DISPONIBILIDADMES) DISPONIBILIDADMES,
  SUM(SALDOS.DISPONIBILIDADMESANTERIOR) DISPONIBILIDADANTERIOR,
  SUM(SALDOS.DISPONIBILIDADES)  DISPONIBILIDADF,
  SUM(SALDOS.REGISTROSMES)      REGISTROSMES,
  SUM(SALDOS.REGISTROSMESANTERIOR) REGISTROSMESANT,
  PCK_SYSMAN_UTL.FC_ROUND(CASE WHEN SUM(SALDOS.REGISTROSMES) > 0 THEN ((SUM(SALDOS.REGISTROSMESANTERIOR)/SUM(SALDOS.REGISTROSMES))*100) ELSE 0 END, 2 ) VARRESMES,
  SUM(SALDOS.REGISTROS) REGISTROSF,
  SUM(SALDOS.TOTALAPROPIADO - SALDOS.DISPONIBILIDADES) SALDODISPONIBLE,
  SUM(SALDOS.TOTALAPROPIADO - SALDOS.REGISTROS)     SALDOPORCOMPROMETER,
  PCK_SYSMAN_UTL.FC_ROUND(CASE WHEN SUM(SALDOS.TOTALAPROPIADO) > 0 THEN ((SUM(SALDOS.REGISTROS)/SUM(SALDOS.TOTALAPROPIADO))*100) ELSE 0 END, 2 ) PORCEJECUTADO,
  PCK_SYSMAN_UTL.FC_ROUND(CASE WHEN SUM(SALDOS.TOTALAPROPIADO) > 0 THEN ((SUM(SALDOS.TOTALAPROPIADO - SALDOS.REGISTROS)/SUM(SALDOS.TOTALAPROPIADO))*100) ELSE 0 END, 2 ) POREJECUTAR, 
  SUM(SALDOS.ADICION)         ADICION,
  SUM(SALDOS.REDUCCION)       REDUCCION,  
  SUM(SALDOS.CREDITOS)        CREDITOS,
  SUM(SALDOS.CONTRACREDITOS)  CONTRACREDITOS,
  SUM(SALDOS.CREDITOS) - SUM(SALDOS.CONTRACREDITOS) TRASLADOS, 
  SUM(SALDOS.APLAZAMIENTOS)   APLAZAMIENTOS,
  SUM(SALDOS.DESAPLAZAMIENTO) DESAPLAZAMIENTO,
  PCK_SYSMAN_UTL.FC_ROUND(CASE WHEN SUM(SALDOS.DISPONIBILIDADMES) > 0 THEN ((SUM(SALDOS.DISPONIBILIDADMESANTERIOR)/SUM(SALDOS.DISPONIBILIDADMES))*100) ELSE 0 END, 2 ) VARMENSUALDIS,
  SUM(SALDOS.OBLIGACIONESMES) REGISTROOBLIGACIONMES,
  SUM(SALDOS.OBLIGACIONES) REGISACUM,
  SUM(SALDOS.PAGOSANTERIORES) PAGOSANTERIORES
  FROM V_PLAN_PRESUPUESTAL INNER JOIN
(
SELECT 
  SALDO_AUX_PPTAL.COMPANIA,
  SALDO_AUX_PPTAL.ANO,
  SALDO_AUX_PPTAL.ID,
  SALDO_AUX_PPTAL.FUENTE_RECURSO,  
  SUM(CASE WHEN SALDO_AUX_PPTAL.NATURALEZA='D' 
           THEN APROPIACION_DEBITO - APROPIACION_CREDITO 
           ELSE APROPIACION_CREDITO - APROPIACION_DEBITO 
           END)  APROPIADO,
  SUM(SALDO_AUX_PPTAL.ADICION)   ADICION,
  SUM(SALDO_AUX_PPTAL.REDUCCION) REDUCCION,      
  SUM(SALDO_AUX_PPTAL.TRASLADO_DEBITO) CREDITOS,    
  SUM(SALDO_AUX_PPTAL.TRASLADO_CREDITO) CONTRACREDITOS,        
  SUM(CASE WHEN SALDO_AUX_PPTAL.NATURALEZA='D' 
      THEN APLAZAM_CREDITO ELSE APLAZAM_DEBITO END)  APLAZAMIENTOS,   
  SUM(CASE WHEN SALDO_AUX_PPTAL.NATURALEZA='D' 
      THEN APLAZAM_DEBITO ELSE APLAZAM_CREDITO END)  DESAPLAZAMIENTO,       
  SUM(CASE WHEN SALDO_AUX_PPTAL.NATURALEZA='D' 
      THEN APLAZAM_DEBITO     - APLAZAM_CREDITO     
      ELSE APLAZAM_CREDITO    - APLAZAM_DEBITO     END)  APLAZAMIENTOFINAL,  
  SUM(CASE WHEN SALDO_AUX_PPTAL.NATURALEZA = 'D' THEN APROPIACION_DEBITO - APROPIACION_CREDITO ELSE ]') || TO_CLOB(q'[APROPIACION_CREDITO - APROPIACION_DEBITO END
      + SALDO_AUX_PPTAL.ADICION + SALDO_AUX_PPTAL.REDUCCION  
      + CASE WHEN SALDO_AUX_PPTAL.NATURALEZA = 'D' THEN APLAZAM_DEBITO     - APLAZAM_CREDITO     ELSE APLAZAM_CREDITO     - APLAZAM_DEBITO     END  
      + CASE WHEN SALDO_AUX_PPTAL.NATURALEZA = 'D' THEN TRASLADO_DEBITO    - TRASLADO_CREDITO    ELSE TRASLADO_CREDITO    - TRASLADO_DEBITO     END
  ) TOTALAPROPIADO,  
  SUM(CASE WHEN SALDO_AUX_PPTAL.MES = s$mes$s THEN SALDO_AUX_PPTAL.DISPONIBILIDAD ELSE 0 END) DISPONIBILIDADMES,
  SUM(CASE WHEN SALDO_AUX_PPTAL.MES = s$mes$s-1 THEN SALDO_AUX_PPTAL.DISPONIBILIDAD ELSE 0 END) DISPONIBILIDADMESANTERIOR,
  SUM(SALDO_AUX_PPTAL.DISPONIBILIDAD) DISPONIBILIDADES,
  SUM(SALDO_AUX_PPTAL.REG_CONTRACT + SALDO_AUX_PPTAL.REG_NO_CONTRACT 
    + SALDO_AUX_PPTAL.MODIF_REG_CONT + SALDO_AUX_PPTAL.MODIF_REG_NOCONT    
  ) REGISTROS,
  SUM(CASE WHEN SALDO_AUX_PPTAL.MES = s$mes$s THEN SALDO_AUX_PPTAL.REG_CONTRACT + SALDO_AUX_PPTAL.REG_NO_CONTRACT 
                                                 + SALDO_AUX_PPTAL.MODIF_REG_CONT + SALDO_AUX_PPTAL.MODIF_REG_NOCONT ELSE 0 END) REGISTROSMES,
   SUM(CASE WHEN SALDO_AUX_PPTAL.MES = s$mes$s-1 THEN SALDO_AUX_PPTAL.REG_CONTRACT + SALDO_AUX_PPTAL.REG_NO_CONTRACT 
                                                 + SALDO_AUX_PPTAL.MODIF_REG_CONT + SALDO_AUX_PPTAL.MODIF_REG_NOCONT ELSE 0 END) REGISTROSMESANTERIOR,                                                 
  SUM(CASE WHEN SALDO_AUX_PPTAL.NATURALEZA='D' THEN EJE_PPT_DEBITO-EJE_PPT_CREDITO ELSE EJE_PPT_CREDITO-EJE_PPT_DEBITO END + 
  SALDO_AUX_PPTAL.MODIF_INGRESOS_EFECTIVO +
  SALDO_AUX_PPTAL.MODIF_INGRESOS_PAPELES)  AS PAGOSTOTALES,   
  SUM(CASE WHEN SALDO_AUX_PPTAL.MES = s$mes$s THEN
  (CASE WHEN SALDO_AUX_PPTAL.NATURALEZA='D' THEN EJE_PPT_DEBITO-EJE_PPT_CREDITO ELSE EJE_PPT_CREDITO-EJE_PPT_DEBITO END) + 
  SALDO_AUX_PPTAL.MODIF_INGRESOS_EFECTIVO +
  SALDO_AUX_PPTAL.MODIF_INGRESOS_PAPELES  ELSE 0 END) AS PAGOSMES, 
  SUM(CASE WHEN SALDO_AUX_PPTAL.MES < s$mes$s THEN
  (CASE WHEN SALDO_AUX_PPTAL.NATURALEZA='D' THEN EJE_PPT_DEBITO-EJE_PPT_CREDITO ELSE EJE_PPT_CREDITO-EJE_PPT_DEBITO END) + 
  SALDO_AUX_PPTAL.MODIF_INGRESOS_EFECTIVO +
  SALDO_AUX_PPTAL.MODIF_INGRESOS_PAPELES  ELSE 0 END) AS PAGOSANTERIORES, 
  SUM(CASE WHEN SALDO_AUX_PPTAL.MES = s$mes$s THEN SALDO_AUX_PPTAL.REGISTRO_OBLIGACION + SALDO_AUX_PPTAL.MODIF_REGISTRO_OBLIGACION ELSE 0 END) OBLIGACIONESMES,
  SUM(SALDO_AUX_PPTAL.REGISTRO_OBLIGACION + SALDO_AUX_PPTAL.MODIF_REGISTRO_OBLIGACION) OBLIGACIONES
  
FROM  SALDO_AUX_PPTAL 
WHERE SALDO_AUX_PPTAL.COMPANIA = s$compania$s
AND SALDO_AUX_PPTAL.ANO        = s$anio$s
AND SALDO_AUX_PPTAL.MES       <= s$mes$s
AND SALDO_AUX_PPTAL.ID BETWEEN 's$cuentaInicial$s' AND 's$cuentaFinal$s'
AND SALDO_AUX_PPTAL.NATURALEZA = 'D'
GROUP BY SALDO_AUX_PPTAL.COMPANIA,
  SALDO_AUX_PPTAL.ANO,
  SALDO_AUX_PPTAL.ID,
  SALDO_AUX_PPTAL.FUENTE_RECURSO
) SALDOS
 ON V_PLAN_PRESUPUESTAL.COMPANIA = SALDOS.COMPANIA
AND V_PLAN_PRESUPUESTAL.ANO      ]') || TO_CLOB(q'[= SALDOS.ANO
AND V_PLAN_PRESUPUESTAL.ID       = SUBSTR(SALDOS.ID, 1, LENGTH(V_PLAN_PRESUPUESTAL.ID))
GROUP BY V_PLAN_PRESUPUESTAL.COMPANIA,
         V_PLAN_PRESUPUESTAL.ANO,
         V_PLAN_PRESUPUESTAL.CODIGO,
         V_PLAN_PRESUPUESTAL.ID ,
         V_PLAN_PRESUPUESTAL.NOMBRE,  
         V_PLAN_PRESUPUESTAL.NATURALEZA,
         V_PLAN_PRESUPUESTAL.FUENTE_RECURSO
ORDER BY V_PLAN_PRESUPUESTAL.ID]') CONSULTA, 3 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);
