MERGE INTO CONSULTAS FIN USING (SELECT '002293REGIN' INFORME ,TO_CLOB(q'[SELECT V_DETALLE_AUXILIAR_PPTAL.COMPROBANTE,
  V_DETALLE_AUXILIAR_PPTAL.CUENTA,
  V_DETALLE_AUXILIAR_PPTAL.TIPO_CPTE_AFECT,
  V_DETALLE_AUXILIAR_PPTAL.TIPO TIPO_CPTE,
  V_DETALLE_AUXILIAR_PPTAL.CUENTANOMBRE NOMBREPP ,
  V_DETALLE_AUXILIAR_PPTAL.CMPTE_AFECTADO,
  CUENTANOMBRE,
  TO_CHAR(FECHA_COM,'DD') || ' ' || 'dia(s) del mes de ' || 
  UPPER(PCK_SYSMAN_UTL.FC_NOMBRE_MES(TO_CHAR(FECHA_COM,'MM'))) || ' de ' || TO_CHAR(FECHA_COM,'YYYY') FECHALETRAS,
  TRIM (TO_CHAR(TO_DATE(TO_CHAR(EXTRACT (MONTH FROM SYSDATE)),'mm'),'MONTH')) MES,
  TO_CHAR(FECHA_COM,'DD') DIA,
  EXTRACT (YEAR FROM SYSDATE ) ANIO,
  VALOR_DEBITO CREDITO,
  VALOR_CREDITO CONTRACREDITO,
  TERCERO_COM_NOM NOMBRETERCERO1,
  FECHA,
  FECHA_COM,
  DEBITO_AFECTADO,
  TEXTO,
  FECHA_COM,
  TIPO_COMPROBANTE_NOM,
  TEXTO,
  TERCERO_COM,
  SUCURSAL_COM,
  DESCRIPCION,
  TEXTO TXT,
  TIPO_COMPROBANTE_NOM NOMBREBPP,
  TIPO,
  FUENTE_RECURSOS,
  CASE
    WHEN VALOR_DEBITO = '0'
    THEN VALOR_CREDITO
    ELSE VALOR_DEBITO
  END VALORCOMPROBANTE,
  DESCRIPCION_DET
  || '   '
  || TEXTO TEXTOCOMPLETO,
  PCK_SYSMAN_UTL.FC_PAR (V_DETALLE_AUXILIAR_PPTAL.COMPANIA , 'NIVELES A MOSTRAR EN RUBRO', 3, SYSDATE, -1 )RUBRO1,
  CASE
    WHEN NATURALEZA='D'
    THEN (VALOR_DEBITO  + MODIFICACION_DEBITO - MODIFICACION_CREDITO) - DEBITO_AFECTADO
    ELSE (VALOR_CREDITO + MODIFICACION_CREDITO - MODIFICACION_DEBITO) - CREDITO_AFECTADO
  END AS SALDOCOMPROBANTE,
  DESCRIPCION
  || ' '
  || TEXTO OBJETO,
  VALOR_DEBITO + VALOR_CREDITO TOTDETALLE,
  UPPER(TIPO_COMPROBANTE_NOM) NOMBRETP,
  SALDO +
  CASE
    WHEN VALOR_DEBITO = '0'
    THEN VALOR_CREDITO
    ELSE VALOR_DEBITO
  END SALDOO,
  SALDO +
  CASE
    WHEN VALOR_DEBITO = '0'
    THEN VALOR_CREDITO
    ELSE VALOR_DEBITO
  END -
  CASE
    WHEN VALOR_DEBITO = '0'
    THEN VALOR_CREDITO
    ELSE VALOR_DEBITO
  END DISPONIBILIDADNETA1,
  CASE
    WHEN VALOR_DEBITO= '0'
    THEN VALOR_CREDITO
    ELSE VALOR_DEBITO
  END VALOR,
  CASE
    WHEN LENGTH (DESCRIPCION
      || ' '
      || TEXTO)>255
    THEN DESCRIPCION
      || ' '
      || TEXTO
    ELSE DESCRIPCION
  END EXPR3,
  CREATED_BY ELABORO,
  AUXILIAR,
  CENTRO_COSTO,
  REFERENCIA,
  FUENTE_RECURSOS
FROM V_DETALLE_AUXILIAR_PPTAL
WHERE V_DETALLE_AUXILIAR_PPTAL.COMPANIA          = s$compania$s
AND V_DETALLE_AUXILIAR_PPTAL.ANO                 = s$ano$s
AND V_DETALLE_AUXILIAR_PPTAL.TIPO                =  's$tipoCpte$s'
AND V_DETALLE_AUXILIAR_PPTAL.COMPROBANTE BETWEEN s$numeroPptoInicial$s AND s$numeroPptoFinal$s]') CONSULTA, 3 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);