MERGE INTO CONSULTAS FIN USING (SELECT '002317RES_PPTAL_SOGA' INFORME ,TO_CLOB(q'[SELECT
    V_DETALLE.FECHA,
    V_DETALLE.TERCERO_COM_NOM,
    V_DETALLE.TERCERO_COM,
    V_DETALLE.CUENTA,
    V_DETALLE.CUENTANOMBRE,
    V_DETALLE.CENTRO_COSTO CENTRO_COSTO,
    V_DETALLE.CODIGO_CPC CODIGO_CPC,
    V_DETALLE.FUENTE_RECURSOS FUENTE_RECURSOS,
    V_DETALLE.TIPO_CPTE_AFECT,
    V_DETALLE.CMPTE_AFECTADO,
    V_DETALLE.DESCRIPCION_DET,
    V_DETALLE.TIPO,
    V_DETALLE.TIPO_COMPROBANTE_NOM,
    V_DETALLE.VALOR_DEBITO,
    V_DETALLE.VALOR_CREDITO,
    V_DETALLE.COMPANIA,
    V_DETALLE.COMPROBANTE,
    V_DETALLE.AUXILIAR,
    V_DETALLE.DETALLE_SECTORIAL AS DSECTORIAL,
    V_DETALLE.COD_PROD_CUIPO AS PMGA,
    (V_DETALLE.VALOR_DEBITO - V_DETALLE.VALOR_CREDITO) -
    (V_DETALLE.DEBITO_AFECTADO - V_DETALLE.CREDITO_AFECTADO) +
    (V_DETALLE.MODIFICACION_DEBITO - V_DETALLE.MODIFICACION_CREDITO) VALORDISPONIBLE,
    V_DETALLE.CREATED_BY, 
    TO_CHAR(V_DETALLE.DATE_CREATED,'DD/MM/YYYY') DATE_CREATED
FROM V_DETALLE_AUXILIAR_PPTAL V_DETALLE
  INNER JOIN ANO
    ON   V_DETALLE.COMPANIA =  ANO.COMPANIA
    AND  V_DETALLE.ANO      =  ANO.NUMERO
WHERE V_DETALLE.COMPANIA    = s$compania$s
  AND V_DETALLE.ANO         = s$ano$s
  AND V_DETALLE.TIPO        = 's$tipoCpte$s'
  AND V_DETALLE.COMPROBANTE BETWEEN s$numeroPptoInicial$s  AND s$numeroPptoFinal$s]') CONSULTA, 3 APLICACION ,TO_CLOB(q'[(null)]') CONSULTA_OPCIONAL, 'calarcon' CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);