MERGE INTO CONSULTAS FIN USING (SELECT '002434DISTEL' INFORME ,TO_CLOB(q'[SELECT TIPO_COMPROBPP.NOMBRE TIPO_COMPROBANTE_NOM,COMPROBANTE_PPTAL.DESTINO,
COMPROBANTE_PPTAL.NUMERO COMPROBANTE,
DETALLE_COMPROBANTE_PPTAL.SECTOR ||' '|| SECTORES.DESCRIPCION AS SECTOR,
DETALLE_COMPROBANTE_PPTAL.FUENTE_RECURSO ||' '|| FUENTE_RECURSOS.NOMBRE AS FUENTE,
DETALLE_COMPROBANTE_PPTAL.PROGRAMA ||' '|| TIPOCLASIFICADOR.NOMBRE AS PROGRAMA,
DETALLE_COMPROBANTE_PPTAL.CODIGO_CPC AS CODIGO_CPC,
DETALLE_COMPROBANTE_PPTAL.COD_PROD_CUIPO ||' '|| TIPOCLASIFICADOR.NOMBRE AS COD_PROD,
COMPROBANTE_PPTAL.FECHA,
COMPROBANTE_PPTAL.FECHA_VCN_DOC,
REFERENCIA.NOMBRE NOMBRETERCERO,
COMPROBANTE_PPTAL.CARGO,
    TERCERDEP.NOMBRE           NOMBRECARGO,
    COMPROBANTE_PPTAL.DEPENDENCIA,
    DEPENDENCIA.NOMBRE         NOMBREDEPENDENCIA,
DETALLE_COMPROBANTE_PPTAL.DESCRIPCION  || ' ' || COMPROBANTE_PPTAL.TEXTO TEXTOCOMPLETO ,
COMPROBANTE_PPTAL.NRO_DOCUMENTO,
PLAN_PRESUPUESTAL.CODIGO || ' ' || PLAN_PRESUPUESTAL.NOMBRE as CUENTA,
PLAN_PRESUPUESTAL.NOMBRE,

PCK_SYSMAN_UTL.FC_PAR(UN_COMPANIA          =>COMPROBANTE_PPTAL.COMPANIA, 
                      UN_NOMBRE            =>'NOMBRE DE JEFE DE PRESUPUESTO', 
                       UN_MODULO            =>3, 
                       UN_FECHA_PAR         =>COMPROBANTE_PPTAL.FECHA, 
                       UN_IND_MAYUS         =>-1) NOMBRE_JEFE_PRESUPUESTO,

PLAN_PRESUPUESTAL.NOMBRE 
        NOMBRECUENTA,
DETALLE_COMPROBANTE_PPTAL.VALOR_DEBITO + DETALLE_COMPROBANTE_PPTAL.VALOR_CREDITO TOTDETALLE, 
       COMPROBANTE_PPTAL.VLR_DOCUMENTO,
 CASE COMPROBANTE_PPTAL.DESTINO  WHEN 'F'
       THEN 
         (SELECT DISTINCT

        RESPONSABLE.CEDULA ||' '||TERCERO.NOMBRE ||' '||DEPENDENCIA_RESPONSABLE.CARGO

FROM DETALLE_COMPROBANTE_PPTAL
 INNER JOIN COMPROBANTE_PPTAL
ON DETALLE_COMPROBANTE_PPTAL.COMPANIA = COMPROBANTE_PPTAL.COMPANIA
AND DETALLE_COMPROBANTE_PPTAL.ANO = COMPROBANTE_PPTAL.ANO
AND DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE = COMPROBANTE_PPTAL.TIPO
AND DETALLE_COMPROBANTE_PPTAL.COMPROBANTE = COMPROBANTE_PPTAL.NUMERO
 LEFT JOIN SOLICITUDDISPONIBILIDAD
           ON DETALLE_COMPROBANTE_PPTAL.COMPANIA = SOLICITUDDISPONIBILIDAD.COMPANIA
          AND DETALLE_COMPROBANTE_PPTAL.NUMERO_SOLICITUD = SOLICITUDDISPONIBILIDAD.NUMERO
          AND DETALLE_COMPROBANTE_PPTAL.TIPO_SOLICITUD = SOLICITUDDISPONIBILIDAD.TIPO_SOLICITUD
          INNER JOIN DEPENDENCIA 
                  ON SOLICITUDDISPONIBILIDAD.COMPANIA = DEPENDENCIA.COMPANIA
                 AND SOLICITUDDISPONIBILIDAD.DEPENDENCIA   = DEPENDENCIA.CODIGO
          INNER JOIN TERCERO 
           ON SOLICITUDDISPONIBILIDAD.COMPANIA = TERCERO.COMPANIA
          AND SOLICITUDDISPONIBILIDAD.TERCERO  = TERCERO.NIT
          AND SOLICITUDDISPONIBILIDAD.SUCURSAL = TERCERO.SUCURSAL
         LEFT JOIN RESPONSABLE 
           ON RESPONSABLE.COMPANIA = TERCERO.COMPANIA   
          AND RESPONSABLE.CEDULA =  TERCERO.NIT  
          AND RESPONSABLE.SUCURSAL = TERCERO.SUCURSAL 
          INNER JOIN DEPENDENCIA_RESPONSABLE 
ON RESPONSABLE.COMPANIA = DEPENDENCIA_RESPONSABLE.COMPANIA
AND RE]') || TO_CLOB(q'[SPONSABLE.CEDULA  = DEPENDENCIA_RESPONSABLE .RESPONSABLE
AND RESPONSABLE.SUCURSAL = DEPENDENCIA_RESPONSABLE .SUCURSAL
 AND SOLICITUDDISPONIBILIDAD.DEPENDENCIA   = DEPENDENCIA_RESPONSABLE.DEPENDENCIA
 WHERE COMPROBANTE_PPTAL.COMPANIA    = s$compania$s
   AND COMPROBANTE_PPTAL.ANO         = s$ano$s
  AND COMPROBANTE_PPTAL.TIPO        = 's$tipoCpte$s'
AND COMPROBANTE_PPTAL.NUMERO BETWEEN s$numeroPptoInicial$s AND s$numeroPptoFinal$s
)
       WHEN 'I' 
       THEN 
         (SELECT DISTINCT 
BPNOVEDADPROYECTO.RESPONSABLE ||' '||
TERCERO.NOMBRE ||' '||
BPNOVEDADPROYECTO.CARGORESPONSABLE 
  FROM DETALLE_COMPROBANTE_PPTAL
           INNER JOIN COMPROBANTE_PPTAL
           ON DETALLE_COMPROBANTE_PPTAL.COMPANIA = COMPROBANTE_PPTAL.COMPANIA
          AND DETALLE_COMPROBANTE_PPTAL.ANO = COMPROBANTE_PPTAL.ANO
          AND  DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE = COMPROBANTE_PPTAL.TIPO  
          AND DETALLE_COMPROBANTE_PPTAL.COMPROBANTE = COMPROBANTE_PPTAL.NUMERO 
          LEFT JOIN BPNOVEDADPROYECTO
           ON DETALLE_COMPROBANTE_PPTAL.COMPANIA = BPNOVEDADPROYECTO.COMPANIA
          AND DETALLE_COMPROBANTE_PPTAL.TIPOT = BPNOVEDADPROYECTO.TIPOT
          AND DETALLE_COMPROBANTE_PPTAL.CLASET = BPNOVEDADPROYECTO.CLASET
          AND DETALLE_COMPROBANTE_PPTAL.CMPTE_SOLICI_AFECTADO = BPNOVEDADPROYECTO.CODIGO
          AND DETALLE_COMPROBANTE_PPTAL.DEPENDENCIA = BPNOVEDADPROYECTO.DEPENDENCIA
INNER JOIN DEPENDENCIA_RESPONSABLE
ON BPNOVEDADPROYECTO.COMPANIA    = DEPENDENCIA_RESPONSABLE.COMPANIA
AND BPNOVEDADPROYECTO.DEPENDENCIA    = DEPENDENCIA_RESPONSABLE.DEPENDENCIA
AND BPNOVEDADPROYECTO.RESPONSABLE    = DEPENDENCIA_RESPONSABLE.RESPONSABLE
AND BPNOVEDADPROYECTO.SUCURSAL    = DEPENDENCIA_RESPONSABLE.SUCURSAL
INNER JOIN DEPENDENCIA
ON DEPENDENCIA_RESPONSABLE.COMPANIA       = DEPENDENCIA.COMPANIA
AND DEPENDENCIA_RESPONSABLE.DEPENDENCIA   = DEPENDENCIA.CODIGO
INNER JOIN TERCERO
ON DEPENDENCIA_RESPONSABLE.COMPANIA     = TERCERO.COMPANIA
AND DEPENDENCIA_RESPONSABLE.RESPONSABLE = TERCERO.NIT
AND DEPENDENCIA_RESPONSABLE.SUCURSAL    = TERCERO.SUCURSAL
WHERE DEPENDENCIA_RESPONSABLE.COMPANIA    = s$compania$s
AND COMPROBANTE_PPTAL.ANO = s$ano$s
AND COMPROBANTE_PPTAL.TIPO        = 's$tipoCpte$s'
AND COMPROBANTE_PPTAL.NUMERO BETWEEN s$numeroPptoInicial$s AND s$numeroPptoFinal$s
)
 END 
NOMBREORDENADOR 
FROM COMPROBANTE_PPTAL  
 INNER JOIN TIPO_COMPROBPP 
    ON  COMPROBANTE_PPTAL.COMPANIA  = TIPO_COMPROBPP.COMPANIA 
    AND COMPROBANTE_PPTAL.TIPO      = TIPO_COMPROBPP.CODIGO   
    LEFT JOIN DETALLE_COMPROBANTE_PPTAL 
    ON  DETALLE_COMPROBANTE_PPTAL.COMPANIA    = COMPROBANTE_PPTAL.COMPANIA 
    AND DETALLE_COMPROBANTE_PPTAL.ANO         = COMPROBANTE_PPTAL.ANO 
    AND DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE   = COMPROBANTE_PPTAL.TIPO 
      AND DETALLE_COMPROBANTE_PPTAL.COMPROBANTE = COMPROBANTE_PPTAL.NUMERO
     LEFT JOIN REFERENCIA 
    ON  DETALLE_COMPROBANTE_PPTAL.COMPANIA                                                = REFERENCIA.COMPANIA 
    AND DETALLE_COMPROBANTE_]') || TO_CLOB(q'[PPTAL.ANO                                                     = REFERENCIA.ANO 
    AND DETALLE_COMPROBANTE_PPTAL.REFERENCIA = REFERENCIA.CODIGO  
    LEFT JOIN PLAN_PRESUPUESTAL
    ON  DETALLE_COMPROBANTE_PPTAL.COMPANIA = PLAN_PRESUPUESTAL.COMPANIA 
    AND DETALLE_COMPROBANTE_PPTAL.ANO      = PLAN_PRESUPUESTAL.ANO 
    AND DETALLE_COMPROBANTE_PPTAL.CUENTA   = PLAN_PRESUPUESTAL.CODIGO
    LEFT JOIN CENTRO_COSTO 
   ON  DETALLE_COMPROBANTE_PPTAL.COMPANIA                                                  = CENTRO_COSTO.COMPANIA 
   AND DETALLE_COMPROBANTE_PPTAL.ANO                                                       = CENTRO_COSTO.ANO 
   AND DETALLE_COMPROBANTE_PPTAL.CENTRO_COSTO = CENTRO_COSTO.CODIGO
    LEFT JOIN FUENTE_RECURSOS 
    ON  DETALLE_COMPROBANTE_PPTAL.COMPANIA                                                    = FUENTE_RECURSOS.COMPANIA 
    AND DETALLE_COMPROBANTE_PPTAL.ANO                                                         = FUENTE_RECURSOS.ANO 
    AND DETALLE_COMPROBANTE_PPTAL.FUENTE_RECURSO  = FUENTE_RECURSOS.CODIGO
     LEFT JOIN SECTORES
    ON DETALLE_COMPROBANTE_PPTAL.COMPANIA = SECTORES.COMPANIA
    AND DETALLE_COMPROBANTE_PPTAL.SECTOR = SECTORES.CODIGO
     LEFT JOIN TIPOCLASIFICADOR
    ON DETALLE_COMPROBANTE_PPTAL.COMPANIA = TIPOCLASIFICADOR.COMPANIA
    AND DETALLE_COMPROBANTE_PPTAL.ANO = TIPOCLASIFICADOR.ANO
    AND DETALLE_COMPROBANTE_PPTAL.PROGRAMA = TIPOCLASIFICADOR.CODIGO
    AND DETALLE_COMPROBANTE_PPTAL.COD_PROD_CUIPO = TIPOCLASIFICADOR.CODIGO
      LEFT JOIN AUXILIAR 
    ON  DETALLE_COMPROBANTE_PPTAL.COMPANIA                                              = AUXILIAR.COMPANIA 
    AND DETALLE_COMPROBANTE_PPTAL.ANO                                                   = AUXILIAR.ANO 
    AND DETALLE_COMPROBANTE_PPTAL.AUXILIAR = AUXILIAR.CODIGO  
    LEFT JOIN TERCERO 
   ON  DETALLE_COMPROBANTE_PPTAL.COMPANIA                                                                = TERCERO.COMPANIA 
   AND DETALLE_COMPROBANTE_PPTAL.TERCERO   = TERCERO.NIT 
   AND  DETALLE_COMPROBANTE_PPTAL.SUCURSAL  = TERCERO.SUCURSAL  
LEFT JOIN DEPENDENCIA ON COMPROBANTE_PPTAL.COMPANIA = DEPENDENCIA.COMPANIA
                              AND COMPROBANTE_PPTAL.DEPENDENCIA = DEPENDENCIA.CODIGO
    LEFT JOIN DEPENDENCIA_RESPONSABLE ON DEPENDENCIA_RESPONSABLE.COMPANIA = COMPROBANTE_PPTAL.COMPANIA
                                          AND DEPENDENCIA_RESPONSABLE.DEPENDENCIA = COMPROBANTE_PPTAL.DEPENDENCIA
                                          AND DEPENDENCIA_RESPONSABLE.CARGO = COMPROBANTE_PPTAL.CARGO
    LEFT JOIN TERCERO TERCERDEP ON DEPENDENCIA_RESPONSABLE.COMPANIA = TERCERDEP.COMPANIA
                                    AND DEPENDENCIA_RESPONSABLE.RESPONSABLE = TERCERDEP.NIT
                                    AND DEPENDENCIA_RESPONSABLE.SUCURSAL = TERCERDEP.SUCURSAL
   WHERE COMPROBANTE_PPTAL.COMPANIA    = s$compania$s
   AND COMPROBANTE_PPTAL.ANO         = s$ano$s
  AND COMPROBANTE_PPTAL.TIPO        = 's$tipoCpte$s'
AND COMPR]') || TO_CLOB(q'[OBANTE_PPTAL.NUMERO BETWEEN s$numeroPptoInicial$s AND s$numeroPptoFinal$s]') CONSULTA, 3 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);