MERGE INTO CONSULTAS FIN USING (SELECT '0024441LisEjecPptalGasFuenteApl' INFORME ,TO_CLOB(q'[WITH AUX AS(
SELECT 
  SALDO_PLAN_PPTAL.COMPANIA,
  PLAN_PRESUPUESTAL.CODIGO,
  PLAN_PRESUPUESTAL.NOMBRE,
  SALDO_PLAN_PPTAL.ID CUENTA,
  SALDO_PLAN_PPTAL.FUENTE_RECURSO,
  SUM(CASE WHEN PLAN_PRESUPUESTAL.NATURALEZA='D' THEN APROPIACION_DEBITO-APROPIACION_CREDITO ELSE APROPIACION_CREDITO-APROPIACION_DEBITO END) AS APROPIADO,
  SUM(CASE WHEN PLAN_PRESUPUESTAL.NATURALEZA='D' THEN TRASLADO_DEBITO-TRASLADO_CREDITO ELSE TRASLADO_CREDITO-TRASLADO_DEBITO END)             AS TRASLADO,
  SUM(CASE WHEN PLAN_PRESUPUESTAL.NATURALEZA='D' THEN EJE_PPT_DEBITO-EJE_PPT_CREDITO ELSE EJE_PPT_CREDITO-EJE_PPT_DEBITO END)                 AS EJECUCIONPPT,
  SUM(CASE WHEN PLAN_PRESUPUESTAL.NATURALEZA='D' THEN APLAZAM_DEBITO-APLAZAM_CREDITO ELSE APLAZAM_CREDITO-APLAZAM_DEBITO END)                 AS APLAZAMIENTO,
  SUM(SALDO_PLAN_PPTAL.ADICION)                                                                                            AS ADICION,
  SUM(SALDO_PLAN_PPTAL.REDUCCION)                                                                                          AS REDUCCION,
  SUM(ADICION)+SUM(TRASLADO_DEBITO)                                                                                        AS MODIFADICION,
  ABS(SUM(REDUCCION))+SUM(TRASLADO_CREDITO)                                                                                AS MODIFREDUCCION
FROM V_PLAN_PRESUPUESTAL PLAN_PRESUPUESTAL
INNER JOIN V_SALDO_PLAN_PPTAL SALDO_PLAN_PPTAL ON 
PLAN_PRESUPUESTAL.COMPANIA = SALDO_PLAN_PPTAL.COMPANIA AND
PLAN_PRESUPUESTAL.ANO      = SALDO_PLAN_PPTAL.ANO AND 
PLAN_PRESUPUESTAL.ID        = SALDO_PLAN_PPTAL.ID
WHERE PLAN_PRESUPUESTAL.COMPANIA = s$compania$s 
AND PLAN_PRESUPUESTAL.ANO = s$anio$s 
AND SALDO_PLAN_PPTAL.ID 
  BETWEEN 's$cuentaInicial$s' AND 's$cuentaFinal$s'
AND SALDO_PLAN_PPTAL.MES <= s$mes$s
GROUP BY SALDO_PLAN_PPTAL.COMPANIA,
  SALDO_PLAN_PPTAL.ANO,
  SALDO_PLAN_PPTAL.ID,
  PLAN_PRESUPUESTAL.CODIGO,
  PLAN_PRESUPUESTAL.NOMBRE,
  SALDO_PLAN_PPTAL.FUENTE_RECURSO
)

SELECT
AUX.COMPANIA,
AUX.CODIGO,
AUX.CUENTA,
AUX.NOMBRE,
AUX.FUENTE_RECURSO,
AUX.APROPIADO,
AUX.MODIFADICION,
AUX.MODIFREDUCCION,
AUX.EJECUCIONPPT,
AUX.APLAZAMIENTO,
AUX.APROPIADO+AUX.ADICION+AUX.TRASLADO+AUX.REDUCCION AS TOTANTAPLA,
AUX.APROPIADO+AUX.ADICION+AUX.TRASLADO+AUX.REDUCCION+AUX.APLAZAMIENTO AS TOTAL,
AUX.APROPIADO+AUX.ADICION+AUX.TRASLADO+AUX.REDUCCION+AUX.APLAZAMIENTO-AUX.EJECUCIONPPT AS SALDODISPONIBLEPAC
FROM AUX
ORDER BY AUX.CUENTA]') CONSULTA, 3 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);