MERGE INTO CONSULTAS FIN USING (SELECT '002467SolicitudPresupuestal' INFORME ,TO_CLOB(q'[SELECT
    SOLICITUD.NUMERO           CODIGO,
    TO_CHAR(SOLICITUD.FECHA, 'YYYY-MM-DD') FECHA_SOLICITUD,
    CONCAT(CONCAT(D_SOLICITUD.RUBRO, '/'), PLANPPTAL.NOMBRE) COD_NOM_RUBRO,
    DEPENDENCIA.NOMBRE DEPENDENCIA,
    CONCAT(CONCAT(D_SOLICITUD.FUENTE, '/'), FUENTE.NOMBRE) FUENTE_RECURSOS,
    D_SOLICITUD.CODIGOCPCDANE     CODCPCDANE,
    D_SOLICITUD.VALOR   VALORSOL,
    SOLICITUD.OBJETO             NOM_OBJETO,
    RESPONSABLE.CARGO CARGO_SOLICITANTE
FROM
    SOLICITUDDISPONIBILIDAD      SOLICITUD
    INNER JOIN D_SOLICITUDDISPONIBILIDAD  D_SOLICITUD  ON SOLICITUD.COMPANIA = D_SOLICITUD.COMPANIA
                                    AND SOLICITUD.NUMERO = D_SOLICITUD.NUMERO
                                    AND SOLICITUD.TIPO_SOLICITUD = D_SOLICITUD.TIPO_SOLICITUD
    INNER JOIN DEPENDENCIA  ON SOLICITUD.COMPANIA = DEPENDENCIA.COMPANIA
                                    AND SOLICITUD.DEPENDENCIA = DEPENDENCIA.CODIGO
    INNER JOIN PLAN_PRESUPUESTAL PLANPPTAL ON D_SOLICITUD.COMPANIA = PLANPPTAL.COMPANIA
                                    AND D_SOLICITUD.ANO = PLANPPTAL.ANO
                                    AND D_SOLICITUD.RUBRO = PLANPPTAL.CODIGO
    INNER JOIN FUENTE_RECURSOS FUENTE ON D_SOLICITUD.COMPANIA = FUENTE.COMPANIA
                                    AND D_SOLICITUD.ANO = FUENTE.ANO
                                    AND D_SOLICITUD.FUENTE = FUENTE.CODIGO
    INNER JOIN TERCERO  ON SOLICITUD.COMPANIA = TERCERO.COMPANIA
                                    AND SOLICITUD.TERCERO = TERCERO.NIT
                                    AND SOLICITUD.SUCURSAL = TERCERO.SUCURSAL
    INNER JOIN RESPONSABLE  ON TERCERO.COMPANIA = RESPONSABLE.COMPANIA
                                    AND TERCERO.NIT = RESPONSABLE.CEDULA
                                    AND TERCERO.SUCURSAL = RESPONSABLE.SUCURSAL
WHERE
    SOLICITUD.COMPANIA = s$compania$s
    AND SOLICITUD.TIPO_SOLICITUD = '1'
    AND TO_CHAR(SOLICITUD.FECHA, 'YYYY') = s$anio$s
    AND SOLICITUD.DEPENDENCIA = s$dependencia$s
    AND SOLICITUD.NUMERO = s$codigo$s
]') CONSULTA, 3 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);