MERGE INTO CONSULTAS FIN USING (SELECT '002523lisAuxPptalContratos' INFORME ,TO_CLOB(q'[SELECT
    DCP.FECHA,
    NVL(DCP.TIPO_CPTE_AFECT || '-', '') || TO_CHAR(DCP.CMPTE_AFECTADO) AS DOCUMENTOAFECTADO,
    DCP.TIPO_CPTE,
    DCP.COMPROBANTE,
    DCP.MODIFICACION_DEBITO AS MODIFICACION_DEBITO1,
    DCP.MODIFICACION_CREDITO AS MODIFICACION_CREDITO1,
    PP.NOMBRE AS NOMBRE_T,
    CASE 
        WHEN DCP.TERCERO = RPAD('9', LENGTH('Tercero'), '9') THEN ''
        ELSE T.NOMBRE
    END AS NOMBRETERCERO,
    TC.NOMBRE,
    CASE 
        WHEN TC.CLASE <> 'EGR' THEN 
            CASE 
                WHEN PP.NATURALEZA = 'D' THEN 
                    (DCP.VALOR_DEBITO - DCP.VALOR_CREDITO) -
                    (DCP.DEBITO_AFECTADO - DCP.CREDITO_AFECTADO) +
                    (DCP.MODIFICACION_DEBITO - DCP.MODIFICACION_CREDITO)
                ELSE 
                    (DCP.VALOR_CREDITO - DCP.VALOR_DEBITO) -
                    (DCP.CREDITO_AFECTADO - DCP.DEBITO_AFECTADO) +
                    (DCP.MODIFICACION_CREDITO - DCP.MODIFICACION_DEBITO)
            END
        ELSE 0
    END AS SALDOPOREJECUTAR,
    CP.TIPOCONTRATO || '-' || CP.NUMEROCONTRATO AS CONTRATO,
    DCP.CUENTA,
    DCP.DESCRIPCION,
    DCP.VALOR_DEBITO,
    DCP.VALOR_CREDITO,
    DCP.DEBITO_AFECTADO,
    DCP.CREDITO_AFECTADO,
    CP.TIPOCONTRATO || '-' || CP.NUMEROCONTRATO AS TIPONUMEROCONTRATO
FROM 
    DETALLE_COMPROBANTE_PPTAL DCP
LEFT JOIN 
    AUXILIAR A ON    DCP.COMPANIA = A.COMPANIA 
                 AND DCP.ANO = A.ANO 
                 AND DCP.AUXILIAR = A.CODIGO 
LEFT JOIN 
    CENTRO_COSTO CC ON DCP.COMPANIA = CC.COMPANIA
                 AND DCP.ANO = CC.ANO
                 AND DCP.CENTRO_COSTO = CC.CODIGO 
LEFT JOIN 
    COMPROBANTE_PPTAL CP ON DCP.COMPANIA = CP.COMPANIA 
                         AND DCP.TIPO_CPTE = CP.TIPO 
                         AND DCP.ANO = CP.ANO 
                         AND DCP.COMPROBANTE = CP.NUMERO
LEFT JOIN 
    PLAN_PRESUPUESTAL PP ON DCP.COMPANIA = PP.COMPANIA 
                         AND DCP.ANO = PP.ANO 
                         AND DCP.CUENTA = PP.CODIGO
LEFT JOIN 
    TIPO_COMPROBPP TC ON DCP.TIPO_CPTE = TC.CODIGO 
                      AND DCP.COMPANIA = TC.COMPANIA
LEFT JOIN 
    TERCERO T ON DCP.COMPANIA = T.COMPANIA 
                      AND DCP.TERCERO = T.NIT 
                      AND DCP.SUCURSAL = T.SUCURSAL 
WHERE 
   DCP.FECHA BETWEEN 's$fechainicial$s' AND 's$fechafinal$s'
    AND CP.NUMEROCONTRATO BETWEEN 's$numerocontratoinicial$s' AND 's$numerocontratofinal$s'
    AND CP.TIPOCONTRATO = 's$tipocontrato$s'
    AND DCP.COMPANIA = s$compania$s
    AND DCP.CUENTA BETWEEN 's$cuentainicial$s' AND 's$cuentafinal$s'
    AND DCP.TERCERO BETWEEN 's$terceroinicial$s' AND 's$tercerofinal$s'
ORDER BY 
    DCP.CUENTA]') CONSULTA, 3 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);