MERGE INTO CONSULTAS FIN USING (SELECT '002501SubNoAfectadosdocu' INFORME ,TO_CLOB(q'[WITH JERARQUIA AS (
   SELECT  DCP.COMPANIA,ANO,TIPO_CPTE,COMPROBANTE,CONSECUTIVO,ANO_AFECT,TIPO_CPTE TIPO_CPTE_AFECT, COMPROBANTE CMPTE_AFECTADO,TCPP.CLASE,TAPP.CLASE CLASE_AFECTADA
     FROM DETALLE_COMPROBANTE_PPTAL DCP
      INNER JOIN TIPO_COMPROBPP TCPP ON(DCP.COMPANIA= TCPP.COMPANIA AND DCP.TIPO_CPTE=TCPP.CODIGO)
      LEFT JOIN TIPO_COMPROBPP TAPP ON(DCP.COMPANIA= TAPP.COMPANIA AND DCP.TIPO_CPTE_AFECT=TAPP.CODIGO)
     WHERE DCP.COMPANIA = s$compania$s
   AND TIPO_CPTE = 's$tipoComprobante$s'
   AND COMPROBANTE = s$numeroComprobante$s
   AND  ((DEBITO_AFECTADO - CREDITO_AFECTADO ) + (MODIFICACION_DEBITO - MODIFICACION_CREDITO))=0
   ), RESUMEN AS(
   SELECT  DCPP.COMPANIA, 
       DCPP.ANO, 
       DCPP.TIPO_CPTE TIPO , 
       DCPP.COMPROBANTE , 
       DCPP.FECHA,
       DCPP.ANO_AFECT, 
       DCPP.TIPO_CPTE_AFECT TIPOAFECT, 
       DCPP.CMPTE_AFECTADO COMPAFECT, 
     CASE WHEN DCPP.NATURALEZA = 'D' 
              THEN (DEBITO_AFECTADO-CREDITO_AFECTADO) 
              ELSE  (CREDITO_AFECTADO-DEBITO_AFECTADO)
            END AFECTADO,
      CASE WHEN DCPP.NATURALEZA = 'D' 
              THEN (VALOR_DEBITO-VALOR_CREDITO) 
              ELSE  (VALOR_CREDITO-VALOR_DEBITO)
            END VALOR,
       DCPP.ID RUBRO,
       DCPP.DESCRIPCION,
       DCPP.TERCERO NIT_TERCERO,
       DCPP.SUCURSAL,
       CASE WHEN DCPP.TIPO_CPTE IN ('DMD','ADD','DMR','ADR','DRO','ARO','DEG','AEG') 
       THEN 'Modificaciones' ELSE 'Afectaciones' END TIPOMODIF,
       CASE WHEN DCPP.NATURALEZA = 'D' 
              THEN (DEBITO_AFECTADO-CREDITO_AFECTADO) 
              ELSE  (CREDITO_AFECTADO-DEBITO_AFECTADO)
            END VALORAFECT,
        JQ.CLASE,JQ.CLASE_AFECTADA,
         CASE WHEN DCPP.TIPO_CPTE IN ('ADD','ADR','DRO','ARO','DEG','AEG') 
            THEN VALOR_DEBITO - VALOR_CREDITO 
            WHEN DCPP.TIPO_CPTE NOT IN('DMD','DMR')
            THEN 
              CASE WHEN DCPP.NATURALEZA = 'D' 
              THEN (VALOR_DEBITO-VALOR_CREDITO) - (DEBITO_AFECTADO-CREDITO_AFECTADO) + (MODIFICACION_DEBITO-MODIFICACION_CREDITO)
              ELSE (VALOR_CREDITO-VALOR_DEBITO) - (CREDITO_AFECTADO-DEBITO_AFECTADO) + (MODIFICACION_CREDITO-MODIFICACION_DEBITO)
              END
            ELSE 0 
            END SALDO
   FROM JERARQUIA JQ 
   LEFT JOIN DETALLE_COMPROBANTE_PPTAL DCPP 
   ON (JQ.COMPANIA = DCPP.COMPANIA 
      AND JQ.ANO= DCPP.ANO 
      AND JQ.TIPO_CPTE=DCPP.TIPO_CPTE 
      AND JQ.COMPROBANTE=DCPP.COMPROBANTE
      AND JQ.CONSECUTIVO=DCPP.CONSECUTIVO)
   ),TOTALES AS(
   SELECT CLASE,RUBRO,SUM(SALDO) SALDO ,SUM(VALOR) VALORTOTAL FROM RESUMEN group by  CLASE, RUBRO)
    SELECT RES.COMPANIA, 
       RES.ANO, 
       RES.ANO_AFECT, 
       RES.TIPOAFECT, 
       RES.COMPAFECT, 
      RES.AFECTADO,
      RES.RUBRO,
      RES.NIT_TERCERO,
     RES.SUCURSAL,
     RES.TIPOMODIF,
     RES.VALORAFECT,
     RES.CLASE,
     RES.TIPO, 
     SUM(RES.SALDO) SALDO,
     SUM(RES.VALOR)SALDO_SIN_AFECTAR , 
   V_PLAN_PRESUPUESTAL.NOMBRE NOMBRERUBRO
   FROM ]') || TO_CLOB(q'[RESUMEN RES 
        LEFT JOIN TOTALES TOT 
         ON (RES.CLASE_AFECTADA=TOT.CLASE AND RES.RUBRO=TOT.RUBRO)
        INNER JOIN V_PLAN_PRESUPUESTAL 
         ON RES.COMPANIA = V_PLAN_PRESUPUESTAL.COMPANIA
         AND RES.ANO = V_PLAN_PRESUPUESTAL.ANO
         AND RES.RUBRO = V_PLAN_PRESUPUESTAL.ID   
        INNER JOIN TERCERO
          ON RES.COMPANIA = TERCERO.COMPANIA
          AND RES.SUCURSAL = TERCERO.SUCURSAL
          AND RES.NIT_TERCERO = TERCERO.NIT
          group by   RES.COMPANIA, 
       RES.ANO, 
       RES.ANO_AFECT, 
       RES.TIPOAFECT, 
       RES.COMPAFECT, 
      RES.AFECTADO,
      RES.RUBRO,
      RES.NIT_TERCERO,
     RES.SUCURSAL,
     RES.TIPOMODIF,
     RES.VALORAFECT,
     RES.CLASE,
     RES.TIPO, 
   V_PLAN_PRESUPUESTAL.NOMBRE]') CONSULTA, 3 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);

MERGE INTO CONSULTAS_SUB FIN USING (SELECT '002499Afectacionesdocu' INFORME_PADRE, '002501SubNoAfectadosdocu' INFORME_HIJO, 'PR_STRLQL_NO_AFECTADO' PARAMETRO ,NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (FIN.INFORME_PADRE = INI.INFORME_PADRE AND INI.INFORME_HIJO = FIN.INFORME_HIJO)  WHEN MATCHED THEN  UPDATE SET FIN.PARAMETRO = INI.PARAMETRO , FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME_PADRE,INFORME_HIJO, PARAMETRO,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME_PADRE,INI.INFORME_HIJO, INI.PARAMETRO,INI.CREATED_BY,SYSDATE);