MERGE INTO CONSULTAS FIN USING (SELECT '002740SCDMELGAR' INFORME ,TO_CLOB(q'[SELECT S.COMPANIA, 
S.NUMERO CONSECUTIVO, 
S.ANO, 
S.OBJETO, 
S.VALOR VALORTOTAL_SOL,
PCK_SYSMAN_UTL.FC_VALOR_LETRAS(S.VALOR,0) AS VALORLETRAS,
S.DEPENDENCIA,
T.NOMBRE NOMBRE_SECRETARIO,
R.CARGO CARGO_SECRETARIO,
S.CREATED_BY, 
(SELECT VALOR FROM PARAMETRO WHERE COMPANIA = s$compania$s AND NOMBRE = 'VERSION FORMATO DE SOLICITUD CDP') VERSIONDOC,
TO_CHAR(S.FECHA,'DD') DIA,
TO_CHAR(S.FECHA,'MM') MES,
TO_CHAR(S.FECHA,'YYYY') ANIO,
P.NOMBRE NOMBRERUBRO,
DS.RUBRO,
DS.FUENTE FUENTERECURSOS,
DS.REFERENCIA,
DS.VALOR VALORSOLICITADO,
TERCEROU.NOMBRE PROYECTADOPOR,
RESPONSABLEU.CARGO CARGOPROYECTADO
FROM SOLICITUDDISPONIBILIDAD S
INNER JOIN D_SOLICITUDDISPONIBILIDAD DS
ON DS.COMPANIA = S.COMPANIA
AND DS.ANO = S.ANO
AND DS.NUMERO = S.NUMERO
INNER JOIN PLAN_PRESUPUESTAL P
ON P.COMPANIA = DS.COMPANIA
AND P.ANO = DS.ANO
AND P.CODIGO = DS.RUBRO
INNER JOIN RESPONSABLE R
ON R.COMPANIA = S.COMPANIA
AND R.CEDULA = S.TERCERO
AND R.SUCURSAL = S.SUCURSAL
INNER JOIN TERCERO T
ON T.COMPANIA = S.COMPANIA
AND T.NIT = S.TERCERO
AND T.SUCURSAL = S.SUCURSAL
INNER JOIN USUARIO U
ON U.CODIGO = S.CREATED_BY
INNER JOIN TERCERO TERCEROU
ON TERCEROU.NIT = U.CEDULA
AND TERCEROU.SUCURSAL = U.SUCURSAL
AND TERCEROU.COMPANIA = s$compania$s
LEFT JOIN RESPONSABLE RESPONSABLEU
ON RESPONSABLEU.CEDULA = U.CEDULA
AND RESPONSABLEU.SUCURSAL = U.SUCURSAL
AND RESPONSABLEU.COMPANIA = s$compania$s
WHERE S.COMPANIA = s$compania$s
AND S.NUMERO = s$numeroSolicitud$s]') CONSULTA, 3 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, 'grojas' CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);