MERGE INTO CONSULTAS FIN USING (SELECT '002900EjeGastosPorUnidadEje' INFORME ,TO_CLOB(q'[SELECT P.CODIGO,P.NOMBRE,CASE WHEN P.MOVIMIENTO <> 0 THEN F.CPI END AS CPI ,CASE WHEN P.MOVIMIENTO <> 0 THEN F.CPINOMBRE END AS CPINOMBRE,
CASE WHEN P.MOVIMIENTO <> 0 THEN F.CCP END AS CCP,CASE WHEN P.MOVIMIENTO <> 0 THEN F.CCPNOMBRE END AS CCPNOMBRE,
CASE WHEN P.MOVIMIENTO <> 0 THEN F.BPIN END AS BPIN,CASE WHEN P.MOVIMIENTO <> 0 THEN F.BPINOMBRE END AS BPINOMBRE,
CASE WHEN P.MOVIMIENTO <> 0 THEN F.FUENTE END AS FUENTE,CASE WHEN P.MOVIMIENTO <> 0 THEN F.FUENTENOMBRE END AS FUENTENOMBRE,CASE WHEN P.MOVIMIENTO <> 0 THEN F.FONDOS END AS FONDOS,SUM(F.APROPIACIONANTERIOR) APROPIADO,
SUM(F.ADICION) ADICION,SUM(F.REDUCCION) REDUCCION ,SUM(F.CREDITO) CREDITO,SUM(F.CONTRACREDITOS) CONTRACREDITO,SUM(F.PPTO_DEFINITIVO) PPTO_DEFINITIVO,
SUM(F.CDPTOTAL) CDPTOTAL,SUM(F.CDPSALDO) CDPSALDO,SUM(F.RPTOTAL) RPTOTAL,
SUM(F.RPSALDO) RPSALDO,SUM(F.OBTOTAL) OBTOTAL,SUM(F.OBSALDO) OBSALDO,SUM(F.GGTOTAL) GGTOTAL,SUM(F.GGSALDO) GGSALDO
FROM TIPOCLASIFICADOR P INNER JOIN (SELECT  INI.COMPANIA,INI.ANO,NVL(INI.CODIGOCCPET_MAN,INI.CODIGOCCPET_PAD) CODIGO ,
    (SELECT NOMBRE FROM TIPOCLASIFICADOR WHERE CODIGO = NVL(INI.CODIGOCCPET_MAN, INI.CODIGOCCPET_PAD) AND ANO = s$ano$s  AND COMPANIA = s$compania$s AND CLASECLASIFICADOR = '006' AND ROWNUM =1) NOMBRE,
    NVL(NVL(INI.CODIGOCPI_MAN,INI.CODIGOCPI_PAD),0) CPI,
    NVL(TCCPI.NOMBRE, '-') CPINOMBRE,
    NVL(NVL(INI.CODIGOCCP_MAN,INI.CODIGOCCP_PAD),0) CCP,
    NVL(TCDANE.NOMBRE, '-') CCPNOMBRE,
    NVL(NVL(INI.CODIGOBPIN_MAN,INI.CODIGOBPIN_PAD),0) BPIN,
    NVL(TCBPIN.NOMBRE, '-') BPINOMBRE,
    NVL(FR.EQUIVALENTECUIPO,0)FUENTE,
     CASE WHEN FR.EQUIVALENTECUIPO IS NULL THEN '-' ELSE  NVL(FR.NOMBRE, '-') END FUENTENOMBRE,
    CASE WHEN INI.CONSITUACIONFONDOS = -1 THEN 'S' ELSE 'C' END FONDOS,
    SUM(CASE WHEN SALDO.MES < 1
                    THEN   APROPIACION_DEBITO  - APROPIACION_CREDITO - TRASLADO_CREDITO + TRASLADO_DEBITO + ADICION + REDUCCION
                    ELSE 0 END
                ) AS APROPIACIONANTERIOR,
    SUM(SALDO.ADICION)ADICION,
    SUM(SALDO.REDUCCION*-1)REDUCCION,
    SUM(SALDO.TRASLADO_DEBITO)  CREDITO,
    SUM(SALDO.TRASLADO_CREDITO )  CONTRACREDITOS,
    SUM(   APROPIACION_DEBITO  - APROPIACION_CREDITO - TRASLADO_CREDITO + TRASLADO_DEBITO - SALDO.APLAZAM_CREDITO + SALDO.APLAZAM_DEBITO + ADICION + REDUCCION) AS PPTO_DEFINITIVO,
    SUM(SALDO.DISPONIBILIDAD) CDPTOTAL,
    SUM(  APROPIACION_DEBITO  - APROPIACION_CREDITO - TRASLADO_CREDITO + TRASLADO_DEBITO - SALDO.APLAZAM_CREDITO + SALDO.APLAZAM_DEBITO + ADICION + REDUCCION) - SUM(SALDO.DISPONIBILIDAD ) CDPSALDO,
    SUM(SALDO.REG_CONTRACT
                   + SALDO.REG_NO_CONTRACT
                   + SALDO.MODIF_REG_CONT
                   + SALDO.MODIF_REG_NOCONT
                ) RPTOTAL,
    SUM(SALDO.DISPONIBILIDAD)- SUM(SALDO.REG_CONTRACT
                   + SALDO.REG_NO_CONTRACT
                   + SALDO.MODIF_REG_CONT
                   + SALDO.MODIF_REG_NOCONT
                ) RPSALDO,
    SUM(SALDO.REGISTRO_OBLIGACION
                   + ]') || TO_CLOB(q'[SALDO.MODIF_REGISTRO_OBLIGACION
              )  OBTOTAL,
    SUM(SALDO.REG_CONTRACT
                   + SALDO.REG_NO_CONTRACT
                   + SALDO.MODIF_REG_CONT
                   + SALDO.MODIF_REG_NOCONT
       )- SUM(SALDO.REGISTRO_OBLIGACION
                   + SALDO.MODIF_REGISTRO_OBLIGACION) OBSALDO,
    SUM( SALDO.EJE_PPT_DEBITO - SALDO.EJE_PPT_CREDITO )  GGTOTAL,
    SUM(SALDO.REGISTRO_OBLIGACION
                   + SALDO.MODIF_REGISTRO_OBLIGACION
              ) - SUM(SALDO.EJE_PPT_DEBITO - SALDO.EJE_PPT_CREDITO )GGSALDO
    FROM (SELECT MOV.COMPANIA,
    MOV.ANO,
    MOV.CODIGO,
    MAX(CASE WHEN PADRE.CLASECLASIFICADOR ='006' THEN
    PADRE.TIPOCLASIFICADOR
    ELSE
    NULL END) CODIGOCCPET_PAD,
    MOV.CODIGOCCPET CODIGOCCPET_MAN,
    MAX(CASE WHEN PADRE.CLASECLASIFICADOR ='004' THEN
    PADRE.TIPOCLASIFICADOR
    ELSE
    NULL END) CODIGOCPI_PAD,
    MOV.CODIGOPRODUCTO CODIGOCPI_MAN,
    MAX(CASE WHEN PADRE.CLASECLASIFICADOR ='007' THEN
    PADRE.TIPOCLASIFICADOR
    ELSE
    NULL END) CODIGOCCP_PAD,
    MOV.CODIGOCPCDANE CODIGOCCP_MAN,
    MAX(CASE WHEN PADRE.CLASECLASIFICADOR ='005' THEN
    PADRE.TIPOCLASIFICADOR
    ELSE
    NULL
    END) CODIGOBPIN_PAD,
    MOV.CODIGOBPIN CODIGOBPIN_MAN,
    MOV.CONSITUACIONFONDOS
    FROM PLAN_PRESUPUESTAL MOV
    LEFT JOIN PLAN_PRESUPUESTAL PADRE
    ON PADRE.COMPANIA = MOV.COMPANIA
    AND PADRE.ANO = MOV.ANO
    AND PADRE.CODIGO = SUBSTR(MOV.CODIGO,1,LENGTH(PADRE.CODIGO))
    WHERE MOV.COMPANIA = s$compania$s
    AND MOV.ANO      = s$ano$s
    AND MOV.NATURALEZA = 'D'
    AND PADRE.CODIGO BETWEEN 's$codigoInicial$s' AND 's$codigoFinal$s'
    s$unidadeje$s
    AND MOV.REGALIAS IN(0)
    AND (MOV.MOVIMIENTO<>0
    OR MOV.MAN_AUX_FUE<>0
    OR MOV.MAN_AUX_GEN<>0
    OR MOV.MAN_AUX_REF<>0
    OR MOV.MAN_AUX_TER<>0
    OR MOV.MAN_CEN_CTO<>0
    )
    GROUP BY MOV.COMPANIA,
    MOV.ANO,
    MOV.CODIGO,
    MOV.CODIGOCCPET,MOV.CODIGOPRODUCTO,
    MOV.CODIGOBPIN,MOV.CODIGOCPCDANE,MOV.CONSITUACIONFONDOS
    ORDER BY MOV.CODIGO
       ) INI
    INNER JOIN SALDO_AUX_PPTAL SALDO
    ON INI.COMPANIA = SALDO.COMPANIA
    AND INI.ANO      = SALDO.ANO
    AND INI.CODIGO   = SALDO.CODIGO
    LEFT JOIN(select codigo,nombre,compania,ano
    from tipoclasificador
    where  claseclasificador = 004) TCCPI
        ON INI.COMPANIA = TCCPI.COMPANIA
        AND INI.ANO = TCCPI.ANO AND NVL(INI.CODIGOCPI_MAN,INI.CODIGOCPI_PAD) = TCCPI.CODIGO
    LEFT JOIN (select codigo,nombre,compania,ano
    from tipoclasificador
    where  claseclasificador = 007) TCDANE
        ON INI.COMPANIA = TCDANE.COMPANIA
        AND INI.ANO = TCDANE.ANO AND NVL(INI.CODIGOCCP_MAN,INI.CODIGOCCP_PAD) = TCDANE.CODIGO
    LEFT JOIN (select codigo,nombre,compania,ano
    from tipoclasificador
    where  claseclasificador = 005) TCBPIN
        ON INI.COMPANIA = TCBPIN.COMPANIA
        AND INI.ANO = TCBPIN.ANO AND NVL(INI.CODIGOBPIN_MAN,INI.CODIGOBPIN_PAD) = TCBPIN.CODIGO
    LEFT JOIN FUENTE_RECURSOS FR  ON SALDO.COMPANIA = FR.COMPANIA ]') || TO_CLOB(q'[AND SALDO.ANO =FR.ANO AND SALDO.FUENTE_RECURSO = FR.CODIGO
    WHERE SALDO.COMPANIA = s$compania$s
    AND SALDO.ANO   = s$ano$s
    AND SALDO.MES  <= s$mes$s
    AND NVL(INI.CODIGOCCPET_MAN, INI.CODIGOCCPET_PAD) IS NOT NULL
    GROUP BY
    NVL(INI.CODIGOCCPET_MAN,INI.CODIGOCCPET_PAD),
    NVL(NVL(INI.CODIGOCPI_MAN,INI.CODIGOCPI_PAD),0),
    NVL(TCCPI.NOMBRE, '-'),
    NVL(NVL(INI.CODIGOCCP_MAN,INI.CODIGOCCP_PAD),0),
    NVL(TCDANE.NOMBRE, '-'),
    NVL(INI.CODIGOBPIN_MAN,INI.CODIGOBPIN_PAD),
    NVL(TCBPIN.NOMBRE, '-'),
    NVL(FR.EQUIVALENTECUIPO,0),
    CASE WHEN FR.EQUIVALENTECUIPO IS NULL THEN '-' ELSE  NVL(FR.NOMBRE, '-') END, INI.COMPANIA,INI.ANO,
    CASE WHEN INI.CONSITUACIONFONDOS = -1 THEN 'S' ELSE 'C' END
    HAVING(SUM(CASE WHEN SALDO.MES < 1
                    THEN   APROPIACION_DEBITO  - APROPIACION_CREDITO - TRASLADO_CREDITO + TRASLADO_DEBITO + ADICION + REDUCCION
                    ELSE 0 END
                )+
           SUM(SALDO.ADICION)+
           SUM(SALDO.REDUCCION*-1)+
           SUM(SALDO.TRASLADO_DEBITO)+
           SUM(SALDO.TRASLADO_CREDITO )+
          SUM(   APROPIACION_DEBITO  - APROPIACION_CREDITO - TRASLADO_CREDITO + TRASLADO_DEBITO - SALDO.APLAZAM_CREDITO + SALDO.APLAZAM_DEBITO + ADICION + REDUCCION) +
           SUM(SALDO.DISPONIBILIDAD) +
           SUM(SALDO.REG_CONTRACT
                   + SALDO.REG_NO_CONTRACT
                   + SALDO.MODIF_REG_CONT
                   + SALDO.MODIF_REG_NOCONT
                ) +
            SUM(SALDO.REGISTRO_OBLIGACION
                   + SALDO.MODIF_REGISTRO_OBLIGACION
              )  +
             SUM(  SALDO.EJE_PPT_DEBITO - SALDO.EJE_PPT_CREDITO
              ))  <>0) F
ON  P.COMPANIA = F.COMPANIA
AND P.ANO = F.ANO
AND P.CODIGO = SUBSTR(F.CODIGO,1,LENGTH(P.CODIGO))
AND P.CLASECLASIFICADOR = 006
GROUP BY P.CODIGO,P.NOMBRE,CASE WHEN P.MOVIMIENTO <> 0 THEN F.CPI END, CASE WHEN P.MOVIMIENTO <> 0 THEN F.CPINOMBRE END,CASE WHEN P.MOVIMIENTO <> 0 THEN F.CCP END,
CASE WHEN P.MOVIMIENTO <> 0 THEN F.CCPNOMBRE END,CASE WHEN P.MOVIMIENTO <> 0 THEN F.BPIN END,CASE WHEN P.MOVIMIENTO <> 0 THEN F.BPINOMBRE END,
CASE WHEN P.MOVIMIENTO <> 0 THEN F.FUENTE END,CASE WHEN P.MOVIMIENTO <> 0 THEN F.FUENTENOMBRE END,CASE WHEN P.MOVIMIENTO <> 0 THEN F.FONDOS END
ORDER BY P.CODIGO]') CONSULTA, 3 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, 'NCARDENAS' CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);