MERGE INTO CONSULTAS FIN USING (SELECT '8000579Rpt_Ejecucion_Presupuestal_Gastos' INFORME ,TO_CLOB(q'[SELECT 
    V_PLAN_PRESUPUESTAL.CODIGO,
    V_PLAN_PRESUPUESTAL.ID AS CUENTA,  
    V_PLAN_PRESUPUESTAL.NOMBRE,
    V_PLAN_PRESUPUESTAL.AUXILIAR,
    SUM(SALDOS.APROPIACIONINICIAL) AS APROPIACION_INICIAL,
    SUM(SALDOS.ADICION_PERIODO) AS ADICION_PERIODO,
    SUM(SALDOS.REDUCCION_PERIODO) AS REDUCCION_PERIODO,
    SUM(SALDOS.CREDITOS_PERIODO) AS CREDITOS_PERIODO,
    SUM(SALDOS.CONTRA_CREDITOS_PERIODO) AS CONTRA_CREDITOS_PERIODO,
    SUM(SALDOS.ADICION_ACUMULADA) AS ADICION_ACUMULADA,
    SUM(SALDOS.REDUCCION_ACUMULADA) AS REDUCCION_ACUMULADA,
    SUM(SALDOS.CREDITOS_ACUMULADO) AS CREDITOS_ACUMULADO,
    SUM(SALDOS.CONTRA_CREDITOS_ACUMULADO) AS CONTRA_CREDITOS_ACUMULADO,
    SUM(SALDOS.APLAZAMIENTO_ACUMULADO) AS APLAZAMIENTO_ACUMULADO,
    SUM(SALDOS.DESAPLAZAMIENTO_ACUMULAFO) AS DESAPLAZAMIENTO_ACUMULAFO,
    SUM(SALDOS.APROPIACION_DEFINITIVA) AS APROPIACION_DEFINITIVA,
    SUM(SALDOS.CERTIFICADOS) AS CERTIFICADOS,
    SUM(SALDOS.CERTIFICADOS_ACUMULADOS) AS CERTIFICADOS_ACUMULADOS,
    (SUM(SALDOS.APROPIACION_DEFINITIVA) - SUM(SALDOS.CERTIFICADOS_ACUMULADOS)) AS SALDO_DISPONIBLE,
    SUM(SALDOS.COMPROMISOS) AS COMPROMISOS,
    SUM(SALDOS.COMPROMISOS_ACUMULADOS) AS COMPROMISOS_ACUMULADOS,
    (SUM(SALDOS.DISPONIBILIDAD) - SUM(SALDOS.COMPROMISOS_ACUMULADOS)) AS DISPONIBILIDADES_ABIERTAS,
    SUM(SALDOS.OBLIGACIONES) AS OBLIGACIONES,
    SUM(SALDOS.OBLIGACIONES_ACUMULADAS) AS OBLIGACIONES_ACUMULADAS,
    SUM(SALDOS.PAGOS) AS PAGOS,
    SUM(SALDOS.PAGOS_ACUMULADOS) AS PAGOS_ACUMULADOS,
    (SUM(SALDOS.OBLIGACIONES_ACUMULADAS) - SUM(SALDOS.PAGOS_ACUMULADOS)) AS SALDO_POR_PAGAR,
    (SUM(SALDOS.APROPIACION_DEFINITIVA) - SUM(SALDOS.COMPROMISOS_ACUMULADOS)) AS SALDO_DE_APROPIACION
FROM V_PLAN_PRESUPUESTAL 
INNER JOIN (
    SELECT 
        PLAN_PRESUPUESTAL.COMPANIA,
        PLAN_PRESUPUESTAL.ANO,
        SALDO_AUX_PPTAL.ID,
        SALDO_AUX_PPTAL.AUXILIAR,
        SUM(SALDO_AUX_PPTAL.APROPIACION_DEBITO) AS APROPIACIONINICIAL,
        
        SUM(CASE WHEN SALDO_AUX_PPTAL.MES BETWEEN s$mes$s  AND s$mesFinal$s 
            THEN SALDO_AUX_PPTAL.ADICION 
            ELSE 0 END) AS ADICION_PERIODO,
            
        SUM(CASE WHEN SALDO_AUX_PPTAL.MES BETWEEN s$mes$s AND s$mesFinal$s
            THEN SALDO_AUX_PPTAL.REDUCCION * -1 
            ELSE 0 END) AS REDUCCION_PERIODO,
            
        SUM(CASE WHEN SALDO_AUX_PPTAL.MES BETWEEN s$mes$s AND s$mesFinal$s 
            THEN SALDO_AUX_PPTAL.TRASLADO_DEBITO 
            ELSE 0 END) AS CREDITOS_PERIODO,
            
        SUM(CASE WHEN SALDO_AUX_PPTAL.MES BETWEEN s$mes$s AND s$mesFinal$s
            THEN SALDO_AUX_PPTAL.TRASLADO_CREDITO 
            ELSE 0 END) AS CONTRA_CREDITOS_PERIODO,
            
        SUM(SALDO_AUX_PPTAL.ADICION) AS ADICION_ACUMULADA,
        SUM(SALDO_AUX_PPTAL.REDUCCION * -1) AS REDUCCION_ACUMULADA,
        SUM(SALDO_AUX_PPTAL.TRASLADO_DEBITO) AS CREDITOS_ACUMULADO,
        SUM(SALDO_AUX_PPTAL.TRASLADO_CREDITO) AS CONTRA_CREDITOS_ACUMULADO,
        
       SUM(CASE WHEN P]') || TO_CLOB(q'[LAN_PRESUPUESTAL.NATURALEZA='C' 
                           THEN   SALDO_AUX_PPTAL.APLAZAM_DEBITO 
                           ELSE  SALDO_AUX_PPTAL.APLAZAM_CREDITO
                           END
                          )
               APLAZAMIENTO_ACUMULADO,        

       SUM(CASE WHEN PLAN_PRESUPUESTAL.NATURALEZA='C' 
                THEN   SALDO_AUX_PPTAL.APLAZAM_CREDITO
                ELSE  SALDO_AUX_PPTAL.APLAZAM_DEBITO
          END) DESAPLAZAMIENTO_ACUMULAFO,
          
        SUM(CASE WHEN PLAN_PRESUPUESTAL.NATURALEZA = 'D' 
            THEN APROPIACION_DEBITO - APROPIACION_CREDITO - TRASLADO_CREDITO + TRASLADO_DEBITO 
            ELSE -APROPIACION_DEBITO + APROPIACION_CREDITO + TRASLADO_CREDITO - TRASLADO_DEBITO 
            END + ADICION + REDUCCION) AS APROPIACION_DEFINITIVA,
        
        SUM(CASE WHEN SALDO_AUX_PPTAL.MES BETWEEN s$mes$s AND s$mesFinal$s 
            THEN SALDO_AUX_PPTAL.DISPONIBILIDAD
            ELSE 0 END) AS CERTIFICADOS,
            
        SUM(SALDO_AUX_PPTAL.DISPONIBILIDAD) AS CERTIFICADOS_ACUMULADOS,
        
        SUM(CASE WHEN SALDO_AUX_PPTAL.MES BETWEEN s$mes$s AND s$mesFinal$s THEN
            SALDO_AUX_PPTAL.REG_CONTRACT 
            + SALDO_AUX_PPTAL.REG_NO_CONTRACT
            + SALDO_AUX_PPTAL.MODIF_REG_CONT
            + SALDO_AUX_PPTAL.MODIF_REG_NOCONT
            ELSE 0 END) AS COMPROMISOS,
            
        SUM(SALDO_AUX_PPTAL.REG_CONTRACT 
            + SALDO_AUX_PPTAL.REG_NO_CONTRACT
            + SALDO_AUX_PPTAL.MODIF_REG_CONT
            + SALDO_AUX_PPTAL.MODIF_REG_NOCONT) AS COMPROMISOS_ACUMULADOS,
        
        SUM(SALDO_AUX_PPTAL.DISPONIBILIDAD) AS DISPONIBILIDAD,
        
        SUM(CASE WHEN SALDO_AUX_PPTAL.MES BETWEEN s$mes$s AND s$mesFinal$s THEN
            SALDO_AUX_PPTAL.REGISTRO_OBLIGACION
            + SALDO_AUX_PPTAL.MODIF_REGISTRO_OBLIGACION
            ELSE 0 END) AS OBLIGACIONES,
            
        SUM(SALDO_AUX_PPTAL.REGISTRO_OBLIGACION
            + SALDO_AUX_PPTAL.MODIF_REGISTRO_OBLIGACION) AS OBLIGACIONES_ACUMULADAS,
        
        SUM(CASE WHEN SALDO_AUX_PPTAL.MES BETWEEN s$mes$s AND s$mesFinal$s THEN
            CASE WHEN PLAN_PRESUPUESTAL.NATURALEZA = 'D' 
                THEN SALDO_AUX_PPTAL.EJE_PPT_DEBITO - SALDO_AUX_PPTAL.EJE_PPT_CREDITO
                ELSE -SALDO_AUX_PPTAL.EJE_PPT_DEBITO + SALDO_AUX_PPTAL.EJE_PPT_CREDITO
            END 
            ELSE 0 END) AS PAGOS,
            
        SUM(CASE WHEN PLAN_PRESUPUESTAL.NATURALEZA = 'D' 
            THEN SALDO_AUX_PPTAL.EJE_PPT_DEBITO - SALDO_AUX_PPTAL.EJE_PPT_CREDITO
            ELSE -SALDO_AUX_PPTAL.EJE_PPT_DEBITO + SALDO_AUX_PPTAL.EJE_PPT_CREDITO
            END) AS PAGOS_ACUMULADOS
            
    FROM PLAN_PRESUPUESTAL 
    INNER JOIN SALDO_AUX_PPTAL
        ON PLAN_PRESUPUESTAL.COMPANIA = SALDO_AUX_PPTAL.COMPANIA 
        AND PLAN_PRESUPUESTAL.ANO = SALDO_AUX_PPTAL.ANO
        AND PLAN_PRESUPUESTAL.CODIGO = SALDO_AUX_PPTAL.CODIGO
    WHERE PLAN_PRESUPUESTAL.COMPANIA = s$compania$s
   ]') || TO_CLOB(q'[     AND PLAN_PRESUPUESTAL.ANO = s$ano$s 
        AND PLAN_PRESUPUESTAL.NATURALEZA IN ('D')
        AND PLAN_PRESUPUESTAL.TIPOVIGENCIA NOT IN ('RC')
        AND SALDO_AUX_PPTAL.MES <= s$mesFinal$s
        AND PLAN_PRESUPUESTAL.REGALIAS IN (0) 
    GROUP BY 
        PLAN_PRESUPUESTAL.COMPANIA,
        PLAN_PRESUPUESTAL.ANO,
        SALDO_AUX_PPTAL.ID,
        SALDO_AUX_PPTAL.AUXILIAR
) SALDOS
    ON V_PLAN_PRESUPUESTAL.COMPANIA = SALDOS.COMPANIA
    AND V_PLAN_PRESUPUESTAL.ANO = SALDOS.ANO
    AND V_PLAN_PRESUPUESTAL.ID = SUBSTR(SALDOS.ID, 1, LENGTH(V_PLAN_PRESUPUESTAL.ID))
    AND V_PLAN_PRESUPUESTAL.CODIGO BETWEEN s$cuentaInicial$s AND s$cuentaFinal$s
GROUP BY 
    V_PLAN_PRESUPUESTAL.CODIGO,
    V_PLAN_PRESUPUESTAL.ID,
    V_PLAN_PRESUPUESTAL.NOMBRE,
    V_PLAN_PRESUPUESTAL.AUXILIAR
ORDER BY V_PLAN_PRESUPUESTAL.CODIGO]') CONSULTA, 3 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);