WITH CERTIFICADODISPRE  AS(
SELECT   
  DETALLE_COMPROBANTE_PPTAL.COMPANIA,
  DETALLE_COMPROBANTE_PPTAL.ANO,
  DETALLE_COMPROBANTE_PPTAL.COMPROBANTE,
  DETALLE_COMPROBANTE_PPTAL.CUENTA,
  SUM(DETALLE_COMPROBANTE_PPTAL.VALOR_DEBITO) VALOR_DEBITO,
  SUM(CASE WHEN TIPO_CPTE = 'ADD' THEN VALOR_DEBITO ELSE 0 END) INCREMENTO_CDP,
  SUM(CASE WHEN TIPO_CPTE = 'DMD' THEN VALOR_CREDITO ELSE 0 END) DECREMENTO_CDP,  
  CASE WHEN SUM(CASE WHEN TIPO_CPTE IN ('DIS','ADD') THEN VALOR_DEBITO ELSE 0 END - CASE WHEN TIPO_CPTE = 'DMD' THEN VALOR_CREDITO ELSE 0 END) = 0 THEN 
  SUM(CASE WHEN TIPO_CPTE = 'DMD' THEN VALOR_CREDITO ELSE 0 END) ELSE 0 END  ANULADO_CDP,
  SUM(CASE WHEN TIPO_CPTE IN ('DIS','ADD') THEN VALOR_DEBITO ELSE 0 END) +
  SUM(CASE WHEN TIPO_CPTE IN  ('ADD')  THEN VALOR_DEBITO ELSE 0 END) - 
  SUM(CASE WHEN TIPO_CPTE IN  ('DMD')  THEN VALOR_CREDITO ELSE 0 END) VALOR_FINAL_CDP
FROM DETALLE_COMPROBANTE_PPTAL
WHERE DETALLE_COMPROBANTE_PPTAL.COMPANIA = s$compania$s
  AND DETALLE_COMPROBANTE_PPTAL.ANO = s$anio$s
  AND DETALLE_COMPROBANTE_PPTAL.MES = s$mes$s
  AND DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE IN ('DIS','ADD','DMD')
GROUP BY DETALLE_COMPROBANTE_PPTAL.COMPANIA,
  DETALLE_COMPROBANTE_PPTAL.ANO,
  DETALLE_COMPROBANTE_PPTAL.COMPROBANTE,
  DETALLE_COMPROBANTE_PPTAL.CUENTA
), CERTIFICADORESPRE  AS(
SELECT   
  DETALLE_COMPROBANTE_PPTAL.COMPANIA,
  DETALLE_COMPROBANTE_PPTAL.ANO,
  DETALLE_COMPROBANTE_PPTAL.COMPROBANTE,
  DETALLE_COMPROBANTE_PPTAL.CUENTA,
  DETALLE_COMPROBANTE_PPTAL.FECHA,
  SUM(DETALLE_COMPROBANTE_PPTAL.VALOR_DEBITO) VALOR_DEBITO,
  SUM(CASE WHEN TIPO_CPTE = 'ADR' THEN VALOR_DEBITO ELSE 0 END) INCREMENTO_CRP,
  SUM(CASE WHEN TIPO_CPTE = 'DMR' THEN VALOR_CREDITO ELSE 0 END) DECREMENTO_CRP, 
  CASE WHEN SUM(CASE WHEN TIPO_CPTE IN ('RES','ADR') THEN VALOR_DEBITO ELSE 0 END - CASE WHEN TIPO_CPTE = 'DMR' THEN VALOR_CREDITO ELSE 0 END) = 0 THEN 
  SUM(CASE WHEN TIPO_CPTE = 'DMR' THEN VALOR_CREDITO ELSE 0 END) ELSE 0 END  ANULADO_CRP,
  SUM(CASE WHEN TIPO_CPTE IN ('RES','ADR') THEN VALOR_DEBITO ELSE 0 END) +
  SUM(CASE WHEN TIPO_CPTE IN  ('ADR')  THEN VALOR_DEBITO ELSE 0 END) - 
  SUM(CASE WHEN TIPO_CPTE IN  ('DMR')  THEN VALOR_CREDITO ELSE 0 END) VALOR_FINAL_CRP
FROM DETALLE_COMPROBANTE_PPTAL
WHERE DETALLE_COMPROBANTE_PPTAL.COMPANIA = s$compania$s
  AND DETALLE_COMPROBANTE_PPTAL.ANO = s$anio$s
  AND DETALLE_COMPROBANTE_PPTAL.MES = s$mes$s
  AND DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE IN ('RES','ADR','DMR')
GROUP BY DETALLE_COMPROBANTE_PPTAL.COMPANIA,
  DETALLE_COMPROBANTE_PPTAL.ANO,
  DETALLE_COMPROBANTE_PPTAL.COMPROBANTE,
  DETALLE_COMPROBANTE_PPTAL.CUENTA,
   DETALLE_COMPROBANTE_PPTAL.FECHA
), PAGOBLIGACIONES AS(
SELECT   
  DETALLE_COMPROBANTE_PPTAL.COMPANIA,
  DETALLE_COMPROBANTE_PPTAL.ANO,
  DETALLE_COMPROBANTE_PPTAL.CUENTA,
  SUM(CASE WHEN TIPO_CPTE IN ('REO','COM','NOM') THEN VALOR_DEBITO ELSE 0 END) OBLIGACIONES,
  SUM(CASE WHEN TIPO_CPTE IN ('EGR') THEN VALOR_DEBITO ELSE 0 END) PAGOS 
FROM DETALLE_COMPROBANTE_PPTAL
WHERE DETALLE_COMPROBANTE_PPTAL.COMPANIA = s$compania$s
  AND DETALLE_COMPROBANTE_PPTAL.ANO = s$anio$s
  AND DETALLE_COMPROBANTE_PPTAL.MES = s$mes$s
  AND DETALLE_COMPROBANTE_PPTAL.TIPO_CPTE IN ('REO','COM','NOM', 'EGR')
GROUP BY DETALLE_COMPROBANTE_PPTAL.COMPANIA,
  DETALLE_COMPROBANTE_PPTAL.ANO,
  DETALLE_COMPROBANTE_PPTAL.CUENTA
)
SELECT 
  V_RESUMENPPTO_BASE.ID,
  V_RESUMENPPTO_BASE.NOMBRE NOMBRE_RUBRO,
  V_RESUMENPPTO_BASE.APROPIACIONVIGENTE APROPIACION_INICIAL,
  V_RESUMENPPTO_BASE.APLAZAMIENTO,
  V_RESUMENPPTO_BASE.REDUCCION REDUCCIONES,
  V_RESUMENPPTO_BASE.ADICION ADICIONES,
  V_RESUMENPPTO_BASE.APRDEFINITIVA APROPIACION_FINAL,
  D_SOLICITUDDISPONIBILIDAD.NUMERO NO_SOLICITUD,
  D_SOLICITUDDISPONIBILIDAD.VALOR VALOR_SOLICITUD,
  CERTIFICADODISPRE.COMPROBANTE NO_CDP,
  CERTIFICADODISPRE.VALOR_DEBITO VALOR_INICIAL_CDP,
  CERTIFICADODISPRE.INCREMENTO_CDP,
  CERTIFICADODISPRE.DECREMENTO_CDP,
  CERTIFICADODISPRE.ANULADO_CDP,
  CERTIFICADODISPRE.VALOR_FINAL_CDP,
  V_RESUMENPPTO_BASE.APRDEFINITIVA-CERTIFICADODISPRE.VALOR_FINAL_CDP SALDO_APROPIACION,
  CERTIFICADORESPRE.FECHA FECHA_CRP,
  CERTIFICADORESPRE.COMPROBANTE NO_CRP,
  CERTIFICADORESPRE.VALOR_DEBITO VALOR_INICIAL_CRP,
  CERTIFICADORESPRE.INCREMENTO_CRP,
  CERTIFICADORESPRE.DECREMENTO_CRP,
  CERTIFICADORESPRE.ANULADO_CRP,
  CERTIFICADORESPRE.VALOR_FINAL_CRP,
  CERTIFICADODISPRE.VALOR_FINAL_CDP-CERTIFICADORESPRE.VALOR_FINAL_CRP SALDO_CDP,
  PAGOBLIGACIONES.OBLIGACIONES,
  CERTIFICADORESPRE.VALOR_FINAL_CRP-PAGOBLIGACIONES.OBLIGACIONES SALDO_CRP,
  PAGOBLIGACIONES.PAGOS,
  V_RESUMENPPTO_BASE.APRDEFINITIVA/PAGOBLIGACIONES.PAGOS PORCENTAJE_EJECUCION,
  DEPENDENCIA.NOMBRE
FROM SOLICITUDDISPONIBILIDAD
INNER JOIN DEPENDENCIA
  ON SOLICITUDDISPONIBILIDAD.COMPANIA     = DEPENDENCIA.COMPANIA
  AND SOLICITUDDISPONIBILIDAD.DEPENDENCIA = DEPENDENCIA.CODIGO
INNER JOIN D_SOLICITUDDISPONIBILIDAD 
   ON SOLICITUDDISPONIBILIDAD.COMPANIA = D_SOLICITUDDISPONIBILIDAD.COMPANIA  
  AND  SOLICITUDDISPONIBILIDAD.NUMERO = D_SOLICITUDDISPONIBILIDAD.NUMERO 
  AND  SOLICITUDDISPONIBILIDAD.TIPO_SOLICITUD = D_SOLICITUDDISPONIBILIDAD.TIPO_SOLICITUD
INNER JOIN V_RESUMENPPTO_BASE
  ON  V_RESUMENPPTO_BASE.COMPANIA = D_SOLICITUDDISPONIBILIDAD.COMPANIA
  AND V_RESUMENPPTO_BASE.ANO = D_SOLICITUDDISPONIBILIDAD.COMPANIA
  AND V_RESUMENPPTO_BASE.ID = D_SOLICITUDDISPONIBILIDAD.RUBRO
INNER JOIN CERTIFICADODISPRE
  ON CERTIFICADODISPRE.COMPANIA =  V_RESUMENPPTO_BASE.COMPANIA
  AND CERTIFICADODISPRE.ANO     =  V_RESUMENPPTO_BASE.ANO
  AND CERTIFICADODISPRE.CUENTA  =  V_RESUMENPPTO_BASE.ID
INNER JOIN CERTIFICADORESPRE
  ON CERTIFICADORESPRE.COMPANIA =  V_RESUMENPPTO_BASE.COMPANIA
  AND CERTIFICADORESPRE.ANO     =  V_RESUMENPPTO_BASE.ANO
  AND CERTIFICADORESPRE.CUENTA  =  V_RESUMENPPTO_BASE.ID
INNER JOIN PAGOBLIGACIONES
  ON PAGOBLIGACIONES.COMPANIA =  V_RESUMENPPTO_BASE.COMPANIA
  AND PAGOBLIGACIONES.ANO     =  V_RESUMENPPTO_BASE.ANO
  AND PAGOBLIGACIONES.CUENTA  =  V_RESUMENPPTO_BASE.ID
WHERE SOLICITUDDISPONIBILIDAD.COMPANIA = s$compania$s
AND D_SOLICITUDDISPONIBILIDAD.RUBRO BETWEEN 's$cuentaInicial$s' AND 's$cuentaFinal$s'
