SELECT TO_CHAR(NUMERO_DOCUMENTO) NUMERO_DOCUMENTO
,TO_CHAR(FECHA_DE_REGISTRO, 'DD/MM/YYYY') FECHA_DE_REGISTRO
,TO_CHAR(FECHA_DE_PAGO, 'DD/MM/YYYY') FECHA_DE_PAGO
,ESTADO
,VALOR_BRUTO
,VALOR_DEDUCCIONES
,VALOR_NETO
,TIPO_BENEFICIARIO
,VIGENCIA_PRESUPUESTAL
,TIPOIDENTIFICACION
,IDENTIFICACION
,RAZON_SOCIAL
,MEDIO_DE_PAGO
,TIPO_CUENTA
,NUMERO_CUENTA
,ESTADO_CUENTA
,ENTIDAD_NIT
,ENTIDAD_DESCRIPCION
,DEPENDENCIA
,DEPENDENCIA_DESCRIPCION
,RUBRO
,DESCRIPCION
,FUENTE
,RECURSO
,SIT
,VALOR_PESOS
,VALOR_MONEDA
,VALOR_REINTEGRADO_PESOS
,VALOR_REINTEGRADO_MONEDA
,TESORERIA_PAGADORA
,IDENTIFICACION_PAGADURIA
,CUENTA_PAGADURIA
,ENDOSADA
,TIPOIDENTIFICACION
,NUM_IDENTIFICACION
,NOMBRE_RAZON_SOCIAL
,NUMERO_CUENTA
,CONCEPTO_PAGO
,SOLICITUD_CDP
,CDP
,COMPROMISOS
,CUENTAS_POR_PAGAR
,TO_CHAR(FECHA_CUENTAS_POR_PAGAR, 'DD/MM/YYYY') FECHA_CUENTAS_POR_PAGAR
,OBLIGACIONES
,ORDENES_DE_PAGO
,REINTEGROS
,TO_CHAR(FECHA_DOC_SOPORTE_COMPROMISO, 'DD/MM/YYYY') FECHA_DOC_SOPORTE_COMPROMISO
,TIPO_DOC_SOPORTE_COMPROMISO
,NUM_DOC_SOPORTE_COMPROMISO
,OBJETO_DEL_COMPROMISO
 FROM SIIF_ORDENESPAGO WHERE COMPANIA = s$compania$s
