SELECT 
SUBSTR(AUXILIAR.CODIGO,0,2)SECTOR,
SUBSTR(AUXILIAR.CODIGO,3,2) PROGRAMA,
SUBSTR(AUXILIAR.CODIGO,5,4) SUBPROGRAMA,
SUBSTR(AUXILIAR.CODIGO,9,1) ELEMENTO_CONTITUTIVO,
SUBSTR(AUXILIAR.CODIGO,10,3)COD_PRODUCTO,
PLAN_PPTAL_CONFIG.CODIGO COD_CATALOGO,
        AUXILIAR.NOMBRE,
 SALDO_AUX_PPTAL.FUENTE_RECURSO FUENTE,
SALDO_AUX_PPTAL.CENTRO_COSTO,
SALDO_AUX_PPTAL.REFERENCIA,
       SUM(CASE WHEN SALDO_AUX_PPTAL.MES < s$mesInicial$s 
                THEN CASE WHEN PLAN_PRESUPUESTAL.NATURALEZA='D' 
                          THEN   APROPIACION_DEBITO  - APROPIACION_CREDITO - TRASLADO_CREDITO + TRASLADO_DEBITO 
                               + APLAZAM_DEBITO      - APLAZAM_CREDITO
                          ELSE - APROPIACION_DEBITO  + APROPIACION_CREDITO + TRASLADO_CREDITO - TRASLADO_DEBITO 
                               - APLAZAM_DEBITO      + APLAZAM_CREDITO 
                          END + ADICION + REDUCCION
                ELSE 0 END
            ) AS APROPIACION_INICIAL,
        SUM(CASE WHEN SALDO_AUX_PPTAL.MES BETWEEN s$mesInicial$s AND s$mesFinal$s  
                THEN SALDO_AUX_PPTAL.TRASLADO_DEBITO 
                ELSE 0 END)  CREDITOS,
        SUM(CASE WHEN SALDO_AUX_PPTAL.MES BETWEEN s$mesInicial$s AND s$mesFinal$s  
                THEN SALDO_AUX_PPTAL.TRASLADO_CREDITO 
                ELSE 0 END)  CONTRA_CREDITO,
       SUM(CASE WHEN SALDO_AUX_PPTAL.MES BETWEEN s$mesInicial$s AND s$mesFinal$s  
                THEN (CASE WHEN PLAN_PRESUPUESTAL.NATURALEZA='D' 
                           THEN   SALDO_AUX_PPTAL.APLAZAM_DEBITO - SALDO_AUX_PPTAL.APLAZAM_CREDITO
                           ELSE - SALDO_AUX_PPTAL.APLAZAM_DEBITO + SALDO_AUX_PPTAL.APLAZAM_CREDITO
                           END
                          ) 
                ELSE 0 END)  APLAZAMIENTOS,
        SUM(CASE WHEN SALDO_AUX_PPTAL.MES BETWEEN s$mesInicial$s AND s$mesFinal$s 
                THEN SALDO_AUX_PPTAL.REDUCCION*-1 
                ELSE 0 END)  REDUCCIONES,
        SUM(CASE WHEN SALDO_AUX_PPTAL.MES BETWEEN s$mesInicial$s AND s$mesFinal$s 
                THEN SALDO_AUX_PPTAL.ADICION 
                ELSE 0 END)  ADICIONES,
        SUM(CASE WHEN PLAN_PRESUPUESTAL.NATURALEZA='D' 
                          THEN   APROPIACION_DEBITO  - APROPIACION_CREDITO - TRASLADO_CREDITO + TRASLADO_DEBITO 
                               + APLAZAM_DEBITO      - APLAZAM_CREDITO
                          ELSE - APROPIACION_DEBITO  + APROPIACION_CREDITO + TRASLADO_CREDITO - TRASLADO_DEBITO 
                               - APLAZAM_DEBITO      + APLAZAM_CREDITO 
                          END + ADICION + REDUCCION
           ) AS APROPIACION_DEFINITIVA,
        SUM(SALDO_AUX_PPTAL.DISPONIBILIDAD
           )  CDP_EXPEDIDOS,
        SUM(SALDO_AUX_PPTAL.DISPONIBILIDAD
           ) -  SUM(SALDO_AUX_PPTAL.REG_CONTRACT 
               + SALDO_AUX_PPTAL.REG_NO_CONTRACT
               + SALDO_AUX_PPTAL.MODIF_REG_CONT
               + SALDO_AUX_PPTAL.MODIF_REG_NOCONT
            ) CDP_ABIERTOS,
        SUM(SALDO_AUX_PPTAL.REG_CONTRACT 
               + SALDO_AUX_PPTAL.REG_NO_CONTRACT
               + SALDO_AUX_PPTAL.MODIF_REG_CONT
               + SALDO_AUX_PPTAL.MODIF_REG_NOCONT
            )  COMPROMISOS,
            SUM(SALDO_AUX_PPTAL.REGISTRO_OBLIGACION + SALDO_AUX_PPTAL.MODIF_REGISTRO_OBLIGACION)  OBLIGACIONES,
            SUM(CASE WHEN PLAN_PRESUPUESTAL.NATURALEZA='D' 
                THEN   SALDO_AUX_PPTAL.EJE_PPT_DEBITO - SALDO_AUX_PPTAL.EJE_PPT_CREDITO
                ELSE - SALDO_AUX_PPTAL.EJE_PPT_DEBITO + SALDO_AUX_PPTAL.EJE_PPT_CREDITO
                END 
          )  PAGOS,
	    SUM(CASE WHEN PLAN_PRESUPUESTAL.NATURALEZA='D' 
                          THEN   APROPIACION_DEBITO  - APROPIACION_CREDITO - TRASLADO_CREDITO + TRASLADO_DEBITO 
                               + APLAZAM_DEBITO      - APLAZAM_CREDITO 
                          ELSE - APROPIACION_DEBITO  + APROPIACION_CREDITO + TRASLADO_CREDITO - TRASLADO_DEBITO 
                               - APLAZAM_DEBITO      + APLAZAM_CREDITO 
                          END + ADICION + REDUCCION 
                              -( REG_CONTRACT 
                              + REG_NO_CONTRACT
                              + MODIF_REG_CONT
                              + MODIF_REG_NOCONT)
           ) AS SALDO_POR_COMPROMETER,
     SUM(CASE WHEN PLAN_PRESUPUESTAL.NATURALEZA='D' 
                          THEN   APROPIACION_DEBITO  - APROPIACION_CREDITO - TRASLADO_CREDITO + TRASLADO_DEBITO 
                               + APLAZAM_DEBITO      - APLAZAM_CREDITO
                          ELSE - APROPIACION_DEBITO  + APROPIACION_CREDITO + TRASLADO_CREDITO - TRASLADO_DEBITO 
                               - APLAZAM_DEBITO      + APLAZAM_CREDITO 
                          END + ADICION + REDUCCION
           ) -  SUM(SALDO_AUX_PPTAL.DISPONIBILIDAD ) SALDO_DISPONIBLE,
     SUM(SALDO_AUX_PPTAL.REG_CONTRACT 
               + SALDO_AUX_PPTAL.REG_NO_CONTRACT
               + SALDO_AUX_PPTAL.MODIF_REG_CONT
               + SALDO_AUX_PPTAL.MODIF_REG_NOCONT
            ) - SUM(SALDO_AUX_PPTAL.REGISTRO_OBLIGACION + SALDO_AUX_PPTAL.MODIF_REGISTRO_OBLIGACION)  RESERVA_APROPIACION,
    SUM(SALDO_AUX_PPTAL.REGISTRO_OBLIGACION + SALDO_AUX_PPTAL.MODIF_REGISTRO_OBLIGACION) -  SUM(CASE WHEN PLAN_PRESUPUESTAL.NATURALEZA='D' 
                THEN   SALDO_AUX_PPTAL.EJE_PPT_DEBITO - SALDO_AUX_PPTAL.EJE_PPT_CREDITO
                ELSE - SALDO_AUX_PPTAL.EJE_PPT_DEBITO + SALDO_AUX_PPTAL.EJE_PPT_CREDITO  END  )  CUENTAS_POR_PAGAR
FROM PLAN_PRESUPUESTAL
INNER JOIN SALDO_AUX_PPTAL
  ON PLAN_PRESUPUESTAL.COMPANIA = SALDO_AUX_PPTAL.COMPANIA 
 AND PLAN_PRESUPUESTAL.ANO      = SALDO_AUX_PPTAL.ANO
 AND PLAN_PRESUPUESTAL.CODIGO   = SALDO_AUX_PPTAL.CODIGO
INNER JOIN V_PLAN_PRESUPUESTAL  
 ON V_PLAN_PRESUPUESTAL.COMPANIA = PLAN_PRESUPUESTAL.COMPANIA
AND V_PLAN_PRESUPUESTAL.ANO      = PLAN_PRESUPUESTAL.ANO
AND V_PLAN_PRESUPUESTAL.ID     = SALDO_AUX_PPTAL.CODIGO
LEFT JOIN AUXILIAR 
ON PLAN_PRESUPUESTAL.COMPANIA = AUXILIAR.COMPANIA
AND PLAN_PRESUPUESTAL.ANO = AUXILIAR.ANO
AND SALDO_AUX_PPTAL.AUXILIAR = AUXILIAR.CODIGO
INNER JOIN PLAN_PPTAL_CONFIG
ON V_PLAN_PRESUPUESTAL.COMPANIA = PLAN_PPTAL_CONFIG.COMPANIA
AND V_PLAN_PRESUPUESTAL.ANO = PLAN_PPTAL_CONFIG.ANO
AND V_PLAN_PRESUPUESTAL.CODIGO = PLAN_PPTAL_CONFIG.CODIGO
WHERE PLAN_PRESUPUESTAL.COMPANIA     = s$compania$s
  AND PLAN_PRESUPUESTAL.ANO          = s$anio$s
  AND PLAN_PRESUPUESTAL.NATURALEZA   = 'D'
 AND PLAN_PRESUPUESTAL.CODIGO BETWEEN 's$cuentaInicial$s' AND 's$cuentaFinal$s'
 AND SALDO_AUX_PPTAL.CENTRO_COSTO   BETWEEN  's$centroInicial$s' AND  's$centroFinal$s'
 AND SALDO_AUX_PPTAL.FUENTE_RECURSO BETWEEN  's$fuenteInicial$s' AND  's$fuenteFinal$s'
 AND SALDO_AUX_PPTAL.AUXILIAR BETWEEN 's$auxiliarInicial$s' AND 's$auxiliarFinal$s'
 AND SALDO_AUX_PPTAL.REFERENCIA BETWEEN 's$referenciaInicial$s' AND 's$referenciafinal$s'
 AND SALDO_AUX_PPTAL.MES <= s$mesFinal$s
GROUP BY 
         AUXILIAR.CODIGO,
         AUXILIAR.NOMBRE,
         PLAN_PPTAL_CONFIG.CODIGO,
         SALDO_AUX_PPTAL.FUENTE_RECURSO,
         SALDO_AUX_PPTAL.CENTRO_COSTO,
         SALDO_AUX_PPTAL.REFERENCIA
ORDER BY AUXILIAR.CODIGO         