MERGE INTO CONSULTAS FIN USING (SELECT '800449FEjecucionPptalDRE_Excel' INFORME ,TO_CLOB(q'[WITH EJECUCIONPPTAL AS (SELECT 
        V_RESUMENPPTO_BASE.ID CODIGO,
        V_RESUMENPPTO_BASE.NOMBRE,
        V_RESUMENPPTO_BASE.ANO,
        SUM(V_RESUMENPPTO_BASE.APROPIACIONVIGENTE) APROPIACION,
        SUM(V_RESUMENPPTO_BASE.DISPONIBILIDAD) DISPONIBILIDAD,
        SUM(V_RESUMENPPTO_BASE.APROPIACIONVIGENTE - V_RESUMENPPTO_BASE.DISPONIBILIDAD )PORDISPONERDIS
FROM V_RESUMENPPTO_BASE
WHERE V_RESUMENPPTO_BASE.COMPANIA = s$compania$s
  AND V_RESUMENPPTO_BASE.ANO = s$ano$s
  AND V_RESUMENPPTO_BASE.MES BETWEEN 0 AND s$mes$s
  AND V_RESUMENPPTO_BASE.ID BETWEEN 's$cuentaInicial$s' AND 's$cuentaFinal$s'
  AND V_RESUMENPPTO_BASE.NATURALEZA IN('D')
   s$movimiento$s 
GROUP BY  V_RESUMENPPTO_BASE.CODIGO,
          V_RESUMENPPTO_BASE.ID ,
          V_RESUMENPPTO_BASE.NOMBRE,
          V_RESUMENPPTO_BASE.ANO
ORDER BY V_RESUMENPPTO_BASE.CODIGO) 
SELECT CODIGO RUBRO,
        NOMBRE DESCRIPCION, 
        APROPIACION APROPIACION_PRES_FECHA,
        DISPONIBILIDAD "DISPONIBILIDADES / MESES ANO",
        CASE WHEN APROPIACION NOT IN(0) 
          THEN PCK_SYSMAN_UTL.FC_ROUND(DISPONIBILIDAD / APROPIACION * 100,2)
          ELSE 100
        END "%" ,
        PORDISPONERDIS "SALDO DE APROPIACION"    
FROM EJECUCIONPPTAL]') CONSULTA, 3 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, 'dcastiblanco' CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);