SELECT
    TO_CHAR(PLAN_PRESUPUESTAL.ANO) ANO,
    PLAN_PRESUPUESTAL.CODIGO,
    PLAN_PRESUPUESTAL.NOMBRE,
    '' AS "PMR1",
    '' AS "PMR2",
    '' AS "FUENTERECURSOS"
FROM
    PLAN_PRESUPUESTAL
WHERE
    PLAN_PRESUPUESTAL.COMPANIA = s$compania$s
    AND PLAN_PRESUPUESTAL.ANO = s$anio$s
    AND  PLAN_PRESUPUESTAL.CODIGO  BETWEEN 's$codigoInicial$s' AND 's$codigoFinal$s'
AND ( PLAN_PRESUPUESTAL.MOVIMIENTO NOT IN (
        0
    )
          OR PLAN_PRESUPUESTAL.MAN_CEN_CTO NOT IN (
        0
    )
          OR PLAN_PRESUPUESTAL.MAN_AUX_TER NOT IN (
        0
    )
          OR PLAN_PRESUPUESTAL.MAN_AUX_GEN NOT IN (
        0
    )
          OR PLAN_PRESUPUESTAL.MAN_AUX_REF NOT  IN (
        0
    )
          OR PLAN_PRESUPUESTAL.MAN_AUX_FUE NOT IN (0
    ) )
ORDER BY
    PLAN_PRESUPUESTAL.CODIGO