MERGE INTO CONSULTAS FIN USING (SELECT '800628CuentasConAuxiliaresGastosEspecial' INFORME ,TO_CLOB(q'[SELECT  V.ID CUENTA,
        V.CODIGO, 
        REPLACE(V.NOMBRE,CHR(32)||CHR(32),'')NOMBRE,
        V.CENTRO_COSTO,
        V.AUXILIAR,
        V.REFERENCIA,
        V.FUENTE_RECURSO,
        SUM(APROPIACIONANTERIOR)APROPIACIONANTERIOR,
        SUM(ADICION)ADICION,
        SUM(REDUCCION)REDUCCION,
        SUM(CREDITO)CREDITO,
        SUM(CONTRACREDITOS)CONTRACREDITOS,
        SUM(APLAZAMIENTO)APLAZAMIENTO,
        SUM(DESPLAZAMIENTO)DESPLAZAMIENTO,
        SUM(TOTALAPROPIADO)"TOTAL APROPIADO",
        SUM(DISPONIBILIDADMES) "DISPONIBILIDAD MES",
        SUM(DISPONIBILIDAD)"DISPONIBILIDADES ACUMULADAS",
        SUM(SALDODISPONIBLE)"SALDO DISPONIBLE",
        SUM(COMPROMISOSMES)"COMPROMISOS MES",
        SUM(COMPROMISOS)"COMPROMISOS ACUMULADOS",
        SUM(DISPONIBILIDADABIERTA)"DISPONIBILIDAD ABIERTA",
        SUM(SALDOAPROPIADO)"SALDO APROPIADO",
        SUM(OBLIGACIONESMES)"OBLIGACIONES MES",
        SUM(OBLIGACIONES)"OBLIGACIONES ACUMULADAS",
        SUM(DISPONIBLEOBLIGACIONES)"DISPONIBLE OBLIGACIONES",
        SUM(PAGOSMES)"PAGOS MES",
        SUM(PAGOSACUMULADOS)"PAGOS ACUMULADOS",
        SUM(SALDOPORPAGAR)"SALDO POR PAGAR",
        PCK_SYSMAN_UTL.FC_ROUND(
          CASE WHEN 
            SUM(TOTALAPROPIADO) NOT IN(0) 
                  THEN (SUM(COMPROMISOS) /SUM(TOTALAPROPIADO)) * 100 
                  ELSE 0 
                  END,2)  "% EJECUCION"
  FROM V_PLAN_PRESUPUESTAL V INNER JOIN (SELECT P.COMPANIA,
       P.ANO,
       S.ID,
       SUM(CASE WHEN S.MES < 1 
                THEN CASE WHEN P.NATURALEZA='D' 
                          THEN   APROPIACION_DEBITO  - APROPIACION_CREDITO - TRASLADO_CREDITO + TRASLADO_DEBITO 
                          ELSE - APROPIACION_DEBITO  + APROPIACION_CREDITO + TRASLADO_CREDITO - TRASLADO_DEBITO 
                          END + ADICION + REDUCCION
                ELSE 0 END
            ) AS APROPIACIONANTERIOR,      
       SUM(S.ADICION) AS ADICION,                     
       SUM(S.REDUCCION*-1) AS REDUCCION,          
       SUM(S.TRASLADO_DEBITO)  CREDITO,         
       SUM(S.TRASLADO_CREDITO )  CONTRACREDITOS, 
       SUM(CASE WHEN P.NATURALEZA='D' 
                           THEN   S.APLAZAM_CREDITO
                           ELSE  S.APLAZAM_DEBITO
                           END
                          )APLAZAMIENTO,             
       SUM(CASE WHEN P.NATURALEZA='D' 
                THEN   S.APLAZAM_DEBITO
                ELSE  S.APLAZAM_CREDITO
          END) DESPLAZAMIENTO,  
        SUM(CASE WHEN P.NATURALEZA='D' 
                THEN   APROPIACION_DEBITO  - APROPIACION_CREDITO - TRASLADO_CREDITO + TRASLADO_DEBITO - S.APLAZAM_CREDITO + S.APLAZAM_DEBITO
                ELSE - APROPIACION_DEBITO  + APROPIACION_CREDITO + TRASLADO_CREDITO - TRASLADO_DEBITO - S.APLAZAM_DEBITO + S.APLAZAM_CREDITO 
            END + ADICION + REDUCCION) AS TOTALAPROPIADO,  
            SUM(CASE WHEN S.MES= s$mesFinal$s
               THEN S.DISP]') || TO_CLOB(q'[ONIBILIDAD
            END) DISPONIBILIDADMES,
       SUM(S.DISPONIBILIDAD) DISPONIBILIDAD,  
        SUM(CASE WHEN P.NATURALEZA='D' 
                 THEN   APROPIACION_DEBITO  - APROPIACION_CREDITO - TRASLADO_CREDITO + TRASLADO_DEBITO - S.APLAZAM_CREDITO + S.APLAZAM_DEBITO
                ELSE - APROPIACION_DEBITO  + APROPIACION_CREDITO + TRASLADO_CREDITO - TRASLADO_DEBITO - S.APLAZAM_DEBITO + S.APLAZAM_CREDITO 
            END + ADICION + REDUCCION) - SUM(S.DISPONIBILIDAD )SALDODISPONIBLE,
             SUM(CASE WHEN S.MES=s$mesFinal$s THEN
               S.REG_CONTRACT 
               + S.REG_NO_CONTRACT
               + S.MODIF_REG_CONT
               + S.MODIF_REG_NOCONT
            ELSE 0 END  
            )  COMPROMISOSMES,
       SUM(S.REG_CONTRACT 
               + S.REG_NO_CONTRACT
               + S.MODIF_REG_CONT
               + S.MODIF_REG_NOCONT
            )  COMPROMISOS,
       SUM(S.DISPONIBILIDAD)- SUM(S.REG_CONTRACT 
               + S.REG_NO_CONTRACT
               + S.MODIF_REG_CONT
               + S.MODIF_REG_NOCONT
            ) DISPONIBILIDADABIERTA, 
         SUM(CASE WHEN P.NATURALEZA='D' 
                THEN   APROPIACION_DEBITO  - APROPIACION_CREDITO - TRASLADO_CREDITO + TRASLADO_DEBITO - S.APLAZAM_CREDITO + S.APLAZAM_DEBITO
                ELSE - APROPIACION_DEBITO  + APROPIACION_CREDITO + TRASLADO_CREDITO - TRASLADO_DEBITO - S.APLAZAM_DEBITO + S.APLAZAM_CREDITO 
            END + ADICION + REDUCCION)- SUM(S.REG_CONTRACT 
               + S.REG_NO_CONTRACT
               + S.MODIF_REG_CONT
               + S.MODIF_REG_NOCONT
            ) SALDOAPROPIADO,     
             SUM(CASE WHEN S.MES=s$mesFinal$s THEN
               S.REGISTRO_OBLIGACION
               + S.MODIF_REGISTRO_OBLIGACION
            ELSE 0 END  
            ) OBLIGACIONESMES,  
       SUM(S.REGISTRO_OBLIGACION
               + S.MODIF_REGISTRO_OBLIGACION
          )  OBLIGACIONES,
        SUM(S.REG_CONTRACT 
               + S.REG_NO_CONTRACT
               + S.MODIF_REG_CONT
               + S.MODIF_REG_NOCONT
            )- SUM(S.REGISTRO_OBLIGACION
               + S.MODIF_REGISTRO_OBLIGACION)DISPONIBLEOBLIGACIONES,       
          SUM(CASE WHEN S.MES= s$mesFinal$s THEN
                CASE WHEN P.NATURALEZA='D' 
                THEN   S.EJE_PPT_DEBITO - S.EJE_PPT_CREDITO
                ELSE - S.EJE_PPT_DEBITO + S.EJE_PPT_CREDITO
                END 
            ELSE 0
            END
          )  PAGOSMES , 
       SUM(CASE WHEN P.NATURALEZA='D' 
                THEN   S.EJE_PPT_DEBITO - S.EJE_PPT_CREDITO
                ELSE - S.EJE_PPT_DEBITO + S.EJE_PPT_CREDITO
                END 
          )  PAGOSACUMULADOS,    
      SUM(S.REGISTRO_OBLIGACION
               + S.MODIF_REGISTRO_OBLIGACION
          ) - SUM(CASE WHEN P.NATURALEZA='D' 
                THEN   S.EJE_PPT_DEBITO - S.EJE_PPT_CREDITO
                ELSE - S.EJE_PPT_DEBITO + S.EJE_PPT_CREDITO
                END )]') || TO_CLOB(q'[SALDOPORPAGAR
   FROM PLAN_PRESUPUESTAL P INNER JOIN SALDO_AUX_PPTAL S
   ON P.COMPANIA = S.COMPANIA 
   AND P.ANO      = S.ANO
   AND P.CODIGO   = S.CODIGO
   WHERE P.COMPANIA     = s$compania$s
  AND P.ANO          = s$ano$s 
  AND P.NATURALEZA   IN ('s$naturaleza$s')
  AND S.MES <=s$mesFinal$s
  AND P.CODIGO  BETWEEN 's$codigoInicial$s' AND 's$codigoFinal$s'
  s$centroCosto$s
  s$auxiliar$s
  s$referencia$s
  s$fuenteRecurso$s
 GROUP BY P.COMPANIA,
         P.ANO,
         S.ID
UNION 
    SELECT P.COMPANIA,
       P.ANO,
       S.CODIGO,
       SUM(CASE WHEN S.MES < 1 
                THEN CASE WHEN P.NATURALEZA='D' 
                          THEN   APROPIACION_DEBITO  - APROPIACION_CREDITO - TRASLADO_CREDITO + TRASLADO_DEBITO 
                          ELSE - APROPIACION_DEBITO  + APROPIACION_CREDITO + TRASLADO_CREDITO - TRASLADO_DEBITO 
                          END + ADICION + REDUCCION
                ELSE 0 END
            ) AS APROPIACIONANTERIOR,      
       SUM(S.ADICION) AS ADICION,                     
       SUM(S.REDUCCION*-1) AS REDUCCION,          
       SUM(S.TRASLADO_DEBITO)  CREDITO,         
       SUM(S.TRASLADO_CREDITO )  CONTRACREDITOS, 
       SUM(CASE WHEN P.NATURALEZA='D' 
                           THEN   S.APLAZAM_CREDITO
                           ELSE  S.APLAZAM_DEBITO
                           END
                          )APLAZAMIENTO,             
       SUM(CASE WHEN P.NATURALEZA='D' 
                THEN   S.APLAZAM_DEBITO
                ELSE  S.APLAZAM_CREDITO
          END) DESPLAZAMIENTO,  
        SUM(CASE WHEN P.NATURALEZA='D' 
                THEN   APROPIACION_DEBITO  - APROPIACION_CREDITO - TRASLADO_CREDITO + TRASLADO_DEBITO - S.APLAZAM_CREDITO + S.APLAZAM_DEBITO
                ELSE - APROPIACION_DEBITO  + APROPIACION_CREDITO + TRASLADO_CREDITO - TRASLADO_DEBITO - S.APLAZAM_DEBITO + S.APLAZAM_CREDITO 
            END + ADICION + REDUCCION) AS TOTALAPROPIADO,  
            SUM(CASE WHEN S.MES= s$mesFinal$s
               THEN S.DISPONIBILIDAD
            END) DISPONIBILIDADMES,
       SUM(S.DISPONIBILIDAD) DISPONIBILIDAD,  
        SUM(CASE WHEN P.NATURALEZA='D' 
                 THEN   APROPIACION_DEBITO  - APROPIACION_CREDITO - TRASLADO_CREDITO + TRASLADO_DEBITO - S.APLAZAM_CREDITO + S.APLAZAM_DEBITO
                ELSE - APROPIACION_DEBITO  + APROPIACION_CREDITO + TRASLADO_CREDITO - TRASLADO_DEBITO - S.APLAZAM_DEBITO + S.APLAZAM_CREDITO 
            END + ADICION + REDUCCION) - SUM(S.DISPONIBILIDAD )SALDODISPONIBLE,
             SUM(CASE WHEN S.MES=s$mesFinal$s THEN
               S.REG_CONTRACT 
               + S.REG_NO_CONTRACT
               + S.MODIF_REG_CONT
               + S.MODIF_REG_NOCONT
            ELSE 0 END  
            )  COMPROMISOSMES,
       SUM(S.REG_CONTRACT 
               + S.REG_NO_CONTRACT
               + S.MODIF_REG_CONT
               + S.MODIF_REG_NOCONT
            )  COMPROMISOS,
       SUM(S.DISPONIBILIDAD)- SUM(S.REG_CONTRACT 
               + S]') || TO_CLOB(q'[.REG_NO_CONTRACT
               + S.MODIF_REG_CONT
               + S.MODIF_REG_NOCONT
            ) DISPONIBILIDADABIERTA, 
         SUM(CASE WHEN P.NATURALEZA='D' 
                THEN   APROPIACION_DEBITO  - APROPIACION_CREDITO - TRASLADO_CREDITO + TRASLADO_DEBITO - S.APLAZAM_CREDITO + S.APLAZAM_DEBITO
                ELSE - APROPIACION_DEBITO  + APROPIACION_CREDITO + TRASLADO_CREDITO - TRASLADO_DEBITO - S.APLAZAM_DEBITO + S.APLAZAM_CREDITO 
            END + ADICION + REDUCCION)- SUM(S.REG_CONTRACT 
               + S.REG_NO_CONTRACT
               + S.MODIF_REG_CONT
               + S.MODIF_REG_NOCONT
            ) SALDOAPROPIADO,     
             SUM(CASE WHEN S.MES=s$mesFinal$s THEN
               S.REGISTRO_OBLIGACION
               + S.MODIF_REGISTRO_OBLIGACION
            ELSE 0 END  
            ) OBLIGACIONESMES,  
       SUM(S.REGISTRO_OBLIGACION
               + S.MODIF_REGISTRO_OBLIGACION
          )  OBLIGACIONES,
        SUM(S.REG_CONTRACT 
               + S.REG_NO_CONTRACT
               + S.MODIF_REG_CONT
               + S.MODIF_REG_NOCONT
            )- SUM(S.REGISTRO_OBLIGACION
               + S.MODIF_REGISTRO_OBLIGACION)DISPONIBLEOBLIGACIONES,       
          SUM(CASE WHEN S.MES= s$mesFinal$s THEN
                CASE WHEN P.NATURALEZA='D' 
                THEN   S.EJE_PPT_DEBITO - S.EJE_PPT_CREDITO
                ELSE - S.EJE_PPT_DEBITO + S.EJE_PPT_CREDITO
                END 
            ELSE 0
            END
          )  PAGOSMES , 
       SUM(CASE WHEN P.NATURALEZA='D' 
                THEN   S.EJE_PPT_DEBITO - S.EJE_PPT_CREDITO
                ELSE - S.EJE_PPT_DEBITO + S.EJE_PPT_CREDITO
                END 
          )  PAGOSACUMULADOS,    
      SUM(S.REGISTRO_OBLIGACION
               + S.MODIF_REGISTRO_OBLIGACION
          ) - SUM(CASE WHEN P.NATURALEZA='D' 
                THEN   S.EJE_PPT_DEBITO - S.EJE_PPT_CREDITO
                ELSE - S.EJE_PPT_DEBITO + S.EJE_PPT_CREDITO
                END )SALDOPORPAGAR
  FROM PLAN_PRESUPUESTAL P 
  INNER JOIN SALDO_PLAN_PPTAL S
  ON P.COMPANIA = S.COMPANIA 
 AND P.ANO      = S.ANO
 AND P.CODIGO   = S.CODIGO

 WHERE P.COMPANIA     = s$compania$s
  AND P.ANO          = s$ano$s 
  AND P.NATURALEZA   IN ('s$naturaleza$s')
  AND S.MES <=s$mesFinal$s
  AND P.CODIGO  BETWEEN 's$codigoInicial$s' AND 's$codigoFinal$s'
 GROUP BY P.COMPANIA,
         P.ANO,
         S.CODIGO 
)SALDOS
  ON V.COMPANIA = SALDOS.COMPANIA
  AND V.ANO      = SALDOS.ANO
  AND V.ID       = SALDOS.ID
  GROUP BY  V.ID ,
          V.CODIGO, 
          REPLACE(V.NOMBRE,CHR(32)||CHR(32),''),
          V.CENTRO_COSTO,
          V.AUXILIAR,
          V.REFERENCIA,
          V.FUENTE_RECURSO
      ORDER BY V.ID]') CONSULTA, 3 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);