MERGE INTO CONSULTAS FIN USING (SELECT '800730RptResumenApropiaciones' INFORME ,TO_CLOB(q'[WITH RESUMENAPROPIACIONES AS
 (
    SELECT PLAN_PRESUPUESTAL.COMPANIA,
           PLAN_PRESUPUESTAL.ANO,
           PLAN_PRESUPUESTAL.NOMBRE,
           V1.APROPIADO,
           SUM(SALDO_PLAN_PPTAL.ADICION) ADICION,
           SUM(SALDO_PLAN_PPTAL.REDUCCION) REDUCCION,
           SUM(SALDO_PLAN_PPTAL.TRASLADO_DEBITO - SALDO_PLAN_PPTAL.TRASLADO_CREDITO) TRASLADO,
           SUM(SALDO_PLAN_PPTAL.APLAZAM_DEBITO - SALDO_PLAN_PPTAL.APLAZAM_CREDITO) APLAZAMIENTO,
           SUM(SALDO_PLAN_PPTAL.TRASLADO_CREDITO) CONTRACREDITO,
           SUM(SALDO_PLAN_PPTAL.TRASLADO_DEBITO) CREDITO,
           SUM(SALDO_PLAN_PPTAL.DISPONIBILIDAD) DISPONIBILIDADACUM,
           SALDO_PLAN_PPTAL.CODIGO,
           PLAN_PRESUPUESTAL.NIVEL1,
           PLAN_PRESUPUESTAL.NIVEL2,
           PLAN_PRESUPUESTAL.NIVEL3,
           PLAN_PRESUPUESTAL.NIVEL4,
           PLAN_PRESUPUESTAL.NIVEL5,
           PLAN_PRESUPUESTAL.NIVEL6,
           PLAN_PRESUPUESTAL.NIVEL7,
           PLAN_PRESUPUESTAL.DESTINO
      FROM PLAN_PRESUPUESTAL PLAN_PRESUPUESTAL
      INNER JOIN SALDO_PLAN_PPTAL SALDO_PLAN_PPTAL
             ON PLAN_PRESUPUESTAL.COMPANIA = SALDO_PLAN_PPTAL.COMPANIA
            AND PLAN_PRESUPUESTAL.ANO      = SALDO_PLAN_PPTAL.ANO
           AND PLAN_PRESUPUESTAL.CODIGO        = SALDO_PLAN_PPTAL.CODIGO
      LEFT JOIN (SELECT SALDO.COMPANIA,
                   SALDO.ANO,
                   SALDO.CODIGO,
                   SALDO.APROPIACION_DEBITO - SALDO.APROPIACION_CREDITO APROPIADO,
                   SALDO.MES
                   FROM SALDO_PLAN_PPTAL SALDO) V1
             ON V1.COMPANIA = PLAN_PRESUPUESTAL.COMPANIA
            AND V1.ANO = PLAN_PRESUPUESTAL.ANO
            AND V1.CODIGO = PLAN_PRESUPUESTAL.CODIGO
            AND V1.MES = 0
      WHERE SALDO_PLAN_PPTAL.COMPANIA    = s$compania$s
        AND SALDO_PLAN_PPTAL.CODIGO BETWEEN 's$cuentaInicial$s' AND 's$cuentaFinal$s'
        AND SALDO_PLAN_PPTAL.ANO         = s$anio$s
        AND SALDO_PLAN_PPTAL.MES BETWEEN 0 AND s$mes$s
        AND PLAN_PRESUPUESTAL.NATURALEZA = 'D'
      GROUP BY PLAN_PRESUPUESTAL.COMPANIA,
               PLAN_PRESUPUESTAL.ANO,
               PLAN_PRESUPUESTAL.NOMBRE,
               V1.APROPIADO,
               SALDO_PLAN_PPTAL.CODIGO,
               PLAN_PRESUPUESTAL.NIVEL1,
               PLAN_PRESUPUESTAL.NIVEL2,
               PLAN_PRESUPUESTAL.NIVEL3,
               PLAN_PRESUPUESTAL.NIVEL4,
               PLAN_PRESUPUESTAL.NIVEL5,
               PLAN_PRESUPUESTAL.NIVEL6,
               PLAN_PRESUPUESTAL.NIVEL7,
               PLAN_PRESUPUESTAL.DESTINO
 )SELECT COMPANIA,
         CODIGO AS CUENTA,
         CODIGO,
         NOMBRE,
         APROPIADO,
         ADICION,
         REDUCCION,
         CREDITO,
         CONTRACREDITO,
         DESTINO,
         NIVEL1,
         NIVEL2,
         NIVEL3,
         NIVEL4,
         NIVEL5,
         NIVEL6,
         NIVEL7,
         DISPONIBILIDADACUM,
         TRASLADO,
         APLAZAMIENTO,
         (APROPIADO + ADICION + REDUCCION + TRASLADO ]') || TO_CLOB(q'[+ APLAZAMIENTO) TOTALAPROPIADO,
         DISPONIBILIDADACUM DISPONIBILIDADES,
         (ADICION + REDUCCION + TRASLADO +APLAZAMIENTO) AS MODIFICACIONES,
         ((APROPIADO + ADICION + REDUCCION + TRASLADO + APLAZAMIENTO) - DISPONIBILIDADACUM) SALDOXCOMPROMETER,
         CASE WHEN (APROPIADO + ADICION + REDUCCION + TRASLADO + APLAZAMIENTO) = 0
              THEN 0
              ELSE ROUND((DISPONIBILIDADACUM/(APROPIADO + ADICION + REDUCCION + TRASLADO + APLAZAMIENTO))*100,2)
         END PORC_EJECUTADO,
         CASE WHEN (APROPIADO + ADICION + REDUCCION + TRASLADO + APLAZAMIENTO) = 0
              THEN 0
              ELSE ROUND((((APROPIADO + ADICION + REDUCCION + TRASLADO + APLAZAMIENTO) - DISPONIBILIDADACUM)/(APROPIADO + ADICION + REDUCCION + TRASLADO + APLAZAMIENTO))*100,2)
         END PORC_POREJECUTAR
    FROM RESUMENAPROPIACIONES
  ORDER BY CUENTA]') CONSULTA, 3 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);
  