CREATE OR REPLACE TRIGGER "BD_REFERENCIA"  
  /*
      NAME              : BD_REFERENCIA
      AUTHORS           : SYSMAN  SAS
      AUTHOR MIGRACION  : JOSE PASCUAL GOMEZ BLANCO
      DATE MIGRADOR     : 04/02/2016
      TIME              : 8:15 AM
      SOURCE MODULE     : 
      MODIFIER          : JAVIER ANDRES RODRIGUEZ RIOS
      DATE MODIFIED     : 31/01/2017
      TIME              : 08:55 AM
      DESCRIPTION       : CONTROLA NO BORRAR LA REFERENCIA VARIOS \ SE AJUSTA AL ESTANDAR
                          
  */
BEFORE DELETE ON REFERENCIA 
FOR EACH ROW 
BEGIN
  BEGIN 
    IF :OLD.CODIGO=PCK_DATOS.CONS_REFERENCIA THEN
      RAISE PCK_EXCEPCIONES.EXC_GENERAL;
    END IF;
  EXCEPTION WHEN PCK_EXCEPCIONES.EXC_GENERAL THEN 
  PCK_ERR_MSG.RAISE_WITH_MSG(
                UN_EXC_COD    => SQLCODE
               ,UN_TABLAERROR => 'REFERENCIA'
               ,UN_ERROR_COD  => PCK_ERRORES.ERROR_GRAL_ELIMINARREFER
               );
  END;
END;
