CREATE OR REPLACE TRIGGER "BD_TERCERO"  
  /*
      NAME              : BD_TERCERO
      AUTHORS           : SYSMAN  SAS
      AUTHOR MIGRACION  : JOSE PASCUAL GOMEZ BLANCO
      DATE MIGRADOR     : 04/02/2016
      TIME              : 8:15 AM
      SOURCE MODULE     : 
      MODIFIER          : JAVIER ANDRES RODRIGUEZ RIOS
      DATE MODIFIED     : 31/01/2017
      TIME              : 09:00 AM
      DESCRIPTION       : CONTROLA NO BORRAR EL TERCERO VARIOS \ SE AJUSTA AL ESTANDAR
                          
  */
BEFORE DELETE ON TERCERO
FOR EACH ROW
BEGIN
  BEGIN
    IF :OLD.NIT=PCK_DATOS.CONS_TERCERO THEN
      RAISE PCK_EXCEPCIONES.EXC_GENERAL;
    END IF;
  EXCEPTION WHEN PCK_EXCEPCIONES.EXC_GENERAL THEN 
    PCK_ERR_MSG.RAISE_WITH_MSG(
                UN_EXC_COD    => SQLCODE
               ,UN_TABLAERROR => 'TERCERO'
               ,UN_ERROR_COD  => PCK_ERRORES.ERROR_GRAL_ELIMINARTERCERO
               );
  END;
END;
