CREATE OR REPLACE TRIGGER "BI_CIIU"  
/*
      NAME              : BI_CIIU
      AUTHORS           : SYSMAN  SAS
      AUTHOR MIGRACION  : 
      DATE MIGRADOR     : 
      TIME              : 
      SOURCE MODULE     : 
      MODIFIER          : EDWIN FERNANDO CABRERA MARTINEZ
      DATE MODIFIED     : 23/11/2022
      TIME              : 12:30 PM
      DESCRIPTION       : CREA EL ID DE LOS CODIGOS DE ACTIVIDADES CIIU

  */
BEFORE INSERT ON CIIU
FOR EACH ROW
DECLARE
  MI_RTA NUMBER;
  MI_CAMPOS   VARCHAR2(32000);
  MI_VALORES  VARCHAR2(32000);
BEGIN
	IF ( :NEW.ID_CIIU IS NULL /*OR :NEW.ID_CIIU := -1*/ ) THEN
		:NEW.ID_CIIU := TO_NUMBER( :NEW.CLASE_RIESGO || LPAD(:NEW.COD_CIIU,4,'0')	|| LPAD(:NEW.COD_SUBACTIVIDAD,2,'0'));
	END IF;
END;
/