CREATE OR REPLACE TRIGGER "BI_FORMULARIOS_AMARA"  BEFORE
/*
      NAME              : BI_FORMULARIOS_AMARA
      AUTHORS           : SYSMAN  SAS
      AUTHOR MIGRACION  : 
      DATE MIGRADOR     : 
      TIME              : 
      SOURCE MODULE     : 
      MODIFIER          : JAVIER ANDRES RODRIGUEZ RIOS
      DATE MODIFIED     : 31/01/2017
      TIME              : 09:05 AM
      DESCRIPTION       : SE AJUSTA AL ESTANDAR                          
*/  
  INSERT ON FORMULARIOS_AMARA FOR EACH ROW 
  BEGIN 
    IF(UPPER(:NEW.OPERACION) LIKE 'CREACION')THEN 
      :NEW.CONSECUTIVO:=1;
    ELSE
      SELECT NVL(MAX(CONSECUTIVO),0)+1
      INTO :NEW.CONSECUTIVO
      FROM FORMULARIOS_AMARA
      WHERE ID_FORMULARIO= :NEW.ID_FORMULARIO;
    END IF;
END;
