CREATE OR REPLACE TRIGGER BI_HISTORIAL_UBICACION
  BEFORE INSERT ON HISTORIAL_UBICACION
  FOR EACH ROW
  BEGIN
    IF :NEW.ID_HISTORIAL IS NULL THEN
      SELECT SEQ_HISTORIAL_UBICACION.NEXTVAL INTO :NEW.ID_HISTORIAL FROM DUAL;
    END IF;
  END;