create or replace TRIGGER BIU_SFTIPOCOBRO
  /*
    NAME              : BIU_SFTIPOCOBRO
    AUTHORS           : STEFANINI SYSMAN
    AUTHOR MIGRATION  : ELKIN GEOVANNY AMAYA SILVA
    DATE MIGRATION    : 17/06/2019
    TIME              : 08:27 AM
    SORUCE MODULE     : FACTURACON_GENERAL
    MODIFIER          :
    DATE MODIFIED     :
    TIME              :
    DESCRIPTION       : El campo CODIGO debe ser diferente a CPTE_DIFERIDA
  */
BEFORE INSERT OR UPDATE OF CODIGO,CPTE_DIFERIDA ON SF_TIPO_COBRO
FOR EACH ROW
BEGIN
  IF :NEW.CPTE_DIFERIDA = :NEW.CODIGO THEN
    BEGIN
      RAISE PCK_EXCEPCIONES.EXC_FACTURACION;

    EXCEPTION WHEN PCK_EXCEPCIONES.EXC_FACTURACION THEN
      PCK_ERR_MSG.RAISE_WITH_MSG(UN_EXC_COD   => SQLCODE
                                ,UN_ERROR_COD => PCK_ERRORES.ERR_BIU_SFTIPOCOBRO);
    END;
  END IF;
END;
