CREATE OR REPLACE TRIGGER "BIU_CLASEVISITA"  
/*
      NAME              : BIU_CLASEVISITA
      AUTHORS           : SYSMAN  SAS
      AUTHOR MIGRACION  : 
      DATE MIGRADOR     : 
      TIME              : 
      SOURCE MODULE     : 
      MODIFIER          : JAVIER ANDRES RODRIGUEZ RIOS
      DATE MODIFIED     : 31/01/2017
      TIME              : 09:15 AM
      DESCRIPTION       : SE AJUSTA AL ESTANDAR                          
*/ 
BEFORE INSERT OR UPDATE ON CLASE_VISITA 
FOR EACH ROW
DECLARE
  MI_CANT     NUMBER DEFAULT 0; -- ALMACENA LA CANTIDAD DE REGISTROS QUE CUMPLAN CON LA CONDICIÓN 
BEGIN
  IF  :NEW.IND_CLASIFICAR NOT IN (0) THEN
    BEGIN
      SELECT COUNT(0) CANT
        INTO MI_CANT 
        FROM CLASE_VISITA 
       WHERE COMPANIA  = :NEW.COMPANIA
         AND IND_CLASIFICAR NOT IN (0);
    EXCEPTION WHEN NO_DATA_FOUND THEN
      MI_CANT :=0;
    END ;
  END IF;
  BEGIN 
    IF MI_CANT NOT IN (0) THEN 
      RAISE PCK_EXCEPCIONES.EXC_PROGRAMACION_VISITAS;
      --RAISE_APPLICATION_ERROR(-20000,'Ya existe alguna clase de visita con indicador de Clasificar '||SQLERRM);
    END IF;
  EXCEPTION WHEN PCK_EXCEPCIONES.EXC_PROGRAMACION_VISITAS THEN
    PCK_ERR_MSG.RAISE_WITH_MSG(
                UN_EXC_COD    => SQLCODE
               ,UN_TABLAERROR => 'CLASE_VISITA'
               ,UN_ERROR_COD  => PCK_ERRORES.ERR_PROGVISITAS_CLASE_VISITA
               );
  END;
END;
