CREATE OR REPLACE TRIGGER "BIU_CAMBIOSDEFONDO" 
  /*
    NAME              : BIU_CAMBIOSDEFONDO
    AUTHORS           : STEFANINI SYSMAN
    AUTHOR MIGRATION  : PABLO ANDRÉS ESPITIA CUCA
    DATE MIGRATION    : 11/10/2017
    TIME              : 11:27 AM
    SORUCE MODULE     : NOMINA (6)
    MODIFIER          :
    DATE MODIFIED     :
    TIME              :
    DESCRIPTION       : La FECHA_TRASLADO y el FONDONUEVO deben ser diligenciados para cambiar el fondo.
  */
BEFORE INSERT OR UPDATE OF FECHA_TRASLADO,FONDONUEVO ON CAMBIOSDEFONDO
FOR EACH ROW
BEGIN
  IF (:NEW.FECHA_TRASLADO IS NULL AND :NEW.FONDONUEVO IS NOT NULL) OR (:NEW.FECHA_TRASLADO IS NOT NULL AND :NEW.FONDONUEVO IS NULL) THEN
    BEGIN
      RAISE PCK_EXCEPCIONES.EXC_NOMINA;

    EXCEPTION WHEN PCK_EXCEPCIONES.EXC_NOMINA THEN
      PCK_ERR_MSG.RAISE_WITH_MSG(UN_EXC_COD   => SQLCODE
                                ,UN_ERROR_COD => PCK_ERRORES.ERR_N_TR_BIUCAMFON_CAMBIARFOND);
    END;
  END IF;
END;
