CREATE OR REPLACE TRIGGER "BU_AUT_PERSONAL" 
/*
      NAME              : AU_AUT_PERSONAL
      AUTHORS           : SYSMAN SAS
      AUTHOR MIGRACION  : VICTOR MOLANO
      DATE MIGRADOR     : 20/02/2018
      TIME              : 05:00 PM
      SOURCE MODULE     :
      MODIFIER          :
      DATE MODIFIED     :
      TIME              :
      DESCRIPTION       : Actualiza los campos que deben tener control su valor anterior.
*/
BEFORE UPDATE OR INSERT
ON AUT_PERSONAL
FOR EACH ROW
BEGIN

  :NEW.EMAIL_PERSONAL_A   := CASE WHEN :OLD.EMAIL_PERSONAL <> :NEW.EMAIL_PERSONAL THEN :NEW.EMAIL_PERSONAL ELSE :NEW.EMAIL_PERSONAL_A END;
  :NEW.DIRECCION_A        := CASE WHEN :OLD.DIRECCION <> :NEW.DIRECCION THEN :NEW.DIRECCION ELSE :NEW.DIRECCION_A END;
  :NEW.TELEFONOS_A        := CASE WHEN :OLD.TELEFONOS <> :NEW.TELEFONOS THEN :NEW.TELEFONOS ELSE :NEW.TELEFONOS_A END;
  :NEW.PANTALON_A         := CASE WHEN :OLD.PANTALON <> :NEW.PANTALON THEN :NEW.PANTALON ELSE :NEW.PANTALON_A END;
  :NEW.CAMISA_A           := CASE WHEN :OLD.CAMISA <> :NEW.CAMISA THEN :NEW.CAMISA ELSE :NEW.CAMISA_A END;
  :NEW.CALZADO_A          := CASE WHEN :OLD.CALZADO <> :NEW.CALZADO THEN :NEW.CALZADO ELSE :NEW.CALZADO_A END;
  :NEW.CHAQUETA_A         := CASE WHEN :OLD.CHAQUETA <> :NEW.CHAQUETA THEN :NEW.CHAQUETA ELSE :NEW.CHAQUETA_A END;
  :NEW.PAIS_HAB_A         := CASE WHEN :OLD.PAIS_HAB <> :NEW.PAIS_HAB THEN :NEW.PAIS_HAB ELSE :NEW.PAIS_HAB_A END;
  :NEW.DEPARTAMENTO_HAB_A := CASE WHEN :OLD.DEPARTAMENTO_HAB <> :NEW.DEPARTAMENTO_HAB THEN :NEW.DEPARTAMENTO_HAB ELSE :NEW.DEPARTAMENTO_HAB_A END;
  :NEW.CIUDAD_HAB_A       := CASE WHEN :OLD.CIUDAD_HAB <> :NEW.CIUDAD_HAB THEN :NEW.CIUDAD_HAB ELSE :NEW.CIUDAD_HAB_A END;
END;