CREATE OR REPLACE TRIGGER "CBD_BP_PLAN_IND"  
/*
      NAME              : CBD_MANTENIMIENOT
      AUTHORS           : ESTEFANINI SYSMAN
      AUTHOR MIGRACION  : JONATHAN ENRIQUE GUERRERO TORRES
      DATE MIGRADOR     : 18/10/2017
      TIME              : 9:56 AM
      SOURCE MODULE     : 
      DESCRIPTION       : CONTROLA NO BORRAR CODIGOS SI  TIENE NIVELES POSTERIORES ASOCIADOS.
                          
  */
FOR DELETE ON BP_PLAN_INDICATIVO 
COMPOUND TRIGGER
  TYPE REGISTRO IS RECORD
  (COMPANIA        BP_PLAN_INDICATIVO.COMPANIA%TYPE,
   ANO             BP_PLAN_INDICATIVO.VIGENCIA_INICIAL%TYPE,
   ID              BP_PLAN_INDICATIVO.ID%TYPE
  );
  TYPE REGISTROS IS TABLE OF REGISTRO INDEX BY BINARY_INTEGER;
  TABLA REGISTROS;
  POS NUMBER DEFAULT 0;
  MI_RTA                PCK_SUBTIPOS.TI_LOGICO;
  MI_REEMPLAZOS         PCK_SUBTIPOS.TI_CLAVEVALOR;
BEFORE EACH ROW IS 
BEGIN 
  POS := POS +1;
  TABLA(POS).COMPANIA := :OLD.COMPANIA;
  TABLA(POS).ANO      := :OLD.VIGENCIA_INICIAL;
  TABLA(POS).ID       := :OLD.ID;
  
END BEFORE EACH ROW;
AFTER STATEMENT IS 
  BEGIN
    FOR i  IN 1 .. POS LOOP
      BEGIN 
        MI_RTA := PCK_BANCOS_PROY5.FC_VERICAR_REG_SECUNDA_PLANIND(UN_COMPANIA => TABLA(I).COMPANIA,
                                                                  UN_ANO      => TABLA(I).ANO,
                                                                  UN_ID       => TABLA(I).ID);
         
         IF MI_RTA = -1 THEN 
            RAISE PCK_EXCEPCIONES.EXC_GENERAL;
         END IF;
      EXCEPTION WHEN PCK_EXCEPCIONES.EXC_GENERAL THEN 
        PCK_ERR_MSG.RAISE_WITH_MSG(UN_EXC_COD    => SQLCODE
                                  ,UN_TABLAERROR => 'MANTENIMIENTO'
                                  ,UN_ERROR_COD  => PCK_ERRORES.ERR_BDP_ELIMINAR_ID
                                  ,UN_REEMPLAZOS => MI_REEMPLAZOS);                                                           
     END;
    END LOOP; 
  END AFTER STATEMENT;   
END;
