CREATE OR REPLACE VIEW V_FONDO_DE_PENSION_VOL AS 
SELECT CF.COMPANIA, 
       CF.ID ID_DEL_FONDO, 
       F.NIT,
       F.SUCURSAL,
       F.NOMBRE_FONDO NOMBRE_DEL_FONDO,
       F.FORMA_PAGO, F.BANCO_PAGO, F.TIPO_CUENTA, F.CUENTA_CONSIGNAR, 
       F.DIRECCION DIRECCIONPV,
       F.TELEFONO TELEFONOPV,
       F.CORREOELECTRONICO CORREOELECTRONICOPV,
       F.CODA CODAIPV,
       F.COD_SIIF_PTO COD_SIIF_VOL,
       F.DOC_SIIF DOC_SIIF_VOL,
       F.PUBLICO
FROM CLASEFONDO CF 
INNER JOIN FONDO F ON CF.COMPANIA = F.COMPANIA  AND CF.ID_DE_FONDO = F.ID_DE_FONDO
WHERE CF.CLASE='APV' WITH READ ONLY 
 ;