SELECT
  MANTENIMIENTO.COMPANIA,
  D_MANTENIMIENTO.CONSECUTIVO,
  D_MANTENIMIENTO.CODIGOELEMENTO,
  MANTENIMIENTO.TIPO,
  D_MANTENIMIENTO.COMPROBANTE,
  INVENTARIO.NOMBRECORTO,
  TAREAMANTENI.NOMBRE,
  TAREAMANTENI.CODIGO,
  D_MANTENIMIENTO.FECHAINICIAL,
  D_MANTENIMIENTO.FECHAFINAL,
  D_MANTENIMIENTO.VALORUNITARIO,
  D_MANTENIMIENTO.VALORTOTAL,
  D_MANTENIMIENTO.DESCRIPCION,
  TALLER.NOMBRE NOMBRETALLER,
  TALLER.NIT
FROM MANTENIMIENTO 
  INNER JOIN D_MANTENIMIENTO
    ON MANTENIMIENTO.COMPANIA = D_MANTENIMIENTO.COMPANIA 
    AND MANTENIMIENTO.NUMERO = D_MANTENIMIENTO.COMPROBANTE 
    AND MANTENIMIENTO.TIPO = D_MANTENIMIENTO.TIPO_CPTE 
    AND MANTENIMIENTO.ANO = D_MANTENIMIENTO.ANO
  LEFT JOIN TAREAMANTENI 
    ON  D_MANTENIMIENTO.COMPANIA = TAREAMANTENI.COMPANIA 
    AND D_MANTENIMIENTO.TAREAMANTENIMIENTO = TAREAMANTENI.CODIGO 
  LEFT JOIN TALLER 
    ON  D_MANTENIMIENTO.COMPANIA = TALLER.COMPANIA
    AND D_MANTENIMIENTO.NIT_TALLER = TALLER.NIT 
  INNER JOIN INVENTARIO 
    ON  D_MANTENIMIENTO.COMPANIA = INVENTARIO.COMPANIA
    AND D_MANTENIMIENTO.CODIGOELEMENTO = INVENTARIO.CODIGOELEMENTO
WHERE MANTENIMIENTO.COMPANIA=s$compania$s
  AND D_MANTENIMIENTO.CODIGOELEMENTO BETWEEN 's$codigoActivoDesde$s' AND 's$codigoActivoHasta$s'
  AND MANTENIMIENTO.TIPO IN ('AUT') 
  AND TAREAMANTENI.CODIGO BETWEEN 's$codigoTareaDesde$s' AND 's$codigoTareaHasta$s'
  AND TRUNC(D_MANTENIMIENTO.FECHAINICIAL)>=s$desde$s 
  AND TRUNC(D_MANTENIMIENTO.FECHAFINAL)<=s$hasta$s
  AND TALLER.NIT BETWEEN 's$codigoTallerDesde$s' AND 's$codigoTallerHasta$s'
