SELECT 
    DEPENDENCIA.NOMBRE DEPENDENCIA,
    TERCERO.NOMBRE RESPONSABLE,
     TIPO_DE_AUTOMOTOR.NOMBRE || ' -  '|| D_MANTENIMIENTO.NOMBRELEMENTO  TIPO_DE_BIEN,
    D_MANTENIMIENTO.PLACA PLACASYSMAN,
    D_MANTENIMIENTO.FECHAINICIAL D_MANTE_FECHAINI,
    D_MANTENIMIENTO.FECHAFINAL D_MANTE_FECHAFIN,
    D_MANTENIMIENTO.DESCRIPCION DETALLE_MANTENIMIENTO,
    INVENTARIO_PARQUE_AUTOMOTOR.PLACA PLACA_DE_TRANSITO,
    MANTENIMIENTO.TIPO,
    TO_CHAR(MANTENIMIENTO.FECHA,'DD/MM/YYYY') FECHA,
    MANTENIMIENTO.SOLICITUD AUTORIZACION,
    MANTENIMIENTO_MOV_ASOCIADO.NUM_MOVIMIENTO SALIDA_ALMACEN
FROM MANTENIMIENTO
    INNER JOIN MANTENIMIENTO_MOV_ASOCIADO 
        ON MANTENIMIENTO_MOV_ASOCIADO.COMPANIA = MANTENIMIENTO.COMPANIA
        AND MANTENIMIENTO_MOV_ASOCIADO.ANO = MANTENIMIENTO.ANO
        AND MANTENIMIENTO_MOV_ASOCIADO.TIPOCOMPROBANTE = MANTENIMIENTO.TIPO
        AND MANTENIMIENTO_MOV_ASOCIADO.NUM_MANTENIMIENTO = MANTENIMIENTO.NUMERO
    INNER JOIN D_MANTENIMIENTO 
        ON D_MANTENIMIENTO.COMPANIA = MANTENIMIENTO.COMPANIA
        AND D_MANTENIMIENTO.ANO = MANTENIMIENTO.ANO
        AND D_MANTENIMIENTO.TIPO_CPTE = MANTENIMIENTO.TIPO
        AND D_MANTENIMIENTO.COMPROBANTE = MANTENIMIENTO.NUMERO
    INNER JOIN DEVOLUTIVO 
        ON DEVOLUTIVO.COMPANIA = D_MANTENIMIENTO.COMPANIA
        AND DEVOLUTIVO.ELEMENTO = D_MANTENIMIENTO.CODIGOELEMENTO
        AND DEVOLUTIVO.SERIE = D_MANTENIMIENTO.PLACA
   INNER JOIN RESPONSABLE
        ON DEVOLUTIVO.COMPANIA = RESPONSABLE.COMPANIA
        AND DEVOLUTIVO.RESPONSABLE = RESPONSABLE.CEDULA
        AND DEVOLUTIVO.SUCURSAL_RESPONSABLE =  RESPONSABLE.SUCURSAL
    INNER JOIN TERCERO
        ON TERCERO.COMPANIA = RESPONSABLE.COMPANIA 
        AND TERCERO.NIT = RESPONSABLE.CEDULA
        AND TERCERO.SUCURSAL = RESPONSABLE.SUCURSAL
    INNER JOIN DEPENDENCIA
        ON DEPENDENCIA.COMPANIA = DEVOLUTIVO.COMPANIA
        AND DEPENDENCIA.CODIGO = DEVOLUTIVO.DEPENDENCIA
    INNER JOIN INVENTARIO_PARQUE_AUTOMOTOR 
        ON INVENTARIO_PARQUE_AUTOMOTOR.COMPANIA = DEVOLUTIVO.COMPANIA
        AND INVENTARIO_PARQUE_AUTOMOTOR.CODIGO_ELEMENTO = DEVOLUTIVO.ELEMENTO
        AND INVENTARIO_PARQUE_AUTOMOTOR.SERIE_ELEMENTO = DEVOLUTIVO.SERIE
    LEFT JOIN TIPO_DE_AUTOMOTOR
        ON TIPO_DE_AUTOMOTOR.TIPO_DE_AUTOMOTOR = INVENTARIO_PARQUE_AUTOMOTOR.TIPO
WHERE MANTENIMIENTO.COMPANIA = s$compania$s
    AND   MANTENIMIENTO.TIPO IN ('AUT','EJE')
    AND MANTENIMIENTO.FECHA BETWEEN s$fechaInicial$s AND s$fechaFinal$s
    AND D_MANTENIMIENTO.CODIGOELEMENTO BETWEEN 's$elementoInicial$s' AND 's$elementoFinal$s'
    AND DEVOLUTIVO.SERIE BETWEEN s$serieInicial$s AND s$serieFinal$s
ORDER BY DEVOLUTIVO.SERIE
