52   52                        null                      MENU PRINCIPAL/BANCODEPROYECTOS                                                                                                                                                                                                                                
52   5201                      52                        MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS                                                                                                                                                                                                                        
52   5202                      52                        MENUPRINCIPAL/BANCODEPROYECTOS/PROCESOS                                                                                                                                                                                                                        
52   5203                      52                        MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES                                                                                                                                                                                                                        
52   5204                      52                        MENUPRINCIPAL/BANCODEPROYECTOS/MANTENIMIENTO                                                                                                                                                                                                                   
52   520101                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/PLAN DE DESARROLLO                                                                                                                                                                                                     
52   520102                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/PLAN INDICATIVO                                                                                                                                                                                                        
52   520103                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/NIVELES DE PLAN INDICATIVO                                                                                                                                                                                             
52   520104                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/NIVELES DE CUMPLIMIENTO                                                                                                                                                                                                
52   520105                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/FUENTES DE FINANCIACIÓN                                                                                                                                                                                                
52   520106                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/ENTIDADES                                                                                                                                                                                                              
52   520107                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/MODELO FICHAS TÉCNICAS                                                                                                                                                                                                 
52   520108                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/SECTORES DNP                                                                                                                                                                                                           
52   520109                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/TIPO FUENTE RECURSO                                                                                                                                                                                                    
52   520110                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/GASTOS INVERSION                                                                                                                                                                                                       
52   520111                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/TIPOS DE PROYECTOS                                                                                                                                                                                                     
52   520112                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/TIPOS DE NOVEDAD TÉCNICA                                                                                                                                                                                               
52   520113                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/TIPOS DE NOVEDAD DE PROYECTOS                                                                                                                                                                                          
52   520114                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/TIPOS COMPONENTES                                                                                                                                                                                                      
52   520115                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/PROCESOS INICIALES                                                                                                                                                                                                     
52   520116                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/UNIDAD PRODUCTO                                                                                                                                                                                                        
52   520117                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/ACTIVIDADES                                                                                                                                                                                                            
52   520118                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/DIVISION POLITICA                                                                                                                                                                                                      
52   520119                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/DEPENDENCIA-RESPONSABLE                                                                                                                                                                                                
52   520121                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/RESPONSABLES                                                                                                                                                                                                           
52   520122                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/FESTIVOS                                                                                                                                                                                                               
52   520123                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/CÓDIGOS FUT                                                                                                                                                                                                            
52   520127                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/PREGUNTAS PROYECTOS                                                                                                                                                                                                    
52   520128                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/PLANTILLA DOCUMENTOS                                                                                                                                                                                                   
52   520129                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/SECTORES                                                                                                                                                                                                               
52   520130                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/TIPOS DE RECURSOS                                                                                                                                                                                                      
52   520131                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/TIPO SIRECI APSB                                                                                                                                                                                                       
52   520132                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/TIPO SIRECI INF                                                                                                                                                                                                        
52   520133                    5201                      MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/ARMONIZACIÓN PLAN DE DESARROLLO                                                                                                                                                                                        
52   520201                    5202                      MENUPRINCIPAL/BANCODEPROYECTOS/PROCESOS/PROYECTOS                                                                                                                                                                                                              
52   520202                    5202                      MENUPRINCIPAL/BANCODEPROYECTOS/PROCESOS/PROGRAMACION Y SEGUIMIENTO                                                                                                                                                                                             
52   520203                    5202                      MENUPRINCIPAL/BANCODEPROYECTOS/PROCESOS/NOVEDADES DE PROYECTO                                                                                                                                                                                                  
52   520204                    5202                      MENUPRINCIPAL/BANCODEPROYECTOS/PROCESOS/MONITORES                                                                                                                                                                                                              
52   520205                    5202                      MENUPRINCIPAL/BANCODEPROYECTOS/PROCESOS/SUBIR PROYECTOS DESDE MGA                                                                                                                                                                                              
52   520206                    5202                      MENUPRINCIPAL/BANCODEPROYECTOS/PROCESOS/TODAS LAS NOVEDADES                                                                                                                                                                                                    
52   520301                    5203                      MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/DATOS BÁSICOS                                                                                                                                                                                                          
52   520302                    5203                      MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/INF. PROYECTOS                                                                                                                                                                                                         
52   520303                    5203                      MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/INF. PLAN INDICATIVO                                                                                                                                                                                                   
52   520304                    5203                      MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/INF. PLAN DE DESARROLLO                                                                                                                                                                                                
52   520305                    5203                      MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/INF. BANCOS DE PROYECTOS / CONTRATOS                                                                                                                                                                                   
52   520306                    5203                      MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/ENTES DE CONTROL                                                                                                                                                                                                       
52   520401                    5204                      MENUPRINCIPAL/BANCODEPROYECTOS/MANTENIMIENTO/REVISAR SALDOS                                                                                                                                                                                                    
52   520402                    5204                      MENUPRINCIPAL/BANCODEPROYECTOS/CAMBIAR PERIODICIDAD A UN PROYECTO                                                                                                                                                                                              
52   520403                    5204                      MENUPRINCIPAL/BANCODEPROYECTOS/PROCESOS A PLAN INDICATIVO                                                                                                                                                                                                      
52   520404                    5204                      MENUPRINCIPAL/BANCODEPROYECTOS/MANTENIMIENTO/CREAR AUXILIARES DE PROYECTOS                                                                                                                                                                                     
52   520406                    5204                      MENUPRINCIPAL/BANCODEPROYECTOS/MANTENIMIENTO/ELIMINAR PROYECTO                                                                                                                                                                                                 
52   520407                    5204                      MENUPRINCIPAL/BANCODEPROYECTOS/MANTENIMIENTO/ANULAR NOVEDAD                                                                                                                                                                                                    
52   520408                    5204                      MENUPRINCIPAL/BANCODEPROYECTOS/MANTENIMIENTO/ACTUALIZAR DESC. PLAN INDICATIVO                                                                                                                                                                                  
52   520409                    5204                      MENUPRINCIPAL/BANCODEPROYECTOS/MANTENIMIENTO/ACTUALIZAR VALOR PROGRAMACIÓN FINANCIERA                                                                                                                                                                          
52   520410                    5204                      MENUPRINCIPAL/BANCODEPROYECTOS/MANTENIMIENTO/SUBIR PROYECTOS DESDE MGA                                                                                                                                                                                         
52   520411                    5204                      MENUPRINCIPAL/BANCODEPROYECTOS/MANTENIMIENTO/CREAR PROGRAMACION A PROYECTO                                                                                                                                                                                     
52   520412                    5204                      MENUPRINCIPAL/BANCODEPROYECTOS/MANTENIMIENTO/ARMONIZAR PLAN DE DESARROLLO                                                                                                                                                                                      
52   520413                    5204                      MENUPRINCIPAL/BANCODEPROYECTOS/MANTENIMIENTO/ELIMINAR ACTIVIDADES                                                                                                                                                                                              
52   52010101                  520101                    MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/PLAN DE DESARROLLO/PLAN PRESUPUESTAL                                                                                                                                                                                   
52   52010102                  520101                    MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/PLAN DE DESARROLLO/RUBROS DE INVERSIÓN                                                                                                                                                                                 
52   52010201                  520102                    MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/PLAN INDICATIVO/DATOS BÁSICOS DEL PLAN INDICATIVO                                                                                                                                                                      
52   52010202                  520102                    MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/PLAN INDICATIVO/PONDERACIÓN DEL PLAN INDICATIVO                                                                                                                                                                        
52   52010203                  520102                    MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/PLAN INDICATIVO/PROGRAMACIÓN DE METAS DE PRODUCTO                                                                                                                                                                      
52   52011801                  520118                    MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/DIVISION POLITICA/PAÍSES                                                                                                                                                                                               
52   52011802                  520118                    MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/DIVISION POLITICA/DEPARTAMENTOS - CIUDADES                                                                                                                                                                             
52   52011803                  520118                    MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/DIVISION POLITICA/DIVISIÓN MUNICIPAL                                                                                                                                                                                   
52   52011804                  520118                    MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/DIVISION POLITICA/REGIONES                                                                                                                                                                                             
52   52011805                  520118                    MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/DIVISION POLITICA/TIPOS DIVISIÓN                                                                                                                                                                                       
52   52011806                  520118                    MENUPRINCIPAL/BANCODEPROYECTOS/ARCHIVOS/DIVISION POLITICA/ASOCIACIONES MUNICIPALES                                                                                                                                                                             
52   52020101                  520201                    MENUPRINCIPAL/BANCODEPROYECTOS/PROCESOS/PROYECTOS/REGISTRO DE PROYECTOS                                                                                                                                                                                        
52   52020102                  520201                    MENUPRINCIPAL/BANCODEPROYECTOS/PROCESOS/PROYECTOS/CONSULTA DE PROYECTOS                                                                                                                                                                                        
52   52020201                  520202                    MENUPRINCIPAL/BANCODEPROYECTOS/PROCESOS/PROGRAMACION Y SEGUIMIENTO/PROGRAMACION FINANCIERA                                                                                                                                                                     
52   52020202                  520202                    MENUPRINCIPAL/BANCODEPROYECTOS/PROCESOS/PROGRAMACION Y SEGUIMIENTO/PROGRAMACION FINANCIERA EJECUTADA                                                                                                                                                           
52   52020301                  520203                    MENUPRINCIPAL/BANCODEPROYECTOS/PROCESOS/NOVEDADES DE PROYECTO/SOLICITUD CDP                                                                                                                                                                                    
52   52020302                  520203                    MENUPRINCIPAL/BANCODEPROYECTOS/PROCESOS/SOLICITUD DE CERTIFICADO DE BANCO DE PROYECTOS                                                                                                                                                                         
52   52020401                  520204                    MENUPRINCIPAL/BANCODEPROYECTOS/PROCESOS/MONITORES/MONITORES NOVEDADES PROYECTOS                                                                                                                                                                                
52   52020402                  520204                    MENUPRINCIPAL/BANCODEPROYECTOS/PROCESOS/MONITORES/MONITOR DE PROYECTOS                                                                                                                                                                                         
52   52030101                  520301                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/DATOS BÁSICOS /I.PLAN INDICATIVO                                                                                                                                                                                       
52   52030102                  520301                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/DATOS BÁSICOS /I.FUENTES DE FINANCIACIÓN                                                                                                                                                                               
52   52030103                  520301                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/DATOS BÁSICOS /I.ENTIDADES                                                                                                                                                                                             
52   52030104                  520301                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/DATOS BÁSICOS /I. SECTORES DNP                                                                                                                                                                                         
52   52030105                  520301                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/DATOS BÁSICOS /I.INDICADORES                                                                                                                                                                                           
52   52030106                  520301                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/DATOS BÁSICOS /I. TIPOS DE PROYECTO                                                                                                                                                                                    
52   52030107                  520301                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/DATOS BÁSICOS /I. TIPOS DE NOVEDAD TECNICA                                                                                                                                                                             
52   52030108                  520301                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/DATOS BÁSICOS /I. TIPO DE NOVEDAD DE PROYECTO                                                                                                                                                                          
52   52030109                  520301                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/DATOS BÁSICOS /I. TIPO INDICADOR                                                                                                                                                                                       
52   52030110                  520301                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/DATOS BÁSICOS /I. TIPO DE COMPONENTE                                                                                                                                                                                   
52   52030111                  520301                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/DATOS BÁSICOS /I.PROCESOS                                                                                                                                                                                              
52   52030112                  520301                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/DATOS BÁSICOS /I. UNIDADES DE PRODUCTO                                                                                                                                                                                 
52   52030113                  520301                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/DATOS BÁSICOS /I. ACTIVIDADES                                                                                                                                                                                          
52   52030114                  520301                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/DATOS BÁSICOS /I.DIVISIÓN POLITICA                                                                                                                                                                                     
52   52030115                  520301                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/DATOS BÁSICOS /I.ASOCIACIONES MUNICIPALES                                                                                                                                                                              
52   52030116                  520301                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/DATOS BÁSICOS /I. TIPOS DE DIVISIÓN                                                                                                                                                                                    
52   52030117                  520301                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/DATOS BÁSICOS /I. RESPONSABLES DEPENDENCIA                                                                                                                                                                             
52   52030118                  520301                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/DATOS BÁSICOS /I.DEPENDENCIAS                                                                                                                                                                                          
52   52030119                  520301                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/DATOS BÁSICOS /I.RESPONSABLES                                                                                                                                                                                          
52   52030201                  520302                    MENUPRINCIPAL/BANCOPROYECTOS/INFORMES/INF. PROYECTOS / INFORMES PROYECTOS                                                                                                                                                                                      
52   52030202                  520302                    MENUPADRE/BANCOPROYECTOS/INFORMES/INF. PROYECTOS / CONTRATOS POR PROYECTOS                                                                                                                                                                                     
52   52030203                  520302                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/INF. PROYECTOS/PROYECTOS PLAN DE DESARROLLO                                                                                                                                                                            
52   52030204                  520302                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/INF. PROYECTOS/INFORME SOLICITUDES                                                                                                                                                                                     
52   52030205                  520302                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/INF. PROYECTOS/INFORMES PARA REVISION DE PROYECTOS                                                                                                                                                                     
52   52030206                  520302                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/INF. PROYECTOS/AVANCE DE PROYECTO                                                                                                                                                                                      
52   52030207                  520302                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/INF. PROYECTOS/ENTES DE CONTROL                                                                                                                                                                                        
52   52030301                  520303                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/INFORMES DE PLAN INDICATIVO                                                                                                                                                                                            
52   52030302                  520303                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/INFORMES PARA LA REVISIÓN DE INDICADORES                                                                                                                                                                               
52   52030303                  520303                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/AVANCE PLAN INDICATIVO CUATRENIO                                                                                                                                                                                       
52   52030401                  520304                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/INF. PLAN DE DESARROLLO / COMPORTAMIENTO POR CUATRENIO                                                                                                                                                                 
52   52030402                  520304                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/INF. PLAN DE DESARROLLO / COMPORTAMIENTO POR NIVEL                                                                                                                                                                     
52   52030403                  520304                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/INF. PLAN DE DESARROLLO / INVERSIÓN POR CUATRENIO                                                                                                                                                                      
52   52030404                  520304                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/INF. PLAN DE DESARROLLO / INVERSIÓN POR NIVEL                                                                                                                                                                          
52   52030501                  520305                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/INF. BANCOS DE PROYECTOS / CONTRATOS/ F-SCV-17 PROGRAMACIÓN / EJECUCIÓN - PROY INVERSIÓN                                                                                                                               
52   52030502                  520305                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/INF. BANCOS DE PROYECTOS / CONTRATOS/ F-SCV-18 CERTIFICACIÓN DE CONTRATOS                                                                                                                                              
52   52030601                  520306                    MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/ENTES DE CONTROL/INFORMES SIRECI                                                                                                                                                                                       
52   52040301                  520403                    MENUPRINCIPAL/BANCODEPROYECTOS/MANTENIMIENTO/ PROCESO A PLAN INDICATIVO/ GENERAR PREDECESOR                                                                                                                                                                    
52   52040303                  520403                    MENUPRINCIPAL/BANCODEPROYECTOS/MAYORIZAR PONDERACIÓN                                                                                                                                                                                                           
52   52040304                  520403                    MENUPRINCIPAL/BANCODEPROYECTOS/MAYORIZAR AVANCE DEL PLAN INDICATIVO                                                                                                                                                                                            
52   52040305                  520403                    MENUPRINCIPAL/BANCODEPROYECTOS/ACTUALIZAR PLAN INDICATIVO DESDE NOVEDADES                                                                                                                                                                                      
52   5203020701                52030207                  MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/INF. PROYECTOS/ENTES DE CONTROL/INFORME CONTRALORIA                                                                                                                                                                    
52   5203020702                52030207                  MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/INF. PROYECTOS/ENTES DE CONTROL/INFORME CONTRALORIA                                                                                                                                                                    
52   5203060101                52030601                  MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/ENTES DE CONTROL/INFORMES SIRECI/IF238   PROYECTOS DE INVERSION DEL SISTEMA GENERAL DE REGALIAS                                                                                                                        
52   5203060102                52030601                  MENUPRINCIPAL/BANCODEPROYECTOS/INFORMES/ENTES DE CONTROL/INFORMES SIRECI/INFORME DE EFICACIA DNP                                                                                                                                                               
52   5203060103                52030601                  BANCO DE PROYECTOS\INFORMES\ENTES DE CONTROL\INFORMES SIRECI\IF19_2 PROY. ORIENTADOS A ATENCIÓN DE INFANCIA, NIÑEZ Y ADOLESCENCIA                                                                                                                              
