60   60                        null                      MENU PRINCIPAL/IMPUESTO PREDIAL                                                                                                                                                                                                                                
60   6001                      60                        MENU PRINCIPAL/IMPUESTO PREDIAL/ARCHIVOS                                                                                                                                                                                                                       
60   6002                      60                        MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES                                                                                                                                                                                                           
60   6003                      60                        MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS ANUALES                                                                                                                                                                                                               
60   6004                      60                        MENU PRINCIPAL/IMPUESTO PREDIAL/MANTENIMIENTO                                                                                                                                                                                                                  
60   6005                      60                        MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES                                                                                                                                                                                                                       
60   600101                    6001                      MENU PRINCIPAL/IMPUESTO PREDIAL/ARCHIVOS/USUARIOS DE PREDIAL                                                                                                                                                                                                   
60   600102                    6001                      MENU PRINCIPAL/IMPUESTO PREDIAL/ARCHIVOS/USUARIOS DE PREDIAL INACTIVOS                                                                                                                                                                                         
60   600105                    6001                      MENU PRINCIPAL/IMPUESTO PREDIAL/MODELOS DE RESOLUCIONES                                                                                                                                                                                                        
60   600106                    6001                      MENU PRINCIPAL/IMPUESTO PREDIAL/ARCHIVOS/TASAS INTERÉS                                                                                                                                                                                                         
60   600107                    6001                      MENU PRINCIPAL/IMPUESTO PREDIAL/ARCHIVO/CUOTAS DE PAGO                                                                                                                                                                                                         
60   600108                    6001                      MENU PRINCIPAL/IMPUESTO PREDIAL/ARCHIVOS/TARIFAS DE PREDIAL                                                                                                                                                                                                    
60   600109                    6001                      MENU PRINCIPAL/IMPUESTO PREDIAL/ARCHIVOS/CONCEPTOS DE PREDIAL                                                                                                                                                                                                  
60   600110                    6001                      MENU PRINCIPAL/IMPUESTO PREDIAL/ARCHIVOS/BANCOS DE PAGO                                                                                                                                                                                                        
60   600111                    6001                      MENU PRINCIPAL/IMPUESTO PREDIAL/ARCHIVOS/TIPO DESCUENTOS                                                                                                                                                                                                       
60   600112                    6001                      MENU PRINCIPAL/IMPUESTO PREDIAL/ARCHIVOS/TIPOS DE PREDIOS                                                                                                                                                                                                      
60   600113                    6001                      MENU PRINCIPAL/IMPUESTO PREDIAL/ARCHIVOS/CLASE DE PREDIOS                                                                                                                                                                                                      
60   600114                    6001                      MENU PRINCIPAL/IMPUESTO PREDIAL/ARCHIVOS/AÑO                                                                                                                                                                                                                   
60   600115                    6001                      MENU PRINCIPAL/IMPUESTO PREDIAL/ARCHIVOS/DESTINO PARA DOCUMENTOS                                                                                                                                                                                               
60   600116                    6001                      MENU PRINCIPAL/IMPUESTO PREDIAL/ARCHIVOS/DIVISIÓN POLÍTICA                                                                                                                                                                                                     
60   600119                    6001                      MENU PRINCIPAL/IMPUESTO PREDIAL/ARCHIVOS/TARIFAS ESPECIALES                                                                                                                                                                                                    
60   600120                    6001                      MENU PRINCIPAL/IMPUESTO PREDIAL/ARCHIVOS/TARIFAS RESERVA                                                                                                                                                                                                       
60   600121                    6001                      MENU PRINCIPAL/IMPUESTO PREDIAL/ARCHIVOS/CONFIGURAR FACTOR EXPONENCIAL                                                                                                                                                                                         
60   600122                    6001                      MENU PRINCIPAL/IMPUESTO PREDIAL/ARCHIVOS/FORMATOS DE CERTIFICADOS DE ESTRATO                                                                                                                                                                                   
60   600123                    6001                      MENU PRINCIPAL/IMPUESTO PREDIAL/ARCHIVOS/ESTRATOS SOCIO ECONÓMICOS                                                                                                                                                                                             
60   600124                    6001                      MENU PRINCIPAL/IMPUESTO PREDIAL/ARCHIVOS/CLASE DE MUTACIÓN                                                                                                                                                                                                     
60   600201                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/REGISTRAR PAGOS                                                                                                                                                                                           
60   600202                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/ANULAR RECIBO DE PAGO                                                                                                                                                                                     
60   600204                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/ANULAR PREDIO                                                                                                                                                                                             
60   600205                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/ANULAR PREDIO                                                                                                                                                                                             
60   600206                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/REGISTRO DE PAGOS AÑOS ANTERIORES                                                                                                                                                                         
60   600207                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/REGISTRO DE PAGO CUOTAS DE ACUERDO                                                                                                                                                                        
60   600208                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/FACTURACIÓN EN SERIE                                                                                                                                                                                      
60   600210                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/ANULAR PAZ Y SALVOS                                                                                                                                                                                       
60   600211                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/RESOLUCIONES DEL IGAC                                                                                                                                                                                     
60   600212                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/CAMBIO DE CÉDULA CATASTRAL                                                                                                                                                                                
60   600214                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/REGISTRO DE PRESCRIPCIONES                                                                                                                                                                                
60   600215                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/ANULAR PRESCRIPCION                                                                                                                                                                                       
60   600216                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/IMPORTAR CÓDIGOS POSTALES                                                                                                                                                                                 
60   600217                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/ANULAR PREDIO                                                                                                                                                                                             
60   600218                    6002                      PREDIAL/PROCESOS OCASIONALES/ GENERAR DECLARACIÓN DE AUTOAVALÚO                                                                                                                                                                                                
60   600219                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/ABONOS O SALDOS CRÉDITO                                                                                                                                                                                   
60   600220                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/ANULAR ABONOS O SALDOS CRÉDITO                                                                                                                                                                            
60   600221                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/CAMBIAR CONSECUTIVOS                                                                                                                                                                                      
60   600222                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/INDICAR PREDIOS EXENTOS DE IMPUESTO                                                                                                                                                                       
60   600223                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/EXONERACIÓN DE VIGENCIAS                                                                                                                                                                                  
60   600224                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/RECIBOS EXCEDENTES                                                                                                                                                                                        
60   600225                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/MODIFICACIÓN DE PAGOS                                                                                                                                                                                     
60   600226                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/PAGOS ASOBANCARIA                                                                                                                                                                                         
60   600227                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/COPIA DE FACTURA                                                                                                                                                                                          
60   600228                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/INDICADOR PROCESO DE COBRO                                                                                                                                                                                
60   600230                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/ANULAR CERTIFICADO CATASTRAL                                                                                                                                                                              
60   600231                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/PROCESO DE INCAUTACIÓN                                                                                                                                                                                    
60   600232                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/PAGO DE PAZ Y SALVOS                                                                                                                                                                                      
60   600234                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/ANULAR PREDIO                                                                                                                                                                                             
60   600235                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/MODIFICACIÓN DE ESTRATOS                                                                                                                                                                                  
60   600236                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/APLICA PORCENTAJE DE RESERVA                                                                                                                                                                              
60   600237                    6002                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/ ANULAR CERTIFICADO DE VAlORACIÓN                                                                                                                                                                         
60   600301                    6003                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS ANUALES/PREPARAR CONCEPTOS SIGUIENTE AÑO                                                                                                                                                                              
60   600302                    6003                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS ANUALES/PREPARAR TARIFAS SIGUIENTE AÑO                                                                                                                                                                                
60   600303                    6003                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS ANUALES/CALCULO DEL IMPUESTO PREDIAL                                                                                                                                                                                  
60   600304                    6003                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS ANUALES/CONFIGURACION TARIFAS                                                                                                                                                                                         
60   600308                    6003                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS ANUALES/ACTUALIZACION IGAC TIPO MES                                                                                                                                                                                   
60   600309                    6003                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS ANUALES/ACTUALIZACION IGAC TIPO MES                                                                                                                                                                                   
60   600310                    6003                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS ANUALES/ACTUALIZACION IGAC INFORMACIÓN CATASTRAL TIPO DOS ANUAL                                                                                                                                                       
60   600312                    6003                      MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS ANUALES/INCREMENTOS CON AUTOAVALÚO                                                                                                                                                                                    
60   600400                    6004                      MENU PRINCIPAL/IMPUESTO PREDIAL/MANTENIMIENTO/ACUERDOS DE PAGO - ACTUALIZACIÓN CUOTAS                                                                                                                                                                          
60   600401                    6004                      MENU PRINCIPAL/IMPUESTO PREDIAL/MANTENIMIENTO/REVISIÓN DE DATOS ERRÓNEOS                                                                                                                                                                                       
60   600402                    6004                      MENU PRINCIPAL/IMPUESTO PREDIAL/DEPURACIÓN DE CUPONES DE PAGO                                                                                                                                                                                                  
60   600403                    6004                      MENU PRINCIPAL/IMPUESTO PREDIAL/MANTENIMIENTO/ACTUALIZACIÓN ULTIMA VIG. CANCELADA                                                                                                                                                                              
60   600404                    6004                      MENU PRINCIPAL/IMPUESTO PREDIAL/MANTENIMIENTO/ELIMINAR CEROS IZQUIERDA NIT                                                                                                                                                                                     
60   600406                    6004                      MENU PRINCIPAL/IMPUESTO PREDIAL/MANTENIMIENTO/ACT. AÑO PAGO - PREDIOS NUEVOS                                                                                                                                                                                   
60   600501                    6005                      MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/CON PREDIOS                                                                                                                                                                                                           
60   600502                    6005                      MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/DE CARTERA                                                                                                                                                                                                            
60   600503                    6005                      MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/OTROS                                                                                                                                                                                                                 
60   600504                    6005                      MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/ESPECIALES                                                                                                                                                                                                            
60   600506                    6005                      MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/ACUERDOS DE PAGO                                                                                                                                                                                                      
60   600507                    6005                      MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/INFORMES DNP                                                                                                                                                                                                          
60   600508                    6005                      MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/PLANO MOROSOS                                                                                                                                                                                                         
60   60011101                  600111                    MENU PRINCIPAL/IMPUESTO PREDIAL/ARCHIVOS/TIPO DESCUENTOS\DESCUENTOS                                                                                                                                                                                            
60   60011102                  600111                    MENU PRINCIPAL/IMPUESTO PREDIAL/ARCHIVOS/TIPO DESCUENTOS\DESCUENTOS POR MES                                                                                                                                                                                    
60   60011103                  600111                    MENU PRINCIPAL/IMPUESTO PREDIAL/ARCHIVOS/TIPO DESCUENTOS\LEY DESCUENTOS ESPECIALES                                                                                                                                                                             
60   60011601                  600116                    MENU PRINCIPAL/IMPUESTO PREDIAL/ARCHIVOS/DIVISIÓN POLÍTICA/PAÍSES                                                                                                                                                                                              
60   60011602                  600116                    MENU PRINCIPAL/IMPUESTO PREDIAL/ARCHIVOS/DIVISIÓN POLÍTICA/DEPARTAMENTOS - CIUDADES                                                                                                                                                                            
60   60023201                  600232                    MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/PAGO DE PAZ Y SALVOS\RECIBOS DE PAZ Y SALVOS                                                                                                                                                              
60   60023202                  600232                    MENU PRINCIPAL/IMPUESTO PREDIAL/PROCESOS OCASIONALES/PAGO DE PAZ Y SALVOS\REGISTRAR PAGOS DE PAZ Y SALVOS                                                                                                                                                      
60   60050101                  600501                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/CON PREDIOS/LISTADO DE PROPITARIOS POR PREDIO                                                                                                                                                                         
60   60050102                  600501                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/CON PREDIOS/LISTADO GENERAL DE PREDIOS                                                                                                                                                                                
60   60050104                  600501                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/CON PREDIOS/RESUMEN DE PREDIOS POR MANZANA Y VEREDA                                                                                                                                                                   
60   60050106                  600501                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/CON PREDIOS/RELACIÓN DE PREDIOS ANULADOS                                                                                                                                                                              
60   60050109                  600501                    PREDIAL\INFORMES\CON PREDIOS\ESTADÍSTICA POR AVALÚOS CATRASTALES                                                                                                                                                                                               
60   60050110                  600501                    PREDIAL\INFORMES\CON PREDIOS\ESTADÍSTICAS CATASTRALES DE LOS PREDIOS NO CONSTRUIDOS                                                                                                                                                                            
60   60050111                  600501                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/CON PREDIOS/ESTADÍSTICAS CATASTRALES POR SECTORES                                                                                                                                                                     
60   60050113                  600501                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/CON PREDIOS/INFORME DE RESOLUCIONES                                                                                                                                                                                   
60   60050115                  600501                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/CON PREDIOS/PROPIETARIOS POR TARIFA                                                                                                                                                                                   
60   60050117                  600501                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/CON PREDIOS/PROYECCIÓN IMPUESTO POR TARIFA                                                                                                                                                                            
60   60050118                  600501                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/CON PREDIOS/LISTADO DE PREDIOS CON AUTOAVALÚO                                                                                                                                                                         
60   60050119                  600501                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/CON PREDIOS/LISTADO DE PREDIOS CON INCAUTACIÓN                                                                                                                                                                        
60   60050120                  600501                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/CON PREDIOS/LISTADO DE PREDIOS CON DESCUENTO FACTURADO                                                                                                                                                                
60   60050121                  600501                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/CON PREDIOS/PREDIOS CON DESCUENTOS ESPECIALES                                                                                                                                                                         
60   60050122                  600501                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/CON PREDIOS/LISTADO DE PREDIOS CON RESERVA                                                                                                                                                                            
60   60050201                  600502                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/DE CARTERA/RECAUDO                                                                                                                                                                                                    
60   60050202                  600502                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/DE CARTERA/DEUDAS                                                                                                                                                                                                     
60   60050203                  600502                    PANEL PRINCIPAL/PREDIAL\INFORMES\DE CARTERA\OTROS INFORMES                                                                                                                                                                                                     
60   60050304                  600503                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/OTROS/CERTIFICADO PREDIAL                                                                                                                                                                                             
60   60050305                  600503                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/OTROS/CERTIFICADO DE PAZ Y SALVO                                                                                                                                                                                      
60   60050306                  600503                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/OTROS/LISTADO DE CERTIFICADOS DE VALORIZACION EXPEDIDOS                                                                                                                                                               
60   60050308                  600503                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/OTROS/RECIBOS DE PAGO ANULADOS                                                                                                                                                                                        
60   60050309                  600503                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/OTROS/CERTIFICADOS DE PAZ Y SALVO EXPEDIDOS                                                                                                                                                                           
60   60050310                  600503                    PANEL PRINCIPAL\PREDIAL\INFORMES\OTROS\CERTIFICADOS DE PAZ Y SALVO ANULADOS                                                                                                                                                                                    
60   60050312                  600503                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/OTROS/LISTADO DE FACTURACIÓN PARA FIRMAS                                                                                                                                                                              
60   60050313                  600503                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/OTROS/RELACIÓN DE PRESCRIPCIONES                                                                                                                                                                                      
60   60050314                  600503                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/OTROS/PREDIOS POR PRESCRIBIR                                                                                                                                                                                          
60   60050315                  600503                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/OTROS/CERTIFICADOS CATASTRALES EXPEDIDOS                                                                                                                                                                              
60   60050316                  600503                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/OTROS/VIGENCIAS EXONERADAS                                                                                                                                                                                            
60   60050317                  600503                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/OTROS/VALORES EXENTOS                                                                                                                                                                                                 
60   60050318                  600503                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/OTROS/VIGENCIAS PRESCRITAS                                                                                                                                                                                            
60   60050319                  600503                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/OTROS/PREDIOS EN PROCESO DE COBRO                                                                                                                                                                                     
60   60050320                  600503                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/OTROS/SALDOS POR APLICAR                                                                                                                                                                                              
60   60050321                  600503                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/OTROS/CERTIFICADOS DE PAZ Y SALVO EXPEDIDOS DE VALORIZACIÓN                                                                                                                                                           
60   60050322                  600503                    PANEL PRINCIPAL\PREDIAL\INFORMES\OTROS\CERTIFICADOS DE PAZ Y SALVO ANULADOS DE VALORIZACIÓN                                                                                                                                                                    
60   60050324                  600503                    PANEL PRINCIPAL\PREDIAL\INFORMES\OTROS\LISTADO DE CERTIFICADOS DE ESTRATO                                                                                                                                                                                      
60   60050325                  600503                    PANEL PRINCIPAL\PREDIAL\INFORMES\OTROS\INFORME DE ESTRATIFICACIÓN                                                                                                                                                                                              
60   60050327                  600503                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/OTROS/INFORME MODIFICACION ESTRATOS                                                                                                                                                                                   
60   60050328                  600503                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/OTROS/AUDITORIA DE IMPUESTO PREDIAL                                                                                                                                                                                   
60   60050401                  600504                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/ESPECIALES/RELACIÓN DE INGRESOS                                                                                                                                                                                       
60   60050404                  600504                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/ESPECIALES/USUARIOS POR CLASE DE PREDIO                                                                                                                                                                               
60   60050405                  600504                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/ESPECIALES/RELACIÓN DE USUARIOS EXCENTOS                                                                                                                                                                              
60   60050406                  600504                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/ESPECIALES/LISTADO RESOLUCIONES DEL IGAC                                                                                                                                                                              
60   60050409                  600504                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/ESPECIALES/RELACIÓN DE CAUSACIÓN                                                                                                                                                                                      
60   60050410                  600504                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/ESPECIALES/ALUMBRADO PÚBLICO DISCRIMINADO                                                                                                                                                                             
60   60050411                  600504                    MENU PRINCIPAL\PREDIAL\INFORMES\ESPECIALES\CERTIFICADO DE ESTRATO                                                                                                                                                                                              
60   60050412                  600504                    MENU PRINCIPAL\PREDIAL\INFORMES\ESPECIALES\RELACIÓN CAR UNIFICADO                                                                                                                                                                                              
60   60050413                  600504                    MENU PRINCIPAL\PREDIAL\INFORMES\ESPECIALES\INFORME DIAN                                                                                                                                                                                                        
60   60050601                  600506                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/ACUERDOS DE PAGO / LISTADO DE ACUERDOS DE PAGO                                                                                                                                                                        
60   60050602                  600506                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/ACUERDOS DE PAGO / LISTADO DE CUOTAS                                                                                                                                                                                  
60   60050603                  600506                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/ACUERDOS DE PAGO / ACUERDOS DE PAGO ELIMINADOS                                                                                                                                                                        
60   60050604                  600506                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/ACUERDOS DE PAGO/REPORTES DE CARTERA                                                                                                                                                                                  
60   60050605                  600506                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/ACUERDOS DE PAGO/REPORTES DE CARTERA RESUMIDA                                                                                                                                                                         
60   60050701                  600507                    PREDIAL\Informes\Informes DNP\Informe de facturados predial                                                                                                                                                                                                    
60   60050702                  600507                    PREDIAL\INFORMES\INFORMES DNP\INFORME DE RECAUDO PREDIAL                                                                                                                                                                                                       
60   60050703                  600507                    PREDIAL\Informes\Informes DNP\Informe de cartera Morosa                                                                                                                                                                                                        
60   60050801                  600508                    MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/PLANO MOROSOS/INFORME PLANO MOROSOS                                                                                                                                                                                   
60   6005020101                60050201                  MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/DE CARTERA/RECAUDO/RELACIONES DETALLADAS DE PREDIAL Y CAR POR RECIBO Y AÑO                                                                                                                                            
60   6005020102                60050201                  MENU PRINCIPAL\IMPUESTO PREDIAL\INFORMES\DE CARTERA\RECAUDO\REPORTE DIARIO DE PREDIAL POR RECIBO                                                                                                                                                               
60   6005020103                60050201                  MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/DE CARTERA/RECAUDO/RELACIÓN DIARIA PAGOS PREDIAL EN BANCOS                                                                                                                                                            
60   6005020104                60050201                  MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/DE CARTERA/RECAUDO/PREDIOS ACTUALIZADOS POR PAGOS                                                                                                                                                                     
60   6005020106                60050201                  MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/DE CARTERA/RECAUDO/LISTADO DE ÚLTIMOS PAGOS                                                                                                                                                                           
60   6005020107                60050201                  PREDIAL/INFORMES/DE CARTERA/RECAUDO/RESUMEN DE RECAUDOS ENTRE FECHAS                                                                                                                                                                                           
60   6005020110                60050201                  MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/DE CARTERA/INFORME CAR                                                                                                                                                                                                
60   6005020111                60050201                  MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/DE CARTERA/INFORME DE RECAUDO - PREDIO CON RESERVA                                                                                                                                                                    
60   6005020112                60050201                  MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/DE CARTERA/INFORME DE RECAUDO ENTRE VIGENCIAS                                                                                                                                                                         
60   6005020201                60050202                  PANEL PRINCIPAL\PREDIAL\INFORMES\DE CARTERA\DEUDAS\FACTURACIÓN POR DIRECCIÓN                                                                                                                                                                                   
60   6005020202                60050202                  PANEL PRINCIPAL\PREDIAL\INFORMES\DE CARTERA\DEUDAS\FACTURACIÓN POR CÓDIGO                                                                                                                                                                                      
60   6005020203                60050202                  PANEL PRINCIPAL/PREDIAL/INFORMES/DE CARTERA/DEUDAS/LISTADO DE FACTURACIÓN                                                                                                                                                                                      
60   6005020204                60050202                  MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/DE CARTERA/DEUDAS/CARTA PARA COBRO DE PREDIAL                                                                                                                                                                         
60   6005020205                60050202                  MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/DE CARTERA/DEUDAS/NOTIFICACIÓN COBRO PREDIAL                                                                                                                                                                          
60   6005020206                60050202                  MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/DE CARTERA/DEUDAS/REPORTE DE NOTIFICACIONES A DEUDORES                                                                                                                                                                
60   6005020208                60050202                  PANEL PRINCIPAL\PREDIAL\INFORMES\DE CARTERA\DEUDAS\DEUDORES DE PREDIAL                                                                                                                                                                                         
60   6005020209                60050202                  MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/DE CARTERA/DEUDAS/DEUDORES POR VIGENCIA                                                                                                                                                                               
60   6005020210                60050202                  PANEL PRINCIPAL/PREDIAL/INFORMES/DE CARTERA/DEUDAS/INFORME DE CARTERA                                                                                                                                                                                          
60   6005020211                60050202                  MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/DE CARTERA/DEUDAS/CARTERA RESUMIDA POR VIGENCIAS                                                                                                                                                                      
60   6005020212                60050202                  MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/DE CARTERA/DEUDAS/ESTADO DE CUENTA                                                                                                                                                                                    
60   6005020213                60050202                  MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/DE CARTERA/DEUDAS/PREDIOS SIN REGISTRAR PAGOS                                                                                                                                                                         
60   6005020214                60050202                  MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/DE CARTERA/DEUDAS/PREDIOS PARA PRESCRIPCIÓN                                                                                                                                                                           
60   6005020215                60050202                  MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/DE CARTERA/DEUDAS/CARTERA POR EDADES                                                                                                                                                                                  
60   6005020219                60050202                  MENU PRINCIPAL/IMPUESTO PREDIAL/INFORMES/DE CARTERA/DEUDAS/DEUDORES POR PROPIETARIO                                                                                                                                                                            
60   6005020220                60050202                  PANEL PRINCIPAL/PREDIAL/INFORMES/DE CARTERA/DEUDAS/FACTURACIÓN POR TIPO DE PREDIO                                                                                                                                                                              
60   6005020221                60050202                  PANEL PRINCIPAL/PREDIAL\INFORMES\DE CARTERA\DEUDAS\REPORTE NOTIFICACIONES DE COBRO                                                                                                                                                                             
60   6005020301                60050203                  PANEL PRINCIPAL/PREDIAL\INFORMES\DE CARTERA\OTROS INFORMES\ERRORES EN CÁLCULO POR LOTES                                                                                                                                                                        
60   6005020303                60050203                  PANEL PRINCIPAL/PREDIAL\INFORMES\DE CARTERA\OTROS INFORMES\EXCEDENTES Y SALDOS EN PAGOS                                                                                                                                                                        
60   6005020304                60050203                  MENU PRINCIPAL/PREDIAL\INFORMES\DE CARTERA\OTROS INFORMES\USUARIOS SIN DEUDA                                                                                                                                                                                   
