65   65                        null                      MENU PRINCIPAL/PROGRAMACION DE VISITAS                                                                                                                                                                                                                         
65   6501                      65                        MENU PRINCIPAL/PROGRAMACION DE VISITAS/ARCHIVOS                                                                                                                                                                                                                
65   6502                      65                        MENU PRINCIPAL/PROGRAMACION DE VISITAS/PROCESOS                                                                                                                                                                                                                
65   6503                      65                        MENU PRINCIPAL/PROGRAMACION DE VISITAS/INFORMES                                                                                                                                                                                                                
65   650101                    6501                      MENU PRINCIPAL/PROGRAMACION DE VISITAS/ARCHIVOS/CLASE DE VISITAS                                                                                                                                                                                               
65   650102                    6501                      MENU PRINCIPAL/PROGRAMACION DE VISITAS/ARCHIVOS/ESTADO VISITA                                                                                                                                                                                                  
65   650103                    6501                      MENU PRINCIPAL/PROGRAMACION DE VISITAS/ARCHIVOS/RESULTADO VISITA                                                                                                                                                                                               
65   650104                    6501                      MENU PRINCIPAL/PROGRAMACION DE VISITAS/ARCHIVOS/DEPENDENCIA-RESPONSABLE                                                                                                                                                                                        
65   650106                    6501                      MENU PRINCIPAL/PROGRAMACION DE VISITAS/ARCHIVOS/RESPONSABLE-DEPENDENCIA                                                                                                                                                                                        
65   650107                    6501                      MENU PRINCIPAL/PROGRAMACION DE VISITAS/ARCHIVOS/TIPO ESTABLECIMIENTO                                                                                                                                                                                           
65   650108                    6501                      MENU PRINCIPAL/PROGRAMACION DE VISITAS/ARCHIVOS/TIPO SERVICIO - VEHICULO                                                                                                                                                                                       
65   650109                    6501                      MENU PRINCIPAL/PROGRAMACION DE VISITAS/ARCHIVOS/VEHICULO VISITA                                                                                                                                                                                                
65   650110                    6501                      MENU PRINCIPAL/PROGRAMACION DE VISITAS/ARCHIVOS/ZONA - PUNTO CARDINAL                                                                                                                                                                                          
65   650201                    6502                      MENU PRINCIPAL/PROGRAMACION DE VISITAS/ARCHIVOS/VISITAS                                                                                                                                                                                                        
65   650301                    6503                      MENU PRINCIPAL/PROGRAMACION DE VISITAS/INFORMES/GENERAR INFORME                                                                                                                                                                                                
