campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
CODIGOELEMENTO                     VARCHAR2                                          16      0           0       N     16          null                                                                                                                                                                                                    
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
MES                                NUMBER                                            22      2           0       N     0           null                                                                                                                                                                                                    
SALDO                              NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CANTENTRADAS                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CANTSALIDAS                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VLRAJUSTEUNIT                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VLRENTRADAS                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VLRSALIDAS                         NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VLRUNITARIO                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VLRTOTAL                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VLRDEPRECIACION                    NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VLRDEPRECIACIONAJUS                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VLRAJUSTE                          NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DEPACUMULADA                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DEPACUMULADAAJUS                   NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VLUNITARIOAJUS                     NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
AJUSTEAPPMES                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DELTAPROMEDIO                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
COSTOSALIDA                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
COSTOSALIDAAJ                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
AJCOSTOSALIDA                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
AJDEPACUMULADA                     NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
AJDEPRECIACION                     NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SALDOBODEGA                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VLRSALDOBODEGA                     NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
AJUSINFLA                          NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DEPREC                             NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
AJUSDEPREC                         NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DEPACUMULADADC                     NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
AJUSTEDEPRECIACION                 NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VLRDEPRECIACIONCOMODATO            NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
AJUSDEPRECCOMODATO                 NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
INDICADOR                          NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
CENTRO_COSTO                       VARCHAR2                                          20      0           0       N     20          '99999999999999999999'                                                                                                                                                                                  
VLRCUANTIAMIN                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA                              TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
