campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
NUMERO                             NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
ASOCIADOPC                         NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
PLANAPROBADO                       NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
SALARIOMINIMO                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CUANTIAMINIMA                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
LIM_AUTORETENEDOR                  NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALORUVT                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
MAXIMOUVT                          NUMBER                                            22      5           0       N     0           0                                                                                                                                                                                                       
PORCENTAJESALUD                    NUMBER                                            22      9           6       N     0           0                                                                                                                                                                                                       
PORCENTAJEPENSION                  NUMBER                                            22      9           6       N     0           0                                                                                                                                                                                                       
VLRFONDOSOL_PENSIONAL              NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MESESAMNISTIA_PREDIAL              NUMBER                                            22      10          0       N     0           0                                                                                                                                                                                                       
FORMULA                            VARCHAR2                                          4000    0           0       Y     4000        null                                                                                                                                                                                                    
MESESAMNISTIA_IMPUESTOS            NUMBER                                            22      10          0       N     0           0                                                                                                                                                                                                       
IPC                                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
PERIODICIDAD                       NUMBER                                            22      5           0       N     0           0                                                                                                                                                                                                       
CUANTIAMINIMADEPRE                 NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_CIERRE_ADQUISICIONES         TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_CIERRE_PLAN_INDI_EJEC        TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_CIERRE_PLAN_ACCION_EJEC      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_CIERRE_PLAN_ACCION           TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_CIERRE_PLAN_INDICATIVO       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_CIERRE_ADQUI_EJEC            TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
PATRIMONIOBRUTO_UVT                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
INGRESOSTOTALES_UVT                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CONSUMOTARJETACRE_UVT              NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
COMPRASYCONSUMO_UVT                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CONSIGNACIONESBANCARIAS_UVT        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
INICIA_CONTABILIDAD                NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
FORMATO_DIAN                       VARCHAR2                                          4000    0           0       Y     4000        null                                                                                                                                                                                                    
CEDULAFIRMACERT_DIAN               VARCHAR2                                          100     0           0       Y     100         null                                                                                                                                                                                                    
NOMBREFIRMACERT_DIAN               VARCHAR2                                          4000    0           0       Y     4000        null                                                                                                                                                                                                    
