campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
CODIGO                             VARCHAR2                                          20      0           0       N     20          null                                                                                                                                                                                                    
NOMBRE                             VARCHAR2                                          120     0           0       N     120         null                                                                                                                                                                                                    
MOVIMIENTO                         NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
CODIGOBP                           VARCHAR2                                          16      0           0       Y     16          null                                                                                                                                                                                                    
COD_EQUIVALENTE_PROY               VARCHAR2                                          10      0           0       Y     10          null                                                                                                                                                                                                    
CONCEPTOCHIPFUTREGALIA             VARCHAR2                                          60      0           0       Y     60          null                                                                                                                                                                                                    
CONCEPTOCHIPFUTDESPLAZADO          VARCHAR2                                          60      0           0       Y     60          null                                                                                                                                                                                                    
COD_FTEFIN                         VARCHAR2                                          2       0           0       Y     2           null                                                                                                                                                                                                    
CODIGO_SIA                         VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
CODIGO_FUT_F3                      VARCHAR2                                          10      0           0       Y     10          null                                                                                                                                                                                                    
REPORTAENREGISTROS                 NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
INVENTARIO                         VARCHAR2                                          16      0           0       Y     16          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
