campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
VIGENCIA_PLAN                      NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
VIGENCIA_META                      NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
ID_META                            VARCHAR2                                          60      0           0       N     60          null                                                                                                                                                                                                    
VIGENCIA_RUBRO                     NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
ID_RUBRO                           VARCHAR2                                          32      0           0       N     32          null                                                                                                                                                                                                    
FUENTE                             VARCHAR2                                          20      0           0       N     20          '99999999999999999999'                                                                                                                                                                                  
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
