campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
VIGENCIA_INICIAL                   NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
VIGENCIA_META                      NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
RUBRO                              VARCHAR2                                          32      0           0       N     32          null                                                                                                                                                                                                    
SUBPROYECTO                        VARCHAR2                                          32      0           0       N     32          null                                                                                                                                                                                                    
PORCENTAJE_PART                    NUMBER                                            22      9           6       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
PORCENTAJE_PART_OBL                NUMBER                                            22      9           6       N     0           0                                                                                                                                                                                                       
CODIGO                             NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
