campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
ID_PLAN                            VARCHAR2                                          60      0           0       N     60          null                                                                                                                                                                                                    
VIGENCIA_INICIAL                   NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
COD_INDICADOR                      VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
COD_PROYECTO                       VARCHAR2                                          16      0           0       N     16          null                                                                                                                                                                                                    
TIPO_META                          VARCHAR2                                          2       0           0       Y     2           null                                                                                                                                                                                                    
CANTIDAD_META                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
