campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
CODIGO                             NUMBER                                            22      5           0       N     0           0                                                                                                                                                                                                       
SECTOR                             VARCHAR2                                          12      0           0       N     12          null                                                                                                                                                                                                    
SECCION                            VARCHAR2                                          255     0           0       N     255         null                                                                                                                                                                                                    
ITEM                               VARCHAR2                                          4000    0           0       N     4000        null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
