campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
ID_PLAN                            VARCHAR2                                          32      0           0       N     32          null                                                                                                                                                                                                    
VIGENCIA_PLAN                      NUMBER                                            22      4           0       N     0           0                                                                                                                                                                                                       
VIGENCIA_META                      NUMBER                                            22      4           0       N     0           0                                                                                                                                                                                                       
FUENTE                             VARCHAR2                                          20      0           0       N     20          '99999999999999999999'                                                                                                                                                                                  
VALOR_POR_FUENTES                  NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
META                               NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CANTIDAD_EJECUTADA                 NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
PRESUPUESTO                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
COMPROMETIDO                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
PAGADO                             NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALOR_OBLIGACIONES                 NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALOR_DISPONIBLE                   NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
