campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
ID_PLAN                            VARCHAR2                                          32      0           0       N     32          null                                                                                                                                                                                                    
VIGENCIA_PLAN                      NUMBER                                            22      4           0       N     0           0                                                                                                                                                                                                       
VIGENCIA_META                      NUMBER                                            22      4           0       N     0           0                                                                                                                                                                                                       
ID_PLAN1                           VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
ID_PLAN2                           VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
ID_PLAN3                           VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
ID_PLAN4                           VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
ID_PLAN5                           VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
ID_PLAN6                           VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DESCRIPCION_1                      VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
DESCRIPCION_2                      VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
DESCRIPCION_3                      VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
DESCRIPCION_4                      VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
DESCRIPCION_5                      VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
DESCRIPCION_6                      VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
