campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
ESCALAFON                          VARCHAR2                                          2       0           0       N     2           null                                                                                                                                                                                                    
ID_DE_CATEGORIA                    VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
NOMBRE_CATEGORIA                   VARCHAR2                                          50      0           0       N     50          null                                                                                                                                                                                                    
SALARIO_BASE                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
GASTOSREPRESENTACION               NUMBER                                            22      9           6       N     0           0                                                                                                                                                                                                       
SALARIOANTERIOR                    NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
GRADO                              NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CODIGOGRADO                        VARCHAR2                                          10      0           0       Y     10          null                                                                                                                                                                                                    
VLREXTRA                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VLR_INCREMENTO                     NUMBER                                            22      9           6       N     0           0                                                                                                                                                                                                       
SALARIO_RETROACTIVO                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
PRIMATECNICA                       NUMBER                                            22      9           6       N     0           0                                                                                                                                                                                                       
SUBSALIMENTACION                   NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SUBSTRANSPORTE                     NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VLR_INCREMENTO_XE                  NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VRLEXTRA_ANTERIOR                  NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
VIATICOPAIS                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VIATICOEXTERIORCA                  NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VIATICOEXTERIOREU                  NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VIATICOEXTERIOREAO                 NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
BONIFICACION_DOCENTE               NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CODCMD                             VARCHAR2                                          1       0           0       Y     1           null                                                                                                                                                                                                    
