campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
TIPO                               VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
NUMERO                             NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
CODIGO                             VARCHAR2                                          10      0           0       N     10          null                                                                                                                                                                                                    
VALOR                              NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CANTIDAD                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
