campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
NUMERO                             NUMBER                                            22      20          0       N     0           0                                                                                                                                                                                                       
NITANTERIOR                        VARCHAR2                                          18      0           0       N     18          null                                                                                                                                                                                                    
SUCURSALANTERIOR                   VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
NITNUEVO                           VARCHAR2                                          18      0           0       N     18          null                                                                                                                                                                                                    
SUCURSALNUEVA                      VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
NOMBREANTERIOR                     VARCHAR2                                          320     0           0       Y     320         null                                                                                                                                                                                                    
NOMBRENUEVO                        VARCHAR2                                          320     0           0       Y     320         null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
