campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
ELEMENTO                           VARCHAR2                                          16      0           0       N     16          null                                                                                                                                                                                                    
SERIE                              NUMBER                                            22      15          0       N     0           0                                                                                                                                                                                                       
VLRELEMENTO                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VLRDEPRECIACION                    NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VLRACUMULADO                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SALDOXDEPRECIAR                    NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VLRAJUSTADO                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VLRACUMULADOAJ                     NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
COSTOAJUSTADO                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VLRLIBROS                          NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
IMPRIMIR                           NUMBER                                            22      5           0       Y     0           null                                                                                                                                                                                                    
VLRAJUSTEELEM                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VLRACUMAJUSTEELEM                  NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
ELEMENTOBODEGA                     NUMBER                                            22      5           0       Y     0           null                                                                                                                                                                                                    
PLACAANULADA                       NUMBER                                            22      5           0       Y     0           null                                                                                                                                                                                                    
VLRDEPRECIACIONAJ                  NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DEPACUMULADAAJ                     NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SALDOAJ                            NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
COSTOSALIDA                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
COSTOSALIDAAJ                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DEPACUMULADA                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DEPENDENCIA                        VARCHAR2                                          12      0           0       N     12          '999999999999'                                                                                                                                                                                          
AJDEPACUMULADA                     NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
AJDEPRECIACION                     NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
MES                                NUMBER                                            22      2           0       N     0           null                                                                                                                                                                                                    
ACUMDEPAJ                          NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
ACUMAJUSTESAJ                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DEPENDENCIAINICIAL                 VARCHAR2                                          12      0           0       Y     12          null                                                                                                                                                                                                    
VLRREVERSIONAI                     NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
FECHASALIDASERVICIO                TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
PERIODO                            TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       N     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHAENTRADASERVICIO               TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
