campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
NUMERO_EVALUACION                  NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
CLASE_EVALUACION                   NUMBER                                            22      3           0       N     0           null                                                                                                                                                                                                    
TIPO_EVALUACION                    VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
CEDULA_EVALUADO                    VARCHAR2                                          18      0           0       N     18          '999999999999999999'                                                                                                                                                                                    
SUCURSAL_EVALUADO                  VARCHAR2                                          3       0           0       N     3           '999'                                                                                                                                                                                                   
CEDULA_EVALUADOR                   VARCHAR2                                          18      0           0       N     18          '999999999999999999'                                                                                                                                                                                    
SUCURSAL_EVALUADOR                 VARCHAR2                                          3       0           0       N     3           '999'                                                                                                                                                                                                   
REPOSICION                         NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
DESICIONREPOSICION                 VARCHAR2                                          50      0           0       Y     50          null                                                                                                                                                                                                    
FECHAREPOSICION                    TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
MOTIVACIONREPOSIC                  CLOB                                              4000    0           0       Y     0           null                                                                                                                                                                                                    
APELACION                          NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
DESICIONREAPELACI                  VARCHAR2                                          50      0           0       Y     50          null                                                                                                                                                                                                    
FECHAAPELACION                     TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
MOTIVACIONAPELAC                   CLOB                                              4000    0           0       Y     0           null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
