campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
COD_REQUISICION                    NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
COD_DETALLE                        NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
CODIGOELEMENTO                     VARCHAR2                                          16      0           0       N     16          null                                                                                                                                                                                                    
ESPECIFICACION                     VARCHAR2                                          4000    0           0       Y     4000        null                                                                                                                                                                                                    
CANTIDAD                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALORUNITARIO                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALORTOTAL                         NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
COD_PROPUESTA                      NUMBER                                            22      20          0       N     0           0                                                                                                                                                                                                       
SALDODETALLE                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
PORCDESCUENTO                      NUMBER                                            22      9           6       N     0           0                                                                                                                                                                                                       
PORCIVA                            NUMBER                                            22      9           6       N     0           0                                                                                                                                                                                                       
ORDENDESUMINISTRO                  NUMBER                                            22      20          0       N     0           0                                                                                                                                                                                                       
DEPENDENCIA                        VARCHAR2                                          12      0           0       N     12          '999999999999'                                                                                                                                                                                          
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
