campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
ANO                                NUMBER                                            22      4           0       N     0           0                                                                                                                                                                                                       
RUBRO                              VARCHAR2                                          32      0           0       N     32          null                                                                                                                                                                                                    
CODIGO                             VARCHAR2                                          16      0           0       N     16          null                                                                                                                                                                                                    
DEPENDENCIA                        VARCHAR2                                          12      0           0       N     12          null                                                                                                                                                                                                    
MES                                NUMBER                                            22      2           0       N     0           0                                                                                                                                                                                                       
CANTIDAD                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALOR_UNITARIO                     NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALORACOMPRAR                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
COMPRADO                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALORTOTALCOMPRADO                 NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
ENTRADAS                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALOR_ENTRADAS                     NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SALIDAS                            NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALOR_SALIDAS                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
ESPECIFICACION                     VARCHAR2                                          4000    0           0       Y     4000        null                                                                                                                                                                                                    
TIPO_CONTRATACION                  VARCHAR2                                          4       0           0       Y     4           3                                                                                                                                                                                                       
SUBPROYECTO                        NUMBER                                            22      20          0       Y     0           0                                                                                                                                                                                                       
SALDO_CANTIDAD                     NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SALDO_TOTALACOMPRAR                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
ENVIAR_CERT                        NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
RESPONSABLE                        VARCHAR2                                          18      0           0       N     18          '999999999999999999'                                                                                                                                                                                    
SUCURSAL                           VARCHAR2                                          3       0           0       N     3           '999'                                                                                                                                                                                                   
CONSECUTIVO_PC                     NUMBER                                            22      5           0       N     0           0                                                                                                                                                                                                       
DURACION_ESTIMADA_DEL_CONTRATO     VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
