campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
TIPO_CPTE                          VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
COMPROBANTE                        NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
CONSECUTIVO                        NUMBER                                            22      5           0       N     0           0                                                                                                                                                                                                       
CUENTA                             VARCHAR2                                          32      0           0       N     32          null                                                                                                                                                                                                    
NATURALEZA                         VARCHAR2                                          1       0           0       N     1           null                                                                                                                                                                                                    
TIPOPPTAL                          VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
NUMEROPPTAL                        NUMBER                                            22      20          0       Y     0           null                                                                                                                                                                                                    
CUENTAPPTAL                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
CONSECUTIVOPPTO                    NUMBER                                            22      5           0       Y     0           null                                                                                                                                                                                                    
DESCRIPCION                        VARCHAR2                                          250     0           0       Y     250         null                                                                                                                                                                                                    
VALOR_DEBITO                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALOR_CREDITO                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
EJECUCION_DEBITO                   NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
EJECUCION_CREDITO                  NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
BASE_GRAVABLE                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
TIPO_DOCUMENTO                     VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
NRO_DOCUMENTO                      VARCHAR2                                          30      0           0       Y     30          null                                                                                                                                                                                                    
CENTRO_COSTO                       VARCHAR2                                          20      0           0       N     20          '99999999999999999999'                                                                                                                                                                                  
TERCERO                            VARCHAR2                                          18      0           0       N     18          '999999999999999999'                                                                                                                                                                                    
SUCURSAL                           VARCHAR2                                          3       0           0       N     3           '999'                                                                                                                                                                                                   
AUXILIAR                           VARCHAR2                                          20      0           0       N     20          '99999999999999999999'                                                                                                                                                                                  
REFERENCIA                         VARCHAR2                                          20      0           0       N     20          '99999999999999999999'                                                                                                                                                                                  
FUENTE_RECURSO                     VARCHAR2                                          20      0           0       N     20          '99999999999999999999'                                                                                                                                                                                  
ANO_AFECT                          NUMBER                                            22      4           0       Y     0           null                                                                                                                                                                                                    
TIPO_CPTE_AFECT                    VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
CMPTE_AFECTADO                     NUMBER                                            22      20          0       Y     0           null                                                                                                                                                                                                    
CONSECUTIVOAFECTADO                NUMBER                                            22      5           0       Y     0           null                                                                                                                                                                                                    
CHEQUEPARAANULAR                   VARCHAR2                                          20      0           0       Y     20          'Cheque para Anular'                                                                                                                                                                                    
CIERRE                             NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
BASE_IVA                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
PAGADOBANCO                        NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
TIPOCONTRATO                       VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
NUMEROCONTRATO                     NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SALDOCUENTA                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DEBITO_AFECTADO                    NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CREDITO_AFECTADO                   NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
ABONOINICIAL                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
PORCENTAJERETENCION                NUMBER                                            22      9           6       N     0           0                                                                                                                                                                                                       
VALORTOTAL                         NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
RECONOCIMIENTO                     NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
DEBITOSAFECTADOS_CXP               NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CREDITOSAFECTADOS_CXP              NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
TEXTOD                             VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
FORMATO_CONCEPTO_EX                VARCHAR2                                          10      0           0       Y     10          null                                                                                                                                                                                                    
CONCEPTO_EX                        VARCHAR2                                          10      0           0       Y     10          null                                                                                                                                                                                                    
CONCILIADOR                        VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
REVELACIONES                       VARCHAR2                                          4000    0           0       Y     4000        null                                                                                                                                                                                                    
PORDISTRIBUIDOCNT                  NUMBER                                            22      9           6       N     0           0                                                                                                                                                                                                       
PAIS                               VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
DEPARTAMENTO                       VARCHAR2                                          2       0           0       N     2           null                                                                                                                                                                                                    
CIUDAD                             VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
D_DEPENDENCIACNT                   VARCHAR2                                          12      0           0       Y     12          null                                                                                                                                                                                                    
D_RESPONSABLECNT                   VARCHAR2                                          18      0           0       Y     18          null                                                                                                                                                                                                    
D_RESPSUCURSALCNT                  VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
CODIGO_PPTAL                       VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
BANCO_RETENCION                    VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DEBITO_EQUIV                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CREDITO_EQUIV                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SINIDENTIFICAR                     NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
DESEMBOLSO                         NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
TIPO_GENERADIF                     VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
NRO_GENERADIF                      NUMBER                                            22      20          0       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_CONCILIACION_PLANO           TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_CONSIGNACIONPLANO            TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
HORA                               TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHACONCILIA                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA                              TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_PAGO_RETENCION               TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_CONCILIA                     TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_IDENTIFICACION               TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_CALC_DET                     TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
PAGO_RETENCION                     NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
MES                                NUMBER                                            22      22          0       Y     0           null                                                                                                                                                                                                    
AUXILIARI                          VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
TERCEROI                           VARCHAR2                                          18      0           0       Y     18          null                                                                                                                                                                                                    
SUCURSALI                          VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
ID                                 VARCHAR2                                          133     0           0       Y     133         null                                                                                                                                                                                                    
DIA                                NUMBER                                            22      22          0       Y     0           null                                                                                                                                                                                                    
CENTRO_COSTOI                      VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
FUENTE_RECURSOI                    VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
REFERENCIAI                        VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
CODIGO_FUT                         VARCHAR2                                          113     0           0       Y     113         null                                                                                                                                                                                                    
ANO_RETENCION                      NUMBER                                            22      4           0       Y     0           null                                                                                                                                                                                                    
COMPROBANTE_PAGO_RETENCION         NUMBER                                            22      20          0       Y     0           null                                                                                                                                                                                                    
TIPO_PAGO_RETENCION                VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
FORMATO_CONCEPTO_DIST              VARCHAR2                                          10      0           0       Y     10          null                                                                                                                                                                                                    
CONCEPTO_DIST                      VARCHAR2                                          10      0           0       Y     10          null                                                                                                                                                                                                    
