campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
ID_DE_PROCESO                      NUMBER                                            22      2           0       N     0           null                                                                                                                                                                                                    
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
MES                                NUMBER                                            22      2           0       N     0           null                                                                                                                                                                                                    
PERIODO                            NUMBER                                            22      2           0       N     0           null                                                                                                                                                                                                    
ID_DE_EMPLEADO                     NUMBER                                            22      5           0       N     0           null                                                                                                                                                                                                    
ID_CENTRO_DE_COSTO                 VARCHAR2                                          20      0           0       N     20          '99999999999999999999'                                                                                                                                                                                  
HORAST                             NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
MINUTOST                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
TIEMPOTRABAJADO                    NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
ID_AUXILIAR                        VARCHAR2                                          20      0           0       N     20          '99999999999999999999'                                                                                                                                                                                  
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA                              TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       N     0           null                                                                                                                                                                                                    
