campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
ID_DE_PROCESO                      NUMBER                                            22      2           0       N     0           null                                                                                                                                                                                                    
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
MES                                NUMBER                                            22      2           0       N     0           null                                                                                                                                                                                                    
PERIODO                            NUMBER                                            22      2           0       N     0           null                                                                                                                                                                                                    
ID_DE_EMPLEADO                     NUMBER                                            22      5           0       N     0           null                                                                                                                                                                                                    
ID_EMBARGO                         VARCHAR2                                          10      0           0       N     10          null                                                                                                                                                                                                    
ID_JUZGADO                         VARCHAR2                                          6       0           0       N     6           null                                                                                                                                                                                                    
OFICIO                             VARCHAR2                                          15      0           0       N     15          null                                                                                                                                                                                                    
MONTO_EMBARGO                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
PORCENTAJE                         NUMBER                                            22      9           6       N     0           0                                                                                                                                                                                                       
VALOR                              NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SALDO                              NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VR_CUOTA                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DEMANDANTE                         VARCHAR2                                          50      0           0       Y     50          null                                                                                                                                                                                                    
TIPO_DEMANDANTE                    VARCHAR2                                          1       0           0       Y     1           null                                                                                                                                                                                                    
NUM_RADICACION                     VARCHAR2                                          15      0           0       Y     15          null                                                                                                                                                                                                    
OBSERVACIONES                      VARCHAR2                                          4000    0           0       Y     4000        null                                                                                                                                                                                                    
FORMA_PAGO                         VARCHAR2                                          2       0           0       N     2           '00'                                                                                                                                                                                                    
FACTOR1                            NUMBER                                            22      4           0       Y     0           null                                                                                                                                                                                                    
FACTOR2                            NUMBER                                            22      4           0       Y     0           null                                                                                                                                                                                                    
FACTOR3                            NUMBER                                            22      4           0       Y     0           null                                                                                                                                                                                                    
FACTOR4                            NUMBER                                            22      4           0       Y     0           null                                                                                                                                                                                                    
FACTOR5                            NUMBER                                            22      4           0       Y     0           null                                                                                                                                                                                                    
FACTOR6                            NUMBER                                            22      4           0       Y     0           null                                                                                                                                                                                                    
FACTOR7                            NUMBER                                            22      4           0       Y     0           null                                                                                                                                                                                                    
FACTOR8                            NUMBER                                            22      4           0       Y     0           null                                                                                                                                                                                                    
ESTADO                             VARCHAR2                                          1       0           0       N     1           'N'                                                                                                                                                                                                     
CONCEPTO_DEPOSITO                  VARCHAR2                                          2       0           0       Y     2           null                                                                                                                                                                                                    
CUENTA                             VARCHAR2                                          16      0           0       Y     16          null                                                                                                                                                                                                    
DCTO_IDENTIDAD                     VARCHAR2                                          2       0           0       Y     2           null                                                                                                                                                                                                    
CEDULA                             VARCHAR2                                          18      0           0       Y     18          null                                                                                                                                                                                                    
SUCURSAL                           VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
BANCO                              VARCHAR2                                          4       0           0       Y     4           null                                                                                                                                                                                                    
DEMANDANTE_NOMBRES                 VARCHAR2                                          50      0           0       Y     50          null                                                                                                                                                                                                    
PORCENTAJE_CESANTIAS               NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
PORCENTAJE_PRIMAS                  NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
OFICINA_DESTINO                    VARCHAR2                                          4       0           0       Y     4           null                                                                                                                                                                                                    
ID_DE_CONCEPTO                     NUMBER                                            22      4           0       Y     0           null                                                                                                                                                                                                    
COMISION                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
MANEJAIPC                          NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
NUMERO_PROCESO                     VARCHAR2                                          23      0           0       Y     23          null                                                                                                                                                                                                    
TEM_EMBARGOS                       VARCHAR2                                          23      0           0       Y     23          null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
FECHA_EMBARGO                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       N     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_RADICACION                   TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
CUOTAS                             NUMBER                                            22      5           0       Y     0           null                                                                                                                                                                                                    
