campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
COD_PROY                           VARCHAR2                                          16      0           0       N     16          null                                                                                                                                                                                                    
COD_ESTUDIO                        NUMBER                                            22      15          0       N     0           null                                                                                                                                                                                                    
T_COMPONENTE                       VARCHAR2                                          12      0           0       N     12          null                                                                                                                                                                                                    
COMPONENTE                         VARCHAR2                                          12      0           0       N     12          null                                                                                                                                                                                                    
ACTIVIDAD                          VARCHAR2                                          12      0           0       N     12          null                                                                                                                                                                                                    
CODIGOBPPIM                        VARCHAR2                                          50      0           0       Y     50          null                                                                                                                                                                                                    
COSTOUNITARIO                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
COSTOTOTAL                         NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
PORCEJECUTADO                      NUMBER                                            22      9           4       N     0           0                                                                                                                                                                                                       
PRIORIDAD                          NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CANTIDAD                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALORPROGRAMADO                    NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALOREJECUTADO                     NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DESCRIPCION                        VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
VIGENCIA                           NUMBER                                            22      4           0       N     0           0                                                                                                                                                                                                       
CONPROGRAMACION                    NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALOR_SOLICITADO_ACTIV             NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DESTINORECURSOS                    VARCHAR2                                          4       0           0       Y     4           null                                                                                                                                                                                                    
CANTIDAD_EJE                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SOLICITUD_SCD_BP                   NUMBER                                            22      15          0       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
VALOR                              NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CANTIDAD_PLAN                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CANTIDAD_PRODUCTO_C                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
META_PROD                          VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
FUENTE_RECURSOS                    VARCHAR2                                          20      0           0       N     20          '99999999999999999999'                                                                                                                                                                                  
AUXILIAR                           VARCHAR2                                          20      0           0       N     20          '99999999999999999999'                                                                                                                                                                                  
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
