campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
ID_RUBRO                           VARCHAR2                                          32      0           0       N     32          null                                                                                                                                                                                                    
COD_ESTUDIO                        NUMBER                                            22      15          0       N     0           null                                                                                                                                                                                                    
ANO                                NUMBER                                            22      4           0       N     0           0                                                                                                                                                                                                       
NOMBRE                             VARCHAR2                                          100     0           0       Y     100         null                                                                                                                                                                                                    
DESTINO                            VARCHAR2                                          1       0           0       Y     1           null                                                                                                                                                                                                    
VIGENCIA                           NUMBER                                            22      4           0       N     0           0                                                                                                                                                                                                       
FUENTE_RECURSOS                    VARCHAR2                                          20      0           0       N     20          '99999999999999999999'                                                                                                                                                                                  
VLR_SOLICITADO                     NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
