campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
CODIGO                             NUMBER                                            22      5           0       N     0           null                                                                                                                                                                                                    
ATRIBUTO                           VARCHAR2                                          10      0           0       Y     10          null                                                                                                                                                                                                    
DESCRIPCION                        VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
TIPO                               VARCHAR2                                          50      0           0       Y     50          null                                                                                                                                                                                                    
LONGITUD                           NUMBER                                            22      5           0       Y     0           null                                                                                                                                                                                                    
OBLIGATORIO                        NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
CAMPOVALOR                         NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
ESTRUCTURA_ACREEDORES              NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
