campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
CODIGO                             VARCHAR2                                          32      0           0       N     32          null                                                                                                                                                                                                    
CLASE_EVALUACION                   NUMBER                                            22      3           0       N     0           null                                                                                                                                                                                                    
NOMBRE                             VARCHAR2                                          255     0           0       N     255         null                                                                                                                                                                                                    
TEXTO                              VARCHAR2                                          500     0           0       Y     500         null                                                                                                                                                                                                    
MOVIMIENTO                         NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
PUNTAJE                            NUMBER                                            22      5           0       N     0           0                                                                                                                                                                                                       
IND_GRUPO                          NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
IND_TEXTO                          NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
IND_SELECCION_MULTIPLE             NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
ESCOMPROMISO                       NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
PUNTAJEMAXIMO                      NUMBER                                            22      5           0       N     0           0                                                                                                                                                                                                       
