campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
NUMERO_EVALUACION                  NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
CLASE_EVALUACION                   NUMBER                                            22      3           0       N     0           null                                                                                                                                                                                                    
TIPO_EVALUACION                    VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
PERIODO                            NUMBER                                            22      2           0       N     0           null                                                                                                                                                                                                    
CEDULA_EVALUADO                    VARCHAR2                                          18      0           0       N     18          null                                                                                                                                                                                                    
SUCURSAL_EVALUADO                  VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
CEDULA_EVALUADOR                   VARCHAR2                                          18      0           0       N     18          null                                                                                                                                                                                                    
SUCURSAL_EVALUADOR                 VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
CONSECUTIVO                        NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
CALIFICACION                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
PESO_PORCENTUAL                    NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
