campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
NUMERO_EVALUACION                  NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
CLASE_EVALUACION                   NUMBER                                            22      3           0       N     0           null                                                                                                                                                                                                    
TIPO_EVALUACION                    VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
CONSECUTIVO                        NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
CEDULA_EVALUADO                    VARCHAR2                                          18      0           0       N     18          '999999999999999999'                                                                                                                                                                                    
SUCURSAL_EVALUADO                  VARCHAR2                                          3       0           0       N     3           '999'                                                                                                                                                                                                   
CEDULA_EVALUADOR                   VARCHAR2                                          18      0           0       N     18          '999999999999999999'                                                                                                                                                                                    
SUCURSAL_EVALUADOR                 VARCHAR2                                          3       0           0       N     3           '999'                                                                                                                                                                                                   
COMPONENTE                         VARCHAR2                                          255     0           0       N     255         null                                                                                                                                                                                                    
DESCRIPCION                        VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
UBICACION                          VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
FECHA                              TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
OBSERVACIONES                      VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
APORTADO_POR                       NUMBER                                            22      2           0       Y     0           null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
TIPO                               VARCHAR2                                          2       0           0       N     2           'CC'                                                                                                                                                                                                    
