campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
ID_DE_PROCESO                      VARCHAR2                                          2       0           0       N     2           null                                                                                                                                                                                                    
VERSION                            VARCHAR2                                          16      0           0       N     16          null                                                                                                                                                                                                    
CONSECUTIVO                        VARCHAR2                                          16      0           0       N     16          null                                                                                                                                                                                                    
TITULO                             VARCHAR2                                          256     0           0       Y     256         null                                                                                                                                                                                                    
TIPO                               VARCHAR2                                          1       0           0       Y     1           null                                                                                                                                                                                                    
NIVEL                              NUMBER                                            22      2           0       Y     0           null                                                                                                                                                                                                    
ID_DE_CONCEPTO                     VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
ECUACION                           CLOB                                              4000    0           0       Y     0           null                                                                                                                                                                                                    
CONDICION                          CLOB                                              4000    0           0       Y     0           null                                                                                                                                                                                                    
ESTADO                             VARCHAR2                                          1       0           0       Y     1           null                                                                                                                                                                                                    
COMENTARIO                         VARCHAR2                                          256     0           0       Y     256         null                                                                                                                                                                                                    
