campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
CODIGO_FUT                         VARCHAR2                                          10      0           0       N     10          null                                                                                                                                                                                                    
NOMBRE_FUT                         VARCHAR2                                          255     0           0       N     255         null                                                                                                                                                                                                    
CODIGO_FORMULARIO                  VARCHAR2                                          5       0           0       Y     5           null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
