campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
TIPO_IMPUESTO                      VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
MESESAMNISTIA                      NUMBER                                            22      2           0       N     0           null                                                                                                                                                                                                    
PERIODICIDAD                       NUMBER                                            22      2           0       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
