campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
NUMCER                             VARCHAR2                                          20      0           0       N     20          null                                                                                                                                                                                                    
COD_ESTAB                          VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
TIPO_NIT                           VARCHAR2                                          1       0           0       N     1           null                                                                                                                                                                                                    
NIT                                VARCHAR2                                          18      0           0       N     18          '999999999999999999'                                                                                                                                                                                    
SUCURSAL                           VARCHAR2                                          3       0           0       N     3           '999'                                                                                                                                                                                                   
NOMBRE                             VARCHAR2                                          100     0           0       Y     100         null                                                                                                                                                                                                    
RAZON                              VARCHAR2                                          100     0           0       Y     100         null                                                                                                                                                                                                    
NUMERO_ORDEN                       VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
ANO_GENERADO                       NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
VALOR                              NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
ANULADO                            NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
DESTINO                            VARCHAR2                                          100     0           0       Y     100         null                                                                                                                                                                                                    
COD_ACTIVIDAD                      VARCHAR2                                          10      0           0       Y     10          null                                                                                                                                                                                                    
DESC_ACTIVIDAD                     VARCHAR2                                          100     0           0       Y     100         null                                                                                                                                                                                                    
USUARIO                            VARCHAR2                                          100     0           0       Y     100         null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
VALIDO_HASTA                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
HORA_ANULADO                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_EXPEDICION                   TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
HORAPYS                            TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_ANULADO                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
