campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
NUMERO_CARTA                       VARCHAR2                                          15      0           0       N     15          null                                                                                                                                                                                                    
DESTINO                            VARCHAR2                                          50      0           0       Y     50          null                                                                                                                                                                                                    
IND_ENTREGADO                      NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
USUARIO_GEN                        VARCHAR2                                          40      0           0       Y     40          null                                                                                                                                                                                                    
IND_ANULADO                        NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
CODIGO                             VARCHAR2                                          15      0           0       Y     15          null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FEC_RESPUESTA                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA                              TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
