campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
TIPOIMPUESTO                       VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
CODIGOBANCO                        VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
NOMBREBANCO                        VARCHAR2                                          30      0           0       Y     30          null                                                                                                                                                                                                    
CODIGOCONTABLE                     VARCHAR2                                          60      0           0       Y     60          null                                                                                                                                                                                                    
ESCAJA                             NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
CUENTA                             VARCHAR2                                          50      0           0       Y     50          null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
FECHA_BLOQUEO                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
