campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
RECAUDODB_INTFINAN                 VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
RECAUDOCR_INTFINAN                 VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
RECAUDODB_INTREC                   VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
RECAUDOCR_INTREC                   VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
CAUSACIONDBFE_INTFINAN             VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
CAUSACIONCRFE_INTFINAN             VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
CAUSACIONDBFE_INTREC               VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
CAUSACIONCRFE_INTREC               VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
CAUSACIONDBFA_INTFINAN             VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
CAUSACIONCRFA_INTFINAN             VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
CAUSACIONDBFA_INTREC               VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
CAUSACIONCRFA_INTREC               VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
FUENTE_ACUERDO                     VARCHAR2                                          20      0           0       N     20          '99999999999999999999'                                                                                                                                                                                  
FUENTE_RECARGO                     VARCHAR2                                          20      0           0       N     20          '99999999999999999999'                                                                                                                                                                                  
TIPOIMPUESTO                       VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
COD_CENTRO_COSTO_ACUERDO           VARCHAR2                                          20      0           0       N     20          '99999999999999999999'                                                                                                                                                                                  
COD_CENTRO_COSTO_RECARGO           VARCHAR2                                          20      0           0       N     20          '99999999999999999999'                                                                                                                                                                                  
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
