campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
TIPOIMPUESTO                       VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
DOCNUM                             VARCHAR2                                          10      0           0       N     10          null                                                                                                                                                                                                    
TIPO_NIT                           VARCHAR2                                          1       0           0       N     1           null                                                                                                                                                                                                    
CONTRIBUYENTE                      VARCHAR2                                          18      0           0       N     18          '999999999999999999'                                                                                                                                                                                    
SUCURSAL                           VARCHAR2                                          3       0           0       N     3           '999'                                                                                                                                                                                                   
PREVAL                             NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
PREUSU                             VARCHAR2                                          50      0           0       Y     50          null                                                                                                                                                                                                    
ANULADO                            NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
PAGO                               NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
C1                                 NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
C2                                 NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
C3                                 NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
C4                                 NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
C5                                 NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
C6                                 NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
C7                                 NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
C8                                 NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
C9                                 NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
C10                                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
C11                                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
C12                                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
C13                                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
C14                                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
C15                                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
C16                                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
C17                                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
C18                                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
C19                                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
C20                                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
PAG_BANPAG                         VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
ESACUERDO                          NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
NCUOTA_ACUERDO                     NUMBER                                            22      5           0       N     0           0                                                                                                                                                                                                       
ACUERDO                            VARCHAR2                                          10      0           0       Y     10          null                                                                                                                                                                                                    
INTERES_ACUERDO                    NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
INTERES_RECARGO                    NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
ESRECDECSINPAGO                    NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
DECSINPAGO                         NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
ESABONO                            NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
NCUOTA_ABONO                       NUMBER                                            22      5           0       N     0           0                                                                                                                                                                                                       
ABONO                              VARCHAR2                                          10      0           0       Y     10          null                                                                                                                                                                                                    
ESDECLARACION                      NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
NUMDECLARACION                     VARCHAR2                                          10      0           0       Y     10          null                                                                                                                                                                                                    
TIPODECLARACION                    VARCHAR2                                          1       0           0       Y     1           null                                                                                                                                                                                                    
ANOPAGADO                          NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
MESPAGADO                          NUMBER                                            22      2           0       N     0           null                                                                                                                                                                                                    
DESP_C1                            NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DESP_C2                            NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DESP_C3                            NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DESP_C4                            NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DESP_C5                            NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DESP_C6                            NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DESP_C7                            NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DESP_C8                            NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DESP_C9                            NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DESP_C10                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DESP_C11                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DESP_C12                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DESP_C13                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DESP_C14                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DESP_C15                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DESP_C16                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DESP_C17                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DESP_C18                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DESP_C19                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DESP_C20                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DESP_INTERES                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DESP_INTERES_ACU                   NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DESP_INTERES_REC                   NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
PAQUETE                            VARCHAR2                                          5       0           0       Y     5           null                                                                                                                                                                                                    
ESPARCIAL                          NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
CODIGOPARCIAL                      VARCHAR2                                          10      0           0       Y     10          null                                                                                                                                                                                                    
CUOTAHASTAFIN                      NUMBER                                            22      5           0       N     0           0                                                                                                                                                                                                       
ABONOAACUERDO                      NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
TIPOABONOAACUERDO                  VARCHAR2                                          1       0           0       Y     1           null                                                                                                                                                                                                    
TIPOABONOAA                        VARCHAR2                                          1       0           0       Y     1           null                                                                                                                                                                                                    
ANULADOINT                         NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
ANULADOINTDOCNUM                   VARCHAR2                                          10      0           0       Y     10          null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
FECHAFACTURADO                     TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHAANULADOINT                    TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHAANULADO                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
PREFECPAG                          TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
PREFECLIM                          TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
PREFEC                             TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
