campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
ID_DE_EMPLEADO                     NUMBER                                            22      5           0       N     0           null                                                                                                                                                                                                    
ID_DE_PROCESO                      NUMBER                                            22      2           0       N     0           null                                                                                                                                                                                                    
INCAPACIDAD                        VARCHAR2                                          2       0           0       N     2           null                                                                                                                                                                                                    
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
MES                                NUMBER                                            22      2           0       N     0           null                                                                                                                                                                                                    
PERIODO                            NUMBER                                            22      2           0       N     0           null                                                                                                                                                                                                    
AUTO                               VARCHAR2                                          10      0           0       N     10          null                                                                                                                                                                                                    
DIAS                               NUMBER                                            22      10          0       N     0           0                                                                                                                                                                                                       
TIPOENFERMEDAD                     VARCHAR2                                          5       0           0       Y     5           null                                                                                                                                                                                                    
OBSERVACION_I                      VARCHAR2                                          250     0           0       Y     250         null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHAFINREAL                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHAINIREAL                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_AUTO                         TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_FIN                          TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_INICIO                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
NUMERO_DCTO                        VARCHAR2                                          18      0           0       Y     18          '999999999999999999'                                                                                                                                                                                    
SUCURSAL                           VARCHAR2                                          3       0           0       Y     3           '999'                                                                                                                                                                                                   
ENTIDADQUELAEMITE                  VARCHAR2                                          18      0           0       Y     18          '999999999999999999'                                                                                                                                                                                    
SUCURSAL_ENTIDADQUELAEMITE         VARCHAR2                                          3       0           0       Y     3           '999'                                                                                                                                                                                                   
FECHAEMISION                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DIAGNOSTICO                        VARCHAR2                                          500     0           0       Y     500         null                                                                                                                                                                                                    
ORIGEN                             VARCHAR2                                          50      0           0       Y     50          null                                                                                                                                                                                                    
NUMEROPERIODO                      VARCHAR2                                          8       0           0       Y     8           null                                                                                                                                                                                                    
NUM_CERTIFICADO                    NUMBER                                            22      20          0       Y     0           0                                                                                                                                                                                                       
FECHA_EXPEDICION                   TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
TRANSCRIPCION                      VARCHAR2                                          50      0           0       Y     50          null                                                                                                                                                                                                    
VALOR_LIQUIDADO                    NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
ACUMDIAS                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DCTO_PAGO_EPS                      VARCHAR2                                          10      0           0       Y     10          null                                                                                                                                                                                                    
FECHA_PAGO_EPS                     TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
VALOR_PAGADO_EPS                   NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
BASEIBC                            NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
