campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
CODIGO                             VARCHAR2                                          10      0           0       N     10          null                                                                                                                                                                                                    
FONDO                              VARCHAR2                                          30      0           0       N     30          null                                                                                                                                                                                                    
ANO                                NUMBER                                            22      4           0       Y     0           null                                                                                                                                                                                                    
ORIGENRECURSOS                     VARCHAR2                                          20      0           0       N     20          null                                                                                                                                                                                                    
ENTIDADEMISORA                     VARCHAR2                                          30      0           0       Y     30          null                                                                                                                                                                                                    
VALORNOMINAL                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
TASA                               NUMBER                                            22      9           6       N     0           0                                                                                                                                                                                                       
VENCIDO                            NUMBER                                            22      9           6       N     0           0                                                                                                                                                                                                       
ANTICIPADO                         NUMBER                                            22      9           6       N     0           0                                                                                                                                                                                                       
RENDIMIENTOSFINANCIEROS            NUMBER                                            22      9           6       N     0           0                                                                                                                                                                                                       
SALDOFINAL                         NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
REINVERSION                        NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
TIPOINVERSION                      NUMBER                                            22      2           0       Y     0           null                                                                                                                                                                                                    
MONEDA                             VARCHAR2                                          3       0           0       N     3           'COP'                                                                                                                                                                                                   
TIPO_INV_FUT                       VARCHAR2                                          5       0           0       Y     5           null                                                                                                                                                                                                    
ENCARGO_FIDUCIARIO                 NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
PLAZO                              NUMBER                                            22      5           0       N     0           0                                                                                                                                                                                                       
INVERSION_VENDIDA                  NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
VALOR_VENTA                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
TASA_VENTA                         NUMBER                                            22      9           6       N     0           0                                                                                                                                                                                                       
TASA_COMPRA                        NUMBER                                            22      9           6       N     0           0                                                                                                                                                                                                       
VALOR_PAGADO                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
INTERMEDIARIA                      VARCHAR2                                          15      0           0       Y     15          null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
BANCO                              VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
DESCRIPCION                        VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
PERIODICIDAD                       NUMBER                                            22      5           0       N     0           0                                                                                                                                                                                                       
TIPO_MEN                           VARCHAR2                                          4       0           0       Y     4           null                                                                                                                                                                                                    
NUMERO                             NUMBER                                            22      20          0       N     0           0                                                                                                                                                                                                       
FECHACOLOCACION                    TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHAVENCIMIENTO                   TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_COMPRA                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_VENTA                        TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
