campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
CAUSACIONDBINTACU                  VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
CAUSACIONCRINTACU                  VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
RECAUDODBINTACU                    VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
RECAUDOCRINTACU                    VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
CAUSACIONDBINTREC                  VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
CAUSACIONCRINTREC                  VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
RECAUDODBINTREC                    VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
RECAUDOCRINTREC                    VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
FUENTE_ACUERDO                     VARCHAR2                                          20      0           0       N     20          '99999999999999999999'                                                                                                                                                                                  
FUENTE_RECARGO                     VARCHAR2                                          20      0           0       N     20          '99999999999999999999'                                                                                                                                                                                  
CAUSACIONDBINTACU_FA               VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
CAUSACIONCRINTACU_FA               VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
CAUSACIONDBINTREC_FA               VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
CAUSACIONCRINTREC_FA               VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
COD_CENTRO_COSTO_ACUERDO           VARCHAR2                                          20      0           0       N     20          '99999999999999999999'                                                                                                                                                                                  
COD_CENTRO_COSTO_RECARGO           VARCHAR2                                          20      0           0       N     20          '99999999999999999999'                                                                                                                                                                                  
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
