campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
MES                                NUMBER                                            22      2           0       N     0           null                                                                                                                                                                                                    
CONSECUTIVO                        NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
CODIGO_INICIAL                     VARCHAR2                                          50      0           0       N     50          null                                                                                                                                                                                                    
NUMERO_ORDENI                      VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
CODIGO_FINAL                       VARCHAR2                                          50      0           0       N     50          null                                                                                                                                                                                                    
NUMERO_ORDENF                      VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
INCREM_INICIAL                     NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
INCREM_FINAL                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
AREA_CONST_ANT                     VARCHAR2                                          20      0           0       N     20          null                                                                                                                                                                                                    
AREA_CONST_ACTUAL                  VARCHAR2                                          20      0           0       N     20          null                                                                                                                                                                                                    
IND_PRIORIDAD                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
PORC_DSCTO                         NUMBER                                            22      9           6       N     0           0                                                                                                                                                                                                       
TITULO_RANGO                       VARCHAR2                                          250     0           0       Y     250         null                                                                                                                                                                                                    
CLASE_PREDIO                       VARCHAR2                                          10      0           0       Y     10          null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_LIMITE                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
