campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
CONSECUTIVO                        NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
CODPREDIO                          VARCHAR2                                          50      0           0       N     50          null                                                                                                                                                                                                    
NUMERO_ORDEN                       VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
DOCSOPORTE                         VARCHAR2                                          15      0           0       Y     15          null                                                                                                                                                                                                    
VALOR                              NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
OBSERVACIONES                      VARCHAR2                                          4000    0           0       Y     4000        null                                                                                                                                                                                                    
NOTIFICADOR                        VARCHAR2                                          100     0           0       Y     100         null                                                                                                                                                                                                    
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
FECHANOTIFICACION                  TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
