campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
PAQUETE                            VARCHAR2                                          5       0           0       N     5           null                                                                                                                                                                                                    
PAG_BAN                            VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
NROCUPONES                         NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VLRREPORTADO                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
NROCUPONESACU                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
ACUMULADO                          NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
PREFEC                             TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       N     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
