campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
PAIS                               VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
DEPARTAMENTO                       VARCHAR2                                          2       0           0       N     2           null                                                                                                                                                                                                    
MUNICIPIO                          VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
RESOLUCION                         VARCHAR2                                          17      0           0       N     17          null                                                                                                                                                                                                    
CONSECUTIVO                        NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
TIPOREGISTRO                       VARCHAR2                                          1       0           0       Y     1           null                                                                                                                                                                                                    
CODIGO                             VARCHAR2                                          50      0           0       N     50          null                                                                                                                                                                                                    
NUMERO_ORDEN                       VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
TIPO_NIT                           VARCHAR2                                          1       0           0       Y     1           null                                                                                                                                                                                                    
NIT                                VARCHAR2                                          18      0           0       N     18          '999999999999999999'                                                                                                                                                                                    
NOMBRE                             VARCHAR2                                          100     0           0       Y     100         null                                                                                                                                                                                                    
INDBORRADO                         NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
SUCURSAL                           VARCHAR2                                          3       0           0       N     3           '999'                                                                                                                                                                                                   
