campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
NUMERO                             NUMBER                                            22      15          0       N     0           null                                                                                                                                                                                                    
NITSOCIEDAD                        VARCHAR2                                          18      0           0       N     18          null                                                                                                                                                                                                    
SUCURSAL                           VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
ENTIDADCONTRATA                    VARCHAR2                                          40      0           0       Y     40          null                                                                                                                                                                                                    
TIPO                               VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
TELEFONO                           VARCHAR2                                          15      0           0       Y     15          null                                                                                                                                                                                                    
FECHATERMINA                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
VALORSERVICIO                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
