campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
NUMERO_DCTO                        VARCHAR2                                          18      0           0       N     18          null                                                                                                                                                                                                    
SUCURSAL                           VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
NUMERO                             NUMBER                                            22      15          0       N     0           null                                                                                                                                                                                                    
MODALIDAD                          VARCHAR2                                          2       0           0       Y     2           null                                                                                                                                                                                                    
ESTABLECIMIENTO                    VARCHAR2                                          50      0           0       Y     50          null                                                                                                                                                                                                    
HORAS                              NUMBER                                            22      11          0       Y     0           null                                                                                                                                                                                                    
ANO                                NUMBER                                            22      4           0       Y     0           null                                                                                                                                                                                                    
DEPTO                              VARCHAR2                                          2       0           0       N     2           null                                                                                                                                                                                                    
NOE_CODIGOPERSONA                  VARCHAR2                                          20      0           0       N     20          null                                                                                                                                                                                                    
TITULOOBTENIDO                     VARCHAR2                                          100     0           0       Y     100         null                                                                                                                                                                                                    
MUNICIPIO                          VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
DIAINICIO                          NUMBER                                            22      2           0       Y     0           null                                                                                                                                                                                                    
MESINICIO                          NUMBER                                            22      2           0       Y     0           null                                                                                                                                                                                                    
ANOINICIO                          NUMBER                                            22      4           0       Y     0           null                                                                                                                                                                                                    
DIATERMINACION                     NUMBER                                            22      2           0       Y     0           null                                                                                                                                                                                                    
MESTERMINACION                     NUMBER                                            22      2           0       Y     0           null                                                                                                                                                                                                    
ANOTERMINACION                     NUMBER                                            22      4           0       Y     0           null                                                                                                                                                                                                    
GRADUADO                           NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
PATROCINADO                        NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
PAIS                               VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
FECHAINICIO                        TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHATERMINACION                   TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
