campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
DP_NUMEDOCU                        VARCHAR2                                          18      0           0       N     18          null                                                                                                                                                                                                    
SUCURSAL                           VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
ID_DE_EMPLEADO                     NUMBER                                            22      5           0       N     0           null                                                                                                                                                                                                    
VA_TIPONOVE                        VARCHAR2                                          50      0           0       N     50          null                                                                                                                                                                                                    
VA_TIPODOCUACTO                    VARCHAR2                                          50      0           0       N     50          null                                                                                                                                                                                                    
VA_NUME                            VARCHAR2                                          50      0           0       N     50          null                                                                                                                                                                                                    
DP_TIPODOCU                        VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
VA_PAGO                            NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VA_OBSERVACION                     VARCHAR2                                          4000    0           0       Y     4000        null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
VA_FECHFINA                        TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
VA_FECHINI                         TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
VA_DESDE                           TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
VA_FECHRESODECR                    TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       N     0           null                                                                                                                                                                                                    
VA_HASTA                           TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
