campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
CONSECUTIVO                        NUMBER                                            22      15          0       N     0           null                                                                                                                                                                                                    
ID_DE_EMPLEADO                     NUMBER                                            22      5           0       N     0           null                                                                                                                                                                                                    
FACTOR_RIESGO                      VARCHAR2                                          10      0           0       N     10          null                                                                                                                                                                                                    
CONCEPTO_RIESGO                    VARCHAR2                                          10      0           0       N     10          null                                                                                                                                                                                                    
CRITERIO_RIESGO                    VARCHAR2                                          4000    0           0       Y     4000        null                                                                                                                                                                                                    
NATURALEZA_LESION                  VARCHAR2                                          4000    0           0       Y     4000        null                                                                                                                                                                                                    
PARTE_CUERPO_AFEC                  VARCHAR2                                          4000    0           0       Y     4000        null                                                                                                                                                                                                    
AGENTE_LESION                      VARCHAR2                                          4000    0           0       Y     4000        null                                                                                                                                                                                                    
TIPO_ACCIDENTE                     VARCHAR2                                          4000    0           0       Y     4000        null                                                                                                                                                                                                    
CAUSA_ACCIDENTE                    VARCHAR2                                          4000    0           0       Y     4000        null                                                                                                                                                                                                    
ACCIONES_CORRECT                   VARCHAR2                                          4000    0           0       Y     4000        null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
NUMERO_DCTO                        VARCHAR2                                          18      0           0       N     18          null                                                                                                                                                                                                    
SUCURSAL                           VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
TIPO_TRANSACCION                   NUMBER                                            22      5           0       N     0           null                                                                                                                                                                                                    
CLASE_TRANSACCION                  VARCHAR2                                          1       0           0       N     1           null                                                                                                                                                                                                    
IND_INCAPACIDAD                    NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
DIAS_INCAPACIDAD                   NUMBER                                            22      5           0       N     0           0                                                                                                                                                                                                       
DIAGNOSTICO                        VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
IND_TESTIGOS                       NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
IND_REMISION                       NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
FECHA_REMISION                     TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
OBSERVACION_REMISION               VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
