campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
CLASEORDEN                         VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
NUMERO                             NUMBER                                            22      15          0       N     0           0                                                                                                                                                                                                       
TIPOTRANSACCION                    VARCHAR2                                          1       0           0       N     1           null                                                                                                                                                                                                    
ACTO_ADMINISTRATIVO                VARCHAR2                                          50      0           0       N     50          null                                                                                                                                                                                                    
CONSECUTIVO                        NUMBER                                            22      5           0       N     0           0                                                                                                                                                                                                       
DESCRIPCION                        VARCHAR2                                          4000    0           0       Y     4000        null                                                                                                                                                                                                    
VALORMULTA                         NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALORPAGADOMULTA                   NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
ESTADOMULTA                        NUMBER                                            22      2           0       N     0           0                                                                                                                                                                                                       
ACTOREVOCACION                     VARCHAR2                                          50      0           0       Y     50          null                                                                                                                                                                                                    
INDICADOR_ENVIO                    NUMBER                                            22      2           0       N     0           0                                                                                                                                                                                                       
TIPO                               VARCHAR2                                          1       0           0       Y     1           null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHAACTOREVOCACION                TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHAACTOADMINISTRATIVO            TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
