campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
DP_NUMEDOCU                        VARCHAR2                                          18      0           0       N     18          null                                                                                                                                                                                                    
SUCURSAL                           VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
NO_TIPODOCUACTO                    NUMBER                                            22      2           0       N     0           null                                                                                                                                                                                                    
NO_NUME                            VARCHAR2                                          50      0           0       N     50          null                                                                                                                                                                                                    
NO_CARGOA                          VARCHAR2                                          5       0           0       Y     5           null                                                                                                                                                                                                    
NO_SALARIOA                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
NO_CODIGOCARGO                     VARCHAR2                                          5       0           0       Y     5           null                                                                                                                                                                                                    
NO_GRADOCARGO                      VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
NO_CARGON                          VARCHAR2                                          5       0           0       Y     5           null                                                                                                                                                                                                    
NO_SALARION                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
NO_ACTAPOSE                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
NO_TIPO                            VARCHAR2                                          50      0           0       Y     50          null                                                                                                                                                                                                    
NO_CAUSA                           VARCHAR2                                          200     0           0       Y     200         null                                                                                                                                                                                                    
NO_DEPEANTE                        VARCHAR2                                          12      0           0       Y     12          null                                                                                                                                                                                                    
NO_DEPENUEV                        VARCHAR2                                          12      0           0       Y     12          null                                                                                                                                                                                                    
EVALUADOPRUEBA                     NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
NB_CODIGOPERSONA                   VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
PRIMATECNICAFACTOR                 NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
PRIMATECNICANFACTOR                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
PRIMAALTAGESTION                   NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
GASTOSREPRESENTACION               NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
NO_ESCALAFON                       VARCHAR2                                          2       0           0       Y     2           null                                                                                                                                                                                                    
NO_CATEGORIA                       VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
NO_ID_DE_CARGO                     VARCHAR2                                          10      0           0       Y     10          null                                                                                                                                                                                                    
ESTADO_VINCULACION                 NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
NO_AUXT                            NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
NO_AUXA                            NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
RETIRO_O_NOMBRAMIENTO              VARCHAR2                                          2       0           0       Y     2           null                                                                                                                                                                                                    
OTROSFACTORES                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
ULT_CARGO                          NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
ANOFUNCION                         NUMBER                                            22      4           0       Y     0           null                                                                                                                                                                                                    
CODAREA                            VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
NO_FECHAEFECTIVIDAD                TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
EN_FECHHASTA                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
EN_FECHDESDE                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
NO_FECHACTAPOSE                    TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
NO_FECHACARGO                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
NO_FECHRESODECR                    TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       N     0           null                                                                                                                                                                                                    
