campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
NUMERO_DCTO                        VARCHAR2                                          18      0           0       N     18          null                                                                                                                                                                                                    
SUCURSAL                           VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
NUM                                NUMBER                                            22      15          0       N     0           null                                                                                                                                                                                                    
NES_CODIGOPERSONA                  VARCHAR2                                          20      0           0       N     20          null                                                                                                                                                                                                    
MODALIDAD                          VARCHAR2                                          4       0           0       Y     4           null                                                                                                                                                                                                    
SEMESTRES                          VARCHAR2                                          1       0           0       Y     1           null                                                                                                                                                                                                    
GRADUADO                           VARCHAR2                                          1       0           0       Y     1           null                                                                                                                                                                                                    
TITULO                             VARCHAR2                                          50      0           0       Y     50          null                                                                                                                                                                                                    
PROFESION                          VARCHAR2                                          40      0           0       Y     40          null                                                                                                                                                                                                    
MATRICULA                          VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
