campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
EVENTO                             VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
ENTIDAD                            VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
ID_DE_EMPLEADO                     NUMBER                                            22      5           0       N     0           null                                                                                                                                                                                                    
NUMERO_INSCRITOS                   NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
RESERVA_PRESUPUESTAL               VARCHAR2                                          15      0           0       Y     15          null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_INSCRIPCION                  TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_ACTIVIDAD                    TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       N     0           null                                                                                                                                                                                                    
