campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
CODIGO                             VARCHAR2                                          32      0           0       N     32          null                                                                                                                                                                                                    
CODIGO_PROCESO                     VARCHAR2                                          32      0           0       N     32          null                                                                                                                                                                                                    
CODIGO_NODO                        VARCHAR2                                          32      0           0       N     32          null                                                                                                                                                                                                    
TIPO_DATO                          NUMBER                                            22      6           0       N     0           null                                                                                                                                                                                                    
ETIQUETA                           VARCHAR2                                          20      0           0       N     20          null                                                                                                                                                                                                    
OBLIGATORIO                        NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
MANEJA_ADJUNTO                     NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
ESTADO                             NUMBER                                            22      6           0       N     0           4                                                                                                                                                                                                       
MANEJA_RADICADO                    NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
ADJUNTO                            VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
TABLA                              NUMBER                                            22      6           0       Y     0           null                                                                                                                                                                                                    
COD_REG_TABLA                      VARCHAR2                                          16      0           0       Y     16          null                                                                                                                                                                                                    
SUC_REG_TABLA                      VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
ANO_REG_TABLA                      NUMBER                                            22      4           0       Y     0           null                                                                                                                                                                                                    
