campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
NUMERO                             NUMBER                                            22      15          0       N     0           null                                                                                                                                                                                                    
TERCERO                            VARCHAR2                                          18      0           0       N     18          '999999999999999999'                                                                                                                                                                                    
SUCURSAL                           VARCHAR2                                          3       0           0       N     3           '999'                                                                                                                                                                                                   
DEPENDENCIA                        VARCHAR2                                          12      0           0       N     12          '999999999999'                                                                                                                                                                                          
DESCRIPCION                        VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
PORCIVAGLOBAL                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
PORCDESCGLOBAL                     NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SUBTOTAL                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALORIVA                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALORDESCUENTO                     NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALORTOTAL                         NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VACIA                              NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
IMPRESA                            NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
VALORESTIMADO                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SELECCIONADA                       NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
RUBROCOMPRAS                       VARCHAR2                                          16      0           0       Y     16          null                                                                                                                                                                                                    
OBSERVACIONES                      VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
NSOLICITUDDISPON                   NUMBER                                            22      11          0       N     0           0                                                                                                                                                                                                       
CONCEPTO                           VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
PLACA                              NUMBER                                            22      15          0       N     0           0                                                                                                                                                                                                       
KILOMETRAJE                        NUMBER                                            22      11          0       N     0           0                                                                                                                                                                                                       
PERIODICIDAD                       VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
NUMERO_ENTREGAS                    NUMBER                                            22      11          0       N     0           0                                                                                                                                                                                                       
UNIDAD_TIEMPO                      VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
PLAZO                              NUMBER                                            22      11          0       N     0           0                                                                                                                                                                                                       
AUXILIAR                           VARCHAR2                                          20      0           0       N     20          '99999999999999999999'                                                                                                                                                                                  
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
CLASE_BODEGA                       VARCHAR2                                          2       0           0       Y     2           null                                                                                                                                                                                                    
FECHAMODIFICACION                  TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA                              TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHACREACION                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
