campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
TIPO                               VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
NUMERO                             NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
VIGENCIA_INICIAL                   NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
ID_PLAN                            VARCHAR2                                          60      0           0       N     60          null                                                                                                                                                                                                    
CODIGO                             NUMBER                                            22      5           0       N     0           null                                                                                                                                                                                                    
VIGENCIA                           NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
VALOR_ESTIMADO_INI                 NUMBER                                            22      20          2       Y     0           null                                                                                                                                                                                                    
VALOR_ESTIMADO_FIN                 NUMBER                                            22      20          2       Y     0           null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
VALOR_EJECUTADO_INI                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALOR_EJECUTADO_FIN                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
ESNUEVO                            NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
