campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
VIGENCIA                           NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
CONSECUTIVO                        NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
ID_PLAN_PRODUCTO                   VARCHAR2                                          60      0           0       N     60          null                                                                                                                                                                                                    
CODIGO_PRODUCTO                    VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
ID_PLAN_RESULTADO                  VARCHAR2                                          60      0           0       Y     60          null                                                                                                                                                                                                    
CODIGO_RESULTADO                   VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
PRINCIPAL                          NUMBER                                            22      1           0       Y     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
