campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
CODIGO                             VARCHAR2                                          16      0           0       N     16          null                                                                                                                                                                                                    
ESTADO                             VARCHAR2                                          1       0           0       N     1           'P'                                                                                                                                                                                                     
SEPARADOR                          VARCHAR2                                          1       0           0       Y     1           null                                                                                                                                                                                                    
DESCRIPCION                        VARCHAR2                                          128     0           0       N     128         null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
