campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
CODIGO                             VARCHAR2                                          32      0           0       N     32          null                                                                                                                                                                                                    
ANO                                NUMBER                                            22      4           0       N     0           0                                                                                                                                                                                                       
NOMBRE                             VARCHAR2                                          250     0           0       N     250         null                                                                                                                                                                                                    
DEPENDENCIA                        VARCHAR2                                          12      0           0       N     12          null                                                                                                                                                                                                    
VLRASIGNADO                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VLRPROGRAMADO                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VLREJECUTADO                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
ANOTACIONES                        VARCHAR2                                          4000    0           0       Y     4000        null                                                                                                                                                                                                    
VLRENTREGADO                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VRLENTREGADO                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SUBPROYECTO                        NUMBER                                            22      20          0       Y     0           0                                                                                                                                                                                                       
VLRADICION                         NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VLRREDUCCION                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VLRTRASLADO                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VLRAPRINICIAL                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VLRDIFERENCIA                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
REQUIERE_VIGENCIA_FUTURA           NUMBER                                            22      1           0       N     0           -1                                                                                                                                                                                                      
ESTADO_VF                          VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
FUENTE_TMPA                        NUMBER                                            22      8           0       N     0           0                                                                                                                                                                                                       
FUENTE_DE_RECURSOS                 VARCHAR2                                          20      0           0       N     20          '99999999999999999999'                                                                                                                                                                                  
RESPONSABLE                        VARCHAR2                                          18      0           0       N     18          NULL                                                                                                                                                                                                    
SUCURSAL                           VARCHAR2                                          3       0           0       N     3           NULL                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
