campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
TIPONOVEDAD                        VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
CLASENOVEDAD                       VARCHAR2                                          1       0           0       N     1           null                                                                                                                                                                                                    
NOVEDAD                            NUMBER                                            22      11          0       N     0           null                                                                                                                                                                                                    
DEPENDENCIA                        VARCHAR2                                          12      0           0       N     12          null                                                                                                                                                                                                    
PREGUNTA                           NUMBER                                            22      5           0       N     0           null                                                                                                                                                                                                    
RESPUESTA                          VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
