campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
ID_DE_PROCESO                      NUMBER                                            22      2           0       N     0           null                                                                                                                                                                                                    
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
MES                                NUMBER                                            22      2           0       N     0           null                                                                                                                                                                                                    
PERIODO                            NUMBER                                            22      2           0       N     0           null                                                                                                                                                                                                    
ID_DE_EMPLEADO                     NUMBER                                            22      5           0       N     0           null                                                                                                                                                                                                    
ID_SERV_MEDICO                     VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
NUM_RADICA                         VARCHAR2                                          20      0           0       N     20          null                                                                                                                                                                                                    
NUM_FACTURA                        VARCHAR2                                          10      0           0       N     10          null                                                                                                                                                                                                    
MONTO_INICIAL                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
NUM_CUOTAS                         NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SALDO                              NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALOR_CUOTA                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CUOTA                              NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
OBSERVACIONES                      VARCHAR2                                          4000    0           0       Y     4000        null                                                                                                                                                                                                    
ESTADO_PRESTAMO                    VARCHAR2                                          1       0           0       N     1           'T'                                                                                                                                                                                                     
CUOTAS_A_DESCONTAR                 NUMBER                                            22      11          0       Y     0           null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_PRESTAMO                     TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       N     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_RADICA                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
