campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
TIPOMOVIMIENTO                     VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
NUMERO                             NUMBER                                            22      15          0       Y     0           null                                                                                                                                                                                                    
RESPONSABLE_DESTINO                VARCHAR2                                          18      0           0       Y     18          null                                                                                                                                                                                                    
SUCURSAL_RESDESTINO                VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
DEPENDENCIA_DESTINO                VARCHAR2                                          12      0           0       Y     12          null                                                                                                                                                                                                    
FECHA                              TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DESCRIPCION                        VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
PORCIVAGLOBAL                      NUMBER                                            22      9           4       Y     0           0                                                                                                                                                                                                       
TIPOMOVASOCIADO                    VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
MOVASOCIADO                        NUMBER                                            22      15          0       Y     0           0                                                                                                                                                                                                       
FECHAMOVASOCIADO                   TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
VALORIVA                           NUMBER                                            22      20          2       Y     0           0                                                                                                                                                                                                       
VALORDESCUENTO                     NUMBER                                            22      20          2       Y     0           0                                                                                                                                                                                                       
VALORTOTAL                         NUMBER                                            22      20          2       Y     0           0                                                                                                                                                                                                       
VACIA                              NUMBER                                            22      1           0       Y     0           0                                                                                                                                                                                                       
CENTRODECOSTO                      VARCHAR2                                          20      0           0       Y     20          '99999999999999999999'                                                                                                                                                                                  
VALORDOCASOCIADO                   NUMBER                                            22      20          2       Y     0           0                                                                                                                                                                                                       
AJUSTECENTAVOS                     NUMBER                                            22      20          2       Y     0           0                                                                                                                                                                                                       
AJUSTECENTAVOS1                    NUMBER                                            22      20          2       Y     0           0                                                                                                                                                                                                       
REGISTRADO                         NUMBER                                            22      1           0       Y     0           0                                                                                                                                                                                                       
IMPRESO                            NUMBER                                            22      1           0       Y     0           0                                                                                                                                                                                                       
GENERADO                           NUMBER                                            22      1           0       Y     0           0                                                                                                                                                                                                       
AUXILIAR                           VARCHAR2                                          20      0           0       Y     20          '99999999999999999999'                                                                                                                                                                                  
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
PROVEEDORCA                        VARCHAR2                                          18      0           0       Y     18          '999999999999999999'                                                                                                                                                                                    
SUCURSALCA                         VARCHAR2                                          3       0           0       Y     3           '999'                                                                                                                                                                                                   
FINICIO_CONTRATO                   TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FFINAL_CONTRATO                    TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
VALORTOTALCONIVA                   NUMBER                                            22      20          2       Y     0           0                                                                                                                                                                                                       
AJUSTE_DEC_MANUAL                  NUMBER                                            22      20          2       Y     0           0                                                                                                                                                                                                       
TOTALCONAJUSTE                     NUMBER                                            22      20          2       Y     0           0                                                                                                                                                                                                       
BODEGA_ORIGEN                      VARCHAR2                                          12      0           0       Y     12          null                                                                                                                                                                                                    
BODEGA_DESTINO                     VARCHAR2                                          12      0           0       Y     12          null                                                                                                                                                                                                    
CLASE_BODEGA_ORIGEN                VARCHAR2                                          2       0           0       Y     2           null                                                                                                                                                                                                    
CLASE_BODEGA_DESTINO               VARCHAR2                                          2       0           0       Y     2           null                                                                                                                                                                                                    
DEPENDENCIA_ORIGEN                 VARCHAR2                                          12      0           0       Y     12          null                                                                                                                                                                                                    
RESPONSABLE_ORIGEN                 VARCHAR2                                          18      0           0       Y     18          null                                                                                                                                                                                                    
