campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
COD_REQUISICION                    NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
ORDENDESUMINISTRO                  NUMBER                                            22      20          0       N     0           0                                                                                                                                                                                                       
COD_ACTIVIDAD                      NUMBER                                            22      20          0       Y     0           0                                                                                                                                                                                                       
DEPENDENCIA                        VARCHAR2                                          12      0           0       Y     12          null                                                                                                                                                                                                    
RESPONSABLE                        VARCHAR2                                          18      0           0       N     18          null                                                                                                                                                                                                    
SUCURSAL                           VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
COD_CLACONTRATO                    NUMBER                                            22      20          0       N     0           0                                                                                                                                                                                                       
COD_CONTRATO                       NUMBER                                            22      20          0       N     0           0                                                                                                                                                                                                       
NUMOFICIO                          VARCHAR2                                          15      0           0       Y     15          null                                                                                                                                                                                                    
DESCRIPCION                        VARCHAR2                                          4000    0           0       Y     4000        null                                                                                                                                                                                                    
VALORESTIMADO                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALORREAL                          NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VIABILIDAD                         VARCHAR2                                          15      0           0       Y     15          null                                                                                                                                                                                                    
RUBRO                              VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DISPONIBILIDAD                     NUMBER                                            22      20          0       N     0           0                                                                                                                                                                                                       
VALORDISPONIBILIDAD                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CLASEGASTO                         VARCHAR2                                          1       0           0       N     1           'F'                                                                                                                                                                                                     
VACIA                              NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
DEFINIRCONTRATACION                NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
RUBROCOMPRAS                       VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
REQUISICIONES                      VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
REQUISIONES                        VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHAREQUISICION                   TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
