campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
DOCUMENTO_IDENTIDAD                VARCHAR2                                          18      0           0       N     18          '999999999999999999'                                                                                                                                                                                    
SUCURSAL                           VARCHAR2                                          3       0           0       N     3           '999'                                                                                                                                                                                                   
RESTRICCION                        VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHARESTRICCION                   TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
