campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
TIPO                               VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
NUMERO                             NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
TERCERO                            VARCHAR2                                          18      0           0       N     18          '999999999999999999'                                                                                                                                                                                    
SUCURSAL                           VARCHAR2                                          3       0           0       N     3           '999'                                                                                                                                                                                                   
TOTALINGRESO                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DEDUCCION                          NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
PAGOS_SALUD                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
APORTES_PENSION                    NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DEDUCCION_DEPENDIENTE              NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
ARL                                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
APORTE_VOLUNTARIO                  NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DEDUCCION_PREPAGADA                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
EXENCION                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALORUVT                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALORRETENIDO                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA                              TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FSP                                NUMBER                                            22      20          2       Y     0           null                                                                                                                                                                                                    
APORTE_AFC                         NUMBER                                            22      20          2       Y     0           null                                                                                                                                                                                                    
