campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
TIPO_ABONO                         VARCHAR2                                          5       0           0       N     5           null                                                                                                                                                                                                    
CODIGO_ABONO                       NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
CUOTA                              NUMBER                                            22      5           0       N     0           0                                                                                                                                                                                                       
FECHACUOTA                         TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
CAPITAL                            NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
INTERES                            NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
INT_RECARGO                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
TOTAL_CUOTA                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
FECHA_PAGO                         TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
ANODOC                             NUMBER                                            22      4           0       Y     0           null                                                                                                                                                                                                    
TIPODOC                            VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
NRODOC                             NUMBER                                            22      20          0       Y     0           null                                                                                                                                                                                                    
BANCO_PAGO                         VARCHAR2                                          16      0           0       Y     16          null                                                                                                                                                                                                    
ESTADO                             VARCHAR2                                          1       0           0       Y     1           null                                                                                                                                                                                                    
CODIGORUTA                         VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
ANOCPTE_CAUSACION                  NUMBER                                            22      4           0       Y     0           null                                                                                                                                                                                                    
TIPOCPTE_CAUSACION                 VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
NROCPTE_CAUSACION                  NUMBER                                            22      20          0       Y     0           null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
INT_FINANCIACION                   NUMBER                                            22      20          4       Y     0           null                                                                                                                                                                                                    
