campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
CONSECUTIVO_DETALLE                NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
DEPENDENCIA_AFECTACION_GASTOS      VARCHAR2                                          30      0           0       N     30          null                                                                                                                                                                                                    
POSICION_DE_GASTOS                 VARCHAR2                                          50      0           0       N     50          null                                                                                                                                                                                                    
FUENTE_DE_FINANCIACION             VARCHAR2                                          2       0           0       N     2           null                                                                                                                                                                                                    
RECURSO_PRESUPUESTAL               VARCHAR2                                          5       0           0       N     5           null                                                                                                                                                                                                    
SITUACION_DE_FONDOS                VARCHAR2                                          2       0           0       N     2           null                                                                                                                                                                                                    
VALOR_EN_PESOS                     NUMBER                                            22      20          2       N     0           null                                                                                                                                                                                                    
COMPANIA                           VARCHAR2                                          11      0           0       N     11          null                                                                                                                                                                                                    
