campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
TIPO_DOC                           VARCHAR2                                          2       0           0       N     2           null                                                                                                                                                                                                    
NUMERO_DOC                         VARCHAR2                                          50      0           0       N     50          null                                                                                                                                                                                                    
DIGITO_CHEQUEO                     VARCHAR2                                          1       0           0       N     1           null                                                                                                                                                                                                    
ENTIDAD_FINANCIERA_TIPO_DOC        VARCHAR2                                          50      0           0       N     50          null                                                                                                                                                                                                    
ENTIDAD_FINANCIERA_NUMERO_DOC      VARCHAR2                                          50      0           0       N     50          null                                                                                                                                                                                                    
CUENTA_BANCARIA_TIPO               VARCHAR2                                          50      0           0       N     50          null                                                                                                                                                                                                    
CUENTA_BANCARIA_NUMERO             VARCHAR2                                          50      0           0       N     50          null                                                                                                                                                                                                    
TIPO_MONEDA                        VARCHAR2                                          50      0           0       N     50          null                                                                                                                                                                                                    
UNIDAD_EJECUTORA                   VARCHAR2                                          220     0           0       N     220         null                                                                                                                                                                                                    
VIGENCIA_CUENTA                    TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       N     0           null                                                                                                                                                                                                    
COMPANIA                           VARCHAR2                                          11      0           0       N     11          null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
