campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
CONSECUTIVO                        NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
POS_PAGO_NO_PPTAL                  VARCHAR2                                          30      0           0       Y     30          null                                                                                                                                                                                                    
BENEFICIARIO_TIPO_DOC              VARCHAR2                                          2       0           0       Y     2           null                                                                                                                                                                                                    
BENEFICIARIO_NUMERO_DOC            VARCHAR2                                          50      0           0       Y     50          null                                                                                                                                                                                                    
VALOR                              NUMBER                                            22      20          2       Y     0           null                                                                                                                                                                                                    
COMPANIA                           VARCHAR2                                          11      0           0       N     11          null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
