campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
PCICONEXION                        VARCHAR2                                          220     0           0       N     220         null                                                                                                                                                                                                    
FECHAREGISTRO                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       N     0           null                                                                                                                                                                                                    
SOLICITUDCDP                       NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
VALORTOTALCDP                      NUMBER                                            22      20          2       N     0           null                                                                                                                                                                                                    
TEXTOJUSTIFICATIVO                 VARCHAR2                                          250     0           0       N     250         null                                                                                                                                                                                                    
TIPODOCSOPORTE                     VARCHAR2                                          20      0           0       N     20          null                                                                                                                                                                                                    
NUMERODOCSOPORTE                   NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
FECHASOLICITUD                     TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       N     0           null                                                                                                                                                                                                    
EXPEDIDOR                          NUMBER                                            22      20          0       Y     0           null                                                                                                                                                                                                    
NOMBREFUNCIONARIO                  VARCHAR2                                          50      0           0       Y     50          null                                                                                                                                                                                                    
CARGOFUNCIONARIO                   VARCHAR2                                          20      0           0       N     20          null                                                                                                                                                                                                    
OBSERVACION                        VARCHAR2                                          250     0           0       Y     250         null                                                                                                                                                                                                    
URLDOCUMENTOSOPORTE                VARCHAR2                                          220     0           0       Y     220         null                                                                                                                                                                                                    
URLDESCRIPCIONDOCSOPORTE           VARCHAR2                                          220     0           0       Y     220         null                                                                                                                                                                                                    
COMPANIA                           VARCHAR2                                          11      0           0       N     11          null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
