campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
POSICIONCATALOGOPAGONOPRESU        VARCHAR2                                          220     0           0       N     220         null                                                                                                                                                                                                    
TIPODOCUMENTOIDENTIDAD             VARCHAR2                                          1       0           0       N     1           null                                                                                                                                                                                                    
NUMERODOCUMENTOTERCERO             VARCHAR2                                          50      0           0       N     50          null                                                                                                                                                                                                    
TIPOCUENTABANCARIA                 VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
NUMEROCUENTABANCARIA               VARCHAR2                                          30      0           0       Y     30          null                                                                                                                                                                                                    
BASEGRAVABLE                       NUMBER                                            22      20          2       Y     0           null                                                                                                                                                                                                    
TARIFA                             NUMBER                                            22      20          2       Y     0           null                                                                                                                                                                                                    
VALORDEDEDUCCION                   NUMBER                                            22      20          2       N     0           null                                                                                                                                                                                                    
COMPANIA                           VARCHAR2                                          11      0           0       N     11          null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
