campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
NUMERO_CAJAMENOR                   NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
PENDIENTELEGALIZACION              VARCHAR2                                          2       0           0       N     2           null                                                                                                                                                                                                    
NATURALEZAJURIDICA                 VARCHAR2                                          2       0           0       N     2           null                                                                                                                                                                                                    
TERCERO_NUMERO_DOC                 VARCHAR2                                          50      0           0       N     50          null                                                                                                                                                                                                    
TIPOCUENTAPAGAR                    VARCHAR2                                          50      0           0       N     50          null                                                                                                                                                                                                    
CLASIFICADOR_REGIONAL              VARCHAR2                                          50      0           0       N     50          null                                                                                                                                                                                                    
CLASIFICADOR_CIUDAD                VARCHAR2                                          50      0           0       N     50          null                                                                                                                                                                                                    
VALOR_BRUTO                        NUMBER                                            22      20          2       N     0           null                                                                                                                                                                                                    
VALOR_IVA                          NUMBER                                            22      20          2       Y     0           null                                                                                                                                                                                                    
VALOR_DEDUCCIONES                  NUMBER                                            22      20          2       Y     0           null                                                                                                                                                                                                    
MEDIO_PAGO                         VARCHAR2                                          2       0           0       N     2           null                                                                                                                                                                                                    
CUENTABANCARIA                     VARCHAR2                                          50      0           0       Y     50          null                                                                                                                                                                                                    
CHEQUERA                           NUMBER                                            22      20          0       Y     0           null                                                                                                                                                                                                    
SOPORTE_TIPO_DOC                   VARCHAR2                                          10      0           0       N     10          null                                                                                                                                                                                                    
SOPORTE_NUMERO_DOC                 NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
FECHASOLICITUD                     TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       N     0           null                                                                                                                                                                                                    
EXPEDIDOR                          NUMBER                                            22      20          0       Y     0           null                                                                                                                                                                                                    
FUNCIONARIO_NOM                    VARCHAR2                                          50      0           0       Y     50          null                                                                                                                                                                                                    
FUNCIONARIO_CARGO                  VARCHAR2                                          50      0           0       Y     50          null                                                                                                                                                                                                    
OBSERVACION                        VARCHAR2                                          250     0           0       Y     250         null                                                                                                                                                                                                    
SOPORTE_URL_DOC                    VARCHAR2                                          220     0           0       Y     220         null                                                                                                                                                                                                    
SOPORTE_URL_DESCRIPCION            VARCHAR2                                          220     0           0       Y     220         null                                                                                                                                                                                                    
COMPANIA                           VARCHAR2                                          11      0           0       N     11          null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
