campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
CONSECUTIVO                        NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
DEPENDENCIA_AFEC_INGRESOS          VARCHAR2                                          30      0           0       N     30          null                                                                                                                                                                                                    
POS_CATALOG_INGRESOS               VARCHAR2                                          50      0           0       N     50          null                                                                                                                                                                                                    
VALOR_MONEDAEXTRANJERA             NUMBER                                            22      20          2       N     0           null                                                                                                                                                                                                    
VALOR_PESOS                        NUMBER                                            22      20          2       N     0           null                                                                                                                                                                                                    
COMPANIA                           VARCHAR2                                          11      0           0       N     11          null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
