campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
PCI                                VARCHAR2                                          30      0           0       N     30          null                                                                                                                                                                                                    
FECHA                              TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       N     0           null                                                                                                                                                                                                    
CONSECUTIVO_OBLIGACION             VARCHAR2                                          30      0           0       N     30          null                                                                                                                                                                                                    
DEPENDENCIA_AFEC_PAC               VARCHAR2                                          20      0           0       N     20          null                                                                                                                                                                                                    
POS_PAC                            VARCHAR2                                          50      0           0       N     50          null                                                                                                                                                                                                    
FECHAPAGO                          TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       N     0           null                                                                                                                                                                                                    
VALORTOTAL_LINEA                   NUMBER                                            22      20          2       N     0           null                                                                                                                                                                                                    
BENEFICIARIO_TIPO                  VARCHAR2                                          1       0           0       N     1           null                                                                                                                                                                                                    
MEDIO_PAGO                         VARCHAR2                                          2       0           0       N     2           null                                                                                                                                                                                                    
PCI_TESORERIA                      VARCHAR2                                          30      0           0       Y     30          null                                                                                                                                                                                                    
BENEFICIARIO_TIPO_DOC              VARCHAR2                                          2       0           0       N     2           null                                                                                                                                                                                                    
BENEFICIARIO_NUMERO_DOC            VARCHAR2                                          50      0           0       N     50          null                                                                                                                                                                                                    
BENEFICIARIO_CUENTABANCA           VARCHAR2                                          30      0           0       N     30          null                                                                                                                                                                                                    
BENEFICIARIO_TIPO_CUENTABANCA      VARCHAR2                                          4       0           0       N     4           null                                                                                                                                                                                                    
FECHA_LIMITEPAGO                   TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       N     0           null                                                                                                                                                                                                    
SOPORTE_TIPO_DOC                   VARCHAR2                                          30      0           0       Y     30          null                                                                                                                                                                                                    
SOPORTE_NUMERO_DOC                 NUMBER                                            22      20          0       Y     0           null                                                                                                                                                                                                    
SOPORTE_FECHA_DOC                  TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
EXPEDIDOR                          NUMBER                                            22      20          0       Y     0           null                                                                                                                                                                                                    
FUNCIONARIO_NOM                    VARCHAR2                                          220     0           0       Y     220         null                                                                                                                                                                                                    
FUNCIONARIO_CARGO                  VARCHAR2                                          220     0           0       Y     220         null                                                                                                                                                                                                    
NOTAS                              VARCHAR2                                          220     0           0       Y     220         null                                                                                                                                                                                                    
COMPANIA                           VARCHAR2                                          11      0           0       N     11          null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
