campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
CODIGO                             VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
NOMBRE                             VARCHAR2                                          255     0           0       N     255         null                                                                                                                                                                                                    
PERIODICIDAD                       VARCHAR2                                          5       0           0       Y     5           null                                                                                                                                                                                                    
CONCEPTODEUCAPITAL                 VARCHAR2                                          5       0           0       Y     5           null                                                                                                                                                                                                    
CONCEPTODEUINTERES                 VARCHAR2                                          5       0           0       Y     5           null                                                                                                                                                                                                    
CONCEPTOSANCION                    VARCHAR2                                          5       0           0       Y     5           null                                                                                                                                                                                                    
GENERADEUDA                        NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
MANEJAESTRATO                      NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
VENCIMIENTO_FACTURACION            VARCHAR2                                          5       0           0       N     5           null                                                                                                                                                                                                    
DIAS_VALIDEZ                       NUMBER                                            22      5           0       N     0           0                                                                                                                                                                                                       
MANEJA_INVENTARIO                  NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
CONSECUTIVO_FACTURACION            NUMBER                                            22      20          0       Y     0           null                                                                                                                                                                                                    
CPTE_RECAUDO                       VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
TIPOCPTE_ANULACION                 VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
MANEJA_RESFACTURACION              NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
NORES_FACTURACION                  VARCHAR2                                          50      0           0       Y     50          null                                                                                                                                                                                                    
FECRES_FACTURACION                 TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
NOINICIAL_FACTURACION              NUMBER                                            22      20          0       Y     0           null                                                                                                                                                                                                    
NOFINAL_FACTURACION                NUMBER                                            22      20          0       Y     0           null                                                                                                                                                                                                    
FORMATO_FACTURA                    VARCHAR2                                          50      0           0       Y     50          null                                                                                                                                                                                                    
LEYENDA_FACTURA                    VARCHAR2                                          250     0           0       Y     250         null                                                                                                                                                                                                    
IND_DERECHOSCONEXION               NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
INTERFAZ_RECAUDO                   NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
TIPOFACTURA_RECAUDO                NUMBER                                            22      5           0       Y     0           null                                                                                                                                                                                                    
TIPOCOBRO_NOFACTURADO              NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
MANEJA_RECAUDOTERCEROS             NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
CLASE_CUENTASRECAUDO               VARCHAR2                                          30      0           0       Y     30          null                                                                                                                                                                                                    
BASEORIGINAL                       NUMBER                                            22      20          0       N     0           0                                                                                                                                                                                                       
LIQUIDACION                        NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
CODIGOEAN                          VARCHAR2                                          250     0           0       Y     250         null                                                                                                                                                                                                    
NOAPLICACAUSACION                  NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
INICIAEN                           NUMBER                                            22      20          0       N     0           0                                                                                                                                                                                                       
BANCO_CUENTA1                      VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
BANCO_CUENTA2                      VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
BANCO_CUENTA3                      VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
BANCO_CUENTA4                      VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
INDPRELIQUIDACION                  NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
APLCUENTAREC                       NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
MANEJATARIFABASE                   NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
MANEJADESCRIP_EST                  NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
