campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
CICLO                              NUMBER                                            22      3           0       N     0           null                                                                                                                                                                                                    
CODIGORUTA                         VARCHAR2                                          16      0           0       N     16          null                                                                                                                                                                                                    
CONSECUTIVO                        NUMBER                                            22      11          0       N     0           null                                                                                                                                                                                                    
USO                                VARCHAR2                                          2       0           0       Y     2           null                                                                                                                                                                                                    
ESTRATO                            VARCHAR2                                          2       0           0       Y     2           null                                                                                                                                                                                                    
ESTADO                             VARCHAR2                                          1       0           0       Y     1           null                                                                                                                                                                                                    
USO_ANT                            VARCHAR2                                          2       0           0       Y     2           null                                                                                                                                                                                                    
ESTRATO_ANT                        VARCHAR2                                          2       0           0       Y     2           null                                                                                                                                                                                                    
ESTADO_ANT                         VARCHAR2                                          1       0           0       Y     1           null                                                                                                                                                                                                    
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
PERIODO                            VARCHAR2                                          2       0           0       N     2           null                                                                                                                                                                                                    
LECTURA                            NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
LECTURA1                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
FECHALECTURACTUAL                  TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
PERIODOSATRASO                     NUMBER                                            22      5           0       N     0           0                                                                                                                                                                                                       
FECHAPAGOPERANTERIOR               TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHAPAGOPERPROCESO                TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHAPAGOPERACTUAL                 TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
TOTFACTURAPERACTUAL                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
ACUEDUCTO                          NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
ASEO                               NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
ASEOBARRIDO                        NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
ALCANTARILLADO                     NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
CHAPETAS                           NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
CHAPETAS_ANT                       NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
COMENTARIOS                        VARCHAR2                                          4000    0           0       Y     4000        null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
OBSERVACION                        VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
