campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
CICLO                              NUMBER                                            22      3           0       N     0           null                                                                                                                                                                                                    
CODIGORUTA                         VARCHAR2                                          16      0           0       N     16          null                                                                                                                                                                                                    
FECHA                              TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       N     0           null                                                                                                                                                                                                    
BANCO                              VARCHAR2                                          16      0           0       N     16          null                                                                                                                                                                                                    
NUMEROPAQUETE                      VARCHAR2                                          4       0           0       N     4           null                                                                                                                                                                                                    
CONCEPTO                           NUMBER                                            22      5           0       N     0           null                                                                                                                                                                                                    
CONSECUTIVO                        NUMBER                                            22      11          0       N     0           null                                                                                                                                                                                                    
TIPOPAGO                           VARCHAR2                                          1       0           0       N     1           null                                                                                                                                                                                                    
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
PERIODO                            VARCHAR2                                          2       0           0       N     2           null                                                                                                                                                                                                    
VALORDEUDA                         NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALORPAGOPERIODO                   NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALORFINACT                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALORFINANT                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALORABONOACT                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALORABONOANT                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CREDITOABONADO                     NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
