campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
FINANCIABLE                        NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
NUMERO                             NUMBER                                            22      5           0       N     0           null                                                                                                                                                                                                    
CUOTAS                             NUMBER                                            22      5           0       N     0           0                                                                                                                                                                                                       
USUARIO                            VARCHAR2                                          15      0           0       Y     15          null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA                              TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
