campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
USO                                VARCHAR2                                          2       0           0       N     2           null                                                                                                                                                                                                    
CODIGO                             VARCHAR2                                          2       0           0       N     2           null                                                                                                                                                                                                    
NOMBRE                             VARCHAR2                                          25      0           0       Y     25          null                                                                                                                                                                                                    
CLASIFICACIONSUI                   VARCHAR2                                          2       0           0       Y     2           null                                                                                                                                                                                                    
CLASIFICACIONSUIASEO               VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
COD_CTASPORCOBRAR                  VARCHAR2                                          60      0           0       Y     60          null                                                                                                                                                                                                    
DESCR_COD_CTASPORCOBRAR            VARCHAR2                                          100     0           0       Y     100         null                                                                                                                                                                                                    
HOMOLOGACION                       VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
