campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
CONSECUTIVO                        NUMBER                                            22      11          0       N     0           null                                                                                                                                                                                                    
USUARIO                            VARCHAR2                                          20      0           0       N     20          null                                                                                                                                                                                                    
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
PERIODO                            VARCHAR2                                          2       0           0       N     2           null                                                                                                                                                                                                    
VRAFINANCIAR                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
NOCUOTAS                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
ABONOINICIAL                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
USUARIOSISTEMA                     VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
FINANCIADO                         NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
CICLO                              NUMBER                                            22      3           0       N     0           null                                                                                                                                                                                                    
VALORCUOTA                         NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
PERIODOSNOCOBRO                    NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
INDANULADO                         NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
USUARIOANULO                       VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
CONSECUTIVOMANUAL                  VARCHAR2                                          50      0           0       Y     50          null                                                                                                                                                                                                    
NOMBRES                            VARCHAR2                                          50      0           0       Y     50          null                                                                                                                                                                                                    
IDENTIFICACION                     VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
LUGAREXPEDICION                    VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
CELULAR                            VARCHAR2                                          13      0           0       Y     13          null                                                                                                                                                                                                    
ROL                                VARCHAR2                                          30      0           0       Y     30          null                                                                                                                                                                                                    
PERIODOSATRASOINI                  NUMBER                                            22      5           0       N     0           0                                                                                                                                                                                                       
ESTRATO                            VARCHAR2                                          2       0           0       N     2           null                                                                                                                                                                                                    
USO                                VARCHAR2                                          2       0           0       N     2           null                                                                                                                                                                                                    
FACTURA                            NUMBER                                            22      20          0       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHAFACTURA                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHAANULACION                     TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHAACTUAL                        TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA                              TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
