campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
CICLO                              NUMBER                                            22      3           0       N     0           null                                                                                                                                                                                                    
CODIGORUTA                         VARCHAR2                                          16      0           0       N     16          null                                                                                                                                                                                                    
TIPO                               VARCHAR2                                          1       0           0       N     1           null                                                                                                                                                                                                    
CONSECUTIVO                        NUMBER                                            22      11          0       N     0           null                                                                                                                                                                                                    
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
PERIODO                            VARCHAR2                                          2       0           0       N     2           null                                                                                                                                                                                                    
FACTURA                            NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALORFACTURA                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALORABONO                         NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
PERIODOSATRASO                     NUMBER                                            22      5           0       N     0           0                                                                                                                                                                                                       
USO                                VARCHAR2                                          2       0           0       N     2           null                                                                                                                                                                                                    
ESTRATO                            VARCHAR2                                          2       0           0       N     2           null                                                                                                                                                                                                    
CREADOR                            VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
AUTORIZA                           VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
TIMPRESION                         VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA                              TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
