campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
CICLO                              NUMBER                                            22      3           0       N     0           null                                                                                                                                                                                                    
CODIGORUTA                         VARCHAR2                                          16      0           0       N     16          null                                                                                                                                                                                                    
CONSECUTIVO                        NUMBER                                            22      11          0       N     0           null                                                                                                                                                                                                    
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
PERIODO                            VARCHAR2                                          2       0           0       N     2           null                                                                                                                                                                                                    
TIPO_OPERACION                     VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
AFORADOR                           VARCHAR2                                          4       0           0       N     4           null                                                                                                                                                                                                    
DESCRIPCION                        VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
LECTURA                            NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
MEDIDOR                            NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SELLO_RETIRADO                     VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
SELLO_INSTALADO                    VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
ESTADO                             VARCHAR2                                          1       0           0       Y     1           null                                                                                                                                                                                                    
USUARIO                            VARCHAR2                                          30      0           0       Y     30          null                                                                                                                                                                                                    
ESTADO_OPE                         VARCHAR2                                          1       0           0       Y     1           null                                                                                                                                                                                                    
OBSERVACIONES                      VARCHAR2                                          254     0           0       Y     254         null                                                                                                                                                                                                    
FORMATO                            VARCHAR2                                          15      0           0       N     15          null                                                                                                                                                                                                    
OBSERVACIONESSITIO                 VARCHAR2                                          4000    0           0       Y     4000        null                                                                                                                                                                                                    
AFORADORSITIO                      VARCHAR2                                          13      0           0       Y     13          null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
HORACREACION                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHASOLUCIONSITIO                 TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHAEJECUCION                     TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
HORAEJECUCION                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA                              TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHAACTA                          TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       N     0           null                                                                                                                                                                                                    
TIPOACTA                           NUMBER                                            22      5           0       N     0           null                                                                                                                                                                                                    
