campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
CONSECUTIVO                        NUMBER                                            22      11          0       N     0           null                                                                                                                                                                                                    
CODIGO                             VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
MARCA                              VARCHAR2                                          30      0           0       Y     30          null                                                                                                                                                                                                    
DIGITOS                            NUMBER                                            22      5           0       N     0           null                                                                                                                                                                                                    
LECTURAINICIAL                     NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
ANO                                NUMBER                                            22      4           0       Y     0           null                                                                                                                                                                                                    
PERIODO                            VARCHAR2                                          2       0           0       Y     2           null                                                                                                                                                                                                    
ESTADO                             VARCHAR2                                          1       0           0       Y     1           null                                                                                                                                                                                                    
CICLO                              NUMBER                                            22      3           0       Y     0           null                                                                                                                                                                                                    
CODIGORUTA                         VARCHAR2                                          16      0           0       Y     16          null                                                                                                                                                                                                    
LECTMEDANT                         NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
LECTACTUAL                         NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
NUMFACTURA                         VARCHAR2                                          15      0           0       Y     15          null                                                                                                                                                                                                    
ELEMCAMBIO                         VARCHAR2                                          15      0           0       Y     15          null                                                                                                                                                                                                    
NOORDENINST                        VARCHAR2                                          15      0           0       Y     15          null                                                                                                                                                                                                    
TIPO                               VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
GEO_VERTICE                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
GEO_LONGITUD                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
GEO_LATITUD                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
GEO_ALTITUD                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
LECTURAFINALVIEJO                  NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
DIAMETRO                           VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
LECTURAPROMEDIO                    NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
PROMEDIO                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
LONGITUD                           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
MEDIDORNUEVO                       VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
CLASIFICACION                      VARCHAR2                                          1       0           0       Y     1           null                                                                                                                                                                                                    
NUMCERTIFICACION                   VARCHAR2                                          250     0           0       Y     250         null                                                                                                                                                                                                    
POSICION                           VARCHAR2                                          1       0           0       Y     1           null                                                                                                                                                                                                    
RADIO                              NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CLASE                              NUMBER                                            22      5           0       N     0           null                                                                                                                                                                                                    
LOCALIZACION                       NUMBER                                            22      5           0       N     0           null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
FECHACOMPRA                        TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHAINST                          TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_REG                          TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
