campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
CICLO                              NUMBER                                            22      3           0       N     0           null                                                                                                                                                                                                    
CODIGORUTA                         VARCHAR2                                          16      0           0       N     16          null                                                                                                                                                                                                    
CONCEPTO                           NUMBER                                            22      5           0       N     0           null                                                                                                                                                                                                    
USUARIO                            VARCHAR2                                          15      0           0       Y     15          null                                                                                                                                                                                                    
VRANT                              NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VRNUE                              NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
TIPOMODIFICACION                   NUMBER                                            22      5           0       N     0           null                                                                                                                                                                                                    
CAUSAMODIFICACION                  NUMBER                                            22      5           0       N     0           null                                                                                                                                                                                                    
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
PERIODO                            VARCHAR2                                          2       0           0       N     2           null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
FECHA                              TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       N     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
HORA                               TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       N     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
