campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
CICLO                              NUMBER                                            22      3           0       N     0           null                                                                                                                                                                                                    
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
PERIODO                            VARCHAR2                                          2       0           0       N     2           null                                                                                                                                                                                                    
PAGO1                              VARCHAR2                                          50      0           0       Y     50          'CUALQUIER BANCO AUTORIZADO'                                                                                                                                                                            
PAGO2                              VARCHAR2                                          50      0           0       Y     50          'CUALQUIER BANCO AUTORIZADO'                                                                                                                                                                            
OBSERVACION2                       VARCHAR2                                          50      0           0       Y     50          null                                                                                                                                                                                                    
OBSERVACION3                       VARCHAR2                                          50      0           0       Y     50          null                                                                                                                                                                                                    
FACTURAINICIAL                     VARCHAR2                                          50      0           0       Y     50          null                                                                                                                                                                                                    
NORECIBOINICIAL                    VARCHAR2                                          14      0           0       N     14          null                                                                                                                                                                                                    
CODIGOINICIAL                      VARCHAR2                                          16      0           0       N     16          null                                                                                                                                                                                                    
CODIGOFINAL                        VARCHAR2                                          16      0           0       N     16          null                                                                                                                                                                                                    
PERIODOCORTO                       VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
PERIODOLARGO                       VARCHAR2                                          64      0           0       Y     64          null                                                                                                                                                                                                    
PERIODOANT1                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
PERIODOANT2                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
PERIODOANT3                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
PERIODOANT4                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
PERIODOANT5                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
PERIODOANT6                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
FECHACORTEC1                       VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
FECHACORTEC2                       VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
FECHACORTEC3                       VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
FECHACORTEL1                       VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
FECHACORTEL2                       VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
FECHACORTEL3                       VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
OBSERVACION1                       VARCHAR2                                          200     0           0       Y     200         null                                                                                                                                                                                                    
PUBLICIDAD                         VARCHAR2                                          100     0           0       Y     100         null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
FECHALIMITE3                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHAINICIOPERIODO                 TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHAFINPERIODO                    TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHASUSPENSION                    TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHAEXPEDICION                    TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHALIMITE2                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHALIMITE1                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
