campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
TIPOPRODUCTOR                      VARCHAR2                                          20      0           0       N     20          null                                                                                                                                                                                                    
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
PERIODO                            VARCHAR2                                          16      0           0       N     16          null                                                                                                                                                                                                    
USO                                VARCHAR2                                          16      0           0       N     16          null                                                                                                                                                                                                    
ESTRATO                            VARCHAR2                                          16      0           0       N     16          null                                                                                                                                                                                                    
CICLO                              NUMBER                                            22      3           0       N     0           null                                                                                                                                                                                                    
NUMUSUARIOS                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
PERIODOUNICO                       VARCHAR2                                          16      0           0       N     16          null                                                                                                                                                                                                    
SUMADEPESOASEO                     NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SUMADECONCEPTO21                   NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SUMADECONCEPTO20                   NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SUMADECONCEPTO22                   NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SUMADECONCEPTO3                    NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SUMADECONCEPTO48                   NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SUMADESUMADETOTFACTURAASEO         NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
NOMBREUSO                          VARCHAR2                                          16      0           0       N     16          null                                                                                                                                                                                                    
SUMADECONCEPTO46                   NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SUMADECONCEPTO37                   NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SUMADECONCEPTO38                   NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
SUMADETAFNA                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SUMADECONCEPTO201                  NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SUMADECONCEPTO202                  NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SUMADECONCEPTO203                  NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SUMADECONCEPTO204                  NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SUMADECONCEPTO205                  NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SUMADECONCEPTO206                  NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SUMADECONCEPTO207                  NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
