campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
PROYECTO                           VARCHAR2                                          16      0           0       N     16          null                                                                                                                                                                                                    
INDICADOR                          VARCHAR2                                          60      0           0       N     60          null                                                                                                                                                                                                    
VIGENCIA                           NUMBER                                            22      5           0       N     0           0                                                                                                                                                                                                       
VIGENCIA_PLAN                      NUMBER                                            22      5           0       N     0           0                                                                                                                                                                                                       
DESCRIPCION_INDICADOR              VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
EJECUTADO_COMPROMETIDO             NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
EJECUTADO_PAGADO                   NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
META_PROGRAMADA_ANO1               NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
META_PROGRAMADA_ANO2               NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
META_PROGRAMADA_ANO3               NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
META_PROGRAMADA_ANO4               NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
META_TOTALPROGRAMADA               NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
META_TOTAL_CUMPLIDA_ACTUAL         NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
META_TOTAL_ACUMULADA_EJECUTADA     NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
PORC_CUMPLIMIENTO_IND              NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
