campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
RESOLUCION                         VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_RESOLUCION                   TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_INICIAL                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       N     0           null                                                                                                                                                                                                    
FECHA_FINAL                        TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       N     0           null                                                                                                                                                                                                    
