campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
TIPO_DOCUMENTO                     VARCHAR2                                          2       0           0       Y     2           null                                                                                                                                                                                                    
NUMERO_IDENT                       VARCHAR2                                          18      0           0       Y     18          null                                                                                                                                                                                                    
DIGITO_VERI                        NUMBER                                            22      2           0       N     0           null                                                                                                                                                                                                    
PRIMER_APELLIDO                    VARCHAR2                                          80      0           0       Y     80          null                                                                                                                                                                                                    
SEGUNDO_APELLIDO                   VARCHAR2                                          80      0           0       Y     80          null                                                                                                                                                                                                    
PRIMER_NOMBRE                      VARCHAR2                                          80      0           0       Y     80          null                                                                                                                                                                                                    
SEGUNDO_NOMBRE                     VARCHAR2                                          80      0           0       Y     80          null                                                                                                                                                                                                    
RAZON_SOCIAL                       VARCHAR2                                          320     0           0       Y     320         null                                                                                                                                                                                                    
DIRECCION                          VARCHAR2                                          100     0           0       Y     100         null                                                                                                                                                                                                    
DEPARTAMENTO                       VARCHAR2                                          2       0           0       Y     2           null                                                                                                                                                                                                    
CIUDAD                             VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
BASE_RETE                          NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
RETENCION                          NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
PAGOCUENTA                         NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
