campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
PROCESOS                           VARCHAR2                                          32      0           0       N     32          null                                                                                                                                                                                                    
TIPOTRAMITE                        VARCHAR2                                          18      0           0       N     18          null                                                                                                                                                                                                    
PREFIJO                            VARCHAR2                                          8       0           0       Y     8           null                                                                                                                                                                                                    
RUTA                               VARCHAR2                                          255     0           0       N     255         null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
NOMBRE                             VARCHAR2                                          50      0           0       N     50          null                                                                                                                                                                                                    
