campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
CODIGO                             VARCHAR2                                          10      0           0       N     10          null                                                                                                                                                                                                    
NOMBRE                             VARCHAR2                                          60      0           0       N     60          null                                                                                                                                                                                                    
CONCEPTO_DESCUENTO                 VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
CONCEPTO_PORCENTAJE                VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
DESCRIPCION                        VARCHAR2                                          4000    0           0       Y     4000        null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
