campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
TIPO                               VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
DESCRIPCION                        VARCHAR2                                          72      0           0       Y     72          null                                                                                                                                                                                                    
TEXTO                              VARCHAR2                                          4000    0           0       Y     4000        null                                                                                                                                                                                                    
TERCERO                            VARCHAR2                                          18      0           0       N     18          null                                                                                                                                                                                                    
SUCURSAL                           VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
CENTRO_COSTO                       VARCHAR2                                          20      0           0       N     20          null                                                                                                                                                                                                    
AUXILIAR                           VARCHAR2                                          20      0           0       N     20          null                                                                                                                                                                                                    
REFERENCIA                         VARCHAR2                                          20      0           0       N     20          null                                                                                                                                                                                                    
FUENTE_RECURSO                     VARCHAR2                                          20      0           0       N     20          null                                                                                                                                                                                                    
CLASE                              VARCHAR2                                          16      0           0       Y     16          null                                                                                                                                                                                                    
VLRAGIRAR                          VARCHAR2                                          200     0           0       Y     200         null                                                                                                                                                                                                    
PIDEDOLARES                        NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
PIDEDOCASOCIADO                    NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
PIDECTABANCOS                      NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
VLRCOMPROBANTE                     VARCHAR2                                          200     0           0       Y     200         null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA                              TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
VLRBASEGRAVABLE                    VARCHAR2                                          200     0           0       Y     200         null                                                                                                                                                                                                    
VLRIVAFACTURADO                    VARCHAR2                                          200     0           0       Y     200         null                                                                                                                                                                                                    
TODOSLOSCENTROS                    NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
TIPOGENERAR                        VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
NUMEROGENERAR                      NUMBER                                            22      20          0       Y     0           null                                                                                                                                                                                                    
TIPO_GASTO                         VARCHAR2                                          30      0           0       Y     30          null                                                                                                                                                                                                    
MEDIO_PAGO                         VARCHAR2                                          30      0           0       Y     30          null                                                                                                                                                                                                    
CONCEPTO                           VARCHAR2                                          10      0           0       Y     10          null                                                                                                                                                                                                    
RESOLUCION                         VARCHAR2                                          16      0           0       Y     16          null                                                                                                                                                                                                    
MOVIMIENTO                         NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
NUMERO                             VARCHAR2                                          20      0           0       N     20          null                                                                                                                                                                                                    
TIPO_OPERACION                     VARCHAR2                                          1       0           0       Y     1           null                                                                                                                                                                                                    
