campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
TIPOCONTRATO                       VARCHAR2                                          5       0           0       N     5           null                                                                                                                                                                                                    
CONSECUTIVO                        NUMBER                                            22      15          0       N     0           null                                                                                                                                                                                                    
ANO                                NUMBER                                            22      4           0       N     0           NULL                                                                                                                                                                                                    
ESTADO                             VARCHAR2                                          2       0           0       N     2           0                                                                                                                                                                                                       
OBSERVACION                        VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
OBSERVACION_ANULA                  VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
NUMERO                             NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
ESTUDIOPREVIO                      NUMBER                                            22      20          0       Y     0           NULL                                                                                                                                                                                                    
NUM_PROCESO                        VARCHAR2                                          60      0           0       Y     60          null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
FECHA                              TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
