campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
TIPOCONTRATO                       VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
TRANSACCION                        NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
VARIABLE                           VARCHAR2                                          50      0           0       N     50          null                                                                                                                                                                                                    
VALOR                              VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
VLR_NUMERO                         NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VLR_TEXTO                          VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
VISIBLE                            NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
VLR_FECHA                          TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
