campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
PLACA                              VARCHAR2                                          15      0           0       N     15          null                                                                                                                                                                                                    
CODIGO                             NUMBER                                            22      15          0       N     0           0                                                                                                                                                                                                       
NUMEROPOLIZA                       VARCHAR2                                          16      0           0       Y     16          null                                                                                                                                                                                                    
NIT                                VARCHAR2                                          18      0           0       N     18          '999999999999999999'                                                                                                                                                                                    
SUCURSAL                           VARCHAR2                                          3       0           0       N     3           '999'                                                                                                                                                                                                   
NOMBRE                             VARCHAR2                                          150     0           0       Y     150         null                                                                                                                                                                                                    
OBSERVACIONES                      VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
FECHAINICIAL                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHAFINAL                         TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
