campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
TIPO_VIATICO                       VARCHAR2                                          1       0           0       N     1           null                                                                                                                                                                                                    
NUMERO                             NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
TERCERO                            VARCHAR2                                          18      0           0       N     18          '999999999999999999'                                                                                                                                                                                    
SUCURSAL                           VARCHAR2                                          3       0           0       N     3           '999'                                                                                                                                                                                                   
CONCEPTO                           VARCHAR2                                          3       0           0       N     3           null                                                                                                                                                                                                    
DESCRIPCION                        VARCHAR2                                          255     0           0       N     255         null                                                                                                                                                                                                    
NUMDIASPER                         NUMBER                                            22      3           0       N     0           0                                                                                                                                                                                                       
NUMDIASSINPER                      NUMBER                                            22      3           0       N     0           0                                                                                                                                                                                                       
VALDIASPER                         NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALDIASSINPER                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
TOTAL                              NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
TIPO_CPTE_PPTAL                    VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
COMPROBANTE_PPTAL                  NUMBER                                            22      20          0       Y     0           null                                                                                                                                                                                                    
SALDO_PRESUPUESTAL                 NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
RUBRO                              VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
TIPO_CPTE_CNT                      VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
COMPROBANTE_CNT                    NUMBER                                            22      20          0       Y     0           null                                                                                                                                                                                                    
VALOR_ABONADO                      NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SALDO                              NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
CONSECUTIVO                        NUMBER                                            22      5           0       N     0           null                                                                                                                                                                                                    
