campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
CODIGO_RANGO                       VARCHAR2                                          15      0           0       N     15          null                                                                                                                                                                                                    
LIMITE_INFERIOR                    NUMBER                                            22      20          2       N     0           null                                                                                                                                                                                                    
LIMITE_SUPERIOR                    NUMBER                                            22      20          2       N     0           null                                                                                                                                                                                                    
VALOR_VIATICO_NACIONAL             NUMBER                                            22      20          2       N     0           null                                                                                                                                                                                                    
VALOR_VIATICO_ZONA1                NUMBER                                            22      20          2       N     0           null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
VIGENCIA                           NUMBER                                            22      4           0       N     0           0                                                                                                                                                                                                       
VALOR_MANUAL                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALOR_VIATICO_ZONA2                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALOR_VIATICO_ZONA3                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
