campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
ANO                                NUMBER                                            22      4           0       N     0           null                                                                                                                                                                                                    
TIPO_VIATICO                       VARCHAR2                                          1       0           0       N     1           null                                                                                                                                                                                                    
CODSOLICITUD                       NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
NUMSOLICITUD                       NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
NUMERO_RESOLUCION                  VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
FECHA                              TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       N     0           null                                                                                                                                                                                                    
FECHAINICIO                        TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHAFIN                           TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
PERNOCTA                           NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
VEHICULO                           NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
PLACA_VEHICULO                     VARCHAR2                                          10      0           0       Y     10          null                                                                                                                                                                                                    
OBJETO                             VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
OBSERVACION                        VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
JUSTIFICACION                      VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
OBSERVACIONCOMITE                  VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
DEPENDENCIA                        VARCHAR2                                          12      0           0       Y     12          null                                                                                                                                                                                                    
TVISITA                            VARCHAR2                                          2       0           0       Y     2           null                                                                                                                                                                                                    
PAIS_DESTINO                       VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
DEPARTAMENTO_DESTINO               VARCHAR2                                          2       0           0       Y     2           null                                                                                                                                                                                                    
CIUDAD_DESTINO                     VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
APROBADO                           NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
SABADO                             NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
DOMINGO                            NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
FESTIVO                            NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
TRSNESPECIAL                       NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
NODIAS                             NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
TSOLICITUD                         VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
TERCERO                            VARCHAR2                                          18      0           0       N     18          '999999999999999999'                                                                                                                                                                                    
SUCURSAL                           VARCHAR2                                          3       0           0       N     3           '999'                                                                                                                                                                                                   
TIPO_CPTE_PPTAL                    VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
COMPROBANTE_PPTAL                  NUMBER                                            22      20          0       Y     0           null                                                                                                                                                                                                    
TIPO_CPTE_CNT                      VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
COMPROBANTE_CNT                    NUMBER                                            22      20          0       Y     0           null                                                                                                                                                                                                    
VALORTOTALVIATICO                  NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALORABONADO                       NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
SALDOTOTAL                         NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
PAIS_ORIGEN                        VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
DEPARTAMENTO_ORIGEN                VARCHAR2                                          2       0           0       Y     2           null                                                                                                                                                                                                    
CIUDAD_ORIGEN                      VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
COD_PERSONA                        VARCHAR2                                          5       0           0       Y     5           null                                                                                                                                                                                                    
ESCALAFON                          VARCHAR2                                          2       0           0       Y     2           null                                                                                                                                                                                                    
ID_CATEGORIA                       VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
TCOMISION                          VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
VALOR_RESERVA_INICIAL              NUMBER                                            22      20          2       Y     0           null                                                                                                                                                                                                    
VALOR_TIQUETE_EMITIDO              NUMBER                                            22      20          2       Y     0           null                                                                                                                                                                                                    
NUMERO_LOCALIZADOR                 VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
ITINERARIO                         VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
NUMERO_RADICADO                    VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
FECHA_RADICADO                     TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
VALOR_FACTURA_TIQUETE              NUMBER                                            22      20          2       Y     0           null                                                                                                                                                                                                    
FECHA_FACTURA_TIQUETE              TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
VALOR_DESCUENTO_AGENCIA            NUMBER                                            22      20          2       Y     0           null                                                                                                                                                                                                    
ESTADO                             VARCHAR2                                          1       0           0       N     1           null                                                                                                                                                                                                    
TIPOCOMISION                       VARCHAR2                                          1       0           0       N     1           null                                                                                                                                                                                                    
JEFE_DEPENDENCIA                   VARCHAR2                                          18      0           0       Y     18          null                                                                                                                                                                                                    
FECHA_NACIMIENTO                   TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
BANCO                              VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
CTA_BANCARIA                       VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
TELEFONOS                          VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
CORREO_ELECTRONICO                 VARCHAR2                                          50      0           0       Y     50          null                                                                                                                                                                                                    
OBSERVACION_SOLICITUD              CLOB                                              4000    0           0       Y     0           NULL                                                                                                                                                                                                    
SUCURSAL_JEFE                      VARCHAR2                                          3       0           0       N     3           '999'                                                                                                                                                                                                   
FECHA_AUT_SIIF_NACION              TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_COM_DESEMBOLSO_SIIF          TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_DESEMBOLSO_TRANSPORTE        TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
NUMERO_COM_DESEMBOLSO_SIIF         VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
NUMERO_COM_DESEM_TRANSPORTE        VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
FECHA_APROBACION                   TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
SALARIO_COMISIONADO                NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CLASE_TRANSPORTE                   VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
DESCRIPCION_TRANS                  VARCHAR2                                          250     0           0       Y     250         null                                                                                                                                                                                                    
VALOR_TRANSPORTE                   NUMBER                                            22      20          2       Y     0           null                                                                                                                                                                                                    
DESTINO_CORRERIA                   CLOB                                              4000    0           0       Y     0           EMPTY_CLOB()                                                                                                                                                                                            
PAIS_REGRESO                       VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
DEPARTAMENTO_REGRESO               VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
CIUDAD_REGRESO                     VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
HORA_SALIDA                        TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
HORA_REGRESO                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
NRO_RADICADO_DOC                   VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
GENERA_VIATICOS                    NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
SOLICITA_TIQUETE                   NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
VALOR_DIARIO_COMISION              NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
ESTADO_LEGALIZACION                VARCHAR2                                          1       0           0       Y     1           null                                                                                                                                                                                                    
OBSERVACION_LEGALIZACION           VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
FECHA_APROBA_LEGA                  TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
VALOR_VIATICO_LEGALIZADO           NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALOR_TRANSPORTE_LEGALIZADO        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
VALOR_REEMBOLSADO                  NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
FECHA_REEMBOLSO                    TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
VALOR_TRANSPORTE_REEMBOLSO         NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
FECHA_TRANS_REEMBOLSO              TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
FECHA_GRABACION_SIIF               TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
CIUDAD_EXPE                        VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
DEPARTAMENTO_EXPE                  VARCHAR2                                          2       0           0       Y     2           null                                                                                                                                                                                                    
PAIS_EXPE                          VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
FECHA_AUT_FACTURA                  TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
NUMERO_RADICADO_AUTO               VARCHAR2                                          26      0           0       Y     26          null                                                                                                                                                                                                    
FECHA_LEGALIZACION                 TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
RESUMEN_ACTIVIDADES                CLOB                                              4000    0           0       Y     0           null                                                                                                                                                                                                    
LEGALIZADO_PLAZO                   NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
NUMERO_OFICIO_MINTIC               VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
FECHA_RADICADO_MINTIC              TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
ESTADO_MINTIC                      VARCHAR2                                          1       0           0       Y     1           null                                                                                                                                                                                                    
FECHA_APROBA_MINTIC                TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
AVAL_COORDINADOR                   VARCHAR2                                          1       0           0       Y     1           null                                                                                                                                                                                                    
NUMERO_RESOLUCION_MINTIC           VARCHAR2                                          20      0           0       Y     20          null                                                                                                                                                                                                    
FECHA_RESOLUCION_MINTIC            TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
ZONA_EXTERIOR                      VARCHAR2                                          1       0           0       Y     1           null                                                                                                                                                                                                    
DIAS_TRANSITO                      NUMBER                                            22      3           0       N     0           0                                                                                                                                                                                                       
VALOR_TASA_CAMBIO                  NUMBER                                            22      20          2       Y     0           null                                                                                                                                                                                                    
FECHA_TASA_CAMBIO                  TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
VALOR_TOTAL_PESOS                  NUMBER                                            22      20          2       Y     0           null                                                                                                                                                                                                    
NRO_RADICADO_DOC_MINTIC            VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
OBSERVACION_APROB                  VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
FECHA_RADICADO_DOC                 TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
