campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
ID_PROYECTO                        NUMBER                                            22      15          0       N     0           null                                                                                                                                                                                                    
COMPANIA                           VARCHAR2                                          11      0           0       N     11          null                                                                                                                                                                                                    
CODIGO_PROYECTO                    VARCHAR2                                          16      0           0       N     16          null                                                                                                                                                                                                    
NUMERO                             NUMBER                                            22      20          0       N     0           null                                                                                                                                                                                                    
CLASE_PROYECTO                     VARCHAR2                                          2       0           0       N     2           null                                                                                                                                                                                                    
TIPO_TRAMITE                       VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
TIPO_COMPROBANTE                   VARCHAR2                                          3       0           0       Y     3           null                                                                                                                                                                                                    
FECHA                              TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       N     0           null                                                                                                                                                                                                    
NUMERO_ACTOADMINISTRATIVO          NUMBER                                            22      20          0       N     0           0                                                                                                                                                                                                       
RUTA_ANEXO                         VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
FECHA_LIMITE                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       N     0           null                                                                                                                                                                                                    
VALOR_TOTAL                        NUMBER                                            22      20          2       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
