SELECT IP_USUARIOS_PREDIAL.COMPANIA, 
    IP_USUARIOS_PREDIAL.CODIGO, 
    IP_USUARIOS_PREDIAL.NUMERO_ORDEN,
    IP_USUARIOS_PREDIAL.MATRICULA_INMOBILIARIA,
    IP_USUARIOS_PREDIAL.ESTRATO_SOCIOECONOMICO,
    IP_USUARIOS_PREDIAL.DIRECCION,
    IP_USUARIOS_PREDIAL.AREA_M2,
    IP_USUARIOS_PREDIAL.AREA_CONSTRUIDA,
    IP_USUARIOS_PREDIAL.TRPCOD,
    IP_USUARIOS_PREDIAL.EXINICIAL,
    IP_USUARIOS_PREDIAL.NOMBRE,
    IP_USUARIOS_PREDIAL.TIPO,
    IP_USUARIOS_PREDIAL.TIPO_NIT,
    IP_USUARIOS_PREDIAL.NIT,
    IP_USUARIOS_PREDIAL.TELEFONO_PROPIETARIO,
    IP_USUARIOS_PREDIAL.USO_SUELO,
    IP_USUARIOS_PREDIAL.AVALUO_ANO,
    IP_USUARIOS_PREDIAL.C1,
    IP_USUARIOS_PREDIAL.C3,
    (IP_USUARIOS_PREDIAL.C1 + IP_USUARIOS_PREDIAL.C3) AS VALORAPAGAR,
    (IP_USUARIOS_PREDIAL.C2 + IP_USUARIOS_PREDIAL.C4) AS INTERESESMORA,
    IP_USUARIOS_PREDIAL.C13,
    IP_USUARIOS_PREDIAL.TOTAL
FROM IP_USUARIOS_PREDIAL INNER JOIN IP_TARIFAS ON
    IP_USUARIOS_PREDIAL.COMPANIA = IP_TARIFAS.COMPANIA
    AND IP_USUARIOS_PREDIAL.TRPCOD = IP_TARIFAS.TRPCOD
WHERE IP_USUARIOS_PREDIAL.COMPANIA = s$compania$s
    AND IP_USUARIOS_PREDIAL.CODIGO = 's$codigoCons$s'
    AND IP_USUARIOS_PREDIAL.NUMERO_ORDEN = 's$numeroOrden$s'
    AND IP_TARIFAS.TRPANO = s$ano$s
