SELECT  IP_USUARIOS_PREDIAL.CODIGO, 
        IP_USUARIOS_PREDIAL.NIT, 
        IP_USUARIOS_PREDIAL.NOMBRE, 
        IP_USUARIOS_PREDIAL.CODIGO_NO_ACTIVO, 
        IP_USUARIOS_PREDIAL.INDBORRADO,
        CASE WHEN IP_FACTURADOS.CODIGO IS NOT NULL THEN 'SI' ELSE 'NO' END FACTURADO
FROM IP_USUARIOS_PREDIAL
  LEFT JOIN IP_FACTURADOS
    ON IP_USUARIOS_PREDIAL.COMPANIA = IP_FACTURADOS.COMPANIA
    AND IP_USUARIOS_PREDIAL.CODIGO = IP_FACTURADOS.CODIGO
    AND IP_USUARIOS_PREDIAL.NUMERO_ORDEN = IP_FACTURADOS.NUMERO_ORDEN
WHERE IP_USUARIOS_PREDIAL.COMPANIA = s$compania$s
  AND IP_USUARIOS_PREDIAL.NUMERO_ORDEN = 's$numeroOrden$s'
  AND IP_USUARIOS_PREDIAL.PAGO_ANO IN (0)
  AND IP_USUARIOS_PREDIAL.CODIGO_NO_ACTIVO IN (0)
  AND IP_USUARIOS_PREDIAL.INDBORRADO IN (0)
