SELECT IGAC_RESOLUCIONESDET.CODIGO,
  CASE
    WHEN IGAC_RESOLUCIONESDET.CANCELAINSCRIBE = 'I'
    THEN 'Inscribe'
    WHEN IGAC_RESOLUCIONESDET.CANCELAINSCRIBE = 'M'
    THEN 'Modifica'
    ELSE 'Cancela'
  END CANCELAINSCRIBE ,
  IGAC_RESOLUCIONESDET.RESOLUCION,
  IGAC_RESOLUCIONESDET.NOMBRE,
  IGAC_RESOLUCIONESDET.ANTNOMBRE,
  IGAC_RESOLUCIONESDET.TIPODOCUMENTO,
  IGAC_RESOLUCIONESDET.ANTTIPODOCUMENTO,
  IGAC_RESOLUCIONESDET.NUMERODOCUMENTO,
  IGAC_RESOLUCIONESDET.ANTNUMERODOCUMENTO,
  IGAC_RESOLUCIONESDET.DIRECCION,
  IGAC_RESOLUCIONESDET.ANTDIRECCION,
  IGAC_RESOLUCIONESDET.AREATERRENO,
  IGAC_RESOLUCIONESDET.ANTAREATERRENO,
  IGAC_RESOLUCIONESDET.AREACONSTRUIDA,
  IGAC_RESOLUCIONESDET.ANTCONSTRUIDA,
  IGAC_RESOLUCIONESDET.AVALUO,
  IGAC_RESOLUCIONESDET.ANTAVALUO,
  IGAC_RESOLUCIONESDET.AREATERENOM2,
  IGAC_RESOLUCIONESDET.AREAHECTARES,
  IGAC_RESOLUCIONESDET.ANTAREAHECTARES,
  IGAC_RESOLUCIONESDET.FECHAINGRESOSISTEMA
FROM IP_IGAC_RESOLUCIONESDET IGAC_RESOLUCIONESDET
WHERE IGAC_RESOLUCIONESDET.COMPANIA = s$compania$s 
  AND IGAC_RESOLUCIONESDET.CODIGO BETWEEN 's$predioInicial$s' 
                                      AND 's$predioFinal$s'
