SELECT  IP_RECIBOS_DE_PAGO.PAG_BANPAG,
        IP_BANCOS.NOMBREBANCO,
        IP_RECIBOS_DE_PAGO.PREFEC, 
        IP_FACTURADOS.DOCNUM, 
        IP_RECIBOS_DE_PAGO.PRECOD,
        MAX(CASE WHEN TO_CHAR(IP_RECIBOS_DE_PAGO.PREANOI) IS NULL 
              THEN TO_CHAR(IP_USUARIOS_PREDIAL.VIGENCIA)
              ELSE 
                CASE WHEN TO_CHAR(IP_RECIBOS_DE_PAGO.PREANOI) = TO_CHAR(IP_RECIBOS_DE_PAGO.PREANOF)
                  THEN TO_CHAR(IP_USUARIOS_PREDIAL.VIGENCIA)
                  ELSE TO_CHAR(IP_RECIBOS_DE_PAGO.PREANOI) 
                  END 
              END || ' ' ||TO_CHAR(IP_RECIBOS_DE_PAGO.PREANOF)) AS ANIOS,
        IP_RECIBOS_DE_PAGO.PREFECPAG, 
        IP_USUARIOS_PREDIAL.TRPCOD || ' - ' || IP_TARIFAS.TRPPOR AS TARIFA,
        IP_USUARIOS_PREDIAL.AVALUO_ANO, 
        SUM(CASE WHEN IP_FACTURADOS.PREANO <= 2004 THEN IP_FACTURADOS.C1 ELSE ROUND(IP_FACTURADOS.C1*0.85,0) END)IMPUESTOPREDIAL, 
        SUM(CASE WHEN IP_FACTURADOS.PREANO <= 2004 THEN IP_FACTURADOS.C2 ELSE ROUND(IP_FACTURADOS.C2*0.85,0) END) INTERESPREDIAL ,
        SUM(CASE WHEN IP_FACTURADOS.PREANO <= 2004 THEN IP_FACTURADOS.C3 ELSE IP_FACTURADOS.C1 - ROUND(IP_FACTURADOS.C1*0.85,0)END)CAR ,
        SUM(CASE WHEN IP_FACTURADOS.PREANO <= 2004 THEN IP_FACTURADOS.C3 ELSE IP_FACTURADOS.C2 - ROUND(IP_FACTURADOS.C2*0.85) END )INTERESCAR ,
        SUM(CASE WHEN IP_FACTURADOS.PREANO <= 2004 THEN IP_FACTURADOS.C3 ELSE IP_FACTURADOS.C1 - ROUND(IP_FACTURADOS.C1*0.85,0)END)+
        SUM(CASE WHEN IP_FACTURADOS.PREANO <= 2004 THEN IP_FACTURADOS.C3 ELSE IP_FACTURADOS.C2 - ROUND(IP_FACTURADOS.C2*0.85) END )TOTALCAR
FROM IP_FACTURADOS 
  INNER JOIN IP_RECIBOS_DE_PAGO 
    ON  IP_FACTURADOS.COMPANIA 			= IP_RECIBOS_DE_PAGO.COMPANIA
    AND IP_FACTURADOS.DOCNUM 			= IP_RECIBOS_DE_PAGO.DOCNUM 
    AND IP_FACTURADOS.CODIGO 			= IP_RECIBOS_DE_PAGO.PRECOD 
    AND IP_FACTURADOS.PREANO 			= IP_RECIBOS_DE_PAGO.PREANO 
  INNER JOIN IP_USUARIOS_PREDIAL 
    ON  IP_RECIBOS_DE_PAGO.COMPANIA 		= IP_USUARIOS_PREDIAL.COMPANIA 
    AND IP_RECIBOS_DE_PAGO.PRECOD 		= IP_USUARIOS_PREDIAL.CODIGO 
    AND IP_RECIBOS_DE_PAGO.NUMERO_ORDEN 	= IP_USUARIOS_PREDIAL.NUMERO_ORDEN
  INNER JOIN IP_TARIFAS 
    ON IP_USUARIOS_PREDIAL.COMPANIA 		= IP_TARIFAS.COMPANIA 
   AND IP_USUARIOS_PREDIAL.TRPCOD 		= IP_TARIFAS.TRPCOD 
   AND IP_USUARIOS_PREDIAL.TRPANO 		= IP_TARIFAS.TRPANO 
   AND IP_USUARIOS_PREDIAL.TRPRAN 		= IP_TARIFAS.TRPRAN 
  LEFT JOIN IP_BANCOS 
    ON  IP_RECIBOS_DE_PAGO.COMPANIA		= IP_BANCOS.COMPANIA
    AND IP_RECIBOS_DE_PAGO.PAG_BANPAG		= IP_BANCOS.CODIGOBANCO
WHERE IP_FACTURADOS.COMPANIA = s$compania$s
  AND IP_USUARIOS_PREDIAL.NUMERO_ORDEN=s$numeroOrden$s 
  AND IP_RECIBOS_DE_PAGO.PAGO NOT IN (0)  
  AND IP_RECIBOS_DE_PAGO.ANULADO IN(0) 
  AND IP_RECIBOS_DE_PAGO.PREFECPAG BETWEEN s$fechaInicial$s AND s$fechaFinal$s
GROUP BY  IP_RECIBOS_DE_PAGO.PAG_BANPAG,
          IP_BANCOS.NOMBREBANCO,
          IP_RECIBOS_DE_PAGO.PREFEC, 
          IP_FACTURADOS.DOCNUM, 
          IP_RECIBOS_DE_PAGO.PRECOD, 
          IP_RECIBOS_DE_PAGO.PREANOI,
          IP_USUARIOS_PREDIAL.VIGENCIA,
          IP_RECIBOS_DE_PAGO.PREANOF,
          IP_RECIBOS_DE_PAGO.PREFECPAG,
          IP_USUARIOS_PREDIAL.TRPCOD || ' - ' || IP_TARIFAS.TRPPOR,
          IP_USUARIOS_PREDIAL.AVALUO_ANO
UNION 
SELECT IP_RECIBOS_DE_PAGO.PAG_BANPAG,
       IP_BANCOS.NOMBREBANCO,
       IP_RECIBOS_DE_PAGO.PREFEC,
       IP_FACTURADOSABONOS.DOCNUM,
       IP_RECIBOS_DE_PAGO.PRECOD,
       MAX(CASE WHEN TO_CHAR(IP_RECIBOS_DE_PAGO.PREANOI) IS NULL 
              THEN TO_CHAR(IP_USUARIOS_PREDIAL.VIGENCIA)
              ELSE 
                CASE WHEN TO_CHAR(IP_RECIBOS_DE_PAGO.PREANOI)= TO_CHAR(IP_RECIBOS_DE_PAGO.PREANOF)
                THEN TO_CHAR(IP_USUARIOS_PREDIAL.VIGENCIA)
                ELSE TO_CHAR(IP_RECIBOS_DE_PAGO.PREANOI)
                END 
            END || ' ' || TO_CHAR(IP_RECIBOS_DE_PAGO.PREANOF)) AS ANIOS,
       IP_RECIBOS_DE_PAGO.PREFECPAG,
       IP_USUARIOS_PREDIAL.TRPCOD ||' - ' || IP_TARIFAS.TRPPOR AS TARIFA, 
       IP_USUARIOS_PREDIAL.AVALUO_ANO,
       SUM(CASE WHEN IP_FACTURADOSABONOS.PREANO <= 2004 THEN IP_FACTURADOSABONOS.C1 ELSE ROUND(IP_FACTURADOSABONOS.C1*0.85,0)END)IMPUESTOPREDIAL,
       SUM(CASE WHEN IP_FACTURADOSABONOS.PREANO <= 2004 THEN IP_FACTURADOSABONOS.C2 ELSE ROUND(IP_FACTURADOSABONOS.C2*0.85,0)END) INTERESPREDIAL,
       SUM(CASE WHEN IP_FACTURADOSABONOS.PREANO <= 2004 THEN IP_FACTURADOSABONOS.C3 ELSE IP_FACTURADOSABONOS.C1 -ROUND(IP_FACTURADOSABONOS.C1*0.85,0)END)CAR,
       SUM(CASE WHEN IP_FACTURADOSABONOS.PREANO <= 2004 THEN IP_FACTURADOSABONOS.C3 ELSE IP_FACTURADOSABONOS.C2 -ROUND(IP_FACTURADOSABONOS.C2*0.85)END) INTERESCAR,
       SUM(CASE WHEN IP_FACTURADOSABONOS.PREANO <= 2004 THEN IP_FACTURADOSABONOS.C3 ELSE IP_FACTURADOSABONOS.C1 -ROUND(IP_FACTURADOSABONOS.C1*0.85,0)END)+
       SUM(CASE WHEN IP_FACTURADOSABONOS.PREANO <= 2004 THEN IP_FACTURADOSABONOS.C3 ELSE IP_FACTURADOSABONOS.C2 -ROUND(IP_FACTURADOSABONOS.C2*0.85)END) TOTALCAR
       
FROM IP_FACTURADOSABONOS
  INNER JOIN IP_RECIBOS_DE_PAGO
    ON IP_FACTURADOSABONOS.COMPANIA 		= IP_RECIBOS_DE_PAGO.COMPANIA
    AND IP_FACTURADOSABONOS.DOCNUM 		= IP_RECIBOS_DE_PAGO.DOCNUM  
    AND IP_FACTURADOSABONOS.CODIGO 		= IP_RECIBOS_DE_PAGO.PRECOD
    AND IP_FACTURADOSABONOS.PREANO  		= IP_RECIBOS_DE_PAGO.PREANO
  INNER JOIN IP_USUARIOS_PREDIAL 
    ON  IP_RECIBOS_DE_PAGO.COMPANIA 		= IP_USUARIOS_PREDIAL.COMPANIA 
    AND IP_RECIBOS_DE_PAGO.PRECOD 		= IP_USUARIOS_PREDIAL.CODIGO 
    AND IP_RECIBOS_DE_PAGO.NUMERO_ORDEN 	= IP_USUARIOS_PREDIAL.NUMERO_ORDEN
  INNER JOIN IP_TARIFAS
    ON IP_USUARIOS_PREDIAL.COMPANIA 		= IP_TARIFAS.COMPANIA 
   AND IP_USUARIOS_PREDIAL.TRPCOD 		= IP_TARIFAS.TRPCOD 
   AND IP_USUARIOS_PREDIAL.TRPANO 		= IP_TARIFAS.TRPANO 
   AND IP_USUARIOS_PREDIAL.TRPRAN 		= IP_TARIFAS.TRPRAN 
  LEFT JOIN IP_BANCOS
    ON  IP_RECIBOS_DE_PAGO.COMPANIA		= IP_BANCOS.COMPANIA
    AND IP_RECIBOS_DE_PAGO.PAG_BANPAG		= IP_BANCOS.CODIGOBANCO
WHERE IP_FACTURADOSABONOS.COMPANIA = s$compania$s 
  AND IP_USUARIOS_PREDIAL.NUMERO_ORDEN = s$numeroOrden$s  
  AND IP_RECIBOS_DE_PAGO.PAGO   NOT IN(0)
  AND IP_RECIBOS_DE_PAGO.ANULADO   IN(0)
  AND IP_RECIBOS_DE_PAGO.PREFECPAG BETWEEN s$fechaInicial$s AND s$fechaFinal$s
GROUP BY  IP_RECIBOS_DE_PAGO.PAG_BANPAG,
          IP_BANCOS.NOMBREBANCO,
          IP_RECIBOS_DE_PAGO.PREFEC,
          IP_FACTURADOSABONOS.DOCNUM,
          IP_RECIBOS_DE_PAGO.PRECOD,
          IP_RECIBOS_DE_PAGO.PREANOI,
          IP_RECIBOS_DE_PAGO.PREANOF,
          IP_USUARIOS_PREDIAL.VIGENCIA,
          IP_RECIBOS_DE_PAGO.PREFECPAG,
          IP_USUARIOS_PREDIAL.TRPCOD || ' - ' ||  IP_TARIFAS.TRPPOR,
          IP_USUARIOS_PREDIAL.AVALUO_ANO
UNION 
SELECT  IP_RECIBOS_DE_PAGO.PAG_BANPAG,
        IP_BANCOS.NOMBREBANCO,
        IP_RECIBOS_DE_PAGO.PREFEC,
        IP_FACTURADOSACUERDOS.DOCNUM,
        IP_RECIBOS_DE_PAGO.PRECOD,
        MAX(CASE WHEN TO_CHAR(IP_RECIBOS_DE_PAGO.PREANOI) IS NULL 
              THEN TO_CHAR(IP_USUARIOS_PREDIAL.VIGENCIA)
              ELSE 
                CASE WHEN TO_CHAR(IP_RECIBOS_DE_PAGO.PREANOI)=TO_CHAR(IP_RECIBOS_DE_PAGO.PREANOF)
                THEN TO_CHAR(IP_USUARIOS_PREDIAL.VIGENCIA)
                ELSE TO_CHAR(IP_RECIBOS_DE_PAGO.PREANOI)
                END 
              END || ' ' || TO_CHAR(IP_RECIBOS_DE_PAGO.PREANOF)) AS ANIOS,
         IP_RECIBOS_DE_PAGO.PREFECPAG,
         IP_USUARIOS_PREDIAL.TRPCOD || ' - ' || IP_TARIFAS.TRPPOR AS TARIFA,
         IP_USUARIOS_PREDIAL.AVALUO_ANO,
         SUM(CASE WHEN IP_FACTURADOSACUERDOS.PREANO <= 2004 THEN IP_FACTURADOSACUERDOS.C1 ELSE ROUND(IP_FACTURADOSACUERDOS.C1*0.85,0)END)IMPUESTOPREDIAL,
         SUM(CASE WHEN IP_FACTURADOSACUERDOS.PREANO <= 2004 THEN IP_FACTURADOSACUERDOS.C2 ELSE ROUND(IP_FACTURADOSACUERDOS.C2*0.85,0)END)INTERESPREDIAL, 
         SUM(CASE WHEN IP_FACTURADOSACUERDOS.PREANO <= 2004 THEN IP_FACTURADOSACUERDOS.C3 ELSE IP_FACTURADOSACUERDOS.C1 -ROUND(IP_FACTURADOSACUERDOS.C1*0.85,0)END)CAR,
         SUM(CASE WHEN IP_FACTURADOSACUERDOS.PREANO <= 2004 THEN IP_FACTURADOSACUERDOS.C3 ELSE IP_FACTURADOSACUERDOS.C2 -ROUND(IP_FACTURADOSACUERDOS.C2*0.85)END)INTERESCAR,
         SUM(CASE WHEN IP_FACTURADOSACUERDOS.PREANO <= 2004 THEN IP_FACTURADOSACUERDOS.C3 ELSE IP_FACTURADOSACUERDOS.C1 -ROUND(IP_FACTURADOSACUERDOS.C1*0.85,0)END)+
         SUM(CASE WHEN IP_FACTURADOSACUERDOS.PREANO <= 2004 THEN IP_FACTURADOSACUERDOS.C3 ELSE IP_FACTURADOSACUERDOS.C2 -ROUND(IP_FACTURADOSACUERDOS.C2*0.85)END)TOTALCAR
FROM IP_FACTURADOSACUERDOS
  INNER JOIN IP_RECIBOS_DE_PAGO
    ON  IP_FACTURADOSACUERDOS.COMPANIA  	= IP_RECIBOS_DE_PAGO.COMPANIA 
    AND IP_FACTURADOSACUERDOS.DOCNUM    	= IP_RECIBOS_DE_PAGO.DOCNUM 
    AND IP_FACTURADOSACUERDOS.PREDIO    	= IP_RECIBOS_DE_PAGO.PRECOD
    AND IP_FACTURADOSACUERDOS.PREANO    	= IP_RECIBOS_DE_PAGO.PREANO
  INNER JOIN IP_USUARIOS_PREDIAL
   ON  IP_RECIBOS_DE_PAGO.COMPANIA 		= IP_USUARIOS_PREDIAL.COMPANIA 
   AND IP_RECIBOS_DE_PAGO.PRECOD 		= IP_USUARIOS_PREDIAL.CODIGO 
   AND IP_RECIBOS_DE_PAGO.NUMERO_ORDEN 		= IP_USUARIOS_PREDIAL.NUMERO_ORDEN
  INNER JOIN IP_TARIFAS
     ON IP_USUARIOS_PREDIAL.COMPANIA 		= IP_TARIFAS.COMPANIA 
   AND IP_USUARIOS_PREDIAL.TRPCOD 		= IP_TARIFAS.TRPCOD 
   AND IP_USUARIOS_PREDIAL.TRPANO 		= IP_TARIFAS.TRPANO 
   AND IP_USUARIOS_PREDIAL.TRPRAN 		= IP_TARIFAS.TRPRAN 
  LEFT JOIN IP_BANCOS
    ON  IP_RECIBOS_DE_PAGO.COMPANIA		= IP_BANCOS.COMPANIA
    AND IP_RECIBOS_DE_PAGO.PAG_BANPAG		= IP_BANCOS.CODIGOBANCO
WHERE IP_FACTURADOSACUERDOS.COMPANIA = s$compania$s
  AND IP_USUARIOS_PREDIAL.NUMERO_ORDEN =s$numeroOrden$s  
  AND IP_RECIBOS_DE_PAGO.PAGO NOT IN(0)
  AND IP_RECIBOS_DE_PAGO.ANULADO IN(0)
  AND IP_RECIBOS_DE_PAGO.PREFECPAG BETWEEN s$fechaInicial$s AND s$fechaFinal$s
GROUP BY  IP_RECIBOS_DE_PAGO.PAG_BANPAG,
          IP_BANCOS.NOMBREBANCO,
          IP_RECIBOS_DE_PAGO.PREFEC,
          IP_FACTURADOSACUERDOS.DOCNUM,
          IP_RECIBOS_DE_PAGO.PRECOD,
          IP_RECIBOS_DE_PAGO.PREANOI,
          IP_RECIBOS_DE_PAGO.PREANOF,
          IP_USUARIOS_PREDIAL.VIGENCIA,
          IP_RECIBOS_DE_PAGO.PREFECPAG,
          IP_USUARIOS_PREDIAL.TRPCOD ||' - ' || IP_TARIFAS.TRPPOR,
          IP_USUARIOS_PREDIAL.AVALUO_ANO
