SELECT NUMCER, 
       PREDIO CODIGOPREDIO,
       NOMBRE,
       VALOR 
FROM IP_CERTIFICADOVALORIZACION
WHERE COMPANIA     = s$compania$s
   AND ANULADO      NOT IN (0)
  AND TRUNC(FECHA_ANULADO) BETWEEN TO_DATE('s$fechaInicial$s','DD/MM/YYYY') AND TO_DATE('s$fechaFinal$s','DD/MM/YYYY')
