SELECT SUBSTR(IP_USUARIOS_PREDIAL.CODIGO,1,2) || ' ' || SUBSTR (IP_USUARIOS_PREDIAL.CODIGO,3,2) || ' ' || 
       SUBSTR(IP_USUARIOS_PREDIAL.CODIGO,5,4) || ' ' || SUBSTR (IP_USUARIOS_PREDIAL.CODIGO,9,4) || ' ' || 
       SUBSTR(IP_USUARIOS_PREDIAL.CODIGO,13,3) AS CODIGOPREDIO, 
       IP_USUARIOS_PREDIAL.NOMBRE, 
       IP_USUARIOS_PREDIAL.DIRECCION, 
       IP_USUARIOS_PREDIAL.AVALUO_ANO, 
       IP_USUARIOS_PREDIAL.AREA_HA, 
       IP_USUARIOS_PREDIAL.AREA_M2, 
       IP_USUARIOS_PREDIAL.AREA_CONSTRUIDA, 
       IP_USUARIOS_PREDIAL.NIT, 
       IP_USUARIOS_PREDIAL.PAGO_ANO,
       CASE WHEN IP_USUARIOS_PREDIAL.INDCAR = 0 THEN  'N' ELSE 'S' END AS INDICAR,
       CASE WHEN IP_USUARIOS_PREDIAL.INDEXE = 0 THEN  'N' ELSE 'S' END  AS INDIEXE
FROM IP_USUARIOS_PREDIAL 
WHERE IP_USUARIOS_PREDIAL.COMPANIA = s$compania$s
  AND IP_USUARIOS_PREDIAL.CODIGO BETWEEN s$codigoInicial$s  AND  s$codigoFinal$s 
  AND IP_USUARIOS_PREDIAL.NUMERO_ORDEN = s$numeroOrden$s 
  AND IP_USUARIOS_PREDIAL.AVALUO_ANO BETWEEN s$avaluoInicial$s AND s$avaluoFinal$s
  AND IP_USUARIOS_PREDIAL.INDBORRADO = 0 
  AND IP_USUARIOS_PREDIAL.CODIGO_NO_ACTIVO = 0
  s$condicion$s
