SELECT IP_RECIBOS_DE_PAGO.PREFECPAG,
    MIN(IP_RECIBOS_DE_PAGO.DOCNUM) AS PRIMERDOCNUM,
    MAX(IP_RECIBOS_DE_PAGO.DOCNUM) AS ULTIMODOCNUM,
    SUM(CASE 
        WHEN (IP_RECIBOS_DE_PAGO.PREANO NOT IN TO_CHAR(PREFECPAG,'YYYY')) 
        THEN 0 
        ELSE 
        (IP_RECIBOS_DE_PAGO.C1 + IP_RECIBOS_DE_PAGO.C3 + IP_RECIBOS_DE_PAGO.C13 + 
        IP_RECIBOS_DE_PAGO.C14 + IP_RECIBOS_DE_PAGO.C15 + IP_RECIBOS_DE_PAGO.C16 + 
        IP_RECIBOS_DE_PAGO.C17 + IP_RECIBOS_DE_PAGO.C18 + IP_RECIBOS_DE_PAGO.C19 + IP_RECIBOS_DE_PAGO.C20) 
	END) AS VIGENCIAACTUAL,
    SUM(CASE 
        WHEN (IP_RECIBOS_DE_PAGO.PREANO NOT IN TO_CHAR(PREFECPAG,'YYYY')) 
        THEN (IP_RECIBOS_DE_PAGO.C1 + IP_RECIBOS_DE_PAGO.C3 + IP_RECIBOS_DE_PAGO.C13 + 
        IP_RECIBOS_DE_PAGO.C14 + IP_RECIBOS_DE_PAGO.C15 + IP_RECIBOS_DE_PAGO.C16 + 
        IP_RECIBOS_DE_PAGO.C17 + IP_RECIBOS_DE_PAGO.C18 + IP_RECIBOS_DE_PAGO.C19 + IP_RECIBOS_DE_PAGO.C20) 
        ELSE 0 
        END)AS VIGENCIAEXPIRADA,  
    SUM(IP_RECIBOS_DE_PAGO.C2 + IP_RECIBOS_DE_PAGO.C4) AS INTERESES,
    SUM(IP_RECIBOS_DE_PAGO.INTERES_ACUERDO) AS I_ACUERDO, 
    SUM(IP_RECIBOS_DE_PAGO.INTERES_RECARGO) AS I_RECARGO,
    SUM(IP_RECIBOS_DE_PAGO.PREVAL) AS SUMADETOTAL,
    IP_RECIBOS_DE_PAGO.ANULADO
,
    1 AS AGRUPADOREPORTE
FROM IP_RECIBOS_DE_PAGO
WHERE IP_RECIBOS_DE_PAGO.COMPANIA = s$compania$s 
    AND TRUNC(IP_RECIBOS_DE_PAGO.PREFECPAG) BETWEEN s$fechaInicial$s AND s$fechaFinal$s
    AND IP_RECIBOS_DE_PAGO.PAGO <> 0
GROUP BY IP_RECIBOS_DE_PAGO.PREFECPAG,
    IP_RECIBOS_DE_PAGO.ANULADO
