SELECT IP_ACUERDOS.CODIGOACUERDO, 
       IP_ACUERDOS.NCUOTAS,
       IP_ACUERDOS.PREDIO,
       IP_USUARIOS_PREDIAL.DIRECCION_CORRESPONDENCIA,
       IP_USUARIOS_PREDIAL.NOMBRE,
       IP_USUARIOS_PREDIAL.DIRECCION,
       IP_FACTURADOSACUERDOS.CUOTA,
       IP_FACTURADOSACUERDOS.PREANOI,
       IP_FACTURADOSACUERDOS.PREANO,
       (IP_FACTURADOSACUERDOS.C1  + IP_FACTURADOSACUERDOS.C3 + IP_FACTURADOSACUERDOS.C5 + IP_FACTURADOSACUERDOS.C7 + IP_FACTURADOSACUERDOS.C9 + IP_FACTURADOSACUERDOS.C11) IMP,
       (IP_FACTURADOSACUERDOS.C2  + IP_FACTURADOSACUERDOS.C4 + IP_FACTURADOSACUERDOS.C6 + IP_FACTURADOSACUERDOS.C8 + IP_FACTURADOSACUERDOS.C10 + IP_FACTURADOSACUERDOS.C12) INT,
       IP_FACTURADOSACUERDOS.C13,
       (IP_FACTURADOSACUERDOS.C14 + IP_FACTURADOSACUERDOS.C15 + IP_FACTURADOSACUERDOS.C16 + IP_FACTURADOSACUERDOS.C17 + IP_FACTURADOSACUERDOS.C18 + IP_FACTURADOSACUERDOS.C19 + IP_FACTURADOSACUERDOS.C20) ALUM,
       IP_FACTURADOSACUERDOS.INTERES_ACUERDO,
       IP_FACTURADOSACUERDOS.INTERES_RECARGO,
       IP_FACTURADOSACUERDOS.TOTAL,
       IP_USUARIOS_PREDIAL.NUMERO_ORDEN  
FROM IP_ACUERDOS
INNER JOIN IP_FACTURADOSACUERDOS
ON    IP_ACUERDOS.COMPANIA           = IP_FACTURADOSACUERDOS.COMPANIA
AND   IP_ACUERDOS.CODIGOACUERDO      = IP_FACTURADOSACUERDOS.CODIGOACUERDO
AND   IP_ACUERDOS.PREDIO             = IP_FACTURADOSACUERDOS.PREDIO
AND   IP_ACUERDOS.NUMERO_ORDEN       = IP_FACTURADOSACUERDOS.NUMERO_ORDEN
INNER JOIN IP_USUARIOS_PREDIAL
ON    IP_ACUERDOS.COMPANIA           = IP_USUARIOS_PREDIAL.COMPANIA
AND   IP_ACUERDOS.PREDIO             = IP_USUARIOS_PREDIAL.CODIGO
AND   IP_ACUERDOS.NUMERO_ORDEN       = IP_USUARIOS_PREDIAL.NUMERO_ORDEN
WHERE IP_ACUERDOS.COMPANIA = s$compania$s
AND IP_ACUERDOS.PREDIO BETWEEN 's$codigoInicial$s' AND 's$codigoFinal$s'
AND IP_FACTURADOSACUERDOS.TOTAL NOT IN(0)
AND IP_ACUERDOS.CANCELADO             =0
AND IP_FACTURADOSACUERDOS.PAGADO      =0
AND IP_USUARIOS_PREDIAL.NUMERO_ORDEN  =s$numeroOrden$s
AND IP_ACUERDOS.ANULADO               =0
AND IP_USUARIOS_PREDIAL.INDBORRADO    =0
AND IP_USUARIOS_PREDIAL.CODIGO_NO_ACTIVO =0
ORDER BY IP_FACTURADOSACUERDOS.CUOTA DESC
