SELECT U.CODIGO,
  U.NOMBRE, 
  U.DIRECCION,
  SUM(F.C1) AS ANOACTUAL,
  SUM(F.C2) INTPREDIAL,
  SUM(F.C3) CAR,
  SUM(F.C4) INTCAR,
  SUM(F.C13) DESCUENTO,
  SUM(F.C14) SUMADEC14,
  SUM(F.C15) SUMADEC15,
  SUM(F.C16) SUMADEC16,
  SUM(F.C17) SUMADEC17,
  SUM(F.C18) SUMADEC18,
  SUM(F.C19) SUMADEC19,
  SUM(F.C20) SUMADEC20,
  SUM(F.TOTAL) SUMADETOTAL,
  U.PAGO_ANO,
  F.PREANO
FROM IP_USUARIOS_PREDIAL U INNER JOIN IP_FACTURADOS F
ON (U.NUMERO_ORDEN = F.NUMERO_ORDEN) AND (U.CODIGO = F.CODIGO)
WHERE 
U.NUMERO_ORDEN='001'
AND F.PAGADO = 0
AND F.TOTAL NOT IN (0)
AND F.NOCOBRADO = 0
AND F.INDCAR = 0
AND F.INDEXE = 0
AND F.INDPAGO_ACPAG=0
AND F.INDEXEOTROS=0
AND F.INDPAGO_CUOTAS=0
AND F.AREA_CONSTRUIDA >= s$areaConst$s
AND U.CODIGO BETWEEN 's$codigoInicial$s' AND 's$codigoFinal$s'
AND F.PREANO BETWEEN s$anoIni$s AND s$anoFin$s
s$strIncluye$s
GROUP BY U.CODIGO,
  U.NOMBRE,
  U.DIRECCION,
  U.PAGO_ANO,
  F.PREANO  
HAVING SUM(F.TOTAL) BETWEEN s$valorInicial$s AND s$valorFinal$s
ORDER BY U.CODIGO,F.PREANO 
