SELECT DISTINCT RP.ACUERDO, 
  UP.CODIGO, 
  UP.NIT,
  UP.AREA_HA,
  UP.AREA_M2,
  UP.AREA_CONSTRUIDA,
  RP.NCUOTA_ACUERDO,
  RP.C1+RP.C5+RP.C9  AS IMP,
  RP.C2+RP.C6+RP.C10 AS INT,
  RP.C3+RP.C7+RP.C11 AS CAR,
  RP.C4+RP.C8+RP.C12 AS INTCAR,
  RP.C13,
  RP.C14,
  RP.C15,
  RP.C16,
  RP.C17,
  RP.C18,
  RP.C19,
  RP.C20,
  RP.PREVAL,
  UP.NOMBRE,
  UP.DIRECCION,
  RP.DOCNUM,
  RP.PREFECLIM,
  RP.FECHAFACACUERDO,
  RP.INTERES_ACUERDO AS INTA,
  RP.INTERES_RECARGO AS INTR,
  RP.PREANO AS ANOFIN,
  RP.PREANOI AS ANOINI,
  UP.DIRECCION_CORRESPONDENCIA,
  UP.NUMERO_ORDEN,
  UP.TRPCOD,
  UP.ESTRATO_SOCIOECONOMICO,
  UP.NUM_COM,
  RP.INTERES_ACUERDO + RP.INTERES_RECARGO AS INTERESACUERDO,
  UP.AVALUO_ANO, 
  RP.C1+RP.C5+RP.C9 + RP.C3+RP.C7+RP.C11 AS IMPUESTO,
  RP.C2+RP.C6+RP.C10 + RP.C4+RP.C8+RP.C12 AS INTERES,
  RP.C16+RP.C17+RP.C18+RP.C19 AS TEXTO377
FROM IP_USUARIOS_PREDIAL UP
INNER JOIN IP_RECIBOS_DE_PAGO RP
ON UP.COMPANIA         = RP.COMPANIA
AND UP.CODIGO           = RP.PRECOD
AND UP.NUMERO_ORDEN       = RP.NUMERO_ORDEN
INNER JOIN IP_DETALLE_RECIBOPAGO DR
ON RP.COMPANIA           = DR.COMPANIA
AND RP.DOCNUM            = DR.DOCNUM
WHERE UP.COMPANIA           = s$compania$s
     AND UP.CODIGO               = $P!{PR_CODIGO}  
     AND UP.NUMERO_ORDEN = $P!{PR_NUMERO_ORDEN}
     AND RP.DOCNUM 	     = s$docnum$s
