SELECT   
         RECIBOS_DE_PAGO.DOCNUM
		,RECIBOS_DE_PAGO.PRECOD
		,RECIBOS_DE_PAGO.PREFECPAG
		,NULL FECHAANULACION
		,USUARIOS_PREDIAL.NOMBRE
		,RECIBOS_DE_PAGO.PREANO
		,RECIBOS_DE_PAGO.PREVAL
		,RECIBOS_DE_PAGO.C1
		,RECIBOS_DE_PAGO.C2
		,RECIBOS_DE_PAGO.C3
		,RECIBOS_DE_PAGO.C4
		,RECIBOS_DE_PAGO.C5
		,RECIBOS_DE_PAGO.C6
		,RECIBOS_DE_PAGO.C7
		,RECIBOS_DE_PAGO.C8
		,RECIBOS_DE_PAGO.C9
		,RECIBOS_DE_PAGO.C10
		,RECIBOS_DE_PAGO.C11
		,RECIBOS_DE_PAGO.C12
		,RECIBOS_DE_PAGO.C13
		,RECIBOS_DE_PAGO.C14
		,RECIBOS_DE_PAGO.C15
		,RECIBOS_DE_PAGO.C16
		,RECIBOS_DE_PAGO.C17
		,RECIBOS_DE_PAGO.C18
		,RECIBOS_DE_PAGO.C19
		,RECIBOS_DE_PAGO.C20
		,PCK_PREDIAL_COM4.FC_NOMBRE_CONCEPTO_PREDIAL(
			              UN_COMPANIA => RECIBOS_DE_PAGO.COMPANIA
			             ,UN_CODIGO   => 13
			             ,UN_ANIO     => EXTRACT(YEAR FROM s$fechaInicial$s)) NOMBRECONCEPTO13
		,PCK_PREDIAL_COM4.FC_NOMBRE_CONCEPTO_PREDIAL(
			              UN_COMPANIA => RECIBOS_DE_PAGO.COMPANIA
			             ,UN_CODIGO   => 14
			             ,UN_ANIO     => EXTRACT(YEAR FROM s$fechaInicial$s)) NOMBRECONCEPTO14
		,PCK_PREDIAL_COM4.FC_NOMBRE_CONCEPTO_PREDIAL(
			              UN_COMPANIA => RECIBOS_DE_PAGO.COMPANIA
			             ,UN_CODIGO   => 15
			             ,UN_ANIO     => EXTRACT(YEAR FROM s$fechaInicial$s)) NOMBRECONCEPTO15
		,PCK_PREDIAL_COM4.FC_NOMBRE_CONCEPTO_PREDIAL(
			              UN_COMPANIA => RECIBOS_DE_PAGO.COMPANIA
			             ,UN_CODIGO   => 16
			             ,UN_ANIO     => EXTRACT(YEAR FROM s$fechaInicial$s)) NOMBRECONCEPTO16
		,PCK_PREDIAL_COM4.FC_NOMBRE_CONCEPTO_PREDIAL(
			              UN_COMPANIA => RECIBOS_DE_PAGO.COMPANIA
			             ,UN_CODIGO   => 17
			             ,UN_ANIO     => EXTRACT(YEAR FROM s$fechaInicial$s)) NOMBRECONCEPTO17
		,PCK_PREDIAL_COM4.FC_NOMBRE_CONCEPTO_PREDIAL(
			              UN_COMPANIA => RECIBOS_DE_PAGO.COMPANIA
			             ,UN_CODIGO   => 18
			             ,UN_ANIO     => EXTRACT(YEAR FROM s$fechaInicial$s)) NOMBRECONCEPTO18
		,PCK_PREDIAL_COM4.FC_NOMBRE_CONCEPTO_PREDIAL(
			              UN_COMPANIA => RECIBOS_DE_PAGO.COMPANIA
			             ,UN_CODIGO   => 19
			             ,UN_ANIO     => EXTRACT(YEAR FROM s$fechaInicial$s)) NOMBRECONCEPTO19
		,PCK_PREDIAL_COM4.FC_NOMBRE_CONCEPTO_PREDIAL(
			              UN_COMPANIA => RECIBOS_DE_PAGO.COMPANIA
			             ,UN_CODIGO   => 20
			             ,UN_ANIO     => EXTRACT(YEAR FROM s$fechaInicial$s)) NOMBRECONCEPTO20
		, RECIBOS_DE_PAGO.C1+RECIBOS_DE_PAGO.C2
		 +RECIBOS_DE_PAGO.C3+RECIBOS_DE_PAGO.C4
		 +RECIBOS_DE_PAGO.C13+RECIBOS_DE_PAGO.C14
		 +RECIBOS_DE_PAGO.C15+RECIBOS_DE_PAGO.C16
		 +RECIBOS_DE_PAGO.C17+RECIBOS_DE_PAGO.C18
		 +RECIBOS_DE_PAGO.C19+RECIBOS_DE_PAGO.C20 TOTALPAGO
		,RECIBOS_DE_PAGO.PAG_BANPAG
		,NVL(RECIBOS_DE_PAGO.INTERES_ACUERDO,0) I_ACUERDO
		,NVL(RECIBOS_DE_PAGO.INTERES_RECARGO,0) I_RECARGO
		,RECIBOS_DE_PAGO.PAG_BANPAG
                                          ,BANCOS.NOMBREBANCO       
   FROM IP_RECIBOS_DE_PAGO RECIBOS_DE_PAGO 
   		INNER JOIN IP_USUARIOS_PREDIAL USUARIOS_PREDIAL 
   			ON  RECIBOS_DE_PAGO.COMPANIA     = USUARIOS_PREDIAL.COMPANIA
			AND RECIBOS_DE_PAGO.PRECOD       = USUARIOS_PREDIAL.CODIGO
			AND RECIBOS_DE_PAGO.NUMERO_ORDEN = USUARIOS_PREDIAL.NUMERO_ORDEN
 
    INNER JOIN IP_BANCOS BANCOS 
	    ON  RECIBOS_DE_PAGO.COMPANIA     = BANCOS.COMPANIA 
	    AND RECIBOS_DE_PAGO.PAG_BANPAG   = BANCOS.CODIGOBANCO

  WHERE USUARIOS_PREDIAL.COMPANIA     = s$compania$s  
    AND USUARIOS_PREDIAL.NUMERO_ORDEN = 's$numeroOrden$s'  
    AND RECIBOS_DE_PAGO.PREFECPAG     BETWEEN s$fechaInicial$s AND s$fechaFinal$s
    AND RECIBOS_DE_PAGO.PAG_BANPAG    BETWEEN NVL(s$bancoInicial$s,'000') AND NVL(s$bancoFinal$s,'999') 
    AND RECIBOS_DE_PAGO.PAGO          NOT IN (0)
    AND RECIBOS_DE_PAGO.ANULADO       IN (0)
