SELECT IP_RECIBOS_DE_PAGO.DOCNUM,
  IP_RECIBOS_DE_PAGO.PRECOD,
  IP_RECIBOS_DE_PAGO.PREFECPAG,
  IP_RECIBOS_DE_PAGO.C1 AS IMP_ACTUAL,
  C5+C9 AS IMP_ANT,
  C2+C6+C10+INTERES_ACUERDO+INTERES_RECARGO AS INTER,
  (C1+C5+C9+C13+C17) * 0.15 AS CAR_CAP,
  (C1+C13+C5+C9+C2+C6+C10+C17+INTERES_ACUERDO+INTERES_RECARGO) * 0.15 AS CAR_CAPINT,
  IP_RECIBOS_DE_PAGO.PAG_BANPAG,
  IP_RECIBOS_DE_PAGO.PREANOI,
  IP_RECIBOS_DE_PAGO.PREANO,
  IP_RECIBOS_DE_PAGO.C13,
  IP_RECIBOS_DE_PAGO.ANULADO,
  IP_RECIBOS_DE_PAGO.PAGO
FROM IP_RECIBOS_DE_PAGO
WHERE TRUNC(IP_RECIBOS_DE_PAGO.PREFECPAG) BETWEEN s$fechaInicial$s AND s$fechaFinal$s
AND IP_RECIBOS_DE_PAGO.PAG_BANPAG BETWEEN s$bancoInicial$s AND s$bancoFinal$s
AND IP_RECIBOS_DE_PAGO.ANULADO = 0
AND IP_RECIBOS_DE_PAGO.PAGO  <> 0
ORDER BY IP_RECIBOS_DE_PAGO.DOCNUM
