SELECT  s$titulo$s AS TIPO_PREDIO, 
        IP_RECIBOS_DE_PAGO.PREANOI || '-' || IP_RECIBOS_DE_PAGO.PREANOF AS ANO_PAGO,  
        SUM(IP_RECIBOS_DE_PAGO.C1) "s$totalC1$s",  
        SUM(IP_RECIBOS_DE_PAGO.C2)  "s$totalC2$s",  
        SUM(IP_RECIBOS_DE_PAGO.C3)  "s$totalC3$s",  
        SUM(IP_RECIBOS_DE_PAGO.C4)  "s$totalC4$s",  
        SUM(IP_RECIBOS_DE_PAGO.C5 + IP_RECIBOS_DE_PAGO.C9) "s$totalC5$s",  
        SUM(IP_RECIBOS_DE_PAGO.C6 + IP_RECIBOS_DE_PAGO.C10) "s$totalC6$s",  
        SUM(IP_RECIBOS_DE_PAGO.C7+ IP_RECIBOS_DE_PAGO.C11)  "s$totalC7$s",  
        SUM(IP_RECIBOS_DE_PAGO.C8+ IP_RECIBOS_DE_PAGO.C12)  "s$totalC8$s", 
s$camposAdicionales$s 
        SUM(IP_RECIBOS_DE_PAGO.PREVAL) AS ULTIMO_PAGO 
FROM IP_USUARIOS_PREDIAL    
  INNER JOIN IP_RECIBOS_DE_PAGO  
    ON IP_USUARIOS_PREDIAL.COMPANIA       = IP_RECIBOS_DE_PAGO.COMPANIA 
    AND IP_USUARIOS_PREDIAL.CODIGO        = IP_RECIBOS_DE_PAGO.PRECOD 
    AND IP_USUARIOS_PREDIAL.NUMERO_ORDEN  = IP_RECIBOS_DE_PAGO.NUMERO_ORDEN 
    AND IP_USUARIOS_PREDIAL.NUM_COM       = IP_RECIBOS_DE_PAGO.DOCNUM  
WHERE IP_USUARIOS_PREDIAL.COMPANIA        = s$compania$s 
  s$condicion$s 
  AND IP_RECIBOS_DE_PAGO.PAGO NOT IN (0) 
  AND SUBSTR(IP_USUARIOS_PREDIAL.CODIGO, 1 , 2)  IN (s$condTipoPred$s)
GROUP BY  IP_RECIBOS_DE_PAGO.PREANOI || '-' || IP_RECIBOS_DE_PAGO.PREANOF 
s$union$s
