/*
 * ConceptosNoFacturadosControladorUrlEnum
 *
 * 1.0
 *
 * 09/09/2016
 *
 * Copyright Stefanini Sysman
 */
package com.sysman.facturaciongeneral.enums;

/**
 * @author Processors-api
 * 
 * @version 1.0
 * 
 *          Enumeracion que permite clasificar cada uno de los identificadores
 *          geenerados en el refactoring y asociados al codigo legacy obtenido
 *          con patrones de busqueda.
 */
public enum ConceptosNoFacturadosControladorUrlEnum {

	URL001("CONCEPTOSNOFACTURADOSCONTROLADORURL001", "675001"),

	URL002("CONCEPTOSNOFACTURADOSCONTROLADORURL002", "663021"),

	URL003("CONCEPTOSNOFACTURADOSCONTROLADORURL003", "675002"),

	URL004("CONCEPTOSNOFACTURADOSCONTROLADORURL004", "16121"),

	URL005("CONCEPTOSNOFACTURADOSCONTROLADORURL005", "677002"),

	URL006("CONCEPTOSNOFACTURADOSCONTROLADORURL006", "675003"),

	URL15069("CONCEPTOSNOFACTURADOSCONTROLADORURL15069", "15069"),

	URL27145("CONCEPTOSNOFACTURADOSCONTROLADORURL27145",
			" listaContratoAfectar = new RegistroDataModel( ConectorPool.ESQUEMA_SYSMAN, \":FR1467_nuevo:TBCB4814\", \"SELECT NUMERO CONTRATO,\" + \" SF_CONTRATOS.FECHA_INICIO,\" + \" SF_CONTRATOS.FECHA_FINALIZACION,\" + \" SF_CONTRATOS.TERCERO,\" + \" SF_CONTRATOS.VALOR_TOTAL,\" + \" SF_CONTRATOS.OBJETO_CONTRATO,\" + \" SF_CONTRATOS.TIPO,\" + \" TO_CHAR(SF_CONTRATOS.NUMERO) NUMERO,\" + \" SF_CONTRATOS.ESTADO,\" + \" SF_CONTRATOS.ANO, \" + \" SF_CONTRATOS.SUCURSAL,\" + \" SF_CONTRATOS.CENTRO_COSTO,\" + \" SF_CONTRATOS.AUXILIAR,\" + \" CENTRO_COSTO.NOMBRE NOMBRE_CENTRO_COSTO,\" + \" AUXILIAR.NOMBRE NOMBREAUXILIAR,\" + \" TERCERO.NOMBRE NOMBRE_TERCERO,\" + \" TERCERO.DIRECCION,\" + \" TERCERO.TELEFONOS,\" + \" TERCERO.CODIGOPOSTAL\" + \" FROM SF_CONTRATOS\" + \" LEFT JOIN CENTRO_COSTO\" + \" ON SF_CONTRATOS.COMPANIA = CENTRO_COSTO.COMPANIA\" + \" AND SF_CONTRATOS.CENTRO_COSTO = CENTRO_COSTO.CODIGO\" + \" AND SF_CONTRATOS.ANO = CENTRO_COSTO.ANO\" + \" LEFT JOIN AUXILIAR\" + \" ON SF_CONTRATOS.COMPANIA = AUXILIAR.COMPANIA\" + \" AND SF_CONTRATOS.ANO = AUXILIAR.ANO\" + \" AND SF_CONTRATOS.AUXILIAR = AUXILIAR.CODIGO\" + \" LEFT JOIN TERCERO\" + \" ON SF_CONTRATOS.COMPANIA = TERCERO.COMPANIA\" + \" AND SF_CONTRATOS.TERCERO = TERCERO.NIT\" + \" AND SF_CONTRATOS.SUCURSAL = TERCERO.SUCURSAL\" + \" WHERE SF_CONTRATOS.COMPANIA = '\" + compania + \"' \" + \" AND SF_CONTRATOS.ESTADO = 2\","),

	URL14101("CONCEPTOSNOFACTURADOSCONTROLADORURL14101", "662005"),

	URL29788("CONCEPTOSNOFACTURADOSCONTROLADORURL29788", "15057"),

	URL25342("CONCEPTOSNOFACTURADOSCONTROLADORURL25342", "20059"),

	URL15077("CONCEPTOSNOFACTURADOSCONTROLADORURL15077", "663019"),

	URL13109("CONCEPTOSNOFACTURADOSCONTROLADORURL13109",
			" listaAuxiliarConcepto = new RegistroDataModel( ConectorPool.ESQUEMA_SYSMAN, \":FR1467_nuevo:TBCB4815\", \"SELECT \" + \" AUXILIAR.CODIGO, \" + \" AUXILIAR.NOMBRE, \" + \" AUXILIAR.MOVIMIENTO \" + \" FROM \" + \" AUXILIAR \" + \" WHERE \" + \" AUXILIAR.COMPANIA = '\" + compania + \"' \" + \" AND \" + \" AUXILIAR.ANO = \" + anio + \" \" + \" AND \" + \" AUXILIAR.MOVIMIENTO <> 0\","),

	URL21618("CONCEPTOSNOFACTURADOSCONTROLADORURL21618",
			" listaTerceroConceptoE = new RegistroDataModel( ConectorPool.ESQUEMA_SYSMAN, \":FR1467_nuevo:TBCB4818\", \"SELECT \" + \" TERCERO.NIT, \" + \" TERCERO.NOMBRE, \" + \" TERCERO.SUCURSAL \" + \" FROM \" + \" TERCERO \" + \" WHERE \" + \" TERCERO.COMPANIA = '\" + compania + \"'\","),

	URL20867("CONCEPTOSNOFACTURADOSCONTROLADORURL20867",
			" listaTerceroConcepto = new RegistroDataModel( ConectorPool.ESQUEMA_SYSMAN, \":FR1467_nuevo:TBCB4818\", \"SELECT \" + \" TERCERO.NIT, \" + \" TERCERO.NOMBRE, \" + \" TERCERO.SUCURSAL \" + \" FROM \" + \" TERCERO \" + \" WHERE \" + \" TERCERO.COMPANIA = '\" + compania + \"'\","),

	URL24417("CONCEPTOSNOFACTURADOSCONTROLADORURL24417", "14128"),

	URL41719("CONCEPTOSNOFACTURADOSCONTROLADORURL41719",
			"Acciones.eliminar(ConectorPool.ESQUEMA_SYSMAN, \"SF_DETALLE_COBRO\","),

	URL17965("CONCEPTOSNOFACTURADOSCONTROLADORURL17965", "663019"),

	URL28509("CONCEPTOSNOFACTURADOSCONTROLADORURL28509", "663029"),

	URL22377("CONCEPTOSNOFACTURADOSCONTROLADORURL22377",
			" listaCentroCostoConcepto = new RegistroDataModel( ConectorPool.ESQUEMA_SYSMAN, \":FR1467_nuevo:TBCB4819\", \"SELECT \" + \" CENTRO_COSTO.CODIGO, \" + \" CENTRO_COSTO.NOMBRE, \" + \" CENTRO_COSTO.MOVIMIENTO \" + \" FROM \" + \" CENTRO_COSTO \" + \" WHERE \" + \" CENTRO_COSTO.COMPANIA = '\" + compania + \"' \" + \" AND \" + \" CENTRO_COSTO.ANO = \" + anio + \" \" + \" AND \" + \" CENTRO_COSTO.MOVIMIENTO <> 0\","),

	URL23406("CONCEPTOSNOFACTURADOSCONTROLADORURL23406",
			" listaCentroCostoConceptoE = new RegistroDataModel( ConectorPool.ESQUEMA_SYSMAN, \":FR1467_nuevo:TBCB4819\", \"SELECT \" + \" CENTRO_COSTO.CODIGO, \" + \" CENTRO_COSTO.NOMBRE, \" + \" CENTRO_COSTO.MOVIMIENTO \" + \" FROM \" + \" CENTRO_COSTO \" + \" WHERE \" + \" CENTRO_COSTO.COMPANIA = '\" + compania + \"' \" + \" AND \" + \" CENTRO_COSTO.ANO = \" + anio + \" \" + \" AND \" + \" CENTRO_COSTO.MOVIMIENTO <> 0\","),

	URL26250("CONCEPTOSNOFACTURADOSCONTROLADORURL26250", "23028"),

	URL11916("CONCEPTOSNOFACTURADOSCONTROLADORURL11916",
			" listaSubconceptosnofacturadosbg = service.getListado( ConectorPool.ESQUEMA_SYSMAN, \"SELECT SF_DETALLE_COBRO.COMPANIA,\" + \" SF_DETALLE_COBRO.ANO,\" + \" SF_DETALLE_COBRO.TIPOCOBRO,\" + \" SF_DETALLE_COBRO.CODIGO_COBRO,\" + \" SF_DETALLE_COBRO.CONCEPTO,\" + \" SF_CONCEPTOS.NOMBRE,\" + \" SF_DETALLE_COBRO.BASE_GRAVABLE,\" + \" SF_DETALLE_COBRO.CANTIDAD,\" + \" SF_DETALLE_COBRO.VALOR_UNITARIO,\" + \" SF_DETALLE_COBRO.VALOR_BASE,\" + \" SF_DETALLE_COBRO.VALOR_IVA,\" + \" SF_DETALLE_COBRO.VALOR_RETEFUENTE,\" + \" SF_DETALLE_COBRO.VALOR_DESCUENTO,\" + \" SF_DETALLE_COBRO.VALOR_ICA,\" + \" SF_DETALLE_COBRO.VALOR_NETO,\" + \" SF_DETALLE_COBRO.TERCERO,\" + \" SF_DETALLE_COBRO.CENTRO_COSTO,\" + \" SF_DETALLE_COBRO.AUXILIAR\" + \" FROM SF_DETALLE_COBRO \" + \" INNER JOIN SF_CONCEPTOS \" + \" ON SF_DETALLE_COBRO.COMPANIA = SF_CONCEPTOS.COMPANIA \" + \" AND SF_DETALLE_COBRO.ANO = SF_CONCEPTOS.ANO \" + \" AND SF_DETALLE_COBRO.TIPOCOBRO = SF_CONCEPTOS.TIPOCOBRO \" + \" AND SF_DETALLE_COBRO.CONCEPTO = SF_CONCEPTOS.CODIGO \" + \"WHERE COMPANIA='\" + compania + \"' AND TIPOCOBRO='\" + registro.getCampos().get(\"TIPOCOBRO\") + \"' AND CODIGO_COBRO='\" + registro.getCampos().get(\"CODIGO_COBRO\") + \"'\","),;

	private final String key;
	private final String value;

	private ConceptosNoFacturadosControladorUrlEnum(String key, String value) {
		this.key = key;
		this.value = value;
	}

	public String getKey() {
		return key;
	}

	public String getValue() {
		return value;
	}
}
