SELECT 
    V_PLAN_PRESUPUESTAL.CODIGOFUT_H,
    V_PLAN_PRESUPUESTAL.UNIDADEJECUTORA_FUT ,
    V_PLAN_PRESUPUESTAL.FUENTE_FUT AS FUENTE,
    SUM(V_RESUMENPPTO_BASE.APROPIADO) PRESUPUESTO_INICIAL,
    SUM(V_RESUMENPPTO_BASE.APROPIACIONVIGENTE) PRESUPUESTO_DEFINITIVO,
    SUM(V_RESUMENPPTO_BASE.COMPROMISOSACUM) COMPROMISOS,
    SUM(V_RESUMENPPTO_BASE.OBLIGACIONESACUM) OBLIGACIONES,
    SUM(V_RESUMENPPTO_BASE.EJECUCIONPPT) PAGOS
  FROM V_PLAN_PRESUPUESTAL
  INNER JOIN  V_RESUMENPPTO_BASE 
        ON V_PLAN_PRESUPUESTAL.COMPANIA       =  V_RESUMENPPTO_BASE.COMPANIA 
       AND V_PLAN_PRESUPUESTAL.ANO            =  V_RESUMENPPTO_BASE.ANO
       AND V_PLAN_PRESUPUESTAL.ID             =  V_RESUMENPPTO_BASE.ID
  WHERE V_PLAN_PRESUPUESTAL.COMPANIA    = s$compania$s
    AND V_RESUMENPPTO_BASE.ANO          = s$aniotrabajo$s
    AND V_RESUMENPPTO_BASE.MES         <= s$mesfinal$s
    AND V_PLAN_PRESUPUESTAL.DESTINO     = 's$tipo$s'
    AND V_RESUMENPPTO_BASE.NATURALEZA   ='D'
    AND V_PLAN_PRESUPUESTAL.UNIDADEJECUTORA_FUT IS NOT NULL
    AND V_PLAN_PRESUPUESTAL.FUENTE_FUT          IS NOT NULL
    AND V_PLAN_PRESUPUESTAL.TIPOVIGENCIA           ='VA'  
  HAVING SUM(V_RESUMENPPTO_BASE.APROPIADO +
    V_RESUMENPPTO_BASE.APROPIACIONVIGENTE +
    V_RESUMENPPTO_BASE.COMPROMISOSACUM +
    V_RESUMENPPTO_BASE.OBLIGACIONESACUM +
    V_RESUMENPPTO_BASE.EJECUCIONPPT) <> 0
  GROUP BY  
    V_PLAN_PRESUPUESTAL.CODIGOFUT_H,
    V_PLAN_PRESUPUESTAL.UNIDADEJECUTORA_FUT ,
    V_PLAN_PRESUPUESTAL.FUENTE_FUT
 ORDER BY   V_PLAN_PRESUPUESTAL.CODIGOFUT_H,
    V_PLAN_PRESUPUESTAL.UNIDADEJECUTORA_FUT ,
    V_PLAN_PRESUPUESTAL.FUENTE_FUT
