SELECT NVL(PCK_SYSMAN_UTL.FC_PAR(UN_COMPANIA   => s$compania$s
              , UN_NOMBRE    => 'FUENTE FUT PARA CIFRA DE CONTROL VAL'
              , UN_MODULO    => 99
              , UN_FECHA_PAR => SYSDATE),'700'),
    SUM(PRESUPUESTO_INICIAL) PRESUPUESTO_INICIAL,
    SUM(PRESUPUESTO_DEFINITIVO) PRESUPUESTO_DEFINITIVO,
    SUM(COMPROMISOS) COMPROMISOS,
    SUM(OBLIGACIONES) OBLIGACIONES,
    SUM(PAGOS) PAGOS
  FROM (s$consultabase$s)
