SELECT  SUM(PRESUPUESTO_INICIAL) PRESUPUESTO_INICIAL,  
        SUM(PRESUPUESTO_DEFINITIVO) PRESUPUESTO_DEFINITIVO,
        SUM(RECUADO)  RECUADO   , 
        SUM(SINFONDOS)  SINFONDOS,
        SUM(RECAUDOFONDO) RECAUDOFONDO,    
         'No' DOCUMENTOSOPORTE,
         'NA' NUMERO_DOCUMENTO,
         '0' PORCENTAJE_DESTINACION,
          0  VALOR_DESTINACION
       FROM (s$consultabase$s)
