MERGE INTO CONSULTAS FIN USING (SELECT '800489V_CGR_mayor_balances' INFORME ,TO_CLOB(q'[SELECT     TO_CHAR(ANO)  Anio,
           NITCOMPANIA   NIT_Entidad,
           NOMBRECOM     Nombre_Entidad,
           NVL(CODIGO,0) Codigo_Contable,
           NVL(NOMBRE,'N/A') Descripcion,
           REGEXP_REPLACE(REGEXP_REPLACE(REPLACE(NVL(SALDOANTDEB,0),'.',','),'(^-,)','-0,'),'(^,)','0,') Saldo_DB_Anterior,   
           REGEXP_REPLACE(REGEXP_REPLACE(REPLACE(NVL(SALDOANTCRE,0),'.',','),'(^-,)','-0,'),'(^,)','0,') Saldo_CR_Anterior,
           REGEXP_REPLACE(REGEXP_REPLACE(REPLACE(NVL(DEBITO,0),'.',','),'(^-,)','-0,'),'(^,)','0,')      Movimiento_DB_Periodo, 
           REGEXP_REPLACE(REGEXP_REPLACE(REPLACE(NVL(CREDITO,0),'.',','),'(^-,)','-0,'),'(^,)','0,')     Movimiento_CR_Periodo,
           REGEXP_REPLACE(REGEXP_REPLACE(REPLACE(NVL(SALDOFINDEB,0),'.',','),'(^-,)','-0,'),'(^,)','0,') Saldo_Final_DB,
           REGEXP_REPLACE(REGEXP_REPLACE(REPLACE(NVL(SALDOFINCRE,0),'.',','),'(^-,)','-0,'),'(^,)','0,') Saldo_Final_CR

    FROM (   
        SELECT     PLAN_CONTABLE.ANO,PLAN_CONTABLE.CODIGO,                                                                                            
                   PLAN_CONTABLE.NOMBRE,
                   SUBSTR(REPLACE(COMPANIA.NITCOMPANIA, '.', ''),1,9) NITCOMPANIA,
                   COMPANIA.NOMBRE NOMBRECOM,
                   (CASE WHEN 0  =s$mesInicial-1$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO0>0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO0<0) THEN ABS(PLAN_CONTABLE.SALDO0) ELSE 0 END 
                   + CASE WHEN 1  =s$mesInicial-1$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO1>0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO1<0) THEN ABS(PLAN_CONTABLE.SALDO1)  ELSE 0 END
                   + CASE WHEN 2  =s$mesInicial-1$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO2>0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO2<0)  THEN ABS(PLAN_CONTABLE.SALDO2)  ELSE 0 END
                   + CASE WHEN 3  =s$mesInicial-1$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO3>0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO3<0)  THEN ABS(PLAN_CONTABLE.SALDO3)  ELSE 0 END
                   + CASE WHEN 4  =s$mesInicial-1$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO4>0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO4<0)  THEN ABS(PLAN_CONTABLE.SALDO4)  ELSE 0 END
                   + CASE WHEN 5  =s$mesInicial-1$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO5>0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO5<0)  THEN ABS(PLAN_CONTABLE.SALDO5)  ELSE 0 END
                   + CASE WHEN 6  =s$mesInicial-1$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO6>0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO6<0)  THEN ABS(PLAN_CONTABLE.SALDO6)  ELSE 0 END
                   + CASE WHEN 7  =s$mesInicial-1$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO7>0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO7<0)  THEN ABS(PLAN_CONTABLE.SALDO7)  ELSE 0 END
                   + CASE WHEN 8  =s$mesInicial-1$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO8>0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO8<0)  THEN ABS(PLAN_CONTABLE.SALDO8)  ELSE 0 END
              ]') || TO_CLOB(q'[     + CASE WHEN 9  =s$mesInicial-1$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO9>0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO9<0)  THEN ABS(PLAN_CONTABLE.SALDO9)  ELSE 0 END
                   + CASE WHEN 10 =s$mesInicial-1$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO10>0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO10<0)  THEN ABS(PLAN_CONTABLE.SALDO10) ELSE 0 END
                   + CASE WHEN 11 =s$mesInicial-1$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO11>0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO11<0)  THEN ABS(PLAN_CONTABLE.SALDO11) ELSE 0 END
                   + CASE WHEN 12 =s$mesInicial-1$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO12>0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO12<0)  THEN ABS(PLAN_CONTABLE.SALDO12) ELSE 0 END
                   + CASE WHEN 13 =s$mesInicial-1$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO13>0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO13<0)  THEN ABS(PLAN_CONTABLE.SALDO13) ELSE 0 END
                   ) SALDOANTDEB,    
                   (CASE WHEN 0  =s$mesInicial-1$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO0<0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO0>0) THEN ABS(PLAN_CONTABLE.SALDO0) ELSE 0 END 
                   + CASE WHEN 1  =s$mesInicial-1$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO1<0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO1>0) THEN ABS(PLAN_CONTABLE.SALDO1)  ELSE 0 END
                   + CASE WHEN 2  =s$mesInicial-1$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO2<0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO2>0)  THEN ABS(PLAN_CONTABLE.SALDO2)  ELSE 0 END
                   + CASE WHEN 3  =s$mesInicial-1$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO3<0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO3>0)  THEN ABS(PLAN_CONTABLE.SALDO3)  ELSE 0 END
                   + CASE WHEN 4  =s$mesInicial-1$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO4<0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO4>0)  THEN ABS(PLAN_CONTABLE.SALDO4)  ELSE 0 END
                   + CASE WHEN 5  =s$mesInicial-1$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO5<0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO5>0)  THEN ABS(PLAN_CONTABLE.SALDO5)  ELSE 0 END
                   + CASE WHEN 6  =s$mesInicial-1$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO6<0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO6>0)  THEN ABS(PLAN_CONTABLE.SALDO6)  ELSE 0 END
                   + CASE WHEN 7  =s$mesInicial-1$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO7<0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO7>0)  THEN ABS(PLAN_CONTABLE.SALDO7)  ELSE 0 END
                   + CASE WHEN 8  =s$mesInicial-1$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO8<0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO8>0)  THEN ABS(PLAN_CONTABLE.SALDO8)  ELSE 0 END
                   + CASE WHEN 9  =s$mesInicial-1$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO9<0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO9>0)  THEN ABS(PLAN_CONTABLE.SALDO9)  ELSE 0 END
                   + CASE WHEN 10 =s$mesInicial-1$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO10<0 OR  PLAN_CONTABLE.NAT]') || TO_CLOB(q'[URALEZA='C' AND SALDO10>0)  THEN ABS(PLAN_CONTABLE.SALDO10) ELSE 0 END
                   + CASE WHEN 11 =s$mesInicial-1$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO11<0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO11>0)  THEN ABS(PLAN_CONTABLE.SALDO11) ELSE 0 END
                   + CASE WHEN 12 =s$mesInicial-1$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO12<0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO12>0)  THEN ABS(PLAN_CONTABLE.SALDO12) ELSE 0 END
                   + CASE WHEN 13 =s$mesInicial-1$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO13<0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO13>0)  THEN ABS(PLAN_CONTABLE.SALDO13) ELSE 0 END
                   ) SALDOANTCRE,    
                 (CASE WHEN 0  BETWEEN s$mesInicial$s AND s$mesFinal$s  THEN PLAN_CONTABLE.DEBITO0  ELSE 0 END
                   + CASE WHEN 1  BETWEEN s$mesInicial$s AND s$mesFinal$s  THEN PLAN_CONTABLE.DEBITO1  ELSE 0 END
                   + CASE WHEN 2  BETWEEN s$mesInicial$s AND s$mesFinal$s  THEN PLAN_CONTABLE.DEBITO2  ELSE 0 END
                   + CASE WHEN 3  BETWEEN s$mesInicial$s AND s$mesFinal$s  THEN PLAN_CONTABLE.DEBITO3  ELSE 0 END
                   + CASE WHEN 4  BETWEEN s$mesInicial$s AND s$mesFinal$s  THEN PLAN_CONTABLE.DEBITO4  ELSE 0 END
                   + CASE WHEN 5  BETWEEN s$mesInicial$s AND s$mesFinal$s  THEN PLAN_CONTABLE.DEBITO5  ELSE 0 END
                   + CASE WHEN 6  BETWEEN s$mesInicial$s AND s$mesFinal$s  THEN PLAN_CONTABLE.DEBITO6  ELSE 0 END
                   + CASE WHEN 7  BETWEEN s$mesInicial$s AND s$mesFinal$s  THEN PLAN_CONTABLE.DEBITO7  ELSE 0 END
                   + CASE WHEN 8  BETWEEN s$mesInicial$s AND s$mesFinal$s  THEN PLAN_CONTABLE.DEBITO8  ELSE 0 END
                   + CASE WHEN 9  BETWEEN s$mesInicial$s AND s$mesFinal$s  THEN PLAN_CONTABLE.DEBITO9  ELSE 0 END
                   + CASE WHEN 10 BETWEEN s$mesInicial$s AND s$mesFinal$s  THEN PLAN_CONTABLE.DEBITO10 ELSE 0 END
                   + CASE WHEN 11 BETWEEN s$mesInicial$s AND s$mesFinal$s  THEN PLAN_CONTABLE.DEBITO11 ELSE 0 END
                   + CASE WHEN 12 BETWEEN s$mesInicial$s AND s$mesFinal$s  THEN PLAN_CONTABLE.DEBITO12 ELSE 0 END
                   + CASE WHEN 13 BETWEEN s$mesInicial$s AND s$mesFinal$s  THEN PLAN_CONTABLE.DEBITO13 ELSE 0 END
                   )      DEBITO,                                                                                            
                 (CASE WHEN 0  BETWEEN s$mesInicial$s AND s$mesFinal$s  THEN PLAN_CONTABLE.CREDITO0  ELSE 0 END
                   + CASE WHEN 1  BETWEEN s$mesInicial$s AND s$mesFinal$s  THEN PLAN_CONTABLE.CREDITO1  ELSE 0 END
                   + CASE WHEN 2  BETWEEN s$mesInicial$s AND s$mesFinal$s  THEN PLAN_CONTABLE.CREDITO2  ELSE 0 END
                   + CASE WHEN 3  BETWEEN s$mesInicial$s AND s$mesFinal$s  THEN PLAN_CONTABLE.CREDITO3  ELSE 0 END
                   + CASE WHEN 4  BETWEEN s$mesInicial$s AND s$mesFinal$s  THEN PLAN_CONTABLE.CREDITO4  ELSE 0 END
                   + CAS]') || TO_CLOB(q'[E WHEN 5  BETWEEN s$mesInicial$s AND s$mesFinal$s  THEN PLAN_CONTABLE.CREDITO5  ELSE 0 END
                   + CASE WHEN 6  BETWEEN s$mesInicial$s AND s$mesFinal$s  THEN PLAN_CONTABLE.CREDITO6  ELSE 0 END
                   + CASE WHEN 7  BETWEEN s$mesInicial$s AND s$mesFinal$s  THEN PLAN_CONTABLE.CREDITO7  ELSE 0 END
                   + CASE WHEN 8  BETWEEN s$mesInicial$s AND s$mesFinal$s  THEN PLAN_CONTABLE.CREDITO8  ELSE 0 END
                   + CASE WHEN 9  BETWEEN s$mesInicial$s AND s$mesFinal$s  THEN PLAN_CONTABLE.CREDITO9  ELSE 0 END
                   + CASE WHEN 10 BETWEEN s$mesInicial$s AND s$mesFinal$s  THEN PLAN_CONTABLE.CREDITO10 ELSE 0 END
                   + CASE WHEN 11 BETWEEN s$mesInicial$s AND s$mesFinal$s  THEN PLAN_CONTABLE.CREDITO11 ELSE 0 END
                   + CASE WHEN 12 BETWEEN s$mesInicial$s AND s$mesFinal$s  THEN PLAN_CONTABLE.CREDITO12 ELSE 0 END
                   + CASE WHEN 13 BETWEEN s$mesInicial$s AND s$mesFinal$s  THEN PLAN_CONTABLE.CREDITO13 ELSE 0 END
                   )  CREDITO,                                                                                             

                     (CASE WHEN 0  =s$mesFinal$s  AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO0>0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO0<0) THEN ABS(PLAN_CONTABLE.SALDO0) ELSE 0 END 
                   + CASE WHEN 1  =s$mesFinal$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO1>0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO1<0) THEN ABS(PLAN_CONTABLE.SALDO1)  ELSE 0 END
                   + CASE WHEN 2  =s$mesFinal$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO2>0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO2<0)  THEN ABS(PLAN_CONTABLE.SALDO2)  ELSE 0 END
                   + CASE WHEN 3  =s$mesFinal$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO3>0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO3<0)  THEN ABS(PLAN_CONTABLE.SALDO3)  ELSE 0 END
                   + CASE WHEN 4  =s$mesFinal$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO4>0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO4<0)  THEN ABS(PLAN_CONTABLE.SALDO4)  ELSE 0 END
                   + CASE WHEN 5  =s$mesFinal$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO5>0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO5<0)  THEN ABS(PLAN_CONTABLE.SALDO5)  ELSE 0 END
                   + CASE WHEN 6  =s$mesFinal$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO6>0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO6<0)  THEN ABS(PLAN_CONTABLE.SALDO6)  ELSE 0 END
                   + CASE WHEN 7  =s$mesFinal$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO7>0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO7<0)  THEN ABS(PLAN_CONTABLE.SALDO7)  ELSE 0 END
                   + CASE WHEN 8  =s$mesFinal$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO8>0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO8<0)  THEN ABS(PLAN_CONTABLE.SALDO8)  ELSE 0 END
                   + CASE WHEN 9  =s$mesFinal$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO9>0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO9<0)  THEN ABS(PLAN_CONTABLE.SALDO9)  ELSE 0 END
    ]') || TO_CLOB(q'[               + CASE WHEN 10 =s$mesFinal$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO10>0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO10<0)  THEN ABS(PLAN_CONTABLE.SALDO10) ELSE 0 END
                   + CASE WHEN 11 =s$mesFinal$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO11>0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO11<0)  THEN ABS(PLAN_CONTABLE.SALDO11) ELSE 0 END
                   + CASE WHEN 12 =s$mesFinal$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO12>0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO12<0)  THEN ABS(PLAN_CONTABLE.SALDO12) ELSE 0 END
                   + CASE WHEN 13 =s$mesFinal$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO13>0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO13<0)  THEN ABS(PLAN_CONTABLE.SALDO13) ELSE 0 END
                   ) SALDOFINDEB,    
                   (CASE WHEN 0  =s$mesFinal$s  AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO0<0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO0>0) THEN ABS(PLAN_CONTABLE.SALDO0) ELSE 0 END 
                   + CASE WHEN 1  =s$mesFinal$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO1<0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO1>0) THEN ABS(PLAN_CONTABLE.SALDO1)  ELSE 0 END
                   + CASE WHEN 2  =s$mesFinal$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO2<0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO2>0)  THEN ABS(PLAN_CONTABLE.SALDO2)  ELSE 0 END
                   + CASE WHEN 3  =s$mesFinal$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO3<0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO3>0)  THEN ABS(PLAN_CONTABLE.SALDO3)  ELSE 0 END
                   + CASE WHEN 4  =s$mesFinal$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO4<0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO4>0)  THEN ABS(PLAN_CONTABLE.SALDO4)  ELSE 0 END
                   + CASE WHEN 5  =s$mesFinal$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO5<0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO5>0)  THEN ABS(PLAN_CONTABLE.SALDO5)  ELSE 0 END
                   + CASE WHEN 6  =s$mesFinal$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO6<0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO6>0)  THEN ABS(PLAN_CONTABLE.SALDO6)  ELSE 0 END
                   + CASE WHEN 7  =s$mesFinal$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO7<0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO7>0)  THEN ABS(PLAN_CONTABLE.SALDO7)  ELSE 0 END
                   + CASE WHEN 8  =s$mesFinal$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO8<0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO8>0)  THEN ABS(PLAN_CONTABLE.SALDO8)  ELSE 0 END
                   + CASE WHEN 9  =s$mesFinal$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO9<0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO9>0)  THEN ABS(PLAN_CONTABLE.SALDO9)  ELSE 0 END
                   + CASE WHEN 10 =s$mesFinal$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO10<0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO10>0)  THEN ABS(PLAN_CONTABLE.SALDO10) ELSE 0 END
                   + CASE WHEN 11 =s$mesFinal$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO11<0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO11>0)  THEN ABS(PLAN_CONTABLE.]') || TO_CLOB(q'[SALDO11) ELSE 0 END
                   + CASE WHEN 12 =s$mesFinal$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO12<0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO12>0)  THEN ABS(PLAN_CONTABLE.SALDO12) ELSE 0 END
                   + CASE WHEN 13 =s$mesFinal$s AND (PLAN_CONTABLE.NATURALEZA='D' AND SALDO13<0 OR  PLAN_CONTABLE.NATURALEZA='C' AND SALDO13>0)  THEN ABS(PLAN_CONTABLE.SALDO13) ELSE 0 END
                   ) SALDOFINCRE                                                                             

           FROM  PLAN_CONTABLE
           INNER JOIN COMPANIA 
            ON PLAN_CONTABLE.COMPANIA=COMPANIA.CODIGO
           WHERE PLAN_CONTABLE.COMPANIA =s$compania$s
             AND PLAN_CONTABLE.ANO      =s$ano$s


           )
WHERE     SALDOANTDEB +SALDOANTCRE  +  DEBITO  +  CREDITO + SALDOFINDEB +SALDOFINCRE  NOT IN (0)
ORDER BY  CODIGO ]') CONSULTA, 99 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);
