MERGE INTO CONSULTAS FIN USING (SELECT '800473PROGRAMACION_DE_GASTOS_T5' INFORME ,TO_CLOB(q'[SELECT CASE WHEN SUBSTR(CODIGO,1,3)='2.3'
       THEN '2.99'
       ELSE CODIGO
       END CODIGO,
       s$nombre$s
       CASE WHEN NVL(PCK_SYSMAN_UTL.FC_PAR('001','RELACIONAR VIGENCIA DESDE AUXILIAR GENERAL',03,SYSDATE,-1),'NO') = 'SI'
       THEN NVL(VIGENCIA_AUXILIAR, VIGENCIA_GASTO)
       ELSE VIGENCIA_GASTO
       END AS VIGENCIA_GASTO,
       SECCION_PRESUPUESTAL,
       SECTOR,
	   ROUND(SUM(APROPIACION_INICIAL), NVL(PCK_SYSMAN_UTL.FC_PAR('001','DIGITOS DE REDONDEO INFORMES CUIPO',99,SYSDATE,-1), 2)) APROPIACION_INICIAL,
	   ROUND(SUM(APROPIACION_DEFINITIVA), NVL(PCK_SYSMAN_UTL.FC_PAR('001','DIGITOS DE REDONDEO INFORMES CUIPO',99,SYSDATE,-1), 2)) APROPIACION_DEFINITIVA
FROM(
SELECT NVL(INI.CODIGOCCPET_MAN,INI.CODIGOCCPET_PAD) CODIGO,       
(SELECT NOMBRE FROM TIPOCLASIFICADOR WHERE CODIGO = NVL(INI.CODIGOCCPET_MAN, INI.CODIGOCCPET_PAD) AND ANO = s$anio$s AND COMPANIA = s$compania$s AND ROWNUM =1) NOMBRE,      
CASE WHEN SALDO.AUXILIAR NOT IN('0040') THEN INI.VIGENCIA_GASTO ELSE '4' END VIGENCIA_GASTO, 
TV_AUXILIAR.EQUIVALENTE_CUIPO VIGENCIA_AUXILIAR,  
NVL(INI.SECTOR,0) SECTOR,
NVL(NVL(INI.CODIGOUNIDADEJE_MAN,INI.CODIGOUNIDADEJE_PAD),0) SECCION_PRESUPUESTAL,              
NVL(NVL(INI.PROGRAMA_MAN,INI.PROGRAMA_PAD),0) PROGRAMA,              
NVL(NVL(INI.CODIGOBPIN_MAN,INI.CODIGOBPIN_PAD),0) BPIN,              
SUM(SALDO.APROPIACION_DEBITO) APROPIACION_INICIAL,               
SUM(SALDO.APROPIACION_DEBITO + SALDO.ADICION + SALDO.REDUCCION +(SALDO.TRASLADO_DEBITO - SALDO.TRASLADO_CREDITO)+(SALDO.APLAZAM_DEBITO - SALDO.APLAZAM_CREDITO))APROPIACION_DEFINITIVA        
FROM ( SELECT MOV.COMPANIA,
MOV.ANO,                
MOV.CODIGO, 
MOV.SECTOR,
MAX(CASE WHEN PADRE.CLASECLASIFICADOR ='006' THEN
PADRE.TIPOCLASIFICADOR 
ELSE 
NULL END) CODIGOCCPET_PAD,
MOV.CODIGOCCPET CODIGOCCPET_MAN,
MAX(CASE WHEN PADRE.CLASECLASIFICADOR ='005' THEN
PADRE.TIPOCLASIFICADOR 
ELSE 
NULL 
END) CODIGOBPIN_PAD,
MOV.CODIGOBPIN CODIGOBPIN_MAN, 
MAX(CASE WHEN PADRE.CLASECLASIFICADOR ='002' THEN
PADRE.TIPOCLASIFICADOR 
ELSE 
NULL 
END) PROGRAMA_PAD,
MOV.PROGRAMA PROGRAMA_MAN, 
MAX(CASE WHEN PADRE.CLASECLASIFICADOR ='008' THEN
PADRE.TIPOCLASIFICADOR 
ELSE
NULL 
END) CODIGOUNIDADEJE_PAD, 
MOV.CODIGOUNIDADEJE CODIGOUNIDADEJE_MAN,
MOV.TIPOVIGENCIA,
TV.EQUIVALENTE_CUIPO VIGENCIA_GASTO
FROM PLAN_PRESUPUESTAL MOV 
LEFT JOIN PLAN_PRESUPUESTAL PADRE 
ON PADRE.COMPANIA = MOV.COMPANIA 
AND PADRE.ANO = MOV.ANO 
AND PADRE.CODIGO = SUBSTR(MOV.CODIGO,1,LENGTH(PADRE.CODIGO))
INNER JOIN TIPOVIGENCIA TV ON TV.CODIGO = MOV.TIPOVIGENCIA 
WHERE MOV.COMPANIA = s$compania$s  
AND MOV.ANO      = s$anio$s  
AND MOV.NATURALEZA = 'D'
AND MOV.REGALIAS IN(0)  
AND (MOV.MOVIMIENTO<>0             
OR MOV.MAN_AUX_FUE<>0            
OR MOV.MAN_AUX_GEN<>0            
OR MOV.MAN_AUX_REF<>0           
OR MOV.MAN_AUX_TER<>0            
OR MOV.MAN_CEN_CTO<>0            
)        
GROUP BY MOV.COMPANIA,
MOV.ANO,
MOV.CODIGO,
MOV.SECTOR,
MOV.CODIGOCCPET,
MOV.CODIGOBPIN, 
MOV.PROGRAMA,  
MOV.CODIGOUNIDADEJE, 
MOV.TIPOVIGENCIA, 
TV.EQUIVALENTE_CUIPO      ) INI
INNER JOIN SALDO_AUX_PPTAL SALDO
ON INI.COMPANIA = SALDO.COMPANIA
AND INI.ANO      = SALDO.ANO  
AND INI.CODIGO   = SALDO.CODIGO 
INNER JOIN AUXILIAR 
ON SALDO.COMPANIA =AUXILIAR.COMPANIA
AND SALDO.ANO = AUXILIAR.ANO
AND SALDO.AUXILIAR = AUXILIAR.CODIGO
LEFT JOIN TIPOVIGENCIA TV_AUXILIAR
ON AUXILIAR.TIPOVIGENCIA = TV_AUXILIAR.CODIGO
WHERE SALDO.COMPANIA = s$compania$s      
AND SALDO.ANO   = s$anio$s      
AND SALDO.MES  <= s$mesfinal$s  
AND NVL(INI.CODIGOCCPET_MAN, INI.CODIGOCCPET_PAD) IS NOT NULL  
GROUP BY 
NVL(INI.CODIGOCCPET_MAN,INI.CODIGOCCPET_PAD),
INI.SECTOR,
CASE WHEN SALDO.AUXILIAR NOT IN('0040') THEN INI.VIGENCIA_GASTO ELSE '4' END ,  
TV_AUXILIAR.EQUIVALENTE_CUIPO,
NVL(INI.CODIGOUNIDADEJE_MAN,INI.CODIGOUNIDADEJE_PAD),  
NVL(INI.PROGRAMA_MA]') || TO_CLOB(q'[N,INI.PROGRAMA_PAD),     
NVL(INI.CODIGOBPIN_MAN,INI.CODIGOBPIN_PAD)
   HAVING SUM(SALDO.Apropiacion_DEBITO) <>0 
       OR SUM(SALDO.Apropiacion_DEBITO + SALDO.Adicion +SALDO.Reduccion + (SALDO.TRASLADO_DEBITO- SALDO.TRASLADO_CREDITO) + (SALDO.Aplazam_Debito -SALDO.Aplazam_Credito)) <>0  
       )CUIPO
GROUP BY CASE WHEN SUBSTR(CODIGO,1,3)='2.3'
       THEN '2.99'
       ELSE CODIGO
       END ,
       CASE WHEN NVL(PCK_SYSMAN_UTL.FC_PAR('001','RELACIONAR VIGENCIA DESDE AUXILIAR GENERAL',03,SYSDATE,-1),'NO') = 'SI'
       THEN NVL(VIGENCIA_AUXILIAR, VIGENCIA_GASTO)
       ELSE VIGENCIA_GASTO
       END,
       s$nombre$s
       VIGENCIA_GASTO,
       SECCION_PRESUPUESTAL,
       SECTOR
ORDER BY CODIGO]') CONSULTA, 99 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);