WITH LISEJECPPTALGASTOSRESUMEN AS (
        SELECT  
                 V_RESUMENPPTO_BASE.COMPANIA, 
                 V_RESUMENPPTO_BASE.ANO, 
                 V_RESUMENPPTO_BASE.CODIGO , 
                 V_RESUMENPPTO_BASE.NOMBRE, 
                 TV.NOMBRE TIPVIGENCIA,        
                CASE WHEN CONSITUACIONFONDOS = 0 THEN 'SIN' ELSE 'CON' END SITUACIONFONDO ,     
                SUM(APROPIADO) APROPIACIONINICIAL,  
                SUM(ADICION) ADICIONES, 
                SUM(REDUCCION) REDUCCIONES, 
                SUM(TRASLADO_DEBITO) TRASLADOCREDITO, 
                SUM(TRASLADO_CREDITO) TRASLADOCONTRACREDITO,  
                SUM(APROPIACIONVIGENTE) APROPIACIONVIGENTE, 
                SUM(APRDEFINITIVA) APROPIACIONDEFINITIVA, 
                SUM(DISPONIBILIDAD) DISPONIBILIDADES, 
                SUM(COMPROMISOSACUM) COMPROMISOS, 
                SUM(OBLIGACIONESACUM) OBLIGACIONES, 
                SUM(V_RESUMENPPTO_BASE.EJECUCIONPPT) AS PAGOSACUMULADOS
        FROM V_RESUMENPPTO_BASE 
            INNER JOIN TIPOVIGENCIA TV
            ON V_RESUMENPPTO_BASE.TIPOVIGENCIA = TV.CODIGO
        WHERE V_RESUMENPPTO_BASE.COMPANIA = s$compania$s
            AND V_RESUMENPPTO_BASE.ANO = s$anio$s 
            AND V_RESUMENPPTO_BASE.CODIGO BETWEEN 's$codinicial$s' AND 's$codfinal$s' 
            AND V_RESUMENPPTO_BASE.MES <= s$mes$s
         GROUP BY    V_RESUMENPPTO_BASE.COMPANIA, 
                            V_RESUMENPPTO_BASE.ANO, 
                            V_RESUMENPPTO_BASE.CODIGO , 
                            V_RESUMENPPTO_BASE.NOMBRE, 
                            TV.NOMBRE,
                            V_RESUMENPPTO_BASE.CONSITUACIONFONDOS
)
   SELECT 
       DIS.ANO,
       's$nitcompania$s' NIT_ENTIDAD, 
       's$nomcompania$s' NOMBRE_ENTIDAD, 
       TO_CHAR(DIS.COMPROBANTE)    NUMERO_DISPONIBILIDAD, 
        TO_CHAR(RES.COMPROBANTE)    NUMERO_REGISTRO, 
       TO_CHAR(REO.COMPROBANTE)    NUMERO_OBLIGACION,
       TO_CHAR(EGR.COMPROBANTE)    NUMERO_PAGO,
       TIPOVIG.NOMBRE TIPOVIGENCIA,
       DIS.CUENTA         RUBRO, 
       PLAN.NOMBRE NOMBRE_RUBRO,        
       FR.NOMBRE FUENTE_RECURSO,
       CASE WHEN PLAN.CONSITUACIONFONDOS = 0 THEN 'SIN' ELSE 'CON' END SITUACION_FONDOS,
       REPLACE(RES.DESCRIPCION, ',', '.')    OBJETO,       
       TO_CHAR(RES.FECHA,'YYYY/MM/DD')          FECHA_REGISTRO, 
       TO_CHAR(REO.FECHA,'YYYY/MM/DD')        FECHA_OBLIGACION, 
       TO_CHAR(EGR.FECHA,'DD/MM/YYYY')          FECHA_PAGO, 
       RES_TERCERO.TIPOID, 
       RES_TERCERO.NIT    NIT_TERCERO_DEL_RES,
       RES_TERCERO.NOMBRE NOMBRE_TERCERO_DEL_RES,
       DATOSBANCO.NOMBREBANCO,
       DATOSBANCO.TIPOCUENTA,
       DATOSBANCO.CUENTA,
       L.APROPIACIONINICIAL, 
       L.ADICIONES,
       L.REDUCCIONES,
       L.TRASLADOCREDITO,
       L.TRASLADOCONTRACREDITO, 
       L.APROPIACIONVIGENTE,
       L. APROPIACIONDEFINITIVA, 
       L.DISPONIBILIDADES, 
       L.COMPROMISOS, 
       L.OBLIGACIONES, 
       L.PAGOSACUMULADOS
FROM DETALLE_COMPROBANTE_PPTAL DIS
    INNER JOIN TIPO_COMPROBPP DIS_TIPO
        ON  DIS.COMPANIA  = DIS_TIPO.COMPANIA
        AND DIS.TIPO_CPTE = DIS_TIPO.CODIGO
    INNER JOIN TERCERO DIS_TERCERO
        ON  DIS.COMPANIA = DIS_TERCERO.COMPANIA
        AND DIS.TERCERO  = DIS_TERCERO.NIT
        AND DIS.SUCURSAL = DIS_TERCERO.SUCURSAL
    LEFT JOIN DETALLE_COMPROBANTE_PPTAL RES 
        ON  DIS.COMPANIA    = RES.COMPANIA
        AND DIS.ANO         = RES.ANO_AFECT
        AND DIS.TIPO_CPTE   = RES.TIPO_CPTE_AFECT
        AND DIS.COMPROBANTE = RES.CMPTE_AFECTADO
        AND DIS.CONSECUTIVO = RES.CONSECUTIVOPPTO
    LEFT JOIN TIPO_COMPROBPP RES_TIPO 
        ON  RES.COMPANIA  = RES_TIPO.COMPANIA
        AND RES.TIPO_CPTE = RES_TIPO.CODIGO
    LEFT JOIN TERCERO RES_TERCERO
        ON  RES.COMPANIA = RES_TERCERO.COMPANIA
        AND RES.TERCERO  = RES_TERCERO.NIT
        AND RES.SUCURSAL = RES_TERCERO.SUCURSAL      
    LEFT JOIN DETALLE_COMPROBANTE_PPTAL REO 
        ON  RES.COMPANIA    = REO.COMPANIA
        AND RES.ANO         = REO.ANO_AFECT
        AND RES.TIPO_CPTE   = REO.TIPO_CPTE_AFECT
        AND RES.COMPROBANTE = REO.CMPTE_AFECTADO
        AND RES.CONSECUTIVO = REO.CONSECUTIVOPPTO
    LEFT JOIN TIPO_COMPROBPP REO_TIPO 
        ON  REO.COMPANIA  = REO_TIPO.COMPANIA
        AND REO.TIPO_CPTE = REO_TIPO.CODIGO
    LEFT JOIN TERCERO REO_TERCERO
        ON  REO.COMPANIA = REO_TERCERO.COMPANIA
        AND REO.TERCERO  = REO_TERCERO.NIT
        AND REO.SUCURSAL = REO_TERCERO.SUCURSAL     
    LEFT JOIN DETALLE_COMPROBANTE_PPTAL EGR 
        ON  REO.COMPANIA    = EGR.COMPANIA
        AND REO.ANO         = EGR.ANO_AFECT
        AND REO.TIPO_CPTE   = EGR.TIPO_CPTE_AFECT
        AND REO.COMPROBANTE = EGR.CMPTE_AFECTADO
        AND REO.CONSECUTIVO = EGR.CONSECUTIVOPPTO
    LEFT JOIN TIPO_COMPROBPP EGR_TIPO 
        ON  EGR.COMPANIA  = EGR_TIPO.COMPANIA
        AND EGR.TIPO_CPTE = EGR_TIPO.CODIGO
    LEFT JOIN TERCERO EGR_TERCERO
        ON  EGR.COMPANIA = EGR_TERCERO.COMPANIA
        AND EGR.TERCERO  = EGR_TERCERO.NIT
        AND EGR.SUCURSAL = EGR_TERCERO.SUCURSAL
    INNER JOIN PLAN_PRESUPUESTAL PLAN
        ON DIS.COMPANIA = PLAN.COMPANIA
        AND DIS.ANO = PLAN.ANO
        AND DIS.CUENTA = PLAN.CODIGO
    INNER JOIN TIPOVIGENCIA  TIPOVIG
        ON PLAN.TIPOVIGENCIA = TIPOVIG.CODIGO
    INNER JOIN FUENTE_RECURSOS FR
        ON DIS.COMPANIA = FR.COMPANIA
        AND DIS.ANO = FR.ANO
        AND DIS.FUENTE_RECURSO = FR.CODIGO
    LEFT JOIN (
                SELECT  TP.COMPANIA, TP.NIT, TP.SUCURSAL , B.NOMBREBANCO, CASE WHEN  TP.TIPOCUENTA = 'C' THEN 'CORRIENTE' ELSE 'AHORRO' END TIPOCUENTA, CUENTA
                FROM    TERCEROPAGOS TP
                    INNER JOIN BANCO  B  
                        ON TP.COMPANIA = B.COMPANIA
                        AND TP.BANCO = B.BANCO
                WHERE   TP.ACTIVA NOT IN (0)
                AND ROWNUM = 1
                ) DATOSBANCO 
        ON   RES_TERCERO.COMPANIA = DATOSBANCO.COMPANIA
        AND  RES_TERCERO.NIT = DATOSBANCO.NIT
        AND  RES_TERCERO.SUCURSAL = DATOSBANCO.SUCURSAL
    INNER JOIN LISEJECPPTALGASTOSRESUMEN L
        ON DIS.COMPANIA = L.COMPANIA
        AND DIS.ANO = L.ANO
        AND DIS.CUENTA = L.CODIGO
        
WHERE DIS.COMPANIA = s$compania$s
  AND DIS.ANO      = s$anio$s
  AND DIS.MES    = s$mes$s
  AND DIS.CUENTA   BETWEEN 's$codinicial$s' AND 's$codfinal$s' 
  AND DIS_TIPO.CLASE            = 'DIS'
  AND (RES_TIPO.CLASE            = 'RES' OR  RES_TIPO.CLASE IS NULL)
  AND (REO_TIPO.CLASE            = 'REO' OR  REO_TIPO.CLASE IS NULL)
  AND (EGR_TIPO.CLASE            = 'EGR' OR  EGR_TIPO.CLASE IS NULL)
  
ORDER BY DIS.CUENTA