MERGE INTO CONSULTAS FIN USING (SELECT '800571V_CGR_Relacion_ObligacionesAppUI' INFORME ,TO_CLOB(q'[SELECT 
nombreRubro,
Vigencia,
macroCampo,
codigoPresupuestal,
fechaObligacion,
valorObligacion,
nitTercero,
numeroObligacion,
numeroCompromiso
FROM (
        SELECT TO_CHAR(dcp.COMPROBANTE) numeroObligacion,
               NVL(CODIGO_CCPET.NOMBRE,'NA')  nombreRubro,
              TIPOVIGENCIA.EQUIVALENTE_APPUI VIGENCIA,
              '2' macroCampo,
            CASE WHEN CODIGO_CCPET.CODIGO IS NULL
             THEN dcp.CUENTA 
             ELSE CODIGO_CCPET.CODIGO END codigoPresupuestal,
             NVL(TO_CHAR(dcp.FECHA,'YYYY-MM-DD'),'1900-01-01') fechaObligacion,
             NVL(dcp.VALOR_DEBITO,0) - NVL(VALOR_CREDITO,0)  valorObligacion,
             NVL(t.NIT,0) nitTercero,
            TO_CHAR(dcp.CMPTE_AFECTADO) numeroCompromiso


        FROM DETALLE_COMPROBANTE_PPTAL dcp 
        INNER JOIN COMPANIA c 
        ON 	dcp.COMPANIA = c.CODIGO
        INNER JOIN PLAN_PRESUPUESTAL pp 
        ON 	dcp.COMPANIA = pp.COMPANIA
            AND dcp.ANO = pp.ANO
            AND dcp.CUENTA = pp.CODIGO
        INNER JOIN TIPO_COMPROBPP tc 
        ON 	dcp.COMPANIA = tc.COMPANIA
            AND dcp.TIPO_CPTE = tc.CODIGO
        INNER JOIN TERCERO t 
        ON 	dcp.COMPANIA = t.COMPANIA
            AND dcp.TERCERO = t.NIT
            AND dcp.SUCURSAL = t.SUCURSAL
        INNER JOIN COMPROBANTE_PPTAL CP   
         ON DCP.COMPANIA=CP.COMPANIA
         AND DCP.ANO_AFECT=CP.ANO
         AND DCP.TIPO_CPTE_AFECT=CP.TIPO
         AND DCP.CMPTE_AFECTADO=CP.NUMERO
        LEFT JOIN TIPOCLASIFICADOR CODIGO_CCPET
          ON dcp.COMPANIA= CODIGO_CCPET.COMPANIA
          AND dcp.ANO= CODIGO_CCPET.ANO
          AND '006'= CODIGO_CCPET.CLASECLASIFICADOR
           AND dcp.CODIGO_CCPET= CODIGO_CCPET.CODIGO
           LEFT JOIN TIPOVIGENCIA 
ON PP.TIPOVIGENCIA = TIPOVIGENCIA.CODIGO
        WHERE
            dcp.COMPANIA =s$compania$s
            and dcp.ANO=s$ano$s 
            AND dcp.MES  BETWEEN s$mesInicial$s AND s$mesFinal$s
            AND tc.CLASE IN ('REO', 'ARO', 'DRO')
            AND pp.REGALIAS IN (0)
            AND PP.TIPOVIGENCIA IN (s$vigenciasAppui$s))
]') CONSULTA, 99 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);