MERGE INTO CONSULTAS FIN USING (SELECT '800578FutVictimas' INFORME ,TO_CLOB(q'[SELECT     PLAN_PPTAL_CONFIG.FUT_VICTIMAS1 CONCEPTO
           ,PLAN_PPTAL_CONFIG.HECHOVICTIMIZANTE
          , PLAN_PPTAL_CONFIG.FUENTE_FLS  FUENTES_DE_FINANCIACION 
          , SUM(CASE WHEN PLAN_PPTAL_CONFIG.NATURALEZA='D'
                     THEN APROPIACION_DEBITO  - APROPIACION_CREDITO
                     ELSE APROPIACION_CREDITO - APROPIACION_DEBITO
                END)  PRESUPUESTO_INICIAL
          , SUM(CASE WHEN PLAN_PPTAL_CONFIG.NATURALEZA='D'
                     THEN APROPIACION_DEBITO  - APROPIACION_CREDITO
                     ELSE APROPIACION_CREDITO - APROPIACION_DEBITO
                END + SALDO_AUX_PPTAL.ADICION + SALDO_AUX_PPTAL.REDUCCION + 
                CASE WHEN PLAN_PPTAL_CONFIG.NATURALEZA='D'
                     THEN TRASLADO_DEBITO-TRASLADO_CREDITO
                     ELSE TRASLADO_CREDITO-TRASLADO_DEBITO
                END) PRESUPUESTO_DEFINITIVO 
          , SUM(SALDO_AUX_PPTAL.REG_CONTRACT         + SALDO_AUX_PPTAL.MODIF_REG_CONT 
              + SALDO_AUX_PPTAL.REG_NO_CONTRACT      + SALDO_AUX_PPTAL.MODIF_REG_NOCONT) COMPROMISOS      
          , SUM(SALDO_AUX_PPTAL.REGISTRO_OBLIGACION + SALDO_AUX_PPTAL.MODIF_REGISTRO_OBLIGACION) OBLIGACIONES      
          , SUM(CASE WHEN PLAN_PPTAL_CONFIG.NATURALEZA='D'
                     THEN EJE_PPT_DEBITO  - EJE_PPT_CREDITO 
                     ELSE EJE_PPT_CREDITO - EJE_PPT_DEBITO 
                END ) PAGOS
  FROM PLAN_PPTAL_CONFIG
  INNER JOIN SALDO_AUX_PPTAL  
    ON PLAN_PPTAL_CONFIG.COMPANIA       = SALDO_AUX_PPTAL.COMPANIA
   AND PLAN_PPTAL_CONFIG.ANO            = SALDO_AUX_PPTAL.ANO        
   AND PLAN_PPTAL_CONFIG.CODIGO         = SALDO_AUX_PPTAL.CODIGO
   AND PLAN_PPTAL_CONFIG.CENTRO_COSTO   = SALDO_AUX_PPTAL.CENTRO_COSTO
   AND PLAN_PPTAL_CONFIG.TERCERO        = SALDO_AUX_PPTAL.TERCERO
   AND PLAN_PPTAL_CONFIG.SUCURSAL       = SALDO_AUX_PPTAL.SUCURSAL
   AND PLAN_PPTAL_CONFIG.AUXILIAR       = SALDO_AUX_PPTAL.AUXILIAR
   AND PLAN_PPTAL_CONFIG.REFERENCIA     = SALDO_AUX_PPTAL.REFERENCIA    
   AND PLAN_PPTAL_CONFIG.FUENTE_RECURSO = SALDO_AUX_PPTAL.FUENTE_RECURSO
WHERE PLAN_PPTAL_CONFIG.COMPANIA = s$compania$s
   AND PLAN_PPTAL_CONFIG.ANO     = s$anioTrabajo$s
   AND SALDO_AUX_PPTAL.MES      <= s$mesfinal$s
   AND PLAN_PPTAL_CONFIG.FUENTE_FLS       IS NOT NULL 
   AND PLAN_PPTAL_CONFIG.FUT_VICTIMAS1 IS NOT NULL
 GROUP BY   SALDO_AUX_PPTAL.COMPANIA 
          , SALDO_AUX_PPTAL.ANO 
          , PLAN_PPTAL_CONFIG.NATURALEZA 
          , PLAN_PPTAL_CONFIG.FUENTE_FLS
          , PLAN_PPTAL_CONFIG.FUT_VICTIMAS1
          ,PLAN_PPTAL_CONFIG.HECHOVICTIMIZANTE]') CONSULTA, 99 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);