MERGE INTO CONSULTAS FIN USING (SELECT '800671F01Catalogodecuentasconsolidado' INFORME ,TO_CLOB(q'[SELECT     COD_CONTABLE             "Código Contable",
           MAX(NOMBRE_CUENTA)           "Nombre De La Cuenta",
           SUM(SALDO_ANT)            "Saldo Anterior",   
           SUM(DEBITO)               "Débito", 
           SUM(CREDITO)              "Crédito",
           SUM(SALDO_CTE)           "Saldo Corriente", 
           SUM(SALDO_NOCTE)               "Saldo No Corriente"       
    FROM SIA_CATALOGO_CUENTAS                                                                                                     
          WHERE ANO      =s$ano$s
             AND MES_FINAL<=s$mesFinal$s
   GROUP BY  COD_CONTABLE, NOMBRE_CUENTa       
HAVING     SUM(ABS(SALDO_ANT)) +  SUM(DEBITO)  +  SUM(CREDITO) + SUM(ABS(SALDO_CTE))+ SUM(ABS(SALDO_NOCTE))  NOT IN (0)
ORDER BY  COD_CONTABLE]') CONSULTA, 99 APLICACION ,TO_CLOB(q'[]') CONSULTA_OPCIONAL, NULL CREATED_BY, NULL MODIFIED_BY  FROM DUAL ) INI ON (INI.INFORME = FIN.INFORME )  WHEN MATCHED THEN  UPDATE SET FIN.CONSULTA =  INI.CONSULTA, FIN.APLICACION =  INI.APLICACION, FIN.CONSULTA_OPCIONAL =  INI.CONSULTA_OPCIONAL, FIN.MODIFIED_BY = INI.MODIFIED_BY, FIN.DATE_MODIFIED = SYSDATE  WHEN NOT MATCHED THEN  INSERT (INFORME,CONSULTA, APLICACION,CONSULTA_OPCIONAL,CREATED_BY,DATE_CREATED)  VALUES (INI.INFORME,INI.CONSULTA, INI.APLICACION,INI.CONSULTA_OPCIONAL,INI.CREATED_BY,SYSDATE);