SELECT 
  SALDO_PLAN_PPTAL.COMPANIA,
  SALDO_PLAN_PPTAL.ANO,
  SALDO_AUX_PPTAL.CODIGOFUT_H                                                                                                 AS FUT,
 SUM(CASE PLAN_PRESUPUESTAL.NATURALEZA WHEN 'D' THEN SALDO_PLAN_PPTAL.APROPIACION_DEBITO-SALDO_PLAN_PPTAL.APROPIACION_CREDITO ELSE SALDO_PLAN_PPTAL.APROPIACION_CREDITO-SALDO_PLAN_PPTAL.APROPIACION_DEBITO END) AS APROPIADO,
  SUM(CASE PLAN_PRESUPUESTAL.NATURALEZA WHEN 'D' THEN SALDO_PLAN_PPTAL.MODIF_PAC_DEBITO-SALDO_PLAN_PPTAL.MODIF_PAC_CREDITO ELSE SALDO_PLAN_PPTAL.MODIF_PAC_CREDITO-SALDO_PLAN_PPTAL.MODIF_PAC_DEBITO END)         AS MODIFPAC,
  SUM(CASE PLAN_PRESUPUESTAL.NATURALEZA WHEN 'D' THEN SALDO_PLAN_PPTAL.EJE_CNT_DEBITO-SALDO_PLAN_PPTAL.EJE_CNT_CREDITO ELSE SALDO_PLAN_PPTAL.EJE_CNT_CREDITO-SALDO_PLAN_PPTAL.EJE_CNT_DEBITO END)                 AS EJECUCIONCNT,
  SUM(CASE PLAN_PRESUPUESTAL.NATURALEZA WHEN 'D' THEN SALDO_PLAN_PPTAL.TRASLADO_DEBITO-SALDO_PLAN_PPTAL.TRASLADO_CREDITO ELSE SALDO_PLAN_PPTAL.TRASLADO_CREDITO-SALDO_PLAN_PPTAL.TRASLADO_DEBITO END)             AS TRASLADO,
  SUM(CASE PLAN_PRESUPUESTAL.NATURALEZA WHEN 'D' THEN SALDO_PLAN_PPTAL.EJE_PPT_DEBITO-SALDO_PLAN_PPTAL.EJE_PPT_CREDITO ELSE SALDO_PLAN_PPTAL.EJE_PPT_CREDITO-SALDO_PLAN_PPTAL.EJE_PPT_DEBITO END)          	      AS EJECUCIONPPT,
  SUM(CASE PLAN_PRESUPUESTAL.NATURALEZA WHEN 'D' THEN SALDO_PLAN_PPTAL.APLAZAM_DEBITO-SALDO_PLAN_PPTAL.APLAZAM_CREDITO ELSE SALDO_PLAN_PPTAL.APLAZAM_CREDITO-SALDO_PLAN_PPTAL.APLAZAM_DEBITO END )             	  AS APLAZAMIENTO,
  SUM(SALDO_PLAN_PPTAL.ADICION)                                                                                               AS ADICION,
  SUM(SALDO_PLAN_PPTAL.REDUCCION)                                                                                             AS REDUCCION,
  SUM(SALDO_PLAN_PPTAL.DISPONIBILIDAD)                                                                                        AS DISPONIBILIDAD,
  SUM(SALDO_PLAN_PPTAL.REG_CONTRACT)                                                                                          AS REG_CONTRACT,
  SUM(SALDO_PLAN_PPTAL.REG_NO_CONTRACT)                                                                                       AS REG_NO_CONTRACT,
  SUM(SALDO_PLAN_PPTAL.REG_REVERSION)                                                                                         AS REG_REVERSION,
  SUM(SALDO_PLAN_PPTAL.VIGENCIAANTERIOR)                                                                                      AS VIGENCIAANTERIOR,
  SUM(SALDO_PLAN_PPTAL.VIGENCIAFUTURA)                                                                                        AS VIGENCIAFUTURA,
  SUM(SALDO_PLAN_PPTAL.PAC_APROPIADO)                                                                                         AS PAC_APROPIADO,
  SUM(SALDO_PLAN_PPTAL.PAC_PROGRAMADO)                                                                                        AS PAC_PROGRAMADO,
  SUM(SALDO_PLAN_PPTAL.MODIF_REG_CONT)                                                                                        AS MODIF_REG_CONT,
  SUM(SALDO_PLAN_PPTAL.MODIF_REG_NOCONT)                                                                                      AS MODIF_REG_NOCONT,
  SUM(SALDO_PLAN_PPTAL.REINTEGRO)                                                                                             AS REINTEGRO,
  PLAN_PRESUPUESTAL.NATURALEZA																											  ,
  SUM(SALDO_PLAN_PPTAL.REG_NO_CONTRACT)+  SUM(SALDO_PLAN_PPTAL.MODIF_REG_CONT)		 										  AS REGNOCONTRACT,
  SUM(SALDO_PLAN_PPTAL.REG_CONTRACT)   +  SUM(SALDO_PLAN_PPTAL.MODIF_REG_CONT)	          									  AS REGCONT,
  SUM(SALDO_PLAN_PPTAL.PAC_APROPIADO)  +  SUM(CASE PLAN_PRESUPUESTAL.NATURALEZA WHEN 'D' THEN SALDO_PLAN_PPTAL.MODIF_PAC_DEBITO-SALDO_PLAN_PPTAL.MODIF_PAC_CREDITO ELSE SALDO_PLAN_PPTAL.MODIF_PAC_CREDITO-SALDO_PLAN_PPTAL.MODIF_PAC_DEBITO END)AS PACTOTAL,
  SUM(SALDO_PLAN_PPTAL.REGISTRO_OBLIGACION)       																			  AS REO,
  SUM(SALDO_PLAN_PPTAL.MODIF_REGISTRO_OBLIGACION) 																			  AS MODIFREO,
  SUM(SALDO_PLAN_PPTAL.REGISTRO_OBLIGACION)+SUM(SALDO_PLAN_PPTAL.MODIF_REGISTRO_OBLIGACION) 								  AS TOTALREO,
  SUM(SALDO_PLAN_PPTAL.MODIF_INGRESOS)        																			      AS TOTALMODIFINGRESOS,
  CASE NVL(SALDO_AUX_PPTAL.SITUACIONFONDOSSCHIP,0) WHEN -1 THEN SUM(CASE PLAN_PRESUPUESTAL.NATURALEZA WHEN 'D' THEN SALDO_PLAN_PPTAL.EJE_PPT_DEBITO-SALDO_PLAN_PPTAL.EJE_PPT_CREDITO ELSE SALDO_PLAN_PPTAL.EJE_PPT_CREDITO-SALDO_PLAN_PPTAL.EJE_PPT_DEBITO END )  +SUM(SALDO_PLAN_PPTAL.MODIF_INGRESOS) ELSE 0 END  AS   SINSITUACION,       CASE NVL(SALDO_AUX_PPTAL.SITUACIONFONDOSSCHIP,0) WHEN 0 THEN SUM(CASE PLAN_PRESUPUESTAL.NATURALEZA WHEN 'D' THEN    SALDO_PLAN_PPTAL.EJE_PPT_DEBITO-SALDO_PLAN_PPTAL.EJE_PPT_CREDITO ELSE SALDO_PLAN_PPTAL.EJE_PPT_CREDITO-SALDO_PLAN_PPTAL.EJE_PPT_DEBITO END)    +SUM(SALDO_PLAN_PPTAL.MODIF_INGRESOS) ELSE 0 END AS   CONSITUACION, 
  CASE NVL(SALDO_AUX_PPTAL.SITUACIONFONDOSSCHIP,0) WHEN -1 THEN SUM(CASE PLAN_PRESUPUESTAL.NATURALEZA WHEN 'D' THEN SALDO_PLAN_PPTAL.EJE_PPT_DEBITO-SALDO_PLAN_PPTAL.EJE_PPT_CREDITO ELSE SALDO_PLAN_PPTAL.EJE_PPT_CREDITO-SALDO_PLAN_PPTAL.EJE_PPT_DEBITO END) +SUM(SALDO_PLAN_PPTAL.MODIF_INGRESOS) ELSE 0 END AS SINSITUACION,   CASE NVL(SALDO_AUX_PPTAL.SITUACIONFONDOSSCHIP,0) WHEN 0 THEN SUM(CASE PLAN_PRESUPUESTAL.NATURALEZA WHEN 'D' THEN SALDO_PLAN_PPTAL.EJE_PPT_DEBITO-SALDO_PLAN_PPTAL.EJE_PPT_CREDITO ELSE SALDO_PLAN_PPTAL.EJE_PPT_CREDITO-SALDO_PLAN_PPTAL.EJE_PPT_DEBITO END ) +SUM(SALDO_PLAN_PPTAL.MODIF_INGRESOS) ELSE 0 END AS CONSITUACION  ,
  SALDO_AUX_PPTAL.FUT_TRANSFERENCIA,
  SUM( CASE PLAN_PRESUPUESTAL.NATURALEZA WHEN 'D' THEN SALDO_PLAN_PPTAL.EJE_PPT_DEBITO-SALDO_PLAN_PPTAL.EJE_PPT_CREDITO ELSE SALDO_PLAN_PPTAL.EJE_PPT_CREDITO-SALDO_PLAN_PPTAL.EJE_PPT_DEBITO END ) +SUM(SALDO_PLAN_PPTAL.MODIF_INGRESOS)  AS TOTALINGRESOS,
  SUM(SALDO_PLAN_PPTAL.INGRESOS_CAUSADOS)       																			  AS INGRESOSCAUSADOS,
  SUM(SALDO_PLAN_PPTAL.MODIF_INGRESOS_CAUSADOS)																				  AS MODIFICACIONICA,
  SUM(SALDO_PLAN_PPTAL.INGRESOS_CAUSADOS) + SUM(SALDO_PLAN_PPTAL.MODIF_INGRESOS_CAUSADOS)         							  AS TOTALICA,
  SALDO_AUX_PPTAL.SITUACIONFONDOSSCHIP      																				  AS SITF,
  SUM(SALDO_PLAN_PPTAL.PAC_EJECUTADO)        																				  AS PACEJECUTADO_P
FROM PLAN_PRESUPUESTAL
INNER JOIN SALDO_PLAN_PPTAL
   ON  PLAN_PRESUPUESTAL.COMPANIA    = SALDO_PLAN_PPTAL.COMPANIA
   AND PLAN_PRESUPUESTAL.CODIGO      = SALDO_PLAN_PPTAL.CODIGO
   AND PLAN_PRESUPUESTAL.ANO         = SALDO_PLAN_PPTAL.ANO  
INNER JOIN SALDO_AUX_PPTAL 
    ON  PLAN_PRESUPUESTAL.COMPANIA 	 = SALDO_AUX_PPTAL.COMPANIA
	AND PLAN_PRESUPUESTAL.CODIGO	 = SALDO_AUX_PPTAL.CODIGO 
    AND PLAN_PRESUPUESTAL.ANO        = SALDO_AUX_PPTAL.ANO  
WHERE 
  SALDO_PLAN_PPTAL.MES <=s$mesFinal$s
GROUP BY 
  SALDO_PLAN_PPTAL.COMPANIA,
  SALDO_PLAN_PPTAL.ANO,
  SALDO_AUX_PPTAL.CODIGOFUT_H,
  PLAN_PRESUPUESTAL.NATURALEZA,
  SALDO_AUX_PPTAL.FUT_TRANSFERENCIA,
  SALDO_AUX_PPTAL.SITUACIONFONDOSSCHIP
HAVING 
    SALDO_PLAN_PPTAL.COMPANIA        = 's$compania$s'
AND SALDO_PLAN_PPTAL.ANO		     = s$anoTrabajo$s
AND SALDO_AUX_PPTAL.CODIGOFUT_H      NOT IN('0')
AND PLAN_PRESUPUESTAL.NATURALEZA     = 'C'
