campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
DATE_CREATED                       TIMESTAMP(6)                                      11      0           6       N     0           null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          100     0           0       Y     100         null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6)                                      11      0           6       Y     0           null                                                                                                                                                                                                    
SQL                                CLOB                                              4000    0           0       Y     0           EMPTY_CLOB()                                                                                                                                                                                            
ID                                 VARCHAR2                                          100     0           0       N     100         null                                                                                                                                                                                                    
PAR_SALIDA                         CLOB                                              4000    0           0       Y     0           EMPTY_CLOB()                                                                                                                                                                                            
BORRADO_LOGICO                     NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
USECONFIG                          VARCHAR2                                          100     0           0       Y     100         null                                                                                                                                                                                                    
COLUMNAS_LLAVE                     VARCHAR2                                          250     0           0       Y     250         null                                                                                                                                                                                                    
PAR_ENTRADA                        CLOB                                              4000    0           0       Y     0           EMPTY_CLOB()                                                                                                                                                                                            
PAR_ENTRADA_DEFAULT                CLOB                                              4000    0           0       Y     0           EMPTY_CLOB()                                                                                                                                                                                            
PLANTILLA                          NUMBER                                            22      2           0       Y     0           null                                                                                                                                                                                                    
