campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
CODIGO                             NUMBER                                            22      5           0       N     0           null                                                                                                                                                                                                    
NOMBRE                             VARCHAR2                                          250     0           0       N     250         null                                                                                                                                                                                                    
CONSULTA                           CLOB                                              4000    0           0       N     0           null                                                                                                                                                                                                    
ENLACE_PRINCIPAL                   VARCHAR2                                          200     0           0       Y     200         null                                                                                                                                                                                                    
ENLACE_SECUNDARIO                  VARCHAR2                                          200     0           0       Y     200         null                                                                                                                                                                                                    
CONDICION                          VARCHAR2                                          1000    0           0       Y     1000        null                                                                                                                                                                                                    
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
TIPO_VARIABLES_CONSULTA            VARCHAR2                                          1000    0           0       Y     1000        null                                                                                                                                                                                                    
FECHA                              TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       N     0           null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
MODO_CREACION                      CHAR                                              1       0           0       N     1           'D'                                                                                                                                                                                                     
