campo                              Tipo                                              tama�o  Precisi�n   Escala  Nulo  LargoTexto  Po Defecto                                                                                                                                                                                              
NOMBRE                             VARCHAR2                                          50      0           0       N     50          null                                                                                                                                                                                                    
DESCRIPCION                        VARCHAR2                                          255     0           0       Y     255         null                                                                                                                                                                                                    
MANEJA_ESTILOS                     NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
SOPORTE_WORD                       NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
SOPORTE_EXCEL                      NUMBER                                            22      1           0       N     0           0                                                                                                                                                                                                       
CREATED_BY                         VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
MODIFIED_BY                        VARCHAR2                                          32      0           0       Y     32          null                                                                                                                                                                                                    
DATE_MODIFIED                      TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
DATE_CREATED                       TIMESTAMP(6) WITH LOCAL TIME ZONE                 11      0           6       Y     0           null                                                                                                                                                                                                    
